### ISSUE TITLE
Theme not loaded when installation path contains spaces

### ISSUE THREAD

**Issue by maftieu** [JanDeDobbeleer/oh-my-posh#100]
### Prerequisites

- [ x ] I have read and understand the `CONTRIBUTING` guide
- [ x ] I looked for duplicate issues before submitting this one

### Description

Selected theme is not loaded by name or path (that contains spaces), but `get-themes` is working.

### Environment

- Oh my Posh version: 3.23.1
- Theme: any
- Operating System: Windows 10 Pro 2004
- Shell: Powershell 7
- Terminal: Microsoft Terminal

### Steps to Reproduce

1. Install Oh My Posh for local user, in Documents, that is synched on a Sharepoint Onedrive, so the path contains spaces
2. Ask to use any theme by name: none are working
3. Use a theme by path: not working either
4. Go to the themes installation directory, use a theme by path: ok when inside this directory, ko when somewhere
5. Make a junction of the themes directory to somewhere without spaces and use theme by path: ok

Oh My Posh is installed in `~\OneDrive - XXX\Documents\PowerShell\Modules\oh-my-posh\`
When using theme from there (either by referencing it by name or by full path), it's not working.
When using theme from a path without spaces it works.

![image](https://user-images.githubusercontent.com/6186483/97174829-e59f0480-1792-11eb-898a-6891ae67c50c.png)

**Expected behavior:**
Selected theme to be used

**Actual behavior:**
Default theme used

**Comment by JanDeDobbeleer** [comment]
Same issue as #98, I'll wrap it in spaces too. Should've thought about that.

**Comment by JanDeDobbeleer** [comment]
Btw @maftieu you might want to tweak the theme to use transparency to get rid of the black triangles in the error and path segments.

**Comment by JanDeDobbeleer** [comment]
I'm going to validate the change tomorrow morning and merge if it works. This needs a manual test.

**Comment by maftieu** [comment]
Thanks for the quick fix! I've updated to 3.23.2, it's working 👍
