### ISSUE TITLE
CTRL+R (reverse search) results are reset after shell is closed

### ISSUE THREAD

**Issue by therealpaulgg** [JanDeDobbeleer/oh-my-posh#1002]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After closing a shell (ZSH) on Linux (both WSL and SSH), the CTRL+R results do not show up after logging back into the Linux system (also affects searching with up + down arrow keys). In regular bash, zsh, and oh-my-zsh, after logging off and logging back on, command history is preserved.

The ctrl+r functionality works perfectly fine on Windows after closing/reopening Powershell on Windows.

### Version

5.6.0. Have tested both the winget Windows version (includes oh-my-posh-wsl), as well as a native Linux install on one of my machines. Both have the same problem.

### Theme

blue-owl, lightly customized. https://gist.github.com/therealpaulgg/9aabf3235278a3227b6daff1fcc52837

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

zsh, powershell

**Comment by lnu** [comment]
you mean this(sorry for the quality):
![Screencast from 26-09-21 07 16 07](https://user-images.githubusercontent.com/1829553/134794767-52ec8737-b462-415e-8d64-d76ead9fb583.gif)

![bcksearch](https://user-images.githubusercontent.com/1829553/134795309-cf0309e1-b245-43c4-8daa-5cfc8188f643.gif)

I tried on an opensuse tumbleweed and on windows with wsl. With or without omp enabled, different themes.
I Opened/Closed the terminal, reboot and the history and the backward search seem to work. Am I missing something?

**Comment by JanDeDobbeleer** [comment]
If memory serves me right, we've had someone stumble upon this [before](https://github.com/JanDeDobbeleer/oh-my-posh/issues/645).

**Comment by lnu** [comment]
You have a good memory... I completely forgot about that one

**Comment by therealpaulgg** [comment]
Yes, it turns out that in order to make ZSH history work you have to configure it yourself. It seems to be auto-configured for history when using oh-my-zsh or if you set up ZSH initially with option (1). Thanks for linking that issue, that really helps. Led me to this which solved it:

https://unix.stackexchange.com/questions/389881/history-isnt-preserved-in-zsh

Added these lines to .zshrc:

```
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
```

Apologies for not knowing enough about zsh to have to open this issue, lol. Hopefully this helps someone out in the future.

**Comment by JanDeDobbeleer** [comment]
I'll create a FAQ item about this. As we want to be careful overriding people's settings, I don't want to add this to our init script, but it's really useful to know if you encounter this.

**Comment by lnu** [comment]
> Yes, it turns out that in order to make ZSH history work you have to configure it yourself. It seems to be auto-configured for history when using oh-my-zsh or if you set up ZSH initially with option (1). Thanks for linking that issue, that really helps. Led me to this which solved it:
> 
> https://unix.stackexchange.com/questions/389881/history-isnt-preserved-in-zsh
> 
> Added these lines to .zshrc:
> 
> ```
> HISTFILE=~/.zsh_history
> HISTSIZE=10000
> SAVEHIST=10000
> setopt appendhistory
> ```
> 
> Apologies for not knowing enough about zsh to have to open this issue, lol. Hopefully this helps someone out in the future.

I found the links to solve the issue months ago and still I forgot about it, so don’t be sorry :)
