### ISSUE TITLE
Unnecessary rectangle is displayed and npm version is not displayed

### ISSUE THREAD

**Issue by haosmos** [JanDeDobbeleer/oh-my-posh#1012]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

hello! 😃

Thanks for the awesome tool! 

Two questions: 

1. I upgraded to the latest version today and for some reason, a white rectangle started displaying on the right side. How do I remove it? It wasn't there before. 

2.  I set the property to display npm version, but for some reason, it doesn't work and the npm version is not displayed. How to make it display after (to the right side) displaying node js version? 

![WindowsTerminal_SLN9H9PFXX](https://user-images.githubusercontent.com/30666874/135638628-e4009c9e-0841-4d27-9cf9-10dece76a9f2.png)

I should note that earlier in version 3 of oh-my-posh, which I used for a long time, there was no such problem with the rectangle. But in the last version (3) the npm version did not show up as well. 

My environment: 

os: windows 11, build: 22000.194
shell: PowerShell 7.2.0-preview.10
font: fira code Nerd Font (5.2)

for some reason, the published code of my theme is poorly displayed (apparently GitHub can not properly publish an object nested inside another object), so I published the theme code [here:](https://pastebin.com/D5SqhCYh)

### Version

5.6.4

### Theme

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "newline": true,
      "segments": [],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#e9eed9",
          "foreground": "#0fb4e6",
          "leading_diamond": "╭─",
          "style": "diamond",
          "type": "os"
        },
        {
          "background": "#3465a4",
          "foreground": "#EEEE8B",
          "powerline_symbol": "",
          "properties": {
            "enable_hyperlink": false,
            "home_icon": "~",
            "prefix": "  ",
            "style": "full",
            "mapped_locations": {
              "D:\\Projects": "  ",
              "C:\\Users\\haosmos": "  "
            }
          },
          "style": "powerline",
          "type": "path"
        },
        {
          "background": "#425B67",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "ahead_and_behind_color": "#f26d50",
            "branch_icon": " ",
            "stash_count_icon": " ",
            "ahead_color": "#2EC4B6",
            "behind_color": "#8A4FFF",
            "color_background": false,
            "display_stash_count": true,
            "display_status": true,
            "display_upstream_icon": true,
            "local_changes_color": "#41fd3a",
            "postfix": "\u2800",
            "staging_color": "#00fad9",
            "status_colors_enabled": true,
            "working_color": "#fdf263"
          },
          "style": "powerline",
          "type": "git"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "#425B67",
          "foreground": "#41fd3a",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "display_version": true,

            "postfix": "<#7a7a7a> </>",
            "prefix": "  ",
            "display_error": true,
            "display_mode": "files",
            "display_package_manager:": true,
            "yarn_icon": "\uF61A",
            "npm_icon": "\uE71E"
          },
          "style": "powerline",
          "type": "node"
        },
        {
          "background": "#FFDE57",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "display_mode": "files",
            "display_version": true,
            "display_virtual_env": false,
            "postfix": "  "
          },
          "style": "powerline",
          "type": "python"
        },
        {
          "background_templates": [
            "{{if contains \"default\" .Profile}}#FFA400{{end}}",
            "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
          ],
          "foreground": "#ffffff",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "display_default": false,
            "postfix": "  "
          },
          "style": "powerline",
          "type": "aws"
        },
        {
          "background": "#ffff66",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "root_icon": ""
          },
          "style": "powerline",
          "type": "root"
        },
        {
          "background": "#c4a000",
          "foreground": "#000000",
          "invert_powerline": true,
          "powerline_symbol": "",
          "always_enabled": true,
          "properties": {
            "threshold": 500,
            "style": "austin",
            "postfix": "  "
          },
          "style": "powerline",
          "type": "executiontime"
        },
        {
          "background": "#546E7A",
          "foreground": "#47fc00",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "always_enabled": true,
            "color_background": false,
            "display_exit_code": false,
            "error_color": "#cc2222",
            "success_icon": "👌",
            "error_icon": "😡"
          },
          "style": "powerline",
          "type": "exit"
        },
        {
          "background": "#e9eed9",
          "foreground": "#000000",
          "invert_powerline": true,
          "properties": {
            "time_format": "15:04"
          },
          "style": "diamond",
          "trailing_diamond": "─╮ ",
          "type": "time"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {

          "type": "text",
          "style": "plain",
          "foreground": "#e9eed9",
          "leading_diamond": "╰─",
          "properties": {
            "postfix": "",
            "prefix": "╰─ ",
            "text": "👉"
          }
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "background": "#e9eed9",
          "properties": {
            "postfix": "",
            "text": ""
          },
          "style": "diamond",
          "trailing_diamond": "─╯",
          "type": "text"
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@haosmos a few errors in the theme:

- the fact that the NPM icon (or Yarn) doesn't show is because your have  `"display_package_manager:": true,` which should be `"display_package_manager": true,`. The `:` makes it so it doesn't accept that (rightfully so).
- the rectangle is because your `rprompt` block has a background color set, just change that to `"foreground": "#e9eed9",` and it will display correctly.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/2492783/135669594-93493c67-131a-4370-ab68-3cb1d01fc3ad.png">

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "newline": true,
      "segments": [],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#e9eed9",
          "foreground": "#0fb4e6",
          "leading_diamond": "╭─",
          "style": "diamond",
          "type": "os"
        },
        {
          "background": "#3465a4",
          "foreground": "#EEEE8B",
          "powerline_symbol": "",
          "properties": {
            "enable_hyperlink": false,
            "home_icon": "~",
            "prefix": "  ",
            "style": "full",
            "mapped_locations": {
              "D:\\Projects": "  ",
              "C:\\Users\\haosmos": "  "
            }
          },
          "style": "powerline",
          "type": "path"
        },
        {
          "background": "#425B67",
          "foreground": "#000000",
          "powerline_symbol": "",
          "properties": {
            "ahead_and_behind_color": "#f26d50",
            "branch_icon": " ",
            "stash_count_icon": " ",
            "ahead_color": "#2EC4B6",
            "behind_color": "#8A4FFF",
            "color_background": false,
            "display_stash_count": true,
            "display_status": true,
            "display_upstream_icon": true,
            "local_changes_color": "#41fd3a",
            "postfix": "\u2800",
            "staging_color": "#00fad9",
            "status_colors_enabled": true,
            "working_color": "#fdf263"
          },
          "style": "powerline",
          "type": "git"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "#425B67",
          "foreground": "#41fd3a",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "display_version": true,
            "postfix": "<#7a7a7a> </>",
            "prefix": "  ",
            "display_error": true,
            "display_mode": "files",
            "display_package_manager": true,
            "yarn_icon": "\uF61A",
            "npm_icon": " \uE71E"
          },
          "style": "powerline",
          "type": "node"
        },
        {
          "background": "#FFDE57",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "display_mode": "files",
            "display_version": true,
            "display_virtual_env": false,
            "postfix": "  "
          },
          "style": "powerline",
          "type": "python"
        },
        {
          "background_templates": [
            "{{if contains \"default\" .Profile}}#FFA400{{end}}",
            "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
          ],
          "foreground": "#ffffff",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "display_default": false,
            "postfix": "  "
          },
          "style": "powerline",
          "type": "aws"
        },
        {
          "background": "#ffff66",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "root_icon": ""
          },
          "style": "powerline",
          "type": "root"
        },
        {
          "background": "#c4a000",
          "foreground": "#000000",
          "invert_powerline": true,
          "powerline_symbol": "",
          "always_enabled": true,
          "properties": {
            "threshold": 500,
            "style": "austin",
            "postfix": "  "
          },
          "style": "powerline",
          "type": "executiontime"
        },
        {
          "background": "#546E7A",
          "foreground": "#47fc00",
          "invert_powerline": true,
          "powerline_symbol": "",
          "properties": {
            "always_enabled": true,
            "color_background": false,
            "display_exit_code": false,
            "error_color": "#cc2222",
            "success_icon": "👌",
            "error_icon": "😡"
          },
          "style": "powerline",
          "type": "exit"
        },
        {
          "background": "#e9eed9",
          "foreground": "#000000",
          "invert_powerline": true,
          "properties": {
            "time_format": "15:04"
          },
          "style": "diamond",
          "trailing_diamond": "─╮ ",
          "type": "time"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {

          "type": "text",
          "style": "plain",
          "foreground": "#e9eed9",
          "leading_diamond": "╰─",
          "properties": {
            "postfix": "",
            "prefix": "╰─ ",
            "text": "👉"
          }
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "foreground": "#e9eed9",
          "properties": {
            "postfix": "",
            "text": "─╯"
          },
          "style": "plain",
          "type": "text"
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true
}

```

**Comment by haosmos** [comment]
> @haosmos a few errors in the theme:
> 
> * the fact that the NPM icon (or Yarn) doesn't show is because your have  `"display_package_manager:": true,` which should be `"display_package_manager": true,`. The `:` makes it so it doesn't accept that (rightfully so).
> * the rectangle is because your `rprompt` block has a background color set, just change that to `"foreground": "#e9eed9",` and it will display correctly.
> 
> <img alt="image" width="730" src="https://user-images.githubusercontent.com/2492783/135669594-93493c67-131a-4370-ab68-3cb1d01fc3ad.png">
> 
> ```json
> {
>   "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
>   "blocks": [
>     {
>       "alignment": "left",
>       "newline": true,
>       "segments": [],
>       "type": "prompt"
>     },
>     {
>       "alignment": "left",
>       "newline": true,
>       "segments": [
>         {
>           "background": "#e9eed9",
>           "foreground": "#0fb4e6",
>           "leading_diamond": "╭─",
>           "style": "diamond",
>           "type": "os"
>         },
>         {
>           "background": "#3465a4",
>           "foreground": "#EEEE8B",
>           "powerline_symbol": "",
>           "properties": {
>             "enable_hyperlink": false,
>             "home_icon": "~",
>             "prefix": "  ",
>             "style": "full",
>             "mapped_locations": {
>               "D:\\Projects": "  ",
>               "C:\\Users\\haosmos": "  "
>             }
>           },
>           "style": "powerline",
>           "type": "path"
>         },
>         {
>           "background": "#425B67",
>           "foreground": "#000000",
>           "powerline_symbol": "",
>           "properties": {
>             "ahead_and_behind_color": "#f26d50",
>             "branch_icon": " ",
>             "stash_count_icon": " ",
>             "ahead_color": "#2EC4B6",
>             "behind_color": "#8A4FFF",
>             "color_background": false,
>             "display_stash_count": true,
>             "display_status": true,
>             "display_upstream_icon": true,
>             "local_changes_color": "#41fd3a",
>             "postfix": "\u2800",
>             "staging_color": "#00fad9",
>             "status_colors_enabled": true,
>             "working_color": "#fdf263"
>           },
>           "style": "powerline",
>           "type": "git"
>         }
>       ],
>       "type": "prompt"
>     },
>     {
>       "alignment": "right",
>       "segments": [
>         {
>           "background": "#425B67",
>           "foreground": "#41fd3a",
>           "invert_powerline": true,
>           "powerline_symbol": "",
>           "properties": {
>             "display_version": true,
>             "postfix": "<#7a7a7a> </>",
>             "prefix": "  ",
>             "display_error": true,
>             "display_mode": "files",
>             "display_package_manager": true,
>             "yarn_icon": "\uF61A",
>             "npm_icon": " \uE71E"
>           },
>           "style": "powerline",
>           "type": "node"
>         },
>         {
>           "background": "#FFDE57",
>           "foreground": "#111111",
>           "invert_powerline": true,
>           "powerline_symbol": "",
>           "properties": {
>             "display_mode": "files",
>             "display_version": true,
>             "display_virtual_env": false,
>             "postfix": "  "
>           },
>           "style": "powerline",
>           "type": "python"
>         },
>         {
>           "background_templates": [
>             "{{if contains \"default\" .Profile}}#FFA400{{end}}",
>             "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
>           ],
>           "foreground": "#ffffff",
>           "invert_powerline": true,
>           "powerline_symbol": "",
>           "properties": {
>             "display_default": false,
>             "postfix": "  "
>           },
>           "style": "powerline",
>           "type": "aws"
>         },
>         {
>           "background": "#ffff66",
>           "foreground": "#111111",
>           "invert_powerline": true,
>           "powerline_symbol": "",
>           "properties": {
>             "root_icon": ""
>           },
>           "style": "powerline",
>           "type": "root"
>         },
>         {
>           "background": "#c4a000",
>           "foreground": "#000000",
>           "invert_powerline": true,
>           "powerline_symbol": "",
>           "always_enabled": true,
>           "properties": {
>             "threshold": 500,
>             "style": "austin",
>             "postfix": "  "
>           },
>           "style": "powerline",
>           "type": "executiontime"
>         },
>         {
>           "background": "#546E7A",
>           "foreground": "#47fc00",
>           "invert_powerline": true,
>           "powerline_symbol": "",
>           "properties": {
>             "always_enabled": true,
>             "color_background": false,
>             "display_exit_code": false,
>             "error_color": "#cc2222",
>             "success_icon": "👌",
>             "error_icon": "😡"
>           },
>           "style": "powerline",
>           "type": "exit"
>         },
>         {
>           "background": "#e9eed9",
>           "foreground": "#000000",
>           "invert_powerline": true,
>           "properties": {
>             "time_format": "15:04"
>           },
>           "style": "diamond",
>           "trailing_diamond": "─╮ ",
>           "type": "time"
>         }
>       ],
>       "type": "prompt"
>     },
>     {
>       "alignment": "left",
>       "newline": true,
>       "segments": [
>         {
> 
>           "type": "text",
>           "style": "plain",
>           "foreground": "#e9eed9",
>           "leading_diamond": "╰─",
>           "properties": {
>             "postfix": "",
>             "prefix": "╰─ ",
>             "text": "👉"
>           }
>         }
>       ],
>       "type": "prompt"
>     },
>     {
>       "segments": [
>         {
>           "foreground": "#e9eed9",
>           "properties": {
>             "postfix": "",
>             "text": "─╯"
>           },
>           "style": "plain",
>           "type": "text"
>         }
>       ],
>       "type": "rprompt"
>     }
>   ],
>   "console_title": true,
>   "console_title_style": "template",
>   "console_title_template": "{{ .Shell }} in {{ .Folder }}",
>   "final_space": true
> }
> ```

Thanks a lot! 

Just I don't quite understand, — option: "display_package_manager" show only using the package manager names and don't show the package manager version?

I thought it would show the version of the package manager used — 7.21.1, something like this))

anyway, thanks for the help!

**Comment by JanDeDobbeleer** [comment]
Correct, only the name. There's no use case for the version.
