### ISSUE TITLE
Use plugin in oh my posh

### ISSUE THREAD

**Issue by vuboi** [JanDeDobbeleer/oh-my-posh#1015]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Can I use plugin like zsh-autosuggestions,.. for oh my posh ?

**Comment by JanDeDobbeleer** [comment]
You can use any functionality you want. You can even use oh-my-zsh and use oh-my-posh as the prompt renderer. Everything works.

**Comment by vuboi** [comment]
> You can use any functionality you want. You can even use oh-my-zsh and use oh-my-posh as the prompt renderer. Everything works.

thank you :P
