### ISSUE TITLE
powerlevel10k_rainbow theme bug

### ISSUE THREAD

**Issue by ikreva** [JanDeDobbeleer/oh-my-posh#1019]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

<img width="809" alt="2021-10-03 130952" src="https://user-images.githubusercontent.com/69108874/135740910-d48cc0b8-ec11-4462-a79b-3f385bf7ceb7.png">

### Version

5.6.4

### Theme

powerlevel10k_rainbow

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@ikreva you mean the rectangle, right? Would've been really useful information ;-)

**Comment by ikreva** [comment]
> @ikreva you mean the rectangle, right? Would've been really useful information ;-)

yes , the rectangle,
