### ISSUE TITLE
Invalid username

### ISSUE THREAD

**Issue by DoPeRaSo** [JanDeDobbeleer/oh-my-posh#1024]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Username in session is determined using USERNAME from environmental settings. This is not necessarily correct and can also be changed by the user.

When using tools like [gsudo](https://github.com/gerardog/gsudo) the username may change but the environment variables stay the same.

It's better to use `[System.Security.Principal.WindowsIdentity]::GetCurrent().Name` to identify the current username

### Version

5.7.0

### Theme

Paradox

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@DoPeRaSo the solution you propose is Powershell yet the codebase is in go so that won't work. Can you validate which env var holds the actual user name? As I would expect gsudo to either update that (when using `su` that does work) or provide another way to retrieve who's active right now.

**Comment by JanDeDobbeleer** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/2492783/136187493-2731faf6-9935-48a8-948a-4f9db70e8e0e.png">

So it picks up the admin part, but does that really change the username? Do you expect to see ADMIN at that point in time? I'm still very much `jan` here, but with admin rights.

**Comment by DoPeRaSo** [comment]
Your account is member of the Administrators group, so it did not ask for different credentials. When removing this account, gsudo (well, in fact it is Windows) asks for a username, so you can easily switch.

For this new session, gsudo copies over the whole env-settings. As I could easily update $env:USERNAME while starting the session, I would rely on this value.

I'm (currently) not familar with Golang but is it maybe possible to use the package "os/user" for this purpose?

**Comment by JanDeDobbeleer** [comment]
@DoPeRaSo we used that before, but it also has side-effects. Outside of gsudo, this has been the most reliable way for every use-case. Can't we ask the gsudo folks to set the correct env var? Because they are in this case responsible to set up the right env imho.

**Comment by DoPeRaSo** [comment]
Hm, I would not go this way as all affected variables would have to be updated (USERPROFILE, APPdATA, etc.), this would only relieve the symptoms.

Anyway, as the powershell runs the profile.ps1-stuff, I will just change it during intializisation myself.

**Comment by JanDeDobbeleer** [comment]
@DoPeRaSo well, yes. Because if those variables aren't correct probably other tools also take wrong assumptions. This sounds like a structural issue from gsudo imho.

**Comment by JanDeDobbeleer** [comment]
Closing in awaiting the reponse from gsudo, we'll see what happens when they reply.
