### ISSUE TITLE
Windows Terminal: Unexpected space(s) between segments/text

### ISSUE THREAD

**Issue by LRitzdorf** [JanDeDobbeleer/oh-my-posh#1029]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When starting Oh-My-Posh, specifically in a PowerShell session running within Windows Terminal, certain pieces of blank space in the prompt do not render correctly. This issue occurs only in Windows Terminal, *not* in a "standard" PowerShell session, and affects all the themes I've cared to test so far.

More interestingly, this only occurs for the first prompt drawn. The issue is not present in any prompts drawn later (caused by pressing <kbd>Ctrl</kbd>+<kbd>L</kbd>, entering a command, etc).

I think the spaces where this occurs are all separators between segments, but I'm not certain of that. Also, an image is attached below for reference, using the default `jandedobbeleer` theme:

![OMP-render-bug](https://user-images.githubusercontent.com/42657792/136498511-38a649a1-f752-4b1a-8bb7-7aef5c87bc75.png)

(Apologies for the red markup - that's hiding my (user)name)

### Version

5.7.2 (though the issue has been present for some time)

### Theme

Discovered using a (very slightly) customized `slimfat`, but seems to affect all themes.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@LRitzdorf that's indeed a Windows Terminal bug. See this [FAQ](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) item for more information.

**Comment by LRitzdorf** [comment]
Ah, now I feel silly. Thanks for the quick response!

**Comment by JeromeDeLeon** [comment]
Using the fix indicated in the [FAQ](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) item didn't fix my issue but what I did instead added `clear` at the end of `~/.profile`.

**Comment by JanDeDobbeleer** [comment]
@JeromeDeLeon that's a different issue indeed. I have no idea why, but sometimes only the first line is broken. Which is also a Windows Terminal thing, so I can't fix that.

**Comment by JeromeDeLeon** [comment]
That's totally fine. Adding the above `clear` at the end of shell config fix it. Must have been Windows bug 😅. Thank you.

I just commented that here so someone could use the workaround. 😁

**Comment by pmakowski23** [comment]
I have this issue with just plain text using `zash` theme. On every segment I have additional preceding and following space.
![image](https://user-images.githubusercontent.com/58031604/152594651-f35d83d0-0b21-47c1-ad67-ad712017a539.png)

**Comment by LRitzdorf** [comment]
I... don't think that's the same issue? For the problem described, there aren't any extra characters -- instead, some of the background highlights are missing.

Also, you should be able to customize your theme to change the spacing.

**Comment by lewis-yeung** [comment]
Another workaround for PowerShell with a startup flag of `-NoLogo` in Windows Terminal, just simply append this line to the end of your profile:
```powershell
Write-Host -NoNewline "`n`e[1F"
```
which means spawning a new empty line and move the cursor back to the beginning of the previous line, just like "nothing" is done. This works when there is expected background-colored space characters output in the first line before the first prompt spawned.

**Comment by RanvirChoudhary** [comment]
> @LRitzdorf that's indeed a Windows Terminal bug. See this [FAQ](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) item for more information.

sorry but i absolutely do not understand where i am supposed to paste that code block. could you please explain it to me? sorry i'm new to this oh-my-posh thing!

**Comment by JanDeDobbeleer** [comment]
@RanvirChoudhary have a look at the [customization](https://ohmyposh.dev/docs/customize#export-the-current-theme) section.

**Comment by ffes** [comment]
FYI: It appear the bug has been fixed in Windows Terminal, because with v1.15.2282.0 (in the preview channel) I don't see this happen anymore. Not sure about the release channel, which is v1.14

**Comment by sergiomiranda** [comment]
> FYI: It appear the bug has been fixed in Windows Terminal, because with v1.15.2282.0 (in the preview channel) I don't see this happen anymore. Not sure about the release channel, which is v1.14

Yes, I think that it was also fixed in the current stable version, check here:

https://github.com/microsoft/terminal/issues/8341
