### ISSUE TITLE
Persisting 

### ISSUE THREAD

**Issue by veritem** [JanDeDobbeleer/oh-my-posh#1032]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've install `oh-my-posh` and setup a new font, but by the time i close the editor and open it back everything looks broken. How  can i fix that?

### Version

latest 

### Theme

jandedobbeleer

### What OS are you seeing the problem on?

Windows

**Comment by JanDeDobbeleer** [comment]
@veritem can you give some more details and maybe screenshots of the issue?

**Comment by veritem** [comment]
I've setup oh-my-posh  and is working well you can check the screenshot below
![image](https://user-images.githubusercontent.com/53856673/136650509-f16c109f-8689-49b6-b8ba-bdbf4d06917c.png)

by the time I close the time and open a new PowerShell window, all that customization goes away 
![image](https://user-images.githubusercontent.com/53856673/136650588-de0057c9-2674-4bd4-bce6-5c89d1631aca.png)

**Comment by JanDeDobbeleer** [comment]
@Veritem perfect, that means you need to add those lines to your Powershell profile so they are loaded every time Powershell starts. Have a look [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles) for more information.

**Comment by veritem** [comment]
thanks, @JanDeDobbeleer, to anyone with this issue
I did `code $Profile`.
I added `Set-PoshPrompt -Theme spaceship`(Note: spaceship is my theme), saved, and restarted.
