### ISSUE TITLE
Cygwin integration 

### ISSUE THREAD

**Issue by neradp** [JanDeDobbeleer/oh-my-posh#1036]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello, i wish to use oh-my-posh in Cygwin. I got error when i try to access Cygwin virtual directories...

> 
> Error: Current working directory is a virtual Cygwin directory which does
> not exist for a native Windows application.
> Can't start native Windows application from here.
> 
> C:\cygwin\bin\bash: C:/Users/peter/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe: Not a directory
> Error: Current working directory is a virtual Cygwin directory which does
> not exist for a native Windows application.
> Can't start native Windows application from here.

**Comment by JanDeDobbeleer** [comment]
As the error indicates, this is a cygwin limitation and not oh-my-posh. It can't run native Windows apps from that location (goes for any application).

**Comment by neradp** [comment]
I know, but it would be nice to have oh-my-posh compiled for Cygwin environment too 👯

**Comment by JanDeDobbeleer** [comment]
@neradp no, that's something I will never do. If the linux binary doesn't do the trick, please migrate to WSL2.

**Comment by kevin-stuart** [comment]
Hmm. From what I am seing, `eval "$(oh-my-posh init bash)"` works. If I call something more elaborate like `"$(oh-my-posh init bash --config ~/.config/oh-my-posh/themes/default.omp.json)"` I get an error.

Looking at the output of the inner eval, I see that oh-my-posh just outputs the paths in the regular Windows style. All one would have to do is to rewrite these paths. One could rewrite these paths with some clever sed/grep, but this is needlessly complex.

So maybe the presence of an environment variable or a switch would easily solve this. How about this solution?

**Comment by JanDeDobbeleer** [comment]
@kevin-stuart you only need to reference the correct path. The config path `~/` will not reference the user's HOME folder on Windows. I'm open for PR's on this one if you have a fix, but I'm not investing time in Git Bash anymore.

**Comment by kevin-stuart** [comment]
I did not even get ~ at all, I just got some absolute Windows path such as C:/Users/USER/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe. I guess I could just rewrite this to /c/Users... and it would work for me. I definitely would be prefer an officially sanctioned way for this and had hoped that this idea was simple enough to justify it.

**Comment by JanDeDobbeleer** [comment]
@kevin-stuart for any other shell, yes. But not for Git bash. I can't justify spending so much time on that. It would be different if I could do this full time in a sustainable way financially, but that's not the case. I have to set my limits as I get no joy from that shell.
