### ISSUE TITLE
Add Transient Prompt

### ISSUE THREAD

**Issue by DrMagPie** [JanDeDobbeleer/oh-my-posh#1037]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Powerlevel10k has transient prompt feature. in short it hides previous prompt and displays only command and its output.
Please see gif bellow
![](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif)

Would be really cool to get it in `OMP`, but looks like it's quite tricky to implement (at least in Z shell).
Here is same request for https://github.com/starship/starship/issues/888 with some additional details that might help if you consider implementing it.

**Comment by JanDeDobbeleer** [comment]
https://ohmyposh.dev/docs/beta#transient-prompt

**Comment by DrMagPie** [comment]
ohhh didn't notice that one. sorry for spam :)

**Comment by JanDeDobbeleer** [comment]
All fine, as it's in beta, feedback is appreciated!
