### ISSUE TITLE
enable segement "dotnet" if "global.json" is present

### ISSUE THREAD

**Issue by FroggieFrog** [JanDeDobbeleer/oh-my-posh#1041]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Is it possible to enhance the `dotnet` segment to be enabled if a `global.json` file is present?

See the image for clarification.
I would like to see the version of dotnet when I'm inside the `G:\posh-test\with global.json` directory.
Currently it is only displayed when I'm in the `src` directory (which contains a `*.sln` file).

I'm not familiar with Go as a programming language, but maybe it is sufficinet to add `global.json` to [this array inside the segment_dotnet.go file](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segment_dotnet.go#L28).

![posh_request](https://user-images.githubusercontent.com/6222752/137129806-b9b569b1-a9d3-4092-9def-3c988aa79b9d.png)

**Comment by lnu** [comment]
You're right about adding `global.json`to the extensions list.
something like this: https://github.com/JanDeDobbeleer/oh-my-posh/pull/1042

**Comment by FroggieFrog** [comment]
@lnu Thank you for your help.
