### ISSUE TITLE
Prompt Styles Not Working After Enabling Conda for PS

### ISSUE THREAD

**Issue by Vortexx2** [JanDeDobbeleer/oh-my-posh#1043]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

- I have had anaconda installed on my PC for a long time, but wasn't using it with PowerShell since I wasn't able to activate environments with it. 
- In the **Anaconda PowerShell Prompt** , I used `conda init powershell` to enable activation of environments. While this did the intended job for conda, this has completely disabled the stylised prompt of `oh-my-posh`.
- The bugged prompt is shown below:
 
![image](https://user-images.githubusercontent.com/68988130/137179415-7582ec36-e698-4bad-8841-f3e9d15c6e85.png)

- No amount of uninstalling and reinstalling the module has seemed to fix the problem.

### Version

5.6.4

### Theme

No theme seems to style the prompt, as shown in the picture in one of the 2 sections above.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@Vortexx2 this is not a bug but rather anaconda that overrides the prompt function. You have to check the script (activate.ps1) to see if you can disable it from doing that, but that's beyond our reach.

**Comment by Vortexx2** [comment]
Thank you @JanDeDobbeleer. 

For future reference, I've outlined a fix that might come in handy for anyone who's facing the same issue. This solution should only work if you've broken your prompt by running `conda init powershell`:

1. Traverse to your anaconda installation. Then, go to `shell/condabin`.
2.  Open the  `Conda.psm1` file.
3.  Find the section which has the heading **PROMPT MANAGEMENT**.  Comment all of the part of the script till **ALIASES**.
4. Save the file and open a new PowerShell instance.
5. The issue should be resolved now.
