### ISSUE TITLE
Show node.js version

### ISSUE THREAD

**Issue by taep96** [JanDeDobbeleer/oh-my-posh#1060]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Idea: add an option to show node.js version/add themes that show it. This could be very useful to people that are using version managers with node

**Comment by lnu** [comment]
You can display the node version with this config(and add it to any themes):
```
{
  "type": "node",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "#ffffff",
  "background": "#6CA35E",
  "properties": {
    "prefix": " \uE718 "
  }
}
```

<img width="115" alt="image" src="https://user-images.githubusercontent.com/1829553/137613975-b2ca3ff5-ebc9-43a2-b9d1-f0d5f53445b3.png">

Or maybe I'm missing your point? do you need something more?

**Comment by taep96** [comment]
Sorry, I didn't notice when I checked last time. Works great!

![21_10_17_51_llprDgapp6_WindowsTerminal](https://user-images.githubusercontent.com/64481039/137624828-606ce2c7-57a8-45b9-a310-5b471aa81d89.png)
I used hacker cat emoji, but it takes space for 2 emojis (🐱💻) even though is rendered correctly, so I put it after github.

**Comment by taep96** [comment]
Sharing :)
[pure-custom.omp.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7359792/pure-custom.omp.zip)
