### ISSUE TITLE
Icons not loading properly when starting powershell with -nologo

### ISSUE THREAD

**Issue by diamkil** [JanDeDobbeleer/oh-my-posh#1064]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

![image](https://user-images.githubusercontent.com/35732047/137614884-5b82cd1d-f4f5-4790-b8d6-097735ca0b28.png)
I'm using Nerd Font Meslo LGM NF
After clicking  enter once it shows propercly

### Version

5.8.0

### Theme

slimfat.omp.json

Installed from Winget, file is copied in Home directory

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@diamkil this is a bug in Windows Terminal. See [this](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) FAQ item for more information.

**Comment by diamkil** [comment]
Sorry, I can't seem to figure out exactly where I should put this piece of json code

**Comment by JanDeDobbeleer** [comment]
@diamkil you can adjust that by exporting your current theme to a new config file (some are packaged within the module). Then you'll be able to adjust those parts. See [here](https://ohmyposh.dev/docs/pwsh#override-the-theme-settings) for information on extending.

**Comment by rjhoff** [comment]
This is also resolved if you `Write-Host` a null character or empty string in the first line of your profile. It'll start the prompt on a new line, but it feels cleaner (to me) than sprinkling invisible characters throughout the theme.
