### ISSUE TITLE
wrong characters in username

### ISSUE THREAD

**Issue by aauerswald** [JanDeDobbeleer/oh-my-posh#1067]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The path of my profile in not interpreted correctly during install, because of "é" in my name.

### Version

5.8.0

### Theme

 - 

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
PS C:\Users\André> oh-my-posh.exe --init --shell pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression

&: The term 'C:/Users/Andr├®/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.

Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.
```

**Comment by JanDeDobbeleer** [comment]
Can you set your terminal to utf-8 before running that command?

`[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

**Comment by aauerswald** [comment]
Worked!! Thank you very much.
