### ISSUE TITLE
Transient prompt should be compact

### ISSUE THREAD

**Issue by rollingmoai** [JanDeDobbeleer/oh-my-posh#1069]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Transient prompts should be compact and not be separated from each other, as to how Powerlevel10k does it.

Powerlevel10k:
![powerlevel10k](https://user-images.githubusercontent.com/75471378/137624620-f02dca59-61a9-4637-8b72-fd704f69f2d0.png)

Oh My Posh:
![image](https://user-images.githubusercontent.com/75471378/137624705-c6b24292-0325-45f5-ba32-bf2b7fcfed8c.png)

**Comment by JanDeDobbeleer** [comment]
@itsmeboy0 that's going to be your config:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/2492783/137625664-6938ddb7-72b7-44dd-882a-787b22281d1e.png">

**Comment by rollingmoai** [comment]
Weird, I think I got a case of https://github.com/JanDeDobbeleer/oh-my-posh/issues/701, will investigate further.
