### ISSUE TITLE
Set-PoshPrompt doesn't resolve path using home ~

### ISSUE THREAD

**Issue by darthwalsh** [JanDeDobbeleer/oh-my-posh#107]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

`Set-PoshPrompt` doesn't resolve path using home `~`

### Environment

- Oh my Posh version: 3.23.4
- Theme: `~/OneDrive/Documents/PowerShell/.go-my-posh.json`
- Operating System: macOS 10.15.7
- Shell: pwsh
- Terminal: iTerm2

### Steps to Reproduce

From a good prompt, I'll run 

```
Set-PoshPrompt ~/OneDrive/Documents/PowerShell/.go-my-posh.json
Set-PoshPrompt ( Resolve-Path ~/OneDrive/Documents/PowerShell/.go-my-posh.json )
```

**Expected behavior:** prompt should always be `➜ ~/OneDrive/Documents/PowerShell`

**Actual behavior:** 

```
➜ ~/OneDrive/Documents/PowerShell Set-PoshPrompt ~/OneDrive/Documents/PowerShell/.go-my-posh.json
 walshca@MACPC1FN2NL.ads.autodesk.com   PowerShell  96  ﲵ pwsh    Set-PoshPrompt ( Resolve-Path ~/OneDrive/Documents/PowerShell/.go-my-posh.json )
➜ ~/OneDrive/Documents/PowerShell
```

You can see that `Set-PoshPrompt ~/OneDrive/Documents/PowerShell/.go-my-posh.json` causes the prompt to become the default powerline: ` carl@MACPC   PowerShell  96  ﲵ pwsh   `

---

Workaround is to call `Resolve-Path` first like:

    Set-PoshPrompt ( Resolve-Path ~/OneDrive/Documents/PowerShell/.go-my-posh.json )

**Comment by JanDeDobbeleer** [comment]
I'll add `Resolve-Path` to the module code. I thought I tested this, but on MacOS however.
