### ISSUE TITLE
Lightning icon (⚡) adds extra space in prompt with some fonts

### ISSUE THREAD

**Issue by SharakPL** [JanDeDobbeleer/oh-my-posh#1073]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

With any NerdFont i get extraspace. Happens with FiraCode NF, FuraCode NF, JetBrainsMono NF and also official releases of Cascadia Code, JetBrains Mono, etc.

![obraz](https://user-images.githubusercontent.com/5007456/137625974-ea291f0b-b83c-49ee-ac94-1e2865d0f77b.png)

On most of the system fonts, official Fira Code or FiraCode Retina it all looks correct, but of course with them I miss all or most of powerline glyphs.

![obraz](https://user-images.githubusercontent.com/5007456/137626031-5b79ec1e-e8b6-4e98-be40-86a775292374.png)

It looks like this character is designed to occupy 2 places, but NerdFonts and few others force it to 1, but prompt still reserves 2 places for it.

I'd like to use original JetBrains Mono in my terminal as all NF versions of all fonts ruin original glyphs instead of simply adding new ones ☹

### Version

5.9.0

### Theme

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "final_space": true,
  "console_title": true,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "time",
          "style": "powerline",
          "foreground": "#fff",
          "background": "#9d38aa",
          "properties": {
            "time_format": "15:04:05"
          }
        },
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#d40000",
          "background": "#fbff00",
          "properties": {
            "root_icon": "⚡"
          }
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#fff",
          "background": "#403ec4",
          "properties": {
            "style": "agnoster_full",
            "folder_separator_icon": "│"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#1ffdf2",
          "background": "#1d1e20",
          "properties": {
            "display_branch_status": true,
            "display_status_detail": true,
            "display_worktree_count": true,
            "display_status": true,
            "staging_color": "#08c502",
            "working_color": "#e2d300",
            "ahead_and_behind_color": "#fc63a3",
            "branch_icon": "",
            "tag_icon": "⌂",
            "branch_gone_icon": "≢ ",
            "branch_ahead_icon": "↥",
            "local_staged_icon": "✓",
            "branch_behind_icon": "↧",
            "local_working_icon": "✶",
            "branch_identical_icon": "≡ ",
            "status_separator_icon": " │ "
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#fff",
          "background": "#19bd0a",
          "properties": {
            "always_enabled": true,
            "color_background": true,
            "display_exit_code": true,
            "always_numeric": true,
            "error_color": "#e21111"
          }
        }
      ]
    }
  ]
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@SharakPL that's a lovely Windows Terminal bug. See [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) for more information on how to resolve it.

**Comment by SharakPL** [comment]
Thanks. This fixed it for me:
```json
"properties": {
    "root_icon": "⚡",
    "postfix": "\u2800"
}
```

**Comment by SharakPL** [comment]
Actually it works without `postfix`, but with [official](https://github.com/microsoft/cascadia-code/releases) Cascadia Code PL and Cascadia Mono PL. I see it has italic variants now so I'll stick with this one :)
