### ISSUE TITLE
5.10.0 Release has no scoop manifest (oh-my-posh.json)

### ISSUE THREAD

**Issue by asoluter** [JanDeDobbeleer/oh-my-posh#1078]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

5.10.0 Release has no scoop manifest (oh-my-posh.json)

### Version

Having 5.9.0 installed you get `WARN  error: The remote server returned an error: (404) Not Found.` when you try to update it

### Theme

Not relevant

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
I know. There's a bug at GitHub or AWS as we don't seem to be able to download releases anymore (at one point). I'll remove that release, the next one should recreate it.
