### ISSUE TITLE
`ahead_color` in `git` segment has no effect

### ISSUE THREAD

**Issue by bozho** [JanDeDobbeleer/oh-my-posh#1080]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

`ahead_color` segment setting seems to have no effect. When my branch is ahead (there are thing to push to remote), `git` segment colour is the one set in `foreground`. I've tried both colour names and hex codes.

`behind_color` works fine, haven't had a chance to test `ahead_and_behind_color` yet.

### Version

`oh-my-posh` PS module v5.8.0 in PowerShell `5.1` and `7.2.0-preview.7`, on Windows 10 Pro,

### Theme

Here's my `git` segment config:
```
        {
          "type": "git",
          "style": "plain",
          "foreground": "#1cb3e0",
          "properties": {
            "prefix": "<#ffffff> [</>",
            "postfix": "<#ffffff>]</>",
            "display_status": true,
            "display_branch_status": true,
            "display_status_detail": true,
            "display_stash_count": true,
            "display_worktree_count": false,
            "display_upstream_icon": true,
            "branch_max_length": 0,
            "status_colors_enabled": true,
            "color_background": false,
            "ahead_and_behind_color": "lightYellow",
            "behind_color": "lightRed",
            "ahead_color": "lightGreen",
            "working_color": "lightRed",
            "staging_color": "green"
          }
        }
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by lnu** [comment]
Strange. Works here:
![image](https://user-images.githubusercontent.com/1829553/137905156-0e8f374f-aac3-410b-897a-cc6731e586ab.png)

with:
```
          "background": "#fffb38",
          "foreground": "#193549",
          "powerline_symbol": "",
          "properties": {
            "ahead_and_behind_color": "#f26d50",
            "ahead_color": "#a3dc89",
            "behind_color": "#f17c37",
            "local_changes_color": "#f567fa",
            "display_stash_count": true,
            "display_upstream_icon": true,
            "stash_count_icon": " ",
            "status_colors_enabled": true,
            "display_status": true,
            "branch_max_length": 255,
            "display_worktree_count": true
          },
          "style": "powerline",
          "type": "git"
```

I also tried you config and the colors are fine(green when ahead):`
![image](https://user-images.githubusercontent.com/1829553/137906811-a0148ff1-4511-4a09-b657-4fd91fb0c35a.png)

**Comment by bozho** [comment]
Ah, it looks like `ahead_color` is not honoured when the branch is ahead _and_ there are local changes:

![image](https://user-images.githubusercontent.com/126446/137910275-639bc83c-d701-4276-acb4-7c475811289d.png)

Is that by design?

**Comment by bozho** [comment]
Ah, there's `local_ changes_color`, too, which I didn't set, so it defaults to the segment colour.

I'm just used to `posh-git` prompt, where branch colours are separate from local working tree colours :)

**Comment by lnu** [comment]
you can still use posh git => https://ohmyposh.dev/docs/poshgit

**Comment by bozho** [comment]
I know, I just wanted to be cool with icons and stuff :)

Thank you, closing.

**Comment by SharakPL** [comment]
So is there any way to set the color for ahead/behind in `git` segment? That's my config:

![obraz](https://user-images.githubusercontent.com/5007456/140723320-d0caca39-9bdb-490e-9136-9a4083a69da9.png)

Colors for staging and working are correct:

![obraz](https://user-images.githubusercontent.com/5007456/140724813-dc0037f0-cf8a-4b2b-b26c-11755be89588.png)

but ahead (I suspect it's the same for behind) are not:

![obraz](https://user-images.githubusercontent.com/5007456/140723608-d6ddd17f-eea9-4e28-b810-a834368383d2.png)

Tried setting up `local_changes_color` (changes background instead of foreground!) and `ahead_and_behind_color` but it doesn't seem to work.
It should be reopned as it still needs fixing.

**Comment by JanDeDobbeleer** [comment]
You need to set `"status_colors_enabled": true `. Also, there's a change incoming for the git segment (#1163) that will render this deprecated and you can use (by then) the `background_templates`/`foreground_templates` logic to color the segment accordingly.

And yes, setting `local_changes_color` colors the background as there's also `color_background` that defaults to `true`.

**Comment by SharakPL** [comment]
Correction: `local_changes_color` doesn't change anything on its own and adding `"status_colors_enabled": true` changes background. Naming of properties seems quite complicated TBH. I would expect `status_color_enabled` to simply toggle color customization. `false` should make whole git segment rendered with default color (`"foreground": "#1ffdf2"` in my case).

**Comment by JanDeDobbeleer** [comment]
@SharakPL these will all go away (silent support, no active support) so that'll be fixed really, really soon. Follow the PR #1163 for more information ;-)
