### ISSUE TITLE
Install error (404) on macOS

### ISSUE THREAD

**Issue by ovinc** [JanDeDobbeleer/oh-my-posh#1082]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have tried to follow the steps listed here: https://ohmyposh.dev/docs/macos to install Oh My Posh on a mac from the terminal (using both iTerm2 and Terminal). The first command 
```bash
brew tap jandedobbeleer/oh-my-posh
```
works fine.
The second command
```bash
brew install oh-my-posh
```
outputs a bunch of things, and then produces an error (see log output attached), which makes the install fail.

### Version

Homebrew is trying to install v5.10

### Theme

None

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Relevant log output

```shell
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.17.2
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:a98bd1c5f1cae4907712126d9ea04
==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v5.10.0.tar.gz
==> Downloading from https://codeload.github.com/JanDeDobbeleer/oh-my-posh/tar.g

curl: (22) The requested URL returned error: 404 
Error: oh-my-posh: Failed to download resource "oh-my-posh"
Download failed: https://github.com/JanDeDobbeleer/oh-my-posh/archive/v5.10.0.tar.gz
```

**Comment by JanDeDobbeleer** [comment]
@ovinc you are right, that release broke (due to GH) I'll see if I can build it again hang on.

**Comment by JanDeDobbeleer** [comment]
@ovinc should be fixed.

**Comment by ovinc** [comment]
Yes, it works now. Thank you for the very fast response !!
