### ISSUE TITLE
Visual bug on VS Code Terminal

### ISSUE THREAD

**Issue by Mr-Vipi** [JanDeDobbeleer/oh-my-posh#1086]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I open my integrated VS Code terminal an unplesant behaviour happens.

![Immagine 2021-10-20 031311](https://user-images.githubusercontent.com/58825526/138011753-2e6d9285-e6b8-4a40-8d63-68b6d3517d0c.png)

I don't know if this issue is related directly with VS Code but what I've seen so far it happens only when I use git bash. No issue with powershell.

### Version

5.10.1

### Theme

jandedobbeleer.omp

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

**Comment by lnu** [comment]
which version of vscode? did you try with another theme?

looks like an ansi sequence not handled correctly(or not correctly escaped).

with vscode 1.61.1 and latest omp:
![image](https://user-images.githubusercontent.com/1829553/138036632-1f6c48fb-0b26-4646-867e-26bc67ac8af8.png)

**Comment by JanDeDobbeleer** [comment]
I also can't reproduce this:
<img width="1833" alt="image" src="https://user-images.githubusercontent.com/2492783/138039975-911f8c3d-fca6-47be-8e61-dfa773972b17.png">

**Comment by JanDeDobbeleer** [comment]
@Mr-Vipi does it also happen in the "standard" git bash shell or Windows Terminal?

**Comment by Mr-Vipi** [comment]
Ok I made a secreen trying to show how this issue occurs. 

> which version of vscode? did you try with another theme?
> 
> looks like an ansi sequence not handled correctly(or not correctly escaped).
> 
> with vscode 1.61.1 and latest omp

![Immagine 2021-10-20 132142](https://user-images.githubusercontent.com/58825526/138084042-93c62c4f-4636-4e89-855d-8ac44e916924.png)





> @Mr-Vipi does it also happen in the "standard" git bash shell or Windows Terminal?

![Animation](https://user-images.githubusercontent.com/58825526/138084184-3febd74f-21e1-4070-95b4-bd2b869b65cf.gif)

At the end I opened the terminal with the shortcut combination. The VS Code environment, is the one with all my extensions disbaled, but the issue happens with the extensions enabled too, as well with my personal theme choice Night Owl.
Git bash shell no issue

**Comment by JanDeDobbeleer** [comment]
OK, so it's only an issue in VSCode, I would LOVE to understand why that happens but you're basically the only case today. Which Windows version are you on?

**Comment by Mr-Vipi** [comment]
![Immagine 2021-10-20 134527](https://user-images.githubusercontent.com/58825526/138086709-98e5fa1e-b248-4837-9ad9-841d0f768c3a.png)

**Comment by Mr-Vipi** [comment]
I would add that's not only jandedobbeleer theme presenting this issues so far I've tried blue-owl, bueish, cert, cinnamon, all this theme presented somehow the same issue but with their respective colors.

**Comment by JanDeDobbeleer** [comment]
@Mr-Vipi I know they changed conhost on 11, any way you can upgrade and see if that resolves the issue?

**Comment by Mr-Vipi** [comment]
> @Mr-Vipi I know they changed conhost on 11, any way you can upgrade and see if that resolves the issue?

unforutnately can't upgrade due to the cpu "limitations".

**Comment by JanDeDobbeleer** [comment]
@Mr-Vipi can you open an issue at vscode? This has to be an issue on their end looking at how nobody can reproduce it.
