### ISSUE TITLE
Question: How to find codes for symbols

### ISSUE THREAD

**Issue by MJECloud** [JanDeDobbeleer/oh-my-posh#109]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Hi Jan, 

just a simple (and maybe stupid) question. 😊
Where do you find all the codes for the symbols like the GitHub Icon `\uF408` ? 

Many thanks in advance!

Cheers, 
Maurice

**Comment by JanDeDobbeleer** [comment]
There are no stupid questions. https://www.nerdfonts.com/cheat-sheet

**Comment by MJECloud** [comment]
Thank you!

**Comment by JanDeDobbeleer** [comment]
I'm going to add this context to the docs as well.
