### ISSUE TITLE
Add search functionality in docs (e.g using Algolia)

### ISSUE THREAD

**Issue by GasimGasimzada** [JanDeDobbeleer/oh-my-posh#1090]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would make it easier to find things in docs if there was a dedicated search functionality. I have personally used Algolia which works well with indexing static pages and free for open source but it can be any product you prefer.

**Comment by JanDeDobbeleer** [comment]
Allow me to see what can be done 👍🏻

**Comment by GasimGasimzada** [comment]
Thank you for this! Its awesome!
