### ISSUE TITLE
New segment style mixing `powerline` with `diamond`

### ISSUE THREAD

**Issue by hugo-ricateau** [JanDeDobbeleer/oh-my-posh#1099]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'm not sure whether it's truly a feature request or if it's I misunderstood something in the documentation: as I understand it, there is no way to customise both ends of a segment while preserving the "colour chaining of segments" feature provided by the `powerline` style. In other words, I'd like to use the `diamond` style with leading/trailing symbols' colour automatically adjusted with the one of adjacent segments.

Without such a new "powerline diamond" style, I can't figure out how to properly achieve such a prompt:
![rprompt](https://user-images.githubusercontent.com/24565342/138166662-1f2e63cd-4e22-427c-8858-73722c72ee43.jpg)
where the execution time segment is optional (threshold based). Unfortunately, the only way I found to achieve this is to enforce display of the execution time segment, but this workaround is not satisfying for me with more complex parts of the prompt. I can still add an extra spacing between the segments (as achieved with the `jandedobbeleer` theme) but this implies losing precious room on prompt width and I personally find this less aesthetic.

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau can you give me a sample config? Just so I can play around with it a bit. If there's no way, I'll check what we need to extend this.

**Comment by hugo-ricateau** [comment]
Here is the WIP config I ended with for now (it uses the workaround of always displaying execution time)
```json
{
  "blocks": [
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "executiontime",
          "style": "powerline",
          "powerline_symbol": "\uE0B6",
          "invert_powerline": true,
          "foreground": "white",
          "background": "darkGray",
          "properties": {
            "always_enabled": true,
            "threshold": 100,
            "style": "round",
            "prefix": " \uF608"
          }
        },
        {
          "type": "exit",
          "style": "diamond",
          "invert_powerline": true,
          "trailing_diamond": "\uE0B4",
          "foreground": "black",
          "background": "green",
          "properties": {
            "display_exit_code": true,
            "always_enabled": true,
            "always_numeric": true,
            "success_icon": "\uF00C",
            "error_icon": "\uF00D ",
            "color_background": true,
            "error_color": "lightRed"
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [<inherit from jandedobbeleer.omp.json>]
    },
    {
      "type": "rprompt",
      "segments": [<inherit from jandedobbeleer.omp.json>]
    }
  ],
  "final_space": true
}
```
Changing `"always_enabled": true` to `false` in the `"properties"` or the `"executiontime"` segment highlights the issue (that only appears for fast enough commands i.e. when the execution time segment is not displayed).

Changing the first block to the following produces a result closer to the desired behaviour but that misses of colour ligature between the two segments:
```json
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "executiontime",
          "style": "diamond",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "",
          "foreground": "white",
          "background": "darkGray",
          "properties": {
            "always_enabled": false,
            "threshold": 100,
            "style": "round",
            "prefix": " \uF608"
          }
        },
        {
          "type": "exit",
          "style": "diamond",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "\uE0B4",
          "foreground": "black",
          "background": "green",
          "properties": {
            "display_exit_code": true,
            "always_enabled": true,
            "always_numeric": true,
            "success_icon": "\uF00C",
            "error_icon": "\uF00D ",
            "color_background": true,
            "error_color": "lightRed"
          }
        }
      ]
    },
```

**Comment by hugo-ricateau** [comment]
In case the engine capabilities should be extended, instead of defining a new "powerline diamond" style, it might be better defining a special code to place in `"leading_diamond": ` / `"trailing_diamond": ` indicating to the engine that it should apply the current background colour to the trailing / leading symbol of the previous / next segment.

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau we have that for plain text which is `inherit`. Now, I have a way incoming asap using plain segments as I found an issue. (need to add tests).

**Comment by JanDeDobbeleer** [comment]
```json
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "executiontime",
          "style": "plain",
          "foreground": "white",
          "background": "#6F7783",
          "properties": {
            "always_enabled": false,
            "threshold": 100,
            "style": "round",
            "prefix": "<#6F7783,transparent>\uE0B6</> "
          }
        },
        {
          "type": "exit",
          "style": "plain",
          "foreground": "black",
          "background": "green",
          "properties": {
            "prefix": "<green,inherit>\uE0B6</> ",
            "postfix": " <green,transparent>\uE0B4</>",
            "display_exit_code": true,
            "always_enabled": true,
            "always_numeric": true,
            "success_icon": "\uF00C",
            "error_icon": "\uF00D ",
            "color_background": true,
            "error_color": "lightRed"
          }
        }
      ]
    },
```

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau this will never properly work with base16 colors, so you'll need to use hex colors instead.

**Comment by hugo-ricateau** [comment]
@JanDeDobbeleer, the provided config does not properly render as the background colour of the `"exit"` segment is not always green. It seams the engine should be extended to add the ability to have some kind of `"invert_powerline": true` in colours overrides or the ability to do something like
```json
            "prefix": "<background,inherit>\uE0B6</> ",
            "postfix": " <background,transparent>\uE0B4</>",
```
where `background` / `foreground` should be special keywords representing the background / foreground colour of the current segment.

> @hugo-ricateau this will never properly work with base16 colors, so you'll need to use hex colors instead.

In my setup it seams to work: if I only change `#6F7783` back to `darkGray` in the configuration you supply, colour inheritance works as expected.

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau ah yes, this indeed changes color. Will check.

**Comment by hugo-ricateau** [comment]
@JanDeDobbeleer the `background` / `foreground` special keywords work fine; I think they should be documented [here](https://ohmyposh.dev/docs/configure#standard-colors).

However, this approach is still incomplete: for instance, exchanging positions of `"executiontime"` and `"exit"` segments in my previous sample config cannot be properly rendered using this technique; I think it misses one more special keyword referencing the colour of the next segment (as `inherit` does for the previous one).

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau I don't see how you would be switching segments back and forth a lot other than the initial configuration? It's by design that you'll probable need to do some tweaking when swapping things around. Inheritance (own and parent) works perfect as all necessary elements are in place, that's not true for following elements (and we're keeping it that way).

Yes, the docs need to be extended, but I wanted to make sure any issues are ironed out before doing so.

**Comment by hugo-ricateau** [comment]
Here is the config I have in mind (this is a MNWE, not my true use-case):
```json
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "exit",
          "style": "plain",
          "foreground": "transparent",
          "background": "green",
          "properties": {
            "prefix": "<background,transparent>\uE0B6</> ",
            "postfix": " <background,anticipate>\uE0B4</>",
            "display_exit_code": true,
            "always_enabled": true,
            "always_numeric": false,
            "success_icon": "\uF00C",
            "error_icon": "\uF00D ",
            "color_background": true,
            "error_color": "lightRed"
          },
          {
            "type": "executiontime",
            "style": "plain",
            "foreground": "white",
            "background": "darkGray",
            "properties": {
              "postfix": "<background,transparent>\uE0B4</>"
              "always_enabled": false,
              "threshold": 500,
              "style": "round"
            }
          }
        }
      ]
    },
```
Note the use of a suggested `anticipate` keyword (the equivalent of `inherit` but related to the next segment instead of the previous one). Without such keyword I cannot figure out a way to have a proper colour ligature between the two segments when `"executiontime"` is displayed.

**Comment by hugo-ricateau** [comment]
@JanDeDobbeleer?

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau I read it yes, couldn't find an immediate answer without an additional feature. Something I don't want is a look ahead. But a lookback could work with a specification on fg/bg. I'm letting this marinate in my mind as I also don't want to create (and maintain) Frankenstein.

**Comment by hugo-ricateau** [comment]
So I think this issue should be re-opened in the meantime.

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau imho, no, as your issue got resolved. The hypothetical segment design brings architectural questions to the table. Nobody else is going in this direction. Allow me to give this some thoughts, not sure where I'm going yet. The notification stays visible, I'm not forgetting this.

**Comment by hugo-ricateau** [comment]
As you wish but as far as I am concerned I do not consider my issue as resolved (even though I agree that the initial report was a bit too specific). I would be happy to help discussing these architectural questions if you are open to the idea.

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau I'm mainly struggling with the naming. If we move `inherit` to both `inheritFg` and `inheritBg`, this is completely possible. So I'm going to explore that path.

**Comment by hugo-ricateau** [comment]
> If we move `inherit` to both `inheritFg` and `inheritBg`, this is completely possible.

How would you achieve that? It seems to me that splitting `inherit` into `inheritFg` and `inheritBg` does not solve the issue mentioned [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1099#issuecomment-955779304); and that this is unfortunately impossible to achieve without look ahead (the key point here being the optionality of the next segment). 

> Something I don't want is a look ahead.

Could you elaborate a bit on this?

**Comment by JanDeDobbeleer** [comment]
> How would you achieve that?

I'll share my sample as soon as I'm home (which needs this change to then work).

> Could you elaborate a bit on this?

Sure, it makes it so that we do not have to already populate that context before the facts. So we can be more efficient (less overhead). It's perfectly solvable though.

**Comment by JanDeDobbeleer** [comment]
With the change coming with #1180 you can make this happen using the following:

```json
{
  "type": "prompt",
  "alignment": "right",
  "segments": [
    {
      "type": "exit",
      "style": "plain",
      "foreground": "transparent",
      "background": "green",
      "properties": {
        "prefix": "<background,transparent>\uE0B6</> ",
        "postfix": " ",
        "display_exit_code": true,
        "always_enabled": true,
        "always_numeric": false,
        "success_icon": "\uF00C",
        "error_icon": "\uF00D ",
        "color_background": true,
        "error_color": "lightRed"
      }
    },
    {
      "type": "executiontime",
      "style": "plain",
      "foreground": "white",
      "background": "darkGray",
      "properties": {
        "prefix": "<parentBackground,background>\uE0B4</> ",
        "postfix": "",
        "always_enabled": false,
        "threshold": 500,
        "style": "round"
      }
    },
    {
      "type": "text",
      "style": "plain",
      "properties": {
        "text": "<parentBackground,transparent>\uE0B4</>",
        "prefix": "",
        "postfix": ""
      }
    }
  ]
}
```

This now deprecates the `inherit` keyword in favour of something much more capable (which is why I didn't document these things just yet).

**Comment by hugo-ricateau** [comment]
On the user view point, this configuration looks a bit more hacky than a lookahead; but if it significantly helps performances (in particular to avoid a costly loop detection), it makes sense. However, it would probably not be useless discussing this approach in the documentation.

If I could suggest one last change: in order to avoid a breaking change, what about adding `inherit.foregroud` & `inherit.background` (for explicit foreground/background reference) while keeping the existing `inherit` keyword as it is? The same pattern could be used for `current`, `current.foreground` & `current.background`.

**Comment by JanDeDobbeleer** [comment]
@hugo-ricateau documentation will follow as soon as we consider the right approach :-) The fact that the keyword is now split makes for a lot more readable code so I'd like to keep that (the change is through anyways meaning it's already broken for the 2 people who used it:-))

I will be rewriting the docs on this part anyways, so keep en eye out for that somewhere in the course of next week.
