### ISSUE TITLE
Get-PoshThemes has issue while get-theme works

### ISSUE THREAD

**Issue by imba-tjd** [JanDeDobbeleer/oh-my-posh#11]
![图片](https://user-images.githubusercontent.com/24759802/93666548-b4575880-fab1-11ea-8d69-1a8383032e27.png)

**Comment by JanDeDobbeleer** [comment]
That's weird as this works on multiple of my machines, I'll try to think about a root cause. I'm currently tackling #10

**Comment by imba-tjd** [comment]
The path of the module is `C:\Program Files\PowerShell\Modules\go-my-posh\0.3.0`. I installed it via `Install-Module go-my-posh -Scope AllUsers -Force` in privileged pwsh. Because if not, the module would be installed in my `documents` which is synced with my onedrive. oh-my-posh is installed in the same way and works.

**Comment by JanDeDobbeleer** [comment]
It's probably PSScriptRoot which is indicating a different path in that case causing the executable not to be found. Which is strange though as oh-my-posh does the same. I'll try to reproduce it!

**Comment by JanDeDobbeleer** [comment]
Upon closer inspection it's just the space in `Program Files` causing the wrong invocation 🤦🏻‍♂️ I'll see if I can create a fix for that.

**Comment by JanDeDobbeleer** [comment]
@imba-tjd should be fixed!
