### ISSUE TITLE
Dynamic background colors

### ISSUE THREAD

**Issue by MJECloud** [JanDeDobbeleer/oh-my-posh#110]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

using v2 of oh-my-posh i used different backgroundcolors to indicate the status of the local git repo
![image](https://user-images.githubusercontent.com/22131101/97556914-5d12a500-19da-11eb-9337-f618374ea25b.png)

Is this still possible via envvar or is it static only?

**Comment by JanDeDobbeleer** [comment]
That functionality is available when enabling colors on the git segment. See [here](https://ohmyposh.dev/docs/git) for more info.

**Comment by MJECloud** [comment]
Oh i'm so blind sorry.. Thank you so much! 
Keep up your great work
