### ISSUE TITLE
Change default display mode for python segment from `files` to `environment`

### ISSUE THREAD

**Issue by XuehaiPan** [JanDeDobbeleer/oh-my-posh#1104]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The Python virtual environments (`conda` / `venv` / `virtualenv`) are usually activated by the users intentionally. The virtual environment (e.g. `conda`) will change many shell environment variables (e.g. `$Env:PATH`). It is very important for users to know whether the virtual environment is currently activated and if so which one is activated.

The current default behavior is the python segment is shown only if the current directory contains `*.py` / `*.ipynb` files and does not show in HomeDir. However, regardless of these conditions, the `$Env:PATH` variable has been modified upon activation.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/631aace7a81fa2d144b5d1860fa4a58d0f8b1201/docs/docs/segment-python.md#L27-L41

I'm using `oh-my-posh`'s built-in themes and don't have a customized json-format theme. It is really annoying that I don't know my conda environment has been activated or not while writing Python projects. I think this could be a common use-case for all Python developers who are using `oh-my-posh`.

I propose to change the default `display_mode` for the python segment from `files` to `environment` and make `home_enabled` to be `true` by default (including built-in themes). Such changes will not affect normal users who do not write in Python (as mentioned above, the environment is usually activated intentionally).

![oh-my-posh](https://user-images.githubusercontent.com/16078332/138418830-ede70a1d-9ab7-4184-9d1d-e3fffff3a481.png)

**Comment by JanDeDobbeleer** [comment]
@XuehaiPan it's all based on preferences, we've been seeing multiple views on this and I'm not inclined to change the default behaviour. In this case I highly suggest to switch to your own theme config, which allows you to override any setting to whatever makes more sense for you. I understand this might be more normal for power users, but to keep oh-my-posh accessible for most people out there, we opted for these defaults.

**Comment by XuehaiPan** [comment]
> it's all based on preferences

Thanks for the reply. I understand to use the same default behavior for all languages (Python, Java, etc.). If you have decided, it's fine for me.

------

> we've been seeing multiple views on this and I'm not inclined to change the default behaviour. In this case I highly suggest to switch to your own theme config, which allows you to override any setting to whatever makes more sense for you.

I have seen multiple issues and blogs for the conda prefix and how to configure oh-my-posh. Indeed oh-my-posh can handle this issue with some tricks, but I wander what if we support this out-of-boxly. Many other themes on other shell environments (oh-my-zsh, powerlevel10k, etc.) is out-of-box usable without any extra configuration. This is conducive to the promotion of the project and to attract more potential users. I installed oh-my-posh for my colleague few days ago. What was disappointed that he tried only a few minutes and then uninstalled it due to the conda prefix issues.

------

> I understand this might be more normal for power users, but to keep oh-my-posh accessible for most people out there, we opted for these defaults.

As I have mentioned:

> I propose to change the default `display_mode` for the python segment from `files` to `environment` and make `home_enabled` to be `true` by default (including built-in themes). Such changes will not affect normal users who do not write in Python (as mentioned above, the environment is usually activated intentionally).

Such changes will not affect normal users.

**Comment by JanDeDobbeleer** [comment]
@XuehaiPan you seem to be quite passionate about the topic so maybe we should simply give it a go. If we do see a lot of people with issues, we'll revert at that time. Simply changes anyways.
