### ISSUE TITLE
Allow not showing git branch name

### ISSUE THREAD

**Issue by dospunk** [JanDeDobbeleer/oh-my-posh#1105]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'd like to be able to not show the git branch name at all. I'm trying to make a tooltip for git that shows just the changes and ahead/behind status, but there's no way to completely hide the branch name. The closest I can get is setting the max length of the name to 1, but that just leaves a random letter at the beginning of the tooltip.

**Comment by JanDeDobbeleer** [comment]
@dospunk I will be rewriting the git segment to also have template functionality which will then also bring this (same for #967). It's next on my list but it's going to take a while ;-)

**Comment by JanDeDobbeleer** [comment]
@dospunk this change is coming with #1163
