### ISSUE TITLE
'Azure functions' segment gets wrapped to next line

### ISSUE THREAD

**Issue by JatinSanghvi** [JanDeDobbeleer/oh-my-posh#1108]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have set `display_version` property value to `true` in `azfunc` segment. That makes the prompt wrap to next line for some reason.

**Segment**
```
{
  "type": "azfunc",
  "style": "plain",
  "foreground": "#333",
  "background": "#ccc",
  "properties": {
    "display_version": true
  }
}
```

**PowerShell**

![image](https://user-images.githubusercontent.com/20547963/138553989-6288c95c-b90f-4634-a996-d2edcbcbe842.png)

### Version

5.12.1

### Theme

Custom Theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
Interesting. Maybe there's a line break in the output.

**Comment by JanDeDobbeleer** [comment]
@JatinSanghvi I can't reproduce this, can I get the full theme config?

<img width="624" alt="image" src="https://user-images.githubusercontent.com/2492783/138592105-0a9ca1d0-d519-4324-aa43-0cb54a0b9641.png">

**Comment by JatinSanghvi** [comment]
@JanDeDobbeleer - Here's the complete config:

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "azfunc",
          "style": "plain",
          "foreground": "black",
          "background": "white",
          "properties": {
            "display_version": true
          }
        }
      ]
    }
  ],
  "final_space": true
}
```

I also installed Azure Functions Core Tools on Ubuntu 18.04 WSL, and set the same config for bash shell. Did not find any problem there.

![image](https://user-images.githubusercontent.com/20547963/138622449-c2c29d1d-01a6-42fe-801e-e01063b19162.png)

**Comment by JatinSanghvi** [comment]
Here's a short [Go program](https://play.golang.org/p/HjlQM2R8DEc) I came up with that should give the clue.

```go
package main

import (
	"fmt"
	"regexp"
)

func main() {
	ver := parse(`(?P<version>.+)`, "3.0.3785\x0d\x0a")
	fmt.Println("Windows PowerShell: Azure Functions version segment", []byte(ver.full))

	ver = parse(`(?:(?P<version>((?P<major>[0-9]+).(?P<minor>[0-9]+).(?:\d{2})(?P<patch>[0-9]{1}))))`, "5.0.402\x0d\x0a")
	fmt.Println("Windows PowerShell: .NET version segment           ", []byte(ver.full))

	ver = parse(`(?P<version>.+)`, "3.0.3785\x0a")
	fmt.Println("Ubuntu Bash:        Azure Functions version segment", []byte(ver.full))
}

type version struct {
	full, major, minor, patch string
}

func parse(regex, versionInfo string) version {
	values := findNamedRegexMatch(regex, versionInfo)
	return version{values["version"], values["major"], values["minor"], values["patch"]}
}

func findNamedRegexMatch(pattern, text string) map[string]string {
	re := regexp.MustCompile(pattern)
	match := re.FindStringSubmatch(text)

	result := make(map[string]string)
	for i, name := range re.SubexpNames() {
		if i == 0 {
			continue
		}
		result[name] = match[i]
	}
	return result
}
```

**Output**
```text
Windows PowerShell: Azure Functions version segment [51 46 48 46 51 55 56 53 13]
Windows PowerShell: .NET version segment            [53 46 48 46 52 48 50]
Ubuntu Bash:        Azure Functions version segment [51 46 48 46 51 55 56 53]
```

Note that only the version of Azure Functions on Windows has carriage return (ASCII code 13 in decimal) added to the end. Updating the value of `language.commands.regex` property of `azfunc` struct will be one of the ways to fix it.
