### ISSUE TITLE
In the prompt displays an error "-error 0"

### ISSUE THREAD

**Issue by maxtushewski** [JanDeDobbeleer/oh-my-posh#111]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: 3.23.5
- Theme: powerlevel10k_lean, avit, etc
- Operating System: Windows 10
- Shell: PowerShell 7.0.3
- Terminal: Windows Terminal

### Steps to Reproduce

1. Open terminal window
2. Go to disk root `cd \`
3. See error

![prompt_error](https://user-images.githubusercontent.com/464035/97604572-b270a580-1a1e-11eb-873c-b25c4e65b8b8.jpg)

**Expected behavior:** In the prompt displays an error "-error 0"

**Actual behavior:** there are no errors in the prompt

**Comment by JanDeDobbeleer** [comment]
Oh gawd. Nice. It escapes the " and ruins everything. Lovely bug. Will fix.

**Comment by JanDeDobbeleer** [comment]
On MacOS it does not do this. Weird.
