### ISSUE TITLE
jandedobbeleer Theme in Windows Terminal display a gap at tail.

### ISSUE THREAD

**Issue by HYBB-rash** [JanDeDobbeleer/oh-my-posh#1111]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

![image](https://user-images.githubusercontent.com/55585958/138619069-9a35686b-a45b-480b-bb27-be0c569b21a5.png)
When I use windows terminal, this theme will display a gap at tail.
And I find that this gap will hide when display xxxs not xxxms.
![image](https://user-images.githubusercontent.com/55585958/138619144-af3958a0-01c7-4d91-87b4-06c03a6687c8.png)
This issue happen in Windows Terminal, but It work well in VSCode Terminal.
![image](https://user-images.githubusercontent.com/55585958/138619243-c4768de1-f076-4a24-9d0a-3cfe72886094.png)
I don't know how to resolve it ...

### Version

Version: 5.12.1

### Theme

jandedobbeleer Theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@HYBB-rash this is a bug in Windows Terminal. See [this](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) FAQ item for more information.

**Comment by HYBB-rash** [comment]
Thank for you help!
