### ISSUE TITLE
Regression - Navigate to PowerShell Drive causes theme to not render anymore

### ISSUE THREAD

**Issue by bgelens** [JanDeDobbeleer/oh-my-posh#112]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Regression when using a PSDrive. Theme is not rendered anymore.

Before 3.20.4:

![image](https://user-images.githubusercontent.com/10071039/97616222-91a75080-1a1c-11eb-9913-0a4f250f1481.png)

After 3.23.5:

![image](https://user-images.githubusercontent.com/10071039/97616356-bac7e100-1a1c-11eb-8402-2a3163148fc5.png)

### Environment

- Oh my Posh version: see above
- Theme: [custom](https://gist.github.com/bgelens/440c21ced26a42a7cbd7a147a006b13c)
- Operating System: MacOs
- Shell: PowerShell 7.1 rc2
- Terminal: iTerm2

### Steps to Reproduce

Navigate to the PowerShell temp drive

```powershell
cd temp:
```

**Expected behavior:** [What you expected to happen]

Normal behavior as before

**Actual behavior:** [What actually happened]

Theme doesn't render anymore

**Comment by JanDeDobbeleer** [comment]
I know why this happens but I need to find out how to fix this. Basically the new invocation fails because that path only exists in PowerShell and `$startInfo.WorkingDirectory` is invalid.

**Comment by JanDeDobbeleer** [comment]
The problem is that the fix will probably result in git and other info not working anymore. I'll give this some thought first.

**Comment by bgelens** [comment]
Maybe?

```
if ($PWD.Provider.Name -eq "FileSystem") {
  $startInfo.WorkingDirectory = "$($PWD.ProviderPath)"
}
```

**Comment by JanDeDobbeleer** [comment]
So, I can fix this but given that the actual location (according to dotnet) is still the same as before, a lot is showing as incorrect. 
<img width="759" alt="afbeelding" src="https://user-images.githubusercontent.com/2492783/97630150-77c33900-1a2f-11eb-95f0-a4456b1d0914.png">

**Comment by JanDeDobbeleer** [comment]
That fixes it. Let's see if I can ship this tomorrow morning as today (as you can see) I'm fried.

**Comment by bgelens** [comment]
No worries! I've unblocked myself :) Have a good rest! almost weekend 🍺

**Comment by JanDeDobbeleer** [comment]
I think this way the could even be removed. I'll debug on Windows as well to be sure. Thanks a bunch for pairing 🙏🏻
