### ISSUE TITLE
php segment like a node segment

### ISSUE THREAD

**Issue by HarasimowiczKamil** [JanDeDobbeleer/oh-my-posh#1121]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

There are segments for many languages and php is clearly missing. It's probably enough to rebuild the segment from node but I haven't used Go yet. Maybe such a segment could be added?

**Comment by lnu** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/pull/1122

Can you have a look and see what else can be added(in extensions for ie.)

**Comment by HarasimowiczKamil** [comment]
Wow! I did not expect such a quick implementation. The only thing that could be added is the ability to conditionally display a segment when there is a `composer.json`/`composer.lock` (https://getcomposer.org/ substitute npm/yarn) file in the current directory. But I am impressed

**Comment by lnu** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/pull/1125

**Comment by JanDeDobbeleer** [comment]
Merged, props to @lnu 👊🏻

**Comment by JanDeDobbeleer** [comment]
@HarasimowiczKamil if it works according to expectations, can you close the issue?
