### ISSUE TITLE
Extremely Slow Profile Loading and Control

### ISSUE THREAD

**Issue by ybadragon** [JanDeDobbeleer/oh-my-posh#1126]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When loading my powershell prompt with any theme for oh-my-posh  it takes an extremely long time to load at ~18 seconds. I only have a completely empty profile except for the theme loading, so it's not profile bloat. 

The shell is also extremely slow to give control back to me after running any command. I believe the reason behind this is due to my user profile being on a network drive for my company. The reason I think this is because when I run Write-PoshDebug I get the following output. ```2021/10/27 15:59:33 error opening file: open H:\/oh-my-posh.log: The system cannot find the path specified.```. H:\ I think is a remapped drive to my user profile on the company's network which I would not have access to. 

What I'm wondering is if there is a way that I can change the location which logs are written to. I was thinking it was just using $HOME for writing to logs so I tried overriding my $HOME manually to see if it would fix the issue but it still tries writing to H:\. Attached is a screenshot of the output.

![OMP](https://user-images.githubusercontent.com/3091040/139139987-44e676f6-329f-4607-b0a6-4893109c67be.png)

### Version

V3

### Theme

cert

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
2021/10/27 15:59:33 error opening file: open H:\/oh-my-posh.log: The system cannot find the path specified.
```

**Comment by JanDeDobbeleer** [comment]
@ybadragon the logs aren't written when you run the prompt, only when actively specifying debug. Once loaded everything works as expected?

**Comment by ybadragon** [comment]
Everything works once it is loaded, but even running a command like ```ls``` takes ~12 seconds to return control back to me. Just found out the commands return in sub-second if I remove the Set-PoshPrompt in my profile. This happens with the jandedobbeleer profile as well though for me. Here is the command I'm using in profile.

```Set-PoshPrompt -Theme C:\OMP\Themes\cert.omp.json```

**Comment by lnu** [comment]
but it means that you're executing omp from the network drive. If you copy the exe and the theme locally and set this in your powershell profile:
```Invoke-Expression (@(&"LOCALFOLDER\oh-my-posh.exe" --print-init --shell pwsh --config LOCALFOLDER\jandedobbeleer.omp.json) -join "`n")```

is it faster?

**Comment by JanDeDobbeleer** [comment]
@ybadragon if oh-my-posh is indeed on a network drive and the disk/network speed is not optimal, that will for sure slow things down significantly. As @lnu suggests, add the oh-my-posh executable locally and make sure it can execute directly on your machine. In this case installing using Winget/scoop might even be advised > powershell module (and that will most probably also install on the network drive).

**Comment by ybadragon** [comment]
Your suggestion gave me an idea. I decided to completely remove oh-my-posh and then re-install it with AllUsers scope instead of CurrentUser scope. Once I did that everything is working great now! Thanks for making this awesome tool, and for helping me get on the right track.
