### ISSUE TITLE
pwsh -nologo

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#1129]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened! nologo

### Version

v5.16.2

### Theme

![image](https://user-images.githubusercontent.com/69176988/139234489-ef2c0bdc-c203-4022-adaa-15f427c10115.png)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@tlyboy this is a bug in Windows Terminal. See [this](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) FAQ item for more information.
