### ISSUE TITLE
Slow startup on Enterprise Machine

### ISSUE THREAD

**Issue by syradar** [JanDeDobbeleer/oh-my-posh#1133]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Loading personal and system profiles took 13310ms.
I can see that it is loading module from Network drive. Any idea how I change that?

### Version

5.16.2
It would be great if the label for this box said how I can find the version. I could not find available commands in the docs and `Write-PoshVersion` or `Get-PoshVersion` did not exist.

### Theme

Paradox

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by lnu** [comment]
looks like this one https://github.com/JanDeDobbeleer/oh-my-posh/issues/1126

**Comment by JanDeDobbeleer** [comment]
It's indeed the same problem statement @syradar can you check if the [solution](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1126#issuecomment-953823676) also works for you?

**Comment by syradar** [comment]
It improved to 6 seconds

**Comment by darkvertex** [comment]
Did you check if your default `PATH` has any network paths in there?

Network shares in the `PATH` can slow down any shell because for every command you run, it's gonna ping each path in there until it finds a given command. If there's a network share in those paths, the latency hit is brutal.

**Comment by JanDeDobbeleer** [comment]
@darkvertex that's interesting, I had no idea people do such things 😨

**Comment by JanDeDobbeleer** [comment]
@syradar we've had a previous [issue](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1168#issuecomment-961250861) where it seemed the virus scanner was responsible for a slow startup of oh-my-posh. Might be interesting to check this too.
