### ISSUE TITLE
Transient prompt add date and timestamp as a template property

### ISSUE THREAD

**Issue by pcostarg** [JanDeDobbeleer/oh-my-posh#1138]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be nice to know when we ran some command, So it would make sense for the following template properties to be available:

- {{ .Date}}
- {{ .Time}}

**Comment by JanDeDobbeleer** [comment]
@pcostarg in theory that should already be possible by levering sprig's [built-in date/time functions](http://masterminds.github.io/sprig/date.html).

In this case that would be leveraging the following (untested):

- `{{ now | date "2006-01-02" }}`
- `{{ now | date "15:04:05" }}`

**Comment by pcostarg** [comment]
I just had to escape the double quote but it works:

`{{ now | date \"02-01 15:04:05\" }}`

output: 29-10 19:24:55

Thanks
