### ISSUE TITLE
Windows terminal - Spaces in prompt at first displaying

### ISSUE THREAD

**Issue by tweetysat** [JanDeDobbeleer/oh-my-posh#1139]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I tired with windows 10 and 11.
I tried with windows terminal 1.10 1.11 and 1.12.
I tried with powersehll and ubuntu 20.04.
When the terminal is opened, there are unwanted spaces in the prompt.
A simple enter, and the nex prompt is ok.
I also noticed that if some text is dsiplaying before the first prompt (like motd in unbuntu), it's ok.
Same result with all themes.

![2021-10-28 (1)](https://user-images.githubusercontent.com/16302367/139525280-3a55f927-1459-458e-99c7-818d26abfc1a.png)

### Version

5.13

### Theme

powerlevel10k_rainbow

**Comment by JanDeDobbeleer** [comment]
@tweetysat that’s a known Windows Terminal bug. You can find more information and a fix [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext).
