### ISSUE TITLE
Support for æ

### ISSUE THREAD

**Issue by lcizzle** [JanDeDobbeleer/oh-my-posh#1141]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello,

Wasn't sure if I should file this as a bug or feature request. Could we get support for letters like æ please? All PowerShell modules I use and programs support it except OhMyPosh.

Thanks

**Comment by JanDeDobbeleer** [comment]
@lcizzle that should be supported with UTF-8 enabled (which we force by default). What does `$OutputEncoding` say?

**Comment by lcizzle** [comment]
> @lcizzle that should be supported with UTF-8 enabled (which we force by default). What does `$OutputEncoding` say?

`Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001`

My Profile has the following line.

`oh-my-posh --init --shell pwsh --config C:\Users\Daed\Documents\Programs\System\Shells\PowerShell\Configurations\OhMyPosh\PromptV1-01.json | Invoke-Expression`

I receive the following error when the profile loads.

`&: The term 'C:/Users/D├ªd/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.`

Any idea what the issue could be? Otherwise all my other powershell scripts and my username show up correctly in the console. Example `PS C:\Users\Dæd>`

**Comment by JanDeDobbeleer** [comment]
What happens when you set `[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding` before `oh-my-posh --init --shell pwsh --config C:\Users\Daed\Documents\Programs\System\Shells\PowerShell\Configurations\OhMyPosh\PromptV1-01.json | Invoke-Expression`?

**Comment by lcizzle** [comment]
Boom! Worked perfectly! Thank you! I'll close this issue.
