### ISSUE TITLE
YTMDA segment not showing up/working.

### ISSUE THREAD

**Issue by Pyrrhusn** [JanDeDobbeleer/oh-my-posh#1143]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've installed and enabled the remote play options in  YYTMA, so when the ytm segement is added it should pop up on the prompt. But none of that happens, I've also tried putting the segment at the beginning or at end of the themes code and as too with explicitly using use_api, and defining the same website in different styles. Maybe I'm missing something very small here or I just over looked stuff but I think I had copied the write code from the website (firstly I used the sample code, that's also didn't work). So what could be the cause of this situation?

Thanks

### Version

Latest

### Theme

A mix/hybrid of themes but the core is night-owl theme.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

**Comment by JanDeDobbeleer** [comment]
@Speakable1 OK, so we have the hidden setting called `http_timeout` which is set to 20ms. It's possible the call to YTDM takes longer and thus the segment is never shown. You can play around with that property to see fi makes a difference. For example, set it high so we can rule it out:

```json
{
  "type": "ytm",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "#ffffff",
  "background": "#FF0000",
  "properties": {
    "prefix": "\uF16A ",
    "playing_icon": "\uE602 ",
    "paused_icon": "\uF8E3 ",
    "stopped_icon": "\uF04D ",
    "track_separator" : " - ",
   "http_timeout": 1000
  }
}
```

**Comment by Pyrrhusn** [comment]
Thanks for your fast reply. 
I'm trying to make it work with `http_timeout` but it also doesn't do anything. I tried setting the value to a greater value but no changes. Here is my code of the segment:

![image](https://user-images.githubusercontent.com/43817108/139651656-8bfebd0c-ae36-4afb-bffc-4c00d37f41f3.png)

`use_api` still doesn't work. I'm suspecting that the problem may be on the YTMA end.

**Comment by JanDeDobbeleer** [comment]
@Speakable1 can you try to debug using the --debug flag with your config?
