### ISSUE TITLE
Bug in omp.ps1, v5.16.5

### ISSUE THREAD

**Issue by asherber** [JanDeDobbeleer/oh-my-posh#1150]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

[These two lines](https://github.com/JanDeDobbeleer/oh-my-posh/blob/d328c819323dd0794db635ce211e6c0e5c28f2b2/src/init/omp.ps1#L38-L39) throw an error for me in v5.16.5

I think they should be:

```pwsh
Remove-Variable omp_value -Confirm:$false
Remove-Variable omp_config -Confirm:$false
```

### Version

v5.16.5

### Theme

Custom theme, but issue exists with built-in themes as well

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
Remove-Variable:
Line |
  38 |  Remove-Variable $omp_value -Confirm:$false
     |                  ~~~~~~~~~~
     | Cannot bind argument to parameter 'Name' because it is null.
Remove-Variable:
Line |
  39 |  Remove-Variable $omp_config -Confirm:$false
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a variable with the name 'C:\Users\Aaron\Documents\PowerShell\aas.omp.yaml'.
```

**Comment by trungnhm1998** [comment]
Just installed OMP same thing happened with Powershell on Windows 10.

**Comment by Langsdorf** [comment]
Same thing here, 
![image](https://user-images.githubusercontent.com/13462281/139769871-a186616d-73ba-4bb4-a39f-73955e0d1b36.png)

PowerShell 7.1.5 
Windows 11

**Comment by Andre-Atkinson** [comment]
Running into the same issue, fresh install as of 2/11/2021
Win10
PowerShell 7.1.5
![2021-11-02_11h33_44](https://user-images.githubusercontent.com/74160430/139784707-ce352d22-86f1-44f3-ad35-b6d858113a15.png)

**Comment by JanDeDobbeleer** [comment]
So sorry, I tested this pretty late at night and must have done something wrong in the process. Won't happen again.

**Comment by trungnhm1998** [comment]
> So sorry, I tested this pretty late at night and must have done something wrong in the process. Won't happen again.

allis good, we here just trying to help out by submitting git issue.
