### ISSUE TITLE
Can't install oh my posh

### ISSUE THREAD

**Issue by goddvader** [JanDeDobbeleer/oh-my-posh#1159]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

hey, i just wanted to install oh my posh. Everthing seems to work fine until i want to set a theme.
PS C:\Powershell> Set-Poshprompt Paradox
ResourceUnavailable: C:\Users\
![InkedOhMyPoshError](https://user-images.githubusercontent.com/67023837/139871884-df9dd316-0d94-463a-9397-7de50df0eb36.jpg)
******\Documents\PowerShell\Modules\oh-my-posh\5.16.6\oh-my-posh.psm1:86
Line |
  86 |      (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'posh-windows-amd64.exe' failed to run: StandardOutputEncoding is only supported when standard
     | output is redirected.At C:\Users\******\Documents\PowerShell\Modules\oh-my-posh\5.16.6\oh-my-posh.psm1:86 char:6 +     (& $poshCommand
     | --init --shell=pwsh --config="$config") | Invoke- … +
     | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.

### Version

The newest

### Theme

Does not matter, no one is working for me

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@goddvader it seems we can't set the console to UTF8 encoding (which is needed and done on line 8 [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/packages/powershell/oh-my-posh/oh-my-posh.psm1)). Anything special on your system?

Can you run the following command?

```
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

**Comment by goddvader** [comment]
Hi @JanDeDobbeleer  thank you! Command runs without an issue. Already installed my device completely new. Without any effect..

**Comment by JanDeDobbeleer** [comment]
@goddvader can you try to install the module outside of your Onedrive folder? Because something is off on your system.

**Comment by goddvader** [comment]
Hi Jan @JanDeDobbeleer  i have my PS $PROFILE now directly on C:\ - uninstalled the module and installed it new. Still the same. Even went into windows settings and marked the beta option for utf8 for the whole OS

**Comment by JanDeDobbeleer** [comment]
@goddvader it's not going to be the problem probably then, can you run `((Get-Module oh-my-posh).Modulebase)/posh-windows-amd64.exe` directly?

**Comment by goddvader** [comment]
@JanDeDobbeleer  no, this comes up:

ParserError:
Line |
   1 |  ((Get-Module oh-my-posh).Modulebase)/posh-windows-amd64.exe
     |                                       ~
     | You must provide a value expression following the '/' operator.

**Comment by JanDeDobbeleer** [comment]
@goddvader I'm sorry, that me being incomplete. The following command should run the executable:

``` posh
 & "$((Get-Module oh-my-posh).ModuleBase)\bin\posh-windows-amd64.exe"
```

**Comment by goddvader** [comment]
@JanDeDobbeleer  that seems to work! 
![Snipaste_2021-11-03_12-50-29](https://user-images.githubusercontent.com/67023837/140055006-506cd961-b58f-4ec9-97ea-c82654725dbb.png)

**Comment by JanDeDobbeleer** [comment]
Can you try the following?

```pwsh
(& "$((Get-Module oh-my-posh).ModuleBase)\bin\posh-windows-amd64.exe" --init --shell=pwsh --config="$((Get-Module oh-my-posh).ModuleBase)\themes\agnoster.omp.json") | Invoke-Expression
```

**Comment by goddvader** [comment]
`C:\Powershell>(& "$((Get-Module oh-my-posh).ModuleBase)\bin\posh-windows-amd64.exe" --init --shell=pwsh --config="$((Get-Module oh-my-posh).ModuleBase)\themes\agnoster.omp.json") | Invoke-Expression
ResourceUnavailable: Program 'posh-windows-amd64.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected.At line:1 char:2
+ (& "$((Get-Module oh-my-posh).ModuleBase)\bin\posh-windows-amd64.exe" …
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.`


still nothing... i dont get it

**Comment by JanDeDobbeleer** [comment]
This really smells like a crazy encoding issue. Can you try the following:

```pwsh
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
(& "$((Get-Module oh-my-posh).ModuleBase)\bin\posh-windows-amd64.exe" --init --shell=pwsh --config="$((Get-Module oh-my-posh).ModuleBase)\themes\agnoster.omp.json") | Invoke-Expression
```

**Comment by goddvader** [comment]
Nice that works!! 
how do I now that this remains? even after a reboot etc.?

**Comment by JanDeDobbeleer** [comment]
> Nice that works!! 
> 
> how do I now that this remains? even after a reboot etc.?

Edit your `$PROFILE` and add the following:

```pwsh
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
Import-Module oh-my-posh
Set-Poshprompt agnoster
```

**Comment by goddvader** [comment]
Thank you! YOU are the man! really appriciate that support!
