### ISSUE TITLE
Ctrl + ← or Ctrl + → converted to ;5C or ;5D

### ISSUE THREAD

**Issue by satanasdiabolo** [JanDeDobbeleer/oh-my-posh#1162]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When using keyboard shortcut ctrl + arrow left or right to accelerate the motion of the cursor it's interpreted as ;5C or ;5D by the shell

### Version

5.16.6

### Theme

jandedobbeleer.omp.json

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

**Comment by JanDeDobbeleer** [comment]
@satanasdiabolo oh-my-posh does not influence readline so I don't see how that's an issue for us? Can't reproduce this on mac using zsh.

**Comment by satanasdiabolo** [comment]
@JanDeDobbeleer thank you very much for pointing me to readline. Before Oh-My-Posh, I was used to OhMYZsh, and they did the magic for me. After some research I've find the default binding of ohmyzsh: https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh

**Comment by JanDeDobbeleer** [comment]
@satanasdiabolo you can also use OhMYZsh with oh-my-posh, best of both worlds!
