### ISSUE TITLE
Templates for all!

### ISSUE THREAD

**Issue by regice202** [JanDeDobbeleer/oh-my-posh#1167]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hey @JanDeDobbeleer I was wondering if it would be possible to just add templates to all of the tags?... Or at least the majority would be nice. I don't imagine it would be too difficult of an addition. Thanks again for your help in the discussions!

**Comment by JanDeDobbeleer** [comment]
@regice202 what do you mean exactly? Templates for all segments?

**Comment by regice202** [comment]
I'm talking basically templates for everything in the config (within reason). So stuff like `prefix, postfix, leading_diamond, trailing_diamond`. Any configuration that seems reasonable to have a template.

**Comment by JanDeDobbeleer** [comment]
@regice202 if we do templates on every segment (which is in the works), there's no need for this in combination with advanced coloring techniques (all properties you mentioned can be obsolete in that case). So I'm closing this in favor of that.
