### ISSUE TITLE
Prompt is slow even with empty profile

### ISSUE THREAD

**Issue by kosmakoff** [JanDeDobbeleer/oh-my-posh#1168]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Just installed Posh on fresh installation of Powershell Core on Windows 11. There is a noticeable delay - around 2 seconds - between consecutive prompts when I simply smash Enter key multiple times.

I made empty theme for debugging, to see if any block was causing the delay, but it was slow even without blocks.

Theme is as follows:
```json
{
  "blocks": [
  ],
  "final_space": true,
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{ .Shell }} in {{ .Folder }}"
}
```

Posh-Debug output:
```
Here are the timings of segments in your prompt:

ConsoleTitle(true) -   2 ms - pwsh in ~
```

Debug log file:
```
2021/11/04 14:31:45 #### start oh-my-posh run ####
2021/11/04 14:31:45 getenv duration: 0s, args: LOCALAPPDATA
2021/11/04 14:31:45 getCachePath duration: 0s, args: 
2021/11/04 14:31:45 getArgs duration: 0s, args: 
2021/11/04 14:31:45 getArgs duration: 0s, args: 
2021/11/04 14:31:45 getShellName duration: 14.3044ms, args: 
2021/11/04 14:31:45 isRunningAsRoot duration: 0s, args: 
2021/11/04 14:31:45 getcwd duration: 0s, args: 
2021/11/04 14:31:45 getPathSeperator duration: 0s, args: 
2021/11/04 14:31:45 getPathSeperator duration: 0s, args: 
2021/11/04 14:31:45 getShellName duration: 0s, args: 
2021/11/04 14:31:45 getCurrentUser duration: 0s, args: 
2021/11/04 14:31:45 getHostName duration: 0s, args: 
2021/11/04 14:31:45 #### end oh-my-posh run ####
```

### Version

5.18.0

### Theme

`jandedobbeleer`, also empty made for debugging.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by lnu** [comment]
and you don't have that delay at all when not using omp? because looking at the logs, omp is really fast.
is it a local profile or something similar to this issue https://github.com/JanDeDobbeleer/oh-my-posh/issues/1126

**Comment by kosmakoff** [comment]
> and you don't have that delay at all when not using omp? because looking at the logs, omp is really fast. is it a local profile or something similar to this issue #1126

No, it's a local profile. I did a little bit more investigation and found that it is the omp executable being slow (or rather starting slow), not pwsh. I ran the `posh-windows-amd64.exe` from `cmd` and had the same timings.

Additionally, when running in debug mode, I noticed that the whole lag time it outputs nothing, then it outputs the debug info, then immediately stops. Seems like the executable initialization takes that long.

Attached screen recording:

https://user-images.githubusercontent.com/1533952/140367910-c7ce3778-6782-41f5-aa85-d131a42be5c2.mp4

**Comment by JanDeDobbeleer** [comment]
@kosmakoff can it be you're having issues caused by security scanning before running executables for example? As I can't reproduce this on my Windows machine.

**Comment by kosmakoff** [comment]
Apparently it was it, so embarrassing. I added the omp executable to antivirus exclusions, and the lag disappeared. Maybe it makes sense to add this solution to FAQ?

**Comment by JanDeDobbeleer** [comment]
I'll make an FAQ item out of this! Good suggestion. Truth be told, I'm happy we found the root cause this fast. These issues are always scary tbh (as it can be a gazillion things).

**Comment by lnu** [comment]
Does not surprise me at all… which one is it?

**Comment by kosmakoff** [comment]
@lnu It's Microsoft Defender Antivirus. I added exclusion under `Virus & threat protection settings` specifying the exact omp executable from Powershell modules folder.

![image](https://user-images.githubusercontent.com/1533952/140387394-49447b3b-7036-4ad8-b6ac-55bd8aa0c899.png)
