### ISSUE TITLE
Vue and Laravel segments like the node segment 

### ISSUE THREAD

**Issue by Alhada06** [JanDeDobbeleer/oh-my-posh#1171]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Since there are many segments for many languages and frameworks, maybe it would be possible to add two new segments for Vue js and Laravel ?
I never used Go,  but after looking through the docs and using for my own theme , i think its  probably  enough  to rebuild the segment from node or php for Vue and Laravel.

**Comment by JanDeDobbeleer** [comment]
@Alhada06 what would expect with vue (js code) and laravel (php)? Is there a CLI or maybe missing files for those two segments we don't detect yet?

**Comment by Alhada06** [comment]
@JanDeDobbeleer  hi, in terms of behavior I was thinking something like showing the icon and the version as it already is with node and php.
As for files, for Vue I think it’s just the .vue files missing in relation to the node ones, and for Laravel the blade.php files in relation to the php ones.

As for CLI i think that Vue as one but i have never really used it because I have been using Vue packaged with Laravel, as for Laravel it uses the Artisan as a CLI.

Hope I was helpful enough as I am still quite new both with Vue and Laravel.
