### ISSUE TITLE
Using themes that have text segment on leave 2 letters when using git command history

### ISSUE THREAD

**Issue by BaneOfCode** [JanDeDobbeleer/oh-my-posh#1172]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am trying to create a custom theme and I noticed that if I hit the up arrow to use my git commands from history it leaves 2 letters in my text segment from the first command in history.  I tried other themes with the same result always 2 letters remain in the text segment.  I cannot delete those 2 letters and they do not affect commands and I have to Ctrl-c to get them to clear out.

### Version

5.18.0

### Theme

Blue-owl

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

**Comment by BaneOfCode** [comment]
Also this seems to be happening in Windows Terminal and neovim terminal emulator, but is not happening in a git bash window or VsCode Terminal.

**Comment by JanDeDobbeleer** [comment]
@Otherone22 do you have a screenshot (I can't reproduce this)?

**Comment by BaneOfCode** [comment]
![image](https://user-images.githubusercontent.com/21108368/140507701-2590cd41-5d85-469e-9bce-224bffacd065.png)

The re is from reload.  I have someone I work with that also has this issue when running bash in windows terminal.

I do know bash has a similar issue on linux if the PS1 statement does not escape characters with 0 length with [ ] around it.

**Comment by JanDeDobbeleer** [comment]
@Otherone22 we escape everything on bash (using `\[` and `\]`, but that's not the issue here). When you say Windows and bash you mean Git BASH right?

**Comment by BaneOfCode** [comment]
I am using Windows Terminal (From windows store) as my terminal emulator and running a bash profile inside of Windows terminal.  If I use the Git Bash console it does not have the issue.

**Comment by JanDeDobbeleer** [comment]
@Otherone22 I can't reproduce this at all using the theme you mention inside Windows Terminal. Can you make sure that one's up-to-date? Here's a screenshot of my Windows Terminal setup and Git BASH (I pressed up to cycle commands on every line):

![image](https://user-images.githubusercontent.com/2492783/140535799-acacff97-188e-4fa2-b4fa-7a505e08a2f0.png)

**Comment by BaneOfCode** [comment]
I am on the latest version.  I will play with some more settings and see if I can figure out what is causing this.  I only put an issue here because I also had this issue in neovims terminal emualtor and a coworker also had this issue.  I will try to mess around and see if one of my terminal settings is causing this.

**Comment by ThisWholeDev** [comment]
I am currently getting the same behavior as well. I am using Windows terminal preview version 1.12.2931.0 Oh-my-posh version 5.18.0. I am seeing this in both powershell and bash terminals which both have different themes

![image](https://user-images.githubusercontent.com/8668947/140553740-36f291d0-abf8-4cbe-b76c-85faeddaddf8.png)

I can not get it to happen consistently though.

**Comment by BaneOfCode** [comment]
I have not found anything that cause this behavior to happen but I am seeing it on my home computer as well.  It seems to happen when you have longer commands in your history.  If you are scrolling through commands and scroll through one that is decently long then the next is short I see the cursor jump to the > symbol on the command line and 2 letters are stuck.  I also noticed that pasting long strings like curls don't move to a new line but instead wrap to the front of the terminal.

Here is a docker command that does it with the darkblood.omp.json theme.

![image](https://user-images.githubusercontent.com/21108368/141124100-6ea0416f-9192-4778-9a2e-cea749535f91.png)

**Comment by JanDeDobbeleer** [comment]
OK, let me check if there's an issue with some non-escaped characters.

**Comment by JanDeDobbeleer** [comment]
@Otherone22 I checked the following:
- iTerm2 BASH: no issues
- Windows Terminal Git BASH 1.11.2921.0: no issues
- Windows Terminal Git BASH 1.12.2931.0: no issues

All tested with Blue-owl. I really can't reproduce this on my end.

**Comment by JanDeDobbeleer** [comment]
@BaneOfCode same questions here as for others, is your git up to date? We've seen serious issues when using older versions.

**Comment by BaneOfCode** [comment]
@JanDeDobbeleer Yes I had the latest version but I can update again and try a newer version

**Comment by Strazdonis** [comment]
Sorry for bringing up this dead issue but did you ever find a solution to this issue? @BaneOfCode Running on newest git, terminal preview and oh-my-posh and I get this problem very frequently.

**Comment by ehawman-rosenberg** [comment]
@Strazdonis I had something similar to this and the culprit turned out to be the zero-width character \u200b. Did you edit that into your config or are you using stock?

**Comment by Strazdonis** [comment]
> @Strazdonis I had something similar to this and the culprit turned out to be the zero-width character \u200b. Did you edit that into your config or are you using stock?

No, I still get the issue on default config. However I did find the culprit! Seems like there is a bug when rendering emojis in git bash. 
Adding `export LC_ALL=en_US.UTF-8` at the top of my .bashrc solves it and I haven't experienced the bug so far.

**Comment by JanDeDobbeleer** [comment]
@BaneOfCode can you try @Strazdonis fix and see if that also applies to your issue?

**Comment by BaneOfCode** [comment]
@JanDeDobbeleer I just added the export statement to my .bashrc and so far I am not seeing it keeping any characters at the start of the lines.  I will update this if I find any issues but so far it looks like it worked.

**Comment by JanDeDobbeleer** [comment]
Closing this on Friday 13 as this seems resolved and I like to gamble with luck.

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer hopefully we don't get haunted 💀👻
