### ISSUE TITLE
Inconsistent capitalization for path

### ISSUE THREAD

**Issue by gschizas** [JanDeDobbeleer/oh-my-posh#1173]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When formatting the path, inconsistent capitalization is used, with `c:`  and only `c:` replaced with `C:` indiscrimately.

This is the table of what I'm getting and what I should be getting (note that it's possible to have custom PS drives):

This, surprisingly  only happens when testing (e,g. with `Get-PoshThemes`) not when actually using the program.

In all cases, the command is `.\oh-my-posh.exe -config ..\themes\hunk.omp.json -pwd ENTER_PATH_HERE`. I'm using hunk as the simplest demo, this happens to many other themes. I have also removed extraneous powerline characters, for clarity.

| path | result | expected | status |
|---|---|---|---|
|C:\Windows\ |C:\Windows\ |C:\Windows\ | :white_check_mark: |
|src:\test\test|srC:\test\test |src:\test\test | :x: |
|g:\Other\ | g:\Other\ | G:\Other\ | :x: |
|test:\test\ | test:\test\ | test:\test\ |  :white_check_mark: |
|testb:\test\ | testb:\test\ | testb:\test\ |  :white_check_mark: |
|testc:\test\ | testC:\test\ | testc:\test\ |  :x: |
|HKLM:\SOFTWARE\testc:test\ | HKLM:\SOFTWARE\testC:test\ | HKLM:\SOFTWARE\testc:test\ | :x: |

I've located the problem [at the `environment.go` file, line 188](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/environment.go#L188), where the `correctPath` function is being too naïve about Windows paths. Other drive letters than `C:` are obviously possible, you can make custom PSDrives that end in `c` (obviously the full name is greater) and you can have colons in the middle of registry keys.

The correct way would be to replace "Letter + : at the start of the string only" (if this is even necessary), not just `c:` to `C:` indiscriminately 

### Version

5.18.0

### Theme

hunk

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by gschizas** [comment]
I have corrected this locally and will be making a pull request soon.

The fact that I don't really know golang didn't stop me. It didn't even stop me from adding a test case for the function. 😄

**Comment by JanDeDobbeleer** [comment]
@gschizas you're right, that's a bit silly indeed. The expected seems correct as well and perfect test cases. Great work on the issue and completeness, this is a prime example. Looking forward to the PR!
