### ISSUE TITLE
Cannot get it working on my debian 11

### ISSUE THREAD

**Issue by xcap2000** [JanDeDobbeleer/oh-my-posh#1175]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Team.

I have installed on my Debian 11 following the steps described here:
https://ohmyposh.dev/docs/linux

I added to my .bashrc the eval line. When I test the configuration using:
oh-my-posh -eval -debug -shell bash -config ~/.xcap.omp.json
No error was reported, I checked logs (oh-my-posh.log) and no error was reported too.

I copied the theme based on blue-owl.

I am using gnome-terminal on gnome and I have a nerd font properly set. The issue is that no errors is reported and my shell keeps the same, no change. If I iterate through the themes as per documentation all themes are shown correctly.

Eval line at the end of my ~/.bashrc:
eval "$(oh-my-posh -debug -init -shell bash -config ~/.xcap.omp.json)"

As I get no error I might be missing something but after reviewing the installations steps I was not able to figure it out.

Kind Regards,

Carlos Adriano Portes

### Version

5.19.0

### Theme

blue-owl

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Relevant log output

```shell
oh-my-posh -init -shell bash -config ~/.xcap.omp.json
export POSH_THEME="/home/carlos/.xcap.omp.json"
export POWERLINE_COMMAND="oh-my-posh"
export CONDA_PROMPT_MODIFIER=false

TIMER_START="/tmp/${USER}.start.$$"

# some environments don't have the filesystem we'd expect
if [[ ! -d "/tmp" ]]; then
  TIMER_START="${HOME}/.${USER}.start.$$"
fi

PS0='$(/usr/local/bin/oh-my-posh --millis > "$TIMER_START")'

function _omp_hook() {
    local ret=$?

    omp_stack_count=$((${#DIRSTACK[@]} - 1))
    omp_elapsed=-1
    if [[ -f "$TIMER_START" ]]; then
        omp_now=$(/usr/local/bin/oh-my-posh --millis)
        omp_start_time=$(cat "$TIMER_START")
        omp_elapsed=$((omp_now-omp_start_time))
        rm -f "$TIMER_START"
    fi
    PS1="$(/usr/local/bin/oh-my-posh --config="$POSH_THEME" --shell=bash --error="$ret" --execution-time="$omp_elapsed" --stack-count="$omp_stack_count" | tr -d '\0')"

    return $ret
}

if [ "$TERM" != "linux" ] && [ -x "$(command -v /usr/local/bin/oh-my-posh)" ] && ! [[ "$PROMPT_COMMAND" =~ "_omp_hook" ]]; then
    PROMPT_COMMAND="_omp_hook; $PROMPT_COMMAND"
fi

function _omp_runonexit() {
  [[ -f $TIMER_START ]] && rm -f "$TIMER_START"
}

trap _omp_runonexit EXIT

function export_poshconfig() {
    [ $# -eq 0 ] && { echo "Usage: $0 \"filename\""; return; }
    format=$2
    if [ -z "$format" ]; then
      format="json"
    fi
    /usr/local/bin/oh-my-posh --config="$POSH_THEME" --print-config --config-format="$format" > $1
}

oh-my-posh.log
2021/11/05 11:15:14 #### start oh-my-posh run ####
2021/11/05 11:15:14 getenv duration: 2.291µs, args: XDG_CACHE_HOME
2021/11/05 11:15:14 getCachePath duration: 105.036µs, args: 
2021/11/05 11:15:14 getArgs duration: 540ns, args: 
2021/11/05 11:15:14 getArgs duration: 325ns, args: 
2021/11/05 11:15:14 getShellName duration: 762ns, args: 
2021/11/05 11:15:14 isRunningAsRoot duration: 2.44µs, args: 
2021/11/05 11:15:14 getcwd duration: 20.922µs, args: 
2021/11/05 11:15:14 getPathSeperator duration: 284ns, args: 
2021/11/05 11:15:14 getPathSeperator duration: 158ns, args: 
2021/11/05 11:15:14 getShellName duration: 214ns, args: 
2021/11/05 11:15:14 getCurrentUser duration: 883ns, args: 
2021/11/05 11:15:14 getHostName duration: 5.307µs, args: 
2021/11/05 11:15:14 getcwd duration: 507ns, args: 
2021/11/05 11:15:14 isRunningAsRoot duration: 2.234µs, args: 
2021/11/05 11:15:14 getcwd duration: 233ns, args: 
2021/11/05 11:15:14 isRunningAsRoot duration: 2.093µs, args: 
2021/11/05 11:15:14 getcwd duration: 208ns, args: 
2021/11/05 11:15:14 getPathSeperator duration: 330ns, args: 
2021/11/05 11:15:14 getPathSeperator duration: 385ns, args: 
2021/11/05 11:15:14 getShellName duration: 410ns, args: 
2021/11/05 11:15:14 getCurrentUser duration: 1.447µs, args: 
2021/11/05 11:15:14 getHostName duration: 4.22µs, args: 
2021/11/05 11:15:14 #### end oh-my-posh run ####
```

**Comment by JanDeDobbeleer** [comment]
@xcap2000 what happens when you run `eval "$(oh-my-posh -debug -init -shell bash -config ~/.xcap.omp.json)"` directly in your shell?

**Comment by xcap2000** [comment]
Nothing happens if I ran this command, nor another bash prompt is created, I mean, if I ctrl + d after running it will exit gnome-terminal immediately. No errors are reported.

**Comment by JanDeDobbeleer** [comment]
@xcap2000 what bash version do you have? I honestly can't explain this.

**Comment by xcap2000** [comment]
$ bash --version
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

**Comment by xcap2000** [comment]
I found the issue and this might be something similar on the other post, I had in bash a configuration for git-prompt.sh which I use for showing git info on bash, after commenting it it started to work. I thought it would not cause any problems once I put omp eval at the end of .bashrc. Sorry for making you loose time with this and thank you for your support.

**Comment by JanDeDobbeleer** [comment]
@xcap2000 every issue and solution brings more context to me so I'm able to help others as well. Not everyone is able to figure things out so I'm grateful you took the time to create an issue and share this.

**Comment by diorcula** [comment]
> I found the issue and this might be something similar on the other post, I had in bash a configuration for git-prompt.sh which I use for showing git info on bash, after commenting it it started to work. I thought it would not cause any problems once I put omp eval at the end of .bashrc. Sorry for making you loose time with this and thank you for your support.

So what did you exactly do? As i'm not sure if i have a git prompt.sh file that i edited?

**Comment by xcap2000** [comment]
> > I found the issue and this might be something similar on the other post, I had in bash a configuration for git-prompt.sh which I use for showing git info on bash, after commenting it it started to work. I thought it would not cause any problems once I put omp eval at the end of .bashrc. Sorry for making you loose time with this and thank you for your support.
> 
> So what did you exactly do? As i'm not sure if i have a git prompt.sh file that i edited?

The issue was on my .bashrc, I had previous configurations there that conflicted with OMP, once I removed them everything started working. It is worth mentioning that the extra configurations were made by me, not default ones.

**Comment by diorcula** [comment]
> 

I only have the following in my bash.rc:
```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
source /home/diorcula/.local/lib/python3.9/site-packages/powerline/bindings/bash/powerline.sh

# Environment Variable
export ACF_PRO_KEY=b3JkZXJfaWQ9Njc3OTl8dHlwZT1kZXZlbG9wZXJ8ZGF0ZT0yMDE1LTEwLTMxIDEzOjE3OjA4


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Oh-my-posh, as of now doesn't work, except the Jandedobbeleer theme
eval "$(oh-my-posh --init --shell bash --config ~/.poshthemes/bubbles.omp.json)"
```

**Comment by JanDeDobbeleer** [comment]
@diorcula what stands out is the following:

```bash
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt
...

# Powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
source /home/diorcula/.local/lib/python3.9/site-packages/powerline/bindings/bash/powerline.sh
```

Comment out everything except oh-my-posh, that should work. Then work your way back, but those two are my main contenders.

**Comment by xcap2000** [comment]
> @diorcula what stands out is the following:
> 
> ```shell
> # set a fancy prompt (non-color, unless we know we "want" color)
> case "$TERM" in
>     xterm-color|*-256color) color_prompt=yes;;
> esac
> 
> # uncomment for a colored prompt, if the terminal has the capability; turned
> # off by default to not distract the user: the focus in a terminal window
> # should be on the output of commands, not on the prompt
> #force_color_prompt=yes
> 
> if [ -n "$force_color_prompt" ]; then
>     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
> 	# We have color support; assume it's compliant with Ecma-48
> 	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
> 	# a case would tend to support setf rather than setaf.)
> 	color_prompt=yes
>     else
> 	color_prompt=
>     fi
> fi
> 
> if [ "$color_prompt" = yes ]; then
>     PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
> else
>     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
> fi
> unset color_prompt force_color_prompt
> ...
> 
> # Powerline
> powerline-daemon -q
> POWERLINE_BASH_CONTINUATION=1
> POWERLINE_BASH_SELECT=1
> source /home/diorcula/.local/lib/python3.9/site-packages/powerline/bindings/bash/powerline.sh
> ```
> 
> Comment out everything except oh-my-posh, that should work. Then work your way back, but those two are my main contenders.

Comparing to my version the only thing different is:
# Powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
source /home/diorcula/.local/lib/python3.9/site-packages/powerline/bindings/bash/powerline.sh

Removing it should work, as @JanDeDobbeleer said you may remove this make it work and then work your way back. From what I could understand from powerline docs (https://github.com/powerline/powerline) I strong believe this is conflicting with OMP.

**Comment by diorcula** [comment]
@JanDeDobbeleer  @xcap2000 Thanks for the help, commenting out powerline indeed worked like a charm!!

**Comment by xcap2000** [comment]
> @JanDeDobbeleer @xcap2000 Thanks for the help, commenting out powerline indeed worked like a charm!!

Perfect! Good to know :+1:
