### ISSUE TITLE
Support showing pre-release version suffix identifiers in the dotnet segment

### ISSUE THREAD

**Issue by DamianEdwards** [JanDeDobbeleer/oh-my-posh#1178]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be great if the dotnet segment could support an option to include a configurable number of identifiers from the pre-release suffix in the .NET version string. Today only the stable portion of the version string is displayed, e.g.:

![image](https://user-images.githubusercontent.com/249088/140592286-66942bde-1059-4752-ad11-6caa7fc53701.png)

It would be useful to support configuring the number of pre-release suffix period-delimited identifiers to include (with the default being zero). Details of pre-release suffix identifiers are in the [SemVer 2.0 spec](https://semver.org/#spec-item-9).

Strawman segment configuration and resultant display:
``` jsonc
{
  "type": "dotnet",
  "style": "powerline",
  "powerline_symbol": "\uE0C4",
  "properties": {
    "prefix": "  " // .NET logo,
    "prerelease_suffix_identifiers": 2
  }
}
```
``` shell
➜ dotnet -- version
6.0.100-rc.2.21505.57
➜ dotnet new globaljson
The template "global.json file" was created successfully.
  6.0.100-rc.2 ➜ 
```

**Comment by JanDeDobbeleer** [comment]
@DamianEdwards in the example you gave, would you expect to see `6.0.100-rc.2` or the entire version string?

**Comment by lnu** [comment]
the original regex is partially incorrect but we can capturate the rc group with something like this:
`(?P<version>((?P<major>[0-9]+).(?P<minor>[0-9]+).(?P<patch>[0-9]+)))-(?P<rc>rc\..*)`

![image](https://user-images.githubusercontent.com/1829553/140602562-45f8e59c-79c0-4b8c-85ec-526304b2543a.png)

needs to be tweaked to allow rc and non rc versions:
`(?P<version>(?P<major>[0-9]+).(?P<minor>[0-9]+).(?P<patch>[0-9]+)(?:-(?P<rc>rc\.[a-zA-Z0-9.]*))?)`

Could be done throug templates, offering Major, Minor, Path, RC and Full properties

`{{.Major}}.{{.Minor}}.{{.Patch}}.{{ substr 0 4 .RC }}` 

quick start: https://github.com/lnu/oh-my-posh/commit/910a61397d4fa1127340a3ecf73fb10c74368dbb

**Comment by lnu** [comment]
so with version 6.1.0 and with no templates in your config it will display the following:
![image](https://user-images.githubusercontent.com/1829553/140658216-d4833e90-00c6-4509-b65d-84ad39f0ebb9.png)

with this template:
```
"template":"{{.Major}}.{{.Minor}}.{{.Patch}}{{if .Prerelease }}.{{ substr 0 4 .Prerelease }}{{end}}"
```
![image](https://user-images.githubusercontent.com/1829553/140658252-76cfb572-e7e9-43b1-99dd-9262cc5d54ea.png)

and if you want the hyperlink to the release notes(should work for preview and non-preview releases):
```
 "version_url_template":"[{{.Major}}.{{.Minor}}.{{.Patch}}{{if .Prerelease }}.{{ substr 0 4 .Prerelease }}{{end}}](https://github.com/dotnet/core/blob/master/release-notes/{{.Major}}.{{.Minor}}/{{if .Prerelease }}preview/{{.Major}}.{{.Minor}}.0-{{ substr 0 4 .Prerelease }}.md{{else}}{{.Major}}.{{.Minor}}.{{ substr 0 1 .Patch}}/{{.Major}}.{{.Minor}}.{{ substr 0 1 .Patch}}.md{{end}})"   
```
![image](https://user-images.githubusercontent.com/1829553/140658284-f0886ae8-c951-4014-91c8-ecd3bc7cc47b.png)

https://github.com/dotnet/core/blob/main/release-notes/6.0/preview/6.0.0-rc.2.md

**Comment by DamianEdwards** [comment]
@JanDeDobbeleer with the example I gave I'd expect `6.0.100-rc.2` due to configuring for 2 pre-release identifiers, which in this case would be `rc` and `2`.

Doing this via a template would allow for the ultimate expression (and the hyperlink is a nice touch too!).

**Comment by lnu** [comment]
=> `"template":"{{.Major}}.{{.Minor}}.{{.Patch}}{{if .Prerelease }}-{{ substr 0 4 .Prerelease }}{{end}}"`
`"version_url_template":"[{{.Major}}.{{.Minor}}.{{.Patch}}{{if .Prerelease }}-{{ substr 0 4 .Prerelease }}{{end}}](https://github.com/dotnet/core/blob/master/release-notes/{{.Major}}.{{.Minor}}/{{if .Prerelease }}preview/{{.Major}}.{{.Minor}}.0-{{ substr 0 4 .Prerelease }}.md{{else}}{{.Major}}.{{.Minor}}.{{ substr 0 1 .Patch}}/{{.Major}}.{{.Minor}}.{{ substr 0 1 .Patch}}.md{{end}})"`

**Comment by JanDeDobbeleer** [comment]
@lnu @DamianEdwards can we consider this closed?

**Comment by DamianEdwards** [comment]
Ok I didn't realize it was done? Is it in a new build I can try?

**Comment by lnu** [comment]
> Ok I didn't realize it was done? Is it in a new build I can try?

https://github.com/JanDeDobbeleer/oh-my-posh/issues/1178#issuecomment-962663574

It works from 6.1.0

**Comment by DamianEdwards** [comment]
Fantastic, thank you!
