### ISSUE TITLE
 This bug goes away when I use the clear command.  I use windows 11 wsl2 ubuntu

### ISSUE THREAD

**Issue by masud-rana-1** [JanDeDobbeleer/oh-my-posh#1181]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

This bug goes away when I use the clear command and keyboard enter key. How to solve the problem?

![image](https://user-images.githubusercontent.com/56246849/140613686-a92e2078-5703-4a6d-9656-4677093c56d9.png)

### Version

install official website

### Theme

ohmyposhv3-v2.json

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash

**Comment by JanDeDobbeleer** [comment]
@masud4 that’s a known Windows Terminal bug. You can find more information and a fix [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext).
