### ISSUE TITLE
Update the session segment in "bubblines" theme

### ISSUE THREAD

**Issue by atRafeq** [JanDeDobbeleer/oh-my-posh#1183]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I notice when using `bubblesline` theme, and I input a long command the text  _corrupts_ the right aligned segment. I favor the `bubbles` theme the most because it fits my python workflow the most. However as the time passed, I notice that `bublesline` _color palette fits the long-hours_ editing workflow better. I like the type `session` to be left aligned instead of above-righted like in `bubbles`. I tried to tweak it in the `themes\bubblesline.omp.json` but no avail. There is `"newline": true` however it does not put that segment in like expected it should behave like in `bubbles` theme. Is this a bug or intended like that?

**Comment by lnu** [comment]
something like this?
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1829553/140634518-b6f2acca-7620-4698-a5b0-54f41d427f87.png">

**Comment by atRafeq** [comment]
Yes, exactly like that but with `bubblesline` color palette 😀 and the rest is left untouched. In simple words, only the `session` move to button left. But I don't know whether the `executiontime` should be tweaked.

**Comment by JanDeDobbeleer** [comment]
@Rafeqm `bubblesline` uses an `rprompt` which will always render to the right on the same line regardless. `bubbles` doesn't have that. You want to create custom theme between both ;-) I would not adjust the themes here (I fixed `bubblesline` as it had a newline in it for some strange reason).

**Comment by JanDeDobbeleer** [comment]
@lnu can you share the config so @Rafeqm can have a go?

**Comment by lnu** [comment]
https://gist.github.com/lnu/26fac07bf92d2576ac4349866a3e50c9

![image](https://user-images.githubusercontent.com/1829553/140657423-fa3bfa08-2333-4941-8714-aae34d9a836a.png)


I added the executiontime which was not in bubblesline

**Comment by atRafeq** [comment]
👍🏽 Thanks @lnu, finally my eyes can get more comfortable in the long-hours work 😊.

> @Rafeqm `bubblesline` uses an `rprompt` which will always render to the right on the same line regardless. `bubbles` doesn't have that.

Also thanks to make me more understand what `rpromt` means (@JanDeDobbeleer, I think the docs maybe should have a little preview on this?). Btw, I notice that `executiontime`'s color is still that of `bubbles`, but no problem I shall try to match it with `bubblesline`'s color as my exercise. Happy coding 🤗!
