### ISSUE TITLE
Regression - Git segment doesn't render anymore

### ISSUE THREAD

**Issue by bgelens** [JanDeDobbeleer/oh-my-posh#119]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The git segment doesn't work anymore. Last version it worked for me was 3.23.5. In the screenshot you can see I checked 2 newer versions (2.24.3 and 2.26.1)

![image](https://user-images.githubusercontent.com/10071039/97841249-b5e98280-1ce5-11eb-9329-fc0950c11ab5.png)

I checked both with a PSDrive path (my normal operation, `GIT:/bgelens.github.io`) and normal filesystem path (`/Users/bengelens/git/bgelens.github.io`).

### Environment

- Oh my Posh version: see above
- Theme: [custom](https://gist.github.com/bgelens/440c21ced26a42a7cbd7a147a006b13c)
- Operating System: MacOs
- Shell: PowerShell 7.1 rc2
- Terminal: iTerm2

### Steps to Reproduce

Load explicit version via profile:

Working version:

```powershell
#requires -Module @{ModuleName = 'oh-my-posh'; RequiredVersion = '3.23.5'}
```

Non working version:

```powershell
#requires -Module @{ModuleName = 'oh-my-posh'; RequiredVersion = '3.26.1'}
```

Navigate to a git repository on disk

**Expected behavior:** [What you expected to happen]

Should render

**Actual behavior:** [What actually happened]

Does not render

**Comment by mtushevsky** [comment]
I have this problem on windows 10 too

**Comment by maxtushewski** [comment]
I have this problem on windows 10 too

**Comment by lewishenson** [comment]
Seeing on Windows 10 also (git version 2.27.0.windows.1)

**Comment by JanDeDobbeleer** [comment]
This has to do with the PWD issues I've been having on Powershell. I've fixed this a few times already but it always introduces a new bug due to the way ohmyposh is now called.

I'll try to run all scenarios and see if there's a fix for everything once and for all.

**Comment by JanDeDobbeleer** [comment]
Fixed
<img width="840" alt="afbeelding" src="https://user-images.githubusercontent.com/2492783/97872280-15f81d00-1d16-11eb-9cc7-a5a3bc45d8b3.png">
