### ISSUE TITLE
Add "oh-my-posh" tag to the manifest for the Windows Package Manager

### ISSUE THREAD

**Issue by denelon** [JanDeDobbeleer/oh-my-posh#1192]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Several users searched for "oh-my-posh" and didn't get any results in the Windows Package Manager. Adding this as a tag would help this to show up in `winget search oh-my-posh`.

**Comment by JanDeDobbeleer** [comment]
Thank you so much!

**Comment by JanDeDobbeleer** [comment]
@All-contributors please add @denelon for code
