### ISSUE TITLE
Doesn't show Python version

### ISSUE THREAD

**Issue by YSCohen** [JanDeDobbeleer/oh-my-posh#1196]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

When using the `night-owl` theme, I expected it to show the Python version in the top right, but it didn't. Neither did `space` or `star`. It does show .NET version, though.

### Version

6.1.1

### Theme

night-owl

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output
```
Here are the timings of segments in your prompt:

ConsoleTitle(false)  -   0 ms -
os(true)             -   0 ms - ╭─   
root(false)          -   0 ms -
path(true)           -   0 ms -        Python 
git(false)           -   4 ms -
executiontime(true)  -   0 ms -  9s 1ms 
node(false)          -   0 ms -
python(false)        -   0 ms -
java(false)          -   5 ms -
dotnet(false)        -   0 ms -
go(false)            -   0 ms -
rust(false)          -   0 ms -
dart(false)          -   0 ms -
angular(false)       -   0 ms -
julia(false)         -   0 ms -
ruby(false)          -   0 ms -
azfunc(false)        -   0 ms -
aws(false)           -   0 ms -
kubectl(false)       -  32 ms -
time(true)           -   0 ms -     20:46:48 
text(true)           -   0 ms - ╰─
spotify(false)       -   7 ms -
exit(true)           -   0 ms - 
```

**Comment by YSCohen** [comment]
Fixed: added `"display_mode": "files"` to python.properties, but i feel like that was just patching a bigger problem

**Comment by JanDeDobbeleer** [comment]
@HashemLovesYou initially `files` was the default. But for Python, a lot of people use a virtual env so that got switched because `files` caused even more confusion (as a default value).

What do you mean with the last statement ?

**Comment by YSCohen** [comment]
in the `theme.omp.json` 
```
{
  "type": "python",
  "style": "diamond",
  "leading_diamond": " \uE0B6",
  "trailing_diamond": "\uE0B4",
  "foreground": "#ffc51e",
  "background": "#105ea0",
  "properties": {
    "prefix": "\ue235  ",
    "postfix": "",
    "display_mode": "files"
  }
},
```

**Comment by JanDeDobbeleer** [comment]
@HashemLovesYou yes, but what do you mean with ` i feel like that was just patching a bigger problem`?

**Comment by YSCohen** [comment]
I was saying that the problem wasn't in the profile but in the module itself. Thanks for explaining!

**Comment by JamesIslan** [comment]
> Fixed: added `"display_mode": "files"` to python.properties, but i feel like that was just patching a bigger problem

Hello, i know this is a old report but i'm facing the same problem here, for Python and Node version. Can you please tell me where is that "python.properties" file or option? Thanks!

**Comment by JanDeDobbeleer** [comment]
@JamesIslan sure, you can add this like this:

```json
{
  "background": "transparent",
  "foreground": "p:yellow",
  "properties": {
    "display_mode": "files",
    "fetch_version": true,
    "fetch_virtual_env": false
  },
  "style": "plain",
  "template": "\ue235 ",
  "type": "python"
}
```
