### ISSUE TITLE
Powerline/diamond symbols not rendered correctly (possible regression)

### ISSUE THREAD

**Issue by mwasowski** [JanDeDobbeleer/oh-my-posh#1197]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm not sure if it's a regression or new issue, but bug I reported [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/1137) is back in some form.

![obraz](https://user-images.githubusercontent.com/1921808/141079660-5a4a4a6d-4639-413d-bc29-a0aa5a5c7f40.png)

### Version

6.2.0

### Theme

Powerline10k_rainbow with minor modifications

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@mwasowski aah, yes. I forgot to inform you. Please replace `inherit` with `parentBackground` in your config. Related to the [following](https://github.com/JanDeDobbeleer/oh-my-posh/commit/9323f89704214137bd57be902f1ba6d955f1ed91) change.

**Comment by mwasowski** [comment]
Yup, that was it. Sorry, missed that in release notes for 6.0.0 :(

**Comment by JanDeDobbeleer** [comment]
The docs weren't updated either, so this is on me ;-) -> #1200

**Comment by mwasowski** [comment]
Is there a way to spit out summary of the release notes when I am doing `Update-Module oh-my-posh -Scope CurrentUser`? In the same way as `omz update` does on Linux? I know it's proprietary method and here we are dealing with generic powershell one, but yeah, just an idea ;)

**Comment by JanDeDobbeleer** [comment]
I was thinking about that, but given that we push SO MANY releases it's a bit of a challenge to group the relevant information.

**Comment by mwasowski** [comment]
That's true but at the same time release notes are in a lot of cases 1-2 lines. So unless someone updates lets say from 5.0.0 to 6.0.0 (and a lot of changes in this case well..it's expected), it shouldn't be that big of a deal.

Another approach would be to narrow it down to breaking changes?
