### ISSUE TITLE
feat: segment that shows CPU information

### ISSUE THREAD

**Issue by JanDeDobbeleer** [JanDeDobbeleer/oh-my-posh#1201]
### Discussed in https://github.com/JanDeDobbeleer/oh-my-posh/discussions/1199

<div type='discussions-op-text'>

<sup>Originally posted by **joeljose350** November 10, 2021</sup>
A segment that shows CPU information like utilisation, clock speed, temperature, etc. The ability to show this information for each core would make it even better imo.</div>

**Comment by lnu** [comment]
I don't really get it. The prompt is static once generated, so you'll get data only when the prompt is executed the next time?

**Comment by JanDeDobbeleer** [comment]
True, although the same goes for battery. Good point though. My reasoning was that if we can why not do it :-)

**Comment by lnu** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/commit/25be3706189abe3be4b6a6d4d10f8cfe53233437

New sysinfo segment relying on templates. https://ohmyposh.dev/docs/sysinfo
