### ISSUE TITLE
Java segment not working correctly with JAVA_HOME

### ISSUE THREAD

**Issue by carlosrpg** [JanDeDobbeleer/oh-my-posh#1202]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

Java segment not working correctly when using JAVA_HOME and Zulu SDK
![image](https://user-images.githubusercontent.com/759671/141132724-9583be8e-758a-4d13-9927-99c1cdb6f70c.png)

### Version

6.0.0

### Theme

[myPosh.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7513500/myPosh.zip)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@carlosrpg let me check if we can extend the regex (but oh my lord what a terribly long and unstructured output).

**Comment by JanDeDobbeleer** [comment]
@carlosrpg can you copy paste that text here so I can add a test easily?

**Comment by carlosrpg** [comment]
err parsing info from C:\Program Files\Zulu\zulu-11/bin/java with OpenJDK 64-Bit Server VM (11.0.13+8-LTS) for windows-amd64 JRE (Zulu11.52+13-CA) (11.0.13+8-LTS), built on Oct  7 2021 16:00:23 by "zulu_re" with MS VC++ 15.9 (VS2017)

**Comment by carlosrpg** [comment]
I dont know what it is trying to parse, but the java --version give me this


openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

**Comment by JanDeDobbeleer** [comment]
@carlosrpg it runs `java -Xinternalversion`
