### ISSUE TITLE
Path doesn't change on bash in iterm2

### ISSUE THREAD

**Issue by gregbair** [JanDeDobbeleer/oh-my-posh#1207]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Using any theme, the path segment doesn't update the current path when changing directories. Only updates when opening a new terminal.

Using bash 5.1.8(1)-release from homebrew.

### Version

6.2.0

### Theme

craver and M365Princess

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

**Comment by JanDeDobbeleer** [comment]
@gregbair I can't reproduce this:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/2492783/141179302-e703d9f0-71b2-49d7-91af-2e9516feba2a.png">

**Comment by gregbair** [comment]
Hmm, this is what I'm seeing - Any ideas to troubleshoot?

![image](https://user-images.githubusercontent.com/234524/141179652-5fd32d07-9ec6-4148-8ed3-d69f7328bf4b.png)

**Comment by JanDeDobbeleer** [comment]
@gregbair we cache the directory, but do not persist it cross prompt runs. TBH I have no idea other than Go is having a bug on some cases on macOS (it uses a sys call to get that context). We could work around it by feeding it directly to the CLI call, but we haven't seen this before TBH.

**Comment by JanDeDobbeleer** [comment]
@gregbair check when the next version is available, that one should cache the working directory. If it fixes your issue, we know this is a bug with the golang stack somewhere.

**Comment by JanDeDobbeleer** [comment]
@gregbair if you installed via homebrew, it should be there. Reload the shell for the init script to reload as well.

**Comment by gregbair** [comment]
Ok, I installed 6.2.3 via homebrew, and the same issue still exists. :(

**Comment by gregbair** [comment]
I'll note that I've also got OMP in Powershell on the same machine, and it does not have this issue.

**Comment by gregbair** [comment]
Oh, wait, it's bigger than that. Nothing updates on the prompt. The time doesn't either.

**Comment by gregbair** [comment]
Oh, wow, I'm so sorry. I must've done something wrong on my end. I went through the installation instructions again, and it works now.

I'm sorry for wasting your time and resources on this.

**Comment by JanDeDobbeleer** [comment]
@gregbair you did not waste my time and I really appreciate the donation 🙏🏻
