### ISSUE TITLE
Posh-Git segment color doesn't work

### ISSUE THREAD

**Issue by rmccampbell** [JanDeDobbeleer/oh-my-posh#1213]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The poshgit segment doesn't properly show the background or foreground colors. It shows the background color to the left and right of the git status display but the display itself is always a black background and fixed colors.
Segment configuration:
```
{
  "type": "poshgit",
  "style": "powerline",
  "background": "#00ff00",
  "foreground": "#000001",
  "powerline_symbol": "\ue0b0"
}
```
Result:
![ohmyposh_screenshot](https://user-images.githubusercontent.com/8339155/141424603-0b81977f-2e16-4aae-8326-564cdc4b55b2.png)

### Version

1.0.0 beta3

### Theme

Modified Paradox theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
My guess is that the string coming from posh-git is having its own ANSI color codes (or resets). I'll check if there's a setting or something we can do.

**Comment by JanDeDobbeleer** [comment]
@rmccampbell what happens when you set `$GitPromptSettings.AnsiConsole = $false` before importing oh-my-posh and after importing posh-git?

**Comment by rmccampbell** [comment]
Strange, it moves the posh-git display before the prompt with no background color.
![image](https://user-images.githubusercontent.com/8339155/141600080-37e72ffc-2d68-4a57-bc83-c08f18ce11fd.png)

**Comment by rmccampbell** [comment]
Oops, just realized I wasn't using the latest version of posh-git. Updated it and it works as expected now. So no bug here
