### ISSUE TITLE
Not compatible with pwsh 7.2

### ISSUE THREAD

**Issue by bravoeguizabal** [JanDeDobbeleer/oh-my-posh#1216]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

This is what it looks like when using powershell 7.1.5
![pwsh7 1 5](https://user-images.githubusercontent.com/33873082/141481523-c8d08831-f84e-462d-9eb2-524634eeec27.png)
Then right after upgrading to powershell 7.2.0 the glyphs seem to be working but the colors are not there anymore.
![pwsh7 2 0](https://user-images.githubusercontent.com/33873082/141481526-408853e9-d96c-4ce0-a823-aa679235d1f3.png)
Any ideas what might have happened?

Btw, awesome work putting together this package @JanDeDobbeleer!

### Version

6.2.3

### Theme

paradox

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@bravoeguizabal that's going to be something else than 7.2 (or oh-my-posh). We also just received a neat screenshot from another user on [7.2.0](https://github.com/JanDeDobbeleer/oh-my-posh/issues/737#issuecomment-967185958) and here's my config (both on macOS and Windows):

<img width="508" alt="image" src="https://user-images.githubusercontent.com/2492783/141489846-55d4788d-f6b7-4d63-b9db-1c67b49cd285.png">

<img width="429" alt="image" src="https://user-images.githubusercontent.com/2492783/141490169-df730928-7dc7-4772-a621-e66cdd3b43f9.png">

Can you share your `$PROFILE` and config (if it's default, pls ignore)?

**Comment by bravoeguizabal** [comment]
This is my profile:

Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme paradox

config is just the default

I upgraded to 6.2.5 but am getting the same result. I tried to check if something in my environment is interfering with oh-my-posh but can't thing of anything.

**Comment by JanDeDobbeleer** [comment]
Seems like somehow ANSI isn't supported in your shell. I'll try to give a sample that should work.

**Comment by JanDeDobbeleer** [comment]
@bravoeguizabal [this](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2) is interesting. Can you have a look at what `$PSStyle.OutputRendering` says? That should be `ANSI`.

**Comment by bravoeguizabal** [comment]
Currently that field is set to:
OutputRendering          : Host

**Comment by JanDeDobbeleer** [comment]
@bravoeguizabal try setting that to ANSI and maybe also have a look at any of [these](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2#disabling-ansi-output).

**Comment by bravoeguizabal** [comment]
Jan, thanks for the links you shared I got the clue from there.
It happens that I was setting TERM to a dumb value in my environment therefore the lack of color. I removed that from my environment and now I have my posh shell working perfectly. Sorry about that!
Looks like $Env;TERM doesn't have any effect on previous versions of pwsh but the latest.
