### ISSUE TITLE
Displays last installed Python, not latest version

### ISSUE THREAD

**Issue by YSCohen** [JanDeDobbeleer/oh-my-posh#1227]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have Python 3.10.0 and 3.9.8 I installed 3.9.8 recently, and now it shows that in the python version bubble instead of 3.10.0

### Version

6.1.1

### Theme

custom theme based on night-owl (it won't let me attach the omp.json)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
Installed Pythons found by C:\WINDOWS\py.exe Launcher for Windows
 -3.10-64 *
 -3.9-64
```

**Comment by JanDeDobbeleer** [comment]
@HashemLovesYou that logic follows the path rather than installed time, moving that Python executable up in the list will also use it. We have no idea what you installed first, nor last. If you want to only use a specific version, I advice to set up a virtual env.
