### ISSUE TITLE
Encoding issue when user has diacritic characters in its profile name

### ISSUE THREAD

**Issue by FMauroy** [JanDeDobbeleer/oh-my-posh#1242]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi,

great tool, love it :)

I noticed a little issue right after installing the tool, as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/1107417/142166864-cc2139e2-7b20-4f53-8e28-4a3446e97fbf.png)

I fixed it by putting the short 8.3 name of my profile directly in the "Microsoft.PowerShell_profile.ps1" script, like this:
C:/Users/FRDRIC~1/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe --init --shell pwsh ....

Don't know if this encoding issue is in your tool, the Windows Terminal or Windows 10 in general. Looks like Unicode is still not properly handled everywhere after all these years ;-)

I looked for "oh-my-posh" in the registry and all paths are properly displayed (with accents).

Cheers
fred

**Comment by JanDeDobbeleer** [comment]
@FMauroy that's a UTF-8 bug (PowerShell doesn't default to that yet).

Add this line to the TOP of your `$PROFILE`:

```powershell
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

**Comment by FMauroy** [comment]
It works, thank you very much!
