### ISSUE TITLE
Allow swapping Node package manager icon and text position

### ISSUE THREAD

**Issue by puttehi** [JanDeDobbeleer/oh-my-posh#1253]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Add new values to `properties.display_packager_manager`: `left`, `right` to allow swapping icon and version text order

**Comment by JanDeDobbeleer** [comment]
@puttehi we'll be adding templates to all the language segments soon which will resolve this 👌🏻

**Comment by puttehi** [comment]
That's just awesome ❤️ 
Somewhat off-topic: I imagine that will also allow me to color my `terraform` foreground by `.workspaceName` ?

**Comment by JanDeDobbeleer** [comment]
@puttehi yes!

**Comment by lnu** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/pull/1258
