### ISSUE TITLE
Posh-Git autocomplete broken when importing oh-my-posh3 in $profile

### ISSUE THREAD

**Issue by EmKayUltra** [JanDeDobbeleer/oh-my-posh#126]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

With empty profile:
![empty-profile](https://user-images.githubusercontent.com/3580562/98314700-8f0ca400-1fa4-11eb-9c63-3e0c8ab3a4f5.gif)

With imports in profile:
![with-profile](https://user-images.githubusercontent.com/3580562/98314706-92079480-1fa4-11eb-8001-8993f58ed1eb.gif)

posh-git's contextual autocomplete is not working if I have these three lines in my $profile:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt powerlevel10k_lean
```

Interestingly, if I remove those and import them at the commandline in that same order, everything works just fine.

### Environment

- Oh my Posh version: 3.28.0
- Theme: powerlevel10k_lean (also tried agnoster, same problem)
- Operating System: Windows 10
- Shell: Powershell 7.0.3
- Terminal: Windows Terminal

### Steps to Reproduce

1. Add these lines to your $profile
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt powerlevel10k_lean
```
2. navigate to directory containing git repo `cd C:\path\to\git\repo`
3. make a change to a file (or create a new one) to create an unstaged change scenario.  for this, calling this file "dir/to/filetoadd.txt"
4. type `git add ` (include a space after "add") and hit {TAB} 

**Expected behavior:** Terminal autocompletes to: `git add dir/to/filetoadd.txt`

**Actual behavior:** Terminal autocompletes to something else, like `git add .\.git\`

**Comment by lnu** [comment]
Because oh-my-posh replace the git prompt, the `$gitStatus` global variable is not set in git-posh.
in this code(`posh-git.psm1`):
```
# If there is no prompt function or the prompt function is the default, replace the current prompt function definition
if ($ForcePoshGitPrompt -or !$currentPromptDef -or ($currentPromptDef -eq $defaultPromptDef)) {
    # Set the posh-git prompt as the default prompt
    Set-Item Function:\prompt -Value $GitPromptScriptBlock
}
```
in `git-prompt.ps1`:
```
$PoshGitVcsPrompt = {
    try {
        $Global:GitStatus = Get-GitStatus
        Write-GitStatus $GitStatus
    }
```
This code is never called if oh-my-posh is defined as current prompt.

The completion relies on `$gitStatus` it's only set if the prompt is not already set.

It means we can benefit of parameters completion but not git completion like branches, files, ...

**Comment by EmKayUltra** [comment]
@lnu that makes sense.  But why does it work when importing modules in the commandline?

**Comment by lnu** [comment]
It "seems" to work but in fact you keep the initial $gitStatus variable.
I tried locally this scenario: I type git add then tab with some changes, then stash everything. If I do type again git add then tab, the auto completion still shows my stashe files(should be empty).

**Comment by JanDeDobbeleer** [comment]
We could set the status in the Powershell module of Oh my Posh after rendering the prompt, no? If the function is available that is.

**Comment by lnu** [comment]
Something like that yes 👍 
It's available(Get-GitStatus)

**Comment by JanDeDobbeleer** [comment]
@lnu @EmKayUltra I'm in a bit of a hurry, can either of you adjust your local copy of the module and check if this change resolves the issue (without adding latency)?

**Comment by lnu** [comment]
see https://github.com/JanDeDobbeleer/oh-my-posh3/pull/130#discussion_r519147762

**Comment by MendelMonteiro** [comment]
This seems to have regressed in (at least) versions 5.12.1 and 5.16.2.

**Comment by lnu** [comment]
Strange, I just tried and autocomplete is still working with the latest version. What do you experience? same behaviour?

**Comment by MendelMonteiro** [comment]
Same behaviour - with Posh-Git 1.0.0 - installed via `Install-Module`

**Comment by lnu** [comment]
can you check the result of `$env:POSH_GIT_ENABLED -eq $true -and (Get-Module -Name "posh-git")` and `Get-GitStatus`?
https://github.com/JanDeDobbeleer/oh-my-posh/blob/27d324441be2c35fc905557ece4bdfb1f516273d/src/init/omp.ps1#L48

**Comment by JanDeDobbeleer** [comment]
@MendelMonteiro what does `$env:POSH_GIT_ENABLED` say?

**Comment by MendelMonteiro** [comment]
Ok, sorry for wasting your time.  I hadn't seen [this page](https://ohmyposh.dev/docs/poshgit) in the docs and as it was not mentioned in this issue I didn't think that I had missed any steps.

After setting `$env:POSH_GIT_ENABLED = $true` in my `$PROFILE` the posh-git completion works as expected.

**Comment by biel-correa** [comment]
just to note here the problem that I was having since someone might have it as well.

to use posh-git first you need to install it with `Install-Module posh-git` remember to run as admin. After that's done you can add `Import-Module posh-git` to the top of youre $PROFILE, it will look like this:

```ps1
Import-Module posh-git

$env:POSH_GIT_ENABLED=$true
oh-my-posh init pwsh | Invoke-Expression
```

**Comment by lanierhall** [comment]
I'm having the same issue.
I am using Windows Server 2022 Datacenter so I can't use the Windows Store.
I got an error initializing powershell core with the message to consult this document: https://ohmyposh.dev/docs/migrating
I've tried a lot of different things so I'm starting to feel cursed...I'm almost there, I've got some font problems and this problem:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/2318456/4afdd818-aeab-4a0b-bd1b-9b296abc0cbf)

*Hit Tab*

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/2318456/c9864464-55b7-4100-a59d-06e0eb90b72e)

And my profile:
Import-Module -Name Terminal-Icons
Import-Module posh-git
Import-Module Get-ChildItemColor
$env:POSH_GIT_ENABLED = $true
oh-my-posh --init --shell pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression

**Comment by JanDeDobbeleer** [comment]
@lanierhall did you upgrade posh-git as well? Because they're the ones offering autocomplete.

**Comment by lanierhall** [comment]
Yes, I have v1.1.0 installed

**Comment by JanDeDobbeleer** [comment]
@lanierhall I would ask over at posh-git as we don't really do anything there. Enabling posh-git from oh-my-posh allows posh-git to have status completion, but is simple command completion which is completely on their end.

**Comment by ferrata** [comment]
> Yes, I have v1.1.0 installed

@lanierhall It started working for me after I added this to my `$PROFILE` file after `oh-my-posh --init`:

```ps
Import-Module posh-git
```

So my `$PROFILE` is:

```ps
oh-my-posh init pwsh | Invoke-Expression
Import-Module posh-git
```
