### ISSUE TITLE
OMP is incredibly slow in WSL2 due to filesystem boundary

### ISSUE THREAD

**Issue by jonaskuske** [JanDeDobbeleer/oh-my-posh#1268]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

On both my laptop and my desktop, OMP takes multiple seconds to show the prompt with the default way OMP is installed into WSL2, where the Linux binary is located in the Windows file system:

```shell
> which oh-my-posh-wsl
> /mnt/c/Users/Username/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh-wsl
```

On my Surface Book 2, it is only usable when I put the device in high-performance mode, anything less and you need to wait 3-5 seconds *after each command* until the prompt is shown again. However, this delay disappears almost entirely if I move the binary over to the Linux filesystem:

```shell
> cp $(which oh-my-posh-wsl) ~
# now call with ~/oh-my-posh-wsl --init ...
```

Now the prompt appears virtually instant even with my device in energy-saver mode.

So I'd recommend to change the install strategy so that the OMP binary resides within the Linux VM. I'm not sure about what's the best way forward in this case, though. Simply recommend WSL users to install via `brew`? Copy the binary manually (after every update...)? Add a helper that copies it for you into your default distro?

**Comment by lnu** [comment]
It would be nice to have a single windows install for both windows and all its wsl instances but I see lots of questions:

- do we update all wsl or only the default?
- is the instance started?
- is the instance v1 or v2?
- do we have the permission to write directly in /usr/local/bin? (not sure but I think not)
- what do we do when the linux executable cannot be updated(instance not started, ...)? do we rollback also the windows one to avoid discrepancy?

if you are a wsl user, you should probably stick to the [linux install](https://ohmyposh.dev/docs/linux) which is really simple.

I tested on my laptop and it takes +- 600ms to render the prompt when calling the executable installed with winget.

Curious to see what @JanDeDobbeleer ideas on this one.

**Comment by lnu** [comment]
Tested a bit more and we can copy by doing this:  
`wsl -e sudo cp "$(wsl wslpath -u ($env:userprofile).replace('\','\\'))/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh-wsl" /usr/local/bin/oh-my-posh-wsl && wsl -e sudo chmod +x  /usr/local/bin/oh-my-posh-wsl` which seems to copy to the default wsl instance. But by default it will call the windows one, so you have to remove it from the winget folder.
But it asks you twice for your password before effectively copying the file.

**Comment by JanDeDobbeleer** [comment]
@lnu I'm in doubt if WE should be fixing that. In that case it makes more sense to have this somehow be Winget functionality (we might be the only use-case here though), or we fallback to separating both but that ends up being annoying once again. I agree the current solution is working against us, I was hoping this would get resolved by WSL2, but that doesn't seem to be the case just yet.

Long story short, we're better off for now to split both worlds, we'll end up in maintenance hell otherwise.

**Comment by lnu** [comment]
@JanDeDobbeleer  we should remove the wsl version from the winget install and from the doc, to avoid that kind of issue.  
Can we display a message at the end of the winget install? at least people won't forget to update even it's a manual step

**Comment by JanDeDobbeleer** [comment]
@lnu I don't think we can, but I'll check. Working on oh-my-posh ATM so I'll keep you posted.

**Comment by JanDeDobbeleer** [comment]
Removed for the time bing and revert to manual install on Linux.

**Comment by jonaskuske** [comment]
@lnu We could skip the first password prompt by copying to the home directory (and potentially updating PATH), and the second one isn't necessary because the binary is already executable.

But yeah I agree that resorting to Linux install methods works. Maybe remove the Linux binary from the winget install, or even better update it to log something like:

```shell
> oh-my-posh: WSL installs via winget are not supported anymore.
Please install Oh My Posh using Linux install methods, then use `oh-my-posh` instead of `oh-my-posh-wsl` in your terminal setup.
You can find installation instructions here: https://ohmyposh.dev/docs/linux
```
