### ISSUE TITLE
Move custom themes to new folder version on update

### ISSUE THREAD

**Issue by MontejoJorge** [JanDeDobbeleer/oh-my-posh#1271]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

When upgrading with `Update-Module -Name oh-my-posh` the custom themes stay in the folder of the old version, I propose to move them to the new folder created when upgrading the version.

**Comment by JanDeDobbeleer** [comment]
@MontejoJorge the issue is that you add custom themes to the module version folder, while they're not supposed to be there. You should move any custom theme to a location that's not impacted by updating like your home folder (just like other config settings).
