### ISSUE TITLE
wrapping strange with nushell

### ISSUE THREAD

**Issue by fdncred** [JanDeDobbeleer/oh-my-posh#128]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]
Text truncates and wraps in an odd way with nushell. I'm not sure what's going on. 
![image](https://user-images.githubusercontent.com/343840/98391931-ec443c00-201c-11eb-8011-5e80657c7dfe.png)

The strange thing here is the cursor is as far right as possible and that point is between the o and r in the word selector.
If I hit enter with the cursor there it executes the entire line just fine.
If I hit backspace it starts deleting characters from the end of the line where it says first 5 but the cursor moves from where it's at between the o and r by one space left.
### Environment
Windows
- Oh my Posh version: 3.26.4 i think but i'm not sure how to tell
- Theme: Custom
- Operating System: Windows
- Shell: Nushell
- Terminal: Windows Terminal Preview

### Steps to Reproduce

1. using it regularly. sometimes i maximize the window. sometimes I restore the window but it happens whenver there is line wrapping

**Comment by JanDeDobbeleer** [comment]
This is a nu shell issue. Other shells have this behavior as well when the ANSI sequences aren't escaped properly (see [here](https://github.com/JanDeDobbeleer/oh-my-posh3/blob/main/renderer.go#L44)). Now, I tested this on MacOS myself an there it seems to work fine so this bug might be Windows only for nu.

**Comment by fdncred** [comment]
I'm trying to follow what you're saying. Do you mean nushell is not printing ANSI sequences correctly? Is there a way to see what OMP sees as the escape sequences?

I assume it's using the default section in your link since it's not one of the other shells. i'm not really sure how to troubleshoot this.

**Comment by JanDeDobbeleer** [comment]
The ANSI characters are printed correctly, what happens on other shells is that the prompt length isn't calculated correctly when they aren't escaped in the prompt function, causing the cursor to do all kind of wonky stuff. Which is identical to what is happening here.

**Comment by fdncred** [comment]
Ugh, this must be happening in `rustyline` since that's what nushell uses for it's prompt. I'm not going down that path again. I'll just rollback. :(

**Comment by JanDeDobbeleer** [comment]
@fdncred I do see [this](https://github.com/nushell/nushell/blob/4e17292a12a7913c8cd308e81af4f9c9fcb3f4fc/crates/nu-cli/src/cli.rs#L457). And [also](https://github.com/luser/strip-ansi-escapes/issues/1).

**Comment by fdncred** [comment]
@JanDeDobbeleer I played with the nushell code, commented it out and just passed the normal colored_prompt in and couldn't get it to work right. Maybe we just need to remove the ansi escape codes for colors and not all of them. Maybe that's what you're saying. I'll try to dig for a regex that can do that to see what happens.

Now that I think about it, I have no idea if what I suggested will make any difference since nushell is using an external prompt.

**Comment by fdncred** [comment]
So, for funsies I removed the color ansi escape sequences from the prompt to see if that made any difference.

P1 is before. P2 is after.
```
P1="\u{1b}[38;2;229;192;123m11/09/2020 10:33:42.888 AM\u{1b}[0m\u{1b}[38;2;255;255;255m\n\u{1b}[0m\u{1b}[38;2;52;101;164;49m\u{1b}[7m\u{e0b0}\u{1b}[m\u{1b}[0m\u{1b}[48;2;52;101;164m\u{1b}[38;2;255;255;255m ~\\source\\repos\\forks\\nushell \u{1b}[0m\u{1b}[48;2;149;255;164m\u{1b}[38;2;52;101;164m\u{e0b0}\u{1b}[0m\u{1b}[48;2;149;255;164m\u{1b}[38;2;0;0;0m \u{e709}\u{e0a0}main ≣\u{1b}[0m\u{1b}[48;2;149;255;164m\u{1b}[38;2;0;0;0m\u{f044} ~1\u{1b}[0m\u{1b}[48;2;149;255;164m\u{1b}[38;2;0;0;0m \u{f692} 1 \u{1b}[0m\u{1b}[48;2;87;154;0m\u{1b}[38;2;149;255;164m\u{e0b0}\u{1b}[0m\u{1b}[48;2;87;154;0m\u{1b}[38;2;0;0;0m ﲵ nu \u{1b}[0m\u{1b}[38;2;87;154;0m\u{e0b0}\u{1b}[0m\u{1b}[K\u{1b}[0m \u{1b}[K \u{1b}]2; C/U/d/s/r/f/nushell \u{7}"

P2=" 11/09/2020 10:33:42.888 AM  \n   \u{e0b0}     ~\\source\\repos\\forks\\nushell    \u{e0b0}    \u{e709}\u{e0a0}main ≣   \u{f044} ~1    \u{f692} 1    \u{e0b0}    ﲵ nu   \u{e0b0} \u{1b}[K  \u{1b}[K \u{1b}]2; C/U/d/s/r/f/nushell \u{7}"
```

code
```rust
        let re = Regex::new(r"\x1b\[[0-9;]*m").expect("error removing color");
        let prompt_no_color = re.replace_all(&colored_prompt, " ").to_string();
```
It apparently doesn't help because when I type the lines move up the screen like it's erasing whatever is in my window a line at a time as I type a character at a time. also, the cursor is moved way over to the right. so, it's clear, that i have no idea what's going on or how to fix it. LOL.

**Comment by JanDeDobbeleer** [comment]
The exclusion of possible causes is also a sign of progress 😉

**Comment by JanDeDobbeleer** [comment]
@fdncred I noticed nu lso can't handle a right aligned prompt. I get the same weird behaviour. This would imply it's an issue with nu.

**Comment by fdncred** [comment]
@JanDeDobbeleer I'm trying to reproduce the error in nushell version 0.31.1 and I'm not having much luck. Maybe i'll run with omp v3.150.2 for a few days and see what happens.

**Comment by fdncred** [comment]
looks fixed to me. i guess we'll wait and see if anyone else complains. thanks!
