### ISSUE TITLE
Unwanted thin vertical line 

### ISSUE THREAD

**Issue by rucksman** [JanDeDobbeleer/oh-my-posh#1281]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

There are small vertical lines which I want to get rid off. Using MobaXterm on a Ubuntu server in a bash shell.
![image](https://user-images.githubusercontent.com/24551016/142842018-25cea5c3-bc16-472c-bef5-2991fd0dd0e0.png)

### Theme

Unmodified jandedobbeleer.omp.json

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```shell
Here are the timings of segments in your prompt:

ConsoleTitle(true)   -   0 ms - uni in ~
session(true)        -   0 ms -   myuser 
path(true)           -   0 ms -    ~ 
git(false)           -   0 ms -
node(false)          -   0 ms -
go(false)            -   0 ms -
julia(false)         -   0 ms -
python(false)        -   0 ms -
ruby(false)          -   0 ms -
azfunc(false)        -   0 ms -
aws(false)           -   0 ms -
root(false)          -   0 ms -
executiontime(true)  -   0 ms -  羽0ms⠀
exit(true)           -   0 ms -   
shell(true)          -   0 ms -   uni 
ytm(false)           -   0 ms -
battery(false)       -   0 ms -
time(true)           -   0 ms -  11:01:56 
```

**Comment by JanDeDobbeleer** [comment]
@rucksman that's a terminal settings issue, not an issue with oh-my-posh. Wish I could help, but I have no idea what's causing that on your end. Best is to check the font and rendering settings.
