### ISSUE TITLE
temp bug after homebrew update

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh#1287]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

after updating via homebrew on ubuntu 18.04 wsl i got the following bug:

> ==> Summary
> 🍺  /home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/6.11.1: 72 files, 18.9MB, built in 11 seconds
> Removing: /home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/6.2.2... (71 files, 18.9MB)
> Removing: /home/fheberl/.cache/Homebrew/oh-my-posh--6.2.2.tar.gz... (3.3MB)
> /home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/6.2.2/bin/oh-my-posh: command not found
> - (line 21):
>     /home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/6.2.2/bin/oh-my-posh --config $posh_theme --error $omp_status_cache --execution-time $omp_duration --stack-count $omp_stack_count
>     ^
> in function 'fish_prompt'
> in command substitution

fish config snippet:

`oh-my-posh --init --shell fish --config $HOME/.oh-my-posh/themes/fish.json | source`

i do not have a fish_prompt function defined.
when i reopen the terminal oh-my-posh is working normal

### Theme

does not matter

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

fish

### Log output

```shell
does not matter?
```

**Comment by JanDeDobbeleer** [comment]
@floh96 on reload that disappeared, right? So I take it you didn't see this again? My hunch is that it has to do with fish trying to render the prompt while homebrew is replacing the executable (which other shells don't do). I'm afraid we can't avoid that from happening at times.

**Comment by floh96** [comment]
@JanDeDobbeleer this seems to be a regression in terms of the oh-my-posh init script/setup.
i changed the fish config back to the old setup script:
```
    function fish_prompt
      eval oh-my-posh -config $HOME/.oh-my-posh/themes/fish.json -error $status
    end
```
then i updated oh-my-posh now I'm not getting the error.

**Comment by JanDeDobbeleer** [comment]
@floh96 I'll check. I was unaware that was recently adjusted.

**Comment by floh96** [comment]
it could have been changed quite some time ago but i did not update my fish config until last month

**Comment by jonaskuske** [comment]
Noticed the same issue on `zsh`, had to change my update script to

```shell
brew update && brew upgrade && exec zsh
```

so the shell reloads and uses the path to the correct (updated) oh-my-posh binary in the end.

**Comment by JanDeDobbeleer** [comment]
@jonaskuske that's weird as I'm on zsh too and never noticed this.

**Comment by floh96** [comment]
@JanDeDobbeleer the issue occurs only on linux

**Comment by JanDeDobbeleer** [comment]
@floh96 thx, I'll have a look tomorrow 🙏🏻

**Comment by oalders** [comment]
> brew update && brew upgrade && exec zsh

I found, as of about last week ,that after an upgrade via homebrew the execution time is always at `0ms`. An `exec bash` gets the timing working again. Glad I found this issue.
