### ISSUE TITLE
Wifi segment not showing on Windows 11

### ISSUE THREAD

**Issue by NileshGule** [JanDeDobbeleer/oh-my-posh#1312]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have added the Wifi segment to the json file.
It doe not show any information on the prompt.

Please refer to the wifi segment configuration
https://github.com/NileshGule/windows-dev-playbook/blob/master/profiles/oh-my-posh.omp.json

![image](https://user-images.githubusercontent.com/1298374/143477475-aaff6ba8-fd3e-4c05-b3c0-479580c8d8f1.png)

### Theme

https://github.com/NileshGule/windows-dev-playbook/blob/master/profiles/oh-my-posh.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
   Write-PoshDebug

Here are the timings of segments in your prompt:

ConsoleTitle(true)   -   1 ms - root :: pwsh :: windows-dev-playbook
shell(true)          -   0 ms -   pwsh 
battery(true)        -   4 ms -   26  
time(true)           -  22 ms -   00:38  
text(true)           -   0 ms - ▓
kubectl(true)        - 756 ms -  ﴱ azure-azconf-live-demo-cluster
az(true)             - 466 ms -  ﴃ Microsoft Azure Sponsorship 
root(true)           -   0 ms -   
os(true)             -   0 ms -  
path(true)           -   0 ms -   windows-dev-playbook 
git(true)            - 108 ms -   master ≡
node(false)          -   0 ms -
go(false)            -   0 ms -
julia(false)         -   0 ms -
python(false)        -   0 ms -
ruby(false)          -   0 ms -
azfunc(false)        -   0 ms -
dotnet(false)        -   0 ms -
aws(false)           -   0 ms -
executiontime(true)  -   0 ms -  羽9.001s
exit(true)           -   0 ms -  ﰌ1337 
text(true)           -   0 ms -  

-----------------------------------------------------------------
oh-my-posh --debug --shell uni --config="$POSH_THEME"

Here are the timings of segments in your prompt:

ConsoleTitle(true) -   0 ms -
session(true)  -   0 ms -  niles@DESKTOP-HFOT07V 
path(true)     -   0 ms -   windows-dev-playbook 
git(true)      -  15 ms -  master 
battery(true)  -   3 ms -  29 
node(false)    -   0 ms -
shell(true)    -   0 ms -  ﲵ uni 
root(true)     -   0 ms -   
text(true)     -   0 ms -  NO CONFIG 
exit(true)     -   0 ms -   
```

**Comment by JanDeDobbeleer** [comment]
@NileshGule I think you might need to update oh-my-posh first

Additionally, the template line needs to be a single line.

**Comment by NileshGule** [comment]
> @NileshGule I think you might need to update oh-my-posh first

@JanDeDobbeleer I have already update the oh-my-posh
![image](https://user-images.githubusercontent.com/1298374/143507960-281f3a5b-9f27-443e-9bb2-865ab370c71a.png)

I saw the same issue is happening with the sysinfo segment as well.
Nothing is getting rendered on the prompt

**Comment by JanDeDobbeleer** [comment]
Did you restart your shell? Because the output from `Write-PoshDebug` is not the latest version.

**Comment by NileshGule** [comment]
hi @JanDeDobbeleer 
Restarting the shell did the trick

Now I am able to see wifi and the sysinfo segments

Thanks
![image](https://user-images.githubusercontent.com/1298374/143539073-76d37e00-67c1-4cdd-81b3-566cd6fc0392.png)
