### ISSUE TITLE
dotnet segment should not be shown in VC++ projects

### ISSUE THREAD

**Issue by ffes** [JanDeDobbeleer/oh-my-posh#1314]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Right now the dotnet segment is shown when a `*.sln` file is found in the directory. But a Visual Studio C++ project often has a `*.sln` file as well, but is not likely to be a dotnet project. A `*.vcxproj` is used for C/C++ projects.

So could the extensions checked for be configurable?

For my dotnet projects only `*.cs` and `*.csproj` are relevant to determine if it is a dotnet project, because that is all I use. So I would like to set just those extensions and especially exclude `*.sln`.

Something like this:

```json
{
  "type": "dotnet",
  "properties": {
    "prefix": " \uE77F ",
    "extensions": [ "*.cs", "*.csproj" ]
  }
}
```

Note that there is nothing wrong with the current default extensions. They make sense to support a broad audience.

**Comment by lnu** [comment]
we can add the `extensions` but it somewhat defeats the purpose of specific segments. We could have only one language segment configurable as needed and no more 8-9 different specific ones.

**Comment by JanDeDobbeleer** [comment]
@lnu I was indeed thinking in that direction too. For this use case though it might make more sense to use `exclude-folders` (or remove the segment if you don't have a use case at all.

**Comment by lnu** [comment]
@JanDeDobbeleer  there's a refactoring of the language segment on your side? 

After all doing this enough to open the extensions(and I used composition for the version): https://github.com/JanDeDobbeleer/oh-my-posh/pull/1318/files  
It really depends on the direction you want for the segment

**Comment by ffes** [comment]
I just tried v6.16.0. I still had the json as I suggested above in my settings and it just worked.

Thanks for the very quick reaction and solution!

**Comment by JanDeDobbeleer** [comment]
> it just worked

@lnu that one's for you my friend 👏🏻
