### ISSUE TITLE
minimal themes

### ISSUE THREAD

**Issue by Arnab-Developer** [JanDeDobbeleer/oh-my-posh#1319]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In the [themes document page](https://ohmyposh.dev/docs/themes) I saw below line:

> Themes with `minimal` in their names do not require a Nerd Font.

![image](https://user-images.githubusercontent.com/3396447/143553185-578e323b-adff-446a-acf1-b6b8b2aace4d.png)

But I found that not all themes which do not need Nerd Font has `minimal` in their name. For example `robbyrussel` don't need Nerd Font but don't have `minimal` in its name.

### Theme

Themes which don't need Nerd Font.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
https://ohmyposh.dev/docs/themes
```

**Comment by JanDeDobbeleer** [comment]
@Arnab-Developer not necessarily, that might work but not for every segment. The minimal themes contain all overrides to compatible glyphs.

**Comment by Arnab-Developer** [comment]
Thanks
