### ISSUE TITLE
Problems installing in Linux (WSL2)

### ISSUE THREAD

**Issue by xela-nosretap** [JanDeDobbeleer/oh-my-posh#1325]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm following the instructions [here](https://ohmyposh.dev/docs/linux#installation), I ran the install homebrew command 
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
I then tried to run `brew tap jandedobbeleer/oh-my-posh` but I was getting a `brew command not found` error, I then looked around the homebrew site and [found](https://docs.brew.sh/Homebrew-on-Linux) that I needed to run the following commands to get it working
```
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.bash_profile
echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.profile
```
This allowed me to run `brew install hello`

I then ran `brew tap jandedobbeleer/oh-my-posh` which worked but when I try and run `brew install oh-my-posh`

```
alex@alex-desktop:~$ brew install oh-my-posh
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.17.2
Already downloaded: /home/alex/.cache/Homebrew/downloads/d3e60ec09348a7c69ac49620d5755b91ad1d018b49be5662b4e577ccc645582a--go-1.17.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:aa5fbcd2c12be4e08d5edbcbb5eb8a8859c48ecd036c6
Already downloaded: /home/alex/.cache/Homebrew/downloads/cc2eab6801b9e12d240699c583ae8776b435b65b0a71a9432ef3bc532386fa3b--go--1.17.2.x86_64_linux.bottle.tar.gz
==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v6.16.0.tar.gz
Already downloaded: /home/alex/.cache/Homebrew/downloads/4b7f001acd2978f7e3b83a53d9ca5141b99254b7c1abeb3f2d5dc72eb217069b--oh-my-posh-6.16.0.tar.gz
==> Installing oh-my-posh from jandedobbeleer/oh-my-posh
Error: The following formula cannot be installed from bottle and must be
built from source.
  oh-my-posh
Install Clang or run `brew install gcc`.
```

I've tried running `brew install gcc` but I'm still getting the same error when trying to install.

### Theme

Non yet

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```shell
No log output
```

**Comment by JanDeDobbeleer** [comment]
@alexander-paterson I take it you can run `brew install hello`?

**Comment by xela-nosretap** [comment]
> 

Yeah, seemed to run and complete with no errors.

**Comment by JanDeDobbeleer** [comment]
@alexander-paterson the homebrew docs [clearly state](https://docs.brew.sh/Homebrew-on-Linux#requirements) those dependencies and what to do per platform.

**Comment by xela-nosretap** [comment]
Bugger. I stopped one line too early.

Thanks

**Comment by apsolut** [comment]
Win11: for me to work I had to run:
    `sudo apt-get update`
    `sudo apt-get install build-essential`

**Comment by VincentWasswa** [comment]
thanks @apsolut
