### ISSUE TITLE
Emoji breaks Python segment ?

### ISSUE THREAD

**Issue by ArnaudWald** [JanDeDobbeleer/oh-my-posh#1351]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am trying ot customize my prompt on Powershell, using Hyper.is terminal. I am adding emojis in segments to make it prettier. 

But when I try customizing the Python segment with a snake emoji, this happens :

![tempsnip](https://user-images.githubusercontent.com/16063422/144093078-fe46a291-d0bf-46f8-83e6-b536bbb1f37e.png)

I get a weird line break at the end of the right segment. 

--- 

When using the Nerd Font python icon, everything is fine : 

![tempsnip2](https://user-images.githubusercontent.com/16063422/144093169-25c45fbe-7be5-4814-8226-c3e695971d28.png)

How can I fix it ?

Edit : To elaborate, adding emojis in the other segments, like the folder, the battery and the clock do not trigger this behaviour.

### Theme

I'm using a modified version of iterm2, with emojis instead of Nerd Font icons basically.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
No error output
```

**Comment by JanDeDobbeleer** [comment]
@ArnaudWald that emoji spans more than one "space", you can use `horizontal_offset` to position the block correctly in that case. Powershell has no native right alignment.

**Comment by ArnaudWald** [comment]
Alright, I was able to make it work ! 👍 
Sorry for the bad labeling of the issue

**Comment by JanDeDobbeleer** [comment]
@ArnaudWald all fine, I don't think we have a question issue yet ;-)
