### ISSUE TITLE
Allow Spotify segment to display from Spotify window installed by PWA (browser)

### ISSUE THREAD

**Issue by latipun7** [JanDeDobbeleer/oh-my-posh#1354]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Spotify segment is already amazing, but I'd like to see that segment to show Spotify installed by PWA, more love of the Progressive Web Apps 💖

This is in Windows and Microsoft Edge:
![Microsoft Edge's PWA](https://i.imgur.com/1Aotyuu.png)

Thank you ✨

**Comment by JanDeDobbeleer** [comment]
@latipun7 this wasn't an easy one. As the actually app is Edge there's a difference between the Spotify process and the actual window. I had to completely refactor the way we fetch an app's window title (and it can still have side-effects).

**Comment by latipun7** [comment]
Yeah sorry, I understand, and I guess so. I guess it would be hard because the implementation might be different between browsers, and even with same browser, it would be different too between OS 🙇

**Comment by JanDeDobbeleer** [comment]
@latipun7 solved.

**Comment by latipun7** [comment]
oh... thank you very much~ 🎉
