### ISSUE TITLE
git segment string() is called twice 

### ISSUE THREAD

**Issue by lnu** [JanDeDobbeleer/oh-my-posh#136]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The string() function of the git segment is called twice when rendering. Since git is slow on windows, it could improve the performance.
It seems all segment are called twice when rendering, is it by design?

### Environment

- Oh my Posh version: 3.30.1
- Theme: any
- Operating System: Windows
- Shell: Powershell 7
- Terminal: Windows terminal

### Steps to Reproduce

1. Go to a git repo
2. Add a print to the console at the beginning of the `string()` function of `segme,t_git.go`
3. See the message twice:
![segment_git_twice](https://user-images.githubusercontent.com/1829553/98702981-53465580-237b-11eb-9dec-7b5ec2a52c34.gif)

**Expected behavior:**  Execute only once

**Actual behavior:** Executed twice

**Comment by JanDeDobbeleer** [comment]
That's definitely not by design. I'll check what/how.

**Comment by lnu** [comment]
in `renderBlockSegments`(`engine.go`), instead of reusing `stringValue`(set in `setStringValues`) `string()` is called again:
![image](https://user-images.githubusercontent.com/1829553/98705767-58f16a80-237e-11eb-9982-b6b560ffb83e.png)

**Comment by lnu** [comment]
I also put some timing and the git segment takes between 300 and 500 ms on my laptop(macbook pro 32gb under bootcamp).
![segment_git_perf](https://user-images.githubusercontent.com/1829553/98708452-76740380-2381-11eb-8521-5613f05f366f.gif)

**Comment by JanDeDobbeleer** [comment]
I just saw the same thing. That's pretty stupid and probably due to changing the code around a few times. Hang on.
