### ISSUE TITLE
Ho to use oh my posh on cmd?

### ISSUE THREAD

**Issue by ahmad-ghais** [JanDeDobbeleer/oh-my-posh#1372]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello! I was wondering if there's any way to enable all my posh outside PowerShell such as cmd, etc...

**Comment by JanDeDobbeleer** [comment]
@Ahmadghaith there is, please read the [docs](https://ohmyposh.dev/docs/windows#replace-your-existing-prompt).

**Comment by ahmad-ghais** [comment]
Okay, thanks! Not sure if it is right like this: **PATH=$env:POSH_PATH** but after it what should I do?

**Comment by JanDeDobbeleer** [comment]
@Ahmadghaith ah, no. You have ro edit the Windows PATH from settings and add the actual path(`echo $env:POSH_PATH`) to it. Probably reboot to be on the safe side and the you can call `oh-my-posh` from any shell.

**Comment by ahmad-ghais** [comment]
Ohh Okayy! Thank you so much! <3
