### ISSUE TITLE
Wrong parameter in Expand-Archive for Windows PowerShell 5.1

### ISSUE THREAD

**Issue by meCoding** [JanDeDobbeleer/oh-my-posh#1376]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
At C:\Users\XXXXX\Documents\WindowsPowerShell\Modules\oh-my-posh\6.23.0\oh-my-posh.psm1:87 char:27
+     $tmp | Expand-Archive -DestinationPath $destination -Force
+                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand

When oh-my-posh is updated in Windows PowerShell 5.1 above error happens. In PS 5.1 there is no such parameter as "-DestinationPath" in Expand-Archive. The parameter is "-OutputPath" in PS 5.1.

The update process works in PS 7. The parameter used is correct.

### Theme

-

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
-
```

**Comment by lnu** [comment]
I did the update on my side and had no issues.
![image](https://user-images.githubusercontent.com/1829553/144708573-fe166a72-9e9d-4d7f-a272-fea4ce4e4c3f.png)

`-DestinationPath` works, at least with pwsh 5.1:
![image](https://user-images.githubusercontent.com/1829553/144708581-5ca26ebc-3c54-4478-a2ab-764f425aaa43.png)

**Comment by JanDeDobbeleer** [comment]
I also tested this on 5.1 and it works, so not sure where this comes from?

![image](https://user-images.githubusercontent.com/2492783/144708892-2cee3ebc-70aa-41a0-a811-3df37ba8c45b.png)

**Comment by meCoding** [comment]
Thank you for pointing me to right direction. I checked and noticed that I have an other module installed which also have Expand-Archive cmdlet. So, the error is in my side. Closing this issue.

**Comment by JanDeDobbeleer** [comment]
@meCoding indeed, I was just about to show you [this](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/52#issuecomment-355706834) :-)
