### ISSUE TITLE
Avast and windows 11 defender removes oh-my-posh.exe as IDP.GENRIC 

### ISSUE THREAD

**Issue by Fighteros** [JanDeDobbeleer/oh-my-posh#1379]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

### Theme

oh-my-posh --debug --shell uni 
oh-my-posh is not defined 

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
oh-my-posh --debug --shell uni 
oh-my-posh is not defined
```

**Comment by JanDeDobbeleer** [comment]
@Fighteros add an exclusion as I can't fix defender (and I've been in contact quite a few times already).
