### ISSUE TITLE
Shows SHA instead of branch name when upstream gone

### ISSUE THREAD

**Issue by centreboard** [JanDeDobbeleer/oh-my-posh#138]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Shows SHA instead of branch name when upstream gone

### Environment

- Oh my Posh version: 3.30.1  beta
- Theme: Avit
- Operating System: Windows 10
- Shell: Powershell 7
- Terminal: Windows terminal

### Steps to Reproduce

1. Checkout a branch from upstream
2. Delete upstream branch and run `git fetch --prune`

**Expected behavior:** Shows local branch name with branch gone symbol

**Actual behavior:** Shows the SHA of the commit

![image](https://user-images.githubusercontent.com/10487726/98715342-eb473d80-2381-11eb-9611-2982bf78dee5.png)

Running
> git status -unormal --short --branch
> `## tower_sizes...origin/tower_sizes [gone]`

Running `git branch --unset-upstream` does then show branch name

![image](https://user-images.githubusercontent.com/10487726/98722766-5e07e700-2389-11eb-92b8-28f8ada2b81e.png)

**Comment by JanDeDobbeleer** [comment]
Can fix 👍🏻
