### ISSUE TITLE
GitHub PR status

### ISSUE THREAD

**Issue by xt0rted** [JanDeDobbeleer/oh-my-posh#1380]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Using the GitHub CLI you're able to query for a PR's status. Would it be possible to check if the current branch has a status every so often and include it with the other status items (changed files etc.)? It wouldn't be feasible to do this every time the prompt is loaded, but maybe it could be checked and cached for 60 seconds or so?

Here's one way to get to the info from the cli:

```console
gh pr view 1377 --repo JanDeDobbeleer/oh-my-posh --json statusCheckRollup
```

This is probably a better way since it pulls based on the current repo & branch ([docs](https://cli.github.com/manual/gh_pr_status)):

```console
gh pr status --json statusCheckRollup
```

The [`gh api`](https://cli.github.com/manual/gh_api) command is generic but has a flag to cache the response for a period of time which could be useful here as well.

This request is inspired by GitHub Desktop which has an overall status in the header.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/831974/144757530-84df62ae-0d1a-4be5-a41e-d48e3045fad9.png">

<img width="355" alt="image" src="https://user-images.githubusercontent.com/831974/144758762-d52ef0ad-1879-4fc2-bac6-e7b67bdb4bbb.png">

**Comment by JanDeDobbeleer** [comment]
@xt0rted that's definitely possible. We already have caching capabilities 😬. Allow me to first fix the git segment for efficiency and we'll have a look at this one!

**Comment by JanDeDobbeleer** [comment]
@xt0rted I've been playing with this an tbh, it's insane how slow this is. I can't possibly make this happen even with caching it's just too much.

**Comment by xt0rted** [comment]
Running `gh pr status` consistently takes 1.3 seconds for me, but I'm sure there's many things that could slow this down even more. Thanks for looking into this though.
