### ISSUE TITLE
Segment starting in new line if it doesn't fit

### ISSUE THREAD

**Issue by KamQb** [JanDeDobbeleer/oh-my-posh#1395]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would it be possible for ohmyposh to start a segment in newline if it doesn't fit current line? Something like responsive design in web.

For example here (I know it's really narrow but just to grasp the idea) the git segement ending drops to new line:
![image](https://user-images.githubusercontent.com/76776123/145365035-15f8fc41-9b3b-4a90-bbb1-827904a72236.png)
Could it just start from new line so that I could see whole git segment in one line? But only when the viewport is narrow. Ofcourse this wouldn't be always possible.

**Comment by JanDeDobbeleer** [comment]
@KamQb that's not easy and will slow down everything significantly. I'm reluctant to do this mostly due to performance issues and the fact that this isn't a very much requested feature. I'll leave it up for grabs for the moment.

**Comment by JanDeDobbeleer** [comment]
@KamQb I tried to give this a go 3 times already (about 10 hours in total) but there are so many side effects when trying this I just can't. You can see this already happening when using the debug functionality. It works perfectly when you have a standard `powerline` or `diamond` style, but always breaks on any segments that isn't a straightforward implementation.
