### ISSUE TITLE
Prompt lines are not displayed correctly (missing px at the top)

### ISSUE THREAD

**Issue by romanlarrosa** [JanDeDobbeleer/oh-my-posh#1401]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The lines at the prompt are not fully displayed. No matter what theme I use, it always looks like there are a few pixels missing at the top. 

![image](https://user-images.githubusercontent.com/58295696/145565237-dc9c4748-d921-4b69-9716-6de41c99cb7e.png)

Powershell and Windows termianal configs are as default.

### Theme

Currently using bubblesline.omp, but it is happening in all of them.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Here are the timings of segments in your prompt:

ConsoleTitle(false) -   0 ms -
path(true)     -   0 ms -  ~
git(false)     -   3 ms -
python(false)  -   0 ms -
go(false)      -   0 ms -
node(false)    -   0 ms -
ruby(false)    -   0 ms -
java(false)    -   0 ms -
julia(false)   -   0 ms -
battery(true)  -   9 ms -  ⇣ 69
session(true)  -   0 ms - roman ❯
```

**Comment by JanDeDobbeleer** [comment]
@romanlarrosa probably a terminal setting (or something else), but can you also update to the latest version?

**Comment by romanlarrosa** [comment]
Just updated, but i'm still facing the same problem 

![image](https://user-images.githubusercontent.com/58295696/145566798-f3e8ed58-a3f6-4aef-b2a1-d170fe64cc7a.png)

**Comment by JanDeDobbeleer** [comment]
@romanlarrosa is your issue that font is chopped off at the top of the line? Because that's a terminal or font issue, we do not (nor can't) influence rendering (line height, font, spacing,...).

**Comment by romanlarrosa** [comment]
I think so @JanDeDobbeleer, sorry for the issue posting then... But do you have any idea about how to fix it?

**Comment by JanDeDobbeleer** [comment]
@romanlarrosa that's what issues are for 🤗. No, I do not. I would create an issue in the terminal repo if you can't figure it out.

**Comment by romanlarrosa** [comment]
It would be wondwefull! I'm a bit noob 😅
