### ISSUE TITLE
Support for GitKraken CLI

### ISSUE THREAD

**Issue by vedantmgoyal9** [JanDeDobbeleer/oh-my-posh#1402]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The community wants that GitKraken CLI should support oh-my-posh themes and since you are yourself a GitKraken Ambassador, please upvote the feature request at https://feedback.gitkraken.com/suggestions/232775/ohmyposh-theme-support.

Here is what latest preview version of GitKraken CLI renders:

![image](https://user-images.githubusercontent.com/83997633/145590480-c7020570-1c2a-4fa7-a64f-4cd3ef7ba089.png)

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 a lot of work has been done on UI (for powerline fonts), which is what seems missing in your settings here.

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 I asked internally, but I do not consider this part of this repo to follow-up on.
