### ISSUE TITLE
oh-my-posh.exe not started when path to it contains unicode symbols

### ISSUE THREAD

**Issue by IGR2014** [JanDeDobbeleer/oh-my-posh#1403]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

After installation with WinGet oh-my-posh.exe could not be launched with the following error:

`&: The term 'C:/Users/<NAME>/OneDrive/╨Ф╨╛╨║╤Г╨╝╨╡╨╜╤В╤Л/PowerShell/Modules/oh-my-posh/oh-my-posh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.`

That's happening due to unicode symbols in path (my Windows 11 is russian lang).

So the problem:
oh-my-hosh.exe path is detected as **"C:/Users/<NAME>/OneDrive/╨Ф╨╛╨║╤Г╨╝╨╡╨╜╤В╤Л/PowerShell/Modules/oh-my-posh/oh-my-posh.exe"**
But it should be detected as: **"C:/Users/<NAME>/OneDrive/Документы/PowerShell/Modules/oh-my-posh/oh-my-posh.exe"** (if I launch this manually - it started and I can see OhMyPosh bar)

Windows 11 version: 10.0.22000.348
PowerShell version: 7.2.0
OhMyPosh version: 6.29.1

### Theme

It's not even launching

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Write-PoshDebug: The term 'Write-PoshDebug' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by JanDeDobbeleer** [comment]
@IGR2014 how do you install with Winget and end up referencing the PowerShell module?

If you have the PowerShell module, you need to import it first:

```powershell
Import-Module oh-my-posh
```

To set PowerShell to UTF-8 (that's a PowerShell issue), add the following line first:

```powershell
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
Import-Module oh-my-posh
```

**Comment by IGR2014** [comment]
Just tried to make this run so used couple of information sources on how to install.

Yes, the problem was with PowerShell itself, now everything works with your fix, thanks!
