### ISSUE TITLE
Wifi segment not working when system language isn't English

### ISSUE THREAD

**Issue by Khaos66** [JanDeDobbeleer/oh-my-posh#1405]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The `wifi` segment is not showing on my German system

### Theme

Any theme using `wifi`

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
.
```

**Comment by Khaos66** [comment]
This is the output of `netsh.exe wlan show interfaces`
![image](https://user-images.githubusercontent.com/4013009/145643228-e9039c1e-b16b-490d-9c37-96c2008928d2.png)

but `parseNetshCmdResult` only accepts english text

**Comment by Khaos66** [comment]
`netsh` seems to be a tricky one. It only returns localized output no matter what.
There is a `wifi` go lib: https://github.com/mdlayher/wifi
But it only supports unix

On windows there is an API for getting the network and wifi state
https://docs.microsoft.com/en-us/windows/win32/api/netlistmgr/nn-netlistmgr-inetworklistmanager

**Comment by Khaos66** [comment]
Using the win32 api would be the cleanest way, but maybe it is enought to have [all constants here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segment_wifi.go#L87) configurabe by the user

**Comment by JanDeDobbeleer** [comment]
Win32 it is 😬 I'm not pushing that burden to the user.

For reference: https://github.com/Tviljan/WifiHotspotStatus/blob/master/WifiHotspotStatus/Program.cs

**Comment by Khaos66** [comment]
It would be nice to contribute to https://github.com/mdlayher/wifi and use this lib. Then wifi will work on Linux as well

**Comment by JanDeDobbeleer** [comment]
@Khaos66 really good point. But we need to get it to work first 😉

**Comment by Khaos66** [comment]
> Win32 it is 😬 I'm not pushing that burden to the user.
> 
> For reference: https://github.com/Tviljan/WifiHotspotStatus/blob/master/WifiHotspotStatus/Program.cs

The API used in this reference is used to monitor a wifi hotspot **hosted on the current system**. That's not really what we want here, right? 
The `wifi` segment shows information about the currently **connected** (not hosted) wifi network, correct?

Update:
Maybe this is a better reference:
https://github.com/dahall/Vanara/blob/master/PInvoke/NetListMgr/NetListMgr.cs

**Comment by Khaos66** [comment]
I had a look at https://github.com/mdlayher/wifi. It's super complext with other dependencies requiring changes... so I guess it can be skipped and implemented in this project =D

**Comment by Khaos66** [comment]
Found another lib. Created an issue to add the relevant API
https://github.com/winlabs/gowin32/issues/84

Plz support it by up-voting ;)

**Comment by Khaos66** [comment]
@JanDeDobbeleer I'm on this. It isn't easy, though. The Win32 API uses COM a lot... But I figured it out and will soon push a PR ;)

**Comment by Khaos66** [comment]
Turns out it was the wrong API all together... We need this one:
https://docs.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlanqueryinterface

**Comment by Khaos66** [comment]
@JanDeDobbeleer I  just created PR #1469
This was a journey =D
