### ISSUE TITLE
Request: Wakatime

### ISSUE THREAD

**Issue by Khaos66** [JanDeDobbeleer/oh-my-posh#1408]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I use https://wakatime.com/ to track who much time I spend on each project.

Wakatime has an API to get the sum of tracked hours on the current day.

In vscode this is displayed in the bottom line like this
![image](https://user-images.githubusercontent.com/4013009/145679918-a4aa05ff-7a38-4b41-9cfb-2241b453a520.png)

Would be great to have a segment displaying the tracked time of the current day

**Comment by lnu** [comment]
Looks like token for authentication and simple api. We already use that type of call for OWM.  
Do you already have something?

**Comment by Khaos66** [comment]
Docs:
~https://wakatime.com/developers#all_time_since_today~
https://wakatime.com/developers#summaries

Endpoint:
~https://wakatime.com/api/v1/users/current/all_time_since_today~
https://wakatime.com/api/v1/users/current/summaries?start=today&end=today

Sample response:
```json
{
  "cummulative_total": {
    "decimal": "2.12",
    "digital": "2:07",
    "seconds": 7661.199602,
    "text": "2 hrs 7 mins"
  },
  "data": [
   ...
  ],
  "end": "2021-12-11T22:59:59Z",
  "start": "2021-12-10T23:00:00Z"
}
```

**Comment by Khaos66** [comment]
I can prepare a PR

**Comment by lnu** [comment]
Beware of the default http_timeout

**Comment by Khaos66** [comment]
I'll take `segment_owa` as a base then. Should be similar. Maybe I need to refactor some functions into a `webapi` base type again, just like with the `scm` changes I did resently =D 
(I havn't had a look at it. Maybe it's already like that)

**Comment by JanDeDobbeleer** [comment]
@Khaos66 that's already pretty standard.

**Comment by Khaos66** [comment]
@JanDeDobbeleer I created #1410 for this ;)

**Comment by JanDeDobbeleer** [comment]
@Khaos66 I have a hard time following here, will do my best 😬

**Comment by Khaos66** [comment]
JanDeDobbeleer made a better PR #1418 (and I'm a bit envious) =D

**Comment by Khaos66** [comment]
@JanDeDobbeleer Thanks for helping implement this =)

**Comment by JanDeDobbeleer** [comment]
The release did fail though (which is strange).

**Comment by Khaos66** [comment]
> The release did fail though (which is strange).

@JanDeDobbeleer I'm sure you will figure this out ;D

**Comment by JanDeDobbeleer** [comment]
Fixed.

**Comment by Khaos66** [comment]
@JanDeDobbeleer I'm not sure it's fixed. The Wakatime segment is not listed in the sidebar
<img width="197" alt="image" src="https://user-images.githubusercontent.com/4013009/145831859-298d6094-6db1-4bc6-862d-eabcca539e7a.png">

**Comment by JanDeDobbeleer** [comment]
@Khaos66 yes, the functionality is there, the docs didn't get pushed due to the fix not being in the doc path

**Comment by JanDeDobbeleer** [comment]
@Khaos66 https://ohmyposh.dev/docs/wakatime
