### ISSUE TITLE
Battery: the battery level can be > 100%

### ISSUE THREAD

**Issue by lnu** [JanDeDobbeleer/oh-my-posh#141]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

**Really minor**

![image](https://user-images.githubusercontent.com/1829553/98788224-db227300-2400-11eb-9500-e7bcd3dd3852.png)

![image](https://user-images.githubusercontent.com/1829553/98788184-cb0a9380-2400-11eb-9ae6-fc56fd8ac457.png)

### Environment

- Oh my Posh version:
- Theme: any
- Operating System: windows(macbook pro with bootcamp)
- Shell: Powershell 7
- Terminal: Windows terminal

### Steps to Reproduce

1. Check the prompt battery value

**Expected behavior:** max 100%

**Actual behavior:** 101%

**Comment by JanDeDobbeleer** [comment]
Ok. Not sure how to tackle that rather than cap at 100.
