### ISSUE TITLE
path segment: Prioritize showing folder names on the left

### ISSUE THREAD

**Issue by KTibow** [JanDeDobbeleer/oh-my-posh#1411]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Right now, when you set `style` in the `path` segment to anything that uses the `folder_icon`, it prioritizes showing folder names on the right instead of the left.

For example, let's say you were in `~longfolder/longfolder1/longfolder2/longfolder3`. Right now, that would render as:
![image](https://user-images.githubusercontent.com/10727862/145684231-a77d9de3-b3ad-49ca-872e-986b6a05ae7e.png)
However, I'd like if there was an option to make it render like:
`~ > longfolder > [icon] > [icon] > [icon]`
or even
`~ > longfolder > [icon] > [icon] > longfolder3`
(it would show the current folder on the right, then show as many from the left as possible).

**Comment by JanDeDobbeleer** [comment]
@KTibow OK, but how would that even render outside of the home folder? As the would always indicate the root?

**Comment by KTibow** [comment]
> OK, but how would that even render outside of the home folder?

original:
![image](https://user-images.githubusercontent.com/10727862/145685138-cecf8196-4611-4b83-80fe-057b592fbaaa.png)
case 1:
`> tmp > longfolder > [icon] > [icon] > [icon]`
case 2:
`> tmp > [icon] > [icon] > [icon] > longfolder4`

> As the would always indicate the root?

Not sure what you mean by that.

**Comment by JanDeDobbeleer** [comment]
@KTibow I fully understand now, can do.

**Comment by KTibow** [comment]
Some weird stuff seems to be happening with `agnoster_left`.
![image](https://user-images.githubusercontent.com/10727862/145689842-108a4dd6-3ad7-445f-8bce-f443ae4d0eea.png)

**Comment by JanDeDobbeleer** [comment]
@KTibow that's not `agnoster_left` but a glyph which is doing that. It's an [issue](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) on Windows Terminal.

**Comment by KTibow** [comment]
I got the same thing on gnome-terminal, but that fix worked. Thanks.
