### ISSUE TITLE
Request: loading indicator / progress bar

### ISSUE THREAD

**Issue by Khaos66** [JanDeDobbeleer/oh-my-posh#1416]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Sometimes loading the segments takes a little longer. For web requests there is a timeout defined. But executables don't have a timeout yet.
Maybe it would be good to show a loading indicator of some kind.
For example a progress bar. There are several libs for progress bars using go lang.
https://github.com/cheggaaa/pb
Or
https://github.com/schollz/progressbar

Or something completely different 
What do you think?

**Comment by JanDeDobbeleer** [comment]
Not possible without a very complex setup. For those segments, use tooltips. That implies we are able to re-render the prompt WHILE oh-my-posh is fetching information.
