### ISSUE TITLE
working in cmd.exe as a command (posh-windows-amd64.exe)

### ISSUE THREAD

**Issue by IBIT-ZEE** [JanDeDobbeleer/oh-my-posh#1417]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi,,,
I tested with CLink to get a CMD.EXE prompt with OMP 
but I run into a few problems... 

I'm trying to get OMP info with just cmd.exe,,, 

I've made a few tweaks with the folders and themes
and create a OMP-CMD that calls  "posh-windows-amd64.exe"
with the theme parameter ( I'm using "jandedobbeleer.omp.json" )

so when I want the omp info-line...  I just type omp (omp.cmd)
(my main goal for now is to get the github info... next... we'll see...)

it works fine but no git information...

what is the mechanism used to get the git information...
(in the posh-windows-amd64.exe executable)
?is via gh.exe... git.exe... or other ?

Thanks...

**Comment by JanDeDobbeleer** [comment]
It uses git.exe under the hood. Let me get this right, you're not following the guide but followed your own path? Because it's difficult to debug something non-standard. You do need the git segment in your config, so make sure that's there
