### ISSUE TITLE
Feature Request: full agnoster path hybrid with colours

### ISSUE THREAD

**Issue by takashi1kun** [JanDeDobbeleer/oh-my-posh#142]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [ X] I looked for duplicate issues before submitting this one

### Description

It would be good to have a mix in the path segment style between full and agnoster, so it displays the full path, separated by folder_separator_icon but with the text of all folders and not home path fumbling shenanigans.
I understand that this may lead to some, very long paths that wrap, in those cases the best i think would be to minimize as the folder_icon or as ... the most meddlesome folders, it would also be great to color each folder "section" with a color based on a sequence defined in the theme settings. 

### Environment

Does not matter.

### Steps to Reproduce

Does not matter.

**Expected behavior:** Does not matter.

**Actual behavior:** Does not matter.

**Comment by JanDeDobbeleer** [comment]
<img width="852" alt="afbeelding" src="https://user-images.githubusercontent.com/2492783/98813008-cf947380-2423-11eb-80c1-d9699446bd89.png">

I have something like this (uses a prefix which show the folder icon, that's optional).
You can also do this :-)

<img width="852" alt="afbeelding" src="https://user-images.githubusercontent.com/2492783/98813114-fbaff480-2423-11eb-8cfe-8cfe0f0281d2.png">

**Comment by silkfire** [comment]
@JanDeDobbeleer 

What's the difference between Full and Agnoster Full? They look both identical in my terminal.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/1554615/f4523b9d-2030-46ef-bf31-76b422c615d2)

**Comment by JanDeDobbeleer** [comment]
@silkfire nothing anymore since we now allow overriding the path separator everywhere.

**Comment by silkfire** [comment]
I see, will one of them be removed in the future?

**Comment by JanDeDobbeleer** [comment]
@silkfire no, that would be a breaking change. Also not really an issue imho.
