### ISSUE TITLE
My directory tree appearance is not look like everyone else...

### ISSUE THREAD

**Issue by hgflac** [JanDeDobbeleer/oh-my-posh#1437]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

![terminal](https://user-images.githubusercontent.com/56708450/146124490-d111c882-a50c-4695-9a3d-116c78ae8f5c.PNG)

### Theme

Operator

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
...
```

**Comment by JanDeDobbeleer** [comment]
Please set up the correct [font](https://ohmyposh.dev/docs/config-fonts).
