### ISSUE TITLE
Linux install doc command update

### ISSUE THREAD

**Issue by mattwojo** [JanDeDobbeleer/oh-my-posh#1452]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

On the Linux install doc, in the Replace your existing prompt section: https://ohmyposh.dev/docs/linux#replace-your-existing-prompt

The command to replace your existing prompt with an Oh My Posh theme is listed as:
eval "$(oh-my-posh --init --shell bash --config ~/.poshthemes/jandedobbeleer.omp.json)"

I believe the correct command to list this for Linux (at least for WSL -- which is my only means of testing at the moment) should actually be: 
eval "$(oh-my-posh --init --shell bash --config $(brew --prefix oh-my-posh)/themes/jandedobbeleer.omp.json)"

This should correctly reference the path to where the Oh My Posh themes are stored by default. *I believe this also means that the line above could be removed that says: "The guides below assume you copied the theme called jandedobbeleer.omp.json to your user's $HOME folder. "  

Wanted to file a PR to make this update, but wasn't wrapping my head around where this command is kept in the repo for reference in the doc.

Thanks! ~Matt

### Theme

jandedobbeleer.omp.json

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```shell
Path error
```

**Comment by JanDeDobbeleer** [comment]
Wait. That one's shared cross platform. The `.poshthemes` reference should be removed and the statement needs to be kept. Check the other shell guides in `install-shells.mdx`

**Comment by mattwojo** [comment]
Ahh - didn't see that `install-shells.mdx` page.
I'm not quite tracking what you're saying about removing `.poshthemes` though... 

So with WSL, the themes were installed for me in this folder (I'm using Ubuntu):
`\\wsl.localhost\Ubuntu-20.04\home\linuxbrew\.linuxbrew\Cellar\oh-my-posh\6.34.1\themes`
..and can be accessed with:
`eval "$(oh-my-posh --init --shell bash --config $(brew --prefix oh-my-posh)/themes/jandedobbeleer.omp.json)"`

...but I'm not quite tracking how to suggest an edit to represent this especially given this is cross platform (& I'm not quite sure what aligns or doesn't on normal Linux or Mac). I just know I was getting an error on the current:
`eval "$(oh-my-posh --init --shell bash --config ~/.poshthemes/jandedobbeleer.omp.json)"`

**Comment by JanDeDobbeleer** [comment]
@mattwojo if you read through the docs, it always highlights where the teams can be found based on the installation method, then the info block states we're assuming you're using a theme you copied to your user's home folder. So the issue is that `.poshthemes` is still there (which is because a contribution re-introduced that part but we didn't spot that issue).

**Comment by mattwojo** [comment]
Thanks Jan!
