### ISSUE TITLE
Add Set-PoshPrompt commad to winget installed oh-my-posh

### ISSUE THREAD

**Issue by haoenz** [JanDeDobbeleer/oh-my-posh#1453]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

If I install oh-my-posh by winget, I cannot use the ```Set-PoshPrompt``` commad.

Meanwhile, I cannot use ```Get-Command -Module oh-my-posh``` to list all the oh-my-posh cmdlet, beacuse these cmdlet do not have the source attribution.

**Comment by JanDeDobbeleer** [comment]
@haoenz please read the [docs](https://ohmyposh.dev/docs/windows#replace-your-existing-prompt), `Set-PoshPrompt` is deprecated. And there's no module when installing with Winget.
