### ISSUE TITLE
Add version display support for Terraform segment

### ISSUE THREAD

**Issue by puttehi** [JanDeDobbeleer/oh-my-posh#1455]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It's common to have multiple versions of Terraform used in a workplace across different repositories. It would be a nice-to-have feature to show the version number. Not truly necessary as Terraform will tell the user if the versions mismatch.

This will likely require a configuration parameter for default file or files (and handling of multiple choices) to read the module version from. Usually it's `init.tf`, `versions.tf` or `terraform.tf`.

**Comment by JanDeDobbeleer** [comment]
@puttehi do you have an example file?
