### ISSUE TITLE
winreg: advanced template-based query

### ISSUE THREAD

**Issue by memcpy-rand-rand-rand** [JanDeDobbeleer/oh-my-posh#1458]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The default query mechanism for the winreg segment is that it a "path" is supplied in the config, and a "Value" returned to the template.

The Value is a string or a dword/qword formatted into a string with hex 0x.... formatting.

As a basic case, this works fine.

For advanced use, the individual query functions will be exposed to the template, allowing for nested queries or other complex scenarios, using other variables available to the template to make the query path.

It will also allow for custom formatting of the query and response by the template, not relying on the default string formatting for d/qword entries.

Currently if the query to the registry is unsuccessful (denoted by a nil value returned - a string of "" is not an error), the segment will use the supplied fallback string if supplied in the config, failing that it will become disabled and not display.

Only if the segment is enabled will it run the template process and potentially any additional queries that the template contains.

To solve:

1. basic vs template logic vs enabled state of segment
2. how to expose query values to templates to be useful (rather then pre-formatting into strings)
3. consider if this functionality should exist at a higher level outside the segment?

**Comment by JanDeDobbeleer** [comment]
> For advanced use, the individual query functions will be exposed to the template, allowing for nested queries or other complex scenarios, using other variables available to the template to make the query path.

@memcpy-rand-rand-rand what does this mean, or rather, how did you see this work? The only addition would be to also have a way to get the real value as the path doesn't change (which is possible with #2358). Or do you want to chain multiple queries into one result?

**Comment by JanDeDobbeleer** [comment]
Closing this as I'm not planning this anytime soon, if relevant it can be opened again.
