### ISSUE TITLE
Randomly seeing red "xERROR"

### ISSUE THREAD

**Issue by EmKayUltra** [JanDeDobbeleer/oh-my-posh#147]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

![image](https://user-images.githubusercontent.com/3580562/98980020-1b115500-24ea-11eb-8488-fc6b2809da7f.png)

This randomly happens, but I'm pretty sure it only happens in git repo's (thought I'm not 100% sure of that).

### Environment

- Oh my Posh version: 3.30.1
- Theme: avit
- Operating System: Windows 10
- Shell: pwsh 7.0.3
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
This shows when the last command output wasn't `0`, meaning there was an issue with the previous command. This by design :-)

**Comment by EmKayUltra** [comment]
ah, thanks for clarifying.  keep up the awesome work :)

**Comment by JanDeDobbeleer** [comment]
What might be a good idea for this theme is that I remove the error string and only show the red cross. That'll look better 😬
