### ISSUE TITLE
Provide option to display line between left and right prompt

### ISSUE THREAD

**Issue by Kudostoy0u** [JanDeDobbeleer/oh-my-posh#1472]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Provide an option in the prompt configuration to to display a line (dotted, dashed, or solid) from the left to the right prompt.

![image](https://user-images.githubusercontent.com/69732000/146696239-60caaffa-2d5d-4650-bfec-269ee21a03dc.png)

**Comment by JanDeDobbeleer** [comment]
@Kudostoy0u that's a tricky one. Calculating the distance between these has proven to fail in the past (quite a lot), I'm not inclined to open that jar again tbh. Leaving this open for the adventurous person, but I'm not going down that rabbit hole again myself :-)

**Comment by JanDeDobbeleer** [comment]
@Kudostoy0u @IPushedU Thanks to the latest changes I think I have a working implementation:

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/2492783/152545063-5db95e87-d617-4689-979a-e0284e74f49c.png">

I just need to tweak it a little bit so that it also allows multiple characters, but seems to work.

**Comment by Pyrrhusn** [comment]
@JanDeDobbeleer First of all sorry for making you remember this rabbit hole, as you clearly didn't want to go there again (seeing from your older replies, quite the PTSD trigger). And also sorry for not searching this topic beforehand, before I posted a duplicate of it. But, wow you did it. Congrats 🎉 (How?!) *You're a wizard, Harry*
By the way, Is it available for testing?

**Comment by JanDeDobbeleer** [comment]
@IPushedU incoming ;-) You can prepare by adding this property (`filler`) to the left aligned block:

```json
"alignment": "left",
"filler": "."
```

**Comment by Pyrrhusn** [comment]
@JanDeDobbeleer Saw the v7.9.0 update today and wanted to try it out the filler feature, but it doesn't seem to be working for me. I did add the  `"filler": "."` property to the top left aligned block:
``` json
"blocks": [
    {
      "alignment": "left",
      "filler": ".",
      "segments": [ 
...
```
(thanks is advance)

**Comment by JanDeDobbeleer** [comment]
@IPushedU which terminal and platform?

**Comment by Pyrrhusn** [comment]
(Should've mentioned before)

platform: linux
terminal: Konsole (Kde plasma default emulator)
shell: zsh

**Comment by JanDeDobbeleer** [comment]
@IPushedU I'm so sorry, it needs to be set on the RIGHT aligned block...

**Comment by Pyrrhusn** [comment]
Ah I see, it's alright. Stuff like this happens 😃. But thanks for looking into it. 
I was going to troubleshoot/diagnose later today to maybe find the culprit on my end, thought it was my theme or installation or the emulator settings self but I don't have to that anymore luckily, saved my time thanks to you.
