### ISSUE TITLE
[Azure segment] Parse azure context from config file

### ISSUE THREAD

**Issue by obesser** [JanDeDobbeleer/oh-my-posh#1473]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Since fetching the azure context is quite slow, I think it would be good to have an option to get it from the config file in the `.azure` directory. Somewhat similar to what we have in the kubectl segment ([the parse_kubeconfig property](https://ohmyposh.dev/docs/kubectl#properties)).

**Comment by JanDeDobbeleer** [comment]
@obesser can you provide me with a redacted config file and the exact location?

**Comment by obesser** [comment]
Sure.

Azure CLI: `~/.azure/azureProfile.json`: (choose the one that is `isDefault`)
`{"subscriptions": [{"id": "subscription_id", "name": "subscription_name", "state": "Enabled", "user": {"name": "user_name", "type": "user"}, "isDefault": true, "tenantId": "tenant_id", "environmentName": "AzureCloud", "homeTenantId": "tenant_id", "managedByTenants": []}], "installationId": "a5bd7f78-6169-11ec-835d-d46d6dfcd860"}`


Azure PowerShell: `~/.azure/AzureRmContext.json`: (choose the `"DefaultContextKey"` from the `"Contexts"` object)
`{
  "DefaultContextKey": "My Azure Subscription (subscription_id) - tenant_id - user_name",
  "EnvironmentTable": {},
  "Contexts": {
    "My Azure Subscription (subscription_id) - tenant_id - user_name": {
      "Account": {
        "Id": "user_name",
        "Credential": null,
        "Type": "User",
        "TenantMap": {},
        "ExtendedProperties": {
          "Subscriptions": "subscription_ids",
          "Tenants": "tenants_ids",
          "HomeAccountId": "tenants_ids"
        }
      },
      "Tenant": {
        "Id": "tenant_id",
        "Directory": null,
        "IsHome": true,
        "ExtendedProperties": {}
      },
      "Subscription": {
        "Id": "subscription_id",
        "Name": "My Azure Subscription",
        "State": "Enabled",
        "ExtendedProperties": {
          "HomeTenant": "tenant_id",
          "AuthorizationSource": "Legacy",
          "SubscriptionPolices": "{\"locationPlacementId\":\"Public_2014-09-01\",\"quotaId\":\"MSDN_2014-09-01\",\"spendingLimit\":\"On\"}",
          "Tenants": "tenant_id",
          "Account": "user_name",
          "Environment": "AzureCloud"
        }
      },
      "Environment": {
        "Name": "AzureCloud",
        "Type": "Built-in",
        "OnPremise": false,
        "ServiceManagementUrl": "https://management.core.windows.net/",
        "ResourceManagerUrl": "https://management.azure.com/",
        "ManagementPortalUrl": "https://portal.azure.com/",
        "PublishSettingsFileUrl": "https://go.microsoft.com/fwlink/?LinkID=301775",
        "ActiveDirectoryAuthority": "https://login.microsoftonline.com/",
        "GalleryUrl": "https://gallery.azure.com/",
        "GraphUrl": "https://graph.windows.net/",
        "ActiveDirectoryServiceEndpointResourceId": "https://management.core.windows.net/",
        "StorageEndpointSuffix": "core.windows.net",
        "SqlDatabaseDnsSuffix": ".database.windows.net",
        "TrafficManagerDnsSuffix": "trafficmanager.net",
        "AzureKeyVaultDnsSuffix": "vault.azure.net",
        "AzureKeyVaultServiceEndpointResourceId": "https://vault.azure.net",
        "GraphEndpointResourceId": "https://graph.windows.net/",
        "DataLakeEndpointResourceId": "https://datalake.azure.net/",
        "BatchEndpointResourceId": "https://batch.core.windows.net/",
        "AzureDataLakeAnalyticsCatalogAndJobEndpointSuffix": "azuredatalakeanalytics.net",
        "AzureDataLakeStoreFileSystemEndpointSuffix": "azuredatalakestore.net",
        "AdTenant": "Common",
        "ContainerRegistryEndpointSuffix": "azurecr.io",
        "VersionProfiles": [],
        "ExtendedProperties": {
          "OperationalInsightsEndpoint": "https://api.loganalytics.io/v1",
          "OperationalInsightsEndpointResourceId": "https://api.loganalytics.io",
          "AzureAnalysisServicesEndpointSuffix": "asazure.windows.net",
          "AnalysisServicesEndpointResourceId": "https://region.asazure.windows.net",
          "AzureAttestationServiceEndpointSuffix": "attest.azure.net",
          "AzureAttestationServiceEndpointResourceId": "https://attest.azure.net",
          "AzureSynapseAnalyticsEndpointSuffix": "dev.azuresynapse.net",
          "AzureSynapseAnalyticsEndpointResourceId": "https://dev.azuresynapse.net",
          "ManagedHsmServiceEndpointResourceId": "https://managedhsm.azure.net",
          "ManagedHsmServiceEndpointSuffix": "managedhsm.azure.net",
          "MicrosoftGraphEndpointResourceId": "https://graph.microsoft.com/",
          "MicrosoftGraphUrl": "https://graph.microsoft.com"
        }
      },
      "VersionProfile": null,
      "TokenCache": {
        "CacheData": null
      },
      "ExtendedProperties": {}
    }
  },
  "ExtendedProperties": {}
}`
