### ISSUE TITLE
Path segment shows backslash when folder_separator_icon is set to "/"

### ISSUE THREAD

**Issue by HasEveryUsernameBeenTaken** [JanDeDobbeleer/oh-my-posh#1477]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When using the folder_separator_icon set to "/", and I set the root of a drive letter as my current directory, my prompt shows a "\" as the directory separator.

A manual call to oh-my-posh.exe will print the drive with a "/" separator.  It only seems to affect the prompt that is actually printed in Microsoft PowerShell.

In my PowerShell profile, the theme is loaded with the following code:
```
# Oh-My-Posh
Set-PoshPrompt -Theme test
```

Examples from my terminal

With a current location of "C:\Program Files", my prompt shows:

`C:/Program Files $`

Next, I go up to "C:\", my prompt shows "C:\ $ "
```
C:/Program Files $ cd ..
C:\ $
```

The output of oh-my-posh with the theme file appears to show correctly.
```
C:\ $ oh-my-posh -config C:\Users\<username>\Documents\PowerShell\Modules\oh-my-posh\themes\test.omp.json
C:/ $
```

### Theme

[test.omp.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7758919/test.omp.zip)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Version: 6.32.5

Segments:

ConsoleTitle(false) -   0 ms -
path(true)  -   0 ms - C:\
text(true)  -   0 ms - $

Run duration: 555.4µs

Logs:

2021/12/21 18:41:27 debug: getenv
C:\Users\cdenn\AppData\Local
2021/12/21 18:41:27 getenv duration: 0s, args: LOCALAPPDATA
2021/12/21 18:41:27 getCachePath duration: 519.9µs, args:
2021/12/21 18:41:27 getArgs duration: 0s, args:
2021/12/21 18:41:27 getArgs duration: 0s, args:
2021/12/21 18:41:27 getShellName duration: 7.9132ms, args:
2021/12/21 18:41:27 debug: getenv

2021/12/21 18:41:27 getenv duration: 0s, args: OMP_CACHE_DISABLED
2021/12/21 18:41:27 isRunningAsRoot duration: 0s, args:
2021/12/21 18:41:27 getcwd duration: 0s, args:
2021/12/21 18:41:27 getPathSeperator duration: 0s, args:
2021/12/21 18:41:27 getShellName duration: 0s, args:
2021/12/21 18:41:27 getCurrentUser duration: 0s, args:
2021/12/21 18:41:27 getHostName duration: 0s, args:
2021/12/21 18:41:27 getcwd duration: 0s, args:
2021/12/21 18:41:27 getcwd duration: 0s, args:
2021/12/21 18:41:27 getArgs duration: 0s, args:
2021/12/21 18:41:27 getRuntimeGOOS duration: 0s, args:
2021/12/21 18:41:27 getRuntimeGOOS duration: 0s, args:
2021/12/21 18:41:27 getPathSeperator duration: 0s, args:
2021/12/21 18:41:27 getRuntimeGOOS duration: 0s, args:
2021/12/21 18:41:27 getcwd duration: 0s, args:
2021/12/21 18:41:27 isRunningAsRoot duration: 0s, args:
2021/12/21 18:41:27 getcwd duration: 0s, args:
2021/12/21 18:41:27 getPathSeperator duration: 0s, args:
2021/12/21 18:41:27 getShellName duration: 0s, args:
2021/12/21 18:41:27 getCurrentUser duration: 0s, args:
2021/12/21 18:41:27 getHostName duration: 0s, args:
```

**Comment by lnu** [comment]
It works if  we switch this code(https://github.com/JanDeDobbeleer/oh-my-posh/blob/64a9e65e7414288541f3a2d4f0bec5a922f01c3c/src/init/omp.ps1#L40):
![image](https://user-images.githubusercontent.com/1829553/147067570-c4c9c68f-760e-4145-a0a5-86f15a475369.png)
I don't really remember why the last `\` is trimmed. Any idea @JanDeDobbeleer ?

**Comment by JanDeDobbeleer** [comment]
@lnu Consistency cross platform? We can remove it as there was no clear use-case that drove that implementation. If this affects anyone we'll find out soon enough anyways.
