### ISSUE TITLE
Segmented visual elements in normal (non-admin) shell windows

### ISSUE THREAD

**Issue by mohamedghry** [JanDeDobbeleer/oh-my-posh#1478]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Environment

OS: Windows 11 Home 21H2
Windows Terminal: Version 1.11.3471.0
PowerShell Core: Version 7.2.1
Oh-My-Posh: Version: Version 6.37.1
Oh-My-Posh Theme: Any
Font Used: Hack NF

### Description

Visual items are segmented only in normal (non-admin) terminal windows

### Actions taken to fix the issue

- Uninstalled oh-my-posh then re-installed it.
- Changed oh-my-posh theme to other different themes
- Changed font used in terminal

### Visuals

Below is a screenshot of how the two windows look like. Admin session is on top.

![image](https://user-images.githubusercontent.com/70846567/147013283-f15b6636-cd51-4a98-95b0-17d7f7d4a7c4.png)

### Theme

All

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@JanDeDobbeleer that’s a known Windows Terminal bug. You can find more information and a fix [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext).
