### ISSUE TITLE
Theme not loading when new Powershell tab is opened

### ISSUE THREAD

**Issue by mwasowski** [JanDeDobbeleer/oh-my-posh#1485]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am having issue when I open Windows Terminal with either Powershell Core or Windows Powershell. The theme is not loading nad I am presented with the default one:
![obraz](https://user-images.githubusercontent.com/1921808/147117378-e8a65ade-7395-4abe-9b7f-0ac1f94ff540.png)
I have both configured in `$profile` and it was working before the update I did today.
What is strange when I launch `. $profile` it correctly sets my theme.

### Theme

powerlevel10k_rainbow with minor modifications

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Version: 6.38.2

Segments:

ConsoleTitle(true) -   0 ms -
session(true)  -   0 ms -  * 
path(true)     -   0 ms -   ~ 
git(false)     -   9 ms -
battery(false) -   1 ms -
node(false)    -   0 ms -
shell(true)    -   0 ms -  ﲵ uni 
root(false)    -   0 ms -
text(true)     -   0 ms -  NO CONFIG 
exit(true)     -   0 ms -   

Run duration: 12.1987ms

Logs:

2021/12/22 16:40:22 debug: getenv
C:\Users\*\AppData\Local
2021/12/22 16:40:22 getenv duration: 0s, args: LOCALAPPDATA
2021/12/22 16:40:22 getCachePath duration: 0s, args:
2021/12/22 16:40:22 getArgs duration: 0s, args:
2021/12/22 16:40:22 getArgs duration: 0s, args:
2021/12/22 16:40:22 getShellName duration: 0s, args:
2021/12/22 16:40:22 debug: getenv

2021/12/22 16:40:22 getenv duration: 0s, args: OMP_CACHE_DISABLED
2021/12/22 16:40:22 isRunningAsRoot duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getShellName duration: 0s, args:
2021/12/22 16:40:22 getCurrentUser duration: 0s, args:
2021/12/22 16:40:22 getHostName duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 debug: getenv

2021/12/22 16:40:22 getenv duration: 0s, args: SSH_CONNECTION
2021/12/22 16:40:22 debug: getenv

2021/12/22 16:40:22 getenv duration: 0s, args: SSH_CLIENT
2021/12/22 16:40:22 getCurrentUser duration: 0s, args:
2021/12/22 16:40:22 getRuntimeGOOS duration: 0s, args:
2021/12/22 16:40:22 getHostName duration: 0s, args:
2021/12/22 16:40:22 debug: getenv
*
2021/12/22 16:40:22 getenv duration: 0s, args: POSH_SESSION_DEFAULT_USER
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getArgs duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getRuntimeGOOS duration: 0s, args:
2021/12/22 16:40:22 getRuntimeGOOS duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getRuntimeGOOS duration: 0s, args:
2021/12/22 16:40:22 stackCount duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getRuntimeGOOS duration: 0s, args:
2021/12/22 16:40:22 hasCommand duration: 9.5085ms, args: git.exe
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 error: hasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2021/12/22 16:40:22 hasParentFilePath duration: 0s, args: .git
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getBatteryInfo duration: 1.5932ms, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getShellName duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 isRunningAsRoot duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 isRunningAsRoot duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getPathSeperator duration: 0s, args:
2021/12/22 16:40:22 getShellName duration: 0s, args:
2021/12/22 16:40:22 getCurrentUser duration: 0s, args:
2021/12/22 16:40:22 getHostName duration: 0s, args:
2021/12/22 16:40:22 getcwd duration: 0s, args:
2021/12/22 16:40:22 lastErrorCode duration: 0s, args:
```

**Comment by mwasowski** [comment]
Did I miss another configuration change in one of the updates? :)

**Comment by JanDeDobbeleer** [comment]
@mwasowski what does your profile look like?

**Comment by mwasowski** [comment]
```
using namespace System.Management.Automation
using namespace System.Management.Automation.Language

$env:POSH_SESSION_DEFAULT_USER  = [System.Environment]::UserName

# Import-Module posh-git
Import-Module oh-my-posh
Import-Module PSReadLine

function upmod { Get-InstalledModule | Update-Module }

Set-PoshPrompt -Theme ~\.oh-my-posh\.powerlevel10k_rainbow.omp.json

Enable-PoshTransientPrompt

Clear-Host

# Shows navigable menu of all options when hitting Tab
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete

# Autocompletion for arrow keys
Set-PSReadLineOption -HistorySearchCursorMovesToEnd
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
```

**Comment by JanDeDobbeleer** [comment]
@mwasowski what happens when you change

```Powershell 
Set-PoshPrompt -Theme ~\.oh-my-posh\.powerlevel10k_rainbow.omp.json 
```

for 

```Powershell 
oh-my-posh --init --shell pwsh --config ~\.oh-my-posh\.powerlevel10k_rainbow.omp.json | Invoke-Expression
```

**Comment by mwasowski** [comment]
Interesting..that actually works. Just it feels like it's taking longer? 🤔 

Also with my initial config, if I do
```
. $profile
```
It loads the theme correctly. It's like it's unable to do it on the initial open.

**Comment by JanDeDobbeleer** [comment]
@mwasowski can't take longer to load as the first cmdlet is a wrapper around that one :-)

**Comment by mwasowski** [comment]
That's why I wrote that it feels like it takes longer ;)

**Comment by mwasowski** [comment]
Interesting. When I did this in my config:
```
Set-PoshPrompt -Theme ~\.oh-my-posh\.powerlevel10k_rainbow.omp.json
Set-PoshPrompt -Theme ~\.oh-my-posh\.powerlevel10k_rainbow.omp.json
```
It also works ;)

**Comment by JanDeDobbeleer** [comment]
@mwasowski zero sense was made but I'll try to see what's going on 😀

**Comment by mwasowski** [comment]
@JanDeDobbeleer Yeah, I know! It's like it is not initializing correctly? I think this is not that urgent and now I bite myself I bothered you by opening this before Christmas 😦

**Comment by JanDeDobbeleer** [comment]
@mwasowski I tried to reproduce this but I can't... It always loads first try. I would resort to only using the invoke syntax:

```powershell
oh-my-posh --init --shell pwsh --config ~\.oh-my-posh\.powerlevel10k_rainbow.omp.json | Invoke-Expression
```

The `Set-PoshPrompt` command is silently deprecated.

**Comment by BenjaminAbt** [comment]
Looks like I have the same issue (or at least a side effect) on a fresh install of Windows 10

Does not work anymore:
```powershell
oh-my-posh --init --shell pwsh --config ~\.oh-my-posh\.unicorn.omp.json  | Invoke-Expression
```

Works great:
```powershell
Set-PoshPrompt Unicorn
```

Env:
- PowerShell 7.2.1
- Windows 10.0.19044
- oh my posh v6.39.1 via winget
- Profile on OneDrive
- Env = LOCALAPPDATA

It looks like `oh-my-posh --init --shell pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\unicorn.omp.json | Invoke-Expression` is working for me (now).

**Comment by JanDeDobbeleer** [comment]
> Does not work anymore:
> 
> ```powershell
> oh-my-posh --init --shell pwsh --config ~\.oh-my-posh\.unicorn.omp.json  | Invoke-Expression
> ```

@BenjaminAbt  but is that theme located there?

**Comment by akshay-zz** [comment]
Hi I was also facing this. Today only I setup the oh-my-posh.

When I was trying to change the them by below command nothing was happening. Btw this command is working for the first time. Also one behavior I found , It doesn't matter which theme you are selecting it will by default applying `jandedobbeleer.omp.json  ` theme for me.
`oh-my-posh --init --shell pwsh --config ~\.oh-my-posh\.unicorn.omp.json  | Invoke-Expression`

As soon I tried the following command it worked for me

`oh-my-posh --init --shell pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\unicorn.omp.json | Invoke-Expression`

@JanDeDobbeleer @BenjaminAbt

**Comment by BenjaminAbt** [comment]
> @BenjaminAbt but is that theme located there?

Sorry! Obviously lost in the wave of notifications.
Yes, the file was there.

In the meantime I moved the file to a new location. It can be loaded again.

```powershell
oh-my-posh --init --shell pwsh --config $Env:OneDriveConsumer\Apps\OhMyPosh\abt.omp.json | Invoke-Expression
```

**Comment by llysyganicz** [comment]
Hi. I have the same issue. 

I keep my config in home directory which is `C:\Users\Łukasz`. It contains letter from polish alphabet. 
Reloading profile or executing `init` once more loads theme correctly.
I moved my theme to different location (without polish letter) and it works now.

**Comment by posthumz** [comment]
I am having the same issue and I think this may be a problem with the codepage.
I got this problem whenever the path to my theme contains some non-ASCII character.
With out setting any module my console is in codepage 936, by setting my theme with a non-ASCII path the it automatically uses the default theme and the codepage changes to 65001. Setting the theme the again under codepage 65001 works. (This may explain why setting it twice works)
![图片](https://user-images.githubusercontent.com/63167402/152719870-c78bf9d4-f479-412b-b5d4-7e28a353a4f0.png)

Alternatively, doing
```
chcp 65001
Set-PoshPrompt path_to_theme
```
in the ```$Profile``` works for me.
