### ISSUE TITLE
Support shorter current working directory

### ISSUE THREAD

**Issue by deadwards90** [JanDeDobbeleer/oh-my-posh#149]
### Prerequisites

- [ /] I have read and understand the `CONTRIBUTING` guide
- [ /] I looked for duplicate issues before submitting this one

### Description

It would be really great if we had support for a shorter version of the current working directory as the console title, in particular I'm thinking the ability to just have the name of the current folder.

![image](https://user-images.githubusercontent.com/9741849/99048353-59ac1b80-258d-11eb-9bbf-6962574fe8b1.png)

Just as an example, I can't really see what folder I'm in here.

I'm happy to have a go at this myself, but I've never written any go before so it might be a bit of back and forth!

### Environment

- Oh my Posh version: 3.30.* (not sure which one I downloaded but it was a few days ago)
- Theme: Powerline
- Operating System: Windows
- Shell: Powershell
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
Can do! This is set using the `set_console_title` property on settings [here](https://github.com/JanDeDobbeleer/oh-my-posh3/blob/main/engine.go#L142). We could extend this with a `console_title_style` property with the following values:
- `path`
- `folder`

**Comment by catthehacker** [comment]
I've added replacing home directory path with `~` like in prompt: https://github.com/CatTheHacker/oh-my-posh3/blob/520c6e2771110d0e3c3dda48fe7cce3455f45f40/environment.go#L83
and I also was thinking of adding [`oh-my-fish`](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#default)-like style of prompt (https://github.com/CatTheHacker/oh-my-posh3/blob/520c6e2771110d0e3c3dda48fe7cce3455f45f40/segment_path.go#L82) and terminal title but didn't looked into project to figure out how to make configuration for that yet.

**Comment by JanDeDobbeleer** [comment]
@CatTheHacker the replacement of the home path is done in the `path` [segment](https://github.com/JanDeDobbeleer/oh-my-posh3/blob/main/segment_path.go#L68) as the environment needs to return the actual working directory for other tools to work with (which at times, really require the full path as `~` isn't compatible). What we can do is make/extend those function outside of the path segment and reuse them here as well.

**Comment by catthehacker** [comment]
@JanDeDobbeleer Not sure if I know how 😄 I was thinking about exporting the `path` but then the types have to be matched and I haven't dived into whole project to know where is what.
