### ISSUE TITLE
Git Bash Error

### ISSUE THREAD

**Issue by Rafi-99** [JanDeDobbeleer/oh-my-posh#1494]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

bash: oh-my-posh: command not found

This is the error I get whenever I startup Git Bash. I am not sure why it is saying not found.

![image](https://user-images.githubusercontent.com/58924129/147281717-8431155b-6a12-44ad-bb45-13426adf20bf.png)

I get the same issue in the integrated terminal of VSCode too. 

![image](https://user-images.githubusercontent.com/58924129/147281386-824976e9-8433-4993-89f7-93a770c29d4f.png)

However, in Windows Terminal, the theme loads as expected:

![image](https://user-images.githubusercontent.com/58924129/147281448-ce3c210e-c924-4d3f-8231-d537ec8cc137.png)
![image](https://user-images.githubusercontent.com/58924129/147281425-6fbd3993-ac96-4325-90dd-80fc26b25997.png)

P.S. This is a separate question, but I am struggling to enable oh-my-posh for Windows Command Prompt. Could someone guide me on how to go about doing so?

### Theme

microverse-power

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```shell
bash: oh-my-posh: command not found
```

**Comment by JanDeDobbeleer** [comment]
@Rafi-99 how did you install oh-my-posh? Because if you want it to be available, it needs to be in your `PATH`.

**Comment by Rafi-99** [comment]
@JanDeDobbeleer Oh wow! Thank you for replying so fast!

At first, I installed it using PowerShell. Then I ended up installing it using chocolatey. I believe I have 2 installations of oh-my-posh on my machine since I got confused. 

How do I add it to my path correctly?

**Comment by JanDeDobbeleer** [comment]
@Rafi-99 I suggest to install using Winget or scoop. That's official and will also add it to PATH. You can follow the guide for Windows [here](https://ohmyposh.dev/docs/windows), that also contains all you need to know for CMD. First, uninstall the current ones so there's no conflicts possible.

**Comment by Rafi-99** [comment]
@JanDeDobbeleer Alright, thank you so much! I will let you know how it goes.

**Comment by Rafi-99** [comment]
@JanDeDobbeleer I installed it using Winget as you suggested.  Got it working in Powershell natively. Windows Terminal profiles for Powershell and Git Bash work. However, the original issue of the native Git Bash and VSCode integrated terminal is still not working.

![image](https://user-images.githubusercontent.com/58924129/147288468-36ccacd2-844f-49db-ae6e-d93bd2ff85b2.png)

Could you guide me to where I should look next?

**Comment by JanDeDobbeleer** [comment]
The only thing I can think off is either the Profile which is different on vscode and/or the PATH that doesn't contain the right entry for oh-my-posh.

**Comment by Rafi-99** [comment]
@JanDeDobbeleer Okay, thanks. For the native Git Bash issue, do you suggest looking at the PATH as well?

![image](https://user-images.githubusercontent.com/58924129/147298206-a6c7c876-7f2b-4e5d-8268-4efc20e8dd62.png)

I do have oh-my-posh in my PATH correctly I think. The scope is user and not system though

![image](https://user-images.githubusercontent.com/58924129/147298503-cd5b0dd4-b221-4922-b8c5-71e1ac469d7f.png)

Lastly, I have this in my .bashrc
```bash
eval "$(oh-my-posh --init --shell bash --config ~/microverse-power.omp.json)"
```

Appreciate any help you can provide.

**Comment by Rafi-99** [comment]
Never mind, I believe I have fixed the issue. The issue was with Git Bash not finding the required variables in my path at all. Maybe all I needed was a reboot, but adding this one-liner to my .bashrc saved the day!

```bash 
PATH=$PATH:/c/Users/rafim/AppData/Local/Programs/oh-my-posh/bin
```

Now, it's working as intended :)

![image](https://user-images.githubusercontent.com/58924129/147299309-6a446dd5-103f-41b5-a658-8d5678ab7969.png)
![image](https://user-images.githubusercontent.com/58924129/147299311-c3aa54a3-537e-418d-8a63-9eec8ab4aaca.png)
