### ISSUE TITLE
Docs Text Segment Template Property & JanDeDobbeleer Schema

### ISSUE THREAD

**Issue by mattcargile** [JanDeDobbeleer/oh-my-posh#1512]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I got kind of confused with the docs when converting my `envvar` segment to `text`. Should the below doc .md point to the `text` property instead of `template`?

https://github.com/JanDeDobbeleer/oh-my-posh/blob/5d1cd6209a879e9061a63607e08b535d1311468d/docs/docs/segment-text.md?plain=1#L40

Additionally, would it be ok to add the `"schema"` property to this file? It makes it more convenient to edit it for me.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/5d1cd6209a879e9061a63607e08b535d1311468d/themes/jandedobbeleer.omp.json#L2

This is the code from the other files.

`"$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",`

P.S. @JanDeDobbeleer and team: Love all the work and updates you put in this. It makes it quite a joy to customize everything. I've become quite obsessed. So thank you!

### Theme

Not applicable

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```shell
Not applicable
```

**Comment by JanDeDobbeleer** [comment]
@mattcargile you're right, I forgot to change that. `template` is the official one, `text` is still supported due to backwards compatibility.

And yes, a PR for adding the schema is welcome, it should have that.

**Comment by mattcargile** [comment]
So I've only done a PR for the `"schema"` property add.

I'm not sure what should be done, if anything, on the `template` vs `text` deal. Does the `schema.json` need to be altered too in order to add `template`. Forgive me as I'm not super familiar with how it works.

**Comment by JanDeDobbeleer** [comment]
@mattcargile I’ll fix that 😉
