### ISSUE TITLE
Suppress leading "WSL - " in is OS segment.

### ISSUE THREAD

**Issue by atkinsroy** [JanDeDobbeleer/oh-my-posh#1531]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

With WSL, the OS segment shows "WSL - " in front of the icon. Can this either be removed or add an option to suppress this, please? I just want to see the appropriate Linux icon.

**Comment by JanDeDobbeleer** [comment]
@atkinsroy yes, you can set the `wsl` and `wsl_separator` properties to an empty string. See the [os segment docs](https://ohmyposh.dev/docs/os#properties) for details.

**Comment by atkinsroy** [comment]
Nice. Thankyou.
