### ISSUE TITLE
Incorrectly having extra spaces for right-aligned blocks even after horizontal shift

### ISSUE THREAD

**Issue by shunjiewang** [JanDeDobbeleer/oh-my-posh#154]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

When setting ``horizontal_offset`` to ``1`` for a right-aligned block, there is still an extra space / or is missing background color and only the text was correctly shifted.
![Screenshot 2020-11-13 173455](https://user-images.githubusercontent.com/27458788/99135458-2bebc480-25d7-11eb-813c-998c2744b04c.png)

### Environment

- Oh my Posh version: 3.34.0
- Theme: powerlevel10k_classic
- Operating System: Windows 10 20H2
- Shell: PowerShell 5.1
- Terminal: Windows Terminal 1.4.3141.0

### Steps to Reproduce

1. In ``powerlevel10k_classic.json``, adding ``"horizontal_offset": 1`` to a right-aligned prompt.

**Expected behavior:**
On a earlier version released around 10/28, there is no missing background color.
![Screenshot 2020-11-13 174037](https://user-images.githubusercontent.com/27458788/99136025-c0562700-25d7-11eb-8983-0b0e358d16a1.png)

**Actual behavior:** Background color is either missing or there is an extra space on version ``3.34.0`` for right-aligned block.

**Comment by JanDeDobbeleer** [comment]
I think I know why this happens. The colors are reset after every segment since a while to resolve another bug on Powershell. I'll check if something is off in the timing of this.

**Comment by JanDeDobbeleer** [comment]
I have the same "issue", but it's due to the icon going out of bounds of the text area of the terminal. You can see this effect here where I select the text in my terminal.
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/2492783/99905790-59212c80-2cd3-11eb-9840-a861693c1689.png">

**Comment by JanDeDobbeleer** [comment]
Same as #244
