### ISSUE TITLE
jandedobbeleer theme exception in pwsh 7

### ISSUE THREAD

**Issue by Tyf0x** [JanDeDobbeleer/oh-my-posh#155]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide

- [x] I looked for duplicate issues before submitting this one

### Description

Using the jandedobbeleer theme in powershell 7.1.0 doesn't seem to work and shows an exception in the output of Get-PoshThemes

### Environment

- Oh my Posh version: 3.34.0
- Theme: jandedobbeleer 
- Operating System: w10
- Shell: pwsh 7.1.0
- Terminal: pwsh 

### Steps to Reproduce

1. install and configure a compatible font (Meslo LGM NF in my case)
2. install oh-my-posh using  `Install-Module oh-my-posh -Scope CurrentUser -AllowPrerelease`
3. run `Set-PoshPrompt -Theme jandedobbeleer`
4. [optional] run `Get-PoshThemes`

**Expected behavior:** Show the oh-my-posh pompt

**Actual behavior:**

* prompt not showing:
![image](https://user-images.githubusercontent.com/6980921/99138336-2304fc80-2684-11eb-8321-15f3ea3df676.png)

* jandedobbeleer theme output for `Get-PoshThemes` (all other themes are fine):
![image](https://user-images.githubusercontent.com/6980921/99138323-010b7a00-2684-11eb-80fc-e88773e989d6.png)

### Stack

```
panic: runtime error: index out of range [0] with length 0

goroutine 7 [running]:
main.getWindowTitle(0xf66e29, 0xb, 0xf6c09e, 0x19, 0x0, 0x0, 0x0, 0x0)
        D:/a/oh-my-posh3/oh-my-posh3/environment_windows_win32.go:44 +0xf5
main.(*environment).getWindowTitle(0xc0000050c0, 0xf66e29, 0xb, 0xf6c09e, 0x19, 0xe, 0x10b7260, 0x0, 0x0)
        D:/a/oh-my-posh3/oh-my-posh3/environment_windows.go:54 +0x50
main.(*spotify).enabled(0xc00020e000, 0xf67d46)
        D:/a/oh-my-posh3/oh-my-posh3/segment_spotify_windows.go:12 +0x69
main.(*Segment).enabled(...)
        D:/a/oh-my-posh3/oh-my-posh3/segment.go:89
main.(*engine).setStringValues.func1(0xc00000af24, 0xc000062400, 0xc00000c480, 0x2c, 0xc0000fa0b0)
        D:/a/oh-my-posh3/oh-my-posh3/engine.go:114 +0xc6
created by main.(*engine).setStringValues
        D:/a/oh-my-posh3/oh-my-posh3/engine.go:111 +0x105
```

**Comment by Tyf0x** [comment]
Oh, looking at the stack I guessed the segments that was breaking the theme: spotify.

Removing the segment from the theme fixes the issue.

Spotify isn't installed on my machine, but should that throw?

**Comment by nwykes** [comment]
Looks like a duplicate of #153

**Comment by Tyf0x** [comment]
Yup, apologies, closing
