### ISSUE TITLE
Azure segment: Indicator showing context (Azure CLI or PowerShell)

### ISSUE THREAD

**Issue by Marc013** [JanDeDobbeleer/oh-my-posh#1562]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be great when segment _Azure_ would show if the information is retrieved from a PowerShell context (".azure/AzureRmContext.json" [function: getAzureRmContext]), Azure CLI context (".azure/azureProfile.json" [function: getAzureProfile]) or both.
Color coding or icon might do the trick.

**Comment by Marc013** [comment]
@JanDeDobbeleer,
Can you please inform us how this update can be used?

**Comment by JanDeDobbeleer** [comment]
@Marc013 you can make use of the `.Origin` variable inside the `template` which contains `CLI` or `PWSH` based on where we retrieved the info from. I notice I forgot to add the info to the docs, will fix.

**Comment by Marc013** [comment]
@JanDeDobbeleer,
Thanks for this info!

I do notice it isn't shown when both contexts are available.
When I first login to Azure using pwsh and secondly using Azure CLI is only see the latter. This is confusing. Might it be possible to indicate both contexts are present in this situation?

My experience:

![image](https://user-images.githubusercontent.com/28644241/149472668-69497fba-bc9c-41d5-9dcb-144516996dae.png)

![image](https://user-images.githubusercontent.com/28644241/149474219-d2ef8442-5c5c-4280-8cf2-8901ccefa62d.png)

**Comment by JanDeDobbeleer** [comment]
I currently take CLI first and stop when that one's present. Or we have to split these but the that becomes two segments basically. Ad you can have a different account looking at both. What would be the best option?

**Comment by Marc013** [comment]
The account used is not of interest for me. Knowing I don't need to sign in anymore is (either pwsh or cli).

You might want to add logic in the segment that checks if both contexts are present and indicate this like _'CLI | PWSH'_.

**Comment by PixelRobots** [comment]
> I currently take CLI first and stop when that one's present. Or we have to split these but the that becomes two segments basically. Ad you can have a different account looking at both. What would be the best option?

Hey @JanDeDobbeleer I know this is a closed issue, but I am wondering how to display both if needed.

**Comment by JanDeDobbeleer** [comment]
Allow me to add something for that.

**Comment by JanDeDobbeleer** [comment]
@PixelRobots I have a solution ready but want to double check something. Do you have both installed? I need to know if the files are under `.azure` or `.Azure` or both.

**Comment by PixelRobots** [comment]
Yes, I have both installed. I only have a .azure folder

**Comment by JanDeDobbeleer** [comment]
@PixelRobots once this merges, you will be able to have two az segments where one can look at pwsh, the other at the cli.

**Comment by PixelRobots** [comment]
Amazing. Thank you!

**Comment by JanDeDobbeleer** [comment]
@PixelRobots be aware the PowerShell module somehow can't publish anymore, I have yet to look into that. Winget/scoop are up to date.

**Comment by PixelRobots** [comment]
Works perfectly. Thanks :)
![image](https://user-images.githubusercontent.com/22979170/157460709-d0b28cb0-f32b-44b0-8dbb-b338d92ad3c5.png)

**Comment by Marc013** [comment]
@PixelRobots,

Can you please share how you defined the two Az segments in you theme?
When I specify the segment twice it displays the CLI result twice or PWSH when not logged in using the CLI.

**Comment by PixelRobots** [comment]
Make sure you are using the most up to date version of the software. I used Winget to install.

**Comment by Marc013** [comment]
@PixelRobots,
I also used Winget for installation, and daily upgrade 😉
The current version I use is 7.59.2

![image](https://user-images.githubusercontent.com/28644241/162014463-9eb26aa8-1a10-4b20-8680-bd1099dd30fd.png)

Az segment in my theme:

```JSON
{
  "background": "#0674fa",
  "foreground": "#000000",
  "powerline_symbol": "\ue0b0",
  "source": "pwsh",
  "style": "diamond",
  "template": " \ufd03 {{ .Name }} {{ .Origin }} ",
  "type": "az"
},
{
  "background": "#0674fa",
  "foreground": "#000000",
  "powerline_symbol": "\ue0b0",
  "source": "cli",
  "style": "diamond",
  "template": " {{ .Name }} {{ .Origin }} ",
  "trailing_diamond": "\ue0b0",
  "type": "az"
}
```

Can you perhaps point out the mistake I'm making?

**Comment by PixelRobots** [comment]
the source line should look like:

 "properties": {
            "source": "cli"
          },
 
 Here is mine:

         {
          "background": "#008AD7",
          "foreground": "#000000",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "source": "cli"
          },
          "style": "powerline",
          "template": " \ufd03 {{ .Name }} [ {{ .Origin }} ] ",
          "type": "az"
        },
        {
          "background": "#012456",
          "foreground": "#FFFFFF",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "source": "pwsh"
          },
          "style": "powerline",
          "template": " \ufd03 {{ .Name }} [ {{ .Origin }} ] ",
          "type": "az"
        }

**Comment by Marc013** [comment]
@PixelRobots,
That did the trick. Thank you very much❗

**Comment by PixelRobots** [comment]
Glad you got it working.
