### ISSUE TITLE
Az segment does not update in WSL2

### ISSUE THREAD

**Issue by rossmeyer1** [JanDeDobbeleer/oh-my-posh#1567]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I believe this to be a casing issue.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segment_az.go

In Ubuntu 20.04.3 LTS (WSL2), the AzureRMContext.json file is in /home/XXXX/.Azure with the file name AzureRmContext.json.

And (I believe) the AzureProfile.json exists in the same place ONLY if the Save-AzProfile cmdlet has been used. Interestingly, I can't see that this cmdlet exists anymore [this page returns a 404](https://docs.microsoft.com/en-us/powershell/module/az.accounts/Save-AzProfile) but DOES exist in the latest Az.Accounts module (perhaps deprecated?). (Get-Module | Where-Object Version -eq '2.7.1').ExportedCommands.

Interestingly, after changing the path to .azure and changing the file names to match the segment code, this **does** then show the segment the **first** time the prompt is reloaded, however, after that, switching contexts to a different subscription fails to update the segment again.

Here is the segment code, for reference.
`{
                    "type": "az",
                    "style": "diamond",
                    "leading_diamond": "\uE0B2",
                    "trailing_diamond": "<transparent,#516BEB>\uE0B2</>",
                    "powerline_symbol": "\uE0B0",
                    "foreground": "#ffffff",
                    "background": "#516BEB",
                    "properties": {
                        "template": "{{ .Name }} - {{ .ID }}",
                        "prefix": " \uFD03 "
                    }
                }`

### Theme

clean-detailed

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

powershell

### Log output

```shell
2022/01/13 17:07:58 error: getFileContent
open /home/XXXX/.azure/azureProfile.json: no such file or directory
open /home/XXXX/.azure/azureRmContext.json: no such file or directory
```

**Comment by JanDeDobbeleer** [comment]
@GHRoss yes, apparently someone somewhere decided to have non-standard folder name when it comes to this and AZ CLI. I have no words for this tbh. I will try to validate on both names, but that could always still have a weird side effects in case both are present (I don't expect it, but it can).

**Comment by rossmeyer1** [comment]
This now seems to be broken again, but with a different error this time and it's not seeing the context at all.

'unable to create text based on template'

This is on the very latest version, but was working on 6.47.0.

EDIT - This is because of this (I guess technically?) breaking change. https://github.com/JanDeDobbeleer/oh-my-posh/commit/2ea2e633b8caf55015ce3eea4426e323748216ec

Changed .Name to .UserName in the template and it's working again.

**Comment by JanDeDobbeleer** [comment]
@GHRoss yes, that was a remnant of the template additions. Something I missed and decided not to include it as a breaking change in the assumption nobody would add their User.Name to the segment (which was broken).
