### ISSUE TITLE
Enhance dotnet segment to support .Net framework

### ISSUE THREAD

**Issue by PilotBob** [JanDeDobbeleer/oh-my-posh#1568]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Enhance the dotnet segment to recognize if the folder contains a .Net framework project vs a dotnet core project.

Some suggestions are on the discussion such as parsing the project files and looking at the TargetFrameworkVersion element. 

I don't see an easy way to do this if only the .sln file is in the folder however, perhaps drilling into one of the projects in the solution and looking at that.

**Comment by JanDeDobbeleer** [comment]
@PilotBob can you add some example files here for reference?

**Comment by PilotBob** [comment]
It seems like there are several options. I guess the question is, what is the expectation of this segment? Is it to show you what dotnet cli version you would run if you type dotnet in the shell, or is it to show you the .net version that the project in the current folder is targeting?

**Comment by JanDeDobbeleer** [comment]
@PilotBob dotnet CLI. That's how it's always been designed.

**Comment by PilotBob** [comment]
@JanDeDobbeleer  Ok, my expectation was that when I cd into a folder with .net code, it would show up and would show what version is being used by/for that project. If that's not the goal, I get it. 

There are two types of project files. Legacy projects:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{35EC500A-DFD3-405A-821D-9CACFBECEBF1}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>DotNetEmptyProject</RootNamespace>
    <AssemblyName>DotNetEmptyProject</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

SDK Projects: (new style)

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

You can actually target netstandard, net framework (for some project types), net core, net in the SDK project. 

The <TargetFrameworkVersion /> element should be in a legacy project.
The  <TargetFramework /> element should be in all SDK projects.

There is no distinction in a .sln file sadly.

Do with this what you will.

**Comment by PilotBob** [comment]
I think it's also possible to code .net without a solution or project. Probably the exception to the rule though, since msbuild really needs at least a project file afaik.

**Comment by SpaceShot** [comment]
I see value in this idea.  Just with .net core/.net 5+, if you have multiple folders with projects/solutions in them it would be nice (I think) to have the prompt tell you "if you ran dotnet run right now here is the version this is running under".  I don't know if that's difficult to figure out or would slow the prompt down.  

At the same time, when going back to a folder with a .net framework project, that would be nice feedback as well... maybe it should even be something I could turn red when an out-of-support NetFx or NetCore/Net5+ version is being targeted.

I'm new to oh-my-posh but loving it so far and will see what I can come up with as to the how and maybe see if I can get a really crummy version of it going that would probably be unbearably slow.

**Comment by babieiev** [comment]
> I see value in this idea. Just with .net core/.net 5+, if you have multiple folders with projects/solutions in them it would be nice (I think) to have the prompt tell you "if you ran dotnet run right now here is the version this is running under". I don't know if that's difficult to figure out or would slow the prompt down.
> 
> At the same time, when going back to a folder with a .net framework project, that would be nice feedback as well... maybe it should even be something I could turn red when an out-of-support NetFx or NetCore/Net5+ version is being targeted.
> 
> I'm new to oh-my-posh but loving it so far and will see what I can come up with as to the how and maybe see if I can get a really crummy version of it going that would probably be unbearably slow.

Unfortunately, it seems like it is not possible to check .NET version in working folder using CLI. [`dotnet` command uses the latest SDK installed on the machine](https://learn.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version), even if the project targets an earlier version of the .NET runtime. Only global.json can affect it, but it is used quite rarely.

I imagine it's possible to determine which of the installed SDKs corresponds to a particular TFM (framework moniker) and display it, but it can take an unacceptably long time.

Moreover, if the project targets multiple versions, `dotnet` (CLI) cannot decide for you which version of the runtime to run until you specify it via the `--framework` option. Therefore, it is even theoretically impossible to determine which version will be launched in this case (only you decide) 😅.

As I understand, the author of this issue suggested displaying raw TFMs. I think this is a completely acceptable solution that would be useful to many people (including me). However, this completely changes the output of a segment that many people already use.

So, my suggestion is to create a new segment (e.g. dotnet_target) that will parse .NET project file and show `<TargetFramework(s)></>` contents (if there is a `.csproj`, `.vbproj` or `.fsproj` file in the folder). Maybe I'll try to implement it, but I'm not very familiar with Go.
