### ISSUE TITLE
Inherit terminal theme colours

### ISSUE THREAD

**Issue by amzon-ex** [JanDeDobbeleer/oh-my-posh#1575]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

How would it be to have a consistent way to let an omp theme inherit the colors of Windows Terminal colour schemes by default, so that the colour code is consistent throughout? 
The functionality of palettes is very useful, but the palette colours need to be changed manually to match the theme, even though it allows us to not write out the colours explicitly a thousand times. If only one could refer to the terminal colour palette somehow...

**Comment by JanDeDobbeleer** [comment]
@amzon-ex using the default [16 color palette names](https://ohmyposh.dev/docs/config-colors#standard-colors) should do the trick already.

**Comment by amzon-ex** [comment]
@JanDeDobbeleer Even if the colours are named differently in the scheme? For instance, the scheme I use lists "brightGreen" and not "lightGreen".

**Comment by JanDeDobbeleer** [comment]
@amzon-ex should be the same as they use the base ANSI reference, the name is something we added from within oh-my-posh and is not used for rendering the prompt.

**Comment by amzon-ex** [comment]
Alright. Since this request seems redundant, I'm closing this issue. Sorry for the inconvenience!

**Comment by JanDeDobbeleer** [comment]
@amzon-ex happy you got it working!
