### ISSUE TITLE
Colors are not rendering (Git Bash - Windows 10)

### ISSUE THREAD

**Issue by LukeIsHereToDevelop** [JanDeDobbeleer/oh-my-posh#1578]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

I don't know why but the colors are not rendering.
I'm using Git Bash on Windows Terminal.

![Image](https://user-images.githubusercontent.com/43251906/149527084-01188b6f-6532-48f1-98e1-6b4583aa0fe9.png)

Also, I don't know if it is an useful information, but:

![Immagine 2022-01-14 150306](https://user-images.githubusercontent.com/43251906/149527753-b77b48a6-592a-4fc9-b755-22a1a506987c.png)

The debug command correctly renders the segments.

### Theme

The default one. (I tried with bubbles too)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```shell
2022/01/14 14:36:31 debug: getenv
C:\Users\Luca\AppData\Local
2022/01/14 14:36:31 getenv duration: 0s, args: LOCALAPPDATA
2022/01/14 14:36:31 getCachePath duration: 0s, args:
2022/01/14 14:36:31 getArgs duration: 0s, args:
2022/01/14 14:36:31 getArgs duration: 0s, args:
2022/01/14 14:36:31 getShellName duration: 0s, args:
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/01/14 14:36:31 isRunningAsRoot duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getShellName duration: 0s, args:
2022/01/14 14:36:31 getCurrentUser duration: 0s, args:
2022/01/14 14:36:31 getHostName duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: SSH_CONNECTION
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: SSH_CLIENT
2022/01/14 14:36:31 getCurrentUser duration: 0s, args:
2022/01/14 14:36:31 getRuntimeGOOS duration: 0s, args:
2022/01/14 14:36:31 getHostName duration: 0s, args:
2022/01/14 14:36:31 isRunningAsRoot duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getArgs duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getRuntimeGOOS duration: 0s, args:
2022/01/14 14:36:31 getRuntimeGOOS duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getRuntimeGOOS duration: 0s, args:
2022/01/14 14:36:31 stackCount duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getRuntimeGOOS duration: 0s, args:
2022/01/14 14:36:31 hasCommand duration: 20.5817ms, args: git.exe
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 error: hasParentFilePath
CreateFile C:\.git: Impossibile trovare il file specificato. (translated: cannot find the specified file)
2022/01/14 14:36:31 hasParentFilePath duration: 998.1µs, args: .git
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: VIRTUAL_ENV
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: CONDA_ENV_PATH
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: CONDA_DEFAULT_ENV
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: PYENV_VERSION
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 debug: getenv

2022/01/14 14:36:31 getenv duration: 0s, args: JAVA_HOME
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getBatteryInfo duration: 3.5218ms, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 executionTime duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 isRunningAsRoot duration: 0s, args:
2022/01/14 14:36:31 getcwd duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getPathSeperator duration: 0s, args:
2022/01/14 14:36:31 getShellName duration: 0s, args:
2022/01/14 14:36:31 getCurrentUser duration: 0s, args:
2022/01/14 14:36:31 getHostName duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@LukeIsHereToDevelop weird, there's zero difference in rendering when it comes to non-debug and debug. There seem to be others experiencing this issue as well, adding the [following](https://github.com/gulpjs/gulp/issues/1292#issuecomment-332407627) to `.bashrc` seems to do the trick.

```bash
export FORCE_COLOR=true
```

**Comment by bradleylandis** [comment]
I'm having the same problem on ZSH/MacOS 12.1.

This was in Terminal.  The colors look fine in iTerm 2.

**Comment by JanDeDobbeleer** [comment]
@bradleylandis yes, Terminal doesn't come with color support out of the box. That's also mentioned in the docs.

**Comment by LukeIsHereToDevelop** [comment]
Hmm, I tried with `export FORCE_COLOR=true` and `export FORCE_COLOR="1"`, but it still doesn't work. I think I'll temporarily switch to PowerShell (it works perfectly on it) because Oh My Posh seems so cool to see haha.

**Comment by JanDeDobbeleer** [comment]
@LukeIsHereToDevelop did you also try updating git? Seems like we have some issues on older versions.

This also popped up:

> Click next until you'll prompt to choose to Configure the terminal emulator to use with Git Bash, here you select Use Windows default console window (instead of the default option which use [MinTTY](https://mintty.github.io/) as terminal emulator)

And this one (which is different compared to what you tried, see **Windows** system variable):

> Was helped in another thread - Created a windows system variable FORCE_COLOR and had it set to true, did not restart, and now I have colors in Git Bash (windows 7)

**Comment by JanDeDobbeleer** [comment]
@LukeIsHereToDevelop what's the output of `curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/ | bash`

It should render colors correctly, if not it's an issue with either your setup/git bash version (but not oh-my-posh).

![image](https://user-images.githubusercontent.com/2492783/156882630-8fc9eea0-e0ca-437f-8d3f-d3bc6f68a5cf.png)
