### ISSUE TITLE
Configurable handling for oh-my-posh data path

### ISSUE THREAD

**Issue by ralish** [JanDeDobbeleer/oh-my-posh#1589]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The [v6.47.4](https://github.com/JanDeDobbeleer/oh-my-posh/commit/37e96ef96825da899d805302eb72ac0dba098288) release introduced a change where the _oh-my-posh_ "data" files (binary and themes) are now stored in an `.oh-my-posh` directory under the user's home directory. There's nothing wrong with that, but it does add further clutter to the user's home directory, especially on Windows systems where directories with a leading dot are not hidden.

I'd like to suggest improving on this by using the same general approach as implemented in #1017. To summarize for each platform:

**Windows**
Retrieve the `$env:LOCALAPPDATA` variable and append `oh-my-posh` to the path. Note this will mean using the same path as is being used for the cache, but I don't think that's a problem? The current behaviour could be used as a fallback in the event something goes wrong attempting to use the `$env:LOCALAPPDATA` path.

**Unix-like**
Conform to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) by checking for the existence of `$XDG_DATA_HOME`, and if it exists, use `$XDG_DATA_HOME/oh-my-posh`. Otherwise, fallback to `$HOME/.local/share/oh-my-posh` (per the specification). Finally, the existing behaviour could be used if all else fails.

These changes will ensure _oh-my-posh_ stores its data files in the standard/canonical locations on each platform.

**Comment by JanDeDobbeleer** [comment]
@ralish fair point. I actually forgot we did that as I was working in PowerShell and not go when it comes to this feature.

**Comment by ShrykeWindgrace** [comment]
I'd like to chime in with a nix-based setup, where actual files would be stored somewhere in `/nix/store/` and env vars/symlinks would be put in place for the software to use.

It might also be beneficial to have a way to manually set POSH_PATH/POSH_THEMES_PATH (they seem to be hardcoded right now) which would have priority over XDG paths, but being conform with XDG is already a great thing to have.

Cheers!

**Comment by JanDeDobbeleer** [comment]
@ralish this is only an issue for the PowerShell module and I'm not going to resolve this for that installation methods as it's not advised anymore (due to annoyances like this). Installing with Winget/brew will add the files correctly without overhead.

**Comment by ralish** [comment]
@JanDeDobbeleer That's a shame, as the convenience of just doing `Install-Module oh-my-posh` is hard to beat, especially on systems where more general package managers like `winget` or `scoop` aren't available and can't/shouldn't be installed.

On Linux systems the `oh-my-posh` package generally isn't present in the native package management repositories by default, but PowerShell is once you've installed Microsoft's Apt/Yum repository. Once you've got PowerShell installed, you can then just use `Install-Module`.

Regardless, thanks for all your work on this fantastic software!

**Comment by JanDeDobbeleer** [comment]
@ralish maybe I went about it wrong. Allow me to try again, but it'll require duplicate logic.
