### ISSUE TITLE
.OS environmental variable is capitalized in WSL, but lower-case otherwise

### ISSUE THREAD

**Issue by RustyBrakes** [JanDeDobbeleer/oh-my-posh#1593]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When referencing .OS as an environmental variable, I've found that a native Linux install shows as ".OS=debian" but on WSL I get ".OS=Debian". The same happens with ".OS=ubuntu" (native) and ".OS=Ubuntu" (WSL).

**Desired behaviour**
- WSL distro name stays capitalized when used in the OS Segment (depends on display_distro_name=true)
- WSL distro name should be all lower case in the .OS env variable for consistency with non-WSL installs

### Theme

Custom theme. Use following segment for example:

```
{
          "type": "path",
          "style": "plain",
          "foreground_templates": [
            "{{ if eq .OS \"ubuntu\" }}#E95420{{ end }}",
            "{{ if eq .OS \"debian\" }}#d70651{{ end }}",
            "{{ if eq .Shell \"pwsh\" }}#7FD5EA{{ end }}",
            "{{ if eq .OS \"windows\" }}#19B7A4{{ end }}",
            "#3EC669"
          ],
          "properties": {
            "enable_hyperlink": true,
            "max_depth": 2,
            "prefix": "",
            "postfix": "",
            "folder_icon": "\uf6d7",
            "style": "agnoster_short"
          }
},
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```shell
WSL DEBIAN
2022/01/16 17:43:19 debug: getenv
Debian
2022/01/16 17:43:19 getenv duration: 1.37µs, args: WSL_DISTRO_NAME
2022/01/16 17:43:19 getcwd duration: 140ns, args:
2022/01/16 17:43:19 debug: getenv
Debian
2022/01/16 17:43:19 getenv duration: 1.05µs, args: WSL_DISTRO_NAME

WSL UBUNTU
2022/01/16 17:44:47 debug: getenv
Ubuntu
2022/01/16 17:44:47 getenv duration: 1.12µs, args: WSL_DISTRO_NAME
```

**Comment by JanDeDobbeleer** [comment]
@RustyBrakes your desired behaviour is impossible due to these being the same variable. You can't technically have two variables with the same name in a template, so we need to choose. I would opt to lowercase all. You can always change the icon to translate that to a name with casing.

**Comment by RustyBrakes** [comment]
That's a good suggestion @JanDeDobbeleer thanks!
