### ISSUE TITLE
Ability to keep settings of Themes when updating

### ISSUE THREAD

**Issue by SirTwsted** [JanDeDobbeleer/oh-my-posh#1603]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

When updating, it seems like it wipes out ALL settings a user has done for a particular theme.
If a person set a theme just the way they want & like, when updating, the update tends to wipe out all themes user settings.

I am REALLY lucky I made a backup of the .json theme file on a thumb-drive, otherwise all my settings, colors
and other things I have set for a particular theme would have been permanently lost.

Maybe you can create a **_user_** folder in the themes folder that the update ignores & doesn't erase,
when a user places a costumed configured a theme in the user folder.  or something.....

**Comment by JanDeDobbeleer** [comment]
You have to move that theme to a location that's outside of the standard theme files as highlighted in the docs. We don't have a way to know what you altered on `Import-Module` or installation.
