### ISSUE TITLE
prompt broke after upgrading via winget

### ISSUE THREAD

**Issue by homie-desktop** [JanDeDobbeleer/oh-my-posh#1609]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

prompt broke after updating via Winget:

`winget upgrade JanDeDobbeleer.OhMyPosh`

![omp](https://user-images.githubusercontent.com/60292566/150035562-22e9efa8-b6f0-4c02-8567-25b39c56c61b.jpg)

### Theme

atomicbit.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
unable to create text based on template
```

**Comment by JanDeDobbeleer** [comment]
Please read the [release notes](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v7.0.0).
