### ISSUE TITLE
Update-Module oh-my-posh   7.4.0  Error  “a valid zip archive.”  

### ISSUE THREAD

**Issue by Archer456** [JanDeDobbeleer/oh-my-posh#1618]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

update to 7.4.0  
I use powershell 7.2.1
step:
1 winget upgrade JanDeDobbeleer.OhMyPosh

2 powershell7 :
Update-Module oh-my-posh

then ：
`PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Updating oh-my-posh executable to 7.4.0
Invoke-WebRequest:  Received an unexpected EOF or 0 bytes from the transport stream.

Downloading oh-my-posh themes for 7.4.0
Invoke-WebRequest:  Received an unexpected EOF or 0 bytes from the transport stream.

Import-Module: C:\Users\Archer\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:1
Line |
   1 |  Import-Module oh-my-posh
     |  ~~~~~~~~~~~~~~~~~~~~~~~~
     | File 'C:\Users\Archer\AppData\Local\Temp\tmp4B6D.zip' does not appear to be a valid zip archive.

Updating oh-my-posh executable to 7.4.0
Downloading oh-my-posh themes for 7.4.0
Set-PoshPrompt: C:\Users\Archer\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:3
Line |
   3 |  Set-PoshPrompt powerlevel10k_rainbow
     |  ~~~~~~~~~~~~~~
     | The 'Set-PoshPrompt' command was found in the module 'oh-my-posh', but the module could not be loaded. For more
     | information, run 'Import-Module oh-my-posh'.`  

### Theme

powerlevel10k_rainbow

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Updating oh-my-posh executable to 7.4.0
Invoke-WebRequest:  Received an unexpected EOF or 0 bytes from the transport stream.

Downloading oh-my-posh themes for 7.4.0
Invoke-WebRequest:  Received an unexpected EOF or 0 bytes from the transport stream.

Import-Module: C:\Users\Archer\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:1
Line |
   1 |  Import-Module oh-my-posh
     |  ~~~~~~~~~~~~~~~~~~~~~~~~
     | File 'C:\Users\Archer\AppData\Local\Temp\tmp4B6D.zip' does not appear to be a valid zip archive.

Updating oh-my-posh executable to 7.4.0
Downloading oh-my-posh themes for 7.4.0
Set-PoshPrompt: C:\Users\Archer\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:3
Line |
   3 |  Set-PoshPrompt powerlevel10k_rainbow
     |  ~~~~~~~~~~~~~~
     | The 'Set-PoshPrompt' command was found in the module 'oh-my-posh', but the module could not be loaded. For more
     | information, run 'Import-Module oh-my-posh'.

Loading personal and system profiles took 43012ms.
```

**Comment by JanDeDobbeleer** [comment]
This works on my end so I would look at your connection (maybe the gallery is blocked somehow), or first try again as maybe GitHub experienced some issues.

**Comment by Archer456** [comment]
> This works on my end so I would look at your connection (maybe the gallery is blocked somehow), or first try again as maybe GitHub experienced some issues.

After I tried many times, it already worked。
Maybe it's a problem with my network, or there is something wrong with the server at that time.
