### ISSUE TITLE
Exception: oh-my-posh: Unsupported architecture:

### ISSUE THREAD

**Issue by Adkimsm** [JanDeDobbeleer/oh-my-posh#1625]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

When I try `Import-Module oh-my-posh`, I get an error:

```
Get-CimInstance: 指定的类不存在。

Exception: oh-my-posh: Unsupported architecture:

```

![图片](https://user-images.githubusercontent.com/75924586/150526451-eb64f564-5b17-4dd0-8a2c-318299751165.png)

### Theme

There is a bug before using the theme.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Write-PoshDebug: The term 'Write-PoshDebug' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by Adkimsm** [comment]
#966 was mentioned, but I'm using 64-bit Windows 11, and I've also tried updating, uninstalling, reinstalling oh-my-posh.

**Comment by Adkimsm** [comment]
oh-my-posh still worked before I update to Windows 11, but after the update there was a problem.

**Comment by Adkimsm** [comment]
![图片](https://user-images.githubusercontent.com/75924586/150529458-4c48bdb3-888a-4167-ba21-5771e1e0ffc6.png)

This is the prompt to install with an older version of Powershell

**Comment by JanDeDobbeleer** [comment]
@Adkinsm2020 what's the output of `Get-CimInstance -Class Win32_Processor -Property Architecture`? That's what we use to identify the architecture. If this really outputs Chinese characters (excuse me if that's not what they are), that's really strange as we expect an int for the `Architecture` property.

**Comment by Adkimsm** [comment]
its meaning,"invalid class" or "no such as class",and it always throw error.
sorry,l am not good at English.i cannot speak it well.
and i am using a android device now,i will send a comment about the output of Get-CimInstance -Class Win32_Processor -Property Architecture.

**Comment by Adkimsm** [comment]
but Get-CimInstance -Class Win32_Processor -Property Architecture command always return some Chinese characters.its meaning is Mentioned above.

**Comment by Adkimsm** [comment]
I think this error may have something to do with upgrading win11

**Comment by Adkimsm** [comment]
before i upgrade win11, i can use oh my posh.but after this i cannot use it.

**Comment by Adkimsm** [comment]
Maybe Microsoft deleted some things when upgrading win11

**Comment by Adkimsm** [comment]
![图片](https://user-images.githubusercontent.com/75924586/150662651-acdc5565-9402-4a04-a696-f148561c5cf3.png)

**Comment by Adkimsm** [comment]
@JanDeDobbeleer What can i do for this bug?

**Comment by JanDeDobbeleer** [comment]
Raise an issue in PowerShell. This is regression on their end.

**Comment by Adkimsm** [comment]
ok,i will close this issue.

**Comment by JanDeDobbeleer** [comment]
@Adkinsm2020 please link the tickets so I can follow-up as well.

**Comment by Adkimsm** [comment]
Ok.

**Comment by Adkimsm** [comment]
What should be the output of `Get-CimInstance -Class Win32_Processor -Property Architecture` if it is normal?

**Comment by Adkimsm** [comment]
powershell team needs it.

**Comment by Adkimsm** [comment]
@JanDeDobbeleer and is's required

**Comment by Adkimsm** [comment]
https://github.com/PowerShell/PowerShell/issues/16802

**Comment by JanDeDobbeleer** [comment]
@Adkinsm2020 

```powershell


[32;1mAvailability                            : [0m
[32;1mCpuStatus                               : [0m
[32;1mCurrentVoltage                          : [0m
[32;1mDeviceID                                : [0mCPU0
[32;1mErrorCleared                            : [0m
[32;1mErrorDescription                        : [0m
[32;1mLastErrorCode                           : [0m
[32;1mLoadPercentage                          : [0m
[32;1mStatus                                  : [0m
[32;1mStatusInfo                              : [0m
[32;1mAddressWidth                            : [0m
[32;1mDataWidth                               : [0m
[32;1mExtClock                                : [0m
[32;1mL2CacheSize                             : [0m
[32;1mL2CacheSpeed                            : [0m
[32;1mMaxClockSpeed                           : [0m
[32;1mPowerManagementSupported                : [0m
[32;1mProcessorType                           : [0m
[32;1mRevision                                : [0m
[32;1mSocketDesignation                       : [0m
[32;1mVersion                                 : [0m
[32;1mVoltageCaps                             : [0m
[32;1mCaption                                 : [0m
[32;1mDescription                             : [0m
[32;1mInstallDate                             : [0m
[32;1mName                                    : [0m
[32;1mConfigManagerErrorCode                  : [0m
[32;1mConfigManagerUserConfig                 : [0m
[32;1mCreationClassName                       : [0m
[32;1mPNPDeviceID                             : [0m
[32;1mPowerManagementCapabilities             : [0m
[32;1mSystemCreationClassName                 : [0m
[32;1mSystemName                              : [0m
[32;1mCurrentClockSpeed                       : [0m
[32;1mFamily                                  : [0m
[32;1mOtherFamilyDescription                  : [0m
[32;1mRole                                    : [0m
[32;1mStepping                                : [0m
[32;1mUniqueId                                : [0m
[32;1mUpgradeMethod                           : [0m
[32;1mArchitecture                            : [0m9
[32;1mAssetTag                                : [0m
[32;1mCharacteristics                         : [0m
[32;1mL3CacheSize                             : [0m
[32;1mL3CacheSpeed                            : [0m
[32;1mLevel                                   : [0m
[32;1mManufacturer                            : [0m
[32;1mNumberOfCores                           : [0m
[32;1mNumberOfEnabledCore                     : [0m
[32;1mNumberOfLogicalProcessors               : [0m
[32;1mPartNumber                              : [0m
[32;1mProcessorId                             : [0m
[32;1mSecondLevelAddressTranslationExtensions : [0m
[32;1mSerialNumber                            : [0m
[32;1mThreadCount                             : [0m
[32;1mVirtualizationFirmwareEnabled           : [0m
[32;1mVMMonitorModeExtensions                 : [0m
[32;1mPSComputerName                          : [0m
[32;1mCimClass                                : [0mroot/cimv2:Win32_Processor
[32;1mCimInstanceProperties                   : [0m{Caption, Description, InstallDate, Name…}
[32;1mCimSystemProperties                     : [0mMicrosoft.Management.Infrastructure.CimSystemProperties





```

**Comment by falcon-Z** [comment]
```
Get-CimInstance: The specified Class does not exist.

Exception: Oh My Posh: Unsupported architecture:
```

I face similar issue and get the above error

**Comment by Adkimsm** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.

**Comment by JanDeDobbeleer** [comment]
@JanDeDobbeleer you're still using the module which is why this is an issue. Please [migrate](https://ohmyposh.dev/docs/migrating) to the executable and you'll be all set.
