### ISSUE TITLE
Half-diamond, arrow style first segment

### ISSUE THREAD

**Issue by springcomp** [JanDeDobbeleer/oh-my-posh#163]
### Prerequisites

- [x ] I have read and understand the `CONTRIBUTING` guide
- [ x] I looked for duplicate issues before submitting this one

### Question

I’m using Powerline on other WSL2 shells with great success.
I like using a style for the first segment that looks like this:

![image](https://user-images.githubusercontent.com/8488398/99229510-68453d80-27ee-11eb-9f93-2c0daf0f473f.png)

I have tried the three available styles `plain`, `powerline` and `diamond` and the closest I could come up with is this:

![image](https://user-images.githubusercontent.com/8488398/99229612-8ad75680-27ee-11eb-9a6e-d13d09fc2286.png)

Is it possible to change the color of the `powerline` symbol so that it takes the background of the segment? This proble only occurs for the first segment obviously.

### Environment

- Oh my Posh version: v3
- Theme: any
- Operating System: WSL2
- Shell: PWSH
- Terminal: Windows Terminal (CaskaydiaCove Nerd Font Mono)

**Comment by JanDeDobbeleer** [comment]
Yes, this is possible, but it's sometimes found by trying a few combinations (there's more than one way). This one specifically can be created by using a plain and diamond segment.

```json
{
  "type": "session",
  "style": "plain",
  "foreground": "#ffffff",
  "background": "#0087AF",
  "properties": {
    "user_info_separator": "@"
  }
},
{
  "type": "session",
  "style": "diamond",
  "foreground": "#ffffff",
  "background": "#585858",
  "trailing_diamond": "\uE0B0",
  "properties": {
    "user_info_separator": "@",
    "prefix": "<#0087AF>\uE0B0</> ",
    "postfix": " "
  }
}
```

Which results into this:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/2492783/99261724-62b31c00-281d-11eb-9446-de26fa6a5db8.png">

**Comment by springcomp** [comment]
Oh, yes, of course.
Thanks

**Comment by springcomp** [comment]
Oh, yes, of course.
Thanks
