### ISSUE TITLE
Error in Readme, wrong file pointing

### ISSUE THREAD

**Issue by 1499360414** [JanDeDobbeleer/oh-my-posh#1637]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!
In the Install->Linux "Download them" manual, it says we will store the json files in **~/.poshthemes/**, but in the edit below, "**$ PROFILE**" points to the "**~/*.json**" folder. The "**.poshthemes**" folder is missing here. This error also appears on this page under "Override theme settings".

![image](https://user-images.githubusercontent.com/82309514/150705702-b538b316-27d1-4102-8594-1328b2556e47.png)

![image](https://user-images.githubusercontent.com/82309514/150705761-5009fb79-1f7e-4ea1-9312-e9f6ff020dd3.png)

Here you should use
`oh-my-posh --init --shell pwsh --config ~/.poshthemes /jandedobbeleer.mp.json | Invoke-Expression`

I know it's not a big bug, but since Oh My Posh's readme is so comprehensive, I think most users will copy and paste the code like I did and then have problems finding the folder

### Theme

The error in readme.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh, bash, fish, powershell, other (please specify)

### Log output

```shell
Oh My Posh Error:
 stat /home/vagrant/amro.omp.json: no such file or directory
```

**Comment by JanDeDobbeleer** [comment]
@1499360414 if you read the paragraph right below Replace your existing prompt, you'll find what you're looking for 😉
