### ISSUE TITLE
Merge trailing diamond of one segment with leading diamond of the other

### ISSUE THREAD

**Issue by mkartikk** [JanDeDobbeleer/oh-my-posh#1638]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

How do merge the leading diamond of one segment with trailing diamond of the other? (When both are exactly the same.)
I there a way to remove the space between the two?

**Comment by JanDeDobbeleer** [comment]
@mkartikk leaving `leading_diamond` empty should do the trick (on the to be merged segment).
