### ISSUE TITLE
Suggestion: use ~ for $HOME in agnoster_full

### ISSUE THREAD

**Issue by springcomp** [JanDeDobbeleer/oh-my-posh#164]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The `path` segment style supports `agnoster` and `agnoster_full`.
Is there a possibility to have the same behaviour of `agnoster_full` whereas replacing `$HOME` with `~`.

![image](https://user-images.githubusercontent.com/8488398/99368159-1d452c00-28bb-11eb-8956-1ac8c5668077.png)

Perhaps an `agnoster_partial` style 😊 ?

### Environment

- Oh my Posh version: v3
- Theme: any
- Operating System: WSL2
- Shell: PowerShell Core
- Terminal: Windows Terminal (Caskaydia Nerd Font Mono)

**Comment by JanDeDobbeleer** [comment]
Can do. Let's simply align them 😀
