### ISSUE TITLE
PowerShell 7.2.1 cannot update to 7.51

### ISSUE THREAD

**Issue by DEberhardt** [JanDeDobbeleer/oh-my-posh#1640]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

### Theme

Personal theme - ParagnosterPlus - Mash of Paradox and AgnosterPlus

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Updating oh-my-posh executable to 7.5.1
Downloading oh-my-posh themes for 7.5.1

Loading personal and system profiles took 51450ms.
 David.Eberhardt  C:\                                                                                      13:56:49
❯
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 44

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

The problem is that the Shell becomes unusable as the output is repeatedly shown upon hitting enter.
Once restarted, the error is repeated.

The same is observed with v7.3.1-preview
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.3.0-preview.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 44

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```

**Comment by DEberhardt** [comment]
This works for PowerShell 5 btw.

**Comment by JanDeDobbeleer** [comment]
@DEberhardt did you upgrade PSReadline as the error comes from them, not oh-my-posh.

Works on my machine for that version (macOS):

![image](https://user-images.githubusercontent.com/2492783/150808988-47d6a6dd-2ec9-41a2-9d56-e02445112c82.png)

**Comment by JanDeDobbeleer** [comment]
@DEberhardt check [this](https://github.com/PowerShell/PSReadLine/issues/3020) issue (same error). Suggestion is to indeed upgrade PSReadline to the latest beta.

**Comment by DEberhardt** [comment]
PSreadline v2.2.0-beta4 - didn't realise I wasn't on this already :)
so far so good.

**Comment by JanDeDobbeleer** [comment]
@DEberhardt so you're still experiencing this issue, right?

**Comment by DEberhardt** [comment]
Actually no - now that I updated, I do not receive it any longer. Both PowerShell 7 and 7 preview are now loading OK.
Sorry not to report sooner, the absence of something is always harder to detect (unless it is the car keys 😄 )

**Comment by JanDeDobbeleer** [comment]
Amazing!
