### ISSUE TITLE
Get-PoshThemes Requiring File Path

### ISSUE THREAD

**Issue by homie-desktop** [JanDeDobbeleer/oh-my-posh#1643]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi, just like to clarify, when `oh-my-posh` is installed via `winget` the `Get-PoshThemes` is requiring a `FilePath` input. So what I did is ` Get-PoshThemes -Path 'C:/Users/castr/AppData/Local/Programs/oh-my-posh/themes'`. Is this the proper way or is there another posh-themes directory? Also when posh is updated, are the newer themes stored there? Thanks! 

### Theme

omp.thecyberden.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Please enter the themes path:
```

**Comment by JanDeDobbeleer** [comment]
Yes to both questions!

**Comment by jamiebarrow** [comment]
I had the same issue. The `FilePath` parameter is defaulted to `$env:POSH_THEMES_PATH` - [see here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/4c4b97fa8b37e0126e91dd3f26f6c378bb864470/src/engine/init/omp.ps1#L242). So I've added the below to my `$PROFILE`:

```powershell
$Env:POSH_THEMES_PATH = "~/AppData/Local/Programs/oh-my-posh/themes/"
```
