### ISSUE TITLE
exitcode segment does not work correctly

### ISSUE THREAD

**Issue by ondrasek** [JanDeDobbeleer/oh-my-posh#1649]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

My prompt is using the `exit` segment with `always_enabled = false`. OMP fails to recognize that the last executed command failed and does not render the segment correctly.

I am using the following script to simulate failure:
```
param($code=99)
echo Hello!
$global:TestError=$code
exit $code
```

When I run the following, I get the expected result:
```
PS> .\test.ps1; echo $?
Hello!
False
```

When I run:
```
PS > .\test.ps1
```

OMP fails to render the `exit` segment. I have also tested this with various other failing utilities with the same result. Documentation clear states, that $? should work as assumed, i.e. $? evaluates to False if $LASTEXITCODE is non-zero. Even though I am getting situations where $? in the Prompt function is True and $LASTEXITCODE is nonzero. I have attached my experimental OMP module for reference.

With experimentation, I found out that the problem is in the Prompt function generated by OMP. For some reason, $? always evaluates to $true. 

When I add the following statement (manually) at the beginning of the generated config, I get the correct result.
```
[ScriptBlock]$Prompt = {
    #store if the last command was successful
    $lastCommandSuccess = $?
    #store the last exit code for restore
    $realLASTEXITCODE = $global:LASTEXITCODE
    $lastCommandSuccess = $lastCommandSuccess -and ($realLASTEXITCODE -eq 0)
```

My entire OMP init test module here:
[test-omp-init.ps1.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/7935334/test-omp-init.ps1.txt)

Why the $? does not work eludes me. Even though my GO is a bit rusty, I am happy to submit a pull request.

### Theme

{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",

  "palette": {
	  "runtimeVersion": "lightGray",
	  "runtimeVersionBackground": "black"
  },

  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{.UserName}} {{.Shell}} in {{.PWD}}",
  "final_space": false,
  "osc99": true,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "session",
          "style": "plain",
          "properties": {
            "prefix": "╭─[",
            "postfix": "]─",
            "template": "<#ffff55>{{ .UserName }}</>"
          }
        },
        {
          "type": "path",
          "style": "plain",
          "foreground": "#ff5555",
          "properties": {
            "prefix": "<#ffffff>[</>",
            "postfix": "<#ffffff>]</>",
            "style": "folder",
            "enable_hyperlink": true
          }
        },
        {
          "type": "root",
          "style": "plain",
          "foreground": "#FF9248",
          "properties": {
            "prefix": "<#ffffff>─(</>",
            "postfix": "<#ffffff>)</>",
            "root_icon": "#"
          }
        },
		{
		  "type": "executiontime",
		  "style": "plain",
		  "foreground": "yellow",
		  "background": "black",
		  "properties": {
			  "style": "austin",
			  "threshold": 500,
			  "prefix": "<#fefefe>─[\ufbab</>",
			  "postfix": "<#fefefe>]</>"
		  }
		}
      ]
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
		{
			"type": "kubectl",
			"style": "plain",
			"foreground": "p:runtimeVersion",
			"background": "p:runtimeVersionBackground",
			"properties": {
				"prefix": "(\uFD31 ",
				"postfix": ")",
				"template": "{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}"
			}
		},
        {
          "type": "dotnet",
		  "style": "plain",
		  "foreground": "p:runtimeVersion",
		  "background": "p:runtimeVersionBackground",
		  "properties": {
			"prefix": "(.net v",
			"postfix": ")",
			"home_enabled": true,
			"display_mode": "files",
			"display_version": true
		  }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "properties": {
            "prefix": "",
            "postfix": "",
            "text": "╰─"
          }
        },
        {
          "type": "git",
          "style": "plain",
          "foreground": "#e0f8ff",
          "properties": {
            "prefix": "<#ffffff>[</>",
            "postfix": "<#ffffff>]</>",
            "branch_icon": "\ue725 ",
            "fetch_status": true,
            "fetch_upstream_icon": true,
            "template": "{{ .HEAD }}{{ if .Staging.Changed }}<#00AA00> ● {{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }}<#D75F00> ● {{ .Working.String }}</>{{ end }}"
          }
        },
		{
          "type": "exit",
          "style": "plain",
          "foreground": "#ecf7fa",
		  "background": "black",
          "properties": {
			"prefix": "<#fefefe>─[</>",
            "postfix": "<#fefefe>]</>",
            "always_enabled": false,
			"template": "<#e91e63>{{ if gt .Code 0 }}!{{ end }}{{ .Code }}</>"
          }
        },
		{
		  "type": "text",
		  "style": "plain",
		  "foreground": "#fefefe",
		  "background": "black",
		  "properties": {
			"prefix": "",
            "text": "\ue285ﬀ"
		  }
		}
      ]
    }
  ]
}

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
[1mVersion:[0m 6.49.2

[1mSegments:[0m

ConsoleTitle(true) -   0 ms - 
session(true)  -   0 ms - [38;2;195;134;241m[0m[48;2;195;134;241m[38;2;255;255;255m [0m[48;2;195;134;241m[38;2;255;255;255mondra-pragmax@GOTHMOG[0m[48;2;195;134;241m[38;2;255;255;255m [0m[38;2;195;134;241m[0m
path(true)     -   0 ms - [38;2;255;71;156;49m[7m[0m[48;2;255;71;156m[38;2;255;255;255m  [0m[48;2;255;71;156m[38;2;255;255;255moh-my-posh[0m[48;2;255;71;156m[38;2;255;255;255m [0m[38;2;255;71;156m[0m
git(true)      -   3 ms - [48;2;255;251;56m[38;2;255;71;156m[0m[48;2;255;251;56m[38;2;25;53;73m [0m[48;2;255;251;56m[38;2;25;53;73mmaster[0m[48;2;255;251;56m[38;2;25;53;73m [0m[38;2;255;251;56m[0m
battery(false) -   1 ms - 
node(false)    -   0 ms - 
shell(true)    -   0 ms - [48;2;0;119;194m[38;2;255;251;56m[0m[48;2;0;119;194m[38;2;255;255;255m ﲵ [0m[48;2;0;119;194m[38;2;255;255;255muni[0m[48;2;0;119;194m[38;2;255;255;255m [0m[38;2;0;119;194m[0m
root(false)    -   0 ms - 
text(true)     -   0 ms - [48;2;255;255;255m[38;2;0;119;194m[0m[48;2;255;255;255m[38;2;17;17;17m [0m[48;2;255;255;255m[38;2;17;17;17mNO CONFIG[0m[48;2;255;255;255m[38;2;17;17;17m [0m[38;2;255;255;255m[0m
exit(true)     -   0 ms - [38;2;255;255;255m[0m[38;2;46;149;153;49m[7m[0m[48;2;46;149;153m[38;2;255;255;255m [0m[48;2;46;149;153m[38;2;255;255;255m [0m[38;2;46;149;153m[0m

[1mRun duration:[0m 6.7795ms

[1mLogs:[0m

2022/01/25 17:24:57 debug: getenv
C:\Users\ondra-pragmax\AppData\Local
2022/01/25 17:24:57 getenv duration: 0s, args: LOCALAPPDATA
2022/01/25 17:24:57 getCachePath duration: 517.9µs, args: 
2022/01/25 17:24:57 getArgs duration: 0s, args: 
2022/01/25 17:24:57 getArgs duration: 0s, args: 
2022/01/25 17:24:57 getShellName duration: 0s, args: 
2022/01/25 17:24:57 debug: getenv

2022/01/25 17:24:57 getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/01/25 17:24:57 isRunningAsRoot duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getShellName duration: 0s, args: 
2022/01/25 17:24:57 getCurrentUser duration: 0s, args: 
2022/01/25 17:24:57 getHostName duration: 0s, args: 
2022/01/25 17:24:57 lastErrorCode duration: 0s, args: 
2022/01/25 17:24:57 environ duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 debug: getenv

2022/01/25 17:24:57 getenv duration: 0s, args: SSH_CONNECTION
2022/01/25 17:24:57 debug: getenv

2022/01/25 17:24:57 getenv duration: 0s, args: SSH_CLIENT
2022/01/25 17:24:57 getCurrentUser duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 getHostName duration: 0s, args: 
2022/01/25 17:24:57 debug: getenv

2022/01/25 17:24:57 getenv duration: 0s, args: POSH_SESSION_DEFAULT_USER
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getArgs duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 stackCount duration: 0s, args: 
2022/01/25 17:24:57 isRunningAsRoot duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getShellName duration: 0s, args: 
2022/01/25 17:24:57 getCurrentUser duration: 0s, args: 
2022/01/25 17:24:57 getHostName duration: 0s, args: 
2022/01/25 17:24:57 lastErrorCode duration: 0s, args: 
2022/01/25 17:24:57 environ duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 hasCommand duration: 3.6557ms, args: git.exe
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 hasParentFilePath duration: 0s, args: .git
2022/01/25 17:24:57 getFileContent duration: 0s, args: C:\Users\ondra-pragmax\Repositories\ondrasek\dotfiles\.git/HEAD
2022/01/25 17:24:57 error: getFileContent
open C:\Users\ondra-pragmax\Repositories\ondrasek\dotfiles\.git/logs/refs/stash: The system cannot find the file specified.
2022/01/25 17:24:57 getFileContent duration: 0s, args: C:\Users\ondra-pragmax\Repositories\ondrasek\dotfiles\.git/logs/refs/stash
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getBatteryInfo duration: 1.5669ms, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 520.3µs, args: *.js
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 0s, args: *.ts
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 0s, args: package.json
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 0s, args: .nvmrc
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 0s, args: pnpm-workspace.yaml
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 0s, args: .pnpmfile.cjs
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 hasFiles duration: 0s, args: .npmrc
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getShellName duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 isRunningAsRoot duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 isRunningAsRoot duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getPathSeperator duration: 0s, args: 
2022/01/25 17:24:57 getShellName duration: 0s, args: 
2022/01/25 17:24:57 getCurrentUser duration: 0s, args: 
2022/01/25 17:24:57 getHostName duration: 0s, args: 
2022/01/25 17:24:57 lastErrorCode duration: 0s, args: 
2022/01/25 17:24:57 environ duration: 0s, args: 
2022/01/25 17:24:57 getRuntimeGOOS duration: 0s, args: 
2022/01/25 17:24:57 getcwd duration: 0s, args: 
2022/01/25 17:24:57 lastErrorCode duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@ondrasek which PowerShell version is this? As that did work and we never changed that part the past half year.

**Comment by ondrasek** [comment]
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by ondrasek** [comment]
It seems @JanDeDobbeleer that the devil is in $? scoping. When I look at: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.2, the sample there says that Write-Error (as an example) sets $? within the scope, but is not visible outside the scope. So:

```
PS> function TestError { ls \NonExistedPath }
PS> TestError; $?
...
True
```

Seems to me that using $? in the prompt to test for success is moot point :/. But I am still kind of new to PowerShell.

**Comment by JanDeDobbeleer** [comment]
That may be, but this did/does work 🤔

**Comment by ondrasek** [comment]
Does not work for me. When I run my TestError, the lastCommandSuccess in Prompt evaluates to True. So it does when I run something like `ls \NONEXISTENTPATH`.

**Comment by ondrasek** [comment]
As an example, I added this to my Prompt:
```
[ScriptBlock]$Prompt = {
    #store if the last command was successful
    $lastCommandSuccess = $?
    #store the last exit code for restore
    $realLASTEXITCODE = $global:LASTEXITCODE

	Write-Host $lastCommandSuccess
	Write-Host $realLASTEXITCODE
```

And get the following:
```
ls \ThisDoesNotExist
...
True
0
```

That of course does mean that the fix with $LASTEXITCODE would not work in this case :/. It still fixes the case when a script/utility ends with a non-zero exitcode.

**Comment by ondrasek** [comment]
> 

Btw, it seems to me that $? in Prompt just cannot work. It simply resets whenever execution exits the current scope.

```
PS> function Test1 { ls \DoesNotExist }
PS> function Test2 { $? }
PS> Test1; Test2
...
True
```

Since Prompt is yet another function, the $? behavior is the same. Scoping kills it.

**Comment by JanDeDobbeleer** [comment]
I'll have a look tomorrow but if this would be true, we'd see a lot more issues here. Whatever it is, we'll figure it out.

**Comment by lnu** [comment]
I'm not sure, but in your example:

- `ls` with a non existing folder returns an error. The error is handled and thrown from within the cmdlet
- `TestError` does not handle exeption and does not return any error, thus returning True

![image](https://user-images.githubusercontent.com/1829553/151144037-36f76a51-3d77-483c-ba57-0fef098cc887.png)

You see that by default the [`$ErrorActionPreference`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.2#erroractionpreference) is set to `Continue` and returns True even if a statement fails inside your cmdlet. If you change it to `Stop`, the return value is correct. The key is the difference between a non terminating  and a terminating error.

**Comment by ondrasek** [comment]
Fair enough, I missed the $ErrorActionPreference. That seems to make the difference and "Continue" is default on my install. I have not configured it to Continue myself. I will do few more tests though. Sorry for the false alarm.

**Comment by lnu** [comment]
Don't be sorry. The error handling/propagation is not the best part of powershell 😀.

**Comment by ondrasek** [comment]
One of the reasons why I always hated VB was "On Error Resume Next". Here we go again.

**Comment by rkeithhill-keysight** [comment]
I've found that the `ZLocation` module also causes the exitcode segment to not display errors.  And it seems there is something unusual with the terminal inside in `VSCode` (on Windows) that causes the same problem.  :-(

**Comment by JanDeDobbeleer** [comment]
@rkeithhill-keysight VSCode is because of their [shell integration](https://code.visualstudio.com/docs/terminal/shell-integration) feature that has a bug. Disabling it will resolve that. ZLocation will probably do a similar prompt hook and ruin things.

**Comment by rkeithhill-keysight** [comment]
Thanks.  When I disabled both `Shell Integrations: Enabled` and `Enable Persistent Sessions`, the exitcode segment started working again.

**Comment by rkeithhill-keysight** [comment]
Oh, and ZLocation does modify the prompt function.  IIRC we had to jump through a few hoops to get it to work together with posh-git.
