### ISSUE TITLE
Detecting Node and Go environments with package.json and go.mod

### ISSUE THREAD

**Issue by FlomoN** [JanDeDobbeleer/oh-my-posh#165]
### Prerequisites

- [x ] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

Right now the node segment and go segment, simply scan the files in the current directory for .js/ts or .go files. Usually I have my terminal open in the root folder of the project, where my package.json resides and start scripts or install packages from there. Usually though i dont have any source (.js/.ts) files in there, but rather have them in a separate `src` folder.
(Similar concepts apply for go, with other programming languages im not sure).

So I would suggest to scan for an existing `package.json` file or `node_modules` folder for a node environment.
For go i would suggest scanning for `go.mod` file.

(PS: I see that you dont have such a folder structure in this project, and therefore might think this is unecessary, but im pretty sure its very common to not have source files in the root folder. Dont want to step on your toes tho)

### Environment

- Oh my Posh version: 3.36.1
- Theme: Custom
- Operating System: Windows
- Shell: Powershell
- Terminal: Any

**Comment by JanDeDobbeleer** [comment]
My toes can handle a beating after being in OSS for a while, so don't worry 😂. I'll add this functionality, it's literally almost no work due to a refactor I did last week.

**Comment by FlomoN** [comment]
Great stuff :) Love the new look of my powershell, thanks to your project, great work
