### ISSUE TITLE
HELP！！Windows Terminal报错：指定的可执行文件不是此操作系统平台的有效应用程序

### ISSUE THREAD

**Issue by WqxLoveCoding** [JanDeDobbeleer/oh-my-posh#1662]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I follow the instruction of installation on Windows, when I complete editing `Microsoft.PowerShell_profile.ps1`, which is also the step `notepad $PROFILE`, it always report this error, I guess it is because my path name contains Chinese characters, just like this：`C:\Users\你好\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`, but I can't simply modify its name because it is in `C:` and may lead to serious consequences, you know. How can I deal with this dilemma?

screenshots：
![屏幕截图 2022-01-27 212920](https://user-images.githubusercontent.com/57825815/151370479-0559e4b1-4596-4af6-becd-be668863d39d.png)
![屏幕截图 2022-01-27 213001](https://user-images.githubusercontent.com/57825815/151369964-29a68f2d-5879-4364-853b-ba99f606f327.png)
![屏幕截图 2022-01-27 213427](https://user-images.githubusercontent.com/57825815/151369970-59b0ee80-4823-4f4d-b200-7730381d8b6c.png)

### Theme

None.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
None.
```

**Comment by JanDeDobbeleer** [comment]
@WqxLoveCoding please add the following line at the start of your `$PROFILE`:

```powershell
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```
