### ISSUE TITLE
Execution time incorrectly formatted on Linux

### ISSUE THREAD

**Issue by thorstenkampe** [JanDeDobbeleer/oh-my-posh#1666]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Execution time displays incorrectly on Linux (while displaying fine on Windows). The issue seems to be caused by the unicode character (`ﮫ`) which comes straight from the [sample configuration](https://ohmyposh.dev/docs/executiontime).

- Linux (Konsole terminal): 
![image](https://user-images.githubusercontent.com/475462/151672250-ce0911ef-dbb0-420b-ad98-026d754206c9.png)

- Windows (ConEmu):
![image](https://user-images.githubusercontent.com/475462/151672328-e3dd8745-0823-4c90-a001-11ba105f7b86.png)

### Theme

```json
{
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "segments": [
                {
                    "type": "executiontime",
                    "style": "plain",
                    "properties": {
                        "prefix": " ﮫ "
                    }
                }
            ]
        }
    ]
}
```

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

powershell

### Log output

```shell
Version: 7.5.1

Segments:

ConsoleTitle(false)  -   0 ms -
executiontime(true) -   0 ms -

Run duration: 436.127µs

Cache path: /home/thorsten/.cache/oh-my-posh

Logs:

2022/01/29 19:15:00 getArgs duration: 155ns, args:
2022/01/29 19:15:00 getArgs duration: 25ns, args:
2022/01/29 19:15:00 getShellName duration: 307ns, args:
2022/01/29 19:15:00 debug: getenv

2022/01/29 19:15:00 getenv duration: 5.424µs, args: OMP_CACHE_DISABLED
2022/01/29 19:15:00 isRunningAsRoot duration: 835ns, args:
2022/01/29 19:15:00 getShellName duration: 71ns, args:
2022/01/29 19:15:00 lastErrorCode duration: 180ns, args:
2022/01/29 19:15:00 debug: pwd
/home/thorsten
2022/01/29 19:15:00 pwd duration: 23.273µs, args:
2022/01/29 19:15:00 getPathSeperator duration: 47ns, args:
2022/01/29 19:15:00 getPathSeperator duration: 25ns, args:
2022/01/29 19:15:00 getCurrentUser duration: 589ns, args:
2022/01/29 19:15:00 getHostName duration: 3.723µs, args:
2022/01/29 19:15:00 getRuntimeGOOS duration: 51ns, args:
2022/01/29 19:15:00 templateCache duration: 97.099µs, args:
2022/01/29 19:15:00 debug: pwd
/home/thorsten
2022/01/29 19:15:00 pwd duration: 1.108µs, args:
2022/01/29 19:15:00 executionTime duration: 72ns, args:
2022/01/29 19:15:00 debug: getenv

2022/01/29 19:15:00 getenv duration: 1.219µs, args: XDG_CACHE_HOME
2022/01/29 19:15:00 getCachePath duration: 11.018µs, args:
```

**Comment by JanDeDobbeleer** [comment]
@thorstenkampe that's a terminal/font issue and nothing we can do to resolve. If the config is fine in one terminal and wonky in the other, it's a good idea to change terminal.

**Comment by thorstenkampe** [comment]
@JanDeDobbeleer how can you tell, it's a terminal and not an operating system issue?

**Comment by JanDeDobbeleer** [comment]
@thorstenkampe the terminal is responsible for displaying the ANSI string correctly (or any string). There's bug on Windows Terminal too for example when it comes to fonts and ANSI rendering, same on macOS for the standard terminal and full ANSI support. There's no difference in output string cross platform (except for shell escape sequences, but those do not influence character positioning).

You can try two things:

- test a different font
- test a different terminal (Hyper is usually pretty good at displaying fonts correctly, but has other quirks :-))
