### ISSUE TITLE
Display hash instead of branch (or alongside?)

### ISSUE THREAD

**Issue by attisan** [JanDeDobbeleer/oh-my-posh#1667]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would be great to have a variable or option to display the git hash alongside / instead of the branch - kind of the invers #747 was having as an issue.

If this is already possible - I would be grateful to learn how 😁.

**Comment by JanDeDobbeleer** [comment]
@attisan can be done, just allow me to finish the work on templates (almost done now). Then we can add this for sure.

**Comment by JanDeDobbeleer** [comment]
@attisan you can make use of the `{{ .Hash }}` property in a template, that one has the short hash, to only get the branch name, make use of `{{ .Ref }}`

**Comment by mm-nbergen** [comment]
Is `.Hash` / `.ShortHash` still expected to work?  I'm getting a blank template output for either of those.  `.Ref`, `.Head` both work when swapped in.

**Comment by JanDeDobbeleer** [comment]
@mm-nbergen yes, it still works. We have tests for that and I also validated myself just now. Can you show the output of `oh-my-posh debug`?

**Comment by mm-nbergen** [comment]
Looks like I was just missing the `fetch_status` property from the segment, which I finally realized after staring at it a bit longer today.
```
"properties": {			  			
       "fetch_status": true
}
```

**Comment by UltraPulpo** [comment]
Hello!  I am struggling to get the `.Hash` or `.ShortHash` to work on my setup.  I think I just have something configured incorrectly and would greatly appreciate some insight, please and thank you!

Here is the relevant segment.
```
{
  "type": "git",
  "style": "plain",
  "foreground": "#C2C206",
  "template": "[{{ .ShortHash }}] {{ .HEAD }}{{ if and (eq .Ahead 0) (eq .Behind 0) }} \u2261{{end}}{{ if gt .Ahead 0 }} \u2191{{.Ahead}}{{end}}{{ if gt .Behind 0 }} \u2193{{.Behind}}{{end}} {{ if .Working.Changed }}+{{ .Working.Added }} ~{{ .Working.Modified }} -{{ .Working.Deleted }} {{ end }}",
  "properties": {
    "cherry_pick_icon": "\u2713 ",
    "commit_icon": "\u25b7 ",
    "fetch_status": true,
    "merge_icon": "\u25f4 ",
    "no_commits_icon": "[no commits]",
    "rebase_icon": "\u2c62 ",
    "tag_icon": "\u25b6 "
  }
}
```

The `[{{ .ShortHash }}]` bit at the beginning of the template is where I'm struggling.  See here, the hash shows up perfectly with `oh-my-posh debug` but not on the actual command prompt.  Further, I do have the fetch status set in the segment.

![image](https://user-images.githubusercontent.com/46415865/217915134-d28d3092-aaf3-45f3-8ebe-2ca8284fc747.png)

What am I missing? 😅

**Comment by JanDeDobbeleer** [comment]
@UltraPulpo nothing, this works for me so I don't get why it fails to get that information on your prompt. On me end with the same segment config as yours this works.

**Comment by dfalk-paraport** [comment]
@JanDeDobbeleer Okay, thank you for checking!  Must be some configuration f***ery on my machine somewheres.

**Comment by UltraPulpo** [comment]
@JanDeDobbeleer Okay, thank you for checking!  Must be some kind of configuration f***ery on my machine somewheres.

**Comment by travispalmer** [comment]
@UltraPulpo, .Hash and .ShortHash are not working for me either, but wanted to share what I came up with to get this to work
![image](https://user-images.githubusercontent.com/29313758/222292498-90ce644d-16bc-48ff-ab4c-1b8a1ea01b59.png)

Unfortunately it can be a slow call at times:
![image](https://user-images.githubusercontent.com/29313758/222293010-a9d372c0-6a2b-42de-8b06-9731a134367b.png)

**Comment by UltraPulpo** [comment]
@travispalmer Thanks for the follow-up and nice work!  Serendipitously, I am using a similar workaround. 😄 
```
{
  "type": "command",
  "style": "plain",
  "foreground": "#C2C206",
  "template": "[{{ .Output }}] ",
  "properties": {
    "shell": "pwsh",
    "command": "git rev-parse --short HEAD"
  }
}
```
![image](https://user-images.githubusercontent.com/46415865/222294452-4a383089-dcfc-425a-9a6c-2dc0226c506d.png)

**Comment by JanDeDobbeleer** [comment]
Did you all enable posh-git support by any chance?

**Comment by UltraPulpo** [comment]
@JanDeDobbeleer I think so?  This is what I have in my PowerShell profile...
```
Import-Module posh-git
$env:POSH_GIT_ENABLED = $true
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\myCustomTheme.omp.json" | Invoke-Expression
```

**Comment by JanDeDobbeleer** [comment]
@UltraPulpo that's the culprit. We don't get that information from posh-git ;-)

**Comment by UltraPulpo** [comment]
@JanDeDobbeleer Oh!  So I can remove the first two lines from my P$ profile and it'll work?
[EDIT]  Of course it wasn't that simple, ha.

**Comment by JanDeDobbeleer** [comment]
@UltraPulpo yes, and restart the shell.

**Comment by UltraPulpo** [comment]
@JanDeDobbeleer Aha!  That did indeed work for me!  I also updated to latest (14.8.0 to 14.9.2) and also updated my PowerShell7 to latest (7.3.3), which may or may not have helped.  Regardless, thanks for the input!  I'm glad it was just a silly little configuration issue on my end.
![image](https://user-images.githubusercontent.com/46415865/222533879-e8c5e089-54a6-4784-9ca7-927fc358a5e3.png)

**Comment by travispalmer** [comment]
@JanDeDobbeleer, that fixed my setup as well. Once I commented out the posh-git lines in my profile .ShortHash works perfectly and works WAY faster:
![image](https://user-images.githubusercontent.com/29313758/222582412-696b04c6-56df-4423-acba-42fea738b050.png)

Thank you for your help!
