### ISSUE TITLE
Can't use environment variable in Microsoft.PowerShell_profile.ps1

### ISSUE THREAD

**Issue by xmha97** [JanDeDobbeleer/oh-my-posh#1677]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Can't use environment variable in Microsoft.PowerShell_profile.ps1
```powershell
oh-my-posh --init --shell pwsh --config "%LocalAppData%\Programs\oh-my-posh\themes\jandedobbeleer.omp.json" | Invoke-Expression
```

### Theme

jandedobbeleer.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell

```

**Comment by JanDeDobbeleer** [comment]
@xmha97 that's not a bug, this won't work in PowerShell. You need to use `$env:LOCALAPPDATA`:

```
oh-my-posh --init --shell pwsh --config "$($env:LOCALAPPDATA)\Programs\oh-my-posh\themes\jandedobbeleer.omp.json" | Invoke-Expression
```
