### ISSUE TITLE
Virus PUA:Win32/Caypnamer.A!ml found in the release 9.8.3 on Windows

### ISSUE THREAD

**Issue by miiitch** [JanDeDobbeleer/oh-my-posh#1689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

First, sorry for the french text in the capture: 
![image](https://user-images.githubusercontent.com/2396269/152570389-4abc3430-cf92-4092-9d59-9e4e95702b14.png)

Windows Defender found the virus PUA:Win32/Caypnamer.A!ml in at least 2 versions 7.8.3 and 7.8.2. I downloaded the releases from winget

### Theme

not relevant

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
not relevant
```

**Comment by JanDeDobbeleer** [comment]
@miiitch that's a false positive (provided you installed via the official channels). We've seen this before.

**Comment by miiitch** [comment]
Thanks

**Comment by JanDeDobbeleer** [comment]
@miiitch btw, you can follow [this](https://github.com/JanDeDobbeleer/oh-my-posh/issues/767) thread for advancements on signing.
