### ISSUE TITLE
Update WinGet Manifest to ManifestVersion 1.1.0

### ISSUE THREAD

**Issue by OfficialEsco** [JanDeDobbeleer/oh-my-posh#1693]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

* Update to ManifestVersion: 1.1.0
* https://aka.ms/winget-manifest.installer.1.1.0.schema.json
  * Implement ReleaseDate (YYYY-MM-DD)
* https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json
  * Implement ReleaseNotes
  * Implement ReleaseNotesUrl
* https://aka.ms/winget-manifest.version.1.1.0.schema.json
  * No changes, but schema needs to be updated for all of them =)

**Comment by JanDeDobbeleer** [comment]
@OfficialEsco will have a look tomorrow. Seems pretty straightforward.

**Comment by OfficialEsco** [comment]
It doesn't look like the ReleaseDate and ReleaseNotesUrl field is being added

**Comment by JanDeDobbeleer** [comment]
@OfficialEsco I see them though?

**Comment by OfficialEsco** [comment]
> @OfficialEsco I see them though?

In this PR? o_O
* https://github.com/microsoft/winget-pkgs/pull/44871

**Comment by JanDeDobbeleer** [comment]
Strange, not in the PR. Hmm.

**Comment by KaranKad** [comment]
Could this be because of wingetcreate? because right now their latest release does not support v1.1.0 and basically removes unsupported stuff from the manifest when submitting. Support for v1.1.0 was added in https://github.com/microsoft/winget-create/pull/218 but there is no new release right now.

**Comment by JanDeDobbeleer** [comment]
@KaranKad that would be my guess too. @denelon any info on that?

**Comment by OfficialEsco** [comment]
> Could this be because of wingetcreate? because right now their latest release does not support v1.1.0 and basically removes unsupported stuff from the manifest when submitting. Support for v1.1.0 was added in [microsoft/winget-create#218](https://github.com/microsoft/winget-create/pull/218) but there is no new release right now.

Ohhhh yes it is🤦‍♂️
I keep forgetting it does that.. Confusing when it doesn't replace the ManifestVersion
My bad (=

**Comment by JanDeDobbeleer** [comment]
Well, the good news is I did my job 😂

**Comment by denelon** [comment]
I believe @ryfu-msft is working on the next release. @OfficialEsco is that a bug we need to fix? It sounds like it might be.

**Comment by OfficialEsco** [comment]
> I believe @ryfu-msft is working on the next release. @OfficialEsco is that a bug we need to fix? It sounds like it might be.

Sort of yes? Since it dosn't replace the ManifestVersion and Schema, my bug report https://github.com/microsoft/winget-create/issues/139#issuecomment-973285647
But it will probably be supported/fixed once the release is out (hopefully)
It would probably be good to future proof winget-create tho as YamlCreate.ps1 will adapt the new Schemas much quicker

**Comment by ryfu-msft** [comment]
> > I believe @ryfu-msft is working on the next release. @OfficialEsco is that a bug we need to fix? It sounds like it might be.
> 
> Sort of yes? Since it dosn't replace the ManifestVersion and Schema, my bug report [microsoft/winget-create#139 (comment)](https://github.com/microsoft/winget-create/issues/139#issuecomment-973285647) But it will probably be supported/fixed once the release is out (hopefully) It would probably be good to future proof winget-create tho as YamlCreate.ps1 will adapt the new Schemas much quicker

I've only been focusing on making sure that all the new fields are generated correctly when using the new command. I'm working on fixing/ensuring that updating from v1.0 to v1.1 schema is consistent and handled appropriately. PR coming soon...
