### ISSUE TITLE
Arch icon instead of Manjaro in OS segment.

### ISSUE THREAD

**Issue by petrosAth** [JanDeDobbeleer/oh-my-posh#1696]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I use zsh and powershell in Manjaro Linux. A distribution based on Arch. 
![ohmyposh_arch_manjaro_bug](https://user-images.githubusercontent.com/78369447/152610804-ee3557e5-3510-416a-a86d-142e22852cd3.png)
As you can see the icon is that of Arch instead of Manjaro.
I should add that if I use a different icon for Arch in the theme file, the change reflects correctly on the prompt.

The exact same thing happens with PowerShell under Manjaro as well.

### Theme

[https://github.com/petrosAth/ohmyposh/blob/master/themes/nord.omp.json](url)

Same thing happens with a couple premaid themes that I downloaded for testing.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh, powershell

### Log output

```shell
Version: 7.9.0

Segments:

ConsoleTitle(true)   -   0 ms -
exit(true)           -   0 ms - ┬
session(true)        -   0 ms - [petrosath
session(true)        -   0 ms - |@|
session(true)        -   0 ms - wsManjaro]
path(true)           -   0 ms - [~]
git(false)           -   0 ms -
kubectl(false)       -   0 ms -
exit(true)           -   0 ms - └
os(true)             -   0 ms - [ |
shell(true)          -   0 ms -  uni]
executiontime(false) -   0 ms -
exit(true)           -   0 ms - ❯

Run duration: 4.31597ms

Cache path: /home/petrosath/.cache/oh-my-posh

Logs:

2022/02/04 23:50:06 Args duration: 394ns, args:
2022/02/04 23:50:06 Args duration: 85ns, args:
2022/02/04 23:50:06 Args duration: 181ns, args:
2022/02/04 23:50:06 Shell duration: 247ns, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 7.145µs, args: OMP_CACHE_DISABLED
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 27.33µs, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.539µs, args:
2022/02/04 23:50:06 ErrorCode duration: 181ns, args:
2022/02/04 23:50:06 Root duration: 1.087µs, args:
2022/02/04 23:50:06 Shell duration: 126ns, args:
2022/02/04 23:50:06 ErrorCode duration: 75ns, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.643µs, args: WSL_DISTRO_NAME
2022/02/04 23:50:06 IsWsl duration: 4.033µs, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.026µs, args:
2022/02/04 23:50:06 PathSeperator duration: 244ns, args:
2022/02/04 23:50:06 PathSeperator duration: 43ns, args:
2022/02/04 23:50:06 User duration: 307ns, args:
2022/02/04 23:50:06 Host duration: 2.081µs, args:
2022/02/04 23:50:06 GOOS duration: 79ns, args:
2022/02/04 23:50:06 TemplateCache duration: 59.959µs, args:
2022/02/04 23:50:06 TemplateCache duration: 211ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.123µs, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.342µs, args: SSH_CONNECTION
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.053µs, args: SSH_CLIENT
2022/02/04 23:50:06 TemplateCache duration: 232ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 6.681µs, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.247µs, args: SSH_CONNECTION
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 2.842µs, args: SSH_CLIENT
2022/02/04 23:50:06 TemplateCache duration: 176ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.126µs, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.179µs, args: SSH_CONNECTION
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 965ns, args: SSH_CLIENT
2022/02/04 23:50:06 TemplateCache duration: 172ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.05µs, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 923ns, args:
2022/02/04 23:50:06 Args duration: 74ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 830ns, args:
2022/02/04 23:50:06 GOOS duration: 206ns, args:
2022/02/04 23:50:06 GOOS duration: 70ns, args:
2022/02/04 23:50:06 PathSeperator duration: 52ns, args:
2022/02/04 23:50:06 GOOS duration: 42ns, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.145µs, args: WSL_DISTRO_NAME
2022/02/04 23:50:06 IsWsl duration: 3.174µs, args:
2022/02/04 23:50:06 StackCount duration: 390ns, args:
2022/02/04 23:50:06 TemplateCache duration: 182ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.185µs, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 1.124µs, args: WSL_DISTRO_NAME
2022/02/04 23:50:06 IsWsl duration: 3.098µs, args:
2022/02/04 23:50:06 GOOS duration: 65ns, args:
2022/02/04 23:50:06 HasCommand duration: 24.646µs, args: git
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 837ns, args:
2022/02/04 23:50:06 error: HasParentFilePath
stat /.git: no such file or directory
2022/02/04 23:50:06 HasParentFilePath duration: 11.703µs, args: .git
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 1.648µs, args:
2022/02/04 23:50:06 error: HasCommand
exec: "kubectl": executable file not found in $PATH
2022/02/04 23:50:06 HasCommand duration: 21.364µs, args: kubectl
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 13.3µs, args:
2022/02/04 23:50:06 ErrorCode duration: 73ns, args:
2022/02/04 23:50:06 TemplateCache duration: 160ns, args:
2022/02/04 23:50:06 TemplateCache duration: 174ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.179µs, args:
2022/02/04 23:50:06 GOOS duration: 85ns, args:
2022/02/04 23:50:06 TemplateCache duration: 176ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.002µs, args:
2022/02/04 23:50:06 Shell duration: 264ns, args:
2022/02/04 23:50:06 TemplateCache duration: 183ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 2.057µs, args:
2022/02/04 23:50:06 ExecutionTime duration: 183ns, args:
2022/02/04 23:50:06 debug: Pwd
/home/petrosath
2022/02/04 23:50:06 Pwd duration: 1.776µs, args:
2022/02/04 23:50:06 ErrorCode duration: 81ns, args:
2022/02/04 23:50:06 TemplateCache duration: 169ns, args:
2022/02/04 23:50:06 TemplateCache duration: 161ns, args:
2022/02/04 23:50:06 debug: Getenv

2022/02/04 23:50:06 Getenv duration: 2.181µs, args: XDG_CACHE_HOME
2022/02/04 23:50:06 CachePath duration: 21.475µs, args:
```

**Comment by JanDeDobbeleer** [comment]
That's not a bug but rather Manjaro reporting as Arch. So if the platform returns Arch, while you expect Manjora, that's on Manjaro to fix.

We do use an underlying package to identify the platform so I'll have a peek there first.

**Comment by JanDeDobbeleer** [comment]
As I suspected, there's no [differentiation](https://github.com/shirou/gopsutil/blob/e0ec1b9cda4470db704a862282a396986d7e930c/host/host_linux.go#L249).

**Comment by petrosAth** [comment]
`/etc/lsb-release` content is:
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.2
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"
```
`/etc/os-release` content is:
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
I tried `"manjarolinux": "\uf312 "` instead of `"manjaro": "\uf312 "` based on `DISTRIB_ID=ManjaroLinux` and [this](https://github.com/shirou/gopsutil/blob/e0ec1b9cda4470db704a862282a396986d7e930c/host/host_linux.go#L276-L279) but nothing changed.

**Comment by JanDeDobbeleer** [comment]
@petrosAth super useful, thanks!

**Comment by petrosAth** [comment]
.OS still returns `arch`

**Comment by JanDeDobbeleer** [comment]
@petrosAth I can't validate this unless I also install Manjaro, but according to the information you gave me this should in theory work as `host.PlatformInformation()` [returns](https://github.com/shirou/gopsutil/blob/master/host/host_linux.go#L250) the string `arch`. If the above information is also correct, `/etc/os-release` should also contain the string `Manjaro`:

```golang
platform, _, _, _ = host.PlatformInformation()
if platform == "arch" {
        // validate for Manjaro
	lsbInfo := env.FileContent("/etc/os-release")
	if strings.Contains(lsbInfo, "Manjaro") {
		platform = "manjaro"
	}
}
```

**Comment by petrosAth** [comment]
@JanDeDobbeleer It works perfectly fine under wsl so maybe there is something wrong with my system
![ohmyposh_wsl_manjaro](https://user-images.githubusercontent.com/78369447/152794534-deb2165d-bb89-4c93-b839-55e43b1786e6.png)
Leave the issue closed and I'll bug you in the future if it persists after a fresh install. It is not a big deal anyway.
Thank you for your time and for the great app.

**Comment by petrosAth** [comment]
>Leave the issue closed and I'll bug you in the future if it persists after a fresh install. It is not a big deal anyway. Thank you for your time and for the great app.

@JanDeDobbeleer Just came back to verify that It is indeed working as expected in a fresh install. Something must've been wrong in my system.
![gnome-shell-screenshot-chu6mi](https://user-images.githubusercontent.com/78369447/154505288-0a5842f3-f8ed-42b1-9ad1-8951661b01e2.png)

**Comment by sim590** [comment]
Similarly to this issue, oh-my-posh is identifying my OS as fedora even though I'm on Archlinux:

![image](https://user-images.githubusercontent.com/4147254/218288198-85e765c5-8dd7-4e3a-a412-12b2d326ca17.png)

Is that a new bug or am I missing something?

**Comment by JanDeDobbeleer** [comment]
@sim590 what does `oh-my-posh debug` say?

**Comment by sim590** [comment]
Here's what I get:

[oh-my-posh-debug.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/10717060/oh-my-posh-debug.txt)

**Comment by JanDeDobbeleer** [comment]
@sim590 I need some more logging to get the real value, can you have a look at what's set as a value for `environment_platform` in the cache? You can use `oh-my-posh cache edit` to see the contents.

**Comment by sim590** [comment]
```
> oh-my-posh cache edit
exit status 1
```

but, I did

```
> oh-my-posh cache path
```

and I edited the file manually and saw this:

```
"environment_platform": {
    "value": "arch",
    "timestamp": 1676226828,
    "ttl": -1
},
```
-1 value seems odd, doesn't it?

**Comment by JanDeDobbeleer** [comment]
@sim590 -1 implies it never expires, that does say arch though.

**Comment by JanDeDobbeleer** [comment]
@sim590 the logic is correct and it returns `nf-linux-archlinux` from NF which is `\uf303`. On my system, `echo "\uf303"` returns the arch icon, what about yours?

**Comment by sim590** [comment]
I have different behaviour between Powershell and zsh:

![image](https://user-images.githubusercontent.com/4147254/218536540-4e3dbeb3-f8df-4ec0-8699-3820e1018582.png)

but in my case, echoing the character sequence you suggested gives me the fedora Icon.

**Comment by JanDeDobbeleer** [comment]
@sim590 then it's a font and not logical issue. Pretty sure that's either an old nerd font or not at all. You can map the icon yourself if you don't want to change font, have a look at the [docs](https://ohmyposh.dev/docs/segments/os).

**Comment by sim590** [comment]
You're right. I did install a more recent version of the font and it's fixed!
