### ISSUE TITLE
Long command doesn't start from a new line

### ISSUE THREAD

**Issue by SongRongLee** [JanDeDobbeleer/oh-my-posh#1699]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm using Git Bash on Win10.

As the screenshot below, when the command is too long and start wrapping, it doesn't start from a newline but overwriting the same line instead. After the second line is also filled, it finally creates a new line.  

![screenshot](https://user-images.githubusercontent.com/17636996/152630357-633c3bdf-e921-4aa5-842f-bc26c9d6757f.gif)

I've searched for related issues but none of them works for me, such as setting `newline: true`, `export LANG_ALL=...` etc.
The theme I used is modified from `agnosterplus.omp.json`, but this behavior also occurs on default `jandedobbeleer.omp.json`.

`echo $PS1` gives the follow:
![image](https://user-images.githubusercontent.com/17636996/152630622-3d4c8227-c456-425b-a122-f06be2f526f3.png)

Thank you for the fantastic work!

### Theme

```
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "right",
      "segments": [
        {
          "foreground": "#007ACC",
          "properties": {
            "template": " {{ .CurrentDate | date .Format }} ",
            "time_format": "15:04:05"
          },
          "style": "plain",
          "type": "time"
        }
      ],
      "type": "prompt",
      "vertical_offset": -1
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#ffffff",
          "foreground": "#100e23",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "template": " {{ .UserName }}@{{ .HostName }} "
          },
          "style": "powerline",
          "type": "session"
        },
        {
          "background": "#91ddff",
          "foreground": "#100e23",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "folder_icon": "\uf115",
            "folder_separator_icon": " \ue0b1 ",
            "home_icon": "\uf7db",
            "style": "agnoster",
            "template": " {{ .Path }} "
          },
          "style": "powerline",
          "type": "path"
        },
        {
          "background": "#906cff",
          "foreground": "#100e23",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "template": " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "
          },
          "style": "powerline",
          "type": "python"
        },
        {
          "background": "#95ffa4",
          "foreground": "#193549",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "template": " {{ .HEAD }} "
          },
          "style": "powerline",
          "type": "git"
        }
      ],
      "type": "prompt"
    }
  ],
  "final_space": true,
  "version": 1
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash, other (please specify)

### Log output

```shell
Version: 7.9.0

Segments:

ConsoleTitle(false) -   0 ms -
time(true)     -   1 ms -  13:54:59
session(true)  -   0 ms -  hub12@HubertPC
path(true)     -   0 ms -  
python(true)   -  94 ms -   base 3.7.4
git(false)     -   3 ms -

Run duration: 99.5003ms

Cache path: C:\Users\hub12\AppData\Local/oh-my-posh

Logs:

2022/02/05 13:54:59 Args duration: 0s, args:
2022/02/05 13:54:59 Args duration: 0s, args:
2022/02/05 13:54:59 Args duration: 0s, args:
2022/02/05 13:54:59 Shell duration: 0s, args:
2022/02/05 13:54:59 debug: Getenv

2022/02/05 13:54:59 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 Root duration: 0s, args:
2022/02/05 13:54:59 Shell duration: 0s, args:
2022/02/05 13:54:59 ErrorCode duration: 0s, args:
2022/02/05 13:54:59 IsWsl duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 User duration: 0s, args:
2022/02/05 13:54:59 Host duration: 0s, args:
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 TemplateCache duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 debug: Getenv

2022/02/05 13:54:59 Getenv duration: 0s, args: SSH_CONNECTION
2022/02/05 13:54:59 debug: Getenv

2022/02/05 13:54:59 Getenv duration: 0s, args: SSH_CLIENT
2022/02/05 13:54:59 TemplateCache duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 Args duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 Args duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 IsWsl duration: 0s, args:
2022/02/05 13:54:59 StackCount duration: 0s, args:
2022/02/05 13:54:59 TemplateCache duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 debug: Getenv

2022/02/05 13:54:59 Getenv duration: 0s, args: VIRTUAL_ENV
2022/02/05 13:54:59 debug: Getenv

2022/02/05 13:54:59 Getenv duration: 0s, args: CONDA_ENV_PATH
2022/02/05 13:54:59 debug: Getenv
base
2022/02/05 13:54:59 Getenv duration: 0s, args: CONDA_DEFAULT_ENV
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 PathSeperator duration: 0s, args:
2022/02/05 13:54:59 HasCommand duration: 499.8µs, args: python
2022/02/05 13:54:59 debug: RunCommand
Python 3.7.4
2022/02/05 13:54:59 RunCommand duration: 93.0459ms, args: python --version
2022/02/05 13:54:59 TemplateCache duration: 0s, args:
2022/02/05 13:54:59 TemplateCache duration: 0s, args:
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 debug: Home
C:\Users\hub12
2022/02/05 13:54:59 GOOS duration: 0s, args:
2022/02/05 13:54:59 HasCommand duration: 3.498ms, args: git.exe
2022/02/05 13:54:59 debug: Pwd
C:\Users\hub12
2022/02/05 13:54:59 Pwd duration: 0s, args:
2022/02/05 13:54:59 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/02/05 13:54:59 HasParentFilePath duration: 499.9µs, args: .git
2022/02/05 13:54:59 debug: Getenv
C:\Users\hub12\AppData\Local
2022/02/05 13:54:59 Getenv duration: 0s, args: LOCALAPPDATA
2022/02/05 13:54:59 CachePath duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@SongRongLee I did a few tests on my end

- Bash 5.1.12 -> OK
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/2492783/152641545-13769301-d7e3-4534-9c48-65e054ac4dcf.png">
- Git Bash 4.4.23 -> OK
<img width="979" alt="image" src="https://user-images.githubusercontent.com/2492783/152642152-efaac3be-8ba0-49d1-a2b8-6c9f36160046.png">

I only have the oh-my-posh init script in my `.bashrc` btw.
Can you try updating Git Bash? Because Bash needs to be up-to-date.

**Comment by SongRongLee** [comment]
@JanDeDobbeleer 
Thanks for checking that!
My Git Bash is also 4.4.23.
I notice that this problem only happens in Windows Terminal app, while it works fine using right-click opened Mintty console.
![image](https://user-images.githubusercontent.com/17636996/152642938-e0e0cb72-8544-4ef8-b78b-bee50ba8015b.png)
Any ideas on what the causes would be? The issue might be out of scope of this project, but any suggestion is really appreciated. Thanks!

**Comment by JanDeDobbeleer** [comment]
@SongRongLee not really, I did validate on Windows Terminal, maybe update that one first?

**Comment by SongRongLee** [comment]
@JanDeDobbeleer 
I notice that the PS1 I pasted above is quite messy, it actually looks like this:
![image](https://user-images.githubusercontent.com/17636996/152643701-a6632e5d-da2f-480a-b4e5-f4d20fa56a69.png)
I have the latest `1.11.3471.0` version of Windows Terminal.
I also found a similar issue [in their repo](https://github.com/microsoft/terminal/issues/10039), but I saw you have fixed this kind of problems already in other issues.

**Comment by SongRongLee** [comment]
@JanDeDobbeleer 
I can reproduce on another Win10 machine.
1. Fresh installed Git & Git Bash of version 4.4.23.
2. Latest Windows Terminal downloaded from Microsoft Store of version 1.11.3471.
3. Install oh-my-posh by `winget install JanDeDobbeleer.OhMyPosh`
4. Create a `.bash_profile` as follow:  
```
export PATH=/c/Users/hub12/AppData/Local/Programs/oh-my-posh/bin:$PATH
eval "$(oh-my-posh --init --shell bash --config ~/AppData/Local/Programs/oh-my-posh/themes/jandedobbeleer.omp.json)"
```
5. Create a Windows Terminal profile as follow:
```
...
{
    "acrylicOpacity": 0.80000000000000004,
    "commandline": "C:\\Program Files\\Git\\bin\\bash.exe  --login -i",
    "font": 
    {
        "face": "Hack Nerd Font Mono"
    },
    "guid": "{da3904f6-9c19-40ee-96fd-1000b5851560}",
    "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
    "name": "Git Bash",
    "startingDirectory": "%USERPROFILE%",
    "suppressApplicationTitle": true,
    "tabTitle": "Git Bash",
    "useAcrylic": true
},
...
```
6. Install fonts, I used hack nerd font, but any font has the problem.

**Comment by JanDeDobbeleer** [comment]
I'll see if I can reproduce. Could be I'm not on the latest version of WT though.

**Comment by JanDeDobbeleer** [comment]
@SongRongLee I have the exact same setup now, still can't reproduce. The only difference is the Git Bash `commandline` parameter: `%PROGRAMFILES%/git/usr/bin/bash.exe -i -l` although `-l` is short for `--login`.

**Comment by SongRongLee** [comment]
@JanDeDobbeleer 
I noticed that my Git version is a little bit behind, which is 2.29, so I tried reinstall Git and Git Bash altogether.
The problem is gone and everything works fine now! 
Thanks for your help!

**Comment by JanDeDobbeleer** [comment]
@SongRongLee awesome! That's good to be aware of though!

**Comment by kevincharp** [comment]
The same thing has been happening to me with the mt.omp.json theme, the only solution is to reinstall git and gitbash? Or is there some type of configuration to modify so that every time you execute a long command the prompt appears on a new line below? Just in case I clarify that this only happens to me when launching a bash in widnows to finish Windows 11, when I open the independent bash terminal that does not happen to me.
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/85292141/f6d16da7-29f8-43bc-9e24-a1503cde13d1)

I reinstalled git and yet the problem was not fixed

**Comment by JanDeDobbeleer** [comment]
@kevincharp making sure that's up-to-date yes.

**Comment by kevincharp** [comment]
> making sure that's up-to-date yes.
I reinstalled git and yet the problem was not fixed 😢 and I have updated both gitbash and oh my posh

**Comment by JanDeDobbeleer** [comment]
@kevincharp this doesn't seem to happen in native bash. To be completely transparent, git bash isn't a real shell environment. It's like using `wine` on Linux. I would move to nushell or PowerShell (or even CMD) for a good experience on Windows.
