### ISSUE TITLE
Feature Request: YouTube Music Desktop App Integration

### ISSUE THREAD

**Issue by KyleCrowley** [JanDeDobbeleer/oh-my-posh#170]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

[YouTube Music Desktop App (YTMDA)](https://github.com/ytmdesktop/ytmdesktop) is a cross-platform desktop music player for [YouTube Music (YTM)](https://music.youtube.com/), a la the Spotify desktop app.

The request here is to add a segment very similar to the [Spotify segment](https://ohmyposh.dev/docs/spotify) for YTM/YTMDA.

Based on some (very brief) investigation, similar logic ("scrape" the currently playing `Artist - Song` in the title of the application window) used in the Spotify segment *should* be able to be used with the YTMDA segment.

**Comment by KyleCrowley** [comment]
Upon further investigation, my initial solution will work, with the caveat that the title persists if the song is paused, so there's no way to "suppress" the segment if the song is paused (as the Spotify segment does). The Spotify player sets the title to `Spotify` (or `Spotify Free` if you don't not have Spotify premium), so that can be used to determine if the song is playing.

The good news is that YTMDA has a [Remote Control API](https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API) that can be used to [get the currently playing track](https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API), which also returns whether the song is paused.

**Comment by lnu** [comment]
If the title persists it's even better. It will work like the macos version of the spotify segment.  
The status will be paused with the right artist and track, instead of nothing on windows.

**Comment by KyleCrowley** [comment]
Interesting. I'm on Windows so for me the segment just "disappears" when I pause Spotify (or if an ad is playing).

If we want to display a play/paused icon in the segment, we'll likely have to go down the Remote Control API route, as there's no way of determining if the song is paused purely from the title of the window.

**Comment by JanDeDobbeleer** [comment]
If we go for remote control, it can be identical to MacOS Spotify. It's localhost so theoretically this should go fast.

EDIT: also that way it's cross platform from the start

**Comment by KyleCrowley** [comment]
@JanDeDobbeleer Unless you want to implement this yourself, I can give this a shot.

**Comment by JanDeDobbeleer** [comment]
> @JanDeDobbeleer Unless you want to implement this yourself, I can give this a shot.

Feel free to do so!
