### ISSUE TITLE
Add cross-platform CPU utilization property to SysInfo segment

### ISSUE THREAD

**Issue by mekwall** [JanDeDobbeleer/oh-my-posh#1711]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The properties for load averages (`.Load1`, `.Load5` and `.Load15`) doesn't work on Windows and takes more than CPU utilization into account. It would be great if we could get a property for CPU utilization that also works on Windows.

**Comment by JanDeDobbeleer** [comment]
@mekwall that's one for https://github.com/shirou/gopsutil as we rely on that library to get that information.

**Comment by mekwall** [comment]
@JanDeDobbeleer Ah, I see! But it looks like it's already implemented in gopsutil as `cpu_percent` and it should be working on Windows as well. Perhaps it's a good idea to expose `cpu_times`, `cpu_count` and `cpu_times_percent` while you're at it. Not exactly sure what they are but I guess it wouldn't hurt to have them available as template properties.

**Comment by mekwall** [comment]
@JanDeDobbeleer looking at https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segments/sysinfo.go#L76-L80 it turns out that `cpu_percent` is already being exposed but as the undocumented property `Times` which I believe is wrong. Also, passing `0` as duration might not be the best idea since that will compare it with the last call.

**Comment by JanDeDobbeleer** [comment]
@mekwall CPU percentage is impossible to add as it will effectively block the execution of oh-my-posh to get a correct reading. That's why `Times` is undocumented 😅

**Comment by mekwall** [comment]
> @mekwall CPU percentage is impossible to add as it will effectively block the execution of oh-my-posh to get a correct reading. That's why `Times` is undocumented 😅

Aha! That explains why the numbers are unreliable. Thanks for getting back to me :)
