### ISSUE TITLE
Powershell -NoLogo parameter render spaces between blocks

### ISSUE THREAD

**Issue by fedeiglesias** [JanDeDobbeleer/oh-my-posh#172]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
Using parameter "-NoLogo" with Powershell, to avoid show the startup message the windows terminal show spaces between blocks, only in the first prompt. I will add pictures to clarify this point.

The windows terminal configuration with *NoLogo* parameter.
![image](https://user-images.githubusercontent.com/21363793/99728189-56e38600-2ab9-11eb-9299-4b45c69a9776.png)

This is an example with the error, the first line add some spaces until press enter the problem is solved
![image](https://user-images.githubusercontent.com/21363793/99728432-b80b5980-2ab9-11eb-8430-789e4eaea71e.png)

This is an example running from Windows Terminal without *-NoLogo* param (working as expected)
![image](https://user-images.githubusercontent.com/21363793/99728562-edb04280-2ab9-11eb-8810-f544ca8af44c.png)

This is an example running directly from pwsh.exe with *-NoLogo* param setted.
Despite not displaying the fonts correctly, it does not generate the error of spaces between blocks.
![image](https://user-images.githubusercontent.com/21363793/99728830-526b9d00-2aba-11eb-8401-522a8374bbee.png)

### Environment

- Oh my Posh version: 3.38.0-beta
- Theme: All themes tested
- Operating System: Windows 10 Profesional (64 bits)
- Shell:  * Powershell 7.2.0-preview.1
             * Powershell 7.1.0 - (2020-11-11)
- Terminal: Windows Terminal Preview Version: 1.5.3142.0

### Steps to Reproduce

1. Install Oh-my-posh v3 following [this guide](https://ohmyposh.dev/docs/)
2. Install Windows Terminal
3. set "-NoLogo" in powershell parameters

**Expected behavior:**  Using *-NoLogo* parameter in Powershell must render the first prompt line correctly

**Actual behavior:** The first line is rendered with spaces between blocks

**Comment by JanDeDobbeleer** [comment]
My first reaction is: euh...wat? I do not add spaces in between in the code. I can have a look but this is most likely a Powershell issue.

**Comment by fedeiglesias** [comment]
Hi @JanDeDobbeleer  First of all, nice work with Oh-myPosh!  There were very few tools to spice up the windows terminals.
Yes, If it seems to be powershell because I just installed fluentTerminal from the store and the same thing happens here I leave a screenshot

![image](https://user-images.githubusercontent.com/21363793/99789173-7367d880-2b22-11eb-9ca1-70947928ed5a.png)

**Comment by JanDeDobbeleer** [comment]
I'll try to reproduce. It's not because I don't understand where this is coming from, it can't be fixed 😉

**Comment by fedeiglesias** [comment]
yes, apparently Powershell get angry when try to hide his beautifull startup text... Thank you for your support @JanDeDobbeleer !!!

**Comment by turtlebasket** [comment]
I'm noticing this as well with Powershell 7.1.0

**Comment by JanDeDobbeleer** [comment]
If this is rather new, I suspect the debug parameter. That's my preliminary theory for now.

**Comment by JanDeDobbeleer** [comment]
I can't reproduce this on my Mac using PowerShell... I'm waiting for a Windows machine to continue testing there. Stay tuned 👍🏻 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/2492783/99905548-be741e00-2cd1-11eb-8253-c939f3da2a8f.png">

**Comment by fedeiglesias** [comment]
@JanDeDobbeleer i dont know why, i think with the latest versions (3.44.0) this error not appear anymore 🎉!
If i have any notice about it i will report here 👍

**Comment by turtlebasket** [comment]
I'm still having this problem, even with 3.44.1. I'm not especially bothered by it (the startup message is only a marginal annoyance), but do know that this didn't happen when I tried switching oh-my-posh to v2--- so I think the problem probably has something to do with v3.

**Comment by JanDeDobbeleer** [comment]
> I think the problem probably has something to do with v3.

Probably, as V3 is significantly different on how it renders this. Somehow Powershell is a bit of a PITA when it comes to ANSI although the position of the space (or rather omitting of the bg color) has in theory nothing to do with ANSI.

**Comment by rducom** [comment]
workaround : add `cls` in your `$PROFILE` (and still use `-NoLogo`)

**Comment by LemuelKL** [comment]
Still having this issue with 5.12.1. Using @rducom 's workaround for now.

**Comment by JanDeDobbeleer** [comment]
@LemuelKL yes as it's a Windows Terminal bug we can't fix that 😁

**Comment by tommasodotNET** [comment]
I think it's related so I'm going to share this issue as well. If you set transparency effects on Win Terminal, this is how the spaces between segments won't pick up the transparency:
![image](https://user-images.githubusercontent.com/12819039/141433293-9bb075e8-0395-45db-8edc-ba87d46c2023.png)

**Comment by JanDeDobbeleer** [comment]
@tommasodotNET yes, Windows Terminal does not support inverted ANSI yet. That's on [their](https://github.com/microsoft/terminal/issues/7014) end.

**Comment by hyoretsu** [comment]
> workaround : add `cls` in your `$PROFILE` (and still use `-NoLogo`)

That works. Though it's strange how running Windows Terminal as administrator also fixes it.

**Comment by hkrobotics** [comment]
Hey I am having this weird issue, every time I launch my terminal, I get this message saying 
```Save-Preferences: Cannot bind argument to parameter 'Preferences' because it is null.```

![image](https://user-images.githubusercontent.com/39943449/213955988-38bf7e1a-0824-454f-8453-e528ed53d080.png)


I figured out that something was wrong with my $PROFILE, 


```
# workaround for weird space at start refer : https://github.com/JanDeDobbeleer/oh-my-posh/issues/172
Clear-Host
#oh my posh config
oh-my-posh --init --shell pwsh --config C:\Users\kumar\Documents\PowerShell\Modules\oh-my-posh\5.18.0\themes\ohmyposhv3-v2.json | Invoke-Expression
#Terminal Icons
#Import-Module -Name Terminal-Icons
```

commenting the ```Import-Module -Name Terminal-Icons``` fixes the issue, 

can anyone help me fix this issue
