### ISSUE TITLE
Break on updating to 7.12.0

### ISSUE THREAD

**Issue by antonklimov** [JanDeDobbeleer/oh-my-posh#1720]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Updating oh-my-posh executable to 7.12.0
Downloading oh-my-posh themes for 7.12.0

Action to take for this exception:
Program 'oh-my-posh.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected.At
C:\Users\aklimov\Documents\PowerShell\Modules\oh-my-posh\7.12.0\oh-my-posh.psm1:158 char:6
+     (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- …
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
[C] Continue  [I] Silently Continue  [B] Break  [S] Suspend  [?] Help (default is "C"): c
ResourceUnavailable: Program 'oh-my-posh.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected.At
C:\Users\aklimov\Documents\PowerShell\Modules\oh-my-posh\7.12.0\oh-my-posh.psm1:158 char:6 +     (& $poshCommand --init --shell=pwsh --config="$config") | Invoke- … +

### Theme

custom

### What OS are you seeing the problem on?

Windows

### Log output

```shell
unavailable
```

**Comment by JanDeDobbeleer** [comment]
@antonklimov two things you can try:

- add this at the top of your `$PROFILE`: `[console]::InputEncoding = [console]::OutputEncoding = [System.Text.UTF8Encoding]::new()`
- if that doesn't work, remove the module and install using winget (the module is only a wrapper anyways)

**Comment by antonklimov** [comment]
That worked, thanks, and in the meantime it was already 7.13.0, but then on a restart I have the same problem again,

**Comment by JanDeDobbeleer** [comment]
The fix should stay persistent unless the profile wasn't saved somehow?

**Comment by antonklimov** [comment]
Finally I have it working, maybe profile was not persisting. I also had problems because I am using both core and desktop versions of powershell. I think currently they are fighting each other like I upgraded one and then when starting the other it downloaded the older executable. I think ideally since the modules are installed separately in core and desktop the executable should not be shared somehow.

**Comment by JanDeDobbeleer** [comment]
@antonklimov yes, core and 5 do not share the same modules and profile.
