### ISSUE TITLE
How to Uninstall 

### ISSUE THREAD

**Issue by bhantsi** [JanDeDobbeleer/oh-my-posh#1721]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I checked the documentation from A to Z and can't find any docs on how to uninstall. I'm using Ubuntu 20.04 LTS

**Comment by JanDeDobbeleer** [comment]
@bhantsi delete the program 😉

**Comment by bhantsi** [comment]
How can I

**Comment by JanDeDobbeleer** [comment]
rm (which oh-my-posh)
