### ISSUE TITLE
Ubuntu WSL doesn't show oh-my-posh until exec bash

### ISSUE THREAD

**Issue by bcarvalho2500** [JanDeDobbeleer/oh-my-posh#1722]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When opening Ubuntu in WSL or the Ubuntu app, I get an error saying oh-my-posh: command not found. Only when I execute exec bash does the terminal show the oh-my-posh theme.
![image](https://user-images.githubusercontent.com/32946299/152888365-480b1307-3efa-4b64-a7eb-0ac848bb55b8.png)

My .bashrc file
![image](https://user-images.githubusercontent.com/32946299/152888484-ee8221ca-6537-460b-9ac7-9e7605b19bdb.png)

Also the theme loads up just fine on VS Code
### Theme

powerlevel10k_rainbow

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```shell
no log output
```

**Comment by JanDeDobbeleer** [comment]
@bcarvalho2500 does the shell load without your profile? If running . ~/.bashrc works, that's exactly what happens so double check the settings in Windows Terminal first. To load bash without a profile, this is what that usually looks like `bash --noprofile --norc`

**Comment by bcarvalho2500** [comment]
@JanDeDobbeleer My shell loads like this at startup
![image](https://user-images.githubusercontent.com/32946299/153119720-2734c1c8-c78d-49f0-ad41-f4e98cdd36ad.png)

When I run the command you replied with, my shell changes to this:
![image](https://user-images.githubusercontent.com/32946299/153119794-b43af0c5-30be-4420-a629-411aecc782f4.png)

When running . ~/.bashrc my shell changes to this:
![image](https://user-images.githubusercontent.com/32946299/153119903-2f2583df-8ff1-4e51-8bf4-b7adb915a23d.png)

So to be honest I'm not exactly sure where the issue is but I added the oh-my-posh to my bashrc file, but it just doesn't seem to load it correctly at startup.

**Comment by lnu** [comment]
It works for me, but the only difference I see is that omp init is the last exec of the .bashrc file, not the first.

**Comment by JanDeDobbeleer** [comment]
I suggest to create a profile with only the oh-my-posh init line. Should just work.

**Comment by JanDeDobbeleer** [comment]
@bcarvalho2500 any update on your end?

**Comment by SuriSureda** [comment]
I had the same problem.
I fixed it adding 
```
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
```
at the beginning of my .profile.

Then on my .bashrc I have 
```
eval "$(oh-my-posh --init --shell bash --config ~/my.omp.json)"
```

**Comment by bcarvalho2500** [comment]
Sorry for not responding. @SuriSureda your fix worked! Thanks. The only issue now which you may have had is that the bar is now broken up but only for the first line, hitting enter makes a new line that looks correct. Not a big issue but if its a small fix please let me know!

![image](https://user-images.githubusercontent.com/32946299/155649922-e36de135-1f0c-4b47-aa28-a06c0cfa0104.png)

**Comment by JanDeDobbeleer** [comment]
@bcarvalho2500 see [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext)

**Comment by bcarvalho2500** [comment]
Sorry, but where exactly in the settings JSON am I supposed to put that?

**Comment by JanDeDobbeleer** [comment]
@bcarvalho2500 it's going to be the ubuntu icon, so 9/10 in the session segment after the icon: ` {{ if .WSL }}WSL at {{ end }}{{.Icon}}\u2800`

**Comment by bcarvalho2500** [comment]
Ok found that and added the \u2800 but did not fix it and only cuts off the ubuntu logo now. 

![image](https://user-images.githubusercontent.com/32946299/156065619-18b5b4b0-7d61-4c8d-ba06-80c281bd9cd4.png)

![image](https://user-images.githubusercontent.com/32946299/156065696-c0e7f0d4-1b1c-4538-8b03-656955b4410c.png)

**Comment by JanDeDobbeleer** [comment]
@bcarvalho2500 I see. Either way, that is a [terminal issue](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext), not oh-my-posh.

**Comment by Emtyloc** [comment]
add eval "clear", on your .bashrc, is not a fix but works.

**Comment by bcarvalho2500** [comment]
> add eval "clear", on your .bashrc, is not a fix but works.

Great, thanks!

**Comment by ismailmo1** [comment]
the windows terminal docs suggest putting the ``eval "$(oh-my-posh --init --shell bash --config ~/jandedobbeleer.omp.json)"`` line into ``~/.profile`` instead of ``~/.bashrc`` and that fixed it for me:

https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup#choose-and-apply-a-wsl-prompt-theme

**Comment by bcarvalho2500** [comment]
@ismailmo1 Thanks for the suggestion. Sadly I still get the broken up bar when I try it in ~/.profile.
