### ISSUE TITLE
Colors for Filler

### ISSUE THREAD

**Issue by SPFabGerman** [JanDeDobbeleer/oh-my-posh#1745]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hey, I would really like it, if it was possible to change the color of the `filler`. I tried using something like `"filler": "<darkGray>=</>"` to override the color manually, but that didn't work. I think the inclusion of two new option (something like `filler_foreground` and `filler_background`) would be really nice.

**Comment by JanDeDobbeleer** [comment]
I actually tried that this morning and failed 😅 But I'll make a solution, it an architectural "challenge".

**Comment by JanDeDobbeleer** [comment]
@SPFabGerman 

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/2492783/153720439-f80bdcc1-6386-4bdd-9eb4-60b56d76d02a.png">
