### ISSUE TITLE
"Oh My Posh Error" Mac terminal 

### ISSUE THREAD

**Issue by Longshoez** [JanDeDobbeleer/oh-my-posh#1756]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I followed the instructions on the website but the error  persists

### Theme

jandedobbeleer

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```shell
Oh My Posh Error:                                                                                                  

stat /Users/gabriel/jandedobbeleer.omp.json: no such file or directory
```

**Comment by JanDeDobbeleer** [comment]
@Longshoez seems like that config doesn't exist? Oh-my-posh is reporting that your HOME folder has no file called `jandedobbeleer.omp.json`
