### ISSUE TITLE
Version is not set correctly during build

### ISSUE THREAD

**Issue by MJECloud** [JanDeDobbeleer/oh-my-posh#176]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
Hi Jan, 

sadly the version is not set correctly during the build. 
![image](https://user-images.githubusercontent.com/22131101/99784558-47495900-2b1c-11eb-88c1-4a683ee2832a.png)

Maybe the variable is not available at [this step](https://github.com/JanDeDobbeleer/oh-my-posh3/blob/77cd537501382e4caa4c4e41702ceba3bd6b2ec1/.github/workflows/release.yml#L71)

### Environment

- Oh my Posh version: 3.42.0

### Steps to Reproduce

1. Execute the binary with the switch `-version`

**Expected behavior:** 
Output the current version v3.42.0

**Actual behavior:** 
Output development

**Comment by JanDeDobbeleer** [comment]
I'll check and patch 😉

**Comment by JanDeDobbeleer** [comment]
Fixed. You tried to set `main.version`, but that doesn't exist as your variable was called `currentVersion`. I updated the code to just use `Version`, this works as expected now.
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/2492783/99798078-a618cd80-2b30-11eb-983b-7782c6dc9ecb.png">

**Comment by MJECloud** [comment]
Great thank you! 😊
