### ISSUE TITLE
Unicode support in binaries install path

### ISSUE THREAD

**Issue by tomgron** [JanDeDobbeleer/oh-my-posh#1764]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I install the module itself to scoped as CurrentUser (or all users) the installation goes just fine. When the module tries to download themes and binaries and as a user I have unicode characters in my user path, I get an error as shown below:

![image](https://user-images.githubusercontent.com/1743381/154254042-5a3bc80a-822f-4c20-9cd3-2ef137c268fe.png)

### Theme

None yet. Not working.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell, other (please specify)

### Log output

```shell
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Updating oh-my-posh executable to 7.18.0
Downloading oh-my-posh themes for 7.18.0
&: The term 'C:/Users/TommiGr├╢nlund/.oh-my-posh/oh-my-posh.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.
Loading personal and system profiles took 5834ms.
C:\Users\TommiGrönlund>
```

**Comment by JanDeDobbeleer** [comment]
@tomgron that's an issue with PowerShell and UTF8. To resolve this, set the shell to UTF8 in your profile (first line, or for sure before oh-my-posh init):

```Powershell 
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

**Comment by tomgron** [comment]
@JanDeDobbeleer found another option to fix this:

As your page in your site (https://ohmyposh.dev/docs/migrating)  suggests use of the Invoke-Expression after winget install 👍 

```oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.omp.json" | Invoke-Expression```

I modified this as ```(@(&"C:/Users/TommiGrönlund/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe" init powershell --config="C:\Users\TommiGrönlund\AppData\Local\oh-my-posh\config.omp.json" --print) -join "`n") | out-file c:\temp\foo.ps1```

![image](https://user-images.githubusercontent.com/1743381/166146575-b97124d0-cd1f-476f-a5ea-b8441c03da45.png)


In the ```foo.ps1``` I found that the powershell file had false encoding, just changed the wrong characters, ran the ps1 file and everything works.

Just to note that this is an option as well.
