### ISSUE TITLE
Set omp.cache file to use ~/.oh-my-posh path

### ISSUE THREAD

**Issue by peyton-chandarana** [JanDeDobbeleer/oh-my-posh#1769]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I am using WSL with Ubuntu installed. I noticed the omp.cache file is showing up in the user's home directory for some reason. I see that the file was originally named ".omp.cache" before #1017 so as to hide it in the home directory. 

Is there a way to redirect the cache file to another directory? Say "~/.oh-my-posh" so it is not showing up in the home directory?

I see that the code is expecting a directory named "oh-my-posh" without the "." which would also show up in the home directory and not be hidden?

I am using 7.18.0.

Thanks!

**Comment by JanDeDobbeleer** [comment]
@s7117 you can set `XDG_CACHE_HOME` to the path you'd like to use. Otherwise, creating the `.cache` folder inside your `HOME` directory will also move it there.

**Comment by peyton-chandarana** [comment]
Thank you for the update! That worked!
