### ISSUE TITLE
Path Segment not render mappedlocations

### ISSUE THREAD

**Issue by fedeiglesias** [JanDeDobbeleer/oh-my-posh#177]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Implementing Path Segment, cannot make custom paths work using mappedlocations property. 

I tried using **short**, **agnoster**, and **agnoster_full**
Inside or outside $HOME path, always render the full path

`        {
          "type": "path",
          "style": "plain",
          "foreground": "#26C6DA",
          "background": "#546E7A",
          "properties": {
            "style": "short",
            "mappedlocations": [
              ["C:\\tools", "Handy tools!"]
            ]
          }
        },
`

### Environment

- Oh my Posh version: 3.38.0-beta
- Theme: All themes tested
- Operating System: Windows 10 Profesional (64 bits)
- Shell:  * Powershell 7.2.0-preview.1
             * Powershell 7.1.0 - (2020-11-11)
- Terminal: Windows Terminal Preview Version: 1.5.3142.0

### Steps to Reproduce

1. Use Path Block as show in the documentation exanple

**Expected behavior:** Render icon or text in specific directories

**Actual behavior:** Render omit mappedlocations

**Comment by JanDeDobbeleer** [comment]
I'll check, I didn't create that (and it's brand new) @lnu care to have a look?

**Comment by lnu** [comment]
of course
I think it was integrated later than in version 3.38.0-beta. Can you try the latest one?

**Comment by fedeiglesias** [comment]
With the latest version is working like a charm 👌! Thank you @lnu !!!  🙌
