### ISSUE TITLE
use 'ls' to list files, an empty line displays under non-English file name

### ISSUE THREAD

**Issue by wswind** [JanDeDobbeleer/oh-my-posh#1774]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

a folder contains some files with non-English character string like "中文"
```
folder
├───a
├───a中文
├───b
├───b中文
└───c
```

`ls` would show an empty line under the file with non-English name,
everything works fine without using oh-my-posh

![image](https://user-images.githubusercontent.com/18399096/154632319-84b1237c-5799-460a-bcd1-544aab36dd46.png)

### Theme

paradox

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
> oh-my-posh --debug --shell uni --config="$POSH_THEME"

Version: 7.18.0
...
```

**Comment by JanDeDobbeleer** [comment]
@wswind that's a bug in PowerShell due to UTF8. They need to fix that.

**Comment by wswind** [comment]
Yeah,  can't reproduce this issue with clink, it's not a bug of oh-my-posh, thanks.
