### ISSUE TITLE
Az Segment does not work with custom config dir in AZURE_CONFIG_DIR

### ISSUE THREAD

**Issue by mwiedemeyer** [JanDeDobbeleer/oh-my-posh#1775]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm using different az cli environments as described here: https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file
That means that the config folder should not be hard coded as `.azure` but should use the environment variable `AZURE_CONFIG_DIR` if it exists.
Else the az segment uses the wrong information not reflecting the data from the actual `az account show`

The issue exists on Windows (PowerShell) and on Ubuntu bash.

### Theme

{
          "background": "#36B9EE",
          "foreground": "#000000",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_id": false,
            "display_name": true,
            "info_separator": " @ ",
            "template": " \ufd03 {{ .Name }}"
          },
          "style": "powerline",
          "type": "az"
        },

### Log output

```shell
2022/02/18 11:30:53 Pwd duration: 1.36µs, args:
2022/02/18 11:30:53 FileContent duration: 3.017629ms, args: /home/marco/.azure/azureProfile.json
2022/02/18 11:30:53 TemplateCache duration: 160ns, args:
2022/02/18 11:30:53 debug: Pwd
```

**Comment by JanDeDobbeleer** [comment]
@mwiedemeyer thanks for this info, that's an easy fix 👍🏻

**Comment by mwiedemeyer** [comment]
Thank you very much! Awesome project, awesome support! 🥰
