### ISSUE TITLE
Typo in `Write-PoshDebug` output (`PathSeperator`)

### ISSUE THREAD

**Issue by thorstenkampe** [JanDeDobbeleer/oh-my-posh#1787]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

`2022/02/19 15:51:26 PathSeperator duration: 0s, args:` should be `PathSeparator` (a instead of e)

### Theme

not relevant

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
not relevant
```

**Comment by JanDeDobbeleer** [comment]
You're allowed to create a quick PR to fix 😁

**Comment by thorstenkampe** [comment]
Sorry, I'm not a developer and not familiar with the procedure. Is there a simple Howto?

**Comment by JanDeDobbeleer** [comment]
@thorstenkampe that'll bring us pretty far :-) I'll fix it for you!
