### ISSUE TITLE
[Feature request] Set background & foreground inline 

### ISSUE THREAD

**Issue by fedeiglesias** [JanDeDobbeleer/oh-my-posh#179]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

This is not an issue, its a "nice to have" feature.
As we read in the [color documentation](https://ohmyposh.dev/docs/configure#colors) we can set a foreground color in the segment for any specific text.
It will be nice to be able to set also the background, i think something like this

<#ff0000,#00ff00>Hello budy!</>

Where the first or the second can be the foreground and background.

It will be usefull in escenarios like that, in where we want to put a "label" for an specific path (but not for the rest)

![image](https://user-images.githubusercontent.com/21363793/99865061-8cff3380-2ba7-11eb-84f4-b2356f97b517.png)

Thank you for this  awesome tool !!!

**Comment by JanDeDobbeleer** [comment]
Let's see what can be done. I think it's possible, and the suggestion could even work in terms of interface.

**Comment by shedric1** [comment]
I was looking for a way to do this, and the syntax suggestion inspired me to get it set up. Hope that's all right! I'm no expert with Go, so feel free to suggest changes/totally alter it as needed.

Existing themes with in-line colors shouldn't need to change anything, the suggested syntax only adds new options.

And now I can connect `plain` style segments to `powerline` segments without a blank space between!
![image of inline background color changes](https://i.imgur.com/wLDPV34.png)

**Comment by JanDeDobbeleer** [comment]
Should be live! (or ASAP 😅)

**Comment by fedeiglesias** [comment]
@shedric1 thank you very much mate! I think i need to learn some GoLang 😄
@JanDeDobbeleer  I'm in love with oh-my-posh!!! in my new job we use Win env for work and I won't miss bash at all!
Here is the feature working like a charm 👌

![ohmyposh](https://user-images.githubusercontent.com/21363793/99890762-fee88300-2c62-11eb-92b2-f8125e26d20b.gif)
