### ISSUE TITLE
Doc: Update Scoop install instructions to install scoop's manifest

### ISSUE THREAD

**Issue by kennedy** [JanDeDobbeleer/oh-my-posh#1794]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I would like to suggest simplifying the scoop install step to call `scoop install oh-my-posh` instead. ~~I understand currently the `scoop/main` manifest is labeled `oh-my-posh3` but I have created a ticket to change the name to `oh-my-posh`~~:

- Issue: [ScoopInstaller/Main#3321](https://github.com/ScoopInstaller/Main/issues/3321)
- ~~Draft~~ Merged PR [ScoopInstaller/Main#3320](https://github.com/ScoopInstaller/Main/pull/3320).

What do you think?

Edit: My PR for changing the name to `oh-my-posh` got approved

**Comment by JanDeDobbeleer** [comment]
@Kennedy how do the hashes get updated?

**Comment by kennedy** [comment]
> @kennedy how do the hashes get updated?

From what I can tell, there is a powershell github action that calls the`checkver.ps1` script, which goes through all the apps, checks for new versions and automatically updates the manifest. How often seems like `At minute 20 past every 4th hour: 20 */4 * * *` 

You can find more information here: https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate

source for [checkver.ps1](https://github.com/ScoopInstaller/Scoop/blob/master/bin/checkver.ps1)

**Comment by JanDeDobbeleer** [comment]
@Kennedy while I like the addition on scoop's end, I want to stay in control of my own deliveries as much as I can. Sometimes losing a day on a deploy isn't what I want.
