### ISSUE TITLE
Themes for Cmder windows

### ISSUE THREAD

**Issue by alichampion** [JanDeDobbeleer/oh-my-posh#1802]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi, I was curious if we can have some themes for `Cmder` windows terminal.

I have been using this terminal for a few years now and it's very lovely and easy to work with it.

[Checkout `Cmder`](https://cmder.net/)

**Comment by JanDeDobbeleer** [comment]
@alichampion what do you mean specifically? Because you can create any configuration you want. Actual Cmder themes are out of scope for this project. You can have a look at [existing resources](https://github.com/joonro/ConEmu-Color-Themes) to get you started.

**Comment by alichampion** [comment]
Alright Thanks
