### ISSUE TITLE
Pull Set-PoshPrompt directly from gist

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#1803]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I've been playing with gists, and I was wondering if OMP could alter Set-PoshPrompt to accept JSON directly.

My initial thought was something like this:

`myprofile.ps1`
``` powershell
$PoshResponse = Invoke-Webrequest -Uri "https://gist.githubusercontent.com/myusername/mygistid/raw/myfileid/myfile.omp.json"
Set-PoshPrompt -Theme $PoshResponse.Content
```

`oh-my-posh.psm1`
``` powershell
function Set-PoshPrompt {
    ...
    if (Test-JSON $Theme) {
        Out-File -FilePath "$($env:POSH_THEMES_PATH)/gist-theme.omp.json" -InputObject $Theme -Force
        $Theme = "gist-theme"
    }

    $config = ""
    ...
```

The result would be the creation/overwriting of a gist-theme theme file, which is then loaded via the normal flow. 

Before I bother making a pull request, does this seem like something you'd be interested in? Are there consequences to this that I am not considering?

**Comment by ehawman-rosenberg** [comment]
I didn't even realize, but Test-JSON has a -Schema flag so you could hand it `https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json` for proper validation.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg I like the idea, but we can have a much better implementation. The PowerShell module is just a wrapper around the golang binary, and Set-PoshPrompt is only there for old school reasons (thus deprecated).

However, we can extend the [init functionality](https://github.com/JanDeDobbeleer/oh-my-posh/blob/917bb8e7c5a2438e767823bb60b0a3fd979caff0/src/main.go#L170) to also accept a URL as the config value, download and store that in the cache path we already have and initialize the shell as such.

**Comment by ehawman-rosenberg** [comment]
I tried to puzzle it out myself but my self-taught lack of experience is coming to bite me.

A) How does one properly write to and read from the cache? I see the syncs, mutexes, and locks/unlocks but I'm not sure how to properly invoke them.

B) When contributing to public projects like this, how are packages picked? I don't see a JSON validator for your schema, and [xeipuuv/gojsonschema](https://github.com/xeipuuv/gojsonschema) has a bunch of dependencies. Do you already have a validator and I'm just missing it?

Apologies for being a bother. I'd do it myself if I had the background.

**Comment by ehawman-rosenberg** [comment]
Nice! Thanks!
