### ISSUE TITLE
ExportedCommands only contains Set-PoshPrompt

### ISSUE THREAD

**Issue by dpaulson45** [JanDeDobbeleer/oh-my-posh#1808]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In version 6.14.0 there was the following ExportedCommands

```
Key                    Value
---                    -----
Get-PoshInfoForV2Users Get-PoshInfoForV2Users
Get-PoshThemes         Get-PoshThemes
Set-PoshPrompt         Set-PoshPrompt
Get-ThemesLocation     Get-ThemesLocation
Set-Prompt             Set-Prompt
Show-Colors            Show-Colors
Show-ThemeColors       Show-ThemeColors
Show-ThemeSymbols      Show-ThemeSymbols
Write-ColorPreview     Write-ColorPreview
```

In Version 7.24.0, only Set-PoshPrompt is available to export. 

Based off your docs, you should still have Get-PoshThemes at least to see all the possible themes and what they look like. 

https://ohmyposh.dev/docs/themes

### Theme

NA

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Write-PoshDebug isn't even a command in this version, that appears to be in 7.5.1 but not in any newer module's versions.
```

**Comment by JanDeDobbeleer** [comment]
@dpaulson45 it's available but as a global function. Not part of the module.

**Comment by dpaulson45** [comment]
@JanDeDobbeleer only if you have the old modules in the profile

**Comment by JanDeDobbeleer** [comment]
If you init the prompt you automatically get those cmdlets available. But they're indeed not available after `Import-Module`.

**Comment by dpaulson45** [comment]
![image](https://user-images.githubusercontent.com/22776718/155797226-a8530276-f15f-4b66-b1d4-84576ddc785d.png)


Add back an older module version under my profile 

![image](https://user-images.githubusercontent.com/22776718/155798663-904c945a-ada6-4b27-9044-2724c1e341af.png)

Then able to run the command

![image](https://user-images.githubusercontent.com/22776718/155798901-70395c00-c3c1-44ee-9e04-cf2b75f54108.png)

and loaded old module

![image](https://user-images.githubusercontent.com/22776718/155798965-606c5131-f5c2-49c0-8dc5-f4e789b34ac1.png)

**Comment by dpaulson45** [comment]
Okay, I get what you are saying now. You need to run `Set-PoshPrompt` even though I don't know what I might like just yet. And unable to run `Get-PoshThemes` till after I do that.

A bad design to load your other cmdlets from a module that way. 

Recommend at least updating your docs on this.

**Comment by JanDeDobbeleer** [comment]
@dpaulson45 clean system installation

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2492783/155799786-bb93aab9-7983-41d4-a3f1-1ec34179b637.png">

The reason it doesn't work is that you need to initialise the prompt either via `Set-PoshPrompt` (deprecated) or the command I added inline, or for you `oh-my-posh --init --shell pwsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v$(oh-my-posh --version)/themes/jandedobbeleer.omp.json | Invoke-Expression`

**Comment by JanDeDobbeleer** [comment]
@dpaulson45 it's a bit rude to come to that conclusion without understanding the bigger picture. This isn't subject to change anymore as it facilitates having the core functionality in the binary and the module only acts as a wrapper around that. This makes extending everything a lot easier even if it means "sacrificing" good module design. Remember, I'm doing this for free, during moments where I could instead enjoy family life or leisure.
