### ISSUE TITLE
Dimmed Style in Template Text Decoration

### ISSUE THREAD

**Issue by icy-comet** [JanDeDobbeleer/oh-my-posh#1813]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I was going through Starship's documentation and noticed an extra formatting style called `dimmed` along with common ones like `bold` and `italic`. While OhMyPosh supports others, I noticed `dimmed` is missing.

If you check the source code of the Rust library `ansi_term` that Starship uses, they are adding just one extra character to the ANSI sequence. `\x1b[1` sequence makes the text bold while `\x1B[2` makes it dim.

```rust
        // Taken from ansi_term's github repo -> https://github.com/ogham/rust-ansi-term/blob/master/src/ansi.rs
       // MIT Licensed

        // Write the codes’ prefix, then write numbers, separated by
        // semicolons, for each text style we want to apply.
        write!(f, "\x1B[")?;
        let mut written_anything = false;

        {
            let mut write_char = |c| {
                if written_anything { write!(f, ";")?; }
                written_anything = true;
                write!(f, "{}", c)?;
                Ok(())
            };

            if self.is_bold           { write_char('1')? }
            if self.is_dimmed         { write_char('2')? }
            if self.is_italic         { write_char('3')? }
            if self.is_underline      { write_char('4')? }
            if self.is_blink          { write_char('5')? }
            if self.is_reverse        { write_char('7')? }
            if self.is_hidden         { write_char('8')? }
            if self.is_strikethrough  { write_char('9')? }
        }
```

I can see OhMyPosh is doing something similar as well:
https://github.com/JanDeDobbeleer/oh-my-posh/blob/d3d370309ffa9e8b522b3bcdb84c7ceed589fee8/src/color/ansi.go#L118

Is it possible to add the `dimmed` style to OhMyPosh?

PS: I would have opened a PR myself, but I haven't dealt much with these languages.

**Comment by JanDeDobbeleer** [comment]
@icy-comet for sure. Easy addition 😄

**Comment by icy-comet** [comment]
@JanDeDobbeleer take a look at `reverse` and `blink` as well :)
