### ISSUE TITLE
Invoke-Expressions : The term 'Invoke-Expressions' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by angadschawla** [JanDeDobbeleer/oh-my-posh#1819]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I was installing using the guide "https://ohmyposh.dev/docs/windows".

After adding `oh-my-posh --init --shell pwsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v$(oh-my-posh --version)/themes/jandedobbeleer.omp.json | Invoke-Expression` to $PROFILE and reloading it, I get the following:

'Invoke-Expressions : The term 'Invoke-Expressions' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\user1\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:1 char:159
+                                                       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-Expressions:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException'

### Theme

jandedobbeleer

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Write-PoshDebug : The term 'Write-PoshDebug' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Write-PoshDebug
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-PoshDebug:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by JanDeDobbeleer** [comment]
@angadschawla [Invoke-Expression](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-expression?view=powershell-7.2) is a PowerShell cmdlet so this is not something oh-my-posh can resolve for you. Which version of PowerShell are you using?

**Comment by angadschawla** [comment]
@JanDeDobbeleer  here is the version I am running:


Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by JanDeDobbeleer** [comment]
@angadschawla I don't know why that cmdlet isn't known on your system, but I advise to [upgrade to 7.2.1](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-5.1) anyways unless you really need 5.1 (and also need to find the root cause of that cmdlet missing).

**Comment by angadschawla** [comment]
@JanDeDobbeleer Upgrading to 7.2.1 handled the issue! Thank you very much!
