### ISSUE TITLE
p10k style newlines ?

### ISSUE THREAD

**Issue by Magniquick** [JanDeDobbeleer/oh-my-posh#1821]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
### What would you like to see changed/added?

ATM, newlines are made all the time in omp when using the newline option
Is it possible to make it more like powerlevel10k - where newlines are not made if a window is first opened or when `clear` is used ?

eg - p10k -
<img width="851" alt="Screenshot 2022-02-27 at 4 24 00 PM" src="https://user-images.githubusercontent.com/67406856/155879541-a2373b4a-1a05-47d4-a489-acb029eaa921.png">

omp -
<img width="851" alt="Screenshot 2022-02-27 at 4 23 55 PM" src="https://user-images.githubusercontent.com/67406856/155879564-488f3878-4d6d-4031-abf6-72df04456f81.png">

In p10k, there is no newline before the first promt displayed, unike omp.

**Comment by JanDeDobbeleer** [comment]
@Magniquick we do not print a newline before the prompt tbh. Can you share your config/theme?

**Comment by Magniquick** [comment]
It's a shitty theme I made by changing bubblesline :P
[bubblesline.mod.omp.json.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8148529/bubblesline.mod.omp.json.txt)

**Comment by Magniquick** [comment]
> @Magniquick we do not print a newline before the prompt tbh. Can you share your config/theme?

I meant as when you are using the newline option

**Comment by JanDeDobbeleer** [comment]
@Magniquick ah. So you're looking for a way that you don't have a newline on start? I propose to do that natively in zsh. Remove the newline in your config and add the following in `.zshrc`:

```
precmd() {
    precmd() {
        echo
    }
}
```

[source](https://stackoverflow.com/questions/20512957/zsh-new-line-prompt-after-each-command)

**Comment by Magniquick** [comment]
> @Magniquick ah. So you're looking for a way that you don't have a newline on start? I propose to do that natively in zsh. Remove the newline in your config and add the following in `.zshrc`:
> 
> ```
> precmd() {
>     precmd() {
>         echo
>     }
> }
> ```
> 
> [source](https://stackoverflow.com/questions/20512957/zsh-new-line-prompt-after-each-command)

You are awesome !
Thanks a million !

fyi - needed a newline between promts because they overlap
<img width="842" alt="Screenshot 2022-02-27 at 5 54 44 PM" src="https://user-images.githubusercontent.com/67406856/155882193-ca99e1ad-62ac-4eac-921c-cee150fa1c11.png">
 
 : )

**Comment by Magniquick** [comment]
Sorry to bother you again but using clear breaks it again : (
<img width="842" alt="A cleared terminal" src="https://user-images.githubusercontent.com/67406856/155882658-a5f60341-9638-4610-ac98-61518153f106.png">

**Comment by Magniquick** [comment]
However, [this](https://stackoverflow.com/a/50103965) along with [this](https://stackoverflow.com/a/67280892) fixes it !
: )
