### ISSUE TITLE
Display UI in segment sections in website

### ISSUE THREAD

**Issue by RiteshChepuri** [JanDeDobbeleer/oh-my-posh#1827]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be amazing if we could a get a picture or snippet of UI in the Segment section in the website so that we could actually see what it looks before customizing 
Thank you

**Comment by JanDeDobbeleer** [comment]
@RiteshChepuri as you can basically create any look you want, I don't see what you're after specifically? I don't want to maintain evolving UI as I don't have time for that.
