### ISSUE TITLE
Oh My Posh not setting theme on windows terminal by ver：7.27

### ISSUE THREAD

**Issue by deeplee** [JanDeDobbeleer/oh-my-posh#1828]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Oh My Posh suddenly stopped working on Powershell in the Windows Terminal App (and in other places). Here is how the powershell looks no
![Screenshot_2022-02-28_10-47-02](https://user-images.githubusercontent.com/8621954/155915725-431b39b0-1125-4c38-a842-cad8e2c02ed3.png)
w

### Theme

Set-PoshPrompt -Theme gmay

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
 ulixl112@HQ781-6950-ZNZC  ~  pwsh  no config   oh-my-posh --debug --shell uni --config="$POSH_THEME"

Version: 7.27.0

Segments:

ConsoleTitle(false) -   0 ms -
session(true)  -   1 ms -  ulixl112@HQ781-6950-ZNZC 
path(true)     -   1 ms -  ~
shell(true)    -   0 ms -  uni
text(true)     -   0 ms -  no config
exit(true)     -   1 ms -  

Run duration: 5.6341ms

Cache path: C:\Users\ulixl112\AppData\Local/oh-my-posh

Logs:

2022/02/28 10:49:09 Args duration: 0s, args:
2022/02/28 10:49:09 Args duration: 0s, args:
2022/02/28 10:49:09 Args duration: 0s, args:
2022/02/28 10:49:09 Shell duration: 0s, args:
2022/02/28 10:49:09 debug: Getenv

2022/02/28 10:49:09 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 debug: Getenv

2022/02/28 10:49:09 Getenv duration: 0s, args: SSH_CONNECTION
2022/02/28 10:49:09 debug: Getenv

2022/02/28 10:49:09 Getenv duration: 0s, args: SSH_CLIENT
2022/02/28 10:49:09 Root duration: 0s, args:
2022/02/28 10:49:09 Shell duration: 0s, args:
2022/02/28 10:49:09 ErrorCode duration: 0s, args:
2022/02/28 10:49:09 IsWsl duration: 0s, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 User duration: 0s, args:
2022/02/28 10:49:09 Host duration: 0s, args:
2022/02/28 10:49:09 GOOS duration: 0s, args:
2022/02/28 10:49:09 TemplateCache duration: 555.1µs, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 Args duration: 0s, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 GOOS duration: 0s, args:
2022/02/28 10:49:09 GOOS duration: 0s, args:
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 PathSeparator duration: 0s, args:
2022/02/28 10:49:09 GOOS duration: 0s, args:
2022/02/28 10:49:09 IsWsl duration: 0s, args:
2022/02/28 10:49:09 StackCount duration: 0s, args:
2022/02/28 10:49:09 TemplateCache duration: 0s, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 Shell duration: 0s, args:
2022/02/28 10:49:09 TemplateCache duration: 0s, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 TemplateCache duration: 0s, args:
2022/02/28 10:49:09 debug: Pwd
C:\Users\ulixl112
2022/02/28 10:49:09 Pwd duration: 0s, args:
2022/02/28 10:49:09 debug: Home
C:\Users\ulixl112
2022/02/28 10:49:09 ErrorCode duration: 0s, args:
2022/02/28 10:49:09 TemplateCache duration: 0s, args:
2022/02/28 10:49:09 TemplateCache duration: 0s, args:
2022/02/28 10:49:09 debug: Getenv
C:\Users\ulixl112\AppData\Local
2022/02/28 10:49:09 Getenv duration: 0s, args: LOCALAPPDATA
2022/02/28 10:49:09 CachePath duration: 508.5µs, args:
```

**Comment by deeplee** [comment]
only I update oh-my-posh to 7.27 it  appear

**Comment by JanDeDobbeleer** [comment]
@deeplee when I update to 7.27 I can still use `Set-PoshPrompt -Theme gmay` so I don't see what happens here. We changed the location of the themes, but as everything resolves around `$env:POSH_THEMES_PATH`, I don't see how that could break for you and not me?

<img width="727" alt="image" src="https://user-images.githubusercontent.com/2492783/155935667-ef2adc5d-99dc-495d-8e21-3f7bfcf5b6b3.png">

Same for Windows

<img width="771" alt="image" src="https://user-images.githubusercontent.com/2492783/155935971-d5cd9e47-1c14-4d73-b52a-b2bf0527a433.png">

**Comment by deeplee** [comment]
@JanDeDobbeleer  $env:POSH_THEMES_PATH is C:\Users\ulixl112\AppData\Local\oh-my-posh\themes   but it is  empty so I think oh-my-posh do not（or can not） download themes

**Comment by deeplee** [comment]
I use this command “Install-Module -Name oh-my-posh -Scope CurrentUser -RequiredVersion 7.20.0” and delete 7.27 folder   
theme looks normal  but I update to 7.27 it reproduce

**Comment by JanDeDobbeleer** [comment]
@deeplee it downloads the themes on import-module. Do me a favor, remove that folder (oh-my-posh) and re-import the module. It should download everything.

**Comment by deeplee** [comment]
I import oh-my -posh in  C:\Users\ulixl112\Documents\PowerShell\profile.ps1 when I update to 7.27  it reproduce  and I try as below
![Screenshot_2022-02-28_17-01-22](https://user-images.githubusercontent.com/8621954/155954532-71faf26d-91d3-4170-a3ae-ce24214660d5.png)


Import-Module Get-ChildItemColor
Import-Module oh-my-posh
Import-Module ZLocation

#Set-PoshPrompt -Theme  agnosterplus
Set-PoshPrompt -Theme gmay

**Comment by JanDeDobbeleer** [comment]
I'll see if I can reproduce by being on that version and upgrading. Try the following first:

```powershell
rm "C:\Users\ulixl112\AppData\Local\oh-my-posh" -Force -Recurse
```
and restart the shell, that should trigger the download (could be you have a mix between winget/scoop installs and the PowerShell module).

**Comment by JanDeDobbeleer** [comment]
@deeplee please try again when [7.27.1](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v7.27.1) is available.

**Comment by deeplee** [comment]
@JanDeDobbeleer  I update to 7.28.1  it also reproduce

must  delete cache  rm "C:\Users\ulixl112\AppData\Local\oh-my-posh" -Force -Recurse

and restart  pwsh  it will normal  when import any error it also need  delete cache

**Comment by JanDeDobbeleer** [comment]
> and restart pwsh it will normal when import any error it also need delete cache

@deeplee I don't understand what you mean by that

**Comment by deeplee** [comment]
@JanDeDobbeleer  I means
I update to 7.28.1  it reproduce 
then  I delete cache（ rm "C:\Users\ulixl112\AppData\Local\oh-my-posh" ）-Force -Recurse   when I restart pwsh it download execute bin and themes but has some wrone，do not complete。 so it reprodece too。 Restarting pwsh again doesn't help, you can only re-delete the cache

**Comment by JanDeDobbeleer** [comment]
@deeplee can you share the actual error message?

**Comment by deeplee** [comment]
@JanDeDobbeleer  like this
![Screenshot_2022-02-28_17-01-22](https://user-images.githubusercontent.com/8621954/156127451-a7a888e0-b78c-45c9-a25b-4ff31d706d7e.png)

**Comment by JanDeDobbeleer** [comment]
@deeplee aha. Do you have a network connection which blocks incoming traffic? Because it's unable to download anything...

```
Invoke-WebRequest: Unable to read data from the transport connection
```

**Comment by deeplee** [comment]
@JanDeDobbeleer 

Yes  I hava network connection because I use Update-Module to update oh-my-posh

sometimes it has wrone， and sometimes it works normal

if error like this  it will not redownload theme when I restart pwsh
![Screenshot_2022-02-28_17-01-22](https://user-images.githubusercontent.com/8621954/156129641-f8c1e05e-3496-4387-a2d7-a2bf6f60d0dd.png)

**Comment by JanDeDobbeleer** [comment]
@deeplee this is network related and nothing we can do on our end. I propose to use a different installation method (winget/scoop) as this is out of our hands.

**Comment by deeplee** [comment]
@JanDeDobbeleer  I think oh-my-posh need check themes folder exist when it import everytimes like check executeable

**Comment by JanDeDobbeleer** [comment]
@deeplee it only updates on a new version, not every time it starts.

**Comment by deeplee** [comment]
@JanDeDobbeleer 

it look everytimes because I delete executeable it will download when restart pwsh

**Comment by JanDeDobbeleer** [comment]
Yes, but that's expected behavior. In the case your connection works, it only does this once per version. The issue is that your network is somehow blocking the download. And that's something I can't fix for you. The best thing is to remove the module and install via winget.

**Comment by JanDeDobbeleer** [comment]
@deeplee **solution**: install via winget rather than the powershell module:

```powershell
Uninstall-Module -Name oh-my-posh --AllVersions
winget install JanDeDobbeleer.OhMyPosh
```

restart Windows Terminal and edit your `$PROFILE`

```powershell
oh-my-posh --init --shell pwsh --config "$env:POSH_THEMES_PATH/gmay.omp.json" | Invoke-Expression
```
