### ISSUE TITLE
[Request] Provides a preview page for themes similar to oh-my-zsh.

### ISSUE THREAD

**Issue by Vixb1122** [JanDeDobbeleer/oh-my-posh#183]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

1. Provide a preview page of a theme similar to [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes) for selecting a theme.
2. Or support for importing oh-my-zsh themes.

**Comment by JanDeDobbeleer** [comment]
1. could work, but I'd rather loop the themes and print them for example (this functionality exists in the Powershell package)
2. technically not possible

**Comment by catthehacker** [comment]
I wouldn't mind making list of themes with screenshots.

**Comment by JanDeDobbeleer** [comment]
> I wouldn't mind making list of themes with screenshots.

@CatTheHacker would be interesting to add that to the docs. Feel free to give it a go.
