### ISSUE TITLE
feat(winget-release): replace existing manifests

### ISSUE THREAD

**Issue by vedantmgoyal9** [JanDeDobbeleer/oh-my-posh#1832]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

When submitting manifests to the winget-pkgs repository, can you please refactor the automation so that it should update existing manifests instead of creating a new version directory every time and publishing new manifests in that? 

Since it won't affect the users and functionality will be the same while doing `winget install` and `winget upgrade` and winget doesn't require a previous version manifest to detect an upgrade (see: https://github.com/microsoft/winget-pkgs/issues/38444#issuecomment-999601658), I don't think there should be any problem.

P.S. This is a suggestion, and I don't mean that you must implement it. It completely depends on you and your choice.

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 we use [wingetcreate](https://github.com/microsoft/winget-create) for that so I'm following their practices. Feel free to create a feature request there ;-)

**Comment by vedantmgoyal9** [comment]
Would you allow me to remove previous versions manually until wingetcreate supports overwriting manifests?

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 sure, don't see a problem with that.

**Comment by vedantmgoyal9** [comment]
Okay, thanks 😀

**Comment by vedantmgoyal9** [comment]
@JanDeDobbeleer since you release very frequently, would it be ok to keep only last N version in WinGet repo?

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 of course. Latest would also work for me.
