### ISSUE TITLE
Powershell: Import-Module fails with oh-my-posh 7.27.0

### ISSUE THREAD

**Issue by h-tw** [JanDeDobbeleer/oh-my-posh#1833]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

Hi all. 

`Import-Module oh-my-posh` fails with 

`Invoke-WebRequest: Could not find a part of the path 'C:\Users\<user>\AppData\Local\oh-my-posh\oh-my-posh.exe`

This happens when I do an install via `Install-Module oh-my-posh -Scope CurrentUser` as well as an update via `Update-Module oh-my-posh -Scope CurrentUser`. Doesn't work in PowerShell Desktop and PowerShell Core.  When installing a prior version (7.26.0) everything works fine.

Shell versions:
PowerShell 5.1.19041.1320
PowerShellCore 7.2.1 

Best 
h-t-w

### Theme

-

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
-
```

**Comment by JanDeDobbeleer** [comment]
@h-t-w I'm reverting the cache path, looking at that we're facing multiple issues.

**Comment by JanDeDobbeleer** [comment]
@h-t-w do you have the `C:\Users\<user>\AppData\Local\oh-my-posh\` folder?

**Comment by h-tw** [comment]
@JanDeDobbeleer 

Fix seems to work. Thanks for the quick replies.

FIY: Prior to the fix I didn't have a `\Users\<user>\AppData\Local\oh-my-posh\` folder. The only folder was `C:\Users\<user>\Documents\PowerShell\Modules\oh-my-posh`

**Comment by JanDeDobbeleer** [comment]
@h-t-w while going through the changes I did I noticed a logic error which resulted into not creating the `oh-my-posh` folder (it validated the same root path rather than that one), [this](https://github.com/JanDeDobbeleer/oh-my-posh/commit/c098391ff75d168e1ddcca8bd95f6a0220ee43e8) change should address that.

If changing that also makes the download and prompt work this can be closed.

**Comment by JanDeDobbeleer** [comment]
@h-t-w please try again when [7.27.1](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v7.27.1) is available.

**Comment by h-tw** [comment]
@JanDeDobbeleer 

Sure. I just checked with the 7.21.1 release. Does work.

I'll close the issue.
