### ISSUE TITLE
Missing icons in VSCode integrated terminal on UBUNTU

### ISSUE THREAD

**Issue by YoushaaMurhij** [JanDeDobbeleer/oh-my-posh#1850]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!
The icons are missing in VSCode integrated terminal even if using Nerd fonts.

### Theme

I am using _jandedobbeleer_ theme.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```shell
 josh    latency   master ↓6  +30 ~3   2.7.18  ﮫ0ms⠀                                                                             zsh  13:39:37 
 josh    latency   master ↓6  +30 ~3   2.7.18  ﮫ0ms⠀                                                                             zsh  13:39:39 
 josh    latency   master ↓6  +30 ~3   2.7.18  ﮫ0ms⠀                                                                                                                                                                                    zsh  13:39:39 
```

**Comment by JanDeDobbeleer** [comment]
@YoushaaMurhij do you have a screenshot?

**Comment by YoushaaMurhij** [comment]
![Screenshot from 2022-03-01 14-50-39](https://user-images.githubusercontent.com/16229594/156164290-a99ba82a-a1d4-41d1-a73d-210224605b9c.png)

**Comment by JanDeDobbeleer** [comment]
@YoushaaMurhij the font has not been set correctly as otherwise that would show (fonts are always outside of our control, that's a terminal setting). Have a look at [this](https://youngstone89.medium.com/how-to-change-font-for-terminal-in-visual-studio-code-c3305fe6d4c2) post to get you going.

**Comment by YoushaaMurhij** [comment]
Thanks for your response! I checked my settings. It does not seem to fix the problem. I face this problem only on Ubuntu.

**Comment by JanDeDobbeleer** [comment]
@YoushaaMurhij check that the font name is the same on every platform, it's not necessarily identical.
