### ISSUE TITLE
Anti virus engine detected issues

### ISSUE THREAD

**Issue by marko444** [JanDeDobbeleer/oh-my-posh#186]
Can you please double check if the warnings found on your release binaries are false positives?

https://www.virustotal.com/gui/file/301f7d9f010e8eb087493dd29e6f16b8c6aaa746ae8d1bb55036f20b22e71e4d/community

Regards,
Marko

**Comment by JanDeDobbeleer** [comment]
Probably because it accesses `kernel32.dll` to figure out certain stuff. Given that I own the source, the builds are done completely within the GitHub ecosystem, yes these are false positives. I do not pack malware, which I hope can be illustrated by the source and build pipeline available here.
