### ISSUE TITLE
Something wrong with windos amd64 installer

### ISSUE THREAD

**Issue by saboco** [JanDeDobbeleer/oh-my-posh#1862]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Something is wrong with the installer, it does nothing, hence I don't have any error to show here, only thing I know is oh-my-posh is not installed.

### Theme

none yet

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
have no logs
```

**Comment by saboco** [comment]
Actually it is installed, just so fast! and as before installing with chocolatey would install the powershell module I got confused because no powershell module was installed... now I know I should use the cli

**Comment by JanDeDobbeleer** [comment]
@saboco yes, indeed. When installing using the installer (or winget) you only get the CLI which contains everything the module also has. The module is just a wrapper around the CLI anyways and can be seen as an alternative installation method more than anything else.
