### ISSUE TITLE
Feature Request: Support regex patterns for ignore_folders

### ISSUE THREAD

**Issue by DotNetSparky** [JanDeDobbeleer/oh-my-posh#187]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

It would be cool to be able to specify regex patterns for the "ignore_folders" property.  Currently, it seems to require being an exact match to the full path (so it doesn't even match sub-directories).

Probably should be a separate property (e.g. "ignore_folders_regex") so as to not be a breaking change to existing configurations.

(it would also be cool to have a property that does the opposite--i.e. the segment will only be used if there IS a match)

My goal is to have some conditional "extras" that only show when I'm in certain project folders.

**Comment by JanDeDobbeleer** [comment]
I don't think this is impossible, let's try it.

**Comment by lnu** [comment]
would be nice to have the same for the mappedLocations in the path segment.

**Comment by JanDeDobbeleer** [comment]
@DotNetSparky good news, it's backwards compatible AND you can choose to do the opposite as well using a [negative lookahead](https://www.regular-expressions.info/lookaround.html). The docs will contain all information to get this up and running.

@lnu can you create a new issue for the `mapped_locations` regex?

**Comment by DotNetSparky** [comment]
@JanDeDobbeleer - That is awesome, thank-you!
