### ISSUE TITLE
Support the Znap plugin manager for zsh

### ISSUE THREAD

**Issue by TheOnlyTails** [JanDeDobbeleer/oh-my-posh#1881]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The [Znap](https://github.com/marlonrichert/zsh-snap) plugin manager is a way to install zsh plugins and prompts, and it would be awesome to have Oh My Posh support the `prompt` function (with something like `znap prompt jandedobbeleer/oh-my-posh`).

**Comment by JanDeDobbeleer** [comment]
@TheOnlyTails is there a guide somewhere on how to add a package? I couldn't immediately find that.

**Comment by TheOnlyTails** [comment]
Me neither lol, I'll search for stuff and let you know if I find something.

**Comment by JanDeDobbeleer** [comment]
@TheOnlyTails confirmed to work with the latest changes using:

```zsh
znap eval ohmyposh 'oh-my-posh --shell zsh --print-init --config=myconfig.omp.json'
znap prompt
```

You still need to install oh-my-posh as standalone, but that's the same as starship (I did the research).

**Comment by TheOnlyTails** [comment]
Awesome, thanks!
