### ISSUE TITLE
Feature Request: Add Scoop and/or winget to the package managers you'll support

### ISSUE THREAD

**Issue by cprivitere** [JanDeDobbeleer/oh-my-posh#189]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

Chocolatey is poorly maintained and not going in a great direction at the moment. Scoop is doing much better and doesn't require admin privileges to run, so bonus there. winget will be the future but is taking a while for microsoft to finish, so if you don't want to jump on board with it yet, that's understandable.

**Comment by JanDeDobbeleer** [comment]
Good news @cprivite, [Scoop](https://ohmyposh.dev/docs/scoop) is available ;-) As for Winget, I was waiting on a stable basis (and a Windows machine too).
