### ISSUE TITLE
oh-my-posh is slow but shows no spikes in the debug view

### ISSUE THREAD

**Issue by KabelitzJ** [JanDeDobbeleer/oh-my-posh#1904]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am using `PowerShell 7` and when I use `oh-my-posh` the shell gets very slow.
Even when I am not in a git repository and just press enter.
When I disable `oh-my-posh` the shell behaves normaly

### Theme

theme:
```
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "type": "prompt",
      "segments": [
        {
          "foreground": "#86E033",
          "properties": {
            "template": "{{ .UserName }}@{{ .HostName }}"
          },
          "style":"plain",
          "type": "session"
        }
      ]
    }
  ],
  "console_title": true,
  "console_title_style": "template",
  "console_title_template": "{{.Folder}}",
  "final_space": true,
  "version": 1
}

```
profile:
```
# Initalize OhMyPosh
$env:AZ_ENABLED=$false
oh-my-posh --init --shell pwsh --config "~/.oh-my-posh/kabelitzj.omp.json" | Invoke-Expression

```

timing of loading the profile:
```
jonas@DESKTOP-OIS92OO Measure-Command {. $PROFILE}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 396
Ticks             : 43969497
TotalDays         : 5,08906215277778E-05
TotalHours        : 0,00122137491666667
TotalMinutes      : 0,073282495
TotalSeconds      : 4,3969497
TotalMilliseconds : 4396,9497
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
jonas@DESKTOP-OIS92OO Write-PoshDebug

Version: 7.35.0

Segments:

ConsoleTitle(true) -   0 ms -
session(true)  -   0 ms - jonas@DESKTOP-OIS92OO

Run duration: 551.1µs

Cache path: C:\Users\jonas\AppData\Local\oh-my-posh

Logs:

2022/03/11 16:15:09 Args duration: 0s, args:
2022/03/11 16:15:09 Args duration: 0s, args:
2022/03/11 16:15:09 Args duration: 0s, args:
2022/03/11 16:15:09 Shell duration: 4.7409ms, args:
2022/03/11 16:15:09 debug: Getenv

2022/03/11 16:15:09 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/03/11 16:15:09 Root duration: 503.1µs, args:
2022/03/11 16:15:09 Shell duration: 0s, args:
2022/03/11 16:15:09 ErrorCode duration: 0s, args:
2022/03/11 16:15:09 IsWsl duration: 0s, args:
2022/03/11 16:15:09 debug: Pwd
C:\Users\jonas
2022/03/11 16:15:09 Pwd duration: 0s, args:
2022/03/11 16:15:09 debug: Home
C:\Users\jonas
2022/03/11 16:15:09 PathSeparator duration: 0s, args:
2022/03/11 16:15:09 PathSeparator duration: 0s, args:
2022/03/11 16:15:09 User duration: 0s, args:
2022/03/11 16:15:09 Host duration: 0s, args:
2022/03/11 16:15:09 GOOS duration: 0s, args:
2022/03/11 16:15:09 TemplateCache duration: 551.1µs, args:
2022/03/11 16:15:09 debug: Pwd
C:\Users\jonas
2022/03/11 16:15:09 Pwd duration: 0s, args:
2022/03/11 16:15:09 debug: Home
C:\Users\jonas
2022/03/11 16:15:09 debug: Getenv

2022/03/11 16:15:09 Getenv duration: 0s, args: SSH_CONNECTION
2022/03/11 16:15:09 debug: Getenv

2022/03/11 16:15:09 Getenv duration: 0s, args: SSH_CLIENT
2022/03/11 16:15:09 TemplateCache duration: 0s, args:
2022/03/11 16:15:09 debug: Getenv
C:\Users\jonas\AppData\Local
2022/03/11 16:15:09 Getenv duration: 0s, args: LOCALAPPDATA
2022/03/11 16:15:09 CachePath duration: 528.6µs, args:
```

**Comment by JanDeDobbeleer** [comment]
@KabelitzJ previously this was because defender or an anti virus was blocking the execution. Adding an exclusion solves this instantly.

**Comment by KabelitzJ** [comment]
@JanDeDobbeleer What files/folders do I need to exclude to solve this?

**Comment by JanDeDobbeleer** [comment]
@KabelitzJ depends on how you installed it, you should be able to see that in defender already

**Comment by JanDeDobbeleer** [comment]
@KabelitzJ were you able to exclude it?

**Comment by KabelitzJ** [comment]
@JanDeDobbeleer Yes, thank you for the quick help

**Comment by drobiu** [comment]
Hey @KabelitzJ I think I might be struggling with a similar problem, yet I'm unable to find anything in the defender. What exactly did you exclude? Was it the .exe file? We are talking about windows defender firewall, right?

**Comment by JanDeDobbeleer** [comment]
@drobiu https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by drobiu** [comment]
Well, adding oh-my-posh.exe to the exclusion list didn't help, ~so I'm guessing it has to do with something else~. I'll poke around and if nothing helps I'll create an issue.

Edit: It has to be the defender, when I hold down enter in the terminal - thus getting some lag - the antivirus service in the task manager takes a lot of resources.

**Comment by JanDeDobbeleer** [comment]
@drobiu you need to exclude the full path to the executable if I'm not mistaken.

**Comment by JayeshC-2598** [comment]
I just installed oh-my-posh and added a theme on git bash and windows terminal. As I initialized oh-my-posh on terminal it was working fine, the code were running fast but now my both the terminals are getting slow I tried to restart the terminal but it takes to much time load.

**Comment by JanDeDobbeleer** [comment]
@JayeshC-2598 how did you install? Make sure you're either using the winget or Store build. Scoop isn't serving signed binaries.

**Comment by ezhupa99** [comment]
I think it's just slow because this is the normal state of the terminal

![image](https://user-images.githubusercontent.com/34006441/224202548-9cc1a143-802b-4633-b435-2c5ef6b5ee2f.png)

and this is the processes that are spawning on just pressing enter on Angular working dir
![image](https://user-images.githubusercontent.com/34006441/224202757-a4f942a9-4fbb-474d-9a44-5e3436a0e5b3.png)

**Comment by petrsapak** [comment]
I had the same issue. Adding bitdefender exception solved it. Now the exception was to path returned by:
`Get-Command oh-my-posh | Select-Object $_ -ExpandProperty Source`
