### ISSUE TITLE
oh-my-posh attempts to use 64-bit binary on 32-bit Windows machine

### ISSUE THREAD

**Issue by sba923** [JanDeDobbeleer/oh-my-posh#1908]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

My PowerShell "modules" folder is sync'ed between all my PCs via OneDrive.

One of those machines is an old 32-bit Windows 10 PC I just keep to run whatever doesn't cope with 64-bit Windows.

On that machine, I get:

![image](https://user-images.githubusercontent.com/12860484/158025495-1abec739-2a8c-40c7-bf6e-95a5c8acc16f.png)

### Theme

[sba.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/8237909/sba.zip)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
(I can't run either command, for obvious reasons)
```

**Comment by JanDeDobbeleer** [comment]
@sba923 that's not a bug but expected. Please do not do this for oh-my-posh as well always fetch the binary based on the system we run on. As the module is a wrapper around the binary, I advice to move to winget or scoop and simply remove the module.

**Comment by sba923** [comment]
Actually I think my way of formulating the issue was quite confusing / incorrect.

I should have called this "cannot share module deployment folder between different architectures" -- which BTW is not an issue specific to `oh-my-posh` but to all modules that contain _native_ executables.

I will think of a way to have that (single) 32-bit machine have a different `$env:PSModulePath` with a `x86` folder _ahead_ of the folder(s) that are shared with the 64-bit machines. This way, I will be able to have the 32-bit `oh-my-posh` (auto)downloaded to that `x86` folder, ignoring the folder later on `$env:PSModulePath` that contains the 64-bit oh-my-posh binary.

**Comment by JanDeDobbeleer** [comment]
@sba923 I understood the issue. Originally we shipped all binaries which makes things work, but has a ton of overhead. BTW, do you then also sync the local app data folder?

**Comment by sba923** [comment]
No I don't sync _that_.

For now I'm struggling with installing the module on the 32-bit machine into that `x86` folder:


````text
PS 7.2.1 C:/Users/<REDACTED>> $env:PSModulePath -split ';'
C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\x86
C:\Program Files\PowerShell\Modules
c:\program files\powershell\7\Modules
C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\x86
C:\Program Files\WindowsPowerShell\Modules
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
C:\Users\<REDACTED>\OneDrive\Documents\WindowsPowerShell\Modules

PS 7.2.1 C:/Users/<REDACTED>> install-module oh-my-posh -ver
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='oh-my-posh'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'oh-my-posh'.
VERBOSE: Performing the operation "Install-Module" on target "Version '7.37.2' of module 'oh-my-posh'".

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
VERBOSE: The installation scope is specified to be 'CurrentUser'.
VERBOSE: The specified module will be installed in 'C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules'.
WARNING: Version '7.28.0' of module 'oh-my-posh' is already installed at 'C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules\x86\oh-my-posh\7.28.0'. To install version '7.37.2', run Install-Module and add the -Force parameter, this command will install version '7.37.2' side-by-side with version '7.28.0'.
````

How come the folder `Install-Module` wants to install into is not `C:\Users\<REDACTED>\OneDrive\Documents\PowerShell\Modules**\x86**`?

**Comment by sba923** [comment]
BTW, I've been wondering for some time why the executable is downloaded to `...\Modules\oh-my-posh` and not to `...\Modules\oh-my-posh\<version_number>`. 

Side-by-side installation of multiple versions, even temporarily 'cos the `...\Modules\oh-my-posh` folder is shared / sync'ed between systems but several of them have a handle on the executable for a non-latest version, can't work IMVHO the way files are deployed today.

Or am I missing something?

**Comment by JanDeDobbeleer** [comment]
@sba923 all you need to do is update to the latest version. As that will install in app data local, meaning it should also install the right executable per machine. We moved that location a while ago.

**Comment by JanDeDobbeleer** [comment]
@sba923 on why Install-Module doesn't do what you expect it to do, I have no idea. Out of scope of oh-my-posh 😃
