### ISSUE TITLE
feat: managing themes from the command line

### ISSUE THREAD

**Issue by Vixb1122** [JanDeDobbeleer/oh-my-posh#191]
### Describe the solution you'd like
Just Like oh-my-zsh:
```powershell
# List all available oh-my-posh themes, similar to omz theme list
oh-my-posh -theme list
# Set global theme, similar to omz theme use <theme>
oh-my-posh -theme global <theme>
# Set local theme
oh-my-posh -theme use <theme>
```
### Describe alternatives you've considered
1. Set environment variables
```powershell
$env:Path="C:\tools\oh-my-posh.exe;$env:Path"
[environment]::setEnvironmentVariable('Path',"$env:Path",'User')
$env:OMP_THEME_PATH="$env:USERPROFILE\.poshthemes"
[environment]::setEnvironmentVariable('OMP_THEME_PATH',"$env:OMP_THEME_PATH",'User')
$env:OMP_THEME_NAME="material"
[environment]::setEnvironmentVariable('OMP_THEME_NAME',"$env:OMP_THEME_NAME",'User')
```
2. Update initialization script
* Replace `$startInfo.FileName = "C:\tools\oh-my-posh.exe"` with `$startInfo.FileName = "oh-my-posh.exe"`
* Replace `$startInfo.Arguments = "-config=""C:\Users\User\.poshthemes\jandedobbeleer.json"" -error=$errorCode -pwd=""$cleanPWD"""` with 
```powershell
$themeName = [environment]::GetEnvironmentvariable("OMP_THEME_NAME", "User")
$startInfo.Arguments = "-config=""$OMP_THEME_PATH\$themeName.json"" -error=$errorCode -pwd=""$cleanPWD"""
```
3. List all available oh-my-posh themes
```powershell
Get-ChildItem "$env:OMP_THEME_PATH" | Select-Object -ExpandProperty BaseName
```
4. Set local theme
```powershell
$env:OMP_THEME_NAME="fish"
```
5. Set global theme
```powershell
$env:OMP_THEME_NAME="fish"
[environment]::setEnvironmentVariable('OMP_THEME_NAME',"$env:OMP_THEME_NAME",'User')
```
### Environment
- Oh my Posh version: 3.44.1
- Theme: Material
- Operating System: Windows 10
- Shell: PowerShell
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
This is available in the PowerShell package. When installing omz it also packs the themes, that's not the same here depending on what you do. For PowerShell, Scoop and Homebrew this is true, but not for manual installs and definitely not in terms of function definition.

**Comment by Vixb1122** [comment]
Is there another way to implement this feature?

**Comment by JanDeDobbeleer** [comment]
> Is there another way to implement this feature?

I was thinking of reworking `main.go` to include a flag like `-render-themes` which accepts a path. This can then loop and display every file in the folder that matches a theme definition (will tackle that in #184 -> `*.omp.json`)

**Comment by JanDeDobbeleer** [comment]
Looking at this again with a fresh set of eyes, it's not something that the executable should provide. We now have the preview page, the Powershell package has the `Get-PoshThemes` cmdlet and if you're on bash/zsh, it's rather easy to do using `for file in themes/*.omp.json; do echo "$file\n"; oh-my-posh --config $file --shell universal; echo "\n"; done;`

**Comment by Vixb1122** [comment]
There is not a `Get-PoshThemes` cmdlet in the powershell package if you install this program manually.

**Comment by JanDeDobbeleer** [comment]
That's right, I'm writing a small addition to the docs. I expect people to know how to do this when they go down the manual route ;-)
