### ISSUE TITLE
app fails to run after latest update to 7.37.1

### ISSUE THREAD

**Issue by ATGardner** [JanDeDobbeleer/oh-my-posh#1913]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

this morning i upgraded to 7.37.1 on both my windows, wsl and pi-hole machines in parallel. usually this process works without any problems.
after the upgrade, i am getting this error message on every prompt in all of my shells:
```terminal
Error: unknown flag: --error
Usage:
  oh-my-posh [flags]
  oh-my-posh [command]
System.Management.Automation.RemoteException
Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Interact with the configuration
  help        Help about any command
  prompt      Setup the prompt for your shell
  version     Print the version
System.Management.Automation.RemoteException
Flags:
  -c, --config string   config (required)
  -h, --help            help for oh-my-posh
  -i, --init            init (deprecated)
  -s, --shell string    shell (deprecated)
System.Management.Automation.RemoteException
Use "oh-my-posh [command] --help" for more information about a command.
System.Management.Automation.RemoteException
unknown flag: --error
```

i can't even run `oh-my-posh version` - it fails with the same error
i haven't tried on my macos yet. i am hesitant to try, since it is my main work environment

### Theme

i am not sure it is relevant.

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

zsh, powershell

### Log output

```shell
i get the same error output as above. it doesn't seem like the --debug flag is doing anything.
```

**Comment by JanDeDobbeleer** [comment]
@ATGardner if you didn't install via the PowerShell Module, all you need to do is restart your shell.

**Comment by ATGardner** [comment]
Awesome. works like a charm. thanks.

**Comment by JanDeDobbeleer** [comment]
I'll revert the renames of certain CLI flags, as that's what causing this. It will confuse more people and doesn't matter that much. That means you'll see this one more time 😓
