### ISSUE TITLE
Export broken in YAML: map type properties do not parse correctly

### ISSUE THREAD

**Issue by asherber** [JanDeDobbeleer/oh-my-posh#1917]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

If I start with a valid yaml config from v5, the migration process does not work, and `Set-PoshPrompt` hangs. With a semi-complicated yaml file, the "migrated" file winds up just with the schema and version info, nothing else. With the simple theme file below, `Set-PoshPrompt` adds the `version` property and alphabetizes the other properties -- but it doesn't transform `prefix` and `postfix` into `template`, and the call never returns. With a more complicated file, the "transformed" yaml only contains the `version` property, nothing else.

Maybe this is a known issue?

### Theme

``` yaml
$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt,
    alignment: left,
    segments:     
      - type: shell,
        style: plain,
        properties:
          prefix: ''
          postfix: '> '
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Version: 7.37.2

Segments:

ConsoleTitle(false) -   0 ms -
shell(true)  -   1 ms - pwsh>

Run duration: 1.2272ms

Cache path: C:\Users\WDAGUtilityAccount\AppData\Local\oh-my-posh

Logs:

2022/03/13 15:05:32 Flags duration: 0s, args:
2022/03/13 15:05:32 Flags duration: 0s, args:
2022/03/13 15:05:32 Shell duration: 7.2514ms, args:
2022/03/13 15:05:32 debug: Getenv

2022/03/13 15:05:32 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/03/13 15:05:32 debug: Pwd
C:\Users\WDAGUtilityAccount\Documents\PowerShell
2022/03/13 15:05:32 Pwd duration: 0s, args:
2022/03/13 15:05:32 debug: Home
C:\Users\WDAGUtilityAccount
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 debug: Pwd
C:\Users\WDAGUtilityAccount\Documents\PowerShell
2022/03/13 15:05:32 Pwd duration: 0s, args:
2022/03/13 15:05:32 debug: Home
C:\Users\WDAGUtilityAccount
2022/03/13 15:05:32 Shell duration: 0s, args:
2022/03/13 15:05:32 Root duration: 0s, args:
2022/03/13 15:05:32 Shell duration: 0s, args:
2022/03/13 15:05:32 ErrorCode duration: 0s, args:
2022/03/13 15:05:32 IsWsl duration: 0s, args:
2022/03/13 15:05:32 debug: Pwd
C:\Users\WDAGUtilityAccount\Documents\PowerShell
2022/03/13 15:05:32 Pwd duration: 537.9µs, args:
2022/03/13 15:05:32 debug: Home
C:\Users\WDAGUtilityAccount
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 PathSeparator duration: 0s, args:
2022/03/13 15:05:32 User duration: 0s, args:
2022/03/13 15:05:32 Host duration: 63.5µs, args:
2022/03/13 15:05:32 GOOS duration: 0s, args:
2022/03/13 15:05:32 TemplateCache duration: 601.4µs, args:
2022/03/13 15:05:32 debug: Getenv
C:\Users\WDAGUtilityAccount\AppData\Local
2022/03/13 15:05:32 Getenv duration: 0s, args: LOCALAPPDATA
2022/03/13 15:05:32 CachePath duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@asherber I'll try tomorrow but it should export as that has nothing to do with the migration provided it can read the config (as we migrate on the object).

**Comment by asherber** [comment]
No rush on this, I've managed to migrate my theme file by hand.

**Comment by JanDeDobbeleer** [comment]
@asherber confirmed to not work. I'll see what the issue is.

**Comment by JanDeDobbeleer** [comment]
@asherber the reason the example above doesn't work is because it has trailing comma's in the strings (and thus the values are invalid and won't get migrated). I did find an issue in the migration, that made the CLI act weird, so I'll push that fix, and with the right config, everything gets migrated correctly now:

```yaml
$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: shell
        style: plain
        properties:
          prefix: ''
          postfix: '> '
```

```yaml
> oh-my-posh config migrate --config ~/.test.omp.yml --format yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
- alignment: left
  segments:
  - properties:
      template: '{{ .Name }}> '
    style: plain
    type: shell
  type: prompt
version: 1
```

**Comment by asherber** [comment]
@JanDeDobbeleer Well now it's my turn to slap my forehead! As I was trying to work out migrating my config, I was going back and forth between json and yaml with simple examples, and clearly I screwed something up with this file.

I do have another file -- my real theme -- which is clean yaml, no trailing commas, and which continues to flummox v7.39.0. Attached [here](https://github.com/JanDeDobbeleer/oh-my-posh/files/8245027/aas.omp.yaml.txt) in case you want to look at it. (I had to change the extension to txt to get GH to upload.)

**Comment by JanDeDobbeleer** [comment]
@asherber I found the issue. When using YAML the maps aren't able to marshal to JSON (we do that for syncing the config object in memory to the one we need for export. I'll try to find the solution.

**Comment by JanDeDobbeleer** [comment]
@asherber the issue is located around the following part:

```yaml
mapped_shell_names:
  pwsh: PS
```

This is also only an issue in YAML, it parses correctly everywhere else.

**Comment by JanDeDobbeleer** [comment]
@asherber important question, I'm about to drop YAML support as it has a few structural issues I can't resolve easily. Thoughts?

**Comment by asherber** [comment]
Thanks for asking, but ack! Aside from the fact that I prefer yaml to json for config files like this in general (I find it more readable and easier to write), with the recent introduction of templates to OMP I find it essential, because I can make use of yaml line folding to do this:

```yaml
  template: |-
    [{{.HEAD}}{{.BranchStatus}}
    {{- if .Working.Changed}} wk {{.Working.String}}{{end}}
    {{- if and (.Staging.Changed) (.Working.Changed)}} |{{end}}
    {{- if .Staging.Changed}} st {{.Staging.String}}{{end}}]
```

Instead of this less readable very long line:

```json
"template": "[{{.HEAD}}{{.BranchStatus}}{{if .Working.Changed}} wk {{.Working.String}}{{end}}{{if and (.Staging.Changed) (.Working.Changed)}} |{{end}}{{if .Staging.Changed}} st {{.Staging.String}}{{end}}]"
```

Having said that, I have no idea what others use, and if you drop yaml support I'll figure out something for me -- either keep a yaml file that my profile JIT converts to json for OMP, or bite the bullet and live with those dreadfully long lines.

Some crazy thoughts off the top of my head:

*   Maybe don't try to migrate yaml files, but print out some message to that effect to the user?
*   Maybe migrate yaml files and spit them back out as json? Since yaml is a superset of json, you could write the json back out to the original .yaml file. (I would warn the user, though.)
*   Addressing my specific peeve about json in this case, what if `template` could be an array of string, and OMP automatically concatenated the values, thereby mimicking yaml line folding? That would make me miss yaml less.

**Comment by JanDeDobbeleer** [comment]
@asherber yes, I was thinking in the exact same direction 😁 Allow me to draft something.

**Comment by JanDeDobbeleer** [comment]
@asherber found the fix for the other issue, not ideal but it will at least keep things working #1961. I'm still going to see if I can fix this issue.

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer I am not currently using YAML, but had intended to migrate to it at some point in the future since I've been working with it a lot at my job and it's absolutely fantastic for config files (Adding comments is an especially useful feature of YAML that I miss when trying to untangle my past JSON scribblings)

Having seen this conversation I just want to say that I would still *like* to use YAML in the future, but I understand if it's too much work for a niche feature (albeit one that would likely be less niche if there was more documentation accompanying it).

To that end, if you do end up deciding to commit to future YAML support I'd be happy to help flesh out the docs with a YAML page and some examples (perhaps TOML as well if I brush up enough). I suspect that @asherber would feel similarly.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg there's only one issue I still need to look at, YAML isn't going anywhere.

**Comment by ehawman-rosenberg** [comment]
Love it. I'll put YAML documentation on my to-do list.

**Comment by ehawman-rosenberg** [comment]
On that note, if I wanted to convert `devious-diamonds` to a yml for my own use, would you want to keep the official submitted version in JSON format or are you open to having an "official" yml theme?

**Comment by JanDeDobbeleer** [comment]
They can be either format imho.

**Comment by JanDeDobbeleer** [comment]
@asherber this seems fixed with a recent dependency update.
