### ISSUE TITLE
Allow Define Path For oh-my-posh.exe

### ISSUE THREAD

**Issue by yekanchi** [JanDeDobbeleer/oh-my-posh#1919]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

by default oh-my-posh automatically downloads `themes ` and `oh-my-posh.exe` to default user profile. let user define another path when we want to use oh-my-posh with portable PowerShell installation.

**Comment by JanDeDobbeleer** [comment]
@yekanchi you can now set `$env:POSH_PATH` **_before_** importing oh-my-posh:

```powershell
$env:POSH_PATH = "$HOME/poshpath"
Import-Module oh-my-posh
...
```

**Comment by yekanchi** [comment]
> @yekanchi you can now set `$env:POSH_PATH` **_before_** importing oh-my-posh:
> 
> ```powershell
> $env:POSH_PATH = "$HOME/poshpath"
> Import-Module oh-my-posh
> ...
> ```

this works.
