### ISSUE TITLE
Ability to add git status to the console title / cleanse environment variables

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#1922]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Please add the ability to include the git status to the console title. I still use Posh Git in my Windows 10 powershell 7 terminal and it does set the POSH_GIT_STATUS environment variable that I could use but OMP doesn't like it to be added to my console_title_template, e.g.:

 "console_title_template": "{{ if .Root }}(Admin) {{ end }}{{ .Folder }}{{ .Env.POSH_GIT_STATUS }}"

I assume it is because it is full of escape characters to colourise it. Could it be possible to cleanse this variable so that it can be added to the console title?

**Comment by JanDeDobbeleer** [comment]
@piersmyers confirmed to be ANSI. Will tackle that.

**Comment by JanDeDobbeleer** [comment]
@piersmyers 

![image](https://user-images.githubusercontent.com/2492783/158262283-7d4ff6e9-10c3-4c9b-b177-33486cec425e.png)

**Comment by piersmyers** [comment]
Awesome, thank you so much for doing this so quickly Jan, works perfectly now. You're a ⭐.
