### ISSUE TITLE
Installing through Install-Module failed

### ISSUE THREAD

**Issue by kraussian** [JanDeDobbeleer/oh-my-posh#1935]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've installed oh-my-posh on Windows Powershell following the docs:
`Install-Module oh-my-posh -Scope CurrentUser`

The command silently completes without giving any errors.

But when I restart PowerShell and try to invoke oh-my-posh, I get the error:
`oh-my-posh : The term 'oh-my-posh' is not recognized as the name of a cmdlet, function, script file, or operable program.`

`$env:POSH_PATH` also appears to be missing.

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Write-PoshDebug : The term 'Write-PoshDebug' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

**Comment by JanDeDobbeleer** [comment]
@kraussian from the [docs](https://ohmyposh.dev/docs/prompt):

CAUTION

If you installed Oh My Posh using `Install-Module oh-my-posh`, you need to first import Oh My Posh in your $PROFILE before adding the line above:

```PowerShell 
Import-Module oh-my-posh
```
