### ISSUE TITLE
dotnet segment matches folder names as well as file names

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#1938]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The dotnet segment file pattern matching matches folders as well as files. The matching should only be for files, not folders. For example, with a folder structure like this:

```
└root
    └folder1
    └folder2
    └folder.cs
        └file1
        └file2
```

The folder called 'folder.cs' causes the dotnet segment logic to think the 'root' folder is a .NET folder.

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@piersmyers honest question. Who creates a folder with a file extension?

**Comment by piersmyers** [comment]
Well, me for a start 😉. Although I got it when I cloned this repo: https://github.com/migueldeicaza/gui.cs

**Comment by JanDeDobbeleer** [comment]
@piersmyers as this is by design, I'll see what I can do to do things differently (if it doesn't impact performance). I agree it needs to be semantically correct, which it's isn't.

**Comment by piersmyers** [comment]
This is working perfectly now, thanks again Jan, you're a star :)
