### ISSUE TITLE
AgnosterPlus cuts out last line

### ISSUE THREAD

**Issue by catthehacker** [JanDeDobbeleer/oh-my-posh#195]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

AgnosterPlus cuts out last line of output

### Environment

- Oh my Posh version: 3.44.1
- Theme: AgnosterPlus
- Operating System: Ubuntu 20.04.1 LTS (focal)
- Shell: fish, version 3.1.0 | GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
- Terminal: Windows Terminal, Version: 1.4.3243.0

### Steps to Reproduce

1. Use theme AgnosterPlus
2. List files in directory

**Expected behavior:** Last line is not cut out

**Actual behavior:** Last line is cut out
![image](https://user-images.githubusercontent.com/31106839/100374457-9ad01100-300c-11eb-8f95-45940bb8baa6.png)
Top listing is AgnosterPlus
Bottom listing is Agnoster
You can see that `oh-my-posh3` folder isn't appearing, no idea if that is intentional. Doesn't happen in PowerShell because it prints one empty line at the end of output.

**Comment by JanDeDobbeleer** [comment]
That's probably due to moving the cursor up. Although it shouldn't clear the line behind the cursor, it is being cleared after the cursor. Pressing enter should in that case also clear the prompt.

**Comment by catthehacker** [comment]
![image](https://user-images.githubusercontent.com/31106839/100383140-38cbd780-301d-11eb-8377-b9e18533c8f5.png)
Just few `enter` presses

**Comment by JanDeDobbeleer** [comment]
Found the issue, will try to fix it. The problem is the line is cleared while moving the cursor. It should only do so after the last segment of a block.

**Comment by JanDeDobbeleer** [comment]
`3.44.3` should be available soon.
