### ISSUE TITLE
Broken Text in fish

### ISSUE THREAD

**Issue by carrotfarmer** [JanDeDobbeleer/oh-my-posh#1966]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After installing ohmyposh and reloading the fish session, the prompt started behaving weirdly. It works fine when I'm in the home directory or a level above it (Documents, Desktop, Pictures, etc.), but the prompt breaks when I go to a specific directory in this level. PFA screenshot:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/66675022/159435470-630a2060-0dff-43bc-ba7f-986446d635b2.png">

<img width="985" alt="image" src="https://user-images.githubusercontent.com/66675022/159435530-e27f3861-3af5-4091-a3eb-c7b11dd4326d.png">

<img width="989" alt="image" src="https://user-images.githubusercontent.com/66675022/159435567-53716323-1e88-47cb-8c3a-8a416bb51a7d.png">

When this happens, I am able to delete parts of the prompt when I hit the delete key like so:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/66675022/159435128-01e1c9dd-736c-4cb8-9f75-219416a08bb7.png">

### Theme

Default config

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

fish

### Log output

```shell
ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...

This ^ was because I tried to make my own config to see if this issue persists, but I ended up deleting it.
```

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer is this in Hyper terminal by any chance?

**Comment by carrotfarmer** [comment]
Yep!

**Comment by carrotfarmer** [comment]
Just wanted to add that this issue persists in iTerm2 too:
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/66675022/159448693-7af4c97e-7997-43f6-8ddd-3d06197473b3.png">

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer I will check somewhere during lunch, haven't seen this in any other shell but I don't use fish that often (I agree it's a very nice shell). Is this a folder a public git repo perhaps?

**Comment by carrotfarmer** [comment]
Yes, it is. All of the folders I tested this in are public git repos.

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer do you have the link? Just so that's it related.

**Comment by carrotfarmer** [comment]
yea sure:
https://github.com/carrotfarmer/cubedeck
https://github.com/carrotfarmer/blog-posts
https://github.com/genicsblog/theme-files

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer hmm, I can't reproduce this in iTerm, nor Hyper. I'm on the latest version of fish and only have the following line in my config:

`oh-my-posh prompt init fish | source`

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/2492783/159470131-1ae59865-bdbc-49d1-a5fe-7da23f762c04.png">


<img width="1099" alt="image" src="https://user-images.githubusercontent.com/2492783/159470084-8c3590ee-cdf0-44bd-a67c-8ecec5b4c729.png">

**Comment by carrotfarmer** [comment]
@JanDeDobbeleer Oh, I'm having the same issue after clearing out my config too... Do you have any idea why this could be happening? Is it something with my font? Because it's a nerd font (FiraCode Nerd Font) and it shouldn't cause any issues...

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer do you have the latest fish version?

**Comment by carrotfarmer** [comment]
No, I'll try upgrading now

**Comment by carrotfarmer** [comment]
@JanDeDobbeleer Ah, I'm having the same issue with the latest version (3.4.0) too lol

**Comment by karl-chanel** [comment]
try a different font ,even the same nerd font ,we can still see a different redering , I don't really know why, But you can see the difference When you switch it

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer the font can obviously have an influence on rendering, the extended background is a bug in ANSI rendering (but that can't just "happen", it needs to be reproducible). Did you tweak the theme a little bit? There might be something in your env that has ANSI escape sequences which ruins the rendering.

BTW, what is that initial symbol in your shell? That's not oh-my-posh.

**Comment by carrotfarmer** [comment]
@JanDeDobbeleer No, there are no such modifications in my configs. That symbol is vi mode for the shell, though this issue occurs even with vi mode disabled.

**Comment by carrotfarmer** [comment]
I'll try installing a new theme to see if there are glitches. Could just be the default theme's problem I guess...

**Comment by carrotfarmer** [comment]
@JanDeDobbeleer This issue isn't there with other themes, might be something with the default theme? Or could you try showing me the JSON config for the default theme?

**Comment by carrotfarmer** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/66675022/159659556-e25f0600-ac93-41e4-b427-f7717edbeb55.png">
I also tried it with this theme, which looks pretty similar to the default and it works fine too

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer you can look have a look [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/default.omp.json).

**Comment by karl-chanel** [comment]
<img width="709" alt="屏幕截图 2022-03-23 180938" src="https://user-images.githubusercontent.com/78248702/159675806-0e4ffd65-033b-475f-a2e6-091001459059.png">
<img width="662" alt="屏幕截图 2022-03-23 181052" src="https://user-images.githubusercontent.com/78248702/159675832-be2450a6-f56e-4111-8161-7c141aaf6209.png">
im sorry for not making it clear , what i mean is that i installed the codenewroman font(nerd font ) ,then i have several choices in the setting panel ,codenewroman nf renders like pic1,codenewroman nerd font mono renders like pic2, you can see the difference of the icon(not just happen in codenewroman ,cascaydiacove nerd font etc),i dont know the reason but the problem has been there for a long time and still exist,i didnt file an issue ,cause pic 1 works fine with me (pic 2 the icon is too small),ireally dont n why ,maybe it's a bug you  dont realize or it's just natural, just telling you

**Comment by karl-chanel** [comment]
<img width="943" alt="屏幕截图 2022-03-23 183420" src="https://user-images.githubusercontent.com/78248702/159680461-fed06f06-6f1c-41b0-9da1-9247b99b865c.png">
<img width="925" alt="屏幕截图 2022-03-23 183449" src="https://user-images.githubusercontent.com/78248702/159680474-44178431-5efe-4e4c-8d45-70032cb9741f.png">

here is more comparison

**Comment by carrotfarmer** [comment]
> @carrotfarmer you can look have a look [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/default.omp.json).

Yeah, it's a problem with the theme, ig. It still doesn't work.

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer can you comment out segments until it doesn't happen anymore? Trying to find the culprit.

**Comment by carrotfarmer** [comment]
Yea

**Comment by JanDeDobbeleer** [comment]
@karl-chanel font rendering is never something oh-my-posh can influence (it even differs per shell, you can also see that in my screenshots above). It's not because the front have been patched with the same glyphs that they also render equally. oh-my-posh only outputs a set of characters and color indications using ANSI, it can't influence how the terminal renders that.

**Comment by karl-chanel** [comment]
> @karl-chanel font rendering is never something oh-my-posh can influence (it even differs per shell, you can also see that in my screenshots above). It's not because the front have been patched with the same glyphs that they also render equally. oh-my-posh only outputs a set of characters and color indications using ANSI, it can't influence how the terminal renders that.

thanks ,vscode and wt did a great job in rendering the font (apart from what i mentioned above ),but jetbrains ides did poorly,hoping there will be a change in the future, anyway thank u for ur reply

**Comment by JanDeDobbeleer** [comment]
@karl-chanel we even have a [FAQ](https://ohmyposh.dev/docs/faq#jetbrains-terminals-icons-do-not-render) item for that.

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer I noticed that hyperlinks can break the rendering, I have a fix in #2001. This could be related.

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer can you validate the latest release? We now have proper hyperlink parsing and character escaping

**Comment by carrotfarmer** [comment]
Sure @JanDeDobbeleer 
Sorry for the late response!

**Comment by carrotfarmer** [comment]
@JanDeDobbeleer I updated to version 7.61.0, and the issue still persists

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer I've been using fish as my daily driver, can't reproduce this in any way.

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer I actually found a way to reproduce this which implies a non-escaped character (`\c`)

**Comment by JanDeDobbeleer** [comment]
@carrotfarmer can you try again?
