### ISSUE TITLE
Latest Powershell Broke it? - StandardOutputEncoding is only supported when standard output is redirected

### ISSUE THREAD

**Issue by kdethlefs-lindsay** [JanDeDobbeleer/oh-my-posh#1967]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Install of Oh My Posh resulted in 
```
Downloading oh-my-posh executable for 7.46.1
Downloading oh-my-posh themes for 7.46.1
ResourceUnavailable: Program 'oh-my-posh.exe' failed to run: StandardOutputEncoding is only supported when standard output is redirected.At
```

every time I start up windows terminal/powershell. 

At first I thought it was my companies restriction on AppData applications, but I moved it to c:\winget (installed with winget) and it still gives me the error. It appears there's related errors on unrelated applications. The research I've seen is something related to PowerShell no longer providing a console on remote calls? I haven't dug into it too far.

Using powershell 7.2.2.

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
No output provided by command.
```

**Comment by kdethlefs-lindsay** [comment]
My apologies, I feel like it downloaded the updated binary and put it back in AppData. Working with IT to exempt it from group policies, will report back.

**Comment by JanDeDobbeleer** [comment]
@kdethlefs yes, this could imply execution is blocked. I have never been able to reproduce this so definitely curious what the root cause is.

**Comment by kdethlefs-lindsay** [comment]
For the sake of complete information and helping you, this is what I did.
I ran `oh-my-posh` on its own and it gave me:
```
ResourceUnavailable: Program 'oh-my-posh.exe' failed to run: An error occurred trying to start process 'C:\Users\kevin.dethlefs\AppData\Local\oh-my-posh\oh-my-posh.exe' with working directory 'C:\Users\kevin.dethlefs'. This program is blocked by group policy. For more information, contact your system administrator.At line:1 char:1
+ oh-my-posh
+ ~~~~~~~~~~.
```
Referring directly to the "This program is blocked by group policy". It's not uncommon for corporate networks to block this due to the fact that malicious software will often run from AppData (Roaming/Local). I'm a little annoyed the installer didn't respect the location WinGet installed it at, which would have avoided this. The application is in my path at `C:\winget\bin`. Moving the file manually did not seem to help. I remember reading something about the exe being a wrap around?

IT said they exempted it, but my group policy updates fail (for those that don't know, if IT updates, you can force group policy updates with `gpupdate /force`) I'm still working with IT, but I imagine it's not high on their priority. I'll report back when I resolve the access restrictions that you can't do anything about.

**Comment by JanDeDobbeleer** [comment]
@kdethlefs the installer has no relationship with where winget is installed.

**Comment by kdethlefs-lindsay** [comment]
So trying to understand the process, winget downloads installer, installer runs and defaults to %LOCALAPPDATA%? Boo. Considering how it's made to be cross compatible across package managers and OS's, I get why.

**Comment by JanDeDobbeleer** [comment]
@kdethlefs what do you mean with "Boo"? The installer has nothing to do with winget, winget provides a CLI platform to install a plethora of tools, abstracting away the underlying installation method for the end user.

The oh-my-posh [installer](https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/packages/inno) is tailor made for Windows and uses sane defaults for the platform. Disagreeing with that is fine, in that case you can always download and install the binary from the releases section here.

**Comment by kdethlefs-lindsay** [comment]
Small inconvenience with the installer putting it in AppData without an override or considering the location winget downloaded it. It's sane defaults, yes. I'm not given the chance to override them, using winget or anything. 

Not sure why I didn't think about the binary manually and placing it where I need it... In doing so, I had some cleanup to do. I'm having a hard time with finding where the command keeps referring to the local app data directory rather than the single command I have downloaded. I don't see POSH_PATH in my environment variables. Not being too familiar with powershell (haven't had much of a reason to script it), not sure where it pulls $env:POSH_PATH from. I'll have to fix it later. I don't think this is a problem with the app though, so you can close this ticket if you like.
