### ISSUE TITLE
 Not able to change theme to a different one 

### ISSUE THREAD

**Issue by little-medjed** [JanDeDobbeleer/oh-my-posh#1968]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi, I'm having the same issue as the guy on issue #1030

The smoothie theme is in my home folder and I use eval "$(oh-my-posh --init --shell bash --config ~/.smoothie.omp.json)" to change to it but the theme don't change when I restart bash.

I'm using bash it too, maybe this is the problem?

It's the last version of oh-my-posh too...

### Theme

jandedobbeleer

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```shell
no response
```

**Comment by JanDeDobbeleer** [comment]
@LoveyApprentice you need to add that line your `.bashrc` file otherwise it's only valid for the current session. Have a look at the [docs](https://ohmyposh.dev/docs/prompt) as the init functionality also changed recently (but that's not related to the issue).

**Comment by little-medjed** [comment]
I have that line in the .bashrc file already.
I tried to remove the bash it and put that line in the backup .bashrc file too, but its not working...

**Comment by JanDeDobbeleer** [comment]
@LoveyApprentice taken from the interwebs:

Read the INVOCATION section from "bash(1)" for full details (that's the man page for bash; use man bash). Your first shell upon logging in is a "login shell", which means that the .bashrc file is not sourced. Your second invocation creates an interactive shell, where .bashrc is sourced.

If you always want the content of your .bashrc file processed, you can add the following lines to your .bash_profile file, creating that file if it does not already exist:

```
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
```

**Comment by little-medjed** [comment]
@JanDeDobbeleer I tried, it does not work ;-;

**Comment by JanDeDobbeleer** [comment]
@LoveyApprentice what happens when you type `exec bash`?

**Comment by little-medjed** [comment]
@JanDeDobbeleer there is no output.

**Comment by JanDeDobbeleer** [comment]
@LoveyApprentice what happens when you add the lines to `.bash_profile` directly?

**Comment by little-medjed** [comment]
I did not work...

But I tried to add the line eval "$(oh-my-posh --init --shell bash --config ~/.smoothie.omp.json)" direct into .bashrc and now the theme just work...
So I guess the problem is solve now.

Sorry about all this.

**Comment by JanDeDobbeleer** [comment]
@LoveyApprentice yes, but it won't work when restarting as it's not persisted. You could also try the `.profile` file. But the fact that doesn't work is related to your machine and not oh-my-posh.

**Comment by little-medjed** [comment]
@JanDeDobbeleer but it is working after I restart my machine...

**Comment by JanDeDobbeleer** [comment]
If it works on restart then everything is fine, right?

**Comment by little-medjed** [comment]
Yes.
