### ISSUE TITLE
Tool tips not rendering in PowerShell

### ISSUE THREAD

**Issue by TylerEich** [JanDeDobbeleer/oh-my-posh#1977]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Tool tips don't render on PowerShell!

My profile looks like this:

```powershell
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
Import-Module oh-my-posh
oh-my-posh prompt init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer-copy.omp.json" | Invoke-Expression
Enable-PoshTooltips
```

![image](https://user-images.githubusercontent.com/3460063/159960505-9ccefe32-4beb-412f-b17a-7e3c5d919f32.png)

### Theme

```json
{
    "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
    "blocks": [],
    "tooltips": [
        {
            "tips": ["time"],
            "type": "time",
            "style": "plain",
            "foreground": "white",
            "properties": {
                "time_format": "15:04:05",
                "template": "{{ .CurrentDate | date .Format }}"
            }
        }
    ],
    "console_title_template": "{{ .Shell }} in {{ .Folder }}",
    "version": 1
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Version: 7.47.0

Segments:

ConsoleTitle(true) -  13 ms - dotnet in src

Run duration: 13.8836ms

Cache path: C:\Users\TEICH\AppData\Local\oh-my-posh

Logs:

2022/03/24 12:08:27 Flags duration: 0s, args:
2022/03/24 12:08:27 Flags duration: 0s, args:
2022/03/24 12:08:27 debug: Getenv

2022/03/24 12:08:27 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/03/24 12:08:27 Root duration: 0s, args:
2022/03/24 12:08:27 Shell duration: 13.2188ms, args:
2022/03/24 12:08:27 ErrorCode duration: 0s, args:
2022/03/24 12:08:27 IsWsl duration: 0s, args:
2022/03/24 12:08:27 debug: Pwd
C:\src
2022/03/24 12:08:27 Pwd duration: 0s, args:
2022/03/24 12:08:27 debug: Home
F:\
2022/03/24 12:08:27 PathSeparator duration: 0s, args:
2022/03/24 12:08:27 PathSeparator duration: 0s, args:
2022/03/24 12:08:27 PathSeparator duration: 0s, args:
2022/03/24 12:08:27 PathSeparator duration: 0s, args:
2022/03/24 12:08:27 PathSeparator duration: 0s, args:
2022/03/24 12:08:27 User duration: 0s, args:
2022/03/24 12:08:27 Host duration: 0s, args:
2022/03/24 12:08:27 GOOS duration: 0s, args:
2022/03/24 12:08:27 TemplateCache duration: 13.3436ms, args:
2022/03/24 12:08:27 debug: Getenv
C:\Users\TEICH\AppData\Local
2022/03/24 12:08:27 Getenv duration: 0s, args: LOCALAPPDATA
2022/03/24 12:08:27 CachePath duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@TylerEich let me check as I just now was working on it and it worked on my end (as we had a bug).

**Comment by JanDeDobbeleer** [comment]
@TylerEich everything works on my end, also with your config. 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/2492783/159988655-9089e74e-4700-4396-b6ec-eacb1483ad0c.png">

A couple of questions. What version of PowerShell are you using? We use PSReadLine to handle this, we've seen this behaviour before but never for the time segment tbh (unless it fails to display time). Can you try to see if that one has an update (also prerelease). If that doesn't work, try the following simple tooltip that "should" work.

```json
{
  "tips": ["hello"],
  "type": "text",
  "style": "plain",
  "foreground": "white",
  "properties": {
    "template": "hello"
  }
}
```

**Comment by TylerEich** [comment]
@JanDeDobbeleer Thanks for investigating. Here's what I've got for you:

![image](https://user-images.githubusercontent.com/3460063/159991673-1c3339d3-272a-4c56-a5c8-72ac5d5e8004.png)

**Comment by TylerEich** [comment]
I just upgraded to PowerShell 7.2.2 and I have the same behavior

**Comment by JanDeDobbeleer** [comment]
@TylerEich did you update PSReadLine too?

**Comment by TylerEich** [comment]
I updated my PSReadLine like so (from cmd) ` C:\Users\TEICH\.dotnet\tools\pwsh.exe -noprofile -command "Install-Module PSReadLine -Force -SkipPublisherCheck -AllowPrerelease"`

Same behavior after restarting Windows Terminal.

For what it's worth, the cursor does "jump" when I hit the spacebar after typing `hello`, which doesn't happen when `Enable-PoshTooltips` is not there

**Comment by JanDeDobbeleer** [comment]
@TylerEich which terminal are you using?

**Comment by TylerEich** [comment]
@JanDeDobbeleer I'm using Windows Terminal with the shell PowerShell 7.2.2

**Comment by JanDeDobbeleer** [comment]
@TylerEich with that config set, what happens when you enter the following command:

```bash
oh-my-posh print tooltip --command hello
```

<img width="772" alt="image" src="https://user-images.githubusercontent.com/2492783/160713869-fc0a0795-bf59-4a87-afcc-777c1c9e8c32.png">

**Comment by TylerEich** [comment]
@JanDeDobbeleer 
![image](https://user-images.githubusercontent.com/3460063/160720699-22c3c255-b75e-4d49-b4c1-a8ba2b7e5bfb.png)

**Comment by JanDeDobbeleer** [comment]
@TylerEich silly question, is your `white` maybe black? Because I can see a line break that appears empty.

**Comment by TylerEich** [comment]
@JanDeDobbeleer Heh, not a silly question, but I don't think that's the issue. I updated my config to be this 
![image](https://user-images.githubusercontent.com/3460063/160835355-f009af79-a7c1-42c9-ac21-41f6cd8ac0da.png)

And when I run the command I see this
![image](https://user-images.githubusercontent.com/3460063/160835422-efd70c9e-8139-4517-9b88-3c9f3264583e.png)

Thanks for sticking with me figuring this one out! Easily my favorite shell customizer ever :heart:

**Comment by TylerEich** [comment]
I don't know what exactly fixed this, but the issue is resolved in the latest release.
