### ISSUE TITLE
`oh-my-posh.exe help get` Shows `cache-path` As Valid Argument

### ISSUE THREAD

**Issue by mattcargile** [JanDeDobbeleer/oh-my-posh#1986]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Below command shows `Error: invalid argument "cache-path" for "oh-my-posh get"`

```powershell
oh-my-posh.exe get cache-path
````

Help shows:

<pre>
Usage:
  oh-my-posh get [shell|<b>cache-path</b>|millies] [flags]
</pre>

Should the below line be modified?

https://github.com/JanDeDobbeleer/oh-my-posh/blob/96df24789d72955e36b40d87c98cdb080ccc14e0/src/cli/get.go#L17

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@mattcargile yes, that word need to be removed as it's replaced by `oh-my-posh cache path`.
