### ISSUE TITLE
Prefix `$global` `ERRORCODE` And `EXECUTIONTIME` In `omp.ps1` 

### ISSUE THREAD

**Issue by mattcargile** [JanDeDobbeleer/oh-my-posh#1987]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would it be reasonable to add a `OMP` prefix/postfix to these variables just in case a user happens to use one of these variables in a local session? They are a little general in name. Otherwise, the user's variable is overwritten.

Maybe the `$global` modifier can be removed?

#### Example
![image](https://user-images.githubusercontent.com/74641867/160258335-64ea58b9-c2a1-41b0-9790-46a445341e99.png)

#### Code 
https://github.com/JanDeDobbeleer/oh-my-posh/blob/112043f8050e1a900f73158515a89e455141912d/src/shell/scripts/omp.ps1#L75
https://github.com/JanDeDobbeleer/oh-my-posh/blob/112043f8050e1a900f73158515a89e455141912d/src/shell/scripts/omp.ps1#L97

**Comment by JanDeDobbeleer** [comment]
@mattcargile prefix would be best in that case.
