### ISSUE TITLE
Your patreon profile doesn't seem to let me support you...!

### ISSUE THREAD

**Issue by fsackur** [JanDeDobbeleer/oh-my-posh#199]
### Description

- I click on your Patreon link, https://www.patreon.com/jandedobbeleer
- It redirects to https://www.patreon.com/jandedobbeleer/creators and I have no option to send you cashmoney

If there is a cost implication that makes it ineffective to support you on Patreon, perhaps remove that link and I will sign up with one of your other platforms.

**Comment by JanDeDobbeleer** [comment]
Thank you so much for letting me know! I updated the links to the ones that actually work ;-)
