### ISSUE TITLE
Start-Utf8Process doesn't seem to be in a global scope

### ISSUE THREAD

**Issue by antonklimov** [JanDeDobbeleer/oh-my-posh#2006]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

on 7.55.0 it fails to find Start-Utf8Process function

### Theme

any

### What OS are you seeing the problem on?

Windows

### Log output

```shell
Theme: agnoster


Action to take for this exception:
The term 'Start-Utf8Process' is not recognized as a name of a cmdlet, function, script file, or executable
program.
```

**Comment by JanDeDobbeleer** [comment]
@antonklimov what's your environment as I did test this and that wasn't an issue on my machines. Are you using the module?

**Comment by antonklimov** [comment]
Yes, in my profile I have:

    Import-Module oh-my-posh -MinimumVersion "6.0"
    Set-PoshPrompt -Theme mytheme
    
Also when just extracting Start-Utf8Process and adding it as a global function, everything works

**Comment by JanDeDobbeleer** [comment]
@antonklimov should be live!

**Comment by antonklimov** [comment]
Thanks!
