### ISSUE TITLE
Powerlevel10k Classic renders gaps between blocks in PowerShell

### ISSUE THREAD

**Issue by SirJson** [JanDeDobbeleer/oh-my-posh#201]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

This behavior does not happen with every font, only on startup and only with the Powerlevel10k classic theme. I've made a screenshot of this issue. The problematic font is Hasklug NF.

![grafik](https://user-images.githubusercontent.com/1042414/100552287-7f703a80-3286-11eb-917b-aa80e09665db.png)

The weird part is, it seems to be inconsistently broken, just two hours before I've seen gaps in basically every block. Pressing enter resolves the issue or executing the `clear` command.

I've had a look at the theme file and the code but couldn't see anything obvious. The source seems to be the `postfix` space char used in the theme. Removing that property or replacing it with for example a 'x' fills the gab.  

After some debugging I've found that when the `postfix` spaces are replaced with \u2588 (the Unicode char for "Full Block") the issue is fixed. I tried to use the Unicode char for space to see if that solves the issue but it didn't make any difference. I will submit a PR with the fixed theme, as far as I can tell it doesn't break anything but I could be wrong.

### Environment

- Oh my Posh version: 3.46.1
- Theme: powerlevel10k_classic
- Operating System: Windows 10 Version 20H2
- Shell: PowerShell 7.1.0
- Terminal: Windows Terminal 1.4.3243.0 Preview

### Steps to Reproduce

1. Add `Set-PoshPrompt -Theme powerlevel10k_classic` in your `Microsoft.PowerShell_profile.ps1` file.
2. Open the Windows Terminal settings and set  `Hasklug NF` as default Font (I've used size 12 but other size values did the same)
3. Modify the PowerShell command line to not print the logo `"commandline": "pwsh.exe -nol"`

**Expected behavior:** That the first line of my shell prompt is rendered correctly without gaps between segments

**Actual behavior:** The first line will get rendered with gaps in between segments, sometimes everywhere, sometimes just on the right side.

**Comment by SirJson** [comment]
It looks like the bug is still around in the latest version:

![grafik](https://user-images.githubusercontent.com/1042414/101982865-28e80080-3c77-11eb-9b90-c613db6c534b.png)

The thing is what you suggested in that PR I fully agree with, this was obviously better than my solution. Though assuming you implemented that why is the config in my PR still fixing it even if it's ugly and more like a hack and the newest version is still showing that behavior? 

That brings me back to the part that I just briefly mentioned in my PR, I think the source isn't really what char is used but the color system somehow hence I had to slightly modify the colors to make it 100% work in my PR. I just don't have any explanation as to why this is happening only that colors seems to influence it.

**Comment by JanDeDobbeleer** [comment]
@SirJson I didn't see this anymore since I implemented the fix. That said, a theme can have spaces at which time this becomes an issue again. To be fully clear, this bug does not originate from oh-my-posh, it's either the terminal or Powershell doing this, we can only try to work around it.

**Comment by SirJson** [comment]
True I also ~think~ thought Powershell is the real problem here, but try to talk to Microsoft about such an "issue". 

Now that I think about it a bit more I thought okay what if I launch the same PowerShell with the same parameter but don't use the Windows Terminal but whatever is used usually for cmd.exe.

![grafik](https://user-images.githubusercontent.com/1042414/101983359-ec1e0880-3c7a-11eb-87c3-623944fa3046.png)

... which brings me back to Microsoft and bugs. The Windows Terminal Team seems to be a bit stubborn with even more serious issues. So, a workaround if someone can come up with it sounds the most realistic... I wonder if one can create a similar prompt in Starship and if so, will I see the same problem? If not, why. I think I have to check that out.

**Comment by JanDeDobbeleer** [comment]
I think I can fix the theme though. It still includes an actual space.

**Comment by JanDeDobbeleer** [comment]
@SirJson this is confirmed as an issue in Windows Terminal and font icons spacing. It's on their backlog.
