### ISSUE TITLE
final_space doesn`t work after upgrade to v7.55.1

### ISSUE THREAD

**Issue by ali50m** [JanDeDobbeleer/oh-my-posh#2010]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

### Theme

  "final_space": true,

### Log output

```shell
na
```

**Comment by JanDeDobbeleer** [comment]
@ali50m can you try again in 7.55.1? I can't reproduce this myself.

![image](https://user-images.githubusercontent.com/2492783/160980523-21d612cc-d1a9-4bbb-a31d-f5d8ce12a3a4.png)

<img width="732" alt="image" src="https://user-images.githubusercontent.com/2492783/160980655-3e984c24-bcb0-4784-9763-5891fdbff944.png">
