### ISSUE TITLE
Add support for other project files

### ISSUE THREAD

**Issue by hadrizi** [JanDeDobbeleer/oh-my-posh#2014]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be nice if [`Project` segment](https://ohmyposh.dev/docs/project) supported other project files(like `pyproject.toml` or `Cargo.toml`)

**Comment by JanDeDobbeleer** [comment]
@hadrizi can you give some example files, because yes, that's the intention.
