### ISSUE TITLE
Diamond rendering with different color

### ISSUE THREAD

**Issue by germancardenasm** [JanDeDobbeleer/oh-my-posh#2017]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi:
In PowerShell in my vscode the Diamonds are rendering in a different color.  I have tried using different themes but when diamonds are used it is rendering in different styles

Expected: 
![image](https://user-images.githubusercontent.com/35246482/161166028-07feb91c-59f5-466e-87f3-498c8a56ba53.png)

Actual result:
![image](https://user-images.githubusercontent.com/35246482/161166049-8e5c28fc-1bdd-4203-873f-a9de81274ed1.png)

Expected: 
![image](https://user-images.githubusercontent.com/35246482/161166268-c06acfe3-a65d-4b0e-8162-706f7918184a.png)

Actual result:
![image](https://user-images.githubusercontent.com/35246482/161166304-4a0cd2fc-6d61-4e20-9901-eead86631c23.png)

### Theme

```
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "#18354c",
          "foreground": "#ffc107",
          "leading_diamond": "\ue0b6",
          "properties": {
            "style": "folder"
          },
          "style": "diamond",
          "template": " \ue5ff {{ .Path }} ",
          "trailing_diamond": "\ue0b0",
          "type": "path"
        },
        {
          "background": "#18354c",
          "foreground": "#ffc107",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_stash_count": true,
            "fetch_upstream_icon": true,
            "fetch_status": true
          },
          "style": "powerline",
          "template": " {{ .HEAD }} {{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} ",
          "type": "git"
        },
        {
          "background": "#ffc107",
          "foreground": "#18354c",
          "powerline_symbol": "\ue0b0",
          "style": "powerline",
          "template": " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} ",
          "type": "python"
        },
        {
          "background": "#ffc107",
          "foreground": "#18354c",
          "powerline_symbol": "\ue0b0",
          "style": "powerline",
          "template": " \uf0e7 ",
          "type": "root"
        }
      ],
      "type": "prompt"
    }
  ],
  "final_space": true,
  "version": 2
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
Does not give any results
```

**Comment by JanDeDobbeleer** [comment]
@germancardenasm I noticed this too yesterday, BUT other terminals display things correctly so it's a bug on the vscode terminal. Can you create an issue there?

**Comment by JanDeDobbeleer** [comment]
@germancardenasm see this [issue](https://github.com/microsoft/vscode/issues/146406). This is the fix:

```json
"terminal.integrated.minimumContrastRatio": 1
```

**Comment by germancardenasm** [comment]
Hey, @JanDeDobbeleer, thank you very much; I appreciated that you spent the time digging into this.

**Comment by Mellbourn** [comment]
I have this issue, but in "reverse": The prompt looks great in the VSCode integrated terminal, but in the Windows Terminal, the diamonds are the wrong hue.

Is there a workaround for Windows Terminal too?

**Comment by Mellbourn** [comment]
To answer my own question: 
The corresponding setting in Windows Terminal is 
`Automatically adjust lightness of indistinguishable text` under `Appearance`
setting this to `Only for colors in the color scheme` or `Never` fixed my issue.

The underlying setting in `settings.json` for Windows Terminal is
````json
 "adjustIndistinguishableColors": "indexed",
````
or
````json
 "adjustIndistinguishableColors": "never",
````
