### ISSUE TITLE
7.55 messes prompt refresh in PowerShell

### ISSUE THREAD

**Issue by Ergamon** [JanDeDobbeleer/oh-my-posh#2020]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Since Version 7.55 the redrawing of some special characters does not work anymore. They are replaced by Questionmarks.

I am using Windows 10 with PowerShell 7.2.2 and PSReadLine 2.2.2.

I am using a custom Key Handler to navigate one directory up:
```
Set-PSReadLineKeyHandler -Key "Ctrl+Pageup" -Description "Move to parent directory" -ScriptBlock {
  param($Key, $Arg)

  $Location = Get-Location
  $Directory = Get-Item $Location
  $Parent = $Directory.Parent

  if (-not $Parent) {
    return
  }

  Set-Location $Parent

  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}
```

The problematic line is the InvokePrompt call.

Up until 7.54 this worked without any problems. Since 7.55 these questionsmarks happen. 

Of course Murphy was hitting hard on me. I had to set up a new machine this week and it took a while to install a necessary stuff. So I thought I must have forgotten something, cause on my old machine everything works and on the new one the output gets messed up. Took me a while to figure out that the difference was 7.54 on the old machine and 7.57 on the new one ;)

As the changelog of 7.55 shows some changes in the UTF8 output, there must probably lie the source of the problem

### Theme

It happens with basically every theme. To reproduce just use Agnoster e.g.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
? user@computer ? D:\ ?
```

**Comment by JanDeDobbeleer** [comment]
@Ergamon that's an issue with PSReadLine and UTF8. You need to wrap that line [like we do](https://github.com/JanDeDobbeleer/oh-my-posh/blob/b61ec064ddb35ae37dea3be78cf0eb578ecee8a2/src/shell/scripts/omp.ps1#L196), store the current encoding, set to UTF8, run the command and restore.

```
$previousOutputEncoding = [Console]::OutputEncoding
[Console]::OutputEncoding = [Text.Encoding]::UTF8
try {
  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
} finally {
    [Console]::OutputEncoding = $previousOutputEncoding
}
```

**Comment by Ergamon** [comment]
Ok, your fix works, Now I remember we had already a discussion about this topic in the past, but as you fixed it, I seem to have forgotten about it.

Seems your fix had some side effects or why did you remove it in 7.55?

As I have a lot of areas where I fall back on the InvokePrompt method, I will add a helper function Invoke-Prompt to my profile. Perhaps an idea ot add it to the PowerShell Module?

Thanks for your help and great module

**Comment by JanDeDobbeleer** [comment]
@Ergamon the issue up until now was that we forced the entire shell to UTF8 which breaks other tools. The changed 7.55 only change the output for oh-my-posh.
