### ISSUE TITLE
Spotify segment not working

### ISSUE THREAD

**Issue by pietro-swe** [JanDeDobbeleer/oh-my-posh#2031]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm trying to make Spotify segment to work. But nothing happens! It seems to load well, but a matching Window Title is not found.
Spotify version: Spotify for Windows 1.1.81.604.gccacfc8c (Installed from Web, not Store (already tried with the Store version))

I made two scripts to get all process windows titles. One using C# and the other using Powershell itself.
These are the string I got from the logs:
C# version (Id, Name and MainWindowTitle, respectively):
`| Process Spotify | ID: 14620 | Window Title: Demon Hunter - Collapsing (feat. Björn "Speed" Strid)`

Powershell version (Id, Name and MainWindowTitle, respectively):
`14620 Spotify Demon Hunter - Collapsing (feat. Björn "Speed" Strid)`

### Theme

[My custom theme URL](https://gist.github.com/marechal-dev/bf1a48b180a6c4eeffe9696c3532c81f)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```shell
oh-my-posh debug log:

Segments:
spotify(false) -  57 ms -

Logs:
2022/04/04 14:56:12 error: QueryWindowTitles
no matching window title found
2022/04/04 14:56:12 WindowTitle duration: 30.0003ms, args: ^(Spotify.*)|(.*\s-\s.*)$
2022/04/04 14:56:12 error: QueryWindowTitles
no matching window title found
2022/04/04 14:56:12 WindowTitle duration: 27.9637ms, args: ^(Spotify.*)
2022/04/04 14:56:12 debug: Pwd
```

**Comment by JanDeDobbeleer** [comment]
@marechal-dev the regex matches, so the title isn't the issue here. I have no idea what just yet.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/2492783/161606494-b44fea8f-da6e-4db1-bf2b-679cfe5f1d41.png">

**Comment by pietro-swe** [comment]
@JanDeDobbeleer
No worries, I'm gonna mess with the configs more to try to figure out what is happening. Thanks for all the support, your job is amazing! If I find something, I will post it here in the future.

**Comment by JanDeDobbeleer** [comment]
@marechal-dev I made sure the logs can now also indicate the actual error, so if you would update and try again, maybe we can get a bit closer to the actual issue.

**Comment by INblau-LucaGerhardt** [comment]
@JanDeDobbeleer For me the spotify segment is working. But when Spotify is not running, I get following error output (on Windows, WSL is working fine):

```
oh-my-posh fatal error rendering spotify segment:runtime error: invalid memory address or nil pointer dereference

goroutine 11 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/debug/stack.go:24 +0x65
oh-my-posh/engine.(*Segment).renderText.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:326 +0x58
panic({0x12f0b20, 0x1da5900})
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:838 +0x207
oh-my-posh/environment.queryWindowTitles({0x13906ab, 0xb}, {0x139bcec, 0x19})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/windows_win32.go:113 +0xf6
oh-my-posh/environment.(*ShellEnvironment).QueryWindowTitles(0xc000280150, {0x13906ab, 0xb}, {0x139bcec, 0x19})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/windows.go:75 +0x118
oh-my-posh/segments.(*Spotify).Enabled(0xc00040c3c0)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/spotify_windows.go:12 +0x49
oh-my-posh/engine.(*Segment).renderText(0xc0002ae780, {0x14c01d0?, 0xc000280150?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:335 +0xa2
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x65
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:86 +0x98
```

**Comment by pietro-swe** [comment]
I got the same problem @JanDeDobbeleer 
My Spotify is up and playing a music

Logs:
```
oh-my-posh fatal error rendering spotify segment:runtime error: invalid memory address or nil pointer dereference

goroutine 23 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/debug/stack.go:24 +0x65
oh-my-posh/engine.(*Segment).renderText.func1()
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:326 +0x58
panic({0x12e0b20, 0x1d95900})
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/panic.go:838 +0x207
oh-my-posh/environment.queryWindowTitles({0x13806ab, 0xb}, {0x138bcec, 0x19})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/windows_win32.go:113 +0xf6
oh-my-posh/environment.(*ShellEnvironment).QueryWindowTitles(0xc000222070, {0x13806ab, 0xb}, {0x138bcec, 0x19})
        /home/runner/work/oh-my-posh/oh-my-posh/src/environment/windows.go:75 +0x118
oh-my-posh/segments.(*Spotify).Enabled(0xc000306480)
        /home/runner/work/oh-my-posh/oh-my-posh/src/segments/spotify_windows.go:12 +0x49
oh-my-posh/engine.(*Segment).renderText(0xc0000de640, {0x14b01d0?, 0xc000222070?})
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/segment.go:335 +0xa2
oh-my-posh/engine.(*Block).renderSegmentsText.func1(0x0?)
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:88 +0x65
created by oh-my-posh/engine.(*Block).renderSegmentsText
        /home/runner/work/oh-my-posh/oh-my-posh/src/engine/block.go:86 +0x98
```

Terminal:
![Terminal Error](https://user-images.githubusercontent.com/47929247/161741578-9e26ae40-d319-4add-8608-67ee8ced1a1a.png)

**Comment by JanDeDobbeleer** [comment]
@marechal-dev @INblau-LucaGerhardt fix incoming

**Comment by pietro-swe** [comment]
Oof
```
2022/04/05 08:35:03 error: QueryWindowTitles
no matching window title found

2022/04/05 08:35:03 WindowTitle duration: 20.3787ms, args: ^(Spotify.*)|(.*\s-\s.*)$
2022/04/05 08:35:03 error: QueryWindowTitles
no matching window title found

2022/04/05 08:35:03 WindowTitle duration: 22.2828ms, args: ^(Spotify.*)
2022/04/05 08:35:03 debug: Pwd
```

**Comment by JanDeDobbeleer** [comment]
Yup, there's no error message. Grasping for straws here as this is deep into the win32 API. @marechal-dev OK if I provide a custom build so we can see a crazy amount of logging? Wouldn't want that for everyone :-)

**Comment by pietro-swe** [comment]
@JanDeDobbeleer sure! Let's go!

**Comment by JanDeDobbeleer** [comment]
[oh-my-posh.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/8419206/oh-my-posh.zip)

@marechal-dev this one will log everything it does

**Comment by pietro-swe** [comment]
@JanDeDobbeleer 
I've wrote the output to a log file, here is the [link to Pastebin](https://pastebin.com/62yUKAKm)

At the very beginning of the log it's possible to see that it found something:
```
2022/04/05 14:56:40 debug: queryWindowTitles
spotify.exe
```
The subsequent calls didn't found anything

**Comment by JanDeDobbeleer** [comment]
@marechal-dev it can't get any of the window titles which is strange.

```
unable to get window process pid: A operação foi concluída com êxito.
```

What happens when you run the terminal as admin?

**Comment by pietro-swe** [comment]
> @marechal-dev it can't get any of the window titles which is strange.
> 
> ```
> unable to get window process pid: A operação foi concluída com êxito.
> ```
> 
> What happens when you run the terminal as admin?

@JanDeDobbeleer I'm always running it as Admin
Btw, "A operação foi concluída com êxito" means "The operation was successfully completed"

**Comment by JanDeDobbeleer** [comment]
@marechal-dev my man. That's the issue. That error is localized 😂

**Comment by JanDeDobbeleer** [comment]
[oh-my-posh.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/8420813/oh-my-posh.zip)

Try this one. I'm ignoring the error altogether. [This](https://github.com/JanDeDobbeleer/oh-my-posh/blob/46992bc7e0559076ffe8f5274e14945dc8cbc66e/src/environment/windows_win32.go#L62) is what we do, and that's not what your OS is reporting due to localization.

**Comment by pietro-swe** [comment]
@JanDeDobbeleer 
Now the debug properly shows the Spotify segment template with a Playing Status (at least it looks like this): 
![Segments Debug](https://user-images.githubusercontent.com/47929247/161823286-10bf5fd6-fbe1-4656-b768-c8aa4f4baa99.png)

[Logs here](https://pastebin.com/AAeSmDwn)

**Comment by JanDeDobbeleer** [comment]
@marechal-dev that's a template issue it seems. Can you try the sample I provided in the comment to your config?

**Comment by pietro-swe** [comment]
@JanDeDobbeleer 
OH YEAH BABY
![YES BABY](https://user-images.githubusercontent.com/47929247/161824431-27b47341-ad7b-4e5d-9d2d-95076d102ad3.png)
![THAT'S WHAT WE'VE WAITING FOR](https://user-images.githubusercontent.com/47929247/161824519-c0f88de6-3992-4e75-acb6-e3859af6914e.png)
