### ISSUE TITLE
jandedobbeleer theme color correction

### ISSUE THREAD

**Issue by DaBasile** [JanDeDobbeleer/oh-my-posh#204]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide

- [x] I looked for duplicate issues before submitting this one

### Description

At line 86 on jandedobbeleer theme default foreground is "#ffffff", I suggest to change it on a dark one cause on background "ffff66" is not visible.

### Environment

- Oh my Posh version: 3.46.1
- Theme: jandedobbeleer 
- Operating System: Windows 10
- Shell: all
- Terminal: Windows Terminal Preview

### Steps to Reproduce

What it looks like
![image](https://user-images.githubusercontent.com/11245411/100641824-4a242500-3338-11eb-884f-4025b34a7ea2.png)

What should looks like
![image](https://user-images.githubusercontent.com/11245411/100641996-7d66b400-3338-11eb-9765-c5e93d74da90.png)

**Comment by JanDeDobbeleer** [comment]
Yup. That's actually a change I've been meaning to do for some time 😅. Can you make a small PR, or shall I fix it?
