### ISSUE TITLE
Exit code segment doesn't work on nushell 0.60

### ISSUE THREAD

**Issue by unional** [JanDeDobbeleer/oh-my-posh#2064]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Exit code segment doesn't work on nushell 0.60.

It was working fine in 0.44

![image](https://user-images.githubusercontent.com/3254987/162591340-6c9b7010-0b10-40b4-b5bb-dba4377fb7e2.png)

I notice that nushell 0.60 saves the exit code in `LAST_EXIT_CODE` (https://github.com/nushell/nushell/issues/3185):

```sh
│ 19 │ LAST_EXIT_CODE                │ int           │                                                                          1 │ 1   
```

Probably the `.Code` needs to map to that value in nushell 0.60

### Theme

```js
{
  "background": "#20ac4f",
  "background_templates": [
    "{{ if gt .Code 0 }}#af1237{{ end }}"
  ],
  "foreground": "#ffffff",
  "properties": {
    "always_enabled": true
  },
  "style": "diamond",
  "template": " \uE23A ",
  "trailing_diamond": "\ue0b0",
  "type": "exit"
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
oh-my-posh debug
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...
```
```

**Comment by JanDeDobbeleer** [comment]
@unional I don't think this ever worked as the error code is added with the `--error` parameter. Changing the way oh-my-posh is invoked will immediately resolve that:

```
let-env PROMPT_COMMAND = { oh-my-posh print primary --error $env.LAST_EXIT_CODE }
let-env PROMPT_COMMAND_RIGHT = { oh-my-posh print right }
```

I have zero experience with nu shell myself and only looked this up real quick. Hope the syntax is correct.

**Comment by unional** [comment]
Thanks for the quick response. Your suggestion works.
I recall it was working, but I could be wrong. 🌷 

Thanks!

**Comment by unional** [comment]
Update doc in #2065
