### ISSUE TITLE
Only Shows When I type oh-my-posh

### ISSUE THREAD

**Issue by DWhirlpool** [JanDeDobbeleer/oh-my-posh#2072]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm Not Sure What Happened But It Is Always Like This
<img width="494" alt="image" src="https://user-images.githubusercontent.com/95860724/162678484-2b66a69b-ddbe-486e-93d8-a371ac137faf.png">

### Theme

default

### What OS are you seeing the problem on?

Windows

### Log output

```Shell
 ludan@TABLET-SUNE7MVB  ~  WindowsTerminal  no config  
```

**Comment by JanDeDobbeleer** [comment]
@DWhirlpool you need to follow the [guide](https://ohmyposh.dev/docs/prompt) to setup your prompt.
