### ISSUE TITLE
feat(git): show status when the .git folder is moved.

### ISSUE THREAD

**Issue by LeonS13** [JanDeDobbeleer/oh-my-posh#2074]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When you have a valid repository that was created with: git init --separate-git-dir /path/to/repo.git Oh My Posh does not show any status. The repo works fine and can be checked with git-status without any problems. Also GUI tools like Sourcetree have no trouble with a moved  git directory. I think Oh My Posh only tries to find a folder .git and when it does not find it then it asumes the folder is not a repository. It should also look for a file called .git and check if there is a line in the file containing the new location of the git directory. Linux and windows examples below.  
gitdir: /path/to/repo.git
gitdir: C:\path\to\repo.git

### Theme

Default theme.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
No logging available, Oh MY Posh just does not recognize a folder with a moved .git folder.
```

**Comment by JanDeDobbeleer** [comment]
@LeonS13 correct, that use-case was unknown to me. Will address when I'm back from holidays.

**Comment by lnu** [comment]
@LeonS13 Can you confirm it works on your side with the latest version?

**Comment by LeonS13** [comment]
Can confirm it works with the latest version, thanks for the insane fast response.

Met vriendelijke groeten / Meilleures salutations / Best regards
Leon Straathof
Infrastructure Architect
