### ISSUE TITLE
Set-PoshPrompt could pass color codes

### ISSUE THREAD

**Issue by FLeven** [JanDeDobbeleer/oh-my-posh#2079]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

As most themes only use one font color and maybe a green/red/battery loading color, it would be nice to set those colors by Set-PoshPrompt. We would gain an easy and very quick way to tune the colors of our prompt, without having to edit the theme templates. In the long run, it could also shrink the available theme count a little.

**Comment by JanDeDobbeleer** [comment]
@FLeven that's not going to be possible as Set-PoshPrompt is a deprecated cmdlet and a PowerShell module only functionality. So, very limited in use case.

**Comment by FLeven** [comment]
How could I set, the a default font color etc. for all segments in a theme, to save me from setting it for each segment ?
Ok, I missed that Set-PoshPrompt is deprecated, what would be the alternative to Set-PoshPrompt ?

**Comment by JanDeDobbeleer** [comment]
@FLeven very good question! You can use [palette](https://ohmyposh.dev/docs/config-colors#palette) for that! The [default theme](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/default.omp.json) highlights a use case.

**Comment by FLeven** [comment]
Ok, I looked at the default theme, but I missed that, because I expected the defaults to be set, at the beginning of the default theme and I was obviously to lazy to scroll to the end of the file.

To refine my request after the things I learned:
I would like to pass a color value (palette value) on init / --config to change a color(s) in a theme

**Comment by JanDeDobbeleer** [comment]
@FLeven I gave this some thought and decided not to do this. There's no real advantage over editing a config, not from a user or code pov. The current capabilities make this easy to set up, tweak, copy, and adding this would mean the same in terms of time spent/code written.
