### ISSUE TITLE
Doc bug: how to abuse environment variables?

### ISSUE THREAD

**Issue by craigb** [JanDeDobbeleer/oh-my-posh#2082]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I want to know how to abuse my environment variables to speed up arbitrary commands in my prompt, please :)

![image](https://user-images.githubusercontent.com/59184/163055618-da918e14-71c1-44e9-b521-bc7b3ed27cfa.png)

**Comment by JanDeDobbeleer** [comment]
@craigb you can use [.Env.VARNAME](https://ohmyposh.dev/docs/config-templates#global-properties) in any template. Depending on the shell you can populate these before the prompt is rendered.

**Comment by mattcargile** [comment]
Assuming you are using `pwsh` or `powershell`. Check [this](https://ohmyposh.dev/docs/text) page and look for the note about "overriding" the `Set-PoshContext` function. This is an empty function you can latch onto and set environment variables. It even runs after the execution time and error code information so you can grab those variables to do things with.

**Comment by craigb** [comment]
Thank you both so much! This was perfect info. Now I can add Swatch Internet Time to my prompt like it's the late '90's again 👍🏻
