### ISSUE TITLE
Segment to display insert/normal mode for VIM editing mode

### ISSUE THREAD

**Issue by AniAggarwal** [JanDeDobbeleer/oh-my-posh#2088]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I use VIM-like keybinds in terminal, set via my `.inputrc`:
```
# Use Vim keybinds instead of default Emacs
set editing-mode vi
# Show current mode at the beginning of the prompt
set show-mode-in-prompt on
set vi-ins-mode-string "+ "
set vi-cmd-mode-string ": "
```

So that I can see which mode I am in, a `+` or a `:` is displayed at the beginning of my prompt and looks like below:
![Screenshot from 2022-04-14 10-25-04](https://user-images.githubusercontent.com/52252926/163441535-854f1348-0f9e-437a-a582-23082e0c5a01.png)
![Screenshot from 2022-04-14 10-25-53](https://user-images.githubusercontent.com/52252926/163441654-ae8e2a9b-4808-4154-b973-bf7dee24d865.png)

I would love it if there was a way to integrate that into oh-my-posh.

**Comment by JanDeDobbeleer** [comment]
@AniAggarwal I had a look at this and it's not possible to get that value so oh-my-posh can use it. What you could do is change the implementation to use a [cursor style](https://wiki.archlinux.org/title/readline#Different_cursor_shapes_for_each_mode), that will indicate the current mode by displaying a different cursor:

```
set vi-ins-mode-string \1\e[6 q\2
set vi-cmd-mode-string \1\e[2 q\2

# optionally:
# switch to block cursor before executing a command
set keymap vi-insert
RETURN: "\e\n"
```

**Comment by AniAggarwal** [comment]
This worked, thanks!
I use kitty so I need to figure out how to make it work with that now, but it works on Gnome terminal.
Thanks for the pointer.
