### ISSUE TITLE
Themes not working in Windows Terminal 

### ISSUE THREAD

**Issue by Praful** [JanDeDobbeleer/oh-my-posh#2091]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have created a theme on my desktop and have OMS working. I just set up OMS on my laptop and the prompt is not being changed at all. Nothing happens. The command in my PowerShell profile is:

```
oh-my-posh` --init --shell pwsh --config C:\data\powershell\pk-posh-theme.omp.json | Invoke-Expression
```

### Theme

I'm using my own theme but I've tried using the standard themes, eg `jandedobbeleer.omp.json`, but it makes no difference.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
PS>oh-my-posh debug

Version: 7.62.1

Segments:

ConsoleTitle(false)  -   1 ms -
root(false)          -   0 ms -
path(true)           -   1 ms -  C:\data\downloads\themes
git(false)           -  23 ms -
executiontime(false) -   0 ms -
exit(false)          -   0 ms -
text(true)           -   1 ms - ❯

Run duration: 27.4165ms

Cache path: C:\Users\praful\AppData\Local\oh-my-posh

Logs:

2022/04/15 00:07:10 Flags duration: 0s, args:
2022/04/15 00:07:10 Flags duration: 0s, args:
2022/04/15 00:07:10 debug: Getenv

2022/04/15 00:07:10 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/04/15 00:07:10 Root duration: 0s, args:
2022/04/15 00:07:10 Shell duration: 0s, args:
2022/04/15 00:07:10 ErrorCode duration: 0s, args:
2022/04/15 00:07:10 IsWsl duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 debug: User
praful
2022/04/15 00:07:10 User duration: 0s, args:
2022/04/15 00:07:10 debug: Host
PORTEGEZ30
2022/04/15 00:07:10 Host duration: 511.2µs, args:
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 TemplateCache duration: 511.2µs, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 Root duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 Flags duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 PathSeparator duration: 0s, args:
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 IsWsl duration: 0s, args:
2022/04/15 00:07:10 StackCount duration: 0s, args:
2022/04/15 00:07:10 TemplateCache duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 HasCommand duration: 23.0356ms, args: git.exe
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/04/15 00:07:10 HasParentFilePath duration: 0s, args: .git
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 ExecutionTime duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 ErrorCode duration: 0s, args:
2022/04/15 00:07:10 ErrorCode duration: 0s, args:
2022/04/15 00:07:10 debug: Pwd
C:\data\downloads\themes
2022/04/15 00:07:10 Pwd duration: 0s, args:
2022/04/15 00:07:10 debug: Home
c:\data\LinuxHome
2022/04/15 00:07:10 GOOS duration: 0s, args:
2022/04/15 00:07:10 TemplateCache duration: 0s, args:
2022/04/15 00:07:10 debug: Getenv
C:\Users\praful\AppData\Local
2022/04/15 00:07:10 Getenv duration: 0s, args: LOCALAPPDATA
2022/04/15 00:07:10 CachePath duration: 0s, args:
PS>
```

**Comment by Praful** [comment]
I have investigated further, installing from the binaries from the releases here. 

Y= release works, N = release does **not** work:

```
7.44.1 Y
7.51.0 Y
7.54.0 Y
7.55.0 Y
7.56.1 N
7.57.0 N
7.58.1 N
7.59.4 N
7.62.1 N
```

It appears the issue happened between 7.55.0 and 7.56.1.

This is the debug log from the working 7.55.0 (the theme is slightly different from the one used when I logged the issue because I overwrote the previous them; however, I've used this theme for testing all the above versions):

EDIT: I've regenerated the debug for a working and broken version and put them in files so you can compare like-with-like. When I diffed them, I couldn't see anything significant. Hopefully you can :-)

[output-broken.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8492935/output-broken.txt)
[output-working.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8492936/output-working.txt)

**Comment by slamflipstrom** [comment]
I am experiencing a similar issue. When I try to set the theme at startup using the `init --config ...` command, it says that no themes can be found. The directory doesn't exist. I'm on the 7.62.1 release.

**Comment by JanDeDobbeleer** [comment]
@Praful what happens when you use:

```
oh-my-posh init pwsh --config C:\data\powershell\pk-posh-theme.omp.json | Invoke-Expression
```

**Comment by Praful** [comment]
> @Praful what happens when you use:
> 
> ```
> oh-my-posh init pwsh --config C:\data\powershell\pk-posh-theme.omp.json | Invoke-Expression
> ```

@JanDeDobbeleer when I use the above command in v7.62.1, nothing happens. The command prompt remains `PS>`.

**Comment by JanDeDobbeleer** [comment]
That's not possible. Sure you're running that version? What does `$error` say?

**Comment by JanDeDobbeleer** [comment]
@Praful @slamflipstrom what I need to understand the issue is the output of:

-  `oh-my-posh init pwsh --config C:\data\powershell\pk-posh-theme.omp.json --print`
- `Write-Host $Error` after initialisation 

BTW you're certain you edited the correct `$PROFILE`, right? `Get-Content $PROFILE` displays your edit?

**Comment by GrinGrin** [comment]
I all, same issue here

Since latest update to 7.62.2 no more prompt, my custom theme file has been updated but the prompt remain to `PS>`

Tried both commands and attached the result below. Seems that there is a missing Get-GitStatus function in my case.

[init-print.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8498326/init-print.txt)
[init-invoke-expression.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8498327/init-invoke-expression.txt)

**Comment by JanDeDobbeleer** [comment]
@GrinGrin confirmed that when posh-git is not installed, it fails to render the prompt. Will push a fix now. Thx for the logs, that makes this really easy to fix.

**Comment by JanDeDobbeleer** [comment]
@GrinGrin 7.62.3 is out with the fix. Thanks again for the logs!

**Comment by GrinGrin** [comment]
@JanDeDobbeleer ,

I just updated to 7.62.3 and I can confirm that it solved the issue !!

Thanks !

**Comment by JanDeDobbeleer** [comment]
@slamflipstrom @Praful looking at the commits in between, it seems [this](https://github.com/JanDeDobbeleer/oh-my-posh/commit/749eb6cf263fd960644b9d099d973c7c94af4958) is the culprit. The fix mentioned above resolves that.

**Comment by Praful** [comment]
I've just tried the latest version, 7.63.0, and can confirm my prompt has been restored! Thank you @JanDeDobbeleer for fixing this so quickly :-)

**Comment by Padreco-lbr** [comment]
I am having the same problem with version 8.31.0 (I am running on Windows 11)

If I run 'oh-my-posh init pwsh | Invoke-Expression', the prompt is just 'PS>', but after hitting enter, it shows a stylized prompt:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/23504838/185021208-8790a07a-7956-4421-9e2a-2e63d7e3fc40.png">

**Comment by JanDeDobbeleer** [comment]
@Padreco-lbr you can find out why by looking at the `$error` variable. What you're seeing is the transient prompt. But for some reason the default prompt fails to load (on the PowerShell end).

**Comment by Padreco-lbr** [comment]
Thanks, @JanDeDobbeleer!
After looking to the $error variable, I found out the problem was a GIT_POSH_ENABLED env variable set as true, which led to an error by calling Get-GitStatus. ([Reference here](https://bytemeta.vip/repo/JanDeDobbeleer/oh-my-posh/issues/2113))
After disabling GIT_POSH_ENABLED, the prompt appeared as expected.
