### ISSUE TITLE
Detect NuGet package title and version

### ISSUE THREAD

**Issue by FLeven** [JanDeDobbeleer/oh-my-posh#2098]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would it be possible to detect the version and title associated with current Nuget / Chocolatey project ?

Every NuGet Package will require a .nuspec file to be present, containing all the information about the package.
This would be nice to display, as the version info is not part of the foldernames and the title might be different from
the foldername.

**Example:**
`C:\ProgramData\chocolatey\lib\discord\discord.nuspec`

```
...
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
 <metadata>
 <id>discord</id>
 <version>1.0.9004</version>
 <title>Discord</title>
...
```

**Comment by JanDeDobbeleer** [comment]
@FLeven for sure. Perfect match for the [project](https://ohmyposh.dev/docs/project) segment. I'll see what I can do.
