### ISSUE TITLE
Support for CMD

### ISSUE THREAD

**Issue by rashil2000** [JanDeDobbeleer/oh-my-posh#21]
Since this is a (almost) platform-agnostic shell themer, is there a way to support Command Prompt in Windows? 

For inspiration, you can check out how Cmder does it. 
For the most part, it just requires changing the `prompt` environment variable. Like this, for example: 
```
SETX /M PROMPT "$E[1;32;40m→ $E[1;36;40m$p$E[1;35;40m› $E[1;37;40m" 
```

**Comment by JanDeDobbeleer** [comment]
In theory you should be able to call the executable just like you would on Powershell. Let me check and add that info to the README

**Comment by JanDeDobbeleer** [comment]
Never mind the previous activity, that was me fighting the Github Android app 😅

**Comment by rashil2000** [comment]
> In theory you should be able to call the executable just like you would on Powershell. 

That'd be really slick!

**Comment by JanDeDobbeleer** [comment]
You'd think this should be possible, right? Well, turns out my friend `CMD` only works with strings... I'm looking for a way to bypass that, it can print the prompt though :-)

**Comment by rashil2000** [comment]
Yes I tried fighting with it too. Calling the `.exe` momentarily printed the prompt, but the PROMPT variable takes only strings and some escape characters, because specifying the path of `go-my-posh` in PROMPT just printed out the path :)

**Comment by JanDeDobbeleer** [comment]
It's more limited to my friend `CMD` than anything else, but maybe there's an out-of-the-box solution nobody's thinking off.

**Comment by JanDeDobbeleer** [comment]
Doesn't seem to be possible yet with everything I've tried, I'll keep this open in case I (or someone else) has a brilliant idea that might work.

**Comment by rashil2000** [comment]
Sure!
Thanks for your effort!

**Comment by JanDeDobbeleer** [comment]
Had a look once again and it's just not possible as far as I can tell.

**Comment by rashil2000** [comment]
@JanDeDobbeleer Yes, it seemed really difficult. 

Any idea how Cmder achieved a custom prompt though? Was it terminal-specific?

**Comment by JanDeDobbeleer** [comment]
You can change it once, but not change it on the fly and as elaborate as oh-my-posh does.

I will have a look though. If what conemu does works on every prompt invocation, it might work.

**Comment by JanDeDobbeleer** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/2492783/96491048-fa831180-1241-11eb-86b9-021f6cc126d3.png">
I reached this point but as I feared, you can't update the path and other information once you set the string meaning you would need to return the standard variables CMD understands for them to be dynamic. Conemu can do a bit more magic as they own the shell, meaning they have some magic variables they can inject at runtime, but that's not something I can offer. Therefore we can't support CMD 😢

**Comment by rashil2000** [comment]
I understand. 

Thank you for your efforts though! OMP3 looks really in all other shells btw!

**Comment by rashil2000** [comment]
Hey @JanDeDobbeleer, sorry for bumping this old thread again, but I think I finally figured it out! 

It might be out of scope of this project, but Conemu actually uses Clink under the hood, which offers it the ability to have a custom prompt with the help of Lua scripting - [Customizing the Prompt](https://chrisant996.github.io/clink/clink.html#customisingtheprompt) - as mentioned here. With a simple function like this: 

```lua
local custom_prompt = clink.promptfilter(50)
function custom_prompt:filter(prompt)
    return io.popen("oh-my-posh --config C:\\Users\\RashilGandhi\\.oh-my-posh\\honukai.omp.json"):read("*a")
end
```

I was able to have a dynamic and fully working prompt

![image](https://user-images.githubusercontent.com/46838874/103166536-f3cbd880-4848-11eb-801e-35e7a8534019.png)

I say this is out of scope because, well anyone looking for using OMP with CMD will have to install Clink then. 

Anyways, just wanted to share!

**Comment by AbdelrahmanHafez** [comment]
Thanks @rashil2000 

I'd like to extend your answer a little bit more, in case anyone comes across this issue who is also using ConEmu, most of the tutorials out there only specify how it would work for PowerShell, and I am not a fan. I prefer Cmder.

In order to get oh-my-posh working:
1- Locate cmder installation folder.
2- Create a new file `vendor\clink-completions\custom.lua`
Paste the following as the content:
```lua
local custom_prompt = clink.promptfilter(50)
function custom_prompt:filter(prompt)
    return io.popen("oh-my-posh"):read("*a")
end
```

@JanDeDobbeleer
Thank you for the great work, would consider repoening this since Cmder is quite popular on the Windows scene?

**Comment by JanDeDobbeleer** [comment]
@AbdelrahmanHafez it's documentation so I don't mind having this info in the docs tbh.

**Comment by rashil2000** [comment]
Clink's (the extension framework that Cmder uses) own documentation also has a section for oh-my-posh, maybe that can be referred - https://chrisant996.github.io/clink/clink.html#oh-my-posh

**Comment by yaseer-13** [comment]
👍 This command worked for me to make changes in the command prompt!

```shell
load(io.popen('oh-my-posh.exe --config="C:/Users/YourName/AppData/Local/Programs/oh-my-posh/themes/themeName.omp.json" --init --shell cmd'):read("*a"))()
