### ISSUE TITLE
Smoother integration with z.lua

### ISSUE THREAD

**Issue by theperiscope** [JanDeDobbeleer/oh-my-posh#2104]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

## Summary

Oh-my-post default install steps conflict with [z.lua](https://github.com/skywind3000/z.lua) (using clink, cmder on Windows). I believe this is due to a prompt filter priority issue and smother integration would be very useful.

## Details

On Windows, I use [z.lua](https://github.com/skywind3000/z.lua) to navigate quickly folders and clink's flex-prompt but I wanted to switch from flex-prompt to oh-my-posh to take advantage of additional advanced prompt customization. I noticed that when oh-my-posh ran, the z.lua database stopped getting updated -- took some time but I was able to make it work by making z.lua run with higher (lower number) priorty prompt filter.

```batch
setx _ZL_CLINK_PROMPT_PRIORITY 1
```

Because I find both all tools incredibly useful, I thought it may be useful to resolve any conflicts in an upcoming release.

**Comment by JanDeDobbeleer** [comment]
@theperiscope thanks, good to know. I'll do some research and adjust accordingly 👍🏻

**Comment by JanDeDobbeleer** [comment]
@theperiscope I do wonder why they [set it at 99](https://github.com/skywind3000/z.lua/commit/48a77adf3575952b2e951aa820a1ce11ed4ce56b) themselves though. As if they WANT to run last...

**Comment by theperiscope** [comment]
@JanDeDobbeleer I still can't believe you turned it around already into a release and I'm using it. Well done, and thank you!

 I still don't understand quite the root cause for the conflict but I am glad it is working -- z.lua has `prompt_hook` variable which references the `_ZL_NO_PROMPT_COMMAND` environment variable ("_if you're handling PROMPT_COMMAND yourself._") and that may be related. I'll let you know if I find out more useful details.
