### ISSUE TITLE
rbash Support

### ISSUE THREAD

**Issue by ajmeese7** [JanDeDobbeleer/oh-my-posh#2109]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be awesome if `rbash` could be added to the list of supported shells out of the box! I'm allowing users to SSH into a chroot jail on my machine and their default shell is `rbash`, and I would love to use `oh-my-posh` to make it prettier. The shell itself is extremely similar to bash so I doubt many configuration changes would be necessary.

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 seems to be rather straightforward as the only change needed would be to not provide the full path. I'll create a `--strict` flag for this.

**Comment by ajmeese7** [comment]
That would be great, thanks!
