### ISSUE TITLE
Override default file lists for segments

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#2112]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi Jan,

There are many segments that use file lists to determine whether they should be shown, the dotnet segment for example. It would be great if we could override the default file lists with our own. I would like to exclude the *.sln file from the dotnet segment (as there can be other non .NET solutions that use the *.sln file).

This may also be a good opportunity to do the file matching on files only and not directories if possible 😉

**Comment by JanDeDobbeleer** [comment]
@piersmyers this is already exposed (but undocumented) using the `extensions` property (array)

**Comment by piersmyers** [comment]
Ah, perfect, this works wonderfully:

```
{
  "type": "dotnet",
  "style": "plain",
  "template": " {{ if .Unsupported }}{{ else }}<p:white,p:dotnet-purple>.NET</>{{ end }}",
  "properties": {
    "fetch_version": false,
    "extensions": [ "*.cs", "*.csx", "*.vb", "*.csproj", "*.vbproj", "*.fs", "*.fsx", "*.fsproj", "global.json" ]
  }
}
```

Don't keep it hidden please 😁
