### ISSUE TITLE
Can git status display do an equivalent of "git status -uno"?

### ISSUE THREAD

**Issue by tgani** [JanDeDobbeleer/oh-my-posh#2117]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Displaying git status is slow on large repositories. In my case, it takes 1700ms to display the next prompt. Most of the time is from fetching git status, which is slow for large repositories. If OMP does something like the equivalent of "git status -uno", this works far faster at the cost of not showing files not in the repository.

**Comment by JanDeDobbeleer** [comment]
@tgani I suppose you would like to control for which repo's to use this switch, right?

**Comment by tgani** [comment]
> @tgani I suppose you would like to control for which repo's to use this switch, right?

That's a great idea, in fact since fetching full git status might not be too bad on some repos. 

Also, thank you for making a great tool available. It really enhanced my quality of dev life.

**Comment by JanDeDobbeleer** [comment]
@tgani I have an implementation ready, just need to add it to the docs and we're good to go.

**Comment by tgani** [comment]
Super, let me know when and I can give it a try.

**Comment by tgani** [comment]
Unfortunately, specifying "untracked_modes" : { "my-repo-root" : "no" } makes no difference. I tried both forward slashes and (escaped) back-slashes (I'm on Win11).

What I would love is the ability to pass arguments to git status. Here are my times with this command:

git status -> 4.8s
git status -uno -> 0.3s
git status -uno --ignore-submodules -> 0.17s

As you can see there is a 30x difference between the fastest version and the slowest. Being able to specify "-uno --ignore -submodules" in the JSON as an argument to pass git status would be awesome.

**Comment by JanDeDobbeleer** [comment]
@tgani I like that idea, let me see if I can add that somewhere next week. I would also have a look at that repo, it does seem rather huge. But for my reference, can you share the entire git part in your config?
