### ISSUE TITLE
Strict mode doesn't work with rbash

### ISSUE THREAD

**Issue by ajmeese7** [JanDeDobbeleer/oh-my-posh#2118]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I run the new code that supports strict mode with the following: `oh-my-posh init bash --strict --config /jail/home/username/.poshthemes/material.omp.json`

I get the following output printed to my rbash shell: `echo "Unable to find Oh My Posh executable"`

It appears that the new code with strict mode is still not detecting the correct path to the executable, which is located at `/jail/usr/local/bin/oh-my-posh`. The configuration file exists at the specified path and it isn't malformed in any way, it was pulled directly from https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/material.omp.json

I'm not exactly sure what is going wrong, but another possible alternative (you could test it with `rbash` on your machine if you are running Linux) is to add `rbash` as another terminal type and just treat it the same way as you would `bash`. Not 100% confident that this would work, but it might :)

Thanks for your help and your amazing work on this project, I love it!

### Theme

Material

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

other (please specify)

### Log output

```Shell
rbash-5.0$ oh-my-posh debug
Oh My Posh Error:

stat https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v/themes/default.omp.json: no such file or directory
```

I have no idea where the `/v/` is coming from, it isn't present anywhere on the configurations written on my end.
```

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 if I run with `bash --restricted`, it does seem to work on my end.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/2492783/164379776-37ce877d-a76f-4d7a-8031-b25a8bcc4d0d.png">

I did not install rbash separately as this is the same behaviour. This my `.bashrc`:

```bash
eval "$(oh-my-posh prompt init bash --strict)"
```

**Comment by ajmeese7** [comment]
I just tested your code on my main user with `rbash` and it works as expected, I think the issue may be because of the jailed user. The `/jail` root directory is non-standard and the user has very limited permissions, I made sure to `chown` the `oh-my-posh` binary to the user but I'm still getting the error `Unable to find Oh My Posh executable`, and running the debug command still returns `stat https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v/themes/default.omp.json: no such file or directory`.

I ran `strings /jail/usr/local/bin/oh-my-posh | grep theme` in hopes of finding where the mysterious `/v/` was coming from, but no such luck.

Do you have any ideas on how to proceed?

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 OK, so the `/v/` should actually contain the version. As initialising with no config will download the [default theme for that version](https://github.com/JanDeDobbeleer/oh-my-posh/blob/v7.68.0/themes/default.omp.json), it needs to fill it in. But as you build locally, you probably didn't provide that flag to `go build`, which then results in an empty string.

When building locally, try the following command to ensure it has the right value:

```
go build -o /usr/bin/oh-my-posh  -ldflags "-X 'main.Version=7.68.0'"
```

**Comment by ajmeese7** [comment]
@JanDeDobbeleer I'm passing a config file locally, I downloaded the material theme from https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/material.omp.json and my `.bashrc` contains the following:

```bash
eval "$(oh-my-posh prompt init bash --strict --config /home/xterm/.poshthemes/material.omp.json)"
```

The config file exists at that location, but it seems that the config flag isn't being picked up at all. I tried placing the `--strict` after the `--config` but it still gives the same errors described above.

I'm not building locally, I currently don't have `go` on my machine. I ran the following commands to get the executable in my jail:

```bash
sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-arm -O "/jail/usr/local/bin/oh-my-posh"
sudo chmod +x "/jail/usr/local/bin/oh-my-posh"
sudo chown -R xterm "/jail/usr/local/bin/oh-my-posh"
```

Are you suggesting that I install `go` and try building it locally instead?

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 no, it could be that the ARM version somehow doesn't work as expected. I don't have a device I can validate on however. What's the output of `oh-my-posh version`?

**Comment by ajmeese7** [comment]
@JanDeDobbeleer 7.67.0

Edit: Just ran the script again and downloaded 7.69.0, same problem occurs.

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 what happens when you remove the config flag?

**Comment by ajmeese7** [comment]
@JanDeDobbeleer changed it to `eval "$(oh-my-posh prompt init bash --strict)"` and I get the exact same error printed to the screen on `source .bashrc` and with the `oh-my-posh debug` command

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 OMG I'm blind. Remove the print argument. It's `oh-my-posh init bash`

**Comment by ajmeese7** [comment]
@JanDeDobbeleer back to `eval "$(oh-my-posh init bash --strict --config /jail/home/xterm/.poshthemes/material.omp.json)"`, still having the same problem unfortunately. Tried with `eval "$(oh-my-posh init bash --strict)"` as well, no dice.

**Comment by ajmeese7** [comment]
I tried `sudo jk_cp -v -f /jail /usr/local/bin/oh-my-posh` as well, instead of just installing directly to the jailed user, but still no dice. From what I can tell, the `config` flag is just not being read at all [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/8dcd200e3e2715790d369f465639a95e5771bd83/src/environment/shell.go#L228), and then it doesn't find `env.Version` on the next line error, which is where the `debug` command error originates.

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 it seems this happens when the config can't be found (the user can't access it). This functionality was recently adjusted meaning it should now at least behave differently. Can you validate?

**Comment by ajmeese7** [comment]
@JanDeDobbeleer stuff changed! I've got colors now at the top of my debug command:

![debug colors](https://user-images.githubusercontent.com/17814535/168179654-cf4d5200-8d85-4c91-9f7f-f6a5ea6084eb.png)

Below is an attachment of the full logs from `oh-my-posh debug`:

[oh-my-posh-debug.log](https://github.com/JanDeDobbeleer/oh-my-posh/files/8682955/oh-my-posh-debug.log)

Unfortunately I am still getting the error message `Unable to find Oh My Posh executable` when loading into bash/rbash as my jailed user. I made sure to chown the binary and the `.poshthemes` directory recursively to the user and the `users` group just in case there was a hidden permissions error, but the problem persists. The user also has execute capability over the binary and read permissions for the themes directory.

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 according to oh-my-posh, the config path is empty and that's also why you get that prompt:

```
Config path: 
```

This means that whatever config you added, when running oh-my-posh, the executable can't access the config path.

**Comment by ajmeese7** [comment]
@JanDeDobbeleer that's strange! My `.bashrc` for the user has the following lines at the end:

```shell
# Loads the user's 'oh-my-posh' configuration when the shell starts
eval "$(oh-my-posh init bash --strict --config /jail/home/xterm/.poshthemes/material.omp.json)"
```

And the config file's permissions are `-rwxr-xr-x`, so it *should* be able to be read as far as I know. Do you have any suggestions for how to overcome this issue and allow the executable to access the config path?

**Comment by JanDeDobbeleer** [comment]
I'm not the linux expert. The process that's running oh-my-posh doesn't have access to that path.

**Comment by ajmeese7** [comment]
I had a hunch that the problem was the `/jail` portion of the path, since the `.bashrc` is executed in the context of the jailed user so there is no knowledge of a jail directory. Unfortunately changing the path to start with just `/home` had the same issue, so I am back to square one. The error is still `Unable to find Oh My Posh executable`, even though the executable is clearly able to be found since the debug command works just fine.

The config path still appears to be empty for whatever reason, even though I have tried setting the permissions to 777 just for the sake of guaranteeing that the config file is accessible by the executable. The permissions of the executable are also `rwxr-xr-x`, so there is no issue in that file being executed by any user.

Do the logged error messages along the lines of `open /proc/20695/status: no such file or directory` mean anything to you, could it give further insight into where the problem is occurring? From what I can tell the jail doesn't have a `/proc` directory, which is most certainly part of the problem. I am looking into ways to resolve this currently, but if there is an alternative method that can be used that doesn't require the `/proc` directory then that would be most helpful!

**Comment by ajmeese7** [comment]
I GOT IT! I had to run the following commands to set up the jail to support `oh-my-posh`:

```shell
sudo mkdir /jail/proc
sudo mount -t proc /proc /jail/proc/
sudo jk_cp -v -f /jail /usr/bin/tr
```

Now everything appears to be working as expected. Thank you so much for your help in this process! I'm closing this out now, I hope it can be of future use to anyone else who encounters this issue.
