### ISSUE TITLE
OS segment contains tag characters

### ISSUE THREAD

**Issue by cdhunt** [JanDeDobbeleer/oh-my-posh#212]
### Description

`Plain` style OS segment displays extra unwanted characters.

### Environment

- Oh my Posh version: 3.47.3
- Theme: Custom
- Operating System: Ubuntu
- Shell: Pwsh
- Terminal: Windows Terminal

### Steps to Reproduce

```json
                {
                    "type": "os",
                    "style": "plain",
                    "foreground": "#26C6DA",
                    "properties": {
                        "postfix": " \uE0B1",
                        "macos": "\uF179",
                        "windows": "\uE70F"
                    }
                },
```

With this segment config ([doc example](https://ohmyposh.dev/docs/os#sample-configuration)) I now get extra characters in the latest release. I was previously using a version that doesn't have the `-version` flag so I'm not sure what I was on.

**Expected behavior:** [What you expected to happen]

OS icon + foreground colored chevron.

![image](https://user-images.githubusercontent.com/114173/100879381-5d8ad980-3479-11eb-88e6-e3665a3f9c8f.png)

**Actual behavior:** [What actually happened]

![image](https://user-images.githubusercontent.com/114173/100878879-bf970f00-3478-11eb-85ed-702d91b7f248.png)

**Comment by MJECloud** [comment]
I also got the characters displayed.
The  `>>>`  are also `plain` style
![image](https://user-images.githubusercontent.com/22131101/100885099-8e3b3500-34b2-11eb-9dd0-7ea84e462219.png)

**Comment by JanDeDobbeleer** [comment]
Yes, you need to add the `"background":  "transparent"` property to each segment without that property as of the last version. I had to try a fix for spacing issues on Powershell startup.

**Comment by JanDeDobbeleer** [comment]
Scrap that, I'm reverting the change to be smarter. Won't take long.
