### ISSUE TITLE
Terminal embedded in vscode does not display correct color after 3.47.3

### ISSUE THREAD

**Issue by Vixb1122** [JanDeDobbeleer/oh-my-posh#213]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Terminal embedded in vscode does not display correct color after 3.47.3.

### Environment

- Oh my Posh version: 3.47.3
- Theme: material
- Operating System: Windows 10
- Shell: Powershell
- Terminal: vscode

### Steps to Reproduce

1. Reinstall 3.47.3 and config it
2. open terminal in vscode
3. change theme to material
4. toggle terminal panel size

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/17810492/100890488-4688cd80-34f3-11eb-8caa-eebc44abf882.png)

**Actual behavior:** [What actually happened]
1. before toggle panel size
![image](https://user-images.githubusercontent.com/17810492/100890905-b303cc80-34f3-11eb-83d2-dff88d79499b.png)
2. after toggle panel size
![image](https://user-images.githubusercontent.com/17810492/100890961-beef8e80-34f3-11eb-9a9b-4730391f8f26.png)

**Comment by JanDeDobbeleer** [comment]
2 issues: vscode can't handle inverted ANSI (that's a bug on their end, see #182). And the toggle size is something I have no idea where it comes from but it also ANSI related (#211).

**Comment by JanDeDobbeleer** [comment]
@Vixb1122 the inverted ANSI will be gone so that should bring most things back to normal (#214). I'm closing this as a duplicate.
