### ISSUE TITLE
Shell .Version template error in powershell5 and WSL

### ISSUE THREAD

**Issue by FLeven** [JanDeDobbeleer/oh-my-posh#2133]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I started to add the new **.Version** to my theme and it worked as expected in **pwsh** 7.2.2. for example.

On **PowerShell 5** or **WSL** I get a template error. I also tried to get around this error by trying to display the .Version on **pwsh** only and the .Name only on all other shells, but it did not work either.

.Version seems not to be empty, 

### Theme

lambdageneration

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
unable to create text based on template
```

**Comment by JanDeDobbeleer** [comment]
@FLeven did you update/are you using the latest version of oh-my-posh everywhere?

**Comment by FLeven** [comment]
Ok, PowerShell 5 was not up to date and is working now. 

WSL (and **PWSH** in it) ist still showing "**unable to create text based on template**"

**Comment by JanDeDobbeleer** [comment]
@FLeven as this functionality is not in any way influenced by the shell it runs in, please validate the version in WSL as it can't possibly be the right version (that's technically not possible).

**Comment by FLeven** [comment]
you are right, WSL seems to be a little buggy sometimes.

I had to import the module twice and then it finaly worked;
`PS /root> import-Module oh-my-posh`
`PS /root> oh-my-posh init pwsh --config ./.poshthemes/lambdageneration.omp.json | Invoke-Expression`
