### ISSUE TITLE
Error: unknown command "pwsh" for "oh-my-posh"

### ISSUE THREAD

**Issue by dannyluck** [JanDeDobbeleer/oh-my-posh#2138]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hello, at the beginning i just want to say that i am ultra stupid and doing these things first time. So there is a huge chance that i've did something wrong when i was installing it. But everytime i run terminal, it just says:

Error: unknown command "pwsh" for "oh-my-posh"
Run 'oh-my-posh --help' for usage.
unknown command "pwsh" for "oh-my-posh"

I know that it is ultra easy to fix it but im just too dumb to do it. Sorry :(

### Theme

atomic.omp (trying to)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...
```

**Comment by JanDeDobbeleer** [comment]
@437kasugano supposing you're installing for PowerShell, can I get your installation method and `$PROFILE`?

**Comment by dannyluck** [comment]
As i said im really stupid, so u mean that ive installed it for scoop or other methods? If yes then scoop

$PROFILE

oh-my-posh -shell pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\atomic.omp | Invoke-Expression
Set-Alias neofetch winfetch
Remove-Item Alias:curl
clear

**Comment by JanDeDobbeleer** [comment]
@437kasugano what happens when you replace the oh-my-posh line with:

```
oh-my-posh init pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\atomic.omp | Invoke-Expression
```

**Comment by dannyluck** [comment]
it works... thanks, and sorry for being dumb. Age issue

**Comment by dannyluck** [comment]
But, should it look like this? It feels weird, i installed Hack NF font 
![image](https://user-images.githubusercontent.com/67912255/164944787-e76d7fb1-79bb-4900-92bd-b9c4b0bdc84c.png)

**Comment by JanDeDobbeleer** [comment]
That's not atomic. Hmm. I'll need to really validate that config flag it seems. Will check tomorrow.

**Comment by dannyluck** [comment]
I'll check if other themes are working for me

**Comment by dannyluck** [comment]
Even changing theme is difficult....... Should i do something else than just changing it in $profile? After changing the theme in profile it still displays glitched atomic

**Comment by JanDeDobbeleer** [comment]
@437kasugano yes, reload PowerShell.

**Comment by dannyluck** [comment]
Yes, im reloading terminal/powershell but it doesn't change. I mean the theme

**Comment by JanDeDobbeleer** [comment]
@437kasugano can you give me the output of `echo $env:POSH_THEME`?

**Comment by dannyluck** [comment]
Nothing happens 
![image](https://user-images.githubusercontent.com/67912255/164991724-a6167fc2-e1df-4dbf-9c01-4f0a583a7236.png)

**Comment by JanDeDobbeleer** [comment]
@437kasugano that's not really possible and explains a few things (or makes the mystery even harder). 

What's the output of:

```
oh-my-posh init pwsh --config ~\AppData\Local\Programs\oh-my-posh\themes\atomic.omp.json --print
```

**Comment by JanDeDobbeleer** [comment]
@437kasugano BTW, are you certain the path is correct? I would expect it needs to be:

```
oh-my-posh init pwsh --config ~\AppData\Local\oh-my-posh\themes\atomic.omp.json | Invoke-Expression
```

-> without `Programs` (at least on my laptop it is).

**Comment by dannyluck** [comment]
Ill check both things tommorow after school. Thanks for responding.

**Comment by JanDeDobbeleer** [comment]
@437kasugano have a wonderful day!

**Comment by dannyluck** [comment]
Thanks!

**Comment by JanDeDobbeleer** [comment]
@437kasugano I double checked, when installing via Winget, it installs on that location so that's OK. I also noticed that when the theme path can't be resolved, we fallback to the default. That's what you see. Referencing the themes (when installed with winget or the PowerShell module) can be done as such:

```
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\atomic.omp.json" | Invoke-Expression
```

**Comment by dannyluck** [comment]
> @437kasugano I double checked, when installing via Winget, it installs on that location so that's OK. I also noticed that when the theme path can't be resolved, we fallback to the default. That's what you see. Referencing the themes (when installed with winget or the PowerShell module) can be done as such:
> 
> ```
> oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\atomic.omp.json" | Invoke-Expression
> ```

This one works perfectly. I can change to every theme i want. Thanks!
