### ISSUE TITLE
Battery segment showing wrong percentange on MacOS

### ISSUE THREAD

**Issue by hferreira23** [JanDeDobbeleer/oh-my-posh#2139]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm using the oh-my-posh on macOS Big Sur (Intel CPU) and the battery segment is reporting the wrong percentage.

```pmset -g batt``` reports 96% and the segment reports 91%

### Theme

Modified Bubblesline

### What OS are you seeing the problem on?

macOS

### Log output

```Shell
The only relevant log I see using debug is this:

/04/24 00:53:12 BatteryInfo duration: 24.318434ms, args:
```

**Comment by hferreira23** [comment]
Wow, that was quick! The percentage issue is now fixed.

One small thing I found (I don't if its a bug or intended behavior), when the macOS holds the laptop charging at X% (and doesn't charge to 100% to save up battery cycles) the discharge icon and background color show up even though the laptop is not discharging the battery.

```pmset -g batt``` reports:

```
Now drawing from 'AC Power'
 -InternalBattery-0 (id=xxxxxxxx)	80%; AC attached; not charging present: true
```

**Comment by JanDeDobbeleer** [comment]
@hferreira23 I treat that as discharging, but we can easily map that to something else as maybe not charging?

**Comment by hferreira23** [comment]
@JanDeDobbeleer in this specific case the battery is neither charging or discharging so a separate state would be nice.

**Comment by JanDeDobbeleer** [comment]
@hferreira23 the `AC attached` state maps to `NotCharging` so you only need to adjust the logic in the config.
