### ISSUE TITLE
7.70  7.70.1 During the execution process, it is blocked by anti-virus software. Is there a Trojan horse?

### ISSUE THREAD

**Issue by Archer456** [JanDeDobbeleer/oh-my-posh#2142]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

7.70 During the execution process, it is blocked by anti-virus software. Is there a Trojan horse?

![image](https://user-images.githubusercontent.com/18392901/164966260-c3d5f08e-76dd-4f68-b045-fc088a7223ae.png)
![image](https://user-images.githubusercontent.com/18392901/164966408-5f48ede5-e6f7-4f93-b523-f679c77807ec.png)

### Theme

powerlevel10k_rainbow.omp.json |

### Log output

```Shell
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
Downloading https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v7.70.1/install-amd64.exe
  ██████████████████████████████  6.19 MB / 6.19 MB
已成功验证安装程序哈希
正在启动程序包安装...
执行此命令时发生意外错误：
0x800704c7 : �����ѱ��û�ȡ����
```

**Comment by JanDeDobbeleer** [comment]
False positive. See #767
