### ISSUE TITLE
Startup Problem "Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch."

### ISSUE THREAD

**Issue by danielwagn3r** [JanDeDobbeleer/oh-my-posh#2147]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After upgrading to v7.71.0 the follwing error is raised when starting a new powershell prompt:
```
Oh My Posh Error:

open https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v7.71.0/themes/default.omp.json: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
```

the PowerShell profile command for oh-my-posh looks as follows: `oh-my-posh init pwsh | Invoke-Expression`

### Theme

default

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
oh-my-posh debug
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...
Oh My Posh Error:

open https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v7.71.0/themes/default.omp.json: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
```

**Comment by danielwagn3r** [comment]
I could reproduce this issue on two workstations, one with Windows 10 1809 LTCS and one with recent Windows 11. Problem exists when using Windows Terminal or starting PowerShell prompt directly.

**Comment by neksword** [comment]
I face the same issue

**Comment by JanDeDobbeleer** [comment]
On it

**Comment by JanDeDobbeleer** [comment]
Found the issue, the downside of coding at night and making really, really stupid mistakes.

**Comment by danielwagn3r** [comment]
Wow, that was fast as lightning

**Comment by danielwagn3r** [comment]
> Found the issue, the downside of coding at night and making really, really stupid mistakes.

Can confirm this solves the issue for me. Thanks
