### ISSUE TITLE
Changing prompt fails on macOS

### ISSUE THREAD

**Issue by mthmulders** [JanDeDobbeleer/oh-my-posh#2150]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have installed oh-my-posh with `brew install jandedobbeleer/oh-my-posh/oh-my-posh`.
Because `oh-my-posh get shell` reports that I'm using `zsh`, I decided to configure the prompt with `eval "$(oh-my-posh init zsh)"`.

The response is rather disappointing:

```
(eval):1: command not found: Oh
stat: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/v7.71.0/themes/default.omp.json:: stat: No such file or directory
stat: no: stat: No such file or directory
stat: such: stat: No such file or directory
stat: file: stat: No such file or directory
stat: or: stat: No such file or directory
stat: directory: stat: No such file or directory
```

### Theme

I haven't selected a theme yet, I guess it's the default one?

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
oh-my-posh debug
Oh My Posh Error:

ReadMapCB: expect { or n, but found 4, error found in #1 byte of ...|404: Not Fo|..., bigger context ...|404: Not Found|...
```

**Comment by JanDeDobbeleer** [comment]
@mthmulders please update, I just pushed a fix for this. You need 7.71.2.

**Comment by mthmulders** [comment]
Wow, that was quick! Thanks, now the installation works and I can actually start exploring oh-my-posh :-)
