### ISSUE TITLE
!!text property not defined!

### ISSUE THREAD

**Issue by mewisme** [JanDeDobbeleer/oh-my-posh#2153]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I got the message **`!!text property not defined!!`**
When I adding a segments type text and it's taken from the example at [https://ohmyposh.dev/docs/segments/text](https://ohmyposh.dev/docs/segments/text)
I also see it in other themes with newline attribute.
How can I fix it?
Thanks.
![image](https://user-images.githubusercontent.com/63306485/165208440-98bd6a9f-aa2a-42a9-ad21-c3b687b2cc5f.png)
![image](https://user-images.githubusercontent.com/63306485/165208467-e4da8282-381e-439d-a245-bb1321bd14e5.png)

### Theme

my theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
!!text property not defined!!
```

**Comment by JanDeDobbeleer** [comment]
@MeewMeew do you have the latest version of oh-my-posh?

**Comment by JanDeDobbeleer** [comment]
@MeewMeew I can confirm this is caused by an out of date version of oh-my-posh.
