### ISSUE TITLE
docs: Change or remove the Defender exclusion in the Windows setup instructions

### ISSUE THREAD

**Issue by kapsiR** [JanDeDobbeleer/oh-my-posh#2158]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

## Description
Due to the fact that some users have [reported issues with anti virus software](https://github.com/JanDeDobbeleer/oh-my-posh/issues/767) the following Microsoft Defender specifics has been added: https://github.com/JanDeDobbeleer/oh-my-posh/commit/89ab82fde06d4400b23054a6f5ecfc6314f2df48

This should be changed.

## Details
Affected files: `docs/docs/installation/windows.mdx`

There are multiple issues with the exclusion that has been added to the installation documention:
1. Using just the file name in the exclusion list is a [common mistake](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus?view=o365-worldwide#using-just-the-file-name-in-the-exclusion-list)
2. [The cmdlet exclude files that have been opened by the process](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-process-opened-file-exclusions-microsoft-defender-antivirus#use-powershell-cmdlets-to-exclude-files-that-have-been-opened-by-specified-processes-from-scans)  

    From the [Add-MpPreference docs](https://docs.microsoft.com/en-us/powershell/module/defender/add-mppreference):  
    > Specifies an array of processes, as paths to process images. This cmdlet excludes any files opened by the processes that you specify from scheduled and real-time scanning. **Specifying this parameter excludes files opened by executable programs only. The cmdlet does not exclude the processes themselves.** To exclude a process, specify it by using the ExclusionPath parameter.

## Requested change
I think we should change this to a much more general sentence regarding exclusions, if necessary. (or remove it entirely)

**Comment by JanDeDobbeleer** [comment]
@kapsiR I'm open to suggestions. Any proposals?

**Comment by kapsiR** [comment]
> @kapsiR I'm open to suggestions. Any proposals?

I'll think about it and then create a PR? This is not only related to Defender, isn't it?

Something like: "Sometimes antivirus software recognize ... this is most likely a false positive ... you can add report it to the av vendor or add an exclusion  ... "

**Comment by JanDeDobbeleer** [comment]
@kapsiR true, this isn't only related to Defender. Feel free to create that PR, we can even extend the defender info to also include the full path using `Get-Command oh-my-posh` for example. Don't forget we're dealing with a wide range of individuals.

**Comment by kapsiR** [comment]
@JanDeDobbeleer Perfect, thanks. May you assign me here that I don't miss it 😅
