### ISSUE TITLE
Theme directory is overwritten on update

### ISSUE THREAD

**Issue by erikread** [JanDeDobbeleer/oh-my-posh#2159]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When updating Oh-My-Posh using brew update any existing custom themes in the themes directory are deleted. 
What I expected was that my custom theme, custom-theme.omp.json, would not be deleted. Any other built-in themes would be updated.
Putting the theme in Documents and adjusting .zshrc accordingly is my workaraound

### Theme

Custom theme based on clean-detailed

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
n/a
```

**Comment by JanDeDobbeleer** [comment]
@erikread that's by design. The install locations aren't meant to be used.
