### ISSUE TITLE
Feature Request: Do not display battery icon when plugged in

### ISSUE THREAD

**Issue by meakbiyik** [JanDeDobbeleer/oh-my-posh#216]
A small request regarding battery icon: I do not need to see the battery segment when my computer is plugged in, which is nearly all the time. Can you add a flag to disable it in this case?

Also maybe show it when it is plugged in and charging (but do not show it when fully charged)? Though, then a variable limit also has to be set, considering my maximum battery is 98%.

**Comment by JanDeDobbeleer** [comment]
I'd opt for the ability to hide when charging, which means plugged in. I actually like that.

**Comment by lnu** [comment]
@JanDeDobbeleer  I'd rather like to hide it when the battery status if Full. If my latpop is almost empty and I plug it, I'd like to know it's charging until it's Full, then hide it.

**Comment by meakbiyik** [comment]
Everything looks neat, but it does not work for me :( My battery stops charging after 98%, so I imagine it does not return battery.Full == true, but it is not charging either although it is plugged in. I imagine the check should not be with the flag battery.Full, but it should be with (pluggedIn && !battery.Charging)
