### ISSUE TITLE
Windows Security blocks/quarantined posh-windows-amd64.exe 

### ISSUE THREAD

**Issue by audunn** [JanDeDobbeleer/oh-my-posh#218]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]
Windows Security block v3.48.0, I can see it in the protection history flagged as threat blocked or quarantined. 

From the protection history:
Threat detected: Behavior:Win32/DefenseEvasion.UM!ml
Alert Level: Severe
Category: Suspicious Behavior
Details: This program is dangerous and executes commands from an attacker.
Affected item: posh-windows-amd64.exe

### Environment

- Oh my Posh version: v3.48.0
- Theme: Agnoster
- Operating System: Windows 10 1909
- Shell: powershell
- Terminal: Windows Terminal

### Steps to Reproduce

1. [First Step] 
Update to latest `Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser`
2. [Second Step] 
Launch new window

3. After uninstallation and retry install 
```
Package 'oh-my-posh' failed to be installed because: Operation did not complete successfully because the file contains a virus or potentially
      | unwanted software. : 'C:\Users\***\AppData\Local\Temp\ycx0wff3\bin\posh-windows-amd64.exe'
```

**Expected behavior:** [What you expected to happen]  
prompt runs without issue

**Actual behavior:** [What actually happened]
 prompt not running, posh-windows-amd64.exe  is removed from directory

**Comment by JanDeDobbeleer** [comment]
We've seen this before but there's nothing I can do to mitigate that as far as I'm aware. Maybe there's a way to sign this and become accepted but on my own machine for example that doesn't happen.

**Comment by audunn** [comment]
BTW reverted to 3.46.1 it is working fine

**Comment by JanDeDobbeleer** [comment]
Let me do a diff and have a look what might trigger this.

**Comment by JanDeDobbeleer** [comment]
@audunn can you check if 3.47.0 works? That's the only one which does something "new" as in execute http requests, which might be the cause.

**Comment by audunn** [comment]
Hi, I tried that and my very unscientific testing revealed nothing. In fact so much nothing that I am now completely unable to reproduce this on any version and tried several.  Currently on latest 3.49 and working fine. 
Don't know what to tell you to be honest.  But that is where we are at.

**Comment by JanDeDobbeleer** [comment]
I'll close this then until it pops up again.

**Comment by painfulcranium** [comment]
I am actually seeing this now with Norton 360 Data Protector. Every time I go into a git repo, I get the following:

![image](https://user-images.githubusercontent.com/5238279/108781466-e7f24f00-7537-11eb-843d-30decb97e6ee.png)

I am assuming it is a false positive, and can easily add an exclusion, but wanted to raise awareness :)

BTW... killer improvement for Powershell...I come from a Linux background using oh-my-zsh and this is very slick on Windows!

**Comment by JanDeDobbeleer** [comment]
I already submitted the binary for review (at MS) to get an exclusion. It is a false positive, could be due to calling the win32 API. The entire source and pipeline is here on Github so you should be able to assess the validity of that report by auditing here.
