### ISSUE TITLE
does not work on windows accounts other than the account which installed omp via winget

### ISSUE THREAD

**Issue by plastikfan** [JanDeDobbeleer/oh-my-posh#2184]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've just upgraded to using the binary version of omp from the now retired PowerShell module. I have multiple accounts on my machine. The installation process as described at [windows](https://ohmyposh.dev/docs/installation/windows), worked a charm. I setup my custom theme via the powershell profile as instructed. This all works fine with my admin account which I used to install omp.

However, when I attempt to use omp on my other account, omp is not found. Just to confirm, I installed omp with the following command:

> winget install oh-my-posh --scope machine

which results in the installation at `C:\Program Files (x86)\oh-my-posh`

Under my admin account, if I open up the Environment Variables dialog from System Properties I can see that the __POSH_THEMES_PATH__ has been set to `C:\Program Files (x86)\oh-my-posh\themes`

Also, the _USER_ __PATH__ variable has been updated to include `C:\Program Files (x86)\oh-my-posh\bin`

Now this is ok for the admin account, but it does not work for other users on the same machine as their respective _PATH_ variable has not been updated to include the omp path. I tried to re-install in my alternative account, but that failed with another error (I forget what it was, but I'll return after re-attemtping the install and update this with the exact error).

I tried to update the _PATH_ under my non admin account, but modifying environments variables for System and User requires admin authentication which still results in any changes you make being made for the admin account not the currently logged in non-admin account, so this appraoch doesnt work (but this is clearly a windows issue.)

Since I installed omp via winget using the --scope machine, I would have expected that environment variables should have been set as _SYSTEM_ variables not _USER_ variables.

Is there a problem with the installation script?

### Theme

custom theme. The theme is not an issue.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
I'll come back to this ....
```

**Comment by JanDeDobbeleer** [comment]
@plastikfan log isn't relevant in this case. You're right we do set explicitly on `HKEY_CURRENT_USER` and not `HKEY_LOCAL_MACHINE` and I would need to validate if that can be done without admin privileges (I honestly don't know). I'll flag this as an enhancement, will check.

**Comment by plastikfan** [comment]
As a workaround, I could add the omp path to the SYSTEM _PATH_ variable, which should hopefully allow this to work for the other users. Just about to try this out now ...

**Comment by plastikfan** [comment]
... yup that works as a temp fix.

**Comment by JanDeDobbeleer** [comment]
I found the following in the docs

> HKA	(equals HKLM in administrative install mode, HKCU otherwise)

Meaning all we need is change the explicit HKLU to HKA.

**Comment by plastikfan** [comment]
Hi @JanDeDobbeleer , I've just re-installed omp to test your fix and it works fine. Thanks for the swift response, nice work.
