### ISSUE TITLE
Make the dotnet section visible by default in directories containing solution filter files (*.slnf)

### ISSUE THREAD

**Issue by DamianEdwards** [JanDeDobbeleer/oh-my-posh#2185]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I work in a large code base that utilizes VS solution filter files (*.slnf) to make subsets of the overall repo usable in smaller logical chunks. This means many directories contain a *.slnf file instead of a *.sln file (the *.sln file is in the repo root).

It would be great if the dotnet section were visible by default when a *.slnf file is present ([fix](https://github.com/JanDeDobbeleer/oh-my-posh/compare/main...DamianEdwards:patch-1)).

**Comment by JanDeDobbeleer** [comment]
@DamianEdwards go for it, don't forget to add that to the docs as well.
