### ISSUE TITLE
first open powershell incomplete display

### ISSUE THREAD

**Issue by changshunxu520** [JanDeDobbeleer/oh-my-posh#2189]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

![Snipaste_2022-04-29_12-02-28](https://user-images.githubusercontent.com/16171624/165883628-dec60a4f-4234-4193-a632-a0a5cb14aebd.png)
When I use the enter key, the second line is displayed correctly

### Theme

 M365Princess

### Log output

```Shell
I don't know where to find the file
```

**Comment by JanDeDobbeleer** [comment]
This is a bug in Windows Terminal. You use `clear` to start clean.
