### ISSUE TITLE
Latest release is very slow

### ISSUE THREAD

**Issue by springcomp** [JanDeDobbeleer/oh-my-posh#219]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Just running the executable seems slow, even when just displaying the version number.

![image](https://user-images.githubusercontent.com/8488398/101045758-cf017f80-3580-11eb-8828-e0a8287166d1.png)

command | time taken 
----|----
 `oh-my-posh.exe -print-shell` | 900ms 
 `oh-my-posh.exe -version` | 5,7s 
 `oh-my-posh.exe -config xxxx` | 5,9s 

### Environment

- Oh my Posh version: 3.48.0
- Theme: JanDeDobbeler.omp.json
- Operating System: Windows 10
- Shell: PowerShell Core 7.2.x
- Terminal: Windows Terminal, VS Code Integrated Terminal

### Steps to Reproduce

1. Launch your Terminal
2. Run `Measure-Command { oh-my-posh -version }`
3. Notice the `TotalSeconds` time taken

**Expected behavior:** 

Should not exceed, say, 1 second, 1 second and a half.

**Actual behavior:** 

Close to 6 seconds is definitly too long 😉

**Comment by JanDeDobbeleer** [comment]
Can you confirm this is lower on a previous release because nothing significant changed that can impact this.

**Comment by JanDeDobbeleer** [comment]
@springcomp 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/2492783/101049937-44228400-3584-11eb-9a0a-8d4781d565a6.png">
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/2492783/101050161-77651300-3584-11eb-8eab-fe8247953f34.png">

Seems like something other than oh-my-posh is slowing down your machine's capabilities. This is with `3.48.0`

**Comment by JanDeDobbeleer** [comment]
Even in a git repo (which is the most challenging segment) it runs smoothly:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/2492783/101051051-5650f200-3585-11eb-8c58-b4a086fb29fd.png">

**Comment by springcomp** [comment]
Indeed, I just tried other suggestions and it is slow as well.
This behaviour appeared suddenly, on a corporate laptop, so must have to do with AntiVirus or other background processes.

Just restarted and it seems to have resolved itself.
Thanks for the good work and apologies for the false negative.

**Comment by JanDeDobbeleer** [comment]
No worries. I'm here to help! Happy to hear you're enjoying this 🤗
