### ISSUE TITLE
When I enter the "winget install oh-my-posh" command, there's NO response!?

### ISSUE THREAD

**Issue by WqxLoveCoding** [JanDeDobbeleer/oh-my-posh#2190]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I enter the "winget install oh-my-posh" command, there's NO response, it just STUCK LOADING...
![image](https://user-images.githubusercontent.com/57825815/165912815-3282abea-3708-419c-95d5-a46350b150e5.png)

### Theme

none

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
none
```

**Comment by JanDeDobbeleer** [comment]
@WqxLoveCoding this 9/10 is either a network issue (it doesn't even seem to download something), or antivirus issue as Defender (or similar) blocks winget execution. But not something we can fix.
