### ISSUE TITLE
The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by ilkeEren27** [JanDeDobbeleer/oh-my-posh#2191]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I got this error when I open powershell
![image](https://user-images.githubusercontent.com/56888921/165933692-46268208-e0d5-4be6-aac6-c6d4b61e22c0.png)
This is my user_profile.ps1
![image](https://user-images.githubusercontent.com/56888921/165933727-b70948c2-ad19-43a3-baa7-f6ecaa231747.png)

### Theme

I'm using Paradox theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
C:\Users\IlkeEren> oh-my-posh debug
oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by JanDeDobbeleer** [comment]
@Hypnamed there's quite a significant block of text in your screenshot that has a clue to the issue at hand:

> Hey friend
In an effort to grow oh-my-posh, the decision was made to no
longer support the PowerShell module. Over the past year, the
added benefit of the module disappeared, while the burden of
maintaining it increased.
However, this doesn't mean oh-my-posh disappears from your
terminal, it just means that you'll have to use a different
tool to install it.
All you need to do, is follow the migration guide here:
https://ohmyposh.dev/docs/migrating

**Comment by ilkeEren27** [comment]
As you can see, I already tried it but it won't work

**Comment by JanDeDobbeleer** [comment]
@Hypnamed I do still see `Import-Module oh-my-posh` in your `$PROFILE` which could imply you missed some steps in the [migration](https://ohmyposh.dev/docs/migrating) document.

**Comment by ilkeEren27** [comment]
Now, I deleted it but it still gives error
![image](https://user-images.githubusercontent.com/56888921/165939079-455b686a-b918-410b-9437-a5831cf75290.png)

**Comment by JanDeDobbeleer** [comment]
@JanDeDobbeleer let's take this one step at a time. It seems oh-my-posh isn't on your `PATH`. How did you install oh-my-posh now, looking at the migration document? This is the part of the documentation for [installation](https://ohmyposh.dev/docs/installation/windows)

**Comment by ilkeEren27** [comment]
I did everything in https://ohmyposh.dev/docs/migrating from zero and it's solved, thank you so much
