### ISSUE TITLE
Powerline Glyphs replaced with other characters when Out-File used

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#220]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
Writing stock theme with Out-File replaces powerline glyphs with odd characters
[Description of the bug or feature]

### Environment

- Oh my Posh version: 3.46.1
- Theme: emodipt
- Operating System: Win10
- Shell: pwsh
- Terminal: Windows Terminal

### Steps to Reproduce

1. `Set-PoshPrompt -Theme emodipt`
2. `Write-PoshTheme | Out-File -FilePath ~/.go-my-posh.json`
3. `Set-PoshPrompt -Theme  ~/.go-my-posh.json`

**Expected behavior:** [What you expected to happen]
Custom prompt should look the same as stock emodipt
![image](https://user-images.githubusercontent.com/41576511/101093792-46e89d80-35b3-11eb-916d-e63badc3626e.png)

**Actual behavior:** [What actually happened]
Powerline Glyphs aren't rendered properly
![image](https://user-images.githubusercontent.com/41576511/101093887-6c75a700-35b3-11eb-88fc-f500f5d197af.png)

**Comment by JanDeDobbeleer** [comment]
@otaconjh this is a first guess, I'll look into it later today, but I think you need to set the encoding to utf8 in Out-File.

`-Encoding utf8`

**Comment by JanDeDobbeleer** [comment]
@otaconjh confirmed on my machine to be working with the proper encoding, although it's `oem`:

2. `Write-PoshTheme | Out-File -FilePath ~/.go-my-posh.json -Encoding oem`

**Comment by ghost** [comment]
Thank you

**Comment by boarder2** [comment]
Encoding works, might be worth updating the doc on the website with it! https://ohmyposh.dev/docs/upgrading

**Comment by JanDeDobbeleer** [comment]
@boarder2 fair point, we do accept contributions 😉

**Comment by JanDeDobbeleer** [comment]
@boarder2 🙏🏻
