### ISSUE TITLE
Theme Config Export Brainstorm

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2202]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Just a brainstorming session I had with regards to the exporter. Started because it would be nice if obscuring/standardizing the user/host were default, but then I thought of a few more things.

- Fix broken glyphs (obviously if this was a quick fix it would have been done. I've peeked at the code and it's way above my head)
- Add
  - max-width (for the whole render)
  - rprompt-offset: right-align 
  - set-user (defaults to "user")
  - set-host (defaults to "host" or "hostname"
  - set-OS (defaults to current os? affects OS segment and the GUI window render)
  - set-time
  - set-date
  - set-fake-path
  - set-root
  - set-exectime (defaults to 1m:2s:300ms)
  - set-err (not sure of the naming convention you'd prefer for a command that didn't exit 0)
  - set-segment: {"type": "node", ".Full": "18.0.0" } (syntax is surely shell-dependent)
- Change
   - [Configure GitHub's linting process to auto-sort JSON lists???](https://github.com/keithamus/sort-package-json/issues/67)

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg I saw this, letting it marinate. I would rather have a mock environment with default values than allow a ton of settings.  The glyphs is a challenge, previous work was done to already support a lot.

**Comment by ehawman-rosenberg** [comment]
>I would rather have a mock environment with default values

That makes a lot more sense. The only issue you might run into is having `< every / single / language / and / package / manager / segment / active / at / once / which / would / probably / never / happen / in / real / use / and / would / cause / all / kinds / of / formatting / headaches >`

Maybe have a default mock environement, then give us `--hide-segments='langs-repos' --show-segments=('python', 'npm')` 

I'm just brainstorming here so the syntax is a bit fuzzy, but `langs-repos` would be a predefined list of segments referenced in the docs, and users could add to it `(langs-repos, "spotify", "wifi")`

**Comment by lewis-yeung** [comment]
> Maybe have a default mock environement, then give us `--hide-segments='langs-repos' --show-segments=('python', 'npm')`

I know that Cobra CLI supports parsing an array argument input so this is possible.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg @lewis-yeung I'm more in favour of having a model that parses to the segments properties and enables what's listed. Easier to read/extend and maintain, no?

**Comment by andrewcrook** [comment]
> < every / single / language / and / package / manager / segment / active / at / once / which / would / probably / never / happen / in / real / use / and / would / cause / all / kinds / of / formatting / headaches >

Just an idea you could direnv (runs a script upon entering a directory) be used to change language and package manager prompt details upon entering a specific projects folder. This would allow you to simplify the prompts configuration by having separate (or partial) configurations. Direnv will also change back to default when exiting a directory.

in the past I have done this with PS1 etc variables in my .env and .envrc files

You could just use direnv or autoenv to reload ohmypost with a different configuration files.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg I gave this a look and go a few times already but tbh it's pretty hard thing to do correctly (with minimal gain). Therefore, I decided to close this.
