### ISSUE TITLE
Different `oh-my-posh help` calls show the same usage line

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2204]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I run `oh-my-posh help print` or `oh-my-posh print --help`, it shows:

```
Print one of the prompts based on the location/use-case.

Usage:
  oh-my-posh prompt print [debug|primary|secondary|transient|right|tooltip|valid|error] [flags]

...
```

which is the same to the help text shown by `oh-my-posh help prompt print` (though we know that `prompt` is deprecated). However, the `prompt` in the section `Usage` should not appear in this case though it doesn't affect a normal use. The same example occurs in `oh-my-posh help init` and `oh-my-posh help debug`. Seems to be related to:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/0d4adf2c67900c1a4b82bbc0d78810f4f4650540/src/cli/prompt.go#L20-L22

In Golang, AFAIK, the `init` functions in the same package but defined in different .go files are invoked in filename alphabetical order of the files in which they are defined. E.g., `promptCmd.AddCommand(printCmd)` (inside the `init` function defined in `cli/prompt.go`) will be executed after `rootCmd.AddCommand(printCmd)` (inside the `init` function defined in `cli/print.go`), which causes the usage line of `print` to be appended to that of the most recently added parent command `prompt`.

Perhaps I missed something, but for the time being I cannot find a proper way to make it show different usage lines in the help text for different `oh-my-posh help` calls due to the Cobra mechanism of handling multi-parent commands. Do you have any ideas?

### Theme

(This issue has nothing to do with a specific theme config.)

### What OS are you seeing the problem on?

(This issue has nothing to do with a specific OS.)

### Which shell are you using?

(This issue has nothing to do with a specific shell.)

### Log output

(N/A)

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung no immediate idea but also not that relevant as these commands need to be removed anyways in a couple of months. That and this is a purely internal command too, not to be used by anyone under normal circumstances.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Fair point.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung but I get the point 😁 Let's ignore this for now and the removal in due time will also address it.
