### ISSUE TITLE
M365Princess Request change

### ISSUE THREAD

**Issue by MarieMachado** [JanDeDobbeleer/oh-my-posh#2208]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello, 
Would be nice if there was some conflit in the branch the heart would just broke. I know it requires an unnecessary effort, but would be cute ^^

Best regards,
Maria

**Comment by JanDeDobbeleer** [comment]
@MarieMachado there's no way (today) to cross-reference output from 1 segment in the other. But technically, that's feasible I guess. Allow me to have a look at how to achieve this.

**Comment by JanDeDobbeleer** [comment]
@MarieMachado in the latest release, I have this `template` which gives the desired effect:

```json
"template": " {{ if .Segments.Git.UpstreamGone }}\uf7d3{{ else if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} ",
```
