### ISSUE TITLE
oh-my-posh not working in wsl

### ISSUE THREAD

**Issue by RiteshChepuri** [JanDeDobbeleer/oh-my-posh#2213]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened! So I tried to install oh my posh prompt in WSL(ubuntu 22.04) which I already installed successfully in PowerShell and been using it since more than 5 months . After installing the oh my posh it shows that oh my posh command not found. 

### Theme

![image](https://user-images.githubusercontent.com/81766942/166497947-064f5d7c-ee02-415d-8eaf-515054db8d34.png)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```Shell
oh my posh command not found
```

**Comment by JanDeDobbeleer** [comment]
@RiteshChepuri how did you install oh-my-posh? Because the message implies it's not on your `PATH`.

**Comment by RiteshChepuri** [comment]
@JanDeDobbeleer I used Brew To Install oh my posh

**Comment by JanDeDobbeleer** [comment]
Did you follow all brew linux steps to ensure everything is on your `PATH`? There's an important section pointing to [next steps](https://docs.brew.sh/Homebrew-on-Linux#install).

**Comment by lewis-yeung** [comment]
@RiteshChepuri Perhaps you have the same problem as #2123.

**Comment by RiteshChepuri** [comment]
I guess there are some Problems when I installed with brew in ubuntu22.04 i installed it manually its working,
Thank you..
