### ISSUE TITLE
Set-Theme not being recognized

### ISSUE THREAD

**Issue by JasperSurmont** [JanDeDobbeleer/oh-my-posh#222]
### Prerequisites

- [V ] I have read and understand the `CONTRIBUTING` guide
- [V ] I looked for duplicate issues before submitting this one

### Description

After installing oh-my-posh, and editing my profile so it uses Set-Theme, it doesn't recognize Set-Theme as a cmdlet
### Environment

- Oh my Posh version: 3.48.0
- Theme: /
- Operating System: Windows
- Shell:  Powershell
- Terminal: Microsoft terminal

### Steps to Reproduce

1. Install oh-my-posh using `Install-Module oh-my-posh -AllowPrerelease`
2. Use Set-Theme

**Comment by JanDeDobbeleer** [comment]
That's because `Set-Theme` is a V2 cmdlet. You need to use `Set-PoshPrompt`. See [here](https://ohmyposh.dev/docs/upgrading) for more context.
