### ISSUE TITLE
Updating to VSCode 1.67 broke the icons

### ISSUE THREAD

**Issue by veronicageek** [JanDeDobbeleer/oh-my-posh#2225]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Updated to VSCode `1.67` on MacOS and the icons in the prompt are now cut. It might be again a setting to change (like the "minimum contrast ratio" in `1.66`, but not sure.

![image](https://user-images.githubusercontent.com/25181757/167024169-98e06047-cdc7-498c-a610-5e133aae8ac1.png)

I've tried increasing / decreasing font, but same results.

### Theme

Custom theme based on `powerlevel10k_classic`

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

powershell

### Log output

```Shell
.
```

**Comment by ehawman-rosenberg** [comment]
What font are you using? Does a different NF cut in the same location? (Also the fact that they're just chopped in half is hilarious)

**Comment by ehawman-rosenberg** [comment]
Just wanted to report that this problem hasn't yet appeared on Windows.

**Comment by lewis-yeung** [comment]
This also appears in VSCode **v1.67.0** on **Windows**. A temporary workaround:

```json
"terminal.integrated.gpuAcceleration": "canvas"
```

This works for me but I don't know if there are any side effects. Have to complain that it always gets me some "SURPRISE" when VSCode is updated... 😅😅😅

**Comment by ehawman-rosenberg** [comment]
@lewis-yeung I was using 1.67.0 on Windows. I wonder if there's something else at play, like extensions or something. What shell were you using?

**Comment by ehawman-rosenberg** [comment]
Confirming the bug on MacOS.

**Comment by lewis-yeung** [comment]
@ehawman-rosenberg I use PowerShell v7.2.3. That should be a VSCode bug since it doesn't appear in v1.66.2 without any extension changed on my end.

**Comment by JanDeDobbeleer** [comment]
@veronicageek @ehawman-rosenberg unfortunately we can't fix that on our end. Rendering is the responsibility of the terminal. Please create an issue at code.

**Comment by veronicageek** [comment]
> This also appears in VSCode **v1.67.0** on **Windows**. A temporary workaround:
> 
> ```json
> "terminal.integrated.gpuAcceleration": "canvas"
> ```
> 
> This works for me but I don't know if there are any side effects. Have to complain that it always gets me some "SURPRISE" when VSCode is updated... 😅😅😅

Thanks @lewis-yeung, worked on MacOS too!
