### ISSUE TITLE
Possible to split "notcharging" and "discharging" into separate states?

### ISSUE THREAD

**Issue by lassevk** [JanDeDobbeleer/oh-my-posh#2237]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

My Macbook Air has this feature where it charges the battery up to around 80%, and then stops charging, running the computer solely on the power adapter and not using the battery. It does this to preserve the battery life (long term, not charge throughout the day).

The states being used here:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segments/battery.go#L51

`case battery.Discharging, battery.NotCharging:`

Does the "NotCharging" correspond to what I'm describing above? If so, would it be possible to split this into separate states for the plugin? I would actually like to know that the Macbook is running solely on power adapter, even if the battery isn't at 100%, but right now the icons and colors matches the state of discharging, which is not correct in my opinion.

Ideally I would be able to distinguish between the following states:

* Battery full, running on power adapter
* Battery not full, not charging, and running on power adapter
* Battery not full, and charging
* Battery empty

My feature request is thus as follows:

1. Split Discharging and NotCharging into separate states
2. Add a new icon, for X (not good with names), meaning icon for "battery not full, not charging, and running on power adapter"
3. The NotCharging state would look for this new icon, and if it hasn't been set, it would fall back to the discharging icon, this would preserve the current functionality until someone actually edits their configuration file to specify this new icon

**Comment by lassevk** [comment]
Super-ideally I would like to be able to completely hide the segment when the computer is running solely on power adapter, this would mean full and not charging, as well as this not full and not charging states. Then the segment would only show up if the battery is involved, either that it is being charged, or that the computer is running off of it.

**Comment by JanDeDobbeleer** [comment]
@lassevk can do 👍🏻

**Comment by JanDeDobbeleer** [comment]
> Super-ideally I would like to be able to completely hide the segment when the computer is running solely on power adapter

@lassevk that's possible by leveraging the template. As that state is exposed, you can make the template resolve to an empty string using an if else statement.

**Comment by lassevk** [comment]
> > Super-ideally I would like to be able to completely hide the segment when the computer is running solely on power adapter
> 
> @lassevk that's possible by leveraging the template. As that state is exposed, you can make the template resolve to an empty string using an if else statement.

Perfect!
