### ISSUE TITLE
Gaps in powerline segments when using certain icons

### ISSUE THREAD

**Issue by tradiff** [JanDeDobbeleer/oh-my-posh#226]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I am observing strange gaps in powerline segments, but only if certain icons are used.  In this screenshot you can see a black gap, which only appeared once I changed the prefix from `" \uE5FF "` (a folder) to `" \ufa1a "` (a stopwatch)

![image](https://user-images.githubusercontent.com/934490/101301788-2741b700-37f7-11eb-8723-d85dd0e2f458.png)

The entire segment code is:
```json
{
  "type": "path",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "#ffffff",
  "background": "#ff479c",
  "properties": {
    "prefix": " \ufa1a ",
    "style": "folder"
  }
},
```

### Environment

- Oh my Posh version: 3.5.0
- Theme: jandedobbeleer
- Operating System: Windows 10
- Shell: Powershell 7.1.0
- Terminal: Windows Terminal 1.4.3243.0
- Font: I've tried multiple:
  - "fontFace": "MesloLGM Nerd Font",
  - "fontFace": "MesloLGS Nerd Font",
  - "fontFace": "DejaVuSansMono Nerd Font",

### Steps to Reproduce

1. Use a theme with powerline segments such as jandedobbeleer
2. Replace an icon with  `" \ufa1a "`
3. Observe broken powerline segments

This also occurs with other icons, such as `\ufa1e` (nf-mdi-timer_sand). But interestingly it does not occur with the other sand timer icons (`\ufbab` and `\ufc8a`). This also occurs with other segment types, it is not limited to `path`

**Expected behavior:** No gap

**Actual behavior:** Gap

**Comment by JanDeDobbeleer** [comment]
Correct, some icon are acting annoying. Unfortunately it's not something I can fix, that's a Nerd Font issue.
