### ISSUE TITLE
Add writeable test to Path segment

### ISSUE THREAD

**Issue by GrinGrin** [JanDeDobbeleer/oh-my-posh#2269]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi !
I've just watched a video where the user's prompt had a red lock symbol at the end of its prompt when in a non writeable directory:
![image](https://user-images.githubusercontent.com/15949215/168445661-093071e6-b73b-4156-9e2f-9517f38904b4.png)

It would be great to have a new property, let say `.IsWriteable`, that can be used in the template to add an indicator, change colors or the whole path display if we are in a non-writeable directory by the current user.

It can also be achieved using the command segment and parse the output/return code of some test (for example `[ -w . ]` in bash) but it may induce latency in prompt's rendering on some shells and it's not really shell agnostic !

BTW, thanks for the great work ;-)

**Comment by JanDeDobbeleer** [comment]
@GrinGrin can do. Seems rather straightforward too.

**Comment by JanDeDobbeleer** [comment]
@GrinGrin 

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/2492783/168525147-4febee03-484f-4512-9837-14fb33a7442b.png">

**Comment by ehawman-rosenberg** [comment]
Trying to update my theme for this

```json
"background_templates": [
    "{{ if .Root }}red{{ end }}{{ if not .Writable }}red{{ end }}"
],
```
If this evals to `redred`, is that a problem? Do I have access to OR using this format?

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg yes, you need to split this and set the order order right. Either you have both, using and, or an individual color for either case (or both).

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer I'm riding the strugglebus here. Is the {{ if condition }} {{ end }} syntax standard or specific to OMP? I'm trying to find documentation on it and missing.

```json
"background_templates": [
    "{{ if .Writable and not .Root }}{{ else }}red{{ end }}"
],
```

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg it's standard go text/template syntax. The `and` needs to be added before, you can find some info [here](https://learn.hashicorp.com/tutorials/nomad/go-template-syntax). The logs should also display that error now.

```golang
"background_templates": [
    "{{ if and .Writable (not .Root) }}{{ else }}red{{ end }}"
],
```
