### ISSUE TITLE
Azure segment isn't displaying anything

### ISSUE THREAD

**Issue by rossmeyer1** [JanDeDobbeleer/oh-my-posh#2280]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Oh-my-posh is looking in .Azure rather than .azure for PowerShell Azure segment. Renaming fixes, but then stops being able to change context as PowerShell can no longer find the correct file.

### Theme

clean-detailed

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

powershell

### Log output

```Shell
2022/05/16 17:23:30 Getenv duration: 1.2µs, args: AZURE_CONFIG_DIR
2022/05/16 17:23:30 error: FileContent
open /home/ross/.azure/azureProfile.json: no such file or directory
2022/05/16 17:23:30 FileContent duration: 7.2µs, args: /home/ross/.azure/azureProfile.json
2022/05/16 17:23:30 debug: Getenv

2022/05/16 17:23:30 Getenv duration: 800ns, args: AZURE_CONFIG_DIR
2022/05/16 17:23:30 error: FileContent
open /home/ross/.azure/AzureRmContext.json: no such file or directory
2022/05/16 17:23:30 FileContent duration: 2.2µs, args: /home/ross/.azure/AzureRmContext.json
2022/05/16 17:23:30 Flags duration: 100ns, args:
```

**Comment by JanDeDobbeleer** [comment]
@GHRoss well, there's no config to be found so according to oh-my-posh, this is correct as it can't really display anything without that. This means you're not logged in or we have the folder mapped incorrectly?

**Comment by rossmeyer1** [comment]
I'm logged in and yes, I believe the folder is mapped incorrectly.

**Comment by JanDeDobbeleer** [comment]
@GHRoss can you let me know the actual folder and file name? I'll fix accordingly.

**Comment by rossmeyer1** [comment]
> @GHRoss can you let me know the actual folder and file name? I'll fix accordingly.

/home/ross/.Azure

**Comment by JanDeDobbeleer** [comment]
@GHRoss I knew it! Damn upper case. Which file do you have in there? Both or just one?

**Comment by rossmeyer1** [comment]
> @GHRoss I knew it! Damn upper case. Which file do you have in there? Both or just one?

Just one.

**Comment by rossmeyer1** [comment]
> @GHRoss I knew it! Damn upper case. Which file do you have in there? Both or just one?

Is this related?! https://github.com/JanDeDobbeleer/oh-my-posh/issues/1567

**Comment by JanDeDobbeleer** [comment]
@GHRoss no, I removed that one day I think because I forgot about the cases.

**Comment by rossmeyer1** [comment]
Thank you!
