### ISSUE TITLE
Flag to Remove Logging

### ISSUE THREAD

**Issue by ajmeese7** [JanDeDobbeleer/oh-my-posh#2281]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

This may already exist, I didn't see any documentation for it but if this is a duplicate then I apologize.

It would be awesome if there was a flag to disable the relevant `omp` file for our shell of choice, i.e. `src/shell/scripts/omp.bash` in my case. My jailed user doesn't have access to the `rm` and `cat` commands and I would like to keep it that way, so if I could skip those commands in this file or just skip the file execution entirely that would be very helpful!

**Comment by JanDeDobbeleer** [comment]
@ajmeese7 that's way too much overhead to maintain imho. It's going to be easier for you to copy the init script and adjust that to your user's available functionality.
