### ISSUE TITLE
Can't evaluate field Writable

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2284]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

This is (hopefully) due to me misunderstanding {{ templates }}.

First, some pictures of the misbehaving prompt:
Non-Root: 
![image](https://user-images.githubusercontent.com/81652082/169115464-835b3591-b493-4ac1-b20c-c25afda1c6cc.png)
Root: 
![image](https://user-images.githubusercontent.com/81652082/169115518-0b0cbd13-e2d3-4a65-a425-8d4915beaaf0.png)

The last two segments:
```json
{
  "background": "blue",
  "background_templates": ["{{ if not .Writable }}red{{ end }}"],
  "foreground": "black",
  "powerline_symbol": "\ue0bc",
  "properties": {
    "folder_icon": "\uf07b",
    "folder_separator_icon": " \uf554 ",
    "home_icon": "\uf7db",
    "max_depth": 3,
    "style": "agnoster_short"
  },
  "style": "powerline",
  "template": "{{ if gt .Code 0 }} {{ else }}{{ end }}\ue5ff {{ .Path }} {{ if not .Writable }}\uf83d {{end}}",
  "type": "path"
},
{
  "background": "blue",
  "background_templates": [
    "{{ if or .Root (not .Writable) }}red{{ else }}blue{{ end }}"
  ],
  "foreground": "white",
  "properties": {
    "root_icon": "\uf292"
  },
  "style": "diamond",
  "template": "{{ if .Root }} \uf0e7 {{ else }}\u0008{{ end }}",
  "trailing_diamond": "\ue0b0",
  "type": "text"
}
```

Expected behavior: When Root, render a lightning bolt and turn the background red. When not Writable, turn the background red.

Actual behavior: https://youtu.be/68ugkg9RePc?t=32

Tested with both:
`{{ if or .Root (not .Writable) }}red{{ else }}blue{{ end }}` and `{{ if and (not .Root) .Writable }}blue{{ else }}red{{ end }}` and validated on this site: https://camlittle.com/go-template-validation

I'm guessing this line in the logs is the most relevant:
`template: title:1:27: executing "title" at <.Data.Writable>: can't evaluate field Writable in type template.Data`

### Theme

devious-diamonds (Update WIP version)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

<details>
  <summary>Output</summary>
<pre><code>
Shell
Version: 7.85.2

Segments:

ConsoleTitle(true)   -   0 ms - Users
iterm(false)         -   0 ms -
os(true)             -   0 ms -  ═
shell(true)          -   0 ms -   pwsh
session(true)        -   0 ms -  ehawman@EHSupportLaptop
julia(false)         -   0 ms -
go(false)            -   0 ms -
java(false)          -   1 ms -
php(false)           -   0 ms -
node(false)          -   1 ms -
azfunc(false)        -   0 ms -
ruby(false)          -   0 ms -
kubectl(false)       -  26 ms -
python(false)        -   1 ms -
aws(false)           -   0 ms -
time(true)           -   0 ms -  Wed | 13:19:34
executiontime(true)  -   0 ms -  0ms 
git(false)           -  18 ms -
text(true)           -   0 ms -  ╚
exit(true)           -   0 ms -  
path(true)           -   0 ms -  C:  Users 
text(true)           -   0 ms - 

Run duration: 73.5942ms

Cache path: C:\Users\ehawman\AppData\Local\oh-my-posh

Config path: C:\Users\ehawman\AppData\Local\Programs\oh-my-posh\themes\eh_custom\devious-diamonds.omp.json

Logs:

2022/05/18 13:19:34 debug: Getenv
C:\Users\ehawman\AppData\Local
2022/05/18 13:19:34 Getenv duration: 0s, args: LOCALAPPDATA
2022/05/18 13:19:34 CachePath duration: 0s, args:
2022/05/18 13:19:34 debug: Getenv
C:\Users\ehawman\AppData\Local\Programs\oh-my-posh\themes\eh_custom\devious-diamonds.omp.json
2022/05/18 13:19:34 Getenv duration: 0s, args: POSH_THEME
2022/05/18 13:19:34 Shell duration: 18.4656ms, args:
2022/05/18 13:19:34 resolveConfigPath duration: 18.4656ms, args:
2022/05/18 13:19:34 Init duration: 18.4656ms, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 config.loadConfig duration: 1.6048ms, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/05/18 13:19:34 Root duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 ErrorCode duration: 0s, args:
2022/05/18 13:19:34 IsWsl duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: User
ehawman
2022/05/18 13:19:34 User duration: 0s, args:
2022/05/18 13:19:34 debug: Host
EHSupportLaptop
2022/05/18 13:19:34 Host duration: 506.4µs, args:
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 506.4µs, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: TERM_PROGRAM
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: SSH_CONNECTION
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: SSH_CLIENT
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 523.2µs, args: *.jl
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.go
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: go.mod
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: JAVA_HOME
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: pom.xml
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 547.9µs, args: build.gradle.kts
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: build.sbt
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: .java-version
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: .deps.edn
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: project.clj
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: build.boot
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 523.3µs, args: *.java
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.class
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.gradle
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 520.5µs, args: *.jar
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.clj
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.cljc
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.php
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 34.6µs, args: composer.json
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: composer.lock
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: .php-version
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: blade.php
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 522.9µs, args: *.js
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.ts
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: package.json
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: .nvmrc
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: pnpm-workspace.yaml
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: .pnpmfile.cjs
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: .npmrc
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 546.9µs, args: .vue
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: host.json
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: local.settings.json
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: function.json
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: *.rb
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: Rakefile
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 507.2µs, args: Gemfile
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 13µs, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Getenv
C:\Users\ehawman\AppData\Local
2022/05/18 13:19:34 Getenv duration: 0s, args: LOCALAPPDATA
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFilesInDir
false
2022/05/18 13:19:34 HasFilesInDir duration: 0s, args: kubectl.exe
2022/05/18 13:19:34 error: CommandPath
no Windows Store App
2022/05/18 13:19:34 HasCommand duration: 26.1524ms, args: kubectl
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 534.5µs, args: *.py
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 4.4µs, args: *.ipynb
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: pyproject.toml
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 debug: HasFiles
false
2022/05/18 13:19:34 HasFiles duration: 0s, args: venv.bak
2022/05/18 13:19:34 debug: HasFolder
false
2022/05/18 13:19:34 HasFolder duration: 0s, args: .venv
2022/05/18 13:19:34 debug: HasFolder
false
2022/05/18 13:19:34 HasFolder duration: 0s, args: venv
2022/05/18 13:19:34 debug: HasFolder
false
2022/05/18 13:19:34 HasFolder duration: 0s, args: virtualenv
2022/05/18 13:19:34 debug: HasFolder
false
2022/05/18 13:19:34 HasFolder duration: 0s, args: env
2022/05/18 13:19:34 debug: HasFolder
false
2022/05/18 13:19:34 HasFolder duration: 0s, args: venv-win
2022/05/18 13:19:34 debug: HasFolder
false
2022/05/18 13:19:34 HasFolder duration: 557.7µs, args: pyenv-win
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: AWS_VAULT
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: AWS_PROFILE
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: AWS_REGION
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: AWS_DEFAULT_REGION
2022/05/18 13:19:34 debug: Getenv

2022/05/18 13:19:34 Getenv duration: 0s, args: AWS_CONFIG_FILE
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 error: FileContent
open C:\Users\ehawman/.aws/config: The system cannot find the path specified.
2022/05/18 13:19:34 FileContent duration: 0s, args: C:\Users\ehawman/.aws/config
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 ExecutionTime duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 HasCommand duration: 17.7712ms, args: git.exe
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/05/18 13:19:34 HasParentFilePath duration: 15.4µs, args: .git
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 ErrorCode duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 PathSeparator duration: 0s, args:
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 IsWsl duration: 0s, args:
2022/05/18 13:19:34 StackCount duration: 0s, args:
2022/05/18 13:19:34 error: DirIsWritable
Write permission bit is not set on this file for user
2022/05/18 13:19:34 DirIsWritable duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 debug: Pwd
C:\Users
2022/05/18 13:19:34 Pwd duration: 0s, args:
2022/05/18 13:19:34 debug: Home
C:\Users\ehawman
2022/05/18 13:19:34 GOOS duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 Shell duration: 0s, args:
2022/05/18 13:19:34 TemplateCache duration: 0s, args:
2022/05/18 13:19:34 error: Render
template: title:1:27: executing "title" at <.Data.Writable>: can't evaluate field Writable in type template.Data
2022/05/18 13:19:34 debug: Getenv
C:\Users\ehawman\AppData\Local
2022/05/18 13:19:34 Getenv duration: 0s, args: LOCALAPPDATA
2022/05/18 13:19:34 CachePath duration: 0s, args:
2022/05/18 13:19:34 Flags duration: 0s, args:
</code></pre>
</details>

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg OK, now I see it. `.Writable` is only known by the `path` segment. Reference it using the following template:

```
"{{ if or .Root (not .Segments.Path.Writable) }}red{{ else }}blue{{ end }}"
```

**Comment by ehawman-rosenberg** [comment]
Ah that checks out! Is there a part of the docs that mentions cross-referencing properties between segments? Because that's a handy trick I didn't know about before. I think a callout or section in docs/configuration/templates would be useful.

Thanks!

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg it's a silently launched feature 😂 Will talk about it in what's new number 3 and also add the docs at that time.
