### ISSUE TITLE
Code block in issue form template

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2285]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Unsure if this is possible, but the Log output block can be gimungous when rendered out of an Issue form.

Currently, "Log output" gets wrapped in backticks and rendered in its entirety. Is it possible to drop it into this format?

```html
### Log output

<details>
  <summary>Output</summary>
<pre><code>[dump the contents of the Log output field here]
</code></pre>
</details>
```

### Log output

<details>
  <summary>Output</summary>
<pre><code>[dump the contents of the Log output field here]
</code></pre>
</details>

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg I'll need to see if that's supported by issue forms.

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer I looked into this and it doesn't appear to be possible currently. I'm going to close this and make a suggestion with GitHub.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg I have a conversation going on the topic too ;-)

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer Oh! Linkme and I'll give my support.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg it's internal :-) One of the perks of being a GH Star.

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer Ah fair enough! Well best of luck to you.

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer https://github.com/github/feedback/discussions/16934

Does this implementation suggestion make sense or am I asking too much?
