### ISSUE TITLE
Accordion?

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2288]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I apologize if this is an intentional divergent/sensational spelling (or maybe a language difference?), but in [What's new #3](https://ohmyposh.dev/blog/whats-new-3) you refer to collapsed sections as "accordeon" style.

The instrument is typically spelled "[Accordion](https://en.wikipedia.org/wiki/Accordion)".

If "accordeon" is an intentional sensational spelling, I'm happy to use it, but I'd suggest making a note of that somewhere.

### Theme

N/A

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
I actually googled this as I was struggling to find the right spelling 😭

**Comment by ehawman-rosenberg** [comment]
![image](https://user-images.githubusercontent.com/81652082/169341206-52dc584f-64ce-4a78-a478-c3a277db8fa9.png)

I think we've found the explanation. If you want to keep it Dutch I think that's 100% appropriate. You might just include a little callout notifying everyone of the deviation from the rest of the English-language project.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg i'll change it. Needs to be EN 😉

**Comment by ehawman-rosenberg** [comment]
Sounds good. I'll close this issue, then.

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg it's a typo in the blog due to me being a Dutch speaker :-). The implementation is correct.
