### ISSUE TITLE
Conflict with zsh-autosuggestions and history-incremental-search-backward

### ISSUE THREAD

**Issue by AlexJF** [JanDeDobbeleer/oh-my-posh#2289]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

https://github.com/JanDeDobbeleer/oh-my-posh/blame/main/src/shell/scripts/omp.zsh#L62 introduced by https://github.com/JanDeDobbeleer/oh-my-posh/pull/2129 causes (at least) the following symptoms in ZSH if `enable_poshtooltips` is called:

* With zsh-autosuggestions, suggested autocompletion will be accepted but with a space inserted in the middle:
   
    <img width="175" alt="image" src="https://user-images.githubusercontent.com/373323/169356531-c74d1105-6c32-4f3f-8669-b2f20d4745c9.png">
    <img width="180" alt="image" src="https://user-images.githubusercontent.com/373323/169356692-979ad913-9def-4ecc-94de-b0e7a6deb71f.png">

* With the history-incremental-search-backward function (`bindkey '^R' history-incremental-search-backward`), search will be exited as soon as space is pressed

    <img width="181" alt="image" src="https://user-images.githubusercontent.com/373323/169356855-8c655402-b9fe-4c26-87b0-5fbf06c8dd57.png">
    <img width="184" alt="image" src="https://user-images.githubusercontent.com/373323/169356899-7f43797c-1179-4064-aab9-71cb284272af.png">

As soon as I overwrite the keybinding on " " to one of the traditional behaviours (e.g. `bindkey " " magic-space` or `bindkey " " self-insert`), things work again but tooltips seem to stop working:

* zsh-autosuggestions (not entirely clear but the suggestion is not accepted here, it's still just a suggestion for the command that I ended up executing before due to this bug)

    <img width="175" alt="image" src="https://user-images.githubusercontent.com/373323/169356531-c74d1105-6c32-4f3f-8669-b2f20d4745c9.png">
    <img width="174" alt="image" src="https://user-images.githubusercontent.com/373323/169357168-18def0a4-4e85-48b6-bc09-d4fb85d92b6b.png">

* history-incremental-search-backward function

    <img width="181" alt="image" src="https://user-images.githubusercontent.com/373323/169356855-8c655402-b9fe-4c26-87b0-5fbf06c8dd57.png">
    <img width="177" alt="image" src="https://user-images.githubusercontent.com/373323/169357372-55c43b8f-6683-424b-aa4a-871cac6614f6.png">

I remember this worked nicely before :(

### Theme

Custom one. Don't think it's relevant given above findings.

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
❯ oh-my-posh debug

Version: 7.85.2

Segments:

ConsoleTitle(false)  -   0 ms -
session(true)        -   1 ms - alexandre.fonseca
path(true)           -   0 ms - ~/.zsh
git(false)           -   0 ms -
exit(false)          -   0 ms -
executiontime(false) -   0 ms -
time(true)           -   0 ms - 18:04:43
exit(true)           -   0 ms - ❯

Run duration: 5.391741ms

Cache path: /Users/alexandre.fonseca/.cache/oh-my-posh

Config path: /Users/alexandre.fonseca/Onedrive/Configurations/oh-my-posh/alexjf.omp.json

Logs:

2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 16.567µs, args: XDG_CACHE_HOME
2022/05/19 18:04:43 CachePath duration: 62.565µs, args:
2022/05/19 18:04:43 debug: Getenv
/Users/alexandre.fonseca/Onedrive/Configurations/oh-my-posh/alexjf.omp.json
2022/05/19 18:04:43 Getenv duration: 8.767µs, args: POSH_THEME
2022/05/19 18:04:43 resolveConfigPath duration: 12.3µs, args:
2022/05/19 18:04:43 Init duration: 291.998µs, args:
2022/05/19 18:04:43 Flags duration: 69ns, args:
2022/05/19 18:04:43 config.loadConfig duration: 1.343458ms, args:
2022/05/19 18:04:43 Flags duration: 213ns, args:
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 4.486µs, args: OMP_CACHE_DISABLED
2022/05/19 18:04:43 Root duration: 1.824µs, args:
2022/05/19 18:04:43 Shell duration: 215.678µs, args:
2022/05/19 18:04:43 ErrorCode duration: 73ns, args:
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 5.742µs, args: WSL_DISTRO_NAME
2022/05/19 18:04:43 IsWsl duration: 7.66µs, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 37.767µs, args:
2022/05/19 18:04:43 PathSeparator duration: 80ns, args:
2022/05/19 18:04:43 PathSeparator duration: 40ns, args:
2022/05/19 18:04:43 PathSeparator duration: 41ns, args:
2022/05/19 18:04:43 PathSeparator duration: 41ns, args:
2022/05/19 18:04:43 PathSeparator duration: 39ns, args:
2022/05/19 18:04:43 PathSeparator duration: 41ns, args:
2022/05/19 18:04:43 debug: User
alexandre.fonseca
2022/05/19 18:04:43 User duration: 835ns, args:
2022/05/19 18:04:43 debug: Host
COMP-C02FR0JSML87
2022/05/19 18:04:43 Host duration: 16.562µs, args:
2022/05/19 18:04:43 GOOS duration: 73ns, args:
2022/05/19 18:04:43 TemplateCache duration: 336.561µs, args:
2022/05/19 18:04:43 Flags duration: 77ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 1.921µs, args:
2022/05/19 18:04:43 GOOS duration: 81ns, args:
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 1.362µs, args: SSH_CONNECTION
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 1.126µs, args: SSH_CLIENT
2022/05/19 18:04:43 TemplateCache duration: 82ns, args:
2022/05/19 18:04:43 TemplateCache duration: 296ns, args:
2022/05/19 18:04:43 Shell duration: 227ns, args:
2022/05/19 18:04:43 TemplateCache duration: 186ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 9.699µs, args:
2022/05/19 18:04:43 GOOS duration: 102ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 999ns, args:
2022/05/19 18:04:43 Flags duration: 114ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 956ns, args:
2022/05/19 18:04:43 GOOS duration: 49ns, args:
2022/05/19 18:04:43 GOOS duration: 56ns, args:
2022/05/19 18:04:43 PathSeparator duration: 99ns, args:
2022/05/19 18:04:43 PathSeparator duration: 52ns, args:
2022/05/19 18:04:43 GOOS duration: 53ns, args:
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 1.441µs, args: WSL_DISTRO_NAME
2022/05/19 18:04:43 IsWsl duration: 3.807µs, args:
2022/05/19 18:04:43 StackCount duration: 77ns, args:
2022/05/19 18:04:43 DirIsWritable duration: 14.129µs, args:
2022/05/19 18:04:43 TemplateCache duration: 103ns, args:
2022/05/19 18:04:43 TemplateCache duration: 334ns, args:
2022/05/19 18:04:43 Shell duration: 132ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 1.863µs, args:
2022/05/19 18:04:43 GOOS duration: 67ns, args:
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 1.142µs, args: WSL_DISTRO_NAME
2022/05/19 18:04:43 IsWsl duration: 2.889µs, args:
2022/05/19 18:04:43 GOOS duration: 58ns, args:
2022/05/19 18:04:43 HasCommand duration: 56.153µs, args: git
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 774ns, args:
2022/05/19 18:04:43 error: HasParentFilePath
stat /.git: no such file or directory
2022/05/19 18:04:43 HasParentFilePath duration: 39.836µs, args: .git
2022/05/19 18:04:43 Flags duration: 97ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 1.382µs, args:
2022/05/19 18:04:43 GOOS duration: 63ns, args:
2022/05/19 18:04:43 ErrorCode duration: 67ns, args:
2022/05/19 18:04:43 ErrorCode duration: 60ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 1.389µs, args:
2022/05/19 18:04:43 GOOS duration: 60ns, args:
2022/05/19 18:04:43 ExecutionTime duration: 90ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 1.267µs, args:
2022/05/19 18:04:43 GOOS duration: 50ns, args:
2022/05/19 18:04:43 TemplateCache duration: 87ns, args:
2022/05/19 18:04:43 TemplateCache duration: 260ns, args:
2022/05/19 18:04:43 Shell duration: 311ns, args:
2022/05/19 18:04:43 Flags duration: 105ns, args:
2022/05/19 18:04:43 debug: Pwd
/Users/alexandre.fonseca/.zsh
2022/05/19 18:04:43 Pwd duration: 2.423µs, args:
2022/05/19 18:04:43 GOOS duration: 103ns, args:
2022/05/19 18:04:43 ErrorCode duration: 88ns, args:
2022/05/19 18:04:43 TemplateCache duration: 102ns, args:
2022/05/19 18:04:43 TemplateCache duration: 254ns, args:
2022/05/19 18:04:43 Shell duration: 107ns, args:
2022/05/19 18:04:43 TemplateCache duration: 158ns, args:
2022/05/19 18:04:43 debug: Getenv

2022/05/19 18:04:43 Getenv duration: 1.776µs, args: XDG_CACHE_HOME
2022/05/19 18:04:43 CachePath duration: 20.376µs, args:
2022/05/19 18:04:43 Flags duration: 71ns, args:
```

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung we aligned the behaviour but then seemingly ruined the experience somehow. Should we revert that part, or is there a way to have multiple function bindings on the same key?

**Comment by lewis-yeung** [comment]
It seems that the space inserted is the tricky stuff. Is it possible to get the original bound ZLE widget function and call it after the tooltip part, which may make the two features coexist?

**Comment by lewis-yeung** [comment]
@AlexJF TBH, I'm unable to reproduce neither of the two bugs you described in the screenshots with **OMP v7.85.2**, **zsh v5.8**, **zsh-autosuggestions v0.6.4** and **zsh-history-substring-search v1.0.2**. Any key point?

**Comment by AlexJF** [comment]
I'm not doing any special configurations on my side. I assume you're also calling `enable_poshtooltips`?

Also noticed you don't have https://github.com/zsh-users/zsh-syntax-highlighting in that list. I know that plugin has some weird interactions with at least `substring-search` as it has in its README:

> If you want to use [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) along with this script, then make sure that you load it before you load this script:

So maybe this only manifests when all 3 plugins are used simultaneously? 🤔

**Comment by AlexJF** [comment]
Just tried it with syntax highlighting disabled:

* History substring search still breaks with space.
* Autocompletion is not automatically accepted but I can still see some weird spacing interactions (the completion hint gets an extra space added which disappears with next character typed).

**Comment by lewis-yeung** [comment]
@AlexJF Sorry that I forgot to mention this. I do use zsh-syntax-highlighting (v0.6.0) and follow the README. I'll try the latest version of zsh-syntax-highlighting and see what will happen.

**Comment by lewis-yeung** [comment]
I have tried the latest version of zsh-syntax-highlighting, still cannot reproduce any bug...

I found there is `bck-i-search:` in your screenshots which I don't see on my end when using zsh-history-substring-search. Am I missing something? BTW, I installed zsh-history-substring-search v1.0.2 via Homebrew on WSL2 (Ubuntu-20.04). I don't know if there is an OS-specific fator.

**Comment by lewis-yeung** [comment]
Though I cannot reproduce a bug, I got a simple reimplementation to make the feature compatible with zsh plugins. See #2296.

**Comment by AlexJF** [comment]
> I have tried the latest version of zsh-syntax-highlighting, still cannot reproduce any bug...
> 
> I found there is `bck-i-search:` in your screenshots which I don't see on my end when using zsh-history-substring-search. Am I missing something? BTW, I installed zsh-history-substring-search v1.0.2 via Homebrew on WSL2 (Ubuntu-20.04). I don't know if there is an OS-specific fator.

🤦  I mistakenly thought `history-incremental-search-backward` came from the `zsh-history-substring-search` plugin when it appears it's a core function in ZSH. This bug shows when you have `bindkey '^R' history-incremental-search-backward` and do the following interaction `ctrl-R -> git -> <space>`.

**Comment by lewis-yeung** [comment]
> This bug shows when you have bindkey `'^R' history-incremental-search-backward` and do the following interaction `ctrl-R -> git -> <space>`.

Aha, that makes sense. 😆 Reproduced the second bug.
