### ISSUE TITLE
Conflicting Nu docs

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2293]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

On /docs/installation/prompt:
![image](https://user-images.githubusercontent.com/81652082/169426434-81ccafb6-311d-46e0-bc0b-8ed65b20c48e.png)

On /docs/installation/customize:
![image](https://user-images.githubusercontent.com/81652082/169426461-5b17eb48-34d9-4d07-8886-f9ca9423bf8f.png)

So is Nu < 0.60.0 officially supported or not?

### Theme

N/A

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg no, you need nu >= 0.60.0. I'll fix that lingering statement.
