### ISSUE TITLE
https://ohmyposh.dev/install.ps1 picks wrong installer on 32-bit Windows

### ISSUE THREAD

**Issue by sba923** [JanDeDobbeleer/oh-my-posh#2308]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

On 32-bit Windows, installing via

```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))
```

attempts to install using `install-amd64.exe`, which of course fails.

This is due to `(Get-CimInstance -Class Win32_Processor -Property Architecture).Architecture` returning 9 on 32-bit Windows 10 (both in PowerShell 7.2.4 and in Windows PowerShell 5.1).

**Comment by JanDeDobbeleer** [comment]
@sba923 what's the output of `[Environment]::Is64BitOperatingSystem`?

**Comment by sba923** [comment]
> @sba923 what's the output of `[Environment]::Is64BitOperatingSystem`?

Sorry, machine is (slowly...) installing Windows updates, can't test for now... 

I'll be back.

**Comment by sba923** [comment]
> @sba923 what's the output of `[Environment]::Is64BitOperatingSystem`?

`False`

😜

**Comment by JanDeDobbeleer** [comment]
@sba923 latest update should've fixed this.

**Comment by sba923** [comment]
Indeed.

Great job! **That's** being reactive 😝.
