### ISSUE TITLE
execution time segment(macOS)

### ISSUE THREAD

**Issue by lnu** [JanDeDobbeleer/oh-my-posh#231]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

omp_preexec:1: bad math expression: operator expected at `N/1000000'

### Environment

- Oh my Posh version: latest
- Theme: jandedobbeleer
- Operating System: macOS
- Shell: zsh
- Terminal: term

### Steps to Reproduce

Configure zsh following the doc

**Comment by lnu** [comment]
date in macOS does not support N
https://apple.stackexchange.com/questions/135742/time-in-milliseconds-since-epoch-in-the-terminal

The gdate alternative works but it adds a dependency on coreutils

**Comment by JanDeDobbeleer** [comment]
let me see what we can do 👍🏻
