### ISSUE TITLE
flutter segment add 

### ISSUE THREAD

**Issue by iBelow** [JanDeDobbeleer/oh-my-posh#2310]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Something new and amazing!
Hi, can u add support segment for flutter(most popular dart framework for cross-platform developing) version? 
official site: https://flutter.dev/
**$ flutter --version**
```
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (8 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

```

**Comment by JanDeDobbeleer** [comment]
@iBelow I'm going to add this to the dart segment as they're identical, in this case when dart is active we can also allow the flutter version to be shown.
