### ISSUE TITLE
oh-my-posh wont start in powershell

### ISSUE THREAD

**Issue by ollesson-allard** [JanDeDobbeleer/oh-my-posh#2318]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi,  

i have install oh my posh but when i try to start it by reload by run . $PROFILE in the PowerShell wont reload with new Themes instead i look like this:

 
![image](https://user-images.githubusercontent.com/65387364/169963154-ad47a424-d1d4-4f60-ac5f-f0d0080e41b7.png)

When i check the Windows event log i get this error:

Faulting application name: conhost.exe, version: 10.0.19041.1566, time stamp: 0x56b24be3
Faulting module name: conhost.exe, version: 10.0.19041.1566, time stamp: 0x56b24be3
Exception code: 0xc0000409
Fault offset: 0x000000000001e7ff
Faulting process id: 0x2a04
Faulting application start time: 0x01d86f3718d34fbc
Faulting application path: C:\Windows\system32\conhost.exe
Faulting module path: C:\Windows\system32\conhost.exe
Report Id: 4a0005c9-5d46-44b1-ba7f-d7c5368adb14
Faulting package full name: 
Faulting package-relative application ID: 

### Theme

Im using:

[[JanDeDobbeleer](https://github.com/JanDeDobbeleer)](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/jandedobbeleer.omp.json)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
PS>oh-my-posh debug

Version: 7.90.0

Segments:

ConsoleTitle(true) -   0 ms - powershell in ~
session(true)  -   0 ms -  ollesson 
path(true)     -   0 ms -   ~
git(false)     -  11 ms -
root(false)    -   0 ms -
exit(true)     -   1 ms -   
node(false)    -   0 ms -
go(false)      -   0 ms -
python(false)  -   0 ms -
shell(true)    -   0 ms - in powershell
time(true)     -   0 ms - at 08:27:22

Run duration: 28.9412ms

Cache path: C:\Users\ollesson\AppData\Local\oh-my-posh

Config path: C:\Users\ollesson\AppData\Local\oh-my-posh\config.omp.json

Logs:

2022/05/24 08:27:22 debug: Getenv
C:\Users\ollesson\AppData\Local
2022/05/24 08:27:22 Getenv duration: 0s, args: LOCALAPPDATA
2022/05/24 08:27:22 CachePath duration: 500.1µs, args:
2022/05/24 08:27:22 debug: Getenv
C:\Users\ollesson\AppData\Local\oh-my-posh\config.omp.json
2022/05/24 08:27:22 Getenv duration: 0s, args: POSH_THEME
2022/05/24 08:27:22 Shell duration: 10.7582ms, args:
2022/05/24 08:27:22 resolveConfigPath duration: 10.7582ms, args:
2022/05/24 08:27:22 Init duration: 11.2583ms, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
2022/05/24 08:27:22 config.loadConfig duration: 1.0812ms, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
2022/05/24 08:27:22 debug: Getenv

2022/05/24 08:27:22 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/05/24 08:27:22 Root duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 ErrorCode duration: 0s, args:
2022/05/24 08:27:22 IsWsl duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 debug: User
ollesson
2022/05/24 08:27:22 User duration: 0s, args:
2022/05/24 08:27:22 debug: Host
ALLSUP-5HH94J3
2022/05/24 08:27:22 Host duration: 0s, args:
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 498.6µs, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 debug: Getenv

2022/05/24 08:27:22 Getenv duration: 0s, args: SSH_CONNECTION
2022/05/24 08:27:22 debug: Getenv

2022/05/24 08:27:22 Getenv duration: 0s, args: SSH_CLIENT
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 IsWsl duration: 0s, args:
2022/05/24 08:27:22 StackCount duration: 0s, args:
2022/05/24 08:27:22 DirIsWritable duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 HasCommand duration: 11.0012ms, args: git.exe
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/05/24 08:27:22 HasParentFilePath duration: 0s, args: .git
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 Root duration: 502.3µs, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 ErrorCode duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 debug: HasFiles
false
2022/05/24 08:27:22 HasFiles duration: 0s, args: *.py
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 debug: HasFiles
false
2022/05/24 08:27:22 HasFiles duration: 0s, args: *.ipynb
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 debug: HasFiles
false
2022/05/24 08:27:22 HasFiles duration: 501.4µs, args: pyproject.toml
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 PathSeparator duration: 0s, args:
2022/05/24 08:27:22 debug: HasFiles
false
2022/05/24 08:27:22 HasFiles duration: 0s, args: venv.bak
2022/05/24 08:27:22 debug: HasFolder
false
2022/05/24 08:27:22 HasFolder duration: 0s, args: .venv
2022/05/24 08:27:22 debug: HasFolder
false
2022/05/24 08:27:22 HasFolder duration: 0s, args: venv
2022/05/24 08:27:22 debug: HasFolder
false
2022/05/24 08:27:22 HasFolder duration: 0s, args: virtualenv
2022/05/24 08:27:22 debug: HasFolder
false
2022/05/24 08:27:22 HasFolder duration: 0s, args: env
2022/05/24 08:27:22 debug: HasFolder
false
2022/05/24 08:27:22 HasFolder duration: 0s, args: venv-win
2022/05/24 08:27:22 debug: HasFolder
false
2022/05/24 08:27:22 HasFolder duration: 0s, args: pyenv-win
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 debug: Pwd
C:\Users\ollesson
2022/05/24 08:27:22 Pwd duration: 0s, args:
2022/05/24 08:27:22 debug: Home
C:\Users\ollesson
2022/05/24 08:27:22 GOOS duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 TemplateCache duration: 0s, args:
2022/05/24 08:27:22 Shell duration: 0s, args:
2022/05/24 08:27:22 debug: Getenv
C:\Users\ollesson\AppData\Local
2022/05/24 08:27:22 Getenv duration: 0s, args: LOCALAPPDATA
2022/05/24 08:27:22 CachePath duration: 0s, args:
2022/05/24 08:27:22 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard what's the output of `$error`?

**Comment by ollesson-allard** [comment]
@JanDeDobbeleer When i reload the . $PROFILE i don't get any output $error I only get ps> in new line.

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard so, in your case when you run `echo $error` just after you see the PS prompt, that one is empty?

In that case, can I see your `$PROFILE`?

**Comment by ollesson-allard** [comment]
@JanDeDobbeleer  Thanks now I understand what you mean, if I drive with echo $ error I get:

Invoke-Expression : A positional parameter cannot be found that accepts argument 'System.Collections.ArrayList'.
At line:1 char:89
 ... H_THEMES_PATH/jandedobbeleer.omp.json | Invoke-Expression echo $error
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
 FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

![image](https://user-images.githubusercontent.com/65387364/169982027-bd7e6d60-3247-465c-8e39-6b5ab31b9653.png)


my $PROFILE:
`
oh-my-posh --init --shell pwsh --config $env:POSH_THEMES_PATH/jandedobbeleer.omp.json | Invoke-Expression 
`

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard according to the error message, you added the following to your `$PROFILE`:

```powershell
oh-my-posh --init --shell pwsh --config $env:POSH_THEMES_PATH/jandedobbeleer.omp.json | Invoke-Expression echo $error
```

Could it be you added it there when I asked? Please replace with the following and try again:

```powershell
oh-my-posh --init --shell pwsh --config "$env:POSH_THEMES_PATH/jandedobbeleer.omp.json" | Invoke-Expression
```

**Comment by ollesson-allard** [comment]
> 

I have replace it to:

`oh-my-posh --init --shell pwsh --config "$env:POSH_THEMES_PATH/jandedobbeleer.omp.json" | Invoke-Expression `

Still not working :(

**Comment by ollesson-allard** [comment]
Every time i run . $PROFILE in poweshell i get this i windows event log:

`Faulting application name: conhost.exe, version: 10.0.19041.1566, time stamp: 0x56b24be3
Faulting module name: conhost.exe, version: 10.0.19041.1566, time stamp: 0x56b24be3
Exception code: 0xc0000409
Fault offset: 0x000000000001e7ff
Faulting process id: 0x52bc
Faulting application start time: 0x01d86f4c4bfcb1b2
Faulting application path: C:\Windows\system32\conhost.exe
Faulting module path: C:\Windows\system32\conhost.exe
Report Id: 3530b5ef-221e-4fd4-bc66-fd1aad36714d
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard and starting a new terminal, does that display the prompt correctly? BTW, conhost is what renders the shell.

**Comment by ollesson-allard** [comment]
no, I also restarted the computer to see if it helps it does not. Computer is new and windows is clean images as well. okay so is a problem windows then ?

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard not sure, I can't reproduce this. Can you have a look if `echo $error` now contains something different?

**Comment by ollesson-allard** [comment]
okey, I restart the computer and no error at all. :(  `echo $error` is empty

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard can you paste your entire `$profile` here? Also, what happens when you paste the init line directly in PowerShell? That should at least show something.

**Comment by ollesson-allard** [comment]
my $profiel looke like this:
`
oh-my-posh --init --shell pwsh --config "$env:POSH_THEMES_PATH/jandedobbeleer.omp.json" | Invoke-Expression 
`
I record so you see below:
https://user-images.githubusercontent.com/65387364/170024294-30b75e89-b306-4de8-b54f-d8e481074e1a.mp4

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard to rule out any weird stuff as this is very, very strange, can you try this on PowerShell core?

**Comment by ollesson-allard** [comment]
@JanDeDobbeleer i think is not with my windows image, i try start PowerShell now and i get 
![image](https://user-images.githubusercontent.com/65387364/170026970-3ac4b1c7-121c-4815-b292-17f3c5ea8e3e.png)

I running windows 10 pro Enterprise the should have nothing to do with this. 


Thanks for all the help

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard that's really weird. Are you certain PowerShell works correctly? Because when the init fails, there should at least be something in the `$error` variable, or a visible stack trace in the terminal.

**Comment by ollesson-allard** [comment]
PowerShell is working when i using windows terminal. But if start powershell application that error every time . But i never using PowerShell application alone I always use the windows terminal. I maybe need to reinstall the computer.

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard you can set Terminal as the default terminal in Windows 11. But allow me to check if I can reproduce the issue on that default terminal (although I'm on 11 and conhost might have been updated). Either way, it does feel like an issue with the OS/application stack rather than oh-my-posh).

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard seems like I can't make it fail on conhost in Windows 11

![image](https://user-images.githubusercontent.com/2492783/170051624-8eddaa69-a7ab-4df0-908c-3a1e0af07235.png)

**Comment by cdonnellytx** [comment]
I am seeing a similar issue where the prompt isn't coming up.

I traced it to release 7.85.4 and the addition of a function `Test-PSDebugContext` outside the `New-Module` block in the dynamically generated module.  It looks like the `prompt` function needs that function to stay around but by default doesn't do so, at least on my machine.

Output of `oh-my-posh init pwsh --print`:

- [7.85.3.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8765030/7.85.3.txt)
- [7.85.4.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/8765029/7.85.4.txt)

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx could it be the function needs to declared on top rather than below as that could indeed run the prompt function before that function is available.

**Comment by cdonnellytx** [comment]
@JanDeDobbeleer Yes, that sounds reasonable.  Or it may need to be inside the module code block.

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx inside is an issue as we then can't get that variable value. That's why it got moved out. I'll try to move it, hopefully that changes this behavior.

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx @ollesson-allard can you try with [7.79.1](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v7.91.1)?

**Comment by ollesson-allard** [comment]
@JanDeDobbeleer not working for me :( I will probably upgrade to windows 11 and hope this will solve my problem. 

thanks for any help :)

**Comment by cdonnellytx** [comment]
Installed latest this morning (7.91.2); it is not working for me either.

I did notice that the `$Error` variable stack is growing by 2 each time `prompt` executes, one a `CommandNotFoundException`, the other an `ErrorRecord`, both reporting:

```
The term 'Test-PSDebugContext' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

You don't have another module that exports this function do you? It seems odd that PowerShell Core behavior would differ on Windows 11 vs. 10...

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx can you try 7.91.3?

**Comment by cdonnellytx** [comment]
@JanDeDobbeleer 7.91.3 appears to work.  Thanks!

(I'm on my personal machine right now but was able to confirm 7.91.2 does not work on it, whereas 7.91.3 _does_, so I'm confident that fixed it.)

**Comment by JanDeDobbeleer** [comment]
@ollesson-allard can you also give it a go?

**Comment by ollesson-allard** [comment]
@JanDeDobbeleer reinstall my Computer with windows 11  and thane i fund what cause this it what Cisco AMP for endpoints, and now is all working again :)
