### ISSUE TITLE
Support conditions when setting git fetch_status

### ISSUE THREAD

**Issue by skottmckay** [JanDeDobbeleer/oh-my-posh#2353]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I work on a fairly large git repo that is horribly slow to fetch status on Windows but fine on WSL. I'd like to use the one config for both, but there doesn't seem to be a way to set git fetch_status using something like this:

`"fetch_status": "{{ if .WSL }} true {{else}} false {{end}}",`

**Comment by JanDeDobbeleer** [comment]
@skottmckay that's already possible using [`exclude_folders`](https://ohmyposh.dev/docs/configuration/segment#include--exclude-folders). The path should be different on Windows so you can exclude just that repo's path in your config.

**Comment by skottmckay** [comment]
Does that require two different `git` segments - one with status enabled and one with status disabled? If so would it be better to use `include_folders` so the git segment with status applies to one set of folders, and the git segment without status applies to the other, and I don't end up with places that have 2 git segments being enabled for them?
