### ISSUE TITLE
Powershell model for VScode

### ISSUE THREAD

**Issue by xliuxuan** [JanDeDobbeleer/oh-my-posh#2360]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

At that time, after powershell successfully ran oh my posh, I opened the default powershell terminal in vscode, and an error appeared
I don't know why after it can be used normally on Windows terminal, it will report an error on vscode, obviously it is powershell!
![image](https://user-images.githubusercontent.com/73270222/171427228-4697b198-3990-417c-b0c1-4caaebf0fe26.png)

![image](https://user-images.githubusercontent.com/73270222/171426837-0051fa43-db3b-4b92-b4df-8935ccdb94b7.png)

### Theme

anytheme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
oh-my-posh: C:\Users\liuxuan\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:12:1
Line |
  12 |  oh-my-posh init pwsh --config C:\Users\liuxuan\scoop\apps\oh-my-posh\ …
     |  ~~~~~~~~~~
     | The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by JanDeDobbeleer** [comment]
@xliuxuan please read the message above that states you need to migrate from the module to the binary. There's a migration guide [here](https://ohmyposh.dev/docs/migrating).
