### ISSUE TITLE
404 on "https://ohmyposh.dev/docs/configuration/fonts"

### ISSUE THREAD

**Issue by jon-terry** [JanDeDobbeleer/oh-my-posh#2372]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

404, No active link for Nerd fonts on the Config section of the docs at "[https://ohmyposh.dev/docs/configuration/fonts](https://ohmyposh.dev/docs/configuration/fonts)". Would have sent an email but figured this was faster.

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@trisolix on which page did you see this link?

**Comment by ehawman-rosenberg** [comment]
@JanDeDobbeleer 

![image](https://user-images.githubusercontent.com/81652082/171902055-88ffbf36-caf1-452d-8a8c-ac3ade91cca4.png)

You changed it to /docs/installation/fonts, right?

**Comment by JanDeDobbeleer** [comment]
Yes, I even did a find/replace but somehow not correctly in that case.

**Comment by JanDeDobbeleer** [comment]
@trisolix this is resolved as that link is no longer present in main (and deployed) so maybe you still had a page open that was cached.
