### ISSUE TITLE
Feature Request: Fossil VCS support

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#2373]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Support for [Fossil](https://fossil-scm.org/home/doc/trunk/www/index.wiki) VCS

**Comment by JanDeDobbeleer** [comment]
@toolonely which commands do you run and do you have output for them? I'm not using that myself so need some guidance. The website looks like it's from the 90's 😅

**Comment by ghost** [comment]
@JanDeDobbeleer I'd be happy with a minimalist Fossil segment  that can display at least the current branch name. `fossil branch` lists all branches, the current branch is prefixed with '* '. Example output:

    $ fossil branch
    * trunk
      other

**Comment by JanDeDobbeleer** [comment]
@toolonely it's available. Also added status. Let me know if it works as expected, I'm not a fossil user and I reverse engineered it using the fossil codebase 😅

**Comment by ghost** [comment]
Branch name gets displayed and correctly updated when switching it in a Fossil repository. Tested on Linux. Thank you.
