### ISSUE TITLE
themes.zip only contains json themes

### ISSUE THREAD

**Issue by ehawman-rosenberg** [JanDeDobbeleer/oh-my-posh#2389]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

`themes.zip` doesn't currently include themes saved as `yaml` (and presumably `toml`), which breaks Linux manual installation.

In addition to adding all valid theme files to `themes.zip`, I believe the theme download script on [this page](https://ohmyposh.dev/docs/installation/linux) should be changed to the following.

```bash
mkdir ~/.poshthemes
wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip -O ~/.poshthemes/themes.zip
unzip ~/.poshthemes/themes.zip -d ~/.poshthemes
chmod u+rw ~/.poshthemes/*.json
chmod u+rw ~/.poshthemes/*.yaml
chmod u+rw ~/.poshthemes/*.toml
rm ~/.poshthemes/themes.zip
```

Alternatively, you could just drop the extension requirement and chmod everything inside `.poshthemes`.

### Theme

devious-diamonds.omp.yaml

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash, fish

### Log output

```Shell
N/A
```

**Comment by ehawman-rosenberg** [comment]
`devious-diamonds` doesn't appear in the main Theme list either. I'm assuming this is also a `yaml` thing?

**Comment by JanDeDobbeleer** [comment]
@ehawman-rosenberg correct, I'll see if I can adjust this.
