### ISSUE TITLE
New line with custom theme makes the cursor "ghost" and be displaced.

### ISSUE THREAD

**Issue by francisco-lafe** [JanDeDobbeleer/oh-my-posh#2395]
Hello.

This is a weird error and I don't know if it's OMP or my custom theme (attached). [mytheme.omp.json.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/8835922/mytheme.omp.json.zip)
As you can see, on the same line I have the "cursor" on the beginning of the line, but if I do  SHIFT+ENTER (Newline) the cursor gets displaced by a lot: 
![2022-06-03 - 1020  - powershell](https://user-images.githubusercontent.com/90066435/171959620-b637a670-64ff-41c9-81c2-d58cc62a8c18.gif)
What is going on? 
Windows Powershell:
![image](https://user-images.githubusercontent.com/90066435/171963120-14d24745-2652-421a-8acf-1138ef158711.png)

Thanks.

_Originally posted by @francisco-lafe in https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2379_

**Comment by JanDeDobbeleer** [comment]
@francisco-lafe I couldn't reproduce this with my theme, still need to have a go with yours. In the meantime, make sure to update PSReadLine (or upgrade to Core as 5 is very, very old).

**Comment by francisco-lafe** [comment]
> @francisco-lafe I couldn't reproduce this with my theme, still need to have a go with yours. In the meantime, make sure to update PSReadLine (or upgrade to Core as 5 is very, very old).

Hi, I use PS5 as it's compatible across all our windows 10 machines, but I understand if it's not supported.

**Comment by JanDeDobbeleer** [comment]
@francisco-lafe it is supported (till the point it really breaks). I'll try your theme later this week. Can you validate if PSReadLine is up to date?

**Comment by francisco-lafe** [comment]
Hello @JanDeDobbeleer I've upgraded PSReadLine from v2.0.0 to 
![image](https://user-images.githubusercontent.com/90066435/172440797-0bb14040-5223-42e3-bb6e-76994354321b.png)
And that solved the issue.  

Guides I followed:
https://github.com/PowerShell/PSReadLine#:~:text=If%20you%27ve%20installed%20PSReadLine,of%20PowerShell%20you%20are%20using. 
and  
https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-5.1
(with some help from: https://stackoverflow.com/a/67098816/16873491 )
Thanks for the suggestion.

**Comment by ehawman-rosenberg** [comment]
Look at this guy. Fixes his problem and *documents the steps*? Madlad.

If only more people were like you.

**Comment by francisco-lafe** [comment]
> Look at this guy. Fixes his problem and _documents the steps_? Madlad.
> 
> If only more people were like you.

It only takes me a few more minutes and it helps someone in the future :)
