### ISSUE TITLE
Transient prompt support in bash

### ISSUE THREAD

**Issue by CPCNNT** [JanDeDobbeleer/oh-my-posh#2409]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Is there any possible way to add support of Transient Prompt to bash, specifically bash of Ubuntu 22.04 in WSL2?
I appreciate the marvellous work done by the creator and contributors ❤❤❤.

**Comment by JanDeDobbeleer** [comment]
@CPCNNT I looked into it and it's not possible at the time of writing.
