### ISSUE TITLE
Feature Request: Path style with one folder icon

### ISSUE THREAD

**Issue by disshishkov** [JanDeDobbeleer/oh-my-posh#241]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Add a new enum value to **style** property of the **path** segment, Which will render **folder_icon** only once instead of each icon for each path segment. May be folder icon should be different to understand that it combains a several segments 

### Environment

- Oh my Posh version: 3
- Theme: agnoster
- Operating System: Windows 10
- Shell: PowerShell 7.1
- Terminal: alacritty

### Steps to Reproduce

1. Open terminal 
2. Go to into deep of any folder

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/946095/102217348-82596500-3eed-11eb-9dac-375576f7ef2b.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/946095/102217244-59d16b00-3eed-11eb-8ace-3b405565981d.png)

**Comment by JanDeDobbeleer** [comment]
That's pretty easy, let's add this ;-)
