### ISSUE TITLE
Transient prompt and secondary prompt (continuation prompt) cannot coexist in PowerShell

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2417]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

This happens when the transient prompt is enabled. In a continuation prompt context, the cursor will not move to the next line when I press <kbd>Enter</kbd>, instead it sticks to the current line. Pressing <kbd>Enter</kbd> repeatedly, the transient prompt will move up and up until being out of the upper bound of the terminal screen buffer, which raises an exception: (the following is from `$error[0]`)

```
MethodInvocationException:
Line |
  85 |  …              [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "InvokePrompt" with "0" argument(s): "The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1."
```

![bug](https://user-images.githubusercontent.com/83903009/174320107-def45267-8c56-4dfe-873e-d84da61be408.gif)

This never happens in a PowerShell session without OMP. Having no solution for the time being. Or can we change the implementation of the transient prompt to fix this?

### Theme

(This issue has nothing to do with a specific theme config.)

### What OS are you seeing the problem on?

(This issue has nothing to do with a specific OS.)

### Which shell are you using?

(This issue has nothing to do with a specific shell.)

### Log output

(N/A)

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung ha lol, never seen this before as I never got that many secondary prompts 😓 . Not sure how we can work around this though...

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I got a fix. Just do not repaint the prompt (which is done by calling `InvokePrompt`) when there is a parsing error on the ReadLine buffer. 😄

![bug-fixed](https://user-images.githubusercontent.com/83903009/174574683-c5cd10f6-c4a1-49b9-8279-b79e67af7ce1.gif)

See #2421.
