### ISSUE TITLE
Support 256-color palett or raw ANSI color

### ISSUE THREAD

**Issue by ADIX7** [JanDeDobbeleer/oh-my-posh#2429]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Add support for the 256-color palett or raw ANSI colors. Currently only the 16 color palett is available.

Also, there is a backward compatibility hack in Windows Terminal, so currently white foreground and back background with the 16 color palett does not work as it should be in powershell and pwsh. It does work with the 256 color palett so it would be a great fix for that.

https://github.com/microsoft/terminal/issues/13342#issuecomment-1160894288

**Comment by JanDeDobbeleer** [comment]
We have support for that using hex colors or what do you mean?

**Comment by ADIX7** [comment]
I am trying to create a oh-my-posh config where I only use the 16 base color, so I can change the color settings in the terminal emulators if I want and then I dont have to touch the OMP settings. As you know, I would like to use white foreground on some segments, but Windows Terminal+PWSH, one of the terminal emulator+shell combo I use, has this hack, and because of this my white foreground is not white.

Beside the 16 color palett there is a 256 colro palett. The 16 is part of the 256, so one can reach the same color using the 16 color palett and the 256 palett. The mentiond hack only applies to the 16 color palett, so I could use the 256 color palett to set foreground to white, and that would work.

I don't want to 'hardcode' white with RGB, because, as I said, I would like to set colors in the terminal emulator, and I would like that the terminal emulator settings would be used in OMP. So if I could set someting in the OMP config that will translate to [48;5;0m instead of [37m the my foreground would be the color that is set in the terminal emulator as "white" and it would correctly work in WT+PWSH as well.

I hope I could explain what my goal is 😄

**Comment by JanDeDobbeleer** [comment]
@ADIX7 OK, but the only reason to do this is bypass a bug elsewhere and that's where I draw the line. Coloring is a hard part of this codebase and this basically only adds a workaround. Can I do this? Yes. Is it sensible? IMHO no.

**Comment by ADIX7** [comment]
In my case yes, I could bypass a bug in an other program, but that is just my case. Others might also need the 256 color palett, although as you said, it can be a very rare case.

About the implementation, if a very simple solution could be acceptable by you, you could modify the colors.go source code so after an unsuccessful HEX parsing instead of returning `emptyAnsiColor` you could return the supplied string `colorString` if it matches a regex containing numbers and semicolons, otherwise return emptyAnsiColor. The format would not conflict with the base 16 colors nor with the RGB ones.

**Comment by JanDeDobbeleer** [comment]
~~That could work indeed. You can do a quick PR for that if you wanted to.~~

Moved it to 256 integer support so you can use 0 and 7 in this case. The challenge was mapping it to their respective foreground and background representation when using plain ANSI sequences but this works perfectly out of the box. Thanks for the bright mind and support, I needed that!

**Comment by ADIX7** [comment]
Thank you for this change! And for all the great work you put in to oh-my-posh! This is a well made very useful prompt! My co-workers when they saw my prompt were like "oh my god, so much useful information!". Keep up the good work! 😄
