### ISSUE TITLE
Allow left-side overlap right-side

### ISSUE THREAD

**Issue by RFCreate** [JanDeDobbeleer/oh-my-posh#2442]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I have seen that when you have a terminal too small for all the segments that are in the config, the left-side of the prompt is overlap with the right-side, like this:
![ohmyposh render-right](https://user-images.githubusercontent.com/107062289/175817629-ee2dc0c0-7e27-47c3-a663-f459d2da253f.jpg)

I would like an option to render the left side after the right-side so that the right side gets overlap, like this:
![ohmyposh render-left](https://user-images.githubusercontent.com/107062289/175817682-7c5e6dcd-8201-4e8e-ab74-e592d337e872.jpg)

Something in config like this would be nice:
- renderTime:"0" (to use in the right)
- renderTime:"1" (to use in the left)

And to not break other configs, the default being:
- renderTime:"0" (for the left)
- renderTime:"1" (for the right)

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate not a fan of that, we could however print on the next line if it doesn't fit.

**Comment by RFCreate** [comment]
> we could however print on the next line if it doesn't fit.

@JanDeDobbeleer that was my first option, but since the default behavior is to overlap, I guess that overlapping in the opposite way would be the way to go

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate we already have logic that measures the prompt to decide to display `rprompt` or not, it can be used for this as well.

**Comment by RFCreate** [comment]
@JanDeDobbeleer the problem with `rpromt` is that it renders in the same line as the cursor, so if you have a new line in the config it goes by default to the last line.

Or what kind of logic are you referring to?

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate `rprompt` doesn't render when there's no room. Just like a native `rprompt`.

**Comment by RFCreate** [comment]
@JanDeDobbeleer I know that, you can even type over `rprompt` so the text will be overlapping which is not my favorite thing. Also what I just mention before:
>the problem with `rprompt` is that it renders in the same line as the cursor, so if you have a **new line** in the config it goes by default to the last line.

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate that's a limitation of PowerShell as it doesn't have a native `rprompt`. In fish, cmd and zsh it hides when the text reaches the `rprompt` position.

**Comment by RFCreate** [comment]
@JanDeDobbeleer I get it, so what you propose?

**Comment by RFCreate** [comment]
> the problem with `rprompt` is that it renders in the same line as the cursor, so if you have a **new line** in the config it goes by default to the last line.

See what I am refering with this:
![rprompt omp](https://user-images.githubusercontent.com/107062289/175825917-05a340b5-36f5-49a4-926c-e21148d39a44.jpg)

Both in pwsh and bash when I use `rprompt` the right part goes in the line of the cursor, but without `rprompt` the right part is at the same level as the first line which is what I am looking for.

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate I know. I wasn't suggesting it as an alternative. I tried to explain that the logic for hiding/showing the `rprompt` can be used to move the right aligned prompt in your use-case to the next line.

**Comment by RFCreate** [comment]
@JanDeDobbeleer I just want to make sure we were on the same page. Anything in mind?

**Comment by RFCreate** [comment]
@JanDeDobbeleer Thanks, this is really nice. I thought break will cut the right prompt but it gets a new line. Personally hide is my chosen one. Great job!

**Comment by RFCreate** [comment]
@JanDeDobbeleer the changes work in powershell, but not in bash.

Also, I make a PR for the schema JSON file

Edit: I forgot that I also need to update for WSL, so after update, the changes did work in bash.

**Comment by RFCreate** [comment]
-----
For anyone looking at this issue trying to accomplish this look: (meaning left overlapping right)

![ohmyposh render-left](https://user-images.githubusercontent.com/107062289/175817682-7c5e6dcd-8201-4e8e-ab74-e592d337e872.jpg)

Use this structure in your config file:  *(edit: I doesn't work in pwsh, but it should in other shells)*

### Deprecated in #2480 :
```
"blocks": [
    {
      "alignment": "right",
      "segments": [ ...
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "vertical_offset": -1,
      "segments": [ ...
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [ ...
      ],
      "type": "prompt"
    }
  ]
```

Thanks anyway to @JanDeDobbeleer for implementing the Overflow feature.

**Comment by RFCreate** [comment]
@JanDeDobbeleer if you are seeing this, a little question.

Like in the comment above I was full into bash, so I forgot to test for powershell, now in powershell it does not work. Is this the "problem"?: (literary my right prompt I guess is covered in black)

```
defer func() {
	// Due to a bug in Powershell, the end of the line needs to be cleared.
	// If this doesn't happen, the portion after the prompt gets colored in the background
	// color of the line above the new input line. Clearing the line fixes this,
	// but can hopefully one day be removed when this is resolved natively.
	if e.Env.Shell() == shell.PWSH || e.Env.Shell() == shell.PWSH5 {
		e.writeANSI(e.Ansi.ClearAfter())
	}
}()
```

I look through the source code, and found this [file](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/engine/engine.go#L113-L121)

**Comment by JanDeDobbeleer** [comment]
@shyguyCreate after reviewing the reason for that code, I removed it. Let me know.

**Comment by RFCreate** [comment]
@JanDeDobbeleer yes it works as expected, thanks again.
