### ISSUE TITLE
Git default untracked files mode

### ISSUE THREAD

**Issue by FWest98** [JanDeDobbeleer/oh-my-posh#2454]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

As a followup to #2126, it would be great if I can set a default mode for untracked files, instead of a per-folder setting. (the git config variable does not do anything; since the `-u` parameter is explicitly given in the git segment).

**Comment by JanDeDobbeleer** [comment]
@FWest98 did you notice the latest git release has a native file watcher embedded? Not sure if that addition still makes this relevant.

**Comment by FWest98** [comment]
I did not see that yet, but that's a great addition! However, despite this new addition, I still see a x2 difference between different untracked file modes. (the same applies to my submodules suggestion)

**Comment by JanDeDobbeleer** [comment]
@FWest98 I'll add wildcard support so you can override for everything.
