### ISSUE TITLE
[fish] Tooltips feature interferes with fish abbreviations

### ISSUE THREAD

**Issue by FWest98** [JanDeDobbeleer/oh-my-posh#2469]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Fish allows the user to set [abbreviations](https://fishshell.com/docs/current/cmds/abbr.html), sort-of aliases that auto-expand upon pressing <kbd>Space</kbd> or <kbd>Enter</kbd>. Unfortunately, enabling the oh-my-posh tooltips (that also listen for spaces) seems to steal the keypress from fish itself, so the abbreviation is never auto-expanded (even when the current input does not correspond to a tooltip).

This might well be intentional/inevitable; if it cannot be fixed, it would be nice if it would be mentioned in the documentation.

### Theme

fish 3.5.0; oh-my-posh 8.10.0

### Which shell are you using?

fish

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@FWest98 I was looking at the docs [here](https://fishshell.com/docs/current/cmds/bind.html?highlight=bind) and it seems there's no way to "add" a binding and also keep existing ones, right?

**Comment by FWest98** [comment]
In fact; it is not even possible to have a single keybind combine both shell functions (like a tooltip thing) and these built-in functions I just found out there. So I think it is indeed unfeasible to support both (except when you do funky stuff where you put the expansion on another keybind and trigger that from oh-my-posh, but that sounds quite volatile to me).

So I think it would be nice to add a warning about this in the docs.

**Comment by JanDeDobbeleer** [comment]
@FWest98 actually, I think I can simply add the built in function `expand-abbr` to my binding before executing ours. I'll try that tomorrow!
