### ISSUE TITLE
[poweshell] oh-my-posh debug not working, instead giving me shell.

### ISSUE THREAD

**Issue by yrifl** [JanDeDobbeleer/oh-my-posh#2473]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

While setting up my powershell 7 on windows 10 with oh-my-posh some errors popped up

![Capture](https://user-images.githubusercontent.com/79893882/176986512-abea8f1e-df0e-4d48-9718-9ec510807988.PNG)

Here's my powershell config.

![Capture](https://user-images.githubusercontent.com/79893882/176986562-1331ee0c-99da-47fe-bb0d-5b3d7b167e75.PNG)

I tried using oh-my-posh debug to get the logs but I couldn't. Here's the picture

![image](https://user-images.githubusercontent.com/79893882/176986223-f61b2874-9b75-4d82-8241-bb29dad03978.png)

I think there is nothing wrong with my settings.
I think it's a bug or migrating issues?

### Theme

pwsh

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
I can't
```

**Comment by yrifl** [comment]
im not so sure what's wrong..

**Comment by JanDeDobbeleer** [comment]
@Cyber2f08 did you follow the [guides](https://ohmyposh.dev/docs)? Seems like you mixed up config/theme and shell in the initialisation. For PowerShell, the simplest way to initialise (with the default config/theme) is:

```powershell
oh-my-posh init pwsh | Invoke-Expression
```

Note you need `pwsh` as the shell, and not the config/theme. This will load the [default theme](https://ohmyposh.dev/docs/themes#default) for you.

If you want to replace the theme with [ys](https://ohmyposh.dev/docs/themes#ys), you can either reference the locally installed file if you have a `$env:POSH_THEMES_PATH` folder, or download it to a location you want and reference it directly:

```powershell
oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/ys.omp.json" | Invoke-Expression

# OR

oh-my-posh init pwsh --config "~/ys.omp.json" | Invoke-Expression
```

About ANSI support in PowerShell 7, there's something you [need to read](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2) and maybe adjust before the prompt is displayed correctly.
