### ISSUE TITLE
Repaint only the right prompt for rendering a tooltip and preserve the previous in fish

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2475]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently, if we set a tip of `git` for a `git` segment, and get it rendered as a toolip in fish, after we enter `status` and a space character, the previously rendered tooltip will be overwritten by the original right prompt (or in my case, it will disappear if no right prompt is set), as the screenshots show below:

![tooltip-rendered](https://user-images.githubusercontent.com/83903009/176994345-1478c189-0405-412e-9c3d-395b1552ad64.png)
![tooltip-overwritten](https://user-images.githubusercontent.com/83903009/176994344-2dc62e9a-44a0-480b-ba32-ff4ee815c06d.png)

Actually, not only the right prompt, but the whole is re-rendered in this case. That means the previous contents of all segments will lose, as the screenshots show below:

![before-repainting](https://user-images.githubusercontent.com/83903009/176994137-bd394f56-442a-47ae-a387-b91db74ee510.png)
![after-repainting](https://user-images.githubusercontent.com/83903009/176994135-575b86ce-6435-470b-ad0a-6ddd64437cb2.png)

That's a little unreasonable, isn't it?

Related code:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/2710f796131a5502e4c8c6b63adc6578ba59bd07/src/shell/scripts/omp.fish#L64

I just wonder if it is possible to repaint only the right prompt in fish. Besides, I'd like the previously rendered tooltip to remain when there is no new one.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung that's a limitation of fish as there's no way to repaint the right prompt only (looking at the [docs](https://fishshell.com/docs/current/cmds/bind.html)). So you'll need a feature request there.
