### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ondrejkracmar** [JanDeDobbeleer/oh-my-posh#2488]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Install via Winget from the following Uri https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v8.11.2/install-amd64.exe

### Theme

Defaukt

### What OS are you seeing the problem on?

Windows

### Log output

```Shell
An unexpected error occurred while executing the command:
0x800704c7 : The operation was canceled by the user.

Microsoft Defender block the installation

file: C:\Users\KracmarOndrej\AppData\Local\Temp\WinGet\JanDeDobbeleer.OhMyPosh.8.11.2\e9b692c20253d153f42284f09d79e6cad97d71cea0dca28320e43cd0672507bc

This program is dangerous and executes commands from an attacker. Detect the following Trojan:Win32/Wacatac.B!ml
```

**Comment by JanDeDobbeleer** [comment]
Related to #767, add an exclusion for the time being.
