### ISSUE TITLE
Feature Request: Check path

### ISSUE THREAD

**Issue by yihuajack** [JanDeDobbeleer/oh-my-posh#249]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

A feature of the zsh plugin "zsh-syntax-highlighting" implemented by "_zsh_highlight_main_highlighter_check_path()" function
Add an underline if the filename or path is valid and no underline if invalid.

### Environment

- Oh my Posh version: 3.55.0
- Theme: jandedobbeleer
- Operating System: Windows 10 20H2
- Shell: PowerShell 7.1.0
- Terminal: default / Windows Terminal / Fluent Terminal

### Expected behavior:
Similar to the effects in zsh:
Valid path (underlined):
![image](https://user-images.githubusercontent.com/23608500/102693456-af8f7580-4255-11eb-9904-c51be13a71aa.png)
Or filename (underlined):
![image](https://user-images.githubusercontent.com/23608500/102693479-d77ed900-4255-11eb-93ca-88987fc52606.png)
Invalid path (no effects):
![image](https://user-images.githubusercontent.com/23608500/102693467-c8982680-4255-11eb-8cd9-54a63291826c.png)

**Comment by JanDeDobbeleer** [comment]
@yihuajack that's a feature oh-my-posh can't add as it's only use is to adjust the prompt. Unlike ZSH it's not a shell, so it can't access the commands being entered. To get this behaviour, either use ZSH with oh-my-posh, or create your own validator depending in the shell you're in.
