### ISSUE TITLE
Random theme

### ISSUE THREAD

**Issue by rapha8l** [JanDeDobbeleer/oh-my-posh#2490]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi, 
Thanks for oh my posh.
I thought it could be nice to have a random that picks in existing themes and displays a new one at each new prompt

**Comment by JanDeDobbeleer** [comment]
@rapha8l has been discussed before and decided not to implement that natively, however there's a few examples out there on [how to achieve](https://twitter.com/tim_deschryver/status/1542922096468279297?s=21&t=F33YKgTSHlypoapZ0qCb5A) this.

**Comment by rapha8l** [comment]
thanks !

**Comment by rapha8l** [comment]
here is my take for nu shell : 
`let omp-theme = (ls ~/.config/ohMyPosh/themes |shuffle |get name.1)
let-env PROMPT_COMMAND = { oh-my-posh --config $omp-theme }`

**Comment by rapha8l** [comment]
even better 
 let-env PROMPT_COMMAND = { oh-my-posh --config (ls ~/.config/ohMyPosh/themes |shuffle |get name.1) }

**Comment by ENate** [comment]
I added this line using @rapha8l's idea to randomly select a theme from a files of themes on Ubuntu 22.04 via zsh (oh-my-zsh) 
```eval "$(oh-my-posh init zsh --config (ls ~/.poshthemes |shuffle |get name.1))" ```

and got the following:
```
~/.zshrc:45: bad pattern: (ls ~/.poshthemes |shuffle |get name.1) ```
And ideas? Thanks

**Comment by JanDeDobbeleer** [comment]
@ENate that's because @rapha8l example is written for fish shell. Won't work for zsh.

**Comment by ENate** [comment]
@JanDeDobbeleer I did get something similar for zsh as follows:

```
eval "$(oh-my-posh init zsh --config "$(find ~/oh-my-posh/themes -name '*.omp.json' | shuf -n 1)")"
```
I can add this to the doc if necessary :). This works but may not be optimal. Thanks for the great job you guys did with omp.

**Comment by ENate** [comment]
Hi @JanDeDobbeleer  Is it okay if I add this to the doc and open a pull request?

**Comment by JanDeDobbeleer** [comment]
@ENate if it's a FAQ section, yes!

**Comment by ENate** [comment]
Okay then  :)
