### ISSUE TITLE
Execution Time alignement option

### ISSUE THREAD

**Issue by jycouet** [JanDeDobbeleer/oh-my-posh#2494]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Oh My Posh is so 🦄🦄🦄

I like to have my prompt most of the time keeping the same length.
And I like the Execution Time 😊

Could we imagine leading 0 for ms?
I don't know if it would be an option? Or another format?

Something like:

| format    | 0.000s         | 
| --------- | -------------- | 
| austin    | `000ms`          | 
| roundrock | `00ms`          | 
| dallas    | `0.000`        |
| galveston | `00:00:00`     |
| houston   | `00:00:00.000` | 
| amarillo  | `0.000s`       |
| round     | `000ms`          | 

And adding a `houston_5_9`?
If it fits in 5, say at 5, if not move to 9? 
| format    | 0.001s         | 2.1s         | 3m2.1s        | 4h3m2.1s         |
| --------- | -------------- | ------------ | ------------- | ---------------- |
| houston_5_9 | `00.001` | `02.001` | `00:03:02.001`  | `04:03:02.001`     |

What do you think?

**Comment by JanDeDobbeleer** [comment]
@jycouet what about `galveston`? That does exactly that.

**Comment by jycouet** [comment]
Yeah, but I like `ms` as well.

**Comment by JanDeDobbeleer** [comment]
OK, so if I add that as an option with ms that would be OK, right? Which is better than aligning everything on length as that's really a lot of work ;-)

**Comment by jycouet** [comment]
Yes, with ms having 0 => 000. It would be perfect 👍

**Comment by ehawman** [comment]
What is the basis behind naming time schemes after Texas cities?

**Comment by JanDeDobbeleer** [comment]
@ehawman not sure, didn't come from me. Also never really noticed the city names either 😂

**Comment by jycouet** [comment]
Thx a lot @JanDeDobbeleer 🎨
