### ISSUE TITLE
feat: Withings segment

### ISSUE THREAD

**Issue by rossmeyer1** [JanDeDobbeleer/oh-my-posh#2496]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hey, so I have a [Withings hybrid smart watch](https://www.withings.com/uk/en/steel-hr) and I'd like my latest heart rate data or step count to appear in oh-my-posh, similar to the Nightscout segment.

The Withings API uses OAuth 2.0 for authentication, the same as Strava.

This lead me to thinking whether it would be a good idea to have a generic REST API segment, of sorts. Initially it might only support OAuth 2.0, but could be expanded to support Basic, API key or other types of authentication.

The general idea for this would be that you could simply say here are the things required to keep authentication alive (refresh token, etc), and here is the one value I want to be able to show within the segment itself.

It's probably not worth the headache, as it might result in lots of issues being raised where it doesn't work for X or Y API.

If this is a dumb idea, please close it off, it feels like a bit of a reach.

**Comment by JanDeDobbeleer** [comment]
@GHRoss we already have this for [Strava](https://ohmyposh.dev/docs/segments/strava) AND it's generic so it can be extended. If you point me to the API, I'll gladly make it happen.

**Comment by rossmeyer1** [comment]
Oh wow, thank you!

https://developer.withings.com/

**Comment by JanDeDobbeleer** [comment]
The authentication is functional, now I can proceed to the segment itself.

**Comment by rossmeyer1** [comment]
Niiiice!

These are the values that I would say are most valuable to have in segments, if you're looking for some inspiration!

- Latest heart rate measurement
- Total step count for the day
- Hours of sleep last night

**Comment by JanDeDobbeleer** [comment]
I made some progress on the API, but I still need to make it functional. Somewhere next week I guess.
