### ISSUE TITLE
Replace symbols with unicode

### ISSUE THREAD

**Issue by playday3008** [JanDeDobbeleer/oh-my-posh#2498]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Replace symbols with unicode `\u25cf`

### Theme

https://github.com/JanDeDobbeleer/oh-my-posh/blob/b225c0ad397b840ce64e45975eca9b2d1c1fe2e9/themes/bubbles.omp.json#L122
https://github.com/JanDeDobbeleer/oh-my-posh/blob/b225c0ad397b840ce64e45975eca9b2d1c1fe2e9/themes/bubblesextra.omp.json#L122

### What OS are you seeing the problem on?

Windows, Linux, macOS

### Which shell are you using?

powershell

### Log output

```Shell
Not needed
```

**Comment by JanDeDobbeleer** [comment]
@playday3008 feel free to create a PR. This isn't a bug per se, rather a personal preference (that I agree with).
