### ISSUE TITLE
Expose Git branch name with no decorations

### ISSUE THREAD

**Issue by DJackman123** [JanDeDobbeleer/oh-my-posh#2507]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The .HEAD property for the Git segment has the name of the current branch, but also has a glyph to go with it to show branch status.  This works great for prompt segments, but I want to put the branch name in the console_title_template, and the console title on my machine doesn't allow for rendering these special characters.  I would like to just be able to get the branch name without any decoration icons to display in the console title.

**Comment by JanDeDobbeleer** [comment]
@DJackman123 you can use `{{ .Segments.Git.Ref }}`

**Comment by DJackman123** [comment]
That's great. Thanks.  Please add this to the docs.

**Comment by JanDeDobbeleer** [comment]
@DJackman123 indeed, that property is missing. I'll add it.
