### ISSUE TITLE
Support for OSC7?

### ISSUE THREAD

**Issue by replicaJunction** [JanDeDobbeleer/oh-my-posh#2515]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'm using [Wezterm](https://wezfurlong.org/wezterm) as my terminal emulator. Since it's heavily inspired by Unix-like systems, it doesn't use the OSC9;9 sequence currently supported by Windows Terminal. Instead, it uses [OSC7](https://wezfurlong.org/wezterm/shell-integration.html), which apparently started with the macOS Terminal.

I've been trying to get a regular text template to work for this, but I haven't been successful so far. Here's generally what I'm trying to do:

```json
{
  "template": "\\x1b]7;\"{{ .Path }}\"\\x1b\\",
  "type": "text"
}
```

While I'd personally be happy just getting it working with a text segment (I'm sure I just have the syntax wrong), since oh-my-posh has documented support for other shells and platforms, perhaps it could be extended to support OSC7 in addition to the existing support for OSC9;9?

Alternately, perhaps there could be an easier syntax for providing any generic OSC to the prompt. For example, something like `"template": "{{ .OSC("7") }}"`. This would make it easier for users to support whatever arbitrary codes are supported by their terminal emulator of choice, such as the other [application-specific codes in ConEmu](https://conemu.github.io/en/AnsiEscapeCodes.html#OSC_Operating_system_commands), or [sematic prompt codes](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md) also supported by Wezterm.

**Comment by replicaJunction** [comment]
While I really appreciate the quick turnaround on this, I've been trying it since your fix and it doesn't appear to solve my issue in Wezterm.

There is a snippet on the Wezterm doc I linked above containing a minimal PowerShell prompt with the OSC7 code. I've copied it here:

```pwsh
function prompt {
    $p = $executionContext.SessionState.Path.CurrentLocation
    $osc7 = ""
    if ($p.Provider.Name -eq "FileSystem") {
        $ansi_escape = [char]27
        $provider_path = $p.ProviderPath -Replace "\\", "/"
        $osc7 = "$ansi_escape]7;file://${env:COMPUTERNAME}/${provider_path}${ansi_escape}\"
    }
    "${osc7}PS $p$('>' * ($nestedPromptLevel + 1)) ";
}

```

When I run `pwsh -noprofile` and copy/paste that prompt function, Wezterm works as expected - opening a new tab or split automatically sets the working directory to the same value as the active process.

However, using the new `pwd: osc7` feature does not.

I'm not sure how to troubleshoot this further, since the terminal isn't rendering OSC characters as text. I don't know that I can raise an issue on the Wezterm GitHub since their example works as documented. Maybe the OSC7 code requires the full file:// URL syntax?

Tested using both oh-my-posh 8.16.0 and 8.22.4 and Wezterm 20220624-141144-bd1b7c5d. Here is a minimal config.json that reproduces the issue (expected the OSC7 to work, but it did not):

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "background": "#82aaff",
          "foreground": "#011627",
          "leading_diamond": "<transparent,#82aaff>\ue0b0</>",
          "properties": {
            "folder_icon": "\uf115",
            "folder_separator_icon": " <#011627>\ue0b1</> ",
            "home_icon": "\uf7db ",
            "style": "agnoster"
          },
          "style": "diamond",
          "template": " {{ .Path }} ",
          "trailing_diamond": "\ue0b0",
          "type": "path"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "foreground": "#ffffff",
          "style": "plain",
          "template": "  ",
          "type": "text"
        }
      ],
      "type": "prompt"
    }
  ],
  "pwd": "osc7",
  "version": 2
}

```

Am I still doing something wrong?

_(Edit: fix a copy/paste error in the example JSON.)_

**Comment by JanDeDobbeleer** [comment]
@replicaJunction no, this is a completely custom implementation from that terminal and well, that's not how OSC99 works so I'll have to mimic this specific behaviour in osc7's implementation here. Will fix.

**Comment by JanDeDobbeleer** [comment]
@replicaJunction can you validate?

**Comment by lnu** [comment]
This change introduced an issue(at least on iterm2 on macos):
<img width="561" alt="image" src="https://user-images.githubusercontent.com/1829553/181515640-2132d95e-22dd-47e8-9e6d-2330f2fb2cca.png">
An extra char is added at the beginning of the row

**Comment by JanDeDobbeleer** [comment]
but nothing changed for osc99? I'm also using that setup. What's you config @lnu

**Comment by lnu** [comment]
it happens as soon as I set `"pwd": "osc7",`in the config
I don't use osc99 since iterm2 interprets it differently(pop-up notifications in the notification center)

**Comment by JanDeDobbeleer** [comment]
@lnu well, that's a setting which will only work on Wizterm so it's normal that another terminal can output different stuff.

**Comment by lnu** [comment]
Yes but it also works with iterm. Only the latest change added the glitch at the beginning of the row, otherwise it sets the current directory correctly and I can duplicate a tab and be in the same directory.

**Comment by JanDeDobbeleer** [comment]
@lnu which shell? It seems to be the same syntax `OSC 7 ; [Ps] ST` -> `"\x1b]7;file://%s/%s\x1b\\"`

**Comment by lnu** [comment]
I tried all shells (zsh, pwsh, nu, fish and bash) and all have the same behaviour. Moreover, in bash I have now an extra `]` after the prompt:
<img width="119" alt="image" src="https://user-images.githubusercontent.com/1829553/181687015-ef938397-25c0-4f82-9d8e-b7cf7fc3fb29.png">
bash 3.2.57

**Comment by JanDeDobbeleer** [comment]
@lnu I can indeed reproduce this. Will check.

**Comment by lnu** [comment]
~~I checked and this seems to work:
`a.osc7 = "\x1b]7;\"file://%s/%s\"\x1b\\"` (default shell)
I escaped the `file://`part~~
And for bash, two `\`are missing at the end of the sequence

**Comment by JanDeDobbeleer** [comment]
@lnu I fixed bash and it seems that enclosing everything in `"` fixes the caret, however, that's not specified ANYWHERE.

**Comment by lnu** [comment]
Yes but osc7 is used by iterm2 to set the current directory as osc99 in windows terminal.

**Comment by DeadlySquad13** [comment]
Sorry to bother you in the closed issue but is this feature implemented in latest version (12.10.0) or it's being worked on?
I have the same problem: `"pwd": "osc7"` is set in my config but it doesn't work in wezterm while the minimal snippet from wezterm docs already provided in this issue does.

**Comment by JanDeDobbeleer** [comment]
It should yes.

**Comment by vbalien** [comment]
I fixed the problem that osc7 does not work in powershell.

Add the following to `$PROFILE`.
```powershell
function Set-EnvVar
{
  $p = $executionContext.SessionState.Path.CurrentLocation
  $osc7 = ""
  if ($p.Provider.Name -eq "FileSystem")
  {
    $ansi_escape = [char]27
    $provider_path = $p.ProviderPath -Replace "\\", "/"
    $osc7 = "$ansi_escape]7;file://${env:COMPUTERNAME}/${provider_path}${ansi_escape}\"
  }
  $env:OSC7=$osc7
}
New-Alias -Name 'Set-PoshContext' -Value 'Set-EnvVar' -Scope Global -Force
```

then remove the `"pwd": "osc7"` from the omp.json and add the following as the first element in the segments field.
```json
{
  "type": "text",
  "style": "plain",
  "template": "{{ .Env.OSC7 }}"
},
```
