### ISSUE TITLE
Docs assume PowerShell is running on Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [JanDeDobbeleer/oh-my-posh#252]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Look at the "replace prompt" section:
https://ohmyposh.dev/docs/installation#4-replace-your-existing-prompt

```pwsh
$startInfo.FileName = "C:\tools\oh-my-posh.exe"
$cleanPWD = $PWD.ProviderPath.TrimEnd("\")
$startInfo.Arguments = "-config=""$env:USERPROFILE\.poshthemes\jandedobbeleer.omp.json"" -error=$errorCode -pwd=""$cleanPWD"" -execution-time=$executionTime"
```

There are several assumptions that this is being run on Windows.

When I first ran this on macOS, it silently failed and gave me the `PS>` prompt.

### Environment

- Oh my Posh version: N/A
- Theme: N/A
- Operating System: macOS
- Shell: PowerShell
- Terminal: iTerm2

### Steps to Reproduce

1. Install oh-my-posh3 with homebrew
2. Run script in https://ohmyposh.dev/docs/installation#4-replace-your-existing-prompt

**Expected behavior:** Need a tab for "PowerShell on non-Windows" or something like that

**Actual behavior:** None exists

**Comment by JanDeDobbeleer** [comment]
Yes, that's correct. Unfortunately I can't nest the tabs, however, I can offer the same function the Module has, making this work regardless. Unix style paths work on Windows for Powershell so that shouldn't be an issue. Although it does make me wonder why one wouldn't opt for the model in that case.

**Comment by tradiff** [comment]
@JanDeDobbeleer  just my own experience, when I found this project, I went to [the docs](https://ohmyposh.dev/docs/) and looked for "Installation", which led me [here](https://ohmyposh.dev/docs/installation) and had me do a manual installation. It wasn't until much later that I realized this module can also be installed much more simply from the PowerShell Gallery as described [here](https://ohmyposh.dev/docs/powershell).

Just an idea, maybe the installation docs for PowerShell should steer the user to the `Install-Module` route first.  I'm not sure if that fixes the macOS user story.  To be honest, I've never installed using the PowerShell Gallery :D

**Comment by JanDeDobbeleer** [comment]
@TravisTX a high level info block could do the trick. I'll do the platform agnostic changes and add that for completeness. I get the feeling you're not the only ones.

**Comment by TylerLeonhardt** [comment]
@JanDeDobbeleer something worth considering is doing what [starship does](https://starship.rs/guide/#%F0%9F%9A%80-installation) and bundle the init script into the product so that the scripts are a bit more friendly to look at.

**Comment by JanDeDobbeleer** [comment]
@TylerLeonhardt the first working version is drafted, I'm going to add the other init scripts as well (and probably refactor the hell out of this). Should land somewhere this week.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/2492783/102921592-ec917d00-448c-11eb-9c41-ecc561aab28f.png">
