### ISSUE TITLE
Check if "ctrl + c" / aborted / terminated

### ISSUE THREAD

**Issue by WalterWoshid** [JanDeDobbeleer/oh-my-posh#2523]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Is there a way to check if the program has been terminated and change the default behaviour which is the red "^C"?

**Comment by JanDeDobbeleer** [comment]
@WalterWoshid that's already possible as that results in error code 130 which you use in a template:

```json
"{{ if eq .Code 130 }}SIGINT{{ else if gt .Code 0 }}\uf00d {{ .Meaning }}{{ else }}\uf42e{{ end }}"
```

**Comment by WalterWoshid** [comment]
@JanDeDobbeleer This does not work. I get error code 0. I am using [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) with a powershell instance.

This is my segment:
```json
{
  "template": "{{ if eq .Code 130 }}NICE | {{ end }}Real Code: {{ .Code }} ",
  "style": "powerline",
  "type": "text"
},
```

**Comment by JanDeDobbeleer** [comment]
@WalterWoshid seems like on Windows this doesn't return an exit code. It does on macOS, so I the logic is correct, it just behaves differently. That's a bug for PowerShell.
