### ISSUE TITLE
Prompt hangs on initialization

### ISSUE THREAD

**Issue by aerri** [JanDeDobbeleer/oh-my-posh#2549]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Starting from version v8.19.0, the prompt hangs on the initialization. The same version works fine on the same machine with WSL2 using zsh.

### Theme

blueish

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
If using the blueish theme, the debug has the same behavior. When using, for example, the default theme, it works fine.
```

**Comment by siqueira-gustavo** [comment]
Same problem here.
I mean... in my case, when I updated to v8.20.0 it just stopped working.
I tried my custom and the default theme, but it still doesn't work.
Tried to uninstall it from winget and then install again using scoop and same result.
I noticed that when Powershell freezes the cpu usage is high.
I had to unsintall it to keep using powershell.

**Comment by lewis-yeung** [comment]
Confirmed in v8.20.0. A weird thing: it doesn't happen on all theme configs, for example, it hangs on the preset "atomic" theme while not on my custom one.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung in that case a specific segment is causing issues most probably as nothing structurally changed.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Found the culprit: the `battery` segment. OMP hangs on any theme config containing a `battery` segment. I tested it on a desktop PC for which the `battery` segment is certainly meaningless. I don't know whether this will happen on a laptop or not.

**Comment by runehalfdan** [comment]
I can confirm same issue in both v8.19.0 and v.8.20.0

When commenting out the Battery-segment (right aligned), it works again
(Update: this is on a laptop)

**Comment by JanDeDobbeleer** [comment]
@runehalfdan thx! I know what's causing it and it's only a Windows only issue in that case. Will fix!

EDIT: [this](https://github.com/JanDeDobbeleer/oh-my-posh/commit/2ec6b085fd737ececab0bfce7acea814f944d03f#diff-c265de3a82dbecbd1ba891169a76db809294b5364ff044f579392c45ccc77f23) is the issue

**Comment by JanDeDobbeleer** [comment]
Can you all confirm it's fixed now, seems fixed on my end.

**Comment by siqueira-gustavo** [comment]
Fixed here! Wonderful job. Thanks!

**Comment by aerri** [comment]
It's working! Thank you, guys! You're the best!! haha

**Comment by runehalfdan** [comment]
Is fixed, well done!
