### ISSUE TITLE
Withings segment issue

### ISSUE THREAD

**Issue by rossmeyer1** [JanDeDobbeleer/oh-my-posh#2551]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi Jan, thanks for creating this segment!

I've just tried to put it into my config, but it's not returning anything.

Running debug the only mention of Withings I get is: withings(false)      -  22 ms -

Using the example from the Withings segment docs page.

Not much to go on, but let me know if I can help.

EDIT: Just seen this problem in VS Code. 
![Screenshot 2022-07-20 162721](https://user-images.githubusercontent.com/5963184/180021985-4d1e9b8d-a705-476d-9c72-b21e47798826.png)
Incorrect type. Expected "integer".

### Theme

clean-detailed

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

powershell

### Log output

```Shell
withings(false)      -  22 ms -
```

**Comment by JanDeDobbeleer** [comment]
@GHRoss debug should show what it doing underneath.

**Comment by rossmeyer1** [comment]
It doesn't, it only shows what I've posted?

**Comment by rossmeyer1** [comment]
You were of course correct!

2022/07/20 16:51:58 debug: HTTPRequest
GET /api/refresh?segment=withings&token=redacted HTTP/1.1
Host: ohmyposh.dev
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/07/20 16:51:58 debug: HTTPRequest
GET /api/refresh?segment=withings&token=redacted HTTP/1.1
Host: ohmyposh.dev
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/07/20 16:51:58 debug: HTTPRequest
GET /api/refresh?segment=withings&token=redacted HTTP/1.1
Host: ohmyposh.dev
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/07/20 16:51:58 error: HTTPRequest
Get "https://ohmyposh.dev/api/refresh?segment=withings&token=redacted": context deadline exceeded
2022/07/20 16:51:58 HTTPRequest duration: 20.2058ms, args: https://ohmyposh.dev/api/refresh?segment=withings&token=redacted
2022/07/20 16:51:58 error: HTTPRequest
Get "https://ohmyposh.dev/api/refresh?segment=withings&token=redacted": context deadline exceeded
2022/07/20 16:51:58 HTTPRequest duration: 20.1203ms, args: https://ohmyposh.dev/api/refresh?segment=withings&token=redacted
2022/07/20 16:51:58 error: HTTPRequest
Get "https://ohmyposh.dev/api/refresh?segment=withings&token=redacted": context deadline exceeded
2022/07/20 16:51:58 HTTPRequest duration: 20.1668ms, args: https://ohmyposh.dev/api/refresh?segment=withings&token=redacted

**Comment by rossmeyer1** [comment]
Just to clarify, I can connect to this page using Invoke-WebRequest.

**Comment by JanDeDobbeleer** [comment]
@GHRoss you need to set a different `"http_timeout"` as the requests takes longer than the default 20ms.

**Comment by rossmeyer1** [comment]
I've set this to extremely high values already and it doesn't make a difference.

For what it's worth, http_timeout also says that it's an incorrect type in the config viewed in VS Code...

**Comment by JanDeDobbeleer** [comment]
@GHRoss did you add an int or string?

**Comment by rossmeyer1** [comment]
Int. Generally different variations of 9999.

**Comment by JanDeDobbeleer** [comment]
@GHRoss hmm. I have this at 1500 and it works. I'll check.

**Comment by rossmeyer1** [comment]
To rule out OS, I setup oh-my-posh in Windows too and get the same error.

**Comment by JanDeDobbeleer** [comment]
@GHRoss seems like parallel execution was the issue, removed it as race conditions occur to refresh the token which makes oh-my-posh use the current token.

**Comment by rossmeyer1** [comment]
Still getting the same thing...

2022/07/22 11:18:15 debug: HTTPRequest
GET /api/refresh?segment=withings&token=redacted HTTP/1.1
Host: ohmyposh.dev
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/07/22 11:18:15 error: HTTPRequest
Get "https://ohmyposh.dev/api/refresh?segment=withings&token=redacted": context deadline exceeded
2022/07/22 11:18:15 HTTPRequest duration: 21.0939ms, args: https://ohmyposh.dev/api/refresh?segment=withings&token=redacted
2022/07/22 11:18:15 error: OAuth
no data in cache
2022/07/22 11:18:15 debug: HTTPRequest
GET /api/refresh?segment=withings&token=redacted HTTP/1.1
Host: ohmyposh.dev
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/07/22 11:18:15 error: HTTPRequest
Get "https://ohmyposh.dev/api/refresh?segment=withings&token=redacted": context deadline exceeded
2022/07/22 11:18:15 HTTPRequest duration: 21.1064ms, args: https://ohmyposh.dev/api/refresh?segment=withings&token=redacted
2022/07/22 11:18:15 error: OAuth
no data in cache
2022/07/22 11:18:15 debug: HTTPRequest
GET /api/refresh?segment=withings&token=redacted HTTP/1.1
Host: ohmyposh.dev
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/07/22 11:18:15 error: HTTPRequest
Get "https://ohmyposh.dev/api/refresh?segment=withings&token=redacted": context deadline exceeded
2022/07/22 11:18:15 HTTPRequest duration: 20.1959ms, args: https://ohmyposh.dev/api/refresh?segment=withings&token=redacted

**Comment by JanDeDobbeleer** [comment]
But that's still the default 20ms, can you share your redacted segment?

**Comment by rossmeyer1** [comment]
{
          "type": "withings",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "template": "{{ if gt .Weight 0.0 }} {{ round .Weight 2 }}kg {{ end }}",
          "properties": {
            "access_token": "redacted",
            "refresh_token": "redacted",
            "expires_in": "10800",
            "http_timeout": "1500"
          }
        },

**Comment by JanDeDobbeleer** [comment]
@GHRoss can you remove the quotes from the http_timeout value? That's an integer, and I also fixed the website to reflect that upon authentication.

**Comment by rossmeyer1** [comment]
Still get the same thing.

**Comment by rossmeyer1** [comment]
Ah! It seems to be working now, but some of the values are incorrect?

Steps is yesterday's steps where (I personally) would prefer to know how close I am to my steps goal, so today's current step count would be good.

Sleep hours just shows '0.0'.

withings(true)       -   1 ms -  0.0 4215 88.5882

Above is sleep hours, steps and weight.

**Comment by JanDeDobbeleer** [comment]
@GHRoss can you get me the output of `oh-my-posh debug`?

**Comment by rossmeyer1** [comment]
@JanDeDobbeleer 

action=getactivity&category=1&data_fields=steps&enddateymd=2022-07-22&startdateymd=2022-07-21
2022/07/22 15:48:27 debug: HTTPRequest
{"status":0,"body":{"activities":[{"steps":4215,"deviceid":null,"hash_deviceid":null,"timezone":"Europe\/London","date":"2022-07-21","modified":1658476377,"brand":18,"is_tracker":true},{"steps":922,"deviceid":null,"hash_deviceid":null,"timezone":"Europe\/London","date":"2022-07-22","modified":1658493852,"brand":18,"is_tracker":true}],"more":false,"offset":0}}
2022/07/22 15:48:27 HTTPRequest duration: 225.2839ms, args: https://wbsapi.withings.net/v2/measure
2022/07/22 15:48:27 error: OAuth
no data in cache
2022/07/22 15:48:27 debug: HTTPRequest
POST /measure HTTP/1.1
Host: wbsapi.withings.net
User-Agent: Go-http-client/1.1
Content-Length: 59
Authorization: Bearer REDACTED
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

action=getmeas&category=1&lastupdate=1657291707&meastypes=1
2022/07/22 15:48:27 debug: HTTPRequest
{"status":0,"body":{"updatetime":1658501307,"timezone":"Europe\/London","measuregrps":[{"grpid":3714375707,"attrib":2,"date":1657445883,"created":1657445888,"modified":1657445888,"category":1,"deviceid":null,"hash_deviceid":null,"measures":[{"value":675852,"type":1,"unit":-4,"algo":0,"fm":3}],"comment":null}]}}
2022/07/22 15:48:27 HTTPRequest duration: 114.3405ms, args: https://wbsapi.withings.net/measure
2022/07/22 15:48:27 error: OAuth
no data in cache
2022/07/22 15:48:27 debug: HTTPRequest
POST /v2/sleep HTTP/1.1
Host: wbsapi.withings.net
User-Agent: Go-http-client/1.1
Content-Length: 50
Authorization: Bearer REDACTED
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

action=get&enddate=1658501307&startdate=1655909307
2022/07/22 15:48:27 debug: HTTPRequest
{"status":0,"body":{"series":[{"startdate":REDACTED,"state":0,"enddate":REDACTED,"model":"Activite Steel HR","hash_deviceid":"REDACTED","model_id":55},],"model":16}}
2022/07/22 15:48:27 HTTPRequest duration: 139.1991ms, args: https://wbsapi.withings.net/v2/sleep

There were lots more records for /sleep, but I took them out to more quickly redact stuff. They all looked the same, just for different time periods.

**Comment by JanDeDobbeleer** [comment]
@GHRoss ok, so activities aren't sorted meaning I need to filter today from the results. For sleep, duration is calculated from the dates so if I can get those, that would be ace 👍🏻

**Comment by rossmeyer1** [comment]
{"startdate":1655936880,"state":0,"enddate":1655937000,"model":"redacted","hash_deviceid":"redacted","model_id":redacted}

There's about 200 of these that go throughout the night.

**Comment by JanDeDobbeleer** [comment]
@GHRoss ah, so they're all measures for the same night? Meaning I also need to filter out for that night.

**Comment by rossmeyer1** [comment]
It looks like it, yeah.

**Comment by rossmeyer1** [comment]
Steps are no longer working.

withings(true)       -   0 ms -  7.9 0  88.58kg

Sleep, Steps, weight.

**Comment by JanDeDobbeleer** [comment]
@GHRoss strange as I do fetch the current day steps. Do you have the api output for me?

**Comment by rossmeyer1** [comment]
Looks like the value is in there. 1568 today. Need to go for a walk!!

action=getactivity&category=1&data_fields=steps&enddateymd=2022-07-22&startdateymd=2022-07-21
2022/07/22 21:51:48 debug: HTTPRequest
{"status":0,"body":{"activities":[{"steps":4215,"deviceid":null,"hash_deviceid":null,"timezone":"Europe\/London","date":"2022-07-21","modified":1658476377,"brand":,"is_tracker":true},{"steps":1568,"deviceid":null,"hash_deviceid":null,"timezone":"Europe\/London","date":"2022-07-22","modified":1658519211,"brand":,"is_tracker":true}],"more":false,"offset":0}}
2022/07/22 21:51:48 HTTPRequest duration: 5.1716565s, args: https://wbsapi.withings.net/v2/measure
2022/07/22 21:51:48 error: OAuth
no data in cache
2022/07/22 21:51:48 debug: HTTPRequest
POST /measure HTTP/1.1
Host: wbsapi.withings.net
User-Agent: Go-http-client/1.1
Content-Length: 59
Authorization: Bearer REDACTED
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

**Comment by JanDeDobbeleer** [comment]
@GHRoss the code is correct, there's an issue in the JSON however: `"brand":,`, that field has no value which isn't correct. That error should also be logged in the debug output. And that's for Withings to fix...
