### ISSUE TITLE
The term '49ms not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by tigerinus** [JanDeDobbeleer/oh-my-posh#2562]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

It was working on version `6.33.0`. Then I read from https://ohmyposh.dev/docs/migrating that module installation is no longer supported.

Out of curiosity, I followed the migration steps on the page removed omp, restarted powershell, made sure it's gone, and then ran the installation command manually:

```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))
```

However when I do

```powershell
oh-my-posh.exe init pwsh --config $HOME/.poshthemes/powerline-tiger.omp.json |Invoke-Expression
```

I got flooded with messages like

![image](https://user-images.githubusercontent.com/7172560/180570543-bcffa0ee-534d-4232-ada3-4b7c0a40fb59.png)

### Theme

```json
{
  "final_space": true,
  "osc99": false,
  "console_title": false,
  "console_title_style": "",
  "console_title_template": "",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "horizontal_offset": 0,
      "vertical_offset": 0,
      "segments": [
        {
          "type": "root",
          "style": "plain",
          "powerline_symbol": "",
          "invert_powerline": false,
          "foreground": "#FFEE58",
          "foreground_templates": null,
          "background": "",
          "background_templates": null,
          "leading_diamond": "",
          "trailing_diamond": "",
          "properties": {
            "root_icon": ""
          }
        },
        {
          "type": "python",
          "style": "diamond",
          "invert_powerline": false,
          "foreground": "#ffffff",
          "foreground_templates": null,
          "background": "#5fafd7",
          "background_templates": null,
          "leading_diamond": "",
          "trailing_diamond": "<#5fafd7,#5858ff></>",
          "properties": {
            "prefix": " "
          }
        },
        {
          "type": "path",
          "style": "diamond",
          "powerline_symbol": "",
          "invert_powerline": false,
          "foreground": "#efefef",
          "foreground_templates": null,
          "background": "#5858ff",
          "background_templates": null,
          "leading_diamond": "",
          "trailing_diamond": "<#5858ff,transparent></>",
          "properties": {
            "folder_separator_icon": "  ",
            "home_icon": "🏠",
            "folder_icon": "…",
            "style": "mixed"
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "",
          "invert_powerline": false,
          "foreground": "#ffffff",
          "foreground_templates": null,
          "background": "#800000",
          "background_templates": null,
          "leading_diamond": "",
          "trailing_diamond": "",
          "properties": {
            "prefix": " "
          }
        }
      ]
    }
  ]
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

![image](https://user-images.githubusercontent.com/7172560/180570584-f68c0d31-843b-4166-ba8c-0dc5c12723a0.png)

**Comment by lewis-yeung** [comment]
@tigerinus The command `oh-my-posh.exe debug` did not output what it should. Someone has got the same issue as you recently. See #2542 and [this comment](https://github.com/JanDeDobbeleer/oh-my-posh/issues/2542#issuecomment-1189155008).

BTW, your theme config will be migrated to "version 2" automatically after you initialize it using the latest version of OMP for the first time.

**Comment by tigerinus** [comment]
I'm aware of #2542 but since I have the latest build the comment doesn't really help.

**Comment by lewis-yeung** [comment]
> ![image](https://user-images.githubusercontent.com/7172560/180570584-f68c0d31-843b-4166-ba8c-0dc5c12723a0.png)

For the latest version, `oh-my-posh debug` should output debugging info instead of a prompt.

So `oh-my-posh version` shows `8.22.1` on your end, right? Also, is `oh-my-posh font` (which is not available in older versions) a valid subcommand?

**Comment by tigerinus** [comment]
I think I know what happens - something on `$env:PATH` there is a old version sitting there, and it takes the precedence because of the path ordering.

It'd be nice for installation script to check for existing omp.exe before proceed further.

**Comment by JanDeDobbeleer** [comment]
@tigerinus the installer isn't responsible for removing things outside of its scope. That will only lead to problems.
