### ISSUE TITLE
space betwwen prompts..

### ISSUE THREAD

**Issue by drjkpalli** [JanDeDobbeleer/oh-my-posh#2574]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi,

Is there any way to add space ( an empty line) between prompts. The prompt is getting crowded. please see the image. is there a way to add a blank line between prompts ?

![WindowsTerminal_21K0oHWIWr](https://user-images.githubusercontent.com/67685865/181018015-db0ac53e-b819-4c90-89b4-bbce61f2353d.jpg)

**Comment by JanDeDobbeleer** [comment]
@drjkpalli you can start with a leading newline using the `"newline": true` property on block level. See the [docs](https://ohmyposh.dev/docs/configuration/block#newline) for more information.
