### ISSUE TITLE
Withings Segment Issue

### ISSUE THREAD

**Issue by rossmeyer1** [JanDeDobbeleer/oh-my-posh#2581]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Sorry @JanDeDobbeleer, another one!

I've noticed that weight only shows for today, but weight isn't necessarily recorded everyday like the other data. I manually have to input this, as I don't have their scales, for example, so it would be good to just get the latest **available** weight data, rather than today's weight.

### Theme

clean-detailed

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@GHRoss can you help me with the API output in your case? I only have mine, and probably I need to loop all measurements until I have the right value but want to be certain.

**Comment by CaptnCodr** [comment]
Hello @JanDeDobbeleer, my Withings segment is not working. 
Debug is not showing any logs from the withings api only this line in segments:
`withings(false) -   0 ms -` 

Any ideas?

**Comment by JanDeDobbeleer** [comment]
@CaptnCodr can I get the full logs and the Withings segment config?

**Comment by CaptnCodr** [comment]
Config:
```json

        {
          "type": "withings",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "green",
          "background": "#ffffff",
          "template": "{{ if gt .Weight 0.0 }} {{ round .Weight 2 }} kg {{ end }} {{ .SleepHours }} {{ .Steps }}",
          "properties": {
            "access_token": "redacted",
            "refresh_token": "redacted",
            "expires_in": 10800,
            "http_timeout": 1500
          },
          "leading_diamond": "\ue0b2",
          "trailing_diamond": "\ue0b2"
        },
```
Log:
[omp.log](https://github.com/JanDeDobbeleer/oh-my-posh/files/9359357/omp.log)

**Comment by JanDeDobbeleer** [comment]
@CaptnCodr can you have a look at what's inside the cache? You can get the location using `oh-my-posh cache path` and open the `omp.cache` file. If there's some Withings data, remove the cached responses (not the `access_token` etc.). And try again.

**Comment by CaptnCodr** [comment]
After removing those cached element I ran `oh-my-posh debug` following came out:
```
2022/08/17 14:40:47 error: OAuth
no data in cache
2022/08/17 14:40:47 debug: HTTPRequest
POST /v2/measure HTTP/1.1
Host: wbsapi.withings.net
User-Agent: Go-http-client/1.1
Content-Length: 93
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

action=getactivity&category=1&data_fields=steps&enddateymd=2022-08-17&startdateymd=2022-08-16
2022/08/17 14:40:47 debug: HTTPRequest
{"status":501,"error":"Invalid Session: sessionid missing"}
2022/08/17 14:40:47 HTTPRequest duration: 202.176ms, args: https://wbsapi.withings.net/v2/measure
2022/08/17 14:40:47 error: OAuth
no data in cache
2022/08/17 14:40:47 debug: HTTPRequest
POST /measure HTTP/1.1
Host: wbsapi.withings.net
User-Agent: Go-http-client/1.1
Content-Length: 59
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

action=getmeas&category=1&lastupdate=1659530447&meastypes=1
2022/08/17 14:40:47 debug: HTTPRequest
{"status":503,"body":{},"error":"Invalid Params"}
2022/08/17 14:40:47 HTTPRequest duration: 46.6973ms, args: https://wbsapi.withings.net/measure
2022/08/17 14:40:47 error: OAuth
no data in cache
2022/08/17 14:40:47 debug: HTTPRequest
POST /v2/sleep HTTP/1.1
Host: wbsapi.withings.net
User-Agent: Go-http-client/1.1
Content-Length: 50
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

action=get&enddate=1660737600&startdate=1660683600
2022/08/17 14:40:47 debug: HTTPRequest
{"status":503,"error":"Invalid Params: Missing [access_token]"}
2022/08/17 14:40:47 HTTPRequest duration: 54.9086ms, args: https://wbsapi.withings.net/v2/sleep
```

**Comment by JanDeDobbeleer** [comment]
@CaptnCodr yup, that's a Withings API bug. I also had that a few times during development. Can you remove the entire cache and re-authenticate? That could solve the issue.

**Comment by CaptnCodr** [comment]
I did now, but the access_token in `omp.cache` does not match with my access_token, is this correct?
Re-authentication does not help. Same error messages.

**Comment by JanDeDobbeleer** [comment]
@CaptnCodr yes, that's correct. It will refresh when needed. I also had that during my testing and couldn't find the root cause. Unless I did ruin something lately. Will try when I'm at home (but did validate that).

**Comment by JanDeDobbeleer** [comment]
@lnu could this be the same issue you were trying to fix?

**Comment by lnu** [comment]
Exactly

**Comment by JanDeDobbeleer** [comment]
@CaptnCodr can you try again with the latest? Might need to remove the cache values although it shouldn't.

**Comment by CaptnCodr** [comment]
Yes, I will test this as soon as I can.

**Comment by CaptnCodr** [comment]
That works now. Thank you very much. 🙂

**Comment by CaptnCodr** [comment]
No, not anymore. 
After 2nd refresh the access_token and refresh_token are now missing from the cache.

Edit: Unfortunately, I did a re-authentication and that might have helped.

**Comment by CaptnCodr** [comment]
It seems to work properly after deleting cache and re-authenticating. 🙂

**Comment by JanDeDobbeleer** [comment]
> @GHRoss can you help me with the API output in your case? I only have mine, and probably I need to loop all measurements until I have the right value but want to be certain.

@GHRoss any pointers? Would love to fix this one for you ;-)

**Comment by rossmeyer1** [comment]
@JanDeDobbeleer Sorry for the radio silence, I think this might have solved itself! Also, it's a good reminder to actually measure your weight. I was impacted by the bug that @CaptnCodr raised, but didn't have time to raise it.
