### ISSUE TITLE
Keybindings stop work if the transient prompt is enabled in zsh

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2593]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm sure that <kbd>Home</kbd> and <kbd>End</kbd> work correctly before the transient prompt is enabled in zsh. However once it is enabled, the two keybindings stop work. Tested without other plugins. If I run `zle -N zle-line-init`, which disables the transient prompt, the keybindings will work fine again.

### Theme

(This happens with any theme configs, basically irrelevant.)

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

(N/A)

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung not something specific to oh-my-posh it seems. Can you have a look at this [issue](https://github.com/ohmyzsh/ohmyzsh/issues/3061)?

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Thank you for mentioning that issue. I'm sure that [`_posh-zle-line-init`](https://github.com/JanDeDobbeleer/oh-my-posh/blob/9238f3adbf5da839e391af4542c62f23461eec82/src/shell/scripts/omp.zsh#L67-L92) function has something to do with it, however I don't know how to fix it. Anyway, I can just make the two keys work on my end by binding them via:

```zsh
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
```

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung did some research, can you validate the changes in #2595? I have no end/home keys...

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I have tried your quick fix but the problem persists...
