### ISSUE TITLE
Hide battery segment when no information.

### ISSUE THREAD

**Issue by AjayKMehta** [JanDeDobbeleer/oh-my-posh#26]
First of all, ❤️ this module! Finally switched over from `oh-my-posh` 🙂 

I like your default theme (**jandedobbeleer**) but it shows "BATT ERR" on my desktop because no battery info, of course. IMHO it's better to not display the segment if no info but others may disagree.

To cater for both cases, it would be great if you could optionally specify a condition (scriptblock that returns boolean for example) for each segment in the JSON config that determines if the segment gets displayed or not.

**Comment by JanDeDobbeleer** [comment]
I could add a switch to the properties which would allow this. For example:

```json
"hide_error": true
```

Not sure if I want to make a general switch, I do get where you're coming from but it can get confusing.

What's also an option is to remove the segment from the theme altogether. A quick copy-paste, adjust and setting that as the theme will also hide it forever. Although that might take away its portability.

**Comment by AjayKMehta** [comment]
`hide_error` works.

I get your point about the general switch as it may open a can of worms. I like the idea of being able to dynamically determine visibility of a segment based on condition but embedding PowerShell code in JSON is quite ugly and no point in creating your own DSL for this 😀

**Comment by AjayKMehta** [comment]
@JanDeDobbeleer, one use case for a general switch or config setting for segment visibility is the following:

Say I want to add an 💾 indicator in my prompt to show that `(Get-PSReadLineOption).HistorySaveStyle` is set to `SaveIncrementally` or `SaveAtExit` and remove it if it's not set?

**Comment by JanDeDobbeleer** [comment]
You could achieve that with a custom command segment. That one accepts a shell command (and the shell to run it in, here being powershell) . If the command outputs a value, it will show that value.

**Comment by AjayKMehta** [comment]
I created a theme (`cool.json`) with a command segment as suggested:

https://gist.github.com/AjayKMehta/1b5324a485a9db6e7d326276ab5786cf

The command is specified as `"if ((Get-PSReadLineOption).HistorySaveStyle -ne 'SaveNothing'){'💾'} else {''}"`

It seems to run the command the first time and not work subsequently. Even if I disable saving via `Set-PSReadLineOption -HistorySaveStyle SaveNothing`, I still see 💾 in the prompt.

Any help would be appreciated. Thanks.

**Comment by JanDeDobbeleer** [comment]
It should not save state but run the command every time. I'll check!

**Comment by JanDeDobbeleer** [comment]
I can reproduce this. As this is ran on a new instance of `pwsh`, it will only work IF this is set globally via for example your `$PROFILE`. Let me see if I can make it so it runs directly in your shell (which could break if you don't know what you're doing).

**Comment by AjayKMehta** [comment]
Thanks. That's what I figured as I tried changing the command to `Get-Date` and it worked fine.

**Comment by JanDeDobbeleer** [comment]
Be aware the new version is now known as Oh my Posh V3 :-)

`Install-Module oh-my-posh -Scope CurrentUser -AllowPrerelease`
