### ISSUE TITLE
OhMyPosh breaks when opening Windows Terminal from File Explorer's context menu

### ISSUE THREAD

**Issue by MysticalUser** [JanDeDobbeleer/oh-my-posh#2600]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I click "Open in Windows Terminal Preview" in File Explorer's context menu I get this error:
```
oh-my-posh : The term 'oh-my-posh' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\ffmou\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:4 char:1
+ oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH\jandedobbeleer.o ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (oh-my-posh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Loading personal and system profiles took 992ms.
Text: ""Text: "C:\Users\ffmou\Downloads"Text: "> "
```

The prompt text is broken. `C:\Users\ffmou\Downloads` is the directory I open the terminal from.

### Theme

I'm using JanDeDobbeleer.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Running oh-my-posh debug gives the same error.
```

**Comment by JanDeDobbeleer** [comment]
@MysticalUser it doesn't load the PATH. Bug for Windows Terminal. See [here](https://github.com/microsoft/terminal/issues/10526).

**Comment by flopezre** [comment]
![Greenshot](https://user-images.githubusercontent.com/4932575/211056697-3d512d32-de8c-43ab-96ad-50833d06498f.png)

Hello, i have the same problem.

**Comment by JanDeDobbeleer** [comment]
@flopezre how did you install and did you restart Windows Terminal? Sometimes the inno installer fails to set the PATH, but we can solve that by either running the installer again, or setting it manually.

**Comment by flopezre** [comment]
I fix that, thanks.

**Comment by flopezre** [comment]
Hello me again, how to setting it manually? :c

**Comment by JanDeDobbeleer** [comment]
@flopezre I would run the official installer again and restart your machine afterwards. Can be from the Store or winget, whatever you're more comfortable with. It should add to your PATH.
