### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by lucperkins** [JanDeDobbeleer/oh-my-posh#2602]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I was hoping to add an `oh-my-posh` package to Nixpkgs and was able to successfully get the package to work, but when I checked the repo for a license (a necessary pre-condition for Nixpkgs), there was none to be found :cry: I would strongly recommend specifying one for this project, as is now standard practice in the OSS world.

**Comment by JanDeDobbeleer** [comment]
@lucperkins We do. It's MIT. Check the sidebar here and the [COPYING](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/COPYING) file.
