### ISSUE TITLE
Allow transient prompt to take blocks (or segments) to display insights about the command executed

### ISSUE THREAD

**Issue by CodexLink** [JanDeDobbeleer/oh-my-posh#2605]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello,

I would like to request extending the transient prompt by allowing blocks and segments to be rendered for every command to be executed.

As I understand that the transient prompt intends to display minimal context to allow the command to stand out without obscuring it with the primary prompt, some segments can be used as insight from that certain executed command. A few of the segments that I found useful to display were: execution time, return code, time and date, etc.

With that, if blocks and segments were introduced, I would also like transient prompt properties to be extended rather than limited to `background`, `foreground`, and `template`, but since by extending the functionality of the transient to include block and segment render, I think it is already included in this case.

In the end, with the implication of simplicity with the transient prompt, I think we should allow customization for flexibility.

**Comment by JanDeDobbeleer** [comment]
@CodexLink the transient prompt's template can already get a lot of information available from the standard [templates](https://ohmyposh.dev/docs/configuration/templates#global-properties), moving that to a full prompt is a bit beyond the scope of the transient prompt. This means you have access to the exit code, date/time (through [sprig](http://masterminds.github.io/sprig/date.html)). The only missing piece is execution time which needs to be cached anyways as it's not available/correct when the transient prompt is invoked. That makes things fast, as you don't want to wait on 2 prompts being rendered.

What we can do, and I think this is the best solution, is cache all the template properties (including segment data) and use those for all non-primary prompts. That way, you will have the same context lightning fast.

**Comment by CodexLink** [comment]
Forgot to reply, wouldn't it be best to select specific segments to be cached rather than caching everything? I can see that _some_ themes have a lot of segments on them and I'm not quite sure if there would be a performance impact in the first place. The scenario (that I can think of) from where the impact may be seen is on initialization.

Also, in relation to caching segments and using them for non-primary, I'm curious about how these segments will be declared because some segments can be or should be available on both primary and non-primary. (For instance, date and time segment being available for both transient and the primary prompt) And if that's the case, I think there should be a place where these segments are dedicated to being reusable and available to be (selectively) cached for all prompts rather than being exclusively only at certain prompts such as transient prompt.

With the focus of this issue/feature request allowing segments to be rendered on non-primary (ie. transient prompt), the paragraph above also states the potential flexibility of segments between prompts, promoting DRY principles for theme creation.

**Comment by JanDeDobbeleer** [comment]
@CodexLink the impact is zero, I have a working implementation. Time/date can be referenced directly using template functions so no issue there. The segments are referenced using the cross segment template property [syntax](https://ohmyposh.dev/docs/configuration/templates#cross-segment-template-properties), meaning you'll have access to everything that was rendered before and the global [properties](https://ohmyposh.dev/docs/configuration/templates#global-properties).

You could trust me on this one that you'll have exactly what you're looking for as your real use-case is limited, yet the implementation allows for everything. An extra prompt is what it is, it's additional within the same context.

**Comment by CodexLink** [comment]
Okay, I understood, thank you very much for taking the time on this one. Appreciated it. 💯
