### ISSUE TITLE
Bug in windows installation oh-my-posh

### ISSUE THREAD

**Issue by wenbingkun** [JanDeDobbeleer/oh-my-posh#2606]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi, I already mentioned the bug to you a few days ago, and now I found the cause of the problem！
The bug occurs when the user folder of windows is named in Chinese！
The correct path should be C:\Users\文炳坤\AppData\Local\Progrmas\oh-my-posh\bin\oh-my-posh.exe
But the wrong path is shown in the figure below
![oh-my-posh](https://user-images.githubusercontent.com/49178619/182320904-f0d64dfb-9d34-42cb-82c6-302c90601a9d.png)

### Theme

Default theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
The bug is shown in the picture above
```

**Comment by JanDeDobbeleer** [comment]
@wenbingkun I know, and that's because PowerShell and UTF-8 is real pain. To fix that, please init oh-my-posh in UTF-8, we have to do the same in other places ourselves as well. One day they will fix this....

```powershell
$previousOutputEncoding = [Console]::OutputEncoding
try {
    [Console]::OutputEncoding = [Text.Encoding]::UTF8
    oh-my-posh init pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression
} finally {
    [Console]::OutputEncoding = $previousOutputEncoding
}
```
