### ISSUE TITLE
The command prompt does not render well on Konsole and VS Code terminal

### ISSUE THREAD

**Issue by David7ce** [JanDeDobbeleer/oh-my-posh#2609]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The command prompt does not render well in some of my apps,
- In VSCOde looks like this:
![Screenshot_20220803_212906](https://user-images.githubusercontent.com/79609649/182706674-1d10ddcb-f745-4321-a822-2c84be5f2195.png)
- In Konsole looks like this:
![Screenshot_20220803_213005](https://user-images.githubusercontent.com/79609649/182706678-64439244-257c-41f2-84b0-f25429939cf9.png)

However in other terminal emulators like Kitty or Alacritty it looks good:
![Screenshot_20220803_214023](https://user-images.githubusercontent.com/79609649/182707364-124427c8-9119-4257-a24e-53405c081fc4.png)

I'm on Arch Linux using KDE plasma.

### Theme

Default theme

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
There no log output the bug is when rendering command prompt.
```

**Comment by JanDeDobbeleer** [comment]
@David7ce this is a terminal issue (or font setting in the terminal) and not something oh-my-posh can solve. You can try playing with a different font size, settings to resolve that, but that's unfortunately outside of the scope of oh-my-posh.

**Comment by amedee** [comment]
I also struggled with this issue for about two minutes, until I went back to the installation manual _and actually read it_:

> To see the icons displayed in Oh My Posh, install a [Nerd Font](https://www.nerdfonts.com/), **and configure your terminal to use it**.

(emphasis added)

This is where you do it in GNOME Terminal:
![image](https://user-images.githubusercontent.com/463961/203171225-cfc5cbb6-3854-45d2-b155-950b65190b8b.png)

I hope this helps @David7ce, or anyone else who ends up on this page through a Google search.
