### ISSUE TITLE
When I am in the home directory, I want my prompt to show "~"

### ISSUE THREAD

**Issue by just1a-person** [JanDeDobbeleer/oh-my-posh#261]
When I am in the home directory, I want my prompt to show "~"

But when I am not, I don't want it to show the full path. Just the current directory name.

/cc @JanDeDobbeleer

_Originally posted by @itsme-alan in https://github.com/JanDeDobbeleer/oh-my-posh3/discussions/258_

**Comment by just1a-person** [comment]
@JanDeDobbeleer When will this be released?

**Comment by JanDeDobbeleer** [comment]
@itsme-alan it's available. Everything flows automatically after a merge 😉
