### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tradiff** [JanDeDobbeleer/oh-my-posh#262]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I'm probably just missing something obvious, but after a recent change, I can no longer build the main branch.  I get the error:
```
.\main.go:184:15: undefined: Asset
```

### Environment

Tried it on two environments:
- Operating System: Windows 10 
- go version go1.15.5 windows/amd64   

and:
- Operating System: Ubuntu 20.04.1 LTS
- go version go1.13.8 linux/amd64

### Steps to Reproduce

```
❯ git clone https://github.com/JanDeDobbeleer/oh-my-posh3.git omp3-b
Cloning into 'omp3-b'...
remote: Enumerating objects: 523, done.
remote: Counting objects: 100% (523/523), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 6666 (delta 260), reused 436 (delta 201), pack-reused 6143
Receiving objects: 100% (6666/6666), 4.01 MiB | 8.93 MiB/s, done.
Resolving deltas: 100% (3849/3849), done.

❯ cd omp3-b

❯ go install
# github.com/jandedobbeleer/oh-my-posh3
.\main.go:184:15: undefined: Asset

❯ go build
# github.com/jandedobbeleer/oh-my-posh3
.\main.go:184:15: undefined: Asset
```

**Comment by JanDeDobbeleer** [comment]
Yes, you need to do something additional. I added it to the [contributing guide](https://ohmyposh.dev/docs/contributing_segment), but I get it can be weird when that happens all of a sudden 😅

Before building, make sure to pack the init scripts:

```shell
go get -u github.com/kevinburke/go-bindata/...
go-bindata -o init.go init/
```

You only need to do this again when changing the contents in `/init`. The output file is ignored.
