### ISSUE TITLE
(🐞) light/dark theme on the website defaults to light and doesn't match operating system settings

### ISSUE THREAD

**Issue by KotlinIsland** [JanDeDobbeleer/oh-my-posh#2621]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug (🐞) happened! (see title of issue)

### Theme

Dark theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@KotlinIsland that's a bug for [docusaurus](https://github.com/facebook/docusaurus/issues) as that functionality is baked in there.

**Comment by KotlinIsland** [comment]
I think it's available in the next version. https://github.com/facebook/docusaurus/pull/7200
