### ISSUE TITLE
New Theme - simple

### ISSUE THREAD

**Issue by carlosvsilva** [JanDeDobbeleer/oh-my-posh#2622]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

See my new theme, based on sonicboom-light, feel free to publish on oh-my-posh project.

Screenshot attached.
![image](https://user-images.githubusercontent.com/40889421/183263959-e663f3b5-078d-4c4a-aa9a-1f6014c5d643.png)

{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "#000000",
          "foreground": "#dd1e1e",
          "style": "plain",
          "template": " \u26a1",
          "type": "root"
        },
        {
          "background": "#000000",
          "foreground": "#ffffff",
          "properties": {
            "alpine": "\uf300",
            "arch": "\uf303",
            "centos": "\uf304",
            "debian": "\uf306",
            "elementary": "\uf309",
            "fedora": "\uf30a",
            "gentoo": "\uf30d",
            "linux": "\ue712",
            "macos": "\ue711",
            "manjaro": "\uf312",
            "mint": "\uf30f",
            "opensuse": "\uf314",
            "raspbian": "\uf315",
            "ubuntu": "\uf31c",
            "windows": "\ue62a",
            "wsl": "\ue712"
          },
          "style": "plain",
          "template": " {{ if .WSL }}WSL at {{ end }}{{.Icon}} ",
          "type": "os"
        },
        {
          "background": "#4d4d4d",
          "foreground": "#26E5FF",
          "properties": {
            "folder_icon": "\ue5fe",
            "folder_separator_icon": "<transparent> \ue0bd </>",
            "home_icon": "\uf7db",
            "style": "agnoster_short"
          },
          "style": "plain",
          "template": " {{ .Path }} ",
          "type": "path"
        },
        {
          "background": "#4d4d4d",
          "foreground": "#00ff0d",
          "properties": {
            "fetch_stash_count": true,
            "fetch_status": true
          },
          "style": "plain",
          "template": "<#000000>\ue0b1 </>{{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00> \uf046 {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} ",
          "type": "git"
        },
        {
          "background": "#4D9C3E",
		  "background_templates": [
			"{{ if gt .Code 0 }}#9C3E4B{{ end }}"
		  ],
          "foreground": "#ffffff",
		  "style": "plain",
          "properties": {
           "always_enabled": true
          }, 
          "template": "<parentBackground,background,transparent>\ue0b0</> {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} ",
          "type": "exit"
        },
        {
            "type": "text",
            "style": "plain",
            "template": "<parentBackground,transparent>\ue0b0</>"
        }
      ],
      "type": "prompt"
    },
    {
      "alignment": "right",
      "segments": [
        {
          "background": "#4d4d4d",
          "foreground": "#43CCEA",
          "leading_diamond": "\ue0c5",
          "style": "diamond",
          "template": " {{ if .SSHSession }}\uf817 {{ end }}{{ .UserName }}<transparent> / </>{{ .HostName }}",
          "type": "session"
        },
        {
          "background": "#4d4d4d",
          "foreground": "#43CCEA",
          "properties": {
            "time_format": "3:04:05 PM"
          },
          "style": "diamond",
          "template": "<#000000> \ue31e\uf0fb </>{{ .CurrentDate | date .Format }} ",
          "trailing_diamond": "\ue0c5",
          "type": "time"
        }
      ],
      "type": "rprompt"
    }
  ],
  "final_space": true,
  "version": 2
}

**Comment by JanDeDobbeleer** [comment]
@carlosvsilva feel free to create a pull request 😉
