### ISSUE TITLE
Sometime in the last few updates, oh-my-posh stopped working on my system

### ISSUE THREAD

**Issue by scottmc42** [JanDeDobbeleer/oh-my-posh#2636]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Installed and upgraded through `brew` on a Macbook M1, bash shell. Some time in the last few updates (I can't know for sure as it seems like there is a new change every day), OMP stopped displaying correctly.

I was using a custom theme, but have also tried a few of the pre-built themes; carver, dracula, gruvbox.

None of them display correctly. It's like it tries printing out the whole prompt but keeps getting a carriage return and goes back to the beginning of the prompt and overwrites itself.

I have tried doing a `brew reinstall` as well as a complete uninstall and reinstall.

My .bash_profile contains the following to initialize:
`eval "$(oh-my-posh init bash --config ~/.posh-themes/myTheme.omp.json)"`

### Theme

I was using a custom theme, but have also tried a few of the pre-built themes; carver, dracula, gruvbox.

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
Version: 8.29.0

Segments:

ConsoleTitle(false) -   0 ms -
session(true)  -   0 ms - scott
path(true)     -   0 ms -  ~
git(false)     -   0 ms -
python(false)  -   0 ms -
time(true)     -   0 ms -  00:16:36 

Run duration: 2.66175ms

Cache path: /Users/scott

Config path: /Users/scott/.posh-themes/myTheme.omp.json

Logs:

2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 4.375µs, args: XDG_CACHE_HOME
2022/08/09 00:16:36 CachePath duration: 13.75µs, args:
2022/08/09 00:16:36 debug: Getenv
/Users/scott/.posh-themes/myTheme.omp.json
2022/08/09 00:16:36 Getenv duration: 2.667µs, args: POSH_THEME
2022/08/09 00:16:36 resolveConfigPath duration: 5.292µs, args:
2022/08/09 00:16:36 Init duration: 1.681708ms, args:
2022/08/09 00:16:36 Flags duration: 41ns, args:
2022/08/09 00:16:36 config.loadConfig duration: 208.291µs, args:
2022/08/09 00:16:36 Flags duration: 0s, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 791ns, args: OMP_CACHE_DISABLED
2022/08/09 00:16:36 Root duration: 416ns, args:
2022/08/09 00:16:36 Shell duration: 57.208µs, args:
2022/08/09 00:16:36 ErrorCode duration: 84ns, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 584ns, args: WSL_DISTRO_NAME
2022/08/09 00:16:36 IsWsl duration: 1.333µs, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 6.625µs, args:
2022/08/09 00:16:36 PathSeparator duration: 167ns, args:
2022/08/09 00:16:36 PathSeparator duration: 0s, args:
2022/08/09 00:16:36 debug: User
scott
2022/08/09 00:16:36 User duration: 625ns, args:
2022/08/09 00:16:36 debug: Host
Scotts-MacBook-Pro
2022/08/09 00:16:36 Host duration: 3.583µs, args:
2022/08/09 00:16:36 GOOS duration: 0s, args:
2022/08/09 00:16:36 TemplateCache duration: 87.125µs, args:
2022/08/09 00:16:36 Flags duration: 0s, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 459ns, args:
2022/08/09 00:16:36 GOOS duration: 42ns, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 500ns, args: SSH_CONNECTION
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 22.834µs, args: SSH_CLIENT
2022/08/09 00:16:36 TemplateCache duration: 0s, args:
2022/08/09 00:16:36 TemplateCache duration: 42ns, args:
2022/08/09 00:16:36 Shell duration: 41ns, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 541ns, args:
2022/08/09 00:16:36 GOOS duration: 41ns, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 333ns, args:
2022/08/09 00:16:36 Flags duration: 42ns, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 334ns, args:
2022/08/09 00:16:36 GOOS duration: 42ns, args:
2022/08/09 00:16:36 GOOS duration: 41ns, args:
2022/08/09 00:16:36 PathSeparator duration: 0s, args:
2022/08/09 00:16:36 PathSeparator duration: 42ns, args:
2022/08/09 00:16:36 GOOS duration: 42ns, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 2.291µs, args: WSL_DISTRO_NAME
2022/08/09 00:16:36 IsWsl duration: 3.042µs, args:
2022/08/09 00:16:36 StackCount duration: 0s, args:
2022/08/09 00:16:36 DirIsWritable duration: 3.083µs, args:
2022/08/09 00:16:36 TemplateCache duration: 42ns, args:
2022/08/09 00:16:36 TemplateCache duration: 42ns, args:
2022/08/09 00:16:36 Shell duration: 42ns, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 458ns, args:
2022/08/09 00:16:36 GOOS duration: 42ns, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 458ns, args: WSL_DISTRO_NAME
2022/08/09 00:16:36 IsWsl duration: 1.167µs, args:
2022/08/09 00:16:36 GOOS duration: 0s, args:
2022/08/09 00:16:36 debug: CommandPath
/opt/homebrew/bin/git
2022/08/09 00:16:36 CommandPath duration: 11.834µs, args: git
2022/08/09 00:16:36 HasCommand duration: 12.667µs, args: git
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 375ns, args:
2022/08/09 00:16:36 error: HasParentFilePath
stat /.git: no such file or directory
2022/08/09 00:16:36 HasParentFilePath duration: 5.375µs, args: .git
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 375ns, args:
2022/08/09 00:16:36 GOOS duration: 0s, args:
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 333ns, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 417ns, args: VIRTUAL_ENV
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 416ns, args: CONDA_ENV_PATH
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 416ns, args: CONDA_DEFAULT_ENV
2022/08/09 00:16:36 debug: Pwd
/Users/scott
2022/08/09 00:16:36 Pwd duration: 375ns, args:
2022/08/09 00:16:36 GOOS duration: 0s, args:
2022/08/09 00:16:36 TemplateCache duration: 42ns, args:
2022/08/09 00:16:36 TemplateCache duration: 42ns, args:
2022/08/09 00:16:36 Shell duration: 42ns, args:
2022/08/09 00:16:36 debug: Getenv

2022/08/09 00:16:36 Getenv duration: 500ns, args: XDG_CACHE_HOME
2022/08/09 00:16:36 CachePath duration: 3.042µs, args:
2022/08/09 00:16:36 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@cyberfunkr I'm on the same Mac (hardware wise) and can't reproduce this. I'll need more information if I want to find the cause. If you have more than just oh-my-posh in your `.bashrc`, could you comment out everything else to see if it's really oh-my-posh and not something else?

**Comment by scottmc42** [comment]
Commented out everything except initializing brew and OMP and. still see the same problem.

**Comment by JanDeDobbeleer** [comment]
@cyberfunkr I'm on the latest now, and I honestly can't reproduce this on the latest bash. So, next question, is bash up-to-date?

**Comment by scottmc42** [comment]
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Which is the latest Mac goes normally

**Comment by JanDeDobbeleer** [comment]
That’s really old, so please update bash using homebrew (or any preferred method). We’re definitely not supporting that one anymore.

**Comment by oalders** [comment]
I'm seeing something similar. 

<img width="219" alt="Screen Shot 2022-08-09 at 15 13 08" src="https://user-images.githubusercontent.com/96205/183742273-ef2b44a1-5e0d-4b05-88ef-794f355a06c8.png">

<img width="690" alt="Screen Shot 2022-08-09 at 15 14 13" src="https://user-images.githubusercontent.com/96205/183742452-492f8e68-592a-4e3b-b934-76c7c71da3c2.png">

<img width="410" alt="Screen Shot 2022-08-09 at 15 15 35" src="https://user-images.githubusercontent.com/96205/183742692-b59e8b4d-0878-402b-9069-07a2b93d91f2.png">

Apologies for the escape codes. Not sure what's going on there.

---

[1mVersion:[0m 8.29.3

[1mSegments:[0m

ConsoleTitle(false)  -   0 ms - 
os(true)             -   0 ms - [48;2;76;86;106m[38;2;136;192;208m  [0m
path(true)           -   0 ms - [48;2;95;129;157m[38;2;76;86;106m[0m[48;2;95;129;157m[38;2;25;53;73m   cpm [0m
git(true)            -  36 ms - [48;2;94;141;135m[38;2;95;129;157m[0m[48;2;94;141;135m[38;2;235;203;139m main  ≡  ?2 [0m
root(false)          -   0 ms - 
executiontime(true)  -   0 ms - [38;2;94;141;135m[0m[38;2;131;118;156;49m[7m[0m[48;2;131;118;156m[38;2;25;53;73m 羽0ms⠀[0m
exit(true)           -   0 ms - [48;2;138;190;183m[38;2;131;118;156m[0m[48;2;138;190;183m[38;2;25;53;73m ♥ [0m[38;2;138;190;183m[0m

[1mRun duration:[0m 54.389685ms

[1mCache path:[0m /Users/olaf/.cache/oh-my-posh

[1mConfig path:[0m /Users/olaf/.config/oh-my-posh/themes/local.omp.json

[1mLogs:[0m

2022/08/09 15:17:54 debug: Getenv

2022/08/09 15:17:54 Getenv duration: 10.613µs, args: XDG_CACHE_HOME
2022/08/09 15:17:54 CachePath duration: 58.067µs, args: 
2022/08/09 15:17:54 debug: Getenv
/Users/olaf/.config/oh-my-posh/themes/local.omp.json
2022/08/09 15:17:54 Getenv duration: 10.145µs, args: POSH_THEME
2022/08/09 15:17:54 resolveConfigPath duration: 15.59µs, args: 
2022/08/09 15:17:54 Init duration: 14.815751ms, args: 
2022/08/09 15:17:54 Flags duration: 57ns, args: 
2022/08/09 15:17:54 config.loadConfig duration: 790.783µs, args: 
2022/08/09 15:17:54 Flags duration: 72ns, args: 
2022/08/09 15:17:54 debug: Getenv

2022/08/09 15:17:54 Getenv duration: 2.263µs, args: OMP_CACHE_DISABLED
2022/08/09 15:17:54 Root duration: 935ns, args: 
2022/08/09 15:17:54 Shell duration: 102.008µs, args: 
2022/08/09 15:17:54 ErrorCode duration: 144ns, args: 
2022/08/09 15:17:54 debug: Getenv

2022/08/09 15:17:54 Getenv duration: 1.282µs, args: WSL_DISTRO_NAME
2022/08/09 15:17:54 IsWsl duration: 2.853µs, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 22.8µs, args: 
2022/08/09 15:17:54 PathSeparator duration: 79ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 40ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 38ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 38ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 40ns, args: 
2022/08/09 15:17:54 debug: User
olaf
2022/08/09 15:17:54 User duration: 945ns, args: 
2022/08/09 15:17:54 debug: Host
imac
2022/08/09 15:17:54 Host duration: 7.614µs, args: 
2022/08/09 15:17:54 GOOS duration: 64ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 180.407µs, args: 
2022/08/09 15:17:54 Flags duration: 76ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 3.369µs, args: 
2022/08/09 15:17:54 GOOS duration: 65ns, args: 
2022/08/09 15:17:54 GOOS duration: 60ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 77ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 134ns, args: 
2022/08/09 15:17:54 Shell duration: 95ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 1.294µs, args: 
2022/08/09 15:17:54 GOOS duration: 68ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 838ns, args: 
2022/08/09 15:17:54 Flags duration: 66ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 643ns, args: 
2022/08/09 15:17:54 GOOS duration: 39ns, args: 
2022/08/09 15:17:54 GOOS duration: 41ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 82ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 39ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 40ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 39ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 38ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 40ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 38ns, args: 
2022/08/09 15:17:54 GOOS duration: 41ns, args: 
2022/08/09 15:17:54 debug: Getenv

2022/08/09 15:17:54 Getenv duration: 909ns, args: WSL_DISTRO_NAME
2022/08/09 15:17:54 IsWsl duration: 2.353µs, args: 
2022/08/09 15:17:54 StackCount duration: 61ns, args: 
2022/08/09 15:17:54 DirIsWritable duration: 11.111µs, args: 
2022/08/09 15:17:54 TemplateCache duration: 51ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 178ns, args: 
2022/08/09 15:17:54 Shell duration: 166ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 1.3µs, args: 
2022/08/09 15:17:54 GOOS duration: 68ns, args: 
2022/08/09 15:17:54 debug: Getenv

2022/08/09 15:17:54 Getenv duration: 982ns, args: WSL_DISTRO_NAME
2022/08/09 15:17:54 IsWsl duration: 2.516µs, args: 
2022/08/09 15:17:54 GOOS duration: 44ns, args: 
2022/08/09 15:17:54 debug: CommandPath
/usr/local/bin/git
2022/08/09 15:17:54 CommandPath duration: 100.701µs, args: git
2022/08/09 15:17:54 HasCommand duration: 102.569µs, args: git
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 775ns, args: 
2022/08/09 15:17:54 HasParentFilePath duration: 6.599µs, args: .git
2022/08/09 15:17:54 PathSeparator duration: 66ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 43ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 43ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 41ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 41ns, args: 
2022/08/09 15:17:54 PathSeparator duration: 42ns, args: 
2022/08/09 15:17:54 debug: RunCommand
# branch.oid 7c43a9f4209250c8088d5c3fa1c3f2a76fa04165
# branch.head main
# branch.upstream origin/main
# branch.ab +0 -0
? foo.txt
? lib/foo/
2022/08/09 15:17:54 RunCommand duration: 34.439649ms, args: git -C /Users/olaf/Documents/github/skaji/cpm/ --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --branch --porcelain=2
2022/08/09 15:17:54 debug: HasFolder
false
2022/08/09 15:17:54 HasFolder duration: 11.349µs, args: /Users/olaf/Documents/github/skaji/cpm/.git/rebase-merge
2022/08/09 15:17:54 debug: HasFolder
false
2022/08/09 15:17:54 HasFolder duration: 4.647µs, args: /Users/olaf/Documents/github/skaji/cpm/.git/rebase-apply
2022/08/09 15:17:54 PathSeparator duration: 68ns, args: 
2022/08/09 15:17:54 debug: HasFilesInDir
false
2022/08/09 15:17:54 HasFilesInDir duration: 19.581µs, args: MERGE_MSG
2022/08/09 15:17:54 PathSeparator duration: 42ns, args: 
2022/08/09 15:17:54 debug: HasFilesInDir
false
2022/08/09 15:17:54 HasFilesInDir duration: 4.626µs, args: CHERRY_PICK_HEAD
2022/08/09 15:17:54 PathSeparator duration: 43ns, args: 
2022/08/09 15:17:54 debug: HasFilesInDir
false
2022/08/09 15:17:54 HasFilesInDir duration: 4.284µs, args: REVERT_HEAD
2022/08/09 15:17:54 PathSeparator duration: 42ns, args: 
2022/08/09 15:17:54 debug: HasFilesInDir
false
2022/08/09 15:17:54 HasFilesInDir duration: 3.598µs, args: sequencer/todo
2022/08/09 15:17:54 error: FileContent
open /Users/olaf/Documents/github/skaji/cpm/.git/logs/refs/stash: no such file or directory
2022/08/09 15:17:54 FileContent duration: 16.086µs, args: /Users/olaf/Documents/github/skaji/cpm/.git/logs/refs/stash
2022/08/09 15:17:54 TemplateCache duration: 148ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 270ns, args: 
2022/08/09 15:17:54 Shell duration: 178ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 225ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 1.578µs, args: 
2022/08/09 15:17:54 GOOS duration: 81ns, args: 
2022/08/09 15:17:54 Root duration: 878ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 1.044µs, args: 
2022/08/09 15:17:54 GOOS duration: 44ns, args: 
2022/08/09 15:17:54 ExecutionTime duration: 83ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 78ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 104ns, args: 
2022/08/09 15:17:54 Shell duration: 104ns, args: 
2022/08/09 15:17:54 debug: Pwd
/Users/olaf/Documents/github/skaji/cpm
2022/08/09 15:17:54 Pwd duration: 1.337µs, args: 
2022/08/09 15:17:54 GOOS duration: 59ns, args: 
2022/08/09 15:17:54 ErrorCode duration: 72ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 40ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 61ns, args: 
2022/08/09 15:17:54 Shell duration: 62ns, args: 
2022/08/09 15:17:54 TemplateCache duration: 62ns, args: 
2022/08/09 15:17:54 debug: Getenv

2022/08/09 15:17:54 Getenv duration: 1.397µs, args: XDG_CACHE_HOME
2022/08/09 15:17:54 CachePath duration: 57.538µs, args: 
2022/08/09 15:17:54 Flags duration: 60ns, args: 

---

**Comment by JanDeDobbeleer** [comment]
@cyberfunkr @oalders I did change the escape codes for wrapping non printable characters a while back, but that should be compatible. Maybe it's not (but then not sure why that works for me and not you). This would imply that 8.26.1 works and 8.27.0 is broken for you.

**Comment by oalders** [comment]
> This would imply that 8.26.1 works and 8.27.0 is broken for you.

Yes! I've installed both versions and it breaks at 8.27.0

**Comment by JanDeDobbeleer** [comment]
@oalders @cyberfunkr will be available really soon.

**Comment by JanDeDobbeleer** [comment]
@cyberfunkr @oalders if either of you could confirm, we can also close the issue. Helps my OCD 😅

**Comment by oalders** [comment]
@JanDeDobbeleer it works! Thanks for helping my OCD. 😄
