### ISSUE TITLE
Prompt history broken since 8.27.0

### ISSUE THREAD

**Issue by jorisroovers** [JanDeDobbeleer/oh-my-posh#2639]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi Jan, big fan, thanks for creating and maintaining oh-my-posh!

Since a few versions, my prompt history breaks. That is, when hitting return, previous prompt lines no longer contain my full prompt, only the current working directory.

I've been able to pinpoint this to oh-my-posh 8.27, I believe this screenshot shows it well:

<img width="875" alt="CleanShot 2022-08-09 at 10 03 57@2x" src="https://user-images.githubusercontent.com/575086/183599317-964f9ccd-48af-4f03-bc3c-d5a401054096.png">

Note that on 8.26 (first 3 lines) the full commandline prompt shows for each command that's been executing, but after switching to 8.27 only `foo` shows, i.e. the current working directory. The rest of the prompt only shows on the active prompt line, but then changes to only show `foo` right after executing a command.

Apologies if this is known change that requires updating on my side, I wasn't able to tell easily from the 8.27 code changes.
This does sound somewhat similar to #2636 but not sure.

I'm on `zsh 5.8.1 (x86_64-apple-darwin21.0)`.

### Theme

{
    "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "segments": [
                {
                    "background": "p:yellow",
                    "foreground": "p:black",
                    "leading_diamond": "\ue0b6",
                    "properties": {
                        "display_host": false
                    },
                    "style": "diamond",
                    "template": " {{ if .SSHSession }}\uf817 {{ .UserName }}@{{ .HostName }}{{ end }}",
                    "trailing_diamond": "\ue0b0",
                    "type": "session"
                },
                {
                    "type": "python",
                    "style": "diamond",
                    "trailing_diamond": "\ue0b0",
                    // "powerline_symbol": "\uE0B0",
                    // "trailing_diamond": "<transparent,background>\ue0b0</>",
                    "foreground": "#100e23",
                    "background": "p:orange",
                    "template": " \uE235 ({{ .Venv }})"
                },
                {
                    "type": "path",
                    "background": "#0087D8",
                    "foreground": "p:white",
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "folder_separator_icon": "/",
                        "style": "full"
                    },
                    "style": "powerline",
                    "template": " <b>{{ .Path }}</b> "
                },
                {
                    "background": "p:green",
                    "background_templates": [
                        "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
                        "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
                        "{{ if gt .Ahead 0 }}#49416D{{ end }}",
                        "{{ if gt .Behind 0 }}#7A306C{{ end }}"
                    ],
                    "foreground": "p:black",
                    "foreground_templates": [
                        "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
                        "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
                        "{{ if gt .Ahead 0 }}p:white{{ end }}"
                    ],
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "branch_max_length": 25,
                        "fetch_status": true,
                        "fetch_upstream_icon": true,
                        "github_icon": "\uf7a3"
                    },
                    "style": "powerline",
                    "template": " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }} ",
                    "type": "git"
                },
                {
                    "background": "p:yellow",
                    "foreground": "p:white",
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "root_icon": "\uf0ad"
                    },
                    "style": "powerline",
                    "template": " \uf0e7 ",
                    "type": "root"
                },
                {
                    "type": "exit",
                    "background": "p:green",
                    "background_templates": [
                        "{{ if gt .Code 0 }}p:red{{ end }}"
                    ],
                    "foreground": "p:white",
                    "leading_diamond": "<transparent,background>\ue0b0</>",
                    "properties": {
                        "always_enabled": true
                    },
                    "style": "diamond",
                    "template": " {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }} ",
                    "trailing_diamond": "\ue0b4"
                }
            ]
        },
        {
            "type": "rprompt",
            "segments": [
                {
                    "background": "transparent",
                    "foreground": "p:green",
                    "properties": {
                        "display_mode": "files",
                        "fetch_package_manager": false,
                        "home_enabled": false
                    },
                    "style": "plain",
                    "template": "\uf898 ",
                    "type": "node"
                },
                {
                    "background": "transparent",
                    "foreground": "p:blue",
                    "properties": {
                        "fetch_version": false
                    },
                    "style": "powerline",
                    "template": "\ufcd1 ",
                    "type": "go"
                },
                {
                    "background": "transparent",
                    "foreground": "p:yellow",
                    "properties": {
                        "display_mode": "files",
                        "fetch_version": true,
                        "fetch_virtual_env": false
                    },
                    "style": "plain",
                    "template": "\ue235 ",
                    "type": "python"
                },
                {
                    "type": "text",
                    "style": "powerline",
                    "powerline_symbol": "\ue0b2",
                    "invert_powerline": true,
                    "background": "blue",
                    "foreground": "white",
                    "template": "{{ if gt (.Env.SHLVL | atoi) 1 }} \uf489 {{.Env.SHLVL}} {{ end }}"
                },
                {
                    "type": "executiontime",
                    "style": "diamond",
                    "invert_powerline": true,
                    "background": "#83769c",
                    "foreground": "white",
                    "properties": {
                        "always_enabled": true
                    },
                    "template": " {{ .FormattedMs }} "
                },
                {
                    "background": "transparent",
                    "foreground": "p:white",
                    "style": "plain",
                    "template": " {{ .CurrentDate | date \"15:04:05\" }}",
                    "type": "time"
                }
            ]
        }
    ],
    "console_title_template": "{{ .Shell }} in {{ .Folder }}",
    "final_space": true,
    "palette": {
        "black": "#262B44",
        "blue": "#4B95E9",
        "green": "#39b54a",
        "orange": "#F07623",
        "red": "#D81E5B",
        "white": "#E0DEF4",
        "yellow": "#F3AE35"
    },
    "secondary_prompt": {
        "background": "transparent",
        "foreground": "p:black",
        "template": "<p:yellow,transparent>\ue0b6</><,p:yellow> > </><p:yellow,transparent>\ue0b0</> "
    },
    "tooltips": [],
    "transient_prompt": {
        "background": "transparent",
        "foreground": "p:black",
        "template": "<p:yellow,transparent>\ue0b6</><,p:yellow> {{ .Folder }} </><p:yellow,transparent>\ue0b0</> "
    },
    "version": 2
}

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
oh-my-posh debug

Version: 8.27.0

Segments:

ConsoleTitle(true)   -   0 ms - zsh in foo
session(false)       -   0 ms -
python(true)         -  91 ms -   (.venv)
path(true)           -   0 ms -  /tmp/bar/foo
git(false)           -   0 ms -
root(false)          -   0 ms -
exit(true)           -   1 ms -   
node(false)          -   0 ms -
go(false)            -   0 ms -
python(true)         -  79 ms - 
text(false)          -   0 ms -
executiontime(true)  -   0 ms -  0ms
time(true)           -   0 ms -  10:08:55

Run duration: 177.915628ms

Cache path: /Users/jroovers/.cache/oh-my-posh

Config path: /Users/jroovers/.joris.omp.json

Logs:

2022/08/09 10:08:54 debug: Getenv

2022/08/09 10:08:54 Getenv duration: 21.27µs, args: XDG_CACHE_HOME
2022/08/09 10:08:54 CachePath duration: 53.462µs, args:
2022/08/09 10:08:54 debug: Getenv
/Users/jroovers/.joris.omp.json
2022/08/09 10:08:54 Getenv duration: 8.173µs, args: POSH_THEME
2022/08/09 10:08:54 resolveConfigPath duration: 12.27µs, args:
2022/08/09 10:08:54 Init duration: 930.755µs, args:
2022/08/09 10:08:54 Flags duration: 71ns, args:
2022/08/09 10:08:54 config.loadConfig duration: 1.031729ms, args:
2022/08/09 10:08:54 Flags duration: 72ns, args:
2022/08/09 10:08:54 debug: Getenv

2022/08/09 10:08:54 Getenv duration: 1.657µs, args: OMP_CACHE_DISABLED
2022/08/09 10:08:54 Root duration: 966ns, args:
2022/08/09 10:08:54 Shell duration: 126.391µs, args:
2022/08/09 10:08:54 ErrorCode duration: 133ns, args:
2022/08/09 10:08:54 debug: Getenv

2022/08/09 10:08:54 Getenv duration: 1.461µs, args: WSL_DISTRO_NAME
2022/08/09 10:08:54 IsWsl duration: 3.334µs, args:
2022/08/09 10:08:54 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:54 Pwd duration: 26.279µs, args:
2022/08/09 10:08:54 PathSeparator duration: 88ns, args:
2022/08/09 10:08:54 PathSeparator duration: 50ns, args:
2022/08/09 10:08:54 PathSeparator duration: 64ns, args:
2022/08/09 10:08:54 PathSeparator duration: 48ns, args:
2022/08/09 10:08:54 PathSeparator duration: 49ns, args:
2022/08/09 10:08:54 debug: User
jroovers
2022/08/09 10:08:54 User duration: 1.101µs, args:
2022/08/09 10:08:54 debug: Host
JROOVERS-M-3185
2022/08/09 10:08:54 Host duration: 17.818µs, args:
2022/08/09 10:08:54 GOOS duration: 80ns, args:
2022/08/09 10:08:54 TemplateCache duration: 243.967µs, args:
2022/08/09 10:08:54 Flags duration: 101ns, args:
2022/08/09 10:08:54 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:54 Pwd duration: 1.396µs, args:
2022/08/09 10:08:54 GOOS duration: 71ns, args:
2022/08/09 10:08:54 debug: Getenv

2022/08/09 10:08:54 Getenv duration: 1.25µs, args: SSH_CONNECTION
2022/08/09 10:08:54 debug: Getenv

2022/08/09 10:08:54 Getenv duration: 828ns, args: SSH_CLIENT
2022/08/09 10:08:54 TemplateCache duration: 98ns, args:
2022/08/09 10:08:54 TemplateCache duration: 246ns, args:
2022/08/09 10:08:54 Shell duration: 161ns, args:
2022/08/09 10:08:54 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:54 Pwd duration: 1.725µs, args:
2022/08/09 10:08:54 GOOS duration: 83ns, args:
2022/08/09 10:08:54 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:54 Pwd duration: 992ns, args:
2022/08/09 10:08:54 debug: Getenv
/private/tmp/bar/foo/.venv
2022/08/09 10:08:54 Getenv duration: 1.238µs, args: VIRTUAL_ENV
2022/08/09 10:08:54 PathSeparator duration: 96ns, args:
2022/08/09 10:08:54 PathSeparator duration: 54ns, args:
2022/08/09 10:08:54 PathSeparator duration: 56ns, args:
2022/08/09 10:08:54 PathSeparator duration: 53ns, args:
2022/08/09 10:08:54 PathSeparator duration: 54ns, args:
2022/08/09 10:08:54 PathSeparator duration: 56ns, args:
2022/08/09 10:08:54 PathSeparator duration: 81ns, args:
2022/08/09 10:08:54 debug: CommandPath
/Users/jroovers/.pyenv/shims/python
2022/08/09 10:08:54 CommandPath duration: 26.81µs, args: python
2022/08/09 10:08:54 debug: Getenv

2022/08/09 10:08:54 Getenv duration: 1.148µs, args: PYENV_ROOT
2022/08/09 10:08:54 debug: CommandPath
/Users/jroovers/.pyenv/shims/python
2022/08/09 10:08:54 CommandPath duration: 966ns, args: python
2022/08/09 10:08:54 HasCommand duration: 2.346µs, args: python
2022/08/09 10:08:55 debug: RunCommand
Python 3.10.0
2022/08/09 10:08:55 RunCommand duration: 90.665264ms, args: python --version
2022/08/09 10:08:55 TemplateCache duration: 294ns, args:
2022/08/09 10:08:55 TemplateCache duration: 83ns, args:
2022/08/09 10:08:55 TemplateCache duration: 160ns, args:
2022/08/09 10:08:55 Shell duration: 174ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.874µs, args:
2022/08/09 10:08:55 GOOS duration: 67ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 853ns, args:
2022/08/09 10:08:55 Flags duration: 67ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 6.978µs, args:
2022/08/09 10:08:55 GOOS duration: 61ns, args:
2022/08/09 10:08:55 GOOS duration: 44ns, args:
2022/08/09 10:08:55 PathSeparator duration: 75ns, args:
2022/08/09 10:08:55 PathSeparator duration: 46ns, args:
2022/08/09 10:08:55 GOOS duration: 65ns, args:
2022/08/09 10:08:55 debug: Getenv

2022/08/09 10:08:55 Getenv duration: 1.124µs, args: WSL_DISTRO_NAME
2022/08/09 10:08:55 IsWsl duration: 2.826µs, args:
2022/08/09 10:08:55 StackCount duration: 71ns, args:
2022/08/09 10:08:55 DirIsWritable duration: 19.57µs, args:
2022/08/09 10:08:55 TemplateCache duration: 79ns, args:
2022/08/09 10:08:55 TemplateCache duration: 154ns, args:
2022/08/09 10:08:55 Shell duration: 78ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.526µs, args:
2022/08/09 10:08:55 GOOS duration: 52ns, args:
2022/08/09 10:08:55 debug: Getenv

2022/08/09 10:08:55 Getenv duration: 1.199µs, args: WSL_DISTRO_NAME
2022/08/09 10:08:55 IsWsl duration: 2.969µs, args:
2022/08/09 10:08:55 GOOS duration: 61ns, args:
2022/08/09 10:08:55 debug: CommandPath
/usr/local/bin/git
2022/08/09 10:08:55 CommandPath duration: 56.544µs, args: git
2022/08/09 10:08:55 HasCommand duration: 58.612µs, args: git
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 908ns, args:
2022/08/09 10:08:55 error: HasParentFilePath
stat /.git: no such file or directory
2022/08/09 10:08:55 HasParentFilePath duration: 23.414µs, args: .git
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.126µs, args:
2022/08/09 10:08:55 GOOS duration: 65ns, args:
2022/08/09 10:08:55 Root duration: 663ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.03µs, args:
2022/08/09 10:08:55 GOOS duration: 66ns, args:
2022/08/09 10:08:55 ErrorCode duration: 88ns, args:
2022/08/09 10:08:55 TemplateCache duration: 76ns, args:
2022/08/09 10:08:55 TemplateCache duration: 196ns, args:
2022/08/09 10:08:55 Shell duration: 149ns, args:
2022/08/09 10:08:55 TemplateCache duration: 161ns, args:
2022/08/09 10:08:55 Flags duration: 86ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.497µs, args:
2022/08/09 10:08:55 GOOS duration: 86ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 825ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 810ns, args:
2022/08/09 10:08:55 PathSeparator duration: 77ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 160.809µs, args: *.js
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.011µs, args:
2022/08/09 10:08:55 PathSeparator duration: 51ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 92.684µs, args: *.ts
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 963ns, args:
2022/08/09 10:08:55 PathSeparator duration: 53ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 11.232µs, args: package.json
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 816ns, args:
2022/08/09 10:08:55 PathSeparator duration: 46ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 7.088µs, args: .nvmrc
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 782ns, args:
2022/08/09 10:08:55 PathSeparator duration: 47ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 7.009µs, args: pnpm-workspace.yaml
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 758ns, args:
2022/08/09 10:08:55 PathSeparator duration: 49ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 6.596µs, args: .pnpmfile.cjs
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 764ns, args:
2022/08/09 10:08:55 PathSeparator duration: 51ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 6.393µs, args: .npmrc
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 780ns, args:
2022/08/09 10:08:55 PathSeparator duration: 48ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 6.539µs, args: .vue
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.081µs, args:
2022/08/09 10:08:55 GOOS duration: 65ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 719ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 739ns, args:
2022/08/09 10:08:55 PathSeparator duration: 62ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 72.515µs, args: *.go
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 838ns, args:
2022/08/09 10:08:55 PathSeparator duration: 64ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 9.825µs, args: go.mod
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.021µs, args:
2022/08/09 10:08:55 GOOS duration: 77ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 10.081µs, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 785ns, args:
2022/08/09 10:08:55 PathSeparator duration: 50ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 70.706µs, args: *.py
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 775ns, args:
2022/08/09 10:08:55 PathSeparator duration: 65ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 68.76µs, args: *.ipynb
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 816ns, args:
2022/08/09 10:08:55 PathSeparator duration: 64ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 9.827µs, args: pyproject.toml
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 774ns, args:
2022/08/09 10:08:55 PathSeparator duration: 49ns, args:
2022/08/09 10:08:55 debug: HasFiles
false
2022/08/09 10:08:55 HasFiles duration: 7.016µs, args: venv.bak
2022/08/09 10:08:55 debug: HasFolder
true
2022/08/09 10:08:55 HasFolder duration: 8.351µs, args: .venv
2022/08/09 10:08:55 debug: CommandPath
/Users/jroovers/.pyenv/shims/python
2022/08/09 10:08:55 CommandPath duration: 1.243µs, args: python
2022/08/09 10:08:55 debug: Getenv

2022/08/09 10:08:55 Getenv duration: 1.199µs, args: PYENV_ROOT
2022/08/09 10:08:55 debug: CommandPath
/Users/jroovers/.pyenv/shims/python
2022/08/09 10:08:55 CommandPath duration: 892ns, args: python
2022/08/09 10:08:55 HasCommand duration: 2.174µs, args: python
2022/08/09 10:08:55 debug: RunCommand
Python 3.10.0
2022/08/09 10:08:55 RunCommand duration: 78.714114ms, args: python --version
2022/08/09 10:08:55 TemplateCache duration: 320ns, args:
2022/08/09 10:08:55 TemplateCache duration: 66ns, args:
2022/08/09 10:08:55 TemplateCache duration: 125ns, args:
2022/08/09 10:08:55 Shell duration: 158ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.973µs, args:
2022/08/09 10:08:55 GOOS duration: 76ns, args:
2022/08/09 10:08:55 TemplateCache duration: 79ns, args:
2022/08/09 10:08:55 TemplateCache duration: 160ns, args:
2022/08/09 10:08:55 Shell duration: 110ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.37µs, args:
2022/08/09 10:08:55 GOOS duration: 50ns, args:
2022/08/09 10:08:55 ExecutionTime duration: 83ns, args:
2022/08/09 10:08:55 TemplateCache duration: 56ns, args:
2022/08/09 10:08:55 TemplateCache duration: 162ns, args:
2022/08/09 10:08:55 Shell duration: 96ns, args:
2022/08/09 10:08:55 debug: Pwd
/tmp/bar/foo
2022/08/09 10:08:55 Pwd duration: 1.375µs, args:
2022/08/09 10:08:55 GOOS duration: 64ns, args:
2022/08/09 10:08:55 TemplateCache duration: 69ns, args:
2022/08/09 10:08:55 TemplateCache duration: 182ns, args:
2022/08/09 10:08:55 Shell duration: 174ns, args:
2022/08/09 10:08:55 debug: Getenv

2022/08/09 10:08:55 Getenv duration: 1.692µs, args: XDG_CACHE_HOME
2022/08/09 10:08:55 CachePath duration: 45.029µs, args:
2022/08/09 10:08:55 Flags duration: 77ns, args:
```

**Comment by jorisroovers** [comment]
In case it might help... I use the same config on a linux box (`GNU bash 5.0.17(1)-release`) and don't experience this problem there.

**Comment by lewis-yeung** [comment]
@jorisroovers Aha, that's not a bug. There's a `transient_prompt` section in your theme config, see [docs](https://ohmyposh.dev/docs/configuration/transient) for details about it. Starting from [v8.27.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v8.27.0), the feature is [enabled automatically](https://ohmyposh.dev/docs/configuration/transient#enable-the-feature) when the theme config contains a `transient_prompt` section:

> Oh My posh handles enabling the feature automatically for all shells except `cmd` when the config contains a transient prompt configuration.

If you don't like this, just remove that section from your config file. :)

**Comment by jorisroovers** [comment]
That fixes it! Thanks @lewis-yeung!

Sorry to waste your time, should've read the changelog closer!
