### ISSUE TITLE
multi-line command

### ISSUE THREAD

**Issue by aviRon012** [JanDeDobbeleer/oh-my-posh#2674]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

If possible I would like the ability to customize the "mini prompt" that appears when entering a multiline command,
currently what appears is simply "> ".
example:
![shell multiline command](https://user-images.githubusercontent.com/81820388/185116278-c6e5cdb5-b44e-455e-9e64-e92748d592d7.png)

**Comment by JanDeDobbeleer** [comment]
@aviRon012 have a look [here](https://ohmyposh.dev/docs/configuration/secondary-prompt).
