### ISSUE TITLE
Git autocompletion to add modified files does not work

### ISSUE THREAD

**Issue by devholland** [JanDeDobbeleer/oh-my-posh#2689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I don't know if it is a bug or missing feature, but when I use the old version (2.0.496) of `oh-my-posh` together with `posh-git`, then I have tab-completion for modified files in Git repositories. If I modify a file and type `git add <tab>`, then the file is automatically selected. If multiple files are modified, then `<tab>` cycles through them. This behavior is gone with the newest version (8.30.0) of `oh-my-posh` for me.

### Theme

tehrob (2.0.496)
xtoys (8.30.0)
 

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
There's no log output. Instead of selecting the modified file(s) for `git add <tab>`, it just selects a random one, like the normal shell behavior.
```

**Comment by lewis-yeung** [comment]
@devholland Unable to reproduce with the latest release (v8.32.4) of Oh My Posh. It works fine on my end. Tested in PowerShell v7.2.6 with posh-git v1.1.0.

Have you added `$env:POSH_GIT_ENABLED = $true` before the `oh-my-posh init pwsh ...` command in your PowerShell profile?

**Comment by JanDeDobbeleer** [comment]
@devholland you need to enable posh-git support by setting `$env:POSH_GIT_ENABLED = $true`. Be aware this calls git twice when also using the regular git segment.
