### ISSUE TITLE
Considering support more network interface

### ISSUE THREAD

**Issue by LNKLEO** [JanDeDobbeleer/oh-my-posh#2700]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hope omp could support cellular network and cable networks, and hava a variable to identify which network is currently in use.

**Comment by JanDeDobbeleer** [comment]
@LNKLEO unfortunately this isn't available from golang without a full custom implementation which goes beyond the scope of oh-my-posh. Pretty sure there's no language out there that supports this though as it requires a specific implementation per os. Even the Wifi segment here is only available for Windows (because there a contributor did it for us).

**Comment by LNKLEO** [comment]
update some progress with you.
without add more libs, I have found a native way on windows to get all network connections with types(wifi/cellular/bluetooth/etc.), and Link/Transmission speed, but no service provider for Cellular, SSID for wifi, signal strength for both. (while current way supports wifi.)

![Screenshot 2022-08-26 171033 - Copy](https://user-images.githubusercontent.com/10334184/186872118-88ea2023-464e-47dd-a9fc-915cabcdaa14.png)
![Screenshot 2022-08-26 171033](https://user-images.githubusercontent.com/10334184/186872142-cc2ee85d-df02-487c-8603-62177c04b8da.png)
![Screenshot 2022-08-26 172706](https://user-images.githubusercontent.com/10334184/186873848-ffaac203-90ed-4a3f-827e-2f95205c629d.png)

i tested on two of my computers, including wifi/cellular/wired/bluetooth, it looks good. but only problem is i cannot get priority of the networks.

my method using nearly the same way just like get wifi info.

I think i could merge this support into to network indicator first.

**Comment by JanDeDobbeleer** [comment]
@LNKLEO did you look at win32 calls for this?

**Comment by LNKLEO** [comment]
> @LNKLEO did you look at win32 calls for this?

yes, it is win32 call
