### ISSUE TITLE
Update blocked by attack surface reduction

### ISSUE THREAD

**Issue by HenrikBacher** [JanDeDobbeleer/oh-my-posh#2701]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Recently my company has enabled the attack surface reduction on windows pc's, this blocks updates to oh-my-posh, with the following warning:

![image](https://user-images.githubusercontent.com/231445/186375077-8b3346e4-2bd8-4359-bdfc-4ffa8c1e21b6.png)

In this case the update ran thru chocolatey, but the same error occurs when downloading the update directly from github releases

Reference on attack surface reduction: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/overview-attack-surface-reduction?view=o365-worldwide

### Theme

N/A

### What OS are you seeing the problem on?

Windows 10

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@HenrikBacher everything is code signed (even the installer) so ask your company admins to whitelist it. Nothing I more can do on my end.

Maybe the Store version can "bypass" that rule?
