### ISSUE TITLE
Bash misidentifies escape sequences in the console title

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2702]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In bash, if the console title contains a backslash (`\`), there may be a misidentification of an escape sequence.

For example, in Git Bash, if the console title template contains `{{.PWD}}` which is a Windows-style path with some backslashes as separators, the bug may show up. See screenshots below: (misidentifications of `\s` which expands to the shell name and `\a` which triggers the bell in Windows Terminal)

![bug-in-git-bash-1](https://user-images.githubusercontent.com/83903009/186447077-5d44fbd7-4944-435a-a915-79fba55a5f4a.png)
![bug-in-git-bash-2](https://user-images.githubusercontent.com/83903009/186447086-e11f013f-b73e-4eb6-b471-67d6a446aa01.png)

A simple solution I got is using double-backslashes (`\\`) to escape every single one. Just add a change in [`src/color/ansi.go`](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/color/ansi.go):

```go
func (a *Ansi) Title(title string) string {
	// we have to do this to prevent bash from misidentifying escape sequences
	if a.shell == shell.BASH {
		title = strings.ReplaceAll(title, `\`, `\\`)
	}
	return fmt.Sprintf(a.title, title)
}
```

Of course, that way it disables those [built-in escape sequences of bash](https://tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html) (e.g., `\s`) in the console title template. Even so, IMO, it doesn't hurt since we're able to get most of the values using OMP's templates. 😄

### Theme

A custom one, with `console_title_template` as `{{if .Root}}*{{end}}{{.Shell}} | {{.UserName}}@{{.HostName}} | {{.PWD}}`.

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash

### Log output

N/A

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung am I correct in thinking we now went full circle for escape sequences? I'm going to give this some thoughts first. Also, and here I can safely state that, I really don't like git bash (or any cygwin abomination for that matter).

**Comment by lewis-yeung** [comment]
> I really don't like git bash (or any cygwin abomination for that matter).

Neither do I. 😆 But indeed the bug can appear in Linux bash.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I agree, it's possible. I'll have a good look at escaping once again because I did refactor this a while back.

**Comment by lewis-yeung** [comment]
> I'll have a good look at escaping once again because I did refactor this a while back.

@JanDeDobbeleer BTW, it would be more perfect if we don't have to replace backticks with single quotes so that a `` ` `` can be displayed as is. I think this is possible as well. Related code:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/22da6bd96d2a6740f4c0a709c62799c16332e54e/src/engine/segment.go#L404
