### ISSUE TITLE
[fish] Transient prompt triggered after pressing enter in autocomplete dropdown menu

### ISSUE THREAD

**Issue by FWest98** [JanDeDobbeleer/oh-my-posh#2708]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In fish, when pressing <kbd>Tab</kbd> for autocomplete, you can navigate in the autocomplete options with arrow keys and and select a value by pressing <kbd>Enter</kbd>. However, when the transient prompt is enabled, that keypress causes OMP to think that the transient prompt should be rendered instead of the normal prompt, while the command is not yet "submitted".

![afbeelding](https://user-images.githubusercontent.com/1918658/186789066-161fa191-3eba-4c5e-a9aa-ab199c0e7366.png)

### Theme

Any config with a transient prompt

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

fish

### Log output

```Shell
.
```

**Comment by lewis-yeung** [comment]
Bug confirmed. Only if we figure out how to check whether we're in a tab-completion context can this be fixed... Further work may be done for the related function:

https://github.com/JanDeDobbeleer/oh-my-posh/blob/2f4ebfc493a0bed343aa253ae8c73522093952d1/src/shell/scripts/omp.fish#L81-L85
