### ISSUE TITLE
Cannot execute oh-my-posh on PowerShell 7

### ISSUE THREAD

**Issue by PedroDBFlores** [JanDeDobbeleer/oh-my-posh#273]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [X ] I looked for duplicate issues before submitting this one

### Description

Cannot execute oh-my-posh on Windows

### Environment

- Oh my Posh version: 3.64.0
- Theme: Agnoster
- Operating System: Windows 10
- Shell: Powershell 7
- Terminal: Powershell 7 or Windows Terminal

### Steps to Reproduce

1. Install oh-my-posh v3 via the Powershell Module
2. Configure the Powershell $PROFILE
3. Reload Powershell

**Expected behavior:** To be able to use oh-my-posh out of the box.

**Actual behavior:** 

Cannot use oh-my-posh at all. Can use the theme functions though.

I get the following:
```
oh-my-posh: C:\Users\pedro\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:4
Line |
   4 |  Invoke-Expression (oh-my-posh --init --shell pwsh --config ~/.theme.o …
     |                     ~~~~~~~~~~
     | The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
```

My $PROFILE settings:
```
Import-Module 'oh-my-posh'
Invoke-Expression (oh-my-posh --init --shell pwsh --config ~/.theme.omp.json)
```

**Comment by JanDeDobbeleer** [comment]
@PedroDBFlores when using the module, you don't need to follow the installation guide. It contains helper functions for all instructions in that guide. See the [package docs](https://ohmyposh.dev/docs/powershell) for that info.

In your case, you can replace the `Invoke` statement with `Set-PoshPrompt -Theme ~/.theme.omp.json `

**Comment by PedroDBFlores** [comment]
Well that worked, thanks a lot. Maybe I misunderstood while following the guide 👍 .

**Comment by JanDeDobbeleer** [comment]
@PedroDBFlores if you can let me know where that misinterpretation came from I can adjust the docs accordingly. More people seem to be struggling with this.

**Comment by PedroDBFlores** [comment]
Rereading the pages, for me it wasn't clear that I couldn't set that directly on the $PROFILE, on the last bit on [https://ohmyposh.dev/docs/powershell]( https://ohmyposh.dev/docs/powershell) there it says you can customise and set it directly on $PROFILE, but not sure if it should call `Set-PoshPrompt` on every $PROFILE load, which I guess I should.

**Comment by dmcgowan2** [comment]
@JanDeDobbeleer The misinterpretation likely comes from the instruction at bottom of this page - https://ohmyposh.dev/docs/windows

**Comment by JanDeDobbeleer** [comment]
@dmcgowan-dev in the meantime those docs have been restructured implying that if you follow the page you mention you now actually have oh-my-posh as an executable.

**Comment by dmcgowan2** [comment]
@JanDeDobbeleer yes, and using the executable works fine. Thanks.
