### ISSUE TITLE
A parameter cannot be found that matches parameter name 'Key'.

### ISSUE THREAD

**Issue by DEPSTRCZ** [JanDeDobbeleer/oh-my-posh#2733]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The eror pops on when trying to use set up theme, and now when trying to use any posh command

### Theme

The default one
but trying to use: [bubblesextra](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/bubblesextra.omp.json)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Get-PSReadLineKeyHandler : A parameter cannot be found that matches parameter name 'Key'.
At line:355 char:39
+         if ((Get-PSReadLineKeyHandler -Key Spacebar).Function -eq 'Oh ...
+                                       ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSReadLineKeyHandler], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.GetKeyHandlerCommand

Get-PSReadLineKeyHandler : A parameter cannot be found that matches parameter name 'Key'.
At line:358 char:39
+         if ((Get-PSReadLineKeyHandler -Key Enter).Function -eq 'OhMyP ...
+                                       ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSReadLineKeyHandler], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.GetKeyHandlerCommand
```

**Comment by lewis-yeung** [comment]
@DEPSTRCZ What's your PowerShell and PSReadLine version? Please paste the output of `"$($PSVersionTable.PSVersion)"` and `"$((Get-Module PSReadLine).Version)"` here.

**Comment by JanDeDobbeleer** [comment]
@DEPSTRCZ this is definitely due to an outdated PSReadLine module. Updating that to latest will resolve this.
