### ISSUE TITLE
nushell: update init script to be compatible with 0.68

### ISSUE THREAD

**Issue by ehawman** [JanDeDobbeleer/oh-my-posh#2756]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

With the release of [Nushell 0.68](https://www.nushell.sh/blog/2022-09-06-nushell-0_68.html), the change in environment/module import structure has broken OMP's init process wrt Nu.

I admit I haven't puzzled out the correct way to fix this quite yet, although I have created a discussion page for it at Nushell/Nushell#6513 should anyone either see the correct solution or wish to monitor in case a Nushell expert comes along to answer.

### Theme

devious-diamonds.omp.yaml

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@ehawman shouldn't a shell at least try to cover some backwards compatibility? I don't see why they would fundamentally break this, although granted they're on 0.X.

**Comment by ehawman** [comment]
@JanDeDobbeleer it turns out that they tried to do a graceful handover w/ backwards compatibility until the next version, but someone messed up and they shipped with a bug that breaks all implementations (old and new).

Nu is an interesting animal to be sure haha.

**Comment by JanDeDobbeleer** [comment]
@ehawman reading through the comments it's a bug in nu, not oh-my-posh. We can migrate, but then again it won't work until that panic is fixed. I'll add this as an enhancement as it's not a bug for us.

**Comment by ehawman** [comment]
Makes sense to me! I'll ping you here when they get it ironed out.

**Comment by JanDeDobbeleer** [comment]
@ehawman does 0.68.1 fix the issue?
