### ISSUE TITLE
Add `display_mode` property to Text segment

### ISSUE THREAD

**Issue by jrotello** [JanDeDobbeleer/oh-my-posh#2763]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I am using an environment variable with the Text segment to display the result of `docker context show`, but I'd like that segment to only display if there is a Dockerfile or docker-compose.(yml|yaml) file in the current directory. Adding support for the `display_mode` property to the Text segment would make this possible.

One could argue that a Docker segment makes sense in this particular case, but I think the `display_mode` on the Text segment would make it more flexible.

```
function Set-OhMyPoshEnvVars {
    if ($null -ne (Get-Command docker -ErrorAction SilentlyContinue)) {
        $env:POSH_DOCKER_CONTEXT = (docker context show)
    }
}
New-Alias -Name 'Set-PoshContext' -Value 'Set-OhMyPoshEnvVars' -Scope Global -Force
```

Something like this would be needed to make it generic enough for the Text segment
```
{
  "type": "text",
  "style": "powerline",
  "invert_powerline": true,
  "powerline_symbol": "\ue0b2",
  "foreground": "#e4e4e4",
  "background": "#3465a4",
  "template": " \uf308 {{ .Env.POSH_DOCKER_CONTEXT }} ",
  "properties": {
    "display_mode": {
      "mode": "files"
      "filelist": ["Dockerfile", "docker-compose.*"]
    }
  }
}
```

`mode` would need three vaules I think: `never, always, files`. If `files` is set, then another property (`filelist`) would be used.

Thanks for your consideration!

**Comment by JanDeDobbeleer** [comment]
@jrotello you don't need that if your custom PowerShell function validates the existence of the files and only populates the environment variable if so. Combined with a template that only has a text value in that case by adding an `if` statement that checks if the variable has a value and if so print the icon and the value, it can show/hide the segment automatically.

That said, it's significantly easier to create a docker segment for me 😂

**Comment by jrotello** [comment]
Thanks for the guidance! That did in fact work without issue.

```
function Set-OhMyPoshEnvVars {    
    $env:POSH_DOCKER_CONTEXT = ''
    if ((Get-ChildItem -Path $PWD\* -Include Dockerfile, docker-compose*.yml).Length -gt 0) {
        if ($null -ne (Get-Command docker -ErrorAction SilentlyContinue)) {
            $env:POSH_DOCKER_CONTEXT = (docker context show)
        }
    }
}
New-Alias -Name 'Set-PoshContext' -Value 'Set-OhMyPoshEnvVars' -Scope Global -Force
```

```
{
  "type": "text",
  "style": "powerline",
  "invert_powerline": true,
  "powerline_symbol": "\ue0b2",
  "foreground": "#e4e4e4",
  "background": "#3465a4",
  "template": "{{ if .Env.POSH_DOCKER_CONTEXT }} \uf308 {{ .Env.POSH_DOCKER_CONTEXT }} {{ end }}"
}
```

Closing this issue. Thanks again for the help!
