### ISSUE TITLE
Show Deno version and details in Deno projects

### ISSUE THREAD

**Issue by shah** [JanDeDobbeleer/oh-my-posh#2764]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

NodeJS is auto-detected and shows version information in many themes. We use Deno instead of NodeJS for many of our JS/TS projects and I was curious what the best way was to integrate Deno version and details like OMP does for Node today.

**Comment by JanDeDobbeleer** [comment]
@shah not hard. We can definitely implement this.

**Comment by shah** [comment]
Thanks @JanDeDobbeleer !

**Comment by shah** [comment]
@JanDeDobbeleer the `deno` segment works great in general. 

I was curious if you could suggest how to automate the selection of `deno` vs. `node` based on an env var or existence of `deno.json`. 

* Currently we can use the Deno `always` or `files` display option 
* Perhaps we should also allow `deno.json` as another option
* and `TSJS_RUNTIME=node` or `TSJS_RUNTIME=deno` env var strategy as another option 

This is because some projects use `node`, others use `deno` based on existence of `package.json` (node) and `deno.json` (deno) but sometimes neither file exists and we need to detect it some other way.

**Comment by JanDeDobbeleer** [comment]
@shah I'll add `deno.json` to the list and we can already make use of the templating capabilities to work with [environment variables](https://ohmyposh.dev/docs/configuration/templates#environment-variables) in logic.
