### ISSUE TITLE
The az segment with source pwsh does not seem to work on azure cloud shell

### ISSUE THREAD

**Issue by colinrippeyfinarne** [JanDeDobbeleer/oh-my-posh#2771]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've got oh-my-posh installed and configured on azure cloud shell.

I typically always use a Powershell prompt, but I have lots of use cases where I mix and match the Az powershell module and the az cli commands.

The snippet of segments:

`
        {
          "type": "az",
          "style": "powerline",
          "foreground": "p:white",
          "template": ">p {{ .Name }} ",
          "properties": {
            "source": "pwsh"
          }
        },
        {
          "type": "az",
          "style": "powerline",
          "foreground": "p:green",
          "template": ">a {{ .Name }} "
        },
`

The reason I want these two is so I can see at a glance what my Get-AzContext and my az account show outputs are, in other words what are my two subscriptions currently set to for each command.

The first segment shows nothing, the second segment shows the correct subscription for az account show

Trying to dive in...at the root of my ~ I have two folders of note:

.Azure
.azure

In the .Azure folder there is a file 

AzureRmContext.json

If I use the Set-AzContext -subscription command then the AzureRmContext.json command is updated correctly to reflect the current subscription, and the Get-AzContext command reports back the same.

In the .azure folder there is a file:

azureProfile.json

If I run the az account set --subscription command then this file is updated to reflect the new subscription and the command az account show reports back the same,

If I look in the src/segments/az.go file I can see various functions that "look correct" in the sense that they "should" find the correct config files based on the segment property source being pwsh, but it does not seem to be working.

### Theme

Custom theme I have started from onehalf.minimal and added a few extra segments.

### What OS are you seeing the problem on?

Linux

### Log output

```Shell
From azure cloud shell
```

**Comment by colinrippeyfinarne** [comment]
Maybe this partial debug output can help:

2022/09/12 15:41:14 GOOS duration: 100ns, args: 
2022/09/12 15:41:14 debug: HasFolder
true
2022/09/12 15:41:14 HasFolder duration: 14.501µs, args: /home/colin/.azure
2022/09/12 15:41:14 error: FileContent
open /home/colin/.azure/AzureRmContext.json: no such file or directory
2022/09/12 15:41:14 FileContent duration: 7.9µs, args: /home/colin/.azure/AzureRmContext.json
2022/09/12 15:41:14 debug: Pwd
/home/colin/oh-my-posh/.poshthemes
2022/09/12 15:41:14 Pwd duration: 1µs, args: 
2022/09/12 15:41:14 GOOS duration: 0s, args: 
2022/09/12 15:41:14 debug: Getenv

2022/09/12 15:41:14 Getenv duration: 1µs, args: AZURE_CONFIG_DIR
2022/09/12 15:41:14 debug: HasFolder
true
2022/09/12 15:41:14 HasFolder duration: 6.1µs, args: /home/colin/.azure
2022/09/12 15:41:14 debug: FileContent
{"subscriptions": [{"id":
......
2022/09/12 15:41:14 FileContent duration: 29.901µs, args: /home/colin/.azure/azureProfile.json

This looks like for the first segment with source pwsh it is trying to find the AzureRmContext.json in the /home/colin/.azure folder and not the (correct) /home/colin/.Azure folder.

The second segment default source looks for the azureProfile.json file in the (correct) folder /home/colin/.azure

**Comment by JanDeDobbeleer** [comment]
@colinrippeyfinarne the conversations I want to have with the Azure CLI and PowerShell teams...

**Comment by colinrippeyfinarne** [comment]
@JanDeDobbeleer oh absolutely lol the fact they're still using AzureRmContext.json for the "new shiny az module" says it all. I'm "guessing" this is an easy hack fix to the ConfigDir function...never actually had to build a go program before so I'll maybe try to clone the repo and see if I can at least get a fix done for my env then do a pr.

**Comment by colinrippeyfinarne** [comment]
@JanDeDobbeleer just wanted to say big thank you for getting this fix done so quickly, pulled it and tested and working as expected now.

**Comment by JanDeDobbeleer** [comment]
@colinrippeyfinarne thanks for the donation as well, immensely appreciated 🙏🏻
