### ISSUE TITLE
Transient Prompt More Relevant Exit Code

### ISSUE THREAD

**Issue by astridos2go** [JanDeDobbeleer/oh-my-posh#2777]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

To be fair, I'm not sure if I'm missing this functionality already, but I am trying to use the exit code and transient prompt feature to display whether the command completed successfully. However, as the transient prompt doesn't call for an update of the `.Code` variable, it is showing the wrong status for the previous commands.

I try to illustrate this functionality below:

So ideally, if I complete a task successfully, it would update the transient prompt to look like this:
![image](https://user-images.githubusercontent.com/45048997/189785215-487740ce-6c1f-4ed5-a8e4-ad2eeb88c323.png)

And if it fails, to look like this 
![image](https://user-images.githubusercontent.com/45048997/189785245-21f3676b-76e1-466c-b2d6-461e5a4b5251.png)

But in reality, it just uses the _last_ exit code, as shown here:
![image](https://user-images.githubusercontent.com/45048997/189785361-73a17baa-c97c-400e-8e9b-6478f45b1648.png)

Here is my current transient prompt section: 
```json
"transient_prompt": {
    "template": "{{ if gt .Code 0 }}\uea87{{ else }}\ufae0{{ end }} ",
    "foreground": "#00ff00",
    "foreground_templates": [
      "{{ if gt .Code 0 }}#ff0000{{ else }}#00ff00{{ end }}"
    ]
  },
```

Would it be possible to add a flag, or to have oh-my-posh update the `.Code` variable before setting the transient prompt? In the regular prompt, the exit code updates fine. 

I hope I posed this question/feature request clearly, but if not, please let me know, and I can try to clear it up!

Thank you 😄

**Comment by JanDeDobbeleer** [comment]
@astridos2go this isn't a bug but by design. The transient prompt is your **previous** prompt as it's rendered before executing the command as a means to have a compact historical view. I'm also pretty sure it's not possible to get what you want from a functional point of view.
