### ISSUE TITLE
Custom shell prompt sequences possible ?

### ISSUE THREAD

**Issue by amoldeshpande** [JanDeDobbeleer/oh-my-posh#279]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

I was trying to get OMP working with tcsh (the Windows native version that I maintain) and eventually got there. zsh is fairly close in syntax for prompt syntax with "%{" etc. so it was not as hard as I had feared. 

However, I do miss being able to customize my prompt with tcsh-specific formatting sequences. For example, for the "path" segment, I would instead like to substitute  "%c03" , "%T" for time of day, etc.  

Is there a general mechanism to do such a thing ?  I could not find anything in the docs or existing issues.

### Environment

- Oh my Posh version: 3.64.2
- Theme:
- Operating System: Windows
- Shell: tcsh
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
Top of my head I would say the text segment might be better suited for that. Although, if the shell itself substitutes those sequences once prompt is set, you could also use the properties prefix and postfix for example. Just double check if you need to escape the sequences correctly (percentage symbol is used in go as a means to replace text in strings on format).

**Comment by amoldeshpande** [comment]
Text segments  worked perfectly ! thank you !

**Comment by amoldeshpande** [comment]
did this stop working ? I was using `"text":"\0025c03"` in a text segment and it prints a blank now.

**Comment by JanDeDobbeleer** [comment]
@amoldeshpande don't think anything changed on that end.

**Comment by amoldeshpande** [comment]
hmm, I seem to be deliberately using an old version on my own computer anyway. So, the behavior might have changed long ago. oh well.
