### ISSUE TITLE
theme doesn't shows conda env name

### ISSUE THREAD

**Issue by lucasjinreal** [JanDeDobbeleer/oh-my-posh#2792]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Something new and amazing!

Sorry for bother again, I have tried all these 3 themes, none of themshows conda env name:

![Uploading image.png…]()

what should I do

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/190426267-3f4285cc-8130-4899-b2d3-984189b59d90.png)

**Comment by JanDeDobbeleer** [comment]
@jinfagang as the issue guide states, I need the output of `oh-my-posh debug` in this use-case. You can copy-paste the output here.

**Comment by lucasjinreal** [comment]
```
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 debug: User
Administrator
2022/09/15 22:47:52 User duration: 0s, args:
2022/09/15 22:47:52 debug: Host
TX-R90VB4H0
2022/09/15 22:47:52 Host duration: 0s, args:
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 519.2µs, args:
2022/09/15 22:47:52 Flags duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 debug: Getenv

2022/09/15 22:47:52 Getenv duration: 0s, args: SSH_CONNECTION
2022/09/15 22:47:52 debug: Getenv

2022/09/15 22:47:52 Getenv duration: 0s, args: SSH_CLIENT
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 debug: CommandPath
C:\Program Files\Git\cmd\git.exe
2022/09/15 22:47:52 CommandPath duration: 3.8281ms, args: git.exe
2022/09/15 22:47:52 HasCommand duration: 3.8281ms, args: git.exe
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/09/15 22:47:52 HasParentFilePath duration: 0s, args: .git
2022/09/15 22:47:52 Flags duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 ExecutionTime duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 Root duration: 54.3µs, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 Flags duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 Flags duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 PathSeparator duration: 0s, args:
2022/09/15 22:47:52 PathSeparator duration: 0s, args:
2022/09/15 22:47:52 PathSeparator duration: 0s, args:
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 IsWsl duration: 0s, args:
2022/09/15 22:47:52 StackCount duration: 0s, args:
2022/09/15 22:47:52 DirIsWritable duration: 506.4µs, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 debug: Pwd
C:\Users\Administrator
2022/09/15 22:47:52 Pwd duration: 0s, args:
2022/09/15 22:47:52 debug: Home
C:\Users\Administrator
2022/09/15 22:47:52 GOOS duration: 0s, args:
2022/09/15 22:47:52 ErrorCode duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 Shell duration: 0s, args:
2022/09/15 22:47:52 TemplateCache duration: 0s, args:
2022/09/15 22:47:52 debug: Getenv
C:\Users\Administrator\AppData\Local
2022/09/15 22:47:52 Getenv duration: 0s, args: LOCALAPPDATA
2022/09/15 22:47:52 CachePath duration: 529.9µs, args:
2022/09/15 22:47:52 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@jinfagang can I get the full output? This seems like only half of it.

**Comment by lucasjinreal** [comment]
does there a file saved? the terminal screen has a very long print

**Comment by JanDeDobbeleer** [comment]
@jinfagang you can pipe this to clip -> `oh-my-posh debug | clip`

**Comment by gf9276** [comment]
I'm having the same problem

**Comment by gf9276** [comment]
I use oh my posh on wsl

**Comment by JanDeDobbeleer** [comment]
@gf9276 same question as above, I need the logs otherwise this will get closed in a few days automatically.

**Comment by lucasjinreal** [comment]
don't matically, close it. I am too lazy to touch a log... but problem still un solved.

**Comment by gf9276** [comment]
> 
Thank you for your reply. The problem has been solved, most of the themes have not been added to the python segment, so the virtual environment of conda cannot be displayed, and I have made a little modification to its code.

**Comment by gf9276** [comment]
@JanDeDobbeleer Thank you for your reply. The problem has been solved, most of the themes have not been added to the python segment, so the virtual environment of conda cannot be displayed, and I have made a little modification to its code.

**Comment by lucasjinreal** [comment]
@gf9276 Can u verifed which theme have python segment? themes suggested by @JanDeDobbeleer certainly don't have .....

**Comment by gf9276** [comment]
@jinfagang I looked at the code for all the themes, night-owl is the most comprehensive.

**Comment by gf9276** [comment]
@jinfagang I looked at the code for all the themes, 'night-owl' is the most comprehensive.

**Comment by lucasjinreal** [comment]
OK, I given it up.. don't know what i missed here, but still none of theme shows conda env name.

![image](https://user-images.githubusercontent.com/21303438/190902919-41934c44-ff29-4113-98d0-4a3cadcdba64.png)

whats your promot looks like?

**Comment by gf9276** [comment]
Open wsl in windows terminal，like this. Seems like we're not using the same theme. Are you using 'night-owl.omp.json'?
![image](https://user-images.githubusercontent.com/45392113/190903695-e6902b38-0dc8-48c5-b342-cc222cd8fd06.png)

**Comment by JanDeDobbeleer** [comment]
@jinfagang you're not using a theme. The path you shared in `init` is incorrect.

**Comment by gf9276** [comment]
@jinfagang You can write a theme yourself, plus the segments you need. I found that arrows will have some bugs in vscode, like this:
![image](https://user-images.githubusercontent.com/45392113/190904281-f819283b-655d-472a-b3ee-ff3016876ac7.png)
So I rewrote a theme myself based on '1_shell', and I am using this.
![(W8S5COPKVX (S5BWL(T7SD](https://user-images.githubusercontent.com/45392113/190904339-8793af78-ad8b-4a82-a519-ab999a0be123.png)

**Comment by lucasjinreal** [comment]
@JanDeDobbeleer I am confused here:

![image](https://user-images.githubusercontent.com/21303438/190910824-4fb36690-e603-428e-842b-07df2048f038.png)


I set it `night-owl`.

why did  say not same theme?  @gf9276 can u try in Powershell? I am not using wsl.

**Comment by JanDeDobbeleer** [comment]
@jinfagang do you have the `$env:POSH_THEME_PATH` variable? It's either that or the path isn't accessible for oh-my-posh.

**Comment by gf9276** [comment]
@jinfagang i think you loss .omp......

**Comment by gf9276** [comment]
@jinfagang night-owl.omp.json, not night-owl.json

**Comment by lucasjinreal** [comment]
@gf9276 thanks for reminding this. Still can not see conda env names.

![image](https://user-images.githubusercontent.com/21303438/190911672-3773c58c-226f-4d10-b71c-b59b7b27c6ac.png)

**Comment by JanDeDobbeleer** [comment]
@jinfagang the default `display_mode` for python is `environment ` which is also true for night-owl. If you want to understand what oh-my-posh sees in your env, and why it displays what it does, make use of `oh-my-posh debug` and provide the full content of the logs here. Only then can I guide you to a solution. Python is the worst toolchain out there in terms of support so there are a ton of edge cases and bad practices which can influence the output.

**Comment by gf9276** [comment]
@jinfagang , When not using oh my posh, will power shell show the conda environment? Maybe you should use the anaconda prompt for conda operations. But I don't have conda installed on win, so I can't verify .

**Comment by lucasjinreal** [comment]
@gf9276 nop. without ph my posh also can not show

**Comment by gf9276** [comment]
@jinfagang It seems that it is normal that the conda environment is not displayed on the power shell，you should use anaconda prompt.

**Comment by gf9276** [comment]
@jinfagang  It seems that it is normal that the conda environment is not displayed on the power shell，you should use anaconda prompt.

**Comment by JanDeDobbeleer** [comment]
@gf9276 @jinfagang oh-my-posh can show the correct information, provided it's also available in the environment. Which is why I've been asking for the logs for a while now. So, if you care about finding out why and get to the bottom of this, you'll need to do a quick copy pasting instead of starting a mega thread into oblivion.

**Comment by gf9276** [comment]
@JanDeDobbeleer Yes, you are right.

**Comment by gf9276** [comment]
@jinfagang You had better provide logs, or you can try the following command.

Step 1:  Find and open Anaconda Prompt in the Anaconda directory of the start menu, input the command: 
```conda init --all```
Step 2: Reopen PowerShell, if there is a red letter error and you still do not enter the conda environment, then open PowerShell as an administrator and enter:  
```Set-ExecutionPolicy RemoteSigned```. 
Then select Y, reopen PowerShell, you can see the word (base) appears, enter conda activate XXX to enter the corresponding virtual environment.If this still doesn't work, you might as well provide a full diary

**Comment by gf9276** [comment]
@jinfagang You had better provide logs, or you can try the following command.

Step 1: Find and open Anaconda Prompt in the Anaconda directory of the start menu, input the command:
```conda init --all```
Step 2: Reopen PowerShell, if there is a red letter error and you still do not enter the conda environment, then open PowerShell as an administrator and enter:
```Set-ExecutionPolicy RemoteSigned```
Then select Y, reopen PowerShell, you can see the word (base) appears, enter conda activate XXX to enter the corresponding virtual environment.If this still doesn't work, you might as well provide a full logs.

**Comment by VVingerfly** [comment]
> 

`conda init --all` solved my problem. Thanks

**Comment by nowhereman1999** [comment]
> @jinfagang the default `display_mode` for python is `environment ` which is also true for night-owl. If you want to understand what oh-my-posh sees in your env, and why it displays what it does, make use of `oh-my-posh debug` and provide the full content of the logs here. Only then can I guide you to a solution. Python is the worst toolchain out there in terms of support so there are a ton of edge cases and bad practices which can influence the output.

Hi,I also meet this problem in powershell,and below is the output of `oh-my-posh debug | clip`:
[output.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/12523814/output.txt)
and my `profile.ps1` is shown below：
```
# posh-git (`Install-Module Posh-Git -Scope CurrentUser`)
# Import-Module Posh-Git

# Icons
Import-Module -Name Terminal-Icons

# Oh-My-Posh (`winget install oh-my-posh`)
# $env:POSH_GIT_ENABLED = $true
# oh-my-posh init pwsh --config $env:POSH_THEMES_PATH/kushal.omp.json | Invoke-Expression
oh-my-posh init pwsh --config $env:POSH_THEMES_PATH/powerlevel10k_rainbow.omp.json | Invoke-Expression


Set-PSReadLineOption -PredictionSource History # 设置预测文本来源为历史记录
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete # 设置 Tab 键补全
Set-PSReadLineKeyHandler -Chord "Ctrl+RightArrow" -Function ForwardWord # 设置 ctrl + 向右键逐字补全
Set-PSReadLineKeyHandler -Key "Ctrl+z" -Function Undo # 设置 Ctrl+z 为撤销
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward # 设置向上键为后向搜索历史记录
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward # 设置向下键为前向搜索历史纪录

# 3. 查看目录 ls & ll
function ListDirectory {
	(Get-ChildItem).Name
	Write-Host("")
}
Set-Alias -Name ls -Value ListDirectory
Set-Alias -Name ll -Value Get-ChildItem

# winget
Register-ArgumentCompleter -Native -CommandName winget -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
        [Console]::InputEncoding = [Console]::OutputEncoding = $OutputEncoding = [System.Text.Utf8Encoding]::new()
        $Local:word = $wordToComplete.Replace('"', '""')
        $Local:ast = $commandAst.ToString().Replace('"', '""')
        winget complete --word="$Local:word" --commandline "$Local:ast" --position $cursorPosition | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}

#Invoke-Expression (&starship init powershell)
```

**Comment by JanDeDobbeleer** [comment]
@Hezhexi2002 it would be good to update first. You're still on an older version.

**Comment by nowhereman1999** [comment]
> @Hezhexi2002 it would be good to update first. You're still on an older version.

The problem still exists after I upgrade it：
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/862310ce-ac95-4a52-a2d1-6ff831673887)

**Comment by JanDeDobbeleer** [comment]
@VVingerfly you're in the `HOME` folder though. The env name by default doesn't show in there (see `home_enabled`).

**Comment by nowhereman1999** [comment]
> @VVingerfly you're in the `HOME` folder though. The env name by default doesn't show in there (see `home_enabled`).

But the env name still not shown when I change to another folder instead of `HOME`:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/136c376e-2bd9-404f-8939-3904d2210e66)

**Comment by JanDeDobbeleer** [comment]
@Hezhexi2002 I see, and according to your previous debug log, I see you're using `powerlevel10k` which has fetching the virtual env [disabled](https://github.com/JanDeDobbeleer/oh-my-posh/blob/5637f34c42e04b12d04e2ea95f466e9498836324/themes/powerlevel10k_rainbow.omp.json#L96).

**Comment by nowhereman1999** [comment]
> @Hezhexi2002 I see, and according to your previous debug log, I see you're using `powerlevel10k` which has fetching the virtual env [disabled](https://github.com/JanDeDobbeleer/oh-my-posh/blob/5637f34c42e04b12d04e2ea95f466e9498836324/themes/powerlevel10k_rainbow.omp.json#L96).

so how could I change it to `True`?

**Comment by JanDeDobbeleer** [comment]
@Hezhexi2002 by reading the documentation on how to [adjust](https://ohmyposh.dev/docs/installation/customize#adjust-a-theme).

**Comment by nowhereman1999** [comment]
> @Hezhexi2002 by reading the documentation on how to [adjust](https://ohmyposh.dev/docs/installation/customize#adjust-a-theme).

ok,as you can see I have set the `fetch_virtual_env` to `true` but still the same：
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/bf6eb4c0-88ae-4a77-949a-331301b241e4)
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/1d21eeea-3a5b-4d0b-996a-6a4bede1d9ce)

**Comment by JanDeDobbeleer** [comment]
@Hezhexi2002 yes, but that's also in your HOME folder which is disabled by default as well.

**Comment by nowhereman1999** [comment]
> @Hezhexi2002 yes, but that's also in your HOME folder which is disabled by default as well.

but it didn't work even when I change the folder again:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/f3a21945-2a24-4314-8037-70c577a82378)

**Comment by JanDeDobbeleer** [comment]
@Hezhexi2002 we're going in circles here which is a bit annoying tbh, can you share the output of `oh-my-posh debug` in that folder?

**Comment by nowhereman1999** [comment]
> @Hezhexi2002 we're going in circles here which is a bit annoying tbh, can you share the output of `oh-my-posh debug` in that folder?

Sorry to anwser you so lately because I'm a little busy with school starting these days,here is the output of `oh-my-posh debug | clip` in that folder:
[output.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/12565262/output.txt)
Sorry again for bothering you for so long, I hope you can understand

**Comment by JanDeDobbeleer** [comment]
@Hezhexi2002 so, it seems only `CONDA_DEFAULT_ENV` has a value which is `base`. Your python segment's `template` however doesn't use the `.Venv` property so it will never show that value and on top of that your `display_mode` is files which doesn't show unless there are python files inside the folder you're in (which isn't the case). I suggest to change that to `context` and also include `{{ .Venv }}` in your template. Reading the [documentation](https://ohmyposh.dev/docs/segments/python) should also explain all of those things in detail.

**Comment by nowhereman1999** [comment]
@JanDeDobbeleer I hope you're doing well. I wanted to get back to you regarding the changes I made to my Oh My Posh configuration based on your advice like below：
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/83355aae-9ff7-4808-862f-4227cfa3c3c8)
They did help display the Conda virtual environment name, but I noticed a new quirk.

Now, the virtual environment name and Python version show up, but only when I navigate from my home directory to another directory within PowerShell. When I first launch PowerShell from my home directory, they don't appear until I change directories just like below：
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/ad76ea75-1551-4764-b318-9094c79aa4b6)
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/53631206/4e0ec967-1e4c-49b5-a7d1-c53e9a7267b2)
Is there a way to make them show up right from the start when I launch PowerShell, regardless of the directory I'm in? If you have any tips or ideas on how to achieve this, I'd really appreciate it.

Thanks again for your help and insights. Looking forward to your thoughts.

Best regards,
hezhexi2002

**Comment by JanDeDobbeleer** [comment]
> @Hezhexi2002 yes, but that's also in your HOME folder which is disabled by default as well.

@Hezhexi2002 as stated above, to have this visible in the home folder, you need to also add `"home_enabled": true` to the segment's `properties`.
