### ISSUE TITLE
Add WSL indication segment

### ISSUE THREAD

**Issue by JanDeDobbeleer** [JanDeDobbeleer/oh-my-posh#28]
Goal: a segmnet that shows you're inside the WSL. There should be an evironment variable we can use: `WSL_DISTRO_NAME`. If that one's set, you know you're inside of the WSL.

**Comment by nwykes** [comment]
Do you think adding some kind of indicator or the WSL Distro Name to the os segment would be a solution to this?  Or should it be it's own segment?

**Comment by JanDeDobbeleer** [comment]
@nwykes yes, that's actually a good idea. What I'd do in that could something along these lines (peudo).

```go
switch os {
    case wsl:
        return WSLIcon + distroname
    case unix:
        return UnixIcon // (map to DistroIcon?)
    case windows:
        return WindowIcon
    case darwin:
        return MacOSIcon
}
```

I would always give the default value a string value, as in for WindowsIcon return "Windows" of not set etc...
That way it always works regardless of the font that was being used at the time of development (unless we make it a requirement to always use Meslo).

**Comment by nwykes** [comment]
Is there a standard "WSL" icon?  I'm not seeing one in nerdfonts.

**Comment by JanDeDobbeleer** [comment]
Not really, we could default to a Windows icon maybe.

**Comment by nwykes** [comment]
Sounds good.  "Windows Icon - Distro Name" or "Windows Icon - Distro Icon" when we have that support in the os segment.

**Comment by nwykes** [comment]
let me know if this concept works for this.  still need to work on the distro specific icons.

![image](https://user-images.githubusercontent.com/593993/95605961-e9066200-0a16-11eb-8044-30f2c99f3b8c.png)

probably more props like wsl_separator could be added

**Comment by JanDeDobbeleer** [comment]
Yup. I would just use `fmt.Sprintf` to return the string and default to "WSL" rather than an icon.
