### ISSUE TITLE
Tooltips are broken in zsh v5.9

### ISSUE THREAD

**Issue by lewis-yeung** [JanDeDobbeleer/oh-my-posh#2827]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Tooltips work fine in zsh v5.8 but are broken in zsh v5.9, with **any versions of OMP**.

![bug](https://user-images.githubusercontent.com/83903009/192086370-3401c7dc-fb2b-4634-83e9-291e181444f3.png)

As shown in the screenshot, when a tooltip is rendered:

1. It was not right-aligned as expected.
2. The cursor moved to the beginning of the line which is a wrong position.

### Theme

(Not related to a specific theme config.)

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

(N/A)

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung and rprompt works? Because in zsh we have a native rprompt that we replace. So placement should be a zsh responsibility. I'll have a glance layer today.

**Comment by lewis-yeung** [comment]
> and rprompt works?

@JanDeDobbeleer I've just tested it and it didn't work properly.

![rprompt_bug](https://user-images.githubusercontent.com/83903009/192096554-9e3eb460-214f-43f0-869d-194e3a51dfcb.png)

However, it works without OMP enabled.

![rprompt_normal](https://user-images.githubusercontent.com/83903009/192096559-a8077c40-d965-46ca-994a-7354f0f57612.png)

**Comment by lewis-yeung** [comment]
Did some further testing just now. It seems that there are so many problems with zsh v5.9. I've rolled back to v5.8. 🤦🏻‍♂️

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung so they did something different with rprompt or they have a bug 😅. I didn't see anything in the docs. 

I don't think we escape the rprompt. Maybe that's the issue now, otherwise I don't immediately understand how a plain string and our string can have a different behavior.

**Comment by lewis-yeung** [comment]
I'm closing this as we have nothing to do on our side, at least for the time being. I would recommend using zsh v5.8 for the moment. It can be reopened if someone has found a new idea.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I was looking for the zsh issue tracker (doesn't seem to be on GitHub, nor on sourceforge) to find some similar bug reports.
