### ISSUE TITLE
home_icon incorrectly used for all folders starting with $HOME

### ISSUE THREAD

**Issue by MorganAntonsson** [JanDeDobbeleer/oh-my-posh#2832]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

If a user has the username 'user', _home_icon_ will be displayed for all home folders starting with 'user'.

**Example:**
-   /home/user → ~ (correct)
-   /home/user1 → ~1 (incorrect)
-   /home/user-xyz → ~-xyz (incorrect)

![oh-my-posh-bug](https://user-images.githubusercontent.com/4224317/192157821-49f0760a-b940-4206-b2c7-10db83b4c10e.png)

### Theme

Default

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
-
```

**Comment by JanDeDobbeleer** [comment]
@MorganAntonsson correct, it's a startswith but should include the path separator. Good catch.
