### ISSUE TITLE
Vertical offset issue in iTerm2

### ISSUE THREAD

**Issue by lnu** [JanDeDobbeleer/oh-my-posh#284]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

Vertical offset issue in iTerm2

### Environment

- Oh my Posh version: 3.65.0
- Theme: default
- Operating System: macOs 10.15.7
- Shell: zsh/powershell 7
- Terminal: iTerm2 3.4.3

### Steps to Reproduce

Check the prompt an you'll see a vertical alignement issue on both leading_diamond and trailing_diamond

**Expected behavior:** Same alignment for diamond and other blocks

**Actual behavior:** Small vertical offset between diamond and other blocks

<img width="953" alt="Screenshot 2020-12-27 at 21 15 05" src="https://user-images.githubusercontent.com/1829553/103179175-7aa0a580-4889-11eb-91ad-0ae20b46e33d.png">
<img width="962" alt="Screenshot 2020-12-27 at 21 16 30" src="https://user-images.githubusercontent.com/1829553/103179176-7d02ff80-4889-11eb-8d62-8a2efe3c6d77.png">

**Comment by JanDeDobbeleer** [comment]
@lnu that's not an oh-my-posh issue but rather terminal/font related. I've seen this pop up even since V2 and changing the font/size/terminal always resolves the issue.

EDIT: if you look at the code there's nothing being done that results in something like this. All it does is print the character.

**Comment by lnu** [comment]
I'm almost sure I never seen this before. I only noticed this recently with iTerm2.  
Let's close the issue.
