### ISSUE TITLE
Disable automatic transient prompt

### ISSUE THREAD

**Issue by SPFabGerman** [JanDeDobbeleer/oh-my-posh#2848]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The current way transient prompt are handeled slightly conflicts with the rest of my configuration. (I use zsh by the way.) Specifically the way transient prompts are enabled with `zle -N zle-line-init _posh-zle-line-init`, which conflicts with `add-zle-hook-widget`.
This wasn't a problem in earlier versions, since I could just enable transient prompts manually with `add-zle-hook-widget zle-line-init _posh-zle-line-init`. This changed however recently and now transient prompts are enabled automatically, which leads to the above conflict.
I would like it if there was a way to disable automatic transient prompt, while still having a transient prompt configured. I believe the easiest way to achieve this would be with a command line option.

**Comment by JanDeDobbeleer** [comment]
@SPFabGerman are you using the transient prompt for other shells then?

**Comment by SPFabGerman** [comment]
@JanDeDobbeleer I'm only using zsh, no other shells at the moment.

**Comment by JanDeDobbeleer** [comment]
@SPFabGerman then why can't you edit the configuration to not include a transient prompt?

**Comment by JanDeDobbeleer** [comment]
@SPFabGerman ok, I misinterpreted this. Can't we change the script so it's compatible with your setup? I don't want to start exposing internal API's (which is what you abused).

**Comment by JanDeDobbeleer** [comment]
When #2869 lands you can initialise with the `--manual` flag: `oh-my-posh init zsh --manual`
