### ISSUE TITLE
cannot get version

### ISSUE THREAD

**Issue by x0341** [JanDeDobbeleer/oh-my-posh#2854]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

cannot get version, oh-my-posh and posh-git both install in system (Ubuntu WSL and Windows 11)

![image](https://user-images.githubusercontent.com/1771943/193152245-68dda7ec-fb18-45bf-894a-c588ac493ecc.png)

### Theme

night-owl.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```Shell
no log.
See image attached.
```

**Comment by JanDeDobbeleer** [comment]
@x0341 the logs are needed for me to find out why it can't parse the version.

**Comment by BoseSj** [comment]
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct
> 
> ### What happened?
> A bug happened!
> 
> cannot get version, oh-my-posh and posh-git both install in system (Ubuntu WSL and Windows 11)
> 
> ![image](https://user-images.githubusercontent.com/1771943/193152245-68dda7ec-fb18-45bf-894a-c588ac493ecc.png)
> 
> ### Theme
> night-owl.omp.json
> 
> ### What OS are you seeing the problem on?
> Windows
> 
> ### Which shell are you using?
> bash
> 
> ### Log output
> ```shell
> no log.
> See image attached.
> ```

have u run `oh-my-posh debug` in the terminal to get the logs

**Comment by JanDeDobbeleer** [comment]
No logs provided.
