### ISSUE TITLE
Hiding segments with array-based templates

### ISSUE THREAD

**Issue by daniel-liuzzi** [JanDeDobbeleer/oh-my-posh#2859]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

According to the [docs](https://ohmyposh.dev/docs/configuration/templates#hiding-segments):

> To hide a whole segment including the leading and trailing symbol based on a template, the template must render into an empty string.

This works beautifully in single-string templates. For instance:

```json
{
    "template": "{{ if <false> }} foo {{ end }}{{ if <false> }} bar {{ end }}{{ if <false> }} baz {{ end }}"
}
```

The above results in the entire segment disappearing, which is great.

Now, if I convert the template to an array:

```json
{
    "templates": [
        "{{ if <false> }} foo {{ end }}",
        "{{ if <false> }} bar {{ end }}",
        "{{ if <false> }} baz {{ end }}"
    ]
}
```

The segment becomes visible no matter what. Oh My Posh seems to fall back to the default template. It would be nice if array-based templates also allowed showing/hiding segments. They're significantly more maintainable that their oneliner counterparts.

**Comment by JanDeDobbeleer** [comment]
This needs another fix as it's by design right now.
