### ISSUE TITLE
Official Options for Background Initialization

### ISSUE THREAD

**Issue by jhigh2000** [JanDeDobbeleer/oh-my-posh#2861]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I stumbled upon this blog post [PowerShell Profile Instant Prompt](https://sidneys1.com/programming/2022/09/29/powershell-profile-instant-prompt.html) which discusses a technique for background initialization of oh-my-posh for a quicker first run experience.

Would it be feasible to add a background initialization option  like ```--background``` to the oh-my-posh process that would essentially accomplish the same thing, but natively?

**Comment by JanDeDobbeleer** [comment]
@jhigh2000 I also read it. The thing is, the load time is a PowerShell Core issue. As soon as it needs to load some modules, call an executable, things are slowing down significantly. I'll have a look to play around with it, but I'm not sure this can or should be solved by us. In the end, adding PowerShell code to the `$PROFILE` directly will always be faster and we can't do that for you.

**Comment by jhigh2000** [comment]
Understood. Thanks for your time and for looking at it, but if it doesn't make sense then by all means please close this request!

**Comment by JanDeDobbeleer** [comment]
I just had a quick test, for both commands (indicated in the post as well), oh-my-posh uses 20ms. This implies that the timing issue is a PowerShell one. We can't solve that.
