### ISSUE TITLE
$LASTEXITCODE does not preserve its value in PowerShell

### ISSUE THREAD

**Issue by peetrike** [JanDeDobbeleer/oh-my-posh#288]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [ ] I looked for duplicate issues before submitting this one

### Description

When previous command exits with non-zero return code, the prompt function restores it too early so later commands will change it. The restoring of variable value should be the last command in prompt function. 

### Environment

- Oh my Posh version: 3.59.0
- Theme: doesn't make difference
- Operating System: Windows 10
- Shell: PowerShell (5.1 and 7.1)
- Terminal: Windows Terminal

### Steps to Reproduce

1. [First Step]
   ```
   ping.exe doesnotexist
   $LASTEXITCODE
   ```

**Expected behavior:** [What you expected to happen]
1

**Actual behavior:** [What actually happened]
0

**Comment by tradiff** [comment]
Ah, yep I am able to reproduce this only when I'm in a folder that contains a git repository. Maybe we can move `Set-GitStatus` to be before the restoring of `$LASTEXITCODE`

**Comment by peetrike** [comment]
put the restoring of $LASTEXITCODE as last line in prompt function.  That should fix it
