### ISSUE TITLE
Connection segment: '{{ .ReceiveRate }}' return value

### ISSUE THREAD

**Issue by nixeo** [JanDeDobbeleer/oh-my-posh#2894]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

{{ .ReceiveRate }} for connection segment (OMP v12) return incorrect value?

**OMP v12**:
```
"template": "{{ if eq .Type \"wifi\"}}\uf1eb  {{ .ReceiveRate }} Mbps\uf9c4{{ else if eq .Type \"ethernet\"}}\uf6ff{{ end }}",
"type": "connection"
```

![Screenshot 2022-10-06 102241](https://user-images.githubusercontent.com/21344555/194200142-613f078d-6fff-4a89-85ea-b248c5a25180.png)

**OMP v11.4**:
```
"template": "\uFAA8 {{ .Signal }}% \uf05a {{ .ReceiveRate }}Mbps\uf9c4",
"type": "wifi"
```

![Screenshot 2022-10-06 102907](https://user-images.githubusercontent.com/21344555/194200867-de54862c-41e7-4d51-b7e4-fa5e6b26046f.png)

### Theme

custom

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
-
```

**Comment by JanDeDobbeleer** [comment]
@nixeo that's bps, so you can round however you want.
