### ISSUE TITLE
Prompt decoration not remaining for previous lines

### ISSUE THREAD

**Issue by KevinGossentCap** [JanDeDobbeleer/oh-my-posh#2895]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Using Windows 10
I recently upgraded from old v3 using powershell modules to new exec from microsoft store.
I then discovered that the decorations of themes that previously remained from line to line (location, time, error status etc.) now disappear for previous lines and remains only on latest line
![Capture d’écran 2022-10-06 094445](https://user-images.githubusercontent.com/20575643/194247741-a9f3d7e5-06a2-456d-8e77-963afbc75473.png)
![Capture d’écran 2022-10-06 094450](https://user-images.githubusercontent.com/20575643/194247764-0cf035ae-11a4-43f0-910a-14960cb5e4fc.png)
I definitely liked to have previous decorations still there to come back and see some informations (previous location, previous execution time etc.)

### Theme

slimfat

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Version: 9.0.0

Segments:

ConsoleTitle(true)   -   0 ms - pwsh :: kgossent
os(true)             -   0 ms - ▓  
session(true)        -   0 ms -  kgossentLFR035928 
root(false)          -   0 ms -
path(true)           -   0 ms -   ~
git(false)           -   8 ms -
text(false)          -   2 ms -
text(false)          -   0 ms -
node(false)          -   0 ms -
python(false)        -   0 ms -
dotnet(false)        -   0 ms -
time(true)           -   0 ms -  09:46:52  ▓
text(true)           -   0 ms -  ~#@❯
text(true)           -   0 ms -  ❮
executiontime(false) -   0 ms -
exit(true)           -   0 ms -  

Run duration: 42.0054ms

Cache path: C:\Users\kgossent\AppData\Local\oh-my-posh

Config path: C:\Users\kgossent\slimfat.omp.json

Logs:

2022/10/06 09:46:52 debug: Getenv
C:\Users\kgossent\AppData\Local
2022/10/06 09:46:52 Getenv duration: 2.7371ms, args: LOCALAPPDATA
2022/10/06 09:46:52 CachePath duration: 2.7371ms, args:
2022/10/06 09:46:52 debug: Getenv
C:\Users\kgossent\slimfat.omp.json
2022/10/06 09:46:52 Getenv duration: 0s, args: POSH_THEME
2022/10/06 09:46:52 Shell duration: 16.5404ms, args:
2022/10/06 09:46:52 resolveConfigPath duration: 16.5404ms, args:
2022/10/06 09:46:52 Init duration: 27.3668ms, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 config.loadConfig duration: 1.1726ms, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 debug: Getenv

2022/10/06 09:46:52 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/10/06 09:46:52 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC40078D7
2022/10/06 09:46:52 Root duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 ErrorCode duration: 0s, args:
2022/10/06 09:46:52 IsWsl duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: User
kgossent
2022/10/06 09:46:52 User duration: 0s, args:
2022/10/06 09:46:52 debug: Host
LFR035928
2022/10/06 09:46:52 Host duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: Getenv

2022/10/06 09:46:52 Getenv duration: 0s, args: SSH_CONNECTION
2022/10/06 09:46:52 debug: Getenv

2022/10/06 09:46:52 Getenv duration: 0s, args: SSH_CLIENT
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 Root duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 PathSeparator duration: 0s, args:
2022/10/06 09:46:52 PathSeparator duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 IsWsl duration: 0s, args:
2022/10/06 09:46:52 StackCount duration: 0s, args:
2022/10/06 09:46:52 DirIsWritable duration: 46.3µs, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: CommandPath
c:\KGO_Tools\Git\cmd\git.exe
2022/10/06 09:46:52 CommandPath duration: 8.3222ms, args: git.exe
2022/10/06 09:46:52 HasCommand duration: 8.3222ms, args: git.exe
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/10/06 09:46:52 HasParentFilePath duration: 0s, args: .git
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 debug: Getenv

2022/10/06 09:46:52 Getenv duration: 0s, args: VIRTUAL_ENV
2022/10/06 09:46:52 debug: Getenv

2022/10/06 09:46:52 Getenv duration: 0s, args: CONDA_ENV_PATH
2022/10/06 09:46:52 debug: Getenv

2022/10/06 09:46:52 Getenv duration: 0s, args: CONDA_DEFAULT_ENV
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 ExecutionTime duration: 0s, args:
2022/10/06 09:46:52 debug: Pwd
C:\Users\kgossent
2022/10/06 09:46:52 Pwd duration: 0s, args:
2022/10/06 09:46:52 debug: Home
C:\Users\kgossent
2022/10/06 09:46:52 GOOS duration: 0s, args:
2022/10/06 09:46:52 ErrorCode duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 Shell duration: 0s, args:
2022/10/06 09:46:52 TemplateCache duration: 0s, args:
2022/10/06 09:46:52 debug: Getenv
C:\Users\kgossent\AppData\Local
2022/10/06 09:46:52 Getenv duration: 0s, args: LOCALAPPDATA
2022/10/06 09:46:52 CachePath duration: 0s, args:
2022/10/06 09:46:52 Flags duration: 0s, args:
```

**Comment by KevinGossentCap** [comment]
I've just seen that I used normal installer and upgraded to version 12.
Nevertheless, all still remains the same.

Here is the new log

Version: 12.0.0

Segments:

ConsoleTitle(true)   -   1 ms - pwsh :: kgossent
os(true)             -   0 ms - ▓  
session(true)        -   1 ms -  kgossentLFR035928 
root(false)          -   0 ms -
path(true)           -   0 ms -   ~
git(false)           -   9 ms -
text(false)          -   0 ms -
text(false)          -   0 ms -
node(false)          -   0 ms -
python(false)        -   0 ms -
dotnet(false)        -   0 ms -
time(true)           -   0 ms -  09:58:17  ▓
text(true)           -   0 ms -  ~#@❯
text(true)           -   0 ms -  ❮
executiontime(false) -   0 ms -
exit(true)           -   0 ms -  

Run duration: 47.9825ms

Cache path: C:\Users\kgossent\AppData\Local\oh-my-posh

Config path: C:\Users\kgossent\Documents\PowerShell\themes\slimfat.omp.json

Logs:

2022/10/06 09:58:17 debug: Getenv
C:\Users\kgossent\AppData\Local
2022/10/06 09:58:17 Getenv duration: 0s, args: LOCALAPPDATA
2022/10/06 09:58:17 CachePath duration: 0s, args:
2022/10/06 09:58:17 debug: Getenv
C:\Users\kgossent\Documents\PowerShell\themes\slimfat.omp.json
2022/10/06 09:58:17 Getenv duration: 0s, args: POSH_THEME
2022/10/06 09:58:17 debug: Shell
process name: pwsh.exe
2022/10/06 09:58:17 Shell duration: 20.8676ms, args:
2022/10/06 09:58:17 resolveConfigPath duration: 20.8676ms, args:
2022/10/06 09:58:17 Init duration: 31.8152ms, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 config.loadConfig duration: 1.063ms, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 debug: Getenv

2022/10/06 09:58:17 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/10/06 09:58:17 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC40078D7
2022/10/06 09:58:17 Root duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 ErrorCode duration: 0s, args:
2022/10/06 09:58:17 IsWsl duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: User
kgossent
2022/10/06 09:58:17 User duration: 0s, args:
2022/10/06 09:58:17 debug: Host
LFR035928
2022/10/06 09:58:17 Host duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 513.9µs, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: Getenv

2022/10/06 09:58:17 Getenv duration: 0s, args: SSH_CONNECTION
2022/10/06 09:58:17 debug: Getenv

2022/10/06 09:58:17 Getenv duration: 0s, args: SSH_CLIENT
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 Root duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 PathSeparator duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 PathSeparator duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 PathSeparator duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 PathSeparator duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 PathSeparator duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 IsWsl duration: 0s, args:
2022/10/06 09:58:17 StackCount duration: 0s, args:
2022/10/06 09:58:17 DirIsWritable duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: CommandPath
c:\KGO_Tools\Git\cmd\git.exe
2022/10/06 09:58:17 CommandPath duration: 8.861ms, args: git.exe
2022/10/06 09:58:17 HasCommand duration: 8.861ms, args: git.exe
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/10/06 09:58:17 HasParentFilePath duration: 517µs, args: .git
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 debug: Getenv

2022/10/06 09:58:17 Getenv duration: 0s, args: VIRTUAL_ENV
2022/10/06 09:58:17 debug: Getenv

2022/10/06 09:58:17 Getenv duration: 0s, args: CONDA_ENV_PATH
2022/10/06 09:58:17 debug: Getenv

2022/10/06 09:58:17 Getenv duration: 0s, args: CONDA_DEFAULT_ENV
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 Flags duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 ExecutionTime duration: 0s, args:
2022/10/06 09:58:17 debug: Pwd
C:\Users\kgossent
2022/10/06 09:58:17 Pwd duration: 0s, args:
2022/10/06 09:58:17 debug: Home
C:\Users\kgossent
2022/10/06 09:58:17 GOOS duration: 0s, args:
2022/10/06 09:58:17 ErrorCode duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 Shell duration: 0s, args:
2022/10/06 09:58:17 TemplateCache duration: 0s, args:
2022/10/06 09:58:17 debug: Getenv
C:\Users\kgossent\AppData\Local
2022/10/06 09:58:17 Getenv duration: 0s, args: LOCALAPPDATA
2022/10/06 09:58:17 CachePath duration: 0s, args:
2022/10/06 09:58:17 Flags duration: 0s, args:

**Comment by JanDeDobbeleer** [comment]
@KevinGossentCap this is by design as the config you use has a [transient prompt](https://ohmyposh.dev/docs/configuration/transient). If you want to use the config without making a local modification, you can initialize with the `--manual` flag.

**Comment by KevinGossentCap** [comment]
@JanDeDobbeleer Strangely, using the --manual flag doesn't change a thing.
removing the Invoke-Expression at the end gives me the command passed and it's the same with or without the --manual
![Capture d’écran 2022-10-06 102424](https://user-images.githubusercontent.com/20575643/194261189-8b606222-d267-4924-93ba-7da18c54e81e.png)
I'll edit local theme file in the meantime (I suspect it only needs to remove the transient_prompt part)

**Comment by JanDeDobbeleer** [comment]
@KevinGossentCap did you restart the shell? You need to adjust this in your `$PROFILE` and restart the shell:

````
oh-my-posh init pwsh -c '~/Documents/PowerShell/themes/slimfat.omp.json' -m | Invoke-Expression
````

**Comment by KevinGossentCap** [comment]
Yes I confirm.
I have this in my profile file
`oh-my-posh init pwsh -c '~\Documents\PowerShell\themes\slimfat.omp.json' --manual | Invoke-Expression`
but it does not inactivate transient
I tested also with -m => no difference
I restart shell after each modification (and removing the transient_prompt from the json works as I see again after shell restart)

**Comment by JanDeDobbeleer** [comment]
I know why the flag doesn't work for PowerShell. It needs to be passed along to the print function. Will fix that.

**Comment by KevinGossentCap** [comment]
I confirm that the fix is fixing the issue (I can put --manual and let the transient_prompt present in the theme file) :)
