### ISSUE TITLE
Night Owl Theme Stuck in omp 12.0.1

### ISSUE THREAD

**Issue by swojit** [JanDeDobbeleer/oh-my-posh#2899]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Night-Owl gets stuck with Get-PoshThemes and init in $profile. 

### Theme

night-owl

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Invalid syntax.
```

**Comment by JanDeDobbeleer** [comment]
@swojit this is impossible for me to reproduce.

Can I propose to remove segment per segment until you find the culprit?
