### ISSUE TITLE
oh-my-posh in Package Console of Visual Studio

### ISSUE THREAD

**Issue by digitalsigi** [JanDeDobbeleer/oh-my-posh#2904]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Packagae Manager Console in Visual Studio looks not very good after install of oh-my-posh:

`Profile executed
Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 6.3.0.131

Type 'get-help NuGet' to see all available NuGet commands.

[38;2;243;174;53m[0m[48;2;243;174;53m[38;2;38;43;68m jbogad [0m[38;2;243;174;53m[0m[38;2;240;118;35;49m[7m[0m[48;2;240;118;35m[38;2;224;222;244m  ]8;;file:C:\GITatUHU\rvsweb\rvsweb]8;;\ [0m[48;2;89;201;165m[38;2;240;118;35m[0m[48;2;89;201;165m[38;2;38;43;68m release/1.16.0 ≢ [0m[38;2;89;201;165m[0m[38;2;75;149;233;49m[7m[0m[48;2;75;149;233m[38;2;224;222;244m  [0m[38;2;75;149;233m[0m[K[0J[K[0J]0;pwsh in rvsweb[0m 7[1000C[19D[38;2;224;222;244min [0m[38;2;75;149;233m[1mpwsh[22m[0m[38;2;224;222;244m [0m[38;2;224;222;244mat [0m[38;2;75;149;233m[1m13:10:24[22m[0m8 
[38;2;243;174;53m[0m[48;2;243;174;53m[38;2;38;43;68m jbogad [0m[38;2;243;174;53m[0m[38;2;240;118;35;49m[7m[0m[48;2;240;118;35m[38;2;224;222;244m  ]8;;file:C:\GITatUHU\rvsweb\rvsweb]8;;\ [0m[48;2;89;201;165m[38;2;240;118;35m[0m[48;2;89;201;165m[38;2;38;43;68m release/1.16.0 ≢ [0m[38;2;89;201;165m[0m[38;2;75;149;233;49m[7m[0m[48;2;75;149;233m[38;2;224;222;244m  [0m[38;2;75;149;233m[0m[K[0J[K[0J]0;pwsh in rvsweb[0m 7[1000C[19D[38;2;224;222;244min [0m[38;2;75;149;233m[1mpwsh[22m[0m[38;2;224;222;244m [0m[38;2;224;222;244mat [0m[38;2;75;149;233m[1m13:10:48[22m[0m8 `

### Theme

No idea

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
No idea where to get it
```

**Comment by JanDeDobbeleer** [comment]
@digitalsigi this is a bug for the console application as it does not support ANSI. Please pick this up with the Visual Studio team.

**Comment by digitalsigi** [comment]
OK, thanks, I'll do that
