### ISSUE TITLE
Scoop install failed for 12.1.0

### ISSUE THREAD

**Issue by bruegth** [JanDeDobbeleer/oh-my-posh#2927]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Installing 'oh-my-posh' (12.1.0) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v12.1.0/posh-windows-amd64.7z is not valid

### Theme

N.N.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N.N.
```

**Comment by JanDeDobbeleer** [comment]
@bruegth yes, the binary didn't get uploaded. I tried to remove and upload again but GitHub fails me.

**Comment by JanDeDobbeleer** [comment]
fixed
