### ISSUE TITLE
Segments do not have any color formatting in console

### ISSUE THREAD

**Issue by AlexMilender** [JanDeDobbeleer/oh-my-posh#2963]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Thanks for all your great work on this tool!

Segments do not have any color or formatting in console, but color and formatting does exist in debug output.

![image](https://user-images.githubusercontent.com/66804056/196333098-e32e5d5a-a7eb-4dd5-b999-36c422326499.png)

Un-installing and re-installing Powershell 7 has no effect

### Theme

my-posh init pwsh --config "$env:POSH_THEMES_PATH/jandedobbeleer.omp.json" | Invoke-Expression

Note: No changes have been made to this theme, changing themes has no positive effect

{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "alignment": "left",
      "segments": [
        {
          "background": "#c386f1",
          "foreground": "#ffffff",
          "leading_diamond": "\ue0b6",
          "style": "diamond",
          "template": " {{ .UserName }} ",
          "trailing_diamond": "\ue0b0",
          "type": "session"
        },
        {
          "background": "#ff479c",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "folder_separator_icon": " \ue0b1 ",
            "home_icon": "~",
            "style": "folder"
          },
          "style": "powerline",
          "template": " \uf74a  {{ .Path }} ",
          "type": "path"
        },
        {
          "background": "#fffb38",
          "background_templates": [
            "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
            "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
            "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
            "{{ if gt .Behind 0 }}#B388FF{{ end }}"
          ],
          "foreground": "#193549",
          "leading_diamond": "\ue0b6",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "branch_max_length": 25,
            "fetch_stash_count": true,
            "fetch_status": true,
            "fetch_upstream_icon": true
          },
          "style": "powerline",
          "template": " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} ",
          "trailing_diamond": "\ue0b4",
          "type": "git"
        },
        {
          "background": "#6CA35E",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \uf898 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} ",
          "type": "node"
        },
        {
          "background": "#8ED1F7",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "go"
        },
        {
          "background": "#4063D8",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue624 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "julia"
        },
        {
          "background": "#FFDE57",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_mode": "files",
            "fetch_virtual_env": false
          },
          "style": "powerline",
          "template": " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "python"
        },
        {
          "background": "#AE1401",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_mode": "files",
            "fetch_version": true
          },
          "style": "powerline",
          "template": " \ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "ruby"
        },
        {
          "background": "#FEAC19",
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_mode": "files",
            "fetch_version": false
          },
          "style": "powerline",
          "template": " \uf0e7{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} ",
          "type": "azfunc"
        },
        {
          "background_templates": [
            "{{if contains \"default\" .Profile}}#FFA400{{end}}",
            "{{if contains \"jan\" .Profile}}#f1184c{{end}}"
          ],
          "foreground": "#ffffff",
          "powerline_symbol": "\ue0b0",
          "properties": {
            "display_default": false
          },
          "style": "powerline",
          "template": " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} ",
          "type": "aws"
        },
        {
          "background": "#ffff66",
          "foreground": "#111111",
          "powerline_symbol": "\ue0b0",
          "style": "powerline",
          "template": " \uf0ad ",
          "type": "root"
        },
        {
          "background": "#83769c",
          "foreground": "#ffffff",
          "properties": {
            "always_enabled": true
          },
          "style": "plain",
          "template": "<transparent>\ue0b0</> \ufbab{{ .FormattedMs }}\u2800",
          "type": "executiontime"
        },
        {
          "background": "#00897b",
          "background_templates": [
            "{{ if gt .Code 0 }}#e91e63{{ end }}"
          ],
          "foreground": "#ffffff",
          "properties": {
            "always_enabled": true
          },
          "style": "diamond",
          "template": "<parentBackground>\ue0b0</> \ue23a ",
          "trailing_diamond": "\ue0b4",
          "type": "exit"
        }
      ],
      "type": "prompt"
    },
    {
      "segments": [
        {
          "background": "#0077c2",
          "foreground": "#ffffff",
          "style": "plain",
          "template": "<#0077c2,transparent>\ue0b6</> \uf489 {{ .Name }} <transparent,#0077c2>\ue0b2</>",
          "type": "shell"
        },
        {
          "background": "#1BD760",
          "foreground": "#111111",
          "invert_powerline": true,
          "powerline_symbol": "\ue0b2",
          "properties": {
            "paused_icon": "\uf04c ",
            "playing_icon": "\uf04b "
          },
          "style": "powerline",
          "template": " \uf167 {{ .Icon }}{{ if ne .Status \"stopped\" }}{{ .Artist }} - {{ .Track }}{{ end }} ",
          "type": "ytm"
        },
        {
          "background": "#f36943",
          "background_templates": [
            "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
            "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
            "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
          ],
          "foreground": "#ffffff",
          "invert_powerline": true,
          "powerline_symbol": "\ue0b2",
          "properties": {
            "charged_icon": "\ue22f ",
            "charging_icon": "\ue234 ",
            "discharging_icon": "\ue231 "
          },
          "style": "powerline",
          "template": " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 ",
          "type": "battery"
        },
        {
          "background": "#2e9599",
          "foreground": "#111111",
          "invert_powerline": true,
          "leading_diamond": "\ue0b2",
          "style": "diamond",
          "template": " {{ .CurrentDate | date .Format }} ",
          "trailing_diamond": "\ue0b4",
          "type": "time"
        }
      ],
      "type": "rprompt"
    }
  ],
  "console_title_template": "{{ .Shell }} in {{ .Folder }}",
  "final_space": true,
  "version": 2
}

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
 am89954    ~  ﮫ0ms⠀   oh-my-posh debug                                                                            pwsh   100  22:57:33 

Version: 12.3.3

Segments:

ConsoleTitle(true)   -   0 ms - pwsh in am89954
session(true)        -   0 ms -  am89954 
path(true)           -   0 ms -    ~
git(false)           -  20 ms -
node(false)          -   0 ms -
go(false)            -   0 ms -
julia(false)         -   0 ms -
python(false)        -   0 ms -
ruby(false)          -   0 ms -
azfunc(false)        -   0 ms -
aws(false)           -   0 ms -
root(false)          -   0 ms -
executiontime(true)  -   1 ms -  ﮫ0ms⠀
exit(true)           -   1 ms -   
shell(true)          -   0 ms -   pwsh 
ytm(false)           -  20 ms -
battery(true)        -  15 ms -   100
time(true)           -   0 ms -  22:57:39 

Run duration: 81.4708ms

Cache path: C:\Users\am89954\AppData\Local\oh-my-posh

Config path: C:\Users\am89954\AppData\Local\Programs\oh-my-posh\themes\jandedobbeleer.omp.json

Logs:

2022/10/17 22:57:39 debug: Getenv
C:\Users\am89954\AppData\Local
2022/10/17 22:57:39 Getenv duration: 0s, args: LOCALAPPDATA
2022/10/17 22:57:39 CachePath duration: 0s, args:
2022/10/17 22:57:39 debug: Getenv
C:\Users\am89954\AppData\Local\Programs\oh-my-posh\themes\jandedobbeleer.omp.json
2022/10/17 22:57:39 Getenv duration: 0s, args: POSH_THEME
2022/10/17 22:57:39 debug: Shell
process name: pwsh.exe
2022/10/17 22:57:39 Shell duration: 13.4988ms, args:
2022/10/17 22:57:39 resolveConfigPath duration: 13.4988ms, args:
2022/10/17 22:57:39 Init duration: 16.9491ms, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
2022/10/17 22:57:39 config.loadConfig duration: 2.8028ms, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: OMP_CACHE_DISABLED
2022/10/17 22:57:39 WindowsRegistryKeyValue duration: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC44C4A48
2022/10/17 22:57:39 Root duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 ErrorCode duration: 0s, args:
2022/10/17 22:57:39 IsWsl duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: User
am89954
2022/10/17 22:57:39 User duration: 0s, args:
2022/10/17 22:57:39 debug: Host
WDX8QJMGB3
2022/10/17 22:57:39 Host duration: 511.3µs, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 511.3µs, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: SSH_CONNECTION
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: SSH_CLIENT
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 IsWsl duration: 0s, args:
2022/10/17 22:57:39 StackCount duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 DirIsWritable duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: CommandPath
C:\Program Files\Git\cmd\git.exe
2022/10/17 22:57:39 CommandPath duration: 20.6184ms, args: git.exe
2022/10/17 22:57:39 HasCommand duration: 20.6184ms, args: git.exe
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 error: HasParentFilePath
CreateFile C:\.git: The system cannot find the file specified.
2022/10/17 22:57:39 HasParentFilePath duration: 0s, args: .git
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 debug: HasFiles
false
2022/10/17 22:57:39 HasFiles duration: 0s, args: *.py
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 debug: HasFiles
false
2022/10/17 22:57:39 HasFiles duration: 997.3µs, args: *.ipynb
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 debug: HasFiles
false
2022/10/17 22:57:39 HasFiles duration: 0s, args: pyproject.toml
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 PathSeparator duration: 0s, args:
2022/10/17 22:57:39 debug: HasFiles
false
2022/10/17 22:57:39 HasFiles duration: 0s, args: venv.bak
2022/10/17 22:57:39 debug: HasFolder
false
2022/10/17 22:57:39 HasFolder duration: 0s, args: .venv
2022/10/17 22:57:39 debug: HasFolder
false
2022/10/17 22:57:39 HasFolder duration: 0s, args: venv
2022/10/17 22:57:39 debug: HasFolder
false
2022/10/17 22:57:39 HasFolder duration: 0s, args: virtualenv
2022/10/17 22:57:39 debug: HasFolder
false
2022/10/17 22:57:39 HasFolder duration: 0s, args: env
2022/10/17 22:57:39 debug: HasFolder
false
2022/10/17 22:57:39 HasFolder duration: 0s, args: venv-win
2022/10/17 22:57:39 debug: HasFolder
false
2022/10/17 22:57:39 HasFolder duration: 0s, args: pyenv-win
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: AWS_VAULT
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: AWS_PROFILE
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: AWS_REGION
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: AWS_DEFAULT_REGION
2022/10/17 22:57:39 debug: Getenv

2022/10/17 22:57:39 Getenv duration: 0s, args: AWS_CONFIG_FILE
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 error: FileContent
open C:\Users\am89954/.aws/config: The system cannot find the path specified.
2022/10/17 22:57:39 FileContent duration: 0s, args: C:\Users\am89954/.aws/config
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 Root duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 ExecutionTime duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 ErrorCode duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 debug: HTTPRequest
GET /query HTTP/1.1
Host: 127.0.0.1:9863
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


2022/10/17 22:57:39 error: HTTPRequest
Get "http://127.0.0.1:9863/query": context deadline exceeded
2022/10/17 22:57:39 HTTPRequest duration: 20.5716ms, args: http://127.0.0.1:9863/query
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 IsWsl duration: 0s, args:
2022/10/17 22:57:39 BatteryState duration: 14.8855ms, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 debug: Pwd
C:\Users\am89954
2022/10/17 22:57:39 Pwd duration: 0s, args:
2022/10/17 22:57:39 debug: Home
C:\Users\am89954
2022/10/17 22:57:39 GOOS duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 TemplateCache duration: 0s, args:
2022/10/17 22:57:39 Shell duration: 0s, args:
2022/10/17 22:57:39 debug: Getenv
C:\Users\am89954\AppData\Local
2022/10/17 22:57:39 Getenv duration: 0s, args: LOCALAPPDATA
2022/10/17 22:57:39 CachePath duration: 0s, args:
2022/10/17 22:57:39 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@AlexMilender this is a terminal issue, not oh-my-posh. Please file a bug report there (or use a different terminal).

**Comment by AlexMilender** [comment]
Solution: Removing System Environment Variable "Term : dumb" resolved my issue.
