### ISSUE TITLE
oh-my-posh --version does not display the version number

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh#299]
### Prerequisites

- [x ] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

oh-my-posh --version does not display the version number correct

### Environment

- Oh my Posh version: 3.66.9
- Theme: fish
- Operating System: Ubuntu 18.04 WSL
- Shell: fish
- Terminal: Windows Terminal

### Steps to Reproduce

I upgraded oh-my-posh via homebrew then i typed `oh-my-posh --version`

**Expected behavior:** displays version number 3.66.9

**Actual behavior:**  displays development

Screenshoot:

![oh_my_posh_version](https://user-images.githubusercontent.com/49693964/103418852-c5276800-4b90-11eb-918f-fed090e62e6f.PNG)

**Comment by JanDeDobbeleer** [comment]
It did so before. Noticed that too, will investigate!

**Comment by JanDeDobbeleer** [comment]
@floh96 fixed. Happy newyear!

<img width="690" alt="image" src="https://user-images.githubusercontent.com/2492783/103423588-bd26f280-4ba7-11eb-8882-70bb1a7783c8.png">
