### ISSUE TITLE
Transient Prompt

### ISSUE THREAD

**Issue by its0din-ai** [JanDeDobbeleer/oh-my-posh#2990]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

**Please add option to make the prompt is Transient, like in the zsh's powerlevel10k themes below :3**

![](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif)

~thanks

**Comment by JanDeDobbeleer** [comment]
@its0din-ai we have this already. See [here](https://ohmyposh.dev/docs/configuration/transient).
