### ISSUE TITLE
scoop instalation for 12.7.1 is not giving executables

### ISSUE THREAD

**Issue by Thadir** [JanDeDobbeleer/oh-my-posh#3014]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

scoop update oh-my-posh@12.7.1

Will install new version without executable.

Going back to scoop update oh-my-posh@12.7.0 will give you a correct installation.

### Theme

n/a

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
NA
```

**Comment by JanDeDobbeleer** [comment]
@Thadir this isn't a bug. The executable is installed on your system and a PATH entry is set. You'll need to restart your terminal/machine to also reload the PATH. This is to also have signed executables and the same installation location and advantages regardless of the way you install/update oh-my-posh.

**Comment by JanDeDobbeleer** [comment]
@Thadir also have a look at [this](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2989) discussion.
