### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by SettingDust** [JanDeDobbeleer/oh-my-posh#302]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Custom the Path folder-separator color

### Environment

- Oh my Posh version: 3.68.0
- Theme: Custom
- Operating System: Windows 10
- Shell: pwsh
- Terminal: Windows Terminal

**Expected behavior:** 
Folder-separator color can different from foreground like the `Session.properties.user_color`

**Actual behavior:** 
Folder-separator color can't different from foreground

**Comment by JanDeDobbeleer** [comment]
@SettingDust you can set a separator, which should in theory also support overriding its color (did not yet validate this, but basically any string that's rendered is validated for [color overrides](https://ohmyposh.dev/docs/configure)). This means that if I add this, the color of the separator should be orange:

```
"folder_separator_icon": ""<#FFA500>/</>""
```

**Comment by SettingDust** [comment]
> @SettingDust you can set a separator, which should in theory also support overriding its color (did not yet validate this, but basically any string that's rendered is validated for [color overrides](https://ohmyposh.dev/docs/configure)). This means that if I add this, the color of the separator should be orange:
> 
> ```
> "folder_separator_icon": ""<#FFA500>/</>""
> ```

Ohh. Thanks a lot! :D

![image](https://user-images.githubusercontent.com/19922286/103435215-a84d6c00-4c46-11eb-9320-c00b6ffc0f7e.png)

**Comment by JanDeDobbeleer** [comment]
@SettingDust looks nice!!
