### ISSUE TITLE
get error in slim theme

### ISSUE THREAD

**Issue by aerosadegh** [JanDeDobbeleer/oh-my-posh#3026]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I do update to `12.9.1` and get error in slim theme:

![image](https://user-images.githubusercontent.com/5039032/198814638-31d62ca6-a62f-48d4-b9f4-45849a804fb4.png)

### Theme

slim.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
!!text property not defined!!
```

**Comment by JanDeDobbeleer** [comment]
@aerosadegh this probably implies that the theme got updated, but oh-my-posh is still an older version. Can you validate that your oh-my-posh executable is also `12.9.1`? That error message is no longer (for a long time now) in the codebase.
