### ISSUE TITLE
To remove the parameters font background box

### ISSUE THREAD

**Issue by 8ar10der** [JanDeDobbeleer/oh-my-posh#3032]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

![image](https://user-images.githubusercontent.com/26244249/198990328-55bc4400-c95a-4e99-850b-6c7b6f65cfd8.png)
From the discussion: https://github.com/JanDeDobbeleer/oh-my-posh/discussions/3029

Hi,

Could add a switch or config option to remove the shadow?

OMP version: 12.10.0
Windows terminal version: 1.15.2875.0

**Comment by JanDeDobbeleer** [comment]
No, because that's not a shadow but inverted ANSI. You can however make use of [terminal_background](https://ohmyposh.dev/docs/configuration/overview#general-settings)	and set it to a specific color and not invert.

**Comment by 8ar10der** [comment]
For anyone who find the same issue maybe, just update your PSReadLine. It will solve the issue.
