### ISSUE TITLE
Tooltip disappears once subcommand/arg is typed

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3037]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have a tooltip set up for `node`/`npm` to show the node version. 2 issues with it:
- ~~When I'm in my home directory, it won't show at all~~ Ignore this one, I found the `home_enabled` option
- When I'm in another directory, it works, but when I type the arguments after the command name, the tooltip goes away. I'd expect it to stay even after subcommands or arguments are typed

https://user-images.githubusercontent.com/14863373/199593804-3cf53fba-3c4e-4a3a-a920-bdc4bc0b1db4.mp4

### Theme

https://gist.github.com/asportnoy/51f0a34602b92e008ecce6f1cceac572

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

fish

### Log output

```Shell
https://gist.github.com/asportnoy/07eb2750f4051efc981dbc211500ab76
```

**Comment by JanDeDobbeleer** [comment]
@asportnoy I think this is currently by design. But I'll check.

**Comment by asportnoy** [comment]
@JanDeDobbeleer If that's the case, could you add an option to make it persist when args are entered?

**Comment by asportnoy** [comment]
Can confirm the issue is fixed, thanks!
