### ISSUE TITLE
getting bash exec error 

### ISSUE THREAD

**Issue by iamLazyCode** [JanDeDobbeleer/oh-my-posh#3041]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

hi i am using raspberry pi with ubuntu server installed over it 
which i maintain via windows terminal

i am getting this error when i place in .bashrc
eval "$(oh-my-posh init bash)"

error :
bash: /usr/local/bin/oh-my-posh: cannot execute binary file: Exec format error

### Theme

default

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
-bash: /usr/local/bin/oh-my-posh: cannot execute binary file: Exec format error
```

**Comment by JanDeDobbeleer** [comment]
@ifelixculpa it seems like you installed/downloaded a binary for a different platform. Please make sure to download the ARM version on your raspberry pi. If you want to make sure it's 100% compatible, please install using homebrew. That compiles on your machine.

```
sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-arm64 -O /usr/local/bin/oh-my-posh
sudo chmod +x /usr/local/bin/oh-my-posh
```

**Comment by iamLazyCode** [comment]
> @ifelixculpa it seems like you installed/downloaded a binary for a different platform. Please make sure to download the ARM version on your raspberry pi. If you want to make sure it's 100% compatible, please install using homebrew. That compiles on your machine.

thankyou sir il try and update , thanks again sir

edit : i guess

ARM (unsupported)
Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64), but as they lack binary packages (bottles) they are unsupported. Pull requests are welcome to improve the experience on ARM platforms.

You may need to install your own Ruby using your system package manager, a PPA, or rbenv/ruby-build as we no longer distribute a Homebrew Portable Ruby for ARM.

**Comment by iamLazyCode** [comment]
> sudo chmod +x /usr/local/bin/oh-my-posh

thanks a million sir this worked like a magic
