### ISSUE TITLE
Fish - error with new lines

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3042]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I type a multiline command (alt + enter) and press space on a line after the first one, I get the error `Error: accepts 1 arg(s), received 2`.

I believe this is a regression from [2609aa2](https://github.com/JanDeDobbeleer/oh-my-posh/commit/2609aa2aea5c031a6a002cdf393fc4efe2d365ae) (fixed my previous issue - #3037). You might be able fix it by just adding `head -n 1` before the splitting to only get the first line (have not tested).

### Theme

See #3037

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

fish

### Log output

```Shell
The error message.
```

**Comment by asportnoy** [comment]
~~Works, thanks!~~

**Comment by asportnoy** [comment]
@JanDeDobbeleer the issue still persists (I just didn't properly test it before). I am upgraded to v12.12.0.

**Comment by JanDeDobbeleer** [comment]
Did you restart the shell? I validated it on my end (and could reproduce it initially).

**Comment by asportnoy** [comment]
Yes, I fully quit and reopened Terminal.

When you tested, did you press space after typing on the next line? That was what I forgot to do initially when I tested after updating.

**Comment by JanDeDobbeleer** [comment]
Yes I did. That's the only way to reproduce this.

**Comment by JanDeDobbeleer** [comment]
@asportnoy I found it, you can still make it fail by adding a space AFTER the word on the second line. The change I did fixes it for the initial space on the second line. Goddamnit.

**Comment by asportnoy** [comment]
I restarted Terminal again right before this recording just to be sure

https://user-images.githubusercontent.com/14863373/200068875-6da6c465-6c9f-46f7-b3cd-b82884dc7b54.mp4

[My OMP Config](https://gist.github.com/asportnoy/51f0a34602b92e008ecce6f1cceac572)
