### ISSUE TITLE
Single word is not completed

### ISSUE THREAD

**Issue by totkeks** [JanDeDobbeleer/oh-my-posh#3050]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I use the Powershell completion, then it fails to complete, when I want to complete the first word, e.g. `con<tab>` or `com<tab>` - should result in config or completion respectively. Instead neither happens.

I also found the issue in the completion code while writing this issue:

```powershell
$Values = $Out | ForEach-Object {
		#Split the output in name and description
		$Name, $Description = $_.Split("`t", 2)
		__oh-my-posh_debug "Name: $Name Description: $Description"

		# Look for the longest completion so that we can format things nicely
		if ($Longest -lt $Name.Length) {
			$Longest = $Name.Length
		}

		# Set the description to a one space string if there is none set.
		# This is needed because the CompletionResult does not accept an empty string as argument
		if (-Not $Description) {
			$Description = " "
		}
		@{Name = "$Name"; Description = "$Description" }
	}
```

When there is only one completion result, which is oddly the case for `oh-my-posh __complete con` but not for `oh-my-posh __complete config ex`, then the above code makes `$Values` a hashtable and not an array, which results in a hidden error down the line, because a hashtable has no `Length` property.

```powershell
if (($Directive -band $ShellCompDirectiveNoFileComp) -ne 0 ) {
		__oh-my-posh_debug "ShellCompDirectiveNoFileComp is called";

		if ($Values.Length -eq 0) {
			# Just print an empty string here so the
			# shell does not start to complete paths.
			# We cannot use CompletionResult here because
			# it does not accept an empty string as argument.
			""
			return
		}
	}
```

My simple workaround has been forcing `$Values` to become an array by doing this `[Array]$Values` in the first code fragment.

### Theme

Not relevant

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Not relevant
```

**Comment by totkeks** [comment]
After a little more digging I noticed that this code is not from omp, but comes from [@spf13/cobra](https://github.com/spf13/cobra). I will open an issue there and link this one.

**Comment by JanDeDobbeleer** [comment]
@totkeks yes indeed, this can be closed here as we can't do anything on our end.
