### ISSUE TITLE
Sleep segment disappears when starting to type next command

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3053]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The sleep segment disappears when I start to the the next command and press space on that line. If I remove the minimum time for the segment, the time turns to 0. Maybe some command that I'm not running is being logged as the new duration? If not, it's probably just being reset.

https://user-images.githubusercontent.com/14863373/200661467-9ab7e370-4cc5-4cb4-9bb2-0775ab167675.mp4

### Theme

https://gist.github.com/asportnoy/51f0a34602b92e008ecce6f1cceac572

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

fish

### Log output

```Shell
https://gist.github.com/asportnoy/07eb2750f4051efc981dbc211500ab76
```

**Comment by JanDeDobbeleer** [comment]
@asportnoy your config has a tooltip which is why the prompt is reloaded. ~~Caching that isn't really an option.~~ I think I can fix this when there's no output from the tooltip.

**Comment by asportnoy** [comment]
@JanDeDobbeleer shouldn't it only reload if the tooltip is actually triggered?

**Comment by JanDeDobbeleer** [comment]
@asportnoy I've got an almost working implementation but I'm too tired to get it to actually work. Will have another go tomorrow.

**Comment by asportnoy** [comment]
@JanDeDobbeleer That's alright, thanks so much for fixing it!

**Comment by asportnoy** [comment]
Fix works, thanks so much for the quick fixes on all of my bug reports!
