### ISSUE TITLE
.Parent variable without trailing separator

### ISSUE THREAD

**Issue by Fred-Vatin** [JanDeDobbeleer/oh-my-posh#3069]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

| Bin | version |
| --- | ---: |
| Oh My Posh version | 12.13.2 |
| Terminal  | 1.15.2874.0 |
| Windows | 10 (21H1) |

Hi,

I’m trying to get rid of the trailing separator of .Parent keeping the ability to customize `"folder_separator_icon"`.
![image](https://user-images.githubusercontent.com/22337329/201511564-a40fcb3c-100c-4f40-bd35-515ba1c55891.png)

Here is my code : 
```json
                                ...
				{
					"type": "path",
					"style": "diamond",
					"leading_diamond": "",
					"background": "#01579B",
					"foreground": "#ffffff",
					"template": " {{ .Parent }}",
					"properties": {
						"folder_separator_icon": "<transparent>  </>",
						"style": "full"
					}
				},
				{
					"type": "path",
					"style": "powerline",
					"powerline_symbol": "",
					"foreground": "#0C0C0C",
					"background": "#f1184c",
					"background_templates": [
						"{{if .Writable }} #33DD2D {{ end }}"
					],
					"template": " {{ path .Path .Location }} ",
					"properties": {
						"style": "folder"
					}
				},
                            ...
```

I want to use both segments because I need to keep this rendering for folder.
![image](https://user-images.githubusercontent.com/22337329/201511935-e73b5f6e-75f9-488d-b952-b137b1fe3564.png)
And customize the folder based on condition and use custom separator in the .Parent.

Currently, I didn’t find a way to join both segments without trailing separator. I tried to play with sprig to no avail.

Any mean to achieve this by a property would be welcome.

**Comment by JanDeDobbeleer** [comment]
@freMea isn't it possible to use the [trimSuffix](http://masterminds.github.io/sprig/strings.html) function in sprig?

**Comment by Fred-Vatin** [comment]
I tried something like `{{ trimSuffix '/' .Parent }}` but it fails. It you succeed please share how.

**Comment by JanDeDobbeleer** [comment]
@freMea this is what you need:

```json
{
    "type": "path",
    "style": "diamond",
    "leading_diamond": "",
    "background": "#01579B",
    "foreground": "#ffffff",
    "template": " {{ trimSuffix \"<transparent>  </>\" .Parent }} ",
    "properties": {
        "folder_separator_icon": "<transparent>  </>",
        "style": "full"
    }
},
```

Templates are evaluated before everything else so you need the raw content including the separator icon.

**Comment by Fred-Vatin** [comment]
Awesome !
