### ISSUE TITLE
Allow .Env.VarName for mapped_locations

### ISSUE THREAD

**Issue by Fred-Vatin** [JanDeDobbeleer/oh-my-posh#3084]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently `.Env.VarName` are not resolved and I have to set absolute path in `mapped_locations`

```json
"properties": {
  "folder_separator_icon": "<transparent>  </>",
  "style": "full",
  "mapped_locations": {
	  "E:/OneDrive/*": "",
	  "E:/OneDrive/Mes Documents/*": "",
	  "C:/ProgramData/*": "",
	  "C:/Users/Fred/*": "",
	  "C:/Windows/*": ""
}
```

All of these paths could benefit of `.Env.VarName`.

**Comment by JanDeDobbeleer** [comment]
@freMea let me see what I can do without impacting performance

**Comment by Fred-Vatin** [comment]
Awesome. Tested and approved 👍
