### ISSUE TITLE
A command line argument toggle for configure segments

### ISSUE THREAD

**Issue by the-mentor** [JanDeDobbeleer/oh-my-posh#3086]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Dear Developer,

I would like to have a command line argument that will toggle segments on and off.
I've noticed some segments can slow down the prompt tremendously and they might not be required at all times it would be nice to have something like 

`oh-my-posh.exe --config toggle git` or `oh-my-posh.exe --config toggle spotify`

We can also do something like this
`oh-my-posh.exe --config segment toggle git` - will toggle the segment
`oh-my-posh.exe --config segment on git` - will turn on the segment
`oh-my-posh.exe --config segment off git` - will turn off the segment

Which will leave the segment in the config but will toggle it on and off.
It will prevent the user from managing multiple config files just to have a segment turned on/off.
This will also allow the end user to set key bindings to run the command and toggle the segment on and off on demand.

I hope this make sense.
Feel free to ask me any questions you might have.

-DM

**Comment by JanDeDobbeleer** [comment]
@the-mentor tell me the exact use-case as I don't think they're the same for both examples. For git we already [have](https://ohmyposh.dev/docs/configuration/segment#include--exclude-folders) `exclude_folders` and `include_folders` for example, and I'm pretty sure the spotify use-case is for macOS. Toggling this on the fly is a no-go btw, that will never work.

**Comment by the-mentor** [comment]
@JanDeDobbeleer i just used git as an examplemaybe it was a bad one.

Spotify could be a good one or any other 
segment that I want to have a way to turn on and off on demand without managing multiple themes.

Edit: Some segments can be heavy and can take 1s to process or they can take too much screen space etc which is why I want to have a way to not use them all the time.
In pwsh I can bind a key to turn them on and off
I can do it with separate json files I just think its not the best solution to manage so many profiles.

Maybe the implementation can be to reload the theme file but exclude the segment you want to turn off?

**Comment by JanDeDobbeleer** [comment]
@the-mentor there's a way to do this which is by caching the information and validating an explicit disable. I'll see what I can do.
