### ISSUE TITLE
[PowerShell] Debug Prompt doesn't work with ephemeral (non-saved) scripts

### ISSUE THREAD

**Issue by JustinGrote** [JanDeDobbeleer/oh-my-posh#3090]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?
Regression from #2483

The workaround used for debug detection doesn't work in an ephemeral use case. Simple Example in a posh prompt:

```powershell
while ($true) {wait-debugger}
```

`$PSDebugContext` does exist, and I don't see why testing for either psdebugcontext or the workaround needs to be mutually exclusive. PR to follow.

Interestingly, somewhere in 7.x the default prompt was changed to not to the "DBG:" check. Maybe realizing the same unreliability? Need to dig into this.

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JustinGrote** [comment]
@JanDeDobbeleer thanks! Works now
![image](https://user-images.githubusercontent.com/15258962/202499192-02e6f05d-34c6-4dc5-9490-9c0547decf90.png)

**Comment by JanDeDobbeleer** [comment]
Thank you!
