### ISSUE TITLE
no joy in fish

### ISSUE THREAD

**Issue by cekvenich2** [JanDeDobbeleer/oh-my-posh#3092]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

pro@deb01 ~> fish -v
fish, version 3.5.1
pro@deb01 ~> oh-my-posh init fish | source
- (line 61): $(...) is not supported. In fish, please use '(string)'.
if test "$(string match -e '_render_transient' $(bind \r --user 2>/dev/null))" != ''
         ^
from sourcing file -
source: Error while reading file “-”

### Theme

not there yet

### What OS are you seeing the problem on?

Linux

### Log output

```Shell
pro@deb01 ~> fish -v
fish, version 3.5.1
pro@deb01 ~> oh-my-posh init fish | source
- (line 61): $(...) is not supported. In fish, please use '(string)'.
if test "$(string match -e '_render_transient' $(bind \r --user 2>/dev/null))" != ''
         ^
from sourcing file -
source: Error while reading file “-”
```

**Comment by cekvenich2** [comment]
I built fish from source and  ... no joy with latest posh. Help/hint?

**Comment by JanDeDobbeleer** [comment]
@cekvenich2 I'm running fish 3.5.1 (via homebrew) and this works. I would ask at fish as something is off with your build.
