### ISSUE TITLE
[fish] regression: tooltip doesn't reset if you type another command

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3093]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

If you type a command that shows a tooltip and then change the command, the tooltip does not go away

https://user-images.githubusercontent.com/14863373/202511251-d7e4fb6b-14e3-4fc6-bddd-e1d298b07ef5.mp4

If you type a command that shows a tooltip and then cancel (ctrl+c), the next line will show the same tooltip instead of resetting
![Screenshot 2022-11-17 at 11 06 49](https://user-images.githubusercontent.com/14863373/202511196-acfa18f4-864b-41be-93e2-c6d5bb9f2284.png)

This is a regression from #3053

Thanks!

### Theme

https://gist.github.com/asportnoy/51f0a34602b92e008ecce6f1cceac572

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

fish

### Log output

```Shell
https://gist.github.com/asportnoy/07eb2750f4051efc981dbc211500ab76
```

**Comment by JanDeDobbeleer** [comment]
@asportnoy nothing changed for fish however so not sure what causes that regression.

**Comment by asportnoy** [comment]
@JanDeDobbeleer That issue was for fish, the change from that issue was to [src/shell/scripts/omp.fish](https://github.com/JanDeDobbeleer/oh-my-posh/commit/c0c230879a7c3e0bdc44d44d06ffb7fe9a549e21#diff-46360978d2c694be7c9f884ed468ffadc14e53ae489810d1efa42bdb6783641b)

**Comment by JanDeDobbeleer** [comment]
@asportnoy yes. This is also fish and tooltip. What am I missing?

EDIT: wait, I get it. Bot sure if the two are completely solvable though. They could conflict with each other.

**Comment by asportnoy** [comment]
@JanDeDobbeleer What if you add a variable to track if a tooltip is shown so you know if you need to clear it or not?

**Comment by JanDeDobbeleer** [comment]
@asportnoy I think it just lacks clearing the value and resetting rprompt when empty. I'll check!

**Comment by JanDeDobbeleer** [comment]
> If you type a command that shows a tooltip and then cancel (ctrl+c), the next line will show the same tooltip instead of resetting

@asportnoy that's a bug for fish as they do not repaint the prompt then.
