### ISSUE TITLE
Fail to `toggle <type>` because of inconsistent PIDs when caching

### ISSUE THREAD

**Issue by YDX-2147483647** [JanDeDobbeleer/oh-my-posh#3096]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

## Background

[v12.15.0](https://github.com/JanDeDobbeleer/oh-my-posh/commit/63bb1b4729e7aae0218101b46183bdd51084c928#diff-7b082f4396f0c936b17e8deb6c4ea8ec54cb48509691b08354c28ef55aa18557) introduces [`oh-my-posh toggle <type>`](https://ohmyposh.dev/docs/configuration/segment#on-the-fly) to hide or show a segment in a shell session.

As explained in #3086 , the toggles are stored in the per-session cache, whose name contains the PID.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/63bb1b4729e7aae0218101b46183bdd51084c928/src/platform/shell.go#L42

## Issue

However, sometimes **the PID of `oh-my-posh toggle <type>`, `oh-my-posh get toggles` and the prompt can be different** …

↓ I `toggle <something>` in PID x, but `get toggles` in PID y, and the prompt may render in PID z. (Windows, PowerShell 7, slim)

```powershell
(main) > oh-my-posh toggle git

(main) > oh-my-posh get toggles
No segments are toggled off

(main) > rg toggle (oh-my-posh cache path) -A 5  # rg ≈ grep
107:    "toggle_cache_21344": {
108-        "value": "git",
109-        "timestamp": 1668767288, // This matches 18:28:08, when I `toggle git`
110-        "ttl": -1
111-    }
```

![on Windows](https://user-images.githubusercontent.com/73375426/202681170-8d5c3f66-b878-4cbe-b101-36fbbf3bae84.png)

↓ In the codespace, I rebuild it with `fmt.Println(platform.TOGGLECACHE)` in `src/cli/get.go`, `src/cli/toggle.go` and  `src/engine/segment.go`. (bash, default theme)

```bash
(main) $ oh-my-posh get toggles
toggle_cache_29787 (from get.go)
No segments are toggled off
validate toggles?  false toggle_cache_30026 (from segment.go)

(main) $ oh-my-posh toggle git
toggle_cache_29787 (from toggle.go)
validate toggles?  false toggle_cache_30121 (from segment.go)

(main) $
```

![codespace](https://user-images.githubusercontent.com/73375426/202683682-f4a0fc9c-95c6-4a3e-b71c-6c36fcf35442.png)
![codespace](https://user-images.githubusercontent.com/73375426/202686615-20026c2d-3533-4b70-9de7-537be8e0a3d6.png)

### Theme

It's not the theme/config.

I have checked several themes (default, slim, zash on Windows + PowerShell 7) and tried in the codespace (default theme, bash). All of them behaves similarly.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Sorry I believe `oh-my-posh debug` won't help here.

I have tried `oh-my-posh debug` several times. I'm glab to paste it here if anyone asks.
```

**Comment by JanDeDobbeleer** [comment]
@YDX-2147483647 I'm certain this is a PowerShell only problem so I'll fix it there. I can't reproduce at all on macOS using any other shell.

**Comment by YDX-2147483647** [comment]
Everything works fine now. Thanks!
