### ISSUE TITLE
Theme was not changed.

### ISSUE THREAD

**Issue by imsrikant** [JanDeDobbeleer/oh-my-posh#3098]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Why I'm not able to change the theme for git bash.
![image](https://user-images.githubusercontent.com/52560067/202776200-7cc8fb31-85bc-410e-ac63-9955d8aa4cc6.png)

## montys.omp.json
![image](https://user-images.githubusercontent.com/52560067/202776953-4a5e6657-9200-4148-a842-23c744a0cfed.png)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```Shell
2022/11/18 23:57:20 Getenv duration: 0s, args: LOCALAPPDATA
2022/11/18 23:57:20 CachePath duration: 0s, args:
2022/11/18 23:57:20 Flags duration: 0s, args:
```

**Comment by JanDeDobbeleer** [comment]
@marvel-srikant do not use `~` as a pointer to your Windows `HOME` folder from git bash as that's not going to be the same location. Find the actual path (and beware of unix style paths and weirdness allover).

**Comment by marvel-srikant** [comment]
# Can you give me an example ?

**Comment by marvel-srikant** [comment]
Can you give me an `example` for the path?

**Comment by imsrikant** [comment]
Thank you @JanDeDobbeleer  It's done..
