### ISSUE TITLE
feat: display git tag when checked out

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh#31]
in oh-my-posh when git was checked out at a git tag the tag was displayed in oh-my-posh-3 it's displaying unknown.
See screenshot
![Screenshot 2020-10-06 174214](https://user-images.githubusercontent.com/49693964/95225451-1aefac80-07fc-11eb-84d3-50036feeed0f.png)

**Comment by JanDeDobbeleer** [comment]
Yes, that's not yet a feature. I'll make it happen. The git segment needs some more tweaks to be feature complete (but it should in theory not be rocket science). It's next on my list.
