### ISSUE TITLE
Add Rocky Linux icon to Os segment

### ISSUE THREAD

**Issue by jacobo-diaz** [JanDeDobbeleer/oh-my-posh#3101]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Add [Rocky Linux](https://rockylinux.org) icon to OS segment. The hex code for the icon in Nerd Fonts is '\Uf32b'

**Comment by JanDeDobbeleer** [comment]
@jacobo-diaz can you give me the output of `oh-my-posh debug` when in rocky? I need to understand how it identifies.

**Comment by jacobo-diaz** [comment]
Here it is:
<img width="510" alt="screenshot 2022-11-19 at 20 28 24" src="https://user-images.githubusercontent.com/2563927/202868164-07a28641-2b97-4fd2-8349-56b7e699db89.png">

The posh.toml file:
```
#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space = true
version = 2.0

[[blocks]]
  alignment = "left"
  type = "prompt"

  [[blocks.segments]]
    type = "os"
    style = "powerline"
```

**Comment by jacobo-diaz** [comment]
Rocky is a Red Hat clone, like CentOS. This is the content of `/etc/system-release` for Rocky:
```Rocky Linux release 8.6 (Green Obsidian)```

And this is for CentOS:
```CentOS Linux release 7.9.2009 (Core)```

**Comment by the-mentor** [comment]
Since Alma Linux is Also a Red Hat clone maybe it's a good time to add an icon for that as well?
https://almalinux.org/

**Comment by JanDeDobbeleer** [comment]
@jacobo-diaz @jacobo-diaz using the latest version of oh-my-posh, can you provide the output of `oh-my-posh debug` again? I added logging that will show what I need to resolve this.

**Comment by jacobo-diaz** [comment]
Here it is @JanDeDobbeleer 

![screenshot 2022-11-23 at 09 09 01](https://user-images.githubusercontent.com/2563927/203498025-5a854a67-484d-4b1c-8a72-d04feb74ae7f.png)

**Comment by JanDeDobbeleer** [comment]
@jacobo-diaz seems like some of the logs are missing, can you provide the full output?

**Comment by jacobo-diaz** [comment]
@JanDeDobbeleer  It's the full output. What you see at the bottom is the next prompt

![screenshot 2022-11-23 at 09 16 38](https://user-images.githubusercontent.com/2563927/203499146-8f3100cd-eb62-467d-bb4d-e658a576a2f0.png)

**Comment by JanDeDobbeleer** [comment]
@jacobo-diaz ah, yes we cache the value, can you check what listed as `environment_platform` when using `oh-my-posh cache edit`? In my case:

```json
"environment_platform": {
        "value": "darwin",
        "timestamp": 1668963726,
        "ttl": -1
},
```

**Comment by jacobo-diaz** [comment]
Sure. Here you are:
```json
"environment_platform": {
   "value": "rocky",
   "timestamp": 1669190838,
   "ttl": -1
},
```
