### ISSUE TITLE
`oh-my-posh --init` Two small but useful usability proposals

### ISSUE THREAD

**Issue by schittli** [JanDeDobbeleer/oh-my-posh#3113]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Good evening

**thanks a lot for sharing your great work!**
_(I still find the name terrible, but the product is indeed very useful 😅)_

I just started evaluating oh-my-posh and ran into two troublesome problems, therefore I have two small proposals for `oh-my-posh --init` :

#### `oh-my-posh --init`: please make the --shell parameter case *insensitive*
* If users call: `oh-my-posh --init --shell PowerShell`
* They get: `No initialization script available for Powershell`
* if they use lowercase: `powershell`, then it works

Because pretty sure no damage is caused if `--shell` parameter is insensitive 
and because then it is pretty likely that it `oh-my-posh --init` works as the user expects,
therefore it would make sense to have the `--shell` parameter case *insensitive*

Otherwise, users will have to use google to find a solution...

#### `oh-my-posh --config`: please warn the user if `--config` is invalid and a default config is used

It's great that `oh-my-posh` has a config fallback solution if the `--config` parameter is wrong.
But it is very confusing because it happens silently. The user calls `oh-my-posh`, and everything seems to be ok - but the applied configuration is wrong.

Please, display a warning if `oh-my-posh` cannot find the passed `--config`, so that users don't have to use google until they understand what happens.

Thanks a lot, kind regards,
Thomas

**Comment by JanDeDobbeleer** [comment]
Can do. One remark though, `If users call: oh-my-posh --init --shell PowerShell`, this should be replaced with `oh-my-posh init PowerShell`.

This is also what the docs have been saying for > year now, the only reason people still use the old way is because of old blog posts. If you do use the official way, it's correctly provided:

```
> oh-my-posh init PowerShell                                     
Error: invalid argument "PowerShell" for "oh-my-posh prompt init"
Usage:
  oh-my-posh prompt init [bash|zsh|fish|powershell|pwsh|cmd|nu] --config ~/.mytheme.omp.json [flags]

Flags:
  -h, --help     help for init
  -m, --manual   enable/disable manual mode
  -p, --print    print the init script
  -s, --strict   run in strict mode

Global Flags:
  -c, --config string   config (required)
```

I'll check what we can do for the config on init, we can print that there.
