### ISSUE TITLE
Setting last command as the console_title_template in PowerShell

### ISSUE THREAD

**Issue by alfawal** [JanDeDobbeleer/oh-my-posh#3119]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I would like to see a global property defined as `.LastCommand` so I can set the console title (PowerShell in my case) as the last command that I've entered.

#### Edit:
I've tried doing this but it didn't work out.
```ps1
function Set-EnvVar {
    $env:POSH_LAST_COMMAND=$(Get-History -Count 1)
}
New-Alias -Name 'Set-PoshContext' -Value 'Set-EnvVar' -Scope Global -Force
```
```omp.json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "console_title_template": "{{ .Env.POSH_LAST_COMMAND }}",
  "blocks": [
    "blocks"
  ]
}
```

**Comment by JanDeDobbeleer** [comment]
@alfawal you were on the right track, that should actually work. I'll check why it doesn't!

**Comment by JanDeDobbeleer** [comment]
@alfawal this is what you need as the command you use is always empty:

```powershell
function Set-EnvVar {
    $env:POSH_LAST_COMMAND=$((Get-History | Select-Object -Last 1).CommandLine)
}
New-Alias -Name 'Set-PoshContext' -Value 'Set-EnvVar' -Scope Global -Force
```

**Comment by alfawal** [comment]
@JanDeDobbeleer I've noticed that the context updates after the command execution is done. i.e. running django/express wouldn't change the `console_title_template`.
it would be pretty cool if I can change the context mode or have two separate contexts (one before the command execution and one after).

**Comment by JanDeDobbeleer** [comment]
@alfawal that's difficult as it requires the same hook as transient prompt. So either we add the title to that part as well (and you get it for free as part of that) or we need to create a separate hook and config entry if you want to use this regardless of having a transient prompt or not.

**Comment by alfawal** [comment]
@JanDeDobbeleer my original suggestion was to support the last command as one of the [Global Properties](https://ohmyposh.dev/docs/configuration/templates#global-properties), I would be grateful if any similar implementation is possible.
Feel free to change the title/status of the issue if needed so anyone can follow up from here.

Thanks in advance.

**Comment by JanDeDobbeleer** [comment]
@alfawal but your question `it would be pretty cool if I can change the context mode or have two separate contexts (one before the command execution and one after)` won't be resolved when you have that as the population of that only happens after command execution as it's part of the primary prompt (PS1) and not transient which is a hook on ENTER (before command execution).

**Comment by alfawal** [comment]
@JanDeDobbeleer The original suggestion was written in the issue description :D

> I would like to see a global property defined as `.LastCommand` so I can set the console title (PowerShell in my case) as the last command that I've entered.

**Comment by JanDeDobbeleer** [comment]
@alfawal difficult to achieve in every shell so I'm calling this a no. You'd think history is straightforward but it isn't.
