### ISSUE TITLE
Option to hide right prompt for multiline command

### ISSUE THREAD

**Issue by asportnoy** [JanDeDobbeleer/oh-my-posh#3122]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'd like an option to hide the right prompt if the command I'm writing spans multiple lines. This would allow me to copy the command later without the prompt getting in the way. Thanks!

(Using fish on macOS)

**Comment by JanDeDobbeleer** [comment]
@asportnoy that's a request to fish, their rprompt function should handle that.
