### ISSUE TITLE
Add `segment_separator` parameter to block(s)

### ISSUE THREAD

**Issue by Destroy666x** [JanDeDobbeleer/oh-my-posh#3125]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Rather simple suggestion that would improve the configuration by a lot - add a `segment_separator` parameter to block definition so that you can do for example `segment_separator: " "` and the code would just print out that string between each visible segment.

Then you wouldn't need to care about starting/ending spaces or other characters in segment templates, especially `plain` ones.

**Comment by JanDeDobbeleer** [comment]
@Destroy666x gave this a reflection and decided against. We initially had pre and postfix, but if you're creating your own template I'm pretty sure that extra space isn't going to be a dealbreaker (looking at the amount of configs I also already created/tweaked). If people disagree they can surely vote on the suggestion, right now it only adds unnecessary complexity to the engine.

**Comment by Destroy666x** [comment]
Hmmm, not sure I'd agree these are comparable, looking at what prefix/postfix did they were per `segment`, so they basically filled the same role as characters entered at the beginning or end of each template and they didn't really shorten the configuration process, especially if you already modified the default template for a segment.

This suggestion is different as it's per `block` - it adds some automation of not having to move spaces or other kind of separators around between segment templates if you e.g. move the segments. Ofc you can just add trailing/leading separator in each template except 1 to reduce the work, then you only have to consider moving the separator whenever you change the start/end. However, if you wanted to change the separator because let's say a different font looks better with more spaces in between segments, you still have to edit for example 20 templates or run some regex search/replace. If prefix/suffix were per block as well, applying to all segments, I think they'd also be quite useful in some cases.

But sure, maybe more people will request this or something similar in the future.
