### ISSUE TITLE
When i was write only 'cd' terminal goes top of tree. 

### ISSUE THREAD

**Issue by cudoviste** [JanDeDobbeleer/oh-my-posh#3129]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I think a bug happened! When i was write only 'cd' terminal goes top of tree. I write  on terminal without theme doesn't go main tree and shows current folder. 

### Theme

I tried half-life and lambda theme .

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash, powershell

### Log output

```Shell
PowerShell 7.3.0
Loading personal and system profiles took 766ms.
ZvZ in ~ λ cd desktop
ZvZ in ~\Desktop λ cd
ZvZ in ~ λ
```

**Comment by ibrahimsugun** [comment]
Same thing happens on my computer.

**Comment by JanDeDobbeleer** [comment]
@cudoviste @ibrahimsugun we don't have anything that we influence when running commands. We only render the prompt...

EDIT: this is completely expected behaviour, from the man pages:

> DESCRIPTION
       cd changes the current working directory.
       If DIRECTORY is given, it will become the new directory. **_If no parameter is given, the HOME environment variable will be used._**
