### ISSUE TITLE
VS CODE : error because C:\/.git doesn't exist 

### ISSUE THREAD

**Issue by Donfox95** [JanDeDobbeleer/oh-my-posh#3137]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

i'am using VS studio Code  with integrated terminal getting following error : 
 
getting an error because git / git posh / oh my posh cannot find C:\/.git: 

![ohmyposh](https://user-images.githubusercontent.com/106558878/204241763-3bba4638-7f83-486a-bcc5-6393c487bc89.PNG)

### Theme

default

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell, other (please specify)

### Log output

```Shell
2022/11/28 10:23:00 Pwd
C:\Users\admin.pieterJ
2022/11/28 10:23:00 Pwd: 0s
2022/11/28 10:23:00 HasParentFilePath
CreateFile C:\/.git: Het systeem kan het opgegeven bestand niet vinden. ( translation : cannot find path but this is normal ) 
2022/11/28 10:23:00 HasParentFilePath: 19.1104ms, args: .git
2022/11/28 10:23:00 Pwd
C:\Users\admin.pieterJ
2022/11/28 10:23:00 Pwd: 0s
2022/11/28 10:23:00 Home
C:\Users\admin.pieterJ
2022/11/28 10:23:00 GOOS: 0s
2022/11/28 10:2
```

**Comment by JanDeDobbeleer** [comment]
@Donfox95 looking at the error message in your terminal, can you please [upgrade first](https://ohmyposh.dev/docs/migrating) and see if the error still persists? Thanks.
