### ISSUE TITLE
Spotify - Pause / Spotify doesn't work?

### ISSUE THREAD

**Issue by bahree** [JanDeDobbeleer/oh-my-posh#317]
I don't know what the expected behavior is - when I have music playing, I can see the song as expected, but when I pause or have the music stopped, that segment just disappears. Is that how it is supposed to be? Resuming playing it comes back.

I wonder if this is a setting for Spotify as it is sending out some metadata.

Thanks.

![image](https://user-images.githubusercontent.com/3529468/103584976-2a33d400-4e97-11eb-965b-b211986a73c7.png)
![image](https://user-images.githubusercontent.com/3529468/103584989-2dc75b00-4e97-11eb-8fff-58a907e0f4d9.png)

**Comment by lnu** [comment]
On Windows that's expected. We retrieve the information from the window title and paused/stopped is the same(no title).  
On macOS it's handle differently(AppleScript) and you get the track title when paused.  
On linux it's not yet done, we'll probably do it using dbus(one day maybe).
