### ISSUE TITLE
upcoming nushell release

### ISSUE THREAD

**Issue by fdncred** [JanDeDobbeleer/oh-my-posh#3188]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

We just wanted to let you know that in our upcoming nushell release on Dec 20th, we have changed the way the nushell `save` command works. If people using nushell initialize oh-my-posh with each instance like `oh-my-posh param param param | save /some/path/file.nu`, which overwrites the `file.nu` each time, this will break because our `save` command now requires `save -f` to "force" it to overwrite.

Thank you for supporting nushell in omp!

**Comment by JanDeDobbeleer** [comment]
@fdncred thanks for the heads-up!

**Comment by fdncred** [comment]
One other thing that I'd mention, we're changing our `boolean and` from `&&` to `and` and our `boolean or` from `||` to `or`. I'm not sure you use those in your nushell scripts but I wanted to mention it in case you do.

**Comment by JanDeDobbeleer** [comment]
@fdncred 'm going to update the docs this week, somehow I lost track of the date here.

**Comment by JanDeDobbeleer** [comment]
@fdncred I see what you mean 😆 

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/2492783/211636380-dd724021-903c-46a2-8d5c-94310e600462.png">

**Comment by fdncred** [comment]
Indeed. We also let the zoxide folks know too. Not sure if they've released an update yet.

**Comment by JanDeDobbeleer** [comment]
@fdncred they did. Once I added force it started working too.
