### ISSUE TITLE
Unicode character is not properly displayed

### ISSUE THREAD

**Issue by duck2913** [JanDeDobbeleer/oh-my-posh#3201]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

In the terminal inside VS Code, the trailing and leading diamond character appeared to be shorter than usual
![image](https://user-images.githubusercontent.com/65350039/207491522-46036084-3c23-4887-8c1f-43f83c16e27d.png)
![image](https://user-images.githubusercontent.com/65350039/207491605-1b5b45db-2e72-4ab3-a7b4-653c92678d76.png)
and also other characters as well
![image](https://user-images.githubusercontent.com/65350039/207491676-cedd9b11-4d14-4786-9a0d-555704d84818.png)

And if I opened this is Terminal Preview, I think the height of the character is fine, but the height of entire line is not properly displayed
![image](https://user-images.githubusercontent.com/65350039/207493102-d1e49c23-0352-4118-b7fb-ab16dce9479c.png)

I'm using CaskaydiaCove Nerd Font ,

How can I fix this, thank you

### Theme

{
	"$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
	"palette": {
		"os": "#ACB0BE",
		"pink": "#F5BDE6",
		"lavender": "#B7BDF8",
		"blue": "#8AADF4",
		"wight": "#FFFFFF",
		"text": "#373b3e"
	},
	"blocks": [
		{
			"alignment": "left",
			"segments": [
				{
					"background": "p:blue",
					"foreground": "p:wight",
					"powerline_symbol": "\ue0b4",
					"leading_diamond": "\u256d \u2500\ue0b6",
					"properties": {
						"macos": "\uf179 ",
						"ubuntu": "\uf31b ",
						"windows": "\uf871 "
					},
					"style": "diamond",
					"template": " {{ if .WSL }}WSL at {{ end }}{{.Icon}}",
					"type": "os"
				},
				{
					"background": "p:blue",
					"foreground": "p:text",
					"powerline_symbol": "\ue0b4",
					"style": "diamond",
					"template": "{{ .UserName }}@{{ .HostName }}",
					"type": "session"
				},
				{
					"background": "p:pink",
					"foreground": "p:text",
					"properties": {
						"folder_icon": "..\ue5fe..",
						"home_icon": "~",
						"style": "agnoster_short"
					},
					"powerline_symbol": "\ue0b4",
					"style": "powerline",
					"template": " {{ .Path }}",
					"type": "path"
				},
				{
					"background": "p:lavender",
					"foreground": "p:text",
					"foreground_templates": [
						"{{ if or (.Working.Changed) (.Staging.Changed) }}#6287ff{{ end }}",
						"{{ if and (gt .Ahead 0) (gt .Behind 0) }}#7f62ff{{ end }}",
						"{{ if gt .Ahead 0 }}#9962ff{{ end }}",
						"{{ if gt .Behind 0 }}#c062ff{{ end }}"
					],
					"powerline_symbol": "\ue0b4",
					"properties": {
						"display_stash_count": true,
						"display_status": true,
						"display_upstream_icon": true
					},
					"style": "powerline",
					"template": " {{.UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} ",
					"type": "git"
				}
			],
			"type": "prompt"
		},
		{
			"alignment": "right",
			"segments": [
				{
					"background": "#295a35",
					"foreground": "#7feaa5",
					"leading_diamond": "\ue0b6",
					"trailing_diamond": "\ue0b4 ",
					"style": "diamond",
					"template": "RAM:{{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1000000000.0) }}/{{ (div .PhysicalTotalMemory 1000000000.0) }}GB",
					"type": "sysinfo"
				},
				{
					"background": "#29315A",
					"foreground": "#AEA4BF",
					"leading_diamond": "\ue0b6",
					"properties": {
						"style": "austin",
						"threshold": 150
					},
					"style": "diamond",
					"template": "{{ .FormattedMs }}",
					"trailing_diamond": "\ue0b4 ",
					"type": "executiontime"
				},
				{
					"background": "#29315A",
					"foreground": "#42E66C",
					"leading_diamond": "\ue0b6",
					"properties": {
						"fetch_version": false
					},
					"style": "diamond",
					"template": "\ue718{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}",
					"trailing_diamond": "\ue0b4",
					"type": "node"
				},
				{
					"background": "#29315A",
					"foreground": "#9B6BDF",
					"foreground_templates": [
						"{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
						"{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
						"{{if eq \"Full\" .State.String}}#4caf50{{end}}"
					],
					"leading_diamond": " \ue0b6",
					"properties": {
						"charged_icon": "🔋 ",
						"charging_icon": "\u21e1 ",
						"discharging_icon": "🔋 "
					},
					"style": "diamond",
					"template": "{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}%",
					"trailing_diamond": "\ue0b4",
					"type": "battery"
				}
			],
			"type": "prompt"
		},
		{
			"alignment": "left",
			"newline": true,
			"segments": [
				{
					"foreground": "#dbb7f8",
					"style": "plain",
					"template": "\u2570 \u2500",
					"type": "text"
				},
				{
					"background": "#29315A",
					"foreground": "#7FD5EA",
					"leading_diamond": "\ue0b6",
					"style": "diamond",
					"template": "\u276f",
					"trailing_diamond": "\ue0b4",
					"type": "text"
				}
			],
			"type": "prompt"
		}
	],
	"console_title_template": "{{ .Shell }} in {{ .Folder }}",
	"final_space": true,
	"version": 2
}

### Log output

```Shell
Version: 12.26.2

Segments:

ConsoleTitle(true)   -   1 ms - pwsh in code signal
os(true)             -   3 ms - ╭ ─  
session(true)        -   1 ms - duck@Zenbook-15
path(true)           -   2 ms -  D:\....\code signal
git(false)           -  10 ms -
sysinfo(true)        - 160 ms - RAM:6/8GB
executiontime(false) -   0 ms -
node(true)           -   0 ms - 
battery(true)        -   8 ms -  🔋 100%
text(true)           -   0 ms - ╰ ─
text(true)           -   0 ms - ❯

Run duration: 222.4624ms

Cache path: C:\Users\minhd\AppData\Local\oh-my-posh

Config path: C:\Users\minhd\OneDrive\Documents\custom_powershell.json

Logs:

2022/12/14 09:29:24 Getenv
C:\Users\minhd\AppData\Local
2022/12/14 09:29:24 Getenv: 601.1µs, args: LOCALAPPDATA
2022/12/14 09:29:24 CachePath: 601.1µs
2022/12/14 09:29:24 Getenv
C:\Users\minhd\OneDrive\Documents\custom_powershell.json
2022/12/14 09:29:24 Getenv: 0s, args: POSH_THEME
2022/12/14 09:29:24 Shell
process name: pwsh.exe
2022/12/14 09:29:24 Shell: 22.7219ms
2022/12/14 09:29:24 resolveConfigPath: 22.7219ms
2022/12/14 09:29:24 Init: 30.6037ms
2022/12/14 09:29:24 Flags: 0s
2022/12/14 09:29:24 config.loadConfig: 2.2654ms
2022/12/14 09:29:24 Flags: 0s
2022/12/14 09:29:24 Getenv

2022/12/14 09:29:24 Getenv: 0s, args: OMP_CACHE_DISABLED
2022/12/14 09:29:24 WindowsRegistryKeyValue: 0s, args: HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor      
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 WindowsRegistryKeyValue
ColorizationColor(DWORD): 0xC45A311B
2022/12/14 09:29:24 Root: 0s
2022/12/14 09:29:24 Shell: 0s
2022/12/14 09:29:24 ErrorCode: 0s
2022/12/14 09:29:24 IsWsl: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 Home
C:\Users\minhd
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 User
duck
2022/12/14 09:29:24 User: 0s
2022/12/14 09:29:24 Host
Zenbook-15
2022/12/14 09:29:24 Host: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 Flags: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 Home
C:\Users\minhd
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 Shell: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 Home
C:\Users\minhd
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 Getenv

2022/12/14 09:29:24 Getenv: 0s, args: SSH_CONNECTION
2022/12/14 09:29:24 Getenv

2022/12/14 09:29:24 Getenv: 0s, args: SSH_CLIENT
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 Shell: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 Home
C:\Users\minhd
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 Shell: 0s
2022/12/14 09:29:24 Flags: 0s
2022/12/14 09:29:24 Home
C:\Users\minhd
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 PathSeparator: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 IsWsl: 0s
2022/12/14 09:29:24 StackCount: 0s
2022/12/14 09:29:24 isWriteable
current user is member of S-1-5-32-544
2022/12/14 09:29:24 isWriteable
WRITE_DAC
WRITE_OWNER
SYNCHRONIZE
DELETE
READ_CONTROL
2022/12/14 09:29:24 isWriteable
user has write access
2022/12/14 09:29:24 DirIsWritable: 1.0146ms
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 TemplateCache: 0s
2022/12/14 09:29:24 Shell: 0s
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 Home
C:\Users\minhd
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 GOOS: 0s
2022/12/14 09:29:24 CommandPath
C:\Program Files\Git\cmd\git.exe
2022/12/14 09:29:24 CommandPath: 10.5747ms, args: git.exe
2022/12/14 09:29:24 HasCommand: 10.5747ms, args: git.exe
2022/12/14 09:29:24 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:24 Pwd: 0s
2022/12/14 09:29:24 HasParentFilePath
CreateFile D:\/.git: The system cannot find the file specified.
2022/12/14 09:29:24 HasParentFilePath: 0s, args: .git
2022/12/14 09:29:24 Flags: 0s
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 Home
C:\Users\minhd
2022/12/14 09:29:25 GOOS: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 Shell: 0s
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 Home
C:\Users\minhd
2022/12/14 09:29:25 GOOS: 0s
2022/12/14 09:29:25 ExecutionTime: 0s
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 Home
C:\Users\minhd
2022/12/14 09:29:25 GOOS: 0s
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 Home
C:\Users\minhd
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 HasFiles: 0s, args: *.js
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 FileContent
open D:\study\Self study\code signal\.nvmrc: The system cannot find the file specified.
2022/12/14 09:29:25 FileContent: 0s, args: .nvmrc
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 Shell: 0s
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 Home
C:\Users\minhd
2022/12/14 09:29:25 GOOS: 0s
2022/12/14 09:29:25 IsWsl: 0s
2022/12/14 09:29:25 BatteryState: 6.9368ms
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 Shell: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 Flags: 0s
2022/12/14 09:29:25 Pwd
D:\study\Self study\code signal
2022/12/14 09:29:25 Pwd: 0s
2022/12/14 09:29:25 Home
C:\Users\minhd
2022/12/14 09:29:25 GOOS: 0s
2022/12/14 09:29:25 TemplateCache: 0s
2022/12/14 09:29:25 Shell: 0s
2022/12/14 09:29:25 Pwd
```

**Comment by JanDeDobbeleer** [comment]
@duck2913 this is a terminal issue. Oh-my-posh doesn't influence the rendering of the characters itself, it only prints a string containing those characters. You'll have to have a look at your terminal settings (font, renderer, ...), or create an issue at vscode.
