### ISSUE TITLE
Can't upgrade oh-my-posh on homebrew on mac

### ISSUE THREAD

**Issue by gregbair** [JanDeDobbeleer/oh-my-posh#3204]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

brew outdated reports `jandedobbeleer/oh-my-posh/oh-my-posh (12.26.2) < 12.26.2_1`

brew upgrade gives error - 

```
Error: No available formula with the name "go@1.19.4" (dependency of jandedobbeleer/oh-my-posh/oh-my-posh). Did you mean go@1.14?
```

### Theme

N/A

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
Huh? I checked that before pushing that change. Homebrew lists that go version as available but I'll double check.

**Comment by JanDeDobbeleer** [comment]
@gregbair should be fixed

**Comment by gregbair** [comment]
Confirmed fixed
