### ISSUE TITLE
how to configure a two-line prompt with text on both sides

### ISSUE THREAD

**Issue by sql-sith** [JanDeDobbeleer/oh-my-posh#321]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

![image](https://user-images.githubusercontent.com/1082694/103726080-a6184400-4f9d-11eb-93a7-6aa24ed23e22.png)

I am trying to create a prompt that looks like the PNG embedded above, which is just a mockup. Notice that the prompt is made up of 4 blocks, labeled 1 through 4. And I'm sorry the two fields on the right are so hard to see - the contrast is better in real life.

I am having trouble getting all 4 blocks to be visible with the cursor landing after block 3. Can you help?

FYI, here are some of the things I have tried:
* block 1, align=left
* block 2, align=right
* newline
* block 3, align=left
* block 4, align=right

This put all of the blocks in the right places, but the cursor lands on the screen's far-right end, after block 4.

Here's another experiment:
* block 1, align=left
* block 2, align=right
* newline
* block 4, align=right
* block 3, align=left

This causes blocks 1, 2, and 4 to be displayed in their proper spots. However, block 4 begins to display immediately after block 3, on the screen's very far right. It then wraps to the next line, leaving a gap on the left side of the screen between blocks 1 and 3.

Another one:
* block 1, align=left
* block 2, align=right
* newline
* block 4, align=right
* newline
* block 3, align=left

This time everything is great, except there is a gap between blocks 1 and 3. Makes sense - that's obviously what I requested. But I thought this one was close, so I tried tweaking it:

* block 1, align=left
* block 2, align=right
* newline
* block 4, align=right
* newline
* block 3, align=left, vertical offset = -1

This caused the first 3 blocks to appear where they should, with the cursor after block 3, which is what I want. However, block 4 is not visible after the prompt renders, so it looks like block 3 deleted everything on the second line before being rendered.

I hope this makes sense. I may have made mistakes above as I'm trying to switch configurations in a single config file and then observe the effect and report it here in this little tiny box. :-) But the point is that I can't find a way to put all 4 blocks where I want them, with the cursor ending up after block 3. Is this possible?
### Environment

- Oh my Posh version: 3.44.1
- Theme: a variation on jandedobbeleer. I will attach it.
- Operating System: Windows 10 build 21277.1000
- Shell: Powershell, both versions 7.1.0 and 5.1.21277.1000
- Terminal: Windows Terminal 1.4.3243.0 and ConEmu 201011 Preview

### Steps to Reproduce

1. Use the attached theme, or one of the variants described above
2. Observe and ponder

**Expected behavior:** [What you expected to happen]
Blocks 1, 2, 3, 4 all where they are in the mockup, with the cursor placed after block 3.

**Actual behavior:** [What actually happened]
It depends on how I order and configure the blocks (see above).

Here is my theme (this is the final layout discussed above which uses vertical offset):
```
{
  "blocks": [
    {
      "type": "newline"
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "shell",
          "style": "diamond",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "\uE0B4",
          "foreground": "#ffffff",
          "background": "#444444",
          "properties": {
            "prefix": " \uFCB5 "
          }
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B4",
          "foreground": "#151515",
          "background": "#448844",
          "properties": {
            "prefix": " \uE5FF ",
            "styles": "agnoster, agnoster_full, agnoster_short, full, folder",
            "style": "agnoster"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B4",
          "foreground": "#111111",
          "background": "yellow",
          "properties": {
            "display_stash_count": true,
            "display_upstream_icon": true
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "envvar",
          "style": "diamond",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "\uE0B4",
          "foreground": "#555555",
          "background": "#000000",
          "powerline_symbol": "\uE0B4",
          "properties": {
            "var_name": "POSH_lastCommandDuration"
          }
        }
      ]
    },
    {
      "type": "newline"
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "time",
          "style": "diamond",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "\uE0B4",
          "foreground": "#555555",
          "background": "#000000",
          "powerline_symbol": "\uE0B4",
          "properties": {
            "time_format": "mon 02-jan-2006 15:04"
          }
        }
      ]
    },
    {
      "type": "newline"
    },
    {
      "type": "prompt",
      "alignment": "left",
      "vertical_offset": -1,
      "segments": [
        {
          "type": "session",
          "style": "diamond",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "\uE0B4",
          "foreground": "#ffffff",
          "background": "blue",
          "powerline_symbol": "\uE0B4"
        },
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "\uE0B4",
          "foreground": "#ffff66",
          "background": "#770000"
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "\uE0B4",
          "foreground": "red",
          "background": "white",
          "always_enabled": true,
          "always_numeric": true,
          "display_exit_code": true
        }
      ]
    }
  ],
  "final_space": true
}
```

**Comment by tradiff** [comment]
Maybe something like this:

![image](https://user-images.githubusercontent.com/934490/103727469-8fbbb980-4f98-11eb-8219-2a0627608b1f.png)


```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
  "blocks": [
    {
      "type": "rprompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#ffffff",
          "properties": {
            "text": "block 4"
          }
        }
      ]
    },

    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#ffffff",
          "properties": {
            "text": "block 1"
          }
        }
      ]
    },

    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#ffffff",
          "properties": {
            "text": "block 2"
          }
        }
      ]
    },

    {
      "type": "newline"
    },
    
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#ffffff",
          "properties": {
            "text": "block 3"
          }
        }
      ]
    }
  ]
}
```

**Comment by sql-sith** [comment]
Thank you, @TravisTX . I had forgotten about `rprompt` altogether, and it sounds like it may be meant for exactly what I'm trying to do. 

However, I am having trouble reproducing your result. When I run your sample as-is I get this:

![image](https://user-images.githubusercontent.com/1082694/103732748-aa4c5d80-4fad-11eb-870f-bcf2fc21e919.png)

I've tried tweaking it, but this combination of things makes me uncertain of what to tweak:
* block 4 is referenced first in the config
* block 4 is referenced before the newline
* block 4 has align=left (?)

Thanks again for the prompt response. Sorry I'm not able to sift an answer out of a good reply like that.

**Comment by JanDeDobbeleer** [comment]
@sql-sith it seems your version of oh-my-posh is rather old. Updating should do the trick as I don't think your version has `rprompt` support just yet.

**Comment by sql-sith** [comment]
@JanDeDobbeleer you are correct. I checked for newer versions tonight but obviously messed it up. 

By the way, this is one of the most useful and comprehensive updates to a popular open-source project that I've seen for a while. Great job to all.
