### ISSUE TITLE
Black arrow in some segments of theme JanDeDobbeleer are black if using background image in Window terminal

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#322]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
In Window terminal, when I use theme JanDeDobbeleer there are some black arrows between segments if I use background image (`backgroundImage` option) instead of transparent arrows. It isn't the case if I use background color (`background` option).

Even if I use a single color image, the black arrow still appear:

![image](https://user-images.githubusercontent.com/42483897/103728655-304dc000-5011-11eb-83a3-9a9e8780d80b.png)

### Environment

- Oh my Posh version: 3.68.4
- Theme: JanDeDobbeleer 
- Operating System: Win 10 1909
- Shell: Powershell 7.1
- Terminal: Window terminal 1.5.3142.0

**Comment by JanDeDobbeleer** [comment]
That's a Windows terminal issue. The arrow is transparent but Windows Terminals for some reason adds black rather than the bg image. Can you log the issue there?

**Comment by JanDeDobbeleer** [comment]
@Fubuchi there might be some more information [here](https://github.com/microsoft/terminal/issues/1414) (and a way to turn it on). If that's not the issue, then it's going to be [this one](https://github.com/microsoft/terminal/issues/7014).

**Comment by Piervn** [comment]
What is the solution to this problem?

**Comment by JanDeDobbeleer** [comment]
@Piervn using the Atlas renderer in Windows Terminal.

**Comment by Piervn** [comment]
![Zrzut ekranu 2023-11-02 152809](https://github.com/JanDeDobbeleer/oh-my-posh/assets/74148308/131fc141-1c3f-4eed-b29e-9d6752a8b11e)

I've turned on "Use the new text renderer ("AtlasEngine")" in Settings > Defaults > Advanced and still it doesn't work.
