### ISSUE TITLE
v12.28.2 `install-amd64.exe /SILENT /NORESTART` shows progress == not silent

### ISSUE THREAD

**Issue by o-l-a-v** [JanDeDobbeleer/oh-my-posh#3233]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I tried out the new release candidate of winget, where oh-my-posh was one of the programs that needed an upgrade.

Testet out `winget upgrade --all --silent` to see if this bug was fixed in winget 1.4:

* https://github.com/microsoft/winget-cli/issues/2008

But then oh-my-posh showed install progress. Then checked the winget logs, and `/SILENT /NORESTART` was passed to the installer (details in the URL above).

I then tested manually by downloading the oh-my-posh installer from following URL:

* https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v12.28.2/install-amd64.exe

Opened CMD without admin permisisons, `install-amd64.exe /SILENT /NORESTART`, and progress was showed.

Breaking change in the newest installer? Pretty sure previous versions were actually silent.

### Theme

Not applicable.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
Not applicable.
```

**Comment by JanDeDobbeleer** [comment]
@o-l-a-v the flag is incorrect. It should be `/VERYSILENT`. This is also something winget EXPLICITLY confirmed they would handle as I had to remove those from the manifest.

**Comment by o-l-a-v** [comment]
Thanks for the prompt reply @JanDeDobbeleer. I wrongfully assumed winget passed the correct parameters as it has previously, should've thought about the actual install parameters for silent install with the Inno installer.

Tested with current stable winget, v1.3.2691, and it passes `/VERYSILENT`. So created an issue in winget-cli repo.
