### ISSUE TITLE
"Cannot run a document in the middle of a pipeline"

### ISSUE THREAD

**Issue by Ombrelin** [JanDeDobbeleer/oh-my-posh#3236]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After installing oh-my-posh, when running `oh-my-posh init pwsh | Invoke-Expression`, I get : 

```pwsh
Line |
   1 |  oh-my-posh init pwsh | Invoke-Expression
     |  ~~~~~~~~~~~~~~~~~~~~
     | Cannot run a document in the middle of a pipeline:
     | /usr/local/bin/oh-my-posh.

```

### Theme

N/A

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

powershell

### Log output

```Shell
It's empty
```

**Comment by JanDeDobbeleer** [comment]
@Ombrelin did you make oh-my-posh executable? Because that can be the cause of that error. This is a new error altogether for me though.

**Comment by Ombrelin** [comment]
I thought I had, as indicated in the docs, but after redoing it, it works. Thank you !
