### ISSUE TITLE
Subversion segment reports a lot of files as "x"

### ISSUE THREAD

**Issue by mjcarman** [JanDeDobbeleer/oh-my-posh#3242]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The svn segment (with `{{.Working.String}}`) reports a lot of things as "`x`." It's hard to understand why this count has the value it does even in a clean (or mostly clean) checkout. The segment documentation doesn't list "x" as a icon so it's not clear what the value is supposed to mean without poking into the source code in svn.go and scm.go. Doing that makes it clear that svn.go is [ab]using the "Unmerged" field as the default counter while parsing "svn status" output. (The "x" value thus includes untracked files, ignored files, and externals, amongst other things.)

I request/recommend changing the `add` method of svn.go to map values to counters as follows:

- '?' → Untracked
- 'I' → (don't count; it means "ignored" to svn)
- 'R', '!' → Moved ("R" is "replaced", "!" is item missing; i.e. moved or deleted outside of SVN)
- default → (do nothing)

I'm willing to make the changes and submit a pull request for this if you agree with this report and my recommendations.

### Theme

Custom theme containing `svn` segment with template `" \ue0a0{{.Branch}} r{{.BaseRev}} {{.Working.String}}"`

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (cmd)

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@mjcarman please go ahead and make that PR! Looking forward to it. Also, merry Christmas!
