### ISSUE TITLE
Suggestions caused by Get-GitStatus with every command on PowerShell 7.2.0

### ISSUE THREAD

**Issue by daddycocoaman** [JanDeDobbeleer/oh-my-posh#325]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I've updated my oh-my-posh installation and this PR https://github.com/JanDeDobbeleer/oh-my-posh3/pull/130 seems to have caused some unintended issues with PowerShell 7.2.0. Essentially, every command I run results in seeing `Suggestion [4,General]: The most similar commands are: Get-BCStatus.` at the end of the output.  This is because `Get-GitStatus` does not exist. 

This check https://github.com/JanDeDobbeleer/oh-my-posh3/blob/main/src/init/omp.ps1#L11 is causing the problem. If I invoke `Get-Command -Name "Get-GitStatus" -ErrorAction SilentlyContinue`, there is no output but I still get the suggestion. 

### Environment

- Oh my Posh version: 3.68.4
- Theme: Any
- Operating System: Windows 10 Pro
- Shell: PowerShell 7.2.0-preview.1
- Terminal: Windows Terminal 1.5.3242.0

### Steps to Reproduce

1. `Set-PoshPrompt -Theme <any theme>`
2. Run a command
3. See suggestion output in command

**Expected behavior:** [What you expected to happen]
Commands to run without suggestion output

**Actual behavior:** [What actually happened]
Every command has suggestion for Get-BCStatus.

I should mention that this doesn't occur with PowerShell 7.1.0 and isn't a fault of OMP3 but it might be something to track. This issue filed here suggests it's a known problem. https://github.com/PowerShell/PowerShell/issues/11906

**Comment by JanDeDobbeleer** [comment]
I noticed that too and it annoys the crap out of me.

**Comment by daddycocoaman** [comment]
Sorry...I forgot to add my solution. 

You should use `Get-Module` instead. Get-Module returns an object or it doesn't, so there's no suggestions being made.

```powershell
(Get-Module posh-git).ExportedCommands.Keys.Contains("Get-GitStatus")
```

This command will return True if Get-GitStatus exists, It will return False if it doesn't exist but Posh-Git is installed (I don't use posh-git so dunno if this is possible).  If `posh-git` doesn't exist at all, there's no output.

**Comment by JanDeDobbeleer** [comment]
@daddycocoaman 👍🏻 , in the meantime I was on the same path :-) See the [commit](https://github.com/JanDeDobbeleer/oh-my-posh3/commit/0c240689dc4bd06195775b0f11f8528133298829) linked. There's no output when I do things this way.

**Comment by daddycocoaman** [comment]
Dope. Thanks for dope tool!
