### ISSUE TITLE
Subversion: Display basic info when fetch_status is false

### ISSUE THREAD

**Issue by mjcarman** [JanDeDobbeleer/oh-my-posh#3252]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The git segment parses the HEAD file to get the branch name when `fetch_status` is false. The svn segment just displays empty information (" \ue0a0 r0" with the default template) which isn't useful. It would be better to provide basic information (branch and revision) in this situation. There are two obvious ways to implement this.

**Option 1**
Fetch the branch name and revision by running the following query against .svn/wc.db:

`SELECT REPOS_PATH,REVISION FROM NODES WHERE LOCAL_RELPATH=""`

This is the most analogous to parsing the HEAD file for git, but would require adding an SQLite library as a dependency. Whether or not this would be faster than current two calls to `svn info` would require benchmarking.

**Option 2**
Change the semantics of `fetch_status` so that it only controls running `svn status`. Run `svn info` unconditionally (or make it conditional on a different flag, e.g. `fetch_info`).

**Comment by JanDeDobbeleer** [comment]
If we do this, it's option 2 for sure. Option 1 is too much overhead and will require CGO as well.
