### ISSUE TITLE
RAM usage 

### ISSUE THREAD

**Issue by Andrew1988123123** [JanDeDobbeleer/oh-my-posh#3272]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have 32GB of RAM in total but 1_shell template indicate that I have 34GB RAM in total. That is not true. Screen below. Utilization of RAM is different compared to utilization showed in Task Manager. Which tool measure RAM in wrong way? Oh-my-posh or Task Manager?
https://imgur.com/a/RakpthV

### Theme

1_shell

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Doesn't matter.
```

**Comment by JanDeDobbeleer** [comment]
@Andrew1988123123 we use the [gopsutil](https://github.com/shirou/gopsutil/blob/master/mem/mem_windows.go) library for this, and I validated the syscalls myself, Windows actually returns a wrong value there. So we can't solve that, best is to create an issue over at gopsutil.

**Comment by JanDeDobbeleer** [comment]
I'm going to see what [this](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-globalmemorystatusex) call returns. [Samples](https://cs.github.com/?scopeName=All+repos&scope=&q=Language%3Ago+GlobalMemoryStatusEx+).

**Comment by Andrew1988123123** [comment]
> @Andrew1988123123 we use the [gopsutil](https://github.com/shirou/gopsutil/blob/master/mem/mem_windows.go) library for this, and I validated the syscalls myself, Windows actually returns a wrong value there. So we can't solve that, best is to create an issue over at gopsutil.

Ok. I think we can close the issue
