### ISSUE TITLE
Oh-My-Posh not showing itself on terminal of my M1 Mac

### ISSUE THREAD

**Issue by usman1515** [JanDeDobbeleer/oh-my-posh#3280]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have been trying to install oh-my-posh on my M1 Macbook Air, 8GB RAM, 256 GB SSD running MacOS Monterey v12.5. 
I have already done the following:
- installed a Nerd font ie "caskaydiacove nerd font"
- installed and setup the default shell to BASH
- using iterm2 as my default terminal emulator.

To setup oh-my-posh I did the following:
```
brew install jandedobbeleer/oh-my-posh/oh-my-posh
brew update
brew upgrade oh-my-posh
oh-my-posh get shell   # prints bash as default shell

# added te following line to my ~/.bash_profile
eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)"
```

When I refresh and close the terminal no changes take place. Can you tell me what exactly am I doing wrong? I am already using oh-my-posh kali theme on my main linux machine using the same shell and nerd font on Terminator using the instructions from (here)[https://ohmyposh.dev/docs/installation/linux] and it works perfectly. 

### Theme

currently none but want to use kali

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
none
```

**Comment by JanDeDobbeleer** [comment]
@usman1515 on mac, I add this to `.bashrc`

> added te following line to my ~/.bash_profile

**Comment by usman1515** [comment]
I have created a `~/.bashrc` file and added the following line `eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)"` but still no change.
PS. currently both `.bashrc` and `.bash_profile` file exists in `$HOME`

**Comment by JanDeDobbeleer** [comment]
@usman1515 you have to understand why bash isn't loading the profiles, unfortunately that goes beyond oh-my-posh's functionality, we can't solve that one. See these threads for a possible solution:

- https://stackoverflow.com/a/29152555
- https://superuser.com/questions/573633/bash-profile-not-sourced
- https://stackoverflow.com/a/25025999
