### ISSUE TITLE
exit segment doc addition

### ISSUE THREAD

**Issue by dcnieho** [JanDeDobbeleer/oh-my-posh#3296]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

The docs tell us that .Meaning may be equal to .Code, or may be a textual representation of it. I wan't to show .Meaning only if its not equal to .Code. It was not obvious how to do this, but searching through this repo found a solution. Could you add the required template logic to the doc? What worked:
`"template": " {{ if gt .Code 0 }}\uf00d{{ else }}\uf00c{{ end }}{{ if (ne .Meaning (toString .Code)) }} {{ .Meaning }}{{ end }} "`

**Comment by JanDeDobbeleer** [comment]
@dcnieho why would this be a necessary doc change? As everyone's free to alter the templates how they see fit, in this case it's very specific use-case (which I completely understand).

**Comment by dcnieho** [comment]
I would have found it helpful, since I don't know Go, nor was it clear to me that .Meaning is a string even if its "equal" to .Code and thus can't be compared directly. I just got `unable to create text based on template` and no idea why, luckily i could find the correct syntax through a search. Perhaps an addition like "to test whether .Code and .Meaning are different, use `if (ne .Meaning (toString .Code))`" could be helpful.

**Comment by JanDeDobbeleer** [comment]
@dcnieho in the latest version that exact context is printed to the segment instead of that text. Very recent change I might add.
