### ISSUE TITLE
Issue with the fonts

### ISSUE THREAD

**Issue by ozerty** [JanDeDobbeleer/oh-my-posh#33]
Hi,
I am still facing icons issue on Powershell with the theme "jandedobbeleer.json".
Meslo LGM NF fonts are installed.

![image](https://user-images.githubusercontent.com/24736353/95240627-b112db00-07da-11eb-95c0-b66cb3e355f0.png)

Here the theme file coming directly from the module:
![image](https://user-images.githubusercontent.com/24736353/95241624-03083080-07dc-11eb-9dba-b66f511c98de.png)

I suppose the encoding is broken.

I am using: 
- Windows 10 Pro (build 2004)
- Powershell 7.0.3
- Powershell module : oh-my-posh 3.5.1 (scope: CurrentUser)

Thanks

**Comment by JanDeDobbeleer** [comment]
I noticed there are multiple types of Meslo (even the LG variant). I can confirm the encoding is ok as I install the same font on every machine I test on to check the changes, so 9/10 there's a difference in the actual font being used. Can I suggest you use the font you like the most and add your own icons, or do you want me to share the exact font I've installed on my Windows test machine so you can validate this?

**Comment by ozerty** [comment]
If you can share the exact font you have installed on your Windows, that would be great.
Thanks

**Comment by JanDeDobbeleer** [comment]
I'll do that first thing in the morning!

**Comment by JanDeDobbeleer** [comment]
Hey @ozerty the font I use there is `MesloLGM Nerd Font`. The file name is `Meslo LG M Bold Nerd Font Complete.ttf`
It's in the attachment. This one renders according to spec in Windows.
[Meslo.zip](https://github.com/JanDeDobbeleer/oh-my-posh3/files/5345818/Meslo.zip)
<img width="401" alt="image" src="https://user-images.githubusercontent.com/2492783/95424723-ed882900-08f7-11eb-9cfa-580c65c1d847.png">

**Comment by nwykes** [comment]
Terminal needs to be configured to use the font as well so double check the "Settings" there.  You can set each individual profile to use a specific font, or set a default that's used by all profiles.

```
"profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
            "colorScheme": "Gruvbox Dark",
            "fontFace": "JetbrainsMono NF",
            "fontSize": 11
        }
```

**Comment by JanDeDobbeleer** [comment]
@ozerty were you able to resolve the issue?

**Comment by ozerty** [comment]
It's working perfectly now.
The font was missing in my terminal settings.
Thanks both of you @JanDeDobbeleer and @nwykes
