### ISSUE TITLE
Git Upstream Icons

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#3300]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Happy New Year Jan!

Would it be possible to consider these feature requests please?:

1. Add a 'local_git_icon' property that will get used if no remote is set (I know I can use '{{ if .UpstreamIcon }}{{ .UpstreamIcon }}{{ else }}Local Git{{ end }}' in my theme). While you're at it maybe add an 'unknown_remote_icon' to use if something other than github, gitlab, bitbucket or ADO is used.
2. We use an on prem version of Azure Dev Ops and it doesn't contain "dev.azure.com" or "visualstudio.com" in the URL. Maybe a custom keyword could be set for it somehow. (Happy to use the 'unknown_remote_icon' from above if this is too tricky to do cleanly).

Thanks.

**Comment by piersmyers** [comment]
Actually the 'git_icon' does get used if the remote is not known, but not if the remote is not set, the .UpstreamIcon will be blank in that case.

**Comment by JanDeDobbeleer** [comment]
@piersmyers you can now use your own custom map of upstream URL's and icons using `upstream_icons` in the [git](https://ohmyposh.dev/docs/segments/git#upstream) segment.
