### ISSUE TITLE
.Segments.Exit.Code doesn't exist in transient prompt

### ISSUE THREAD

**Issue by dcnieho** [JanDeDobbeleer/oh-my-posh#3303]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Only `{{.Segments.Exit.Meaning}}` is available, not `{{.Segments.Exit.Code}}`, could you make the latter available as well?

`{{.Segments.Exit}}` prints `map[Meaning:ERROR]`

**Comment by JanDeDobbeleer** [comment]
@dcnieho code is available as `.Code`, indicated [here](https://ohmyposh.dev/docs/configuration/templates#global-properties).

**Comment by dcnieho** [comment]
As super! so there is no need for the more complicated path ;) Not sure if it should still be available through that path as well, should someone want to use that or not know any better. You decide ;)
Thanks!

**Comment by JanDeDobbeleer** [comment]
@dcnieho it was originally part of the segment but got moved to a global level later for this specific reason.
