### ISSUE TITLE
Spotify Segment no longer works with Web player (on Windows)

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#3310]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Playing Spotify using the web browser (Edge) does not show up in the Spotify segment.

This is probably due to the browser tab title being "[Track] • [Artist]" (without starting with "Spotify - ". Note also that the track  -  artist order is different to the native app that uses Artist - Track.

Does your code only detect the Edge browser? Not a problem for me as that is my primary browser but it probably should work for Chrome, Firefox (not IE though!)

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@piersmyers correct, we do validate for `Spotify*` and query all windows. This will be an issue though, as there will be other applications with the same title format, I believe in the past we had issues with vscode.

**Comment by JanDeDobbeleer** [comment]
@piersmyers can you give me some samples of Window titles? My lovely ARM64 device refuses to play using the web player and on MacOS I can still see `Spotify - xx xxx` also using Edge.

**Comment by piersmyers** [comment]
Hi @JanDeDobbeleer, I open a new Edge browser window in Windows 10  with a single tab with the URL of https://open.spotify.com, and then navigate to one of my playlists. When not playing the window title is something like "Spotify – Discover Weekly - Personal - Microsoft​ Edge Dev", when playing the title changes to "1st Man in Space • The All Seeing I - Personal - Microsoft​ Edge Dev". If more than one tab is opened then the all the Spotify info is lost from the window title.

To be honest I don't typically run Spotify in a browser as the Spotify App is much better (and works perfectly with oh-my-posh) but occasionally I will use it at work as that is all we have access to. I am not sure how detecting whether Spotify is running in a browser with multiple tabs is even possible on Windows at least, maybe Macs handle the browser window naming differently.

**Comment by JanDeDobbeleer** [comment]
@piersmyers it only support the PWA, so you need to install it as an app for it to work. Otherwise we can't even access that information.

**Comment by piersmyers** [comment]
@JanDeDobbeleer ah, that makes much more sense, And that way works, however the artist / track info is reversed (compared to the native app). PWA title is "Spotify - 1st Man in Space • The All Seeing I" where as native app is "The All Seeing I - 1st Man in Space"

**Comment by JanDeDobbeleer** [comment]
@piersmyers but is the information in your terminal correct?

**Comment by piersmyers** [comment]
@JanDeDobbeleer no it is reversed when using PWA

![image](https://user-images.githubusercontent.com/5651200/211204845-a38d2fa8-26f9-44d2-b9db-46f656e2c1a7.png)

If running both the native app and PWA, the native app takes priority so ensure that's not running in the background.

**Comment by piersmyers** [comment]
@JanDeDobbeleer this works great now, thanks for fixing. Perhaps you can update your docs to state that the Spotify segment works with the native app or an Edge PWA app only?
