### ISSUE TITLE
12.34.6 introduced a weird formatting issue in the git segment

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#3323]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In my git segment (in YAML) I have:

```
templates:
  - '{{ url .RepoName .UpstreamURL }} ['
  - '{{ .HEAD }}]'
 ```

In version 12.34.5 the formatting is correct ("MyRepoURL [main]") but in 12.34.6 it converts the '[' to a carriage return and appends the remainder of the git prompt to the end of the proceeding line. If I change the '[' to a different character then it works as before.

This issue still affects 12.35.1

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
Interesting. I'll check!

**Comment by piersmyers** [comment]
Thanks, even more weird is that it's also dependant on whether the remote url is set or not. If not then it works fine else it's broken.

**Comment by JanDeDobbeleer** [comment]
@piersmyers I'll debug asap. Going to be perfectly logical.

**Comment by JanDeDobbeleer** [comment]
@piersmyers it was silly really. Solved and also fixed the formatting for hyperlinks 🥳
