### ISSUE TITLE
Setting fg/bg colors globally for enhancing visual appearance

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#3327]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I have searched through the available docs and didn't find an answer. If it's there and I somehow missed it, I'd be happy to read the docs again and teach myself how to do it. If it's indeed a missing feature, feel free to consider it a valid feature request.

For quickly distinguishing between different neighbor segments, oh-my-posh allows setting fg/bg colors per segment. The problem with this hardcoded approach is that sometimes segments are invisible, depending of context, thus for any two segments to be visually different, each segment must have its own unique fg/bg color. Another approach would be to have a global list of fg/bg color pairs (with at least two items, but can be more than two) and have oh-my-posh automatically cycle through them when drawing segments one by one. Such an approach is implemented for example in https://github.com/tobi-wan-kenobi/bumblebee-status - a status bar generator for i3wm. Here's how it looks:

https://raw.githubusercontent.com/tobi-wan-kenobi/bumblebee-status/main/screenshots/themes/powerline-solarized.png

you can easily notice the alternating colors.

The concept is described here https://bumblebee-status.readthedocs.io/en/main/development/theme.html , see the `cycle` attribute.

Is it possible to get something similar in oh-my-posh?

**Comment by ghost** [comment]
Thanks for the very quick delivery! :+1: 

I have a question. Here's a quote from the docs:

> If there's nothing in the list anymore and your prompt would still render additional segments, the segment's colors are being used.

What is the reason for this design choice? During the first attempt to adapt my config I got slightly confused. Initially my `cycle` array had two items:

    "cycle": [
    {
      "foreground": "#81a1c1",
      "background": "#2e3440"
    },
    {
      "foreground": "#2e3440",
      "background": "#81a1c1"
    }]

I expected that for the third segment, first array element will be reused again, then second one etc.

Minor itch, because this was easily fixed by copypasting these two items to extend the size of `cycle` array to match the maximum amount of segments in my config, but the repeating pieces just feel a bit redundant.

**Comment by JanDeDobbeleer** [comment]
@toolonely because that felt logical? Dunno, made that decision on the fly. Although the cycle name suggests this could be challenged, it wasn't specified in the request so I did what made sense to me at the time of implementation. A repetitive cycle is technically more challenging but probably not impossible.

**Comment by ghost** [comment]
> Although the cycle name suggests this could be challenged

Hence my question, but as I said, I am fine with the current implementation. Thanks again.

**Comment by JanDeDobbeleer** [comment]
@toolonely already looking at it, should be perfectly possible.

**Comment by JanDeDobbeleer** [comment]
@toolonely I have a solution ready. Will push later today.
