### ISSUE TITLE
Add support for vala programing language

### ISSUE THREAD

**Issue by wszqkzqk** [JanDeDobbeleer/oh-my-posh#3329]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Could the recognition support of vala be added? Vala is a programing language developed by GNOME, and it's widely used in GNOME apps. Some popular tools such as KDE's Kate have added support for it.

[The official website](https://vala.dev/)

**Comment by bend-n** [comment]
But like, where is this to be used?

**Comment by wszqkzqk** [comment]
> But like, where is this to be used?

OhMyPosh can show the environment about the language when the directory contains related source files.
