### ISSUE TITLE
`oh-my-posh` will hang if a git repository is corrupted

### ISSUE THREAD

**Issue by nopeless** [JanDeDobbeleer/oh-my-posh#3332]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I was running IntelliJ like usual but realized that my terminal (PowerShell) hung. I investigated and found out that `oh-my-posh init pwsh | Invoke-Expression` was the line that was causing the block.

But PowerShell works fine on every other terminal and IDE. I narrowed it down to oh-my-posh trying to execute git commands while IntelliJ is trying to do things with their VCS.

`git status` shows

`daemon terminated`

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
debug hangs
```

**Comment by nopeless** [comment]
I believe that this should be mentioned somewhere in the FAQ as I have checked and there was nothing like this

**Comment by JanDeDobbeleer** [comment]
@nopeless the init command doesn't execute git commands though. Unless you have posh-git enabled. I can add something to the FAQ but I can't solve this. When a CLI call hangs (git or other) this will always cause everything to hang.

**Comment by nopeless** [comment]
Well, I resolved this issue by restarting my computer. I did some further investigation and found out that it has to do with git fs-daemon

Now I'm not sure if this is even worth putting in FAQ, but I do think that `init` should report any errors back to the user (as the terminal did output the custom terminal after 20~30 seconds normally)

**Comment by JanDeDobbeleer** [comment]
@nopeless the only sensible thing to do here is see if we can add a timeout to external commands and limit the duration. But for troubleshooting we do have `oh-my-posh debug` which will display this for you.

**Comment by nopeless** [comment]
I see. Would the timeout implementation be hard?

**Comment by JanDeDobbeleer** [comment]
I'll give it a go tomorrow.

**Comment by nopeless** [comment]
good luck 👍

**Comment by JanDeDobbeleer** [comment]
Implemented in the latest release. Timeout is 4 seconds.
