### ISSUE TITLE
Square brackets in git template causing issues (again)

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#3353]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Sorry to be a pain Jan, this relates to #3323 

If I set my git templates to:

```
templates:
  - '[]'
  - '{{ url .RepoName .UpstreamURL }}'
  - '[]'
 ```

I get `][MyRepo[]` (the url link text is `][MyRepo` but the url itself is fine).

Weirdly, using `- '[] []{{ url .RepoName .UpstreamURL }}[] []'` gives `] [][MyRepo[] []`

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@piersmyers you sure have a ton of exotic templates and I love you for it.

**Comment by piersmyers** [comment]
Ha, this is not my actual template but just the minimum to highlight the issue, my actual one is far more exotic ;)

**Comment by JanDeDobbeleer** [comment]
@piersmyers the "challenge" with this is that hyperlinks are created using [text](url) syntax and the we loop over every character to see if we're in a link or not. And that one is confused.

**Comment by piersmyers** [comment]
@JanDeDobbeleer can the square brackets be escaped somehow? I think they are the only character causing this issue - unit tests to test all the other characters maybe? ;)

**Comment by JanDeDobbeleer** [comment]
@piersmyers I just need to understand which use case is missed and fix it. Every other case is added to the tests so eventually we'll have them all.

**Comment by piersmyers** [comment]
@JanDeDobbeleer Thanks for fixing this, all works fine for me again. Woohoo, and I got a major version release for the fix. It even works with the left and right pointing double angle quotation marks («»), not that I use them yet (but maybe I will now) :)

**Comment by JanDeDobbeleer** [comment]
@piersmyers I chose those because who will use that, right?
