### ISSUE TITLE
Git segment doesn't always detect upstream URL

### ISSUE THREAD

**Issue by piersmyers** [JanDeDobbeleer/oh-my-posh#3355]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have a number of repos, all with their upstream urls set (and push/pull working) but oh-my-posh is not setting the `.UpsreamURL` or `.UpstreamIcon` for some of them.

All of my repos have the following git results:

```
> git remote
origin

> git remote get-url origin
https://platform/tfs/DefaultCollection/MyProject/_git/MyRepo
```

I have also run `oh-my-posh debug` but didn't see any git remote info in the results (I can't post it as it contains sensitive info).

I can't see any obvious differences between the repos that work and those that don't (apart from the remote url, but they all have the same pattern as above). Is there any other debugging I can run?

My git segment template is a nice friendly `({{ .UpstreramURL }} - {{ .UpsteamIcon }})` and returns `( - )` for some and `(https://platform/tfs/DefaultCollection/MyProject/_git/MyRepo - TFSIcon)` for others.

I think this may be branch related, it seems that if the remote branch is not set then the upstream URL is not set. For example:

```
> git branch -a
FooBar
main
remotes/origin/main
```

In the `main` branch the upstream URL gets set but in the `FooBar` branch it doesn't (even though `git remote get-url origin` returns the url regardless of which branch I'm in.

Is this by design? I would expect the upstream URL to be set regardless of what branch you are in or whether it had a remote branch. The `.BranchStatus` is correctly set to 'branch_gone_icon' if no remote branch is found.

### Theme

Home grown

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
> I would expect the upstream URL to be set regardless of what branch you are in or whether it had a remote branch.

That's not how this works though. As the upstream can differ based on the branch we check the branch's upstream and construct the URL from there. See [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/4f83452e84a4bea452c34c8e97f5b7feda6a13d4/src/segments/git.go#L674).

So to understand why it doesn't work for that branch, you'll need to see the debug logs. We could do another check and fallback to `origin` [afterwards](https://github.com/JanDeDobbeleer/oh-my-posh/blob/4f83452e84a4bea452c34c8e97f5b7feda6a13d4/src/segments/git.go#L682), but that would be guessing and not a certainty obviously.
