### ISSUE TITLE
Git `UpstreamIcon` does not work in a git worktree

### ISSUE THREAD

**Issue by ADIX7** [JanDeDobbeleer/oh-my-posh#3364]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

`UpstreamIcon` does not work in git worktree folders in the git segment. It happens with my own config. I also cloned this repo, opened the devcontainer, cloned a random repo from github in the container, created a new worktree, switched to it, UpstreamIcon did not show.

### Theme

Default (jandedobbeleer.omp.json)

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

fish, powershell

### Log output

```Shell
not relevant
```

**Comment by JanDeDobbeleer** [comment]
@ADIX7 I'll need to debug this to see which folder pointer we need. It's all there, I just need to adjust to the correct one.

**Comment by JanDeDobbeleer** [comment]
@ADIX7 works for me. But, you need top have an upstream for the currently checked out branch. If not, this will never fetch that information. I'll tweak it to fallback to `origin`.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/2492783/212465269-ff380217-ae9b-4fd8-a020-45e1774caa06.png">

**Comment by ADIX7** [comment]
Hmmmm, I tested it in detached HEAD mode... Thank you for the fallback mechanism! It works perfectly!
