### ISSUE TITLE
Docs for hyperlinks missing?

### ISSUE THREAD

**Issue by ffes** [JanDeDobbeleer/oh-my-posh#3372]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In the Git docs at https://ohmyposh.dev/docs/segments/git#properties-1 are two links to "hyperlinks" which both point to https://ohmyposh.dev/docs/configuration/templates#helper-functions, but there is no description how to build.

Especially the fancy Unicode chars that are needed since 13.0.0 are not mentioned there. Maybe I overlooked something, but if that is the case they are hard to find. I had to copy-paste them from the release notes of v13.0.0.

### Theme

Any theme

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
Not relevant
```

**Comment by JanDeDobbeleer** [comment]
@JanDeDobbeleer the first two in the [custom section](https://ohmyposh.dev/docs/configuration/templates#custom) are the ones you need.

**Comment by ffes** [comment]
But where is the `<<text>>(link)` syntax (with those Unicode chars) explained? That is what i'm missing.

**Comment by JanDeDobbeleer** [comment]
@ffes you don't need that. That's actually an internal API/formatting. From a user perspective you should only be using the `url` and `path` template functions.

**Comment by ffes** [comment]
Ok, make sense. Thanks for clarifying this.

I have one additional question:

Before v13 I had `[{{ .UpstreamIcon }}{{ .HEAD}}]({{ .UpstreamURL }})` in my template.

I convert this to two separate `url`s because it seems impossible to combine two fields as the first parameter? I tried various combinations of curly braces and quotes.

The cosmetic (not a big deal) disadvantage of the two separate urls is that the underlining on hover is shown only under that element and not on the combined url, if that makes sense.

**Comment by JanDeDobbeleer** [comment]
@ffes this is a bit of hidden magic in go text templates:

```json
"template": " {{ url (print .UpstreamIcon .HEAD) .UpstreamURL }} "
```

**Comment by ffes** [comment]
That works great.

Nogmaals bedankt :wink:
