### ISSUE TITLE
New Versions missing in msstore

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh#3386]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The newest version in the msstore is 13.2.0 but the latest version is 13.5.0.
![Screenshot 2023-01-21 144241](https://user-images.githubusercontent.com/49693964/213869660-f773a86d-789d-450f-826e-10059631f736.png)

### Theme

x

### What OS are you seeing the problem on?

Windows

### Log output

```Shell
x
```

**Comment by JanDeDobbeleer** [comment]
@floh96 that's not a bug, the store is always lagging behind as they take longer to process a submission.
