### ISSUE TITLE
Some themes use unicode symbols not supported by some Terminals (Windows Terminal)

### ISSUE THREAD

**Issue by Fischchen** [JanDeDobbeleer/oh-my-posh#3389]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've found that some designs (atleast the ZASH) use the \uf119 Unicode character, which it seems like Windows terminal doesn't support: ![image](https://user-images.githubusercontent.com/61012902/213929722-7f43cce8-c960-4951-87e1-b9d5b5019a05.png)
Why is this? Is this a bug or intended?

I'm using CMD in Windows Terminal

### Theme

ZASH

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
I don't think this is relevant for this issue.
```

**Comment by JanDeDobbeleer** [comment]
@Fischchen that's a question for Windows Terminal. Or, you didn't install and configure a nerd font.
