### ISSUE TITLE
Missing icons for azure dev ops after migration

### ISSUE THREAD

**Issue by yunanj** [JanDeDobbeleer/oh-my-posh#3395]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After migration and removed module based OMP, I noticed there's some icon missing. 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/13696655/214378626-a86b1813-dc5e-4f5a-a98d-cbd88fee7aa4.png">

Connecting to repo in azure dev ops. 

### Theme

Unicorn

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@YunanJiang that icon was recently swapped by @kamfaima in #3336 So if it's not part of the standard set, we need to revert that change.

**Comment by yunanj** [comment]
Thanks!

**Comment by JanDeDobbeleer** [comment]
@YunanJiang I just validated and `\uEBE8` is correct according to the [cheat sheet](https://www.nerdfonts.com/cheat-sheet) and my terminal.
