### ISSUE TITLE
Theme: Tokyo

### ISSUE THREAD

**Issue by feamsr00** [JanDeDobbeleer/oh-my-posh#3400]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened... Maybe

Is Tokyo supposed to have two root segments?

https://github.com/JanDeDobbeleer/oh-my-posh/blob/48797568869882ce33c622c4e1902b501d2a50c0/themes/tokyo.omp.json#L23-L30

https://github.com/JanDeDobbeleer/oh-my-posh/blob/48797568869882ce33c622c4e1902b501d2a50c0/themes/tokyo.omp.json#L69-L74

### Theme

tokyo.omp.json

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@feamsr00 don't know. That's a question for @daht-x, he can provide the answer. Definitely by design in this case so we can always tweak if needed but it's his theme.
