### ISSUE TITLE
oh-my-posh 13.7.0+ breaks Midnight Commander's subshell

### ISSUE THREAD

**Issue by philippetev** [JanDeDobbeleer/oh-my-posh#3415]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

It seems the changes, introduced in version [13.7.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v13.7.0), don't seem to play well with the combo Midnight Commander/Bash. Running version [13.7.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v13.7.0) and later causes Midnight Commander to start slower than usual (something like a 10 seconds startup delay) and the subshell that can be accessed with Ctrl+O is missing, basically MC acts like it's compiled without the subshell support or it's started with the -u parameter (that disables the subshell): you can only watch the messages in the background, but you can't type and execute commands (pressing any key returns you to the MC window).

Versions prior to [13.6.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v13.6.0) (incl. [13.6.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v13.6.0)) don't seem to have this issue.

Tested on my local WSL (Debian 11, amd64, bash 5.1.4, mc 4.8.27), my Ubuntu Server VM (Ubuntu 22.04.1, amd64, bash 5.1.16, mc 4.8.27) and my NAS (Linux  4.2.8, aarch64, bash 5.2.15, mc 4.8.29).

### Theme

[philip.omp.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/10522989/philip.omp.zip)

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
┌[ProBook450G8][ﮟ]
└[philip] oh-my-posh debug

Version: 13.7.0

Segments:

ConsoleTitle(true) -   0 ms - philip@ProBook450G8
text(true)         -   0 ms - ┌
text(false)        -   0 ms -
session(true)      -   0 ms - [ProBook450G8]
path(true)         -   1 ms - [ﮟ]
text(true)         -   0 ms - └
session(true)      -   0 ms - [philip]
exit(true)         -   0 ms - 

Run duration: 4.532297ms

Cache path: /home/philip/.cache/oh-my-posh

Config path: /home/philip/.themes/philip.omp.json

Logs:

[DEBUG] 22:54:11.706 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.706 shell.go:Getenv(XDG_CACHE_HOME) - 58.298µs
[TRACE] 22:54:11.706 shell_unix.go:CachePath() - 121.348µs
[DEBUG] 22:54:11.706 shell.go:Getenv:336 → /home/philip/.themes/philip.omp.json
[TRACE] 22:54:11.706 shell.go:Getenv(POSH_THEME) - 4.155µs
[TRACE] 22:54:11.706 shell.go:resolveConfigPath() - 7.136µs
[TRACE] 22:54:11.706 shell.go:Init() - 347.7µs
[TRACE] 22:54:11.706 shell.go:Flags() - 74ns
[TRACE] 22:54:11.707 config.go:loadConfig() - 461.531µs
[TRACE] 22:54:11.707 shell.go:Flags() - 74ns
[DEBUG] 22:54:11.707 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.707 shell.go:Getenv(OMP_CACHE_DISABLED) - 2.398µs
[TRACE] 22:54:11.707 shell_unix.go:Root() - 896ns
[DEBUG] 22:54:11.707 shell.go:Shell:581 → process name: bash
[TRACE] 22:54:11.707 shell.go:Shell() - 311.708µs
[TRACE] 22:54:11.707 shell.go:ErrorCode() - 67ns
[DEBUG] 22:54:11.707 shell.go:Getenv:336 → Debian
[TRACE] 22:54:11.707 shell.go:Getenv(WSL_DISTRO_NAME) - 6.326µs
[TRACE] 22:54:11.707 shell_unix.go:IsWsl() - 8.767µs
[TRACE] 22:54:11.707 shell.go:GOOS() - 91ns
[DEBUG] 22:54:11.707 shell.go:Pwd:364 → NO DATA
[TRACE] 22:54:11.707 shell.go:Pwd() - 12.69µs
[TRACE] 22:54:11.707 shell.go:GOOS() - 36ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 21ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 22ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 26ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 24ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.707 shell.go:GOOS() - 20ns
[DEBUG] 22:54:11.707 shell.go:User:485 → philip
[TRACE] 22:54:11.707 shell.go:User() - 1.969µs
[DEBUG] 22:54:11.707 shell.go:Host:497 → ProBook450G8
[TRACE] 22:54:11.707 shell.go:Host() - 3.294µs
[TRACE] 22:54:11.707 shell.go:GOOS() - 22ns
[TRACE] 22:54:11.708 shell.go:TemplateCache() - 397.608µs
[TRACE] 22:54:11.708 shell.go:Flags() - 38ns
[DEBUG] 22:54:11.708 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.708 shell.go:Pwd() - 2.728µs
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:TemplateCache() - 104ns
[TRACE] 22:54:11.708 shell.go:Shell() - 66ns
[DEBUG] 22:54:11.708 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.708 shell.go:Pwd() - 2.403µs
[TRACE] 22:54:11.708 shell.go:GOOS() - 34ns
[TRACE] 22:54:11.708 shell.go:TemplateCache() - 41ns
[TRACE] 22:54:11.708 shell.go:TemplateCache() - 170ns
[TRACE] 22:54:11.708 shell.go:Shell() - 61ns
[DEBUG] 22:54:11.708 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.708 shell.go:Pwd() - 2.659µs
[TRACE] 22:54:11.708 shell.go:GOOS() - 60ns
[DEBUG] 22:54:11.708 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.708 shell.go:Getenv(SSH_CONNECTION) - 2.294µs
[DEBUG] 22:54:11.708 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.708 shell.go:Getenv(SSH_CLIENT) - 1.593µs
[TRACE] 22:54:11.708 shell.go:TemplateCache() - 40ns
[TRACE] 22:54:11.708 shell.go:TemplateCache() - 92ns
[TRACE] 22:54:11.708 shell.go:Shell() - 25ns
[DEBUG] 22:54:11.708 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.708 shell.go:Pwd() - 3.291µs
[TRACE] 22:54:11.708 shell.go:GOOS() - 66ns
[DEBUG] 22:54:11.708 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.708 shell.go:Pwd() - 2.078µs
[TRACE] 22:54:11.708 shell.go:Shell() - 33ns
[TRACE] 22:54:11.708 shell.go:Shell() - 26ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 22ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 21ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 28ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 38ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 19ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 23ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 54ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 21ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 21ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 25ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 21ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 21ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 74ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 49ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 23ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 71ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 25ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 30ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 22ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 26ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 25ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 24ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 19ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 36ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:GOOS() - 20ns
[TRACE] 22:54:11.708 shell.go:PathSeparator() - 20ns
[DEBUG] 22:54:11.708 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.708 shell.go:Pwd() - 1.878µs
[DEBUG] 22:54:11.708 shell.go:Getenv:336 → Debian
[TRACE] 22:54:11.708 shell.go:Getenv(WSL_DISTRO_NAME) - 5.826µs
[TRACE] 22:54:11.708 shell_unix.go:IsWsl() - 8.044µs
[DEBUG] 22:54:11.709 shell.go:RunCommand:515 → //wsl.localhost/Debian/home/philip
[TRACE] 22:54:11.709 shell.go:RunCommand(wslpath -m /home/philip) - 878.863µs
[TRACE] 22:54:11.709 shell.go:StackCount() - 121ns
[TRACE] 22:54:11.709 shell_unix.go:DirIsWritable(/home/philip) - 3.894µs
[TRACE] 22:54:11.709 shell.go:TemplateCache() - 112ns
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 214ns
[TRACE] 22:54:11.710 shell.go:Shell() - 74ns
[TRACE] 22:54:11.710 shell.go:Flags() - 78ns
[DEBUG] 22:54:11.710 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.710 shell.go:Pwd() - 2.608µs
[TRACE] 22:54:11.710 shell.go:GOOS() - 53ns
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 45ns
[TRACE] 22:54:11.710 shell.go:Shell() - 24ns
[DEBUG] 22:54:11.710 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.710 shell.go:Pwd() - 2.329µs
[TRACE] 22:54:11.710 shell.go:GOOS() - 21ns
[DEBUG] 22:54:11.710 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.710 shell.go:Getenv(SSH_CONNECTION) - 1.868µs
[DEBUG] 22:54:11.710 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.710 shell.go:Getenv(SSH_CLIENT) - 1.55µs
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 33ns
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 151ns
[TRACE] 22:54:11.710 shell.go:Shell() - 65ns
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 165ns
[DEBUG] 22:54:11.710 shell.go:Pwd:344 → /home/philip
[TRACE] 22:54:11.710 shell.go:Pwd() - 2.546µs
[TRACE] 22:54:11.710 shell.go:GOOS() - 61ns
[TRACE] 22:54:11.710 shell.go:ErrorCode() - 84ns
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 34ns
[TRACE] 22:54:11.710 shell.go:Shell() - 53ns
[TRACE] 22:54:11.710 shell.go:TemplateCache() - 154ns
[DEBUG] 22:54:11.710 shell.go:Getenv:336 → NO DATA
[TRACE] 22:54:11.710 shell.go:Getenv(XDG_CACHE_HOME) - 7.77µs
[TRACE] 22:54:11.711 shell_unix.go:CachePath() - 35.759µs
[TRACE] 22:54:11.711 shell.go:Flags() - 65ns
```

**Comment by JanDeDobbeleer** [comment]
@philippetev does this also happen in other terminals? I validated this on my machine, no impact whatsoever.

**Comment by philippetev** [comment]
I'm primary using the latest OpenSSH client 9.1.0.0p1 for Windows, running in Windows Terminal, but tested it also in PuttY/KittY and Bitvise SSH Client. Same result.

P.S. Tried it also with the stock config. Same result. so my config should be ok.

**Comment by JanDeDobbeleer** [comment]
@philippetev but always inside Midnight Commander or also plain bash?

**Comment by philippetev** [comment]
No, only the MC's subshell is affected. There is no issue outside MC (plain bash).

**Comment by JanDeDobbeleer** [comment]
@philippetev OK thanks, can you log a bug at MC in that case because this shouldn't affect anything at all. They need to fix this. In case there's anything I can do, let me know, so far this isn't a structural issue from oh-my-posh.

[This](https://github.com/JanDeDobbeleer/oh-my-posh/blob/481878262b1419851c7765f4ce47053efa9cf37d/src/shell/scripts/omp.bash#L12) is the function we call.

**Comment by zyv** [comment]
Hi there,

I don't think it's a bug in oh-my-posh or mc. It's rather an incompatibility, and we can work together to solve this, or we can agree, that we don't care.

The reason is, shells do not provide an embedding API, which we would need, and unless mc would include a complete virtual terminal emulator to spawn a shell inside, there is no way to control it other than making up some insane communication protocol based on precmd / PS1 hooks. This is of course extremely fragile and doesn't play well with other software doing the same or even touching this area for own purposes.

We do our best to not to break things for others, but we don't have the capacity or interest to provide compatibility with other tools proactively.

You can have a look at our crazy hooks here:

https://github.com/MidnightCommander/mc/blob/master/src/subshell/common.c#L1081

and shell detection code here:

https://github.com/MidnightCommander/mc/blob/master/src/subshell/common.c#L267

If you need us to change something that wouldn't break things otherwise, let us know. The problem is tracked here in our tracker:

https://midnight-commander.org/ticket/4436

Otherwise, I'm afraid the only solution is to write a launcher script for mc, that disables shell fanciness before it's called.

**Comment by JanDeDobbeleer** [comment]
@zyv is there a way to identify we're running inside MC? Because on our end we could also disable this function in that specific use-case.

**Comment by philippetev** [comment]
[Midnight Commander creates two runtime-only environment variables at startup: MC_TMPDIR and MC_SID](https://stackoverflow.com/questions/25110217/determine-if-bash-zsh-etc-is-running-under-midnight-commander).

I think it also raises the [$SHLVL system variable](https://riptutorial.com/bash/example/16882/-shlvl) value with 1 (from 1 in the main bash instance to 2), but that's not really reliable, you can achieve the same result by starting several bash instances inside each other and every time you do it, $SHLVL will raise its value with 1.
P.S. Yes, it does raise it.

**Comment by philippetev** [comment]
Just tested the new version on both my amd64 and arm64 devices. No more collisions. Thanks!

**Comment by zyv** [comment]
@JanDeDobbeleer even though it's not "officially" documented, `MC_SID` should do the trick. We use it as a mutex to detect running mc from within mc. Thank you!
