### ISSUE TITLE
Website 404

### ISSUE THREAD

**Issue by russleung44** [JanDeDobbeleer/oh-my-posh#3420]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

![image](https://user-images.githubusercontent.com/56534185/215308082-e34cb0b7-867d-42e9-90c3-048dfa74de55.png)

### Theme

null

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
null
```

**Comment by kinoosaki** [comment]
same here

**Comment by JanDeDobbeleer** [comment]
On it
