### ISSUE TITLE
Bash shell stop working on macOS Ventura 13.1 after brew update

### ISSUE THREAD

**Issue by tuffwes** [JanDeDobbeleer/oh-my-posh#3427]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've been using oh-my-posh with bash for a long time and I always upgrade without errors. For some reason today after running brew update & upgrade which also upgrades oh-my-posh, I am now getting an error after opening bash prompt.

-bash: eval: line 27: conditional binary operator expected
-bash: eval: line 27: syntax error near `MC_SID'
-bash: eval: line 27: `    if [[ -v MC_SID ]];then'

I am using an exported theme .my_theme.omp.json 

I am loading from bash as usual in .bash_profile: eval "$(oh-my-posh init bash --config ~/.my-theme.omp.json)"

I tried to go back to a regular theme like: eval "$(oh-my-posh init bash --config ~/jandedobbeleer.omp.json)" I still get the same error.  To recap, everything was working before brew upgrade just fine. I didn't change anything.

### Theme

hul10.omp.json but exported as a custom my_hul10.omp.json

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
-bash: eval: line 27: conditional binary operator expected
-bash: eval: line 27: syntax error near `MC_SID'
-bash: eval: line 27: `    if [[ -v MC_SID ]];then'
```

**Comment by lewis-yeung** [comment]
What is your Bash version?

**Comment by JanDeDobbeleer** [comment]
@tuffwes as @lewis-yeung stated, this is most likely due to an outdated bash version. Apple is known to ship older versions, and I'm on the same device using bash `5.2.12` without issues.
