### ISSUE TITLE
Extra space characters padding git segment

### ISSUE THREAD

**Issue by tom-mckinney** [JanDeDobbeleer/oh-my-posh#3466]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Since upgrading to the latest version (`14.1.2`), the default template for the git segment now has a leading and trailing empty space character when located in a git repository. When located outside of a git repository, there are no leading or trailing characters. For this reason, I cannot have uniform spacing between my segments since I would need a conditional character when not in a git template (and I'd prefer to use the default git template for ease-of-use).

I've attached a screenshot of what I'm seeing:
![image](https://user-images.githubusercontent.com/12684522/217120306-daaf0610-2882-4879-97a6-0c958bc6edbd.png)

### Theme

Fork of powerlevel10k_lean:
```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "version": 2,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "time",
          "style": "plain",
          "foreground": "#00C5C7",
          "template": " {{ .CurrentDate | date .Format }} ",
          "properties": {
            "time_format": "15:04:05"
          }
        }
      ],
      "vertical_offset": -1
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "path",
          "style": "plain",
          "foreground": "#77E4F7",
          "template": "{{ .Path }}",
          "properties": {
            "style": "full"
          }
        },
        {
          "type": "git",
          "style": "plain",
          "foreground": "#FFE700"
        },
        {
          "type": "text",
          "style": "plain",
          "foreground": "#43D426",
          "template": "\u276f "
        }
      ],
      "newline": true
    }
  ]
}
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@tom-mckinney this is by design in the default template, that also didn't really change as far as I can see. That said, changing the default template isn't something I'm doing as most people rely on the spaces, so adjusting the default template is the way to go.
