### ISSUE TITLE
v14.2.7 missing oh-my-posh.json file

### ISSUE THREAD

**Issue by netcore-jroger** [JanDeDobbeleer/oh-my-posh#3489]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

v14.2.7 missing oh-my-posh.json file.

### Theme

material.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
# scoop status
Scoop is up to date.
WARN  error: The remote server returned an error: (404) Not Found.

Name       Installed Version Latest Version Missing Dependencies Info
----       ----------------- -------------- -------------------- ----
oh-my-posh 14.2.5                                                Manifest removed
```

**Comment by JanDeDobbeleer** [comment]
Fixed, GitHub was experiencing some issues with runners during the build.
