### ISSUE TITLE
Invalid syntax in default fish-config. 

### ISSUE THREAD

**Issue by qTipTip** [JanDeDobbeleer/oh-my-posh#3501]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hello! Thanks a lot for the great tool!
Just wanted to report a small bug with the default fish config.

## Problem

The following syntax is not supported in fish. 

```text
>> oh-my-posh init fish > test.fish
>> source test.fish
test.fish (line 76): $(...) is not supported. In fish, please use '(string)'.
if test "$(string match -e '_render_transient' $(bind \r --user 2>/dev/null))" != ''
         ^
from sourcing file test.fish
source: Error while reading file 'test.fish'
``` 

## Solution

Write the tests on [line 71 - line 81](https://github.com/JanDeDobbeleer/oh-my-posh/blame/main/src/shell/scripts/omp.fish#L75-L81) using `( ... )`: 

```fish
"(string match -e '_render_transient' (bind \r --user 2>/dev/null))" != ''
```

### Theme

Default config generated by `oh-my-posh init fish`.

### What OS are you seeing the problem on?

Linux (WSL)

### Which shell are you using?

fish

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@qTipTip not a bug, you need to update fish.

**Comment by qTipTip** [comment]
Ah! I see, I was running `fish 3.3.1`. Sorry for the inconvenience! 

~~Is the version requirement mentioned somewhere?~~
> Oh My Posh requires fish v3.4.0 or higher.

**Comment by qTipTip** [comment]
I updated to `fish 3.6.0`: 

```
>> fish --version
fish, version 3.6.0
>> oh-my-posh --version
14.3.0
```

And I still get the same error, unfortunately:

```
>> oh-my-posh init fish > test.fish
>> source test.fish
test.fish (line 76): $(...) is not supported. In fish, please use '(string)'.
if test "$(string match -e '_render_transient' $(bind \r --user 2>/dev/null))" != ''
         ^
from sourcing file test.fish
source: Error while reading file 'test.fish'
```

Is there something I am missing here?

**Comment by JanDeDobbeleer** [comment]
@qTipTip yes, it could be your terminal is still configured to the old version.
