### ISSUE TITLE
The selected font "MesloLGL NF" could not be found.

### ISSUE THREAD

**Issue by h3zh1** [JanDeDobbeleer/oh-my-posh#3506]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi I have installed themes and fonts but he keeps reporting errors. maybe i need your help
![image](https://user-images.githubusercontent.com/68958533/219660026-077150c7-e082-4e98-93d5-4e450d3fbd06.png)

### Theme

oh-my-posh init pwsh --config 'C:/Users/Posh/jandedobbeleer.omp.json' | Invoke-Expression

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell, other (please specify)

### Log output

```Shell
找不到所选字体 "MesloLGL NF"。

改为选择 "Consolas"。

请安装缺少的字体或选择另一个。
```

**Comment by JanDeDobbeleer** [comment]
@h3zh1 that's a bug for Windows Terminal, not oh-my-posh.
