### ISSUE TITLE
Left prompt + Right prompt + cursor on same line [feat]

### ISSUE THREAD

**Issue by Kudostoy0u** [JanDeDobbeleer/oh-my-posh#351]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Can I get a left prompt and right prompt on the same line, and have the cursor on that line (type commands on that line?)
For an example of what I want, look at this custom theme I made from Oh-My-Posh v2: 
![image](https://user-images.githubusercontent.com/69732000/104827237-2605a000-5821-11eb-862e-e799ff9a5c1d.png)
There is a right prompt in this example on both the left and right sides, and they're on the same line. The cursor is also on that line, laying next to the left prompt. I want this functionality in Oh-My-Posh 3. Here is what I have achieved so far:
![image](https://user-images.githubusercontent.com/69732000/104827262-6f55ef80-5821-11eb-9f40-eed9d666749c.png)
In this theme, the right prompt is one line higher than the left prompt.
### Environment

- Oh my Posh version: 3.75.0-beta
- Theme: Fork of theme `slim`
- Operating System: Windows 10 20H2
- Shell: Powershell (Pwsh) 7
- Terminal: Windows Terminal

**Expected behavior:** [What you expected to happen]
A documented way to get prompts and the cursor on the same line.
**Actual behavior:** [What actually happened]
No documentation on how to do this

**Comment by tradiff** [comment]
Check out the `rprompt` block. It will be positioned on the same line as the cursor.

**Comment by Kudostoy0u** [comment]
Thank you ;) I will see if it works, which I bet it will. If I can't figure it out I'll reopen the issue.
