### ISSUE TITLE
Start transient prompt on a new line if the primary prompt started on one

### ISSUE THREAD

**Issue by dhrdlicka** [JanDeDobbeleer/oh-my-posh#3515]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

This used be possible to do somewhat consistently by adding `"newline": true` to the first block and starting the transient prompt with a `\n`.

However, since 622e2071f16315747233a45dd0a13a839401cbd8, the primary prompt might not necessarily start on a new line despite the setting and as far as I can tell, there is no way to have the transient prompt follow suit.

**Comment by JanDeDobbeleer** [comment]
@dhrdlicka wait, do you want the transient prompt to also NOT start on a newline for the first line? Because if you add a `\n` directly, that's always going to be hacky to control. Depending on the shell I'd argue you're better of configuring space after the command if that's what you're after.

**Comment by dhrdlicka** [comment]
> do you want the transient prompt to also NOT start on a newline for the first line?

Yes. Sorry if I wasn't being completely clear -- I want the transient prompt to start on a new line, but only if the primary prompt started on one.

> Depending on the shell I'd argue you're better of configuring space after the command if that's what you're after.

Thanks for the idea, I will see what I can do.

**Comment by JanDeDobbeleer** [comment]
@dhrdlicka this isn't really possible as it has A LOT of edge cases per shell so it's a rabbit hole I do not wish to enter.
