### ISSUE TITLE
Corrupted prompt after certain commands

### ISSUE THREAD

**Issue by peter-dolkens** [JanDeDobbeleer/oh-my-posh#352]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When running grep, the prompt immediately afterwards is corrupted - not sure if there's other commands with similar issues yet.

### Environment

- Oh my Posh version: v3.75.0
- Theme: custom - see below
- Operating System: Win10 19042.746
- Shell: Powershell 7.1.0
- Terminal: Console Host <native>, Windows Terminal 1.4.3243.0
- Grep: GNU grep 3.1 (bundled with git 2.29.2.windows.2)

### Steps to Reproduce

1. Run `echo hi | grep hi`
2. Hear audible bell, and observe corrupted prompt

**Expected behavior:** [What you expected to happen]

1. Uncorrupted prompt

**Actual behavior:** [What actually happened]

![image](https://user-images.githubusercontent.com/469666/104831129-cd182500-587d-11eb-9e70-0abca36d7f35.png)

### Notes

* I also tested without the special characters in my config file (as they only work in Windows Terminal) - same issue

### Theme

```json
{
    "final_space": false,
    "console_title": true,
    "console_title_style": "template",
    "console_title_template": "[{{.Env.Host}}] {{.Path}}",
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "horizontal_offset": 0,
            "vertical_offset": 0,
            "segments": [
            

                {
                    "type": "exit",
                    "style": "plain",
                    "foreground": "#16c50c",
                    
                    "properties": {
                        "display_exit_code": false,
                        "always_enabled": true,
                        "error_color": "#e74856",
                        "prefix": "\u279C"
                    }
                },
                
                {
                    "type": "path",
                    "style": "plain",
                    "foreground": "#61d6d6",
                    "properties": {
                        "style": "folder"
                    }
                },
                
                {
                  "type": "git",
                  "style": "plain",
                  "foreground": "#e74856",
                  
                  "properties": {
                  
                  "prefix": "<#3b78ff>git:(</>",
                  "postfix": "<#3b78ff>) </>",
                    "local_changes_icon": "\u2717",
                    "display_status": false,
                    "display_status_detail": false,
                    "display_stash_count": false,
                    "display_upstream_icon": false,
                    "working_color": "#e74856",
                    "branch_icon": ""
                  }
                }
            ]
        }
    ]
}
```

**Comment by JanDeDobbeleer** [comment]
It is known that the git tooling in Windows can cause the entire terminal rendering to act weird due to overriding certain variables. I'll check, but can't promise this is something that can be fixed within oh-my-posh.

**Comment by lnu** [comment]
I did the same test with starship and it works. Maybe we can check what they do on their side with the powershell prompt.

**Comment by JanDeDobbeleer** [comment]
> I did the same test with starship

@lnu could you also reproduce the issue for OMP?

**Comment by lnu** [comment]
And..... if I take the powershell bootstrap from starship and sets omp it works

![image](https://user-images.githubusercontent.com/1829553/104836147-08c9e380-58ac-11eb-8701-663bb252ccdf.png)

**Comment by JanDeDobbeleer** [comment]
With all due respect, this works with the out of the box version of OMP on my Windows machine as well, albeit PowerShell 5:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2492783/104836217-a45b5400-58ac-11eb-972a-c199e6e7a674.png">

**Comment by lnu** [comment]
powershell core 7.1.1 here in windows terminal

**Comment by lnu** [comment]
Only added `$omp` and `$config` and changed the starship calls. 

 ```
function global:prompt {
    $omp="D:\dev\temp\oh-my-posh3\src\oh-my-posh3.exe"
    $config="D:\tools\ohmyposh\jandedobbeleer_custom.omp.json"
    $origDollarQuestion = $global:?
    $origLastExitCode = $global:LASTEXITCODE

    $out = $null
    # @ makes sure the result is an array even if single or no values are returned
    $jobs = @(Get-Job | Where-Object { $_.State -eq 'Running' }).Count

    $env:PWD = $PWD
    $current_directory = (Convert-Path -LiteralPath $PWD)
    
    # Whe start from the premise that the command executed correctly, which covers also the fresh console.
    $lastExitCodeForPrompt = 0

    # Save old output encoding and set it to UTF-8
    $origOutputEncoding = [Console]::OutputEncoding
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    if ($lastCmd = Get-History -Count 1) {
        # In case we have a False on the Dollar hook, we know there's an error.
        if (-not $origDollarQuestion) {
            # We retrieve the InvocationInfo from the most recent error.
            $lastCmdletError = try { Get-Error |  Where-Object { $_ -ne $null } | Select-Object -expand InvocationInfo } catch { $null }
            # We check if the las command executed matches the line that caused the last error , in which case we know
            # it was an internal Powershell command, otherwise, there MUST be an error code.
            $lastExitCodeForPrompt = if ($null -ne $lastCmdletError -and $lastCmd.CommandLine -eq $lastCmdletError.Line) { 1 } else { $origLastExitCode }
        }

        $duration = [math]::Round(($lastCmd.EndExecutionTime - $lastCmd.StartExecutionTime).TotalMilliseconds)
        # & ensures the path is interpreted as something to execute
        $out = @(&starship prompt "--path=$current_directory" --status=$lastExitCodeForPrompt --jobs=$jobs --cmd-duration=$duration)
        $out = @(&$omp "--config=$config" --error=$lastExitCodeForPrompt "--pwd=$current_directory" "--pswd=$current_directory" --execution-time=$duration)
    } else {
        #$out = @(&starship prompt "--path=$current_directory" --status=$lastExitCodeForPrompt --jobs=$jobs)
        $out = @(&$omp "--config=$config" --error=$lastExitCodeForPrompt "--pwd=$current_directory" "--pswd=$current_directory")
    }
    # Restore old output encoding
    [Console]::OutputEncoding = $origOutputEncoding

    # Convert stdout (array of lines) to expected return type string
    # `n is an escaped newline
    $out -join "`n"

    # Propagate the original $LASTEXITCODE from before the prompt function was invoked.
    $global:LASTEXITCODE = $origLastExitCode

    # Propagate the original $? automatic variable value from before the prompt function was invoked.
    #
    # $? is a read-only or constant variable so we can't directly override it.
    # In order to propagate up its original boolean value we will take an action
    # which will produce the desired value.
    #
    # This has to be the very last thing that happens in the prompt function
    # since every PowerShell command sets the $? variable.
    if ($global:? -ne $origDollarQuestion) {
        if ($origDollarQuestion) {
             # Simple command which will execute successfully and set $? = True without any other side affects.
            1+1
        } else {
            # Write-Error will set $? to False.
            # ErrorAction Ignore will prevent the error from being added to the $Error collection.
            Write-Error '' -ErrorAction 'Ignore'
        }
    }
}
```

**Comment by JanDeDobbeleer** [comment]
@lnu @peter-dolkens so this is confirmed to only break in PSCore, for me that's `7.2`:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/2492783/104836623-70cdf900-58af-11eb-96df-c96b5440da02.png">

There's a reason I went with the current invocation technique as I did use a starship like invocation which ruined the rendering on certain machines. This solution made it work everywhere. There's something in the output of that command which ruins the rendering, and the next `ENTER` fixes that once again. I'm in favor of figuring out what exactly is the difference and adding a one-liner fix to the current invocation rather than opening that can of worms again (I was happy I was able to close it 5 months ago).

**Comment by JanDeDobbeleer** [comment]
@lnu @peter-dolkens fixed it. I believe, at the time, I was battling combination of issues which led me down this path. I was able to directly invoke OMP now without the entire `process` bootstrap leading to a correctly displayed prompt in all circumstances. I'm going to test a little bit more but you should see a fix ASAP.

**Comment by peter-dolkens** [comment]
Great work - @JanDeDobbeleer!

Was a low-priority bug for me, but thought I had an easy enough repro for it to be worthwhile logging =D

**Comment by JanDeDobbeleer** [comment]
I think I tested everything, also simplified the module in the meantime. Hope I didn't break anything for someone else 🤞🏻

**Comment by kidchenko-jq-tw** [comment]
After run any git command it also breaks for me :/

Terminal: Hyper

![image](https://user-images.githubusercontent.com/60685467/113413928-f4df4980-93e5-11eb-8576-2b28fd9d5b12.png)

**Comment by JanDeDobbeleer** [comment]
@kidchenko-tw That's likely going to be a Hyper issue, allow me to check. Is everything up to date?

**Comment by JanDeDobbeleer** [comment]
@kidchenko-tw I can't reproduce this

**Comment by kidchenko-jq-tw** [comment]
Yes, everything is up to date, I will double check, I remember I already had this problem in the past... But can't remember the fix,

**Comment by JanDeDobbeleer** [comment]
@kidchenko-tw can you copy the prompt here? If you pipe the out of oh-my-posh with your config I can have a look. Maybe there's a character the ruins the ANSI sequences?

**Comment by kidchenko-jq-tw** [comment]
Oh my Posh version: 3.131.0
Operating System: Windows Server 2016 DataCenter
Shell: Powershell 5.1.14393.3866
Terminal: Hyper 3.0.2

**Comment by kidchenko-jq-tw** [comment]
Sorry, but I didn't understand, how can I pipe the out? Is this what you want?

My prompt before: 
![image](https://user-images.githubusercontent.com/60685467/113824775-5f0f3a00-97aa-11eb-8f0d-7e6481b7c530.png)

Copy: ~   
 

My after: 
![image](https://user-images.githubusercontent.com/60685467/113825011-aa294d00-97aa-11eb-968e-245c9f721103.png)

?[38;2;255;255;255mD:\thoughtworks\test ?[0m?[38;2;194;194;6m   ≢ ?[0m?[38;2;181;181;13m  ?[0m?[K
?[K?[38;2;0;122;204m ?[0m?[K?[0m ?[K

**Comment by JanDeDobbeleer** [comment]
Aha git diff. That's going to be the culprit. Did you update git as well?

**Comment by kidchenko-jq-tw** [comment]
Just updated my git

git version 2.31.1.windows.1

Still same problem :/

**Comment by JanDeDobbeleer** [comment]
I'll try to reproduce this.

**Comment by JanDeDobbeleer** [comment]
@kidchenko-tw I just tried to reproduce this again, doesn't happen. Did you add a specific pager or something else in your git config that influences `git diff`?
