### ISSUE TITLE
Doesn't work like I wanted

### ISSUE THREAD

**Issue by bckelley** [JanDeDobbeleer/oh-my-posh#3521]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Ok I figured out the problem...

![image](https://user-images.githubusercontent.com/15696431/220433606-3aa2dc5d-ddce-4df8-b2a9-d79efac6c384.png)

in the photo  .venv can be placed to the right of HOST I would rather it be to the right of PATH. Is there a reason that it can't?

**Comment by bckelley** [comment]
ok, I think I found it:
![image](https://user-images.githubusercontent.com/15696431/220439126-cdc024e2-09c4-4077-a4b8-959bab852706.png)
but don't know how to finish the template so it says the .venv?

**Comment by JanDeDobbeleer** [comment]
@bckelley you don't need to use (and also can't) use cross segment properties from the same segment. To put the python segment to the right of that one, you only need to move the segment to that location like you did, and use the correct notation:

```json
{
    "foreground" : "#88c0dO",
    "style": "plain",
    "template": "<#5e81ac>[</>{{ if .Venv }}{{ .Venv }}{{ end }}<#5e81ac>]</>",
    "type": "python"
}
```

See [here](https://ohmyposh.dev/docs/segments/python) for more information.

**Comment by bckelley** [comment]
that's what I was looking for! Thanks!

Edit: wait that just prints ".Venv" as it was written in the json file

**Comment by JanDeDobbeleer** [comment]
@bckelley edited, forgot to add the brackets.
