### ISSUE TITLE
Can't execute the command on my powershell

### ISSUE THREAD

**Issue by iagosousadev** [JanDeDobbeleer/oh-my-posh#3529]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Before anything: i used omp now for quite some time, recently had to format my pc and now i'm installing everything again. Besides having done this multiple times i still do it with docs open to see if nothing changed.

I installed it with winget but it doesn't seem to recognize the command or install it properly, i'm sending screenshots of trying after install and one after restarting terminal that i did just now
![image](https://user-images.githubusercontent.com/2609728/221371968-d793634f-7b60-414a-a5b3-17d0f77e1f02.png)
![image](https://user-images.githubusercontent.com/2609728/221372114-b83f4086-f423-493e-91ee-bab8ca715d5e.png)

I just need help getting it going and then i can take care of the rest

### Theme

didn't change anything yet, stuck on installation/running

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
can't since the command isn't being recognized
```

**Comment by JanDeDobbeleer** [comment]
@iagosousadev we've heard that before and it's an issue with setting the PATH correctly at times. Running in the installer again mostly resolves the issue. There's no change in logic, just Windows that's acting up somehow.

**Comment by iagosousadev** [comment]
@JanDeDobbeleer thank you, yes i just restarted terminal like 5 times over and on the last one it worked, windows doing windows things, sorry for disturbing.
