### ISSUE TITLE
256-color mode not working on macos

### ISSUE THREAD

**Issue by dueckminor** [JanDeDobbeleer/oh-my-posh#3533]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

With commit 20462aa support for the 256 color mode has been added. Unfortunately in a way which doesn't work on terminals which don't support truecolor mode (like the Terminal on macOS)

I would expect that if I use a 256 color code to specify the color, something like `5;<color_code>` is used, but not `2;<red>;<green>;<blue>`

I'm wondering if it was intentionally to use `c256.RGBColor().String()` and not `c256.String()` to get the ANSI escape sequence?

### Theme

my own theme using 256 color codes.

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
not relevant for this kind of issue
```

**Comment by JanDeDobbeleer** [comment]
@dueckminor fair point, resolved and incoming.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/2492783/221416418-2fbd0859-db6d-4176-a963-4e29ed7ec3cf.png">

**Comment by dueckminor** [comment]
I also thought about how to fix this:
https://github.com/dueckminor/oh-my-posh/commit/50fe4badcb407173ce0c2156905c2c5a57de3451

Using `color.IsSupportTrueColor()` might help for themes which are using RGB colors. It would be also possible to translate RGB to the nearest 256 color code. But I feat that `color.IsSupportTrueColor()` is not really reliable and will report very often that only 256 colors are supported, even if the terminal has truecolor support.

@JanDeDobbeleer If you think that this makes sense, I could work on a PR.

**Comment by JanDeDobbeleer** [comment]
@dueckminor it's easier to leverage color palettes and check for those terminals in the template rather than baking in some half reliable functionality for the very few terminals out there which don't support true color.
