### ISSUE TITLE
Segment after newline is not displayed with Version 3.75.1

### ISSUE THREAD

**Issue by MJECloud** [JanDeDobbeleer/oh-my-posh#354]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

With version 3.75.1 the new line segment is not displayed in powershell.  

### Environment

- Oh my Posh version: 3.75.1
- Theme: my own theme but also tested with the powerlevel10k_classic
- Operating System: Windows
- Shell: PowerShell 7.1.1
- Terminal: WindowsTerminal

### Steps to Reproduce

1. Update oh-my-posh to Version 3.75.1
2. Set a theme with a "newline"

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/22131101/104855940-e79ade80-590f-11eb-811b-721646d8f20e.png)
![image](https://user-images.githubusercontent.com/22131101/104855999-3a749600-5910-11eb-9fce-e2ac42019e32.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/22131101/104855852-8246ed80-590f-11eb-8160-08639e330555.png)
![image](https://user-images.githubusercontent.com/22131101/104856017-5d06af00-5910-11eb-9200-ee91ac36fc18.png)

**Comment by JanDeDobbeleer** [comment]
I think I know what went wrong. Will fix tomorrow 🙏🏻

**Comment by JanDeDobbeleer** [comment]
I could reproduce it, this change resolves the issue.

**Comment by bgelens** [comment]
Can confirm the fix on my end! Thanks @JanDeDobbeleer

**Comment by MJECloud** [comment]
It works, thank you @JanDeDobbeleer!
