### ISSUE TITLE
Automatic conversion from int to string when comparing

### ISSUE THREAD

**Issue by Mertsch** [JanDeDobbeleer/oh-my-posh#3542]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I have the following segment
```
{
  "type": "exit",
  "style": "diamond",
  "foreground": "#ffffff",
  "background": "#e91e63",
  "leading_diamond": "\ue0b6",
  "trailing_diamond": "\uE0B4\n",
  "template": " Exit code {{.Code}}{{ if ne .Code .Meaning }} - {{.Meaning}}{{ end }} ",
  "properties": {
    "always_enabled": false
  }
}
```
resulting in `error calling eq: incompatible types for comparison`

Would be cool to be able to compare `string` and `int` on a string basis, as displaying the int will result in a string.
Alternatively: Have the first argument determine the type conversion for the second and just attempt to convert argument 2 into the first type.

Is there a workaround for this? I can't find anything in the documentation about comparisons in general.

**Comment by Mertsch** [comment]
And another alternative ... remove the fallback
> the textual meaning linked to exit code (if applicable, otherwise identical to .Code)

We can easily implement the fallback conversion of `.Code` when `.Meaning` is empty with a template.
Would remove the need for type comparison altogether.

**Comment by JanDeDobbeleer** [comment]
@Mertsch this isn't needed. You can convert the Code to string in this case:

```json
"template": " Exit code {{.Code}}{{ if ne (.Code | toString) .Meaning }} - {{.Meaning}}{{ end }} ",
```
