### ISSUE TITLE
Unable to change theme since v3.75.1

### ISSUE THREAD

**Issue by LarsBauer** [JanDeDobbeleer/oh-my-posh#355]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

After upgrading to the latest version of the PowerShell module I noticed that the theme was reset to the default one. I tried to change it but the command `Set-PoshPrompt -Theme sorin` does not work. So I started downgrading and with v3.75.0 it started working again.

This is my PowerShell profile:
```powershell
Import-Module oh-my-posh
Set-PoshPrompt -Theme sorin
```

### Environment

- Oh my Posh version: 3.75.1 / 3.75.2 (both broken)
- Theme: sorin
- Operating System: Windows 10 19042.746
- Shell: PowerShell Core 7.1.1
- Terminal: Windows Terminal Preview 1.5.3242.0

### Steps to Reproduce

1. Install v3.75.1
2. Import module and try to change change theme

**Expected behavior:** The prompt should change to the selected theme.

**Actual behavior:** The prompt does not change.

**Comment by JanDeDobbeleer** [comment]
It works for me without the -Theme switch, can you tab through it and validate the autocomplete and setting of the prompt?

**Comment by LarsBauer** [comment]
Thanks for the quick reply. I upgraded to the latest version and tried without the `-Theme` switch. Unfortunately this does not work either.

![image](https://user-images.githubusercontent.com/3920045/104935481-993b1d80-59ab-11eb-9874-a4e770d6da5a.png)

**Edit:** Autocomplete for the themes works fine.

**Comment by JanDeDobbeleer** [comment]
@LarsBauer allow me to validate this in the evening. I did check that so maybe there's something else that influences this negatively. It sets a config, but as the text states, it can't open that location somehow.

**Comment by JanDeDobbeleer** [comment]
@LarsBauer confirmed to work on my machine, so some follow-up questions. Do you have a space in a folder somewhere? Or a mounted drive/Onedrive integration?

**Comment by LarsBauer** [comment]
Yes, OneDrive integration is enabled so I guess there could be some spaces in the path. Can't check for sure because I am not on my work computer right now.

**Comment by JanDeDobbeleer** [comment]
That's probably it though, will try to reproduce 😅

**Comment by JanDeDobbeleer** [comment]
@LarsBauer found the issue. Fix incoming.

**Comment by LarsBauer** [comment]
Just upgraded and the issue is gone. 👍 
Thank you a lot for the quick fix and your dedication to this awesome tool.

**Comment by danvim** [comment]
> 
> 
> Thanks for the quick reply. I upgraded to the latest version and tried without the `-Theme` switch. Unfortunately this does not work either.
> 
> ![image](https://user-images.githubusercontent.com/3920045/104935481-993b1d80-59ab-11eb-9874-a4e770d6da5a.png)
> 
> **Edit:** Autocomplete for the themes works fine.

Do you know what was causing the problem? I also find it weird it says UNABLE TO OPEN CONFIG. I'm getting this with version 3.129.0

**Comment by JanDeDobbeleer** [comment]
Can you show me your invocation?

**Comment by danvim** [comment]
> 
> 
> Can you show me your invocation?

Same as OP,

```powershell
Import-Module oh-my-posh
Set-PoshPrompt -Theme agnoster
# or
Set-PoshPrompt agnoster
```

But I must say, the computer I'm using is pretty locked down for security reasons. I've tested the same in my own personal PC and it works fine with the same version. One of the reasons I wanted oh-my-posh was the git display. I'm currently settling with using posh-git directly.

**Comment by JanDeDobbeleer** [comment]
@danvim I have no idea why it can't open the file, in theory you should be able to get the [agnoster](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/agnoster.omp.json) config, store it somewhere your user has access to and point to that file when setting the prompt.

```pwsh
Import-Module oh-my-posh
Set-PoshPrompt -Theme ~/agnoster.omp.json
```

**Comment by danvim** [comment]
> @danvim I have no idea why it can't open the file, in theory you should be able to get the [agnoster](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/agnoster.omp.json) config, store it somewhere your user has access to and point to that file when setting the prompt.
> 
> ```pwsh
> Import-Module oh-my-posh
> Set-PoshPrompt -Theme ~/agnoster.omp.json
> ```

I am able to copy the file to C: and set the theme now. Thanks.

On the other note, `~/Documents`, where Powershell's modules get installed on this PC is on a network drive, with the path containing a `$`. I'm not sure if that's a problem.

**Comment by JanDeDobbeleer** [comment]
@danvim  That's a problem in Powershell yes

**Comment by rolflobker** [comment]
Installed in pwsh 7 (core) under Debian
Set-PoshTheme works fine

Set-PoshTheme ys
Export-PoshTheme -FilePath ~/.oh-my-posh.omp.json
Set-PoshPrompt -Theme ~/.oh-my-posh.omp.json

UNABLE TO OPEN CONFIG

Set-PoshTheme jandedobbeleer
Export-PoshTheme -FilePath ~/.oh-my-posh.omp.json
Set-PoshPrompt -Theme ~/.oh-my-posh.omp.json

Works just fine

Also works with theme Slim
Have not tested others

So at least with export of theme 'ys'  we get a ' UNABLE TO OPEN CONFIG'

**Comment by JanDeDobbeleer** [comment]
Allow me to check that.

**Comment by rolflobker** [comment]
> Allow me to check that.

I will allow that.

**Comment by JanDeDobbeleer** [comment]
@rolflobker someone added a `\b` in there which is a backspace character and fails to get parsed properly after export. I removed them we'll see what breaks when an issue pops up ;-)
