### ISSUE TITLE
Enter-PSSession

### ISSUE THREAD

**Issue by mkanet** [JanDeDobbeleer/oh-my-posh#3550]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I just noticed when I use `Enter-PSSession` to access our Windows servers' remote shell, my cool looking Oh My Posh prompt completely disappears.  It doesn't come back until I exit Enter-PSSession.

We use Enter-PSSession almost daily, so hopefully there's something simple I'm missing to get this working. 

![PSRemote](https://user-images.githubusercontent.com/811008/222610534-8bba68a0-1c77-43de-9e78-87e1d67d047d.png)

Thank you so much for all your hard work maintaining/updating Oh My Posh!  Please let me know if you need any additional information.

### Theme

This occurs with all themes I've tried.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A??
```

**Comment by JanDeDobbeleer** [comment]
@mkanet this isn't a bug. The computer you're remoting into needs to have oh-my-posh configured for that user.

**Comment by mkanet** [comment]
@JanDeDobbeleer Thank you for confirming its not a bug.  Could you please point me to an example documentation on how to configure oh-my-posh for that user in order for this to work?  I looked and looked, but couldnt find what specifically I need to configure.  

We have hundreds of servers that we remote into... so hopefully, there's a way to do this without make significant configuration changes to every server we have.  In any case, I'd like to know what specific needs to done for this to work on an example remote machine.  Thank you for you time.

Thank you so much for your help!

**Comment by JanDeDobbeleer** [comment]
@mkanet you need to configure the remote computer to have oh-my-posh installed and the same (or different) configuration in the user's `$PROFILE` you're entering.

**Comment by mkanet** [comment]
> @mkanet you need to configure the remote computer to have oh-my-posh installed and the same (or different) configuration in the user's `$PROFILE` you're entering.

Oh I see   It's not feasible for us to install an EXE and configure Oh-my-posh on hundreds of devices; especially since Enter-PSession works already.

**Comment by JanDeDobbeleer** [comment]
@mkanet there's no way to run on a remote machine unfortunately

**Comment by mkanet** [comment]
@JanDeDobbeleer 

Actually found an easy way to load `oh-my-posh.exe` and `xxxxxx.omp.json` files directly from my local PC (or from another central server).  **It is VERY close to working perfectly!!**  The two lines below will load ohmyposh and respective theme just like it is local.
```
New-PSDrive -Name MyLaptop -PSProvider FileSystem -Root "\\MYLAPTOPIP\C$\MYUSERNAME\AppData\Local\Programs\oh-my-posh\" -Credential $Credential
& ([ScriptBlock]::Create((MyLaptop:\oh-my-posh.exe init pwsh --config "MyLaptop:\themes\mkanet.omp.json" --print) -join "`n"))
```
Below, is what it looks like after loading Oh-My-posh theme.  Everything works! However, Ohmyposh is not hiding `[RemotePC]: `  which is provided by PowerShell.
![OhMyPosh](https://user-images.githubusercontent.com/811008/222816725-076646a7-1cc7-408b-b4bd-26f4e40909f5.png)

**With just a small modification to OhMyPosh, this will work great!  Ohmyposh just need to ignore/hide `[RemotePC]: `.** produced by powershell remoting.

The rest can be done easily in the OhMyPosh theme following the documentation.  Considering PowerShell remoting is a core feature that many admins use daily, I'm hoping I could convince you to make this small fix.  It should not hurt anything.

Thank you again for your consideration!

**Comment by JanDeDobbeleer** [comment]
@mkanet that part is added by PSReadLine, which also powers the prompt. I don't know if that one can be disabled, if it can that's just a setting away.

**Comment by mkanet** [comment]
Are you certain that's true?  Even before PSReadline was introduced, PowerShell remoting would still insert `[RemotePCHostname]: ` in the command prompt when using `Enter-PSSession`.  It has been this way as long as I can remember in older versions of Windows.

**Comment by JanDeDobbeleer** [comment]
@mkanet whoever does it, it's not us and they hijack the prompt. So we can't solve that.

**Comment by mkanet** [comment]
Oh okay.  Thank you for trying.  I'll keep looking for a workaround/solution.

**Comment by mkanet** [comment]
@JanDeDobbeleer 

**UPDATE:**   I was able to successfully remove `[RemoteServer]: ` from the prompt in a remote session using the below prompt function (see code at the bottom of this post).  It works great:

**Before:**
![Before](https://user-images.githubusercontent.com/811008/222868474-43d283d5-c158-41a9-a84b-f46ee685f0fe.png)

**After:**
![After](https://user-images.githubusercontent.com/811008/222868477-7a448e4e-c900-4d9a-9de5-714e1dcdc290.png)

However, when I load Oh My Posh in the remote session (screenshot below), it still displays the `[RemoteServer]: `. Please don't get mad at me; but could you **please** tell me what\where specifically Oh My Posh reads the `[RemoteServer]: ` prompt from?  You mentioned it's from **PSReadLine**.... but, when I run the command: `Get-PSReadLineOption | select PromptText` while in the remote session, it doesn't have any value from `PromptText` property; which is correct.  ... so not sure where OhMyPosh is getting this prompt from (see below):
![OhMyPosh3](https://user-images.githubusercontent.com/811008/222868945-ff2579a7-b090-4630-b22e-573726536363.png)

If you can **please** tell me where\what specifically OhMyPosh uses to grab the prompt text, I can hopefully do something similar to what I did in the prompt function below as a workaround.  I am sure it is possible; and, others will be able to benefit from this too hopefully.  I just need a little help, if possible.

```powershell
function Enter-PSRemote([string]$DeviceName)
{
    $DeviceName = $DeviceName.ToUpper()
    if ((!(Get-PSSession | ?{$_.ComputerName -eq $DeviceName}))) {$Global:session = New-PSSession $DeviceName -Credential $PASSCredential}
    Enter-PSSession -Session $Global:session

    Invoke-Command -Session $Global:session -ScriptBlock {
        param ([string]$DeviceName, $PASSCredential)


        function prompt
        {
            $cn = $Devicename
            $defaultPrompt = "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
            $backspaces = "`b" * ($cn.Length + 4)
            $remainingChars = [Math]::Max(($cn.Length + 4) - $defaultPrompt.Length, 0)
            $tail = (" " * $remainingChars) + ("`b" * $remainingChars)

            "${backspaces}${defaultPrompt}${tail}"
        }

        New-PSDrive -Name Src_Drive -PSProvider FileSystem -Root "\\Mylaptop\shared\" -Credential $PASSCredential | Out-Null
        import-module "Src_Drive:\OhMyPoshDir\PSReadline" -force
        
        & ([ScriptBlock]::Create((Src_Drive:\OhMyPoshDir\oh-my-posh.exe init pwsh --config .\mkanet.omp.json --print) -join "`n"))
        
    } -ArgumentList $DeviceName, $PASSCredential
}
```

**Comment by JanDeDobbeleer** [comment]
@mkanet Oh My Posh doesn't do anything here. It's not printing that part. Something else is hijacking the prompt function in PowerShell and prepends this. So it's a question for the PowerShell team. I couldn't find out who/what does that either.

**Comment by mkanet** [comment]
@JanDeDobbeleer no worries.  At this point, I think I'll have to give up.  I really like Oh my posh; but, I use PowerShell remoting too frequently to keep it.

**Comment by JanDeDobbeleer** [comment]
I would really ask the question in the PowerShell repo as they should know. 

EDIT: see [here](https://github.com/PowerShell/PowerShell/discussions/19278).

**Comment by mkanet** [comment]
Thank you.  I was just going to ask you where to ask the question.  I appreciate it.  Maybe they will offer a way.

**Comment by mkanet** [comment]
@JanDeDobbeleer I think I finally figured out a way to do this.  I'm almost there!  It's the same technique I used earlier.  I am printing backspace Unicode characters and writing over the remoteserver text with space characters.

The below template example will successfully erase is:  `[RemoteServer]: ` 16 characters in length:

**[WORKING]**
```
        {
          "template": "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                ",
          "type": "text"
        }
```

Hence, I created the environment variable below (automatically generated by PowerShell to calculate the hostname length needed by the below respective OMP template):
```
$Env:ErasePSRemoteSessionHostNameString = "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                "
```
...and, respective template:  **[NOT WORKING]**
```
        {
          "template": "{{.Env.ErasePSRemoteSessionHostNameString}}",
          "type": "text"
        }
```

Unfortunately, instead of the above template _(with the environment variable)_ erasing the characters exactly like my **WORKING** template, it just literally prints the Unicode character text in my prompt instead of treating them like backspace characters:
```
[RemoteServer]: \u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                
```

It looks like OMP's template doesn't treat the environmental variable text the same as just manually typing the Unicode characters inside the template.  

What is the correct way to use my environment variable to do the same thing as my **[WORKING]** template?  If I'm doing everything correctly, maybe this could be done with small enhancement to OMP to allow this to work?

**Comment by mkanet** [comment]
**[WORKING]**
```
        {
          "template": "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                ",
          "type": "text",
          "style": "plain"
        }
```

**[NOT WORKING]**
```
        {
          // "template": "{{.Env.ErasePSRemoteSessionHostNameString}}",
          "type": "text",
          "style": "plain"
        } 
```

```
$Env:ErasePSRemoteSessionHostNameString = "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                "
```

**Comment by mkanet** [comment]
@JanDeDobbeleer to summarize,  I just need a way for OMP templates to handle environmental variable values (containing Unicode characters) no differently than just typing the unicode characters directly in the the template (in between double-quotes).  Maybe, OMP can do this with a very small enhancement to allow this flexibility?

**[WORKING]**
```
        {
          "template": "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                ",
          "type": "text",
          "style": "plain"
        }
```

**[NOT WORKING]**
```
        {
          "template": "{{.Env.ErasePSRemoteSessionHostNameString}}",
          "type": "text",
          "style": "plain"
        } 
```

```
$Env:ErasePSRemoteSessionHostNameString = "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                "
```

**Comment by JanDeDobbeleer** [comment]
@mkanet oh-my-posh doesn't do anything with the env var, it simply takes the string and adds it into resulting template. So if that doesn't work, it's either a PowerShell or env var thing.

What you could also look at is moving the cursor to the beginning of the line using ANSI escape sequences. That way there's no calculation needed at all. If that works I could add that by default.

```
{
    "template": "\x1b[1000D",
    "type": "text",
    "style": "plain"
}
```

**Comment by mkanet** [comment]
@JanDeDobbeleer Unfortunately, `"\x1b[1000D"` ***(move cursor 1000 characters back in ANSI)*** is not valid for OMP themes.  However, you gave me an idea.  I don't need to calculate hostname length.  The below code will just move the cursor back 42 characters; which is more than enough for any normal hostname.  It works beautifully,reliably, and super-fast.  Once I'm done with my custom theme, I can share it.

Thank you for all your help!
```
        {
          "template": "\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008\u0008                                          ",
          "type": "text",
          "style": "plain"
        },
```
