### ISSUE TITLE
[feature] Allow different icon/text depending on exit code

### ISSUE THREAD

**Issue by Kudostoy0u** [JanDeDobbeleer/oh-my-posh#357]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]
Here is a block for adding an exit code to my custom prompt
![image](https://user-images.githubusercontent.com/69732000/104957996-dcd65d00-5994-11eb-8525-f26013cb381f.png)
The problem is that if an error occurred you can only change the foreground/background color of the segment, not the icon. What I want to happen is if no error occured it shows a green check mark, and otherwise it shows a red "x"
I can only do this so far:
![image](https://user-images.githubusercontent.com/69732000/104958243-46ef0200-5995-11eb-98cf-b4958ec549b3.png)
This would also be useful for the `battery` segment, to display different battery icons depending on the battery level. 
### Environment

- Oh my Posh version: 3.75.0-beta
- Theme: Custom theme based of of "slim"
- Operating System: Windows 10 20H2
- Shell: Powershell Core 7.0
- Terminal: Windows Terminal

**Expected behavior:** [What you expected to happen]
Option to customize output text based on exit code
**Actual behavior:** [What actually happened]
No option to do so (at least, I can't find any documentation to do so)

**Comment by JanDeDobbeleer** [comment]
Makes sense to distinct between success and failure. As for battery, maybe. Although that introduces a lot of complexity for what might be a limited use case.
