### ISSUE TITLE
Expose .nvmrc contents (or node version from other config files) to the `node` segment

### ISSUE THREAD

**Issue by Daeraxa** [JanDeDobbeleer/oh-my-posh#3576]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

See: https://github.com/JanDeDobbeleer/oh-my-posh/discussions/3575

If I have an .nvmrc which has `16` then I want my prompt to display this if I'm entering the folder as well as the active version. I know that I can use `.mismatch` to display if there is a difference in the content of what was read from .nvmrc and my active node version but it doesn't display what it actually is.

```json
        {
          "type": "node",
          "foreground": "green",
          "properties": {
            "fetch_package_manager": true
          },
          "template": "{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Major }}"
        },
```

This is the block I currently have which works but it displays the active node version and not the .npmrc version.

For example what I might want in the template (if it existed) would be:

```
{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} \uE718 {{ .nvmrc }}
```

Reasoning for this is that I may not be using `nvm` to automatically change my node version or might be using other node version tools such as volta or asdf which don't necessarily use the .nvmrc in the same way that nvm does meaning I need to run the commands manually.

You could then also use `.mismatch` as logic to highlight the new element differently depending on whether it is true or false?

**Comment by JanDeDobbeleer** [comment]
You can now make use of `.Expected` to see what's inside `.nvmrc`

**Comment by Daeraxa** [comment]
Awesome, thanks so much for adding that (and so fast!!!)
