### ISSUE TITLE
Update segment in background w/o user interaction

### ISSUE THREAD

**Issue by zanseb** [JanDeDobbeleer/oh-my-posh#3587]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would it be technically possible to redraw a certain segment in the background without any user interaction?

This could be practical for certain segments that retrieve data from external services. For example, the Spotify segment could be redrawn when the song changes without the shell being actively used.

Happy to hear what you think about it.

**Comment by JanDeDobbeleer** [comment]
@zanseb not from oh-my-posh, but you can create a custom shell function that redraws the prompt based on your custom logic.
