### ISSUE TITLE
Name of conda environment not showing in the Python segment

### ISSUE THREAD

**Issue by sobayed** [JanDeDobbeleer/oh-my-posh#360]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

In version 3.77.0, the name of the conda environment is not showing anymore in the Python segment (only the Python logo and version):

![oh-my-posh_3 77 0_missing_conda_name](https://user-images.githubusercontent.com/23031125/105148090-4627ae80-5b02-11eb-9b54-6a076cf8410d.jpg)

In version 3.68.4, this was still working properly:

![oh-my-posh_3 68 4_conda_name_showing](https://user-images.githubusercontent.com/23031125/105148162-58095180-5b02-11eb-9f1a-9ef4e4d3a57d.jpg)

### Environment

- Oh my Posh version: 3.77.0
- Theme: Paradox
- Operating System: Windows 10 (Version 10.0.18363 Build 18363)
- Shell: Powershell 7.1.0
- Terminal: Windows Terminal 1.4.3243.0

### Steps to Reproduce

1. Open Windows Terminal with Powershell and an active conda environment
2. Name of the conda environment is not showing in the Python segment
3. Changing conda environments does not fix the issue

**Expected behavior:** Name of the conda environment is showing in the Python segment

**Actual behavior:** Name of the conda environment missing in the Python segment

**Comment by JanDeDobbeleer** [comment]
@sobayed you're right. I removed `CONDA_DEFAULT_ENV`. Can you tell me you want to see `base` or only when the env name != `base`?

**Comment by sobayed** [comment]
My personal preference would be to always show the environment name (including `base`), as it did with the previous versions. But maybe having a config parameter for that in the Python section would also be an option.

**Comment by JanDeDobbeleer** [comment]
@sobayed I'll remove that logic for now, if it ever pops up as a request that can always be implemented. You'll see this drop after my lunch.
