### ISSUE TITLE
Incorrect encoding in upgrade message

### ISSUE THREAD

**Issue by MartinSGill** [JanDeDobbeleer/oh-my-posh#3606]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Saw an upgrade message:

```
A new release of Oh My Posh is available: v14.12.0 ÔåÆ v14.14.3
```

### Theme

n/a

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
n/a
```

**Comment by JanDeDobbeleer** [comment]
@MartinSGill that's a PowerShell encoding issue. It dislikes UTF8 by default. I'll wrap that in a temporary UTF8 block.
