### ISSUE TITLE
Support max_width for Path segment and substitute unique letters for parent directories only when necessary

### ISSUE THREAD

**Issue by daviewales** [JanDeDobbeleer/oh-my-posh#3607]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Similar to #1663, I'm trying to tweak the Oh-My-Posh Path segment to match Powerlevel10k.
I'm looking for something similar to a cross between `style="unique"` and `style="agnoster_short"`, but not quite.

Powerlevel10k looks at the total number of characters in the path (max_width) rather than the depth of the path (max_depth). If the max_width is exceeded, it replaces top level directories with unique letters until the max_width is satisfied.

Here is a screenshot of Powerlevel10k with a very long path:

![image](https://user-images.githubusercontent.com/2499066/226512417-acc2049e-2826-4336-9b07-48f65161fe3b.png)

This is what we get if we go up a few directories:

![image](https://user-images.githubusercontent.com/2499066/226512540-20574cf7-96d2-4d71-865e-6929657ea4b1.png)

And a few more:

![image](https://user-images.githubusercontent.com/2499066/226512592-93904452-1008-45d8-af54-85e0683be61c.png)

The closest I can get with the Oh-My-Posh Path segment is either `style="unique"`, which substitutes unique letters for parent directories, but does so indiscriminately, or `style="agnoster_short"`, which keeps the `max_depth` preceding directories, but hides all additional directories behind `folder_icon`.

**Comment by daviewales** [comment]
Amazing! Thank you!

**Comment by Narrat** [comment]
Nice addition. :) I also missed that!
But I notice one odd behaviour? If I'm switching paths in `$HOME` this works as expected. Path is fully displayed until `max_width` is hit, whereas the path gets shortened.
But if I hop around in `/` it plays somewhat different.
I have set `max_width` to 50 and do the following:
```shell
$  cd /var/cache/pacman 
v/cache/pacman
$ 
```
But as the limit wasn't reached I expected
```
/var/cache/pacman
$ 
```
even if it's get shortened, the `/` shouldn't be omitted? Or is there some misunderstanding from my side?

**Comment by JanDeDobbeleer** [comment]
@Narrat I'll check!

**Comment by Narrat** [comment]
Thank you for the update. With `14.19.4` and onwards it works now like expected
