### ISSUE TITLE
Allow references to prompt segments in console_title_template

### ISSUE THREAD

**Issue by mbs-c** [JanDeDobbeleer/oh-my-posh#3616]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'd love to see the current git branch in my console title. The [documentation](https://ohmyposh.dev/docs/configuration/title#console-title-template) refers to the more generic [template documentation](https://ohmyposh.dev/docs/configuration/templates), which mentions "Cross segment template properties". I tried the following:

```json
"console_title_template": "{{ .Folder }}{{ if .Segments.Contains \"Git\" }} [{{ .Segments.Git.Output }}]{{ end }}"
```

Unfortunately, referring to segments in the console_title_template does not seem to be supported so far. (I tried adding an alias to my git segment as well - that did not help.) Would it be possible to add this functionality?

**Comment by JanDeDobbeleer** [comment]
@mbs-c how did you come to `.Segments.Git.Output`? Because `Output` isn't a [property](https://ohmyposh.dev/docs/segments/git#properties-1) on the Git Segment. It does have `.Ref` which is what you're looking for. So theoretically, this should work:

```json
"console_title_template": "{{ .Folder }}{{ if .Segments.Contains \"Git\" }} [{{ .Segments.Git.Ref }}]{{ end }}"
```

EDIT: confirmed to work

**Comment by mbs-c** [comment]
Ah, indeed! I mistook the `.Output` property in the documentation example as a generic property that always contains the entire segment contents. Your answer made me realize that such a generic property does not exist and that `.Output` is specific to the `command` segment, which was used in the example.

(I think a generic "full segment contents" property might be useful, though. Does that exist?)

**Comment by JanDeDobbeleer** [comment]
@mbs-c based on the result of the template? No, because they're rendered sequentially. We could add it but only for the title template for example. That one comes last.
