### ISSUE TITLE
Nitpick: Prompt not replaced with transient prompt after Ctrl+C

### ISSUE THREAD

**Issue by mbs-c** [JanDeDobbeleer/oh-my-posh#3617]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

At least in pwsh, the regular prompt is not replaced with the transient prompt after Ctrl+C.

Expected behavior: Since Ctrl+C causes a new prompt to be drawn, the old prompt should be replaced with the transient prompt.

### Theme

Reproducible with any theme that uses a transient prompt, e.g. "chips".

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Version: 14.15.0

(Rest omitted - seems irrelevant for the report.)
```

**Comment by JanDeDobbeleer** [comment]
@mbs-c this is by design. The hook for transient is on enter, not "command accepted/aborted". I'll have a look but I don't know if we can cleanly hook into this.

EDIT: can be adjusted, it seems this is `Ctrl+c                CopyOrCancelLine`
