### ISSUE TITLE
Disabling update checks

### ISSUE THREAD

**Issue by nidrissi** [JanDeDobbeleer/oh-my-posh#3626]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

First, thanks for the great work! Very useful.

Is there a way to disable the banner about updates? There are tiny updates almost every day. It gets a bit annoying - I'm not updating all my software every day.

**Comment by JanDeDobbeleer** [comment]
@nidrissi what do you mean every day? It should only show once a week. That said, you disable it using `oh-my-posh disable notice`.
