### ISSUE TITLE
ERROR Shovel flavour of scoop

### ISSUE THREAD

**Issue by quangkieu** [JanDeDobbeleer/oh-my-posh#364]
### Prerequisites

- [x] I looked for duplicate issues before submitting this one

### Description

Error install through scoop

### Environment

- Oh my Posh version: 3.78.1
- Theme: N/A
- Operating System:
- Edition	Windows 10 Education
  Version	20H2
  Installed on	‎12/‎14/‎2019
  OS build	19042.746
  Experience	Windows Feature Experience Pack 120.2212.1070.0
- Shell: PowerShell 7.2.0-preview.2; PowerShell 7.1.1
- Terminal: Windows Terminal Preview 1.5.3242.0

### Steps to Reproduce

1. `scoop install oh-my-posh3`

**Expected behavior:** [What you expected to happen]
Finished installation without error

**Actual behavior:** [What actually happened]
```
Installing 'oh-my-posh3' (3.78.1) [64bit]
Loading posh-windows-wsl-amd64.7z from cache.
Loading Ash258.json from cache.
Checking hash of posh-windows-wsl-amd64.7z ... ok.
Checking hash of Ash258.json ... ok.
Extracting posh-windows-wsl-amd64.7z ... done.
Linking ~\scoop\apps\oh-my-posh3\current => ~\scoop\apps\oh-my-posh3\3.78.1
Creating shim for 'oh-my-posh'.
Persisting themes
Running post-install script...
ERROR Shovel flavour of scoop is required
```

**Comment by JanDeDobbeleer** [comment]
@quangkieu works when I run the command. Now, it can be your version of scoop is outdated, can you update and try again ` scoop update`?

**Comment by quangkieu** [comment]
Yeah even after the `scoop update` I still get that Shovel error

**Comment by JanDeDobbeleer** [comment]
@quangkieu what is Ash258?

EDIT: figured it out. That command installs from the main bucket which is something I did not add. The supported command is this, installing straight from this repository (and as stated in the docs):

```

scoop install https://github.com/JanDeDobbeleer/oh-my-posh3/releases/latest/download/oh-my-posh.json
```

**Comment by JanDeDobbeleer** [comment]
As I can confirm the issue (and the fix), I'm closing this issue.
