### ISSUE TITLE
Last exit code is not cleared when issuing an empty command

### ISSUE THREAD

**Issue by Mertsch** [JanDeDobbeleer/oh-my-posh#3655]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am not sure if this is a Terminal/Powershell issue, but when you enter a non-command, the last exit code remains.

![2023-03-30 17-00-43 WindowsTerminal](https://user-images.githubusercontent.com/9402861/228879069-3c34c0d2-8e79-48e2-a539-f7b98aa676ec.png)

I would expect the exit code to disappear on the next non-command, as it is no longer causing and error.

### Theme

Custom with
`"template": " Exit code {{ .Code }} ({{ .Code | printf \"%#x\" }}){{ if ne (.Code | toString) .Meaning }} ({{ .Meaning }}){{ end }} ",`

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
[TRACE] 17:02:41.830 shell.go:Host() - 0s
[TRACE] 17:02:41.830 shell.go:GOOS() - 0s
[TRACE] 17:02:41.830 shell.go:TemplateCache() - 0s
[TRACE] 17:02:41.830 shell.go:TemplateCache() - 0s
[TRACE] 17:02:41.830 shell.go:Shell() - 0s
[TRACE] 17:02:41.830 shell.go:Pwd() - 0s
[DEBUG] 17:02:41.830 shell_windows.go:56 → C:\Users\xxx
[TRACE] 17:02:41.830 shell.go:GOOS() - 0s
[TRACE] 17:02:41.830 shell.go:GOOS() - 0s
[DEBUG] 17:02:41.839 shell.go:CommandPath:599 → C:\Program Files\Git\cmd\git.exe
[TRACE] 17:02:41.839 shell.go:CommandPath(git.exe) - 9.8639ms
[TRACE] 17:02:41.839 shell.go:HasCommand(git.exe) - 9.8639ms
[TRACE] 17:02:41.839 shell.go:Pwd() - 0s
[ERROR] 17:02:41.839 shell.go:HasParentFilePath:732 → CreateFile .git: The system cannot find the file specified.
[TRACE] 17:02:41.839 shell.go:HasParentFilePath(.git) - 0s
[DEBUG] 17:02:41.839 shell.go:Getenv:392 → C:\Users\xxx\AppData\Local
[TRACE] 17:02:41.839 shell.go:Getenv(LOCALAPPDATA) - 0s
[TRACE] 17:02:41.839 shell_windows.go:CachePath() - 0s
[TRACE] 17:02:41.839 shell.go:Flags() - 0s
```

**Comment by lewis-yeung** [comment]
This is by design.

**Comment by JanDeDobbeleer** [comment]
@Mertsch that's the shell doing that for you. In this case PowerShell.
