### ISSUE TITLE
A parameter cannot be found that matches parameter name 'AllowPrerelease'.

### ISSUE THREAD

**Issue by sgstq** [JanDeDobbeleer/oh-my-posh#367]
### Prerequisites

- [*] I have read and understand the `CONTRIBUTING` guide
- [*] I looked for duplicate issues before submitting this one

### Description

Hi there!
I'm trying to upgrade from v2 with 
```Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser```
but have an error:
```
Update-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:32
+ Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser
+                                ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
```
`(Get-Command -Name Install-Module).Parameters.Keys` doesn't show me `AllowPrerelease` in the list.

### Environment

- Oh my Posh version: 
- Theme: 
- Operating System: Windows 10 -19042.746
- Shell: Powershell 5.1.19041.610
- Terminal: Windows Terminal Preview Version: 1.5.3242.0

### Steps to Reproduce

```Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser```

**Comment by ntaken** [comment]
Try update your PackageManagement and PowerShellGet modules first.

**Comment by JanDeDobbeleer** [comment]
As @ntaken says, your toolset is outdated. Updating PowerShellGet is the way to go.

```
Update-Module –Name PowerShellGet –Force –Verbose
```

**Comment by sgstq** [comment]
Thanks, for answer. This worked for me!
👌
