### ISSUE TITLE
nushell: 0.78.0 init script is broken

### ISSUE THREAD

**Issue by rmerli** [JanDeDobbeleer/oh-my-posh#3675]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

if I run:
 `oh-my-posh init nu or oh-my-posh init nu --config ~/.poshthemes/huvix.omp.json`
then:
 `source ~/.oh-my-posh.nu`

I get:
```
Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
    ╭─[.oh-my-posh.nu:8:1]
  8 │     # making the behavior different compared to other shells
  9 │     let-env PROMPT_COMMAND_RIGHT = {''}
    ·                                    ──┬─
    ·                                      ╰── Parsing as a closure, but || is missing
 10 │     let-env POSH_SHELL_VERSION = (version | get version)
    ╰────

  help: Try add || to the beginning of closure
```

![Screenshot from 2023-04-05 11-25-34](https://user-images.githubusercontent.com/40023353/230040826-a3e9e857-7aaf-417a-a598-54e9b77fcb12.png)

### Theme

huvix.omp.json or no theme

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

nu

### Log output

```Shell
Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
    ╭─[.oh-my-posh.nu:8:1]
  8 │     # making the behavior different compared to other shells
  9 │     let-env PROMPT_COMMAND_RIGHT = {''}
    ·                                    ──┬─
    ·                                      ╰── Parsing as a closure, but || is missing
 10 │     let-env POSH_SHELL_VERSION = (version | get version)
    ╰────
  help: Try add || to the beginning of closure
```

**Comment by JanDeDobbeleer** [comment]
@Riccardo-merli94 which version of nu?

**Comment by rmerli** [comment]
@JanDeDobbeleer  0.78.0

I just noticed it came out yesterday, I'm going to try to downgrade to 0.77.0 and see if it changes

EDIT: 
Downgrading from 0.78.0 to 0.77.0 fixed it

**Comment by JanDeDobbeleer** [comment]
@Riccardo-merli94 that's annoying, I'll upgrade and try to fix it. I use nu as my primary shell as well.

**Comment by rmerli** [comment]
@JanDeDobbeleer really appreciated it, thanks!

**Comment by JanDeDobbeleer** [comment]
[root cause](https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#now-required-in-closures)
