### ISSUE TITLE
Color label in "local_working_icon" will appear in terminal

### ISSUE THREAD

**Issue by sky96111** [JanDeDobbeleer/oh-my-posh#368]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]
[BUG]: 
Color label in json like `"local_working_icon": "<#FFAFD7>\u002a</>"` ,the source code `<#FFAFD7> </>` will be rendered in terminal

### Environment

- Oh my Posh version: 3.78.1
- Theme: Pure
- Operating System: Windows10 19042.746
- Shell: PowerShell 7.1.1
- Terminal: Windows Terminal

### Steps to Reproduce

1. Write a theme
2. Add color lebel in "git“-"local_working_icon"
```
{
	"type": "prompt",
	"alignment": "left",
	"segments": [{
		"type": "git",
		"style": "plain",
		"foreground": "#6C6C6C",
		"properties": {
			"display_stash_count": true,
			"display_status": true,
			"display_status_detail": true,
			"display_upstream_icon": true,
			"branch_icon": "",
			"github_icon": "",
			"branch_ahead_icon": "<#88C0D0>\u21e1 </>",
			"branch_behind_icon": "<#88C0D0>\u21e3 </>",
			"local_working_icon": "<#FFAFD7>\u002a</>"
		}
	}]
}
```

**Expected behavior:** [What you expected to happen]
Only show "\u002a"(*)

**Actual behavior:** [What actually happened]
 `<#FFAFD7> </>` also shows
![屏幕截图 2021-01-23 220001.jpg](https://i.loli.net/2021/01/23/DBd29tGLlS7IJpz.jpg)

**Comment by lnu** [comment]
Seems like a regex issue. The `*` is colored because of an inner tag inside your custom color. It seems the inner tag breaks the outside one.
![image](https://user-images.githubusercontent.com/1829553/105591744-b6e4fa00-5d92-11eb-9465-254fec614f64.png)

I'm not sure it's a bug as it's not supported: 
> local_working_icon: string - the icon to display in front of the working area changes - defaults to \uF044

From the doc:

> You have the ability to override the foreground and/or background color for text in any property that **accepts it**.

**Comment by JanDeDobbeleer** [comment]
@lnu @sky96111 we can resolve this by nesting the logic. That's what's missing here as I match the outer tags, get the content and colorize while I should check for colors inside that text first. Might be challenging to get right though.

**Comment by lnu** [comment]
> @lnu @sky96111 we can resolve this by nesting the logic. That's what's missing here as I match the outer tags, get the content and colorize while I should check for colors inside that text first. Might be challenging to get right though.

If there's not more than one level of nesting it's ok.

**Comment by JanDeDobbeleer** [comment]
Either way, it's an extension of current functionality rather than a bug. It was never designed to do this.

**Comment by JanDeDobbeleer** [comment]
@lnu @sky96111 this is incredibly hard to get working right. I'm inclined to state nested colouring is out of scope.

**Comment by lnu** [comment]
> @lnu @sky96111 this is incredible hard to get working right. I'm inclined to state nested colouring is out of scope.

I gave it a try too and I confirm it’s not easy to change it quickly

**Comment by JanDeDobbeleer** [comment]
@lnu I'm going try a different route. ~~The reason this turns out to be nested might be a bug.~~ -> Not true, but there might be a way around in this case. The git segment is the only one that can have this issue and I believe it can be resolved.
