### ISSUE TITLE
Award holopin badge to all amazing contributors 🧙🏻 

### ISSUE THREAD

**Issue by JanDeDobbeleer** [JanDeDobbeleer/oh-my-posh#3697]
Because ❤️

**Comment by BoseSj** [comment]
Thanks a lot ❤️ @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@BoseSj let's see if the bot works 😅 You're all my test audience 😄

**Comment by BoseSj** [comment]
Haha..cool! 😁 let's see.

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @JanDeDobbeleer wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @lnu wizard

**Comment by JanDeDobbeleer** [comment]
Ok, I'm going to automate this, seems like it can only handle 1 contributor per comment. Great 😓

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @JanDeDobbeleer wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @ehawman-rosenberg wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @felpel wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @asherber wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @estruyf wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @cdonnellytx wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jedwillick wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @wozjac wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @lewis-yeung wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @icy-comet wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @lnu wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @memcpy-rand-rand-rand wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jos3s wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @the-eduardo wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @BoseSj wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @kapsiR wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Khaos66 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @tomkerkhove wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @cabauman wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @tillig wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @lfelipe1501 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Mr-Vipi wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Jan0660 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @nwykes wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @maxlandon wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @justin-vogt wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @eltociear wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @michalzielanski wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @travatomic wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @sectorogo wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @mikesigs wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @markbullplus wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @CodexLink wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @frohlichcortezh wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @shawnwildermuth wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @shyguyCreate wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @csrakowski wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @LarsBauer wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @denelon wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @chrisant996 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @LNKLEO wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @TheTaylorLee wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @tiwahu wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jvsca wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @tiagaoalb wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @mjcarman wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @erclu wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @darkvertex wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @vimode wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @NickCraver wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @IrwinJuice wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Kushal-Chandar wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @JustinGrote wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @pitkali wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @stefanes wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @GerbenWelter wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @FWest98 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @bewing wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @LuiseFreese wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @evilz wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @sitiom wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @bend-n wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @mosullivan93 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @mattcargile wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @brian6932 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @vedantmgoyal2009 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @mattwojo wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @benallred wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @xt0rted wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @bgelens wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @blowdart wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @DarkMagicSource wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @craiglpeters wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @claudiospizzi wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @gork3n wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @CapularisPerpetua wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @DavidDeSloovere wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Daksh777 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @DamianEdwards wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @davidanthoff wizard

**Comment by BoseSj** [comment]
Nice, it worked this way.

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @simonauner wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @PixelRobots wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Descalon wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @thiagobarros2 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @GZTimeWalker wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @NoF0rte wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @simorgh1 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Gary-H9 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @DataCrusade1999 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @relativityhd wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @asportnoy wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @CorneliusTantius wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Vixb1122 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Goliaita wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @anoopt wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @decart wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @cesarvspr wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @BM0B0T wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @beppler wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @tonybaloney wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @cveld wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @hanskokx wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @th3c0d3br34ker wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @bsiegert wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @dphov wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @softweaprograma wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @fransyrcc wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @atakiya wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @hasancemcerit wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @ttyz wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @guilhermelias wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Goooler wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @AjayKMehta wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @davidcourtney wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @floh96 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @hgreving wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @akselkvitberg wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @Bahnschrift wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @FLeven wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @AsafMah wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @douugdev wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @ethansocal wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @CodyScavenger wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @kasuken wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @FlavienMacquignon wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @zeyugao wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @shiipou wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @aexvir wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @AmRo045 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @HaroldPetersInskipp wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @GavinOsborn wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @gschizas wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @DamianoPellegrini wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @dhrdlicka wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @hadrizi wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @wopian wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @ksdpmx wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jetersen wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @dorian-li wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @FabianEscarate wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @cbargren wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @equinox wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @antonpiatek wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @andresrinivasan wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jakeboone02 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @sharunkumar wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @erresen wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @teoshibin wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @SebastianMineur wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jantielens wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @rfverbruggen wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @jtracey93 wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @zanseb wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @h4iku wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @samuelfahrngruber wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @ralish wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @patHyatt wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @SeanKilleen wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @rahathosen wizard

**Comment by JanDeDobbeleer** [comment]
@holopin-bot @romch007 wizard

**Comment by floh96** [comment]
@JanDeDobbeleer i got 160 mails because of this issue...

**Comment by tomkerkhove** [comment]
Holopins for everyone!

**Comment by JanDeDobbeleer** [comment]
@floh96 160? Sorry about that, would've been nice if holopin had a way to provide a badge using the API and distribute using your GitHub handle but that only works using email which isn't available for everyone. But I'm done!

**Comment by rahathosen** [comment]
Thanks  @JanDeDobbeleer
