### ISSUE TITLE
Windows Terminal running v3 in a v2 cmdlet. 

### ISSUE THREAD

**Issue by awguitar86** [JanDeDobbeleer/oh-my-posh#373]
### Prerequisites

- [ x] I have read and understand the `CONTRIBUTING` guide
- [ x] I looked for duplicate issues before submitting this one

### Description

I'm trying to get the v3 working on my Windows Terminal. I've walked through all the steps I could find to install it and upgrade it, but every time I start up my windows terminal it doesn't grab the theme I've set it to, and it says, 

"It seems you're using an oh-my-posh V2 cmdlet while running V3. To migrate your current setup to V3, have a look the documentation."

I've gone over the documentation multiple times, but I'm not sure how to get v3 fully integrated, and to stop using a V2 cmdlet.

### Environment

- Oh my Posh version: 3.80.0
- Theme: Operator
- Operating System: Windows 10
- Shell: PowerShell 7
- Terminal: Windows Terminal

### Steps to Reproduce

1. Download Windows Terminal
2. Download PowerShell 7
3. Install posh-git
4. Install oh-my-posh
5. Upgrade oh-my-posh with "Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser"
6. Add these lines to the $PROFILE: "Import-Module posh-git" "Import-Module oh-my-posh" "Set-Theme Operator"
7. Open Windows Terminal

**Expected behavior:** 
Expected to have Windows Terminal running oh-my-posh v3 and see the new themes, and new way of making updates and customizing the oh-my-posh.

**Actual behavior:** 
When terminal opens up the message in the terminal says, "It seems you're using an oh-my-posh V2 cmdlet while running V3.
To migrate your current setup to V3, have a look the documentation." And the Theme is not being used.

**Comment by JanDeDobbeleer** [comment]
You're using V3, that's the good part. The only problem is that you got the cmdlet wrong, can you dump that part of your `$PROFILE` here?

From your comment it seems you're using `Set-Theme` which is renamed to `Set-PoshPrompt` in V3.

**Comment by awguitar86** [comment]
This is all I have in my $PROFILE

Import-Module posh-git
Import-Module oh-my-posh
Set-Theme Operator

So instead of using Set-Theme in the profile, should I use Set-PoshPrompt? Because when I do Set-PoshPrompt in PowerShell it doesn't set anything in the profile.

**Comment by JanDeDobbeleer** [comment]
> So instead of using Set-Theme in the profile, should I use Set-PoshPrompt?

@awguitar86 yes. Although `operator` isn't available in V3, but it should fallback to a prompt nonetheless.

**Comment by awguitar86** [comment]
That worked! Thank you!
