### ISSUE TITLE
Ability to override global properties in templates

### ISSUE THREAD

**Issue by maxlandon** [JanDeDobbeleer/oh-my-posh#3734]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently, some global properties have precedence in templates:
https://ohmyposh.dev/docs/configuration/templates#global-properties

This means that if a new, specialized segment type is registered, such as
```go
type SpecialSegment struct {
        OS string
        PWD string
}
// ... Methods to implement SegmentWriter
```

If this segment is referenced in a configuration, with let's say `{{ .OS }}` as its template, the `OS` value will be that of the global properties, and not the one from the segment.

I would like to know if it's possible to let each segment writer to have precedence over these values.
- I have neither looked at the code on how to this.
- I have briefly thought of how could this be an issue or have unintended effects, but I can't see any as of now.

Thanks a lot for considering this !

**Comment by JanDeDobbeleer** [comment]
@maxlandon no, you'll need to define a different word. This is a bit of [magic hack](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/template/text.go#L76), and the global properties get replaced before the template evaluates. We could theoretically look at the properties and see if it exists (as in `t := reflect.TypeOf(SpecialSegment)` and only do the replacement if it doesn't exist at segment level but I don't know if there would be any performance impact. I could try.

**Comment by maxlandon** [comment]
Thanks for the quick answer. 
I'll do a few tries and tests on my own as well, and reach back with any results.

**Comment by JanDeDobbeleer** [comment]
@maxlandon https://github.com/JanDeDobbeleer/oh-my-posh/pull/3741

**Comment by maxlandon** [comment]
Great ! Thanks a lot !
