### ISSUE TITLE
No update

### ISSUE THREAD

**Issue by TheLight8** [JanDeDobbeleer/oh-my-posh#3735]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I try to update using the Docs, but nothing happens.
This is the command and output:
```
> winget update JanDeDobbeleer.OhMyPosh -s winget
No applicable upgrade found.
```

### Theme

night-owl.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
-
```

**Comment by JanDeDobbeleer** [comment]
@TheLight8 winget always lags a bit behind, should flow in soon. See [here](https://github.com/microsoft/winget-pkgs/pull/103007).

**Comment by TheLight8** [comment]
This was incredibly fast, you are amazing. Thank you for your hard work, btw, I love this tool. All the best!
