### ISSUE TITLE
Python virtual environment shows before prompt is rendered

### ISSUE THREAD

**Issue by aarontcannon** [JanDeDobbeleer/oh-my-posh#374]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When creating a python virtual environment, the virtual environment shows correctly in the oh-my-posh prompt, while also showing directly before the prompt. This is unnecessary and should be overwritten by the oh-my-posh prompt. See the attached image for an example of the issue. This happens when using venv in Python 3.9 to create a virtual environment.

![Screenshot 2021-01-28 194803](https://user-images.githubusercontent.com/26099494/106216806-e84e3300-61a1-11eb-9c30-1551aac70cbf.png)

### Environment

- Oh my Posh version: 3.78.1
- Theme: Custom
- Operating System: Windows 10 Pro
- Shell: Powershell 5.1.19041.610
- Terminal: VSCode terminal and Microsoft Terminal
- Python version: 3.9

### Steps to Reproduce

1. Open powershell with oh-my-posh and python segment
2. Create python virtual environment (python 3.9 venv)
3. Activate virtual environment

**Expected behavior:** I expect the virtual environment name to only be displayed in the python segment and not to be displayed before the oh-my-posh prompt.

**Actual behavior:** The python virtual environment name is displayed both before the oh-my-posh prompt and in the python segment.

**Comment by JanDeDobbeleer** [comment]
In theory I could wipe that part. But maybe not everyone want that behavior. So the right approach, as it's other tooling writing that prompt, not oh-my-posh, is to disable that by setting the environment variable `VIRTUAL_ENV_DISABLE_PROMPT` to `1`.

**Comment by aarontcannon** [comment]
I had tried setting `VIRTUAL_ENV_DISABLE_PROMPT` to `1`. While it does work, it also hides the virtual environment name from the oh-my-posh prompt as well (I guess because that is where oh-my-posh is getting the name from).

**Comment by JanDeDobbeleer** [comment]
Ok, not what I expected. I'll clear the line before starting to write the prompt in that case.

**Comment by JanDeDobbeleer** [comment]
@aarontcannon I did some digging into `Activate.ps1` and found something interesting:

**Conda**

```powershell
# Capture existing user prompt
function global:condaUserPrompt {''}
$function:condaUserPrompt = $function:prompt

function global:prompt
{
    # Add the virtualenv prefix to the current user prompt.
    Write-Host "[$condaEnvName] " -nonewline -ForegroundColor Red
    & $function:condaUserPrompt
}
```

**CPython**

```powershell
if (-not $Env:VIRTUAL_ENV_DISABLE_PROMPT) {

    Write-Verbose "Setting prompt to '$Prompt'"

    # Set the prompt to include the env name
    # Make sure _OLD_VIRTUAL_PROMPT is global
    function global:_OLD_VIRTUAL_PROMPT { "" }
    Copy-Item -Path function:prompt -Destination function:_OLD_VIRTUAL_PROMPT
    New-Variable -Name _PYTHON_VENV_PROMPT_PREFIX -Description "Python virtual environment prompt prefix" -Scope Global -Option ReadOnly -Visibility Public -Value $Prompt

    function global:prompt {
        Write-Host -NoNewline -ForegroundColor Green "($_PYTHON_VENV_PROMPT_PREFIX) "
        _OLD_VIRTUAL_PROMPT
    }
    $env:VIRTUAL_ENV_PROMPT = $Prompt
}
```

That actually means I can't do anything as it captures the current prompt and prepends it. Curious to see what your `Activate.ps1` holds as it seems to differ based on the tooling you use.

**Comment by whimian** [comment]
Any update on this problem?

**Comment by whimian** [comment]
I'm using conda as the python package manager. Import oh-my-posh after the conda hook seems to solve the problem for me.
But I don't know if venv works the same way.

![image](https://user-images.githubusercontent.com/3821278/114350585-f5bd6b80-9b9b-11eb-876d-b78984ce9f65.png)

**Comment by 2bndy5** [comment]
FYI, I was able to solve this with python venv by setting `VIRTUAL_ENV_DISABLE_PROMPT` to 1 (in my user env vars), then setting `VIRTUAL_ENV_PROMPT` to the env name in pyvenv.cfg. It is a little hacky, but at least I can use the same OMP theme in both WSL bash and PS.
