### ISSUE TITLE
Upgrading to 15.2.0 breaks oh-my-posh in bash

### ISSUE THREAD

**Issue by jeansagi** [JanDeDobbeleer/oh-my-posh#3757]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!

After upgrade to version 15.2.0

When I run:
`oh-my-posh --version`

It shows:
`Segmentation fault`

And exits.

So there are no more posh prompt for me :(

J.

### Theme

night-owl.omp.json

But any theme ends with a `Segmentation fault`

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```Shell
Segmentation fault
```

**Comment by JanDeDobbeleer** [comment]
@jeansagi can you show me a screenshot?

**Comment by jeansagi** [comment]
ok - on windows11@home
![image](https://user-images.githubusercontent.com/24227857/234281191-7a98def1-4432-47ac-ac65-3bc1add80db6.png)

**Not ok** - on windows10@work (_where I upgraded yesterday_)
![image](https://user-images.githubusercontent.com/24227857/234282346-bb18eb44-77ea-4101-9b88-28fcb35f14f9.png)


J.

**Comment by JanDeDobbeleer** [comment]
@jeansagi are you sure you installed the correct binary? Seems like it's the wrong binary format. I can't reproduce this at all.

**Comment by jeansagi** [comment]
I originally installed with Chocolatey.

And keep it upgraded with that way too.

For the last upgrade I did it as usual:
choco upgrade oh-my-posh

And it "successfully" upgraded it, but after that oh-my-posh stopped working.

How do I know if I have the correct binary?
(_I suppose you are referring to the architecture, that is x64 in my case._)


J.

**Comment by jeansagi** [comment]
Crap!

The problem was mine! (I suppose).

Just uninstalled and re-installed again (with chocolatey) and now it is working as usual...

Most probably I did something wrong when I upgraded.

So, certainly oh-my-posh has no problem here.

Sorry.


J.

**Comment by JanDeDobbeleer** [comment]
Happy we were able to resolve it!
