### ISSUE TITLE
Is there a way to do this ( couple questions ) and maybe a few ideas.

### ISSUE THREAD

**Issue by pb5050** [JanDeDobbeleer/oh-my-posh#376]
1. a way to detect charge level and change colors Based on %?
2. the "root" or admin mode block or whatevr is there a way to incorperate my User/Host name into that? 

-example would be username text or the powerline background would  Turn Gold/Yellow when admin mode), Turn red when error, and a nuetral color?
same thing with the > > > >  >splitters ive been trying to incorporate that into those. the splitter color would act as admin mode, error mode, nuetral, and then if battery is really low they all turn Oarnge.  i cant do this for the life of me after hours i give up lol

  ＼(ﾟｰﾟ＼)
3.

**Comment by JanDeDobbeleer** [comment]
@pb5050 no to all of those. Can it be extended to do this? Yes. The percentages is the second time this question pops up so I'll give that a go. Admin in the session segment can be done. The last one needs some more explanation, I didn't get that.

**Comment by pb5050** [comment]
![Example](https://user-images.githubusercontent.com/58855947/106377123-59d3e000-6360-11eb-8152-e9fd146675a4.png)

ok so like i left part of username original Green  color. Instead of bolt to show admin mode the username turns yellow to show admin mode, and also the username  changes red for when error, and for battery  %.

the > > splitters could change colors to show error, or admin mode, 0r battery level ?  i painted those too. 

or you could do the background behind Username  Janss turn yellow if admin mod instead of the black color.

then i was trying to make all  the splitters > > turn orange if battery is below 10%



Does that explain a little better? sorry if not i will try again hehe

**Comment by pb5050** [comment]
like a variable 
 AdminModeUsernamecolor: "#99ff53"
AdminModebackgroundcolor: "#99ff53"
AdminModeSplittercolor: "#99ff53"
instead of admin "battery%" , Error, "charging"

im just throwing ideas out and maybe u will come up with something better or whatever  i just really like the color changing this stuff because it is using existing parts of the "power line"  and minimizing clutter.

**Comment by JanDeDobbeleer** [comment]
@pb5050 the Battery segment now supports [color templates](https://ohmyposh.dev/docs/configure), some for session. On top of that, session has been extended to have the needed [template properties](https://ohmyposh.dev/docs/session) and template support to allow you to colorize how you want.
