### ISSUE TITLE
Node segment improvement

### ISSUE THREAD

**Issue by roterob** [JanDeDobbeleer/oh-my-posh#378]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

It would be amazing if node segment could check the existence of `.nvm` file and warning (change segment color) if current node version doesn't mach with `.nvm` version.

I'm learning `go` only for this :) but I guess need some help.

**Comment by JanDeDobbeleer** [comment]
`.nvm` file is an easy extension (add it [here](https://github.com/JanDeDobbeleer/oh-my-posh3/blob/main/src/segment_node.go#L15)), version file offset requires additional changes especially given that languages have the same base. But perfectly doable.

**Comment by roterob** [comment]
Yep, maybe is better take as base git segment... Let me know if there is a better approach.

**Comment by JanDeDobbeleer** [comment]
@roterob I have the basis ready, can you give me the contents of `.nvm`?

**Comment by roterob** [comment]
The most common way to generate a `.nvm` file is `node --version > .nvm`. Is a file with the node version that the current project should use.
