### ISSUE TITLE
Improve error reporting when installing a font

### ISSUE THREAD

**Issue by redgoldlace** [JanDeDobbeleer/oh-my-posh#3782]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hey there! I've just spent some time getting oh-my-posh set up on a new Windows 11 installation, and I think the feedback from `oh-my-posh font install` could potentially be made a little clearer when things don't go as expected.

1. **Truncated DNS error messages**
   I'm unsure why, but when using Windows 11's default DNS settings and trying to install a font that didn't exist, I received the following error:
   
   `Get "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrains.zip": dial tcp: lookup github.com: i/o timeout`
   
   **This error was truncated based on the terminal window's total width**, which made it harder to figure out what was going on; I was able to resolve this issue by setting my DNS to 1.1.1.1/1.0.0.1, which honestly just confuses me even more. It's a miracle that the internet works at all.
   
   (It's worth noting that I use Tailscale on this machine, but stopping it didn't seem to have any effect, so I'm unsure whether it was the culprit)

2. **Potentially misleading "... is not a valid zip file" message**

   When you try to download a file from GitHub that doesn't exist, it returns the text `Not Found` verbatim, along with a status code of 404. When using `oh-my-posh font install` to try and install a font that doesn't exist, oh-my-posh reports the following error:
   
   `https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrains.zip is not a valid zip file`
   
   It seems like oh-my-posh attempts to read the contents of the response body without checking whether the request was successful, which can lead to a potentially misleading error. While it *is* technically true that "Not Found" isn't a valid zip file, I think it would probably be more helpful to display something regarding the failed request/the status code in this case.
   
I'm happy to help with implementation (it shouldn't be too much work ^^) but wanted to open an issue first to get opinions. Thank you!

**Comment by JanDeDobbeleer** [comment]
@kaylynn234 sound like a plan. I can have a look at improving this.

**Comment by redgoldlace** [comment]
Thanks a ton! I really appreciate it
