### ISSUE TITLE
Allow links without underlines

### ISSUE THREAD

**Issue by jonaskuske** [JanDeDobbeleer/oh-my-posh#3798]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'd like to be able to make a link with template functions `url` or `path` that appears like regular text, without underlines or other visual highlights.

**Comment by JanDeDobbeleer** [comment]
@jonaskuske that's a Terminal request, not oh-my-posh. We don't render the URL that way. That decoration comes from Terminal.
