### ISSUE TITLE
Disable update check by default in msstore version

### ISSUE THREAD

**Issue by soredake** [JanDeDobbeleer/oh-my-posh#3799]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I don't checking for new version is needed as msstore will update oh-my-posh automatically.

**Comment by JanDeDobbeleer** [comment]
@soredake you can disable this using `oh-my-posh disable notice`. As the installer is identical regardless of the means of installation, we have no way to know how you installed. And, the Store is always behind.

**Comment by soredake** [comment]
> you can disable this using `oh-my-posh disable notice`.

I know, but i think it should be done automatically.

>we have no way to know how you installed.

Actually, there is a way, msstore installs oh-my-posh to `C:\Users\<user>\AppData\Local\Programs\oh-my-posh\bin\`

**Comment by JanDeDobbeleer** [comment]
@soredake the installer does that, not the Store. So we can't distinguish between installation means.
