### ISSUE TITLE
feat: AWS segment

### ISSUE THREAD

**Issue by ppittle** [JanDeDobbeleer/oh-my-posh#380]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Is it possible to have a local powershell variable display in a segment? (And be performant while doing so?)

I tried with the following segment which I want to write out `$localVar`:

```javascript
 "segments": [  {
     "type": "command",
     "style": "plain",
     "powerline_symbol": "",
     "invert_powerline": false,
     "foreground": "#D4E157",
     "background": "#546E7A",
     "leading_diamond": "",
     "trailing_diamond": "",
     "properties": {
         "command": "echo $localVar"
      }
}]
```
But the command segment doesn't print anything:

![image](https://user-images.githubusercontent.com/1190907/107010729-954d2080-674b-11eb-87b0-d12c202eb628.png)

#### Context:
For context, I'm basically trying to port the custom Prompt in this old [aws blog on powershell for aws](https://aws.amazon.com/blogs/developer/handling-credentials-with-aws-tools-for-windows-powershell/) and port it to work inside oh-my-posh.

### Environment

- Oh my Posh version: 3.80.1
- Theme:
- Operating System:  Windows
- Shell: PowerShell Core
- Terminal: Windows Terminal

### Steps to Reproduce

1. Set a powershell variable `$localVar` to `test`
2. Create a theme with a _command_ segmant like above.
3. Run oh-my-posh

**Expected behavior:** Prompt reads local variable and displays `test`

**Actual behavior:** `Test` is not printed inside the Prompt

**Comment by JanDeDobbeleer** [comment]
2 things we can do:
- there's a function called `Set-PoshContext` you can use to update environment variables for example. If you define a new env var and add the value of `$localVar` to it and use that in the `envvar` [segment](https://ohmyposh.dev/docs/environment). The details are also indicated in those docs.
- we build an AWS segment for this use-case

The first option will unblock you, the second one makes the most sense in the long run ;-)

**Comment by ppittle** [comment]
I might be experimenting with an AWS segment :)

Curious if a custom segment would allow me access to local PowerShell variables though?  Inside the segment running `env.runShellCommand` or `env.runCommand` doesn't seam to be able to access the value.

Would the custom segment still need to use the Set-PoshContext trick in the Prompt?

**Comment by JanDeDobbeleer** [comment]
@ppittle you can't access Powershell variables as that runs in a different process. You can call environment variables (AWS cli sets these) and display those or call that AWS cli directly.

**Comment by JanDeDobbeleer** [comment]
@ppittle can you check the latest version offers what you're looking for?

**Comment by glucas** [comment]
Trying this out on Win10 / pwsh 7.1.1 and not seeing anything shown for the AWS template. Just to clarify, this template will look for the $env:AWS_PROFILE and similar variables, right?

**Comment by JanDeDobbeleer** [comment]
@glucas yes, and the config file. How did you add the segment? Because I still have a bug in the docs 😅

**Comment by glucas** [comment]
> How did you add the segment? Because I still have a bug in the docs 😅

Ha, I just copied the example from the doc!

**Comment by JanDeDobbeleer** [comment]
That should be correct, did you update?

**Comment by ppittle** [comment]
@JanDeDobbeleer that's fantastic!

![image](https://user-images.githubusercontent.com/1190907/107840592-e753fe80-6d68-11eb-8a53-b3d7825d8f35.png)

I tweaked out the template to replace the @ with an orange amazon logo and dropped the prefix character:
```
{
    "type": "aws",
    "style": "powerline",
    "powerline_symbol": "",
    "invert_powerline": false,
    "foreground": "#100e23",
    "background": "#ffffff",
    "leading_diamond": "",
    "trailing_diamond": "",
    "properties": {                        
		"template": "{{.Profile}}{{if .Region}}<#F8991D>\uf52c</>{{.Region}}{{end}}"
    }
}
```

**Comment by JanDeDobbeleer** [comment]
Feel free to close this when your request is resolved.

**Comment by glucas** [comment]
> That should be correct, did you update?

Interesting, I get nothing. I grabbed the segment from the doc and added it to my theme. I'm setting $env:AWS_PROFILE and $env:AWS_REGION in my pwsh shell. I'll experiment further.

I can `aws configure list` and see profile and region are picked up from my shell. Created a theme with just path and aws segments, and only get the path. Strange.

**Comment by JanDeDobbeleer** [comment]
@glucas ok, but did you update oh-my-posh? Otherwise it won't work.

**Comment by glucas** [comment]
Yes, this is my fault. I've been updating oh-my-posh3 via scoop to newer versions, but now realize I separately have the powershell module installed and that is on an older version. Once again, apologies for the noise! 

Works great now - this is very useful, thanks for the great package.

**Comment by glucas** [comment]
One possible enhancement for the AWS segment would be to only show when the profile is not 'default'. I think I can achieve something similar with if conditions in the template, however.

**Comment by JanDeDobbeleer** [comment]
@glucas not necessarily, that's an additional feature :-) But very doable indeed. I'll add it.

**Comment by JanDeDobbeleer** [comment]
@glucas added with the [newly available](https://ohmyposh.dev/docs/aws#properties) `display_default` property.

**Comment by alefranz** [comment]
> @glucas yes, and the config file. How did you add the segment? Because I still have a bug in the docs 😅

Hi Jan,
I'm trying to configure this, but it only seems to read the value from the env variables (AWS_PROFILE, AWS_REGION) but it doesn't seem to be loading the config file ~/.aws/config.

For example with AWS_PROFILE, the active profile should be the one called "default" from the config file, but it is not displayed.
When AWS_REGION is not set, the region selected should be the one of the active profile (either "default" or the one specified in the AWS_PROFILE variable).

Could you clarify how the config is loaded?

I think it would also be nice to get a status if the authentication is valid or expired, and extra infromations like the account connected and so on, essentially to get something like the output of `aws sts get-caller-identity` CLI command. Should I create a ticket for this feature request?

**Comment by JanDeDobbeleer** [comment]
@alefranz allow me to explain in the morning 😉 (you can read it [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/1a907f3c4879fab946f8860c39d887506a452af5/src/segment_aws.go#L34)). About using the `aws` command, that's discouraged as it's really slow (tried it).

**Comment by alefranz** [comment]
> @alefranz allow me to explain in the morning 😉 (you can read it [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/1a907f3c4879fab946f8860c39d887506a452af5/src/segment_aws.go#L34)). About using the `aws` command, that's discouraged as it's really slow (tried it).

Appreciate the quick reply, but take your time 😂 not urgent at all!
I had a look at the code, but that logic is somehow not working for me on pwsh on Windows.
I'll get the repo and try to see if I can debug it.

**Comment by glucas** [comment]
@alefranz  For what it's worth, I am running pwsh and when I enable the AWS segment it in fact shows me the default profile name and region, with no AWS variables set:
![image](https://user-images.githubusercontent.com/72533/109046122-65d26980-76a2-11eb-87e4-48fc28aacede.png)

In my case I'd prefer to only see this for non-default values but that should be a separate feature request, I'll file it.

**Comment by JanDeDobbeleer** [comment]
@glucas you can set the property `display_default` to `false` to get that result.
