### ISSUE TITLE
Weather icon need update under owm segment

### ISSUE THREAD

**Issue by LancerLucky** [JanDeDobbeleer/oh-my-posh#3806]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The nerd font update to 3.0.0 that removed a lot of icon and replaced with new icons, therefore some of the weather icon are missing after update the font

### Theme

{
    "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
    "blocks": [
        {
            "alignment": "left",
            "type": "prompt",
            "segments": [
                {
                    "type": "os",
                    "style": "diamond",
                    "leading_diamond": "\ue0b6",
                    "powerline_symbol": "\ue0b0",
                    "foreground": "#26C6DA",
                    "background": "#3a4144",
                    "template": " {{ if .WSL }}WSL at {{ end }}{{.Icon}}  ",
                    "properties": {
                        "macos": "\uf179"
                    }
                },
                {
                    "background": "#f77622",
                    "foreground": "#262b44",
                    "leading_diamond": "\ue0b6",
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "folder_icon": "\ue5fe",
                        "folder_separator_icon": " \ue0b1 ",
                        "mixed_threshold": 6,
                        "style": "mixed"
                    },
                    "style": "powerline",
                    "template": " 󰀶 {{ .Path }} ",
                    "type": "path"
                },
                {
                    "background": "#ff2d2d",
                    "foreground": "#aaaaaa",
                    "foreground_templates": [
                        "{{ if or (.Working.Changed) (.Staging.Changed) }}#4922f7{{ end }}",
                        "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#e43b44{{ end }}",
                        "{{ if gt .Ahead 0 }}#4922f7{{ end }}",
                        "{{ if gt .Behind 0 }}#2ce8f5{{ end }}"
                    ],
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "display_status": true,
                        "display_stash_count": true,
                        "display_upstream_icon": true,
                        "fetch_stash_count": true,
                        "fetch_upstream_icon": true
                    },
                    "style": "powerline",
                    "template": " {{ .HEAD }} {{ .BranchStatus }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and ( .Staging.Changed) ( .Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0}} 󰆓 {{ .StashCount }}{{ end }}{{ if gt .WorktreeCount 0}} \uf1bb {{ .WorktreeCount }}{{ end }} ",
                    "type": "git"
                },
                {
                    "type": "shell",
                    "style": "diamond",
                    "powerline_symbol": "\uE0B2",
                    "trailing_diamond": "\ue0b4",
                    "foreground": "#ffffff",
                    "background": "#0077c2",
                    "properties": {
                        "mapped_shell_names": {
                            "pwsh": "\uebc7",
                            "cmd": "\uebc4 ",
                            "bash": "\uf1d3",
                            "zsh": "\uf489"
                        }
                    }
                }
            ]
        },
        {
            "type": "prompt",
            "alignment": "right",
            "overflow": "hide",
            "segments": [
                {
                    "background": "#2f2f2f",
                    "foreground": "#26C6DA",
                    "leading_diamond": "\ue0b6",
                    "powerline_symbol": "\ue0b2",
                    "invert_powerline": true,
                    "properties": {
                        "precision": 0
                    },
                    "style": "diamond",
                    "template": "󰍛 {{ round .PhysicalPercentUsed .Precision }}% ",
                    "type": "sysinfo"
                },
                {
                    "type": "connection",
                    "style": "powerline",
                    "invert_powerline": true,
                    "background": "#999999",
                    "foreground": "#222222",
                    "powerline_symbol": "\uE0B2",
                    "trailing_diamond": "\ue0b4",
                    "template": " {{ if eq .Type \"wifi\" }}\uf1eb {{.SSID}}{{ else if eq .Type \"ethernet\" }}\uf6ff {{.Type}}{{ end }} "
                },
                {
                    "type": "battery",
                    "style": "powerline",
                    "invert_powerline": true,
                    "powerline_symbol": "\uE0B2",
                    "foreground": "#193549",
                    "background": "#ffeb3b",
                    "background_templates": [
                        "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
                        "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
                        "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
                    ],
                    "templates": [
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 11) }}󰁺{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 21) }}󰁻{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 31) }}󰁼{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 41) }}󰁽{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 51) }}󰁾{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 61) }}󰁿{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 71) }}󰂀{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 81) }}󰂁{{ end }}",
                        "{{ if and (eq \"Discharging\" .State.String) (lt .Percentage 91) }}󰂂{{ end }}",
                        "{{ if eq \"Discharging\" .State.String }}󰁹{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 11) }}󰢜{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 21) }}󰂆{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 31) }}󰂇{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 41) }}󰂈{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 51) }}󰢝{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 61) }}󰂉{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 71) }}󰢞{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 81) }}󰂊{{ end }}",
                        "{{ if and (eq \"Charging\" .State.String) (lt .Percentage 91) }}󰂋{{ end }}",
                        "{{ if eq \"Charging\" .State.String }}󰂄{{ end }}",
                        "{{if eq \"Full\" .State.String}}󰚥{{end}}"
                    ],
                    "templates_logic": "first_match",
                    "template": " {{ .Templates }} {{ .Percentage }}% "
                },
                {
                    "type": "owm",
                    "style": "diamond",
                    "invert_powerline": true,
                    "powerline_symbol": "\uE0B2",
                    "trailing_diamond": "\ue0b4",
                    "foreground": "#000000",
                    "background": "#990000",
                    "background_templates": [
                        "{{ if (gt .Temperature 26) }}#990000{{ else if (gt .Temperature 18) }}#c99a00{{ else if (gt .Temperature 10) }}#00cf45{{ else }}#002FFF{{ end }}"
                    ],
                    "template": " {{.Weather}} ({{.Temperature}}{{.UnitIcon}})",
                    "properties": {
                        "apikey": "1f35b79f39223a8e0fcd7eb6e9a53bff",
                        "location": "BEIJING,CN",
                        "units": "metric",
                        "http_timeout": 1500,
                        "cache_timeout": 60
                    }
                }
            ]
        },
        {
            "type": "prompt",
            "alignment": "left",
            "newline": true,
            "segments": [
                {
                    "type": "time",
                    "style": "diamond",
                    "leading_diamond": "\ue0b6",
                    "powerline_symbol": "\ue0b0",
                    "foreground": "#bbbbbb",
                    "background": "#3a4144",
                    "properties": {
                        "time_format": "15:04:05"
                    }
                },
                {
                    "background": "#fee761",
                    "foreground": "#262b44",
                    "powerline_symbol": "\ue0b0",
                    "style": "powerline",
                    "template": " \uf0e7 ",
                    "type": "root"
                },
                {
                    "background": "#8800dd",
                    "foreground": "#ffffff",
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "style": "austin",
                        "threshold": 500
                    },
                    "style": "powerline",
                    "template": " <#fefefe>󱦟</> {{ .FormattedMs }} ",
                    "type": "executiontime"
                },
                {
                    "background": "#0095e9",
                    "background_templates": [
                        "{{ if gt .Code 0 }}#f1184c{{ end }}"
                    ],
                    "foreground": "#ffffff",
                    "powerline_symbol": "\ue0b0",
                    "properties": {
                        "always_enabled": true
                    },
                    "style": "powerline",
                    "template": " {{ if gt .Code 0 }}\uf00d {{ .Meaning }}{{ else }}\uf42e{{ end }} ",
                    "trailing_diamond": "\ue0b4",
                    "type": "exit"
                }
            ]
        },
        {
            "type": "rprompt",
            "alignment": "right",
            "segments": [
                {
                    "type": "dart",
                    "style": "diamond",
                    "invert_powerline": true,
                    "leading_diamond": "\uE0B6",
                    "powerline_symbol": "\uE0B2",
                    "foreground": "#bbbbbb",
                    "background": "#06A4CE",
                    "template": " \uE798 {{ .Full }} <transparent>\ue0b2</>"
                },
                {
                    "type": "flutter",
                    "style": "diamond",
                    "invert_powerline": true,
                    "leading_diamond": "\uE0B2",
                    "trailing_diamond": "\ue0b4",
                    "powerline_symbol": "\uE0B2",
                    "foreground": "#bbbbbb",
                    "background": "#06A4CE",
                    "template": " \ue28e {{ .Full }} "
                },
                {
                    "type": "angular",
                    "style": "diamond",
                    "leading_diamond": "\uE0B6",
                    "invert_powerline": true,
                    "powerline_symbol": "\uE0B2",
                    "foreground": "#000000",
                    "background": "#1976d2",
                    "template": " \uE753 {{ .Full }} <transparent>\ue0b2</>"
                },
                {
                    "type": "node",
                    "style": "diamond",
                    "invert_powerline": true,
                    "leading_diamond": "\uE0B2",
                    "trailing_diamond": "\ue0b4",
                    "powerline_symbol": "\uE0B2",
                    "foreground": "#000000",
                    "background": "#6CA35E",
                    "template": " \uE718 {{ .Full }} "
                }
            ]
        }
    ],
    "final_space": true,
    "version": 2
}

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
Version: 15.5.0

Shell: zsh (5.9)

Segments:

ConsoleTitle(false)                        -   0 ms -
os(true)                                   -   0 ms -  
path(true)                                 -   0 ms -  󰀶 ~
git(false)                                 -   0 ms -
shell(true)                                -   0 ms -  
sysinfo(true)                              -   1 ms - 󰍛 61%%
connection(false)                          -   0 ms -
battery(true)                              -  16 ms -   100%%
owm(true)                                  -   0 ms -  滛 (24°C)
time(true)                                 -   0 ms -  11:27:35
root(false)                                -   0 ms -
executiontime(false)                       -   0 ms -
exit(true)                                 -   0 ms -  
dart(false)                                -   0 ms -
flutter(false)                             -   0 ms -
angular(false)                             -   0 ms -
node(false)                                -   0 ms -

Run duration: 21.17825ms

Cache path: /Users/yuanchiwang/.cache/oh-my-posh

Config path: /Users/yuanchiwang/.cache/oh-my-posh/mytheme.omp.double.line.json

Logs:

[DEBUG] 11:27:35.100 shell.go:Getenv:394 → iTerm.app
[TRACE] 11:27:35.100 shell.go:Getenv(TERM_PROGRAM) - 73.709µs
[DEBUG] 11:27:35.100 shell.go:Getenv:394 → NO DATA
[TRACE] 11:27:35.100 shell.go:Getenv(XDG_CACHE_HOME) - 1.791µs
[TRACE] 11:27:35.100 shell_unix.go:CachePath() - 31.167µs
[DEBUG] 11:27:35.101 shell.go:Getenv:394 → /Users/yuanchiwang/.cache/oh-my-posh/mytheme.omp.double.line.json
[TRACE] 11:27:35.101 shell.go:Getenv(POSH_THEME) - 3.333µs
[DEBUG] 11:27:35.101 shell_unix.go:Platform:71 → darwin
[TRACE] 11:27:35.101 shell.go:resolveConfigPath() - 23.709µs
[TRACE] 11:27:35.101 shell.go:Init() - 860.375µs
[TRACE] 11:27:35.101 shell.go:Flags() - 83ns
[TRACE] 11:27:35.101 config.go:loadConfig() - 718.75µs
[TRACE] 11:27:35.101 shell.go:Flags() - 42ns
[DEBUG] 11:27:35.101 shell.go:Getenv:394 → NO DATA
[TRACE] 11:27:35.101 shell.go:Getenv(OMP_CACHE_DISABLED) - 1.625µs
[DEBUG] 11:27:35.101 shell.go:Shell:641 → process name: zsh
[TRACE] 11:27:35.101 shell.go:Shell() - 46.542µs
[DEBUG] 11:27:35.101 shell.go:Getenv:394 → 5.9
[TRACE] 11:27:35.101 shell.go:Getenv(POSH_SHELL_VERSION) - 1.709µs
[DEBUG] 11:27:35.101 debug.go:PrintDebug:22 → Segment: Title
[TRACE] 11:27:35.101 shell.go:Flags() - 42ns
[DEBUG] 11:27:35.101 block.go:Debug:230 → Segment: os
[TRACE] 11:27:35.101 shell.go:GOOS() - 84ns
[DEBUG] 11:27:35.101 shell.go:Pwd:424 → /Users/yuanchiwang
[TRACE] 11:27:35.101 shell.go:Pwd() - 23.958µs
[TRACE] 11:27:35.101 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[DEBUG] 11:27:35.101 properties.go:GetString:28 → 
[TRACE] 11:27:35.101 shell_unix.go:Root() - 458ns
[TRACE] 11:27:35.101 shell.go:Shell() - 83ns
[TRACE] 11:27:35.101 shell.go:ErrorCode() - 166ns
[DEBUG] 11:27:35.101 shell_unix.go:IsWsl:35 → false
[TRACE] 11:27:35.101 shell_unix.go:IsWsl() - 2.042µs
[TRACE] 11:27:35.101 shell.go:Pwd() - 41ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 41ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[TRACE] 11:27:35.101 shell.go:GOOS() - 41ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[TRACE] 11:27:35.101 shell.go:GOOS() - 41ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[TRACE] 11:27:35.101 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[TRACE] 11:27:35.101 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.101 shell.go:User:545 → yuanchiwang
[TRACE] 11:27:35.101 shell.go:User() - 2.25µs
[DEBUG] 11:27:35.101 shell.go:Host:557 → Yuanchi-MacBook-Pro
[TRACE] 11:27:35.101 shell.go:Host() - 11.167µs
[TRACE] 11:27:35.101 shell.go:GOOS() - 0s
[DEBUG] 11:27:35.101 shell.go:Getenv:394 → 1
[TRACE] 11:27:35.101 shell.go:Getenv(SHLVL) - 1.625µs
[TRACE] 11:27:35.101 shell.go:TemplateCache() - 62.875µs
[TRACE] 11:27:35.102 shell.go:TemplateCache() - 84ns
[TRACE] 11:27:35.102 shell.go:Shell() - 41ns
[DEBUG] 11:27:35.102 block.go:Debug:230 → Segment: path
[TRACE] 11:27:35.102 shell.go:Pwd() - 125ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.102 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.102 shell.go:Shell() - 42ns
[TRACE] 11:27:35.102 shell.go:Shell() - 0s
[DEBUG] 11:27:35.102 properties.go:GetBool:22 → mapped_locations_enabled: true
[DEBUG] 11:27:35.102 properties.go:GetString:28 → 
[DEBUG] 11:27:35.102 properties.go:GetString:28 → 
[TRACE] 11:27:35.102 shell.go:GOOS() - 41ns
[DEBUG] 11:27:35.102 properties.go:GetString:28 → ~
[DEBUG] 11:27:35.102 properties.go:GetKeyValueMap:46 → mapped_locations: map[]
[TRACE] 11:27:35.102 shell.go:PathSeparator() - 42ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 41ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 0s
[TRACE] 11:27:35.102 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 0s
[TRACE] 11:27:35.102 shell.go:PathSeparator() - 0s
[TRACE] 11:27:35.102 shell.go:PathSeparator() - 42ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 0s
[TRACE] 11:27:35.102 shell.go:PathSeparator() - 41ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 83ns
[TRACE] 11:27:35.102 shell.go:PathSeparator() - 41ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 0s
[TRACE] 11:27:35.102 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.102 shell.go:PathSeparator() - 42ns
[TRACE] 11:27:35.102 shell.go:Pwd() - 41ns
[DEBUG] 11:27:35.102 shell_unix.go:IsWsl:35 → false
[TRACE] 11:27:35.102 shell_unix.go:IsWsl() - 1.959µs
[TRACE] 11:27:35.102 shell.go:StackCount() - 41ns
[TRACE] 11:27:35.102 shell_unix.go:DirIsWritable(/Users/yuanchiwang) - 16.541µs
[TRACE] 11:27:35.102 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.102 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.102 shell.go:Shell() - 42ns
[DEBUG] 11:27:35.102 block.go:Debug:230 → Segment: git
[TRACE] 11:27:35.102 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 0s
[DEBUG] 11:27:35.102 shell_unix.go:IsWsl:35 → false
[TRACE] 11:27:35.102 shell_unix.go:IsWsl() - 1.792µs
[TRACE] 11:27:35.102 shell_unix.go:IsWsl2() - 3.5µs
[TRACE] 11:27:35.102 shell.go:GOOS() - 41ns
[DEBUG] 11:27:35.102 shell.go:CommandPath:596 → /opt/homebrew/bin/git
[TRACE] 11:27:35.102 shell.go:CommandPath(git) - 45.625µs
[TRACE] 11:27:35.102 shell.go:HasCommand(git) - 52.708µs
[TRACE] 11:27:35.102 shell.go:Pwd() - 42ns
[ERROR] 11:27:35.102 shell.go:HasParentFilePath:729 → stat .git: no such file or directory
[TRACE] 11:27:35.102 shell.go:HasParentFilePath(.git) - 233µs
[DEBUG] 11:27:35.102 properties.go:GetBool:22 → fetch_bare_info: false
[DEBUG] 11:27:35.102 block.go:Debug:230 → Segment: shell
[TRACE] 11:27:35.102 shell.go:Pwd() - 83ns
[TRACE] 11:27:35.102 shell.go:GOOS() - 83ns
[DEBUG] 11:27:35.102 properties.go:GetKeyValueMap:46 → mapped_shell_names: map[bash: cmd:  pwsh: zsh:]
[TRACE] 11:27:35.102 shell.go:Shell() - 42ns
[TRACE] 11:27:35.102 shell.go:Flags() - 42ns
[TRACE] 11:27:35.102 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.102 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.102 shell.go:Shell() - 41ns
[TRACE] 11:27:35.103 shell.go:Flags() - 42ns
[DEBUG] 11:27:35.103 block.go:Debug:230 → Segment: sysinfo
[DEBUG] 11:27:35.103 properties.go:GetInt:40 → precision: 0
[TRACE] 11:27:35.103 shell.go:Pwd() - 84ns
[TRACE] 11:27:35.103 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.103 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.103 shell.go:TemplateCache() - 84ns
[TRACE] 11:27:35.104 shell.go:Shell() - 125ns
[DEBUG] 11:27:35.104 block.go:Debug:230 → Segment: connection
[TRACE] 11:27:35.104 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.104 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.104 properties.go:GetString:28 → wifi|ethernet
[DEBUG] 11:27:35.104 block.go:Debug:230 → Segment: battery
[TRACE] 11:27:35.104 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.104 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.104 shell_unix.go:IsWsl:35 → false
[TRACE] 11:27:35.104 shell_unix.go:IsWsl() - 4.75µs
[DEBUG] 11:27:35.116 shell.go:RunCommand:575 ↓
    Now drawing from 'AC Power'
     -InternalBattery-0 (id=6226019)	100%; finishing charge; 0:00 remaining present: true
[TRACE] 11:27:35.116 shell.go:RunCommand(pmset -g batt) - 12.134541ms
[TRACE] 11:27:35.116 shell_darwin.go:BatteryState() - 12.219ms
[TRACE] 11:27:35.116 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.116 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.116 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.116 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.117 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.117 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.117 shell.go:TemplateCache() - 84ns
[TRACE] 11:27:35.117 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.117 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.117 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.118 shell.go:TemplateCache() - 125ns
[TRACE] 11:27:35.118 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.118 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.118 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.118 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.119 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.120 shell.go:Shell() - 42ns
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 41ns
[DEBUG] 11:27:35.120 block.go:Debug:230 → Segment: owm
[TRACE] 11:27:35.120 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.120 shell.go:GOOS() - 41ns
[DEBUG] 11:27:35.120 properties.go:GetString:28 → metric
[DEBUG] 11:27:35.120 properties.go:GetInt:40 → cache_timeout: 60
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.120 shell.go:Shell() - 41ns
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 42ns
[TRACE] 11:27:35.120 shell.go:Flags() - 42ns
[DEBUG] 11:27:35.120 block.go:Debug:230 → Segment: time
[TRACE] 11:27:35.120 shell.go:Pwd() - 41ns
[TRACE] 11:27:35.120 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.120 properties.go:GetString:28 → 15:04:05
[TRACE] 11:27:35.120 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.121 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.121 shell.go:Shell() - 41ns
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: root
[TRACE] 11:27:35.121 shell.go:Pwd() - 0s
[TRACE] 11:27:35.121 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.121 shell_unix.go:Root() - 416ns
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: executiontime
[TRACE] 11:27:35.121 shell.go:Pwd() - 83ns
[TRACE] 11:27:35.121 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.121 properties.go:GetBool:22 → always_enabled: false
[TRACE] 11:27:35.121 shell.go:ExecutionTime() - 166ns
[DEBUG] 11:27:35.121 properties.go:GetFloat64:34 → threshold: 500.000000
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: exit
[TRACE] 11:27:35.121 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.121 shell.go:GOOS() - 42ns
[TRACE] 11:27:35.121 shell.go:ErrorCode() - 42ns
[DEBUG] 11:27:35.121 properties.go:GetBool:22 → always_enabled: true
[TRACE] 11:27:35.121 shell.go:TemplateCache() - 0s
[TRACE] 11:27:35.121 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.121 shell.go:Shell() - 41ns
[TRACE] 11:27:35.121 shell.go:TemplateCache() - 41ns
[TRACE] 11:27:35.121 shell.go:Flags() - 42ns
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: dart
[TRACE] 11:27:35.121 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.121 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → extensions: [*.dart pubspec.yaml pubspec.yml pubspec.lock]
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → folders: [.dart_tool]
[DEBUG] 11:27:35.121 properties.go:GetBool:22 → home_enabled: false
[TRACE] 11:27:35.121 shell.go:Pwd() - 42ns
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: flutter
[TRACE] 11:27:35.121 shell.go:Pwd() - 83ns
[TRACE] 11:27:35.121 shell.go:GOOS() - 0s
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → extensions: [*.dart pubspec.yaml pubspec.yml pubspec.lock]
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → folders: [.dart_tool]
[DEBUG] 11:27:35.121 properties.go:GetBool:22 → home_enabled: false
[TRACE] 11:27:35.121 shell.go:Pwd() - 42ns
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: angular
[TRACE] 11:27:35.121 shell.go:Pwd() - 42ns
[TRACE] 11:27:35.121 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → extensions: [angular.json]
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → folders: []
[DEBUG] 11:27:35.121 properties.go:GetBool:22 → home_enabled: false
[TRACE] 11:27:35.121 shell.go:Pwd() - 42ns
[DEBUG] 11:27:35.121 block.go:Debug:230 → Segment: node
[TRACE] 11:27:35.121 shell.go:Pwd() - 0s
[TRACE] 11:27:35.121 shell.go:GOOS() - 42ns
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → extensions: [*.js *.ts package.json .nvmrc pnpm-workspace.yaml .pnpmfile.cjs .npmrc .vue]
[DEBUG] 11:27:35.121 properties.go:GetStringArray:52 → folders: []
[DEBUG] 11:27:35.121 properties.go:GetBool:22 → home_enabled: false
[TRACE] 11:27:35.121 shell.go:Pwd() - 41ns
[DEBUG] 11:27:35.121 shell.go:Getenv:394 → NO DATA
[TRACE] 11:27:35.121 shell.go:Getenv(XDG_CACHE_HOME) - 2.125µs
[TRACE] 11:27:35.121 shell_unix.go:CachePath() - 40.125µs
[TRACE] 11:27:35.121 shell.go:Flags() - 42ns
```

**Comment by JanDeDobbeleer** [comment]
@LancerLucky known issue, see [here](https://ohmyposh.dev/docs/faq#after-updating-my-nerd-font-to-a-newer-version-the-prompt-displays-unknown-characters) for more info. I'm migrating everything as we speak.
