### ISSUE TITLE
install.sh for unix

### ISSUE THREAD

**Issue by Abraka** [JanDeDobbeleer/oh-my-posh#3815]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Just a little hint about documentation...when I did get through documentation and look for installation instructions I overlook maybe most important info and thats manual installation of OMP. Choosen template for documentation is nice but make you overlook subkapitols very easyli. Lol, I almost drop this nice piece of sw because that brew nonsense(nobody wants such ..beep.. io their linux), why dont you create simple install.sh which download binary and themes, you already have commands writen in docs.
Second thing is description in segments...it would by nice to have screenshot picture in every segment section to show user what its looks like when applied.

### Theme

basic

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
huh
```

**Comment by JanDeDobbeleer** [comment]
> Second thing is description in segments...it would by nice to have screenshot picture in every segment section to show user what its looks like when applied.

@Abraka that's a no-go due to a lot of work for something that's so easily validated by copy-pasting (and most likely tweaked anyways).

**Comment by JanDeDobbeleer** [comment]
#3829

**Comment by Abraka** [comment]
Just one more thing...put this install sh to top side of your doc site (linux install part), so new linux user see this as first...and just suggestion...drop that brew crazyness in linux section. Thx.

**Comment by JanDeDobbeleer** [comment]
@Abraka that's personal preference. If only the linux ecosystem had a proper cross platform package manager solution...

**Comment by Abraka** [comment]
Well, its rather simple for "one" binary sw like this. You just make .deb and .rpm package and you cover over 80% of linux world. Rest will go with install.sh or manual install. Cross platform ecos are already here...snap+flatpak...but it is the question if this is the right path/way. In any case its a lesser mess than that brew thing for sure.

**Comment by JanDeDobbeleer** [comment]
@Abraka I looked at that but documentation is terrible same as automating the ecosystem in a sustainable way. Not a fan. Homebrew is a lot more straightforward than any of the other tools looking at it from a developer experience. The easiest solution would be to install golang and install from source. Then again, it's a discussion about preferences and I'n looking at maintainability.

**Comment by Abraka** [comment]
Ok, I understand your point. Im satisfaied with possibility of manual installation, thats all. Thx.
