### ISSUE TITLE
Conflict with usage of Terminal-Icons module

### ISSUE THREAD

**Issue by jerkovicl** [JanDeDobbeleer/oh-my-posh#382]
### Prerequisites

- [x ] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

I get warning message to upgrade to v3, even if setting theme the proper way `Set-PoshPrompt -Theme  ~/.go-my-posh.json` 

### Environment

- Oh my Posh version: 3.81.0-beta
- Theme: custom theme json 
- Operating System: Win
- Shell: Powershell 7
- Terminal: WT

### Steps to Reproduce

1.  In profile include `Set-TerminalIconsColorTheme -Name DevBlackOps` for usage of Terminal-Icons module

**Expected behavior:**  No warning message

**Actual behavior:**  warning message
![image](https://user-images.githubusercontent.com/5444153/107071711-6b483c80-67e5-11eb-929e-f9013e9fff11.png)

**Comment by tradiff** [comment]
@jerkovicl Hi, I don't know much about the upgrade process from 2 to 3, but I just want to let you know that I use Terminal-Icons with oh-my-posh 3, and they normally work well together. Hope that at least gives you some re-assurance, while you wait for someone who knows more about the upgrade process.

**Comment by JanDeDobbeleer** [comment]
@jerkovicl you still have a V2 cmdlet in your `$PROFILE`, not linked to the icons are oh-my-posh, just that there's still something you did not remove just yet. See [this](https://github.com/JanDeDobbeleer/oh-my-posh3/blob/main/packages/powershell/oh-my-posh/oh-my-posh.psm1) list.

**Comment by jerkovicl** [comment]
@JanDeDobbeleer  i looked at that list but didnt see nothing i am using
```
Import-Module cd-extras
Import-Module posh-git
Import-Module oh-my-posh
Import-Module Terminal-Icons
Import-Module PSColor
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption -Colors @{ 
 InlinePrediction = '#39A3F9' 
 ListPredictionSelected = '#39A3F9'
} 
Set-PSReadLineOption -PredictionViewStyle ListView
Remove-PSReadlineKeyHandler 'Ctrl+r'
Remove-PSReadlineKeyHandler 'Ctrl+t'
Set-PoshPrompt -Theme  ~/.go-my-posh.json
Set-TerminalIconsColorTheme -Name DevBlackOps
```

**Comment by JanDeDobbeleer** [comment]
Something will be present somewhere. Not sure which one though. Might be another module with the same name cmdlet.

**Comment by jerkovicl** [comment]
@JanDeDobbeleer  as soon as i comment this line `Set-TerminalIconsColorTheme -Name DevBlackOps` warning is gone, but i want to use them both :(

**Comment by JanDeDobbeleer** [comment]
I'll check that module and remove the one that's causing it.

**Comment by jerkovicl** [comment]
ok thx

**Comment by JanDeDobbeleer** [comment]
@jerkovicl what happens when you import oh-my-posh at the end? Because I found the [culprit](https://github.com/devblackops/Terminal-Icons/blob/master/Terminal-Icons/Public/Set-TerminalIconsColorTheme.ps1) 😬

**Comment by jerkovicl** [comment]
Haha good idea but sadly that didn't help

**Comment by JanDeDobbeleer** [comment]
@jerkovicl then we'll either have to create a PR on that module to rename the function, or remove `Set-Theme` from the overrides.

**Comment by jerkovicl** [comment]
No need i will just remove that line and use the default theme for Terminal-icons.
As far as my concern I can close this issue. Thx for help figuring out the culprit.

**Comment by JanDeDobbeleer** [comment]
I'm going to fix it nonetheless. As I don't want people to be blocked. But tomorrow morning 😅
