### ISSUE TITLE
Error with foreground_templates

### ISSUE THREAD

**Issue by pwsandoval** [JanDeDobbeleer/oh-my-posh#3827]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm looking to configure oh my posh, using the robbyrussell theme and make it look the closest thing to the same theme in oh my zsh, I'm stuck with the part about displaying the initial character ➜ with a conditional color (green without errors, and red if there is something wrong with the above command), instead of the default behavior that adds a red ✗ at the end.

I first commented on this segment:

```json
// {
   // "foreground": "#E06C75",
   // "style": "plain",
   // "template": " \u2717",
   // "type": "exit"
// }
```

Then edit the property foreground_templates in

```json
{
   "foreground": "#ffffff",
   "style": "plain",
   "template": "\u279c",
   "type": "text",
   "foreground_templates": [
      "{{ if .Error }}#E06C75{{ else }}#98C379{{ end }}"
   ]
},
```

But it doesn't seem to work, as I keep seeing the leading blank character:

![Screenshot_8](https://github.com/JanDeDobbeleer/oh-my-posh/assets/15174704/95eec1da-e18c-4af2-848b-868290af4815)

With `oh-my-posh debug` I can see that the error is in the Error property:

```text
[ERROR] 22:01:29.343 text.go:Render:85 → template: {{ if .Data.Error }}#E06C75{{ end }}:1:11: executing "{{ if .Data.Error }} #E06C75{{ end }}" at <.Data.Error>: can't evaluate field Error in type template.Data
```

How can I fix that?

### Theme

robbyrussell (oh-my-posh --version 15.3.0)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
https://gist.github.com/pwsandoval/78e698c0a871012863acb8d138860a10
```

**Comment by pwsandoval** [comment]
Seems to work with

```json
"foreground_templates": [
   "{{ if gt .Code 0 }}#E06C75{{ else }}#98C379{{ end }}"
]
```
Additionally, how can I test and print the value of any of these global variables?

https://ohmyposh.dev/docs/configuration/templates

Something like "echo .Error" or "echo .Root"

**Comment by JanDeDobbeleer** [comment]
@pwsandoval this isn't a bug as the text segment doesn't have an Error property, so that'll never work.

If the property has a value, adding it to the template will print its value, so they echo by default.
