### ISSUE TITLE
Unable to use the install script for linux

### ISSUE THREAD

**Issue by bhagyajkumar** [JanDeDobbeleer/oh-my-posh#3838]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Unable to use the install script. Gives the error `x86_64 builds for linux are not available for Oh My Posh`

I was using popos.

![Screenshot from 2023-05-11 16-55-32](https://github.com/JanDeDobbeleer/oh-my-posh/assets/85674409/f6249455-8790-48c0-bed7-763fe2a94f8c)

### Theme

n/a

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
n/a
```

**Comment by LarnuUK** [comment]
Receiving the same error on Ubuntu 22.04.
