### ISSUE TITLE
Allow segments in transient prompt (only text with alignment)

### ISSUE THREAD

**Issue by ay0ks** [JanDeDobbeleer/oh-my-posh#3844]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It will be great to have multiple text segments with alignment functionality in transient prompt, so you could make exit code at the right for example, I'm not familiar with the Go language and also couldn't find where the transient prompt is implemented.

**Comment by JanDeDobbeleer** [comment]
@ay0ks this was discussed in the past but as the purpose of transient is to have a very minimal prompt, this is going against the design.

Could you share the use-case rather than the solution?

**Comment by ay0ks** [comment]
Yes, as I already said, for example usage I would like to align exit code in the transient prompt to the right, and prompt to the left.

**Comment by JanDeDobbeleer** [comment]
@ay0ks ok, well in this case the answer is no, we're not going to add that functionality. It's going against the purpose of the transient prompt.
