### ISSUE TITLE
Unable to install oh-my-posh with brew

### ISSUE THREAD

**Issue by mkraats** [JanDeDobbeleer/oh-my-posh#3849]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi,

On a Rocky Linux 9.0 machine with brew, I get the following error after "brew install jandedobbeleer/oh-my-posh/oh-my-posh":

==> Installing jandedobbeleer/oh-my-posh/oh-my-posh
==> go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=16.4.0'"
Last 15 lines from /home/mkraats/.cache/Homebrew/Logs/oh-my-posh/01.go:
go: downloading github.com/spf13/cast v1.5.0
go: downloading golang.org/x/crypto v0.8.0
go: downloading github.com/dsnet/compress v0.0.1
go: downloading github.com/jandedobbeleer/clipboard v0.1.4-1
go: downloading github.com/aymanbagabas/go-osc52/v2 v2.0.1
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading github.com/tklauser/numcpus v0.6.0
go: downloading github.com/fatih/color v1.15.0
go: downloading github.com/agext/levenshtein v1.2.3
go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.1
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/mitchellh/reflectwalk v1.0.2
go: downloading github.com/mattn/go-colorable v0.1.13
github.com/goccy/go-json/internal/encoder/vm_indent: /home/linuxbrew/.linuxbrew/Cellar/go/1.20.4/libexec/pkg/tool/linux_amd64/compile: signal: killed

After running it again I get:

==> Fetching jandedobbeleer/oh-my-posh/oh-my-posh
==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v16.4.0.tar.gz
Already downloaded: /home/mkraats/.cache/Homebrew/downloads/8092e470be47918b4010d84e290d142758ed806b1d1260699960aa723cf476e1--oh-my-posh-16.4.0.tar.gz
==> Installing oh-my-posh from jandedobbeleer/oh-my-posh
==> go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=16.4.0'"
Last 15 lines from /home/mkraats/.cache/Homebrew/Logs/oh-my-posh/01.go:
2023-05-16 10:03:24 +0000

go build -o=oh-my-posh -ldflags="-s -w -X 'main.Version=16.4.0'"

github.com/goccy/go-json/internal/encoder/vm: /home/linuxbrew/.linuxbrew/Cellar/go/1.20.4/libexec/pkg/tool/linux_amd64/compile: signal: killed

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/jandedobbeleer/homebrew-oh-my-posh/issues

### Theme

None, install time issue

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
Not possible yet, install time issue
```

**Comment by JanDeDobbeleer** [comment]
In this case the issue comes from golang itself so I'd advise to use the precompiled binary. Follow the [manual installation steps](https://ohmyposh.dev/docs/installation/linux) which executes our install script for compatible architectures.

And if that also fails, I advise to follow the extra steps when installing homebrew on Linux. These are available on the [homebrew documentation](https://docs.brew.sh/Homebrew-on-Linux#install).
