### ISSUE TITLE
macos configure

### ISSUE THREAD

**Issue by therasuldev** [JanDeDobbeleer/oh-my-posh#3886]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

How I can configure oh-my-posh for macOS terminal? in the documentation very little
 information

### Theme

macOS configure

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

cmd

### Log output

```Shell
macOS configure
```

**Comment by JanDeDobbeleer** [comment]
@therasuldev you don't configure oh-my-posh for a terminal but for a shell. So if you use zsh (now default on macOS), follow the zsh guide [here](https://ohmyposh.dev/docs/installation/prompt) after [installation](https://ohmyposh.dev/docs/installation/macos). The only thing your terminal needs, is a correct font configured.

**Comment by therasuldev** [comment]
how can I find oh-my-posh config file in Mac and edit it?  when I write `oh-my-posh config edit`  result 

> exec: no command
Thanks.

**Comment by therasuldev** [comment]
Config path is Empty why ?

> Run duration: 9.370708ms
> 
> Cache path: /Users/rasulramixanov/.cache/oh-my-posh
> 
> Config path: 
> 
> Logs:

**Comment by JanDeDobbeleer** [comment]
@therasuldev about the first one, you probably didn't set an EDITOR in your shell. And about the second, you need to [export the default config](https://ohmyposh.dev/docs/installation/customize#adjust-a-theme) first, as that's what's being used here (I can add that context though).

**Comment by JanDeDobbeleer** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/pull/3891
