### ISSUE TITLE
Mac Terminal doesn't look as good as VS Code Terminal

### ISSUE THREAD

**Issue by CoderJason123** [JanDeDobbeleer/oh-my-posh#3892]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I don't think this is a bug but rather an issue with what I'm doing.  

You can see in terminal that the nerd fonts don't line up with the powerline / etc, in mac terminal.

But in vscode it all looks great.  I'm on a mac m1, 13.4 os.  So i get the nerd font to show of course, but it's not clean.  Looked through FAQ / etc, just not sure what setting i'm missing or doing wrong.   Help appreciated.

<img width="746" alt="omp" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/33351931/a63cac45-e1b3-4662-bca1-78bff507c188">

<img width="947" alt="ompvscode" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/33351931/ec7ed79c-35e4-4e2b-b52a-47bd5446d557">

### Theme

JanDeDobbeleer

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
no logs of value on this
```

**Comment by CoderJason123** [comment]
I am noticing, I was using one of the recommended fonts, Fira.  When I changed to another recommended font, Meslo, things lined up a bit better.    there are so many meslo i'm not sure which one to use, but maybe this is just that the symbols in Fira are not sized to the proper height? I'm not saying that that is it, but more or less asking if that type of thing is possible or I just have my terminal configured wrong.   Yes, i'm using the default mac terminal at this moment.

**Comment by JanDeDobbeleer** [comment]
@CoderJason123 this is a terminal font rendering or settings issue. You can try playing around with line height and other rendering settings. All in all, I wouldn't advise Terminal on macOS and move to iTerm as it can't handle true color as well. It's a crappy terminal.

**Comment by awdr74100** [comment]
Seems the same problem will happen with iTerm? Windows Terminal doesn't have this problem and works just as well as VSCode Terminal.

@JanDeDobbeleer any help you can offer would be greatly appreciated!

![截圖 2023-06-28 下午4 56 05](https://github.com/JanDeDobbeleer/oh-my-posh/assets/47501692/b77091b2-8c9f-4d32-b1fc-ae1e5149fce2)

**Comment by JanDeDobbeleer** [comment]
@awdr74100 it depends on the font size sometimes. In my case I have to set this to 13 to avoid having those lines. But I noticed it's different per font used.
