### ISSUE TITLE
oh-my-posh font install      failed to get nerd fonts release

### ISSUE THREAD

**Issue by maximunited** [JanDeDobbeleer/oh-my-posh#3897]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Try downloading fonts behind a proxy

### Theme

default

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

cmd

### Log output

```Shell
>oh-my-posh font install

    failed to get nerd fonts release
```

```
>oh-my-posh debug --plain

Version: 16.8.0

Shell: oh-my-posh

Segments:

ConsoleTitle(true)                        -   1 ms - oh-my-posh in alter
session(true)                             -   0 ms -  alter
path(true)                                -   1 ms -   ~
git(false)                                -  35 ms -
root(true)                                -   0 ms -  
exit(true)                                -   0 ms -  
node(false)                               -   0 ms -
go(false)                                 -   0 ms -
python(false)                             -   0 ms -
shell(true)                               -   0 ms - in oh-my-posh
time(true)                                -   0 ms - at 16:08:42

Run duration: 57.4257ms
```
```

**Comment by JanDeDobbeleer** [comment]
@maximunited are you able to reach GitHub from the proxy? It tries to call the following endpoint `https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest`

**Comment by maximunited** [comment]
Yes I can. For example, I'm using `scoop`, and I had to manually configure it to use proxy to make it work.

**Comment by JanDeDobbeleer** [comment]
@maximunited unfortunately we have no way to configure a proxy, and I'm pretty sure this breaks segments as well. Will give it a thought, but it's going to be a though nut if we can't simply bypass it.
