### ISSUE TITLE
Can't install fonts using oh-my-posh

### ISSUE THREAD

**Issue by xmha97** [JanDeDobbeleer/oh-my-posh#3903]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi, I can't install fonts without admin permission.
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/23485114/e5c6bfb0-0746-4b1f-b571-1ceb60983c07)
On Windows 10 and 11, users can install fonts without admin permission.
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/23485114/e42edef8-d57d-4338-97bc-91f7567bb22a)
Fonts path of all users: `%WINDIR%\Fonts`
Fonts path of the current user: `%LOCALAPPDATA%\Microsoft\Windows\Fonts`
Also, users can install nerd fonts using [scoop](https://scoop.sh/) without admin permission:
```
scoop bucket add nerd-fonts
```
```
scoop install Meslo-NF
```
Please write this on the oh-my-posh site: https://ohmyposh.dev/docs/installation/fonts

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@xmha97 unfortunately this is required as some configurations do not work correctly unless you install for all users (thus as admin).

**Comment by xmha97** [comment]
Ok, so write about the scoop method on the oh-my-posh website.

**Comment by JanDeDobbeleer** [comment]
@xmha97 as I said, installing as non-admin has side effects so it's not at all advised. Therefore I'm also not adding that as an option. Walking off the beaten path is ones own responsibility.

**Comment by xmha97** [comment]
Ok, thanks for your explanation.
