### ISSUE TITLE
When manually activating a theme oh-my-posh tries to remove-module itself

### ISSUE THREAD

**Issue by GAZelenka** [JanDeDobbeleer/oh-my-posh#3909]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When Powershell starts, the selected theme activates correctly, but when I manually activate a theme using:
`oh-my-posh init pwsh --config "$env:POSH_THEMES_PATH/theme.omp.json" | Invoke-Expression`
I receive the following errors/notifications:
`What if: Performing the operation "Remove-Module" on target "oh-my-posh-core (Path: 'C:\Users\UserName\Downloads\GitHub\VSCode\PowerShell\e8688299-b133-4eb7-8e2c-08058409452a')".
Remove-Module: 
Line |
   3 |      Remove-Module -Name "oh-my-posh-core" -Force
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No modules were removed. Verify that the specification of modules to remove is correct and those modules exist in the runspace.`
I receive the error when $WhatIfPrefernce = $False as well and the string after the \PowerShell\ folder changes on each attempt. 
I've fully uninstalled oh-my-posh and deleted all of the associated folders and then reinstalled using winget but the issue recurred.
Sometime some themes can be manually activated, but at currently none of them can.
Any help you can provide in resolving this issue would be appreciated.
Thanks.

### Theme

Varies, currently none are working but often devious-diamonds.omp.yaml causes an issue.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

(Log output removed as it's not relevant to this issue)

**Comment by JanDeDobbeleer** [comment]
> but when I manually activate a theme

@GAZelenka you could reload the entire script, which is why the module remove itself and re-registers (this is necessary) but that's not how to change themes. You can simply adjust the `POSH_THEME` environment variable.

```powershell
$env:POSH_THEME="$env:POSH_THEMES_PATH/theme.omp.json"
```

I'll adjust the docs to also include this.

**Comment by GAZelenka** [comment]
Thanks, @JanDeDobbeleer, updating the variable as indicated works perfectly. Thanks for your help.
