### ISSUE TITLE
Weird caret paint issues on latest OMP version on Windows Terminal Preview 1.18.1421.0

### ISSUE THREAD

**Issue by rkeithhill-keysight** [JanDeDobbeleer/oh-my-posh#3911]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I updated to the latest version of Windows Terminal Preview announced at Microsoft Build. I also updated OMP to `16.9.0`. Things work until I do a `cls` to clear the screen.  Then none of the OMP Segments appear.  And when I type, I see the caret move but leave previous caret artifacts on the screen. And I can't see any of the characters I type.  If I switch WT tabs, everything comes back correct.  Even if I try to do a screenshot, that causes the prompt and entered text to display correctly. 

I'm not currently experiencing the issue because I downgraded to OMP `10.1.0`. I noticed I wasn't seeing this issue on another machine where I upgraded WTP to 1.18.1421.  It was running `10.1.0`.  This may be a WT issue.  I saw in a blog post they have turned on a new text rendering engine called `Atlas`.  But it is only OMP that causes these artifacts on my machines.  Here's a link to that [blog post](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-18-release/)

### Theme

Custom theme.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
I've already reset to 10.1.0 and it doesn't recognize that command.
```

**Comment by JanDeDobbeleer** [comment]
I've seen that as well, but that's a Windows Terminal bug in the latest preview. This doesn't happen in the non-preview version or anywhere else.

**Comment by JanDeDobbeleer** [comment]
@rkeithhill-keysight https://github.com/microsoft/terminal/issues/15460
