### ISSUE TITLE
Add ability to display current kubernetes namespace

### ISSUE THREAD

**Issue by andrewsav-bt** [JanDeDobbeleer/oh-my-posh#392]
### Description

I would like to be able to include the name of the current kubernetes namespace into a segment.

See <https://stackoverflow.com/a/55854690> for a kubectl command to get the namespace, but I'm sure that go client api also can do that.

**Comment by tradiff** [comment]
I can work on this today after work. A few questions:
1. @andrewsav-bt If the user has not set a namespace, should the return value be "default"?
2. @JanDeDobbeleer I'm thinking this would be part of the [kubectl segment](https://ohmyposh.dev/docs/kubectl/), and it would work similar to the [azure segment](https://ohmyposh.dev/docs/az). Do you agree with this approach?
    1. Add `DisplayContext` (boolean) defaults to true
    1. Add `DisplayNamespace` (boolean) defaults to false
    2. Add `InfoSeparator` (string)

**Comment by JanDeDobbeleer** [comment]
@TravisTX I would opt to go for templates rather than the `InfoSeparator`, I should finish up the `aws` segment (#387) in that case as that contains a generic way to use templates in segments. All I need to do is add the tests, functionality is validated.

**Comment by JanDeDobbeleer** [comment]
@TravisTX merged #387, will extend the tests later, basic functionality is there.

**Comment by andrewsav-bt** [comment]
> @andrewsav-bt If the user has not set a namespace, should the return value be "default"?

As far as understand when you run any `kubectl` namespaced command, such as `get pod` it will always return data from a single namespace when you do not specify any switches that affect this behaviour. This is the namespace I would expect to be returned. Many thanks.

**Comment by andrewsav-bt** [comment]
Thank you everyone who helped making it happen!

**Comment by alecor191** [comment]
I can't seem to get namespaces to be shown, so I'm wondering if I'm missing something:

- I understand from the [release notes](https://github.com/JanDeDobbeleer/oh-my-posh3/releases/tag/v3.85.0), that support for namespaces was released in 3.85
- I'm currently using 3.87:

```shell
❯ get-module oh-my-posh

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.87.0     beta       oh-my-posh                          {Get-PoshInfoForV2Users, Get-PoshThemes, Set-PoshPrompt, Write-PoshTheme…}
```

- My Kubectl segment config looks as follows:

```json
{
    "type": "kubectl",
    "style": "diamond",
    "foreground": "#FFFFFF",
    "background": "#2A67E5",
    "leading_diamond": " \uE0B6",
    "trailing_diamond": "\uE0B4 ",
    "properties": {
        "prefix": "\uFD31 ",
        "template": "{{.Context}} :: {{if .Namespace}}{{.Namespace}}{{else}}default{{end}}",
        "display_error": true
    }
},
```

- Default namespace is set in `kubectl`

```shell
❯ kubectl config view --minify --output "jsonpath={..current-context},{..namespace}"
test-cluster,my-test-namespace
```

I also tried to remove the `template` property from my kubectl segment as I understand that by default it should now also show the namespace, but it didn't help. I always just get the name of the context printed by oh-my-posh.

I'm using PowerShell 7.1.2 inside Windows Terminal 1.5.10411.0.

Am I missing something?

**Comment by JanDeDobbeleer** [comment]
@TravisTX care to take a look?

**Comment by tradiff** [comment]
@alecor191 everything looks correct to me. Just to be sure, I have copied your config as well as your context and namespace names and confirmed, I do indeed see "my-test-namespace".

The behavior sounds like OMP is actually running on an older version of OMP. Maybe go to your modules folder and delete any older versions to confirm that's not what's going on. @JanDeDobbeleer you have any other ideas about that? I typically don't run from the public powershell module (although I did just now install it, to confirm the kubectl segment works as expected with that method)

**Comment by JanDeDobbeleer** [comment]
No, same thoughts. Couldn't see an issue either.

**Comment by alecor191** [comment]
Thanks a lot @TravisTX  and @JanDeDobbeleer for your super-fast replies. That was it: While I did uninstall all previous versions, even reboot PC before posting my message, it turned out that I still had an old OMP executable around that got picked up when calling `oh-my-posh --init -shell pwsh ...`. 

Deleting that old file and using `Set-PoshPrompt` instead of the command above, resolved the issue.

Thanks for your help!
