### ISSUE TITLE
Failed to apply theme on Ubuntu WSL

### ISSUE THREAD

**Issue by Descalon** [JanDeDobbeleer/oh-my-posh#393]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Running `Set-PoshPrompt -Theme <any theme>` results in an error

### Environment

- Oh my Posh version: 3.83.0-beta
- Theme: any
- Operating System: Ubuntu 20.04 (WSL)
- Shell: Powershell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Install oh-my-posh
2. run `Set-PoshPrompt` cmdlet

**Expected behavior:** 
That the theme is applied

**Actual behavior:** 
Error in `posh-linux-amd64`:
```
ResourceUnavailable: /home/descalon/.local/share/powershell/Modules/oh-my-posh/3.83.0/oh-my-posh.psm1:69
Line |
  69 |      Invoke-Expression (& $poshCommand --init --shell=pwsh --config="$ …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'posh-linux-amd64' failed to run: No such file or directoryAt
     | /home/descalon/.local/share/powershell/Modules/oh-my-posh/3.83.0/oh-my-posh.psm1:69 char:24 + …
     | ke-Expression (& $poshCommand --init --shell=pwsh --config="$config") +
     | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
```
![issuereport](https://user-images.githubusercontent.com/1098500/107490316-05173d00-6b8a-11eb-9b02-de43ace9ff5f.png)

**Comment by JanDeDobbeleer** [comment]
@Descalon thx, that's actually a bug 🙏🏻

**Comment by andrewsav-bt** [comment]
This may be entirely unrelated but when I try the steps above I do not just get the error, I also get a lot of gibberish:
 
![WindowsTerminal_JHi83nukIy](https://user-images.githubusercontent.com/27190911/107588783-682bd100-6c69-11eb-98bb-e0a26351c3b3.png)

In my case this is not WSL but an ssh session into an Ubuntu 20.04 VM.

**Comment by JanDeDobbeleer** [comment]
No, that's for sure going to be related. I'll check. Maybe the recent change in setting the executable is causing this.

**Comment by ielcoro** [comment]
This error is still present in version 3.94.4:

`
ResourceUnavailable: /root/.local/share/powershell/Modules/oh-my-posh/3.94.4/oh-my-posh.psm1:89
Line |
  89 |          & $poshCommand -config $($_.FullName) -pwd $PWD
     |                                   ~~~~~~~~~~~
     | Program 'posh-linux-amd64' failed to run: No such file or directoryAt
     | /root/.local/share/powershell/Modules/oh-my-posh/3.94.4/oh-my-posh.psm1:89 char:9 +         & $poshCommand
     | -config $($_.FullName) -pwd $PWD +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
`

**Environment**

- Oh my Posh version: 3.94.4
- Theme: any
- Operating System: Alpine 3.18.2 (Docker WSL Backend 20.10.2 )
- Shell: Powershell 7 Linux
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
Probably depends on the WSL OS too based on the way it checks for executable permissions. I'll revert that change altogether.

**Comment by JanDeDobbeleer** [comment]
@ielcoro can you check again by updating the module and restarting your shell?
