### ISSUE TITLE
Linux arm binary nil pointer 

### ISSUE THREAD

**Issue by Ash258** [JanDeDobbeleer/oh-my-posh#394]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Since 3.80.1 arm binary is producing `oh-my-posh fatal error rendering git segment:runtime error: invalid memory address or nil pointer dereference `

### Environment

- Oh my Posh version: 3.80.1, ..., 3.84.0
- Theme: https://github.com/Ash258/Scoop-Ash258/blob/master/support/oh-my-posh/Ash258.json
- Operating System: Linux raspberry 5.8.0-1015-raspi #18-Ubuntu SMP PREEMPT Fri Feb 5 06:09:58 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
- Shell: zsh 5.8
- Terminal: Vscode, Windows Terminal

### Steps to Reproduce

1. Download binary for linux arm
2. Use any theme 
3. See error

**Expected behavior:** [What you expected to happen]

![image](https://user-images.githubusercontent.com/13260377/107552494-e0e04e00-6bd3-11eb-960d-42f531f9db14.png)

**Actual behavior:** [What actually happened]

![image](https://user-images.githubusercontent.com/13260377/107553021-8398cc80-6bd4-11eb-933e-fe2122b5d3ef.png)

**Comment by JanDeDobbeleer** [comment]
@Ash258 does this happen all the time or only when running `--version`? As I can see a prompt that's rendered, so I'm confused.

**Comment by Ash258** [comment]
All the time. Prompt is rendered but git and kubectl segments show error and before every prompt there are lots of random characters and %{

**Comment by JanDeDobbeleer** [comment]
It's almost as if there are two invocations of oh-my-posh, one that's correct (the last) and one with an incorrect config (the first). I'll try to reproduce, a nil pointer should show on my machine as well, that's unrelated to arm.

**Comment by Ash258** [comment]
Invocation of oh-my-posh is only one:

```shell
arch=$(uname -m)
case $arch in
        'x86_64') bitness='64bit';;
        'i386') bitness='32bit';;
        'aarch64') bitness='arm64';;
        *) bitness='arm32' ;;

esac
export __SHELL_INFORMATION_POSH_258__="zsh@$ZSH_VERSION@$bitness"
eval "$(oh-my-posh --init --shell zsh --config '/var/Ash258.omp.json')"
#endregion Oh-my-posh
```

As soon as the binary is updated the terminal goes mad:

![image](https://user-images.githubusercontent.com/13260377/107608703-fc337380-6c3c-11eb-8a5b-f78b8e8f3da6.png)

With debug:

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ce8]

goroutine 1 [running]:
runtime/internal/atomic.goLoad64(0xd162ac, 0x2, 0x8)
        /opt/hostedtoolcache/go/1.15.7/x64/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/xaionaro-go/atomicmap.(*openAddressGrowingMap).BusySlots(...)
        /home/runner/go/pkg/mod/github.com/xaionaro-go/atomicmap@v0.0.0-20200307233044-c040bc137895/open_growing_map.go:669
github.com/xaionaro-go/atomicmap.(*openAddressGrowingMap).Get(0xd162a0, 0x382618, 0x119c370, 0x32b6d4, 0x6024d2c9, 0x0, 0xb077102)
        /home/runner/go/pkg/mod/github.com/xaionaro-go/atomicmap@v0.0.0-20200307233044-c040bc137895/open_growing_map.go:432 +0x168
main.(*environment).hasCommand(0x1196010, 0x3d0bba, 0x3, 0x6542e8)
        /home/runner/work/oh-my-posh3/oh-my-posh3/src/environment.go:188 +0x3c
main.(*git).enabled(0x1197810, 0xc0015292)
        /home/runner/work/oh-my-posh3/oh-my-posh3/src/segment_git.go:118 +0x38
main.(*Segment).enabled(...)
        /home/runner/work/oh-my-posh3/oh-my-posh3/src/segment.go:98
main.(*engine).debug(0x11a4060)
        /home/runner/work/oh-my-posh3/oh-my-posh3/src/engine.go:205 +0x234
main.main()
        /home/runner/work/oh-my-posh3/oh-my-posh3/src/main.go:157 +0x690
oh-my-posh fatal error rendering git segment:runtime error: invalid memory address or nil pointer dereference
%{%}%{%}%{%}█%{%}%{%} %{%}%{%}ubuntu%{%}%{%}@%{%}%{%}raspberry%{%}%{%}█%{%}%{%}%{%}%{%}%{%}%{%}  ~%{%}%{%}█%{%}%{%}%{%}%{%}█%{%}%{%}error%{%}%{%}█%{%}%{%}%{%}%{%}█%{%}%{%}100 %{%}%{%}%{%}%{%} ﲵ zsh%{%}%{%}█%{%}%{%}%{%}%{%}█%{%}%{%}NO CONFIG%{%}%{%}█%{%}%{%}%{%}%{%}%{%}%{%} %{%}%{%}█%{%}%{%}%{%}%{%}%{%} oh-my-posh fatal error rendering git segment:runtime error: invalid memory address or nil pointer dereference
%{%}%{%}%{%}█%{%}%{%} %{%}%{%}ubuntu%{%}%{%}@%{%}%{%}raspberry%{%}%{%}█%{%}%{%}%{%}%{%}%{%}%{%}  ~%{%}%{%}█%{%}%{%}%{%}%{%}█%{%}%{%}error%{%}%{%}█%{%}%{%}%{%}%{%}█%{%}%{%}100 %{%}%{%}%{%}%{%} ﲵ zsh%{%}%{%}█%{%}%{%}%{%}%{%}█%{%}%{%
```

**Comment by JanDeDobbeleer** [comment]
That's exactly what I need, thanks!!
