### ISSUE TITLE
INVALID CONFIG using custom theme

### ISSUE THREAD

**Issue by afucher** [JanDeDobbeleer/oh-my-posh#395]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
I follow the instructions in the getting started and created a custom theme file with the content from the site. When I try to use it, it shows INVALID CONFIG message and doesn't work.

### Environment

- Oh my Posh version: 3.84.0
- Theme: trying a custom
- Operating System: Windows 10
- Shell: PowerShell
- Terminal: Windows terminal

### Steps to Reproduce

1. Created a file ` ~/.mytheme.omp.json`
2. Added the content from the site
```
       {
    "final_space": true,
    "blocks": [
        {
        "type": "prompt",
        "alignment": "left",
        "segments": [
            {
            "type": "path",
            "style": "powerline",
            "powerline_symbol": "\uE0B0",
            "foreground": "#ffffff",
            "background": "#61AFEF",
            "properties": {
                "prefix": " \uE5FF ",
                "style": "folder"
            }
            }
        ]
        }
    ]
}
```
3. Changed my profile to set the theme adding this: `Set-PoshPrompt -Theme ~/.mytheme.omp.json`
4. Loaded profile `. $profile`

**Expected behavior:** See PowerShell with this new customized theme

**Actual behavior:** It shows a message in the terminal with INVALID CONFIG
![image](https://user-images.githubusercontent.com/3756185/107558944-2d1e9480-6bba-11eb-8d34-c14ba2fadd61.png)

**Comment by tradiff** [comment]
That error typically means you have invalid json.  However, what you pasted seems valid.  I tested it here:

![image](https://user-images.githubusercontent.com/934490/107573576-effed600-6baa-11eb-93b4-5db1ed0e89c8.png)

Are you sure the file at `~/.mytheme.omp.json` is what you pasted?  Maybe try putting in the exact path instead of ~ to be sure.  Sorry I can't think of any other ideas at the moment.

**Comment by afucher** [comment]
For some reason it is not understanding `~`  :/ 

I changed for the absolute path and it works, thanks!
