### ISSUE TITLE
[Feature] execution time alignment

### ISSUE THREAD

**Issue by nopeless** [JanDeDobbeleer/oh-my-posh#3970]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Execution times are hard to read and have inconsistent width

Proposal has 4 changes 
- execution time will always be 7 characters long
- decimal point will be at the same location
- seconds and milliseconds will be aligned
- [m, s] and [h, m] will be aligned

before
```
1.123s
20.123s
110ms
10ms
1ms
```

after
```
 1.12s 
20.12s 
  110ms
   10ms
    1ms

---
for durations longer than 1 minute

 1m  1s
60m 60s
 1h  1m
24h 60m
```

Rationale: 
- for sub 1 minute executions, comparing execution speeds is easier
- for subsequent command executions (especially when -q flag is present), the output is cleaner as the status doesn't change width

---

I am willing to submit a PR for this

**Comment by JanDeDobbeleer** [comment]
@nopeless this should be an option as it's about taste imho. Which [style](https://ohmyposh.dev/docs/segments/executiontime#style) would you apply this to?

**Comment by nopeless** [comment]
@JanDeDobbeleer I was thinking about updating `austin` as that is what I currently use, but introducing a new format called `constant width` or some quirky name relating to 7 e.g. `lucky7` `7chars` also works

**Comment by JanDeDobbeleer** [comment]
@nopeless I like lucky7, let's go for it 😄
