### ISSUE TITLE
Console Title: show currently running cmdline, until it finishes

### ISSUE THREAD

**Issue by RaffaeleBianc0** [JanDeDobbeleer/oh-my-posh#3971]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Ciao!
It would be nice to have the currently running command in the Console Title, until it has finished.
Something like these new parameters for the configuration:
- {{.Running_1st}} to get only the 1st word of the last command line entered
- {{.Running_full}} to get the full command line entered
The tag could also be prefixed with a "running" icon, like the ⏳.

Example:
- Command: 7-zip a -mx9 test.7z C:\temp\my\folder\*
- {{.Running_1st}} = ⏳ 7-zip
- {{.Running_full}} = ⏳ 7-zip a -mx9 test.7z C:\temp\my\folder\*
When 7-zip finishes, then the {{.Running}} tags become empty.

This feature would help when using multiple Windows Terminal tabs to run long tasks, IMHO.

**Comment by JanDeDobbeleer** [comment]
@RaffaeleBianc0 this feature request is beyond the scope of the project. The reason I make that statement is that we don't execute logic on enter other than the transient prompt. The title is only rendered after the command executed and the shell wants to display the prompt. You can add this for yourself by playing with the shell's built-in hooks.
