### ISSUE TITLE
Repo Review Badge

### ISSUE THREAD

**Issue by repo-reviews** [JanDeDobbeleer/oh-my-posh#3985]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Thank you for building **oh-my-posh**!

I created a review titled:

*oh-my-posh review*

on [repo-reviews.github.io](https://repo-reviews.github.io) to share my experience using **oh-my-posh**.

[link to review](https://repo-reviews.github.io//reviews/2023-06-21_TameWizard_JanDeDobbeleer_oh-my-posh)

If you would like to help your users share their experiences using your repo, add a [badge](https://github.com/repo-reviews/repo-reviews.github.io#add-badges) to your README.md.

I hope these learnings help your users **increase their productivity**.

--
Please be kind,
I’m a human!

**Comment by JanDeDobbeleer** [comment]
Love the review. If I get this right you only started out with the repo-reviews project (1 week). Would love to add the review to our README so I'll go ahead and do that.

**Comment by repo-reviews** [comment]
Thanks!  Yes, it's a new project- we'd love any help socializing its value!

@TameWizard, great review 🚀
