### ISSUE TITLE
Segment Path does not work with Windows Registry

### ISSUE THREAD

**Issue by akselkvitberg** [JanDeDobbeleer/oh-my-posh#40]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When navigating to the registry, the path segment does not show the registry path.
Oh-my-posh3:
![image](https://user-images.githubusercontent.com/5091899/95437251-12f75000-0955-11eb-8148-f2c931e4abe8.png)
Default behavior:
![image](https://user-images.githubusercontent.com/5091899/95437634-8305d600-0955-11eb-8460-28e0c37c5fd0.png)

### Environment

- Oh my Posh version: 3.8.0
- Operating System: Windows 10 2004
- Shell: Powershell 7
- Terminal: Windows Terminal

### Steps to Reproduce

1. Open Powershell
2. Go to the registry, by typing cd HKLM:

**Expected behavior:** Expected path segment to show: HKLM:\

**Actual behavior:** Previous path is displayed

**Comment by JanDeDobbeleer** [comment]
Clear, I'll have to debug that on Windows. In theory this should work, but clearly something is off.

**Comment by JanDeDobbeleer** [comment]
Well. That was annoying but I have a fix.

```go
package main

import (
	"fmt"
	"os"
	"syscall"
)

func main() {
	dir, _ := os.Getwd()
	fmt.Printf("Getwd: %s\n", dir)
	fmt.Printf("$PWD: %s\n", os.Getenv("PWD"))
	dir, _ = syscall.Getwd()
	fmt.Printf("syscall.Getwd: %s\n", dir)
}
```

<img width="203" alt="image" src="https://user-images.githubusercontent.com/2492783/95491498-f6313b80-0999-11eb-9d4f-e010f2c254ce.png">

Basically I can set the env var from PowerShell as there's no way Go can know you're in that location.

**Comment by JanDeDobbeleer** [comment]
I'm going to test this manually one more time with a fresh pair of eyes tomorrow morning.
