### ISSUE TITLE
If a segment produces a error hide the segment

### ISSUE THREAD

**Issue by andrewsav-bt** [JanDeDobbeleer/oh-my-posh#400]
I've seen errors in segments such as kubernetes (no kubeconfig) and python (old unsupported version). Instead of springing the error on the user, I would like a property on a segment to allow to hide the segment on error. In scenarios when debugging is required or if a user prefer to see the error in the segment the property can be flipped.

The idea behind this request is that a single theme may be  shared/used in multiple heterogenous environments, and provides the best experience possible, despite differences in the environments.

**Comment by tradiff** [comment]
Rather than being in each segment, I propose a single global `display_errors` boolean property at the same level as `final_space`.

```jsonc
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh3/main/themes/schema.json",
  "final_space": true,
  "display_errors": true, //  ← new property
  "blocks": [
  ]
}
```

Regardless of the scope of the new property, I can work on this, if nobody else has started on it yet.

**Comment by AndrewSav** [comment]
@TravisTX  For my current needs a single one will suit well. But I wonder what is the motivation of having a single one? Being able to configure it on the segment level seems more flexible? (E.g. if root detection fails, I'd rather know about it that assume I'm not a root) What are drawback?

**Comment by JanDeDobbeleer** [comment]
I agree with @AndrewSav on this one. Btw, the battery segment already has a property like that.

**Comment by AndrewSav** [comment]
@JanDeDobbeleer @TravisTX  what about python?

**Comment by JanDeDobbeleer** [comment]
@AndrewSav when it comes to languages that needs to be added for all as they share the same base. Can be done, just more docs work 😅

**Comment by AndrewSav** [comment]
@JanDeDobbeleer should I open a separate issue to track that, or should we re-open this one? It sounds to me like there is some more work to be done here.

**Comment by JanDeDobbeleer** [comment]
Reopening is fine for me. Bit silly to rewrite everything 😅

**Comment by AndrewSav** [comment]
@JanDeDobbeleer Thanks. Could you re-open, please?
