### ISSUE TITLE
[Dev/CI] prefer yarn ecosystem over npm

### ISSUE THREAD

**Issue by nopeless** [JanDeDobbeleer/oh-my-posh#4002]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I'd like to hear what your opinion is about this before making a PR

I think it is better for the entire project to use yarn (or npm, but npm has a lot of issues in my opinion)

Currently, `website/README.md` says `yarn install` for development, but github workflow uses npm.

I see that `npm install` for the workflow has `--legacy-peer-deps` flag, which probably means swapping the install command with `yarn install --immutable --immutable-cache --check-cache` might cause issues.

**Comment by JanDeDobbeleer** [comment]
It should be all npm. So we can adjust towards that in the docs.
