### ISSUE TITLE
language_test / .Mismatch wrong if .nvmrc isn't fully qualified

### ISSUE THREAD

**Issue by jonaskuske** [JanDeDobbeleer/oh-my-posh#4009]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When `.nvmrc` contains just *18*, `.Mismatch` should be `false` for all `18.x` Node versions. Currently my prompt is red indicating a version mismatch despite using Node v18.16.0 in a repo that specifies *18* in its `.nvmrc`

(feels like a bug but could also be framed as a feature request, I guess?)

### Theme

-

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

powershell, zsh

### Log output

```Shell
-
```

**Comment by JanDeDobbeleer** [comment]
@jonaskuske this is only true when it specifies a major version, right (so, no dots)?

**Comment by jonaskuske** [comment]
@JanDeDobbeleer Ah sorry, turns out everything is working in my WSL setup, including just the major as specifier. The issue is that OMP always reports a Mismatch in my Windows/PowerShell setup, even with "18.16.0" in `.nvmrc`. Will investigate and potentially open another issue.
