### ISSUE TITLE
version idea

### ISSUE THREAD

**Issue by yveshanoulle** [JanDeDobbeleer/oh-my-posh#4014]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

oh-my-posh --version
now returns 17.5.3

It would be interesting if it also tells us the current latest version. 

or add the creation date of the installed version
so

 Version 17.5.3 Version date:2023-06-30

**Comment by JanDeDobbeleer** [comment]
@yveshanoulle created date is possible, and the cleanest solution.

**Comment by yveshanoulle** [comment]
where can I find how this now works?
I upgraded to 17.6.0 assuming it was there, I don't see a date

**Comment by JanDeDobbeleer** [comment]
@yveshanoulle you need to use `oh-my-posh version -v`

**Comment by 0323pin** [comment]
Something fishy with this, on my system the outputs are empty as of 17.6.0

![2023-07-04-062422_632x342_scrot](https://github.com/JanDeDobbeleer/oh-my-posh/assets/90570748/d8875a5d-e8a2-4690-9b83-efffbbd20675)

I will look into what changed.

**EDIT:** Should add that I was the one updating the NetBSD package yesterday.
This use to work previously. Although, we did `sed` the information into `main.go` at build time,
```
SUBST_CLASSES+=		version
SUBST_STAGE.version=	do-configure
SUBST_FILES.version=	main.go
SUBST_SED.version=	-e 's|"development"|"${PKGVERSION_NOREV}"|'
```

But, now there's no variable to replace there.

**Comment by JanDeDobbeleer** [comment]
@0323pin you'll need to adjust the build parameters to populate the correct variables. They moved to [build/version.go](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/build/version.go). That said, I would use the correct way to populate those at build time:

```
go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=17.6.0' -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2023-07-02T19:18:10Z'"
```

**Comment by 0323pin** [comment]
@JanDeDobbeleer Thanks, I've used your `-ldflags` suggestion to fix the version output.

As for the date, I would prefer if it could be fetched from the source and not declared in the package Makefile.
![2023-07-04-100959_715x360_scrot](https://github.com/JanDeDobbeleer/oh-my-posh/assets/90570748/a2df38d7-f78d-4d4d-a857-49d35b5332e2)

**Comment by JanDeDobbeleer** [comment]
@0323pin you can fetch the commit date and format it correctly. Although I'd argue that it's incorrect. It would help me to understand if we or someone else built this.

**Comment by 0323pin** [comment]
@JanDeDobbeleer 

> you can fetch the commit date and format it

I'll look into this later, thanks. 

> Although I'd argue that it's incorrect. It would help me to understand if we or someone else built this.

We build the package from source for the different pkgsrc supported targets. See the package contents [here](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/shells/oh-my-posh/)

I haven't pushed the last change yet.

**EDIT:** 
> help me to understand if we or someone else built this

I've built the binary used in the screenshot locally on my machine using pkgsrc framework on NetBSD-current (development branch).

**Comment by JanDeDobbeleer** [comment]
@0323pin yes, and that's perfectly fine. You can opt to use the timestamp of the moment you build that package. In fact, that's what our homebrew formula does as well.

**Comment by 0323pin** [comment]
I've fixed the version for now and pushed the change into the main branch.
Here's the Makefile,

```
# $NetBSD: Makefile,v 1.38 2023/07/04 15:49:57 pin Exp $

DISTNAME=		oh-my-posh-17.6.0
CATEGORIES=		shells
MASTER_SITES=		${MASTER_SITE_GITHUB:=JanDeDobbeleer/}
GITHUB_TAG=		v${PKGVERSION_NOREV}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		https://ohmyposh.dev/
COMMENT=		Prompt theme engine for any shell
LICENSE=		mit

WRKSRC=			${WRKDIR}/${DISTNAME}/src

USE_LANGUAGES=		c

INSTALLATION_DIRS=	share/${PKGBASE}

GO_BUILD_PATTERN=	-ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=${PKGVERSION_NOREV}'" ./...

post-build:
	${MV} ${WRKDIR}/.gopath/bin/src ${WRKDIR}/.gopath/bin/oh-my-posh

post-install:
	cd ${WRKDIR}/${DISTNAME}/themes &&				\
	for f in *.json *.yaml; do					\
	  ${INSTALL_DATA} $$f ${DESTDIR}${PREFIX}/share/${PKGBASE};	\
	done

.include "go-modules.mk"
.include "../../lang/go/go-module.mk"
.include "../../mk/bsd.pkg.mk"
```

I think the build date would be ok. Thank you for your time.

**Comment by 0323pin** [comment]
@JanDeDobbeleer Just FYI, I've fully fixed the output of `oh-my-posh version -v` now :)
(see screenshot with the Makefile diff and the current output)

![2023-07-05-101220_1338x734_scrot](https://github.com/JanDeDobbeleer/oh-my-posh/assets/90570748/796123a4-3cf7-4a5d-8b23-3c00fb97b4fe)

Will make some minor adjustments and include it on the next release package.
Let me know if would prefer to have hours and minutes as well.
Regards

**Comment by JanDeDobbeleer** [comment]
@0323pin this is perfect!

**Comment by 0323pin** [comment]
@JanDeDobbeleer Hope you don't mind one last question.

I'm working on simplifying the package Makefile and was wondering about the following,
You wrote that I should use:
`go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=17.6.0' -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2023-07-02T19:18:10Z'"`

I've been reading about ldflags and Go and was wondering if writing just:
`go build -o=oh-my-posh -ldflags="-X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=17.6.0' -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2023-07-02T19:18:10Z'" `

would be wrong? I'm failing to see the impact, maybe I should just try it but, though I might just ask.
Sorry for the ignorance.

**Comment by JanDeDobbeleer** [comment]
@0323pin the omitted flags result in a larger binary:

- `-s`: Omit symbol table and debug information.
- `-w`: Omit DWARF symbol table.

**Comment by 0323pin** [comment]
Yes, that's what I read.
How much larger? It is at the expense of easy reading and binary size.

%  maybe?

**Comment by 0323pin** [comment]
Oh! Thank you.

**Comment by 0323pin** [comment]
Sorry but, what about using `-s -w -X` on both?

`go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Version=17.6.0' -s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2023-07-02T19:18:10Z'"`

I'm simply looking to have the same flags on both stages.

**Comment by JanDeDobbeleer** [comment]
They only need to be specified once, -X is used multiple times to override those 2 values.

**Comment by 0323pin** [comment]
Ok, so I could have
```
GO_BUILD_DATE_cmd=	${DATE} "+%Y-%m-%d"
GO_XFLAG_PREFIX=	-X github.com/jandedobbeleer/oh-my-posh/src

GO_LDFLAGS=	-s -w
GO_LDFLAGS+=	${GO_XFLAG_PREFIX}.Version=${PKGVERSION_NOREV}
GO_LDFLAGS+=	${GO_XFLAG_PREFIX}.BuildDate=${GO_BUILD_DATE_cmd:sh}
```
in the package Makefile?

This would be simpler.

**Comment by 0323pin** [comment]
Ok, somewhere in between.
I'm happy for now ...

```
# $NetBSD: Makefile,v 1.38 2023/07/04 15:49:57 pin Exp $

DISTNAME=		oh-my-posh-17.6.0
CATEGORIES=		shells
MASTER_SITES=		${MASTER_SITE_GITHUB:=JanDeDobbeleer/}
GITHUB_TAG=		v${PKGVERSION_NOREV}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		https://ohmyposh.dev/
COMMENT=		Prompt theme engine for any shell
LICENSE=		mit

WRKSRC=			${WRKDIR}/${DISTNAME}/src

USE_LANGUAGES=		c

INSTALLATION_DIRS=	share/${PKGBASE}

GO_BUILD_DATE_cmd=	${DATE} "+%Y-%m-%d"
GO_SOURCE_BUILD=	github.com/jandedobbeleer/oh-my-posh/src
GO_BUILD_PATTERN=	-ldflags="-s -w -X '${GO_SOURCE_BUILD}/build.Version=${PKGVERSION_NOREV}' \
			-X '${GO_SOURCE_BUILD}/build.Date=${GO_BUILD_DATE_cmd:sh}'" ./...

post-build:
	${MV} ${WRKDIR}/.gopath/bin/src ${WRKDIR}/.gopath/bin/oh-my-posh

post-install:
	cd ${WRKDIR}/${DISTNAME}/themes &&				\
	for f in *.json *.yaml; do					\
	  ${INSTALL_DATA} $$f ${DESTDIR}${PREFIX}/share/${PKGBASE};	\
	done

.include "go-modules.mk"
.include "../../lang/go/go-module.mk"
.include "../../mk/bsd.pkg.mk"
```

![2023-07-06-213748_1073x200_scrot](https://github.com/JanDeDobbeleer/oh-my-posh/assets/90570748/b6b2267c-0d2b-4936-a556-3c4a245457d7)
