### ISSUE TITLE
inconsistancy

### ISSUE THREAD

**Issue by yveshanoulle** [JanDeDobbeleer/oh-my-posh#4017]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

 oh-my-posh --version works the same as  oh-my-posh version
 yet 
 oh-my-posh --version -v does not works 
 where oh-my-posh version -v works
 
 and why -v and not -d ?
 

### Theme

not relevant

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
oh-my-posh --version -v
Error: unknown shorthand flag: 'v' in -v
```

**Comment by JanDeDobbeleer** [comment]
@yveshanoulle oh-my-posh--version is deprecated. That's the reason. This is by design. And -v is for verbose.

**Comment by yveshanoulle** [comment]
Then maybe you need to add a text that it's deprecated?
To teach people the new correct way?

**Comment by JanDeDobbeleer** [comment]
@yveshanoulle if I'm not mistaken this command isn't documented anywhere anymore. It needs to output what it outputs now due to backwards compatibility.
