### ISSUE TITLE
OMP reports inaccurate version

### ISSUE THREAD

**Issue by metal-gabe** [JanDeDobbeleer/oh-my-posh#4020]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I'm using the following `eval` command in my shell to initialize my OMP theme: 

`eval "$(oh-my-posh init zsh --config "$(brew --cellar)/oh-my-posh/$(oh-my-posh version)/themes/atomicbit.omp.json")"`

However, the theme is broken right now because the command `oh-my-posh version` reports `17.6.0` when the actual version (and directory name) is `17.6.0_1`. 

### Theme

Atomic Bit

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
I just see `CONFIG ERROR` in the Posh theme in my terminal/shell. The shell still works, but the theme doesn't.
```

**Comment by JanDeDobbeleer** [comment]
@gflujan that's not a bug but probably [the non-official brew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/oh-my-posh.rb) which had to do a fix to get the version number right using a [revision](https://github.com/Homebrew/homebrew-core/blob/1c5b5bcd61a1c304822c90a568abd1427a9b534d/Formula/oh-my-posh.rb#L7). We hardly ever do fixes on existing formulae.

**Comment by metal-gabe** [comment]
@JanDeDobbeleer I wanted to revisit this because it seems like your cask is now having this issue. 

I just updated `oh-my-posh` and the version it updated to is `18.7.0_1`, but running `oh-my-posh --version` reports back `18.7.0`. Which breaks my shell paths/commands/args/etc. 

I can confirm that I have used your official cask of `jandedobbeleer/oh-my-posh/oh-my-posh` to install.

**Comment by JanDeDobbeleer** [comment]
@gflujan the cask version and oh-my-posh version will always be different on revisions. That's not something we can solve. As I stated above, it's rare that this happens though.
