### ISSUE TITLE
option to truncate hostname

### ISSUE THREAD

**Issue by BPplays** [JanDeDobbeleer/oh-my-posh#4034]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

bash and fish already do this by default so an option to truncate the hostname would be nice.
for example _deb1.example.com_ to _deb1_ or _deb-db1.example.com_ to _deb-db1_

**Comment by JanDeDobbeleer** [comment]
@BPplays this is already possible by leveraging the template on the `session` segment: `"template": " {{ trunc 5 . HostName }} "`.  See all available functions [here](http://masterminds.github.io/sprig/strings.html).

**Comment by BPplays** [comment]
sorry if i wasn't very clear, what i want to do is truncate to the first '.'
_"template": " {{ trunc 5 . HostName }} "_ gives me an error _"template": " {{ trunc 5 .HostName }} "_ truncates to a specific amount of characters, split almost works but i cant figure out how to get out just the ._0 part

**Comment by JanDeDobbeleer** [comment]
You can do something like this:

```json
"template": " {{ $a := split \".\" .HostName }}{{ $a._0 }}" 
```
