### ISSUE TITLE
Quasar JS  framework segment

### ISSUE THREAD

**Issue by lorens-osman-dev** [JanDeDobbeleer/oh-my-posh#4049]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Request a feature for the Quasar framework, which is a Vue js based framework for building web and mobile applications. The feature I would like to see is a segment for Quasar that shows the release number , such as Quasar release @quasar/app-vite, @quasar/cli, and vite. This would help me to keep track of the dependencies and versions of the Quasar framework and its components. It would also help me to know which version of vite is compatible with @quasar/app-vite. I think this feature would be useful for many developers who use Quasar and vite. Thank you for your consideration.

**Comment by JanDeDobbeleer** [comment]
@lorens-osman-dev release number is rather easy as we can use `quasar --version` for that. Vite sounds like a separate requirement and could be a specific segment as well. I don't see how both ate identical, or is this always tied to `quasar/app-vite`?
