### ISSUE TITLE
The Azure icon in nerd font is shown in Arabic characters

### ISSUE THREAD

**Issue by yashints** [JanDeDobbeleer/oh-my-posh#4056]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The Azure icon in nerd font is shown in Arabic characters. The default character is `ufd03` which is shown as `ﴃ` in the terminal.

I replaced it with another icon `uebd8` and it displays correctly. It happens in multiple themes.

### Theme

* pixelrobots
* markbull
* cloud-native-azure
* cloud-context
* night-owl
* jonny-chipz

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Version: 16.9.1

Shell: pwsh (7.3.5)

Segments:

ConsoleTitle(true)                         -   0 ms - Code
os(true)                                   -   0 ms - ╭─ 
root(false)                                -   0 ms -
path(true)                                 -   1 ms - C:   Code
git(false)                                 -   5 ms -
executiontime(true)                        -   1 ms -  0ms
shell(true)                                -   0 ms -   pwsh
sysinfo(true)                              -   0 ms -  50%
angular(false)                             -   0 ms -
aws(false)                                 -   0 ms -
az(true)                                   -   1 ms - ﴃ AzureCloud
```

**Comment by JanDeDobbeleer** [comment]
@yashints you need to update your font to V3

**Comment by yashints** [comment]
@JanDeDobbeleer I just checked and I am on V3 of [CascadiaCode](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.zip), any clues?

**Comment by JanDeDobbeleer** [comment]
I'll check NF's database

**Comment by JanDeDobbeleer** [comment]
@yashints confirmed, that icon got removed and somehow my migration missed it. Fix incoming.

**Comment by MrCNeale** [comment]
Just spent 30 minutes learning the unicode nerd font numbering convention, updated my local copy and was about to submit a PR/issue :-) 
Thanks for being so pro-active!

**Comment by JanDeDobbeleer** [comment]
@MrCNeale I'm delighted to hear your learned something today! BTW, you can use the Nerd Font Cheat Sheet, it has a UTF8 copy button that gives the correct string.
