### ISSUE TITLE
icon for android

### ISSUE THREAD

**Issue by BPplays** [JanDeDobbeleer/oh-my-posh#4062]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

android doesn't seem to have an icon yet, so it would be good if it did.
my suggestion is 󰀲  / _f0032_ / _\uDB80\uDC32_ (nf-md-android)

**Comment by JanDeDobbeleer** [comment]
@BPplays ~~the latest Android release has one ;-)~~ Actually, I made a silly mistake.
