### ISSUE TITLE
Display the Conda Environment

### ISSUE THREAD

**Issue by JohnRothan** [JanDeDobbeleer/oh-my-posh#4068]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

When I'm using the Theme,[powerlevel10k_rainbow](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/powerlevel10k_rainbow.omp.json),I want to display my conda_env_name after the os icon,so i can easily to know which environment i'm working.

**Comment by JanDeDobbeleer** [comment]
@JohnRothan you need to [export the theme](https://ohmyposh.dev/blog/whats-new-1#export-config) so you can adjust it and make use of the [python segment](https://ohmyposh.dev/docs/segments/python) for that.

**Comment by JohnRothan** [comment]
ok,thank you very much.
