### ISSUE TITLE
Possibility for pipestatus

### ISSUE THREAD

**Issue by BigBrotherJu** [JanDeDobbeleer/oh-my-posh#4070]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Shell prompts like starship support pipestatus, which essentially means displaying all exit codes of a pipeline altogether. Is there any possibility that oh-my-posh supports this?

pipestatus example:

<img width="476" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/47515692/2f8f6997-5705-4e70-afdb-e0aad0445f34">

**Comment by JanDeDobbeleer** [comment]
@BigBrotherJu I have no idea how that works, but I can check.
