### ISSUE TITLE
Can't install new version on ubuntu 22

### ISSUE THREAD

**Issue by itsMohammadHeidari** [JanDeDobbeleer/oh-my-posh#4073]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I tried to install oh-my-posh for the first time using the guide in [this link](https://ohmyposh.dev/docs/installation/linux) and this error occurred:
```Shell
mohammad@itsMohammadHeidari:~$ curl -s https://ohmyposh.dev/install.sh | bash -s
Cannot write to /usr/local/bin. Please run the script with sudo and try again:
  curl -s https://ohmyposh.dev/install.sh | sudo bash -s

Alternatively, you can set a different directory and try again: 
  curl -s https://ohmyposh.dev/install.sh | bash -s -- -d {directory}
```
_____________________________
then i try the installation command with sudo and this happened:
```Shell
mohammad@itsMohammadHeidari:~$ curl -s https://ohmyposh.dev/install.sh | sudo bash -s
  Installing oh-my-posh for linux-amd64 in /usr/local/bin
⬇️  Downloading oh-my-posh from https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
chmod: cannot access '/usr/local/bin/oh-my-posh': No such file or directory
main: line 133: /usr/local/bin/oh-my-posh: No such file or directory
🎨 Installing oh-my-posh themes in /themes

unzip:  cannot find or open /themes.zip, /themes.zip.zip or /themes.zip.ZIP.
chmod: cannot access '/themes/*.omp.*': No such file or directory
rm: cannot remove '/themes.zip': No such file or directory
🚀 Installation complete.

You can follow the instructions at https://ohmyposh.dev/docs/installation/prompt
to setup your shell to use oh-my-posh.

If you want to use a built-in theme, you can find them in the /themes directory:
  oh-my-posh init {shell} --config /themes/{theme}.omp.json
```
_______________________

> Specification:
> Distro: Ubuntu 22.04.2 LTS
> CPU architecture: x86_64

 

### Theme

i don't use any theme because i cannot install oh-my-posh.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

i don't have oh-my-posh command because i cannot install it.

**Comment by cspencerjr** [comment]
Removing the -s option of the curl command's provides the following error when running the install.sh script:

_curl: (60) SSL: no alternative certificate subject name matches target host name 'objects.githubusercontent.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above._

Also note, I am having the same issue trying to install brew for Linux.

**Comment by JanDeDobbeleer** [comment]
@cspencerjr update your distro's certificates. Because it needs to be sone client side.

**Comment by cspencerjr** [comment]
> @cspencerjr update your distro's certificates. Because it needs to be sone client side.

Thank you.

Looks like curl, on ubuntu (at least for wsl2), was just updated, and that fixed the certificate issue.
I was able to run the install script without issue.

**Comment by JanDeDobbeleer** [comment]
@cspencerjr Thanks for confirming, I'll see if I can add this information to the script

**Comment by itsMohammadHeidari** [comment]
Update:
I switched to root user and oh-my-posh installed successfully using the install script, but other users still can't run the script successfully even using `sudo` command.

**Comment by JanDeDobbeleer** [comment]
@itsMohammadHeidari did you update all dependencies for those users as well? Seems like the download can fail when your certificates aren't up-to-date (which makes perfect sense).

**Comment by nowhereOnce** [comment]
How can I update my distro's certificates?
