### ISSUE TITLE
Python pipenv prompt

### ISSUE THREAD

**Issue by Rolln-dev** [JanDeDobbeleer/oh-my-posh#408]
Not an issue really but is it possible to get the python virtual environment prompt to work with the pipenv shell?

**Comment by JanDeDobbeleer** [comment]
We can add it, which command can I use to get the name of that env? Or point me to the docs 😅

**Comment by Rolln-dev** [comment]
Not sure if this is what your looking for...   
```python
pipenv --venv #returns full path of virtual environment

pipenv shell #actually starts the pipenv virtual environment
```
As well it looks like it creates a `VIRTUAL_ENV` environment variable when active, removes it when not.

Found here https://github.com/pypa/pipenv/wiki/Run-pipenv-shell-automatically

**Comment by JanDeDobbeleer** [comment]
In that case, adding `"display_mode": "context"` should also set the `VIRTUAL_ENV` name in the prompt.

**Comment by Rolln-dev** [comment]
Yup, that seems to have done it.  This is the python segment I added to my profile.

```json
{
          "type": "python",
          "style": "plain",
          "foreground": "green",
          "properties": {
              "display_mode": "context",
              "prefix": "\uE235 (",
              "postfix": ") "
          }
},
```

Is that where the "display_mode" setting should go?

Thanks for the help!

**Comment by JanDeDobbeleer** [comment]
Yes, that's correct!

**Comment by Rolln-dev** [comment]
So `pipenv` by default creates the virtual environment folders in `~/.virtualenv/` so the above settings work as expected. run `pipenv shell` and it adds the prefix.

A regular virtual environment install using something like `venv` creates the virtual environment folder in the working directory. So using the setting above will automatically add the prefix as soon as you are in the working directory, even before you activate the environment using `./venv/Scripts/activate.ps1` And when you actually activate the environment, you end up with 2 prefixes.

So setting like I have done works correctly when you are using `pipenv` but not correctly when using a regular `venv`.

Confusing I know, not sure it all makes sense.

**Comment by JanDeDobbeleer** [comment]
@rollnthndr the `activate.ps1` script actually hijacks the prompt function. That's why you have 2 env names. It's not something I can fix as it literally overrides Powershell's prompt function (just like we do). If you have a look at the script's content, you can find out if you can disable it doing so by using a variable (but no guarantee as I've already seen at least 2 different versions with only 1 where you can disable it). The good news is you can remove that logic from the file ;-)

**Comment by JanDeDobbeleer** [comment]
Relates to #390

**Comment by irqwu** [comment]
> Yup, that seems to have done it.  This is the python segment I added to my profile.
> 
> ```json
> {
>           "type": "python",
>           "style": "plain",
>           "foreground": "green",
>           "properties": {
>               "display_mode": "context",
>               "prefix": "\uE235 (",
>               "postfix": ") "
>           }
> },
> ```
> 
> Is that where the "display_mode" setting should go?
> 
> Thanks for the help!

Hello, could you please give me a hint on which file should I add this settings? Theme json file or Shell profile (git Bash or powershell). I try add this on theme json file but its display the vesrion of python (3.10) not the (venv) prefix.

Also i got problem with git bash. After `pipenv shell`
The theme dosn't work:
![obraz-1.png](https://user-images.githubusercontent.com/89488630/161417593-6254bc85-2cbc-4306-8575-6579e20cb680.png)

**Comment by irekwiecha** [comment]
`pipenv shell`

**Comment by JanDeDobbeleer** [comment]
Themes JSON. And pipev shell either uses a different profile, or is started without login. So you have to see what it does to understand where to initialize oh-my-posh.

From the web:

> .bash_profile is only sourced for login shells, and pipenv apparently creates a nonlogin interactive shell. Aliases should be defined in .bashrc, and on a Mac (where terminal emulators starts login shells by default), add [[ -f ~/.bashrc ]] && source ~/.bashrc to the end of your .bash_profile.
