### ISSUE TITLE
Use GoReleaser for publishing to WinGet

### ISSUE THREAD

**Issue by vedantmgoyal9** [JanDeDobbeleer/oh-my-posh#4081]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

GoReleaser now supports WinGet. https://goreleaser.com/customization/winget/

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 I'd like to stay in control when it comes to this. I also don't use goreleaser to publish any other packages. For Windows definitely it doesn't publish the artifacts created by goreleaser.
