### ISSUE TITLE
$env:POSH_GIT_ENABLED = $true in Powershell 7 disabled oh-my-posh

### ISSUE THREAD

**Issue by seanadams9** [JanDeDobbeleer/oh-my-posh#4089]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Recently upgraded to Powershell 7 and noticed I wasn't seeing oh-my-posh anymore. Debugged and the $env:POSH_GIT_ENABLED = $true is disabling oh-my-posh somehow. 

In Powershell 7 if I type "$env:POSH_GIT_ENABLED = $true" and hit enter oh-my-posh goes away, then if I enter "$env:POSH_GIT_ENABLED = $false" oh-my-posh is back.

Confirmed in Powershell 5 I don't have this issue.

### Theme

Custom Theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@seanadams9 I can't reproduce this at all. I have oh-my-posh and posh-git (1.1.0) on latest. All this environment variable trigger is the following code:

```powershell
$global:GitStatus = Get-GitStatus
$env:POSH_GIT_STATUS = $global:GitStatus | ConvertTo-Json
```

So unless `Get-GitStatus` overwrites the prompt, this can never remove oh-my-posh.
