### ISSUE TITLE
Shell WindowsRegistryKeyValue functionality broken for default key retrieval using trailing "\"

### ISSUE THREAD

**Issue by memcpy-rand-rand-rand** [JanDeDobbeleer/oh-my-posh#4119]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In the Windows Registry, there is a notion of a "Default" key under a path, e.g.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/90210865/d77c734c-d698-434e-871e-4e1bc9b8bcf3)

The Windows APIs support this by asking for the key with name of empty string, "".

To support this in the WindowsRegistryKeyValue function without needing to supply a separate path and key, the function would look for a trailing `\` on the path.  If this is present, it would treat the path as asking for the (Default) key under the path before the trailing `\`.  

It looks like during a refactor this functionality was broken.

The fix is relatively simple.  Perhaps we need to also add a set of tests for the function in case of future refactor.

### Theme

n/a

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

cmd, powershell

### Log output

```Shell
n/a
```

**Comment by JanDeDobbeleer** [comment]
@memcpy-rand-rand-rand this code hasn't changed in a long time and I see this specific logic still in it so I'll have a look

**Comment by memcpy-rand-rand-rand** [comment]
use of (Default) keys is quite rare, but I have a specific use-case I only just spotted wasn't working :)

I have a local fix.  Feel free to assign the bug to me if you like and I'll remind myself of the branching etc process to get a PR done.

**Comment by JanDeDobbeleer** [comment]
@memcpy-rand-rand-rand I have a fix ready, was rather silly

**Comment by memcpy-rand-rand-rand** [comment]
Perfect, same as mine.  Confirmed working, thanks 👍
