### ISSUE TITLE
Prompt to indicate virtual environment is active for Python

### ISSUE THREAD

**Issue by FernandoBorea** [JanDeDobbeleer/oh-my-posh#4126]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I've been an OhMyPosh user for a while now and I love it.

A feature I'd love to see is to have something that indicates when a virtual environment is active in Python. The default prompt has a (venv) prefix added when that's the case but when using OhMyPosh, this is not the case.

Thanks!

**Comment by JanDeDobbeleer** [comment]
@FernandoBorea this is already available in the Python segment but needs to be enabled. Have a look [here](https://ohmyposh.dev/docs/segments/python).
