### ISSUE TITLE
Can't see what I type

### ISSUE THREAD

**Issue by thorstenkampe** [JanDeDobbeleer/oh-my-posh#414]
### Description

Can't see what I type on Windows - on Linux no problem

### Environment

- Oh my Posh version: 3.89.0
- Theme: ?
- Operating System: Windows
- Shell: PowerShell 7.1.2
- Terminal: ConEmu with Monokai Theme

### Steps to Reproduce

1. [First Step] activate oh-my-posh prompt
2. [Second Step] type into shell

**Expected behavior:** [What you expected to happen]
see what I type

**Actual behavior:** [What actually happened]
don't see what I type

**Comment by thorstenkampe** [comment]
Additional information: 3.88.0 did not have the bug.

**Comment by thorstenkampe** [comment]
![image](https://user-images.githubusercontent.com/475462/107919058-0621e300-6f6b-11eb-8873-a924181d73b8.png)

**Comment by lnu** [comment]
You can rollback to 3.88. In the meantime we're fixing the bug, probably related to the new osc9;9 support.
I tried conemu on my side with the fix and it works.

**Comment by JanDeDobbeleer** [comment]
@thorstenkampe fix incoming in [3.39.1](https://github.com/JanDeDobbeleer/oh-my-posh3/releases/tag/v3.89.1)

**Comment by lnu** [comment]
@thorstenkampe  can you confirm it's ok with the latest version ([3.89.1](https://github.com/JanDeDobbeleer/oh-my-posh3/releases/tag/v3.89.1))?

**Comment by thorstenkampe** [comment]
@lnu confirming that the issue is fixed with 3.89.1 - closing ticket
