### ISSUE TITLE
Scoop installation doesn't install any themes

### ISSUE THREAD

**Issue by xmopi** [JanDeDobbeleer/oh-my-posh#415]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

No default themes were installed with scoop installation

### Environment

- Oh my Posh version: 3.89.0
- Theme: any of them
- Operating System: windows 10 pro x64
- Shell: powershell
- Terminal: windows terminal

### Steps to Reproduce

1. run `scoop install oh-my-posh3`
2. scoop 'sucessfully' installs oh-my-posh3
3. no themes are installed

**Expected behavior:** default themes to be installed

**Actual behavior:** no default themes were installed

**Comment by JanDeDobbeleer** [comment]
@iipom `scoop install oh-my-posh3` isn't maintained by me. The right command is `scoop install https://github.com/JanDeDobbeleer/oh-my-posh3/releases/latest/download/oh-my-posh.json` (as indicated in the [docs](https://ohmyposh.dev/docs/installation#installation-1)). That one does install the themes.

**Comment by dysuby** [comment]
Hi @JanDeDobbeleer, thanks your reply. I am a scoop user before, and I am confusing about difference between `scoop install oh-my-posh3` and `scoop install https://github.com/JanDeDobbeleer/oh-my-posh3/releases/latest/download/oh-my-posh.json` util I find this issue. So just curious, will you maintain the manifest in scoop bucket or highlight this fact in the docs?

**Comment by JanDeDobbeleer** [comment]
Hey @vegchic. I'm not the one maintaining scoop in the bucket, also by design. The official way to install using scoop is `scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json` as it is also highlighted in the docs. Otherwise I need to rely on others to keep things up-to-date (even it is PR based, I want to be in control as much as I can).

**Comment by dysuby** [comment]
@JanDeDobbeleer oh I see. It's my fault reading docs in a hurry. I often find apps by `scoop serach <NAME>` so I was tricked by it this time. Thansk for your quick reply again!
