### ISSUE TITLE
Feature: Get random theme

### ISSUE THREAD

**Issue by sionta** [JanDeDobbeleer/oh-my-posh#4156]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Provide random option of themes at any given time, i use this way on PowerShell 5+:

```powershell
$items = Get-Random 'powerline', 'robbyrussell', 'more...'
$theme = "$env:POSH_THEMES_PATH/$items.omp.json"
# or use Get-ChildItem command
$theme = Get-Random (Get-ChildItem $env:POSH_THEMES_PATH).FullName

# init...
Invoke-Expression (oh-my-posh init pwsh --config $theme | Out-String)
```

But it only works when opening a new session, which I hope can be scheduled for an automatic theme change.

**Comment by JanDeDobbeleer** [comment]
@sionta I'm not adding this feature, it was suggested before. You can add this to your $PROFILE, and you get the same result.
