### ISSUE TITLE
Add a way to ignore certain files in Project segment

### ISSUE THREAD

**Issue by Destroy666x** [JanDeDobbeleer/oh-my-posh#4188]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I noticed 2 problems of the Project segment:
1. The fact that it considers PowerShell is not documented here: https://ohmyposh.dev/docs/segments/project
2. It considers all `psd1` files which aren't always project definitions. For example, many PowerShell projects will use `PSScriptAnalyzerSettings.psd1` file in their root, which is one of the recommended ways of storing config for that tool. Example in a repo: https://github.com/chocolatey-community/chocolatey-packages/blob/master/PSScriptAnalyzerSettings.psd1 That results in no data except `.Type`, also no error.

One solution would be an ability to ignore certain files, which could also help with other scenarios, potentially.

Another more direct one is to define PowerShell project files in a better way, I can't say how though. I don't think there's any naming convention that would help: https://learn.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest?view=powershell-7.3 So the 1st one seems much better.

**Comment by Destroy666x** [comment]
Thanks for the attempted workaround @JanDeDobbeleer , however, it doesn't work for me on 18.6.0. This:
```
      - type: project
        style: plain
        template: "<p:icon>\uEB99</>{{.Type}} {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }}{{ if .Name }}{{ .Name }} {{ end }}{{.Version}}{{ end }}{{ end }} "
```
still outputs the icon and the `.Type` which is `powershell`, with nothing else filled. This is the dir: https://github.com/chocolatey-community/chocolatey-packages/tree/master
I checked just in case if there are any other files with `psd1` extension in that repo, but no: 
```
GCI -Recurse | ? { $_.Extension -eq ".psd1" }
    Directory: D:\Dev\Repositories\git\chocolatey-community-packages

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          23.03.2023    20:11            501 PSScriptAnalyzerSettings.psd1
```

**Comment by JanDeDobbeleer** [comment]
@Destroy666x fixed in the next release.
