### ISSUE TITLE
Allow variables to be set on `init`

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/oh-my-posh#4189]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Basically provide a facility to pass in values for `var` to override the one in the theme so people can fetch the theme remotely and just tweak it using variables that are passed in.

Please ensure we can pass lists and objects as well

e.g.
```
--var foo=bar
--var foo='"bar"'
--var foo='["list","of","bar"]' 
--var foo='{"some":"complex", "value":"object"}'
```

The logic could be if first character is either `"` or `[` or `{` then treat the rest of the data as JSON input (this will handle both list and objects.  And prevent you from having to create a complicated parser because it you can simply use the existing JSON parsers.

**Comment by JanDeDobbeleer** [comment]
This was suggested before, but as themes act as inspiration and/or out of the box usage, this goed against their purpose. It's mostly easier to adjust it than to make every theme variable, as where does that end?

**Comment by trajano** [comment]
I think it could/should end where the whole theme would be defined from the command line rather than separate configuration files so rather than having to publish something extra to gist to use it remotely we just happen to have a single command line maybe ridiculously long on our bash profile and since it's bash we can add extra logic as well that is driven by the shell within the shell rather than the prompt.

**Comment by JanDeDobbeleer** [comment]
@trajano that would be something for a different tool imho. I don't see why anyone would create this in a oneliner, that's not manageable.
