### ISSUE TITLE
Async Prompt Update

### ISSUE THREAD

**Issue by saumyajyoti** [JanDeDobbeleer/oh-my-posh#4192]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Can we have Async Prompt update like the Git module of https://github.com/chrisant996/clink-flex-prompt#async-prompt-filtering

**Comment by JanDeDobbeleer** [comment]
@saumyajyoti the cmd implementation has this. As for other shells this is a complex matter.

**Comment by saumyajyoti** [comment]
Thanks @JanDeDobbeleer
