### ISSUE TITLE
Theme creation web UI

### ISSUE THREAD

**Issue by adamerose** [JanDeDobbeleer/oh-my-posh#4199]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I think it would be cool to have a web UI like [this one](https://bash-prompt-generator.org/) where people can create custom oh-my-posh themes by dragging and dropping segments and clicking them to see configuration options. Does anything like this already exist? Or is that something that would be doable?

**Comment by JanDeDobbeleer** [comment]
@adamerose with pleasure if I could build on oh-my-posh fulltime and quit my day job. It's definitely possible, all it needs is a different writer (and some refactoring probably).

**Comment by JanDeDobbeleer** [comment]
Gave this a thought but as the terminal already is a UI and changes to the config are visible straight away, there's no use-case for such a tool.
