### ISSUE TITLE
`pwd` should not execute on remote 

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/oh-my-posh#4208]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I think the `pwd` should have a check whether I am local or SSHing (somehow...) because if I send that notification while I am on SSH and I do the `duplicateTab` was was suggested in  https://github.com/microsoft/terminal/issues/15900  then the PWD will be wrong.

This may be there already for all I know but I didn't see it documented.  I'm actually about to test it out.

**Comment by trajano** [comment]
Hmm this may be a bug at least on bash I get the following when I do duplicate tab and `pwd: osc99`

[error 2147942667 (0x8007010b) when launching `C:/Program Files/Git/usr/bin/bash.exe -i -l']
Could not access starting directory "C:Wed Aug 30hcons4j-self-registration\build"

Pwsh is okay though.

**Comment by JanDeDobbeleer** [comment]
@trajano that's Git bash wonkyness. It tries to replace escape characters in the path as it's used to unix paths. But here it's (obviously) a Windows path due to the fact that this does run on Windows and every executable has to deal with that reality to work. Yet another reason why I dislike that shell with a passion. It's an abomination.

**Comment by trajano** [comment]
The weird part is why is it showing the date? I guess `\d` is translated to current date somehow.

**Comment by JanDeDobbeleer** [comment]
@trajano on the topic, I agree. PWD shouldn't work when in an SSH session. I thought the `pwd` field supports templates, but the docs don't reflect that. I'll check.

**Comment by trajano** [comment]
Specifically I have a folder called `C:\dh\mystuff` and the `\d` gets changed to `Wed Aug 30` yielding `C:Wed Aug 30h\mystuff`

Also since I don't have any remote machines with PWSH I can't really test this out. :D

**Comment by JanDeDobbeleer** [comment]
> I thought the pwd field supports templates, but the docs don't reflect that. I'll check.

Confirmed, so you can add this desired behaviour yourself that way.

**Comment by trajano** [comment]
So something like this? 
```
pwd: "{{if not .Segments.Session.SSHAccess}}osc99{{end}}"
```
Assuming it's correct maybe you can add it to #4209

**Comment by trajano** [comment]
Though I don't get why `\d` is still being translated.  I found where https://github.com/JanDeDobbeleer/oh-my-posh/blob/2c7aa8c49032cb406aca0f00da7458c09ad2ce17/src/platform/shell.go#L422 is logged in oh-my-posh debug and it seems to be correct.

**Comment by JanDeDobbeleer** [comment]
@trajano which directory is it?

**Comment by trajano** [comment]
Say I am in `c:\dh\template-ms` I get it
And if I am at my home directory
```
[DEBUG] 03:10:41.679 shell.go:Pwd:422 → C:\Users\trajano
```

Also this 
```
echo -e '\e]9;9;c:\\dh\\template-ms\e\\'
```
has no issues

It's just the `\d` being converted somehow with pwd but I can't find it.
Also just found it `\t` being converted to time in pwd

**Comment by trajano** [comment]
Maybe we can have a log at

https://github.com/JanDeDobbeleer/oh-my-posh/blob/2c7aa8c49032cb406aca0f00da7458c09ad2ce17/src/ansi/ansi_writer.go#L221C24-L221C29

to show what the `pwd` value is at the moment.

**Comment by JanDeDobbeleer** [comment]
@trajano for Git Bash, this (`c:\dh\template-ms`) will need to be escaped as you highlight in your working example. I'll fix that on our end.

**Comment by trajano** [comment]
It's not specific to *git bash* it's bash in general.  I just found out where it was done from https://askubuntu.com/questions/404341/where-can-i-find-a-complete-reference-for-the-ps1-variable

It's basically because of the `PS1` prompt processing of *Bash*.

So my guess is something along the lines of
```go
	case OSC7:
		return fmt.Sprintf(w.osc7, escapeBackslash(hostName), escapeBackslash(pwd))
	case OSC51:
		return fmt.Sprintf(w.osc51, escapeBackslash(userName), escapeBackslash(hostName), escapeBackslash(pwd))
	case OSC99:
		fallthrough
	default:
		return fmt.Sprintf(w.osc99, escapeBackslash(pwd))
````

**Comment by JanDeDobbeleer** [comment]
@trajano those path characters only occur on Windows unless someone purposefully adds that to their folder name, which is illegal (IMHO).
