### ISSUE TITLE
No icons appearing

### ISSUE THREAD

**Issue by karthikvijay5227** [JanDeDobbeleer/oh-my-posh#4217]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

No icons are appearing in oh-my-posh even after applying multiple theme styles.It is just showing blocks.

### Theme

unicorn.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
No logs
```

**Comment by JanDeDobbeleer** [comment]
@karthikvijay5227 you need to configure a nerd font for your terminal. See [here](https://ohmyposh.dev/docs/installation/fonts).

**Comment by karthikvijay5227** [comment]
It is working fine for me for the last few days.It has gone all of a sudden yesterday.
