### ISSUE TITLE
Support for multiple OSC

### ISSUE THREAD

**Issue by pwsandoval** [JanDeDobbeleer/oh-my-posh#4240]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Based on [2515](https://github.com/JanDeDobbeleer/oh-my-posh/issues/2515) and according to the [pwd](https://ohmyposh.dev/docs/configuration/general#general-settings) documentation, I can add "pwd": "osc99" or "pwd": "osc7", to my theme to notify the terminal of the current working directory, but Windows Terminal/Alacritty/Wezterm don't use the same OSC, there is a way to somehow indicate more than one value, I tried "pwd": ["osc99", "osc7"] but it does not work.

I use the JanDeDobbeleer theme.

Thanks for your time.

**Comment by JanDeDobbeleer** [comment]
@pwsandoval Terminal uses OSC99, so which one is missing? I only found 7 and 99 in my searches.

**Comment by pwsandoval** [comment]
> @pwsandoval Terminal uses OSC99, so which one is missing? I only found 7 and 99 in my searches.

Is there any way to do "pwd": ["osc99", "osc7"]?

**Comment by JanDeDobbeleer** [comment]
@pwsandoval pwd is templatable. You can’t add both as terminals will behave differently based on their implementation (it can make a bell sound for example). So you want to leverage the template to enable the correct one based on the terminal you’re using.
