### ISSUE TITLE
Can't modify theme Paradox

### ISSUE THREAD

**Issue by johnknoop** [JanDeDobbeleer/oh-my-posh#425]
I'm using V3 and I'm trying the steps outlined in this guide:

![image](https://user-images.githubusercontent.com/3394270/108072201-dfe16d80-7066-11eb-9a0b-aedcac1657dd.png)

But I like Paradox rather than jandedobbeleer, so I try out the steps with Paradox:

![image](https://user-images.githubusercontent.com/3394270/108072113-c93b1680-7066-11eb-9c6b-1f669fc1c02c.png)

But as you can see, it now says "invalid config".

**Comment by johnknoop** [comment]
This is the contents of the generated file `.go-my-posh-.json`:

```json
{
    "final_space": false,
    "osc99": false,
    "console_title": false,
    "console_title_style": "",
    "console_title_template": "",
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "horizontal_offset": 0,
            "vertical_offset": 0,
            "segments": [
                {
                    "type": "root",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#100e23",
                    "foreground_templates": null,
                    "background": "#ffe9aa",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": null
                },
                {
                    "type": "session",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#100e23",
                    "foreground_templates": null,
                    "background": "#ffffff",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": null
                },
                {
                    "type": "path",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#100e23",
                    "foreground_templates": null,
                    "background": "#91ddff",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": {
                        "folder_icon": "",
                        "folder_separator_icon": "",
                        "style": "full"
                    }
                },
                {
                    "type": "git",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#193549",
                    "foreground_templates": null,
                    "background": "#95ffa4",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": null
                },
                {
                    "type": "python",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#100e23",
                    "foreground_templates": null,
                    "background": "#906cff",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": {
                        "prefix": "  "
                    }
                },
                {
                    "type": "exit",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#ffffff",
                    "foreground_templates": null,
                    "background": "#ff8080",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": {
                        "prefix": " "
                    }
                }
            ]
        },
        {
            "type": "newline",
            "alignment": "",
            "horizontal_offset": 0,
            "vertical_offset": 0,
            "segments": null
        },
        {
            "type": "prompt",
            "alignment": "left",
            "horizontal_offset": 0,
            "vertical_offset": 0,
            "segments": [
                {
                    "type": "text",
                    "style": "plain",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#007ACC",
                    "foreground_templates": null,
                    "background": "",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": {
                        "prefix": "",
                        "text": "❯"
                    }
                }
            ]
        }
    ]
}

```

**Comment by JanDeDobbeleer** [comment]
@johnknoop try the full path rather than `~` and allow me to fix that annoying issue (only happens when using the module)

**Comment by johnknoop** [comment]
@JanDeDobbeleer same thing seems to happen when using the full path:

![image](https://user-images.githubusercontent.com/3394270/108079926-a2351280-706f-11eb-9f1f-b7ce712cbc84.png)

**Comment by JanDeDobbeleer** [comment]
Oh wait, my mistake. I think it's the null fields being exported. I'll check later today, and hopefully then fix the export to not include those.

**Comment by JanDeDobbeleer** [comment]
Hmm. When I add the above theme to a file, I actually get a rendered prompt. Let's validate on Windows.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/2492783/108104067-1af59800-708b-11eb-987e-5d3d79269ea2.png">

**Comment by JanDeDobbeleer** [comment]
Same on Windows, works like a charm. Starting to think this is related to encoding rather than something oh-my-posh is influencing.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/2492783/108104607-cf8fb980-708b-11eb-8e00-0ff9aa26792e.png">

@johnknoop I need more information here:

### Environment

- Oh my Posh version:
- Theme:
- Operating System:
- Shell:
- Terminal:

**Comment by johnknoop** [comment]
Sure.

Oh my Posh version: 3.94.2
Theme: Paradox
Operating System: Windows 10
Shell: Powershell 7.1.2
Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
@johnknoop when you copy-paste the contents of the theme as described [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/paradox.omp.json), does it work then?

**Comment by johnknoop** [comment]
Same thing happens :(

**Comment by johnknoop** [comment]
I can at least confirm that it locates the file correctly, because if I run Set-PoshPrompt with an invalid path then I get a slightly different prompt afterwards.

**Comment by JanDeDobbeleer** [comment]
@johnknoop ok. That's the first time we see this issue. We've excluded the values in the export, the path is also correct yet somehow it can't parse the file's content correctly. I'll try to provide a build that outputs the actual error later today. 

9/10 it's going to be file encoding as the default themes are included and work (autocomplete on `Set-PoshPrompt`). Which means calling the included scripts directly should work: `Set-PoshPrompt -Theme "$((Get-Module oh-my-posh).ModuleBase)/themes/paradox.omp.json"`.

**Comment by johnknoop** [comment]
Thanks! Let me know when it's deployed and I'll run it and see what it says.

**Comment by sid-6581** [comment]
Speaking of colors, hopefully my issue is related enough to tag onto this issue. I just updated to the new version, and I also use Paradox. Previously I believe it just used the ANSI colors, but now it uses hardcoded colors that clash with the colors I use in my terminal. Are there versions of these themes that use the ANSI colors? In particular Paradox.

**Comment by JanDeDobbeleer** [comment]
@sid-6581 we support hex color codes as well as ANSI colors. See [here](https://ohmyposh.dev/docs/configure#colors) for more info on that.

@johnknoop I have a [binary](https://github.com/JanDeDobbeleer/oh-my-posh/files/5997863/posh-windows-amd64.exe.zip) that prints the information we're looking for. Extract the file in it, navigate to that folder in your terminal and run it with your config ` .\posh-windows-amd64.exe --config ~/.go-my-posh.json`. That should at least give an indication of the issue at hand.

**Comment by sid-6581** [comment]
@JanDeDobbeleer I did see in the documentation that ANSI colors are supported, my question was more along the lines of whether there are versions of the themes that use ANSI colors instead of hex color codes. The previous version of paradox looked fine in my terminal, but the new one has hardcoded hex colors that don't look good with my terminal colors. Do I have to go and modify the theme by hand?

**Comment by JanDeDobbeleer** [comment]
@sid-6581 yes. The whole idea behind the current themes is that they serve more as samples rather than out of the box themes (can be, just not always what you want). With a json config the theme can also be carried cross shell/environment, making it super portable.

**Comment by johnknoop** [comment]
@JanDeDobbeleer does it write to a log file or something? Because it doens't write anything to the console:

![image](https://user-images.githubusercontent.com/3394270/108326790-f3a5e480-71ca-11eb-9298-46976de0d03f.png)

**Comment by johnknoop** [comment]
Oh, hold on. Now I see "invalid config path".

**Comment by johnknoop** [comment]
Now we get some more info!

![image](https://user-images.githubusercontent.com/3394270/108326911-1637fd80-71cb-11eb-80a1-e0a46e664e15.png)

**Comment by johnknoop** [comment]
It turns out the json file was saved with a BOM. As soon as I removed that, it starts working!

**Comment by johnknoop** [comment]
Thanks a lot for the help you provided.

**Comment by JanDeDobbeleer** [comment]
Maybe we can do a structural change here that sets the output encoding correctly and saves the file correctly. Because this will happen more often now that we're out of beta.
