### ISSUE TITLE
How to style error

### ISSUE THREAD

**Issue by amnweb** [JanDeDobbeleer/oh-my-posh#4250]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

How to style or remove this type of error or validation, this is happened always when i start typing with dot ?

![Screenshot 2023-09-12 004542](https://github.com/JanDeDobbeleer/oh-my-posh/assets/16545063/cdedb2fd-8efe-4404-a753-4735ac3491bc)

https://github.com/JanDeDobbeleer/oh-my-posh/assets/16545063/4ed1d764-fd4b-422e-bda0-386f9e2fbba8

**Comment by JanDeDobbeleer** [comment]
@forumwt can you share your config?

**Comment by amnweb** [comment]
Sure, just tell me which config you need, also I found where is problem, this lines
```
"valid_line": {
    "background": "transparent",
    "foreground": "#ffffff",
    "template": "<#e0def4,#286983>\uf42e </><#286983,transparent>\ue0b4</> "
},
"error_line": {
    "background": "transparent",
    "foreground": "#ffffff",
    "template": "<#eb6f92,#286983>\ue009</><#286983,transparent>\ue0b4</> "
},
```

If i remove valid_line and error_line all is working perfect

**Comment by amnweb** [comment]
Fixed

```
"valid_line": {
	"background": "transparent",
	"foreground": "#ffffff",
	"template": "<#3c454e,transparent>╰╴</>"
},
"error_line": {
	"background": "transparent",
	"foreground": "#ffffff",
	"template": "<#e44949,transparent>╰╴</>"
},
```


https://github.com/JanDeDobbeleer/oh-my-posh/assets/16545063/7db85ccb-c93d-48a4-a68a-24a72e53238c
