### ISSUE TITLE
Cascadia Code PL - Some symbols are not displayed 

### ISSUE THREAD

**Issue by AdeeelAsif** [JanDeDobbeleer/oh-my-posh#426]
### Description

Hi everyone, 

some of the symbols are not properly displayed as you can see on the screnshots below. I have the same issue with Powershell 5.1 and Powershell Core 7.0.2

I installed Cascadia Code PL from https://github.com/microsoft/cascadia-code/releases/tag/v2102.03

![image](https://user-images.githubusercontent.com/56124889/108124651-bdbc0f80-70a7-11eb-8e43-2459fb560672.png)

### Environment

- Oh my Posh version: 3.94.2
- Theme: Paradox
- Operating System: Windows 10 
- Shell: Powershell 5.1 (same issue with Powershell core 7.0.2)
- Terminal: Windows Terminal

settings.json content : 

> "list": [
>             {
>                 // Make changes here to the powershell.exe profile.
>                 "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
>                 "name": "Windows PowerShell",
>                 "commandline": "powershell.exe",
>                 "fontFace": "Cascadia Code PL",
>                 "hidden": false
>             },
>             {
>                 "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
>                 "hidden": false,
>                 "name": "PowerShell",
>                 "fontFace": "Cascadia Code PL",
>                 "source": "Windows.Terminal.PowershellCore"
>             },

### Steps to Reproduce

Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme paradox

**Comment by lnu** [comment]
Cascadia does not contain all glyphs(same question here https://github.com/JanDeDobbeleer/oh-my-posh/issues/145). From the doc:

> Oh my Posh was designed using [Meslo LGM NF](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip), but any Nerd Font should be compatible with the standard themes.

The other option is to replace the missing icons with ones available in cascadia.

**Comment by JanDeDobbeleer** [comment]
I'm going to add this information to the docs (Cascadia Code PL missing glyphs). It's crazy how many people ask this question considering V2 also mentioned Nerd Fonts.
