### ISSUE TITLE
oh-my-posh brew cask ?

### ISSUE THREAD

**Issue by Magniquick** [JanDeDobbeleer/oh-my-posh#4262]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Is it possible to add a cask version to hombrews oh-my-posh tap ?
I believe it wouldn't be that hard as you anyway do give a binary version for macos
the compile times and dependencies for the formula are not exactly neglectable.

**Comment by Magniquick** [comment]
Just realized there is a seperate [homebrew-oh-my-posh](https://github.com/JanDeDobbeleer/homebrew-oh-my-posh) repo - should I close this and create an issue there ?

**Comment by JanDeDobbeleer** [comment]
@Magniquick I'll move it when it needs to depending on the solution, but yes I'll have a look at implementing this.

**Comment by JanDeDobbeleer** [comment]
@Magniquick update brew, uninstall and reinstall oh-my-posh using `--cask`. It's added.
