### ISSUE TITLE
Hide username@host from the prompt

### ISSUE THREAD

**Issue by debasish-patnaik** [JanDeDobbeleer/oh-my-posh#430]
### Prerequisites

- [✔] I have read and understand the `CONTRIBUTING` guide
- [✔] I looked for duplicate issues before submitting this one

### Description

In oh-my-posh v2 I used to set $global:DefaultUser = [System.Environment]::UserName to hide username@host but it doesn't work on upgrading to v3. How do I hide it in v3? 

### Environment

- Oh my Posh version: 3.94.2
- Theme: Agnoster
- Operating System: Windows 10 Version 20H2
- Shell: Powershell 7.1.2
- Terminal: Windows Terminal

### Steps to Reproduce

1. Set the global default user using $global:DefaultUser = [System.Environment]::UserName.

**Expected behavior:** username@host should be hidden.

**Actual behavior:** username@host was still visible.

**Comment by JanDeDobbeleer** [comment]
@debasish-patnaik you need to create your own version of the theme and remove that part, that's the main difference with V2. See [here](https://ohmyposh.dev/docs/installation#override-the-theme-settings) for more info on that.

**Comment by krokofant** [comment]
For future readers:
If you're fixing your custom theme then you'd want to hide the "session" configuration from the theme. https://ohmyposh.dev/docs/session
