### ISSUE TITLE
node: option to customize files list

### ISSUE THREAD

**Issue by TommasoAmici** [JanDeDobbeleer/oh-my-posh#4310]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently in the node segment there are two display options: always and files.

The files option uses a hardcoded list of extensions.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segments/node.go#L35

```go
extensions: []string{"*.js", "*.ts", "package.json", ".nvmrc", "pnpm-workspace.yaml", ".pnpmfile.cjs", ".npmrc", ".vue"}
```

Would you be open to letting users customize this list? I have been using [bun](https://github.com/oven-sh/bun/) for a few things lately, and I don't need the `node` segments in those situations. I would like to restrict the extensions list to something like:

```go
extensions: []string{"pnpm-workspace.yaml", "yarn.lock", "package-json.lock"}
```

PS: thanks for all the hard work you put in, this is one of my favorite things on my laptop

**Comment by JanDeDobbeleer** [comment]
@TommasoAmici you can do this using the undocumented property `extensions` which is a string array.
