### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by LunarMarathon** [JanDeDobbeleer/oh-my-posh#4311]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

- ![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/113847439/b9b177f0-3fc0-4e95-b1c4-e1ea62840e60)

- ![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/113847439/ba96ca9c-ca00-44ef-a722-c6943a66dc54)

- ![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/113847439/b894267b-6a91-43d1-bede-b821951355bf)

- ![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/113847439/36c1f445-9688-4e24-98e9-3521719d9dd9)

And in faqs, the word "maximise" has been used, which can be changed to maximize if needed.

Please assign this issue to me if it needs to be fixed. Thank you!

### Theme

-

### Log output

```Shell
-
```

**Comment by JanDeDobbeleer** [comment]
@LunarMarathon feel free to create a PR to solve these. Read though the contribution guide, specifically the part about conventional commits, before starting.
