### ISSUE TITLE
winget installation fails 

### ISSUE THREAD

**Issue by dosych-ev** [JanDeDobbeleer/oh-my-posh#4315]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

We have a script that sets up our invironment. We isntall oh-my-posh as part of this script using:

`& winget install --id 'JanDeDobbeleer.OhMyPosh' --exact --accept-package-agreements --accept-source-agreements`

Recently we noticed that the installation started to fail with:

`Exception: Failed to install oh-my-posh, exit code -1073741819
`

Running the install script again - works.

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Exception: Failed to install oh-my-posh, exit code -1073741819
```

**Comment by JanDeDobbeleer** [comment]
That exit code isn't from oh-my-posh. The oh-my-posh installer is an inno installer, and that one has the [following](https://documentation.help/Inno-Setup/topic_setupexitcodes.htm) exit codes. This error code is outside of oh-my-posh' scope. See [here](https://answers.microsoft.com/en-us/windows/forum/all/solved-error-code-1073741819-when-running-certain/76b4c0e8-c5ff-43cd-9098-0ae524b422ac) for reference.
