### ISSUE TITLE
Allow full control to where to store cache-files by setting env-var OMP_CACHE_DIR

### ISSUE THREAD

**Issue by woutervh** [JanDeDobbeleer/oh-my-posh#4321]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

https://github.com/JanDeDobbeleer/oh-my-posh/issues/1017 was a big step in the right direction using the XDG-standard.

We can take this a step further by introducing an environment-variable `OMP_CACHE_DIR` 
that gives the user full control where to store the cache-files, possibly outside of $HOME.

If this env-var is not, set, then use the XDG-location as default/fallback.

**Comment by JanDeDobbeleer** [comment]
@woutervh why would you opt for a different directory than specified with `XDG_CACHE_HOME`?

**Comment by woutervh** [comment]
Because I try to script and install all my dev-tools locally in a maximally isolated self-contained way:

```
 > git clone git@github.com:woutervh/tools.git /opt/tools
 > cd /opt/tools/oh-my-posh
 > make install
  or
 > make update
```

resulting dir-structure
```
/opt/tools/oh-my-posh
    bin/
        oh-my-posh -> symlinked to $HOME/bin
    etc/
        bashrc
        zshrc
    var/
        cache/   <-- wanted
        themes/
        tmp/


```

see makefile: https://github.com/woutervh/tools/blob/main/oh-my-posh/makefile
