### ISSUE TITLE
 Nerd Font cannot install from nerd-fronts [v3.0.2]

### ISSUE THREAD

**Issue by Vincent-ZHENG-008** [JanDeDobbeleer/oh-my-posh#4323]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### What happened?

in oh-my-post from 18.11.0. when i want to install  Nerd Font, then i get 404 from nerd-fronts [v3.0.2](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2)

Failed to download zip file: 404 Not Found
    → https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Nerd.zip

### Theme

legacyDark

### Log output

```Shell
none
```

**Comment by JanDeDobbeleer** [comment]
@Vincent-ZHENG-008 that's the GitHub API acting up as that file does exist. Can't reproduce this locally either.
