### ISSUE TITLE
Are git colors still supported in v3?

### ISSUE THREAD

**Issue by johnknoop** [JanDeDobbeleer/oh-my-posh#433]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

On my old computer I'm running oh-my-posh v2, and I always got different colors if my local git branch is behind or has changes etc. That doesn't seem to be working in v3. I've tried adding colors as [described here](https://ohmyposh.dev/docs/git#colors), but nothing changes.

Is it supposed to be working in v3, or is it not implemented yet?

### Environment

Oh my Posh version: 3.94.2
Theme: Paradox
Operating System: Windows 10
Shell: Powershell 7.1.2
Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
Yes they are, actually have that set up myself. What does your config look like for the git segment?

EDIT: this is my config

```json
{
    "type": "git",
    "style": "powerline",
    "powerline_symbol": "",
    "foreground": "#193549",
    "background": "#fffb38",
    "properties": {
        "display_stash_count": true,
        "display_upstream_icon": true,
        "status_colors_enabled": true,
        "local_changes_color": "#ff9248",
        "ahead_and_behind_color": "#f26d50",
        "behind_color": "#f17c37",
        "ahead_color": "#89d1dc",
        "stash_count_icon": "\uF692 "
    }
}
```

You need to set `"status_colors_enabled": true` otherwise the logic isn't ran (to avoid spending time).

**Comment by johnknoop** [comment]
Oh, it was the `status_colors_enabled` that was missing. Thanks for that!
