### ISSUE TITLE
Broken link on https://ohmyposh.dev/docs/installation/customize

### ISSUE THREAD

**Issue by oleschri** [JanDeDobbeleer/oh-my-posh#4338]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

On the bottom of the page are two identical links to 

> [configuration guide](https://ohmyposh.dev/docs/installation/configuration/overview.mdx)

> [configuration](https://ohmyposh.dev/docs/installation/configuration/overview.mdx)

that fail to reach their target https://ohmyposh.dev/docs/installation/configuration/overview.mdx (404).

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by lnu** [comment]
that's not the only place. Comes from here https://github.com/JanDeDobbeleer/oh-my-posh/commit/aa51cd65d0bda7f555888280c8a11401e5219b9d#diff-8b686a2d3e66b26a65cce93b0d44226d991ae5b2b7db752487d08b83742618a2. 
https://github.com/JanDeDobbeleer/oh-my-posh/issues/4338
