### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by HeleneVeber** [JanDeDobbeleer/oh-my-posh#4339]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!
I tried to install oh-my-posh on my linux-ubuntu with the command "curl -s https://ohmyposh.dev/install.sh | sudo bash -s"
and here's the error I'm getting.

But in fact the installation doesn't work

### Theme

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
chmod: cannot access '/usr/local/bin/oh-my-posh': No such file or directory
main: line 137: /usr/local/bin/oh-my-posh: No such file or directory
🎨 Installing oh-my-posh themes in /themes

unzip:  cannot find or open /themes.zip, /themes.zip.zip or /themes.zip.ZIP.
chmod: cannot access '/themes/*.omp.*': No such file or directory
rm: cannot remove '/themes.zip': No such file or directory
🚀 Installation complete."
```

**Comment by JanDeDobbeleer** [comment]
@HeleneVeber seems like the curl command failed to download oh-my-posh. Which is strange as I built in a safety that should exit if that's the case (tested with no connection). Is this reproducible ?

**Comment by HeleneVeber** [comment]
Thanks for the feedback. 

I had a curl version installed by snap (v. 8.1.2) with which I was not able to install oh-my-posh.

I installed curl with apt (v. 7.81.0) and the oh-my-posh installation works.

**Comment by JanDeDobbeleer** [comment]
> I had a curl version installed by snap (v. 8.1.2) with which I was not able to install oh-my-posh.

@HeleneVeber this is interesting. I'll see of I can reproduce and catch that issue, thanks!
