### ISSUE TITLE
[Bug] Too broad detection for python environment

### ISSUE THREAD

**Issue by nopeless** [JanDeDobbeleer/oh-my-posh#4342]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

https://github.com/JanDeDobbeleer/oh-my-posh/blob/108a836736d3b95736676e96057b74b78fc5a362/src/segments/python.go#L29-L56

Line 34 seems to include `env` folder, which I also use for some other projects. It's not really python specific

I suggest we remove this

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@nopeless agreed. Can you create a quick PR to remove this?

**Comment by nopeless** [comment]
sure
