### ISSUE TITLE
Execute oh-my-posh.exe into WSL.

### ISSUE THREAD

**Issue by pol73** [JanDeDobbeleer/oh-my-posh#4371]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I would like used "oh-my-posh.exe" (Windows executable file) into WSL environment. It's allowed into WSL. It's allowing used one distributive on the host. In all environment's. One executable file, one theme directories, one theme file, for all OS's. But "oh-my-posh init ..." (elf executable file) and "oh-my-posh.exe init ..." generate don't correct initialization code. And "oh-my-posh.exe print ..." also don't work correctly.

**Comment by JanDeDobbeleer** [comment]
@pol73 the executables are the same. So probably you have an older version installed Windows side. That said, there's different logic in the Windows binary execution wise, but not for init.

**Comment by pol73** [comment]
Hello. Different only in the resources locations...

~ ❯ whereis oh-my-posh
oh-my-posh: /usr/local/bin/oh-my-posh
WSL at  pol@DESKTOP-J3CUGSC                                                                                                took  323ms  11:01:16 
~ ❯ whereis oh-my-posh.exe
oh-my-posh.exe: /mnt/c/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe
WSL at  pol@DESKTOP-J3CUGSC                                                                                                took  251ms  11:01:20 
~ ❯ oh-my-posh version
18.15.0
WSL at  pol@DESKTOP-J3CUGSC                                                                                                 took  12ms  11:01:36 
~ ❯ whereis oh-my-posh.exe
oh-my-posh.exe: /mnt/c/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe
WSL at  pol@DESKTOP-J3CUGSC                                                                                                took  277ms  11:01:41 
~ ❯

**Comment by pol73** [comment]
Ups...
~ ❯ oh-my-posh.exe version
18.15.0
WSL at  pol@DESKTOP-J3CUGSC                                                                                                took  223ms  11:07:40 
~ ❯

**Comment by pol73** [comment]
There may be an error in detecting the location of resources in the WSL environment. Resources from the Windows host. (Perhaps if it is detected that the executable is launched from under WSL, you can use wslpath?)
https://learn.microsoft.com/en-us/windows/wsl/filesystems#run-windows-tools-from-linux
and
https://github.com/ardnew/wslpath

**Comment by JanDeDobbeleer** [comment]
@pol73 we do that in the linux binary. But, there's a major reason we're not adding WSL logic into the Windows executable, it's slow when running in WSL2. So even if we could optimize, we're not doing it.

**Comment by pol73** [comment]
Hello. I understand. Thanks you.
