### ISSUE TITLE
Option to disable ahead/behind counter of git segment

### ISSUE THREAD

**Issue by LarsBauer** [JanDeDobbeleer/oh-my-posh#438]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Hi,

I am trying to re-create the [half-life](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#half-life) theme of Oh My Zsh. It was really straight forward thanks to your excellent docs 🙌  I am quite happy with the looks except for the ahead/behind counter of the git status. Is there any setting I am missing to get rid of the counter?

Here is my current prompt
![image](https://user-images.githubusercontent.com/3920045/108511221-e585c000-72bf-11eb-8550-1fc6ff2cab06.png)

And this is the related configuration of the git segment:
```json
{
  "type": "git",
  "style": "plain",
  "foreground": "#5FD7FF",
  "properties": {
    "prefix": "<#ffffff>on</> ",
    "branch_icon": "",
    "branch_ahead_icon": "",
    "branch_behind_icon": "",
    "branch_gone_icon": "",
    "branch_identical_icon": "",
    "working_color": "#D75F00",
    "staging_color": "#87FF00",
    "local_working_icon": "●",
    "local_staged_icon": "●",
    "status_separator_icon": " ",
    "display_status_detail": false
  }
}
```

I would like to contribute by submitting a PR but unfortunately I have no experience in go at all. It would be great if you could help me out.
Thanks in advance!

**Comment by JanDeDobbeleer** [comment]
We don't have that switch yet but it's definitely possible! Allow me to add that, it's not much work.

**Comment by JanDeDobbeleer** [comment]
@LarsBauer incoming. It would be cool if you're down to create a PR to add this theme to the collection 🙏🏻

**Comment by LarsBauer** [comment]
Wow, that was quick 🚀 Thanks a lot!
I would definitely like to submit the theme to your collection. I am submitting a PR once it's ready.
