### ISSUE TITLE
Linux i686

### ISSUE THREAD

**Issue by duckcantcode** [JanDeDobbeleer/oh-my-posh#4397]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Running the install script shows: "i686 builds for linux are not available for Oh My Posh". It would be great to have an installer for i386/i686/32-bit Linux.

**Comment by JanDeDobbeleer** [comment]
We don't even build it for that architecture, and in 2023 I don't see the use-case myself. Can you explain where you would need this?

**Comment by duckcantcode** [comment]
[iSH](https://ish.app/)! It runs 32-bit Alpine Linux, and I'm trying to bring `nushell` + `oh-my-posh` to all of my personal devices.

**Comment by duckcantcode** [comment]
Thank you! Especially for such a quick response! I'm testing it now.

**Comment by JanDeDobbeleer** [comment]
@duckfromdiscord it doesn't work. The installation succeeds but there's an issue in an underlying package (gopsutil) that causes a panic. I'll have a look to see if I can patch that.

EDIT: traced it all the way to [here](https://github.com/shirou/gopsutil/blob/c020a0890ebf4fb877e096c27141e4111cf7a63f/cpu/cpu_linux.go#L312). That needs to be checked to be `>= 8` as that assumption is being made down the line.

**Comment by duckcantcode** [comment]
Thank you. In case it helps, here's the error running just `oh-my-posh` with no arguments:
```
panic: runtime error: index out of range [5] with length 5

goroutine 1 [running]:
github.com/shirou/gopsutil/v3/cpu.parseStatLine({0x9130210, 0x23})
        /opt/hostedtoolcache/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.23.9/cpu/cpu_linux.go:340 +0x5db
github.com/shirou/gopsutil/v3/cpu.TimesWithContext({0x8a01990, 0x8f189c0}, 0x0)
        /opt/hostedtoolcache/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.23.9/cpu/cpu_linux.go:119 +0x2d0
github.com/shirou/gopsutil/v3/cpu.Times(...)
        /opt/hostedtoolcache/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.23.9/cpu/cpu_linux.go:95
github.com/shirou/gopsutil/v3/cpu.init.0()
        /opt/hostedtoolcache/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.23.9/cpu/cpu.go:62 +0x44
```

I've also asked the devs in the iSH server.

**Comment by JanDeDobbeleer** [comment]
Yup, same issue. But this is on our end,  and could be a rabbit hole. This isn't a real linux distro.

**Comment by duckcantcode** [comment]
If we rebuilt gopsutil with that patch, could it be fixed?

**Comment by JanDeDobbeleer** [comment]
@duckfromdiscord maybe. I'm trying that tomorrow.

**Comment by JanDeDobbeleer** [comment]
@duckfromdiscord confirmed to work, that said, configuring the terminal correctly on iSH is a whole other challenge (font, rendering, etc).
