### ISSUE TITLE
Symbols for controlling fonts

### ISSUE THREAD

**Issue by Tarocch1** [JanDeDobbeleer/oh-my-posh#440]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I want to know if it is possible to add symbols for controlling fonts, such as `<bold>`, `<italic>`, `<underline>`. I think it will be useful.

**Comment by JanDeDobbeleer** [comment]
Not yet. Can be done 😉

**Comment by JanDeDobbeleer** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/2492783/109386723-fc01cc00-78fc-11eb-90fb-d29268e3f5d8.png">
