### ISSUE TITLE
Windows Terminal - PowerShell customization via oh-my-posh/posh-git Set-Theme error?

### ISSUE THREAD

**Issue by nihaltowfiq** [JanDeDobbeleer/oh-my-posh#441]
### Windows Terminal - PowerShell customization via oh-my-posh/posh-git Set-Theme error?

I follow the exact tutorial of Microsoft link: [Link Here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup) video link: [Video Link Here](https://www.youtube.com/watch?v=lu__oGZVT98&feature=youtu.be)

I have installed Posh-Git and Oh-My-Posh: via this code -
`Install-Module posh-git -Scope CurrentUser`
`Install-Module oh-my-posh -Scope CurrentUser`

I have installed PSReadLine: via this code -
`Install-Module -Name PSReadLine -Scope CurrentUser -Force -SkipPublisherCheck`

I am also created Microsoft.PowerShell_profile.ps1 file by typing- code $PROFILE, in my PowerShell profile and copy/paste this code:
`Import-Module posh-git`
`Import-Module oh-my-posh`
`Set-Theme Paradox`

But I get this error:  

> Set-Theme Paradox
> The term 'Set-Theme' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

ScreenShot: [Screenshot of error](https://i.stack.imgur.com/hUy8j.png)

![ssss](https://user-images.githubusercontent.com/62647867/108628039-c2573e00-7482-11eb-9f4c-e8e13f403435.PNG)

**Comment by JanDeDobbeleer** [comment]
`Set-Theme` is a V2 cmdlet. This got renamed to `Set-PoshPrompt` for V3. See [here](https://ohmyposh.dev/docs/installation#3-replace-your-existing-prompt) for more info.

**Comment by nihaltowfiq** [comment]
thanks ♥

**Comment by JanDeDobbeleer** [comment]
@nihaltowfiq thanks for bringing this to my attention, I created a [PR](https://github.com/MicrosoftDocs/terminal/pull/263) to the MS Docs so the information is correct.
