### ISSUE TITLE
OS segment: display WSL distro name (not OS)

### ISSUE THREAD

**Issue by charlesroper** [JanDeDobbeleer/oh-my-posh#443]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I run a number of WSL distros of the same type (Ubuntu 20.04 mainly) for different projects by cloning and renaming my base distro (see instructions [here](https://www.pugetsystems.com/labs/hpc/Note-How-To-Copy-and-Rename-a-Microsoft-WSL-Linux-Distribution-1811/)). It would be very useful to be able to display the WSL distro name as a segment rather than just the OS name/logo. Is this possible? Many thanks.

### Environment

- Oh my Posh version: 3.96.0
- Theme: negligible
- Operating System: Ubuntu 20.04.2 LTS (5.4.72-microsoft-standard-WSL2)
- Shell: bash
- Terminal: Windows Terminal 1.5

**Comment by tradiff** [comment]
@charlesroper do you know a command to get this information from within the WSL instance?

**Comment by tradiff** [comment]
@charlesroper sounds like this is held in the environment variable `$WSL_DISTRO_NAME`  which you can confirm using the command `echo $WSL_DISTRO_NAME`

With that in mind, you should be able to display this in your prompt by adding a `envvar` segment to your theme.  [envvar docs here](https://ohmyposh.dev/docs/environment#sample-configuration)

**Comment by charlesroper** [comment]
Superb, thank you! I didn't think of using an environment var. I've customised my local copy of the negligible theme to include the distro name. Screenshot and content of theme file below.

![image](https://user-images.githubusercontent.com/176/108806135-c1183500-7598-11eb-99b0-e8380a8a6e67.png)

```json
{
    "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
    "blocks": [
      {
        "type": "prompt",
        "alignment": "left",
        "segments": [
          {
            "type": "os",
            "style": "plain",
            "foreground": "green",
            "properties": {
              "wsl": "",
              "wsl_separator": "",
              "prefix": "[",
              "postfix": " "
            }
          },
          {
              "type": "envvar",
              "style": "plain",
              "powerline_symbol": "\uE0B0",
              "foreground": "green",
              "properties": {
                "var_name": "WSL_DISTRO_NAME",
                "prefix": "",
                "postfix": "]"
              }
          },
          {
            "type": "path",
            "style": "plain",
            "foreground": "cyan",
            "properties": {
              "style": "full"
            }
          },
          {
            "type": "git",
            "style": "plain",
            "foreground": "lightYellow",
            "properties": {
              "prefix": ":: <lightBlue>git(</>",
              "postfix": "<lightBlue>)</>"
            }
          }
        ]
      },
      {
        "type": "prompt",
        "alignment": "right",
        "segments": [
          {
            "type": "python",
            "style": "plain",
            "foreground": "lightRed",
            "properties": {
              "display_virtual_env": true,
              "display_version": false,
              "prefix": "[ ",
              "postfix": " ]",
              "display_mode": "always"
            }
          },
          {
            "type": "time",
            "style": "plain",
            "foreground": "lightGreen"
          }
        ]
      },
      {
        "type": "newline"
      },
      {
        "type": "prompt",
        "alignment": "left",
        "segments": [
          {
            "type": "exit",
            "style": "powerline",
            "foreground": "lightGreen",
            "properties": {
              "display_exit_code": false,
              "always_enabled": true,
              "error_color": "red",
              "prefix": "\u279c"
            }
          }
        ]
      }
    ]
  }
  ```
