### ISSUE TITLE
It seems you're using an oh-my-posh V2 cmdlet while running V3.

### ISSUE THREAD

**Issue by itsRajat** [JanDeDobbeleer/oh-my-posh#444]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Upgraded from V2 to V3 using Update-Module -Name oh-my-posh -AllowPrerelease -Scope CurrentUser
and it all worked out successfully. On restarting terminal, ohmyposh doesn't work and an upgrade error comes up.

### Environment

Happens in all terminals using oh-my-posh.

- Oh my Posh version: v3
- Theme: jandedobbelee
- Operating System: Windows
- Shell: PowerShell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Upgrade from V2 to V3 (used admin powershell)
2. Restart terminal.
3. This error occurs. 

**Expected behavior:**
Expected the upgrade to apply successfully and use the theme.

**Actual behavior:** 

This is what I get in my terminal - 

```
Hi there!

It seems you're using an oh-my-posh V2 cmdlet while running V3.
To migrate your current setup to V3, have a look the documentation.

https://ohmyposh.dev/docs/upgrading


Hi there!

It seems you're using an oh-my-posh V2 cmdlet while running V3.
To migrate your current setup to V3, have a look the documentation.

https://ohmyposh.dev/docs/upgrading
```

The same message occurs twice btw. I have tried the command again and also tried installing it manually from the gallery.  Nothing happens when I do that, there's just a 1-2 second delay and then a new line in Terminal begins.

Oddly enough, when I change the Theme using Set-PoshPrompt -Theme jandedobbeleer, it starts working again.

How do I resolve this?

**Comment by JanDeDobbeleer** [comment]
@itsRajat you still have lingering V2 cmdlets in your `$PROFILE`. You can check the list [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/1a907f3c4879fab946f8860c39d887506a452af5/packages/powershell/oh-my-posh/oh-my-posh.psm1#L155) for reference.

**Comment by itsRajat** [comment]
> @itsRajat you still have lingering V2 cmdlets in your `$PROFILE`. You can check the list [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/1a907f3c4879fab946f8860c39d887506a452af5/packages/powershell/oh-my-posh/oh-my-posh.psm1#L155) for reference.

Thanks. Fixed it by doing `ise $PROFILE` to edit the `$PROFILE` & removing everything from there except the theme I wanted to have permanently. Is there any other configuration I should have in $PROFILES?

**Comment by JanDeDobbeleer** [comment]
@itsRajat no, that should be it!
