### ISSUE TITLE
\uE0CE powerline glyph not displaying correctly

### ISSUE THREAD

**Issue by Yongjun042** [JanDeDobbeleer/oh-my-posh#445]
### Prerequisites

- [ v] I have read and understand the `CONTRIBUTING` guide
- [ v] I looked for duplicate issues before submitting this one

### Description

![image](https://user-images.githubusercontent.com/24871665/108874641-b1076080-763f-11eb-884b-63c7b84887f0.png)
\uE0CE powerline glyph doesn't look as expected. Top one is expected sample from powerline extra symbols https://github.com/ryanoasis/powerline-extra-symbols

### Environment

- Oh my Posh version: 3.96.0
- Theme: custom
- Operating System: windows
- Shell: zsh
- Terminal: windows terminal
- Font: 'MesloLGM NF'

### Steps to Reproduce
set block
`
{
...
          "style": "powerline",
          "powerline_symbol": "\uE0CE",
...
}`

**Comment by JanDeDobbeleer** [comment]
@Yongjun042 That's a font/terminal settings issue, unrelated to oh-my-posh.
