### ISSUE TITLE
Support for other languages in the "Time" segment.

### ISSUE THREAD

**Issue by delaviux** [JanDeDobbeleer/oh-my-posh#4469]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I don't know if this is supported in oh my posh, I haven't seen anything in the docs. But if it is not, I would like to propose that the dates, like the days of the week, could be seen in other languages.
I am currently using the theme "froczh" and I thought it would be nice if the days that appear in it were seen in Spanish. Like "Friday" to "Viernes."
Again I'm not sure if this functionality is supported and if so, I would like someone to tell me the correct way to put that in the json.

**Comment by JanDeDobbeleer** [comment]
@iarejenius this isn't supported in golang and opening that jar in one segment will definitely open this in others as well and I honestly don't have the time to support that (also not for the docs for that matter). You can however define a localized array (starting at Sunday) to have this effect:

```json
{
  "background": "#29315A",
  "foreground": "#3EC669",
  "properties": {
    "time_format": "15:04:05"
  },
  "style": "plain",
  "template": "<transparent> \ue0ba\ue0bc </>{{ .CurrentDate | date .Format }} | {{ $weekdays := list \"Domingo\" \"Lunes\" \"Martes\" \"Miércoles\" \"Jueves\" \"Viernes\" \"Sábado\"}}{{ index $weekdays .CurrentDate.Weekday }} ",
  "type": "time"
}
```
