### ISSUE TITLE
Too much latency compared to oh-my-posh2

### ISSUE THREAD

**Issue by aykxt** [JanDeDobbeleer/oh-my-posh#45]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

There is too much latency compared to oh-my-posh2, especially when
typing the `clear` command.

### Environment

- Oh my Posh version: 3.11.0
- Operating System: Windows 10 20H2
- Shell: PowerShell Core 7.0.3
- Terminal: Windows Terminal

### Steps to Reproduce

1. Type `clear` command in the terminal.
2. You will see some latency until the shell bar pops up.

**Expected behavior:**
Little to no latency.

**Actual behavior:**
Some latency.

**Comment by nwykes** [comment]
What theme?

**Comment by aykxt** [comment]
> What theme?

I was using the Star theme.

**Comment by nwykes** [comment]
it seems pretty responsive to me.  But this might be causing an issue on Windows?

```        
{
          "type": "command",
          "style": "plain",
          "foreground": "#C49EE9",
          "properties": {
            "shell": "bash",
            "command": "find . -name package.json -depth 1 -exec echo \" <#ffffff>via node</>\" \\;"
          }
        },
```

Do you have issues with other themes?

**Comment by JanDeDobbeleer** [comment]
The `command` segment seemed like a good idea but I'm starting to resent it. I'm going to look for a different solution. I haven't noticed latency, but I'm mostly on zsh which might explain that. The only segment that has a noticeable impact is `spotify`. And as @nwykes states, in theory `command` is the only one that can have an impact this negative.

**Comment by JanDeDobbeleer** [comment]
For `star` specifically I will replace the command with the default `node` segment functionality as that one makes no sense anymore. I think `command` is neat when you know what you're dealing with, but the out-of-the-box themes shouldn't be using this.

**Comment by JanDeDobbeleer** [comment]
@aykxt can you check to see if the latest version offers a different experience?

**Comment by aykxt** [comment]
> @aykxt can you check to see if the latest version offers a different experience?

Seems like it is a little bit faster now. But there is still some delay when I'm in a git repository.

**Comment by JanDeDobbeleer** [comment]
I'll see if we can speed up things a bit in that regard.

**Comment by JanDeDobbeleer** [comment]
@aykxt looking forward to seeing if the latest update makes a difference. If not, can you check if you're on the latest git version?

**Comment by aykxt** [comment]
> @aykxt looking forward to seeing if the latest update makes a difference. If not, can you check if you're on the latest git version?

Just tried it, it's much faster now!

**Comment by JanDeDobbeleer** [comment]
@aykxt do we close this one for now? I'm not sure there's much I can do to make it even faster, the layout should also keep it that way even when extending to offer support for revert/bisect.

**Comment by aykxt** [comment]
> @aykxt can you check to see if the latest version offers a different experience? 

I think we can close it, it's much faster now.
