### ISSUE TITLE
Transparent font and Windows Terminal acrylic

### ISSUE THREAD

**Issue by RaringCoder** [JanDeDobbeleer/oh-my-posh#450]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Font transparency doesn't react when the underlying background is going transparent.

### Environment

- Oh my Posh version: 3.96.0
- Theme: Nord Custom
- Operating System: Windows 10
- Shell: PowerShell 7
- Terminal: Windows Terminal

### Steps to Reproduce

1. Configure a simple text block, in this case a powerline glyph, with a transparent foreground:

```
{
  "type": "text",
  "style": "plain",
  "foreground": "transparent",
  "background": "#5E81AC",
  "properties": {
    "text": "\uE0B0",
    "prefix": "",
    "postfix": ""
  }
}
```

2. With Windows Terminal acrylic off, assert that foreground colour matches the background colour of the terminal as we have set it to "transparent". This looks fine
3. Enable acrylic, set a low opacity (something like 0.1) and place the terminal over a bright background, this makes it very obvious.
4. Observe the font colour isn't transparent, it has inherited the solid colour of the terminal.

**Expected behavior:**

It would be nice if the colour could be truly transparent such that the background passes through in a more visually appealing manner.

**Actual behavior:**

As you can see from the image (accentuated for effect) the foreground colour (#2E3440) of the text block is far darker than the acrylic-effect background of the terminal. The colour itself is correct to what the terminal has set.

![image](https://user-images.githubusercontent.com/2183058/108979121-40356800-7682-11eb-8605-73744d427cff.png)

**Comment by JanDeDobbeleer** [comment]
That's a bug in Windows Terminal, see [here](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/250).
