### ISSUE TITLE
[Feature request] More format of status code

### ISSUE THREAD

**Issue by Dragon1573** [JanDeDobbeleer/oh-my-posh#4503]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Currently, `Status Code` segment is only supported with decimal format. Is it able to add more format (octal or hexadecimal, binary is too long for segment) for the status code?

**Comment by JanDeDobbeleer** [comment]
@Dragon1573 we have a `hresult` [helper function](https://ohmyposh.dev/docs/configuration/templates#custom) already, this transform it to hexadecimal.
