### ISSUE TITLE
add support for japanese characters

### ISSUE THREAD

**Issue by rafanochi** [JanDeDobbeleer/oh-my-posh#4511]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I created new theme named `zawkins`. 
![image_2023-12-02_00-46-30](https://github.com/JanDeDobbeleer/oh-my-posh/assets/139969429/1453b9f4-43b5-4c12-ab39-0bbd6b05f70d) 
I need japanese characters to make screenshot of it using your tool. I appreciate it if you add support for it as well, cuz it will be my very 

first contirbution to open source project (✯◡✯)

**Comment by JanDeDobbeleer** [comment]
@zawkindev what do you mean? The fonts we use for image generation do not have Japanese characters, nor is it possible to patch those (they're already patched). I understand the request, but it will be challenging to keep this updated with Nerd Font's updates.

**Comment by rafanochi** [comment]
When i used the tool in your project, which kinda takes screenshot the japanese characters were replaced with empty blocks. `[]` like this

**Comment by JanDeDobbeleer** [comment]
@zawkindev yes, the embedded font doesn't have Japanese characters support. Also not something I'm adding as that custom patching I need to maintain.

**Comment by rafanochi** [comment]
Ok I understand, thanks for the response sir😉
