### ISSUE TITLE
Configure the rprompt when the input line reaches it

### ISSUE THREAD

**Issue by alanmoyano** [JanDeDobbeleer/oh-my-posh#4516]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It'd be awesome to have the ability to configure the rprompt to hide or to make a new line when the input line reaches it, something like oh-my-zsh.

**Comment by JanDeDobbeleer** [comment]
This is a request for the shells. On zsh, this is the behaviour as the `rprompt` is built-in. So, if you want this on other shells as well, you'll need to create a feature request there. Note that for `pwsh`, there's no native `rprompt` functionality.
