### ISSUE TITLE
Increase size of weather icon in OWM

### ISSUE THREAD

**Issue by Krishna-Chaitanya-b** [JanDeDobbeleer/oh-my-posh#4517]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi Jan,

The OWM weather icon is looking too small, is there a way to increase the icon size.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/67149457/904ec8e5-43db-4e4a-a595-62084c4facb6)

Thanks in Advance.

**Comment by JanDeDobbeleer** [comment]
@Krishna-Chaitanya-b no. This is a font/terminal settings issue. Nothing we can do about that. You can change the icon for a better one.
