### ISSUE TITLE
"Invalid config" when setting standard theme

### ISSUE THREAD

**Issue by lassenormann** [JanDeDobbeleer/oh-my-posh#452]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When setting a custom theme, which is an exact copy of standard theme, the prompt displays "INVALID CONFIG"

### Environment

- Oh my Posh version: 3.58.0
- Theme: custom/jandedobbeleer
- Operating System: windows
- Shell: powershell
- Terminal: Windows Terminial

### Steps to Reproduce

1. ```Set-PoshPrompt -Theme jandedobbeleer```
2. ```Export-PoshTheme -FilePath ~/.oh-my-posh.omp.json```
3. ```Set-PoshPrompt -Theme  ~/.oh-my-posh.omp.json```

**Expected behavior:** Expected the prompt to be identical after setting the custom theme as duplicate of exported.

**Actual behavior:** The prompt display an extra segment "INVALID CONFIG". Furthermore, if I try to edit the .json, e.g. remove a segment, and Set-Posh-Prompt, changes are not reflected.

![image](https://user-images.githubusercontent.com/2077637/109016754-c4a1de00-76b6-11eb-9a80-a2de75c520ed.png)

**Comment by JanDeDobbeleer** [comment]
@lassenormann can you check the encoding of the generated config file? This happened before due to incorrect encoding which it why it can't be parsed. I assumed this was fixed by setting the output encoding but probably not.

**Comment by JanDeDobbeleer** [comment]
@lassenormann what happens when you run the following:

```PowerShell
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
Set-PoshPrompt -Theme jandedobbeleer
Export-PoshTheme -FilePath ~/.oh-my-posh.omp.json
Set-PoshPrompt -Theme ~/.oh-my-posh.omp.json
```

**Comment by lassenormann** [comment]
The generated config files had encoding UTF-16, and  LE line endings. Setting ```[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding``` before export, did not seem to make a difference on my machine. 

I also tried the solution described in  #220 ;
```
.\posh-windows-amd64.exe -print-config | Out-File -FilePath ~/.utf8.json -Encoding utf8
```

This resulted in ecoding UTF8 with BOM, and CRLF line endings. Changed it to UTF8 (no BOM) and LF. That  did the trick, now it works like a char.

Thank you so much for helping and for building this awesome tool. 👍👍👍

**Comment by mdlopresti** [comment]
I know this is closed, but I'm having the same issue on v3.104.0.  Chances are others might be too.  

Mind if I submit a PR to update [Export-PoshTheme](https://github.com/JanDeDobbeleer/oh-my-posh/blob/5bc4759309ce707b819043fb4380598fa7f03b8c/packages/powershell/oh-my-posh/oh-my-posh.psm1#L81) so it always exports utf8?

Figuring out the file encoding was the only pain point I had on the from v2->v3 update.  And the doc line added in [#220](https://github.com/JanDeDobbeleer/oh-my-posh/issues/220) has since been removed.

**Comment by JanDeDobbeleer** [comment]
@mdlopresti please do as I can't reproduce this making it tricky to fix correctly.

**Comment by mdlopresti** [comment]
Cool, I got a few things coming up the next few days so it'll probably be a week or so.  

I see unit testing standards for Go in the docs, but nothing for the PowerShell code.  Do you want me to try to include pester tests to recreate/validate the issue is fixed or is that overkill?

**Comment by JanDeDobbeleer** [comment]
@mdlopresti I consider that to be overkill as the pwsh logic doesn't change that often.
