### ISSUE TITLE
Make `Path` length based on terminal `$COLUMNS`

### ISSUE THREAD

**Issue by diogo-rossi** [JanDeDobbeleer/oh-my-posh#4522]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Even having the Path styles [Agnoster Short](https://ohmyposh.dev/docs/segments/path#agnoster-short) and [Mixed](https://ohmyposh.dev/docs/segments/path#mixed), which controls the maximum length to display, it would be nice if the maximum length was based on the terminal size width.

**Comment by JanDeDobbeleer** [comment]
@Diogo-Rossi unfortunately, the way oh-my-posh works, this will never be possible. We create the string outside of the context of terminal dimensions (and in parallel). The segment logic doesn't know this context, even if it's available via our injected environment, it has no idea about the other strings being rendered in parallel to understand available space.

**Comment by diogo-rossi** [comment]
@JanDeDobbeleer Thanks for the information!

Now I have a question: how do you set the [filler property](https://ohmyposh.dev/docs/configuration/block#filler)?

**Comment by JanDeDobbeleer** [comment]
@Diogo-Rossi you can `Add this property to the right aligned block` as per the docs.
