### ISSUE TITLE
feat: Add template to show proxy address that provide by environment variable `HTTP_PROXY` etc.

### ISSUE THREAD

**Issue by mrbeardad** [JanDeDobbeleer/oh-my-posh#4523]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Show proxy address that provide by `HTTP_PROXY`, `HTTPS_PROXY` or `ALL_PROXY`. In ohmyzsh, there is a option to show it.

**Comment by JanDeDobbeleer** [comment]
@mrbeardad you can access these using the `.Env` environment variable template [property](https://ohmyposh.dev/docs/configuration/templates#environment-variables). You could create a full-blown, or simple template depending on what you want to visualise:

```json
"template": "{{ if .Env.HTTP_PROXY }}{{ .Env.HTTP_PROXY }}{{ else if .Env.HTTPS_PROXY }}{{ .Env.HTTPS_PROXY }}{{ else if .Env.ALL_PROXY }}{{ .Env.ALL_PROXY }}{{ end }}"
```
