### ISSUE TITLE
feat: git upstream icons does not support ssh/git format: `git@github.com:JanDeDobbeleer/oh-my-posh`

### ISSUE THREAD

**Issue by mrbeardad** [JanDeDobbeleer/oh-my-posh#4524]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

THe scheme is `git@` instead of `https://`, and be aware at the `:` between domain and path, not `/`.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/54128430/6ffe1176-aef6-433c-9505-7675efaf9a70)

**Comment by mrbeardad** [comment]
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/54128430/dddd5bf8-aca8-4f50-a3af-2eee69336ac9)

BTW, a space is required between icon and text.

**Comment by JanDeDobbeleer** [comment]
@mrbeardad that space is font/terminal dependant. You can override that. Which theme is this BTW, as we do support ssh URL's, we even have [tests](https://github.com/JanDeDobbeleer/oh-my-posh/blob/5493ddb640877ff1fa3d6d640664a5eeb161c4c2/src/segments/git_test.go#L634) for that.

**Comment by mrbeardad** [comment]
theme is [night-owl](https://ohmyposh.dev/docs/themes#night-owl)

**Comment by mrbeardad** [comment]
> @mrbeardad that space is font/terminal dependant. You can override that. Which theme is this BTW, as we do support ssh URL's, we even have [tests](https://github.com/JanDeDobbeleer/oh-my-posh/blob/5493ddb640877ff1fa3d6d640664a5eeb161c4c2/src/segments/git_test.go#L634) for that.

Maybe the test case does not cover this format `git@github.com:user/repo`, the most similar format to it in that test case is `_gitea@src.example.com:user/repo.git`

**Comment by mrbeardad** [comment]
> @mrbeardad that space is font/terminal dependant. You can override that.

@JanDeDobbeleer [powerlevel10k](https://github.com/romkatv/powerlevel10k) for zsh will ask user for the display width of symbols, it is useful to add an option to adjust it.

**Comment by JanDeDobbeleer** [comment]
@mrbeardad you have the option by overriding the configuration. Providing a wizard for all these options would be insane depending on the ROI for what's still an after hours project.
