### ISSUE TITLE
Curl unable to download error

### ISSUE THREAD

**Issue by Fuzzycc** [JanDeDobbeleer/oh-my-posh#4534]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hello, I was trying to install following the guide for Linux (im on Ubuntu), using curl from snap (curl 8.1.2)
But I keep getting this error:

(Im posting from mobile, so im writing the output log by hand)

Command used:
```
curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/bin
```

### Theme

...

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

fish

### Log output

```Shell
installation directory /home/sharbel/bin is not in your $PATH

Installing oh-my-posh for Linux-amd64 in /home/sharbel/bin
Downloading oh-my-posh from https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
Unable to download executable at https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
Please validate your curl, connection and/or proxy settings
```

**Comment by JanDeDobbeleer** [comment]
@ChillFire22 not much I can do about that on my end. The curl command `curl -s -f -L https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -o /home/sharbel/bin/oh-my-posh` isn't executing correctly.
