### ISSUE TITLE
Errorcode for transient prompt for original statement

### ISSUE THREAD

**Issue by MatthiasKainer** [JanDeDobbeleer/oh-my-posh#4559]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

hejhej,

I'm using the transient prompt to collapse the powerline prompt and get a quick overview of my typed history. One thing that I would love to have is to see if a command had failed or not by coloring the prompt.

My initial attempt was to add this:

```json
  "transient_prompt": {
      "background": "transparent",
      "foreground": "#ffffff",
      "foreground_templates": [ "{{ if gt .Code 0 }}#AE1401{{ end }}"],
      "template": "❯ "
  },
``` 

This, however, leads to the following result:

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/2781095/11a355b9-48d6-4cae-823b-b1dcaa918777)

The prompt ❯ that is colored is the final `echo "hello"`, rather then the failing `hello` statement. Is there a way to make the error code of the statement available to transient prompt, so that the foreground template is applied to the incorrect statement?

**Comment by JanDeDobbeleer** [comment]
@MatthiasKainer short answer, no. The transient prompt is generated before the command is ran:

- press ENTER
- the transient prompt is generated
- command runs
- new prompt is generated

So, the transient logic doesn't know the command result at that time.

**Comment by MatthiasKainer** [comment]
I feared that to be the answer - thanks for looking into it though, and for your awesome work!
