### ISSUE TITLE
Make parent directory as name if venv name is default optionable

### ISSUE THREAD

**Issue by ergz** [JanDeDobbeleer/oh-my-posh#4561]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Since the release of version v18.18.0, when a virtual environment (venv) has the default name, the prompt displays the parent directory's name. This is usually fine, but when I have long folder names the prompt starts to take too much space. It would be nice if this was an option, especially since this is the way oh-my-posh has worked for a while now. 

This is the PR that merged this new functionality #4400

Thanks!

**Comment by JanDeDobbeleer** [comment]
@ergz if the folder name is too long, you can always make it the max length you want using the template function `trunc` or `abbrev` from sprig's [string functions](http://masterminds.github.io/sprig/strings.html).
