### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by kkebo** [JanDeDobbeleer/oh-my-posh#4585]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be nice if oh-my-posh was available on FreeBSD.

**Comment by kkebo** [comment]
Thank you so much!

**Comment by JanDeDobbeleer** [comment]
@kkk669 let me know if it works!

**Comment by kkebo** [comment]
@JanDeDobbeleer It worked perfectly! Thank you.

(FreeBSD 14.0-RELEASE-p4 amd64, fish 3.6.1)

![IMG_0329](https://github.com/JanDeDobbeleer/oh-my-posh/assets/601636/afce8212-4193-4a53-bd85-337fb3465f89)

By the way, it seems that the `-d` flag of `install.sh` is broken. I modified `install.sh` and used my own.

- fix `-d` https://github.com/kkk669/oh-my-posh/commit/02ed3ba661b31ec1b67c289014e6409d5b3d215f
- modify `SUPPORTED_TARGETS` https://github.com/kkk669/oh-my-posh/commit/4fc1461a94059f15b671f94cd440f231bafa39fa

**Comment by JanDeDobbeleer** [comment]
Mind creating a PR for those? Great additions!

**Comment by kkebo** [comment]
Ok, I'll create PRs.

**Comment by kkebo** [comment]
I created #4589 and #4590.
