### ISSUE TITLE
Symbol-less template variables

### ISSUE THREAD

**Issue by mfedatto** [JanDeDobbeleer/oh-my-posh#4607]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

As I've faced some third party consoles, like web shell, that I couldn't change the current font family, I'm working on a theme that works nicely with no special font needed. Although, I've found that some symbols are embedded within the values, like branch icon in .HEAD for git type. It would be very nice to have an alternative variable in the templates to gather the value with no symbols and some extra variables, so the theme may decide how to render the given context.

**Comment by JanDeDobbeleer** [comment]
@mfedatto these are available, you can swap that out with `branch_icon`. There are some minimal themes that already have these swapped, you can check those for reference. Nothing is hardcoded in that area.

Check the icons section [here](https://ohmyposh.dev/docs/segments/git#icons).

**Comment by mfedatto** [comment]
Well, that is the icon without the text. What I meant was to get the text without the icon. Looking at the docs couldn't find a way to do so.

**Comment by JanDeDobbeleer** [comment]
@mfedatto you can remove that using `"branch_icon": ""` for example. Unsetting is supported.

**Comment by mfedatto** [comment]
That done the trick, thanks! Hadn't figured out the proper way to use properties, my bad.
