### ISSUE TITLE
Windows ARM64 support

### ISSUE THREAD

**Issue by libewa** [JanDeDobbeleer/oh-my-posh#461]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide

- [x] I looked for duplicate issues before submitting this one

### Description

On Windows, ARM64 still isn't working. PowerShell throws (sorry, it's German):
```
Fehler beim Ausführen des Programms "posh-windows-amd64.exe": Die angegebene ausführbare Datei ist keine gültige
Anwendung für diese Betriebssystemplattform.In
C:\Users\me\OneDrive\Dokumente\WindowsPowerShell\Modules\oh-my-posh\3.98.0\oh-my-posh.psm1:75 Zeichen:9
+         & $poshCommand -config $($_.FullName) -pwd $PWD
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
In C:\Users\me\OneDrive\Dokumente\WindowsPowerShell\Modules\oh-my-posh\3.98.0\oh-my-posh.psm1:75 Zeichen:34
+         & $poshCommand -config $($_.FullName) -pwd $PWD
+                                  ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
It means that `oh-my-posh` isn't for ARM64.

### Environment

- Oh my Posh version: 3.98.0
- Theme: any
- Operating System: Windows
- Shell: PowerShell
- Terminal: Windows Terminal 1.5.10411.0 (stable)

### Steps to Reproduce

1. Execute `Set-PoshTheme` on ARM64

**Expected behavior:** Change of Theme

**Actual behavior:** PowerShell throws the error mentioned above.

**Comment by JanDeDobbeleer** [comment]
@libewa you can use the 32 bit version on ARM, there should be emulation. Although fair point, we need to extend the functionality here (if golang permits).

**Comment by JanDeDobbeleer** [comment]
@libewa there's a dependency blocking the build for Windows ARM. I'm looking at how to circumvent this.

**Comment by JanDeDobbeleer** [comment]
@libewa can you validate the executable in the zip below? Let's have a look at if this has side-effects or not.

[posh-windows-arm.exe.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6055053/posh-windows-arm.exe.zip)

**Comment by JanDeDobbeleer** [comment]
@patriksvensson the binary above should be a windows arm64 build, maybe something you can help validate as well.

**Comment by patriksvensson** [comment]
@JanDeDobbeleer Absolutely. Will take a look later tonight when I'm at a computer.

**Comment by libewa** [comment]
I just double-clicked on it, 'cause I don't know the arguments. But there were no errors, so I think it works!
### Edit
Found out just now, that I need to copy it in the `oh-my-posh`-module folder and change `$poshCommand`. Now it throws

```
Invoke-Expression : Das Argument kann nicht an den Parameter "Command" gebunden werden, da es NULL ist.
In C:\Users\linus\OneDrive\Dokumente\WindowsPowerShell\Modules\oh-my-posh\3.98.0\oh-my-posh.psm1:53 Zeichen:23
+ ... ke-Expression (& $poshCommand --init --shell=pwsh --config="$config")
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.InvokeExpre
   ssionCommand
```
`Invoke-Expression: The argument cannot be binded to Param "Command" because it's NULL.`

**Comment by JanDeDobbeleer** [comment]
@libewa you can use `--version` to see if it prints its version. Using `--help` will also show what it can do.

**Comment by libewa** [comment]
It throws
```
oh-my-posh : Die Benennung "oh-my-posh" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder
eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ oh-my-posh --version
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (oh-my-posh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by libewa** [comment]
@JanDeDobbeleer how can I help to check some of the points in #463?

**Comment by JanDeDobbeleer** [comment]
@libewa the executable in the zip is called `posh-windows-arm.exe` so if you extract it somewhere, navigate to that folder in your terminal and execute `posh-windows-arm.exe --version` it should print the version name (or crash if incompatible).

**Comment by libewa** [comment]
Nothing happens. No error, no output.
I navigated to the extracted folder and typed `.\posh-windows-arm.exe --version`, but it waited shortly and had the old prompt again (`C:\Users\me\Downloads\posh-windows-arm\> `)

**Comment by JanDeDobbeleer** [comment]
@libewa @patriksvensson here's a new one, adjusted the version to display the current hash when using version. If I use this on my Windows amd64 it does not work :-)

[posh-windows-arm.exe.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6061522/posh-windows-arm.exe.zip)

**Comment by libewa** [comment]
I'll test tomorrow. @patriksvensson Can you test earlier?

**Comment by libewa** [comment]
Again... nothing happens.

**Comment by JanDeDobbeleer** [comment]
@libewa is there also no output when you run that executable without any parameters?

**Comment by patriksvensson** [comment]
I completely forgot this. Will take it for a run tomorrow.

**Comment by sheijden** [comment]
@JanDeDobbeleer I ran both the 32bit i386 and the ARM binaries. The i386 one displays a prompt when run, the arm binary does not show anything, no output.

**Comment by libewa** [comment]
> @libewa is there also no output when you run that executable without any parameters?

I never tried🤪

**Comment by libewa** [comment]
Tried just now, as @sheijden said... nothing
PS: How to install 32bit? It always installs x64 and says `this software is not executable on this machine`.

**Comment by JanDeDobbeleer** [comment]
@libewa you can find it underneath releases here.

**Comment by JanDeDobbeleer** [comment]
This is blocked due to not having a build infrastructure to create the binary for every release.

**Comment by lucloner** [comment]
I built Win Arm. the Windows Arm Branch is real perfect.

env:
>GOARCH=arm
GOOS=windows
GOPATH=C:\wsl-exchange\go\bin\windows_arm\go
GOROOT=C:\wsl-exchange\go\

golang:
>C:\ext\src>go version
go version go1.16.2 windows/arm
C:\wsl-exchange\go>git status
HEAD detached at go1.16.2

so I also build golang

you can build arm binary. here is log:

>C:\ext\src\oh-my-posh> cd src
C:\ext\src\oh-my-posh\src>go build -o \ext\src\oh-my-posh\bin
C:\ext\src\oh-my-posh\src>dir ..\bin
 Volume in drive C is Windows
 Volume Serial Number is 4AE4-D7D1
>
> Directory of C:\ext\src\oh-my-posh\bin
>
>2021/03/28  22:42    <DIR>          .
2021/03/28  22:42    <DIR>          ..
2021/03/28  22:42         9,430,016 oh-my-posh.exe
               1 File(s)      9,430,016 bytes
               2 Dir(s)  40,564,654,080 bytes free

C:\ext\src\oh-my-posh\src>..\bin\oh-my-posh.exe -version
development

C:\ext\src\oh-my-posh\src>..\bin\oh-my-posh.exe -debug

Here are the timings of segments in your prompt:

ConsoleTitle(true) -   1 ms -
session(true)  -   0 ms - █lucloner@Biggee-S-HuaWei█
path(true)     -   0 ms -   src█
git(true)      - 1407 ms - █ windows-arm ↑1█
battery(true)  -  39 ms - █27 
node(false)    -   3 ms -
shell(true)    -   0 ms -  ﲵ WindowsTerminal█
root(false)    -   0 ms -
text(true)     -   0 ms - █NO CONFIG█
exit(true)     -   0 ms -  █

**Comment by lucloner** [comment]
I believe it could built in x86 golang. I havn't tried.

**Comment by JanDeDobbeleer** [comment]
I tried it. Doesn't work as expected.

**Comment by lucloner** [comment]
> I tried it. Doesn't work as expected.

aha, your code is better then your expected.

**Comment by lucloner** [comment]
I tried the exe in Intel Win7 x64 and return "Not WIN32 Application". So I really build Arm exe. I post It.
[posh-windows-arm.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6217556/posh-windows-arm.zip)

That's All due to Go arm build???

**Comment by lucloner** [comment]
Well its mid night in China. I would compile it by golan x86 tomorrow. Good Luck!

**Comment by JanDeDobbeleer** [comment]
I could also compile it, but it doesn't work on an arm device in the end 😅

**Comment by lucloner** [comment]
> I could also compile it, but it doesn't work on an arm device in the end 😅

I will try the exe you posted. It would be ok.

**Comment by lucloner** [comment]
i m back. i tried your binary. and i reproduce your binary in arch linux that received same error.
that stub binary could execute but return nothing.
that i notice **errorlevel is -1073741819** !
errorlevel of my healthy binary is 0. 

here is full log. the healthy one.
[build.log](https://github.com/JanDeDobbeleer/oh-my-posh/files/6219275/build.log)

Next:
1. try build in win arm by golang x86
2. diff the log to find out

MayBe:
just a bug in dependency.
or Bug from Google??

**Comment by lucloner** [comment]
the error is from cross compile.
but not shown in normal compile by go woa.

so weird.

[build32.log](https://github.com/JanDeDobbeleer/oh-my-posh/files/6219893/build32.log)

windbg is: (left is the stub)
![posh_woa](https://user-images.githubusercontent.com/3920443/112799550-14ead200-90a1-11eb-97c7-91917b879052.png)

**Comment by libewa** [comment]
Wait, I don't understand all this stuff at a time! What's the problem we're facing right now?

**Comment by JanDeDobbeleer** [comment]
@libewa long story short, cross compilation fails. Compiling on ARM succeeds. But there aren't any ARM build machines here so I need to check if I can do something on Azure for example. That could resolve everything.

**Comment by lucloner** [comment]
> @libewa long story short, cross compilation fails. Compiling on ARM succeeds. But there aren't any ARM build machines here so I need to check if I can do something on Azure for example. That could resolve everything.

hey. you need a raspberry pi 4B+ 4G ram or above which could install windows arm.

**Comment by libewa** [comment]
Does surface pro x SQ1? Work too?
Because I don't want to buy windows again

**Comment by JanDeDobbeleer** [comment]
> @lucloner hey. you need a raspberry pi 4B+ 4G ram or above which could install windows arm.

There's no official Windows build that supports this yet. Until I can find a sustainable way to get this build in a setup that's not tweaked by someone at home (no disrespect, just can't trust that) this stays blocked.

**Comment by lucloner** [comment]
> 
> 
> > @lucloner hey. you need a raspberry pi 4B+ 4G ram or above which could install windows arm.
> 
> There's no official Windows build that supports this yet. Until I can find a sustainable way to get this build in a setup that's not tweaked by someone at home (no disrespect, just can't trust that) this stays blocked.

there're other choices. but no better. 
qemu is very lag.

embedded system installation is different from pc. for raspi is u-boot and some deployed (unzipped) file system. 
price is fair.
official installer is windows iot. yes, it could run golang and powershell. ui is very ... cool.
I tried in my raspi 3b. a bit lag for no video accelerate.

> 
> 
> Does surface pro x SQ1? Work too?
> Because I don't want to buy windows again

yes

**Comment by JanDeDobbeleer** [comment]
> @lucloner official installer is windows iot

Yes, and it's no longer maintained.

**Comment by lucloner** [comment]
@JanDeDobbeleer trust is cheap. just upgrade your magic resistance. :smile: 

@libewa just unzip the posh-windows-arm.zip i posted above.
just replace the file
`<User Dir>\Documents\WindowsPowerShell\Modules\oh-my-posh\<Version>\bin\posh-windows-amd64.exe`
whith same name.
**it is just for windows arm64 device such as surface x**

or might in Program Files\WindowsPowerShell\
good luck!

**Comment by libewa** [comment]
THX

**Comment by libewa** [comment]
It's working!!!
![omp-slim](https://user-images.githubusercontent.com/67926131/113988436-c3d0a000-984f-11eb-9394-f434aefe7577.jpg)
