### ISSUE TITLE
oh-my-posh cannot be installed on Windows 10 Powershell

### ISSUE THREAD

**Issue by RiikkaDream** [JanDeDobbeleer/oh-my-posh#4615]
## Suggestion to fix 
Add this critical step that was missing, to the installation tutorial.
`$env:Path += ";C:\Users\user\AppData\Local\Programs\oh-my-posh\bin"`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Steps to replicate:

1 Open powershell
2. Follow the instructions at https://ohmyposh.dev/docs/installation/windows
3. 
[windows#installation](https://ohmyposh.dev/docs/installation/windows#installation)
`winget install JanDeDobbeleer.OhMyPosh -s winget` 
[fonts#installation](https://ohmyposh.dev/docs/installation/fonts#installation) (outputs 
`Import-Module oh-my-posh` nothing)
`oh-my-posh font install`

### Expected behaviour:

The font install successfully.

### Actual behaviour:

```
oh-my-posh : The term 'oh-my-posh' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of    
the name, or if a path was included, verify that the path is correct and     
try again.
```

#### Content of `Microsoft.PowerShell_profile.ps1`

```
Import-Module posh-git
Import-Module oh-my-posh
oh-my-posh init pwsh | Invoke-Expression
```

### Theme

Nothing, as the installation does not get that far.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
oh-my-posh : The term 'oh-my-posh' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of    
the name, or if a path was included, verify that the path is correct and     
try again.
At line:1 char:1
+ oh-my-posh debug --plain
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (oh-my-posh:String) [], Comma  
   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by JanDeDobbeleer** [comment]
@RiikkaDream the installer should do that for you. Sometimes a restart of the shell/device is required for it to populate everywhere though.

**Comment by RiikkaDream** [comment]
Even with a fresh shell, 
`$env:Path += ";C:\Users\user\AppData\Local\Programs\oh-my-posh\bin"`
was required. And that is a faster and easier way than restarting the device anyway. Could you please add this line? It will save massive amounts of time when debugging installation problems.

**Comment by RiikkaDream** [comment]
It is not really "completed".

**Comment by RiikkaDream** [comment]
Here is a suggestion ready to merge

https://github.com/JanDeDobbeleer/oh-my-posh/compare/main...RiikkaDream:oh-my-posh:main
