### ISSUE TITLE
Cause Win10 Dev 21322 green screen(Attach dump log)

### ISSUE THREAD

**Issue by DustinWin** [JanDeDobbeleer/oh-my-posh#464]
### Prerequisites
- [ √ ] I have read and understand the `CONTRIBUTING` guide
- [ √ ] I looked for duplicate issues before submitting this one

### Description
After opening PowerShell and loading oh-my-posh, the computer will have a green screen.

### Environment
- Oh my Posh version: V3（V2 normal）
- Theme: PowerLine
- Operating System: Windows 10 Dev 21322
- Terminal: PowerShell

### Steps to Reproduce
1. Install Windows 10 Dev 21322;
2. Install Git(v2.30.1);
3. Run PowerShell as an administrator, and run the following commands in sequence:
`Set-ExecutionPolicy RemoteSigned`
`Install-Module posh-git`
`Install-Module oh-my-posh`
4. Run the following commands again in sequence 
`Import-Module posh-git`
`Import-Module oh-my-posh`
`Set-PoshPrompt -Theme PowerLine`
5. Create a new "WindowsPowerShell" folder in the "C:\Users\ [Your name] \Documents" directory, and create a new text document. Edit the following content:
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme PowerLine
Save as "Microsoft.PowerShell_profile.ps1".
6. Restart the computer, run PowerShell again as an administrator.

**Expected behavior:** Oh-my-posh can be loaded normally, the computer will not have a green screen.

**Actual behavior:** The computer will have a green screen.

Attach dump log: 
[dump log.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6080954/dump.log.zip)

**Comment by JanDeDobbeleer** [comment]
@DustinWin what's a green screen? Also, the dump directs to a file on localhost (at least in the mobile app).

**Comment by DustinWin** [comment]
> @DustinWin what's a green screen? Also, the dump directs to a file on localhost (at least in the mobile app).
Thank you for your reply. My problem has been solved. This is a permission problem. You need to grant local user permissions in PowerShell.

**Comment by JanDeDobbeleer** [comment]
@DustinWin I'm still curious about the green screen though.

**Comment by DustinWin** [comment]
> @DustinWin I'm still curious about the green screen though.


It means "Blue Screen of Death". And I found that this is not a green screen caused by permission issues. The specific reason can only be viewed in the dump log.

**Comment by DustinWin** [comment]
[dump log.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6080915/dump.log.zip)
@JanDeDobbeleer Sorry, the log is attached here. Oh-My-Posh v2 is normal, but v3 will cause the system to green screen.

**Comment by DustinWin** [comment]
@JanDeDobbeleer 
I analyzed the dump log a little bit.
Possible causes of green screen: hardware_ram ( PAGE_NOT_ZERO )
**Analysis**: UNEXPECTED_KERNEL_MODE_TRAP_M (1000007f)
This means a trap occurred in kernel mode, and it's a trap of a kind
that the kernel isn't allowed to have/catch (bound trap) or that
is always instant death (double fault).  The first number in the
bugcheck params is the number of the trap (8 = double fault, etc)
Consult an Intel x86 family manual to learn more about what these
traps are. Here is a *portion* of those codes:
If kv shows a taskGate
        use .tss on the part before the colon, then kv.
Else if kv shows a trapframe
        use .trap on that value
Else
        .trap on the appropriate frame will show where the trap was taken
        (on x86, this will be the ebp that goes with the procedure KiTrap)
Endif
kb will then show the corrected stack.
Arguments:
Arg1: 0000000000000008, EXCEPTION_DOUBLE_FAULT
Arg2: ffffc201691efe70
Arg3: ffffdf888d977000
Arg4: fffff8072ec83125

**LAST_CONTROL_TRANSFER**:  from 0000000000000000 to fffff8072ec83125

**BUGCHECK_STR**:  0x7f_8

**STACK_TEXT**:  
ffffdf88`8d977000 00000000`00000000 : fffff807`2ec82a8b fffff807`2ea00000 fffff807`2ec80e18 ffffdf88`8d9775b0 : nt+0x283125

Hope to help you!

**Comment by JanDeDobbeleer** [comment]
@DustinWin can you try a two step approach? Remove the root segment and see if that resolves it, if that doesn't work, remove the session segment and see if that resolves it. If you would be so kind to let me know which one is troublesome, greatly appreciated. What I can see is that fetching your user information causes a panic (which is more a Windows bug than oh-my-posh).

**Comment by DustinWin** [comment]
> @DustinWin can you try a two step approach? Remove the root segment and see if that resolves it, if that doesn't work, remove the session segment and see if that resolves it. If you would be so kind to let me know which one is troublesome, greatly appreciated. What I can see is that fetching your user information causes a panic (which is more a Windows bug than oh-my-posh).

The latest Dev 21327 is completely normal when running PowerShell. It should be a system problem, not an oh-my-posh problem.

**Comment by DustinWin** [comment]
> @DustinWin can you try a two step approach? Remove the root segment and see if that resolves it, if that doesn't work, remove the session segment and see if that resolves it. If you would be so kind to let me know which one is troublesome, greatly appreciated. What I can see is that fetching your user information causes a panic (which is more a Windows bug than oh-my-posh).

Sorry to inform again. I newly installed Dev 21327 today, but the green screen still occurs. After I opened VS Code, the green screen appeared, and its dump log was exactly the same as before. I found the problem: VS Code enabled the "PowerShell Preview" terminal. In other words, it is a green screen event caused by PowerShell Preview.

**Comment by DustinWin** [comment]
> @DustinWin can you try a two step approach? Remove the root segment and see if that resolves it, if that doesn't work, remove the session segment and see if that resolves it. If you would be so kind to let me know which one is troublesome, greatly appreciated. What I can see is that fetching your user information causes a panic (which is more a Windows bug than oh-my-posh).

@JanDeDobbeleer Sorry to inform again. I newly installed Dev 21327 today, but the green screen still occurs. After I opened VS Code, the green screen appeared, and its dump log was exactly the same as before. I found the problem: VS Code enabled the "PowerShell Preview" terminal. In other words, it is a green screen event caused by PowerShell Preview.
