### ISSUE TITLE
Negative lookahead in "ignore_folders": "invalid Perl syntax" error

### ISSUE THREAD

**Issue by LeoDupont** [JanDeDobbeleer/oh-my-posh#465]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When using a regular expression containing a negative lookahead in the `"ignore_folders"` property of a segment, I get the following error:
```
oh-my-posh fatal error rendering kubectl segment:regexp: Compile(`^(?!C:\\dev\\).*$`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

Here is the segment description:
```json
{
	"type": "kubectl",
	"style": "powerline",
	"powerline_symbol": "\uE0B0",
	"foreground": "#000000",
	"background": "#ebcc34",
	"properties": {
		"prefix": " \uFD31 ",
		"template": "{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}",
		"ignore_folders": [
			"(?!C:\\\\dev\\\\).*"
		]
	}
}
```

### Environment

- Oh my Posh version: 3.101.1
- Theme: Custom theme
- Operating System: Windows 10 Pro 20H2 19042.804
- Shell: PowerShell 5.1.19041.610
- Terminal: Windows Terminal 1.5.10411.0

**Comment by JanDeDobbeleer** [comment]
@LeoDupont I'll have a look tomorrow in the afternoon. Been a while since I touched that part but from the look of it you're doing it right (might also lack tests that part).

**Comment by tradiff** [comment]
I show that go's regexp has never supported negative lookaheads. I'm not sure why the OMP documentation suggests that's possible. In fact there is even a unit test to validate the above error is thrown.

I think OMP will end up needing a separate property for this. `include_folders` or something like that.

Edit: I'm working on a PR for `include_folders` in case that's the direction we decide to go.

**Comment by JanDeDobbeleer** [comment]
> I'm not sure why the OMP documentation suggests that's possible.

@TravisTX I actually validated that. So sure I got that in a working state.

**Comment by JanDeDobbeleer** [comment]
@TravisTX ~~I just looked at the code and that's a bug, that test was different. Something I missed when we adjusted the way we handle regex (@lnu initiated that I think). So we should look at supporting this once again rather than introduce a new property.~~

EDIT: wait, it seems that this could've worked because it errored and we just return false in that case by swallowing the error. Because indeed, it doesn't seem supported.

**Comment by lnu** [comment]
@JanDeDobbeleer  I just had a look and you're right: before it was returning false and was swallowed. Having two separate properties for included/excluded folders seems an easy way to go and more reliable.

**Comment by JanDeDobbeleer** [comment]
@lnu agreed. I'll review in the afternoon. @TravisTX can you add the changes to the docs if you have time?

**Comment by tradiff** [comment]
> @TravisTX can you add the changes to the docs if you have time?

Oops, I was in the wrong folder when I did `git add .`  doc changes been pushed now.

**Comment by LeoDupont** [comment]
Awesome, you both rock ;)
