### ISSUE TITLE
Add Chocolatey as an install method for Windows

### ISSUE THREAD

**Issue by st3phhays** [JanDeDobbeleer/oh-my-posh#4654]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Chocolatey can be used to install Oh My Posh on Windows by using the command `choco install oh-my-posh`. This can be found on the [Chocolatey Community Repository](https://community.chocolatey.org/packages/oh-my-posh). It would be awesome to see this as an option on the[ install page](https://ohmyposh.dev/docs/installation/windows).

**Comment by VEERT00X** [comment]
I have created a *docs* PR #4661 that updates the documentation by including information about using Chocolatey as an installation and update method for [Oh My Posh](https://ohmyposh.dev/) on Windows.
