### ISSUE TITLE
Can’t build

### ISSUE THREAD

**Issue by Zahrun** [JanDeDobbeleer/oh-my-posh#4655]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Since commit https://github.com/JanDeDobbeleer/oh-my-posh/commit/91fb561de7b44dfe36bb1b0bccccaf561118b290, I get this error at build:
`segments/python.go:7:2: package slices is not in GOROOT (/usr/lib/go-1.18/src/slices)`
I guess slices should be added to https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/go.mod

### Theme

Any

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
N/A
```

**Comment by Zahrun** [comment]
Hum seems slices was added to go 1.21 so 1.18 may be too old

**Comment by Zahrun** [comment]
I was able to build with go 1.21

**Comment by JanDeDobbeleer** [comment]
@Zahrun you need to upgrade go to 1.21 on your machine as per the mod file.
