### ISSUE TITLE
Problem with the new version

### ISSUE THREAD

**Issue by aaridoms** [JanDeDobbeleer/oh-my-posh#4679]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I just upgraded with scoop to the latest version and everything broke.

### Theme

I was using spaceship but changed to test if it was a problem with the theme.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
It: Cannot process argument transformation on parameter 'test'. Cannot convert the "use" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
Invoke-Expression: C:\Users\user\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:11
Line |
  11 |  … -config "$env:POSH_THEMES_PATH\agnoster.omp.json" | Invoke-Expression
     |                                                        ~~~~~~~~~~~~~~~~~
     | Missing argument in parameter list.
```

**Comment by aaridoms** [comment]
![Captura de pantalla 2024-02-12 204433](https://github.com/JanDeDobbeleer/oh-my-posh/assets/28603433/198fefe6-ddac-4bff-9a24-0dfecf9fc348)

**Comment by JanDeDobbeleer** [comment]
@aaridoms what do you have in your `$profile` for oh-my-posh?
