### ISSUE TITLE
Updating the homebrew cask fails with No available formula with the name "go@1.21"

### ISSUE THREAD

**Issue by chrisnruud** [JanDeDobbeleer/oh-my-posh#4689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Upgrading oh-my-posh using homebrew fails because of dependent go version.

### Theme

N/A

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
N/A, this is a homebrew - related issue:

`brew update && brew upgrade oh-my-posh
Already up-to-date.
Warning: Treating oh-my-posh as a formula. For the cask, use jandedobbeleer/oh-my-posh/oh-my-posh
==> Upgrading 1 outdated package:
jandedobbeleer/oh-my-posh/oh-my-posh 19.11.0_2 -> 19.11.1
Error: No available formula with the name "go@1.21" (dependency of jandedobbeleer/oh-my-posh/oh-my-posh). Did you mean go@1.20, go@1.19, go@1.18, go@1.17 or go@1.16?`
```

**Comment by JanDeDobbeleer** [comment]
@chrisnruud check. Made aware of that, I'm fixing this after walking the dog 🐕

**Comment by JanDeDobbeleer** [comment]
@chrisnruud should be solved
