### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by lkurzyniec** [JanDeDobbeleer/oh-my-posh#4695]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

If that's possible, It would be nice to have an update command. I could just type `oh-my-posh update` and magic would happen (I mean, the latest version would be installed). After all, restart of terminal and I have the newest version on my machine.

**Comment by marchello2000** [comment]
+1 this would be awesome

**Comment by JanDeDobbeleer** [comment]
@lkurzyniec this is a huge challenge depending on how you installed. For Windows, check. For macOS and Linux not so much.

**Comment by lkurzyniec** [comment]
Yeah, I could imagine that it can be a huge challenge. That's why I have added "If that's possible" :)

**Comment by nopeless** [comment]
ideally if you have installed a software using a package manager, the software should be managed and updated by the package manager.  This would be outside of the scope of oh-my-posh

**Comment by JanDeDobbeleer** [comment]
@nopeless exactly. Unless you went for a manual install, in which case running the same install command will upgrade the binary and included themes.

For those of you who request this, how did you install oh-my-posh?

**Comment by lkurzyniec** [comment]
I have installed by installer (windows, exe), but I have no problem to start using winget.

It's worth to consider to adjust install PS script (https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/website/static/install.ps1) to start using winget (or other package manager) as well.

**Comment by JanDeDobbeleer** [comment]
@lkurzyniec I don't mind seeing if we can add this for Windows only. Seems solvable.

**Comment by 392781** [comment]
> ideally if you have installed a software using a package manager, the software should be managed and updated by the package manager. This would be outside of the scope of oh-my-posh

Except there is no unified package manager for Linux... Homebrew is sort of a bandaid fix for that and running `curl` every time to update kinda sucks. Granted, packaging for major distros is a headache on its own.

**Comment by JanDeDobbeleer** [comment]
@392781 running curl or update internally is kind of the same logic that will be executed tbh.

**Comment by JanDeDobbeleer** [comment]
OK, this is funny. Inno installer can't replace oh-my-posh when the installer is being invoked from oh-my-posh as that means oh-my-posh is running and has a lock on it 😆 Works on unix though....

EDIT: solved with a go routine to allow the installer to start and oh-my-posh to stop

<img width="1048" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/2492783/1f379a73-0bc3-44d5-94b5-e6295bbaac88">
