### ISSUE TITLE
Invalid chars are there in prompt!

### ISSUE THREAD

**Issue by S3Y3D** [JanDeDobbeleer/oh-my-posh#470]
Hi Guys
I need help;
Unfortunately, invalid chars are there in prompt!
Font face property is set to "Cascadia Code PL" in windows terminal JSON settings file but still ...
Thanks 🌻
![Capture](https://user-images.githubusercontent.com/59525413/109427430-a7974300-7a07-11eb-838b-c4273b7ae11e.PNG)

**Comment by tradiff** [comment]
You're going to want to use a [nerd font](https://ohmyposh.dev/docs/installation#font).

Or use a theme that doesn't use any of the nerd font characters.  Of the default themes, those that have ".minimal" in their name don't use nerd font characters. There is only one minimal theme at this time, [hotstick.minimal.omp.json](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/hotstick.minimal.omp.json).

**Comment by JanDeDobbeleer** [comment]
Thx @TravisTX. There's a thread about this [here](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/427) @SMRHG
