### ISSUE TITLE
Use a development branch

### ISSUE THREAD

**Issue by oSumAtrIX** [JanDeDobbeleer/oh-my-posh#4701]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

# Issue

Currently, PRs and commits are directly merged into the main branch, leaving no window for proper review and scheduled releases.
Accordingly, bugs and problems are released directly, and releases are spammed for nearly every commit. I have noticed this because I am consuming the releases from the Winget repository and see a new release nearly daily.

# Propopsal

Add a development branch. There are many workflows to choose from, such as Git-Flow. PRs are developed in feature branches, reviewed, and (squash) merged into the development branch. After accumulating a handful of commits on the development branch, the branch can be merged into the main branch. Pre-releases are made for every commit on the development branch, whereas regular releases are made on the main branch. Regular releases will, therefore, contain more changes at a time, whereas the project can develop in the meantime in the development branch. 

This solves both issues mentioned above. Bugs can be squashed before releasing them due to a review window. Thanks to the feature and development branches, releases are no longer spammed. Instead, once seen fit, a release is made featuring multiple commits.

# Alternatives

An alternative workaround that would also solve both issues above would be to make workflows dispatchable instead of being on push. This will allow bugs to be squashed and multiple commits made into a single release.

**Comment by alexandreteles** [comment]
I know that changing workflows can be annoying, and that sometimes the slower pace of having a dev branch that accumulates changes can make it feel like the project is taking forever between releases, but I feel like this is probably a better solution than getting a new release for every commit.

This can also make broken changes affect less users (while also making it easier to fix or roll back such changes).

**Comment by JanDeDobbeleer** [comment]
@alexandreteles never going to happen. Development branches are a huge anti pattern.

**Comment by oSumAtrIX** [comment]
@JanDeDobbeleer For future reference, can you elaborate on what exactly outweighs the abovementioned issues? The development branch would prevent spamming full releases for nearly every commit and mitigate bugs, so what is weighing against this?

**Comment by JanDeDobbeleer** [comment]
@alexandreteles a development branch doesn't mitigate against bugs, that's an illusion. Every bug that finds its way outside isn't caught by adding a branch. It's caught by people using software in the wild. The amount of issues and accompanying severity illustrate that the project has its flow under control, it's really stable (other than a few individual events).

The "noise" argument makes no sense to me as that's a client trigger. No-one forces anyone to upgrade every release, you can do so at your own pace. In case you don't like the upgrade notice, feel free to disable it.

Every release adds to the stability and/or functionality of the project. And I will never change that. Git flow should never be the default as it's an anti pattern in the development industry. Releases shouldn't be a conscious action, they just happen. As soon as you gate keep it, regardless how, you never put in the work to create a reliable delivery pipeline as it's easier to work around it. We're all lazy by default.

And yes, I'm very opinionated about this.

**Comment by oSumAtrIX** [comment]
@JanDeDobbeleer If you push commits to a development branch, the PR opening for that branch can be reviewed. The review process is done to squash bugs or other issues __before__ they reach the main branch. By not using a development branch, you skip this process and, therefore, the possibility to squash bugs or other issues __before__ they reach the main branch.

For this reason, the statement about development branches not even mitigating against bugs is wrong:

>  a development branch doesn't mitigate against bugs, that's an illusion 

The issue is visible in broad daylight in real application:

<img width="329" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/13122796/35ba47bd-a885-455f-9f17-6af0547bc910">

A commit was made to the main branch which broke the application for everyone that updated to that release. This issue would have been mitigated by a review process in a development branch. The review would ideally conclude both commits at once and the PR would be closed without having to release the bug to the people. 
There are plenty of other scenarios like this on the main branch that prevent someone from being confident that an update is stable. Because no development branch is involved, and therefore, no review process, one is required to think twice or more before updating. For that reason I disagree with your statement yet again:

> Releases shouldn't be a conscious action, they just happen

Releases should be done when appropriate. Instead of using the consumer as a testing medium, the review process will take this off the shoulders of the consumer.

You conclude, that every release adds to the stability of the project but push commits that have to be reverted shortly after, contradicting your conclusion:

> Every release adds to the stability and/or functionality of the project

Because I understand your issue that comes with caring about delivery pipelines, I had originally added an intermediate solution to the issue description that, both solves the issues I mentioned originally and does not require development branches:

> An alternative workaround that would also solve both issues above would be to make workflows dispatchable instead of being on push. This will allow bugs to be squashed and multiple commits made into a single release.

**Comment by JanDeDobbeleer** [comment]
@alexandreteles you're confusing the lack of a development branch with the lack of CI. I don't push straight to main. Everything goes through a PR and is tested. The revert you highlight is a very exceptional case that git flow wouldn't have caught either. Sometimes things slip through, that'll always happen. But it's still the exception.

But, I'm done arguing about this in an issue. Wouldn't mind doing so in person, but this isn't the place. You'll bever convince me either, I even apply these practices with all the teams I'm managing today and in the past. It works, it makes people happy as it reduces overhead and forces people to focus on what matters. Adding value efficiently and not caring about overhead.
