### ISSUE TITLE
New segment request: Azure Developer CLI (`azd`)

### ISSUE THREAD

**Issue by SvenAelterman** [JanDeDobbeleer/oh-my-posh#4702]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

It would be very useful to see the config details, especially the selected subscription, of the Azure Developer CLI.

**Comment by JanDeDobbeleer** [comment]
@SvenAelterman can you share the command(s) you use for this? I don't use that CLI.

**Comment by ivan-the-terrible** [comment]
@SvenAelterman I see the documentation on https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/overview

I haven't read entirely through it, but I assume it's akin to the existing `az` and `azfunc` commands that exist here already.
