### ISSUE TITLE
Themes installed in /root/themes

### ISSUE THREAD

**Issue by PGScully** [JanDeDobbeleer/oh-my-posh#4731]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

If installing/updating as root (to install into /usr/local/bin) themes are installed into /root/themes.  I would expect a root/system wide install to put them into /usr/local/share/oh-my-posh/themes instead.

### Theme

n/a, it's an install problem

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
# curl -s https://ohmyposh.dev/install.sh | bash -s
Oh My Posh is already installed, updating existing installation in:
  /usr/local/bin

ℹ️  Installing oh-my-posh for linux-amd64 in /usr/local/bin
⬇️  Downloading oh-my-posh from https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
🎨 Installing oh-my-posh themes in /root/themes

🚀 Installation complete.

You can follow the instructions at https://ohmyposh.dev/docs/installation/prompt
to setup your shell to use oh-my-posh.

If you want to use a built-in theme, you can find them in the  directory:
  oh-my-posh init {shell} --config /{theme}.omp.json
```

**Comment by JanDeDobbeleer** [comment]
This can already be achieved using `install.sh -t /usr/local/share/oh-my-posh/themes`. We also respect the `OMP_CACHE_DIR` and `XDG_CACHE_HOME` variables to change the location of the cache.

**Comment by PGScully** [comment]
`/usr/local` is not writable by ordinary users, so sudo is required.

`sudo` does not pass/use any of the user's environment variables (obvious security hole to do so), so `OMP_CACHE_DIR` and `XDG_CACHE_HOME` are ignored.

Also, `install.sh` assumes sh is bash, but on Debian and Raspberry Pi it is dash, to the bash expansions on lines 65 (-d) and 137 (-t) cause errors.

**Comment by JanDeDobbeleer** [comment]
@PGScully I get that. This was designed based on other existing tool's installation scripts, and surely there's room for improvement. So if you have a better suggestion, feel free to add them here or create a PR, we can always improve how we do things.

And due to the scattered linux landscape and terrible packaging ecosystem, this is the only sustainable way to install as long as oh-my-posh doesn't pay my bills.
