### ISSUE TITLE
Allow the config {{ .Venv }} element to show the name of the virtual environment folder instead of the parent folder.

### ISSUE THREAD

**Issue by ZeroKlu** [JanDeDobbeleer/oh-my-posh#4756]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi,

First of all, you're awesome for making this available to all of us in the first place, and I'm still going to love your plug-in no matter how you respond to this request.

---

Up until a few versions ago, the {{ .Venv }} element in a theme configuration for Python used to show the name of the folder containing the virtual environment (".venv", e.g.). Now, it shows the name of the parent folder instead.

I understand the reasoning behind changing it to show the parent directory instead, as for some users, the name of the actual venv folder is not useful information.

For some folks though, we use this primarily as an indicator that a virtual environment is active, so it would be optimal for us to return to the old functionality of displaying the virtual directory folder name.

Would it be possible to add a true/false flag in the Python theme configuration to support switching back to the previous functionality for those of us who loved it the way it was?

Thanks!

**Comment by JanDeDobbeleer** [comment]
There's a switch for that already. It's called `folder_name_fallback`. Set it to `false` and you're good to go.

**Comment by ZeroKlu** [comment]
That's outstanding!

My apologies for missing that in the documentation. Thank you!
