### ISSUE TITLE
Brew on macOS 10.15 still pointing to 19.16.0 vs. 19.16.1

### ISSUE THREAD

**Issue by mdove** [JanDeDobbeleer/oh-my-posh#4766]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Brew on macOS 10.15 is picking up the 19.16.0 source to build, vs the very recently releases 19.16.1 source which allows comments in the config files and thus hitting CONFIG_ERROR as I have some sections commented in my config file.

Brew update; brew upgrade oh-my-posh still stuck on 19.16.0.  Even tried brew update -f, no change.

### Theme

Personally created theme which started with Jan's

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
You're probably using the non-official [oh-my-posh](https://github.com/Homebrew/homebrew-core/blob/master/Formula/o/oh-my-posh.rb) someone added in core and not [jandedobbeleer/oh-my-posh/oh-my-posh](https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/blob/main/oh-my-posh.rb).

**Comment by mdove** [comment]
You are right, my bad.  In the midst of migrating over to oh-my-posh on ~25 different machines, and slipped my mind that it wasn't officially part of the core.  Apologize for the trouble.  Everything working perfectly.
