### ISSUE TITLE
Root user required for installation on Linux 

### ISSUE THREAD

**Issue by leodario7** [JanDeDobbeleer/oh-my-posh#4772]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I tried installing oh-my-posh on Ubuntu 2204 following the online documentation [here](https://ohmyposh.dev/docs/installation/linux).

Similar to the issue [4073](https://github.com/JanDeDobbeleer/oh-my-posh/issues/4073), I get the same error. 

```
leo@leo:~$ curl -s https://ohmyposh.dev/install.sh | bash -s
Cannot write to /usr/local/bin. Please set a different directory and try again: 
  curl -s https://ohmyposh.dev/install.sh | bash -s -- -d {directory}
```
I tried removing the -s option. Still same error

```
curl  https://ohmyposh.dev/install.sh | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6700  100  6700    0     0  42244      0 --:--:-- --:--:-- --:--:-- 42405
Cannot write to /usr/local/bin. Please set a different directory and try again: 
  curl -s https://ohmyposh.dev/install.sh | bash -s -- -d {directory}
```

I tried using sudo, same error

```
sudo curl https://ohmyposh.dev/install.sh | bash -s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6700  100  6700    0     0  31643      0 --:--:-- --:--:-- --:--:-- 31603
Cannot write to /usr/local/bin. Please set a different directory and try again: 
  curl -s https://ohmyposh.dev/install.sh | bash -s -- -d {directory}
```

Since there is no way to proceed, I changed to root user, and managed to install it, but it should be adressed in the documentation if that is the only way to proceed. 

### Theme

Cannot install

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
Cannot install
```

**Comment by JanDeDobbeleer** [comment]
@leodario7 you need to change the directory. This is also explained in the [docs](https://ohmyposh.dev/docs/installation/linux#installation).

**Comment by leodario7** [comment]
@JanDeDobbeleer  it says that I can changed the directory if I **want**, not that I **must**.

**Comment by JanDeDobbeleer** [comment]
@leodario7 depending on how your system is set up, that's definitely not a must.

**Comment by wChris7s** [comment]
@leodario7 
```bash
sudo su
curl -s https://ohmyposh.dev/install.sh | bash -s
```

**Comment by CodeConnoisseur74** [comment]
@leodario7 This worked for me. Thanks!
