### ISSUE TITLE
node segment shouldn't use `.npmrc`

### ISSUE THREAD

**Issue by nopeless** [JanDeDobbeleer/oh-my-posh#4782]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

https://github.com/JanDeDobbeleer/oh-my-posh/blob/2596022db38b769e0b7201e88770f9a45332f75a/src/segments/node.go#L31-L47

```
pwd

Path
----
E:\Users\n

cat .\.npmrc
//registry.npmjs.org/:_authToken=npm_xxxxxxxx
```
Honestly I suggest just removing .npmrc from the list of files to check. 

### Theme

Including node segment

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by nopeless** [comment]
`"*.[cm]?[jt]s[x]"` should catch all js file variants

**Comment by JanDeDobbeleer** [comment]
@nopeless are there valid use case of `.npmrc` in node projects? Because if so, disabling the home folder for node is the right thing to do.

**Comment by nopeless** [comment]
@JanDeDobbeleer yes (useful in many cases), but should be better to check `package.json`, as `.npmrc` would be useless without it (the rationale is based off of the fact that pretty much any npm command involves package.json).

> side note: but now that I think of it, it doesn't work on my actual Windows user directory. I just didn't test it enough (I guess I hastily generalized). I changed the title to reflect this thought.

```
.node_repl_history
.npmrc
.nuxtrc
.yarnrc
```

These are my current relevant node files in my `E:\Users\n` directory. Relying on these to check might result in false positives.
