### ISSUE TITLE
Instalation on windows 32 bit

### ISSUE THREAD

**Issue by allgood** [JanDeDobbeleer/oh-my-posh#479]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

Instalation thorugh Install-Module command on Powershell downloads 64bit binaries always, even if running on 32bit installation.

### Environment

- Oh my Posh version: 3.105.0
- Theme:
- Operating System: Windows 10 home 32 bit
- Shell:
- Terminal:

### Steps to Reproduce

1. Run `Install-Module  oh-my-posh -Scope CurrentUser`
2. Run `Import-Module oh-my-posh`
3. Run `Set-poshPrompt Paradox`

**Expected behavior:**  Theme started

**Actual behavior:** Error trying to load 64bit binary on 32bit windows

![image](https://user-images.githubusercontent.com/6070736/109826185-4e066280-7c19-11eb-9c99-0a249e3e08d4.png)

**Comment by JanDeDobbeleer** [comment]
@allgood I'm going to be honest here for a moment. I had no idea 32 bit OS'es still existed in this day and age. Can be fixed though ;-)

**Comment by allgood** [comment]
I use on virtual machines when they will not need more than 4gb of RAM. But I understand you!

Em 3 de março de 2021 13:01:35 BRT, Jan De Dobbeleer <notifications@github.com> escreveu:
>@allgood I'm going to be honest here for a moment. I had no idea 32 bit
>OS'es still existed in this day and age. Can be fixed though ;-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/JanDeDobbeleer/oh-my-posh/issues/479#issuecomment-789822512

-- 
E-mail enviado do meu celular Android usando K-9 Mail. Por favor, desculpe minha brevidade.
