### ISSUE TITLE
feat: amrobytes - a new theme

### ISSUE THREAD

**Issue by Udayendu** [JanDeDobbeleer/oh-my-posh#4803]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

A new theme for simplified console experience with code and shell.

**Comment by JanDeDobbeleer** [comment]
@Udayendu we no longer accept theme additions, however you can join a discussion her, or our Discord channel and share it there.

**Comment by Udayendu** [comment]
> @Udayendu we no longer accept theme additions, however you can join a discussion her, or our Discord channel and share it there.

Sure !
