### ISSUE TITLE
PSConsoleTheme MUST be loaded before the oh-my-posh commands

### ISSUE THREAD

**Issue by thakyZ** [JanDeDobbeleer/oh-my-posh#481]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

When loading the PowerShell Profile Oh my Posh loading before PSConsoleTheme but the PSConsoleTheme sets it's color profile after it loads then does the Oh my Posh color theme afterwards like so:
```pwsh
Import-Module posh-git
Import-Module oh-my-posh
Import-Module PSConsoleTheme

Set-ConsoleTheme -Name "Google Dark"
Set-PoshPrompt -Theme agnoster
```
It throws this error:
![image](https://user-images.githubusercontent.com/950594/109846042-9f572780-7c02-11eb-902c-e598759c7312.png)

I already reported the bug at mmims/PSConsoleTheme#13

### Environment

- Oh my Posh version: 3.105.0
- Theme: agnoster
- Operating System: Windows 10
- Shell: PowerShell 7 Preview, PowerShell 7, and Powershell 5.1.19041.610
- Terminal: Windows Terminal and Default terminals for those three shells.

### Steps to Reproduce

1. Install Modules, PSConsoleTheme, post-git, and oh-my-posh
2. Setup profile like described above with example code.
3. Relaunch terminal.
4. Get errors.
5. Change the code to this 
```pwsh
Import-Module PSConsoleTheme

Set-ConsoleTheme -Name "Google Dark"

Import-Module posh-git
Import-Module oh-my-posh

Set-PoshPrompt -Theme agnoster
```
6. See that there is no more error.

**Expected behavior:**
The code works in any order when loading modules.

**Actual behavior:**
The code doesn't work and has to be loaded in a very specific order.

**Comment by JanDeDobbeleer** [comment]
@thakyZ that's because we override the V2 cmdlet [Get-Theme](https://github.com/JanDeDobbeleer/oh-my-posh/blob/636ec436eb152a2983cc40af63c8721638c997e3/packages/powershell/oh-my-posh/oh-my-posh.psm1#L159) to alert people they missed something in the upgrade. Either we remove that override, or they change the name of that internal function and we're good to go 😊

**Comment by mmims** [comment]
Other option is to set your profile like this:
```powershell
Import-Module posh-git
Import-Module oh-my-posh
Remove-Item Alias:\Get-Theme
Import-Module PSConsoleTheme

Set-ConsoleTheme -Name "Google Dark"
Set-PoshPrompt -Theme agnoster
```
