### ISSUE TITLE
A changelog file with breaking changes would be nice

### ISSUE THREAD

**Issue by biltongza** [JanDeDobbeleer/oh-my-posh#4813]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I just upgraded from v6 to v19. I know I can go look at the releases page to find all the specific changes, but there are _120_ pages in there. I understand it would be a duplication of effort, but I think it would be really nice if there was a way to see breaking changes (i.e. major releases) in one place. That way I can skim over it to see if there are any breaking changes I need to worry about.

The search function in releases isn't helpful either, searching for "v7.0.0" seems to return _all_ releases of the v7 branch.

**Comment by JanDeDobbeleer** [comment]
@biltongza  you can manipulate the release URL for this:

- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v19.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v18.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v17.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v16.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v15.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v14.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v13.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v12.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v11.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v10.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v9.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v8.0.0
- https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v7.0.0
