### ISSUE TITLE
[wish] introduce condition attribute on the segment

### ISSUE THREAD

**Issue by Banchio** [JanDeDobbeleer/oh-my-posh#483]
It would be cool to specify a env variable to be used as main switcher to enable/disable segments. When using Posh v2 I've accomplished this by introducing an if statement in my theme. 
With the declarative approach of v3 it is not clear to me if I can obtain the same result by creating a full theme and a light one and switch them using the powershell profile.
thanks!

**Comment by tradiff** [comment]
I'll let Jan chime in on whether he sees the feature request as valuable or not.

But I just want to mention that I think you can accomplish your specific goal today.  Basically what you said, create two themes, and swap between them using the command `Set-PoshPrompt -Theme agnoster`

**Comment by Banchio** [comment]
had other few time to work on it. Ended with a similar solution, two functions in my profile that first of all update the global env var (like before) and then use the set-poshprompt to switch between "full" and "light" prompt. Thanks for the answer, sorry to have wasted your time.

**Comment by tradiff** [comment]
Not a waste of time at all :)
