### ISSUE TITLE
Android AArch64 build

### ISSUE THREAD

**Issue by stevenxxiu** [JanDeDobbeleer/oh-my-posh#4831]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi, I see there's a <https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v19.20.0/posh-android-arm>. Could there be an *Android* AArch64 build? I tried <https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v19.20.0/posh-linux-arm64>, and parts of my config can cause it to crash.

Thanks so much for this btw. I just set up my config.

**Comment by stevenxxiu** [comment]
I created a PR for *Termux* to build this. [feat(oh-my-posh): add package by stevenxxiu · Pull Request #19747 · termux/termux-packages](https://github.com/termux/termux-packages/pull/19747).

**Comment by JanDeDobbeleer** [comment]
@stevenxxiu this makes no sense so help me out here. `aarch64` is `arm64` `v9`. We build for `v7` which should be compatible. But, in your termux build, oh-my-posh is built using `linux-amd64`, so I'm rather confused as to why that one should work.

**Comment by stevenxxiu** [comment]
When I last tested <https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v19.20.0/posh-android-arm>, I saw that the `command` and `git` segments crashed. I don't have something that's exactly reproducible atm, as my *Termux* PR got merged and I'm using that.

Where did you see me using `linux-amd64`? Are you talking about <https://github.com/termux/termux-packages/pull/19747/files>? *Termux* should be building it with each supported architecture.

**Comment by JanDeDobbeleer** [comment]
> I saw that the command and git segments crashed

@stevenxxiu can you show me the logs?

> Where did you see me using `linux-amd64`

It's what `termux_setup_golang` installs and I don't see any `GOARCH` or `GOARM` values being set anywhere.

**Comment by stevenxxiu** [comment]
> @stevenxxiu can you show me the logs?

I don't have that atm. I didn't save it when it crashed. Do those segments work for you in *Termux*? If you can't get it to crash I can try to test out my config later.

> It's what `termux_setup_golang` installs and I don't see any `GOARCH` or `GOARM` values being set anywhere.

This is set in <https://github.com/termux/termux-packages/blob/5bdbfc6b1a134a46e70708706f627e80da2d8d7e/scripts/build/toolchain/termux_setup_toolchain_26b.sh>.

**Comment by JanDeDobbeleer** [comment]
@stevenxxiu ok, cool. That shows some additional flags as we compile for that architecture already. I can adjust our build towards that. Also, I don't have an Android device ;-)

**Comment by JanDeDobbeleer** [comment]
@stevenxxiu can you try with [v20.2.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v20.2.0)

**Comment by stevenxxiu** [comment]
It still crashes.

The minimal reproducible examples are pretty small:

```yaml
- type: command
```

[oh_my_posh_command_error_log.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/15441793/oh_my_posh_command_error_log.txt)

```yaml
- type: git
```

[oh_my_posh_git_error_log.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/15441794/oh_my_posh_git_error_log.txt)

You could install some *Android* emulator to test it if you want.

I'm not too fussed about not fixing this, as I got it to build and work in *Termux*. One benefit is it will show people how it's built in a more minimal way than the *Termux* packages repo.

**Comment by JanDeDobbeleer** [comment]
Decided to close this as there are no additional requests. If anyone wants to pursue this, feel free.
