### ISSUE TITLE
iTerm2 shell integration

### ISSUE THREAD

**Issue by Jack-Works** [JanDeDobbeleer/oh-my-posh#4834]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hi, thanks for the amazing project! I found it can be improved when using iTerm2 by adding the following escape sequence:

It's all from https://iterm2.com/documentation-escape-codes.html

`\<Esc>]1337;CurrentDir=/home/jack/some-folder\<Bel>`

CurrentDir: Reports the current directory. It will be convenient to write this escape sequence in every Path prompt.

`\<Esc>]1337;RemoteHost=jack@machine-name\<Bel>`
RemoteHost: Reports the user name and hostname.

```
pwsh ~ >
    #^ add it here and it will be invisible. 
```

I tried to add it in my config but it does not work (the escape sequences are shown as literal texts) so I think maybe it should be built-in. Thanks!

**Comment by JanDeDobbeleer** [comment]
@Jack-Works I'll add that after my holidays!
