### ISSUE TITLE
Path style "full" displays Home Icon

### ISSUE THREAD

**Issue by AakashM** [JanDeDobbeleer/oh-my-posh#484]
### Prerequisites

- [✔] I have read and understand the `CONTRIBUTING` guide
- [✔] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]
Path style "full" displays Home Icon instead of the entire path

### Environment

- Oh my Posh version: 3.106.1
- Theme: powerline
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Navigate to Home directory "C:\Users\Username"

**Expected behavior:** Full directory path should be shown: "C:\Users\Username"

**Actual behavior:**  The character "~" is shown.

**Comment by tradiff** [comment]
You should be able to set `mapped_locations_enabled` to false, to disable that.  https://ohmyposh.dev/docs/path#properties

**Comment by JanDeDobbeleer** [comment]
@TravisTX @AakashM confirmed, also added that test case ;-)
