### ISSUE TITLE
plugin system like "oh-my-zsh"

### ISSUE THREAD

**Issue by xarthurx** [JanDeDobbeleer/oh-my-posh#4841]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I've been using this software for quite some time, and simultaneously use `oh-my-zsh` on my WSL or Ubuntu.
Both are quite amazing.

What is the most missed part in `oh-my-posh` is a similar plugin system.
It seems to me that `oh-my-posh` has a weight on decorating the PowerShell, but a bit less on the ease of use.

For instance, I can add a plugin `git` to OMZ so that:
`git status` --> `gst`
`git add . ` --> `gaa`

Or use the `z` plugin to quickly jump among past folders;

or use the `ubuntu` plugin to:
`agi` -->  `apt get install`
`agar` --> `apt-get auto remove`

I currently have a lot of customized alias and functions in my PowerShell profile file, to achieve the similar function I want from ZSH.

Is it possible to have something similar to ZSH's plugin system, so that users can extend the power of PowerShell?

**Comment by JanDeDobbeleer** [comment]
@xarthurx this was the first idea, but in true Unix philosophy, we moved the project to doing one thing right. Mainly, be the best prompt tool out there.
