### ISSUE TITLE
Firebase segment does not work on child folders

### ISSUE THREAD

**Issue by QuentinPhrl** [JanDeDobbeleer/oh-my-posh#4850]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Issue

The new Firebase segment proposed by @ivan-the-terrible only works at the root of a Firebase project. 

Here's an example in a firebase function project

<img width="894" alt="Prompt" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/87812493/d41dd716-768e-4d61-ac99-5fcfc87edaf7">

### Solution
As in the script I made to provide a solution before the official segment was created, all you need is the go equivalent of a startwith on the current prompt path

[https://github.com/QuentinPhrl/Omp_firebase_prompt/blob/6b6705349a0aeaccd2aaaef342bdb9e19ba27b4a/src/.firebase_project.zsh](url)

### Theme

cloud-native-azure

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
N/A
```

**Comment by ivan-the-terrible** [comment]
Working on a patch as we speak! It's as easy as `|| strings.HasPrefix(key, f.env.Pwd())`.

I'll get the code out and a proper test case for this asap!

**Comment by ivan-the-terrible** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/pull/4852
Fix has been raised.
