### ISSUE TITLE
symbols dont load

### ISSUE THREAD

**Issue by romhayh** [JanDeDobbeleer/oh-my-posh#488]
### Prerequisites

- [x] I looked for duplicate issues before submitting this one

### Description

as you can see in this picture, the symbols are not loaded correctly.
![image](https://user-images.githubusercontent.com/55787256/110222452-f9920a00-7eda-11eb-85d4-e2ab618bc4a1.png)
I get the squares instead

### Environment

- Oh my Posh version:
   v1 branch main
- Theme:
     paradox
- Operating System:
     windows 10
- Shell:
     powershell
- Terminal:
    windows terminal
- Font
    cascadia code PL

**Comment by JanDeDobbeleer** [comment]
@romhayh that's because CCPL doesn't contain those glyphs. See [here](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/427) for more context.
