### ISSUE TITLE
Error recognizing posh-windows-amd64.exe file after customize PowerShell profile

### ISSUE THREAD

**Issue by dunaev-k-s** [JanDeDobbeleer/oh-my-posh#495]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I am getting an error when starting Windows Terminal after trying to set a Paradox theme in my PowerShell profile.

I have Russian PowerShell - it`s translation from Russian:
```
&: The name "C: \ Users \ ╨Ъ╨░╤Б╤Б╨░ \ Documents \ WindowsPowerShell \ Modules \ oh-my-posh \ 3.106.6 \ bin \ posh-windows-amd64.exe" is not available
recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name, and
 See also the presence and correctness of the path, and then try again.
line: 1 character: 23
+ ... ression (@ (& "C: \ Users \ ╨Ъ╨░╤Б╤Б╨░ \ Documents \ WindowsPowerShell \ Modules \ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
    + CategoryInfo: ObjectNotFound: (C: \ Users \ ╨Ъ╨░╤Б ... ndows-amd64.exe: String) [], CommandNotFoundException
    + FullyQualifiedErrorId: CommandNotFoundException

Invoke-Expression: Cannot bind argument to "Command" parameter because it is an empty string.
line: 1 character: 19
+ ... -Expression (@ (& "C: \ Users \ ╨Ъ╨░╤Б╤Б╨░ \ Documents \ WindowsPowerShell \ Modu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
    + CategoryInfo: InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId: ParameterArgumentValidationErrorEmptyStringNotAllowed, Microsoft.PowerShell.Commands.Invo
   keExpressionCommand
```
Screenshots on Monosnap:
1. https://monosnap.com/file/GC9CLQ4TJfqCBiBPX4sNzQkH5Hubq8
2. https://monosnap.com/file/5Wg7UAYfNgvTnfofp69iqBhPi9ZGTU
3. https://monosnap.com/file/g2d1Nw8ZDTozTLBBx4TjMutqUtUfnG

- Oh my Posh version: 3.106.6
- Theme: Paradox
- Operating System: Windows 10 20H2
- Shell: PowerShell
- Terminal: Windows Terminal Version: 1.6.10571.0

### Steps to Reproduce

1. Install `Cascadia Mono PL` on PC and add in PowerShell Settings.json
2. `Install-Module posh-git -Scope CurrentUser`
3. `Install-Module oh-my-posh -Scope CurrentUser`
4. `Install-Module -Name PSReadLine -Scope CurrentUser -Force -SkipPublisherCheck`
5. Create PowerShell profile `notepad $PROFILE`
6. Add in PowerShell profile 
`Import-Module posh-git`
`Import-Module oh-my-posh`
`Set-PoshPrompt -Theme paradox`
7. Restart Windows Terminal

**Expected behavior:** Windows Terminal will start with Paradox theme enabled

**Actual behavior:** Windows Terminal will start with error

**Comment by JanDeDobbeleer** [comment]
@dunaev-k-s Powershell doesn't yet default to UTF8 and I don't want to force it yet from omp.

**Comment by dunaev-k-s** [comment]
@JanDeDobbeleer Will the code work if I exclude the сyrillic from the path?

**Comment by JanDeDobbeleer** [comment]
@dunaev-k-s I was too fast there 😓 You can add this to the top of your `$PROFILE`:

`[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

**Comment by dunaev-k-s** [comment]
@JanDeDobbeleer Yes, It`s work. Thank you very much.
