### ISSUE TITLE
Can't set custom title

### ISSUE THREAD

**Issue by NebularNerd** [JanDeDobbeleer/oh-my-posh#4954]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

This is more likely a user issue than a bug. 

I use a small script to change the title of the currently open shell:
```
param([string]$a)
$host.ui.RawUI.WindowTitle = $a
```

But with oh-my-posh this no longer works as it override anything I set. How do I disable or replicate this functionality in oh-my-posh?

### Theme

This is more likely a user issue than a bug. 

I use a small script to change the title of the currently open shell:
```
param([string]$a)
$host.ui.RawUI.WindowTitle = $a
```
This allows me to name each tab either manually or through a currently running script (e.g. `Dave`, `GitHub Thing` etc...)
But with oh-my-posh this no longer works as it override anything I set. How do I disable or replicate this functionality in oh-my-posh?

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
n/a as not an error
```

**Comment by JanDeDobbeleer** [comment]
If you remove the [console title template](https://ohmyposh.dev/docs/configuration/title), this will work (or adjust the title template to display what you need).

**Comment by NebularNerd** [comment]
Found it, it was at the bottom of the theme file not the top. Knew it was me 😂

Is there a way to set the ability for oh-my-posh to control the console title while running?

**Comment by JanDeDobbeleer** [comment]
You can always set an environment variable which can be used in the title template.

**Comment by NebularNerd** [comment]
OK, so if I set:
`"console_title_template": "{{.Env.MYTITLE}}"`

Then set an env variable with `$Env:MYTITLE = "Powershell - Awesome Title"`

That's going to change all tabs, not just the open one.
