### ISSUE TITLE
White background or light themes compatibility

### ISSUE THREAD

**Issue by betancour** [JanDeDobbeleer/oh-my-posh#497]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: v2
- Theme:
- Operating System: Windows10 PS
- Shell: PS
- Terminal: Windows Terminal

### Steps to Reproduce

1. [First Step]
Use any white or light background theme

**Expected behavior:** [What you expected to happen]
non display black colors and maintain the shape of markers 
**Actual behavior:** [What actually happened]

Post black paths inside the markers 

![image](https://user-images.githubusercontent.com/283403/110384625-adf77180-803c-11eb-89d2-ba2e8602bbcd.png)

**Comment by JanDeDobbeleer** [comment]
@betancour that's a Windows Terminal issue. I'll reproduce this on iTerm just to be 100% sure but it's known that Windows Terminal has issues with [inverted ANSI](https://github.com/microsoft/terminal/issues/7014).

**Comment by JanDeDobbeleer** [comment]
@betancour confirmed:

https://user-images.githubusercontent.com/2492783/110386808-0fc9d280-8061-11eb-95d9-fba8e28c58ef.mp4
