### ISSUE TITLE
Support duplicate pane / tab in Windows Terminal natively

### ISSUE THREAD

**Issue by MattKotsenas** [JanDeDobbeleer/oh-my-posh#4986]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Windows Terminal can open a new shell in the same working directory using it's "duplicate pane / tab" feature: https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory.

To accomplish this, the shell must emit a magic escape sequence that contains the current working directory. I have this working in my custom prompt today with the following segment:

```json
{
  "_comment": "// Emit control sequence so Windows Terminal can duplicate tabs / panes to the current working directory. See https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory",
  "type": "text",
  "style": "plain",
  "template": "{{if .Segments.Path.Location }}\u001b]9;9;\"{{ .Segments.Path.Location }}\"\u001b\\{{ end }}"
}
```

While it's possible to enable this with a custom segment, terminal's duplication feature has the "wow" factor to the point that I thought it might be worth supporting this in omp directly, either as a part of the default prompt theme, or as a property like `emit_windows_terminal_pwd_escape_sequence` on the Path segment.

If you feel this doesn't fit with the goals / direction of omp, feel free to close.

Thanks for the awesome work!

**Comment by JanDeDobbeleer** [comment]
@MattKotsenas this is available using the `pwd` [configuration parameter](https://ohmyposh.dev/docs/configuration/general#general-settings)[](https://ohmyposh.dev/docs/configuration/general#general-settings).

**Comment by MattKotsenas** [comment]
Oh! Will take a look! Sorry for wasting your time!

**Comment by JanDeDobbeleer** [comment]
@MattKotsenas you didn't. I need to adjust the docs so this can be found more easily.

**Comment by MattKotsenas** [comment]
I made a PR to the WT docs to mention that the escape sequence has a name: https://github.com/MicrosoftDocs/terminal/pull/779.
