### ISSUE TITLE
21.2.1 broke NetBSD source build

### ISSUE THREAD

**Issue by 0323pin** [JanDeDobbeleer/oh-my-posh#4997]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

21.2.0 is fine but, 21.2.1 breaks our builds, can't update package.

### Theme

NA

### Which shell are you using?

elvish

### Log output

```Shell
# github.com/jandedobbeleer/oh-my-posh/src/cli
cli/upgrade.go:27:12: undefined: upgrade.Run
cli/upgrade.go:42:11: undefined: upgrade.Run
*** Error code 1

Stop.
make[1]: stopped in /usr/pkgsrc/wip/oh-my-posh
*** Error code 1

Stop.
```

**Comment by JanDeDobbeleer** [comment]
Ah yea, I know why that happens. Can fix, although to be fair, I don't validate for netbsd, it's a bit off the record that one 😅

**Comment by 0323pin** [comment]
> Ah yea, I know why that happens. Can fix, although to be fair, I don't validate for netbsd, it's a bit off the record that one 😅

Ok! Bear with me, it's already enough to keep this on my own. There're reasons why I use NetBSD and, I'd be more than happy to talk about this on a private discussion 😄 

If the fix is easy, I'd appropriate it. Cheers!

**Comment by 0323pin** [comment]
One last thing ...

> I don't validate for netbsd

No, I understand that but, I do. I use `oh-my-posh` myself on my dev environment.
