### ISSUE TITLE
After changing the themes wrong font is loaded?

### ISSUE THREAD

**Issue by Cruik** [JanDeDobbeleer/oh-my-posh#5]
HEy,

i installed it like you provided but i guess the wring font is loaded.
Can you give me a hint what i am missing ?
![grafik](https://user-images.githubusercontent.com/5699060/93463845-a2768980-f8e8-11ea-9942-c4700ec054de.png)

**Comment by JanDeDobbeleer** [comment]
Interesting. It seems the terminal doesn't support ANSI characters, I might have to check that on a Windows machine itself. I used to develop this on ConEmu initially where everything worked, but it seems that's not necessarily true everywhere. I'll see what needs to be done here. Can you provide some information on your current setup (terminal/os/..)?

**Comment by Cruik** [comment]
Yeah sure. here is my current setup:
Windows 10 Enterprise
Version 1909

Windows Terminal
Version: 1.2.2381.0

PowerShell 7.0.3

I m using Windows Terminal which starts powershell which loads your Module (go-my-posh)

**Comment by JanDeDobbeleer** [comment]
I can reproduce this. But the fix is annoyingly hard. It comes down to ANSI color codes not working out of the box, and I need to enable that from an application POV. Stay tuned.

**Comment by Cruik** [comment]
Alright, keep up the good work!

**Comment by JanDeDobbeleer** [comment]
Found the issue, will push a new version!

**Comment by JanDeDobbeleer** [comment]
@Cruik you will also need [Meslo LGM NF](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip) to have the icons which are set in the theme.

**Comment by JanDeDobbeleer** [comment]
Almost there, the colors now render correctly but the prompt function is complaining on something.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/2492783/93671628-d696a980-faa4-11ea-9c46-9edb6b58c1b4.png">

**Comment by JanDeDobbeleer** [comment]
Getting closer, found why the rendering of the colors was broken but that effectively ruins the characters...
<img width="956" alt="image" src="https://user-images.githubusercontent.com/2492783/93686427-7ad51c00-fab6-11ea-806b-5e63abb38ab3.png">

**Comment by JanDeDobbeleer** [comment]
Fix that too, but I don't like the fix for now. I'm going to have a clear look in the morning and push a working build at that time.

**Comment by JanDeDobbeleer** [comment]
New version should be out ASAP. Can you confirm this now works on your machine as well?

**Comment by Cruik** [comment]
getting the same error as you with the promptfunction
88 the handle is invalid

**Comment by JanDeDobbeleer** [comment]
Ah yes. I forgot something obvious. That issue comes from a dependency where I did a fix locally, but then obviously I have to fork it and adjust 🤦🏻‍♂️

**Comment by JanDeDobbeleer** [comment]
@Cruik I just published `0.4.1` with the fix, on my machine when removing all other versions and a fresh install, it works.

**Comment by Cruik** [comment]
with the new version it works now on my machine.
The only character which is not displaying correctly is the arrow in the next line or am i missing there a font ?
![grafik](https://user-images.githubusercontent.com/5699060/93712511-9f80d080-fb56-11ea-88e2-cc1bcb67bf1f.png)

**Comment by Cruik** [comment]
i also noticed another missing character
the line above is the displayed line with go-my-posh
the line down under is from a terminal with oh-my-posh
![grafik](https://user-images.githubusercontent.com/5699060/93712608-47969980-fb57-11ea-88c0-6615741f73eb.png)

**Comment by JanDeDobbeleer** [comment]
Which font is that? I develop everything with MesloLGM NF. I'll update the README accordingly. You can tweak those settings easily by adjusting (or copy pasting the theme JSON, adjusting the icons and setting that file location as the theme. I really need to create that guide next.

**Comment by Cruik** [comment]
i used the wront, blame on me...
i used Cascadia Code PL, with the MesloLGMNF it displays fine!

Thanks for your work and your help!

**Comment by JanDeDobbeleer** [comment]
Thank YOU for trying this out and the donation! 🙏🏻
