### ISSUE TITLE
Conda virtualenv name is not part of the theme's formatting

### ISSUE THREAD

**Issue by V4G4X** [JanDeDobbeleer/oh-my-posh#500]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Tried looking for similar issues, but didn't find anything going over this exact issue.  
Conda's environment name is not being formatted.  
```$env:CONDA_DEFAULT_ENV``` prints ```base```.  
```$env:CONDA_ENV_NAME``` and ```$env:CONDA_ENV_PATH``` both are unset/empty.

Tried adding the following to ```oh-my-posh\current\themes\powerlevel10k_classic.omp.json```:  
```
{
  "type": "python",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "#100e23",
  "background": "#906cff",
  "properties": {
    "display_virtual_env": true,
    "display_default": true,
    "prefix": " \uE235 "
  }
},
```
But it didn't make any difference as ```display_virtual_env``` and ```display_default``` both default to ```true``` anyway,

### Environment

- Oh my Posh version: 3.107.0
- Theme: powerlevel10k_classic
- Operating System: Windows 10 Pro Insider Preview 64-bit (10.0, Build 21327) 
- Shell: Powershell 5.1.21327.1000
- Terminal: Windows Terminal

### Steps to Reproduce

1. Run conda Powershell Prompt on Window Terminal.   
Windows Terminal's settings.json uses this to run conda over Powershell  
```"commandline": "powershell.exe -ExecutionPolicy ByPass -NoExit -Command & 'C:\\Users\\varun\\miniconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\varun\\miniconda3'"```
2. Notice how the default conda virtualenv name is not formatted.

**Expected behavior:** Conda's virtualenv name should be formatted as part of the theme.

**Actual behavior:** Conda's virtualenv name is simply added to the left of the oh-my-posh theme formatting.

### Screenshots   
powerlevel10k_classic
![image](https://user-images.githubusercontent.com/34249137/110498296-351c1680-811d-11eb-8e21-9b4db80cf510.png)

jandedobbeleer:  
![image](https://user-images.githubusercontent.com/34249137/110498193-1e75bf80-811d-11eb-9804-c0b21d6be204.png)

**Comment by JanDeDobbeleer** [comment]
@V4G4X that's unrelated to oh-my-posh and related to the content of `conda-hook.ps1` that hijacks the prompt function (like we do). If you examine that file you should be able to find a switch that doesn't do that on activation (differs a bit per Python tool).
