### ISSUE TITLE
Certain glyphs cut off when they are the right-most symbol being rendered

### ISSUE THREAD

**Issue by stamminator** [JanDeDobbeleer/oh-my-posh#501]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Certain glyphs (for example `f7db` ![image](https://user-images.githubusercontent.com/10633170/110506964-97e5c180-80cd-11eb-8b18-6b4c552c6bf2.png)) are being cut off if there are no further glyphs to display other than the line terminator. I've confirmed that the issue takes place with both the CaskaydiaCove NF and MesloLGM NF fonts, presumably others as well.

![image](https://user-images.githubusercontent.com/10633170/110503870-a1b9f580-80ca-11eb-9c7d-26022ca6f267.png)

### Environment

- Oh my Posh version: 3.106.6
- Theme: agnoster, agnosterplus, nu4a, slim
- Operating System: Windows 10 19042.844
- Shell: PowerShell 7.1.2
- Terminal: Windows Terminal

### Steps to Reproduce

1. Open the shell at the home directory using one of the above-mentioned themes
2. Observe that the home icon is cut off
3. `cd` one level deeper so that the home icon is no longer the right-most symbol being rendered
4. Observe that the home icon no longer cuts off

![image](https://user-images.githubusercontent.com/10633170/110506484-2148c400-80cd-11eb-960d-ed557df3361c.png)

**Comment by JanDeDobbeleer** [comment]
@stamminator on first sight this smells like a Windows Terminal issue. I'll try to reproduce this in other terminals too.

**Comment by JanDeDobbeleer** [comment]
Ok, so did some test:

Doesn't happen on iTerm2 (macOS)

<img width="301" alt="image" src="https://user-images.githubusercontent.com/2492783/110518349-49a3e300-810c-11eb-98bd-c97275070192.png">

Doesn't happen on my Windows 10 VM running Terminal Preview:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/2492783/110518601-925b9c00-810c-11eb-8e4e-8912beffaf74.png">

This is definitely related to either the settings on your Windows Terminal or the Windows Terminal itself (I'm on the [Preview](https://www.microsoft.com/store/productId/9N8G5RFZ9XK3) version).

**Comment by tradiff** [comment]
I've seen this happen on lots of icons, and can confirm I see it on the house icon. It's related to the nerdfont you select.  And this is on both versions of windows terminal (normal and preview).  For example:
```
"fontFace": "MesloLGM Nerd Font Mono", // small icons but shows the entire icon
"fontFace": "MesloLGM Nerd Font", // large icons but cut off
```
Sadly, I don't believe OMP can do anything about this.

**Comment by JanDeDobbeleer** [comment]
@TravisTX @stamminator there was an issue about this in the Windows Terminal backlog but I can't seem to find it anymore (glyph spacing).

**Comment by tradiff** [comment]
Yeah I've seen it before.  This is probably the one you're thinking of:
https://github.com/microsoft/terminal/issues/5095

**Comment by JanDeDobbeleer** [comment]
@TravisTX Yes! Thank you!!!

**Comment by JanDeDobbeleer** [comment]
@stamminator until the Terminal team decides to fix this, moving to the mono variant fixes the issue.

**Comment by stamminator** [comment]
10-4. I tried playing around with inserting special space characters after the icon, like zero-width space (`"home_icon": "\uF7DB\u200B"`), but no luck. Ultimately, the only options I can see are switching to the mono font or inserting a regular space after the icon as a spacer to make room for the whole icon. Bummer, I like the larger icons.

**Comment by JanDeDobbeleer** [comment]
@stamminator you could always switch to ConEmu or another terminal. Although I admit, Windows Terminal is neat. They'll get there eventually though.
