### ISSUE TITLE
Website dependencies do not include `react-router-dom` for pnpm

### ISSUE THREAD

**Issue by FireIsGood** [JanDeDobbeleer/oh-my-posh#5020]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When building the docs website with `pnpm install` and then running with `pnpm start` (though that script name should probably be changed to `dev`), the website was unable to load citing a lack of "react-router-dom".

I believe this is due to `react-router-dom` not being explicitly added in `package.json` as checking the repo's history it appears in the `package-lock.json` consistently but not the `package.json` at any point.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/109556932/732a9687-356b-42a9-b97b-98fbbb64bf1c)

The expected result would have been to just load without issues.

A fix would be just installing it to support explicit imports for pnpm:

```bash
npm install react-router-dom
```

---

As a side note, this repo should probably have a website related issue or enable blank issues. While this issue is a bug report, the further fields did not make sense to fill in.

### Theme

n/a

### Log output

```Shell
n/a
```

**Comment by JanDeDobbeleer** [comment]
@FireIsGood but when using npm, this isn't an issue right?

**Comment by FireIsGood** [comment]
Yes, NPM seems to implicitly add it as a dependency as tested by deleting `node_modules` and `package-lock.json` and then running `npm install`.

A side effect of doing the above steps was that a ton of packages were updated and the node version was fixed from `21.2.0` to the intended `20.9.0`.

**Comment by JanDeDobbeleer** [comment]
@FireIsGood cool, let's merge your changes! Awesome to see someone tackle the website, that's definitely not my forte.
