### ISSUE TITLE
Add more issue templates

### ISSUE THREAD

**Issue by FireIsGood** [JanDeDobbeleer/oh-my-posh#5030]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I would like there to be more issue templates for more general problems such as the documentation website and GitHub repository.

## Problem

Currently, the two existing issue templates of Bug Reports and Feature Requests. These two are using the Issue Form template which is less flexible in what an issue is trying to communicate. If users wish to write about a problem that is not related to the program, they have to fill the form fields out with generic answers and potentially edit the issue after posting it to make more sense.

### 1. Go back to markdown issues (not the best)

As a very simple (though opinionated solution), the maintainers could change the issues to just be plain markdown issues so that users could modify them as needed. This is obviously opinionated as it would go back from the idea of issue forms.

Currently, Starship (the nearest comparison) has a similar two-issue template setup but specifically uses markdown and more generic fields which can be easily deleted due to just being markdown. The Issue Form template does not allow for removing fields except in post as an edit, so is not possible as stated above.

### 2. Add more issue types (on some scale for how many)

Another solution might be to add one or more issue types. Below I will discuss one possibility for a single new issue type, though this could be expanded further if that would work better.

A basic solution might be to have an additional 'Enhancement' issues, potentially as generic markdown file or simple (single text box under the Code of Conduct checkbox) form in the style of this one.

Two examples of the Enhancement issue are #4782 and #3617.

The current issues could be changed from:

> Bug Report
> File a bug report

> Feature Request
> Request a new feature

To be more specific with generics as a side note:

> :bug: Bug Report
> File a bug report about the prompt

> :rocket: Feature Request
> Request a new feature for the prompt

> :star_struck: Enhancement
> Suggest an enhancement to an existing feature

We can note that the Enhancement does not mention the prompt which may help issue writers understand that this is a more catch-all type of issue. I have added the emoji here to help differentiate them, though the emoji could just be added on their own to the two current issues.

This solution could potentially make the issues picking process slightly less streamlined. I'm unsure of how this would affect the user experience, but I would presume that more friction here would be less damaging than on the repo's README or other places since people with bugs or improvements would usually have more motive to report them than the average user who is just reading over the features page.

This solution also leaves a gap for any 'bug' type issues that are not related to the prompt, though I suspect those are rare enough that lacking an issue type might be fine in exchange for a less complicated user experience.

## Additional Notes

It is important to remember that most contributors cannot add or modify labels. As such, allowing for blank issue templates might create more problems than solutions.

I am willing to update the issue templates if any of the proposed solutions sound like a good idea.

**Comment by JanDeDobbeleer** [comment]
2 is the way to go, but I would make the third one "Other" being more free form.
