### ISSUE TITLE
Improve `Dotnet` segment

### ISSUE THREAD

**Issue by FineWolf** [JanDeDobbeleer/oh-my-posh#5040]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Add the following features to the `Dotnet` segment:

- Enable displaying Target Framework from `*.csproj`, `*.fsproj`, `*.xproj` files. (Read the [target framework moniker](https://learn.microsoft.com/en-us/dotnet/standard/frameworks) from [`TargetFramework`](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#targetframework) or [`TargetFrameworks`](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#targetframeworks))
  - Add variables for TFM, include raw moniker, plus version and OS (if specified).
  - Search current directory, or parent directories (up to repository root) for project files in order to display TFM.
- Enable heuristics to determine currently enabled SDK version without calling `dotnet --version`
  - Find a [`global.json`](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) in the current folder, parent folder, or the repository root (if within a repository).
  - If found, read version from CLI (which is slower)
- Add boolean settings to disable/enable version heuristics and to disable/enable TFM.

**Comment by FineWolf** [comment]
I can try to contribute a PR to implement those features.

**Comment by JanDeDobbeleer** [comment]
>Enable displaying Target Framework from *.csproj, *.fsproj, *.xproj files.

@FineWolf this is already done in the [project](https://ohmyposh.dev/docs/segments/project) segment. The entire idea of the `dotnet` segment is to let you know the `dotnet` CLI version, so I'm not sure if this is even desired behaviour.

**Comment by FineWolf** [comment]
Oh. I completely missed the `project` segment. 🤦 

Yup, that seems to do what I would like it to do. I'm closing this issue.
