### ISSUE TITLE
Refresh status on "ctrl + c"

### ISSUE THREAD

**Issue by pedrosousa13** [JanDeDobbeleer/oh-my-posh#5047]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

I'm coming from oh my zsh and before I would do `ctrl + c` and it would refresh the terminal status. this was especially useful for refreshing github status. Am I missing a config in zsh maybe?

**Comment by JanDeDobbeleer** [comment]
@pedrosousa13 this is a zsh question, falls outside the scope of oh-my-posh. You can actually use oh my zsh in combination with oh-my-posh to leverage their default bindings/extensions as well, or create your own handler to achieve this functionality.

**Comment by pedrosousa13** [comment]
Thank you for the clarification @JanDeDobbeleer . appreciate it

**Comment by JanDeDobbeleer** [comment]
@pedrosousa13 if you need any help/pointers, feel free to reach out.

**Comment by pedrosousa13** [comment]
Hi @JanDeDobbeleer sorry but I've been trying to find a way to do this but came up short. I would appreciate the pointers 😄
