### ISSUE TITLE
Change dir with git is slow on linux

### ISSUE THREAD

**Issue by evilz** [JanDeDobbeleer/oh-my-posh#505]
### Description

Very slow on linux when git exists.
It take many seconds to just  change directory.

### Environment

- Oh my Posh version: 3.108.0
- Theme: jandedobbeleer.omp.json with some change (no on git)
- Operating System: Ubuntu 20.04.2 LTS on Windows 10 x86_64
- Shell:  bash 5.0.17
- Terminal: Windows terminal

### Steps to Reproduce

go to a dir with any git

**Comment by JanDeDobbeleer** [comment]
That's the first time we have this on Linux. Can you set `enable_status` to false to see if that resolves it? Also, make sure you're on the latest version.

**Comment by evilz** [comment]
I dont see `enable_status` in doc ? do you mean `display_status`  ?

**Comment by JanDeDobbeleer** [comment]
@evilz oh damn yes, I'm sorry!

**Comment by evilz** [comment]
Ok,

It's clear 

with `"display_status": true`  it's very slow
with `"display_status": false` it's instantaneous.

**Comment by JanDeDobbeleer** [comment]
So somehow running git status is super slow for that repository. Can you time the output of that command in your shell?

**Comment by evilz** [comment]
![image](https://user-images.githubusercontent.com/2937862/110660675-158bf900-81c4-11eb-95c3-1510bb0c023f.png)

**Comment by evilz** [comment]
![image](https://user-images.githubusercontent.com/2937862/110660782-30f70400-81c4-11eb-9d06-0b699812343b.png)

**Comment by evilz** [comment]
OK, it's a issue on WSL2 already known. https://github.com/microsoft/WSL/issues/4197
But maybe a **timeout** should be add for all segment ?

**Comment by JanDeDobbeleer** [comment]
Good idea, although you'd want to control that though. I'll have a look.

**Comment by evilz** [comment]
Ok I think I got a idea of fix I will do a PR :)

**Comment by evilz** [comment]
Working perfectly now \o/ in v3.108.1
