### ISSUE TITLE
ansi codes not decoded in visual studio code terminal

### ISSUE THREAD

**Issue by DomDumont** [JanDeDobbeleer/oh-my-posh#5077]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

With the latest visual studio code, in the terminal, I see not decoded ansi codes  at the end of the prompt

### Theme

don't know , how can I check my theme ?

### What OS are you seeing the problem on?

Windows

### Log output

```Shell
my terminal prompt now looks like this : \x1b[0m\x1b[38\x3b2\x3b224\x3b222\x3b244min \x1b[38\x3b2\x3b75\x3b149\x3b233m\x1b[1mpwsh\x1b[22m\x1b[27m\x1b[38\x3b2\x3b224\x3b222\x3b244m
```

**Comment by sao-coding** [comment]
me too!
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/58339015/40bc703b-8011-49fc-acc2-436539c4334f)

But the computer terminal shows normal
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/58339015/f93306d7-1432-4fbb-b8e6-ba7d20f55747)

**Comment by sao-coding** [comment]
It should be a vscode problem
https://stackoverflow.com/questions/78595670/vs-code-1-90-powershell-is-escaping-ansi-escape-codes-like-x1b0m

**Comment by sao-coding** [comment]
https://github.com/microsoft/vscode/pull/215452
https://github.com/microsoft/vscode/issues/211922

**Comment by suppergerrie2** [comment]
Can confirm this is fixed in the latest vscode insiders version

**Comment by JanDeDobbeleer** [comment]
relates to https://github.com/microsoft/vscode/issues/211922

temporarily disable shell integrations to solve the issue for now:

```json
{
  "terminal.integrated.shellIntegration.enabled": false
}
```
