### ISSUE TITLE
v21.9.1 binary for Linux AMD64 download link broken

### ISSUE THREAD

**Issue by aerri** [JanDeDobbeleer/oh-my-posh#5083]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

The Linux AMD64 binary download link is broken for the version 21.9.1.
https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v21.9.1/posh-linux-amd64
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/26742294/6ba08e65-683f-4b0b-b331-6bd9964efbbd)

### Theme

Not applicable

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

zsh

### Log output

```Shell
⬇️  Downloading oh-my-posh from https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
Unable to download executable at https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
Please validate your curl, connection and/or proxy settings
```

**Comment by JanDeDobbeleer** [comment]
@aerri this highly likely an issue with the GitHub API as that binary was uploaded but somehow seems broken. I'll try to fix it.

**Comment by JanDeDobbeleer** [comment]
Currently rebuilding the broken binary locally.

**Comment by JanDeDobbeleer** [comment]
Updated
