### ISSUE TITLE
Checksum of v21.9.1 for linux/amd64 is wrong

### ISSUE THREAD

**Issue by suzuki-shunsuke** [JanDeDobbeleer/oh-my-posh#5087]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Download all assets with GitHub CLI. https://cli.github.com/manual/gh_release_download

https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v21.9.1

```sh
gh -R JanDeDobbeleer/oh-my-posh release download v21.9.1
```

Check checksum with a shell script.

check_sha256.sh

```sh
#!/usr/bin/env bash

set -euo pipefail

out() {
    while read -r file; do
        echo "$(cat "$file")  ${file%.sha256}"
    done < <(ls posh-*.sha256)
}

out | sha256sum -c
```

```console
$ bash check_sha256.sh
posh-darwin-amd64: OK
posh-darwin-arm64: OK
posh-freebsd-386: OK
posh-freebsd-amd64: OK
posh-freebsd-arm: OK
posh-freebsd-arm64: OK
posh-linux-386: OK
posh-linux-amd64: FAILED
posh-linux-arm: OK
posh-linux-arm64: OK
posh-windows-386.exe: OK
posh-windows-amd64.exe: OK
posh-windows-arm64.exe: OK
sha256sum: WARNING: 1 computed checksum did NOT match
```

```console
$ sha256sum posh-linux-amd64
ccd94aeeaa3bbaa994f313d3538653e730c16dc3a39fa749befd8e768505ba45  posh-linux-amd64
```

posh-linux-amd64.sha256

```
91A82AE1BC7156C97263B45894E2F3624087E19DC7A794FD530FD89D43C52D86
```

### Theme

-

### Log output

```Shell
-
```

**Comment by suzuki-shunsuke** [comment]
I'm not sure if this is related to this issue, bu only the timestamp of linux/amd64 `6 hours ago` is different from other assets `7 hours ago`.

https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v21.9.1

<img width="1007" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/13323303/d5df10cc-ae8d-4422-8ee7-5c39aecc24b5">

**Comment by SriRamanujam** [comment]
Might be related to https://github.com/JanDeDobbeleer/oh-my-posh/issues/5083

**Comment by JanDeDobbeleer** [comment]
@SriRamanujam @suzuki-shunsuke it is related. I had to rebuild.I'll see if I can install the right tools locally to get that file in.

**Comment by JanDeDobbeleer** [comment]
Solved
