### ISSUE TITLE
Include running command in console title template

### ISSUE THREAD

**Issue by Programie** [JanDeDobbeleer/oh-my-posh#5115]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

I would like to display the currently running command in my terminal title.

In case of zsh, this can be done by adding a preexec function which receives the executed command as first argument. But in case of bash, some more hacking with something like a debug trap is required.

Maybe this could be implemented in Oh My Posh to allow configuring it using the already existing console title template.

**Comment by JanDeDobbeleer** [comment]
@Programie this isn't possible as we add the console title in the printed prompt. So running commands will never be added during execution.

**Comment by JanDeDobbeleer** [comment]
@Programie an option is to use the built-in `set_poshcontext` functions, which work for bash, but zsh was a challenge:

### Bash
```bash
function set_poshcontext() {
    export COMMAND=$(history | tail -n1 | sed 's/^[ ]*[0-9]*[ ]*//')
}
```

**Comment by Programie** [comment]
Using `set_poshcontext` won't work as it is not executed before the command is being executed (i.e. in the preexec phase in zsh).

The example sets the `COMMAND` variable to the last executed command, but that happens AFTER the command finishes.

So, as you already pointed out in your first comment, this won't be possible.

I already got a working zsh preexec function which defines my terminal title containing the running command, but the same does not work perfectly in bash and I thought I could simplify it using the console title template feature of Oh My Posh.

Anyway... using Oh My Posh to set my terminal title might also be a bit out of scope, even if it's supported in some way. It's primary purpose is for rendering the prompt which has nothing to do with the terminal title.

**Comment by JanDeDobbeleer** [comment]
@Programie exactly, we currently only print the title in combination with the prompt, not as a separate action. While that can be done, it will also probably conflict with other people's expectations.
