### ISSUE TITLE
Linux ARM64 support

### ISSUE THREAD

**Issue by sidewinder94** [JanDeDobbeleer/oh-my-posh#512]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When trying to use the Set-PoshPrompt from the module in A Linux ARM64 environment, an execution error occurs

### Environment

- Oh my Posh version: 3.109.0
- Theme: default
- Operating System: Debian Buster ARM64 ( Linux 5.9.0-0.bpo.5-cloud-arm64 #​1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31))
- Shell: pwsh (7.1.2)
- Terminal: Windows Terminal (through SSH)

### Steps to Reproduce

1. Install powershell on Debian 10 ARM64
2. Install the oh-my-posh module
3. Import the module
4. Try and set a prompt theme

**Expected behavior:** The prompt theme successfully set

**Actual behavior:** The following error is displayed :

```
PS /home/freebox> Set-PoshPrompt -Theme robbyrussel
ResourceUnavailable: /home/freebox/.local/share/powershell/Modules/oh-my-posh/3.109.0/oh-my-posh.psm1:55

Line |
  55 |      Invoke-Expression (& $poshCommand --init --shell=pwsh --config="$ …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Program 'posh-linux-amd64' failed to run: Exec format errorAt
     | /home/freebox/.local/share/powershell/Modules/oh-my-posh/3.109.0/oh-my-posh.psm1:55 char:24 + …
     | ke-Expression (& $poshCommand --init --shell=pwsh --config="$config") +
     | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
```

I believe it to be quite similar to issue #461

**Comment by JanDeDobbeleer** [comment]
@sidewinder94 it's a little different as we actually have a working Linux ARM binary. It's just not shipped in the Powershell Module. I'll fix that for you.

**Comment by JanDeDobbeleer** [comment]
@sidewinder94 do you have a way to know the processor architecture from Powershell?

**Comment by sidewinder94** [comment]
@JanDeDobbeleer I know I saw it in `$PSVersionTable.OS` but not as the sole information, it contains the following string on my Linux system.

```
Linux 5.9.0-0.bpo.5-cloud-arm64 #​1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31)
```

To find if the OS is 64bit, there is `[System.Environment]::Is64BitOperatingSystem` which returns true on ARM64.

That would allow making an educated guess, but I feel this would be entirely too unreliable.

I couldn't find anything to clearly know the specific architecture of the current system using purely PowerShell.

**Comment by JanDeDobbeleer** [comment]
@sidewinder94 we already use that check to identify if we need to use the 32bit or 64bit binary, but that's still different when it comes to processor architecture. I also found the info in `$PSVersionTable.OS` but I was hoping to see a more typed property somewhere for reliability. I can add this "patch" knowing it could potentially break something else. Let's find out, shall we :-)

**Comment by JanDeDobbeleer** [comment]
@sidewinder94 can you tell me the output of `uname -m`?

**Comment by sidewinder94** [comment]
`uname -m` returns `aarch64`

**Comment by JanDeDobbeleer** [comment]
@sidewinder94 I think we'll find what we're looking when using `uname -p`. That specifically returns `i386` on my machine. I would expect yours to return `arm` or an equivalent.

**Comment by JanDeDobbeleer** [comment]
@sidewinder94 I think we'll find what we're looking when using `uname -p`. That specifically returns `i386` on my machine. I would expect yours to return `arm` or an equivalent.

**Comment by sidewinder94** [comment]
@JanDeDobbeleer This actually returns unkown on my side, but then this is a virtual machine so maybe it's because of that.

`uname -i` and `uname -p` are both returning unkown in fact.
