### ISSUE TITLE
Detect first/last prompt segment

### ISSUE THREAD

**Issue by Bilge** [JanDeDobbeleer/oh-my-posh#5121]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

P10K allows specifying different separator symbols from the end-caps. I cannot see how to achieve this with OMP since each segment is a fixed style, yet segments may not always be displayed (they are hidden conditionally). For example, to achieve a slash (`/`) separator for each segment with a chevron (`>`) end-cap, we can use diamond style and style the last git segment manually.

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/470626/60442f19-4f98-4fa8-8203-579dfa4428be)

This works fine unless and until we're not in a git directory, in which case the git segment becomes hidden and end-cap becomes the slash (`/`) instead of the chevron (`>`).

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/470626/5ccf3c2c-1af3-4362-a593-0fee08dbcaa5)

To be clear, we always want the end-cap to be the chevron (`>`), but this seems impossible to achieve unless we know which is the final segment (which we don't until runtime).

**Comment by JanDeDobbeleer** [comment]
@Bilge this is possible, I'll create a simple sample for this. The only thing that's harder is a start symbol but I don't see that use-case here. That would also require a color lookup ahead of time which is challenging, and where I draw the line.

**Comment by Bilge** [comment]
Isn't this whole project about drawing lines?

**Comment by JanDeDobbeleer** [comment]
@Bilge nice one. That's actually the terminal's responsibility ;-)

**Comment by JanDeDobbeleer** [comment]
Here you go:

```json
{
	"$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
	"blocks": [
	  {
		"alignment": "left",
		"segments": [
		  {
			"type": "os",
			"style": "plain",
			"foreground": "#1c1c1c",
			"background": "#D3D7CF",
			"template": " {{.Icon}} "
		  },
		  {
			"type": "path",
			"style": "diamond",
			"leading_diamond": "<parentBackground,background>\ue0bc</>",
			"foreground": "#ffffff",
			"background": "#3465A4",
			"alias": "A",
			"properties": {
				"style": "full"
			},
			"template": " {{ .Path }} "
		  },
		  {
			"type": "git",
			"style": "diamond",
			"leading_diamond": "<parentBackground,background>\ue0bc</>",
			"foreground": "#1c1c1c",
			"background": "#C4A000"
		  },
		  {
			"type": "text",
			"style": "diamond",
			"leading_diamond": "<parentBackground,background>\ue0bc</>",
			"foreground": "#ffffff",
			"background": "#0072C4",
			"template": " B ",
			"alias": "B"
		  },
		  {
		  },
		  {
			"type": "text",
			"style": "plain",
			"template": "<parentBackground,transparent>\ue0b0</>"
		  }
		],
		"type": "prompt"
	  }
	],
	"final_space": true,
	"version": 2
  }
```

**Comment by Bilge** [comment]
Presumably this wouldn't be a solution for the right-aligned portion of the prompt.

**Comment by JanDeDobbeleer** [comment]
@Bilge I've been going about this wrong. Powerline makes this an insane refactor. But when leveraging diamond segments like the example above, this can easily be defined above. I'll have a look at that, even if your example has a fixed, non conditional starting segment.

**Comment by Bilge** [comment]
Should we reopen this?

**Comment by JanDeDobbeleer** [comment]
I have this on my todo list. I got it.

**Comment by Bilge** [comment]
Is this new feature complete now? I don't really understand how to use it...

**Comment by JanDeDobbeleer** [comment]
@Bilge here you go:

```json
{
	"$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
	"blocks": [
	  {
		"alignment": "left",
		"leading_diamond": "\ue0b6",
		"trailing_diamond": "\ue0b0",
		"segments": [
		  {
			"type": "os",
			"style": "diamond",
			"foreground": "#1c1c1c",
			"background": "#D3D7CF",
			"template": " {{.Icon}} "
		  },
		  {
			"type": "path",
			"style": "diamond",
			"leading_diamond": "<parentBackground,background>\ue0bc</>",
			"foreground": "#ffffff",
			"background": "#3465A4",
			"alias": "A",
			"properties": {
				"style": "full"
			},
			"template": " {{ .Path }} "
		  },
		  {
			"type": "git",
			"style": "diamond",
			"leading_diamond": "<parentBackground,background>\ue0bc</>",
			"foreground": "#1c1c1c",
			"background": "#C4A000"
		  },
		  {
			"type": "text",
			"style": "diamond",
			"leading_diamond": "<parentBackground,background>\ue0bc</>",
			"foreground": "#ffffff",
			"background": "#0072C4",
			"template": " B ",
			"alias": "B"
		  }
		],
		"type": "prompt"
	  }
	],
	"pwd": "osc8",
	"final_space": true,
	"version": 2
  }
```
