### ISSUE TITLE
"disable_notice": true is not working as expected

### ISSUE THREAD

**Issue by joselcaguilar** [JanDeDobbeleer/oh-my-posh#5124]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I would like to have `auto_upgrade` and `disable_notice` set to `true`, however, when I open a new pwsh session (in my case 7.4.2) the upgrade notice is still visible at the beginning:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/7523585/643011ac-8d3e-426f-922d-a4fd102cc7ee)

### Theme

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "version": 2,
  "final_space": true,
  "auto_upgrade": true,
  "disable_notice": true,
  .....
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
NA
```

**Comment by JanDeDobbeleer** [comment]
@joselcaguilar this is by design, but you could argue that it's OK to only display the actual upgrade being done and not when there's no update available. I'll adjust that.

**Comment by joselcaguilar** [comment]
> @joselcaguilar this is by design, but you could argue that it's OK to only display the actual upgrade being done and not when there's no update available. I'll adjust that.

Yup, that's what I expected when `disable_notice` is set to `true`, thanks @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
I'm taking this in the PR I'm prepping for tomorrow probably.
