### ISSUE TITLE
how to Modifying Oh-my-posh theme?

### ISSUE THREAD

**Issue by lipecss** [JanDeDobbeleer/oh-my-posh#514]
I am installing Oh-my-posh, and install version 3.109.0.

I want to add in thema Paradox, before I did adding:

```
$ sl.PromptSymbols.StartSymbol = [char] :: ConvertFromUtf32 (0x01F984) + [char] :: ConvertFromUtf32 (0x0001F525) + ''
$ sl.PromptSymbols.PromptIndicator = [char] :: ConvertFromUtf32 (0x01F680) + [char] :: ConvertFromUtf32 (0x276F)
```

but the file is different now

**Comment by JanDeDobbeleer** [comment]
@lipecss V3 changed things around for good. You can use `Export-PoshTheme` to write the current theme to a new config file to tweak and set that file as your theme.

```powershell
Export-PoshTheme -FilePath ~/.mytheme.omp.json
// edit  ~/.mytheme.omp.json to your linking
Set-PoshPrompt -Theme /Users/jan/.mytheme.omp.json
```
