### ISSUE TITLE
Pass terminal width to command segment

### ISSUE THREAD

**Issue by VoxelPrismatic** [JanDeDobbeleer/oh-my-posh#5148]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

I am writing my own path segment interpreter (which implements p10k's anchor directories), but I cannot manage to fetch the terminal width inside the command.

- `tput cols` always returns 80 (as a fallback)
- `oh-my-posh get width` throws an error
- *`golang.org/x/`*`term.GetSize(1)` throws an error
- I cannot pass the parent's (oh-my-posh) parent's (zsh) PID as a file descriptor
- `/proc/<pid>/environ` doesn't hold COLUMNS or LINES
- No environment variables are set by OMP

I'm lost, tired, and just want a quick fix for this.

Goal:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/45671764/6c68ca33-b8e7-41db-bf8f-0e1873599671)

Golang error:
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/45671764/02c966b9-655b-48de-a8fd-66ef1128801e)
(executable works when run normally, just not via the omp command segment)

Setup:
[~/.omp.json](https://github.com/user-attachments/files/15942122/default.omp.json)
[~/.zsh/](https://github.com/user-attachments/files/15942123/default.zsh.zip) (extract; github doesn't like *.go)

**Comment by JanDeDobbeleer** [comment]
@VoxelPrismatic as this is executed in a subshell, it will never work unless we add that to the context so you can inject it. But then you have the challenge that this is never evaluated as a template either. 

Why not contribute this as a path style?

**Comment by VoxelPrismatic** [comment]
Well that's a whole other issue because I'd need to calculate the remaining width for the best experience.

In my case, I'm not changing the prompt all too often, so I can hardcode the cases I'm looking at.

**Comment by JanDeDobbeleer** [comment]
@VoxelPrismatic I gave this a lot of thought and the easiest, and also most performant way to achieve this is by running it from the shell directly using the override functions in oh-my-posh. That will run it inside the current zsh process and you should have access to everything from the get go:

```
eval "$(oh-my-posh init zsh)"

function set_poshcontext() {
    export POSH_PATH=$(~/.zsh/path)
}
```

And then change the `command` segment to:

```json
{
    "type": "text",
    "style": "powerline",
    "alias": "Path",
    "leading_powerline_symbol": "",
    "powerline_symbol": "",
    "invert_powerline": true,
    "foreground": "p:bg",
    "background": "p:path",
    "template": " {{ .Env.POSH_PATH }} "
}
```

**Comment by VoxelPrismatic** [comment]
does that run every time?

**Comment by VoxelPrismatic** [comment]
oh i see, previously i set the `set_poshcontext` *before* running init

**Comment by JanDeDobbeleer** [comment]
> does that run every time?

@VoxelPrismatic yes it does
