### ISSUE TITLE
Color and path in title problems with ANSI consoles

### ISSUE THREAD

**Issue by Ergamon** [JanDeDobbeleer/oh-my-posh#517]
### Prerequisites

- [x ] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: 3.109.0
- Theme: Paradox (customized)
- Operating System: Windows 10
- Shell: PowerShell 7.1.2
- Terminal: Cmder

### Steps to Reproduce

I am currently in the process of converting from v2 => v3. Really love the easy structure of the new format. Great job, makes customization so much easier.

There are some problems with the colors. Most terminals I use struggle with the free color selection. They also have their own themes defining colors. So I have to figure out how to customize all in build themes to the old color values. Really nasty for me is that the names are now different from the classic console color names. Maybe you could offer some themes with the classic 16 color support?

Anyway this I can fix myself, but my real problem is the fact that since v3 the current path information gets lost.

I have configured my Cmder with %d for the tab title. This was no problem with v2, but since I upgradet to v3 it does not work anymore.

Maybe this helps https://conemu.github.io/en/ShellWorkDir.html#bash_and_other_cygwin_shells

**Expected behavior:** [What you expected to happen]
The tab title shows the current directory

**Actual behavior:** [What actually happened]
The tab title does not change

**Comment by JanDeDobbeleer** [comment]
@Ergamon have a look at the console title [functionality](https://ohmyposh.dev/docs/configure#console-title-style). Basically, setting `console_title` to `true` will display the current folder in the title. You can tweak it with `console_title_style` or `console_title_template` for more advanced functionality.

**Comment by JanDeDobbeleer** [comment]
@Ergamon about colors, 16 ANSI colors are supported. No need to put in a lot of work, you can use your terminal theme's color scheme that way. See [colors](https://ohmyposh.dev/docs/configure#colors) for more info on that.

**Comment by Ergamon** [comment]
Lol, and I thought I read everything before stealing your valuable time. I now realize the console_title setting is global not in the path segment.

It still works quite different. ConEmu has this %d for using the current directory. This worked with v2, but not anymore with v3. But as you showed me this title thing, I can use %s for the current title instead. Basically the same result, but a different way to get there. I am fine with that ;)

As for the colors, this part of the documentation I read before. But the names still confuse me.

I mean if you open a powershell console and type
```
[ConsoleColor].GetEnumValues()
```
you get
```
Black       
DarkBlue    
DarkGreen   
DarkCyan    
DarkRed     
DarkMagenta 
DarkYellow  
Gray        
DarkGray    
Blue        
Green       
Cyan        
Red         
Magenta     
Yellow      
White       
```
These are the names I also see in Cmder. I am still in the middle of figuring out which color is which.

**Comment by JanDeDobbeleer** [comment]
@Ergamon well, the right colors are as they are defined for [ANSI](https://ss64.com/nt/syntax-ansi.html) (that's how oh-my-posh works). My best bet is that the darks map to actual colors and te regular colors are light. No idea why the standard isn't followed on Windows (probably a story there).

**Comment by Ergamon** [comment]
Probably the price for going platform independent. 

As written, I can figure the colors out, so all is fine.

Thx for providing a way to have the current directory back in my tab titles.
