### ISSUE TITLE
Problem with PSReadLine and InvokePrompt

### ISSUE THREAD

**Issue by Ergamon** [JanDeDobbeleer/oh-my-posh#518]
### Prerequisites

- [ x ] I have read and understand the `CONTRIBUTING` guide
- [ x ] I looked for duplicate issues before submitting this one

### Description

When you call the InvokePrompt method, the prompt gets messed up.

### Environment

- Oh my Posh version: 3.109.0
- Theme: Paradox
- Operating System: Windows 10
- Shell: PowerShell 7.1.2
- Terminal: Does not matter

### Steps to Reproduce

Open PowerShell (pwsh) and call

[Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()

**Expected behavior:** [What you expected to happen]
Nothing changes, just new prompt line.

**Actual behavior:** [What actually happened]
The previous prompt line gets messed up.

Propably a little tricky, but this worked without any problems in v2.

In case you are asking why I use this.
I basically have a list of favorite folders in my profile and I want to quickly change to these via keyboard shortcuts. I also have a shortcut for moving one directory up.

So in my profile I use this call:

```
Set-PSReadLineKeyHandler -Key "Ctrl+Pageup" -Description "Move to parent directory" -ScriptBlock {
  param($Key, $Arg)

  $Location = Get-Location
  $Directory = Get-Item $Location
  $Parent = $Directory.Parent

  if (-not $Parent) {
    return
  }

  Set-Location $Parent

  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}

Set-PSReadLineKeyHandler -Key Ctrl+0,Ctrl+1,Ctrl+2,Ctrl+3,Ctrl+4,Ctrl+5,Ctrl+6,Ctrl+7,Ctrl+8,Ctrl+9 `
  -Description "Set location to Favorite" `
  -ScriptBlock {
  param($Info, $Arg)

  $Char = $Info.KeyChar
  $Index = 0 + "$Char"
  $Location = $Favorites[$Index]

  if (-not $Location) {
    return
  }

  Set-Location $Location

  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}
```
If I press Ctrl+Pageup in my terminal with v2 it just goes up one directory and refreshes the prompt with the current data.
If I do the same in my terminal with v3 it messes up the prompt and draws a new one a line deeper.

**Comment by JanDeDobbeleer** [comment]
Never knew about invoke prompt so for sure that's untested. Is your PSReadLine the latest version though?

**Comment by Ergamon** [comment]
Yes, I dont think this feature is widely used. Took me some time to figure it out, but it is in the documentation. But over the time I got really used to it.

With PowerShell 7 PSReadLine is part of the installation. So I don´t install any specific version.

With the current stable release of PowerShell 7.1.2 this means PSReadLine version 2.1.0

**Comment by JanDeDobbeleer** [comment]
@Ergamon can you log this bug at PSReadLine? I did some research and it should only call the prompt function again which works (as that's what we override).

**Comment by Ergamon** [comment]
Meanwhile I spend some time for further investigation.

So far I figured out that my statement about the new line not happening in v2 is wrong. I usually use Cmder about 99.9 percent of the time and wanted to make the steps for you to recreate the problem as easy as possible.

For other terminals than Cmder you need to tell PSReadLine about the height of your prompt. So my prompt spans 2 lines therefore I have to put

```
Set-PSReadLineOption -ExtraPromptLineCount 1
```

With this command the new line problem is gone in all terminals I tested and also has no negative effects on Cmder where it works without this command.

The problem with the powerline symbols sadly stays.

To simplify testing even further I made the key handler even simpler:
```
Set-PSReadLineKeyHandler -Key "Ctrl+Insert" -Description "InvokePrompt" -ScriptBlock {
  param($Key, $Arg)

  [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}
```

With this set up, if I open e.g. Windows terminal:
![grafik](https://user-images.githubusercontent.com/48294299/111025562-38e1be80-83e5-11eb-8e22-eaa30d9f2b7e.png)

Everything looks nice and clean.

When I now trigger my key handler, it changes to:
![grafik](https://user-images.githubusercontent.com/48294299/111025604-6cbce400-83e5-11eb-856a-714ef55fecb9.png)

A lot of questionmarks are created :(

If it is any help, v2 does not have this problem.

Perhaps you have any clue what is going on, otherwise I can only create an issue at PSReadLine with the same content.

PS.: The C# code for the InvokePrompt method can be found [here](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/ReadLine.cs).

**Comment by JanDeDobbeleer** [comment]
I know exactly what your problem is :-) You need to either tweak the theme or use a Nerd Font. See [here](https://ohmyposh.dev/docs/fonts) for more information.

**Comment by Ergamon** [comment]
I dont get it. I use Cascadia Code PL.

So it works with v2 without any problems and also with v3 until I refresh (via InvokePrompt).

How can the font be the problem if it works besides this refresh case?

**Comment by Ergamon** [comment]
Just for the sake of completness and to outrule the font. Same Screenshots with Meslo NF
![grafik](https://user-images.githubusercontent.com/48294299/111026727-25862180-83ec-11eb-966d-72c3b8ec8d88.png)

![grafik](https://user-images.githubusercontent.com/48294299/111026731-2c149900-83ec-11eb-9576-fc351e1ea128.png)

**Comment by JanDeDobbeleer** [comment]
The first image shows no rectangles anymore, the second image shows a bug with PSReadLine as for some freaky reason, it can't render the icons anymore. Two possible causes:

- Meslo isn't installed [system wide](https://ohmyposh.dev/docs/fonts#windows) on your system
- PSReadLine messes with the encoding and shouldn't 

If you set the following at the top of your `$PROFILE` and that resolves the issue, you need to go and annoy PSReadLine for sure:

`[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

**Comment by Ergamon** [comment]
You are the man. Thank you very much for your patience.

I installed the font system wide and your guess about the encoding is a point blank hit.

I put the line into my profile and everything works.

I will open an issue at PSReadLine and close this one here.
