### ISSUE TITLE
Empty prompt for UNIX and FISH shell.

### ISSUE THREAD

**Issue by DoReVo** [JanDeDobbeleer/oh-my-posh#519]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Followed installation instruction at https://ohmyposh.dev/docs/installation for UNIX and FISH shell. But after reloading the 
config and even restarting my terminal, my prompt becomes empty. Nothing is displayed there. The shell is still working but there is no prompt.

### Environment

- Oh my Posh version: 3.110.0
- Theme: jandedobbeleer
- Operating System: KDE Neon (Linux)
- Shell: Fish
- Terminal: Konsole

### Steps to Reproduce

1.Follow installation instruction for UNIX and FISH shell.

**Expected behavior:** It should displayed prompt set by the theme.

**Actual behavior:** Empty prompt. Nothing is displayed.

**Comment by JanDeDobbeleer** [comment]
I can't reproduce this. I have fish set up and working with the latest version of oh-my-posh. Things to check:

- are you on the latest version?
- is oh-my-posh recognised as a command?

**Comment by DoReVo** [comment]
This is my oh-my-posh and fish version, yes it is recognised as a command. As you can see, the prompt is empty.
![versions](https://user-images.githubusercontent.com/43557832/110985277-3c565500-83a7-11eb-8e7f-335124fdb271.png)

This is my config.fish
![fish config](https://user-images.githubusercontent.com/43557832/110985274-3a8c9180-83a7-11eb-85aa-b7cf0c77cec0.png)

**Comment by JanDeDobbeleer** [comment]
I have no idea. I'm on fish 3.1.2 but I don't suppose that has anything to do with it.

**Comment by DoReVo** [comment]
Running `--shell fish` does display the prompt however.
![hello](https://user-images.githubusercontent.com/43557832/110986670-e682ac80-83a8-11eb-8e82-6b9271f6e491.png)
However when making fish evaluate using `source` it doesn't work.
![nothing](https://user-images.githubusercontent.com/43557832/110986852-2d70a200-83a9-11eb-8789-6c1dc916f98c.png)

**Comment by JanDeDobbeleer** [comment]
@DoReVo can you update your fish shell? It seems fish 3.1.0 contained quite a few significant bugs. I'll have a look at the docs in the meantime.

**Comment by DoReVo** [comment]
Oh god updating to fish 3.2.0 worked ! I used the ubuntu PPA [here](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) to get the latest version.

After updating and i open my terminal.. It just worked... Might want to update the docs and add notes saying fish 3.1.0 doesnt work.
![Screenshot_20210313_040157](https://user-images.githubusercontent.com/43557832/110992440-e25a8d00-83b0-11eb-95be-98b611207f84.png)
