### ISSUE TITLE
Git .BranchStatus seems to use some kind of unicode

### ISSUE THREAD

**Issue by dozer75** [JanDeDobbeleer/oh-my-posh#5252]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

We have issues using custom fonts on our restricted environments, so we need to run minimal templates. But the `.BranchStatus` value shows cryptic characters making me believe there are some Unicode with that?

Here is how it looks like: <img width="62" alt="image" src="https://github.com/JanDeDobbeleer/oh-my-posh/assets/7486163/7394d2eb-e39e-4926-968b-1b7bce69f753">

### Theme

Appears in `onehalf.minimal` template

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Will not be provided as it dumps sensitive information, but this issue happens with the template everywhere.
```

**Comment by JanDeDobbeleer** [comment]
@dozer75 this config is just an example, and probably doesn't map every icon in the default configuration. Have a look at all defaults [here](https://ohmyposh.dev/docs/segments/scm/git#branch) and adjust your configuration accordingly.

**Comment by dozer75** [comment]
Ah, sorry for the misunderstanding!
