### ISSUE TITLE
New upgrade system doesn't reflect the new version on winget upgrade

### ISSUE THREAD

**Issue by ezhupa99** [JanDeDobbeleer/oh-my-posh#5254]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I upgraded the oh my posh using `oh-my-posh upgrade`, now when I try to get the list of packages to upgrade using `winget upgrade` I notice oh my posh, has an older version than it has. So it means the version is not reflected in other places when I update from `oh-my-posh upgrade`. 

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/34006441/f90ff393-b2d9-45e2-8e63-ef3ab67ea47d)

### Theme

multiverse-neon.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
I can't do that since it contains Env variables and my PC info, but you should be able to repro
```

**Comment by JanDeDobbeleer** [comment]
@ezhupa99 we don't update winget's information. Upgrade only updates the binary, nothing else. This is by design. Same goes for any other package manager.

**Comment by JanDeDobbeleer** [comment]
@ezhupa99 I will have a look at updating the version number in the registry, provided that's where this information is stored. But for that to happen, upgrade also needs to update the themes, which is on my backlog. So far, this is by design.

**Comment by ezhupa99** [comment]
That's great news

**Comment by JanDeDobbeleer** [comment]
@ezhupa99 It's fixed in latest
