### ISSUE TITLE
Azure segment should contain tenant name

### ISSUE THREAD

**Issue by dozer75** [JanDeDobbeleer/oh-my-posh#5255]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

The Azure segment contains TenanatId, but that is not that useful for display, however the tenant name is more interesting, especially for those of us that works with multiple tenants. It will make it much easier to confirm that we are working in the correct environment since a subscription name may be the same in multiple tenants.

**Comment by JanDeDobbeleer** [comment]
@dozer75 I'll have a look at if this is available.

**Comment by colinrippeyfinarne** [comment]
Hi @JanDeDobbeleer I've got an account that has access to multiple B2B tenants. 

I log into a B2B tenant using az login --tenant <guid> or Connect-AzAccount -TenantId <guid> or Connect-AzAccount -Tenant xxx.onmicrosoft.com 

If I use the .TenantID segment I see the correct tenant id.

If I use the .TenantDisplayName segment I see nothing.
