### ISSUE TITLE
`auto_upgrade` only if SemVer == minor || patch

### ISSUE THREAD

**Issue by ChristopherBull** [JanDeDobbeleer/oh-my-posh#5273]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

`auto_upgrade` should (by default) avoid automatically upgrading to a version which introduces breaking changes.

**Comment by JanDeDobbeleer** [comment]
@ChristopherBull did you already experience this or is it "would be best if" feature request?

The reason I ask is that we don't really have a lot of breaking changes.

It can be stopped, obviously, just wondering if it's worth the effort.

**Comment by ChristopherBull** [comment]
No issue, just a "would be nice".
