### ISSUE TITLE
tooltips ignored (?)

### ISSUE THREAD

**Issue by eladl-ps** [JanDeDobbeleer/oh-my-posh#5288]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hey! 👋 
I'm trying to debug a new theme that I'm creating (based on `bubbles`).
The `kubectl` plugin is a bit slow (even with lazy load), so I want to use it only by typing `kubectl` commands. To do that, I'm using `tooltips`.
For some reason, it seems like it got completely ignored 🤔
Things I've tried:
1. Trying the same block config on `blocks` -- worked well
2. Copy the example from [the doc](https://ohmyposh.dev/docs/configuration/tooltips) -- still no tooltips
3. Disable a bunch of things on zsh -- still no success

Any idea? Am I missing something obvious?

### Theme

https://gist.github.com/eladl-ps/aa69ea97e789b6472ee865b7576fec1e

### What OS are you seeing the problem on?

Mac Sonoma

### Which shell are you using?

ZSH

### Log output

```Shell
Segments:

ConsoleTitle(false)                       -   0 ms
Gcp(true)                                 -   0 ms
Git(false)                                -   0 ms
Git(false)                                -   0 ms
Python(false)                             -   0 ms
Go(false)                                 -   0 ms
Java(false)                               -   0 ms
Path(true)                                -   0 ms
Text(true)                                -   0 ms

Run duration: 11.102625ms

Cache path: /Users/<USERNAME>

Config path: /Users/<USERNAME>/bubbles.omp.json

Logs:

[DEBUG] 20:32:59.584 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.584 os.go:Getenv(OMP_CACHE_DIR) - 897µs
[DEBUG] 20:32:59.584 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.584 os.go:Getenv(XDG_CACHE_HOME) - 3.541µs
[TRACE] 20:32:59.584 os_unix.go:CachePath() - 929.458µs
[DEBUG] 20:32:59.585 os.go:Getenv:306 → /Users/<USERNAME>/bubbles.omp.json
[TRACE] 20:32:59.585 os.go:Getenv(POSH_THEME) - 3.916µs
[DEBUG] 20:32:59.585 os_unix.go:Platform:87 → darwin
[TRACE] 20:32:59.585 os.go:resolveConfigPath() - 26.084µs
[TRACE] 20:32:59.585 os.go:Init() - 1.325209ms
[TRACE] 20:32:59.585 os.go:Flags() - 42ns
[TRACE] 20:32:59.585 load.go:loadConfig() - 636.208µs
[TRACE] 20:32:59.585 os.go:Flags() - 41ns
[DEBUG] 20:32:59.586 debug.go:44 → Terminal shell: %s shell
[DEBUG] 20:32:59.586 debug.go:44 → Terminal program: %s iTerm.app
[DEBUG] 20:32:59.586 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.586 os.go:Getenv(OMP_CACHE_DISABLED) - 2.416µs
[DEBUG] 20:32:59.586 os.go:Shell:581 → no shell name provided in flags, trying to detect it
[DEBUG] 20:32:59.586 os.go:Shell:589 → process name: zsh
[TRACE] 20:32:59.586 os.go:Shell() - 195.208µs
[DEBUG] 20:32:59.586 os.go:Getenv:306 → 5.9
[TRACE] 20:32:59.586 os.go:Getenv(POSH_SHELL_VERSION) - 2.125µs
[DEBUG] 20:32:59.586 debug.go:PrintDebug:23 → Segment: Title
[DEBUG] 20:32:59.586 text.go:Render:73 → Rendering template:
[TRACE] 20:32:59.586 os.go:Shell() - 41ns
[DEBUG] 20:32:59.586 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.586 os.go:Getenv(POSH_CURSOR_LINE) - 150.333µs
[DEBUG] 20:32:59.586 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.586 os.go:Getenv(POSH_CURSOR_COLUMN) - 2.792µs
[TRACE] 20:32:59.586 os.go:Flags() - 83ns
[TRACE] 20:32:59.586 os.go:Flags() - 42ns
[TRACE] 20:32:59.586 os.go:Flags() - 83ns
[TRACE] 20:32:59.586 os.go:GOOS() - 250ns
[DEBUG] 20:32:59.586 os.go:Pwd:336 → /Users/<USERNAME>
[TRACE] 20:32:59.586 os.go:Pwd() - 26.5µs
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[DEBUG] 20:32:59.586 segment.go:SetEnabled:115 → Segment: Gcp
[DEBUG] 20:32:59.586 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.586 os.go:Getenv(CLOUDSDK_CONFIG) - 5.542µs
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[DEBUG] 20:32:59.586 os.go:FileContent:448 → default
[TRACE] 20:32:59.586 os.go:FileContent(/Users/<USERNAME>/.config/gcloud/active_config) - 58µs
[DEBUG] 20:32:59.586 os.go:FileContent:448 ↓
    [core]
...


[TRACE] 20:32:59.586 os.go:FileContent(/Users/<USERNAME>/.config/gcloud/configurations/config_default) - 40.958µs
[TRACE] 20:32:59.586 os_unix.go:Root() - 625ns
[TRACE] 20:32:59.586 os.go:Shell() - 84ns
[TRACE] 20:32:59.586 os.go:StatusCodes() - 83ns
[DEBUG] 20:32:59.586 os_unix.go:IsWsl:35 → false
[TRACE] 20:32:59.586 os_unix.go:IsWsl() - 2.583µs
[DEBUG] 20:32:59.586 os.go:TemplateCache:789 → environment: [...]
[TRACE] 20:32:59.586 os.go:Pwd() - 42ns
[DEBUG] 20:32:59.586 os_unix.go:IsWsl:35 → false
[TRACE] 20:32:59.586 os_unix.go:IsWsl() - 2.417µs
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[TRACE] 20:32:59.586 os.go:GOOS() - 41ns
[TRACE] 20:32:59.586 os.go:GOOS() - 0s
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[TRACE] 20:32:59.586 os.go:GOOS() - 0s
[TRACE] 20:32:59.586 os.go:GOOS() - 0s
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[TRACE] 20:32:59.586 os.go:GOOS() - 42ns
[DEBUG] 20:32:59.586 os.go:User:474 → <USERNAME>
[TRACE] 20:32:59.586 os.go:User() - 6.041µs
[DEBUG] 20:32:59.586 os.go:Host:491 → ....
[TRACE] 20:32:59.586 os.go:Host() - 9.916µs
[TRACE] 20:32:59.586 os.go:GOOS() - 41ns
[DEBUG] 20:32:59.586 os.go:Getenv:306 → 1
[TRACE] 20:32:59.586 os.go:Getenv(SHLVL) - 2.167µs
[TRACE] 20:32:59.586 os.go:TemplateCache() - 123.875µs
[DEBUG] 20:32:59.587 text.go:Render:73 → Rendering template:   {{.Project}}
[TRACE] 20:32:59.587 os.go:TemplateCache() - 83ns
[TRACE] 20:32:59.587 os.go:Shell() - 42ns
[DEBUG] 20:32:59.587 text.go:Render:73 → Rendering template: powerline
[DEBUG] 20:32:59.593 os_unix.go:TerminalWidth:80 → terminal width: 281
[TRACE] 20:32:59.593 os_unix.go:TerminalWidth() - 6.283292ms
[TRACE] 20:32:59.593 os.go:Shell() - 42ns
[TRACE] 20:32:59.593 os.go:Shell() - 42ns
[TRACE] 20:32:59.593 os.go:Flags() - 42ns
[TRACE] 20:32:59.593 os.go:Flags() - 41ns
[DEBUG] 20:32:59.593 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.593 os.go:Getenv(JAVA_HOME) - 3.459µs
[TRACE] 20:32:59.593 os.go:Flags() - 83ns
[TRACE] 20:32:59.593 os.go:Pwd() - 83ns
[TRACE] 20:32:59.593 os.go:GOOS() - 0s
[DEBUG] 20:32:59.593 segment.go:SetEnabled:115 → Segment: Java
[TRACE] 20:32:59.593 os.go:Pwd() - 42ns
[TRACE] 20:32:59.593 os.go:GOOS() - 42ns
[DEBUG] 20:32:59.593 python.go:Init:61 → environment
[DEBUG] 20:32:59.593 segment.go:SetEnabled:115 → Segment: Git
[DEBUG] 20:32:59.593 os_unix.go:IsWsl:35 → false
[TRACE] 20:32:59.593 os_unix.go:IsWsl() - 3.917µs
[DEBUG] 20:32:59.593 language.go:Enabled:109 → extensions: [pom.xml build.gradle.kts build.sbt .java-version .deps.edn project.clj build.boot *.java *.class *.gradle *.jar *.clj *.cljc]
[DEBUG] 20:32:59.593 segment.go:SetEnabled:115 → Segment: Python
[DEBUG] 20:32:59.593 language.go:Enabled:110 → folders: []
[DEBUG] 20:32:59.593 language.go:Enabled:117 → home_enabled: false
[TRACE] 20:32:59.593 os.go:Pwd() - 84ns
[DEBUG] 20:32:59.593 language.go:Enabled:109 → extensions: [*.py *.ipynb pyproject.toml venv.bak]
[DEBUG] 20:32:59.593 language.go:Enabled:110 → folders: [.venv venv virtualenv venv-win pyenv-win]
[TRACE] 20:32:59.593 os.go:Flags() - 42ns
[DEBUG] 20:32:59.593 language.go:Enabled:117 → home_enabled: false
[TRACE] 20:32:59.593 os.go:Pwd() - 0s
[TRACE] 20:32:59.593 os.go:Pwd() - 41ns
[TRACE] 20:32:59.593 os.go:GOOS() - 42ns
[DEBUG] 20:32:59.593 segment.go:SetEnabled:115 → Segment: Git
[TRACE] 20:32:59.593 os.go:Flags() - 125ns
[DEBUG] 20:32:59.593 os_unix.go:IsWsl:35 → false
[TRACE] 20:32:59.593 os_unix.go:IsWsl() - 2.541µs
[TRACE] 20:32:59.593 os_unix.go:IsWsl2() - 4.958µs
[TRACE] 20:32:59.593 os.go:GOOS() - 42ns
[TRACE] 20:32:59.593 os.go:Pwd() - 125ns
[TRACE] 20:32:59.593 os.go:GOOS() - 42ns
[DEBUG] 20:32:59.593 segment.go:SetEnabled:115 → Segment: Go
[DEBUG] 20:32:59.593 os.go:CommandPath:533 → /usr/bin/git
[DEBUG] 20:32:59.593 os.go:CommandPath:533 → /usr/bin/git
[TRACE] 20:32:59.593 os.go:CommandPath(git) - 67.042µs
[TRACE] 20:32:59.593 os.go:CommandPath(git) - 31.375µs
[TRACE] 20:32:59.593 os.go:HasCommand(git) - 70.291µs
[TRACE] 20:32:59.593 os.go:HasCommand(git) - 33.959µs
[TRACE] 20:32:59.593 os.go:Pwd() - 0s
[TRACE] 20:32:59.593 os.go:Pwd() - 42ns
[DEBUG] 20:32:59.593 os.go:ResolveSymlink:433 → /Users/<USERNAME>
[TRACE] 20:32:59.593 os.go:ResolveSymlink(/Users/<USERNAME>) - 34.833µs
[DEBUG] 20:32:59.593 language.go:Enabled:109 → extensions: [*.go go.mod]
[DEBUG] 20:32:59.593 os.go:ResolveSymlink:433 → /Users/<USERNAME>
[ERROR] 20:32:59.594 os.go:HasParentFilePath:697 → stat .git: no such file or directory
[TRACE] 20:32:59.594 os.go:ResolveSymlink(/Users/<USERNAME>) - 210.291µs
[TRACE] 20:32:59.594 os.go:HasParentFilePath(.git) - 346.167µs
[DEBUG] 20:32:59.594 language.go:Enabled:110 → folders: []
[DEBUG] 20:32:59.594 language.go:Enabled:117 → home_enabled: false
[ERROR] 20:32:59.594 os.go:HasParentFilePath:697 → stat .git: no such file or directory
[TRACE] 20:32:59.594 os.go:Pwd() - 83ns
[TRACE] 20:32:59.594 os.go:HasParentFilePath(.git) - 370.416µs
[DEBUG] 20:32:59.594 git.go:shouldDisplay:284 → fetch_bare_info: false
[DEBUG] 20:32:59.594 git.go:shouldDisplay:284 → fetch_bare_info: false
[TRACE] 20:32:59.594 os.go:Shell() - 42ns
[TRACE] 20:32:59.594 os.go:Shell() - 0s
[TRACE] 20:32:59.594 os.go:Flags() - 41ns
[TRACE] 20:32:59.594 os.go:Pwd() - 41ns
[TRACE] 20:32:59.594 os.go:GOOS() - 0s
[DEBUG] 20:32:59.594 segment.go:SetEnabled:115 → Segment: Text
[TRACE] 20:32:59.594 os.go:TemplateCache() - 41ns
[TRACE] 20:32:59.594 os.go:Flags() - 125ns
[TRACE] 20:32:59.594 os.go:Pwd() - 125ns
[TRACE] 20:32:59.594 os.go:GOOS() - 84ns
[DEBUG] 20:32:59.594 segment.go:SetEnabled:115 → Segment: Path
[DEBUG] 20:32:59.594 path.go:124 → display_cygpath: false
[TRACE] 20:32:59.594 os.go:GOOS() - 84ns
[TRACE] 20:32:59.594 os.go:PathSeparator() - 0s
[TRACE] 20:32:59.594 os.go:Pwd() - 42ns
[TRACE] 20:32:59.594 os.go:Shell() - 41ns
[TRACE] 20:32:59.594 os.go:Shell() - 41ns
[DEBUG] 20:32:59.594 path.go:replaceMappedLocations:517 → mapped_locations_enabled: true
[DEBUG] 20:32:59.594 path.go:replaceMappedLocations:518 → 
[DEBUG] 20:32:59.594 path.go:replaceMappedLocations:519 → 
[TRACE] 20:32:59.594 os.go:GOOS() - 41ns
[DEBUG] 20:32:59.594 path.go:replaceMappedLocations:520 → ~
[DEBUG] 20:32:59.594 path.go:replaceMappedLocations:525 → mapped_locations: map[]
[TRACE] 20:32:59.594 os.go:GOOS() - 0s
[TRACE] 20:32:59.594 os.go:GOOS() - 0s
[DEBUG] 20:32:59.594 path.go:makeFolderFormatMap:841 → NO DATA
[TRACE] 20:32:59.594 os.go:Pwd() - 42ns
[TRACE] 20:32:59.594 os.go:TemplateCache() - 83ns
[TRACE] 20:32:59.594 os.go:StackCount() - 83ns
[TRACE] 20:32:59.594 os_unix.go:DirIsWritable(/Users/<USERNAME>) - 21.833µs
[TRACE] 20:32:59.594 os.go:TemplateCache() - 41ns
[DEBUG] 20:32:59.594 text.go:Render:73 → Rendering template: ❯
[DEBUG] 20:32:59.594 text.go:Render:73 → Rendering template: <transparent></> {{ .Path }}
[TRACE] 20:32:59.595 os.go:TemplateCache() - 84ns
[TRACE] 20:32:59.595 os.go:Shell() - 42ns
[DEBUG] 20:32:59.595 text.go:Render:73 → Rendering template: diamond
[DEBUG] 20:32:59.595 text.go:Render:73 → Rendering template: diamond
[TRACE] 20:32:59.595 os.go:Shell() - 42ns
[TRACE] 20:32:59.595 os.go:Shell() - 0s
[TRACE] 20:32:59.595 os.go:Shell() - 41ns
[TRACE] 20:32:59.595 os.go:Shell() - 0s
[TRACE] 20:32:59.595 os.go:Flags() - 41ns
[DEBUG] 20:32:59.595 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.595 os.go:Getenv(OMP_CACHE_DIR) - 2.417µs
[DEBUG] 20:32:59.595 os.go:Getenv:306 → NO DATA
[TRACE] 20:32:59.595 os.go:Getenv(XDG_CACHE_HOME) - 1.625µs
[TRACE] 20:32:59.595 os_unix.go:CachePath() - 11.625µs
[TRACE] 20:32:59.595 os.go:Flags() - 0s
```

**Comment by JanDeDobbeleer** [comment]
@eladl-ps You need to restart the shell when testing this so tooltips get enabled.

**Comment by eladl-ps** [comment]
Thanks for the quick answer (and all your effort) - I did restarted the shell, and even iTerm, still no tooltips

**Comment by JanDeDobbeleer** [comment]
@eladl-ps I'll have a look. I know @lewis-yeung did some refactoring in that area, didn't check zsh yet myself as I trust him 😁

**Comment by lewis-yeung** [comment]
@eladl-ps Tooltips work well in Zsh v5.9 on my end. If you find something suspicious in [the OMP initialization script for Zsh][omp-init-script-zsh], please just tell me. :) Curious about why it doesn't work for you.

[omp-init-script-zsh]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/shell/scripts/omp.zsh

**Comment by dreamfliper** [comment]
When I turn on tooltips, it shows `No such widget ._omp_original::self-insert'` then I can't type anything in command line 😂
Zsh v5.9 on mac

**Comment by lewis-yeung** [comment]
> it shows `No such widget ._omp_original::self-insert'`

@dreamfliper Failed to reproduce this in Zsh v5.9. A prefix dot character (`.`) in `._omp_original::self-insert'` should not be there. What's the output of running `echo "${widgets[self-insert]}"` in a newly started Zsh session?

**Comment by dreamfliper** [comment]
Yes, start a new session and start a keystroke. No character will show up and the error message will appear at the next line

**Comment by lewis-yeung** [comment]
@dreamfliper The `self-insert` widget must be broken (can be caused by some other Zsh plugins) in your case. Disable tooltips and try `echo "${widgets[self-insert]}"`, what does it show?

**Comment by dreamfliper** [comment]
It all shows `user:_zsh_autosuggest_bound_1_self-insert`, whether I turn on the tooltips or not
<img width="445" alt="Screenshot 2024-07-17 at 12 22 17 PM" src="https://github.com/user-attachments/assets/c76b7a4b-f1f5-4c6f-bc56-f33451599411">

**Comment by dreamfliper** [comment]
Just found the conflict Zsh plugin: `zdharma/fast-syntax-highlighting `, but it works fine in the old oh-my-posh version.
Change to `zsh-users/zsh-syntax-highlighting` fix the problem

**Comment by lewis-yeung** [comment]
So, I guess the plugin ***fast-syntax-highlighting*** may override the `self-insert` widget in a breaking approach. We only wrap and decorate an existing widget for Oh My Posh but we cannot guarantee that other Zsh plugins do so.

I use ***zsh-autosuggestions*** v0.7.0, ***zsh-syntax-highlighting*** v0.8.0 and ***zsh-history-substring-search*** v1.1.0. I can confirm these plugins work well with Oh My Posh.

**Comment by JanDeDobbeleer** [comment]
@dreamfliper @lewis-yeung I suppose this is also an issue with oh-my-posh not being added as the last line in `.zshrc` as otherwise we would wrap that and things would work. @eladl-ps @dreamfliper can you validate that's the case? Move `oh-my-posh init` to the bottom of your `.zshrc` and theoretically, that should allow us to wrap any existing widget overrides. That said, @lewis-yeung is right as we can't guarantee anything if other plugins ignore our (and other's) overrides.

**Comment by dreamfliper** [comment]
Move `oh-my-posh init` after the plugin management solve the problem

> @dreamfliper @lewis-yeung I suppose this is also an issue with oh-my-posh not being added as the last line in `.zshrc` as otherwise we would wrap that and thing would work. @eladl-ps @dreamfliper can you validate that's the case? Move `oh-my-posh init` to the bottom of your `.zshrc` and theoretically, that should allow us to wrap any existing widget overrides. That said, @lewis-yeung is right as we can't guarantee anything if other plugins ignore our (and other's) overrides.

**Comment by eladl-ps** [comment]
Unfortunately not for me :(
My init was at the bottom of the file, but just for the sake of it, I've tried to:
```
# Start fresh
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
omz reload

eval "$(oh-my-posh init zsh --config /Users/elad.leev/bubbles.omp.json)"
```
Still the same, even with the config from the doc
I wonder if something on my iTerm config blocks it -- will try to debug some more, buy if you have any idea of something which might do it please let me know 🙏

**Comment by JanDeDobbeleer** [comment]
@eladl-ps same question as above for you, what does `echo "${widgets[self-insert]}"`say? And, additionally, do you have the same issue when just using `eval "$(oh-my-posh init zsh --config /Users/elad.leev/bubbles.omp.json)"` and not the other lines above?

**Comment by eladl-ps** [comment]
Sorry, here's the output - 
```
> echo "${widgets[self-insert]}"
user:_omp_decorated_self-insert
```
It seems that there are no built-in themes which leverage tooltips, right? Maybe something is wrong with my config

re `eval` - yes, the same I'm afraid

**Comment by DeepSpace2** [comment]
I believe this might be a regression introduced in one of the last versions released lately (last 2 weeks maybe), unfortunately I can't pin point to the exact one at the moment. 

Tooltips used to work for me and I didn't install or update any of my zsh plugins.

```shell
$ echo "${widgets[self-insert]}"
user:_zsh_autosuggest_bound_1_self-insert

$ tail -n 1 ~/.zshrc
eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/theme.yaml)"
```

Perhaps I will try to git bisect this later.

**Comment by JanDeDobbeleer** [comment]
@DeepSpace2 as you don't have our widget in there I'm quite sure you don't have your oh-my-posh init line as the last statement in your zsh rc line. It clearly shows autosuggestions which isn't sourced in `zshrc` and theoretically is added after the oh-my-posh init or we would wrap it.

**Comment by DeepSpace2** [comment]
@JanDeDobbeleer sorry, I just manually copied-pasted the commands and their outputs :)

![image](https://github.com/user-attachments/assets/d9eeb2a1-db90-4ad8-a448-f6e25c526914)

**Comment by DeepSpace2** [comment]
So I just commented out `source $ZSH/oh-my-zsh.sh` in `~/.zshrc` and the tooltips work again.

I will try to find the problematic line.

**Comment by JanDeDobbeleer** [comment]
@DeepSpace2 check, but still, autosuggestions is simply hijacking the widget. So that one is sourced after oh-my-posh is sourced. Otherwise this should work. Can you validate where this happens?

**Comment by DeepSpace2** [comment]
@JanDeDobbeleer I commented out `zsh-autosuggestions` from the plugin list in `.zshrc` and the tooltips still don't work even though `self-insert` does not seem to be hijacked anymore:

![image](https://github.com/user-attachments/assets/e7df108a-313f-48e3-afb2-d0f7274ad58c)

As I mentioned above, if I'm not sourcing `$ZSH/oh-my-zsh.sh` at all in `.zshrc` then the tooltips work again

![image](https://github.com/user-attachments/assets/8e65998d-2511-48c7-afc1-e9dd3683df09)

So, at least in my case, there must be something weird going on in there.

**Comment by eladl-ps** [comment]
Can confirm the same thing here, just didn't had the time to get to the root of it yet.
When commenting out `source oh-my-zsh.sh` it's working well

**Comment by lewis-yeung** [comment]
> check, but still, autosuggestions is simply hijacking the widget. So that one is sourced after oh-my-posh is sourced.

@JanDeDobbeleer I guess the ***zsh-autosuggestions*** plugin always ~hijacks~decorates the `self-insert` widget, no matter where it is sourced. Anyway, the OMP tooltips can work well with it.

> if I'm not sourcing `$ZSH/oh-my-zsh.sh` at all in `.zshrc` then the tooltips work again

> When commenting out `source oh-my-zsh.sh` it's working well

@DeepSpace2 @eladl-ps So, I guess Oh My Zsh itself may have hijacked the `self-insert` widget...

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung the problem is, the only way to ensure compatibility is decorating widgets. We have so many issues otherwise, maybe we need to understand what zsh is doing because maybe they simply don't care about anything outside of the ecosystem.

**Comment by DeepSpace2** [comment]
I can confirm it is this commit https://github.com/JanDeDobbeleer/oh-my-posh/commit/ec2c6fb2d80482d0396a5b8b842cadc5c7e2d4a6 ([v21.26.2](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v21.26.2)). 21.26.1 is the last version that tooltips works with my setup

**Comment by DeepSpace2** [comment]
@JanDeDobbeleer  @lewis-yeung 
I can confirm this issue is introduced by this commit https://github.com/JanDeDobbeleer/oh-my-posh/commit/ec2c6fb2d80482d0396a5b8b842cadc5c7e2d4a6 ([v21.26.2](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v21.26.2)). 21.26.1 is the last version in which tooltips work with my setup

**Comment by lewis-yeung** [comment]
@DeepSpace2 Just as @JanDeDobbeleer said, we have to decorate widgets, since there will be more side effects (deeper invasiveness) if we hijack keybindings instead.

**Comment by Allaman** [comment]
I can confirm that switching from fast-syntax-highlighting to zsh-syntax-highlighting solves the issue. 
Also running zsh-autosuggestions.

**Comment by DeepSpace2** [comment]
> I can confirm that switching from fast-syntax-highlighting to zsh-syntax-highlighting solves the issue. Also running zsh-autosuggestions.

@Allaman I'm already using  zsh-syntax-highlighting, never used fast-syntax-highlighting

**Comment by JanDeDobbeleer** [comment]
@Allaman in what order and way do you import stuff in your zshrc?

**Comment by Allaman** [comment]
@JanDeDobbeleer my order is 

1. zsh-autosuggestions
2. oh-my-posh
3. zsh-completions
4. zsh-syntax-highlighting (here was fast-syntax-highlighting, too)

[source](https://github.com/Allaman/dots/blob/main/dot_zshrc) ( a bitt of a mess, need to refactor this 😆 )

However, I switched from zsh-syntax-highlighting to fast-syntax-highlighting a while ago, and I would prefer the latter one ...

edit: Putting oh-my-posh after fast-syntax-highlighting also does the job but breaks something with my page-up/page-down ...

**Comment by ulrichSchreiner** [comment]
hi,

is there anything one can do to fix this? 

my last line in `.zshrc` is the "oh-my-posh init" 

~~~
$ tail -n 2 ~/.zshrc
source <(oh-my-posh completion zsh)
eval "$(oh-my-posh init zsh --config ~/.config/usc-theme.omp.yml)"
$ echo "${widgets[self-insert]}"
user:_omp_decorated_self-insert
$ oh-my-posh version
22.0.1
~~~

but tooltips stopped working since a few versions which is a little annoying at least for `kubectl`

**Comment by JanDeDobbeleer** [comment]
@ulrichSchreiner ~~you should be able to reuse the old logic after initializing oh-my-posh~~

**Comment by ulrichSchreiner** [comment]
thanks, but after this i cannot enter a space any more :-)

**Comment by JanDeDobbeleer** [comment]
@ulrichSchreiner I'm quite sure something else is off, which zsh version are you using? When I use the latest oh-my-posh on the latest zsh with your `.zshrc` config, I have working tooltips.

**Comment by lewis-yeung** [comment]
@ulrichSchreiner The old logic will never work correctly because the function has been modified in recent versions.

**Comment by ulrichSchreiner** [comment]
~~~
zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
~~~

i have many oh-my-zsh plugins install, so it's hard to say what's causing the error. i'll try to reduce the plugins/tools to see when it works

**Comment by lewis-yeung** [comment]
@ulrichSchreiner It's also possible that some plugin is hijacking the key binding of space bar. Not ***zsh-autosuggestions*** since it works fine with the latest OMP.

**Comment by ulrichSchreiner** [comment]
well, it looks like it is `oh-my-zsh`. when i have the lines (normally i have a lot of plugins)

~~~
plugins=()
source $ZSH/oh-my-zsh.sh
~~~

tooltips do not work. after commenting out the line `source $ZSH/oh-my-zsh.sh` it works. no single plugin activated, simply initialization breaks the tooltips.

**Comment by lewis-yeung** [comment]
> So I just commented out `source $ZSH/oh-my-zsh.sh` in `~/.zshrc` and the tooltips work again.

> after commenting out the line `source $ZSH/oh-my-zsh.sh` it works.

@ulrichSchreiner @DeepSpace2 So, now we can confirm that OMZ is not compatible with tooltips of OMP. :(

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I'd love to understand why though. I'll see if I can debug this.

**Comment by ulrichSchreiner** [comment]
the problematic line is

https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh#L117

~~~
bindkey ' ' magic-space                               # [Space] - don't do history expansion
~~~

after commenting out this line, oh-my-zsh works.

but my know-how of shell is too limited to understand the side effects of doing this ...

**Comment by lewis-yeung** [comment]
~Also found some key bindings defined in the `globalias` plugin of OMZ, which may destroy OMP tooltips, if enabled.~ (This is fine since it calls the `self-insert` widget.)

**Comment by DeepSpace2** [comment]
> the problematic line is
> 
> https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh#L117
> 
> ```
> bindkey ' ' magic-space                               # [Space] - don't do history expansion
> ```
> 
> after commenting out this line, oh-my-zsh works.
> 
> but my know-how of shell is too limited to understand the side effects of doing this ...

I can confirm this restores the tooltips 👍 I **suppose** this prevents oh my posh from receiving the tooltip's command, eg when typing `k<space>` the kubectl tooltip won't be triggered because it does not receive the typed `k`.

**Comment by ulrichSchreiner** [comment]
my workaround is this:

~~~
source $ZSH/oh-my-zsh.sh
bindkey " " self-insert
~~~

although i do not really know if this is correct. but in this case i do not patch oh-my-zsh

it would be great if anyone who knows more about this `magic-space` or `self-insert` to look deeper :-)

**Comment by lewis-yeung** [comment]
@ulrichSchreiner For what `magic-space` does, you can see [this SE question][se-question] for details. BTW, the comment in code (`# [Space] - don't do history expansion`) is really misleading...

[se-question]: https://unix.stackexchange.com/questions/47349/what-does-zshs-magic-space-command-do

**Comment by JanDeDobbeleer** [comment]
@ulrichSchreiner can you validate if this also does the trick? When in the broken state.

```
_omp_create_widget magic-space _omp_render_tooltip
```

**Comment by ulrichSchreiner** [comment]
@JanDeDobbeleer 

yes, this snippet also works

**Comment by JanDeDobbeleer** [comment]
@ulrichSchreiner I'm going to make this more robust, but it will always require oh-my-posh to be initialized last.

```zsh
function enable_poshtooltips() {
  widget=${$(bindkey " "):2}

  if [[ -z $widget ]]; then
    widget=self-insert
  fi

  _omp_create_widget $widget _omp_render_tooltip
}
```

**Comment by DeepSpace2** [comment]
@JanDeDobbeleer This also works for me 👍 

Speaking of tooltips, what is the expected behavior? let's say I have a tooltip configured for the `k` command. As I type `k<space>` the tooltip is visible. Do we expect it to disappear if I delete `k` and write a different command? At the moment, once the tooltip appears it will only disappear if pressing "enter" or CTRL-C

**Comment by JanDeDobbeleer** [comment]
@DeepSpace2 that's the current behavior indeed, we have no hooks on backspace, only space.

**Comment by lewis-yeung** [comment]
> it shows `No such widget ._omp_original::self-insert'`

I can reproduce this on Linux/WSL2 with Zsh v5.8 but not v5.9. Both tested with ***zsh-syntax-highlighting*** v0.8.0.

The bug in Zsh v5.8 stems from that [zsh-syntax-highlighting][zsh-syntax-highlighting-code-1] and [OMP][oh-my-posh-code] use different decorating logic. As for Zsh v5.9, zsh-syntax-highlighting utilizes [another logic][zsh-syntax-highlighting-code-2] so the widget is not broken. I guess the [previous implementation][oh-my-posh-code-pre] by @po1o will work fine with zsh-syntax-highlighting both in Zsh v5.8 and v5.9.

Details of tests with only OMP and zsh-syntax-highlighting enabled in my `.zshrc`:

- In Zsh v5.8:
  - `${widgets[self-insert]}` -> `user:_zsh_highlight_widget_orig-s0.0000010000-r14999-self-insert`
  - `${widgets[_omp_original::self-insert]}` -> `user:_zsh_highlight_widget_orig-s0.0000010000-r14999-_omp_original::self-insert` (incorrectly decorated by zsh-syntax-highlighting)
- In Zsh v5.9: (working fine)
  - `${widgets[self-insert]}` -> `user:_omp_decorated_self-insert`
  - `${widgets[_omp_original::self-insert]}` -> `builtin`

[zsh-syntax-highlighting-code-1]: https://github.com/zsh-users/zsh-syntax-highlighting/blob/0.8.0/zsh-syntax-highlighting.zsh#L483
[zsh-syntax-highlighting-code-2]: https://github.com/zsh-users/zsh-syntax-highlighting/blob/0.8.0/zsh-syntax-highlighting.zsh#L409-L431
[oh-my-posh-code]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/7a6478269ca83ebf9dd41ce0d3b55aaaada4ae36/src/shell/scripts/omp.zsh#L186
[oh-my-posh-code-pre]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/31d5de095edd772131b2a48009a290a006ba0e68/src/shell/scripts/omp.zsh#L192

**Comment by po1o** [comment]
Good find @lewis-yeung ! 

IIRC the dot guarantees that it's always the built-in that gets called. There was some trick like that involved.
