### ISSUE TITLE
Visual Studio Code integrated terminal and style powerline colors

### ISSUE THREAD

**Issue by Ergamon** [JanDeDobbeleer/oh-my-posh#529]
### Prerequisites

- [ x ] I have read and understand the `CONTRIBUTING` guide
- [ x ] I looked for duplicate issues before submitting this one

### Description

The integrated terminal in VS Code seems to have problems with the coloring of the powerline style.

### Environment

- Oh my Posh version: 3.109.0
- Theme: Paradox (customized)
- Operating System: Windows 10
- Shell: PowerShell 7.1.3
- Terminal: Visual Studio Code

### Steps to Reproduce

1. Basically I have 2 sequences

```
        {
          "type": "session",
          "style": "plain",
          "foreground": "white",
          "background": "transparent",
          "properties": {
            "prefix": "",
            "postfix": " "
          }          
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "lightWhite",
          "background": "blue",
          "properties": {
            "prefix": " ",
            "folder_icon": "\uF115",
            "folder_separator_icon": "\uE0B1",
            "style": "full",
            "mapped_locations": [["HKCU:", "HKCU"]]
          }
        }
```

So for the powerline_symbol there is no color set, the coloring is figured out by oh-my-posh

**Expected behavior:** [What you expected to happen]
In Wndows Terminal it looks like expected:

![grafik](https://user-images.githubusercontent.com/48294299/111064270-52513c00-84b3-11eb-88d8-919957c2f80e.png)

**Actual behavior:** [What actually happened]
![grafik](https://user-images.githubusercontent.com/48294299/111064354-e91df880-84b3-11eb-99c6-cf29cf51fa41.png)

Yes the colors look different due to different themes. But that is not what I am talking about, I am talking about the powerline_symbol "\eE0B0", which is transparent in Windwos Terminal (and every other terminal I tested), but gets black in the VS Code integrated terminal.

Do you have any clue what is going on?

I can fix this by changing every segment to plain and adding lots of text segments. But this is creating quite an ugly theme file.

**Comment by JanDeDobbeleer** [comment]
@Ergamon that's a bug in vscode. We can't fix that for them 😉

See [here](https://github.com/microsoft/vscode/issues/111762).

**Comment by JanDeDobbeleer** [comment]
@Ergamon given the frequency of this issue, I added the ability to add your terminal's background color. That should allow anyone to fix this as long as they don't use acrylic or transparency in their Windows Terminal (that will still fail).
