### ISSUE TITLE
Add maven support

### ISSUE THREAD

**Issue by rmannibucau** [JanDeDobbeleer/oh-my-posh#5299]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

Hi,

I really like the simplicity to of adding java/dotnet version in PS1, in my custom PS1 I was used to add maven version too (if there is a pom.xml in the folder), is it possible to add it (parsing `mvn --version`)?

**Comment by rmannibucau** [comment]
If i'm not wrong it only does an exec which is fine but would it be possible to either cache it (with the env as key?) or read it from `$MAVEN_HOME/lib/maven-core-${version}.jar` if `MAVEN_HOME` exists - an alternative with the same spirit is to detect where `mvn` binary is from the `PATH`/`Path` then go up to find back lib folder (in path `$MAVEN_HOME/bin` is added generally).
If this heuristic fails, an exec is fine ok I guess - or nothing if it uses a flag like kubectl segment?

**Comment by JanDeDobbeleer** [comment]
@rmannibucau you can use `cache_version` out of the box.

**Comment by rmannibucau** [comment]
@JanDeDobbeleer I probably misread the code but I didn't see the key being composed of the env - my use case is SDKMan (Chocolatey on windows but it works a bit differently) and a switch of project using different maven (+java) versions and I want OMP to refresh the PS1 without a timeout or alike. SDKMan uses a symb link so the file resolution is more robust but since it sets the version in the env in another var using the env as a key can work too.

**Comment by JanDeDobbeleer** [comment]
@rmannibucau is there a specific env var that contains the version? Or just `MAVEN_HOME`?

**Comment by rmannibucau** [comment]
@JanDeDobbeleer think `PATH` or `MAVEN_HOME` is the one, default will point to the symb link but if auto_env is enabled both are updated to preppend the "local" location so should be sufficient - I don't have a windows computer for some weeks to test chocolatey but hope it is close.

Side note: open question, what about invalidating the whole cache if anything in the env changes? Should be sufficient and more generic no?

**Comment by JanDeDobbeleer** [comment]
@rmannibucau that's possible, but we can also just validate that `MAVEN_HOME` changed rather than cache the entire env. Regardless, it's an enhancement as this wasn't requested in the message above (but can be done).

**Comment by rmannibucau** [comment]
@JanDeDobbeleer agree it is another ticket, just mentionning it cause using too much exec the prompt becomes unusable very quickly. The fact to only cache the home is more fragile - nothing mentions it is first in the path/the path is not modified without, it is less to validate the path probably.
