### ISSUE TITLE
Cache font list

### ISSUE THREAD

**Issue by rmannibucau** [JanDeDobbeleer/oh-my-posh#5300]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

I guess font *list* can be cached once a day or something like that (in `~/.cache` or `~/.oh-my-posh/cache`), it is ultra slow so it would be great to make it more reactive.

**Comment by gabriel-vanca** [comment]
Wow! This halved the time it takes my profile to load! (From almost 8 seconds to 3.5 seconds).

**Comment by JanDeDobbeleer** [comment]
@gabriel-vanca that would be the effect of validating connectivity for the upgrade notice rather than this one.

**Comment by gabriel-vanca** [comment]
Oh, just saw that one now. I doubt it though. I virtually never have my network offline and the profile always took very long to load.

**Comment by JanDeDobbeleer** [comment]
@gabriel-vanca there isn't really another change that has influence on this. We check connectivity speed rather than being truly offline.
