### ISSUE TITLE
Kubernetes integration

### ISSUE THREAD

**Issue by rmannibucau** [JanDeDobbeleer/oh-my-posh#5301]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

Would be awesome to know the current context from current kubeconfig (KUBECONFIG en var if set else ~/.kube/config) as a segment.
It just needs to show the name.

An great enhancement would be to be able to set color per regex (if prod red, else if preprod yellow else if dev blue etc).

**Comment by JanDeDobbeleer** [comment]
> An great enhancement would be to be able to set color per regex (if prod red, else if preprod yellow else if dev blue etc).

@rmannibucau you have this by leveraging the [color templates](https://ohmyposh.dev/docs/configuration/colors#color-templates).

> KUBECONFIG en var if set else ~/.kube/config

I don't use kubernetes, do you have a redacted config file example I can use?

**Comment by rmannibucau** [comment]
@JanDeDobbeleer yep, was hoping something more natural and regex friendly but string template works

here is a json sample but it is often in yaml too - dropped the not needed parts for this ticket:

```json
{
  "apiVersion": "v1",
  "clusters": [
    {
      "cluster": {
        "certificate-authority-data": "xxxxxx",
        "server": "https://xxxx:443"
      },
      "name": "local"
    }
  ],
  "contexts": [
    {
      "context": {
        "cluster": "local",
        "user": "user"
      },
      "name": "Default"
    }
  ],
  *"current-context": "Default",*
  "kind": "Config",
  "preferences": {},
  "users": [
    {
      "name": "user",
      "user": {
        // ...
      }
    }
  ]
}
```

the value I want as a segment is `current-context` (`Default` here)

**Comment by DeepSpace2** [comment]
Can you please elaborate how this is different than the current approach used by the [kubectl](https://ohmyposh.dev/docs/segments/cli/kubectl) segment?

**Comment by JanDeDobbeleer** [comment]
@DeepSpace2 good point, I wanted to also validate that. I think we already have this covered.

**Comment by rmannibucau** [comment]
Ok, missed the `parse_kubeconfig` flag which is what I was looking for (the name `kubectl` is misleading cause it makes it look like an exec which is undesired).

Is it possible to make an entry "kubernetes" and point to kubectl page in the doc?

**Comment by Allaman** [comment]
You can slam every command in there, take a look at my [config](https://github.com/Allaman/dots/blob/589e983146f3203f8f6797023b646aa9d5a9e1af/dot_config/oh-my-posh/config.toml#L98) for inspiration. :)

**Comment by rmannibucau** [comment]
@Allaman didnt get it, goal is no exec/fork. It was done in kubectl command but was not referenced as kubernetes so didnt find it first so all good from my window
