### ISSUE TITLE
OMP Startup very slow due to update check

### ISSUE THREAD

**Issue by rtfmkiesel** [JanDeDobbeleer/oh-my-posh#5309]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When starting my PowerShell session, the shell takes over 5s to get ready. 

I've done some light debugging:

Using PSProfiler, I measured my PowerShell profile script. This clearly points to OMP. 

```ps1
Measure-Script C:\Users\USER\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

    C:\Users\USER\Documents\PowerShell\Microsoft.PowerShell_profile.ps1


      Count  Line       Time Taken Statement
      -----  ----       ---------- ---------
          1     1    00:05.1198245 oh-my-posh init pwsh --config $env:USERPROFILE\.config\powershell\custom_ohmyposh.json | Invoke-Expression
          0     2    00:00.0000000
          1     3    00:00.0004130 $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
          1     4    00:00.0003760 $env:POWERSHELL_TELEMETRY_OPTOUT = 1
          0     5    00:00.0000000
          1     6    00:00.0267355 . $env:USERPROFILE\.config\powershell\user_profile.ps1
```

It's a custom theme but it does not matter as it also happens with a built-in one:

```ps1
Measure-Command { oh-my-posh init pwsh --config $env:POSH_THEMES_PATH/jandedobbeleer.omp.json | Invoke-Expression }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 110
Ticks             : 51107174
TotalDays         : 5.91518217592593E-05
TotalHours        : 0.00141964372222222
TotalMinutes      : 0.0851786233333333
TotalSeconds      : 5.1107174
TotalMilliseconds : 5110.7174
```

Both are around the same. 

I then saved the output of `oh-my-posh init pwsh --config $env:USERPROFILE\.config\powershell\custom_ohmyposh.json`:
```ps1
(@(& 'C:/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe' init pwsh --config='C:\Users\USER\.config\powershell\custom_ohmyposh.json' --print) -join "`n") > debug.ps1
```

Using PSProfiler again, I've traced the loading time to the line `$Process.WaitForExit()` in `Start-Utf8Process`.
```ps1
Measure-Script .\debug.ps1 -Top 3

    .\debug.ps1


      Count  Line       Time Taken Statement
      -----  ----       ---------- ---------
          0     1    00:00.0000000 # remove any existing dynamic module of OMP
          0     2    00:00.0000000 if ($null -ne (Get-Module -Name "oh-my-posh-core")) {
          1     3    00:00.0011183     Remove-Module -Name "oh-my-posh-core" -Force
...
          2   116    00:05.0701980         $Process.WaitForExit()
...
```

How can this be investigated further?

### Theme

Custom but it does not matter

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
¯\_(ツ)_/¯
```

**Comment by JanDeDobbeleer** [comment]
@rtfmkiesel this isn't Start-Process being slow but most likely Defender or another virus scanner blocking the execution.

**Comment by rtfmkiesel** [comment]
Even with temporarily adding exclusions for pwsh, oh-my-posh, and the Windows Terminal, it still takes >5s. Also disabling Defender temporarily does not help. Do you have any more debugging steps I could do here?

**Comment by JanDeDobbeleer** [comment]
Not sure, 5 seconds is nowhere near normal so there's something influencing the execution. Could still be a segment causing it, but the oh-my-posh debug would need to show it too, and that has nothing to do with init.

**Comment by rtfmkiesel** [comment]
```ps1
measure-command { oh-my-posh debug }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 68
Ticks             : 683722
TotalDays         : 7.91344907407407E-07
TotalHours        : 1.89922777777778E-05
TotalMinutes      : 0.00113953666666667
TotalSeconds      : 0.0683722
TotalMilliseconds : 68.3722
```

I'll spend some time this weekend investigating this further. This was not always the case. In the past, it was around 1-2s, which was acceptable for me.

**Comment by JanDeDobbeleer** [comment]
68ms is perfectly fine for the prompt rendering (which is what debug does, and more).

**Comment by rtfmkiesel** [comment]
Just figured it out! It was the update check that just takes forever. 

This is visible as Sysinternals Process Monitor showed the program waiting forever with a network request.

After running `oh-my-posh disable notice`, I've got a very fast startup time again. 
```ps1
1    59    00:00.1103982 oh-my-posh init pwsh --config
```


Here's some proof: 
```ps1
oh-my-posh enable notice && measure-command { oh-my-posh notice }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 26
Ticks             : 50267635
TotalDays         : 5.81801331018518E-05
TotalHours        : 0.00139632319444444
TotalMinutes      : 0.0837793916666667
TotalSeconds      : 5.0267635
TotalMilliseconds : 5026.7635
```

```ps1
oh-my-posh disable notice && measure-command { oh-my-posh notice }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 24
Ticks             : 248742
TotalDays         : 2.87895833333333E-07
TotalHours        : 6.9095E-06
TotalMinutes      : 0.00041457
TotalSeconds      : 0.0248742
TotalMilliseconds : 24.8742
```

Guess I'll go and debug network stuff then. Thanks anyway!

**Comment by JanDeDobbeleer** [comment]
@rtfmkiesel ah crap. I should've known this. The 5 seconds gives it away.
