### ISSUE TITLE
Chinese garbled characters when running Java commands after installing v3.113.0

### ISSUE THREAD

**Issue by DustinWin** [JanDeDobbeleer/oh-my-posh#531]
Windows 10 PowerShell
In the previous version, Chinese will not be garbled.
![Snipaste_2021-03-15_21-08-52](https://user-images.githubusercontent.com/45238096/111158151-aa329480-85d2-11eb-816b-1fa94f34a203.png)

**Comment by lnu** [comment]
Probably related to this change https://github.com/JanDeDobbeleer/oh-my-posh/commit/ce5a9d6b768b8807e349779c91b8bf236c21fa60
By default, the console input and output encoding is set to UTF-8 now(which should be soon the default for powershell core).
What's your default encoding? if you call `pwsh -noprofile`(from a run command window) you'll get an untouched powershell prompt and from there get the original encoding with `[console]::OutputEncoding` or `[console]::InputEncoding`.
Looks like this on mine:
![image](https://user-images.githubusercontent.com/1829553/111162321-56a55400-859c-11eb-8e5a-b6a2708b33e9.png)

**Comment by DustinWin** [comment]
> Probably related to this change [ce5a9d6](https://github.com/JanDeDobbeleer/oh-my-posh/commit/ce5a9d6b768b8807e349779c91b8bf236c21fa60)
> By default, the console input and output encoding is set to UTF-8 now(which should be soon the default for powershell core).
> What's your default encoding? if you call (from a run command window) you'll get an untouched powershell prompt and from there get the original encoding with or .
> Looks like this on mine:`pwsh -noprofile``[console]::OutputEncoding``[console]::InputEncoding`
> ![image](https://user-images.githubusercontent.com/1829553/111162321-56a55400-859c-11eb-8e5a-b6a2708b33e9.png)

Use Oh-My-Posh:
![Snipaste_2021-03-15_21-45-43](https://user-images.githubusercontent.com/45238096/111163437-1368d680-85d8-11eb-8e86-b41e601eb43c.png)

Unused Oh-My-Posh:
![Snipaste_2021-03-15_21-48-46](https://user-images.githubusercontent.com/45238096/111163642-3d21fd80-85d8-11eb-9f5a-a4212d8a0b0f.png)

**Comment by lnu** [comment]
Apart from java, do you notice something else not working as before?
Which version of java do you use(adoptopenjdk?)?
And which version of powershell?

**Comment by DustinWin** [comment]
> Apart from java, do you notice something else not working as before?
> Which version of java do you use(adoptopenjdk?)?

Other operations can display Chinese normally, such as viewing files or folders. The Java version is 15.0.2, and the PowerShell version is 1.0(or 7.2.0).

**Comment by JanDeDobbeleer** [comment]
This is exactly what I was afraid of. That said, this will be an issue anyways when PS defaults to UTF8. Not sure how to proceed.

**Comment by lnu** [comment]
looks like this issue https://www.programmersought.com/article/5994857602/
and like this https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding 
Can you try to set the file.encoding to utf-8 for java?

**Comment by DustinWin** [comment]
> looks like this issue https://www.programmersought.com/article/5994857602/
> and like this https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding
> Can you try to set the file.encoding to utf-8 for java?

I have set this environment variable before, and the Chinese will not be garbled after the setting is complete. But this means that in the future, editing Java files must be saved in UTF-8 encoding, and CMD needs to be switched to the 65001 "codepage", which is more troublesome than before. 😭

**Comment by JanDeDobbeleer** [comment]
You should always save files as UTF8 imho, otherwise it won't work cross person/locale. It's the only sensible standard. About CMD, don't use it anymore please, I beg you.

EDIT: even for cross platform's sake, it's a really bad idea. Only Windows still uses different codepages for the terminals due to legacy support/non breaking changes policy but we're at a point where that's just a really bad idea.

**Comment by DustinWin** [comment]
> You should always save files as UTF8 imho, otherwise it won't work cross person/locale. It's the only sensible standard. About CMD, don't use it anymore please, I beg you.
> 
> EDIT: even for cross platform's sake, it's a really bad idea. Only Windows still uses different codepages for the terminals due to legacy support/non breaking changes policy but we're at a point where that's just a really bad idea.

In other words, the future trend is that PowerShell(Windows) uses UTF-8 as the encoding format by default, right?

**Comment by lnu** [comment]
exactly :)

**Comment by JanDeDobbeleer** [comment]
> the future trend is that PowerShell(Windows) uses UTF-8 as the encoding format by default, right

Correct.

**Comment by DustinWin** [comment]
> > the future trend is that PowerShell(Windows) uses UTF-8 as the encoding format by default, right
> 
> Correct.
Okay, thank you for your answer! 😁

**Comment by DustinWin** [comment]
> exactly :)

Thank you for your answer!

**Comment by lnu** [comment]
On your dev project you can use an editorconfig file and set the default encoding(and other things).

**Comment by DustinWin** [comment]
> On your dev project you can use an editorconfig file and set the default encoding(and other things).

Okay, I know. It seems that I have to set up a large number of software encoding formats.😂

**Comment by JanDeDobbeleer** [comment]
@DustinWin do you feel it's ok to close this?

**Comment by DustinWin** [comment]
> @DustinWin do you feel it's ok to close this?

Yes.👌

**Comment by TTsdzb** [comment]
Hey there's one way to set your encoding default to UTF-8 on Windows.  
Using Chinese as an example (I'm not sure if other languages are the same):  
设置->时间和语言->语言  
Then scorll down and click:  
管理语言设置->更改系统区域设置
And check "Beta 版：使用 Unicode UTF-8 提供全球语言支持"
