### ISSUE TITLE
The conda environment name disappears when windows powershell enters the user's root directory.

### ISSUE THREAD

**Issue by marf-ma** [JanDeDobbeleer/oh-my-posh#5324]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I switched conda environments `conda activate labelme` in the user root directory, and using `conda env list`, I could see that the switch was indeed successful, but the conda environment name did not appear. However, when I `cd` into the subdirectory, the environment name 'labelme' appeared and it was a correct env. But when I `cd ..` back to the user root dir and it disappears again.
![image](https://github.com/user-attachments/assets/50012418-a731-4b15-8063-b9d8193f6b13)
btw, I am using windows terminal, my **cmd**, **powershell** are not configured with oh-my-posh, they are all fine, it only appears on **windows powershell** which is configured with oh-my-posh.

### Theme

I've tried many themes which can show conda envs. Such as "ys", "space"......

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Log output

```Shell
No output
```

**Comment by JanDeDobbeleer** [comment]
@md3356 this is disabled by default in the user's home directory. Set `home_enabled` to `true` in the python segment.

**Comment by marf-ma** [comment]
> @md3356 this is disabled by default in the user's home directory. Set `home_enabled` to `true` in the python segment.

Thanks for the reply, this worked! But this seems to require adding this line of code to all the json files of the theme I want to use? Is there a more convenient way to solve this at once?

**Comment by JanDeDobbeleer** [comment]
@md3356 If you want to adjust a theme, which in theory is only a sample configuration, export it locally and reference + edit that file.
