### ISSUE TITLE
$ref not working (References, Definitions and Functions)

### ISSUE THREAD

**Issue by gabriel-vanca** [JanDeDobbeleer/oh-my-posh#5331]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I've tried to define the list of mapped locations as a reference, either in the internal definitions sections (see below) or in a separate file (cross-file referencing), but OMP doesn't seem to recognise the $ref functionality.

`{
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\ue0b0",
          "template": " \uea83 {{ .Path }} ",
          "properties": {
            "style": "agnoster_full",
             "home_icon": "~",
            "folder_separator_icon": " \ue0b1 ",
            "$ref": "#/definitions/def:mapped_locations"                    
          },            
          "background": "#2bc279",
          "foreground": "#262b44"
  },`

with these definitions:

`  "definitions": {
    "def:mapped_locations": {
      "D:/Git Repositories": "\uF09B"
    }
  },`

### Theme

[Custom Theme ](https://gist.githubusercontent.com/gabriel-vanca/b4040df5bf55b5e544e6112c47896dca/raw/b294add94a27223e9d2e4df7544e4842dcca9784/Arch_Theme.omp.json)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@gabriel-vanca that's JSON schema functionality, not JSON. A regular JSON parser doesn't support this.

**Comment by gabriel-vanca** [comment]
Oh. Can this be marked a feature request then? 👀

**Comment by JanDeDobbeleer** [comment]
@gabriel-vanca no, because that's not how JSON works unfortunately.
