### ISSUE TITLE
6-char icons not working

### ISSUE THREAD

**Issue by spdys** [JanDeDobbeleer/oh-my-posh#5358]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

trying to edit the json and it won't allow icons longer than 5 chars. for example, if i input the hex char "\uf05d7" it displays the icon for "\uf05d" instead.

### Theme

catppuccin_mocha

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

### Log output

```Shell
(it's not that kind of bug, it just omits the last char of the icon hex code)
```

**Comment by JanDeDobbeleer** [comment]
@spdys this isn't a bug but how JSON works. You're looking for the surrogate pair, you can find that value when clicking the UTF8 button on the Nerd Fonts cheat sheet.
