### ISSUE TITLE
loading config from url does not work

### ISSUE THREAD

**Issue by harrhp** [JanDeDobbeleer/oh-my-posh#5361]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Loading config from url does not work in latest version. It works on 22.1.0.

### Theme

https://raw.githubusercontent.com/harrhp/configuration/HEAD/files/custom.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
`[ERROR] 07:21:36.846 load.go:loadConfig:66 → open https://raw.githubusercontent.com/harrhp/configuration/HEAD/files/custom.omp.json: The filename, directory name, or volume label syntax is incorrect.`
```

**Comment by JanDeDobbeleer** [comment]
See other issue for explanation.
