### ISSUE TITLE
Sample configuration example image on Docs segments

### ISSUE THREAD

**Issue by v-amorim** [JanDeDobbeleer/oh-my-posh#5367]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

Would be nice to see an example of the sample configuration on the documentation, as a way to visually understand what that segment do.

Can be with the default theme.

Bonus: also show the segments conditional outputs, like different colors, icons or text that appear based on conditions (if appliable).

**Comment by JanDeDobbeleer** [comment]
@v-amorim but that be so many variations. You mean a visual representation, right? If so, that's not something I'm going to add. It's easy to play around and immediately see the effect in the terminal.

**Comment by v-amorim** [comment]
True, maybe just a visual representation of the provided sample code in a normal environment. 
But it is something related to this other Feature I requested, https://github.com/JanDeDobbeleer/oh-my-posh/issues/5368

**Comment by JanDeDobbeleer** [comment]
@v-amorim I think that one is more feasible, especially if we allow to set segment values so you can test/debug segment templates etc too. That's the one which can be hugely beneficial. Closing this as that one's a lot more interesting and I think I know how we can achieve this.
