### ISSUE TITLE
Add Hyperlink Support to Any Template Segment

### ISSUE THREAD

**Issue by v-amorim** [JanDeDobbeleer/oh-my-posh#5369]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

#### Request
Is it possible to use OSC8 hyperlinks in any segment template? I would like the ability to add a hyperlink to any segment icon or text, allowing users to link to a page they like or find useful when clicking the segment.

#### Background
After reviewing the documentation, I noticed that the OSC8 hyperlink technology is already implemented for the `.Location` (in the "path" segment) and `.UpstreamURL` (in the "git" segment). 

Expanding this capability to all segments would significantly enhance the flexibility and usability of custom themes.

**Comment by JanDeDobbeleer** [comment]
@JanDeDobbeleer this is available. Check for the [template helper functions (url and path)](https://ohmyposh.dev/docs/configuration/templates#helper-functions).

**Comment by v-amorim** [comment]
@JanDeDobbeleer Is it for any segment? I want to use custom URL in other segments 

I've tried this and got an error
```javascript
{
  "type": "os",
  "style": "diamond",
  "background": "p:main_background",
  "foreground": "p:os_color",
  "template": "{{ url .Icon 'https://test.com' }}"
}
```

![image](https://github.com/user-attachments/assets/b4d54e2d-9576-4944-b43d-99b986fb6399)

**Comment by v-amorim** [comment]
Never mind.

It has to be a variable, thanks!

```json
"var": {
    "github": "https://github.com/v-amorim"
 }
...
{
  "template": "{{ url .Icon .Var.github }} "
}
```

![image](https://github.com/user-attachments/assets/3aea4a2e-34b2-4e28-99bf-2826fd75cb8a)

**Comment by JanDeDobbeleer** [comment]
@v-amorim needs to be double quoted, not single. It works with a plain URL as well.

**Comment by v-amorim** [comment]
To use double quotes I would need escape characteres, when using json. Right?

Everything I tried:
```
"template": "{{ url .Icon .Var.github }} " ✅
"template": "{{ url .Icon https://github.com }} " ❌
"template": "{{ url .Icon 'https://github.com' }} " ❌
"template": "{{ url .Icon "https://github.com" }} " ❌
"template": "{{ url .Icon (https://github.com) }} " ❌
"template": "{{ url .Icon $(https://github.com) }} " ❌
```

**Comment by JanDeDobbeleer** [comment]
@v-amorim yes, but you never did:

```
"template": "{{ url .Icon \"https://github.com\" }} "
```

**Comment by v-amorim** [comment]
Awesome, thanks!
