### ISSUE TITLE
add a segment for displaying Python Envs (conda) for theme "quick-term.omp.json"

### ISSUE THREAD

**Issue by Pavun-KumarCH** [JanDeDobbeleer/oh-my-posh#5384]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

This feature would benefit from this!

**Comment by JanDeDobbeleer** [comment]
@Pavun-KumarCH you can copy and tweak the theme yourself for this. We're not adjusting themes anymore for these specific requests, they're samples to start from.
