### ISSUE TITLE
OMP3 doesn't updates terminal title like OMP2 did

### ISSUE THREAD

**Issue by catthehacker** [JanDeDobbeleer/oh-my-posh#54]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Terminal title is not set to current directory. Perhaps it could be made into optional setting where different values can be added into it?
![image](https://user-images.githubusercontent.com/31106839/95696686-652dbf00-0c3c-11eb-8221-9bb263e55b0f.png)

### Environment

- Oh my Posh version: 3.13.0
- Theme: powerlevel10k_classic
- Operating System: Windows 10 / Debian 9
- Shell: PowerShell 7
- Terminal: Windows Terminal

### Steps to Reproduce

1. `Import-Module oh-my-posh`
2. change current working directory

**Expected behavior:** Title has current path

**Actual behavior:** Current shell name is present

**Comment by JanDeDobbeleer** [comment]
That can be done indeed. I'll create a high level setting that does this when enabled.

**Comment by JanDeDobbeleer** [comment]
3.14.0 introduces a `console_title` switch that enables V2 behavior in regards to that. See the [docs](https://ohmyposh.dev/docs/configure/#general-settings) for more information.
