### ISSUE TITLE
Issue with Apple Silicon

### ISSUE THREAD

**Issue by boarder2** [JanDeDobbeleer/oh-my-posh#540]
### Description

When trying to use OMP on an Apple Silicon device with zsh 

### Environment

- Oh my Posh version: 3.115.0
- Theme: any
- Operating System: macOS 11.2.3 on Apple Silicon
- Shell: zsh
- Terminal: iTerm2 or default Terminal

### Steps to Reproduce

1. Install OMP via instructions on the website
2. Open a terminal

**Expected behavior:** Prompt should show as expected

**Actual behavior:** Shows the following error then the default prompt
`(eval):1: bad pattern: ^[[38`

I've narrowed it down to https://github.com/JanDeDobbeleer/oh-my-posh/blob/d3252acf859753bb432acc7436cc73230f754a2a/src/init/omp.zsh#L14

I've attempted to compile OMP locally to dig further but ran into issues with getting go-bindata to work.

**Comment by JanDeDobbeleer** [comment]
@boarder2 you don't need `go-bindata` anymore, is there still an indication it's used somewhere? The eval works for me on zsh using macOS on intel. That should work regardless. Can you execute `oh-my-posh --version` from the CLI?

**Comment by royvou** [comment]
One interesting thing would be if rosetta is enabled for the shell and if it makes a difference!

(e.g. Arm binaries vs x64 binaries with rosetta)

**Comment by JanDeDobbeleer** [comment]
@royvou I was in the assumption it would build the arm version as homebrew handles building locally. Unless that somehow doing funky things.

**Comment by royvou** [comment]
> @royvou I was in the assumption it would build the arm version as homebrew handles building locally. Unless that somehow doing funky things.

That's the info I wanted to add in the issue! as it could be both (in theory) , depending if the shell was using rosetta or not. (and it might be worth to check if homebrew 3 is installed which has official support for m1 macs) 

If I'm correct I've seen a similar issue somewhere else, where the native binary arm version did not work correctly but it did work in rosetta (or was it the other way around?), will try if I can find the source.

**Comment by boarder2** [comment]
> @boarder2 you don't need `go-bindata` anymore, is there still an indication it's used somewhere? The eval works for me on zsh using macOS on intel. That should work regardless. Can you execute `oh-my-posh --version` from the CLI?

Version of OMP is 3.115.0
Brew version is 3.0.7

Eval also works for me on macOS on Intel

This is where the reference to go-bindata is https://ohmyposh.dev/docs/contributing_started

I was able to get it to compile locally so I can play around if you've got any suggestions where to start!

**Comment by boarder2** [comment]
Ok, I think I've tracked this down to https://github.com/shirou/gopsutil/issues/1043

When using `--init` in the .zshrc eval it uses https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/init/omp.zsh

Which doesn't pass a `--shell` argument and relies on auto detection.

If I replace my .zshrc with the contents of omp.zsh and add a `--shell zsh` in the eval, it works!

Seems like you could probably hard code the shell type in omp.zsh since you've already made the determination of which shell you're trying to use at that point.
