### ISSUE TITLE
VS Code Terminal (PowerShell) command undeletable extra first letter

### ISSUE THREAD

**Issue by erbanku** [JanDeDobbeleer/oh-my-posh#5402]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

A bug happened!
VS Code Terminal (PowerShell) command undeletable extra first letter shown below, and unable to delete. (but it is not affecting the functionality of PowerShell)
![ShareX_2024-08-02_10-00-25_Friday_Window](https://github.com/user-attachments/assets/c626bea1-c003-4c83-a111-0086939fdec6)

### Theme

A theme modified from the official one.
Works great with PowerShell in Windows Terminal and Git Bash.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
I will provide these when needed
```

**Comment by JanDeDobbeleer** [comment]
@erbanku this is solved with the latest release. The emoji's were calculated incorrectly.

**Comment by erbanku** [comment]
Thanks.
