### ISSUE TITLE
root path directory with global git hooks are detected as git repo

### ISSUE THREAD

**Issue by randelramirez** [JanDeDobbeleer/oh-my-posh#5403]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I installed a global pre-commit/push hook  it added a ".git" folder in my root directory

![image](https://github.com/user-attachments/assets/48e72754-d2b4-45b3-92f0-069a48af30ab)

because of that whenever I open the terminal in my root directory I get a broken text/glyph on the path as a result

![terminal](https://github.com/user-attachments/assets/2e54aa0e-335c-422b-9b26-5f05102ac3f0)

I'm not sure if this can be fixed through editing the theme, but I thought of raising it here 🙏

### Theme

Aliens (but I'm pretty sure other themes might be affected as well)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
No logs needed for this I think
```

**Comment by JanDeDobbeleer** [comment]
@randelramirez this is our fastest way to determine a git repository without resorting to doing CLI calls. `.git` is by convention and in my 8 years of doing this, that's the first time ever anyone reports this 😅. Rather than adjust this, and thus take up more time, I propose to exclude this by adding the [exclude_folders](https://ohmyposh.dev/docs/configuration/segment#include--exclude-folders) property.

**Comment by randelramirez** [comment]
> @randelramirez this is our fastest way to determine a git repository without resorting to doing CLI calls. `.git` is by convention and in my 8 years of doing this, that's the first time ever anyone reports this 😅. Rather than adjust this, and thus take up more time, I propose to exclude this by adding the [exclude_folders](https://ohmyposh.dev/docs/configuration/segment#include--exclude-folders) property.

yeah, sorry for raising it. I was a bit bothered by that character not displaying properly 😅

btw, I have tried adding the exclude folder in the theme's json file (I'm using alien.omp.json)

```
 {
		  "exclude_folders": [
			"C:/Users/my-username-folder",
			"~"
          ],
          "background": "#95ffa4",
          "foreground": "#193549",
          "powerline_symbol": "",
          "style": "powerline",
          "template": " {{ .HEAD }} ",
          "type": "git"
         
        },
```

I have both tried "~" and the actual folder location of my user, but it seems the segment is still being rendered @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@randelramirez that should be inside the `properties` object.

**Comment by randelramirez** [comment]
It worked! Thanks so much @JanDeDobbeleer 🙏
