### ISSUE TITLE
Disable oh-my-posh if it detects that it is not running with a TTY

### ISSUE THREAD

**Issue by trajano** [JanDeDobbeleer/oh-my-posh#5419]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### What would you like to see added?

This is related to another bug that I found, https://github.com/docker/cli/issues/3019#issue-836066088 basically the oh-my-posh update message breaks the Docker SSH connection.

I tried doing `ssh -T` to the server and it still shows the oh-my-posh update message but if there's no PTTY then theoretically the processing should stop, I think it should also apply to **aliae** which is the thing that loads up oh-my-posh for me

**Comment by lewis-yeung** [comment]
For Bash/Zsh, this can be done using `[[ $- = *i* ]] && eval "$(oh-my-posh init bash)"` in `.bashrc`/`.zshrc`.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I'm also wondering if we should be doing this. It's a user configuration IMHO.

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer I'm just providing a workaround for this user-specific case, and haven't considered it to be integrated in any shell initialization script of OMP.

**Comment by trajano** [comment]
Thanks @lewis-yeung  since I am using `aliae` to start the whole thing I added it there instead
```
[[ $- = *i* ]] && eval "$( aliae init $( aliae get shell ) -c $ALIAE_CONFIG )"
```

**Comment by trajano** [comment]
> @lewis-yeung I'm also wondering if we should be doing this. It's a user configuration IMHO.

I'll close this for now the workaround is sufficient for what I need, the people who would be mainly impacted would be those using Docker over SSH context so it may be a small enough user base to not bother with.

**Comment by JanDeDobbeleer** [comment]
@trajano Can you share the workflow/actual commands? I can try to find a reliable way after my holidays.

**Comment by trajano** [comment]
I'll try to simplify it.

A `.bashrc` containing on the remote server where oh-my-posh is an older version
```
eval "$(oh-my-posh init bash)"
```

Then ensure you can connect without any prompts like known hosts and exit SSH session.  Expectation is that the update message appears
```
ssh remote
exit
```

Then do a docker command with the host specified
```
DOCKER_HOST=ssh://remote docker ps
```
