### ISSUE TITLE
Optionally silence autoupgrade output

### ISSUE THREAD

**Issue by Destroy666x** [JanDeDobbeleer/oh-my-posh#5424]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

The problem is that standard output gets messed up whenever you call let's say PowerShell from another application. In my case, I noticed it with OBS Advanced Scene Switcher and this command being ran:
`pwsh -Command "Get-Random -InputObject (Get-Content Fun-facts.txt)"`

The 1st line in the output is this:
![image](https://github.com/user-attachments/assets/62828447-2a32-4d09-972e-8e56b8f91cc6)

I would like to keep OMP autostarted in PowerShell, but without any sort of upgrade-related messages.

**Comment by JanDeDobbeleer** [comment]
@Destroy666x you can disable that using `disable_notice`. Additionally, when calling powershell to do something, use the `-NoProfile` switch.

**Comment by Destroy666x** [comment]
The 2nd part is not a solution if your profile loads some other necessary stuff that's common for many use cases. Too bad loading other profiles is not as easy with PowerShell.

The config parameter works though, missed that, thanks.

**Comment by Destroy666x** [comment]
Another example of failing stuff: cmake compilation looking for OpenSSL dependency. The upgrade info got somehow through and messed up path where cmake was looking for executable, even though I had the notice disabled. Upgrading OMP fixed it. Is it intended that the notice for failed upgrade shows in non-admin shell instances, until upgraded?

**Comment by JanDeDobbeleer** [comment]
@Destroy666x yes, it will show everywhere.
