### ISSUE TITLE
Auto_upgrade Linux non-root permission denied

### ISSUE THREAD

**Issue by D1StrX** [JanDeDobbeleer/oh-my-posh#5436]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

On Ubuntu, when enabling `auto_upgrade` in the theme file, it fails to execute. Which makes sense, since it wants to do this as non-root user.

```shell
📦 Upgrading Oh My Posh from 21.24.0 to v23.6.2

🌘 Verifying download


❌ open /usr/local/bin/.oh-my-posh.new: permission denied
```

Perhaps it should ask for the `sudo` password?

### Theme

blueish.omp

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
📦 Upgrading Oh My Posh from 21.24.0 to v23.6.2

🌘 Verifying download


❌ open /usr/local/bin/.oh-my-posh.new: permission denied
```

**Comment by JanDeDobbeleer** [comment]
@D1StrX not a bug, we can't upgrade, nor ask for sudo in the process. This is for you to solve client side. You still want this to fail, as otherwise you wouldn't know.
