### ISSUE TITLE
Show n/a for execution time if no command was invoked

### ISSUE THREAD

**Issue by sql-sith** [JanDeDobbeleer/oh-my-posh#544]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

This is a feature/wish issue.

You and your crew just helped me with another "[wishlist item](https://github.com/JanDeDobbeleer/oh-my-posh/issues/532)." Thanks for your fast response there. 

This wish is based on something I did when I was using `oh-my-posh.exe` (instead of the `oh-my-posh` module) in Windows 10. It's also something I have coded in my *nix config file for OMP. 

Basically, I go from my normal state of 90% insane to 90.0035% insane when I hit enter without entering a commend, but the prompt still shows an execution time. So in my Powershell `$PROFILE`, I had this code, which puts the execution time into an environment variable. You can see that I keep track of the prior history ID and modify the variable to read `elapsed: [n/a]` if the history ID has not increased. Can the `executiontime` section in OMP be modified to give us a way to configure what is displayed if no command was actually executed?

```
$Script:lastCommand = Get-History -Count 1

if (($null -eq $Script:lastCommand.Id) -or ($Script:lastCommand.Id -eq $global:lastHistoryId)) {
    $env:__elapsed__ = 'elapsed: [n/a]'
}
else {
    $global:lastHistoryId = $Script:lastCommand.Id

    $Script:durationFormat = 'd\.hh\:mm\:ss\.fff'
    $Script:duration = ($Script:lastCommand.Duration.ToString('d\.hh\:mm\:ss\.fff'))
    
    # remove days portion if zero:
    if ($Script:duration.Substring(0, 2) -eq '0.') {
        $Script:duration = $Script:duration.Substring(2)
        
        # remove hours/minutes portions if zero. what a hack, sorry.
        foreach ($Script:element in "hours", "minutes") {
            if ($Script:duration.Substring(0, 3) -eq '00:') {
                $Script:duration = $Script:duration.Substring(3)
            } 
            else {
                continue
            }
        }
    }   
    $env:__elapsed__ = "elapsed: $Script:duration"
}
```

### Environment
- Oh my Posh version: 3.115.0
- Theme: custom
- Operating System: Windows 10 and WSL, both versions 1 and 2, running Ubuntu 18.04 and 20.04
- Shell:  Powershell 7.1.3, bash 5.0.17(1)-release (on Ubuntu 20.4), and bash 4.4.20(1)-release (on Ubuntu 18.4)
- Terminal: Windows Terminal 1.7.572.0

### Steps to Reproduce

1. Use the `executiontime` segment
2. Run a command to produce a value for execution time for your prompt.
3. Hit the ENTER key without running a command.
3. Observe that the execution time is still displayed.

**Expected behavior:** I wish, as if by magic, to be able to customize what is displayed for execution time when no new command has been executed.

**Actual behavior:** the execution time remains displayed even though there is no new command in `history`.

**Comment by JanDeDobbeleer** [comment]
We could also simply add a property that hides the segment when it's <= 0. Maybe that's even the default.

**Comment by lnu** [comment]
So you want to display n/a as execution time in case you hit enter without any command?

**Comment by lnu** [comment]
There's a `threshold` property on the segment to hide execution lower than a specific value
But it always keep the time of the last real command. 
![image](https://user-images.githubusercontent.com/1829553/111685503-47d2d180-8828-11eb-90ce-3d802d7ec183.png)

**Comment by tradiff** [comment]
We can detect this in the powershell, using the code @sql-sith shared, and pass a value of 0 to OMP.  At that point the threshold would apply if the user has specified one.

Would that be ok for you @sql-sith?  (either showing 0, or not showing the segment at all, depending on whether you use threshold).  Just my 2 cents, but "N/A" seems pretty specific to you.

**Comment by lnu** [comment]
Yes but it would break the existing behaviour? I did what you said and now the execution time is cleared after a blank hit. But maybe someone was relying on the old behaviour of keeping the last value.
In that case, we should send an extra param to omp telling it the last command is a blank one and let people decide what to do with it?

**Comment by JanDeDobbeleer** [comment]
@lnu whatever they used it for, it's inconsistent with the other shells so I'm in favor of aligning it.

**Comment by lnu** [comment]
So all can be done outside of omp(in the scripts only). It's easier 👍

**Comment by sql-sith** [comment]
Thanks, @lnu and @JanDeDobbeleer. Laurent, what you are pointing out is exactly what I'd like to change, or have an option to control the behavior: I don't want to see an execution time if no command was run. As you point out, OMP always shows the prior execution time if you just hit ENTER. 

Basing this on a threshold is kind of a dicey idea. Some trivial commands on my laptop actually run in 0ms. One example is simple expression evaluations in Powershell which are then just displayed on the screen. 

Obviously this is not a big deal, and may not be worth the effort, but your mission, should you choose to accept it, is to display the execution time only if a "real" shell command was run. Otherwise, either don't display it (Jan's idea) or give a format option somehow where we can say "use this string if that happens."

In both Powershell and Linux there are ways to _know_ if a command was run or not. In Powershell, use `Get-History -Count 1` as I show in the code above (I'm sure there are faster ways in code vs. PS script). In bash, it's a little trickier since `history` doesn't return a duration for each command. So for Linux, I found a project called `bash-preexec.sh` and used their hooks to inject code at the `preexec` and `precmd` events, which lets me capture the epoch time before and after the command and then fiddle from there. You have my Powershell code, and I'd be happy to post the Linux code if it helps. But like I said, is it worth the effort? That's up to you, as I don't think showing the execution time after hitting ENTER is a full-fledged bug.

As always, thanks for the fast replies.

**Comment by lnu** [comment]
As @TravisTX  pointed out, a combination of the `threshold` property and some filtering in the ps script will do the job. 
And as @JanDeDobbeleer  said, it will be in line with the other shell(zsh, bash, fish, ...)

ps: I was wrong, in fish the behaviour is the same as powershell(keeping the last time of the last real command)....
It seems they did the opposite https://github.com/fish-shell/fish-shell/issues/4926

**Comment by sql-sith** [comment]
@lnu to do it outside of OMP, I think I would have to go back to using an `oh-my-posh.exe` instead of the PS module. Is that correct? I can do that. I see that there is a Windows installer for new releases. I don't know how to have `scoop` install new releases but I can just download it from here, put my profile back the way it was, and profit. 

The reason I care about having a recent version is that I want that lower-case date you guys just did. I thought I could only get that with the module, which is why I started looking at this. If the .exe has the same functionality available for the date, I can just go back to that. I'm not sure that it's _easier_ to do outside of OMP, but it's easier for _you_. :)

**Comment by lnu** [comment]
@sql-sith  I mean the change will be done in the ps script embedded in the omp executable so as soon as you update you'll get the change.

**Comment by sql-sith** [comment]
Oh, cool, I misunderstood. Thanks for the clarification! And in case it was unclear, I wasn't upset about the "easier" comment. it's just one of my go-to talking points, intended as humor. :)
