### ISSUE TITLE
Set default `parse_kubeconfig` property within Kubernetes segment to `true`

### ISSUE THREAD

**Issue by vsantos** [JanDeDobbeleer/oh-my-posh#5443]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

The Kubernetes segment tries to get my context information through the `kubectl` binary instead of relying on your local `kubeconfig` file which would be faster. Is there any particular reason for this approach?

My suggestion is to set the most rapid solution as the default property. If that's good for everyone I can implement it through a PR. 😄 

(Personally, my Kubernetes segment hangs for 2s before giving me the output (I'm not sure why). My only option is to parse from `kubeconfig` when its output is instantaneous)

**Comment by JanDeDobbeleer** [comment]
@vsantos on second thought, go for it. Faster is better. A PR is easily created for this one.
