### ISSUE TITLE
Auto-upgrade instructions need direction

### ISSUE THREAD

**Issue by dylanh724** [JanDeDobbeleer/oh-my-posh#5452]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

In CLI, when prompted to upgrade, I now see:

> To enable automated upgrades, set 'auto_upgrade' to 'true' in your configuration.

Great! However, this falsely assumes everyone knows where "your configuration" is. They probably opened CLI to do a non-OMP task, so the average person doesn't want to look deeper into it and just ignores it (like me).

**Simply provide the path to the configuration.**

> To enable automated upgrades, set 'auto_upgrade' to 'true' in your configuration at '{path}'.

**Comment by JanDeDobbeleer** [comment]
@dylanh724 that's not necessarily a PATH you should edit depending on how you configured oh-my-posh. If you're asking this question, it's probably better to read the documentation as I assume you don't have a custom configuration.

**Comment by epikkoder** [comment]
I'll comment how I did it, as it might help you, or anyone who's looking. I'm using the `atomic.omp.json` theme, located in `C:\Users\{WINDOWS_USER}\AppData\Local\Programs\oh-my-posh\themes\atomic.omp.json` (I'm using a Windows 10 desktop, if that matters). I opened that JSON file, and I edited it, adding the `"auto_upgrade": true,` line, just below the `"$schema"` property. So if you're using one of the themes, whichever it is, open its JSON file and add that line.

As @JanDeDobbeleer said, I read the documentation, but from there, I tried to put the pieces together myself. Based on my experience with docs, they don't always tell you specifically what you need to do. 😛 
https://ohmyposh.dev/docs/configuration/general

**Comment by JanDeDobbeleer** [comment]
@epikkoder never edit a theme file directly. This is indicated in the docs as well, you need to create a local copy.

**Comment by epikkoder** [comment]
> @epikkoder never edit a theme file directly. This is indicated in the docs as well, you need to create a local copy.

Ah, well, I didn't see that part. 😅

Edit:
Ah yes, here we go. https://ohmyposh.dev/docs/installation/customize#adjust-a-theme
Recently though, my edits are retained even when Oh My Posh updates. So I guess I should be good for now?

**Comment by JanDeDobbeleer** [comment]
@epikkoder I wouldn't make a bet on that. The themes can be overridden at any time, so best to take a local copy.

**Comment by epikkoder** [comment]
Yeah. I have a copy of it in a secret gist, but I'll make a local copy and use that.
