### ISSUE TITLE
Add IconicFonts

### ISSUE THREAD

**Issue by haithium** [JanDeDobbeleer/oh-my-posh#5458]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

Hi @JanDeDobbeleer, thanks for this awesome project, I’ve created patched fonts with over 60,000 icons specifically for TUI projects. Can i create new [themes](https://ohmyposh.dev/docs/themes) using [IconicFonts](https://github.com/iconicFonts/iconic-fonts) icons and submit a pull request?

**Comment by JanDeDobbeleer** [comment]
@mdSlash I'd rather add this as a means of installation using `oh-my-posh font install` and a section in the docs. How compatible are your fonts with Nerd Fonts when it comes to glyph code points?

**Comment by haithium** [comment]
Glyph code points are different, except powerline symbols are the same in Unicode

**Comment by JanDeDobbeleer** [comment]
@mdSlash ok, theme PR's will not work as the themes are rendered with a Nerd Font. So that'll be weird. Let's add this information in the docs and a way to install and I guess we're good to go. After my holidays though.

**Comment by haithium** [comment]
Sounds good! Enjoy your holidays!

**Comment by haithium** [comment]
The different codepoints seem to be a nightmare for users, so I'm gonna close this issue. Thanks for the discussion and this awesome project.
