### ISSUE TITLE
auto_upgrade breaks scp 

### ISSUE THREAD

**Issue by hennievn** [JanDeDobbeleer/oh-my-posh#5465]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When you set "auto_upgrade": true in your config file, a message is always displayed on the console when logging on to the remote machine (in this case a raspberry pi) with ssh.  If no update is available this message simply states '✅ no new version available'

This breaks scp when you try to copy a local file to the remote machine.   scp fails with "scp: Received message too long ..."

For background on this error, see this discussion: https://unix.stackexchange.com/questions/61580/sftp-gives-an-error-received-message-too-long-and-what-is-the-reason

A solution would be not to display any message when no update is available.  scp would still fail if an update is available and an appropriate message is displayed, but this seems like an acceptable compromise. 

### Theme

N/A

### What OS are you seeing the problem on?

Linux

### Log output

```Shell
N/A
```

**Comment by JanDeDobbeleer** [comment]
@hennievn if you set `disable_notice: true`, this is the behavior you're looking for.

**Comment by hennievn** [comment]
Thank you!
