### ISSUE TITLE
omp.cache problem

### ISSUE THREAD

**Issue by kryptonproject** [JanDeDobbeleer/oh-my-posh#5467]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

i need help, my home dir always got cache file, how i get rid of them?

### Theme

atomicBit

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
omp.cache  omp.cache.493
```

**Comment by JanDeDobbeleer** [comment]
@kryptonproject you can set the `OMP_CACHE_DIR` environment variable to the correct directory, `HOME` is the default when nothing else is found.

**Comment by kryptonproject** [comment]
> @kryptonproject you can set the `OMP_CACHE_DIR` environment variable to the correct directory, `HOME` is the default when nothing else is found.

OMP_CACHE_DIR="/home/ubuntu/.oh-my-posh-cache"

like that? im sorry im new at this kinda thing.

**Comment by JanDeDobbeleer** [comment]
`export OMP_CACHE_DIR="/home/ubuntu/.oh-my-posh-cache"`

**Comment by kryptonproject** [comment]
> `export OMP_CACHE_DIR="/home/ubuntu/.oh-my-posh-cache"`

thank you, it fixed now
