### ISSUE TITLE
java: .gradle file vs directory

### ISSUE THREAD

**Issue by glucas** [JanDeDobbeleer/oh-my-posh#547]
### Description

Testing out the new Java segment with `files` as the `display_mode` and was surprised to see the segment show up in my home directory, which has no java projects. 

I found that the pattern for `*.gradle` files (e.g. `build.gradle`) is also matching the conf directory `~/.gradle`.

Unrelated: the segment is checking for maven pom.xml files (great!) but that is not mentioned in the docs.

### Environment

- Oh my Posh version: 3.116.2
- Theme: custom
- Operating System: Win10
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
@glucas I gave this some thought and maybe the most pragmatic way to resolve this is simply to exclude the home folder for language segments. There's probably other configs in there as well that can trigger this for other languages too.

**Comment by glucas** [comment]
Using it now -- works for me, thanks.
