### ISSUE TITLE
How to roll back Brew installed OMP while current version has issue

### ISSUE THREAD

**Issue by shaneholloman** [JanDeDobbeleer/oh-my-posh#5470]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

If you added this to the docs you'll need to show folks how to find the correct .rb file

I'll leave that part for you to document. 

In short, you can source from here: https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/tree/f6ba331a0509fb5e14fbb0c3d61c5d5b40af2858

Here's the basics that got me back up and running to version: `23.6.3`

Current version has a minor bork:

Has unevaluated string printing to console: `${_omp_start_time:0:$((_omp_start_time="$(_omp_start_timer)",0))}$(_omp_ftcs_command_start)`

```bash
shadmin @ kea ❯ ~ oh-my-posh --version
${_omp_start_time:0:$((_omp_start_time="$(_omp_start_timer)",0))}$(_omp_ftcs_command_start)23.6.5
```

```bash
wget https://raw.githubusercontent.com/JanDeDobbeleer/homebrew-oh-my-posh/f6ba331a0509fb5e14fbb0c3d61c5d5b40af2858/oh-my-posh.rb

brew install oh-my-posh.rb
```

fixed for now:

```bash
shadmin @ kea ❯ ~ oh-my-posh --version
23.6.3
shadmin @ kea ❯ ~ 
```

**Comment by shaneholloman** [comment]
here you go:

# Oh My Posh Version Selection Process

1. Visit the oh-my-posh Homebrew formula repository:
   https://github.com/JanDeDobbeleer/homebrew-oh-my-posh

2. Navigate to the commit history of the `oh-my-posh.rb` file.

3. Find the commit corresponding to the desired version:
   - Look at commit messages or dates to identify the appropriate version
   - Click on the commit to view its details

4. Once on the correct commit page, find the `oh-my-posh.rb` file.

5. Get the raw URL for this specific version of the file:
   - Click on the "Raw" button or construct the URL using the commit hash

6. Download the file:
   ```
   wget [raw_url_from_step_5]
   ```

7. Install using the downloaded formula:
   ```
   brew install oh-my-posh.rb
   ```

8. Verify the installation:
   ```
   oh-my-posh --version
   ```

**Comment by mjh8431** [comment]
OS: Linux Mint wilma 22 x86_64
Host: NV4xPZ (v2.1)
Kernel: Linux 6.8.0-40-generic
Uptime: 2 hours, 18 mins
Packages: 2440 (dpkg), 23 (flatpak), 18 (brew)
Shell: bash 5.2.21
Display (AUO683D): 1920x1080 @ 60 Hz in 14″ [Built-]
DE: Cinnamon 6.2.9
WM: Muffin (X11)
WM Theme: BlueSky-Clean-Dark (Mint-Y)
Theme: BlueSky-Clean-Dark [GTK2/3/4]
Icons: Futura [GTK2/3/4]
Font: Carlito (13pt) [GTK2/3/4]
Cursor: DMZ-Black (42px)
Terminal: GNOME Terminal 3.52.0
Terminal Font: MesloLGS Nerd Font Mono (12pt)
CPU: 12th Gen Intel(R) Core(TM) i5-1240P (16) @ 4.4z
GPU: Intel Alder Lake-P Integrated Graphics Control]
Memory: 5.45 GiB / 15.46 GiB (35%)
Locale: en_US.UTF-8

I used the temporary rollback command and got the following:
Fetching oh-my-posh
==> Downloading https://github.com/JanDeDobbeleer/oh-my-posh/archive/v23.6.3.tar.gz
==> Downloading from https://codeload.github.com/JanDeDobbeleer/oh-my-posh/tar.gz/refs/tags/v23.
             -=O=-#     #      #      #                                                         
Warning: oh-my-posh 23.6.5 is available and more recent than version 23.6.3.
==> go build -o=oh-my-posh -ldflags="-s -w -X 'github.com/jandedobbeleer/oh-my-posh/src/build.Ve
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################### 100.0%

==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/23.6.3: 131 files, 17MB, built in 4 seconds
==> Running `brew cleanup oh-my-posh`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /home/mjhar8431/.cache/Homebrew/oh-my-posh--23.6.3.tar.gz... (6.4MB)

╭─   mjhar8431  ~                                                      0ms   20:44:48 
╰─ $ oh-my-posh --version
${_omp_start_time:0:$((_omp_start_time="$(_omp_start_timer)",0))}$(_omp_ftcs_command_start)**23.6.5**

As you can see it did not rollback the version to 23.6.3

Running it again, I got this return
brew install oh-my-posh.rb
${_omp_start_time:0:$((_omp_start_time="$(_omp_start_timer)",0))}$(_omp_ftcs_command_start)==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O#-  #                                                                                        
Warning: oh-my-posh 23.6.3 is already installed and up-to-date.
To reinstall 23.6.3, run:
  brew reinstall oh-my-posh

Following the direction above, I got this
brew reinstall oh-my-posh
${_omp_start_time:0:$((_omp_start_time="$(_omp_start_timer)",0))}$(_omp_ftcs_command_start)==> Downloading https://ghcr.io/v2/homebrew/core/oh-my-posh/manifests/23.6.5
Already downloaded: /home/mjhar8431/.cache/Homebrew/downloads/2a66f406c7025ff148403db3ff40775244e5054ec9c5e1108b6ccb8385328725--oh-my-posh-23.6.5.bottle_manifest.json
==> Fetching oh-my-posh
==> Downloading https://ghcr.io/v2/homebrew/core/oh-my-posh/blobs/sha256:f6c8149074876df0e65a782
Already downloaded: /home/mjhar8431/.cache/Homebrew/downloads/720c4a1b55acf44e7c7bcc375f00518db1072e1b34043f0f0d20f5d7252c961d--oh-my-posh--23.6.5.x86_64_linux.bottle.tar.gz
==> Reinstalling oh-my-posh 
==> Pouring oh-my-posh--23.6.5.x86_64_linux.bottle.tar.gz
cp: cannot create regular file '/home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/./23.6.5/bin/oh-my-posh': Permission denied
Error: Failure while executing; `/usr/bin/env cp -pR /tmp/homebrew-unpack20240818-45057-xqvzja/oh-my-posh/. /home/linuxbrew/.linuxbrew/Cellar/oh-my-posh` exited with 1. Here's the output:
cp: cannot create regular file '/home/linuxbrew/.linuxbrew/Cellar/oh-my-posh/./23.6.5/bin/oh-my-posh': Permission denied

I am somewhat new to linux, so this is quite frustrating

**Comment by JanDeDobbeleer** [comment]
@shaneholloman `brew install jandedobbeleer/oh-my-posh/oh-my-posh@<version>`, this is part of the brew docs.

**Comment by shaneholloman** [comment]
Cheers, I did indeed try that first. Did't work for me on my linuxbrew install.

i issued `brew install jandedobbeleer/oh-my-posh/oh-my-posh@23.6.3` 
I wish I had the error output to show you.

amazingly fast fix from you nonetheless. thank you
