### ISSUE TITLE
`edit` sub-command is not available for `oh-my-posh (config | cache)`

### ISSUE THREAD

**Issue by mdanish-kh** [JanDeDobbeleer/oh-my-posh#5481]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

CLI help text shows supported commands `oh-my-posh config edit` & `oh-my-posh cache edit` which don't seem to be available.
 I believe the "Usage" section of help texts needs to be updated to reflect the actual commands available
 
 
<img src=https://github.com/user-attachments/assets/0034d7fe-8a21-4a6e-ba28-67469c773035 height=250>

(Similar for `oh-my-posh cache` command as shown in screenshot above)

## Environment
```
 ~ oh-my-posh version
23.6.6
```

Using Win11 and PowerShell 7.4.4

**Comment by lewis-yeung** [comment]
@mdanish-kh This subcommand requires the `EDITOR` environment variable to be properly set.

@JanDeDobbeleer I think we should clarify this in the help text.
