### ISSUE TITLE
“Dialing” to Google

### ISSUE THREAD

**Issue by Allaman** [JanDeDobbeleer/oh-my-posh#5485]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

I wondered for quite some time why my Firewall detects connections from oh-my-posh to google.com. Finally, I had some time to check the code and stumbled over [connection.go](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/runtime/http/connection.go#L12). 
Maybe, you can add one line about this feature or change the host to `https://ohmyposh.dev/`. At first, I thought some analytics are shared 🙈

**Comment by lewis-yeung** [comment]
Indeed, it will never report "connected" for users in environments where `google.com` is completely blocked.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung the same can be said for `ohmyposh.dev`, no? There's no other fool proof way to check for connectivity so I took the most available service on the web.

**Comment by Allaman** [comment]
Disclaimer: I did not check the reason oh-my-push needs to know if it can connect to the internet. 

Another approach could be to just let oh-my-push do “its thing” without the result of `IsConnected` and just time-out after x seconds.  A time-out logic should be in place, regardless?

Edit: Of course, this should not affect responsiveness of the shell

**Comment by JanDeDobbeleer** [comment]
@Allaman it is in place, but people specifically asked to NOT run any logic when there's no connection. Because you'd be waiting 5 seconds to check if we can upgrade every time you start a shell when `auto_upgrade` is enabled.
