### ISSUE TITLE
Cannot start oh-my-posh: Segmentation Fault

### ISSUE THREAD

**Issue by Blade04208** [JanDeDobbeleer/oh-my-posh#5493]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

apon starting oh-my-posh, i get 'Segmentation fault' and nothing else.

![image](https://github.com/user-attachments/assets/b1c1b3ec-11e5-4281-a31c-87807d94f308)

### Theme

Stock OhMyPosh theme.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
Segmentation fault
```

**Comment by JanDeDobbeleer** [comment]
@Blade04208 you probably installed for the wrong architecture. Depending on the installation means, your architecture could be incorrectly mapped (or the system reports the incorrect state).
