### ISSUE TITLE
_omp_executable global variable incorrectly prefixed with a dollar sign in oh-my-posh 23.6.6 using bash (git-bash in windows terminal)

### ISSUE THREAD

**Issue by jeansagi** [JanDeDobbeleer/oh-my-posh#5496]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Since the some versions ago when I start windows terminal, which uses **git-bash** by default, I see the error:
> `bash: C:/Program: No such file or directory`

Just before my prompt (I'm using theme **night-owl.omp.json**):
![image](https://github.com/user-attachments/assets/82efde53-7ff5-440a-a6dc-c12735b4e2ee)
After that everything works as expected without any problem.

I thought that was a minor glitch that would be addressed soon... but it seems not 😉.

I'm on **Windows 11 23H2** and use **Windows Terminal** with **git-bash** (git version 2.46.0.windows.1).
In my `.bashrc` I start oh-my-posh whith this command:
> `eval "$(oh-my-posh init bash --config ~/.config/ohmyposh/themes/night-owl.omp.json)"`

In fact if I comment that line and start manually oh-my-posh it show the same error reported:
![image](https://github.com/user-attachments/assets/0b32a3c5-e4c6-4671-b20e-13b8b128d470)
And as I said everything works as expected.

Trying to figure out what was happening I issed this command (changed eval from echo):
> `echo "$(oh-my-posh init bash --config ~/.config/ohmyposh/themes/night-owl.omp.json)"`
Whichs output the following code:

```sh
export POSH_THEME=C:/Users/chuch/.config/ohmyposh/themes/night-owl.omp.json
export POSH_SHELL_VERSION=$BASH_VERSION
export POWERLINE_COMMAND="oh-my-posh"
export POSH_PID=$$
export CONDA_PROMPT_MODIFIER=false
export OSTYPE=$OSTYPE

# global variables
_omp_start_time=""
_omp_stack_count=0
_omp_elapsed=-1
_omp_no_exit_code="true"
_omp_status_cache=0
_omp_pipestatus_cache=0
_omp_executable=$'C:/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe'

# switches to enable/disable features
_omp_cursor_positioning=0
_omp_ftcs_marks=0

# start timer on command start
PS0='${_omp_start_time:0:$((_omp_start_time="$(_omp_start_timer)",0))}$(_omp_ftcs_command_start)'
# set secondary prompt
PS2="$("$_omp_executable" print secondary --shell=bash --shell-version="$BASH_VERSION")"

function _omp_set_cursor_position() {
    # not supported in Midnight Commander
    # see https://github.com/JanDeDobbeleer/oh-my-posh/issues/3415
    if [[ $_omp_cursor_positioning == 0 ]] || [[ -v MC_SID ]]; then
        return
    fi

    local oldstty=$(stty -g)
    stty raw -echo min 0

    local COL
    local ROW
    IFS=';' read -sdR -p $'\E[6n' ROW COL

    stty "$oldstty"

    export POSH_CURSOR_LINE=${ROW#*[}
    export POSH_CURSOR_COLUMN=${COL}
}

function _omp_start_timer() {
    "$_omp_executable" get millis
}

function _omp_ftcs_command_start() {
    if [[ $_omp_ftcs_marks == 1 ]]; then
        printf "\e]133;C\a"
    fi
}

# template function for context loading
function set_poshcontext() {
    return
}

# regular prompt
function _omp_hook() {
    _omp_status_cache=$? _omp_pipestatus_cache=(${PIPESTATUS[@]})

    if [[ ${#BP_PIPESTATUS[@]} -ge ${#_omp_pipestatus_cache[@]} ]]; then
        _omp_pipestatus_cache=(${BP_PIPESTATUS[@]})
    fi

    _omp_stack_count=$((${#DIRSTACK[@]} - 1))

    if [[ $_omp_start_time ]]; then
        local omp_now=$("$_omp_executable" get millis --shell=bash)
        _omp_elapsed=$((omp_now - _omp_start_time))
        _omp_start_time=""
        _omp_no_exit_code="false"
    fi

    if [[ ${_omp_pipestatus_cache[-1]} != "$_omp_status_cache" ]]; then
        _omp_pipestatus_cache=("$_omp_status_cache")
    fi

    set_poshcontext
    _omp_set_cursor_position

    PS1="$("$_omp_executable" print primary --shell=bash --shell-version="$BASH_VERSION" --status="$_omp_status_cache" --pipestatus="${_omp_pipestatus_cache[*]}" --execution-time="$_omp_elapsed" --stack-count="$_omp_stack_count" --no-status="$_omp_no_exit_code" --terminal-width="${COLUMNS-0}" | tr -d '\0')"

    return $_omp_status_cache
}

if [[ $TERM != linux ]] && ! [[ $PROMPT_COMMAND =~ _omp_hook ]]; then
    PROMPT_COMMAND="_omp_hook; $PROMPT_COMMAND"
fi

$_omp_executable notice

```

I noted line 15 an incorrect use of a dollar sign IMO:

```sh
_omp_executable=$'C:/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe'
```

So please review the code generated for bash so no errors are shown at oh-my.posh start.

Kind regards,

J.

### Theme

night-owl.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

### Log output

```Shell
`oh-my-posh debug --plain` returns:
Print the prompt in debug mode.

Usage:
  oh-my-posh prompt debug [bash|zsh|fish|powershell|pwsh|cmd|nu|tcsh|elvish|xonsh] [flags]

Flags:
  -h, --help           help for debug
  -p, --plain          plain text output (no ANSI)
      --pwd string     current working directory
      --shell string   the shell to print for

Global Flags:
  -c, --config string   config file path

Since I use bash I suppose the command to be used is `oh-my-posh prompt debug bash --plain` which outputs:

Version: 23.6.6

Shell: bash (5.2.26(1)-release)

Prompt:

╭─   ]8;;file:C:/Users/chuch\  ]8;;\ 0ms                                                                                        bash  25%  17:58:39
╰─  Richard Armitage ~ Misty Mountains   

Segments:

ConsoleTitle(true)                         -   0 ms
Os(true)                                   -   0 ms
Path(true)                                 -   2 ms
Executiontime(true)                        -   0 ms
Shell(true)                                -   0 ms
Sysinfo(true)                              -   0 ms
Time(true)                                 -   0 ms
Text(true)                                 -   0 ms
Spotify(true)                              -   7 ms
Status(true)                               -   0 ms

Run duration: 349.07ms

Cache path: C:\Users\chuch\AppData\Local\oh-my-posh

Config path: C:\Users\chuch\.config\ohmyposh\themes\night-owl.omp.json

Logs:

What follows is too long... If needed I will add it in another way.
```

**Comment by lewis-yeung** [comment]
> I noted line 15 an incorrect use of a dollar sign IMO:
> 
> ```shell
> _omp_executable=$'C:/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe'
> ```
> 
> So please review the code generated for bash so no errors are shown at oh-my.posh start.

@jeansagi The use of `$` here is definitely correct so that your prompt can be rendered normally.

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung did I mess up and should `$_omp_executable notice` be `"$_omp_executable" notice`?

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer Yes, it should be quoted in Bash.

**Comment by jeansagi** [comment]
> > I noted line 15 an incorrect use of a dollar sign IMO:
> > ```shell
> > _omp_executable=$'C:/Program Files (x86)/oh-my-posh/bin/oh-my-posh.exe'
> > ```
> >     
> >   
> > So please review the code generated for bash so no errors are shown at oh-my.posh start.
> 
> @jeansagi The use of `$` here is definitely correct so that your prompt can be rendered normally.

Wow! Didn't knew that `$` bash feature: ANSI-C quoting... My bad!

But...

I saw here in this thread that mr. @JanDeDobbeleer closed this issue but I'm still having the problem, I mean this morning `oh-my-posh` updated to 23.6.7, the problems persist.

Isn't this fixed yet in 23.6.7?


J.

**Comment by JanDeDobbeleer** [comment]
You need 23.7.1, and reload the shell for it to take effect.

**Comment by jeansagi** [comment]
> You need 23.7.1, and reload the shell for it to take effect.

Ok.

I will be watching for this version to be available in chocolatey.

Thanks a lot.


J.

**Comment by JanDeDobbeleer** [comment]
@jeansagi using the installer from the releases tab will have the same result. The choco package uses the same one.

**Comment by jeansagi** [comment]
😉 For me chocolatey usually lags a bit to deliver upgrades ...

Although `cup oh-my-posh --version 23.7.2` did the trick.

I can confirm that no errors are shown when oh-my-posh starts.

Thanks a lot.


J.
