### ISSUE TITLE
Loading profile in Visual Studio Code PowerShell Extension leads to errors in custom key handler

### ISSUE THREAD

**Issue by Akaizoku** [JanDeDobbeleer/oh-my-posh#5501]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

All commands generate the following error:

> An exception occurred in custom key handler, see $error for more information: Object reference not set to an instance of an object.

This has been reported multiple times before but all issues have been closed due to inactivity:

1. #2910 
2. #4710

### Theme

Default

### What OS are you seeing the problem on?

- Windows 11
- Visual Studio Code 1.92.2

### Which shell are you using?

PowerShell for Visual Studio Code 2024.2.2

### Log output

```Shell
An exception occurred in custom key handler, see $error for more information: Object reference not set to an instance of an object.
```

**Comment by JanDeDobbeleer** [comment]
@Akaizoku this isn't an issue with oh-my-posh but `PSReadline` which is why they've been closed. We can't fix that.

**Comment by Akaizoku** [comment]
Fair, enabling the option `PowerShell Integrated Console: Use Legacy Read Line` does indeed solve the issue (see https://github.com/PowerShell/vscode-powershell/issues/4196).

Since the issue has been opened for almost two years and is not likely to get fixed soon, could we add a note in the documentation like the [explanation to install fonts for Visual Studio Code](https://ohmyposh.dev/docs/installation/fonts)?
