### ISSUE TITLE
Add Variable to Display Python Executable Parent Folder in Python Segment

### ISSUE THREAD

**Issue by v-amorim** [JanDeDobbeleer/oh-my-posh#5508]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

Enhance the Python segment by introducing a new variable that displays the parent folder of the Python executable, improving usability in monorepo environments with multiple virtual environments (venvs).

**Problem:**  
In a monorepo setup with numerous Python virtual environments, it can become challenging to track which environment is currently active. This complexity often leads to confusion, especially when dealing with various Python executables across different directories. Besides the `.venv` name, the existing Python segment lacks a straightforward way to display the parent folder of the active Python executable, making it difficult to quickly identify the environment in use.

**Proposed Solution:**  
Introduce a new variable in the Python segment configuration that displays the parent folder of the active Python executable. This feature will provide a clear and immediate indication of which environment is active, simplifying navigation and reducing errors in multi-venv setups.

**Benefits:**  
- **Improved Usability:** Quickly identify the active Python environment by displaying its parent folder.
- **Enhanced Clarity:** Minimize confusion in complex monorepo environments with multiple virtual environments.
- **Streamlined Development:** Make it easier to navigate and manage different venvs, leading to more efficient workflows.

**Comment by JanDeDobbeleer** [comment]
@v-amorim just had a look at this, already possible using the following template part:

```
{{ base (dir (stat .Executable)) }}
```

**Comment by v-amorim** [comment]
@JanDeDobbeleer I tried adding to the template but didn't work as intended, it will only show "bin" regardless of the env used

![image](https://github.com/user-attachments/assets/4481afa1-7d09-4ca6-8987-b14ccc40be0f)

What I intended with this variable was to see "processing" or "datawarehouse"

**Comment by JanDeDobbeleer** [comment]
You need to upgrade. I just added those functions over lunch.

**Comment by v-amorim** [comment]
The printscreen output was using 23.10.1, the latest, with this segment settings:
```json
        {
          "type": "python",
          "style": "diamond",
          "background": "p:secondary_background",
          "foreground": "p:terminal_lightblue",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4",
          "template": "\ue235 {{ .Full }} {{ base (dir (stat .Executable)) }}",
          "properties": {
            "fetch_version": true,
            "folder_name_fallback": false
          }
        }
```

**Comment by JanDeDobbeleer** [comment]
@v-amorim that's because you need to `dir` twice (or three, and this really depends on the python runtime folder structure, can be different), the executable is always in the `bin` folder.

**Comment by v-amorim** [comment]
Indeed working as intended, thank you!

```json
"template": "\ue235 {{ .Full }} {{ base (dir (dir (dir (stat .Executable)))) }}"
```

![image](https://github.com/user-attachments/assets/c1bfefbc-ed78-43fa-ac43-49d48c111e0f)
