### ISSUE TITLE
Cannot hide session segment for default user

### ISSUE THREAD

**Issue by safor** [JanDeDobbeleer/oh-my-posh#551]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The [Session](https://ohmyposh.dev/docs/session) segment doesn't work according to the specification. I cannot hide the segment, when `display_default`:`false` and `default_user_name` marches the current user name.

### Environment

- Oh my Posh version: 3.117.2
- Theme: custom
- Operating System: Windows 10
- Shell: PowerShell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Add the session segment definition as
```json
{
  "type": "session",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "white",
  "background": "#111111",
  "default_user_name": "john",
  "display_default": false
},
```
2. Restart terminal

**Expected behavior:** The session segment is hidden.

**Actual behavior:** The session segment is displayed as `john@my-laptop`, where `john` is my current user.

**Comment by JanDeDobbeleer** [comment]
@safor that's because the structure of your segment is incorrect. You added the properties directly underneath the segment but they need to be inside `properties`. Use this and it should work (validated on my machine):

```json
{
  "type": "session",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "white",
  "background": "#111111",
  "properties": {
       "default_user_name": "john",
       "display_default": false
   }
},
```

**Comment by safor** [comment]
@JanDeDobbeleer, thank you! I have to RTFM more carefully. Moving properties inside the `properties` object helped. 

Though, my version of oh-my-posh required `display_default_user` property instead of `display_default` one. In the documentation and the source code, I can see that `display_default` should be used. Unfortunately, I don't see what is wrong.

I installed oh-my-posh using [scoop](https://scoop.sh/) and I have the latest version:
```terminal
> scoop list
Installed apps:                                                                                                                                                                                                                             
  oh-my-posh 3.117.2 [https://github.com/JanDeDobbeleer/oh-my-posh3/releases/latest/download/oh-my-posh.json]
```

**Comment by JanDeDobbeleer** [comment]
@safor if you run `oh-my-posh --version` does it display the same version too?

**Comment by safor** [comment]
@JanDeDobbeleer it is 3.117.2
```terminal
> oh-my-posh --version
3.117.2
```

**Comment by safor** [comment]
Hmmm, probably, I had an older version of the oh-my-posh installed as powershell module.

**Comment by safor** [comment]
Please ignore my message about the `display_default_user` vs `display_default`. I had multiple different versions.

Cheers!
