### ISSUE TITLE
Add manual build instructions in install section

### ISSUE THREAD

**Issue by siddhpant** [JanDeDobbeleer/oh-my-posh#5511]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Please add manual build instructions. It's apparently just `go build` but the version string is empty then.

**Comment by JanDeDobbeleer** [comment]
@siddhpant no, this is way too advanced and I will not support that. This is a recipe for disaster. If you want to build this, look at the release action.

**Comment by siddhpant** [comment]
How is it 'way too' advanced? Plus only those who want will follow it. All FOSS projects mention build steps.

Some people may want to compile themselves instead of blindly getting binaries from GitHub.

Why is it a 'recipe for disaster'? You make it sound you only want to distribute binaries, which is problematic and borderline malicious.

**Comment by JanDeDobbeleer** [comment]
@siddhpant I don't see how this anywhere near borderline malicious. That's a very offensive statement.

If you want to build this from source, have a look at the release action, but as binaries and installers are signed, this isn't an out of the box "things will always work as designed" type thing.

The entire SDLC is open source and traceable, even when using the upgrade command, so no, I really don't take a remark like this lightly. I don't have time to support issues with people building from source, that's a deliberate decision. If you want to go down that path, I expect you can figure this out easily. If not, don't.

**Comment by siddhpant** [comment]
> @siddhpant I don't see how this anywhere near borderline malicious. That's a very offensive statement.

Saying `This is a recipe for disaster.` is offensive from the POV of security.

> If you want to build this from source, have a look at the release action, but as binaries and installers are signed, this isn't an out of the box "things will always work as designed" type thing.

So you are saying your builds are not reproducible? Then why should we trust it? Builds being signed doesn't mean anything if the distributor is malicious. We did have the xz repo thing playing out exactly this way.

> The entire SDLC is open source and traceable, even when using the upgrade command, so no, I really don't take a remark like this lightly. I don't have time to support issues with people building from source, that's a deliberate decision. If you want to go down that path, I expect you can figure this out easily. If not, don't.

I don't see why you think you would have to "support issues with build" too much for a go program, you can also just put that in docs.

Plus, https://github.com/JanDeDobbeleer/oh-my-posh/blob/45af20c07a13f21308d155bbadc17a8d4841c4e4/.github/workflows/build_code.yml apparently does `go build` through an action, which I did but the Version string isn't there, so I'm not quite sure and asked for build instructions in good faith.

But you seem to think allowing people to build themselves using a command (for a command line application nonetheless) is `way too advanced` and a `recipe for disaster` and give flimsy reasons for it. Sorry, but that does sound malicious.

**Comment by JanDeDobbeleer** [comment]
@siddhpant You asked to add those instruction to the docs, to which I replied: no. Which I still stand by this is my project and I need to be able to support it. Knowing the broad user base, adding that is definitely a recipe for disaster.

However, this doesn't mean I don't want to provide those details, were it not you immediately went on some offensive OSS requirements crusade which doesn't really motivate me to help out.

That said, in light of transparency, allow me to show you the way.

The release action uses [goreleaser](https://github.com/JanDeDobbeleer/oh-my-posh/blob/28817bae481dfc3d715aa8aa4c1b6cda7d903e0f/.github/workflows/release.yml#L75) to build the binaries, and that's the one that also includes the [logic for versioning](https://github.com/JanDeDobbeleer/oh-my-posh/blob/28817bae481dfc3d715aa8aa4c1b6cda7d903e0f/src/.goreleaser.yml#L16).

So, leveraging `go build` alone will require the following to set the version correct (adjust accordingly):

```
go build -o=oh-my-posh -ldflags=\"-s -w -X \'github.com/jandedobbeleer/oh-my-posh/src/build.Version=23.7.2\' -X \'github.com/jandedobbeleer/oh-my-posh/src/build.Date=2024-08-22T18:11:29Z\'\"
```

This command can also be found in the [homebrew formula](https://github.com/JanDeDobbeleer/homebrew-oh-my-posh/blob/bdeac519136ed6c43afd6e5cb65a5424f93d35a4/oh-my-posh.rb#L15C15-L16C31).

Do know all of this is internal logic and subject to change at any time. Two additional reasons I'm not adding this information to the docs.

**Comment by siddhpant** [comment]
Thank you!
