### ISSUE TITLE
No documentation for uninstall

### ISSUE THREAD

**Issue by bryanniwa** [JanDeDobbeleer/oh-my-posh#552]
### Prerequisites

- [ x] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

No documentation for uninstall

### Environment

- Oh my Posh version: 3.117.2
- Theme: N/A
- Operating System: WSL 2 - Ubuntu
- Shell: Fish
- Terminal: Windows terminal

### Steps to Reproduce

1. I installed oh-my-posh for powershell and also for ubuntu but realized I don't actually need it for ubuntu as I am using oh-my-fish.
2. Try as I might, I cannot find any documentation for uninstalling oh-my-posh and `sudo apt remove` says that oh-my-posh cannot be found even though `wheris oh-my-posh` returns the correct location of the binary

Great work btw, I love how it makes powershell look

**Comment by JanDeDobbeleer** [comment]
Simply deleting the binary will do in that case.

**Comment by bryanniwa** [comment]
oh, i see. that's a little embarrassing. Thanks

**Comment by JanDeDobbeleer** [comment]
@bryanniwa we're here to learn. No judgement.

**Comment by hydrogeohc** [comment]
> Simply deleting the binary will do in that case.

Where to find the "binary"?

**Comment by JanDeDobbeleer** [comment]
@hydrogeohc on linux: use `which oh-my-posh`

**Comment by Sh-abang** [comment]
Uhmmm , quick question. I am using ubuntu on wsl2. So I deleted the binary (for ubuntu) , but it just returns after I delete it. Any help you could offer?

**Comment by JanDeDobbeleer** [comment]
@Sh-abang validate if it isn't by accident the Windows binary which is being used. Removing the init statement from your bash profile will also no longer invoke the custom prompt.

**Comment by Sh-abang** [comment]
Thank you, I got it done. Although I will be keeping the oh-my-posh on powershell, it's great. I appreciate the help.

**Comment by StressTest** [comment]
You need remove themes from` /root/themes` too

**Comment by ljredux** [comment]
And you may need to remove `oh-my-posh init pwsh | Invoke-Expression` from your Powershell profile.  In my case, located at `C:\Users\<username>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1`.

I searched anticipating issues such as this, but was reassured by this thread and went ahead.   Oops.  I guess it's time to figure out if any other remnants are left behind.

Edit:  Further to this, had to remove user environment variables `POSH_INSTALLER` and `POSH_THEMES_PATH` (including files at that location), and `C:\Users\<username>\AppData\Local\Programs\oh-my-posh\bin` from the user PATH.  None of these things were done when uninstalled with winget.  

Pretty sure it's gone now.  We will see.

**Comment by unityoxb** [comment]
winget uninstall oh-my-posh
