### ISSUE TITLE
Enable Transient Prompt

### ISSUE THREAD

**Issue by lisonge** [JanDeDobbeleer/oh-my-posh#553]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

**how to Enable Transient Prompt in powershell7 ?** 

just like p10k in zsh 

[![659DsA.png](https://z3.ax1x.com/2021/03/21/659DsA.png)](https://imgtu.com/i/659DsA)

### Environment

- Oh my Posh version:
- Theme:
- Operating System: win10
- Shell: powershell 7
- Terminal: windows terminal

**Comment by JanDeDobbeleer** [comment]
@lisonge that doesn't exist. For Powershell @TravisTX made a [module](https://github.com/TravisTX/MagicTooltips) that supports this.

**Comment by lisonge** [comment]
@JanDeDobbeleer 
 ok, thanks

**Comment by silverqx** [comment]
I'm searching for something similar too, I didn't find anything 🤨

**Comment by JanDeDobbeleer** [comment]
@silverqx @lisonge what does this do actually? Rewrite the previous parts of the prompt once you enter a command?

**Comment by silverqx** [comment]
Here it is described [Transient prompt](https://github.com/romkatv/powerlevel10k#transient-prompt).

I'm using it in every Linux distro on the zsh shells, whole terminal looks much much nicer with this feature. @JanDeDobbeleer

**Comment by silverqx** [comment]
Would be amazing to have something like this in PowerShell, I have not found anything like that for PowerShell.

**Comment by lisonge** [comment]
@JanDeDobbeleer 

![2021-06-11 07-43-08](https://user-images.githubusercontent.com/38517192/121681433-6675fb00-caed-11eb-83b0-33f4e81b6810.gif)

**Comment by silverqx** [comment]
Yeah, exactly thats it. @lisonge 

If you have run 10 commands the output looks much better without all these prompts.

![output](https://user-images.githubusercontent.com/86900/121687927-3285e000-cac3-11eb-88fd-7235c03f376d.jpg)

**Comment by JanDeDobbeleer** [comment]
That's not going to be crazy I think. Let me see what we can do 😉

**Comment by JanDeDobbeleer** [comment]
@silverqx @lisonge we have a [beta](https://ohmyposh.dev/docs/beta#transient-prompt) for this for Powershell.
