### ISSUE TITLE
Permission improvment for discord server

### ISSUE THREAD

**Issue by ClxUne09** [JanDeDobbeleer/oh-my-posh#5535]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

**Hi,**

Normal members can chat in the [hello channel](https://discord.com/channels/1023597603331526656/1055755910099771463) of the OMP Discord server. You can improve the server by preventing normal members from chatting in that channel. (I think you can also change the welcome message sticker reply permissions.)

To do this:

1. Hover over the channel.
2. Select the settings button.
3. Go to Permissions.
4. Open the `Advanced Permissions` drop-down.
5. Select the role for normal members. (If it doesn't exist, select `@everyone` to change permissions for everyone in that channel.)
   
   **Note:** The order of roles also determines their hierarchy. For example, if you move a role higher than other roles, it will gain a higher rank based on its permissions.

6. Deny `Send Messages` in the `TEXT CHANNEL PERMISSIONS` section.
7. Save changes.

> [!TIP]
> You can use `View Server As Role` feature to put yourself on that role.

Discord-related files didn’t exist here, so I couldn't create a pull request for this.

**Comment by JanDeDobbeleer** [comment]
Done
