### ISSUE TITLE
powershell decides to give me a big fat error when running it

### ISSUE THREAD

**Issue by 4kunu** [JanDeDobbeleer/oh-my-posh#5544]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

it just displays
Get-PSReadLineKeyHandler : A positional parameter cannot be found that accepts argument 'Spacebar'.
At line:484 char:18
+             if ((Get-PSReadLineKeyHandler Spacebar).Function -eq 'OhM ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSReadLineKeyHandler], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.GetKeyHandlerCommand

Get-PSReadLineKeyHandler : A positional parameter cannot be found that accepts argument 'Enter'.
At line:488 char:18
+             if ((Get-PSReadLineKeyHandler Enter).Function -eq 'OhMyPo ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSReadLineKeyHandler], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.GetKeyHandlerCommand

Get-PSReadLineKeyHandler : A positional parameter cannot be found that accepts argument 'Ctrl+c'.
At line:492 char:18
+             if ((Get-PSReadLineKeyHandler Ctrl+c).Function -eq 'OhMyP ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSReadLineKeyHandler], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.GetKeyHandlerCommand

### Theme

fish

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Print the prompt in debug mode.

Usage:
  oh-my-posh prompt debug [bash|zsh|fish|powershell|pwsh|cmd|nu|tcsh|elvish|xonsh] [flags]

Flags:
  -h, --help           help for debug
  -p, --plain          plain text output (no ANSI)
      --pwd string     current working directory
      --shell string   the shell to print for

Global Flags:
  -c, --config string   config file path
```

**Comment by JanDeDobbeleer** [comment]
@4kunu you need to upgrade PSReadLine. It's outdated (by a lot).
