### ISSUE TITLE
Getting a `command not found` error after update to 23.10.1

### ISSUE THREAD

**Issue by gorauskas** [JanDeDobbeleer/oh-my-posh#5556]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Today (2024-09-03) I used `brew update && brew upgrade` to update `oh-my-posh` to version 23.10.1

After the update, I get the error message `bash: _omp_hookprintf: command not found` when starting a new terminal session in iTerm and Alacritty. The message repeats every time it tries to render the prompt. 

I am using `oh-my-posh` with the following command in my `.bashrc` 

```
  eval "$(oh-my-posh init bash --config ~/.poshthemes/jonas.omp.json)"
```

Am I missing a package that can be installed with `brew`? or is this a bug?

### Theme

https://github.com/gorauskas/dotfiles/blob/master/.poshthemes/jonas.omp.json

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

bash

**Comment by JanDeDobbeleer** [comment]
@gorauskas can it be something else sets the `PROMPT_COMMAND` variable before oh-my-posh?
