### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by Nicocoww** [JanDeDobbeleer/oh-my-posh#5557]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### What happened?

I tried using the M365Princess theme
![Capture](https://github.com/user-attachments/assets/80251f95-cd25-4801-92d7-6f74ba3c6839)

This is the command I wrote in the profile file.
`oh-my-posh init pwsh --config 'https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/M365Princess.omp.json' | Invoke-Expression`

### Theme

I tried using the M365Princess theme
![Capture](https://github.com/user-attachments/assets/80251f95-cd25-4801-92d7-6f74ba3c6839)
Tried few other themes, same.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
There's no prompt the terminal is stuck in a loop until I delete the file to reset the profile settings with `New-Item -Path $PROFILE -Type File -Force` after
```

**Comment by JanDeDobbeleer** [comment]
@Nicocoww you need the raw GitHub link, not the HTML page of the theme.

**Comment by Nicocoww** [comment]
Hi, it was doing the same thing when I downloaded and used it locally

**Comment by JanDeDobbeleer** [comment]
@Nicocoww then you downloaded the HTML file.
