### ISSUE TITLE
oh-my-posh is not recognized as a name of a cmdlet, function, script file, or executable program

### ISSUE THREAD

**Issue by lassevk** [JanDeDobbeleer/oh-my-posh#558]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When I try to run the `oh-my-posh` command, I get the following error message:

> oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Environment

- Oh my Posh version: 3.118.0
- Theme: jandedobbeleer
- Operating System: Windows 10
- Shell: Powershell Core 7.1.3
- Terminal: Windows Terminal

### Steps to Reproduce

1. Install-Module oh-my-posh -Scope CurrentUser -AllowPrerelease
2. Add "Import-Module oh-my-posh" and "Set-PoshPrompt -Theme jandedobbeleer" into my $PROFILE file
3. Start Powershell, verify that my prompt has changed
4. Execute oh-my-posh (no arguments), get the above mentioned error message

**Expected behavior:** [What you expected to happen]

I expected that the oh-my-posh command would execute, as per the documentation.

**Actual behavior:** [What actually happened]

Error message:

> oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by JanDeDobbeleer** [comment]
You can't execute `oh-my-posh` when using the Powershell module as the binary is bootstrapped automatically by the module itself and isn't exposed. Why do you want/need to run the `oh-my-posh` command?

**Comment by lassevk** [comment]
The documentation page suggests I can use it?

https://ohmyposh.dev/docs/installation
https://ohmyposh.dev/docs/configure

and this is literally the line that the installation guide tells me to use:

> Invoke-Expression (oh-my-posh --init --shell pwsh --config "$(scoop prefix oh-my-posh)/themes/jandedobbeleer.omp.json")

which includes both oh-my-posh and scoop that isn't available. I know I can install scoop separately.

**Comment by JanDeDobbeleer** [comment]
I see. It should select module in that part rather than windows. I'll fix it. When using the module what you added in the `$PROFILE` is correct and you shouldn't do anything else anymore.

**Comment by lassevk** [comment]
OK, I was just guided to those pages because when I upgraded V2 it installed V3 alongside and thus warned me about it, and told me to go to those documentation pages for upgrade information.

Since that Invoke-Expression contained the argument "--init" I was trying to figure out if there was some kind of first-time initialization that I needed to perform.

But it works now that I've cleaned up the profile.

**Comment by JanDeDobbeleer** [comment]
@lassevk thanks for bringing this to my attention, I'll adjust the docs to reflect the right state.

**Comment by JanDeDobbeleer** [comment]
Had a look at the docs, can't fix this as the confusion is with Windows vs Powershell. The only solution is removing the module which I don't want to do :-)

**Comment by themrhead** [comment]
Sorry, @JanDeDobbeleer, but IMHO you should not close this issue.
By no means I am depreciating your work or effort.
Nevertheless, the documentation at configuration section is incorrect. The section "configuration" makes no sense at all.
The second paragraph describes the configuration process...

> To set this configuration in combination with a Oh my Posh executable, use the --config flag to set a path to a json file containing the above code. The --shell universal flag is used to print the prompt without escape characters to see the prompt as it would be shown inside a prompt function for your shell.

Then if follows with a command sample like
>oh-my-posh --config sample.json --shell universal

Sorry, but it's better to reach out a problem/issue and see that there is no solution at this moment than see it closed without solution, leading the user to disregard the thread (since one experience a problem, and the search leads it to something therotically solved).

**Comment by JanDeDobbeleer** [comment]
@themrhead check the new [docs](https://ohmyposh.dev/docs/).

**Comment by roachsinai** [comment]
Hi @JanDeDobbeleer what should I do with the code you posted at

https://github.com/JanDeDobbeleer/oh-my-posh/issues/335#issuecomment-758181922

```powershell
Set-PSReadLineOption -EditMode Vi
Set-PSReadlineOption -ViModeIndicator Script -ViModeChangeHandler {
    Param($mode)
    $Env:SHELL_VI_MODE = $mode
    # go back to the beginning of the line
    Write-Host -NoNewLine "`e[1000D"
    # rewrite the prompt manually
    write-Host -NoNewLine (oh-my-posh --shell pwsh --config ~/.jandedobbeleer.omp.json)
}
```

Thanks in advance!

**Comment by JanDeDobbeleer** [comment]
@roachsinai add it to your `$profile` so that it works automatically (reload your shell or profile afterwards).

**Comment by roachsinai** [comment]
> @roachsinai add it to your `$profile` so that it works automatically (reload your shell or profile afterwards).

I've add

```
Set-PSReadLineOption -EditMode Vi
Set-PSReadlineOption -ViModeIndicator Script -ViModeChangeHandler {
    Param($mode)
    $Env:SHELL_VI_MODE = $mode
    # go back to the beginning of the line
    Write-Host -NoNewLine "`e[1000D"
    # rewrite the prompt manually
    write-Host -NoNewLine (oh-my-posh --shell pwsh --config ~/.jandedobbeleer.omp.json)
}
```

in my $profile and reload shell and press `Esc` get error.

Could you tell me add what in my $profile then? Thanks @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
What error do you get @roachsinai ?

**Comment by roachsinai** [comment]
@JanDeDobbeleer 

![image](https://user-images.githubusercontent.com/9500049/149854234-c7ea77ca-c1bf-49f3-8ba8-a54381693092.png)

Chinese in above picture means:

> oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by roachsinai** [comment]
New release give me the oh-my-posh.exe.

**Comment by MrPickles2009** [comment]
add the following lines above your `oh-my-posh` command in `$PROFILE`:
```ps1
Import-Module oh-my-posh
```

**Comment by mehmetilker** [comment]
I guess problem with documentation is that you should either chose winget way or powershell way.
I tried first winget and writing "oh-my-posh init pwsh | Invoke-Expression" to my profile file did not work.
Then I tried with power shell with following containing in my profile file. Now it works...

```
Import-Module oh-my-posh
oh-my-posh init pwsh | Invoke-Expression
```

**Comment by JanDeDobbeleer** [comment]
@mehmetilker that is mentioned in the [docs](https://ohmyposh.dev/docs/prompt) though.

![image](https://user-images.githubusercontent.com/2492783/163526927-63b271da-2afd-4cc4-a293-c0718a7f1972.jpeg)

**Comment by mehmetilker** [comment]
@JanDeDobbeleer but i did not install with "Install-Module oh-my-posh"
I though using winget would be enough:

![image](https://user-images.githubusercontent.com/279289/163527227-a9ef7c95-2124-4645-9ebd-d2ff750168d6.png)

**Comment by JanDeDobbeleer** [comment]
It is enough. You can't use import-module when you did not install using Import-Module as there's no module. Did you restart your terminal?

**Comment by loop-eren** [comment]
Hi i use import module and i add nvim but i get same error but i use the all imports and modules what should I do

**Comment by JanDeDobbeleer** [comment]
@loop-eren I'm a bit confused by your question, we recently deprecated the module which seems to be what you're experiencing. Following all steps on the [migration page](https://ohmyposh.dev/docs/migrating) will install oh-my-posh correctly and get you going again.

**Comment by malekdev97** [comment]
I have solved this issue "oh-my-posh is not recognized"  by doing these steps.

open PowerShell as admin not from Terminal. 

and then type this command 

![image](https://user-images.githubusercontent.com/41757828/166687258-e544656b-a53c-4881-83b4-a3639039162b.png)

`Install-Module oh-my-posh -Scope CurrentUser -Force`

Here's also, My profile configuration 

```
# Prompt 
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt Paradox
```

I hope it will work with you as it works with me.

**Comment by JanDeDobbeleer** [comment]
@abdulmalikalomayri the module is deprecated so that's not an option.

**Comment by jelitter** [comment]
Hi. I've had the same issue during this week. I did the migration from the module to the winget version. It worked fine initially but I started seeing that error message after a few days (oh-my-posh not found).

Then I ran this command:
`winget upgrade oh-my-posh`
and after restarting Windows Terminal, it was working fine again (Windows Terminal *needs* to be restarted (won't work by just opening a new tab).

Edit: It seems to be happening with every new available version, a manual upgrade is necessary every time.

I also agree this issue shouldn't be closed, as it's something still active, and unrelated to the module version.

**Comment by marcelherd** [comment]
I also installed oh-my-posh via winget. If I start up Windows Terminal Preview normally, it works perfectly fine. But if I start up Windows Terminal Preview via the context menu "Open in Terminal Preview", I get the same error: 

```
oh-my-posh : The term 'oh-my-posh' is not recognized as the name of a cmdlet, function, script file, or operable
program.
```

Any idea how to fix that?

**Comment by MrPickles2009** [comment]
@marcelherd have you tried this?
[https://ohmyposh.dev/docs/installation/prompt](https://ohmyposh.dev/docs/installation/prompt)

 if something went wrong during install, sometimes it can help to link to the full path in `$PROFILE` like so:
`"$env:LOCALAPPDATA\Programs\oh-my-posh\bin\oh-my-posh.exe"`

**Comment by JanDeDobbeleer** [comment]
@marcelherd that would imply the preview doesn't load the PATH entries (which it should). You can indeed map this manually using the path @MrPickles2009 provided:

```powershell
$env:PATH = $env:PATH + ";$env:LOCALAPPDATA\Programs\oh-my-posh\bin\oh-my-posh.exe"
```

**Comment by marcelherd** [comment]
Thanks for the suggestions. Turns out, it *did* load the PATH and oh-my-posh *was* in the PATH, but when I open Window Terminal Preview via the context menu, it didn't reload the PATH (but it did when I started Windows Terminal Preview normally). Not sure how that works in the background, but restarting my PC fixed the problem.

**Comment by Calderic** [comment]
> 

看一下路径中是否有中文，我也是报错找了好久

**Comment by JanDeDobbeleer** [comment]
@gudaonanfeng that's a UTF-8 issue and in all honesty, something Windows/PowerShell just needs to fix. It's not an issue anywhere else.

**Comment by xliuxuan** [comment]
![image](https://user-images.githubusercontent.com/73270222/171428964-568d6ad7-4bc8-4628-8a61-3ebd8825f7d1.png)
![image](https://user-images.githubusercontent.com/73270222/171428992-c34907b3-ea36-4c1e-b78e-af8f96aaf5ba.png)
I don't know why there is such an error in vscode, but I have successfully used it in windows terminal

**Comment by xliuxuan** [comment]
![image](https://user-images.githubusercontent.com/73270222/171428964-568d6ad7-4bc8-4628-8a61-3ebd8825f7d1.png)
![image](https://user-images.githubusercontent.com/73270222/171428992-c34907b3-ea36-4c1e-b78e-af8f96aaf5ba.png)
I don't know why there is such an error in vscode, but I have successfully used it in windows terminal

**Comment by ZurdenRo** [comment]
> ![image](https://user-images.githubusercontent.com/73270222/171428992-c34907b3-ea36-4c1e-b78e-af8f96aaf5ba.png) I don't know why there is such an error in vscode, but I have successfully used it in windows terminal

replace this: `oh-my-posh init pwsh --config ...` for `& "$env:LOCALAPPDATA\Programs\oh-my-posh\bin\oh-my-posh.exe"`

In my profile file (powershell) i have this config, and work fine in vscode and window terminal. Please, remember close all and then open.

**Comment by JanDeDobbeleer** [comment]
@ZurdenRo be aware this is a module install without a binary (because deprecated). That means the path you're suggesting won't be there and if installed with winget it's also not necessary as the installer adds oh-my-posh to your PATH.

**Comment by ZurdenRo** [comment]
> @ZurdenRo be aware this is a module install without a binary (because deprecated). That means the path you're suggesting won't be there and if installed with winget it's also not necessary as the installer adds oh-my-posh to your PATH.

I was wrong in the answer. I read my config file(powershell), and i have this line.

`oh-my-posh init pwsh | Invoke-Expression` and work fine.

In my case, i did installed with `winget`. @xliuxuan

**Comment by EArminjon** [comment]
You need to close and restart your windows terminal completely.

**Comment by name-andy46** [comment]
I was following the steps in the microsoft documentation for terminal [here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup#install-oh-my-posh-for-powershell).
The first time I ran the command `winget install oh-my-posh`, it ran successfully without any issue.

After setting up the profile, I was constantly getting an error saying the oh-my-posh command does not exist. So tried installing again with the above command. This time it gave me two options and said I need to refine my command/instruction.

So I ran the following command since JanDeDobbeleer seems trustworthy: 
`winget install JanDeDobbeleer.OhMyPosh`

This was one of the options. The other option had a short string of random characters next to it.
Now it is working.

**Comment by TranManhCuongQN** [comment]
oh-my-posh : The term 'oh-my-posh' is not recognized as the 
name of a cmdlet, function, script file, or operable program.   
Check the spelling of the name, or if a path was included,      
verify that the path is correct and try again.
At C:\Users\Admin\Documents\WindowsPowerShell\Modules\oh-my-pos 
h\7.85.2\oh-my-posh.psm1:90 char:5
+     oh-my-posh init pwsh | Invoke-Expression
+     ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (oh-my-posh:Stri  
   ng) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JanDeDobbeleer** [comment]
@TranManhCuongQN the module is deprecated. See [here](https://ohmyposh.dev/docs/migrating) for more information.

**Comment by TranManhCuongQN** [comment]
![image](https://user-images.githubusercontent.com/89560029/177066255-3c880882-e9e0-47ab-8ca2-14cb336756f6.png)

**Comment by TranManhCuongQN** [comment]
![image](https://user-images.githubusercontent.com/89560029/177066286-9d9f332a-f38c-4d49-baa9-2bcb3cc850db.png)
I need help to fix this

**Comment by JanDeDobbeleer** [comment]
@TranManhCuongQN you first need to install [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/#install-winget).

**Comment by TranManhCuongQN** [comment]
> @TranManhCuongQN you first need to install [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/#install-winget)
I already installed it.Thanks you.I need you help setting theme

**Comment by JanDeDobbeleer** [comment]
@TranManhCuongQN OK, so you're now at the point where oh-my-posh is installed, right? You should be able to follow this [guide](https://ohmyposh.dev/docs/installation/prompt) in that case.

**Comment by danielcoop** [comment]
After I installed I had this error so I gave my machine a restart.  It now works so I guess that was enough to reset the profile.  Hopefully will save someone else some time if they're looking.

**Comment by JanDeDobbeleer** [comment]
@danielcoop restarting Windows Terminal should be sufficient as the PATH is only loaded on start.

**Comment by asadpk** [comment]
> 

This one works for me.

**Comment by Nessvah** [comment]
> Import-Module oh-my-posh

I was having the same error of most, getting an error of oh my posh is not a cmdlet recognized and the solution was just simply restart the terminal.

**Comment by JanDeDobbeleer** [comment]
@Nessvah about the module, that's a reason old version. Have a look [here](https://ohmyposh.dev/docs/migrating).

**Comment by Nessvah** [comment]
> @Nessvah about the module, that's a reason old version. Have a look [here](https://ohmyposh.dev/docs/migrating).

Thanks. I already have done that 😁 everything is working fine . Thank you!

**Comment by wigster** [comment]
May be a bug with Windows Terminal, but if I start it with the icon, oh-my-posh works fine. 

If I start it using the wt.exe, it fails with oh-my-posh.exe not recognised unless I start as an administator. For some reason, oh-my-posh is not added to the path when WT is launched with the wt command.

Terminal Preview v 1.15, latest oh-my-posh

**Comment by JanDeDobbeleer** [comment]
@wigster did you restart WT/computer? As the PATH is only loaded on start, so if an instance is already active it won't reload.

**Comment by wigster** [comment]
> @wigster did you restart WT/computer? As the PATH is only loaded on start, so if an instance is already active it won't reload.

Aha. I didn't realised that wt keeps on running. Yes -- a reboot has fixed this. Thanks!

**Comment by Israeltheminer** [comment]
> It is enough. You can't use import-module when you did not install using Import-Module as there's no module. Did you restart your terminal?

If you followed the Microsoft docs correctly, this should solve the issue.

**Comment by sadranyi** [comment]
I am having a similar issue where it works from all the terminals and Powershell when I open them direct, but in VSCode, it says oh-my-posh: The term 'oh-my-posh' is not recognized as the name of a cmdlet, function, script file, or operable program.

![image](https://user-images.githubusercontent.com/564700/194134415-e276227c-58a0-41eb-8e7f-2cd5c0ad2424.png)
![image](https://user-images.githubusercontent.com/564700/194134564-4fa0530e-7e59-4374-9ae7-fcfeb4b89aaf.png)
![image](https://user-images.githubusercontent.com/564700/194134722-e34413fe-0a10-42c8-ae3e-37b6301526a5.png)
![image](https://user-images.githubusercontent.com/564700/194134780-3c5a3c6d-819c-4079-90d6-06b3bfa8c6d6.png)

**Comment by JanDeDobbeleer** [comment]
@sadranyi somehow code doesn't load your PATH. No idea why that's the case, but we can't solve that as it's application/system specific.

**Comment by sadranyi** [comment]
@JanDeDobbeleer fixed it, thanks, had to manually add it to my system path and restarted the machine and it works now.

**Comment by sbwiecko** [comment]
> I was following the steps in the microsoft documentation for terminal [here](https://docs.microsoft.com/en-us/windows/terminal/tutorials/custom-prompt-setup#install-oh-my-posh-for-powershell). The first time I ran the command `winget install oh-my-posh`, it ran successfully without any issue.
> 
> After setting up the profile, I was constantly getting an error saying the oh-my-posh command does not exist. So tried installing again with the above command. This time it gave me two options and said I need to refine my command/instruction.
> 
> So I ran the following command since JanDeDobbeleer seems trustworthy: `winget install JanDeDobbeleer.OhMyPosh`
> 
> This was one of the options. The other option had a short string of random characters next to it. Now it is working.

Innded, just type `winget show oh-my-posh` and you get two different apps:
```
Nom        ID                      Source
------------------------------------------
oh-my-posh XP8K0HKJFRXGCK          msstore
Oh My Posh JanDeDobbeleer.OhMyPosh winget
```

Not sure where does the first app come from, but it's not working properly. Also, @JanDeDobbeleer clearly stipulates to use the winget source of its app during the installation, please follow its instructions
`winget install oh-my-posh -s winget` otherwise go for a `winget install JanDeDobbeleer.OhMyPosh`.

**Comment by JanDeDobbeleer** [comment]
@sbwiecko the first one is the store version which is the same installer as winget (but can be out of sync). Winget is always the most up-to-date other that the GitHub releases.

**Comment by adrfelipe** [comment]
> @TranManhCuongQN you first need to install [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/#install-winget).

I have the same problem, I can use the theme configured in the windows terminal but inside the VSCode it gives the same error. Did anyone find the solution?

**Comment by adrfelipe** [comment]
I have the same problem, I can use the theme configured in the windows terminal but inside the VSCode it gives the same error. Did anyone find the solution?
![image](https://user-images.githubusercontent.com/67704156/199804702-5398ae2d-436e-47fc-900f-a463b51df5da.png)
![image](https://user-images.githubusercontent.com/67704156/199804878-66c1cf76-e282-4287-8fcd-952d65f28369.png)

This is my profile file:
![image](https://user-images.githubusercontent.com/67704156/199804990-81969972-30aa-4030-83a9-201dc84d0004.png)

**Comment by JanDeDobbeleer** [comment]
@adrfelipe you need to check if vscode loaded the path. See [here](https://stackoverflow.com/questions/44868656/vs-code-terminal-doesnt-recognize-path-variables) for reference.

**Comment by saklain15** [comment]
![git-posh](https://user-images.githubusercontent.com/100775712/200556036-34e11040-bc5b-47a6-9361-b547c4898f1e.PNG)
What should I do next? Sir. How will I go to the $profile?

**Comment by saklain15** [comment]
![Capture](https://user-images.githubusercontent.com/100775712/200724297-377ba819-a4f3-4e45-bd8c-806c58accaaa.PNG)
Why these messages are still showing?

**Comment by JanDeDobbeleer** [comment]
@mehmetilker because you didn't uninstall the module and remove the `Import-Module oh-my-posh` statement from your `$PROFILE`. This is all stated in the [guide](https://ohmyposh.dev/docs/migrating) if you follow it step by step.

**Comment by joshuadabejero** [comment]
Hello, found the fix on this one. I think company laptops should have a separate installation guide due to its administrative rights / policies.

For installation you have to install it via admin rights powershell - `Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))` and not via Windows Store as it only installs on the CurrentUser privilege.

Then install the fonts - `oh-my-posh font install` if didn't work, install Meslo LGM NF manually, **install all ttf files for all users**.

From there you can use oh-my-posh with vscode terminal smoothly.

For the _Loading personal and system profile took 3325ms_. I just put `.exe -nologo` on terminal profile -> json file.

I wish this help on future reference, it is now working smoothly on my Company Laptop same with my Personal Laptop. Thanks for this project @JanDeDobbeleer finally the feel of Linux Powerline is now on Windows.

**Comment by JanDeDobbeleer** [comment]
@joshuadabejero depends on the company policies, a lot of users do not have the rights to run as admin. Same goes for font installation, that needs to be run as admin, or indeed as you state, install for all users.

**Comment by mmanueljoao** [comment]
ok, so i might need some assistant. I have two desktop working fine, but this one is giving me some trouble. 

Everything is installed as the guide using winget and there was no previous instalation. 

My $PROFILE includes these lines: 
```
$PoshThemePath = "$home\OneDrive \Documentos\PowerShell"
oh-my-posh prompt init pwsh --config "$PoshThemePath\mushroom.omp.json" | Invoke-Expression
```

But when it's loading it gives the next error. If I just run oh-my-posh, it works fine, so it "knows" the path. 

![image](https://user-images.githubusercontent.com/6817527/218332568-d045ea9f-6bc5-4fb6-bc80-f6195412d12f.png)

Any idea of what I am doing wrong ?

**Comment by JanDeDobbeleer** [comment]
@mmanueljoao yes, PowerShell isn't UTF8 by default so it fails to correctly provide the path due to the "special" character. You can set your shell temporarily to UTF8 so oh-my-posh initializes correctly. Read the following [FAQ item](https://ohmyposh.dev/docs/faq#powershell-the-term-oh-my-poshexe-is-not-recognized-as-a-name-of-a-cmdlet)

**Comment by newborne** [comment]
I have solved this issue by adding "C:\Users\win_n\AppData\Local\Programs\oh-my-posh\bin" to my system Path

**Comment by JanDeDobbeleer** [comment]
@newborne the installer should do that for you. Sometimes a reboot is required for it to persist (and for sure a shell reload).

**Comment by Chrisch3n** [comment]
I had the same problems. Sometimes my Path-Variables get messed up by another installation (I guess some config on my end is wrong, but haven't figured out what exactly).

Most of the time, it "only" deletes winget but sometimes also oh-my-posh. 
Therefore, here as reference, if you have the same problem:
- **Winget Path Variable:**     %UserProfile%\AppData\Local\Microsoft\WindowsApps
- **oh-my-posh Path Variable:**     %UserProfile%\AppData\Local\Programs\oh-my-posh\bin

**Comment by onurusluca** [comment]
Happened to me after adding android envs ([to use Quasar android](https://quasar.dev/quasar-cli-vite/developing-capacitor-apps/preparation)):

```
setx ANDROID_HOME "%USERPROFILE%\AppData\Local\Android\Sdk"
setx ANDROID_SDK_ROOT "%USERPROFILE%\AppData\Local\Android\Sdk"
setx path "%path%;%ANDROID_SDK_ROOT%\tools;%ANDROID_SDK_ROOT%\platform-tools"
```

Updating fixed it for me: 

`Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))`

**Comment by TranManhCuongQN** [comment]
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/89560029/fbdd3175-1f9d-4ec6-a7b8-603f20256b42)

**Comment by JanDeDobbeleer** [comment]
@TranManhCuongQN you're still using the module, that's been [deprecated for ages](https://ohmyposh.dev/docs/migrating) now.
