### ISSUE TITLE
Installation on powershell failed

### ISSUE THREAD

**Issue by devhl-labs** [JanDeDobbeleer/oh-my-posh#5582]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

To get this working I had to run this command manually. Perhaps it should be handled by oh-my-posh if not already installed.

Install-Module PsReadLine -Force

**Comment by lewis-yeung** [comment]
No, that's about installing/updating a PowerShell module rather than what Oh My Posh should take care of.

**Comment by JanDeDobbeleer** [comment]
@devhl-labs indeed, what @lewis-yeung said is correct. The environment setup isn't up to oh-my-posh.

**Comment by devhl-labs** [comment]
You are depending on a dependency to be installed. When it is not installed, the error does not make it clear what the problem is. And the windows installation guide has no mention of it.

**Comment by JanDeDobbeleer** [comment]
@devhl-labs PSReadLine is a PowerShell internal. You have the same in every other shell. In a normal scenario we would have a minimum version for PowerShell (which would be 6+), but as PSReadLine can be upgraded separately, this isn't required. But it's still up to the client to make that happen, we will never install anything as that goes outside of the scope of the project. We also don't upgrade git for example.
