### ISSUE TITLE
Status bar for Windows Terminal

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#5584]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

I wish there should be an additional  status line at the bottom of Windows Terminal which is inspired by oh-my-posh themes, looking like this:  
![68374055-01516b00-013c-11ea-8895-fc37759e10bb](https://github.com/user-attachments/assets/b0f49107-e0ee-4278-820f-5a552e434cd3)

**Comment by JanDeDobbeleer** [comment]
@xborke thanks for your idea. While this is very interesting, it's an entirely separate project based on the challenges it brings. I would rather create a feature request at Windows Terminal we can hook into, than us having to manage yet another lifecycle (and entire screen buffer) on top of what they already do.

**Comment by ghost** [comment]
@JanDeDobbeleer thanks for your response, yes i have already created such request and there are similar requests too in Windows Terminal, but there are not satisfied solutions yet, so do you think is it possible to create a plugin for windows terminal to have such feature? i mean like editing the json file

**Comment by JanDeDobbeleer** [comment]
@xborke anything is possible. If you look at tmux for example, which does this, it's a terminal multiplexer. Not something oh-my-posh is, or aims to be. Someone might need to create this 😬

**Comment by ghost** [comment]
@JanDeDobbeleer as Windows terminal written in C++, then probably best is learning GUI development in C++ for applying such features, and then adding them into json file, right?

**Comment by JanDeDobbeleer** [comment]
Actually, there's [a project](https://github.com/liamg/shox) that already does this. I'll have a look at if this is hackable inside oh-my-posh 😬

**Comment by ghost** [comment]
> Actually, there's [a project](https://github.com/liamg/shox) that already does this. I'll have a look at if this is hackable inside oh-my-posh 😬

@JanDeDobbeleer  there should be a way.... i am looking for your news, i think you can find the solution, or a clue that how can it be done for Windows, thanks a lot for your time mate! :)

**Comment by JanDeDobbeleer** [comment]
@xborke the challenge is it needs a conpty implementation on Windows which nobody added just yet.

**Comment by ghost** [comment]
> @xborke the challenge is it needs a conpty implementation on Windows which nobody added just yet.

ok then let's keep searching about it :) i really like tech challenges
