### ISSUE TITLE
The `.env` not appears in terminal

### ISSUE THREAD

**Issue by PedroLuisDionisioFraga** [JanDeDobbeleer/oh-my-posh#5637]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I start a virtual environment not appears it in terminal, follow the image with reference
![image](https://github.com/user-attachments/assets/f145df4b-b542-4bff-8437-c8fee019c87b)
![image](https://github.com/user-attachments/assets/3ed5b84c-4cd8-4f27-910c-ea9bc8acf8d8)

### Theme

hul10

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
ho has log
```

**Comment by JanDeDobbeleer** [comment]
@PedroLuisDionisioFraga you need to adjust the configuration to include a [python](https://ohmyposh.dev/docs/segments/languages/python) segment that fetches the virtual environment.
