### ISSUE TITLE
Disable filestatus

### ISSUE THREAD

**Issue by pedrohaccorsi** [JanDeDobbeleer/oh-my-posh#564]
### Prerequisites

- [ x] I have read and understand the `CONTRIBUTING` guide
- [ x] I looked for duplicate issues before submitting this one

### Description

Starting PowerShell and making any command is taking roughly 2. Depending on the size of the repository it should increase, which makes a big "noticeable" delay when using it multiple times throughout the day.

![image](https://user-images.githubusercontent.com/19296411/112184541-11a5a100-8bde-11eb-8a29-29003f84c9e0.png)

I believe that by disabling file status it should work much much faster, so I made it via ```posh-git``` which allows us to do so, but ```oh-my-posh``` overrides that option and file status keeps being shown.

-as a matter of fact, there's an [issue](https://github.com/dahlbyk/posh-git/issues/843) in ```posh-git``` about this, and it does seem like the issue is due to ```oh-my-posh```.

### Environment

- Oh my Posh version: 3.120.0
- Theme: Paradox
- Operating System: Win10
- Shell: 5.1.18362.1171
- Terminal: PowerShell

### Steps to Reproduce
 
1.  set profile:

*Microsoft.Powershell_profile.ps1*: 
```
Import-Module oh-my-posh
Set-PoshPrompt -Theme Paradox 
```

2. init vscode inside a git repository, specially a big one.
3. see how slow it is

**Expected behavior:** 

Disable file status and be much faster

**Actual behavior:**

cannot disable file status

**Comment by pedrohaccorsi** [comment]
almost 5s only to initialize... 

![image](https://user-images.githubusercontent.com/19296411/112186370-d2784f80-8bdf-11eb-8c75-57f9bc93092d.png)

**Comment by royvou** [comment]
You should create a custom profile (https://ohmyposh.dev/docs/upgrading#i-use-a-custom-themesettings) and disable the git segment from the new config you created. 

You should export the current theme so the rest of the configuration is the same 😄

**Comment by pedrohaccorsi** [comment]
it worked! thank you!

**Comment by JanDeDobbeleer** [comment]
@pedrohaccorsi you can also add a [property](https://ohmyposh.dev/docs/git#status) to the git segment to disable fetching the status (`display_status`). Additionally I would check your git version and update if you can, older versions are known to be a lot slower.

**Comment by pedrohaccorsi** [comment]
@JanDeDobbeleer , yes, I ended up doing exactly what you suggested and it worked like a charm! about git version, I'll check into that, thank you!
