### ISSUE TITLE
Windows PowerShell works, pwsh 7.4.5 doesn't

### ISSUE THREAD

**Issue by underlines** [JanDeDobbeleer/oh-my-posh#5662]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

First of all: OMP is awesome and I use it for years. Love your work.
I use it without problems in Windows Terminal + Windows PowerShell (the legacy one). But recently I had to move to MS `pwsh` (the open source one) and noticed it doesn't work (it never did on my machine, even on older versions).

### System
- Windows 11 Pro
- Windows Terminal (set Nerd Font, use pwsh to invoke PowerSHell 7.4.5)
- Nerd Font: 'Hack' (I tried with 'MesloLGM Nerd Font')
- Microsoft PowerShell 7.4.5 hereby referred to as `pwsh` doesn't work (tried MS Store and winget Version)
- Windows PowerShell (legacy, works)

### Windows PowerShell

![image](https://github.com/user-attachments/assets/5b1e11f0-f19e-4143-b1db-d3902ea5baaa)

**$PROFILE content:**
```text
oh-my-posh init pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression
```

`Write-Host $error` empty

**debug**

`oh-my-posh debug pwsh`

visual:

![image](https://github.com/user-attachments/assets/12d495d8-6a41-47e8-b2f6-19ae1df1e74f)

### MS pwsh 7.4.5:

![image](https://github.com/user-attachments/assets/e1e75e4b-aab4-4bf4-a308-4340fd946e44)

**$PROFILE content:**
```text
oh-my-posh init pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression
```

`Write-Host $error` empty

**debug**

`oh-my-posh debug pwsh`

visual:

![image](https://github.com/user-attachments/assets/39dca83d-2cdb-46be-a893-397284b9cb25)

### Theme

default: jandedobbeleer.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
[pwsh debug.txt](https://github.com/user-attachments/files/17118429/pwsh.debug.txt)
[Windows PowerShell debug.txt](https://github.com/user-attachments/files/17118426/Windows.PowerShell.debug.txt)
```

**Comment by underlines** [comment]
Found your [issue](https://github.com/PowerShell/PowerShell/issues/20733) in PowerShell/PowerShell

`[Console]::OutputEncoding = [Text.Encoding]::UTF8` fixed it, when added to `$PROFILE` before the OMP invokation.

So my init script now looks like this:
```powershell
[Console]::OutputEncoding = [Text.Encoding]::UTF8
oh-my-posh init pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression
Import-Module -Name Terminal-Icons
```

If you compare both outputs exactly in my log output it really seems to be an encoding problem as you noted:

- ` jb   ~   ` Windows PowerShell legacy **Renders correctly in Terminal**
- `¯éÂ jb ¯é░¯é░ ¯¬â ~ ¯é░¯é░ ´Çî ¯é` Microsoft PowerShell 7 **Renders garbage**
- ` jb   ~   ` Microsoft PowerShell 7 after changing text encoding to UTF8 **Renders correctly in Terminal**

**Comment by JanDeDobbeleer** [comment]
@underlines this is a PowerShell UTF8 issue they currently still refuse to fix. We can't solve that. You'll need to force the shell to UTF8 before initializing oh-my-posh.
