### ISSUE TITLE
Custom console_title

### ISSUE THREAD

**Issue by laguill** [JanDeDobbeleer/oh-my-posh#5667]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I would like to change the console title if I am connected to a remote machine using ssh.
It seams that the SSHSession parameter is not recognized or it it just not doable ?

Here is what I tried
`  "console_title_template": "{{ if .Root }}root @ {{ end }} {{else}} {{ if .SSHSession }}\ueba9 ssh@{{.HostName}} {{ end }} {{else}} {{ .Shell }} in {{ .Folder }}",
`

Thanks for your support

### Theme

I am building a custom a theme
[mytheme](https://github.com/laguill/powershell/edit/main/.mytheme.omp.json)

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
.
```

**Comment by lewis-yeung** [comment]
Yes, the `.SSHSession` is not available globally (i.e., outside a `session` segment).

**Comment by JanDeDobbeleer** [comment]
@laguill we can add that to the default template variables. Makes sense in a way.

**Comment by laguill** [comment]
I tried using cross segments properties following the solution of this issue but without success. It is working with a Python segment but not with a Session segment
[discussions/2460](https://github.com/JanDeDobbeleer/oh-my-posh/discussions/2460)

`"console_title_template": "{{.Shell}} in {{ .Folder}} {{ if .Root }}root in {{.Folder}} {{end}} {{if .Segments.Python.Venv }}{{.UserName}}@{{.HostName}} {{end}}",`
The code above is working but not this one

`  "console_title_template": "{{.Shell}} in {{ .Folder}} {{ if .Root }}root in {{.Folder}} {{end}} {{if .Segments.Session.HostName }}{{.UserName}}@{{.HostName}} {{end}}",`

Here is how I configured the session segment
``` 
    {
      "type": "prompt",
      "newline": true,
      "alignment": "left",
      "segments": [
        {
          "type": "session",
          "style": "diamond",
          "foreground": "#ffffff",
          "background": "#c386f1",
          "leading_diamond": "\ue0b2",
          "trailing_diamond": "",
          "template": "{{ if .SSHSession }} {{ .HostName }}{{ end }}"
        }
      ]
    },

**Comment by lewis-yeung** [comment]
@laguill That didn't work because there's no `.HostName` property in a `session` segment.

**Comment by laguill** [comment]
@lewis-yeung sorry Idon't understand what property can I use then ?
Are you talking about those properties ?
[system/session](https://ohmyposh.dev/docs/segments/system/session)

**Comment by lewis-yeung** [comment]
@laguill Yes, but if you use cross-segment template properties, only `.Segments.Session.SSHSession` works. For `.UserName`, `.HostName` and `.Root`, which are [global properties][docs] now, just write them as is. The documentation of a `session` segment is outdated and may be confusing there.

[docs]: https://ohmyposh.dev/docs/configuration/templates#global-properties

**Comment by laguill** [comment]
ok now I understand
I wonder why I did not tried it earlier :cry: 

Issue is solved now :smiley: 
```   
"console_title_style": "template",
"console_title_template": "{{.Shell}} - {{ if .Root }}root {{end}} {{if .Segments.Session.SSHSession }}{{.UserName}}@{{.HostName}} {{end}} in {{ .Folder}}",
