### ISSUE TITLE
Support 5 character icon codes

### ISSUE THREAD

**Issue by atkinsroy** [JanDeDobbeleer/oh-my-posh#5683]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

Currently, oh-my-posh appears to only support 4-character icon codes. I'd like to use 5-character icon codes too. 

Specifically, I was looking for replacement icons for some battery icons - \uf583, \uf588 and \uf57d are all discontinued (only work with one of the CasKaydia fonts). I found \uf0084 \uf0089 and \uf007e resp. on Nerd Fonts cheat sheet, but oh-my-posh ignores the last character.

**Comment by daocang** [comment]
Copy UTF-16 Codes \udb80\udc89

**Comment by JanDeDobbeleer** [comment]
> Copy UTF-16 Codes \udb80\udc89

@atkinsroy this is the correct answer. It's a JSON/TOMO/YAML limitation, not oh-my-posh.

**Comment by atkinsroy** [comment]
Thanks. I didn't know this.

**Comment by JanDeDobbeleer** [comment]
@atkinsroy we all learn something every day. If we're fortunate.
