### ISSUE TITLE
oh-my-posh does not work under bash 4 any more

### ISSUE THREAD

**Issue by ProgramFan** [JanDeDobbeleer/oh-my-posh#5685]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

As the title said. Running oh-my-posh under bash 4 will result in the following error:
```
bash: ${prompt@P}: bad substitution
```

It turns out that this `@P` grammar is introduced in bash 5.0, which causes the above error. This may be addressed by using `$(printf '%q' "$var")` instead.

### Theme

I created my own theme, but I don't think the theme is relavant.

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
Don't need this since the bug is just clear in the code.
```

**Comment by ProgramFan** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/blob/a7d73be1e7d4470b2bccf1da0063a7d75c21f483/src/shell/scripts/omp.bash#L90

and 

https://github.com/JanDeDobbeleer/oh-my-posh/blob/a7d73be1e7d4470b2bccf1da0063a7d75c21f483/src/shell/scripts/omp.bash#L102

**Comment by ProgramFan** [comment]
Sorry. This is more difficult than I initially thought. The `@P` does prompt substitute, which can not be done by `printf %q "$var"`. I am trying to do this on my fork.

**Comment by ProgramFan** [comment]
Is is possible to just make the string a valid PROMPT_COMMAND and let the final shell evaluate it?

**Comment by lewis-yeung** [comment]
@ProgramFan

> It turns out that this `@P` grammar is introduced in bash 5.0, which causes the above error.

It was introduced in Bash v4.4, exactly.

> Is is possible to just make the string a valid PROMPT_COMMAND and let the final shell evaluate it?

No, the trick of using `@P` prevents any unexpected expansions in the original prompt string, and there is not another way to do it.

**Comment by JanDeDobbeleer** [comment]
@ProgramFan I understand this can be annoying, however this will not be reverted. Bash 4.4 is 8 years old, using this is not recommended at all.

**Comment by ProgramFan** [comment]
I think it's fine. I encounter this problem when I use distrobox for a centos-7 development container on a Fedora 40 host. I can manually upgrade the bash inside the container.

**Comment by JanDeDobbeleer** [comment]
@ProgramFan CentOS 7 has also reached EOL in June so I'm also rather confident in my deprecation statement 😅
