### ISSUE TITLE
echo $VIRTUAL_ENV

### ISSUE THREAD

**Issue by kairin** [JanDeDobbeleer/oh-my-posh#5689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

currently without oh-my-posh, we can easily determine that i am on the venv virtual environment by typing the following.

and the (venv) virtual environment is displayed in front of the logged in user.

is this also available once oh-my-posh is installed? is there a way to easily see which virtual environment i am currently in without having to always keep typing the command "echo $VIRTUAL_ENV"?

 
```

ks@4080SUPER:~$ echo $VIRTUAL_ENV

ks@4080SUPER:~$ source venv/bin/activate
(venv) ks@4080SUPER:~$ echo $VIRTUAL_ENV
/home/ks/venv
(venv) ks@4080SUPER:~$

```

![image](https://github.com/user-attachments/assets/15e8785e-81da-4176-beda-32fc45c018b7)

**Comment by JanDeDobbeleer** [comment]
@kairin yes, by adding the Python segment and disable the built-in Python prompt hijacking. This is all available and customizable.
