### ISSUE TITLE
Fatal error starting shell in Visual Studio Code

### ISSUE THREAD

**Issue by bhat-ganesh** [JanDeDobbeleer/oh-my-posh#5690]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I have started getting this error in `
Visual Studio Code (Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40)
` terminal.

I have updated oh-my-posh to latest available:
```
% oh-my-posh --version            
23.15.1
Error: unknown command "fatal" for "oh-my-posh"                                                                                      
Run 'oh-my-posh --help' for usage.
(eval):4: no matches found: [running]:
(eval):7: no matches found: github.com/jandedobbeleer/oh-my-posh/src/config.(*Segment).SetEnabled.func1
```

My other terminal app `Tabby (Version 1.0.211 (1.0.211))` is rendering it fine.

### Theme

[multiverse-neon.omp.json](https://github.com/user-attachments/files/17179853/multiverse-neon.omp.json)

### What OS are you seeing the problem on?

macOS

### Which shell are you using?

zsh

### Log output

```Shell
% oh-my-posh debug <shell> --plain
zsh: no such file or directory: shell
Error: unknown command "fatal" for "oh-my-posh"                                                                                      
Run 'oh-my-posh --help' for usage.
(eval):4: no matches found: [running]:
(eval):7: no matches found: github.com/jandedobbeleer/oh-my-posh/src/config.(*Segment).SetEnabled.func1
```

**Comment by bhat-ganesh** [comment]
The issue was with the `Terraform` segment. My folder was still not initialized with `terraform init`. After init-ing it, the terminal rendered fine. Closing this.

**Comment by JanDeDobbeleer** [comment]
@bhat-ganesh something else is influencing this negatively as we don't have the --fatal parameter anywhere in our shell scripts. If Windows Terminal doesn't show that issue, that vscode's shell integrations could be the cause of this. I would try disabling that first and see if the issue persists.

**Comment by JanDeDobbeleer** [comment]
@bhat-ganesh OK, but then how does that influence oh-my-posh?

**Comment by bhat-ganesh** [comment]
I'm not sure, I have the `Terraform` segment enabled in my theme file, perhaps the `{{ .Version }}` is tripping it up 🤔 

```
        {
          "foreground": "#ffffff",
          "background": "#4040B2",
          "style": "diamond",
          "leading_diamond": "\ue0b6",
          "trailing_diamond": "\ue0b4",
          "properties": {
            "fetch_version": true
          },
          "template": "🛠️ {{ .Version }}",
          "type": "terraform"
        },
```
