### ISSUE TITLE
Emoji-based file and directory icons

### ISSUE THREAD

**Issue by GitClickOk** [JanDeDobbeleer/oh-my-posh#5698]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

[🎨 Emoji-based file and directory icons](https://github.com/yellow-footed-honeyguide/facad) and other features from facade:
📁 Sorted output with directories first
🔗 Supports symlinks and executable files
🧩 Compact grid display
📏 Customizable column width
🌐 Unicode-aware formatting

I think we have some, and others are not needed, but I think these icons could be cool!

**Comment by JanDeDobbeleer** [comment]
@GitClickOk thanks for the suggestion. As oh-my-posh' purpose is and always will be generating the prompt, I won't be adding features outside of that scope. You can use the linked tool in combination with oh-my-posh. Thanks for understanding.
