### ISSUE TITLE
Extra space in some console when using surrogate pair

### ISSUE THREAD

**Issue by sharky98** [JanDeDobbeleer/oh-my-posh#5706]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I use a surrogate pair (such as `\udb80\udced` for the `nf-md-calendar` icon), there is sometime (see note) an extra space before the trailing diamond and after the content of the segment that does not get styled.

Note: It depends of the combination of shell (pwsh or bash via SSH) and program (VSCode, Windows Terminal, [Tabby](https://github.com/Eugeny/tabby))

![image](https://github.com/user-attachments/assets/310b44ff-17ec-492b-8a5d-14de6027852b)

### Theme

I am using a custom theme derived from night-owl. The relevant segment for the above screenshot is this.

```json
{
  "blocks": [
      "segments": [
        {
          "background": "#234d70",
          "foreground": "#d6deeb",
          "leading_diamond": "<transparent,background>\ue0b0</>",
          "properties": {
            "time_format": "2006-01-02"
          },
          "style": "diamond",
          "template": " \udb80\udced {{ .CurrentDate | date .Format }} ",
          "trailing_diamond": "<background,transparent>\ue0b0</>",
          "type": "time"
        },
    ]
  ]
}
```

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash, powershell, other (please specify)

### Log output

- Windows Terminal
  - ✅ pwsh.exe: [omp.pwsh.terminal.log](https://github.com/user-attachments/files/17230105/omp.pwsh.terminal.log)
  - ✅ bash through SSH: [omp.bash.terminal.log](https://github.com/user-attachments/files/17230114/omp.bash.terminal.log)
- Tabby
  - ❌ pwsh.exe: [omp.pwsh.tabby.log](https://github.com/user-attachments/files/17230141/omp.pwsh.tabby.log)
![image](https://github.com/user-attachments/assets/78f234e4-ab70-4035-b29a-3bba90f1c949)
  - ✅ bash through SSH: [omp.bash.tabby.log](https://github.com/user-attachments/files/17230163/omp.bash.tabby.log)
![image](https://github.com/user-attachments/assets/70ea7485-0ffe-476b-8d7f-154aa1345020)
- VS Code
  - ❌ pwsh.exe: [omp.pwsh.vscode.log](https://github.com/user-attachments/files/17230176/omp.pwsh.vscode.log)
![image](https://github.com/user-attachments/assets/9e1d1dc7-d763-4248-8149-6ef7da39b498)
  - ❌ bash through SSH (in pwsh.exe): [omp.bash.vscode.log](https://github.com/user-attachments/files/17230215/omp.bash.vscode.log)
![image](https://github.com/user-attachments/assets/35fcae2e-b968-428f-bc48-a34d0797ff58)
- Console Host:
  - ✅ pwsh.exe: [omp.pwsh.conhost.log](https://github.com/user-attachments/files/17230226/omp.pwsh.conhost.log)
![image](https://github.com/user-attachments/assets/737ac51c-12f0-475e-ac54-e69fce1ee6ac)

**Comment by JanDeDobbeleer** [comment]
@sharky98 unfortunately, this is a terminal bug and not an oh-my-posh one.

**Comment by sharky98** [comment]
> @sharky98 unfortunately, this is a terminal bug and not an oh-my-posh one.

This is what I though, but since in Tabby the behaviour was different between pwsh and bash, I was thinking it may be due to oh-my-posh.

Thanks! 🙂
