### ISSUE TITLE
Slow on corporate network

### ISSUE THREAD

**Issue by dominikjeske** [JanDeDobbeleer/oh-my-posh#571]
On my personal computer every version of oh-my-posh is working good but I have issues on corporate network. Version v2 is slightly slow but 3 is very slow. When I invoke Get-PoshThemes on personal computer it takes 2-3 second but on company computer it takes one minute. I know that problem is probably on my company infrastructure but I have a question to help me investigate problem - when some git command is invoked is there any disk/network call other than call to git commands?

**Comment by lnu** [comment]
do you try get-poshthemes from a git folder?
In the background git.exe is called to retrieve informations.

**Comment by JanDeDobbeleer** [comment]
@dominikjeske there's no other calls being done no. You can make use of `Write-PoshDebug` to display where it spends it time.

**Comment by dominikjeske** [comment]
Ok thank for quick info - I will close this because it is not your concern :)

**Comment by dominikjeske** [comment]
I don't know why but because of my company polices I can see only part of commands from oh-my-posh - Write-PoshDebug is one of excluded. Is there something special with this command? I can see that this command is not visible in any manifest in package but only in binary file.

**Comment by JanDeDobbeleer** [comment]
It gets sourced by the init. Setting the prompt will also give that one as a global function.
