### ISSUE TITLE
Macos Accent

### ISSUE THREAD

**Issue by AndreM222** [JanDeDobbeleer/oh-my-posh#5711]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

Hi,

First of all, great work. During my time on windows your project helped pushed my excitement to open my terminal on windows.

Second since currently I changed to MacOS for some reasons but I want to keep it easy to be crossplatform. I wanted to ask if you guys could add the accent color to also work for MacOS.

Even if its not done still great job.

**Comment by JanDeDobbeleer** [comment]
@AndreM222 I have a working implementation, it only needs to be cached as the call takes 80ms. So it will only fetch this on `init`, changing it while in a session requires a new session.

<img width="976" alt="image" src="https://github.com/user-attachments/assets/ab8fd432-6ae4-4cd2-a665-cb70d4dddd64">

**Comment by JanDeDobbeleer** [comment]
@AndreM222 currently struggling to get the build to work, cgo configuration always annoys me 😭

**Comment by AndreM222** [comment]
Lets goooooooooo!!!!!!!!!
