### ISSUE TITLE
Flutter and Dart project segments

### ISSUE THREAD

**Issue by zs-dima** [JanDeDobbeleer/oh-my-posh#5717]
It could be nice to add Flutter and Dart project segments:
pubspec.yaml file in a project root:
https://docs.flutter.dev/tools/pubspec

oh-my-posh segment:
https://ohmyposh.dev/docs/segments/system/project

**Comment by babieiev** [comment]
It looks like @JanDeDobbeleer is working on other things right now, so I could implement this feature and prepare a pull request if no one minds.

**Comment by JanDeDobbeleer** [comment]
@oleksbabieiev I don't mind, just start from the beta branch and not main.

**Comment by babieiev** [comment]
If everyone is happy, I think we can close this issue now. For some reason, GitHub didn't automatically associate it with my pull request 🫤

**Comment by JanDeDobbeleer** [comment]
Solved in #5686, you can download the build there. Actual release pending for the next week(s).
