### ISSUE TITLE
Powershell module permissions issue on linux

### ISSUE THREAD

**Issue by RobCannon** [JanDeDobbeleer/oh-my-posh#573]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X I looked for duplicate issues before submitting this one

### Description

When importing the powershell module
/usr/bin/chmod: changing permissions of ‘/usr/local/share/powershell/Modules/oh-my-posh/3.118.0/bin/posh-linux-amd64’: Operation not permitted

### Environment

- Oh my Posh version: 3.118.0
- Theme: N/A
- Operating System: linux
- Shell: Powershell
- Terminal: Any

### Steps to Reproduce

1. Run this powershell as sudo to install module for all users: Install-Module oh-my-posh -Scope AllUsers; Import-Module oh-my-posh
2. Start powershell in normal process: Import-Module oh-my-posh

**Expected behavior:** There should be no error when importing the module

**Actual behavior:** The following error is returned:
/usr/bin/chmod: changing permissions of ‘/usr/local/share/powershell/Modules/oh-my-posh/3.118.0/bin/posh-linux-amd64’: Operation not permitted

I originally fixed this in PR #363.  But that change was undone later.  I would have liked to have had the opportunity to fix any issues with that PR.  But since that change was undone, the error message shows up every time we start a powershell session, now.

**Comment by JanDeDobbeleer** [comment]
@RobCannon that change was undone as it was super flaky cross platform/unix distro. So we couldn't rely on it. The issue is that it's `-Scope AllUsers` and we don't have access to `chmod` that file. What's the most straightforward path here?

**Comment by RobCannon** [comment]
I would like to know what errors other people were encountering so I could fix that.  I thought I had enough guard code that it would only attempt to set the permissions when it was necessary and possible to set the permissions.

**Comment by JanDeDobbeleer** [comment]
There was an issue with assuming the permission string was the same for every distro (it checks for index rather than have a certainty a character is at the position we expect it and means what it means). Pretty sure there's another way to tackle this.

**Comment by RobCannon** [comment]
Do you have an issue that was filed, so I can look at details?  PowerShell doesn't have a way to check linux file permissions that is built in, so I am parsing the output of 'ls -al'.  I thought that should be the same across all linux distributions.

Bash has some checks, like [ -x filename ], but that can't be used from PowerShell.

The only alternative I can think of is to just suppress the error message by redirecting it to null and documenting that the module must be imported under a sudo session once in order to set the file permissions if the module is installed by a sudo user.

**Comment by JanDeDobbeleer** [comment]
I don't have the error other than the report it didn't set the permissions meaning (at that time) the check failed by being too strict. Do we know the install scope of the module? Because that could be a clear indication to sudo that command.

**Comment by RobCannon** [comment]
You shouldn't attempt to sudo the command, because if the user doesn't have sudo permissions, that will cause even more problems.  Also, even if you have sudo privileges, then the module will ask for your sudo password every time you import the module (which would usually be every time you start Powershell).

I think suppressing the error might be the best option.  I can submit a PR for that, if you are ok with the plan.

**Comment by JanDeDobbeleer** [comment]
@RobCannon works for me!

**Comment by RobCannon** [comment]
Submitted PR #596
