### ISSUE TITLE
Enabling automated upgrades

### ISSUE THREAD

**Issue by jefmeijvis** [JanDeDobbeleer/oh-my-posh#5734]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current situation
At the moment, when a new version of Oh My Posh is available, users are shown the following message when the terminal is launched:
```
A new release of Oh My Posh is available: vxx.xx.x → vxx.xx.x
To upgrade, run: 'oh-my-posh upgrade'
To enable automated upgrades, set 'auto_upgrade' to 'true' in your configuration.
``` 

I believe there are two scenarios on how a user can enable automatic updates:

**The user has no custom configuration**
1. Export your current "off-the-shelf" theme via following command: `oh-my-posh config export --output ~/.mytheme.omp.json`
2. Edit the newly created custom configuration and add `{"auto_upgrade": true}`
3. Edit the $PROFILE file so it uses the new configuration file `oh-my-posh init pwsh --config "C/Users/USERNAME/.mytheme.omp.json" | Invoke-Expression`
4. Reload the current profile via  `.$PROFILE`

**The user has custom configuration**
1. Edit the custom configuration and add `{"auto_upgrade": true}`
2. Edit the $PROFILE file so it uses the new configuration file `oh-my-posh init pwsh --config "C/Users/USERNAME/.mytheme.omp.json" | Invoke-Expression`
3. Reload the current profile via  `.$PROFILE`

### Possible enhancement
Would it make more sense to introduce a command such as `oh-my-posh autoupgrade` or equivalent that offers a uniform user experience when enabling auto upgrades? 
Some possible issues with this:
- What if the user didn't have a custom configuration yet, should it be created automatically based upon the current theme? 
- Could the oh-my-posh upgrade configuration be handled separately from the theming configuration, e.g. in a different file?

Would love to see if this could be viable a UX improvement, however I might have overlooked a few things here due to my limited experience with the custom configuration file.

**Comment by JanDeDobbeleer** [comment]
@jefmeijvis this can definitely work. It's easy to use the machine cache to set this in and enable using `oh-my-posh enable autoupgrade`

**Comment by darkred** [comment]
@JanDeDobbeleer Could `oh-my-posh enable autoupgrade` be included in the [Upgrade](https://ohmyposh.dev/docs/installation/upgrade#automatic) documentation page for reference?

**Comment by JanDeDobbeleer** [comment]
@darkred yes, coming as part of the next major
