### ISSUE TITLE
Access Segments rendered output in different locations

### ISSUE THREAD

**Issue by nue-melexis** [JanDeDobbeleer/oh-my-posh#5750]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

I understand that there are [cross references](https://ohmyposh.dev/docs/configuration/templates#cross-segment-template-properties) to  Template properties.
Is there a way to get the whole rendered data of a segment?
I want in my transient prompt to show some segments of my prompt (previous exit code and execution time).  So I have 2 lines transient prompt, first adding info about previous command, second adding the new commandline.
It would be nice if I can just grab a segments rendered output instead of having to reassemble it with the cross referencing/global properties.

Simple example:
![image](https://github.com/user-attachments/assets/f7c67e65-3e71-431b-8c83-3eaf7281517c)

Would make things easier if I could access the old segments output.

**Comment by JanDeDobbeleer** [comment]
@nue-melexis I'll see if I can add that for the next major, we have the data, it's just not exposed right now.

**Comment by JanDeDobbeleer** [comment]
Solved in #5686, you can download the build there. Actual release pending for the next week(s). You can now use `.Segments.Git.Text`.

**Comment by nue-melexis** [comment]
@JanDeDobbeleer the text is exposed very well. However formatting (colors) are stripped. Is it possible to get? If not fine, still better than before 👍

**Comment by JanDeDobbeleer** [comment]
Ah. That shouldn't be stripped though. I'll check that.

**Comment by JanDeDobbeleer** [comment]
@nue-melexis I don't have stripped colors, can you show a screenshot of what you mean?

**Comment by nue-melexis** [comment]
Hi, sorry for the late reply.
 Currently it looks like this:
![image](https://github.com/user-attachments/assets/76a33b43-54fe-4b2a-8362-5453dfb4a634)
 config: 
```
transient_prompt:
  template: "{{ .Segments.Time.Text }}{{ .Segments.Status.Text }}{{ .Segments.Executiontime.Text }}{{ .Segments.Path.Text }}\n"```

**Comment by nue-melexis** [comment]
verified with 24.0.9, still an issue

**Comment by JanDeDobbeleer** [comment]
@nue-melexis that's normal, you can't reference the entire segment color, only the text. That's not how transient or this functionality works.

**Comment by nue-melexis** [comment]
Thanks for clearifying. Just adding some simple colors then. But Text already simplifies the prompt
