### ISSUE TITLE
Change color of os section based on used linux distro

### ISSUE THREAD

**Issue by tzabbi** [JanDeDobbeleer/oh-my-posh#5754]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

I love the function that oh-my-posh detects the linux distro and displays the appropiate icon. An enhancement for this would be the that the color will be changed to the main color of the linux distro. e.g. Fedora blue, Linux mint green, ....

**Comment by JanDeDobbeleer** [comment]
@tzabbi this is already possible using the [color template](https://ohmyposh.dev/docs/configuration/colors#color-templates) functionality:

```json
{
  "foreground_templates": [
    "{{if eq \"macos\" .OS}}#FFA400{{end}}"
  ]
}
```
Or `palettes` if you want to only define this logic once:

```json
{
  "palettes": {
    "template": "{{ .OS }}",
    "list": {
      "macos": {
        "accent": "#262B44"      },
      "mint": {
        "accent": "#262B44"
      }
    }
  }
}
```
