### ISSUE TITLE
Oh-My-Posh on PS5.1 and with NerdFonts installed - Documentation does not show how to configure.

### ISSUE THREAD

**Issue by francisco-lafe** [JanDeDobbeleer/oh-my-posh#5755]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

This could change in the documentation! 
https://ohmyposh.dev/docs/installation/fonts

I see that this is oriented to be used on Windows Terminal or VIsual Studio (and Code). 

Are there any specific instructions for PS5.1? The default one on Win10

**Comment by JanDeDobbeleer** [comment]
This is the same guide... Unless if you refer to the PowerShell terminal which is ancient tech and should not be used, you can use 5.1 inside Windows Terminal.

**Comment by francisco-lafe** [comment]
Yes, I was referring to the PowerShell terminal that ships with Windows 10. 

Understandable, is not supported. 
Thansk.

**Comment by JanDeDobbeleer** [comment]
@francisco-lafe it "works", but it's heavily outdated so not adviced.

**Comment by francisco-lafe** [comment]
Yeah, I was just having this issue of the icons not showing, but I think it was because the nerdfonts were updated and my theme is old, so the unicodes changed. 
![image](https://github.com/user-attachments/assets/25c19017-30c4-4b53-8a27-16fa2227cc09)
I recall that some "automated" method existed to replace all old characters with new ones but I couldn't find it, so no biggie. It's not broken, it's just referencing the wrong icon

**Comment by JanDeDobbeleer** [comment]
You can use `oh-my-posh config migrate glyphs --write` for this (hasn't been validated in a while).

**Comment by francisco-lafe** [comment]
That did the trick @JanDeDobbeleer ! 
Thanks
![image](https://github.com/user-attachments/assets/8d560d64-b152-4fa6-94b1-aa0804906ae4)
