### ISSUE TITLE
[fish] Please do not fire `accept-autosuggestion` if transient prompt is not enabled

### ISSUE THREAD

**Issue by kkebo** [JanDeDobbeleer/oh-my-posh#5760]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

[`accept-autosuggestion`](https://github.com/JanDeDobbeleer/oh-my-posh/blob/41b9c8f927d6965279c081e0d25bd5764dff53ac/src/shell/scripts/omp.fish#L190) is really annoying for me because I'm not using transient prompt.

Before #5070 was merged, oh-my-posh fired `accept-autosuggestion` only if `test "::TRANSIENT::" = "true"` was true.

So is it possible to revert back to the previous behavior regarding `accept-autosuggestion`?

**Comment by kkebo** [comment]
Here is my idea, but I don't know whether this breaks other features.

```diff
diff --git a/src/shell/scripts/omp.fish b/src/shell/scripts/omp.fish
index 95637657..1bd8ec7e 100644
--- a/src/shell/scripts/omp.fish
+++ b/src/shell/scripts/omp.fish
@@ -186,7 +186,7 @@ end
 # transient prompt
 
 function _omp_enter_key_handler
-    if commandline --paging-mode
+    if test "::TRANSIENT::" = "true" && commandline --paging-mode
         commandline --function accept-autosuggestion
         return
     end
```

**Comment by JanDeDobbeleer** [comment]
@kkebo `test "::TRANSIENT::"` this syntax is no longer supported. We would need to adjust it to `test "$_omp_transient" = 1`.

@lewis-yeung any pointers on the change requested above?

**Comment by lewis-yeung** [comment]
@JanDeDobbeleer @kkebo We should change `commandline --function accept-autosuggestion` to `commandline --function execute` so that everything works fine. I'll make a PR.
