### ISSUE TITLE
Export-PoshTheme converts characters to unicode

### ISSUE THREAD

**Issue by ghost** [JanDeDobbeleer/oh-my-posh#581]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: 3.120.0
- Theme: ys
- Operating System: Win10
- Shell: pwsh
- Terminal: Windows Terminal

### Steps to Reproduce

1.  `Export-PoshTheme -FilePath $ENV:USERPROFILE\OneDrive\.mytheme.omp.json -Format json`
2. Open custom and original theme side by side:

![image](https://user-images.githubusercontent.com/41576511/112652087-effa2300-8e44-11eb-8ae9-2c3b6db53289.png)

Possibly related to my previous issue #220?
The old method allowed the user to specify encoding explicitly with Out-File, not sure this is available with Export-PoshTheme

**Comment by JanDeDobbeleer** [comment]
I'll export the functionality for that again. 👍🏻

**Comment by JanDeDobbeleer** [comment]
@otaconjh actually, [this](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/init/omp.ps1#L87) should in theory export everything a UTF-8. So I have no idea why it doesn't. What does `[console]::OutputEncoding` say for you?

**Comment by ghost** [comment]
I get the following:
```
Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 65001
```

**Comment by JanDeDobbeleer** [comment]
~~Ok, I can reproduce this. But only on Windows 🤦🏻~~ Found it! The JSON exporter does this for some reason so it's not encoding related. If you select yaml for example it doesn't happen. I'll check.
