### ISSUE TITLE
'unknown command "pwsh" for "oh-my-posh"' after upgrading to v24

### ISSUE THREAD

**Issue by 13xforever** [JanDeDobbeleer/oh-my-posh#5823]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After upgrading to the new version 24, omp fails to initialize on existing setup with an error `unknown command "pwsh" for "oh-my-posh"`.

The root cause seems to be a breaking change to the CLI argument parsing.
Before:
```
oh-my-posh --init --shell pwsh --config $PROMPT_CONFIG | Invoke-Expression
```
now:
```
oh-my-posh init pwsh --config $PROMPT_CONFIG | Invoke-Expression
```

It would be great to not introduce meaningless breaking changes without any prior warning in the future.

### Theme

Custom theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
I don't think it's relevant here.
```

**Comment by linyanm** [comment]
the same issue occurs to me

```
Error: unknown command "bash" for "oh-my-posh"
```

**Comment by mairaw** [comment]
Same here. Thanks for pointing out how to fix it @13xforever.

**Comment by fp024** [comment]
I have the same issue.

It was fine until v23.20.3, but the issue occurs from v24.0.0.

@13xforever : Thank you. I followed your guide and it worked.

**Comment by JanDeDobbeleer** [comment]
@13xforever that change in the CLI was introduced 2 years ago. It only now got deprecated. I'll add it to the changelog, but it's not meaningless.

**Comment by 13xforever** [comment]
My config is stamped for June 22, 2023, built from scratch following the official documentation, so at the very least it wasn't two years. And there was never any kind of warning that currently used commands are being deprecated.

There should be a clear warning before the changes are implemented, as well as a clear, specific error after.
In both cases there should be some user guidance provided on how to fix it.

**Comment by JanDeDobbeleer** [comment]
@13xforever [25th of March 2022](https://github.com/JanDeDobbeleer/oh-my-posh/commit/112043f8050e1a900f73158515a89e455141912d#diff-1a510e0a97ae134f1f39cae058e6264c6b4a42fb2c0441baf221ff4b6cc6aea0R72), so I'm not sure where you got that information from. Any way, looking at the amount of people stumbling upon this, I didn't expect anyone to still use this after what appears to be 2.5 years. I'm reintroducing backwards compatibility.

**Comment by shanselman** [comment]
Ya I hit this today. I had zero idea it changed and wouldn’t have known it was deprecated as there was no warning.

**Comment by JanDeDobbeleer** [comment]
@shanselman yeah, I underestimated the impact of this.

I think the official Windows Terminal documentation used this syntax for a long time after I updated the documentation on my end which could also cause confusion, same as online resources.

The issue is that I can't migrate this automatically, unlike configurations. So I guess I'm stuck with my architectural flaws of the past.
