### ISSUE TITLE
CMD prompt configuration uses out of date method

### ISSUE THREAD

**Issue by trwy7** [JanDeDobbeleer/oh-my-posh#5866]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Clink now contains built in support for oh my posh with the command `clink config prompt use oh-my-posh` and `clink set ohmyposh.theme <path>`, which will automatically configure oh-my-posh to be used as the prompt.

**Comment by JanDeDobbeleer** [comment]
Cool! I'll add that.
