### ISSUE TITLE
Allow `--version` as well

### ISSUE THREAD

**Issue by ffes** [JanDeDobbeleer/oh-my-posh#5871]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

At the moment to show the current version of oh-my-posh you need to type `oh-my-posh version`, but for some reason (probably because that works almost always with other tools) I keep typing `oh-my-posh --version`, get an error and use the right command. Therefore it would be really nice if `--version` would work as well.

Note that for `oh-my-posh help` and `oh-my-posh --help` output the same, so why not for `oh-my-posh version` and `oh-my-posh --version`.

**Comment by lewis-yeung** [comment]
@ffes The `--version` option was removed in [v24][code].

@JanDeDobbeleer The `--version` option seems to be a convention for many CLI tools. Should we restore it?

[code]: https://github.com/JanDeDobbeleer/oh-my-posh/commit/3bc476488a36d4d7e6fde8f40fad18266ec95ad4#diff-0ec2c2a912a109ca143ee5414140456464886cf4c0e6ee714f234bbac669f219L52

**Comment by JanDeDobbeleer** [comment]
@lewis-yeung I was about to. It depends on the CLI tool. I don't agree with `--version` myself as from an interface point of view, you request something. It's not a parameter. That said, I don't care enough to stop us from adding it again 🙃
