### ISSUE TITLE
Outdated command for autoupgrade suggestion in notice

### ISSUE THREAD

**Issue by eelispeltola** [JanDeDobbeleer/oh-my-posh#5885]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Very small change: [line 42 in notice.go](https://github.com/JanDeDobbeleer/oh-my-posh/blob/e005f898fead6bf0cc7ce3e113eb39b1b823a774/src/upgrade/notice.go#L42) should read `To enable automated upgrades, run: 'oh-my-posh enable upgrade'.` to be valid.

**Comment by JanDeDobbeleer** [comment]
@eelispeltola if you create a PR with just that change (mind the commit message guidelines), you get a cool badge for this aa well!

**Comment by eelispeltola** [comment]
Almost did it before but got cold feet since I wasn't sure if it was the doc or command that was wrong. The PR is now up!
