### ISSUE TITLE
A better way to determine if omp is running from WSL.

### ISSUE THREAD

**Issue by dingdang66686** [JanDeDobbeleer/oh-my-posh#5893]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

I tried to use omp installed in windows from WSL. By using some bash hack this can be done.
```bash
WSLENV=$WSLENV:POSH_THEME
eval "`oh-my-posh.exe init bash --config '~/Local/jtracey93.omp.json'|sed '/^_omp_executable/c\_omp_executable=oh-my-posh.exe'`"
```
However, omp still thinks this is a windows shell, so the OS icon and path indicator are not working properly.
![image](https://github.com/user-attachments/assets/46164508-ee92-4a7f-9336-8eea6d22e8ee)

Can we use another method to determine if we are running in WSL?

**Comment by JanDeDobbeleer** [comment]
@dingdang66686 don't use the windows executable in WSL. It's a Windows exe after all and you're in a Linux filesystem. The Linux executable can correctly identify WSL, as it understands the filesystem.
