### ISSUE TITLE
Update to v24.6.2 is broken

### ISSUE THREAD

**Issue by somera** [JanDeDobbeleer/oh-my-posh#5898]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I try to update to v24.6.2 I get this

```
$ scoop update *
WARN  error: The remote server returned an error: (404) Not Found.
Latest versions for all apps are installed! For more information try 'scoop status'
```

and than

```
$ scoop status
Scoop is up to date.
WARN  error: The remote server returned an error: (404) Not Found.

Name       Installed Version Latest Version Missing Dependencies Info
----       ----------------- -------------- -------------------- ----
oh-my-posh 24.5.2                                                Manifest removed
```

And https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json returns
```
{
"error": "Not Found"
} 
```

### Theme

quick-term.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
See above.
```

**Comment by JanDeDobbeleer** [comment]
@somera yes, I'm updating the signing method and currently the installers aren't working due to this. Will debug this evening. In the meantime, use `oh-my-posh upgrade `to update oh-my-posh.

**Comment by JanDeDobbeleer** [comment]
Fixed

**Comment by somera** [comment]
Works. Thx.
