### ISSUE TITLE
Python not showing the correct version because it is set in the cache

### ISSUE THREAD

**Issue by yjcb22** [JanDeDobbeleer/oh-my-posh#5899]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

This is the same issue reported in #5892 

@JanDeDobbeleer This is to answer your rhetorical question here: 

![image](https://github.com/user-attachments/assets/9f943e94-df78-491e-b16e-ce4da87c87c0)

As you can see this is breaking multiple languages. In my case, I use python with different virtualenvs and the version was not updating because it was stored in the omp.cache file and then it was always using it. So, I fixed it by adding the cache_duration = none and removing the cache files with oh-my-posh cache clear. Now, when I switch between folders with different venvs using different python version it is updating correctly. I am using Kushal.omp.json.

Please note that this was a recent change since I have an Archlinux box with an older version of omp (oh-my-posh) and it was working with no issues but I installed a new Ubuntu with the latest omp and this is when I found the bug. 

You can close this since I fixed it with your instructions! Thanks!

### Theme

Kushal.omp.json

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
No need this is already fixed. By the way, thanks for the debug mode. It was the one that pointed me in the right direction with the cache and then I found your comment in the github issue. Thanks :)
```

**Comment by JanDeDobbeleer** [comment]
@yjcb22 I'll adjust this
