### ISSUE TITLE
Themes are not proper in Ubuntu bash

### ISSUE THREAD

**Issue by beingamarnath** [JanDeDobbeleer/oh-my-posh#590]
### Prerequisites

- [ x] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

Themes do not work as expected in Ubuntu Bash

### Environment

- Oh my Posh version: latest
- Theme: Powerline (but the issue is with all themes)
- Operating System: Ubuntu
- Shell: Bash
- Terminal: Windows Terminal

### Steps to Reproduce

1. Installed the packages as per Installation page in Ubuntu(WSL2)
2. eval themes

**Expected behavior:** [What you expected to happen]
(Image is from powershell)
![image](https://user-images.githubusercontent.com/21178321/112727265-cd9cfe00-8f47-11eb-9c41-fc7c3e26b191.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/21178321/112727257-c1b13c00-8f47-11eb-9e8d-e42008d9e6b6.png)

**Comment by beingamarnath** [comment]
My bad. Fonts were not enabled and this was causing the issue. 

Anyhow thanks for the great software.

**Comment by YoushaaMurhij** [comment]
How to enable the fonts?

**Comment by JanDeDobbeleer** [comment]
@YoushaaMurhij depends on the terminal. Not something oh-my-posh can do for you.
