### ISSUE TITLE
The fonts and icons in Windows Terminal are not displaying correctly.

### ISSUE THREAD

**Issue by grey6966** [JanDeDobbeleer/oh-my-posh#5919]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

In the Windows Terminal, font icons are displayed incorrectly, but they appear normal in other terminal tools.

![image](https://github.com/user-attachments/assets/821899bd-4a21-463e-a9f9-d143b226c081)

### Theme

blueish

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
nothing
```

**Comment by JanDeDobbeleer** [comment]
@grey6966 this isn't an issue with oh-my-posh but rather the shell, or terminal configuration. There's no difference in output when it comes to oh-my-posh, and we can't influence the way the terminal prints the icons.
