### ISSUE TITLE
install.ps1 script fails with error "Unsupported 16-Bit Application".

### ISSUE THREAD

**Issue by nbdinara** [JanDeDobbeleer/oh-my-posh#5937]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Manual installation of oh-my-posh fails with error "Unsupported 16-bit Application" (see screenshot below for the full error message)
<img width="316" alt="image" src="https://github.com/user-attachments/assets/0344d21f-d821-41b0-b6e7-9757cddc8b9a">

Command that has been used: 
`Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://ohmyposh.dev/install.ps1'))`

### Theme

Not applicable

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
Not applicable since error happens during oh-my-posh installation
```

**Comment by SoundersFan** [comment]
I'm getting the same. The issue is that the script is now downloading an MSI, not an EXE. But it downloads it to a file with a .exe extension and then tries to run it like an exe. But it's an MSI. You want to run `msiexec -i install-x64.msi`

**Comment by SoundersFan** [comment]
note: here's the PR that cause the issue: https://github.com/JanDeDobbeleer/oh-my-posh/pull/5929/files. In the install.ps1 change.

**Comment by JanDeDobbeleer** [comment]
@SoundersFan @nbdinara fixing as we speak. My bad, didn't catch that part in the script (and also didn't validate it).

**Comment by SoundersFan** [comment]
Thanks!

**Comment by nbdinara** [comment]
@JanDeDobbeleer thank you! just tested, it works now!
@SoundersFan thank you for workaround!
