### ISSUE TITLE
Unable to upgrade Oh My Posh from 24.8.0 to 24.9.0 via scoop update

### ISSUE THREAD

**Issue by captainkirkoff** [JanDeDobbeleer/oh-my-posh#5943]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Trying to update via scoop update oh-my-posh, this is what I get:
```
oh-my-posh: 24.8.0 -> 24.9.0
Updating one outdated app:
Updating 'oh-my-posh' (24.8.0 -> 24.9.0)
Downloading new version
install-x64.msi (5,7 MB) [==========================================================================================================================================================] 100%
Checking hash of install-x64.msi ... ok.
Uninstalling 'oh-my-posh' (24.8.0)
Installing 'oh-my-posh' (24.9.0) [64bit] from 'https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json'
Loading install-x64.msi from cache
Extracting install-x64.msi ... done.
Installer C:\Users\piero\scoop\apps\oh-my-posh\24.9.0\install-x64.msi is missing.
```
The msi gets undeed unpacked inside $USER\scoop\apps\oh-my-posh\24.9.0\  and then deleted. Upgrading hangs here.

### Theme

N/A - This is related to scoop upgrades

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

cmd

### Log output

```Shell
It shouldn't be relevant.
```

**Comment by JanDeDobbeleer** [comment]
@captainkirkoff this seems like a scoop limitation, I'll check.

**Comment by yuniet87** [comment]
Same here...

**Comment by JanDeDobbeleer** [comment]
@captainkirkoff @yuniet87 I did some investigation and it should in theory "just work" ([source](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests#deprecated-properties)):

> The new method is to treat .msi files just like a .zip and extract the files from it without running the full install. You can use the new method simply by not including this msi property in your manifest.

So, in theory, our installer manifest should work as it indeed tries to unpack, but fails to do so. That said, _**I wholeheartedly disagree with that approach**_ as the point of the installer is to set up the environment correctly which doesn't work when they only unpack and make oh-my-posh.exe available in your `PATH`.

This is an issue with scoop and given the limitations, I will remove the option for Oh My Posh. It's not acceptable from a maintainer point of view.

**Comment by treysis** [comment]
.exe also has some benefits, can we have it back?
https://github.com/JanDeDobbeleer/oh-my-posh/issues/5995
