### ISSUE TITLE
oh-my-posh not showing python env when using pixi

### ISSUE THREAD

**Issue by laguill** [JanDeDobbeleer/oh-my-posh#5955]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hello,
I just installed pixi as my python packages manager.

```python
# create project folder
mkdir ~/Documents/Project
cd !$
pixi init --format pyproject
```
Once the project is initialised to activate the environment
I run `pixi shell` 

The shell hangs out and print nothing
I can only exit it

### Theme

here is my theme [config](https://github.com/laguill/powershell/blob/main/.mytheme.omp.json) 

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
.
```

**Comment by JanDeDobbeleer** [comment]
@laguill disable auto upgrade/upgrade notice. That one's "responsible" for making the shell hang. But it's pixi that doesn't correctly spawn a shell process.

**Comment by laguill** [comment]
@JanDeDobbeleer sorry 
I did `oh-my-posh disable notice` but the issue is still there

What do you mean by 
> auto upgrade/upgrade notice

**Comment by laguill** [comment]
ok I changed this part part in my theme
```
  "auto_upgrade": false,
  "disable_notice": true
```

**Comment by JanDeDobbeleer** [comment]
That should do it.
