### ISSUE TITLE
Atomic Theme Enhancement for a Better Terminal Experience

### ISSUE THREAD

**Issue by kevinShogun** [JanDeDobbeleer/oh-my-posh#5961]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

#### Overview
This repository includes an enhanced version of the **Atomic** theme for Oh My Posh. The improvements focus on optimizing the theme for Windows terminals, addressing common issues like broken lines and inconsistent spacing. Key enhancements include:

- **Fixed Line Break Issues**: Resolved the problem of broken lines in Windows terminals, ensuring smoother display and layout.
- **Improved Icon Spacing**: Increased the spacing between icons to enhance readability and visual clarity.

[click me to view gist](https://gist.github.com/kevinShogun/224470d29cdc7b5c121bd5c1a1a125f5)

### old version
![image](https://github.com/user-attachments/assets/29b24feb-d1fc-452f-bc3e-53a959be6354)

### new version
![image](https://github.com/user-attachments/assets/a8ccba9f-ef6f-442f-9751-ef47e21fb097)

**Comment by JanDeDobbeleer** [comment]
@kevinShogun feel free to create a PR For this 👍🏻
