### ISSUE TITLE
AllUser installation isn't working? (Windows, PowerShell)

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [JanDeDobbeleer/oh-my-posh#5962]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I need to have OMP in the "Program Files" folder, not under the user's appdata local. The previous installer (until 24.6?) did that per default, and while the new one appears to also support it with the `AllUsers` parameter in install.ps1, I haven't been able to get it to work.
I tried several ways, such as providing the parameter to `install.ps1`, removing the `if` in the script, and simply running `install-x64.msi` with the parameters copied from the installation script (`INSTALLATION=script ALLUSERS=1`), but it only installs in the same location, i.e. `appdata\local\programs\oh-my-posh`. Is this intentional, and how to get it to install to program files?

### Theme

not-applicable as this is an installation issue

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
not-applicable as this is an installation issue
```

**Comment by zEdS15B3GCwq** [comment]
Logfile from `install-x64.msi INSTALL=script ALLUSERS=1 /li log.txt`
[log.txt](https://github.com/user-attachments/files/17964821/log.txt)

**Comment by JanDeDobbeleer** [comment]
@zEdS15B3GCwq it's the `/quiet` parameter. It will fail quietly when you're not admin (or use sudo).

**Comment by JanDeDobbeleer** [comment]
@zEdS15B3GCwq confirmed to work when you run the script as admin. I'll remove quiet as this will effectively pop the UAC when non-admin, and only display progress when admin.

**Comment by zEdS15B3GCwq** [comment]
Sorry for not pointing it out, but I ran the above in an administrator powershell terminal all the time.

Also, I did it without the `/quiet` parameter, which I didn't include in my post above either.

One thing that comes to mind that could be relevant (or not), is that the actual login account is not member of the administrator group, only the powershell shell was opened with `run as administrator`, which therefore opens as a different user (here, Root) that is part of the admnistrator group. This causes trouble for a few things, for example, `winget` doesn't work properly without actually logging into the admin account directly. Most installers, including your previous version, run without issues, though.

Could you take a look again, please?

**Comment by zEdS15B3GCwq** [comment]
Result of running installation in powershell. The first line is supposed to show that it's an admin account. Am I invoking the installer the right way?

```
 Admin  20:45:38  C:\ ❯ [bool](([System.Security.Principal.WindowsIdentity]::GetCurrent()).groups -match "S-1-5-32-544")
True
 Admin  20:45:41  C:\ ❯ Get-Childitem (Join-Path $env:LOCALAPPDATA 'Programs')

    Directory: C:\Users\Root\AppData\Local\Programs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024.02.16    04:49                Common

 Admin  20:45:44  C:\ ❯ .\install-x64.msi INSTALLER=script ALLUSERS=1 /li log.txt
 Admin  20:45:54  C:\ ❯ Get-Childitem (Join-Path $env:LOCALAPPDATA 'Programs')

    Directory: C:\Users\Root\AppData\Local\Programs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2024.02.16    04:49                Common
d----          2024.11.30    20:45                oh-my-posh

 Admin  20:45:57  C:\ ❯
```

Same results without the /li parameter, by the way.

**Comment by JanDeDobbeleer** [comment]
That's how it works for me, yes. I ran the script as admin with that line and it works. BUT, you probably have to uninstall first, then install again. MSI doesn't allow to mix between the two modes.

**Comment by zEdS15B3GCwq** [comment]
By "it works for you", you mean that it installs into Program Files [(x86)]? As you see, it installs itself into localappdata for me.

I had removed the previous version of OMP, the one installed with the previous installer, when I noticed that this new installer was different. I have 2 environment variables, POSH_INSTALLER and POSH_THEMES_PATH that may have beeen set earlier, I'm not sure.

Or did you mean that I should uninstall the current one, since I probably installed it without ALLUSERS set? Is this version something that can be uninstalled? I don't see an OMP entry in the control panel / programs list, nor elsewhere, and there's no uninstaller in the installation folder, and running `install-x64.msi /uninstall` returns an error.

**Comment by zEdS15B3GCwq** [comment]
You were right about the uninstall being necessary. I didn't see the uninstall entry in the control panel as it only appeared for the administrator user, not the unpriviliged user I'm using. Once I switched accounts and unintalled OMP from that, `ALLUSERS=1` installation correctly installs into Program Files (x86). Thanks for the hint.

However, I found it confusing that there was no warning about the conflict between installation types. Once installed in one way (say, into localappdata), further installations that changed the ALLUSERS parameter appeared to have succeeded, when in fact the parameter was ignored. Wouldn't it be helpful to include a warning in this case? This bug report wouldn't exist if there had been any.

**Comment by JanDeDobbeleer** [comment]
@zElet I don't know if I can solve that though, from what I understood this is MSI default behavior.

**Comment by zEdS15B3GCwq** [comment]
I see, if you cannot configure that then there isn't much you can do to the installer. You could add a note to the installation instructions on `ohmyposh.dev` how to install globally, and that the installer will silently misbehave unless the user-type installation is removed first.
