### ISSUE TITLE
v24.11.2 -> The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by somera** [JanDeDobbeleer/oh-my-posh#5969]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When I try to update my oh-my-posh I get

```
 * 63d04fa48e38 oh-my-posh: Update to version 24.11.2                    main         16 hours ago
Scoop was updated successfully!
WARN  error: The remote server returned an error: (404) Not Found.
Latest versions for all apps are installed! For more information try 'scoop status'
```

### Theme

Can be ignored in this case.

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
See above.
```

**Comment by JanDeDobbeleer** [comment]
@somera we don't support scoop anymore, you have to talk to the upstream maintainer to change the installer configuration.

**Comment by somera** [comment]
I see now. Changed with v24.10.0.
