### ISSUE TITLE
Issues with the oh-my-posh command

### ISSUE THREAD

**Issue by Infinituum17** [JanDeDobbeleer/oh-my-posh#597]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When I run `oh-my-posh` command on Powershell:
>oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again

All the other commands work both ways: on Powershell and on the Powershell Profile.

I was trying to use `oh-my-posh --config sample.json --shell universal` to create a custom design.
### Environment

- Oh my Posh version: 
- Theme: Custom
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
How did you install oh-my-posh?

**Comment by Infinituum17** [comment]
Using `Install-Module oh-my-posh -Scope CurrentUser`

**Comment by JanDeDobbeleer** [comment]
@Infinituum17 in that case, you can't use that command as oh-my-posh isn't exposed. You do have access to the `Export-PoshTheme` cmdlet which has the functionality you're looking for.

**Comment by Infinituum17** [comment]
> @Infinituum17 in that case, you can't use that command as oh-my-posh isn't exposed. You do have access to the `Export-PoshTheme` cmdlet which has the functionality you're looking for.

Oh ok, thanks
