### ISSUE TITLE
Let Oh My Posh's MSI installation uninstall current version and install new version automatically

### ISSUE THREAD

**Issue by CompactProducer** [JanDeDobbeleer/oh-my-posh#5970]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

When we install Oh My Posh from WinGet or any other source, it does not replace an older version. Instead, it installs a new version instead of uninstalling an older one first. It'd be great if updating Oh My Posh by using its MSI installation uninstalls an older version and installs a newer version for a current user.

**Comment by JanDeDobbeleer** [comment]
@CompactProducer as of the next one this will happen, I had a bug in the installer which causes this not to work on current installs. Now, it seems to be a registry issue more than a duplication issue on file level.
