### ISSUE TITLE
install-x64.msi installation path

### ISSUE THREAD

**Issue by 720720** [JanDeDobbeleer/oh-my-posh#5981]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

`https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v24.11.4/install-x64.msi` installs oh-my-posh to
`C:\Program Files (x86)\oh-my-posh` instead of
`C:\Program Files\oh-my-posh`

### Theme

Default

### What OS are you seeing the problem on?

Windows 11

### Which shell are you using?

PowerShell 7

### Log output

```Shell
Version: 24.11.4
Shell: pwsh
```

**Comment by JanDeDobbeleer** [comment]
@720720 that's by design to be aligned with the previous installer.

**Comment by 720720** [comment]
64-bit applications should install to the program files folder no matter what previous installers did

**Comment by JanDeDobbeleer** [comment]
@720720 that's a very bold statement as that would leave the current users with two installations. That's why the answer is not always what one would expect. Context is king.

**Comment by CompactProducer** [comment]
Try uninstalling an older version and installing a newer version. This way, it'll only install to a current user instead of C:\Program Files (x86), which is for all users. Hopefully, next version should fix this problem.

**Comment by 720720** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/issues/5970
https://github.com/JanDeDobbeleer/oh-my-posh/commit/5ddb2d185c6980423a2821b272f8bc49cc451aba


The new installer uninstalls older versions so it would not leave currrent users with two installations.

@JanDeDobbeleer Context is king.

**Comment by JanDeDobbeleer** [comment]
@720720 I see what you did there but the argument doesn't hold as the migration path is coming from the old installer which implies the new installer will not uninstall that version as it can't identify that as an install in the same context.

I can test, but I'm pretty sure it can't correlate that correctly.

**Comment by 720720** [comment]
`winget install --exact --scope machine --id JanDeDobbeleer.OhMyPosh --custom INSTALLDIR="C:\Program Files\oh-my-posh\bin"`

@JanDeDobbeleer unfortunatley didnt work, so perhaps you could offer some installer switches or a zip package for manual installation

**Comment by JanDeDobbeleer** [comment]
@720720 I can make INSTALLDIR work though (of the --location parameter).

**Comment by 720720** [comment]
@JanDeDobbeleer a working winget --location parameter would be great.
