### ISSUE TITLE
winget install ignores `--location`, doesn't support multiple users

### ISSUE THREAD

**Issue by picorealm** [JanDeDobbeleer/oh-my-posh#5985]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Installing JanDeDobbeleer.OhMyPosh via winget, it ignores the --location directive.  
It installs to $HOME\AppData\Local\Programs\oh-my-posh\bin\ of the user who installs it via winget
If another user attempts to install it it fails with "Found an existing package already installed. Trying to upgrade the installed package..."

OhMyPosh should install in a sensible, system-wide location that can be available to all users, such as C:\Program Files, and is should honor the winget --location directive so that OhMyPosh can be installed to a custom location.
Failing that, it should allow itself to be installed by multiple users so that they can all have it available in their $HOME\AppData\Local\Programs\ directory.

### Theme

Own custom minimalist theme

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
## As Administrator (who installed it via winget)
administrator@mssv25-1 pwsh ~    oh-my-posh debug --plain
Version: 24.11.4
Shell: pwsh (7.4.6)
Prompt:
administrator@mssv25-1 pwsh ~  <U+F0AD>
Segments:
ConsoleTitle(true)                        -   0 ms
Session(true)                             -   0 ms
Path(true)                                -   0 ms
Root(true)                                -   0 ms
Run duration: 5.9827ms
Cache path: C:\Users\Administrator\AppData\Local\oh-my-posh
Config path: C:\Users\Administrator\.local\oh-my-posh.json


## As user
PS C:\Users\foo> oh-my-posh debug --plain
oh-my-posh: The term 'oh-my-posh' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by picorealm** [comment]
```ps1
mkdir C:\Lib\OhMyPosh
winget install JanDeDobbeleer.OhMyPosh --location C:\Lib\OhMyPosh
```
It fails to install in C:\Lib\OhMyPosh

**Comment by JanDeDobbeleer** [comment]
@picorealm it can be installed system wide, but that requires the `--scope machine` parameter when installing. Location clearly states it needs to be supported by the installer (which we don't).

I could look at what it takes to have that built-in the installer.

**Comment by picorealm** [comment]
Thank you!  `winget install JanDeDobbeleer.OhMyPosh --scope machine` is the answer!
