### ISSUE TITLE
get certificate expired error on ohmyposh.dev

### ISSUE THREAD

**Issue by maccampb** [JanDeDobbeleer/oh-my-posh#5986]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Firefox reports...

Did Not Connect: Potential Security Issue

Firefox detected an issue and did not continue to ohmyposh.dev. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely.

What can you do about it?

ohmyposh.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

### Theme

n/a

### What OS are you seeing the problem on?

macOS

### Log output

```Shell
see above....
```

**Comment by pl4nty** [comment]
particularly, this breaks installs from `https://ohmyposh.dev/install.sh`

**Comment by JanDeDobbeleer** [comment]
This is managed entirely by Azure, I'll check if they have an issue open about it.

**Comment by JanDeDobbeleer** [comment]
Working site URL's:

- https://www.ohmyposh.dev
- https://ohmypo.sh/
- https://www.ohmypo.sh

I'm recreating https://ohmyposh.dev as that's the only one which broke. This is managed entirely by Azure, I don't have the ability to renew the certificate myself. Hopefully recreating the custom domain also creates a new certificate.

**Comment by evilbaschdi** [comment]
Certificate working again as it seems. But now defender catches the setup file since it detects a trojan "Trojan:Script/Wacatac.B!ml" in it.
Edit: only on Windows ARM

**Comment by JanDeDobbeleer** [comment]
@evilbaschdi that's a false positive, nothing I can solve. Report it as safe and continue, the original installer had the same issue, it disappeared after a while.

**Comment by maccampb** [comment]
Thanks!!!!
