### ISSUE TITLE
My JSON file does not seem to be set

### ISSUE THREAD

**Issue by ryan11lee** [JanDeDobbeleer/oh-my-posh#599]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Set theme in JSON
```
Export-PoshTheme -FilePath ~/.oh-my-posh.omp.json
Set-PoshPrompt -Theme  ~/.oh-my-posh.omp.json
```
When I reload theme is not saved.

### Environment

- Oh my Posh version: 3.120.1
- Theme: Aliens
- Operating System: Windows
- Shell: Poweshell
- Terminal: Windows Terminal

### Steps to Reproduce

1. See description

**Expected behavior:** Save theme and load

**Actual behavior:** non-themed powershell loads

**Comment by JanDeDobbeleer** [comment]
@ryan11lee did you add the `Set-PoshPrompt` line to your `$PROFILE`? Otherwise it will indeed not be kept in starting a new shell.
