### ISSUE TITLE
Bring back .exe installer! .msi sometimes just cannot be installed 🙁

### ISSUE THREAD

**Issue by treysis** [JanDeDobbeleer/oh-my-posh#5995]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

MSI might be nice and shiny, unfortunately it makes it impossible to use on some systems:

![image](https://github.com/user-attachments/assets/4840da72-905d-47b0-a981-1aca09f92d4b)

I don't think I can convince the IT department to change this group policy.

The EXE installer doesn't have this limitation and just works, so I'm stuck on v24.8.0. Please bring it back so we can have the choice which method we want to use!

**Comment by JanDeDobbeleer** [comment]
@treysis I'm not going to maintain two installers unfortunately. Can you use `oh-my-posh upgrade`?

**Comment by treysis** [comment]
@JanDeDobbeleer no, because OMP doesn't seem to support proxy servers :( cannot connect to github.

Can't you have an automated build script for both installers? Kind of sucks that it's getting more difficult to install for many cases.

**Comment by JanDeDobbeleer** [comment]
@treysis you can switch to use the cdn. See [here](https://www.ohmyposh.dev/docs/installation/upgrade). I'm not bringing back the exe installer, the MSI allows for more insights through the store etc, and I'm not going to maintain two installers.

**Comment by treysis** [comment]
@JanDeDobbeleer cdn doesn't help. The problem appears to be that ohmyposh cannot connect through a https proxy:

![image](https://github.com/user-attachments/assets/6ce8213c-ff27-4e31-b594-c77b9f3c0461)
