### ISSUE TITLE
[Bash] incorrect/early text wrapping

### ISSUE THREAD

**Issue by jeroenev** [JanDeDobbeleer/oh-my-posh#60]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description
When using the terminal, the text seems to wrap weirdly,
Seems to wrap around early, and doesn't continue on a newline, overwriting the PS1 text

### Environment

- Oh my Posh version: 3.14.2
- Theme: Default / JanDeDobbeleer
- Operating System: Ubuntu20.04
- Shell: Bash v5.0.17
- Terminal: Tilix / Gnome Terminal

### Steps to Reproduce

1. Open Terminal
2. Start typing

**Expected behavior:** Text wraps around at the end of the window

**Actual behavior:** Text wraps around early / overwrites PS1 text

![image](https://user-images.githubusercontent.com/10954827/95763298-6263b600-0c9e-11eb-9e74-dd5c3d24c543.png)

**Comment by jeroenev** [comment]
might be bash-specific, found some old bash issues related to text-wrapping: 
https://stackoverflow.com/questions/1133031/shell-prompt-line-wrapping-issue
Not sure if they're still relevant/usefull

**Comment by JanDeDobbeleer** [comment]
I need to escape them with `\[... \]` like zsh does (but differently) if I read this correctly. Will do.

**Comment by JanDeDobbeleer** [comment]
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/2492783/95775047-e7ac9200-0cc1-11eb-817f-9c97bb9e8368.png">

Fixed

**Comment by jeroenev** [comment]
Works perfectly, thanks a lot!
