### ISSUE TITLE
Theme ys adding a pair of brackets in the end of output

### ISSUE THREAD

**Issue by NoahELE** [JanDeDobbeleer/oh-my-posh#600]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

While using theme ys, I found it adding a pair of brackets in the end of output for some commands. It doesn't happen on theme like pure or powerline etc. I wonder if it is a bug or a feature.

### Environment

- Oh my Posh version: 3.129.1
- Theme: ys
- Operating System: win10
- Shell: powershell 7
- Terminal: windows terminal

![terminal](https://user-images.githubusercontent.com/49080986/113076977-c6eddf80-9202-11eb-86a1-c4bc53e5c330.png)

**Comment by lnu** [comment]
for some commands only ?
There is this in ys:
```
      {
        "type": "prompt",
        "alignment": "left",
        "segments": [
          {
            "type": "python",
            "style": "plain",
            "foreground": "white",
            "properties": {
              "prefix": "(",
              "postfix": ")",
              "display_version": false
            }
          }
        ]
      },
```

You can try to remove this segment and check if ( ) is still added.

**Comment by NoahELE** [comment]
Yes, thanks, I see it now. 
I have .py file on desktop folder, that's why I have those brackets.
I now use a ys theme modified by me now, and the brackets are gone.
