### ISSUE TITLE
Rendering of powerlevel10k_classic broken

### ISSUE THREAD

**Issue by brainz80** [JanDeDobbeleer/oh-my-posh#601]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

powerlevel10k_classic theme renders branch name twice.

### Environment

- Oh my Posh version: 3.130.0
- Theme: powerlevel10k_classic
- Operating System: Windows 10
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal 1.6.10571.0

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/1257591/113103703-4a5dff80-9208-11eb-83a2-5e0dae361f7b.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/1257591/113103676-3f0ad400-9208-11eb-9617-ccbf72151b47.png)

**Comment by JanDeDobbeleer** [comment]
That's posh-git doing it's magic rather than oh-my-posh. What does your `$PROFILE` say?

**Comment by brainz80** [comment]
Here's what my $profile looks like:

```posh
Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1 -Force

# Import-Module AWSPowerShell
Import-Module oh-my-posh
Import-Module Terminal-Icons
Import-Module ZLocation

Set-PSReadlineKeyHandler -Key Ctrl+d -Function DeleteCharOrExit
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward

Set-Alias npm-holygrail C:\tools\miscellaneous\npm-holygrail.cmd

Set-Alias docc docker-compose
Set-Alias doc docker

Set-PoshPrompt -Theme powerlevel10k_classic
```

I uninstalled ```posh-git``` and tried removing it:
![image](https://user-images.githubusercontent.com/1257591/113255989-38945f00-92d1-11eb-9143-0797ddaf4dbc.png)

but when I reopen the terminal:
![image](https://user-images.githubusercontent.com/1257591/113256090-5b267800-92d1-11eb-85f4-158e8b1b36a9.png)

it's back. Is ```posh-git``` being used as a dependency for ```oh-my-posh```?

**Comment by brainz80** [comment]
Managed to fix my problem. Somehow I had a second ```posh-git``` version installed ```%USERPROFILE%\Documents\WindowsPowerShell\Modules``` that made everything a bit janky. Removing it did the trick.
