### ISSUE TITLE
windows cannot be updated

### ISSUE THREAD

**Issue by yuwenlong** [JanDeDobbeleer/oh-my-posh#6020]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

 winget upgrade JanDeDobbeleer.OhMyPosh -s winget                                                                                                                                                                  
找到了较新的版本，但安装技术与当前安装的版本不同。请卸载包并安装较新的版本。
![image](https://github.com/user-attachments/assets/95e05958-2832-427e-9a1a-b7ba9abaaf7b)

### Theme

winget upgrade JanDeDobbeleer.OhMyPosh -s winget                                                                                                                                                                  
找到了较新的版本，但安装技术与当前安装的版本不同。请卸载包并安装较新的版本。
![image](https://github.com/user-attachments/assets/5f65f25f-1e12-4f85-83ec-b40a1003e64d)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Log output

```Shell
winget upgrade JanDeDobbeleer.OhMyPosh -s winget                                                                                                                                                                  
找到了较新的版本，但安装技术与当前安装的版本不同。请卸载包并安装较新的版本。
```

**Comment by JanDeDobbeleer** [comment]
@yuwenlong yes, this isn't a bug. Uninstall, then install. Everything will stay the same afterwards.
