### ISSUE TITLE
Create environment variable with the state of a segment when it is toggled on or off

### ISSUE THREAD

**Issue by the-mentor** [JanDeDobbeleer/oh-my-posh#6022]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see added?

I suggest adding a feature to create environment variables and update their state when toggling segments on/off

For example:
`POSH_SEGMENT_SPOTIFY = ENABLED` when it is in the enabled state.
`POSH_SEGMENT_SPOTIFY = DISABLED` when it is in the disabled state.

This will programmatically check the state of the segment.
Since it's an environment variable it will be accessible from all the different shells that oh-my-posh supports.
Also, I suggested an environment variable since its faster than running the oh-my-posh executable with arguments every time you want to evaluate the state of the segment.

Let me know what you think.
Thanks
DM

**Comment by JanDeDobbeleer** [comment]
@the-mentor it's impossible for oh-my-posh to set environment variables as they will only be valid for the duration of the execution and not the shell session.

**Comment by the-mentor** [comment]
@JanDeDobbeleer i see
What about an argument that returns the state of the segment?
Would that make sense?
If it does I will open a seperate feature request.

Thanks

**Comment by JanDeDobbeleer** [comment]
@the-mentor the only way this can work is when you create your own wrapper around it. It can be done, but you still need to add a custom code block around it.
