### ISSUE TITLE
Can't parse Java version

### ISSUE THREAD

**Issue by brunovieira97** [JanDeDobbeleer/oh-my-posh#603]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When using the Java segment, it can display a parsing error for the Java version.

In my case, it's OpenJDK 16.

### Environment

- Oh my Posh version: 3.130.0
- Theme: Custom
- Operating System: Windows 10 20H2
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal 1.6.10571.0

### Steps to Reproduce

1. Install OpenJDK (latest version) through Scoop
2. Add Java segment to OhMyPosh theme with "jdk" prefix and "files" display mode
3. Access a directory that contains files that trigger Java segment's exhibition

**Expected behavior:** [What you expected to happen]

Printing `jdk 16` or something like it.

**Actual behavior:** [What actually happened]

Prints `jdk err parsing info from C:\Users\bruno\scoop\apps\openjdk\current/bin/java with OpenJDK 64-Bit Server VM (16+36-2231) for windows-amd64 JRE (16+36-2231), built on Feb  8 2021 11:39:36 by "mach5one" with MS VC++ 16.7 (VS2019)`

**Comment by JanDeDobbeleer** [comment]
Thx, allow me to fix that!

**Comment by brunovieira97** [comment]
Thank you @JanDeDobbeleer! If you need any additional testing, just let me know ;)

**Comment by JanDeDobbeleer** [comment]
Just give me a moment, hectic week with the kids at home while at work and all that. This whole COVID misery is pushing things to the limit.

**Comment by lnu** [comment]
Strange, the regex is fine on my side:
![image](https://user-images.githubusercontent.com/1829553/113294324-21686800-92f7-11eb-950c-54eca87edf3d.png)

Can you post the result of `java -Xinternalversion` ? Curious to see the difference with version 16.

**Comment by JanDeDobbeleer** [comment]
@lnu that should be the output, but you never know 😅

**Comment by lnu** [comment]
OpenJDK 64-Bit Server VM (16+36) for windows-amd64 JRE (16+36), built on Mar 11 2021 10:56:33 by "" with MS VC++ 16.7 (VS2019)

=> fail, but why did they change to 16+36

from the release page:
![image](https://user-images.githubusercontent.com/1829553/113295300-54f7c200-92f8-11eb-97a5-f9383bc77e6e.png)

I guess it means 16.0.0+36 👎

**Comment by lnu** [comment]
This one looks fine in both cases:
`(?:JRE) \((?P<version>(?P<major>[0-9]+)(?:\.(?P<minor>[0-9]+))?(?:\.(?P<patch>[0-9]+))?).*\),`
![image](https://user-images.githubusercontent.com/1829553/113303305-3c3fda00-9301-11eb-9501-c915a649e300.png)

![image](https://user-images.githubusercontent.com/1829553/113303410-58dc1200-9301-11eb-9df2-08afafe15811.png)
