### ISSUE TITLE
VS Code Integrated Terminal Red Line

### ISSUE THREAD

**Issue by GloriousDuck** [JanDeDobbeleer/oh-my-posh#604]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The integrated terminal in VS Code displays a red Line and is vertically shifted.

### Environment

- Oh my Posh version: 3.130.0
- Theme: Paradox 
- Operating System: Windows 10
- Shell: PowerShell 7.1.3
- Terminal: Visual Studio Code

### Steps to Reproduce

The closest issueI could find was https://github.com/JanDeDobbeleer/oh-my-posh/issues/529 this one.
I'm not sure if my problem stems from the same issue (VSCode itself) and i've had no luck fiddling with my theme myself so I basically just want confirmation if this has nothing to do with my oh-my-posh setup.

My Paradox Theme is untouched, my Font is the CaskaydiaCove Nerd Font and I have no terminal-relevant VSCode settings modified.

**Expected behavior:** [What you expected to happen]
In Microsoft Terminal: 
![Untitled](https://user-images.githubusercontent.com/39348917/113243463-98bfdc80-92a2-11eb-8959-db8aff31e985.png)

**Actual behavior:** [What actually happened]
In VS Code:
![Untitled](https://user-images.githubusercontent.com/39348917/113243576-d0c71f80-92a2-11eb-8c5d-4c5818368f47.png)

Additionally to the red line at the start i've also noticed that everything is slightly shifted upwards.

**Comment by JanDeDobbeleer** [comment]
@GloriousDuck yup. That's a vscode issue with inverted ANSI. It's on their backlog though.

**Comment by awdr74100** [comment]
Has this problem been solved? Seems to be only happening on vscode integration terminal at this point. Use Windows 11 as the test.

**Comment by JanDeDobbeleer** [comment]
@awdr74100 you'd have to ask the code team 😀
