### ISSUE TITLE
Migrate command not found in version 24.16.1

### ISSUE THREAD

**Issue by academics700** [JanDeDobbeleer/oh-my-posh#6042]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I am using nerd fonts v3.3.0. While running the following command to migrate

`oh-my-posh config migrate glyphs --config ~/atomic.omp.json --write`

I encountered the following error:

*Error: unknown command "migrate" for "oh-my-posh" *

### Theme

atomic.omp.json

### What OS are you seeing the problem on?

Linux

### Which shell are you using?

bash

### Log output

```Shell
Error: unknown command "migrate" for "oh-my-posh"
Run 'oh-my-posh --help' for usage.
```

**Comment by JanDeDobbeleer** [comment]
@academics700 I'm pretty sure your version of oh-my-posh is outdated and that's why you see that issue.

**Comment by academics700** [comment]
The version is 24.16.1. I just installed today using curl

**Comment by academics700** [comment]
@JanDeDobbeleer The migrate command actually shows up using the --help  flag but doesn't work when I use it.

**Comment by JanDeDobbeleer** [comment]
@academics700 I used the command you provided without issues, so it seems somewhere, something is out of sync.
