### ISSUE TITLE
Rebase progress variables (Git module)

### ISSUE THREAD

**Issue by marekvospel** [JanDeDobbeleer/oh-my-posh#6044]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed?

I am moving my configuration from starship and this is the only feature I really miss.

When in interactive rebase oh-my-posh only offers the `.Rebase` variable, allowing the user to see that we are currently in a rebase. However In the case of interactive rebase, I'd love to see more information (specifically, how many commits I have to go untill my rebase is done)
Starship does this by offering a `$progress_current` and `$progress_total` variable. (https://starship.rs/config/#git-state)

![image](https://github.com/user-attachments/assets/7c6c0e9c-6f3a-45c3-ad68-40adfd415da4)
(a screenshot of starship prompt while in an interactive rebase)

**Comment by marekvospel** [comment]
I am willing to make a PR. Looking over how starship implements this, it seems git saves these numbers as files. (https://github.com/starship/starship/blob/master/src/modules/git_state.rs#L132)

**Comment by marekvospel** [comment]
My bad, oh-my-posh even loads this value, but doesn't expose it to the user (which I still think would be nice)
https://github.com/JanDeDobbeleer/oh-my-posh/blob/bba8c040c263a3255c82aa232e5a93fd6683a7ec/src/segments/git.go#L706C3-L707C60

**Comment by JanDeDobbeleer** [comment]
@marekvospel we do expose it in the `.HEAD` property. That one shows the branch and progress in case in a rebase. But I can definitely adjust it so this information is also exposed raw. My suggestion is to repurpose `.Rebase` but turn it into an object that holds all relevant values. It will still allow `{{ if .Rebase }}` to work as that works the same when an entry is `nil`.

**Comment by marekvospel** [comment]
> @marekvospel we do expose it in the `.HEAD` property. That one shows the branch and progress in case in a rebase. But I can definitely adjust it so this information is also exposed raw. My suggestion is to repurpose `.Rebase` but turn it into an object that holds all relevant values. It will still allow `{{ if .Rebase }}` to work as that works the same when an entry is `nil`.

Great idea! I'll try to implement this later today

**Comment by JanDeDobbeleer** [comment]
@marekvospel already on it ;-)
