### ISSUE TITLE
Background colors on segments not rendering in MacOS during manual execution

### ISSUE THREAD

**Issue by tillig** [JanDeDobbeleer/oh-my-posh#61]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Using [the example theme](https://ohmyposh.dev/docs/configure) from the documentation and running oh-my-posh manually, I don't see background colors rendered.

I'm not sure if this is an artifact of trying to execute it manually or if this means there's something else I need to set. I was trying to do some testing to verify JanDeDobbeleer/oh-my-posh#177 and try converting my custom v2 theme to v3, but I'm not willing to mess up my existing prompt environment if I can't tell if this is going to work the same.

### Environment

- Oh my Posh version: 3.14.2
- Theme: Example from docs.
- Operating System: MacOS
- Shell: PowerShell Core
- Terminal: Mac Terminal

### Steps to Reproduce

First, create `example.json` with the theme from the docs. Note it has a foreground and background color.

Theme:

```json
{
  "final_space": true,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "",
          "foreground": "#ffffff",
          "background": "#61AFEF",
          "properties": {
            "prefix": "  ",
            "style": "folder"
          }
        }
      ]
    }
  ]
}
```

Next, run the oh-my-posh executable and pass it the `example.json` as the configuration, like:

`posh-darwin-amd64 -config ./example.json`

**Expected behavior:** I expected to see the current folder shown with a white foreground and a light blue background.

**Actual behavior:**

<img width="1162" alt="Manual run of oh-my-posh 3" src="https://user-images.githubusercontent.com/1156571/95762681-e730de80-0c62-11eb-8ea1-971db6b29d84.png">

Note there's no light blue background and the foreground color is not white.

**Comment by JanDeDobbeleer** [comment]
My first bet is that the default terminal doesn't accept the colors. Because apart from that it renders what it should. Do me a favor and check iterm2, I'll check how to enable a full color profile in the default terminal later today.

**Comment by tillig** [comment]
Yup, iTerm does seem to render correctly. I mean, I don't have the font set up right, but the colors are correct.

<img width="682" alt="Screen Shot 2020-10-12 at 9 06 33 AM" src="https://user-images.githubusercontent.com/1156571/95767876-4ba36c00-0c6a-11eb-99a7-a39f7aaa51bd.png">

**Comment by JanDeDobbeleer** [comment]
According to the interwebs in regards to Terminal:

> Under Terminal > Preferences... > (Profile) > Advanced, "Declare terminal as:" should be set to xterm-256color

**Comment by tillig** [comment]
I already have that set.

<img width="806" alt="Advanced Preferences" src="https://user-images.githubusercontent.com/1156571/95771410-d9358a80-0c6f-11eb-940f-5e2877dfa251.png">

I also have text set as "display ANSI colors"... however, now I'm wondering if there's some limitation around which colors are allowed or something based on the fact there are only 16 colors shown here.

<img width="806" alt="Text Preferences" src="https://user-images.githubusercontent.com/1156571/95771599-33cee680-0c70-11eb-92e1-42666e75c376.png">

The colors displaying in my existing PowerShell Core prompt (shown in the initial issue) are part of the ANSI palette shown in this preference box.

I did consider that it might have been some PowerShell Core issue, so I started a fresh bash shell without PowerShell Core in the mix and got the same results as when PowerShell Core was there - folder shown in gray text, no background.

**Comment by JanDeDobbeleer** [comment]
It's not related to PowerShell but the terminal. I'll try to check which setting is causing this but it's definitely a Terminal issue and not related to oh-my-posh.

**Comment by JanDeDobbeleer** [comment]
The way I see this, it just can't ever work in Terminal. Everything I tried to set doesn't work so I'll add that context to the docs.

**Comment by tillig** [comment]
Fair enough. I definitely appreciate your looking into it!

**Comment by JanDeDobbeleer** [comment]
I I ever find a solution I'll make sure to provide it though.

**Comment by slice-shikharr** [comment]
JFYI, still facing this issue in 2022 with default Terminal app on macOS Monterey 12.3.1

**Environment**

Oh my Posh version: 7.85.2
Theme: Example from docs.
Operating System: macOS Monterey 12.3.1
Shell: Bash
Terminal: Mac Terminal

**Comment by JanDeDobbeleer** [comment]
I know. And it's still a terminal configuration issue :-)

**Comment by tillig** [comment]
I've been on [iTerm2](https://iterm2.com/) since this issue and have never looked back. Highly recommended.
