### ISSUE TITLE
Install in Git Bash

### ISSUE THREAD

**Issue by capakshay** [JanDeDobbeleer/oh-my-posh#618]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version:
- Theme:
- Operating System:
- Shell:
- Terminal:

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
how to install oh my posh in git bash

**Comment by JanDeDobbeleer** [comment]
You can install this on Windows using either scoop or the [installer](https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v3.133.1/install.exe). Then, follow the bash installation [guide](https://ohmyposh.dev/docs/installation).

**Comment by capakshay** [comment]
Is any other Idea to install it like using  " export PS1="\[\e[30;103m\] \u \[\e[30;104m\] \w \[\e[30;42m\] `__git_ps1` \[\e[0m\] " " in  .bashrc file but it only give rectangular background color .   How to use "fontFace":"Cascadia Code PL"  in **Git Bash** to make beautiful background .

**Comment by JanDeDobbeleer** [comment]
@capakshay you could download the binary and do a full manual setup but that's not advised as the init functionality (as indicated in the docs) will bootstrap everything correctly for you. That's also all validated on git bash.

Also, your sample does not contain anything that would run oh-my-posh.

**Comment by capakshay** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/67746991/113902880-fea1ec00-97ed-11eb-84e0-1c229cf8a6ec.png)
I want my git bash like this

**Comment by JanDeDobbeleer** [comment]
That can indeed be done by installing oh-my-posh using either scoop or the [installer](https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v3.133.1/install.exe). Follow the [installation guide](https://ohmyposh.dev/docs/installation) for bash (same as git bash) and you're all set.

**Comment by capakshay** [comment]
Thanks For The Help, Sir.
But I got an Error While executing this command "scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json" 
Error:'7zip' install failed previously. Please uninstall it and try again.

**Comment by JanDeDobbeleer** [comment]
@capakshay haven't seen that before. I can check when at home.

**Comment by capakshay** [comment]
@JanDeDobbeleer Sir, have you checked it?

**Comment by JanDeDobbeleer** [comment]
I'm home in the weekend, on holiday right now 😉

**Comment by JanDeDobbeleer** [comment]
@capakshay please try the following:

- uninstall oh-my-posh: `scoop uninstall oh-my-posh`
- reboot
- reinstall oh-my-posh: `scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json`
- reboot again (the PATH needs to be populated)
- download a [theme](https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/themes) you like and name it `mytheme.omp.json` for example
- edit your `.bashrc` and add the following line: `eval "$(oh-my-posh --init --shell bash --config ~/mytheme.omp.json)"`
- reload your bash shell

**Comment by capakshay** [comment]
I got the same error that I previously mentioned but I solved it .
"I deleted 7-zip from a directory/local drive and again execute your 3rd command that you are given and further now it works. and I successfully install oh-my-posh"✌

Thank you @JanDeDobbeleer , you're amazing! ❤

Can you suggest me Theme

**Comment by capakshay** [comment]
I got the same error that I previously mentioned but I solved it .
"I deleted 7-zip from a directory/local drive and again execute your 3rd command that you are given and further now it works. and I successfully install oh-my-posh"✌

Thank you @JanDeDobbeleer  , you're amazing! ❤

Can you suggest to me  another Theme

**Comment by JanDeDobbeleer** [comment]
That would be Paradox looking at the screenshot.

**Comment by capakshay** [comment]
I download [Paradox](https://github.com/JanDeDobbeleer/oh-my-posh/releases) theme and made changes but it doesn't work.

**Comment by JanDeDobbeleer** [comment]
@capakshay can you elaborate on what doesn't work?

**Comment by capakshay** [comment]
I download paradox theme and when I enter    
eval "$(oh-my-posh --init --shell bash --config ~/paradox.omp.json)"   in .bashrc and save  the changes in git bash not happen 
it remains the same.

**Comment by JanDeDobbeleer** [comment]
@capakshay did you restart your terminal?

**Comment by capakshay** [comment]
Yes Sir did a lot of time

**Comment by JanDeDobbeleer** [comment]
@capakshay what happens when you enter that command directly in your bash shell?

**Comment by capakshay** [comment]
I didn't enter it in Bash

**Comment by capakshay** [comment]
Which command are you taking about @JanDeDobbeleer ?

**Comment by JanDeDobbeleer** [comment]
@capakshay open your git bash and enter this line directly `eval "$(oh-my-posh --init --shell bash --config ~/paradox.omp.json)"`. If that loads the prompt (which it should), you edited the wrong config file for git bash (a quick lookup suggest it might as well be `~/.bash_profile`).

**Comment by capakshay** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/67746991/114337845-83369680-9b6f-11eb-90d4-34ae48d85440.png)
@JanDeDobbeleer  Nothing changes what to do?

**Comment by JanDeDobbeleer** [comment]
@capakshay it says the path of that config file doesn't exist. So, are you sure that file is there?

**Comment by capakshay** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/67746991/114344775-0d85f700-9b7e-11eb-87ac-9e13bff86592.png)
yes, sir file is there.

**Comment by capakshay** [comment]
@JanDeDobbeleer?

**Comment by JanDeDobbeleer** [comment]
@capakshay the location `~/paradox.omp.json` is not the same as what you're showing here (`D:\Git Doc\paradox.omp.json`). The `~` character is a replacement for your `$HOME` folder.

**Comment by capakshay** [comment]
@JanDeDobbeleer But look at **D:\Git Doc\mytheme.omp.json  ** file. As you say to download and save mytheme.omp.json I save it here but it works. so why paradox.omp.json not work?😞

**Comment by capakshay** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/67746991/114501121-fa8b2980-9c46-11eb-8ed1-a36f40834796.png)
look at this @JanDeDobbeleer I don't know why such happen if I put any address it works😂 Can you Help?

**Comment by capakshay** [comment]
@JanDeDobbeleer?

**Comment by cjboyle** [comment]
@capakshay Git Bash recognizes the Windows filesystem paths differently than, say, PowerShell, so ```D:\Git Doc\paradox.omp.json``` is not recognized as a valid path. Because the theme file isn't in your home directory, you will want to use something like the following in your ```.bashrc```:

```sh
eval "$(oh-my-posh --init --shell bash --config '/d/Git Doc/paradox.omp.json')"
```

**Comment by JanDeDobbeleer** [comment]
Thanks @cjboyle, I was caught up in other things. @capakshay didn't mean to ignore you, sorry if you felt being left out. What CJ says is true, and that command should in theory work.

I would definitely advise to read up on how to use Git Bash, especially given that it's not the same as what you're normally used to on Windows (paths is one example as you now noticed, but there are other things too).

To be honest, I generally discourage the use of Git Bash on Windows, Powershell evolved so much the past years as well as the terminal experience on Windows that it's more of a hassle nowadays than a gain when working against that. That doesn't mean using the WSL doesn't come with clear advantages, but that's on a whole other level obviously. Food for thought.

**Comment by capakshay** [comment]
Thanks, **@cjboyle** I tried many things But it says invalid config path😞. Can you suggest any other way?
**@JanDeDobbeleer**  Is that any change in .gitconfig.
Don't mind sir I know you didn't ignore me.

**Comment by capakshay** [comment]
**@cjboyle** I tried **eval "$(oh-my-posh --init --shell bash --config '/d/Git Doc/paradox.omp.json')" this also**

**Comment by capakshay** [comment]
**@JanDeDobbeleer** can you suggest me source to read up on how to use git Bash

**Comment by JanDeDobbeleer** [comment]
@capakshay I have no resources at my disposal, I'd rather read up on Powershell or run this inside WSL2 if you really want to use Bash.
