### ISSUE TITLE
VS Code Character Appearance

### ISSUE THREAD

**Issue by blopez24** [JanDeDobbeleer/oh-my-posh#621]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
In the integrated terminal in VS Code, the character symbols do not display correctly. Works perfectly in powershell terminal. Not sure if this is another bug (#529 / #604)in VS Code or something to do with my setup. 

### Environment

- Oh my Posh version: 3.133.1
- Theme: paradox
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Visual Studio Code

### Steps to Reproduce

1. Followed the [youtube tutorial](https://www.youtube.com/watch?v=lu__oGZVT98&t=753s) by Scott Hanselman
2. Had to put `Set-PoshPrompt -Theme paradox`   instead of `Set-Theme` to get it working correctly in Powershell.
3. Open terminal on VS Code. 

**Expected behavior:** [What you expected to happen]
For it to look like it did in Powershell. 

**Actual behavior:** [What actually happened]
Broken Characters in VS Code
![a](https://user-images.githubusercontent.com/44515457/114092426-bc6cbf00-986e-11eb-8a2c-cfa96fc56c2b.png)

**Comment by JanDeDobbeleer** [comment]
@blopez24 did you set the vscode terminal font to the same as in Windows Terminal?

**Comment by blopez24** [comment]
No, I just realized that. My bad.

**Comment by blopez24** [comment]
That seemed to fix the issue.

**Comment by JanDeDobbeleer** [comment]
@blopez24 happy to help, hope you're enjoying your new prompt!
