### ISSUE TITLE
I'm having two issues after the update from v2 to v3

### ISSUE THREAD

**Issue by eddynaka** [JanDeDobbeleer/oh-my-posh#627]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

After updating, I started to see this:
```bash
WARNING: You appear to have an unsupported Git distribution; setting $GitPromptSettings.AnsiConsole = $false. posh-git
recommends Git for Windows.
```

Also, I'm seeing duplicated information:
![image](https://user-images.githubusercontent.com/16199012/114279702-54ec7600-9a0c-11eb-9354-b5a35c7ec53b.png)

I saw that you don't have the Paradox theme anymore. It had a nice feature (the time to the right), but I don't know how to add it again.

### Environment

- Oh my Posh version: 3.134
- Theme: powerline
- Operating System: windows 10
- Windows Terminal / Powershell

**Comment by lnu** [comment]
Did you follow the upgrade process?
https://ohmyposh.dev/docs/upgrading/
The list of built-in themes is available here: https://ohmyposh.dev/docs/themes

**Comment by eddynaka** [comment]
Hello,

yes. Now, I'm using powerline, but I still don't know how to fix the duplicate information (ss above) and how to add the time aligned to the right.

**Comment by JanDeDobbeleer** [comment]
@eddynaka that message is coming from posh-git, same as the git status prefix you're seeing. You need to update your git using [git for windows](https://gitforwindows.org/) and can disable that prefix via their settings (I think using `$PoshGitPromptSettings. EnablePromptStatus=$false`). Paradox is available using `Set-PoshPrompt paradox`.

**Comment by eddynaka** [comment]
hi @JanDeDobbeleer , interesting! Because I'm using git for windows, the only different thing is that that is vfs style.

I tried to add this to my $PROFILE:
```bash
$GitPromptSettings.AnsiConsole = $false
$GitPromptSettings.EnablePromptStatus = $false
```

but yet it didn't work.

How do i configure the time to the right? is it possible?

**Comment by JanDeDobbeleer** [comment]
@eddynaka quick question, do you import oh-my-posh first or posh-git?

**Comment by eddynaka** [comment]
Hi @JanDeDobbeleer , this is my current config:

```bash
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme  ~/.oh-my-posh.omp.json
$GitPromptSettings.AnsiConsole = $false
$GitPromptSettings.EnablePromptStatus = $false
```

Do I need to use both?

**Comment by lnu** [comment]
@eddynaka here's a sample of paradox with the time on the right:
```
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffe9aa"
        },
        {
          "type": "session",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffffff"
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#91ddff",
          "properties": {
            "folder_icon": "\uF115",
            "folder_separator_icon": " \uE0B1 ",
            "style": "full"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#95ffa4"
        },
        {
          "type": "python",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#906cff",
          "properties": {
            "prefix": " \uE235 "
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#ffffff",
          "background": "#ff8080",
          "properties": {
            "prefix": " \uE20F"
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "right",
      "segments": [
        {
          "type": "time",
          "style": "plain",
          "foreground": "#007ACC",
          "properties": {
            "time_format": "15:04:05"
          }
        }
      ]
    },
    {
      "type": "newline"
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#007ACC",
          "properties": {
            "prefix": "",
            "text": "\u276F"
          }
        }
      ]
    }
  ],
  "final_space": false
}
```

**Comment by JanDeDobbeleer** [comment]
@eddynaka you can use oh-my-posh without posh-git. Also, which theme is that? Because paradox is shipped with the module.

**Comment by eddynaka** [comment]
@lnu , thanks!

@JanDeDobbeleer ,  i think it's not shipping anymore. At least, the get-theme does not show it!

**Comment by eddynaka** [comment]
@JanDeDobbeleer , without posh-git, it does not show the part: "1 to push 1 uncommited".

**Comment by JanDeDobbeleer** [comment]
@eddynaka `Get-Theme` isn't a cmdlet anymore, you can use `Get-PoshThemes`.

**Comment by eddynaka** [comment]
got it!
that fixed the time to the right and the warning string.

But I lost the part of the string where it showed the git part.

**Comment by lnu** [comment]
@eddynaka So what does it look like now?

**Comment by eddynaka** [comment]
Hi @lnu , below a SS:
![image](https://user-images.githubusercontent.com/16199012/114282751-3b532a80-9a1c-11eb-9692-21bd7e38e01d.png)

It's in main, but i have un-committed things, so before the upgrade it was showing the numbers like [x y z].

**Comment by JanDeDobbeleer** [comment]
@eddynaka what does git status say? Because in the first screenshot, both posh-git and oh-my-posh report the same.

**Comment by eddynaka** [comment]
![image](https://user-images.githubusercontent.com/16199012/114282890-0dbab100-9a1d-11eb-9ff0-a43c0f4ec6cf.png)

In theory, i have a change in the submodule, so the submodule always showed me as a change that i had to make or fix.

doing the same to a specific place, i can see something different:
![image](https://user-images.githubusercontent.com/16199012/114282901-2b881600-9a1d-11eb-8234-c6c0f8fcdc89.png)

am i missing icons? os the number 0 is correct there?

thank u again

**Comment by lnu** [comment]
for the missing icons you need to use one of the Nerd Fonts:https://ohmyposh.dev/docs/fonts

**Comment by JanDeDobbeleer** [comment]
@eddynaka support for submodules is likely something I have to add. I'll check back in the morning.

**Comment by eddynaka** [comment]
Hi @JanDeDobbeleer , got it.

strangely that i'm sure that that was working. but i dont know if that was because of the other import :)

let me try to update the fonts

**Comment by lnu** [comment]
@JanDeDobbeleer @eddynaka in the meantime, you can use the posh git segment instead of the git segment as a workaround for the submodule status.

**Comment by eddynaka** [comment]
how do i do that?

**Comment by lnu** [comment]
try to enable disable with this config(let both to see the difference and enable the one you want to keep):
```
        {
          "type": "poshgit",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#95ffa4"
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#95ffa4"
        },
```
for the posh git segment, you need to have this in your ps profile:
```
import-module posh-git
$GitPromptSettings.EnableFileStatus = $true
$GitPromptSettings.EnablePromptStatus = $true
```
Not sure for the EnableFileStatus but you definitely need the EnablePromptStatus.

With both enabled you'll get something like this:
![image](https://user-images.githubusercontent.com/1829553/114283663-2346cf80-9a4b-11eb-95ae-6ff55952b830.png)

**Comment by eddynaka** [comment]
Fixed the icons.

i will try later the configs above.
thank you!

**Comment by JanDeDobbeleer** [comment]
@eddynaka can you give the output of `git --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --short --branch` when in that state?

**Comment by maidamai0** [comment]
I have duplicated git status information too if I `Import-Module posh-git`.
I keep `Import-Module posh-git` because it provides the auto-complete feature for git.

**Comment by lnu** [comment]
@maidamai0 And that's the reason I still import it too. But the git information should not be duplicated. 
What's your configuration(terminal, shell, ps profile, ...)?

**Comment by JanDeDobbeleer** [comment]
@maidamai0 did you import posh-git before oh-my-posh? Might want to try the other way around according to what I'm reading.

**Comment by maidamai0** [comment]
@lnu 
### terminal
Windows terminal
### shell
poweshell 7.1.3
#### ps profile
```powershell
Import-Module posh-git
Import-Module oh-my-posh
Import-Module -Name Terminal-Icons
Set-PoshPrompt -Theme ~/.oh-my-posh.omp.json # based on star.omp.json
New-Alias ll ls

function Enter-AdminPSSession {
  Start-Process -Verb RunAs (Get-Process -Id $PID).Path
}

# Optionally also define a short alias name:
# Note: 'psadmin' is a nonstandard alias name; a more conformant name would be
#       the somewhat clunky 'etasn' 
#       ('et' for 'Enter', 'a' for admin, and 'sn'` for session)
Set-Alias psadmin Enter-AdminPSSession
Import-Module 'C:\Users\michael\Documents\vcpkg\scripts\posh-vcpkg'
```

@JanDeDobbeleer 
Yes I import `posh-git` before `oh-my-posh`

**Comment by JanDeDobbeleer** [comment]
@maidamai0 swap those two please (add it after the `Set-PoshPrompt` statement)

**Comment by maidamai0** [comment]
@JanDeDobbeleer 
Still have duplicated git status

**Comment by lnu** [comment]
The order of the import has no impact, I swapped both to test and I still have only one status.
Could you put a screenshot of the prompt? and the content of your custom theme?

**Comment by JanDeDobbeleer** [comment]
@lnu according to the docs it does actually. When posh-git detects a custom prompt it doesn't set it. But I asked the creator as the behavior seems to differ per person and I don't see what's causing it.

**Comment by maidamai0** [comment]
@lnu 
I set to the build-in `star` theme and it has duplicated info too:
![image](https://user-images.githubusercontent.com/16829798/114295185-2044f100-9ad6-11eb-9cef-a0135293065e.png)

**Comment by maidamai0** [comment]
`Get-PoshThemes` shows correctly, if this helps.
![demo](https://user-images.githubusercontent.com/16829798/114295331-2d161480-9ad7-11eb-8e99-1fe524baeede.gif)

**Comment by lnu** [comment]
And if you remove the posh git import the duplicated status is gone? 
Could you also print the result of `get-module`?

**Comment by maidamai0** [comment]
Yes, the duplicated status gone if I remove the the posh-git form profile
`get-module` gives:
![image](https://user-images.githubusercontent.com/16829798/114295412-b3caf180-9ad7-11eb-9a2d-c9bafb456964.png)

**Comment by lnu** [comment]
I'm using posh-git 1.0.0. If I rollback to your version I get the same issue:
![image](https://user-images.githubusercontent.com/1829553/114295622-ae08e800-9aa6-11eb-8fa4-3e22cb0fc81d.png)
Please update to the latest version of posh-git and it should work.

**Comment by maidamai0** [comment]
upgrade `posh-git` fixed this issue, Thank you!

**Comment by lnu** [comment]
@JanDeDobbeleer the issue is related to this commit 320ec1d7d32467dfa924f929cd1849fc3c1e4b77
If posh git functions are called before the rendering, it adds itself at the start. Since the issue is only related to an old version of posh git, we can safely tell people to always use posh-git > 1.0.0
I remember we already had this issue a loooonnnnggg time ago.

**Comment by JanDeDobbeleer** [comment]
Let's get this back on track. @eddynaka can you give the output of `git --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --short --branch` when in that state?

**Comment by eddynaka** [comment]
Hello,

below the result:
![image](https://user-images.githubusercontent.com/16199012/114315451-76fdfb00-9ad5-11eb-985a-0b4d982520db.png)

**Comment by JanDeDobbeleer** [comment]
@eddynaka can you copy that output as text for me? I already see a lowercase m rather than a uppercase one. Can you also modify a file in the repo (not the submodule) for me so I can see the difference?

**Comment by eddynaka** [comment]
Of course!

```bash
❯ git --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --short --branch
## main...origin/main
 m src/sarif-pattern-matcher
```

with some file modification:
```bash
❯ git --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --short --branch
## main...origin/main
 M src/Plugins/Tests.Security.Internal/Validators/SEC101_001.HttpAuthorizationRequestHeaderValidatorTests.cs
 m src/sarif-pattern-matcher
```

**Comment by JanDeDobbeleer** [comment]
@eddynaka fix incoming, missed that little bit of information. From the docs:

> Submodules have more state and instead report M the submodule has a different HEAD than recorded in the index m the submodule has modified content ? the submodule has untracked files since modified content or untracked files in a submodule cannot be added via git add in the superproject to prepare a commit.
> m and ? are applied recursively. For example if a nested submodule in a submodule contains an untracked file, this is reported as ? as well.

**Comment by eddynaka** [comment]
@JanDeDobbeleer , with that, i wouldn't need the other extension, right?
Only with oh-my-posh it would be enough to track everything

**Comment by JanDeDobbeleer** [comment]
@eddynaka correct
