### ISSUE TITLE
Incorrectly rendered git status details after version 3.12.1-beta

### ISSUE THREAD

**Issue by edumserrano** [JanDeDobbeleer/oh-my-posh#628]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When in a git directory some of the symbols are not showing correctly when displaying the git status details.  

I've installed several versions of the oh-my-posh powershell module using `Install-Module -Name oh-my-posh -RequiredVersion <specify version> -AllowPrerelease` and found that from version `3.4.7-beta` to version `3.12.1-beta` this problem **does not** exist. However after version `3.12.1-beta` I couldn't find another version where the problem was fixed.

### Environment

- Oh my Posh version:  3.134.0
- Theme: happens in all themes that display detailed git information
- Operating System: Windows 10 Version 2004 (OS Build 19041.867)
- Shell: powershell 7.1.3
- Terminal: Windows Terminal 1.6.10571.0
- Font: FiraCode NF

### Steps to Reproduce

1. Install oh-my-posh via powershell using the command `Install-Module -Name oh-my-posh -AllowPrerelease`
2. Import oh-my-posh via `Import-Module oh-my-posh`
3. Set a theme, such as the agnoster, via  `Set-PoshPrompt -Theme agnoster`

**Expected behavior:** [What you expected to happen]

It should show this:
![image](https://user-images.githubusercontent.com/15857357/114289209-f0620300-9a6d-11eb-8eea-05bd5d9b517a.png)

**Notice that the git status details shows correctly with `+2 ~2 -0`**

The above image was taken using version `3.12.1-beta`  of oh-my-posh.

**Actual behavior:** [What actually happened]

I'm getting this:
![image](https://user-images.githubusercontent.com/15857357/114289208-e93af500-9a6d-11eb-86eb-b0cfab1abfa8.png)

**Notice the `~2 ?2` at the end of the git status details**

The above image was taken using version `3.134.0`  of oh-my-posh.

**Comment by edumserrano** [comment]
Tried the `poshgit` segment and it displays the info correctly using version `3.134.0` of oh-my-posh. Maybe it's an issue with the `git` segment?

Example of `poshgit` which displays git status details correctly and `git` segment which displays it incorrectly:

![image](https://user-images.githubusercontent.com/15857357/114292634-bbfb4080-9a87-11eb-89fa-c97a49ed2144.png)

**Comment by JanDeDobbeleer** [comment]
@edumserrano can you give me the output of `git --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --short --branch`?

**Comment by edumserrano** [comment]
![image](https://user-images.githubusercontent.com/15857357/114314051-11b80300-9af1-11eb-8bc7-9fcd1bbbb300.png)

**Comment by JanDeDobbeleer** [comment]
@edumserrano would you mind copy-pasting that as text?

**Comment by JanDeDobbeleer** [comment]
@edumserrano I'm sorry but we provide the correct state.`??` implies the file is untracked, not "added". That's reserved for `A`.

When I do the following, it's first marked as untracked and after adding to the index it changes to added. This is, according to my understanding 100% correct. @dahlbyk any context on why posh-git does this differently?

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/2492783/114315211-2cdd3f80-9afe-11eb-8cda-832dd9641caf.png">

**Comment by dahlbyk** [comment]
posh-git splits status between staged/unstaged, so _red_ +2 means there are two untracked files to be added and _green_ +2 (from `A`) means two new files have been staged.

**Comment by edumserrano** [comment]
Of course I don't mind that this is considered working as expected but I thought it might be something to consider as an improvement since posh-git displays the information in a more sensible way and because up until version `3.12.1-beta` so did the git segment (arguably).

**Comment by JanDeDobbeleer** [comment]
@edumserrano given that we have the same rendering as posh-git, I suggest we align the behaviour.

**Comment by edumserrano** [comment]
That was quick! Thanks for picking this up @JanDeDobbeleer. I can confirm the new release shows correctly:
![image](https://user-images.githubusercontent.com/15857357/114454933-0e954380-9bd3-11eb-8440-04f6c4678bf7.png)
