### ISSUE TITLE
Battery module shows negative percentage on (battery-less) PC

### ISSUE THREAD

**Issue by vatsan-madhavan** [JanDeDobbeleer/oh-my-posh#633]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

On my desktop, I see a negative value for battery percentage. After setting `"hide_errors: true`, I expected battery to be hidden on the desktop. When I use the same theme on my laptop, the battery percentage shows up correctly: 

**Desktop:**
![image](https://user-images.githubusercontent.com/20246435/114318566-6abc7280-9ac2-11eb-8935-c62c81999c3d.png)

**Laptop:**

![image](https://user-images.githubusercontent.com/20246435/114318552-5c6e5680-9ac2-11eb-82e9-50c8a870c5bd.png)

I wanted to check whether there is a problem with the underlying libraries reporting battery status, so I tried looking at https://github.com/distatus/battery and this is what I noticed, which suggests that battery enumeration is working 

![image](https://user-images.githubusercontent.com/20246435/114318619-b0793b00-9ac2-11eb-99f1-4540bf352ee1.png)

I'll be happy to try to debug the problem if I can get some hints on where to look and how to go about it - I'm completely new at go; I spent a little time trying to bootstrap the sources on vscode to see if I could modify the tests a bit to debug through the code to puzzle out what's going wrong but didn't get far along (spent more time learning the basics of go and less time actually debugging the problem 😉). 

### Environment

- Oh my Posh version: 3.135.1
- Theme: https://gist.github.com/vatsan-madhavan/e1b977665b05c035b3ca39f606160394
- Operating System: Windows 10 
- Shell: Powershell Core (latest)
- Terminal: Windows Terminal

### Steps to Reproduce

**Expected behavior:** Battery module correctly recognizes there are no batteries and hides itself.

**Actual behavior:** Battery is shown with bad/random data.

**Comment by lnu** [comment]
I already thought about this. In that case, the easiest way is to not use the segment on a computer without any batteries.  
But, on the opposite I also like(like you I guess) to use the same theme on all my computers.  
So you can give it a try if you want and I'd be happy to assist you if needed.
The code is located in `segment_battery.go`. You should be able to debug with vscode out of the box(the configs are in the launch.json file). 

PS: now that the battery segment uses the template engine, you can also decide to display something else in case of error(or if the value is not between 0 and 100 for ex.). The default template is:`{{.Icon}}{{ if not .Error }}{{.Percentage}}{{ end }}{{.Error}}`

**Comment by JanDeDobbeleer** [comment]
It's rather easy to hide when there's no battery information to be gathered. I'll see what I can do.

**Comment by vatsan-madhavan** [comment]
Thanks @lnu and @JanDeDobbeleer - appreciate the hints - very helpful! I tinkered with it a bit more and puzzled out a small change that seems to fix the problem  - I tried returning `false` from `enabled()`  early in `segment_battery.go`  when no batteries are found, and that seems to work well. Are you open to a PR from me based on this approach? 

**edit**: See https://github.com/vatsan-madhavan/oh-my-posh/commit/426d8c8c628b6f5f2b9da501684c54eaefec0f9a

**Comment by lnu** [comment]
@vatsan-madhavan You tried your change on a desktop? I don't remember if `getAll()`  returns an error or an empty array when used on a computer without battery.

**Comment by vatsan-madhavan** [comment]
I tested it on 2 different desktops (= no battery) and a laptop (= has battery). 

`getAll()` returns `nil` when no batteries are found. Ultimately, the problems happens at the lines shown below; `batteryPercentage` comes out as `NaN` (=`0/0`) and `b.Percentage` gets set to a value like `-9223372036854775808`.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/5c7d2f40ca79dadf5ff914e8ff12ff544a8a07b1/src/segment_battery.go#L61-L62

**Comment by vatsan-madhavan** [comment]
Thanks for the quick fix!
