### ISSUE TITLE
Location stack in path block

### ISSUE THREAD

**Issue by Aankhen** [JanDeDobbeleer/oh-my-posh#634]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

It would be very useful to have the path block show the size of the location stack if it’s available in the shell and contains more than one entry. In case it helps, the commands I know of to get the size are:

* `(Get-Location -Stack).Count` in PowerShell
* `dirs -p | wc - l` in Bash & zsh

### Environment

- Oh my Posh version: 3.114.0
- Theme: Custom
- Operating System: Windows 10
- Shell: PowerShell
- Terminal: Windows Terminal

### Steps to Reproduce

1. `pushd C:\dir1`
2. `pushd C:\dir2`
3. `pushd C:\dir3`

**Expected behavior:** The path block shows something like:

![Equivalent to 📂2 📁C:\dir3](https://user-images.githubusercontent.com/978992/114349186-352c8d80-9b85-11eb-988e-d68673e3a132.png)

**Actual behavior:** The path block shows only the folder (different one, sorry):

![~ shown](https://user-images.githubusercontent.com/978992/114349412-8046a080-9b85-11eb-829f-b1e679d0918a.png)

**Comment by lnu** [comment]
something like this?
![image](https://user-images.githubusercontent.com/1829553/114353644-8b8dd200-9b6d-11eb-91fe-f2e6cdfbe5be.png)

But the behaviour is different between powershell and unix shells:

- powershell: works only if using pushd/popd (oob)
- zsh (default ohmyzsh config): each time you change directory, the path is added on the stack (and also with pushd/popd)
- fish: pushd/popd only by default (does not support dirs -p)
- bash: pushd/popd only by default

**Comment by Aankhen** [comment]
Yes, like that! (Just with the count hidden if there’s nothing pushed.) May I ask how you have that? I went through `segment_path.go` twice before creating this issue, but I must have missed something, unless it’s a customization of your own.

Thank you for listing the behaviour of the different shells—I only have experience with Bash myself, and all I could find in my brief searches was what I read about zsh. I guess fish would be one of the shells that couldn’t show the stack. As far as zsh goes, I’d defer to actual users on whether it would be useful to show it. They could always hide it if not.

**Comment by lnu** [comment]
I’ll push the branch later today

**Comment by Aankhen** [comment]
Thanks, guys! I wish every feature request went so smoothly! 😬

Do I need to do anything other than update to 3.137 and set `stack_count_enabled`?

**Comment by lnu** [comment]
Should be enough. And reopen or reload your shell.

**Comment by Aankhen** [comment]
I must be doing something wrong. This is my configuration for the block:
```json
        {
          "type": "path",
          "style": "diamond",
          "powerline_symbol": "\uE0B0",
          "foreground": "#ffffff",
          "background": "#004e9d",
          "leading_diamond": "\uE0B6",
          "trailing_diamond": "\uE0B0",
          "properties": {
            "prefix": " \uE5FF ",
            "style": "mixed",
            "stack_count_enabled": true
          }
        }
```
And this is what I see:
![No stack count even after two `pushd`s](https://user-images.githubusercontent.com/978992/114510897-d7677680-9c54-11eb-9a5d-1d4dada9055c.png)

**Comment by lnu** [comment]
It's enough on my side. Don't forget to reload your shell.
Tested on windows and macos:
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/1829553/114511860-bdb83600-9c38-11eb-9448-554fc4f763bb.png">

**Comment by Aankhen** [comment]
Yes, it’s a new shell, but it doesn’t seem to be working:

![No stack count indicator after `pushd`s](https://user-images.githubusercontent.com/978992/114512189-73de4880-9c56-11eb-8652-38b3343b8caf.png)

**Comment by lnu** [comment]
the config I use:
```
{
          "background": "#ff479c",
          "foreground": "#ffffff",
          "powerline_symbol": "",
          "properties": {
            "folder_separator_icon": "  ",
            "home_icon": "~",
            "prefix": "   ",
            "style": "folder",
            "stack_count_enabled": true
          },
          "style": "powerline",
          "type": "path"
        },
```

I also tried your config:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1829553/114521122-68812200-9c42-11eb-960d-535041de0d89.png">

**Comment by Aankhen** [comment]
Odd… are you using your fork or are you using the just-released version?

**Comment by lnu** [comment]
Latest release.

**Comment by lnu** [comment]
I found an issue with set-poshprompt, let me fix this.

It works when invoke directly in the profile like this
Invoke-Expression (&"/usr/local/bin/oh-my-posh" --init --shell=pwsh --config=/Volumes/data/tools/ohmyposh/jandedobbeleer_custom3.omp.json)
but not with set-poshprompt(which does the same)
I'm checking why.

So it's basically the same issue as described here:https://github.com/JanDeDobbeleer/oh-my-posh2/blob/c4919171881e8384a0af4aa5dec26d3ad0ea5f88/README.md#adding-stack-count-to-a-custom-theme https://github.com/JanDeDobbeleer/oh-my-posh2/issues/113

A workaround for the time being is to not use Set-PoshPrompt but this in your Powershell profile:
`Invoke-Expression (oh-my-posh --init --shell pwsh --config "$(scoop prefix oh-my-posh)/themes/jandedobbeleer.omp.json")`

Explained in the documentation here:https://ohmyposh.dev/docs/installation#3-replace-your-existing-prompt

I'll try to see what can be done to make it work with Set-PoshPrompt

**Comment by lnu** [comment]
More context:https://github.com/PowerShell/PowerShell/issues/12868

**Comment by lnu** [comment]
@Aankhen Can you try the latest version and tell us if it's ok?

**Comment by Aankhen** [comment]
The latest version works! Thanks for chasing this down. That was a pretty confusing bug and I really appreciate all the work you put into fixing it. 😊
