### ISSUE TITLE
Some bug or error in YTM

### ISSUE THREAD

**Issue by naruko-hstk** [JanDeDobbeleer/oh-my-posh#639]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [ ] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: 3.129.0
- Theme: my-theme
- Operating System: windows 10 pro
- Shell: powershell
- Terminal: windows terminal

### Steps to Reproduce

When I using YTM and api_url set `http://localhost:9863` it can't show status in YouTube Music Desktop App
Only I set `http://my-ip:9863` can use it and need to refresh again and again.

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/34113239/114425217-7061a780-9beb-11eb-8be8-a16450785cd1.png)
**Actual behavior:** [What actually happened]

**Comment by JanDeDobbeleer** [comment]
@james10949 what do you mean with `need to refresh again and again`? Localhost can be an issue depending on the platform/setup I suppose.

**Comment by kimblesa** [comment]
@JanDeDobbeleer I can confirm this is an issue for me as well, but my issue is it simply doesn't work at all -- I saw no `need to refresh again and again`. Following [the docs](https://ohmyposh.dev/docs/ytm), I verified that I could hit the YTM endpoint myself with postman, and got back sensible JSON output that matches the structure [in the segment](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segment_ytm.go#L55). 

Is there a way to get some logs out to figure out why the segment choked? I saw nothing apparent in the code short of running it locally, but I figured I'd ask.

### Environment
 * Oh my Posh version: 3.133.1
 * Theme: theme I wrote myself, but can repro issue with any theme and boilerplate YTM segment
 * Operating System: windows 10 pro
 * Shell: powershell 7
 * Terminal: windows terminal

```JSON
{
  "type": "ytm",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "#ffffff",
  "background": "#FF0000",
  "properties": {
    "prefix": "\uF16A ",
    "playing_icon": "\uE602 ",
    "paused_icon": "\uF8E3 ",
    "stopped_icon": "\uF04D ",
    "track_separator" : " - ",
    "api_url": "http://localhost:9863"
  }
}
```

![2021-04-12 14_24_08-Postman](https://user-images.githubusercontent.com/6753886/114442822-f86b9100-9b9a-11eb-9db5-2731f12ac76b.png)

sample JSON output from endpoint:
```JSON
{
    "player": {
        "hasSong": true,
        "isPaused": false,
        "volumePercent": 95,
        "seekbarCurrentPosition": 4,
        "seekbarCurrentPositionHuman": "0:04",
        "statePercent": 0.011764705882352941,
        "likeStatus": "INDIFFERENT",
        "repeatType": "NONE"
    },
    "track": {
        "author": "Future Islands",
        "title": "The Fountain",
        "album": "",
        "cover": "https://lh3.googleusercontent.com/LhFwTM-OuArSvdc_Js33BlNkY6RYPMXibAkxjBm41XSrDLoKOqzhY_cfXvKITg7kKgK8k8ivTw5VD1pA=w544-h544-l90-rj",
        "duration": 340,
        "durationHuman": "5:40",
        "url": "https://www.youtube.com/watch?list=RDAMPLOLAK5uy_k_1BYTjiI3oyaTWHkp8pfeyba2U5IlFYQ&v=BCShc8d-8Js",
        "id": "BCShc8d-8Js",
        "isVideo": false,
        "isAdvertisement": false,
        "inLibrary": false
    }
}
```

**Comment by JanDeDobbeleer** [comment]
@kimblesa it's too slow. If you look at the request timing it's 512ms. We stop at [20ms](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/environment.go#L297) because the impact is too high. This was never an issue in the past so maybe something changed at YTDM.

**Comment by kimblesa** [comment]
After mocking the result with my own web app, can confirm it works fine when returning sub-20ms. I ran YTDM on two different machines, and the call never got anywhere near a 20ms response time. I will consider filing an issue with YTDM, and will write a simple app to cache the result from YTDM myself for now :) thanks for the prompt response.

**Comment by JanDeDobbeleer** [comment]
@kimblesa for reference, this is on my machine (macOS, but also validated on Windows)

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2492783/114673148-2d482700-9d06-11eb-960e-95bec01fb0fc.png">

**Comment by tenicio** [comment]
I was able to workaround the issue by specifying the loopback address: `"api_url": "http://127.0.0.1:9863"`.

So perhaps a name resolution issue?

**Comment by kimblesa** [comment]
@tenicio that did the trick! It does appear that some part of my networking stack adds significant amount of latency, that I was able to avoid when hitting a simple caching app I was running on localhost. Thanks so much for the feedback.

**Comment by JanDeDobbeleer** [comment]
I'll make sure to add the local ip by default.
