### ISSUE TITLE
When Oh My Posh is enabled the ZSH history is ignored

### ISSUE THREAD

**Issue by MarcinGil** [JanDeDobbeleer/oh-my-posh#645]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

Using ZSH in Ubuntu my terminals are started with clean history even though a huge .zhistory exists.

### Environment

- Oh my Posh version: 3.136.0
- Theme: powerlevel10k_classic.omp.json
- Operating System: Ubuntu 20.04.2 LTS
- Shell: zsh
- Terminal: Konsole

### Steps to Reproduce

1. Install and configure Oh My Posh in Linux/ZSH as in manual
2. Add startup to .zshrc
`eval "$(oh-my-posh --init --shell zsh --config ~/.poshthemes/powerlevel10k_classic.omp.json)"`
3. Observe history is clear upon startup of Konsole
4. File .zsh_history exists and is non-empty but also not updated with the latest commands

**Expected behavior:** [What you expected to happen]

History works fine

**Actual behavior:** [What actually happened]

ZSH history file is ignored and not updated. New commands are not added there and the shell is also unable to look through the history.

![image](https://user-images.githubusercontent.com/14506/114673558-9c258000-9d06-11eb-9127-f433c883c85e.png)

When using Oh My ZSH (and Powerlevel 10k theme) everything works fine

![image](https://user-images.githubusercontent.com/14506/114673903-faeaf980-9d06-11eb-99b7-7917467bef91.png)

**Comment by JanDeDobbeleer** [comment]
@MarcinGil I'm on macOS using ZSH and can't reproduce this. I have the same invocation and oh-my-posh doesn't really do much other than [set the prompt](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/init/omp.zsh), every other behaviour should stay the same. Are you certain there's nothing in your setup that influences this?

EDIT: hold it, it seems the latest version does ruin this. I was on 3.120.1 before. I'll check.

**Comment by lnu** [comment]
seems to work with the latest version(wsl ubuntu):
![image](https://user-images.githubusercontent.com/1829553/114706051-c6883500-9d28-11eb-8689-180b975e57f0.png)

I also use these plugins:
plugins=(common-aliases git zsh-autosuggestions zsh-syntax-highlighting)

And autosuggestions works based on the history.

**Comment by JanDeDobbeleer** [comment]
@lnu it worked for me until I upgraded. So I can reproduce this. I'll try to figure out a fix (but I'm afraid we could be duplicating history in that case).

**Comment by lnu** [comment]
@JanDeDobbeleer how did you reproduce it? 
I tried my local build and I also downloaded the latest version and in wsl at least it works as expected. Is it a link to a specific configuration ?

PS: if I don't use oh-my-zsh I can reproduce it. But in that case, you have ton configure zsh history in the .zshrc manually. Like this:
```
SAVEHIST=10
HISTFILE=~/.zsh_history
```

**Comment by MarcinGil** [comment]
@lnu for me this is enough to reproduce
![image](https://user-images.githubusercontent.com/14506/114713142-21be2580-9d31-11eb-94c8-ede087b87c63.png)

PS: I'll try your solution to manually specify history file.

**Comment by lnu** [comment]
So you don't use oh-my-zsh and history does not work? but when you user oh-my-zsh it works because history is configured automatically. Can you try to add this in your .zshrc:
```
SAVEHIST=10
HISTFILE=~/.zsh_history
```

Without those lines I can reproduce your issue but it works when they're added to .zshrc.

**Comment by MarcinGil** [comment]
@lnu @JanDeDobbeleer It works with manual setting of the history file

![image](https://user-images.githubusercontent.com/14506/114713720-ad37b680-9d31-11eb-9fba-3b5787507dff.png)

PS. I didn't know you could actually have OhMyZSH and OhMyPosh together.

**Comment by lnu** [comment]
Ohmyzsh does more than just setting the prompt. You can mix both to get all the plugins from ohmyzsh and only use ohmyposh to override th prompt.

**Comment by JanDeDobbeleer** [comment]
@lnu `HISTFILE ` is set for me, I wonder if it's only the `SAVEHIST` part.

**Comment by lnu** [comment]
https://unix.stackexchange.com/questions/389881/history-isnt-preserved-in-zsh
https://www.soberkoder.com/better-zsh-history/

**Comment by MarcinGil** [comment]
> https://unix.stackexchange.com/questions/389881/history-isnt-preserved-in-zsh

Argh! Simply means I relied too much on magic as I usually configure Zsh and OhMyZsh together.
Thank you for insight @lnu !

**Comment by MarcinGil** [comment]
@JanDeDobbeleer I believe we can close the issue as won't fix.
Sorry for taking your time guys.

**Comment by JanDeDobbeleer** [comment]
@MarcinGil it was our pleasure! Learned something today thx to @lnu 👍🏻💪🏻
