### ISSUE TITLE
Git segment may not work with older versions of Git (v1.8)

### ISSUE THREAD

**Issue by cjboyle** [JanDeDobbeleer/oh-my-posh#648]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Git segment "appears" when in repo directories, but shows only ```no_commits_icon``` and ```branch_gone_icon```. I use the same theme configuration file across multiple systems successfully; in this case, the only difference I can see is that the system is running an older version of Git (v1.8 versus v2.x on other systems).

For completeness, the issue persists regardless of a repo's remote scheme (no remote, github.com, GitHub Enterprise, Bitbucket, etc.). All other contextual prompt segments appear to work fine.

### Environment

- Oh my Posh version: 3.317.2
- Theme: tested with the default theme (jandedobbeleer)
- Operating Systems: CentOS 7.6 and Scientific Linux 7.9
- Shell: bash
- Terminal: Windows Terminal (using SSH) and gnome-terminal
- Git version: 1.8.3.1 (the latest available)

### Steps to Reproduce

1. Downgrade Git (I assume)
2. Call oh-my-posh

**Expected behavior:**  ```<github_icon> <branch_icon>master <branch_identical_icon>``` (as an example)

**Actual behavior:** ```<no_commits_icon> <branch_gone_icon>```

**Comment by JanDeDobbeleer** [comment]
Correct. This is by design. We do not support older versions of tooling and I consider that a good thing 😉

**Comment by JanDeDobbeleer** [comment]
Btw, I had the same CentOS discussion at work a few weeks ago when it comes to git, you can't even use these setups as Github Action Runners for example because the "official" git version is too old.

**Comment by cjboyle** [comment]
Ah, good to know. Yeah, in my case, I guess it wouldn't be difficult to add a Command Segment for Git...

Cheers!
