### ISSUE TITLE
Python segment not displayed in home folder

### ISSUE THREAD

**Issue by sobayed** [JanDeDobbeleer/oh-my-posh#649]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

In version 3.137.3 the Python segment is not showing in my home folder, even though `display_mode` is set to `"always"` in the respective part of the configuration. This seems to only affect the home folder, because when changing e.g. to an empty folder the segment shows up (see screenshot).

![oh-my-posh_3 137 2_no_python_segment_in_home_folder](https://user-images.githubusercontent.com/23031125/115030342-4815c980-9ec7-11eb-87d6-66f2886657a5.jpg)

<details>
  <summary>My configuration</summary>

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffe9aa"
        },
        {
          "type": "session",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffffff"
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#91ddff",
          "properties": {
            "folder_icon": "\uF115",
            "folder_separator_icon": " \uE0B1 ",
            "style": "full"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#95ffa4"
        },
        {
          "type": "python",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#906cff",
          "properties": {
            "prefix": " \uE235 ",
            "display_virtual_env": true,
            "display_default": true,
            "display_version": true,
            "display_mode": "always"
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#ffffff",
          "background": "#ff8080",
          "properties": {
            "prefix": " \uE20F"
          }
        }
      ]
    },
    {
      "type": "newline"
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#007ACC",
          "properties": {
            "prefix": "",
            "text": "\u276F"
          }
        }
      ]
    }
  ],
  "final_space": false
}

```

</details>

### Environment

- Oh my Posh version: 3.137.3
- Theme: paradox
- Operating System: Windows 10 (Version 10.0.18363 Build 18363)
- Shell: Powershell 7.1.3
- Terminal: Windows Terminal 1.7.1033.0

### Steps to Reproduce

1. Set `display_mode: "always` in the "python" segment of the configuration
2. Open Powershell in Windows Terminal

**Expected behavior:** Python segment showing in all folders when `display_mode: "always`

**Actual behavior:** Python segment not showing in home folder

**Comment by JanDeDobbeleer** [comment]
That's actually by design as the home folder is generally excluded. Maybe it's indeed a better idea to also allow that for always enabled.

**Comment by sobayed** [comment]
Ah, thanks for the clarification. I was just not expecting this for `display_mode: "always"` so maybe updating the docs might also be an option.

**Comment by JanDeDobbeleer** [comment]
@sobayed you have a valid point I didn't consider so allow me to adjust how that works.

**Comment by awa5114** [comment]
Which posh themes actually have a python segment? How can I find this out?

**Comment by JanDeDobbeleer** [comment]
You can do a quick search here. Or create your own config as it's rather trivial to add it.
