### ISSUE TITLE
Segment to show if NPM or Yarn is being used and possibly their version

### ISSUE THREAD

**Issue by xt0rted** [JanDeDobbeleer/oh-my-posh#653]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I work on projects that use both npm and yarn and often forget which is currently being used. What I'd find really helpful is a segment that shows which tool the current folder or parent folder was set up to use and optionally their version. Looking for a `yarn.lock` should be enough to detect yarn while a `package-lock.json` and falling back to `package.json` should work for npm.

**Comment by JanDeDobbeleer** [comment]
@xt0rted good idea! Let's do it. We could add it as part of the Node segment functionality as well if that makes sense?

**Comment by xt0rted** [comment]
That sounds good to me.
