### ISSUE TITLE
Installation on Ubuntu/bash - "Permission denied".  Likely doc issue.

### ISSUE THREAD

**Issue by NotTheDr01ds** [JanDeDobbeleer/oh-my-posh#654]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

"Permission denied" when installing on Ubuntu.

### Environment

- Oh my Posh version:  N/A
- Theme:  N/A
- Operating System:  Windows/Ubuntu/WSL, but really any **nix.
- Shell:  bash
- Terminal:  N/A

### Steps to Reproduce

I came across [this](https://superuser.com/q/1642350/1210833) Super User question about oh-my-posh installation on Ubuntu 20.04 (on Windows Subsystem for Linux, but I can't imagine that it matters for this issue).  Following the Unix installation instructions as written:

> ### Installation ###
>     wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
>     chmod +x /usr/local/bin/oh-my-posh

... results in "Permission Denied", which is expected since `/usr/local/bin` isn't writeable by non-root users.

**Expected behavior:** Docs should include `sudo` for those commands, right?

> ### Installation ###
>     sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
>     sudo chmod +x /usr/local/bin/oh-my-posh

**Actual behavior:** Docs are missing `sudo` where needed

**Comment by JanDeDobbeleer** [comment]
@NotTheDr01ds correct. Can be added with a small PR if you want ☺️ Otherwise I'll pick it up this weekend.
