### ISSUE TITLE
[Bug] Exit code segment not working with Zsh

### ISSUE THREAD

**Issue by cbargren** [JanDeDobbeleer/oh-my-posh#659]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When running oh-my-posh 3 in a zsh terminal, commands always exit without annotating an error code, regardless of the previous command:

![image](https://user-images.githubusercontent.com/1050712/115126763-773f4000-9f86-11eb-9acc-2795960e473f.png)

These same commands have the expected output in a bash shell:

![image](https://user-images.githubusercontent.com/1050712/115126788-a9e93880-9f86-11eb-8e6f-98f90a9a6268.png)

This is the configuration I used for the above examples:

<h4 id="exit-test">exit-test.omp.json</h4>

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "final_space": true,
  "console_title": true,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "exit",
          "style": "diamond",
          "powerline_symbol": "",
          "invert_powerline": false,
          "foreground": "#ffffff",
          "background": "#2e9599",
          "leading_diamond": "",
          "trailing_diamond": "",
          "properties": {
            "always_enabled": true,
            "color_background": true,
            "display_exit_code": true,
            "always_numeric": true,
            "error_color": "#f1184c",
            "prefix": "\u003ctransparent\u003e\u003c/\u003e  "
          }
        }
      ]
    }
  ]
}
```

### Environment

- Oh my Posh version: `3.137.3`
- Theme: _Custom, see above .omp.json configuration_
- Operating System: _macOS Big Sur_
- Shell: `zsh 5.8 (x86_64-apple-darwin20.0)`
- Terminal: iTerm 2, VSCode integrated terminal, `xterm-256color`

### Steps to Reproduce

1. Apply [above theme](#exit-test) in zsh terminal
2. Execute command that results in a non-zero exit code

**Expected behavior:** Exit segment should display the resulting error code as it does in Bash

**Actual behavior:** Exit segment behaves as if the previous command exited successfully regardless of its exit code value

**Comment by JanDeDobbeleer** [comment]
@cbargren I added your segment to my prompt and it works. Same zsh version so the only difference I could see is how you use oh-my-posh in your `.zshrc` or something else that messes with what we need.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/2492783/115135158-6f2ee100-a016-11eb-9256-9bf701ad22ed.png">

**Comment by cbargren** [comment]
Well, that's strange. I tried removing everything but the oh-my-posh initialization from my .zshrc as well to no avail. If I have time, I'll dig in to this a little more tomorrow. In the meantime, is there anything I should consider that may be messing with what you need? I don't think my setup has anything out-of-the-ordinary, but there must be something here.

Thanks for your help!

**Comment by cbargren** [comment]
@JanDeDobbeleer I think I've figured out why it's happening for me, but if so, I'm not sure what's different and why it's working for you. The issue seems to be right [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/9c4ba43871e42d630a50bb303fe2c128a545f932/src/init/omp.zsh#L9). The problem is that setting `omp_last_error` isn't the first thing happening in the precmd function so the command's exit code is being lost when setting `omp_stack_count`. Moving the `omp_last_error` line up to the top fixes the issue for me.

**Comment by JanDeDobbeleer** [comment]
@cbargren ah, neat. That makes sense though, and indeed I should be able to reproduce. Unless, and this is going to be the case, that change is recent and I didn't restart my shell while validating this 😱.

Do you want to create a PR or shall I go ahead?

**Comment by cbargren** [comment]
Hah! I'm guilty of similar things quite often so I'm in no position to throw stones. 😄

I'll submit a PR. Should be coming in the next 15 minutes or so, barring any other issues. Cheers!
