### ISSUE TITLE
Conda environment showing twice

### ISSUE THREAD

**Issue by jkbellew** [JanDeDobbeleer/oh-my-posh#662]
### Prerequisites

- [ X] I have read and understand the `CONTRIBUTING` guide
- [ X] I looked for duplicate issues before submitting this one

### Description

Whenever a conda environment is activate oh-my-posh shows two of the same environment. The first one is turned on my conda and displays at the front in () and then oh-my-posh reads that same environment and displays that within in the powerline.

### Environment

- Oh my Posh version:  3.139.2
- Theme: Custom
- Operating System: Windows10
- Shell: PowerShell Core 7.1.3
- Terminal: Windows Terminal 1.7.1033.0

### Steps to Reproduce

1. I made sure my profile.ps1 has the following line: [System.Environment]::SetEnvironmentVariable('VIRTUAL_ENV_DISABLE_PROMPT', 1)
2. You need regular python installed and conda installed.
3. When I activate any environment other than conda everything displays fine using ```python -m venv```
4.  But with a conda environment I receive: (env) + my powerline also with the environment. Using ```activate env```

**Expected behavior:** [What you expected to happen]
This shows the current python environment when I use venv:
![image](https://user-images.githubusercontent.com/796886/115157368-e08e8400-a056-11eb-9cd1-350aaa73f984.png)

**Actual behavior:** [What actually happened]
When I turn on a conda environment and not a venv I get:
![image](https://user-images.githubusercontent.com/796886/115157348-c18ff200-a056-11eb-9296-9f14c6463170.png)

**Comment by JanDeDobbeleer** [comment]
@macshaggy have a look at what's inside the `activate.ps1` script as there's no guarantee you can disable the prompt with that variable. There are too many versions of that file out there that all consistency is lost. Long story short, this isn't our responsibility as it might as well be you'd want that to happen.

**Comment by jkbellew** [comment]
Understood

**Comment by JanDeDobbeleer** [comment]
@macshaggy were you able to resolve it?

**Comment by OmkarK45** [comment]
> @macshaggy were you able to resolve it?

Not OP, but this seems to be happening with me as well. 
Oh my Posh version: 3.139.2
Theme: Custom
Operating System: Windows10
Shell: PowerShell Core 7.1.3
Terminal: Windows Terminal 1.7.1033.0

**Comment by SpontaneousDuck** [comment]
For anyone else looking to solve this for Powershell, `conda config --set changeps1 False` disables showing the activated env in powershell. Cheers!

**Comment by Watson-Bao** [comment]
> For anyone else looking to solve this for Powershell, `conda config --set changeps1 False` disables showing the activated env in powershell. Cheers!

Nice, it work.
