### ISSUE TITLE
Theme fails to load a second time using `. ~/.zshrc` command

### ISSUE THREAD

**Issue by jenewland1999** [JanDeDobbeleer/oh-my-posh#663]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Running `. ~/.zshrc` within Windows Terminal (on WSL v2) causes the theme not to load despite. I am not entirely sure why this happens. I hadn't run into the problem before now. I was just editing the path variable and then used the source command to reload my .zshrc file and the prompt stopped working. I tried uninstalling and reinstalling the Ubuntu image for WSL and still the same issue occurs.

### Environment

- Oh my Posh version: 3.139.2
- Theme: Custom (see [gist](https://gist.github.com/jenewland1999/c76222b65c6e81b9a70fa12f5c0f8742))
- Operating System: Windows 10 Pro v20H2 (OS build 19042.928)
- Shell: Zsh
- Terminal: Windows Terminal App (v1.7.1033.0)

### Steps to Reproduce

1. Install Zsh and set as the default prompt
2. Install Oh my Posh
3. Place `eval "$(oh-my-posh --init --shell zsh --config ~/.ws2.omp.json)"` in `~/.zshrc` file and use the command `. ~/zshrc`
4. Close and reopen the Windows Terminal app and repeat the last command (`. ~/.zshrc`)

**Expected behavior:** For it to load the custom theme every time the `. ~/.zshrc` command is run.

**Actual behavior:** Loads default .zsh prompt

**Comment by JanDeDobbeleer** [comment]
@jenewland1999 you don't need to reload `~/.zshrc` every session (that's what `. ~/.zshrc` does, it sources that file and executes the logic. Adding the line to that file is enough for zsh to pick it up every time it starts provided `~` resolves to `$HOME` on your setup (I've seen weird things).

**Comment by jenewland1999** [comment]
> @jenewland1999 you don't need to reload `~/.zshrc` every session (that's what `. ~/.zshrc` does, it sources that file and executes the logic. Adding the line to that file is enough for zsh to pick it up every time it starts provided `~` resolves to `$HOME` on your setup (I've seen weird things).

I'm away on business so I don't have access to my PC, will test when I'm back on Monday to see if it's the $HOME variable not being set/pointing somewhere differently. 

Thanks for your reply though 😄

**Comment by JanDeDobbeleer** [comment]
@jenewland1999 you're welcome. We'll get to the bottom of this!

**Comment by jenewland1999** [comment]
Hi, 

sorry for the late update, so it seems the $HOME variable is in fact set to /home/jenewland1999 which is where `.zshrc` lives. and regardless if you use `. ~/.zshrc`, `source ~/.zshrc` or even the full path `. /home/jenewland1999/.zshrc` it still always fails to load a second time. Which is really odd. Sure you should never need to run this command a second time unless you're adding something new to your `.zshrc` file, and this issue can be avoided by either restarting the terminal or using the `su` command, but just seems strange that it only picks it up the first time.

**Comment by JanDeDobbeleer** [comment]
@jenewland1999 I can't reproduce this which makes it rather annoying to find a fix.

**Comment by JanDeDobbeleer** [comment]
@jenewland1999 this is in fact not an issue. From the [docs](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reload-the-zshrc-file):

### How do I reload the zshrc file?

You may have seen somewhere that when you make a change to your zshrc file, you need to reload it. The common wrong suggestion is to use `source ~/.zshrc`. This may **cause trouble** because some things that are already in the zsh session haven't been removed (variables, functions, hooks...). It's also possible that you're repeatedly running an init script and causing more and more processes to start.

To properly reload the zshrc file, you need to restart the zsh session. You can either:

Restart the terminal.

or

Restart the zsh process by running: `exec zsh`.
