### ISSUE TITLE
Erratic prompt behavior when looking at \\wsl$ directories using Windows Powershell and Powershell Core 

### ISSUE THREAD

**Issue by sql-sith** [JanDeDobbeleer/oh-my-posh#667]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description
When using OMP in (Windows) `Powershell` and `pwsh `(core) and accessing directories in the `\\wsl$` hirearchy, the prompt regresses to an unexpected prompt ... sometimes.

### Environment

- Oh my Posh version: 3.117.2
- Theme: custom
- Operating System: Windows 10 19042.928
- Shell: pwsh v7.1.3 or powershell v5.1.19041.906
- Terminal: WIndows Terminal Preview 1.8.1032.0

### Steps to Reproduce

I'm not sure if you will be able to repro this, but I hope so. Here is what I do. I am using actual directory names because I can't yet repro this generically.

1. Open pwsh.exe v7.1.3
2. cd to \\wsl$\home\chris\github\domains-mssql-uplift
3. continue to cd to other subfolders of \\wsl$\home\chris\github\domains-mssql-uplift

**Expected behavior:** [What you expected to happen]
I expected my prompt to display consistently in each folder.

**Actual behavior:** [What actually happened]
It does not (see screenshot). And even worse, it does not always happen. Right now, in my GitHub directory, after cd'ing into two folders, the prompt looks as expected. The others look like what you see in the screenshot. And ... of the two, one of them looked wrong at first and later corrected itself. Very odd. I will attach a screenshot and my theme file (renamed to *.txt so that GitHub will post it).

[jandedobbeleer-modded.omp.json.txt](https://github.com/JanDeDobbeleer/oh-my-posh/files/6339817/jandedobbeleer-modded.omp.json.txt)

![image](https://user-images.githubusercontent.com/1082694/115318872-43117e00-a144-11eb-98f0-6a13e8543b12.png)

**Comment by JanDeDobbeleer** [comment]
@sql-sith can you give the output of the following commands?

- `$PWD.ProviderPath.TrimEnd("\")`
- `$PWD.ToString().TrimEnd("\")`

**Comment by sql-sith** [comment]
Here you go. I did it once in a directory that does not show the expected prompt and then popped up a level to one that has the expected prompt. 

I also wanted to mention that when I am in a directory where the prompt works as expected, the prompt appears, well, promptly. When I'm in a directory where the expected prompt is not displayed, it takes about 2.5 seconds. I'm going to see if I can figure out why using PS debugging.

![image](https://user-images.githubusercontent.com/1082694/115597586-0908bf00-a29f-11eb-8038-93691403fda7.png)

**Comment by sql-sith** [comment]
Hey, sorry for the double-post, but I did find something I want to share. If I call `prompt` directly, this happens. I'm going to keep chasing this but if it is meaningful to Team OMP, let me know. Thanks!

![image](https://user-images.githubusercontent.com/1082694/115598451-11adc500-a2a0-11eb-8423-d3e8105a0a33.png)

**Comment by sql-sith** [comment]
Also, I don't think I posted my `prompt` function. So in case I'm doing something completely wrong, here it is:
```PS
PS>(dir Function:\prompt).Definition

    #store if the last command was successful
    $lastCommandSuccess = $?
    #store the last exit code for restore
    $realLASTEXITCODE = $global:LASTEXITCODE
    $errorCode = 0
    Set-PoshContext
    if ($lastCommandSuccess -eq $false) {
        #native app exit code
        if ($realLASTEXITCODE -is [int] -and $realLASTEXITCODE -gt 0) {
            $errorCode = $realLASTEXITCODE
        }
        else {
            $errorCode = 1
        }
    }

    $executionTime = -1
    $history = Get-History -ErrorAction Ignore -Count 1
    if ($null -ne $history -and $null -ne $history.EndExecutionTime -and $null -ne $history.StartExecutionTime -and $global:omp_lastHistoryId -ne $history.Id) {
            $executionTime = ($history.EndExecutionTime - $history.StartExecutionTime).TotalMilliseconds
            $global:omp_lastHistoryId = $history.Id
    }
    $omp = "C:/Users/cleonard/Documents/PowerShell/Modules/oh-my-posh/3.117.2/bin/posh-windows-amd64.exe"
    $config = $global:PoshSettings.Theme
    $cleanPWD = $PWD.ProviderPath.TrimEnd("\")
    $cleanPSWD = $PWD.ToString().TrimEnd("\")
    $standardOut = @(&$omp --error="$errorCode" --pwd="$cleanPWD" --pswd="$cleanPSWD" --execution-time="$executionTime" --config="$config" 2>&1)
    # the output can be multiline, joining these ensures proper rendering by adding line breaks with `n
    $standardOut -join "`n"
    Set-PoshGitStatus
    $global:LASTEXITCODE = $realLASTEXITCODE
    #remove temp variables
    Remove-Variable realLASTEXITCODE -Confirm:$false
    Remove-Variable lastCommandSuccess -Confirm:$false
```

**Comment by JanDeDobbeleer** [comment]
@sql-sith when you cd into the directory where it fails can you look at the content of `$error`?

**Comment by sql-sith** [comment]
Hello again, and sorry for the delay. Here is the output of $error when in a directory where the prompt fails:
```ps
PS>$error
Index operation failed; the array index evaluated to null.
Index operation failed; the array index evaluated to null.
At C:\Users\cleonard\Documents\WindowsPowerShell\Modules\posh-git\0.7.3\GitUtils.ps1:165 char:13
+             $hash[$path] = 1
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex
```

Also important: I found that while trying to repro this today, I could only repro on Windows Powershell (v5.1.19041.906). I could not repro it on Powershell (Core v7.1.3). Am I possibly using functionality that only works in Windows Powershell Core?

**Comment by JanDeDobbeleer** [comment]
Oh, so this is in that case a bug in posh-git. But, as they're now already on V1, I suggest you first update posh-git, if it's not resolved raise a bug on their end. But most likely this will be resolved by upgrading.

**Comment by sql-sith** [comment]
Will do. I'm actually looking at their code to see why this happens (basically something that's not supposed to be empty is getting passed in empty), but you're right, I'm missing the forest for the trees, and I should just upgrade to see if that fixes it.

It's an interesting bug though - sometimes happens in the same directory and sometimes not, and when I set a breakpoint on posh-git's function, it appears to not always fire when I expect it to. Anyway, I'm off to see if an upgrade will help. Thanks very much for walking through this with me, Jan!

**Comment by JanDeDobbeleer** [comment]
@sql-sith any update on whether or not the upgrade resolved the issue?

**Comment by sql-sith** [comment]
The upgrade did resolve the issue. Thanks for the nudge to get me to reply.
