### ISSUE TITLE
Auto-upgrade for Azure CLI breaks widget

### ISSUE THREAD

**Issue by tomkerkhove** [JanDeDobbeleer/oh-my-posh#669]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Auto-upgrade for Azure CLI breaks widget by showing `Do you want to continue? (Y/n): <sub-name>`.

### Environment

- Oh my Posh version: 3.136.0
- Theme: Custom
- Operating System: Windows
- Shell: PowerShell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Enable auto-upgrade for Azure CLI ([docs](https://docs.microsoft.com/en-us/cli/azure/update-azure-cli#automatic-update))
2. Wait for a new version to be available
3. Widget shows `Do you want to continue? (Y/n): <sub-name>`

![image](https://user-images.githubusercontent.com/4345663/115388516-43f5ee80-a1dc-11eb-8b5a-b5bc281bd18f.png)

**Expected behavior:** Show that an upgrade is available and I need to update

**Actual behavior:** `Do you want to continue? (Y/n): <sub-name>`

**Comment by tomkerkhove** [comment]
Updating the CLI by calling an Azure CLI operation fixesit

**Comment by JanDeDobbeleer** [comment]
@tomkerkhove What we can do is show a different message. We can't stop and show that prompt, then continue. What message would make sense?

**Comment by tomkerkhove** [comment]
That's fair enough. How about `Pending Azure CLI update` or so?

**Comment by tomkerkhove** [comment]
Thanks Jan!
