### ISSUE TITLE
problem with non english characters in the path

### ISSUE THREAD

**Issue by fuglphoenix** [JanDeDobbeleer/oh-my-posh#670]
### Prerequisites

- [ yes] I have read and understand the `CONTRIBUTING` guide
- [ yes] I looked for duplicate issues before submitting this one

### Description

it doesn't like it when there is non english characters in the path

### Environment

- Oh my Posh version: 3.140.0

- Operating System: windows 10 build 19043
- Shell: powershell 7.1.3
- Terminal: windows terminal

### Steps to Reproduce

1. have a non english characters eg. æ ø å in the path
2. `Set-PoshPrompt -Theme jandedobbeleer -Verbose`

**Expected behavior:** 
Setting the new theme

**Actual behavior:**

Actual path to binary: C:\Users\nbn\OneDrive - Søren Jensen\Dokumenter\PowerShell\Modules\oh-my-posh\3.140.0\bin\posh-windows-amd64.exe
Error message:
```
&: The term 'C:\Users\nbn\OneDrive - S├©ren Jensen\Dokumenter\PowerShell\Modules\oh-my-posh\3.140.0\bin\posh-windows-amd64.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.
```

notice the characters after OneDrive -... they don't match the actual path.

it works fine if i move the binary to another folder (without the special characters) and modify the oh-my-posh.psm1

**Comment by JanDeDobbeleer** [comment]
@fuglphoenix my bad, I removed a line from the module which is in our init script but forgot we load that path before init. You should be able to resolve this by setting the console to UTF8 before importing oh-my-posh and I'll fix that in the meantime: `[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding`

**Comment by fuglphoenix** [comment]
@JanDeDobbeleer thanks :-)

**Comment by JanDeDobbeleer** [comment]
Let me know if the latest release fixes the issue. In theory it should.

**Comment by HughGrant** [comment]
NO,  the issue still somehow remains, my username has Chinese character, I have to set the encoding in order for it to work.
But still, I'm glad that I found this

**Comment by JanDeDobbeleer** [comment]
@HughGrant yes, one day Powershell will fix this 😅
