### ISSUE TITLE
Settings are gone after closing the terminal

### ISSUE THREAD

**Issue by alinademi** [JanDeDobbeleer/oh-my-posh#680]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I have upgraded from the awesome V2 to the amazing V3. But changes won't stay permanently.

### Environment

- Oh my Posh version: V3
- Theme: Both out of the box and custom.
- Operating System: Edition: Windows 10 Home, Version: 20H2, OS build: 19042.928, Experience Pack: 120.2212.551.0

- Shell: Powershell 7
- Terminal: pwsh or winsdows terminal

### Steps to Reproduce

1. upgrade to V3, #Successfull
2. Set-PoshPrompt -Theme [any theme] - #successful

![image](https://user-images.githubusercontent.com/52844766/115800970-806a4b80-a390-11eb-9913-ed33c00ca5f9.png)

3. Theme is set but it's gone after restarting the shell

![image](https://user-images.githubusercontent.com/52844766/115801039-a8f24580-a390-11eb-8041-6c356ead9fbb.png)

It seems you're using an oh-my-posh V2 cmdlet while running V3.
To migrate your current setup to V3, have a look the documentation.

**Expected behavior:** Theme must be set permanently

**Actual behavior:** Theme is gone after restart

**Comment by JanDeDobbeleer** [comment]
@alinademi you need to adjust your `$PROFILE` to contain that line. You probably (according to the output) still have the V2 line in there which needs to be replaced by the one from V3.

**Comment by alinademi** [comment]
Profiles are looking good and updated based on the docs.
I have to investigate more on this. Seems not related to oh-my-posh at all.
It works fine inside Vscode as well as the windows terminal app. The problem occurs when PowerShell 7 is opened individually.
I guess there is something about the coexistence of PowerShell 7 and Windows Powershell.

**Comment by JanDeDobbeleer** [comment]
@alinademi they have a different profile location. Might want to check both.

**Comment by lnu** [comment]
powershell core [location]( https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.1): 
pwershell [location](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1)

You can check both with `$PROFILE | Get-Member -Type NoteProperty`

**Comment by JanDeDobbeleer** [comment]
@alinademi any update on your end?
