### ISSUE TITLE
Norton says Oh My Posh needs attention.

### ISSUE THREAD

**Issue by BlueStaggo** [JanDeDobbeleer/oh-my-posh#686]
### Prerequisites

- ✅ I have read and understand the `CONTRIBUTING` guide
- ✅ I looked for duplicate issues before submitting this one

### Description

Norton, for some reason, warns that Oh My Posh 3.142.0 Windows for both amd64 and 386 is dangerous. However, downloading 3.141.2 fixes this. This is nothing to do with the Powershell module, just the oh-my-posh executable. I feel like this is happening because the file is new.

### Environment

- Oh my Posh version: Only 3.142.0 (amd64 or 386)
- Theme: Any
- Operating System: Windows 10 1909
- Shell: Powershell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Make sure you have Norton installed.
2. Download Oh My Posh ([amd64](https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v3.142.0/posh-windows-amd64.exe) / [386](https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v3.142.0/posh-windows-386.exe)).
3. Norton says that posh-windows-amd64.exe or posh-windows-386.exe requires attention (as well as some random f_###### files).

**Expected behavior:** I expected oh-my-posh 3.142.0 to run perfectly every time.

**Actual behavior:** Norton keeps telling me that the information it has on oh-my-posh is inconclusive. I can still run the program, it's just that Norton keeps popping up every time.

**Comment by BlueStaggo** [comment]
Todo: mention https://github.com/JanDeDobbeleer/oh-my-posh/issues/218

**Comment by BlueStaggo** [comment]
https://github.com/JanDeDobbeleer/oh-my-posh/issues/218 I don't know how to mention other issues.

**Comment by BlueStaggo** [comment]
Oops. Silly me! ^^^

**Comment by JanDeDobbeleer** [comment]
@BlueStaggo the same sometimes happens with Defender. Unfortunately there's nothing we can do about it. The assumption is that as we rely on the win32 API we're flagged. The advise is to exclude it from your AV.
