### ISSUE TITLE
duplicate git information is showing in the prompt

### ISSUE THREAD

**Issue by exxmen** [JanDeDobbeleer/oh-my-posh#689]
### Prerequisites
- [✓] I have read and understood the `CONTRIBUTING` guide
- [✓] I looked for duplicate issues before submitting this one

### Description

I am showing duplicate git information in the prompt

### Environment

- Oh my Posh version: 3.144.0
- Theme: JanDeDobbeleer
- Operating System: Windows 10 18363.1500
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal 1.7.1033.0

### Steps to Reproduce

1. Install posh-git and oh-my-posh modules
2. Install Nerd Font (CaskaydiaCove NF)
3. Edit PowerShell profile to import modules and set theme

$profile
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme JanDeDobbeleer

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/4624303/116254303-d03b7f00-a7a3-11eb-8bee-d89f669d4ff7.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/4624303/116254533-00831d80-a7a4-11eb-9549-97f8c73b4b4e.png)

**Comment by JanDeDobbeleer** [comment]
Good catch, I pushed both segments (git and posh-git) to the theme. I'll remove it, you can also [create a custom theme](https://ohmyposh.dev/docs/pwsh#override-the-theme-settings) based on this if you want.

**Comment by exxmen** [comment]
@JanDeDobbeleer removed post git and created a custom theme and working as expected. trying to figure out though how to remove the gap between the execution time block and the exit block when execution time is only milliseconds. works as expected otherwise

no gap when execution time is more than milliseconds
![image](https://user-images.githubusercontent.com/4624303/117321274-92cfa380-aebf-11eb-9329-08e6f13463cb.png)

with a gap when execution time is within milliseconds
![image](https://user-images.githubusercontent.com/4624303/117321565-d1fdf480-aebf-11eb-9514-4d7a080c0a6c.png)

**Comment by JanDeDobbeleer** [comment]
@exxmen that's a windows terminal issue: https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext

**Comment by exxmen** [comment]
> @exxmen that's a windows terminal issue: https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext

this fixed it for me 👍.
