### ISSUE TITLE
support adding custom information to the prompt again

### ISSUE THREAD

**Issue by hbinkle** [JanDeDobbeleer/oh-my-posh#693]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

in V2 I was able to add custom information to the prompt by adjusting or creating a custom theme.
So I was possible to e.g. add kubernetes information like here:
```powershell
#kubernetes info: https://blog.guybarrette.com/powershell-prompt-how-to-display-your-current-kubernetes-context
    $K8sContext = $(kubectl config current-context)
    If ($K8sContext) {
        #$prompt += Write-Prompt -Object "$($sl.PromptSymbols.SegmentForwardSymbol)" -ForegroundColor $sl.Colors.SessionInfoBackgroundColor -BackgroundColor "DarkGreen"
        $prompt += Write-Prompt -Object $([char]::ConvertFromUtf32(0x2554))
        $prompt += Write-Prompt -Object " $K8sContext " -ForegroundColor "Black" -BackgroundColor "DarkGreen"
        $K8sNamespace = $(kubectl config view --minify --output "jsonpath={..namespace}")
        If ($K8sNamespace ) {
            $prompt += Write-Prompt -Object "$($sl.PromptSymbols.SegmentForwardSymbol)" -ForegroundColor "DarkGreen"  -BackgroundColor "Green"
            $prompt += Write-Prompt -Object " $K8sNamespace " -ForegroundColor "Black" -BackgroundColor "Green"
            #$prompt += Write-Prompt -Object "$($sl.PromptSymbols.SegmentForwardSymbol)" -ForegroundColor "Green"            
        }
    }
```

it would be great to use V3 keeping my kubernetes context info

**Comment by lnu** [comment]
Could the [kubectl segment](https://ohmyposh.dev/docs/kubectl) be helpful for your scenario?

**Comment by JanDeDobbeleer** [comment]
@hbinkle you can also make use of the [environment segment](https://ohmyposh.dev/docs/environment) which has the ability to load context that's set using Powershell. But as @lnu said, if the kubectl segment fits, I'd favour that > custom stuff.

**Comment by JanDeDobbeleer** [comment]
@hbinkle any update on your end?

**Comment by hbinkle** [comment]
@JanDeDobbeleer thank.
I general this looks fine, but I can't find any description where to adjust/add the config or set a custom config file.
The [config section of the docs](https://ohmyposh.dev/docs/configure) explains how modify and test/try a custom config, but not where to put it/how to apply.

**Comment by JanDeDobbeleer** [comment]
@hbinkle you're right, that can be found [here](https://ohmyposh.dev/docs/pwsh#override-the-theme-settings).

**Comment by hbinkle** [comment]
oh, the config has to be done within the theme file.
Now I got it.
Thanks!

**Comment by hbinkle** [comment]
one last question:
Is it possible to disable a block section instead completly remove it from the json?

**Comment by JanDeDobbeleer** [comment]
@hbinkle no, you need to remove it. There's no disable functionality.

> oh, the config has to be done within the theme file.

Yes, that's something that was tricky to adjust based on how V2 worked, themes are basically predefined configs now.

**Comment by hbinkle** [comment]
thanks @JanDeDobbeleer , great work!
