### ISSUE TITLE
Scoop installation after PowerShell Install-Module on Windows

### ISSUE THREAD

**Issue by edshamis** [JanDeDobbeleer/oh-my-posh#695]
Can I just install Scoop version after PowerShell Install-Module has been used? How do I know which version is used?

**Comment by JanDeDobbeleer** [comment]
@edshamis the scoop version and Powershell module one are different in the way that the module is a wrapper with a few additional convenience cmdlets the scoop version doesn't have (mostly for the themes). If you want to use scoop, I advise to uninstall the Powershell module and follow the [platform specific guide](https://ohmyposh.dev/docs/windows) for Powershell and other shells on Windows.

**Comment by edshamis** [comment]
@JanDeDobbeleer Thanks for clarification!
