### ISSUE TITLE
Crash when entering non-filesystem shells in nushell

### ISSUE THREAD

**Issue by cdhunt** [JanDeDobbeleer/oh-my-posh#698]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: 3.113.0
- Theme: Custom
- Operating System: Win10
- Shell: Nushell 3.0
- Terminal: Windows Terminal 1.7.1033

### Steps to Reproduce

1. Have a moderately complex structure file Nu understands
2. enter shell `enter $(config path)` ([Nu docs](https://www.nushell.sh/book/shells_in_shells.html#going-beyond-directories))
3. cd into the file `cd color_config`

**Expected behavior:** [What you expected to happen]

oh-my-posh not to crash. Ideally, it should understand the path format to render in the path section.

**Actual behavior:** [What actually happened]

```
> cd color_config
error: Failed to spawn process
  ┌─ shell:1:8
  │
1 │ echo $(oh-my-posh -config c:\Users\chunt\.ohmyposh-litedark.json)
  │        ^^^^^^^^^^ failed to spawn

> pwd
/color_config
```

**Comment by JanDeDobbeleer** [comment]
@cdhunt is it oh-my-posh that crashes or nu that fails to initialize? When oh-my-posh crashes you usually see a very different output (an actual go stack trace).

**Comment by cdhunt** [comment]
I think Nu is swallowing the go stack trace since it is just calling out to cmd. I'll see if I can expose the details somehow.

**Comment by JanDeDobbeleer** [comment]
@cdhunt calling oh-my-posh directly should result in the same issue (but then not get swallowed).

**Comment by cdhunt** [comment]
Even calling it directly returns the same `failed to spawn` message.

**Comment by JanDeDobbeleer** [comment]
@cdhunt I'll try to reproduce

**Comment by cdhunt** [comment]
I pulled up Process Monitor and watched nu.exe. 

Here's one that fails.
![image](https://user-images.githubusercontent.com/114173/117002627-cb9a2d80-acb1-11eb-92f7-5d2fcc3f9e99.png)

And he's a normal run.
![image](https://user-images.githubusercontent.com/114173/117002881-216ed580-acb2-11eb-9371-be09b9a16c30.png)

**Comment by cdhunt** [comment]
Duplicated this issue at https://github.com/nushell/nushell/issues/3384.

**Comment by JanDeDobbeleer** [comment]
@cdhunt ~~how can I reproduce this? When I enter a file it works as expected `enter go.mod`, what am I missing?~~

Found it:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/2492783/117045049-5b21f980-ad0f-11eb-8517-caec463ba5c4.png">

Let's see what I can do.

**Comment by JanDeDobbeleer** [comment]
@cdhunt this smells like an issue at nu:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2492783/117046252-c3250f80-ad10-11eb-80ee-09920288d6c5.png">

**Comment by JanDeDobbeleer** [comment]
As the original issue is closed at nutshell, I'm not going to track this anymore. We can't fix that here.
