### ISSUE TITLE
feat: add git origin symbols to git segment logic

### ISSUE THREAD

**Issue by JanDeDobbeleer** [JanDeDobbeleer/oh-my-posh#7]
`oh-my-posh` supports showing origin symbols for git repositories (github/gitlab/bitbucket), so `go-my-posh` should have this as well.

**Comment by nwykes** [comment]
I've started working on this.  WIP is at https://github.com/nwykes/oh-my-posh3/tree/git_origin

**Comment by JanDeDobbeleer** [comment]
> I've started working on this.  WIP is at https://github.com/nwykes/oh-my-posh3/tree/git_origin

The icon names are already fine, should be rather straightforward. How comfortable are you with golang?

**Comment by nwykes** [comment]
I've tinkered with golang.

it's working for me locally, trying to build some tests for it and the associated doc updates, etc.

Should it default to on or off?

**Comment by JanDeDobbeleer** [comment]
> Should it default to on or off?

Looking at V2 it's off by default so I'd opt for that.

**Comment by JanDeDobbeleer** [comment]
@nwykes I finished this one. Given that I reworked the git functionality quite a bit, I'm focusing on finishing it. Once this is feature complete (revert and bisect still to be done), everything should be on par with V2.
