### ISSUE TITLE
Always a newline before rendering prompt

### ISSUE THREAD

**Issue by Descalon** [JanDeDobbeleer/oh-my-posh#701]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

After every command (or before rendering the prompt) a newline is added.

### Environment

- Oh my Posh version: 3.146.0
- Theme: All (for as far as I could discover)
- Operating System: Windows 10
- Shell: Powershell 7.1.3
- Terminal: Windows Terminal Preview 1.8.1032.0

### Steps to Reproduce

1. Open a terminal
2. type `Write-Host foo`
3. See the new line before the newly rendered prompt

**Expected behavior:**
No new line before rendering prompt (or make it customizable through config):
![Screenshot 2021-05-04 170447](https://user-images.githubusercontent.com/1098500/117026222-e42f3580-acfb-11eb-90e1-7423fe06c769.png)

**Actual behavior:** [What actually happened]
Newline before rendering prompt:
![Screenshot 2021-05-04 170406](https://user-images.githubusercontent.com/1098500/117026274-f01af780-acfb-11eb-82e6-1a619e723a92.png)

**Comment by JanDeDobbeleer** [comment]
@Descalon that smells like a bug. I'll check.

**Comment by JanDeDobbeleer** [comment]
@Descalon how do you invoke oh-my-posh? I don't have this issue.

Windows (using the push module):

<img width="709" alt="image" src="https://user-images.githubusercontent.com/2492783/117044116-5872d480-ad0e-11eb-91ef-93301bfdba64.png">

macOS (Invoke-Expression):

<img width="704" alt="image" src="https://user-images.githubusercontent.com/2492783/117044172-6b85a480-ad0e-11eb-85a7-93d8c54bcfd1.png">

**Comment by Descalon** [comment]
I'm importing the module and invoking `Set-PoshPrompt -Theme`:

```PowerShell
Import-Module Get-ChildItemColor

$Env:GIT_SSH = $null
Import-Module -Name posh-git
Import-Module -Name posh-sshell
Import-Module -Name posh-with

Import-Module -Name oh-my-posh

$modulePath = Resolve-Path "$PSScriptRoot/PsExtensions.psm1"
Import-Module $modulePath -Force

Set-PoshPrompt -Theme agnoster

Set-PSReadLineOption -Colors @{
    Parameter = 'DarkMagenta'
    Operator = 'Magenta'
    String = 'Green'
}

Import-Module -Name ZLocation
```

**Comment by JanDeDobbeleer** [comment]
I'll check, maybe posh-with has something to do with it.

**Comment by Descalon** [comment]
Your guess as it being one of the other modules is correct! It was `Get-ChildItemColor`:
![image](https://user-images.githubusercontent.com/1098500/117130354-3a55b480-ada0-11eb-8db3-b8c618a5116f.png)

**Comment by Descalon** [comment]
I'll take this issue up with the maintainer for that module! Thanks for the help, though!

**Comment by rollingmoai** [comment]
@JanDeDobbeleer In my case, a newline keeps on getting created until the prompt is filled up.

Here you can notice that the newline is not rendered on the end:
![image](https://user-images.githubusercontent.com/75471378/137626343-bf4797fb-c808-463a-9ead-0f298241c8ff.png)

My `$PROFILE` only contains this:
```powershell
Invoke-Expression (oh-my-posh --init --shell pwsh --config "themes\iterm2.omp.json")
```

**Comment by JanDeDobbeleer** [comment]
@itsmeboy0 I'll check that theme. There's zero logic that can explain it popping up sometimes and sometimes not in oh-my-posh.

**Comment by JanDeDobbeleer** [comment]
@itsmeboy0 I figured it out. It's because the prompt is 2 lines. We tell zsh to redraw the prompt and it seems to not understand we're only 1 line long now. I'll validate the implementation.

**Comment by JanDeDobbeleer** [comment]
@itsmeboy0 found it! Its because of `"vertical_offset": 1,` which pushes the prompt down 1 line. And at the end of the terminal, there's obviously no space which is why it's not an issue there. That took me WAY tool long to see 😓

**Comment by JanDeDobbeleer** [comment]
@itsmeboy0 https://github.com/JanDeDobbeleer/oh-my-posh/pull/1074

**Comment by rollingmoai** [comment]
Great. Removing that has worked, thanks
