### ISSUE TITLE
Add an option for conditional coloring

### ISSUE THREAD

**Issue by hbinkle** [JanDeDobbeleer/oh-my-posh#705]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I'm using oh-my-posh for showing the kubectl context in my powershell.
My theme shows the current k8s namespace (fix color) fine.
But it would be great to be able to define one or two more colors applied to it when a regex matches on the text (namespace).
This way you would be able to "highlight" special k8s namespace.

I can also imagine that such a feature could also be used for other texts like special paths etc...

### Environment

- Oh my Posh version: 3.147
- Theme: custom
- Operating System: windows10
- Shell: powershell
- Terminal: windows terminal

**Comment by JanDeDobbeleer** [comment]
@hbinkle we actually have that for foreground and background, it's called [foreground templates](https://ohmyposh.dev/docs/configure#foreground-templates) (or background templates). For kubectl we have [template properties](https://ohmyposh.dev/docs/kubectl#template-properties) you can use in combination with that.

**Comment by hbinkle** [comment]
great, exactly what I was searching for.
Thanks a lot!
