### ISSUE TITLE
Windows Defender says oh-my-posh contains virus and blocks it

### ISSUE THREAD

**Issue by tigerinus** [JanDeDobbeleer/oh-my-posh#708]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

![image](https://user-images.githubusercontent.com/7172560/117588945-ca736100-b0f4-11eb-91b2-32d7c8b9b03a.png)

![image](https://user-images.githubusercontent.com/7172560/117588950-d6f7b980-b0f4-11eb-85a9-132f2c64948b.png)

### Environment

- Oh my Posh version: 3.147.0
- Theme: customized theme (pasted at the bottom)
- Operating System: Windows 10
- Shell: Windows PowerShell

```
PS D:\xiaoh\Documents\WindowsPowerShell> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Terminal: Windows PowerShell (Standard Windows Console)

### Steps to Reproduce

1. Windows Defender got updated automatically.
2. Boot `powershell`

**Expected behavior:** `oh-my-posh` gets imported successfully

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/7172560/117588945-ca736100-b0f4-11eb-91b2-32d7c8b9b03a.png)

### Customized Theme

```json
{
    "final_space": true,
    "osc99": false,
    "console_title": false,
    "console_title_style": "",
    "console_title_template": "",
    "blocks": [
        {
            "type": "prompt",
            "alignment": "left",
            "horizontal_offset": 0,
            "vertical_offset": 0,
            "segments": [
                {
                    "type": "root",
                    "style": "plain",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#FFEE58",
                    "foreground_templates": null,
                    "background": "",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": {
                      "root_icon": ""
                    }
                },
                {
                    "type": "python",
                    "style": "diamond",
                    "invert_powerline": false,
                    "foreground": "#ffffff",
                    "foreground_templates": null,
                    "background": "#5fafd7",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "<#5fafd7,#5858ff></>",
                    "properties": {
                        "prefix": " "
                    }
                },
                {
                    "type": "path",
                    "style": "diamond",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#efefef",
                    "foreground_templates": null,
                    "background": "#5858ff",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "<#5858ff,transparent></>",
                    "properties": {
                        "folder_separator_icon": "  ",
                        "home_icon": "🏠",
                        "folder_icon": "…",
                        "style": "mixed"
                    }
                },
                {
                    "type": "exit",
                    "style": "powerline",
                    "powerline_symbol": "",
                    "invert_powerline": false,
                    "foreground": "#ffffff",
                    "foreground_templates": null,
                    "background": "#800000",
                    "background_templates": null,
                    "leading_diamond": "",
                    "trailing_diamond": "",
                    "properties": {
                        "prefix": " "
                    }
                }
            ]
        }
    ]
}
```

**Comment by lnu** [comment]
like this one:https://github.com/JanDeDobbeleer/oh-my-posh/issues/218
@JanDeDobbeleer already submitted the binary for review. Any status?

PS: Sophos endpoint here(corporate laptop) and neverd had any warning.

**Comment by JanDeDobbeleer** [comment]
@tigerinus @lnu no, they closed that without notice. I'll see if I can reach out directly. The only way to bypass that today (doesn't happen everywhere) is to exclude it from Defender.

**Comment by silverqx** [comment]
I can confirm this, for me, it has started a few days before.

How did you solve it? I have tried to add `C:\Program Files\WindowsPowerShell\Modules\oh-my-posh\3.147.0\oh-my-posh.psm1` file and `C:\Program Files\WindowsPowerShell\Modules\oh-my-posh` folder to the Defender's exclusion file/folder, but it did not help.
For now, I have added `powershell.exe` as an exclusion process, but this is not a good solution.

**Comment by lnu** [comment]
@JanDeDobbeleer did you use this [url ](https://www.microsoft.com/en-us/wdsi/filesubmission/)to submit the exe for approval?

**Comment by JanDeDobbeleer** [comment]
@lnu correct

**Comment by lnu** [comment]
![](https://media.giphy.com/media/l2JecFbmZJMJmILmg/giphy.gif)

**Comment by JanDeDobbeleer** [comment]
@silverqx @tigerinus I submitted another request, additionally it seems related to [this](https://github.com/PowerShell/PowerShell/issues/15396) issue.

**Comment by tigerinus** [comment]
> @silverqx @tigerinus I submitted another request, additionally it seems related to [this](https://github.com/PowerShell/PowerShell/issues/15396) issue.

Sounds like it's nothing to do with omp. It's happening to profile.ps1 in general. If that's the case, you can close this issue. I will watch the other issue instead.

**Comment by silverqx** [comment]
Yea, it looks like there are many false positives, in that particular issue the reporter describes that command like this `[Reflection.Assembly]::LoadFrom($assemblyPath)` causes false positive, in the `oh-my-posh` project following line causes the false positive:
```
Invoke-Expression (& $poshCommand --init --shell=pwsh --config="$config")
```

I was thinking about trying to change this call, simply try to use another syntax 🤔, I didn't try it, don't have much time.

Still have `powershell.exe` in the exclusion list 🙃 @JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
I'll leave this open to keep track of it myself.

**Comment by JanDeDobbeleer** [comment]
As per the analysis:

> Analyst comments:
 The warning you experienced indicates that the application had not established reputation with the Microsoft Defender SmartScreen Application Reputation feature at that time. We can confirm that the application "posh-windows-amd64-3.exe" (sha256 – “ec350d7b6b8c5553a419425a98a0fa8a5d7d5a2f51b08743c421204168bdb14f”) has since established reputation and attempting to download or run the application should no longer show any warnings. Please note, however, that the submitted files are not signed using a valid digital certificate. Unsigned files will have to establish reputation each time a new version is released. Application Reputation warnings are meant to indicate when applications do not have known positive reputation. This doesn’t mean that the application is malicious, only that it is “unknown.” Users can still proceed to download and run the application. If establishing reputation immediately is critical, you may want to consider investing in an EV Authenticode certificate. A valid EV Authenticode certificate can immediately establish reputation with SmartScreen reputation services even if no prior reputation exists. In order to be considered a valid EV certificate, the certificate must be issued by a Certificate Authority that is authorized by the Microsoft Trusted Root Certificate Program and recognized as an Extended Validation issuer.

I'll see if code signing is an option. Haven't looked at this in 10 years 😅

EDIT: the cert is at least €299/year. So unless OSS becomes sustainable, that's not going to happen.

**Comment by parithon** [comment]
Perhaps [sigstore ](https://security.googleblog.com/2021/03/introducing-sigstore-easy-code-signing.html) can be helpful in this effort someday.

> The mission of sigstore is to make it easy for developers to sign releases and for users to verify them. You can think of it like Let’s Encrypt for Code Signing.

**Comment by vexx32** [comment]
If this code is actually the problem:
```
Invoke-Expression (& $poshCommand --init --shell=pwsh --config="$config")
```

I would recommend trying to just drop the `Invoke-Expression` -- far as I can tell, that is entirely an unnecessary part of the command.

**Comment by silverqx** [comment]
I tried something like this now:
```
& $poshCommand --init --shell=pwsh --config="$config" | Invoke-Expression
```

It works, but afterwards I removed `powershell.exe` from defender exclusion list and even original line is not detected false positive anymore.

**Comment by JanDeDobbeleer** [comment]
@silverqx so this is working when invoked like that?

**Comment by JanDeDobbeleer** [comment]
@vexx32 that statement is incorrect as it actually outputs Powershell code which needs to be interpreted. Otherwise you get that string value.

**Comment by silverqx** [comment]
Defender doesn't detect it as positive anymore. @JanDeDobbeleer

**Comment by vexx32** [comment]
> @vexx32 that statement is incorrect as it actually outputs Powershell code which needs to be interpreted. Otherwise you get that string value.

Fair enough! In that case you might want to manually construct a `[scriptblock]` from the output and invoke it rather than using Invoke-Expression... but yeah, it might be some code that is output from that which is what Defender's really objecting to. Hard to say.

**Comment by JanDeDobbeleer** [comment]
@tigerinus @silverqx the latest version swaps every occurrence of `Invoke-Expression` with the piped version. Curious to see if that would impact something.

**Comment by silverqx** [comment]
The pipe version should work the same as is described in docs.

**Comment by JanDeDobbeleer** [comment]
If suppose for now with the adjusted init scripts and docs we can close this for the time being?

**Comment by silverqx** [comment]
Defender doesn't detect it, so the issue has been solved.

**Comment by DominicCronin** [comment]
I've just installed oh-my-posh using: 

winget install JanDeDobbeleer.OhMyPosh

When I invoke:  

oh-my-posh --init --shell pwsh --config myconfig.json " | invoke-expression 

it fails to run, and I see that McAfee has quarantined the exe.

**Comment by silverqx** [comment]
It should be reported to McAfee, when something calls ` xyz | Invoke-Expression` it does not mean that it is malicious, I'm pretty sure that there is nothing malicious.

**Comment by DominicCronin** [comment]
It's not complaining about Invoke-Expression as far as I can see. It's the oh-my-posh exe that gets quarantined.

**Comment by Jkudjo** [comment]
it 2022 and Issue still lingers

**Comment by JanDeDobbeleer** [comment]
@Jkudjo thanks for reminding me what year it is. One would indeed forget with everything which is going on in the world.

**Comment by anaskhan28** [comment]
![Uploading Screenshot_20230129_094307.png…]()

I am unable to install oh-my-posh on windows after excluding the folder too

**Comment by anaskhan28** [comment]
I am unable to install oh-my-posh on windows after excluding the folder too

**Comment by JanDeDobbeleer** [comment]
@anaskhan28 I don't understand what you mean by that. Can you explain in a bit more detail?

**Comment by anaskhan28** [comment]
after downloading oh-my-posh I ran it but it is not working so I thought it is happening because of windows defender then I exclude the path of oh-my-posh and runs it again still it's not working.. any idea why

**Comment by JanDeDobbeleer** [comment]
@anaskhan28 can you share the exact steps you're taking when saying "making it run"? Might be good to join the [Discord](https://discord.gg/n7E3DkXssv) to get a conversation going.
