### ISSUE TITLE
Theme seems off on latest Windows Terminal with Ubuntu WSL

### ISSUE THREAD

**Issue by squaricdot** [JanDeDobbeleer/oh-my-posh#709]
### Prerequisites

- [V] I have read and understand the `CONTRIBUTING` guide
- [V] I looked for duplicate issues before submitting this one

### Description

Weird space/Interaction between segments for executiontime segment

### Environment

- Oh my Posh version:
- Theme: jandedobbeleer (  22d3f4a  )
- Operating System: Windows 10 - WSL - Ubuntu 20.04.2 LTS
- Shell: zsh 5.8
- Terminal: Windows terminal 1.7.1033.0

### Steps to Reproduce

Install Ubuntu 20 WSL
Install Nerd Font, Configure Windows Terminal
Install ohmyposh, Install themes

**Expected behavior:** https://ohmyposh.dev/docs/themes

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/4513505/117821342-c453c080-b26b-11eb-865c-ae18fec71699.png)

With removed executiontime segment:

![image](https://user-images.githubusercontent.com/4513505/117821404-d5043680-b26b-11eb-8a31-de4a02298032.png)

**Comment by JanDeDobbeleer** [comment]
That's a bug in Windows terminal. More context [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext).
