### ISSUE TITLE
is possible use a unix-like path in current dir?

### ISSUE THREAD

**Issue by alanlivio** [JanDeDobbeleer/oh-my-posh#711]
Is possible configure the oh-my-posh to show a unix-like path in current dir?

Today:
`PS C:\Users\alan\github> `

What I would like:
`PS /Users/alan/github>`

**Comment by JanDeDobbeleer** [comment]
@alanlivio no, but I can definitely offer that if you want. The only question I have is how you'd show the drive?

**Comment by alanlivio** [comment]
Hi @JanDeDobbeleer .

> The only question I have is how you'd show the drive?
Only because it is more unix-like. But is not a requirement.

**Comment by JanDeDobbeleer** [comment]
@alanlivio if I do this, the drive is important. We can't simply ignore that part as in theory you can have `C:\Users\alan\github` and `F:\Users\alan\github` on the same machine meaning you need to be able to distinct between the two.

Maybe it's an idea to reformat it to `/c/Users/alan/github`

**Comment by JanDeDobbeleer** [comment]
@alanlivio I forgot about this, but you can have this with the following setting:

```json
{
    "type": "path",
    "style": "powerline",
    "powerline_symbol": "",
    "foreground": "#ffffff",
    "background": "#ff479c",
    "properties": {
        "folder_separator_icon": "/",
        "style": "full"
    }
}
```
