### ISSUE TITLE
Some themes are crashing in Bash

### ISSUE THREAD

**Issue by GuilhermeCaixetaCTW** [JanDeDobbeleer/oh-my-posh#717]
### Prerequisites

- [ x ] I have read and understand the `CONTRIBUTING` guide
- [ x ] I looked for duplicate issues before submitting this one

### Description
[Description of the bug or feature]

### Environment

- Oh my Posh version: v3
- Theme: jandedobbeleer
- Operating System: Windows 10 version 2004 build 19041.985
- Shell: bash
- Terminal: Windows Terminal

### Steps to Reproduce

1. Open the terminal using bash as your shell.
2. Write a long line.
Result: 
![pwsh_break_line_error](https://user-images.githubusercontent.com/83816065/118501499-b2b56180-b720-11eb-9434-1aca5df864a0.png)

**Expected behavior:** The line should be break as before I'd the theme installed.

**Actual behavior:** The theme crashes and the line is not break.

**Comment by lnu** [comment]
related to themes with right part and especially bash: instead of going to the next line, it overrides the right part and then starts back on the same line thus overidding everything.
With zsh, it goes to the next line (but overrides the right part of the theme).

**Comment by GuilhermeCaixetaCTW** [comment]
Hi @lnu , thank you for your answer.

It is a bit strange to read a text in this format, though I'll try to use the szh as shell instead bash. 

Other point is I notice some odd behaviors. 

- One is when you clear the text, the format doesn't come back as it was. They keep some parts of the previous text in the shell making confuse to read and write or even clearing all the text left behind a clear shell. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/83816065/118503060-30c63800-b722-11eb-9a6e-bfd13c35b8d8.gif)

- The another one is when I use the jonnychips theme, in the terminal path as shown it: "User/<batery-percentage>/bash/ INVALID CONFIG PATH".
![bash_break_line_error](https://user-images.githubusercontent.com/83816065/118500965-2a36c100-b720-11eb-95ad-c46e09c48d73.png)

**Comment by JanDeDobbeleer** [comment]
@GuilhermeCaixetaCTW is your bash shell up-to-date? I haven't seen this before but I'll check.

**Comment by JanDeDobbeleer** [comment]
@GuilhermeCaixetaCTW I can reproduce this. Never typed something this long tbh 😆 This is an issue with some parts of the prompt not being escaped properly which is why bash can't tell the length of the prompt. Let's see if we can find something that's off. @lnu on zsh prompt is actually different, it is a separate prompt, unlike bash and pwsh.
