### ISSUE TITLE
refactor: disambiguate property constants across segments

### ISSUE THREAD

**Issue by tillig** [JanDeDobbeleer/oh-my-posh#72]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When creating a new segment configuration options are specified as constants, like this for the "Exit" segment:

```go
const (
	//DisplayExitCode shows or hides the error code
	DisplayExitCode Property = "display_exit_code"
	//AlwaysEnabled decides whether or not to always display the exitcode info
	AlwaysEnabled Property = "always_enabled"
	//ErrorColor specify a different foreground color for the error text when using always_show = true
	ErrorColor Property = "error_color"
)
```

The challenge is that since all the segments are in the same package, the constants defined here (`AlwaysEnabled`) which _appear_ to be per-segment actually _aren't_. If I wanted a property for a different segment to have an `always_enabled` configuration option I'd have to either:

- Name it something different, like `MySegmentAlwaysEnabled`; or
- Use the constant defined by a different segment, which feels sort of odd.

Maybe that first option is fine, but it seems weird that _some_ of the segments would need a prefix for their constants but there wouldn't be a convention across all the segments.

I'm not sure what the best solution to this is. Since Go doesn't have a notion of file-scoped variables or constant structs, I'd guess the options are:

- Don't do anything, just fix it with name prefixes going forward.
- Refactor all the segments to prefix their associated constants with the segment name (or some similar convention).
- Put all the configuration constants in a single file. This would make it harder to see what each segment uses, but it'd also enable easier standardization of configuration properties across segments. You wouldn't get `always_enabled` vs `enable_always` or something because everyone would be using the same constant for the same intent.
- Put each segment in a different Go package. This seems like it'd be more work but it might be nice to isolate the code and tests for an individual segment.

I didn't know what the preference here was so I figured I'd open an issue and ask. I'd be happy to PR an update if it sounds like some refactoring needs to be done. And if not, I'm glad I asked. 😄

Aside: Thanks for your patience and help with the issues and PRs I'm throwing your way. I'm pretty excited about this new OMP version and it's helping me bring up my Go skills.

**Comment by JanDeDobbeleer** [comment]
For these I actually have properties set in `properties.go`. I already encountered this, so imho the best thing to do is to add it there once there's a proper case to reuse it cross segments, but still add them to each of the segment's docs when they're not used everywhere automatically (some are, via `engine.go`)

**Comment by tillig** [comment]
OK, cool. I noticed the `node` module has a `display_version` setting and I was going to look at a `dotnet` CLI segment that'd act in a similar fashion, so `display_version` might be a candidate here. I figured I'd ask what the situation was before doing the wrong thing. Thanks!
