### ISSUE TITLE
In powershell git directories prompt slow to load after commands

### ISSUE THREAD

**Issue by cmdkev** [JanDeDobbeleer/oh-my-posh#723]
### Prerequisites

- [✓] I have read and understand the `CONTRIBUTING` guide
- [✓] I looked for duplicate issues before submitting this one

### Description

Changing directories in a git directory is much slower than in non git directories as a result of the posh-git module. The prompt takes significantly longer to reappear. I've seen similar behavior reported for WSL2 shells but not for powershell (#505). Is this the intended behavior as a result of being in a git repository?

### Environment

- Oh my Posh version: 3.151.0
- Theme: Paradox and hotstick.minimal tested
- Operating System: OS Build 21382.1 (Windows Insider Dev Channel)
- Shell: Powershell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Go to any directory that is a git repository and changing directories has significantly more load time as reported by the `Write-PoshDebug`.

**Expected behavior:** [What you expected to happen]
![image](https://user-images.githubusercontent.com/19618964/118996406-e3caa780-b955-11eb-9245-b4662a83ed14.png)

**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/19618964/118996334-d1506e00-b955-11eb-9b9f-e3390587244e.png)

**Comment by JanDeDobbeleer** [comment]
@cmdkev in this case that's `git status` being slow for that repository. Which usually implies binaries or a very large repo. You can disable status with `"display_status": false` in your [custom](https://ohmyposh.dev/docs/pwsh#override-the-theme-settings) theme.

**Comment by lnu** [comment]
@JanDeDobbeleer it means lots of people will have to modify their theme. I guess most people expects the status to be displayed(maybe I'm wrong?).

**Comment by JanDeDobbeleer** [comment]
@lnu in all honesty, I was sick of all the "it's slow in my repo and starship is faster" comments/remarks. These are true, and that's because starship disables this by default as well. I know it "breaks" existing prompts, but that's the tradeoff I was willing to make here.

**Comment by lnu** [comment]
totally understand it. Starship is pretty "raw" by default and shows nothing(but I'm fast right ^^).

**Comment by cmdkev** [comment]
Sorry about adding to that deluge of feedback, but I was confused as to why it needs to run git status upon changing a directory instead of using some cached view of the status.

**Comment by pitgrap** [comment]
Hi, I ended up here, because I used oh-my-posh v2 and it worked fine with my large git repo. Now I updated to v3 and it got slow (~3-5s). 
I know, I can go back to v2, but I just want to understand what change cause the bad timings between these 2 releases.

**Comment by JanDeDobbeleer** [comment]
Which version are you on @pitgrap ? Because I just made that change. Are you sure it's the git segment? You can make use of `write-poshdebug` to see the timings per segment.

Know that there's also the [posh-git](https://ohmyposh.dev/docs/poshgit) segment which leverages the posh-git functionality under the hood. That will in theory result in the same behavior as V2 (which also used that).

**Comment by pitgrap** [comment]
I'm using the following versions:

```
Version              Name   
-------              ----     
3.151.0              oh-my-posh 
1.0.0                posh-git   
```

```
❯ Write-PoshDebug

Here are the timings of segments in your prompt:

ConsoleTitle(false) -   0 ms -
root(false)    -   0 ms -
session(true)  -   0 ms -  xxx 
path(true)     -   0 ms -  C:  dev  cms 
git(true)      - 1368 ms -  xxx ≢  +2 
python(false)  -   1 ms -
exit(true)     -   0 ms -  1337 
text(true)     -   0 ms - ❯
```

Now I updated to:
```
Version              Name   
-------              ----     
3.153.1              oh-my-posh 
1.0.0                posh-git   
```


```
 Write-PoshDebug

Here are the timings of segments in your prompt:

ConsoleTitle(false) -   0 ms -
root(false)    -   0 ms -
session(true)  -   0 ms -  xxx 
path(true)     -   0 ms -  C:  dev  cms 
git(true)      - 164 ms -  xxx 
python(false)  -   1 ms -
exit(true)     -   0 ms -  1337 
text(true)     -   0 ms - ❯
```

Ok, that's much better. Thank you.

**Comment by JanDeDobbeleer** [comment]
@pitgrap to give a better understanding of the issue at hand, git status takes a LONG time for that repo causing it to be slow. The latest release disables fetching the status by default. We might need to figure out how to cache (which is what posh-git does in a way), but I feat that can also introduce other side-effects.

**Comment by pitgrap** [comment]
@JanDeDobbeleer Thank you so much. I understand the problem totally. 
I used "cmder" before I switched to your awesome tool. "cmder" has the same "slowness" issue and I had to disable the "git status" check manually in the code. As long as I can see the branch name and I do not have to change code of my terminal tool, I'm happy with it.

**Comment by cpmcgrath** [comment]
Hi - I understand the change and get the reasoning - I've noticed the slowness caused by it recently too.
But it really needs to be documented - I spent an hour trying to figure out why it went away installing various versions trying to get it back.
I don't think it needs to be anything complex, just something like:

> Git Status has been removed from themes by default. If you wish to keep this feature, either:
> * Stay on version 3.151.0  (NOTE: This may cause performance issues)
> * add "display_status": true to your custom theme (NOTE: This may cause performance issues)
> * Use the Posh-Git segment in your custom theme (NOTE: Requires Posh-git installed, powershell only)

**Comment by JanDeDobbeleer** [comment]
@cpmcgrath would you look for this in the git segment docs?

**Comment by cpmcgrath** [comment]
I think that would be a good start - I was thinking on the github homepage as most people don't customise the prompt - they just use the standard templates. With that said, looking for a change related to git, I don't think it's a big leap to expect people to end up at that page pretty quickly. Yeah, I think that's the best place for it.
