### ISSUE TITLE
Git branch displayed 2 times and Python environment missing

### ISSUE THREAD

**Issue by PapyPev** [JanDeDobbeleer/oh-my-posh#731]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Following an upgrade from oh-my-posh 2 to oh-my-posh-3, the theme application seems to have two issues:
1. The conda environment of my user is not displayed by default (the `base` environment)
2. When I move to a git directory, the branch name is displayed as a prefix to the prompt and in the prompt
3. If I activate a virtual environment venv, it is also displayed as a prefix

### Environment

- Oh my Posh version: v3
- Theme: aliens
- Operating System: Microsoft Windows 10 Pro - 10.0.19042 Build 19042
- Shell: Powershell
- Terminal: Windows Terminal + VSCode

### Steps to Reproduce

1. Follow-up of the documentation for the update
2. Set a theme
```
PS > Set-PoshPrompt -Theme aliens
```
3. Export theme into PS profile
```
PS > Export-PoshTheme -FilePath ~/.oh-my-posh.omp.json
```
4. Get the PS profile
```
PS > $PROFILE
C:\Users\<username>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```
5. Edit the profile file :
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme  ~/.oh-my-posh.omp.json
```
6. Restart computer and reload Powershell
7. Move to a Python Git repository with virtualenv

![image](https://user-images.githubusercontent.com/8548854/119097193-bc86df80-ba14-11eb-918f-eae91813780c.png)

**Expected behavior:**

Is it possible :
- to have only once the git branch in the prompt?
- to have only once the Python environment in the prompt ?
- to have the conda `base` environment displayed by default ?
- not to have the error on the Python environment in the prompt ?

**Actual behavior:** 

Currently this is not possible :)

**Comment by lnu** [comment]
maybe related to this for Python:
https://github.com/JanDeDobbeleer/oh-my-posh/issues/662
https://github.com/JanDeDobbeleer/oh-my-posh/issues/374

And the git branch you're seeing is rendered outside omp: https://github.com/JanDeDobbeleer/oh-my-posh/issues/601
check if you don't have multiple config at different levels with `$PROFILE | Get-Member -Type NoteProperty`:
![image](https://user-images.githubusercontent.com/1829553/119101444-48026f80-ba19-11eb-8da0-26809fdf90fd.png)

**Comment by PapyPev** [comment]
@lnu Hello,


#662 -> it doesn't look like it, or maybe I'm wrong
#374 -> Maybe and it seems to correlate with your next question

> check if you don't have multiple config at different levels with $PROFILE | Get-Member -Type NoteProperty:

![image](https://user-images.githubusercontent.com/8548854/119101916-c8c16b80-ba19-11eb-8ba2-ea4ec9870706.png)

Content of the files

![image](https://user-images.githubusercontent.com/8548854/119102536-6cab1700-ba1a-11eb-897d-0cdcc5dad36a.png)

**Comment by lnu** [comment]
So if you put everything in profile.ps1, does it solve the posh-git issue?
Can you show us the result of `get-module`?

**Comment by PapyPev** [comment]
Of course ! Apparently this does not seem to solve the problem :

![image](https://user-images.githubusercontent.com/8548854/119104864-0c69a480-ba1d-11eb-8eba-e89ffc73657b.png)

However, I have the feeling that having two oh-my-posh installed is probably a problem

**Comment by lnu** [comment]
Could you update to the latest version of posh-git(1.0.0)? You can run an `update-module -verbose` and reopen the terminal

**Comment by PapyPev** [comment]
Update module logs :
![image](https://user-images.githubusercontent.com/8548854/119108357-67e96180-ba20-11eb-84b1-482caa7b454d.png)

After Reload :
![image](https://user-images.githubusercontent.com/8548854/119108433-7a639b00-ba20-11eb-8b36-5689881a1a12.png)

It works ! Thank you !! You're amazing !
Issue Git branch displayed 2 times ✔️ **fixed**

But, the Python venv isn't :
![image](https://user-images.githubusercontent.com/8548854/119108744-d3cbca00-ba20-11eb-95c4-f7a9964be8c1.png)

Even in VSCode :
![image](https://user-images.githubusercontent.com/8548854/119108799-e0e8b900-ba20-11eb-8334-9e7536fd0164.png)

**Comment by lnu** [comment]
Must be something related to activate.ps1 like(#662). I tested in wsl and it works fine.
You can try to set `VIRTUAL_ENV_DISABLE_PROMPT=1` and see if it works for you.
It's something out of omp.

**Comment by JanDeDobbeleer** [comment]
@PapyPev yes, @lnu is right, this is depending upon what's in your `activate.ps1`. See [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/662#issuecomment-822049922) for context.

**Comment by PapyPev** [comment]
Thank you @JanDeDobbeleer and @lnu 
Very well, I understand that the loading of the venv environment is dependent on the activation command `activate` or `Activate.ps1`.

However, a small issue seem to persist (is this an issue ?):
- The current Python version of conda is not displayed immediately, while by default the `base` environment of conda is loaded. 

![image](https://user-images.githubusercontent.com/8548854/119138770-882a1800-ba42-11eb-8a22-64fd22cec9fe.png)

**Comment by Kin-Zhang** [comment]
![image](https://user-images.githubusercontent.com/35365764/119140678-099b9d80-ba77-11eb-8b37-a88f1c2e84ce.png)
Do we have to set something to let the env name at head?
@JanDeDobbeleer

**Comment by JanDeDobbeleer** [comment]
@Kin-Zhang you need to add the [segment](https://ohmyposh.dev/docs/python) in you config for it to show, yes.

**Comment by JanDeDobbeleer** [comment]
@PapyPev this is normal, right? CD'ing into a folder with Python files will display the default env name (taken from the environment variables) and as soon as you active, it displays the base one again (that's what's as a value in the environment variables). Exciting the folder with Python files then hides the [segment](https://ohmyposh.dev/docs/python) altogether.

**Comment by Kin-Zhang** [comment]
> @Kin-Zhang you need to add the [segment](https://ohmyposh.dev/docs/python) in you config for it to show, yes.

![image](https://user-images.githubusercontent.com/35365764/119224946-7d02e500-bb33-11eb-9cfa-338d8a698262.png)

Thanks for your replying, I tried this to add in setting.json and also the theme.json
But it still no head of env name. I tried to find a solution on this page but it became 404: [https://ohmyposh.dev/docs/installation#3-replace-your-existing-prompt](https://ohmyposh.dev/docs/installation#3-replace-your-existing-prompt)
Did I do wrong things or it shouldn't add to setting.json but other setting files?
Sorry for these simple questions since I'm quite fresh on this thing.

**Comment by JanDeDobbeleer** [comment]
@Kin-Zhang I'll walk you through it. When we say settings, we mean the oh-my-posh settings. The themes are actually pre-packaged settings files, so if you're using the Powershell module and `Set-PoshPrompt -Theme xxx`, you're currently a [prepared config](https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/themes).

You need to export that one (the one you like) to a new local config, so you can extend it. Using Powershell that's `Export-PoshTheme` which has the ability to copy the theme to your clipboard (default), or specify a path to store the config in, for example `Export-PoshTheme -FilePath ~/.mytheme.omp.json`.

Supposing we do the latter, open the `~/.mytheme.omp.json` file and add this segment in the block you like (read the [concept](https://ohmyposh.dev/docs/#concept) page for reference). Once you're done editing, you can alter your `$PROFILE` and set your custom theme using `Set-PoshPrompt -Theme ~/.mytheme.omp.json`.

**Comment by Kin-Zhang** [comment]
> @Kin-Zhang I'll walk you through it. When we say settings, we mean the oh-my-posh settings. The themes are actually pre-packaged settings files, so if you're using the Powershell module and `Set-PoshPrompt -Theme xxx`, you're currently a [prepared config](https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/themes).
> 
> You need to export that one (the one you like) to a new local config, so you can extend it. Using Powershell that's `Export-PoshTheme` which has the ability to copy the theme to your clipboard (default), or specify a path to store the config in, for example `Export-PoshTheme -FilePath ~/.mytheme.omp.json`.
> 
> Supposing we do the latter, open the `~/.mytheme.omp.json` file and add this segment in the block you like (read the [concept](https://ohmyposh.dev/docs/#concept) page for reference). Once you're done editing, you can alter your `$PROFILE` and set your custom theme using `Set-PoshPrompt -Theme ~/.mytheme.omp.json`.

THANKS!!!!! Thank you very much! here I'm!! One more thing to bother you:
![image](https://user-images.githubusercontent.com/35365764/119225729-25b34380-bb38-11eb-87f8-ddb7fefbe4b4.png)
Since it's a little weird if I went into some folders....
![image](https://user-images.githubusercontent.com/35365764/119225799-a40fe580-bb38-11eb-8590-9e93cc1deb95.png)

Or like this picture show, the right arrow first, and then ~ and then folder name, finally env name. Here is the picture I have oh my zsh in ubuntu: the env name will appear at first:
![FlameShot 2021-03-22-2003](https://user-images.githubusercontent.com/35365764/119225855-e89b8100-bb38-11eb-9e09-e7cc66245128.png)

Important: thank you for your detailed answer which really helps me a lot

**Comment by JanDeDobbeleer** [comment]
@Kin-Zhang in that case, move the `python` segment before the `text` segment. They are rendered based on their order in the config so you can move them where yo'd like to see them. You can always share the config here and I'll gladly adjust it.

**Comment by Kin-Zhang** [comment]
> @Kin-Zhang in that case, move the `python` segment before the `text` segment. They are rendered based on their order in the config so you can move them where yo'd like to see them. You can always share the config here and I'll gladly adjust it.

Oh! Thanks! You are so kind since now I know how simple my question is. 😂
Thank you very much, I set the theme I want now:
![image](https://user-images.githubusercontent.com/35365764/119246443-31445000-bbb4-11eb-8704-347c0b1560bc.png)

Thanks again for your detailed reply!❤️🌹

**Comment by PapyPev** [comment]
> @PapyPev this is normal, right? CD'ing into a folder with Python files will display the default env name (taken from the environment variables) and as soon as you active, it displays the base one again (that's what's as a value in the environment variables). Exciting the folder with Python files then hides the [segment](https://ohmyposh.dev/docs/python) altogether.

Technically, the conda environment is always loaded. Indeed, if you move to a Python project directory, yes the `base` environment is displayed, but it should be displayed no matter what directory it is in because it is loaded by default.

In the following example I just load my Powershell session, and display the current Python environment:

![image](https://user-images.githubusercontent.com/8548854/119474061-11e02b00-bd4c-11eb-9878-31f21a2c91b4.png)

I think we can also understand it in @Kin-Zhang 's screenshot previously between his `base` environment loaded by default and `carla` from the project

**Comment by JanDeDobbeleer** [comment]
@PapyPev that's because the default `display_mode` is `files` and you're looking for `context`. That way you'll always see the env if it's present. See the [Python](https://ohmyposh.dev/docs/python) segment for more info.

**Comment by PapyPev** [comment]
> @PapyPev that's because the default `display_mode` is `files` and you're looking for `context`. That way you'll always see the env if it's present. See the [Python](https://ohmyposh.dev/docs/python) segment for more info.

Excellent! I hadn't seen this option, perfect, thank you very much!!!
