### ISSUE TITLE
Battery info not displaying when unplugged

### ISSUE THREAD

**Issue by justin-vogt** [JanDeDobbeleer/oh-my-posh#737]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When I unplug my laptop, the battery segment indicates an error state.
When I run this powershell command locally I get a valid reponse:

`(Get-WmiObject win32_battery).estimatedChargeRemaining`

### Environment

- Oh my Posh version: 3
- Theme: Custom
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Windows Terminal

### Steps to Reproduce

1. Unplug laptop from powersource
2. Have battery the following battery segment in your theme

```
{
          "type": "battery",
          "style": "plain",
          "foreground": "#193549",
          "background": "#2f2f2f",
          "properties": {
              "battery_icon": "",
              "discharging_icon": "\uE231 ",
              "charging_icon": "\uE234 ",
              "charged_icon": "\uE22F ",
              "color_background": true,
              "charged_color": "#4caf50",
              "charging_color": "#40c4ff",
              "discharging_color": "#ff5722",
              "prefix": "<#4caf50,transparent>\uE0B6</> ",
              "postfix": "\u003c#193549\u003e%\u003c/\u003e\u003c#FFFFFF\u003e \u003c/\u003e",
              "display_charging": true,
              "display_error": true
            }
        },

```        
3. Execute command in shell

**Expected behavior:** [What you expected to happen]
I expect to see battery level information displayed.
I expect to see that the battery is not currently charging.

**Actual behavior:** [What actually happened]
Error
`[{ChargeRate:Unknown value received}]% `

**Comment by lnu** [comment]
Works fine here with your config. But it can happen that sometimes you receive a wrong value and get the message(I had it once when testing then working fine). Is it all the time?

I received this error while testing(not charging status) in wsl:
https://github.com/distatus/battery/pull/16

Issue with distatus/battery

![image](https://user-images.githubusercontent.com/1829553/119474758-ced28780-bd4c-11eb-930a-801f9712feb9.png)
![image](https://user-images.githubusercontent.com/1829553/119475013-03464380-bd4d-11eb-985b-127d4e69c15c.png)
![image](https://user-images.githubusercontent.com/1829553/119475300-528c7400-bd4d-11eb-8f16-ca302fb8cd4d.png)


For me it happens only in wsl. Could you paste the complete output of `(Get-WmiObject win32_battery)` when it fails?

**Comment by justin-vogt** [comment]
Here is the results of (Get-WmiObject win32_battery) when it fails on my machine. Also the failure message I receive is the following: {ChargeRate:Unknown value received}

`
__GENUS                     : 2
__CLASS                     : Win32_Battery
__SUPERCLASS                : CIM_Battery
__DYNASTY                   : CIM_ManagedSystemElement
__RELPATH                   : Win32_Battery.DeviceID="09068 2020/10/13Hewlett-PackardPrimary"
__PROPERTY_COUNT            : 33
__DERIVATION                : {CIM_Battery, CIM_LogicalDevice, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                    : LT-JUV-T-US
__NAMESPACE                 : root\cimv2
__PATH                      : \\LT-JUV-T-US\root\cimv2:Win32_Battery.DeviceID="09068 2020/10/13Hewlett-PackardPrimary"
Availability                : 3
BatteryRechargeTime         :
BatteryStatus               : 1
Caption                     : Internal Battery
Chemistry                   : 2
ConfigManagerErrorCode      :
ConfigManagerUserConfig     :
CreationClassName           : Win32_Battery
Description                 : Internal Battery
DesignCapacity              :
DesignVoltage               : 8476
DeviceID                    : 09068 2020/10/13Hewlett-PackardPrimary
ErrorCleared                :
ErrorDescription            :
EstimatedChargeRemaining    : 100
EstimatedRunTime            : 71582788
ExpectedBatteryLife         :
ExpectedLife                :
FullChargeCapacity          :
InstallDate                 :
LastErrorCode               :
MaxRechargeTime             :
Name                        : Primary
PNPDeviceID                 :
PowerManagementCapabilities : {1}
PowerManagementSupported    : False
SmartBatteryVersion         :
Status                      : OK
StatusInfo                  :
SystemCreationClassName     : Win32_ComputerSystem
SystemName                  : LT-JUV-T-US
TimeOnBattery               :
TimeToFullCharge            :
PSComputerName              : LT-JUV-T-US`

**Comment by justin-vogt** [comment]
I do have Docker with Linux Subsystem running. 
I just shut down Docker completely and tried again to determine if that made a difference.
I still see the same experience.

**Comment by lnu** [comment]
And you confirm you get the error message all the time when laptop is unplugged?

**Comment by justin-vogt** [comment]
Yes, that is correct. As soon as I plug in, I get battery percentage status.

**Comment by JanDeDobbeleer** [comment]
@justin-vogt FYI, the output of that function isn't going to help as we are using go to define the battery status. In this case something get's reported by the OS that [distatus/battery](https://github.com/distatus/battery/blob/master/battery_windows.go#L99) can't handle. @lnu I would opt to simply fall back to discharging in this context, thoughts?

**Comment by lnu** [comment]
You can check the ouput of [distatus ](https://github.com/distatus/battery)using a command line tool based on the go package:
`go get -u github.com/distatus/battery/cmd/battery`

**Comment by JanDeDobbeleer** [comment]
@lnu yes, but that's already the parsed info, right. So we can't see the actual value being retrieved.

**Comment by justin-vogt** [comment]
I'm sorry, I provided that information because @lnu request it.
I haven't developed in Go before.

I installed Go
I ran the command `go get -u github.com/distatus/battery/cmd/battery`
Then I ran the command `battery`

Then my companies malicious software prevention system kicked in :)
"Suspicious executable detected"

I'm trying to help, sorry guys.

**Comment by JanDeDobbeleer** [comment]
@justin-vogt I didn't mean to sound like a dick but seems I did, sorry for that. These things are tricky as the way we retrieve context isn't as straightforward as one might think. Especially Windows, the win32 API isn't as elegant as we might like (or consistent 😅).

**Comment by lnu** [comment]
do you get the same behaviour as here:
![image](https://user-images.githubusercontent.com/1829553/119602251-0d1e8400-bdeb-11eb-89a7-ef75babc4651.png)


It's strange but I never experienced this before and it's the third time I see it since yesterday. My case is the one described in the bug.
@JanDeDobbeleer  you see the error with the 'Not charging status'

**Comment by justin-vogt** [comment]
Close. I'm currently unplugged and I see the following:

![image](https://user-images.githubusercontent.com/84424169/119602456-d3308c00-bdb0-11eb-918c-af30fb69b629.png)

**Comment by lnu** [comment]
set `display_error` to `false` or comment the segment in your config.
Sorry.

**Comment by justin-vogt** [comment]
Right, I can do that but then I get no battery information at all. I expected that whether I'm plugged in or not, I would have an indicator that shows me my battery level. Is that not possible?

If it only displays battery information when plugged in, I will likely just remove this segment. To me it would be most useful when I'm not plugged in so I can see when my battery is getting low.

Imagine running a development related presentation and performing a code/cli demo... having that battery information could be helpful if it's getting low. That's what I was thinking this would do.

Here's what I see when I set the display_error to false

![image](https://user-images.githubusercontent.com/84424169/119603142-3bcc3880-bdb2-11eb-970d-338347569737.png)

**Comment by lnu** [comment]
I understand completely your point. But it's out of our hands since we rely on https://github.com/distatus/battery to get the value.
You fall into that case:
https://github.com/distatus/battery/blob/7b23e7bb9e9100751c20bdbf1bb600cefbb43fcd/battery_windows.go#L91

If you feel comfortable you can clone distatus/battery and debug it to check what happens(with vs code).

**Comment by JanDeDobbeleer** [comment]
@lnu I can create an executable that prints the output so we can see if we make a minor change to the code and deploy as such. It's already using a fork anyways for another issue that simply doesn't get merged but is fixed on our end.

**Comment by lnu** [comment]
Yep missed the fork. Since it's a fork, you could also merge the fix for the 'Not charging' status I'm having now and then since a few days: https://github.com/distatus/battery/pull/16

**Comment by JanDeDobbeleer** [comment]
@lnu I already made that change to the repo :-) And that fix is currently in main. I'l try to build a small utility this evening.

**Comment by lnu** [comment]
It works fine now for the NotCharging status now. But there are strange thins going on between wsl results and windows results of the battery.

**Comment by JanDeDobbeleer** [comment]
@justin-vogt please run the following, it will help us troubleshoot the actual error 
[battery.exe.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6556496/battery.exe.zip)

**Comment by justin-vogt** [comment]
I attempted to run the executable several ways but I always get the same block:

![image](https://user-images.githubusercontent.com/84424169/119895474-71cd0200-bf03-11eb-8704-cecc53373924.png)

**Comment by JanDeDobbeleer** [comment]
@justin-vogt well now. Probably because it uses the win32 API. Argh.

**Comment by cgriebel** [comment]
I see the conversation on this has dried up but I'm also experiencing this issue. Is there any way I can help here?
![image](https://user-images.githubusercontent.com/25422735/141488307-54f7609a-d609-4144-9ad2-b11fd423663a.png)

Oh My Posh: 6.2.3
OS: Windows 10 Enterprise - 10.0.19043 Build 19043
Terminal: Windows Terminal 1.11.2921.0
Shell: PowerShell Core 7.2.0

**Comment by JanDeDobbeleer** [comment]
@cgriebel there's an executable that will print the info we get back [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/737#issuecomment-849906353). If you would be so kind to try to run that one so we can pinpoint the exact issue.

**Comment by cgriebel** [comment]
@JanDeDobbeleer 
```
batteryStatus: {PowerState:2 Capacity:53881 Voltage:12633 Rate:-2147483648}
Error getting info for BAT0: {ChargeRate:Unknown value received}
```

**Comment by Khaos66** [comment]
I did some digging here https://github.com/distatus/battery/issues/25
Because I have the same issue on my notebook and wanted to fix it.

Looks like Windows returns a `BATTERY_UNKNOWN_RATE`. So the `battery` lib adds an error to the response of `battery.GetAll()` [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/c67148670c8b796f60ad49f8e5707ab47cb2895d/src/environment.go#L385)

The problem is [this if](https://github.com/JanDeDobbeleer/oh-my-posh/blob/c67148670c8b796f60ad49f8e5707ab47cb2895d/src/environment.go#L408) it aborts if any error is returned by `battery`. Even if this error is minor, like in this case, when the `charge rate` wasn't returned by Windows.

Here is a screenshot of my debug session with the relevant variables and execution point
![image](https://user-images.githubusercontent.com/4013009/145638294-0777fbab-9675-4014-a367-cfcfb3f67512.png)

@JanDeDobbeleer I think this could be improved to ignore errors about the charing rate

Also isn't #1238 a duplicate?

**Comment by JanDeDobbeleer** [comment]
@Khaos66 if we can distinguish that from other errors, yes please let's add that.

**Comment by Khaos66** [comment]
@justin-vogt Please install the lastest version  (v6.29.2). It should fix this issue.
It did for me ;)

**Comment by JanDeDobbeleer** [comment]
Closing this due to no new reports and looking at the changes we did to prevent this.
