### ISSUE TITLE
Escaped characters in path are replaced with whatever they translate to, but only in git bash, windows-terminal

### ISSUE THREAD

**Issue by mkvlrn-cm42** [JanDeDobbeleer/oh-my-posh#738]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The clickable path in the terminal (for example `D:\dev`) works fine on a powershell core instance, but it breaks in git bash:

![image](https://user-images.githubusercontent.com/6718750/119409833-4b6a5500-bcbe-11eb-84d0-ed3478ba275f.png)
![image](https://user-images.githubusercontent.com/6718750/119409871-57561700-bcbe-11eb-8c8a-d29270134ade.png)

This path, for example, `D:\dev` shows normally on powershell, but the "\d" part of it becomes "Mon May 24", the current day.
It also does not happen when git bash is used inside vscode, only in windows-terminal. Happens with some other themes as well, but `pixelrobots` is the one I use.

### Environment

- Oh my Posh version:  3.156.0
- Theme: pixelrobots
- Operating System: Windows 10 64-bit 20H2 Build 19042.985
- Shell: Git Bash (git version 2.31.1.windows.1)
- Terminal: Windows Terminal 1.7.210419001-release1.7

### Steps to Reproduce

1. Install oh-my-posh with scoop 
2. Configure git bash by adding `eval "$(oh-my-posh --init --shell bash --config 'D:\\scoop\\apps\\oh-my-posh\\current\\themes\\pixelrobots.omp.json')"` to ~/.bashrc (D:\scoop is my scoop home)
3. Navigate to D:\dev

**Expected behavior:** Clickable path in terminal should work "unescaped" (?), like it works with powershell core

**Actual behavior:** Clickable path in terminal replaces some escaped characters (such as "\d" with current day), producing incorrect file paths

**Comment by lnu** [comment]
The issue is only with bash.... how did you configure your path to be "d:\" in git bash?

Same for any segments:
```
{
      "type":"text",
      "style":"plain",
      "properties": {
            "text": "\\d"
      }
}
```

https://tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html
