### ISSUE TITLE
Display branch instead of hash

### ISSUE THREAD

**Issue by devhl-labs** [JanDeDobbeleer/oh-my-posh#747]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The slim template displays my branch name, but many other templates, such as powerlevel10k_rainbow display a hash. How can I change templates to display the branch name and not this hash value? I'm on a clean version of master at the moment, so shouldn't be anything about the branch.

### Environment

- Oh my Posh version: 3.157.3
- Theme: powerlevel10k_rainbow
- Operating System: Windows 10
- Shell: Ubuntu
- Terminal: Windows Terminal

**Comment by lnu** [comment]
All themes display the same branch name. If you call `Get-PoshThemes` you'll see the output of all themes(all should display the same branch name).

**Comment by devhl-labs** [comment]
![Screenshot 2021-05-27 152353](https://user-images.githubusercontent.com/29644329/119885566-ffa6ee00-beff-11eb-9dda-102a206c7071.png)
I must be missing something then.

**Comment by lnu** [comment]
On linux you can call
 `for file in ~/.poshthemes/*.omp.json; do echo "$file\n"; oh-my-posh --config $file --shell universal; echo "\n"; done;` 
to preview the themes(https://ohmyposh.dev/docs/linux)
You can also specify the path to your config file by add `--config CONFIGPATH` to your example.

**Comment by devhl-labs** [comment]
That's a great way to see what I like, but most of them show a hash. Only fish, honukai, lambda, negligle, powerlevel10k_classic, slimfat, sorin, and stelbent show the branch name. All the others show a hash.

**Comment by JanDeDobbeleer** [comment]
@devhl-labs can you show the output of `git status`?

**Comment by devhl-labs** [comment]
On branch -my branch-
nothing to commit, working tree clean

**Comment by JanDeDobbeleer** [comment]
@devhl-labs OK, we use `git --no-optional-locks -c core.quotepath=false -c color.status=false status -unormal --short --branch` can you me that exact output?

**Comment by devhl-labs** [comment]
It returns my branch name. It has a slash (/) in it, maybe that is breaking things?

**Comment by JanDeDobbeleer** [comment]
@devhl-labs if you copy paste me the exact output I can quickly add that to a test and let you know 😉

**Comment by devhl-labs** [comment]
name/workspace

**Comment by JanDeDobbeleer** [comment]
That's the issue, as it should start with `##`, can you update your git version? I fear this is going to be an old one.

**Comment by devhl-labs** [comment]
I started with that actually, but I needed to add a repo per git-scm.com/download. Thanks for the quick responses.

**Comment by JanDeDobbeleer** [comment]
@devhl-labs glad we got it resolved!

**Comment by Lewiscowles1986** [comment]
I'm hitting this too on linux. Here's the output of the command

```
## v1...origin/v1
?? .vscode/
?? null.d
```

**Comment by JanDeDobbeleer** [comment]
@Lewiscowles1986 can you check if you're up-to-date with git? As the status command outputs the correct info, but most likely `git branch --show-current` doesn't return anything for you (which means git is outdated, it's been supported as of git 2.22 (Q2 2019)). So, two options, either update git or enable the status as the status does parse when I add that to a test (see `display_status` [here](https://ohmyposh.dev/docs/git#status)).

**Comment by Lewiscowles1986** [comment]
yeah... That does work is the problem
![image](https://user-images.githubusercontent.com/2605791/120932275-0b0ecc00-c6ed-11eb-912c-f6d55e86fd8c.png)

This is a screenshot of `oh-my-zsh in zsh` which also shows the branch. That is why this is so weird to me that it's not working in oh-my-posh.
![Screenshot from 2021-06-06 17-33-32](https://user-images.githubusercontent.com/2605791/120932367-6214a100-c6ed-11eb-8b67-b86fed82e544.png)

**Comment by Lewiscowles1986** [comment]
This is so much more interesting than I thought... Linux `$PATH` was not consistent between the two shells.

`$ENV:PATH = "/home/linuxbrew/.linuxbrew/bin:$ENV:PATH"` in my `/.config/powershell/profile.ps1` handled this for me.

So basically if you get this issue, maybe your system is odd or non-obviously configured too, and your system git is old, and needs updating.

The reason this line works for me is that I am using homebrew for linux atop my Ubuntu install. This was 100% my issue, and I'm sorry I didn't click to that issue sooner. If you have two git's by another method, then you need to pre-pend the PATH as shown above with the path to your working git binary.

**Comment by devhl-labs** [comment]
I believe this issue is because you haven't told it what theme to use, or provided an invalid string. This is the path that works for me `C:\Users\devhl\scoop\apps\oh-my-posh\current\themes\paradox.omp.json` 

I went through this yesterday while following the windows installation instructions, and they could have been a tiny bit more clear. In the end to fix all my issues, I had to 
-uninstall all cli formatters
-install oh-my-posh
-set the above string in Windows:
  ```ps1
  code $PROFILE
  # append this line and save the file
  oh-my-posh --init --shell pwsh --config ~/scoop/apps/oh-my-posh/current/themes/paradox.omp.json | Invoke-Expression
  ```
-set the above string in WSL
  ```
  nano ~/.bashrc
  #append this line and save the file
  eval "$(oh-my-posh-wsl --init --shell bash --config /mnt/c/users/devhl/scoop/apps/oh-my-posh/current/themes/paradox.omp.json)"
  ``` 
-add `C:\Users\devhl\scoop\apps\oh-my-posh\current\bin` to my path variable
-install a nerd font. In my experience these fonts have four versions, I just install all four. Not sure if that is needed.
-set the font in windows terminal settings, vs code integrated terminal settings, and vanilla powershell.

This covers everything

**Comment by JanDeDobbeleer** [comment]
@devhl-labs what are you missing in the docs? They're definitely up for improvements as it's really challenging to get everything right and clear for everyone.

**Comment by devhl-labs** [comment]
My path variable was missing, so I had to add it manually.

![image](https://user-images.githubusercontent.com/29644329/120933659-14863d00-c6c9-11eb-9830-c5d583b45eee.png)
This image is confusing because the path to the theme is wrong.  Also I wasn't sure what `. $PROFILE` was doing, but I see now.

![image](https://user-images.githubusercontent.com/29644329/120933777-9fffce00-c6c9-11eb-809f-7f16feaa11e4.png)
The theme's path is wrong.
