### ISSUE TITLE
Export-PoshTheme disregards the -FilePath parameter

### ISSUE THREAD

**Issue by skycommand** [JanDeDobbeleer/oh-my-posh#748]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

The `Export-PoshTheme` seems to have trouble understanding the relative path in the `-FilePath` parameter. Instead of resolving the relative path according to the current folder, it resolves the path according to the desktop!

### Environment

- **Oh my Posh version:** 3.157.3
- **Theme:** I tried `Powerline`, `Paradox` and `Slimfat`, but the problem is theme-independent
- **Operating System:** Windows 10 v21H1 x64
- **Shell:** Windows Shell version 10.0.19043.1023
- **Terminal:** PowerShell 7.1

### Steps to Reproduce

1. Launch PowerShell 7.1 via `pwsh.exe -noprofile`
2. Issue the following commands, one by one:

~~~PowerShell
Set-Location 'D:\Projects\AdminScripts\' #or another directory of your choosing
Import-Module -Name 'oh-my-posh' -MinimumVersion 3.0
Set-PoshPrompt Slim
Export-PoshTheme -FilePath '.\slim.json' -Format json
~~~

**Expected behavior:** `slim.json` must appear in `D:\Projects\AdminScripts`

**Actual behavior:** `slim.json` appears in `~` or (in one occasion) `~\Desktop` (Use a utility like Everything to locate it in real-time)

**Comment by lnu** [comment]
If you don't set the FilePath, the text is copied to the clipboard.  
From what I see, the FilePath works well with a fully qualified path but it has an issue with relative paths.

**Comment by JanDeDobbeleer** [comment]
@lnu this is going to be a fix like mapping `HOME`

**Comment by lnu** [comment]
I did this:
```
else {
    $FilePath = "$(pwd)\$FilePath"
}
```
after the 
```
 if ($FilePath.StartsWith('~')) {
     $FilePath = $FilePath.Replace('~', $HOME)
}
```

Final code:
```
    if ($FilePath -ne "") {
        if ($FilePath.StartsWith('~')) {
            $FilePath = $FilePath.Replace('~', $HOME)
        }
        else {
            $FilePath = "$(pwd)\$FilePath"
        }
        [IO.File]::WriteAllLines($FilePath, $configString)
    }
    else {
        Set-Clipboard $configString
        Write-Output "Theme copied to clipboard"
    }
```

It seems ok

**Comment by JanDeDobbeleer** [comment]
@lnu won't that fail when you add a full path?

**Comment by lnu** [comment]
Yep, we should add a check to see if the path is full with ‘IsPathRooted’(for example). Or use `GetFullPath`. I don’t remember if it will resolve \~.

**Comment by lnu** [comment]
```
 if ($FilePath -ne "") {
        if ([IO.Path]::IsPathRooted($FilePath) -eq $false) {
            if ($FilePath.StartsWith('~')) {
                $FilePath = $FilePath.Replace('~', $HOME)
            }
            else {
                $FilePath = "$(pwd)\$FilePath"
            }
        }
        [IO.File]::WriteAllLines($FilePath, $configString)
    }
    else {
        Set-Clipboard $configString
        Write-Output "Theme copied to clipboard"
    }
```
![image](https://user-images.githubusercontent.com/1829553/119928736-784b9000-bf7c-11eb-9d0d-b94025ca3d5a.png)

**Comment by JanDeDobbeleer** [comment]
@lnu I guess we can consider this closed now, right?

**Comment by lnu** [comment]
For me yes,  can you validate @skycommand ?

**Comment by skycommand** [comment]
@lnu and @JanDeDobbeleer 
Since you said that the problem has been fixed, I took the pain of testing it on both my machine and a clean virtual machine. In both tests, I installed Oh-my-posh fresh from the Internet. In both cases, version 3.158.4 got installed.

I am afraid I can say with certainty that **the bug persists**. On my virtual machine, `Export-PoshTheme` attempted to write the file into my Windows folder!

Actual machine's screenshot:
![Actual machine](https://user-images.githubusercontent.com/17097175/120064362-00b35900-c081-11eb-932d-a4df7182a980.png)

Virtual machine's screenshot:
![Virtual machine](https://user-images.githubusercontent.com/17097175/120064358-fdb86880-c080-11eb-9f81-a513d814eba8.png)

**Comment by JanDeDobbeleer** [comment]
@skycommand "you took the pain"? Really? That's how we're addressing people who took up the task the same day waiting on your feedback to see if it was also resolved on your end? 

I'll check later today, in the meanwhile, work on your attitude and gratitude.

**Comment by skycommand** [comment]
@JanDeDobbeleer It's an expression. "Took the pain" means "carried out a certain task". No actual pain is involved. Sorry, that's how English works.

**Comment by lnu** [comment]
Yes, There is a bug for powershell core reported about this(I found it on macos this morning). The fix is to pass $pwd as second parameter to GetFullPath.
https://github.com/PowerShell/PowerShell/issues/10278

**Comment by skycommand** [comment]
Oh, yeah. PowerShell's run space cannot alter the PowerShell host process's current directory. There is a reason for that: In run space, the current directory is a PSDrive not an actual file system volume. Consider this:

```PowerShell
Set-Location HKLM:\Software
$PWD.ProviderPath
```

These paths are not even on the file system.
