### ISSUE TITLE
Vim integration

### ISSUE THREAD

**Issue by SunMar** [JanDeDobbeleer/oh-my-posh#756]
Hi,

This would be the same feature request as #475 but for Vim instead of Tmux ([like powerline](https://powerline.readthedocs.io/en/latest/usage/other.html#vim-statusline)). Vim allows you to customize your status bar and what I like about powerline is that my prompt, tmux and vim can all share the same theme.

Really happy that on the other hand oh-my-posh allows me to have the same across PowerShell and Bash/Zsh :)

**Comment by JanDeDobbeleer** [comment]
I guess it would need a single line prompt, right?

**Comment by JanDeDobbeleer** [comment]
@SunMar I'm closing this as adding it will be the same as TMUX (in theory, except the docs). I updated that title for both TMUX and VIM.
