### ISSUE TITLE
Line height is modified in Korean Powershell, Windows 10

### ISSUE THREAD

**Issue by comiluv** [JanDeDobbeleer/oh-my-posh#762]
### Prerequisites

- [V] I have read and understand the `CONTRIBUTING` guide
- [V] I looked for duplicate issues before submitting this one

### Description
Line height is increased after import-module oh-my-posh

### Environment

- Oh my Posh version: 3.158.4
- Theme: default
- Operating System: Windows 10
- Shell: Powershell 5.1.19041.906
- Terminal: Powershell.exe 5.1.19041.906
- Powershell Get-Host information:
```
Name             : ConsoleHost
Version          : 5.1.19041.906
InstanceId       : fa3b0dc2-785d-47ab-92c7-178d2dada7b7
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : ko-KR
CurrentUICulture : ko-KR
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```
-Powershell $OutputEncoding information:
```
IsSingleByte      : True
BodyName          : us-ascii
EncodingName      : US-ASCII
HeaderName        : us-ascii
WebName           : us-ascii
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 20127
```
#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

1. Install oh-my-posh ```install-module oh-my-posh -force -scope currentuser```
2. Import oh-my-posh ```import-module oh-my-posh```
3. Ls to list files

**Expected behavior:**
Line height is not changed

**Actual behavior:**
Line height is changed

**Screenshots**
Before importing oh-my-posh, showing default line height using ls command
<img width="734" alt="before-ohmyposh" src="https://user-images.githubusercontent.com/19642705/120069268-f2386200-c0bf-11eb-9cf6-d3ea136c884a.png">

After importing oh-my-posh, line height is increased shown by using ls command
<img width="734" alt="after-ohmyposh" src="https://user-images.githubusercontent.com/19642705/120069284-1300b780-c0c0-11eb-953b-285aaa671bec.png">

**Comment by JanDeDobbeleer** [comment]
@comiluv we set the console mode to print colors, not specifically specifying a line height. So, if that's a side effect, we can't really help it. Do you get the same on Windows Terminal, or only in the old console? The reason I ask is that it's very much discouraged to use that one, it's simply not up to par, never has been (also for V2 btw).

**Comment by comiluv** [comment]
@JanDeDobbeleer I get the same result also in Windows Terminal, which uses old powershell.exe I did some more testing, installed Powershell 7 (the latest one in Windows Store) and it solved the issue. Also using pwsh.exe (Powershell 7) in Windows Terminal solves this issue. Thanks for the reply!
