### ISSUE TITLE
Posh-Git should be in RequiredModules

### ISSUE THREAD

**Issue by JustinGrote** [JanDeDobbeleer/oh-my-posh#77]
Since the module will not load without Posh-Git, it should be in the required modules of the manifest so that install-module (and install-psresource) automatically install the dependency.

Alternatively, remove posh-git from the main psm1 dependency and only do a check if git related segments are used (preferred)

**Comment by JustinGrote** [comment]
Disregard, somehow I ended up with v2 and I have no idea why.

**Comment by JanDeDobbeleer** [comment]
No worries!
