### ISSUE TITLE
Git status indication not showing up correctly in Debian using WSL2 in Windows 10

### ISSUE THREAD

**Issue by MarcoKramer** [JanDeDobbeleer/oh-my-posh#775]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

The Git status indication is not showing up as it should when running `oh-my-posh` on Debian using WSL2 in Windows 10 (in Linux in general?):
![image](https://user-images.githubusercontent.com/5435084/120601696-93217700-c44a-11eb-9134-229e1b81b043.png)

When using not using `oh-my-posh` and just `posh-git` it does look fine:
![image](https://user-images.githubusercontent.com/5435084/120601876-bea46180-c44a-11eb-98c8-5a593cf089e0.png)

In Windows 10 PowerShell itself it also works fine:
![image](https://user-images.githubusercontent.com/5435084/120603243-18595b80-c44c-11eb-8481-7374a850302e.png)

### Environment

- Oh my Posh version: 3.160.1
- Theme: Avit (any theme)
- Operating System: Windows 10, using Debian in WSL2
- Shell: Bash
- Terminal: Windows Terminal
  
#### Optional

- posh-git version: 1.0.0
- git version: 2.20.1

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

The Git status indication is the same in both environments.

**Actual behavior:** [What actually happened]

The Git status indication is not the same in both environments.

**Comment by JanDeDobbeleer** [comment]
@MarcoKramer can you update git in WSL? We've seen reports in the past where that version was outdated, resulting in falling back to the hash.

**Comment by MarcoKramer** [comment]
I thought I already was on the latest version, but yeah... it's Debian. 😁 I managed to update it using a backport (version 2.29.2 now) and now it's working as it should. Thanks a lot! 👍
