### ISSUE TITLE
Allow using folder contents to select segments

### ISSUE THREAD

**Issue by WolfspiritM** [JanDeDobbeleer/oh-my-posh#779]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

I'd like to use specific segments only if the folder I am in contains a specific file or folder.
Similar to how the Node segment only displays if there is a package.json found, I want to run a custom command segment in every directory that has a package.json file (or a node_modules folder) while not running it anywhere else.

Some Segments have that "hardcoded" but I think it would be better to make these configurable similar to include_folders and exclude_folders for every segment.

### Environment

- Oh my Posh version: 3.160.1
- Theme: Own
- Operating System: Windows 10
- Shell: pwsh
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
@WolfspiritM when #1847 lands, you can do the following:

```json
{
  "type": "text",
  "style": "plain",
  "foreground": "#ffffff",
  "properties": {
    "template": "{{ if or (glob \"package.json\") (glob \"node_modules\") }}OK{{ end }}"
  }
}
```

As long as the template text turn out empty, it doesn't show the segment.
