### ISSUE TITLE
No background color

### ISSUE THREAD

**Issue by PhyX-Meow** [JanDeDobbeleer/oh-my-posh#791]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh My Posh version: 3.162.2 install form scoop
- Theme: jandedobbeleer
- Operating System: Windows 10.0.21390.1
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal 1.8.1521.0

#### Optional

- posh-git version: 1.0.0
- git version: 2.32.0.windows.1

### Steps to Reproduce

Just open the shell.

**Expected behavior:** 

Background color of the theme is displayed normally.

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/17513581/121147279-4f2bd900-c873-11eb-99f0-5894c5283b31.png)

**Comment by ShrykeWindgrace** [comment]
Other themes are impacted, too.

**Comment by Ash258** [comment]
After update to 3.162.2 the color are no longer handled correctly. Reproducible on two ubuntu systems and even windows

![image](https://user-images.githubusercontent.com/13260377/121154484-4cb38a00-c847-11eb-9939-c901b5a783cb.png)

![image](https://user-images.githubusercontent.com/13260377/121155961-918bf080-c848-11eb-9279-4254a91dbf64.png)

Theme: https://github.com/Ash258/Scoop-Ash258/blob/main/support/oh-my-posh/Ash258.json
Os1: Ubuntu 21.04
Os2: Ubuntu 20.04
Os3: Wndows 21H1

For both zsh, powershell in Ubuntu

**Comment by JanDeDobbeleer** [comment]
@Ash258 @ShrykeWindgrace @PhyX-Meow fix is [building](https://github.com/JanDeDobbeleer/oh-my-posh/actions/runs/917942501). I relied on the tests alone, seems like upgrading a dependency ruined the colouring.

**Comment by Ash258** [comment]
Can confirm it is OK now

![image](https://user-images.githubusercontent.com/13260377/121170724-e41fd980-c855-11eb-817e-8a451750d2a0.png)

**Comment by JanDeDobbeleer** [comment]
@Ash258 seems like GitHub is broken though so can't get everything out

**Comment by JanDeDobbeleer** [comment]
I'm pushing a new version as soon as [this](https://www.githubstatus.com) is resolved. In the meantime I removed the pwsh module and the faulty homebrew version. Scoop is resolved and that build succeeded, Winget is still impacted.

**Comment by ShrykeWindgrace** [comment]
@JanDeDobbeleer thanks for the prompt fix!

**Comment by JanDeDobbeleer** [comment]
Fully fixed in https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v3.162.3
