### ISSUE TITLE
Is there a time zone set for this library

### ISSUE THREAD

**Issue by romanholidaypancakes** [JanDeDobbeleer/oh-my-posh#794]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]
After using ohmyposh, I used the signature service and the timestamp verification failed. Is there any operation to modify the time zone/time?
Once I no longer use `Import-Module oh-my-posh` everything is ok.
### Environment

- Oh My Posh version: 3.160.1
- Theme: 
- Operating System: windows10
- Shell: pwsh
- Terminal: pwsh

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

I can't reproduce it with a simple example

**Expected behavior:** [What you expected to happen]
Do not modify the time zone and time
**Actual behavior:** [What actually happened]
It seems that the time zone and time have been modified

**Comment by JanDeDobbeleer** [comment]
@notes365 we do not do that no. Do you have a reproducible scenario I can use to validate this?

**Comment by romanholidaypancakes** [comment]
It’s the character set problem,`oh-my-posh` changes the terminal character set to utf8, our company signature tool does not work properly in this character set. I solved this problem by changing to our native language character set.

**Comment by JanDeDobbeleer** [comment]
@notes365 that would've been my only guess indeed. Can you update the charset of your company tool? UTF8 makes sense in this day and age (although I know and understand the challenges at company level...).

**Comment by romanholidaypancakes** [comment]
In fact, this is difficult. I have been implementing the `all in utf8` strategy in my department. The new project is very smooth, but the old project is difficult to advance.

**Comment by JanDeDobbeleer** [comment]
@notes365 building a wrapper for the old tool could be a good idea as an intermediate solution.
