### ISSUE TITLE
Unwanted space at second line in `powerlevel10k_rainbow` theme

### ISSUE THREAD

**Issue by Mo-Gul** [JanDeDobbeleer/oh-my-posh#798]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When I load the `powerlevel10k_rainbow` theme there is an unwanted space at the beginning of the second line (see screenshot). I tried the trick explained <https://ohmyposh.dev/docs/faq/#windows-terminal-unexpected-space-between-segmentstext> but that didn't help.

![screenshot of powershell7 with `powerlevel10k_rainbow` theme of `oh-my-posh`](https://user-images.githubusercontent.com/17992976/121485298-59171e80-c9d0-11eb-8076-cea83f98c0a1.png)

### Environment

- Oh My Posh version: v3.162.4
- Theme: powerlevel10k_rainbow
- Operating System: Win10
- Shell: Powershell 7

**Comment by lnu** [comment]
The issue is here:
![image](https://user-images.githubusercontent.com/1829553/121660876-ec6d5400-caa3-11eb-8c4f-e3dc3943b545.png)
![image](https://user-images.githubusercontent.com/1829553/121663240-80d8b600-caa6-11eb-954a-36ea4e5bbfc5.png)


I push the fix asap

**Comment by lnu** [comment]
@Mo-Gul can you confirm it's what you were expecting?

**Comment by Mo-Gul** [comment]
Yes, that is exactly what I expected. Thank you very much for the quick fix.
