### ISSUE TITLE
Theme ys adding a pair of brackets

### ISSUE THREAD

**Issue by FeliksLv01** [JanDeDobbeleer/oh-my-posh#799]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

When having python files in the folder and using theme ys，I found it adding a pair of brackets in the end of output for commands.  Then I found [issue#600](https://github.com/JanDeDobbeleer/oh-my-posh/issues/600), and it solved my problem. But is there any other way to solve this problem，if so, can you update the ys file?  

### Environment

- Oh My Posh version: 3.162.4
- Theme: ys
- Operating System: win10
- Shell: powershell 7
- Terminal: windows terminal

![brackets](https://user-images.githubusercontent.com/49094905/121523488-d9696e00-ca28-11eb-8fe8-d9091f25d827.png)

**Comment by JanDeDobbeleer** [comment]
Interesting, so you have a Python segment (and file) but no version is reported?

**Comment by FeliksLv01** [comment]
Oh，I got it, that pair of brackets is used to show python version, but the default value of display_version is false, so i only saw a pair of brackets. 😂
