### ISSUE TITLE
Difficulties with icons in prompt

### ISSUE THREAD

**Issue by aaronsb** [JanDeDobbeleer/oh-my-posh#8]
Hi, I might be missing something fundimental, but it appears that the characters representing items on the prompt are incorrect-ish?

Here's an example:
![image](https://user-images.githubusercontent.com/2738471/93502896-36862800-f8cc-11ea-9bb9-b0c1f276c7b9.png)

If I edit the theme in vscode, only certain glyphs render correctly:

![image](https://user-images.githubusercontent.com/2738471/93503028-646b6c80-f8cc-11ea-9d6f-449ae574f452.png)

I'm wondering if there's a character encoding thing going on with the file maybe?

![image](https://user-images.githubusercontent.com/2738471/93503279-b14f4300-f8cc-11ea-86cd-26d9b25d011a.png)

**Comment by JanDeDobbeleer** [comment]
Hey @aaronsb, that most likely depends on the font being used. I used nerd fonts [Meslo LG M](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip) (top of my head).

**Comment by JanDeDobbeleer** [comment]
This shows another bug as well, I need to make the battery prompt for UNIX and Windows too 😅

**Comment by aaronsb** [comment]
I forgot about Meslo fonts. I've been using Cascadia Code (PL) for a while now. 

Time to enumerate /sys/class/power_supply/ ? ;)

**Comment by JanDeDobbeleer** [comment]
I'll update the README if you can confirm the right font resolves the issue. And I'll create a new issue for the battery indicator 👍🏻

**Comment by aaronsb** [comment]
Yes, loading Meslo fonts lets the character fallback. Cascadia Code + Meslo FTW!

![image](https://user-images.githubusercontent.com/2738471/93523508-fdf44780-f8e7-11ea-8ec1-ab7c09224fd0.png)

**Comment by JanDeDobbeleer** [comment]
So pretty ❤️
