### ISSUE TITLE
/tmp/XXX no such file error in termux in android

### ISSUE THREAD

**Issue by RichardLuo0** [JanDeDobbeleer/oh-my-posh#802]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I am trying to use it in termux which is a terminal emulator for android phone. Everything works fine except for a weird error says /tmp/XXX no such file before every instruction. I think it may relate to termux's different filesystem hierarchy because /tmp is not available for termux.

![500153200999_148338](https://user-images.githubusercontent.com/22096448/121710915-a0a2c500-cb0c-11eb-81ce-a15302b344d6.jpg)

### Environment

- Oh My Posh version: 3.162.4
- Theme: stelbent.minimal
- Operating System: android
- Shell: bash
- Terminal: termux

**Comment by JanDeDobbeleer** [comment]
Interesting. This is related to the way we treat command duration. We'll do a validation before assuming the file is there.

**Comment by lnu** [comment]
Interesting. @RichardLuo0 What's your goal in using omp in termux on android(just for my understanding)?

**Comment by lnu** [comment]
@JanDeDobbeleer For me, on macOS the duration is not working in bash. No error but no duration shown. Can you confirm?

**Comment by JanDeDobbeleer** [comment]
I've planned to check this weekend yes. It did work (and to my understanding we didn't change it).

**Comment by lnu** [comment]
Because this PS0='$(::OMP:: --millis > $TIMER_START)' is executed in a sub shell. No file is created for me.

=> bash 3.2.57 on the Mac...... PS0 works with 4.4
=> works fine after installing latest version(my bad)

**Comment by RichardLuo0** [comment]
> Interesting. @RichardLuo0 What's your goal in using omp in termux on android(just for my understanding)?

Just to make termux look better... Actually, I find there is an ARM version of omp, so I decided to try it and surprisingly it works well.
