### ISSUE TITLE
"display_version" and "display_mode" in python segment do not work

### ISSUE THREAD

**Issue by ruicx** [JanDeDobbeleer/oh-my-posh#804]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Following the [document](https://ohmyposh.dev/docs/python/), I set `display_version` to `false` and `display_mode` to `always`, but they seem not work.

### Environment

- Oh My Posh version: 3.162.5
- Theme: agnoster-brief (modified form agnoster)
- Operating System: Win10
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

1. Set the theme to `agnoster-brief`

**Expected behavior:** [What you expected to happen]

1. No python version shown
2. Conda environment  name shows, whatever a `.py` file exists

In brief, I hope it looks like this:

![image](https://user-images.githubusercontent.com/20857887/121805021-d9ad7780-cc7b-11eb-856e-5cb0b8ee572c.png)

**Actual behavior:** [What actually happened]

![image](https://user-images.githubusercontent.com/20857887/121804827-db2a7000-cc7a-11eb-9ccb-b96db02520ae.png)

---

My theme (agnoster-brief.omp.json)

``` json with comment
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffe9aa"
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#91ddff",
          "properties" : {
              "home_icon": "\uF7DB",
              "folder_icon": "\uF115",
              "folder_separator_icon": " \uE0B1 ",
              "style": "agnoster_short"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#95ffa4"
        },
        {
          "type": "python",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#906cff",
          "display_mode": "always",
          "display_default": "true",
          "display_virtual_env": "true",
          "display_version": "false",
          "properties": {
            "prefix": " \uE235 "
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#ffffff",
          "background": "#ff8080"
        }
      ]
    }
  ],
  "final_space": true
}
```

**Comment by JanDeDobbeleer** [comment]
@ruicx that's because you added those settings to the segment rather than the properties. Adjusting the `python` segment to contain those overrides in the `properties` makes it work as desired:

```json
{
  "type": "python",
  "style": "powerline",
  "powerline_symbol": "\uE0B0",
  "foreground": "#100e23",
  "background": "#906cff",
  "properties": {
    "prefix": " \uE235 ",
    "display_mode": "always",
    "display_default": true,
    "display_virtual_env": true,
    "display_version": false
  }
}
```

**Comment by ruicx** [comment]
> ``` json
> {
>   "type": "python",
>   "style": "powerline",
>   "powerline_symbol": "\uE0B0",
>   "foreground": "#100e23",
>   "background": "#906cff",
>   "properties": {
>     "prefix": " \uE235 ",
>     "display_mode": "always",
>     "display_default": true,
>     "display_virtual_env": true,
>     "display_version": false
>   }
> } 
> ```


Thanks a lot.

I move them to `properties`, and Conda env name fixed, but the python version is still shown.

![image](https://user-images.githubusercontent.com/20857887/121805732-feefb500-cc7e-11eb-963c-cdc4c816a128.png)

**Comment by JanDeDobbeleer** [comment]
@ruicx on my machine it only displays base with the exact same configuration. Unless the python version is part of the virtual env name, then it can off course still be displayed.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/2492783/121806303-89202500-cc4f-11eb-9bcf-4000d5ee2663.png">

The first time is with `"display_version": true`, the second run is as you have it here.

**Comment by ruicx** [comment]
I switched to Oh-My-Posh V3 from V2 earlier today, and in v2 only the prompt only shows `base`, and my env name doesn't contain a version number. Perhaps, there are some issues with my environment variables. Whatever, the version number is not critical. Thanks for your time.

![image](https://user-images.githubusercontent.com/20857887/121807593-5e51c300-cc87-11eb-90af-d1be2fe2a092.png)

**Comment by JanDeDobbeleer** [comment]
@ruicx are you certain you've set the right config?

**Comment by ruicx** [comment]
I accidentally replaced `false` with `"false"` on formatting the JSON file. Switching to the correct one, now, it works.
