### ISSUE TITLE
Colors changed when upgrading from V2 -> V3

### ISSUE THREAD

**Issue by boehs** [JanDeDobbeleer/oh-my-posh#808]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Before V2, my PowerShell paradox theme looked as follows: ![](https://e.reeee.ee/vlETD2.png). Now, after the upgrade, the colors have switched![](https://e.reeee.ee/dIhtqR.png). I prefer the old one. Is it something I screwed up on my end?

Regards, me.

### Environment

- Oh My Posh version: Latest (3.163)
- Theme: Paradox
- Operating System: Windows
- Shell: Powershell 7
- Terminal: Windows terminal preview.

**Comment by boehs** [comment]
I am honestly not convinced these are the same themes. CASTLE Is upercase in the top one, and the top one has the time on the right (not pictured). If anyone could point me to what I was using, would be much ❤️

**Comment by boehs** [comment]
I became aware I still have a window open with the old theme, here it is

![](https://e.reeee.ee/4zT2D4.png). I would assume it is possible to recover with some sort of command to get the current theme?

**Comment by lnu** [comment]
I don't know the color by heart but you can export the current paradox theme and replace the colors by the ones you want.
`Export-PoshTheme -FilePath ~\myparadox.omp.json -Format json`
=>https://github.com/JanDeDobbeleer/oh-my-posh2/blob/master/Themes/Paradox.psm1

You can also check all themes using `Get-PoshThemes` or https://ohmyposh.dev/docs/themes

you can get the current theme information of v2 with `$ThemeSettings`

**Comment by boehs** [comment]
> I don't know the color by heart but you can export the current paradox theme and replace the colors by the ones you want.
> `Export-PoshTheme -FilePath ~\myparadox.omp.json -Format json`
> =>https://github.com/JanDeDobbeleer/oh-my-posh2/blob/master/Themes/Paradox.psm1
> 
> You can also check all themes using `Get-PoshThemes` or https://ohmyposh.dev/docs/themes
> 
> you can get the current theme information of v2 with `$ThemeSettings`

How can I port a v2 theme to v3?

**Comment by boehs** [comment]
Did it manually, and made it a bit more my own. Cheers!
