### ISSUE TITLE
oh-my-posh.json missing from latest release

### ISSUE THREAD

**Issue by PromoFaux** [JanDeDobbeleer/oh-my-posh#811]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

json appears to be missing from latest release files, so unable to install via scoop (except by linking to specific version)

### Environment

- Oh My Posh version: N/A
- Theme:
- Operating System: Windows 10 LTSC
- Shell: Powershell
- Terminal: Powershell

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

1. Have Scoop Installed
2.  run `scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json`

**Expected behavior:** [What you expected to happen]

Oh-my-posh to install

**Actual behavior:** [What actually happened]

```
PS C:\Windows\system32> scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json
WARN  error: The remote server returned an error: (404) Not Found.
Couldn't find manifest for 'https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json'.
```

No Rush, just happened to be testing my dotfiles 🙂

**Comment by JanDeDobbeleer** [comment]
The release went wrong it seems. Need to check.

**Comment by JanDeDobbeleer** [comment]
I removed that release and I'm fixing the build.

**Comment by PromoFaux** [comment]
Great, thanks!
