### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by NeoFantom** [JanDeDobbeleer/oh-my-posh#814]
I'm not even sure if I'm using oh-my-posh v2 or v3. How to uninstall? respectively, for v2 and v3 (I uninstall because I want to reinstall from start)

**Comment by JanDeDobbeleer** [comment]
@NeoFantom how did you install is the first question? Probably the Powershell module, implying `Uninstall-Module oh-my-posh` should do the trick.

**Comment by ATGardner** [comment]
I am sure I am missing something, but `uninstall-module oh-my-posh` just doesn't work for me.
Whenever I try it, I end up with a blank and simple prompt. But opening a new PowerShell console shows me oh-my-posh again. I also see it when running `get-module` immediately after I try to uninstall it.
I tried with and without `-AllowPrerelease`, `-Force` and in Windows Terminal, standard PowerShell console, with and without Admin rights. The script remains after every attempt.

**Comment by ATGardner** [comment]
I ended up running

```
pwsh -NoProfile -Command "Uninstall-Module oh-my-posh"
```

several times, from admin command prompt (YMMV), each time it removed a different version. After I removed all versions, I also had to edit my `D:\Users\Noam\Documents\PowerShell\Microsoft.PowerShell_profile.ps1` file to remove all oh-my-posh related calls.

**Comment by RenegadeJr** [comment]
the only thing that worked for me was:
`winget uninstall oh-my-posh`

output:
`Found oh-my-posh [XP8K0HKJFRXGCK]
Starting package uninstall...
Successfully uninstalled`

**Comment by JanDeDobbeleer** [comment]
@RenegadeJr depends on the installation method/platform but on Windows it also displays in the installed programs list with the option to remove.
