### ISSUE TITLE
Vagrant -  "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE 

### ISSUE THREAD

**Issue by kennedyabitbol** [JanDeDobbeleer/oh-my-posh#815]
### Description

When launch vagrant up i got :
`C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/childprocess-4.0.0/lib/childprocess/windows/process_builder.rb:44:in encode!': "\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE (Encoding::UndefinedConversionError)`

This behavior is not happening when the terminal is not using a custom theme.

### Environment

- Oh My Posh version: last
- Theme: jandedobbeleer
- Operating System: win10 64x
- Shell: 7
- Terminal:
- Vagrant 2.2.16

**Comment by JanDeDobbeleer** [comment]
@kennedyabitbol chances are this has nothing to do with your theme, but the fact that we set the Terminal to UTF8. Given that the stack trace is from vagrant, and not oh-my-posh, that's the one who's having issues. You can set the terminal to whatever encoding after importing/invoking oh-my-posh, but we can't guarantee full compatibility in that case (although mostly it should work).

**Comment by floh96** [comment]
@kennedyabitbol this is a vagrant bug see https://github.com/hashicorp/vagrant/issues/11637 you need to set the correct encoding for vagrant [manually](https://github.com/hashicorp/vagrant/issues/11637#issuecomment-633622895).

**Comment by kennedyabitbol** [comment]
Hi, and thank you for your replies.
Fact is that it does not happen without oh my posh. Otherwise everything works fine, design, font and colors.

I gave up tunning my terminal, i will try later.

**Comment by JanDeDobbeleer** [comment]
@kennedyabitbol that makes sense as oh-my-posh sets your terminal to UTF-8 (we need to for it to work properly). As @lnu already stated, pwsh will be doing that anyways going forward, so tools need to comply (just like they already do on Unix/macOS without issues). What you can do is upvote that bug at [hashicorp/vagrant](https://github.com/hashicorp/vagrant/issues/11637) or fix it yourself based on the context in that ticket.

**Comment by kennedyabitbol** [comment]
The issue on vagrant is the right one, thanks for pointing me out to this one.
