### ISSUE TITLE
Invalid characters in the Windows 10 PT-BR Defrag application

### ISSUE THREAD

**Issue by RogerioCoimbra** [JanDeDobbeleer/oh-my-posh#816]
### Description

When I import the posh-git module and use the defrag application in Windows 10 in PT-BR, invalid characters appear.

![image](https://user-images.githubusercontent.com/1877482/122686693-fbad7980-d1e8-11eb-9e16-3244069f66ec.png)

![image](https://user-images.githubusercontent.com/1877482/122686807-96a65380-d1e9-11eb-8260-6b8d9e951cf5.png)

This happens only for newer versions:
![image](https://user-images.githubusercontent.com/1877482/122690624-0f64da00-d201-11eb-898c-63c0e88cefda.png)

This does not happen for example in version 2.0.412:
![image](https://user-images.githubusercontent.com/1877482/122690828-12ac9580-d202-11eb-92ad-5f60e2d836da.png)

### Environment

- Oh My Posh version: 3.164.0
- Theme: gmay (Happens with all themes)
- Operating System: Windows 10 (last update) (PT-BR)
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal Versão: 1.8.1521.0

#### Optional

- posh-git version: 1.0.0
- git version: git version 2.32.0.windows.1

### Steps to Reproduce

Install NerdFont
Install oh-my-posh lasta version;
Import Modules
Set Theme

[What you expected to happen]
That oh-my-posh works without invalid characters

[What actually happened]
In the old version(2.0.412) it works perfect.
In the new version(3.164.0) it works but with invalid characters in the Windows 10(PT-BR) Defrag application

**Comment by lnu** [comment]
Probably the same answer as here: https://github.com/JanDeDobbeleer/oh-my-posh/issues/815#issuecomment-864447892

Powershell is set to utf-8 by default by omp: https://github.com/JanDeDobbeleer/oh-my-posh/blob/2ab35b0eecf79200b97cfcecf87819ecc04e8f9e/src/init/omp.ps1#L3

And alos utf-8 is the default on powershell core btw.

**Comment by JanDeDobbeleer** [comment]
@RogerioCoimbra @lnu is right. It's the Defrag application that needs to be fixed to support UTF-8. It will be a problem going forward anyways. You can set Powershell to whatever encoding after importing oh-my-posh, but it can break a lot of other things for oh-my-posh (paths, cmd's,...).

**Comment by JanDeDobbeleer** [comment]
@RogerioCoimbra I suggest you create an issue at Defrag (if possible). We can't prevent this (and shouldn't need to).
