### ISSUE TITLE
32-bit exit codes and int type

### ISSUE THREAD

**Issue by cdonnellytx** [JanDeDobbeleer/oh-my-posh#819]
### Prerequisites

- [X] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

#812 changed the `dotnet.exe` Windows exit code `0x80008091` to `-2147450735`.  Unfortunately the dotnet prompt on 64-bit Windows now fails as the [`int`](https://golang.org/pkg/builtin/#int) type is apparently 64-bit in 64-bit Go.

Unfortunately I don't know what the best approach is here.  Because the exit code ultimately comes from [ProcessState.ExitCode()](https://golang.org/pkg/os/#ProcessState.ExitCode), which returns an `int`, it means the value will be different whether targeting a 32- or 64-bit architecture, and of course on a 32-bit architecture, `int(0x80008091)` returns an overflow error.

### Environment

- Oh My Posh version: 3.166.0
- Theme: (see [exitcodebug.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/6704606/exitcodebug.zip))
- Operating System: Microsoft Windows [Version 10.0.19042.1052] x64
- Shell: pwsh.exe 7.1.3 (x64), powershell.exe (5.1.19041.1023 - both x86 and x64)
- Terminal: conhost, Windows Terminal

### Steps to Reproduce

1. Unzip attachment to `C:\temp\exitcodebug` or other suitable path
2. In PowerShell, `cd C:\temp\exitcodebug`
3. Run
```powershell
path\to\posh-windows-386.exe -config theme.json
path\to\posh-windows-amd64.exe -config theme.json
```

**Expected behavior:** 

![both 386, amd64 show a warning symbol after the dotnet symbol](https://user-images.githubusercontent.com/183046/123158272-30ac0d00-d431-11eb-8373-b9db2f6210bf.png)

**Actual behavior:**
![386 is correct, but amd64 says 'Executing dotnet with [--version]'](https://user-images.githubusercontent.com/183046/123158391-56d1ad00-d431-11eb-894d-6fa2c91a8256.png)

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx we could go down the pragmatic route:

```diff
diff --git a/src/segment_dotnet.go b/src/segment_dotnet.go
index ac8d3891..96b8133f 100644
--- a/src/segment_dotnet.go
+++ b/src/segment_dotnet.go
@@ -1,5 +1,7 @@
 package main
 
+import "runtime"
+
 type dotnet struct {
 	language *language
 }
@@ -19,8 +21,12 @@ func (d *dotnet) string() string {
 	// Exit codes 145 and 0x80008091 are special indicators that dotnet
 	// ran, but the current project config settings specify
 	// use of an SDK that isn't installed.
+	exitCodeWindows := dotnetExitCodeWindows
+	if runtime.GOARCH == "amd64" {
+		exitCodeWindows = int(0x80008091)
+	}
 	exitCode := d.language.exitCode
-	if exitCode == dotnetExitCodeWindows || exitCode == dotnetExitCodeUnix {
+	if exitCode == exitCodeWindows || exitCode == dotnetExitCodeUnix {
 		return d.language.props.getString(UnsupportedDotnetVersionIcon, "\uf071 ")
 	}
 
diff --git a/src/segment_dotnet_test.go b/src/segment_dotnet_test.go
index e13140f6..837372e9 100644
--- a/src/segment_dotnet_test.go
+++ b/src/segment_dotnet_test.go
@@ -1,6 +1,7 @@
 package main
 
 import (
+	"runtime"
 	"testing"
 
 	"github.com/stretchr/testify/assert"
@@ -84,11 +85,15 @@ func TestDotnetVersionUnsupported(t *testing.T) {
 }
 
 func TestDotnetVersionUnsupportedWindows(t *testing.T) {
+	exitCode := dotnetExitCodeWindows
+	if runtime.GOARCH == "amd64" {
+		exitCode = int(0x80008091)
+	}
 	expected := "x"
 	args := &dotnetArgs{
 		enabled:         true,
 		displayVersion:  true,
-		exitCode:        dotnetExitCodeWindows,
+		exitCode:        exitCode,
 		unsupportedIcon: expected,
 	}
 	dotnet := bootStrapDotnetTest(args)
```

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx had to really only include these from being used on that architecture but seems to compile. That should "in theory" also fix the issue.

**Comment by cdonnellytx** [comment]
Just realized -- you might also want to check for `arm64` (either here or as part of #463).

**Comment by JanDeDobbeleer** [comment]
@cdonnellytx I'm doing that when go 1.17 lands which hopefully brings full windows ARM support
