### ISSUE TITLE
[Docs BUG] Installation of bash with Linux has wrong path.

### ISSUE THREAD

**Issue by tasty0tomato** [JanDeDobbeleer/oh-my-posh#823]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Installation of bash with Linux has wrong path.
![chrome_H7S77qPRpX](https://user-images.githubusercontent.com/48764449/123512862-6ca6d280-d6bc-11eb-9a54-804576988a16.png)

But the _theme json_ file was actually in ~/.poshthemes
![chrome_f7w6XLSY0b](https://user-images.githubusercontent.com/48764449/123512906-a546ac00-d6bc-11eb-94e9-2cb26a491f87.png)

Because it was not a huge bug, I decided to pull a request at first. But I found that the _bash_ part is not just in _install-linux.mdx_, but it belonged to a global file _install-shells.mdx_.

I do not know much about this document, so it will be danger for me to change a global file.

_**There might be some other bugs like this.**_

**Expected behavior:**

The picture ONE should be
```
eval "$(oh-my-posh --init --shell bash --config ~/.poshthemes/jandedobbeleer.omp.json)"
```

And also, I think the path of the downloaded themes should not change.

**Actual behavior:** [What actually happened]

Like picture ONE and TWO.

**Comment by JanDeDobbeleer** [comment]
That's not exactly accurate as the guide states this just above that section:

![image](https://user-images.githubusercontent.com/2492783/123517642-78859b00-d6a2-11eb-8112-0bb2f0d69471.jpeg)

**Comment by tasty0tomato** [comment]
So sorry not read that line...

**Comment by JanDeDobbeleer** [comment]
Don't worry, I wonder what I can do to avoid confusion though. That part received multiple iterations already. We could also add homebrew as an option.
