### ISSUE TITLE
Font characters in the prompts not rendering correctly on a fresh install

### ISSUE THREAD

**Issue by LoZeno** [JanDeDobbeleer/oh-my-posh#829]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

On a fresh install of oh-my-posh, both using the Powershell method and the scoop method, and on both Powershell and Powershell code, on any theme available many characters used by the themes are replaced by the "undefined character" glyph.

Here's an example of 'Get-PoshThemes' on Powershell, with Cascadia Mono as the font:
![image](https://user-images.githubusercontent.com/3267561/124249336-aee86d80-db1b-11eb-84df-4468aa8e4991.png)

Here's an example of 'Get-PoshThemes' on Powershell Core, with Fira Code as the font:
![image](https://user-images.githubusercontent.com/3267561/124249516-de977580-db1b-11eb-9f70-a4f82b9666d9.png)

### Environment

- Oh My Posh version: 3.166.3
- Theme: all of them
- Operating System: Windows 10
- Shell: Powershell, Powershell Core, CMD
- Terminal: Windows Terminal 1.8.1521.0

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

1. Install oh-my-posh
2. 'Get-PoshThemes'

**Expected behavior:**
The prompts should render all the characters and glyphs correctly

**Actual behavior:**
Many characters and glyphs are not rendered.

**Comment by JanDeDobbeleer** [comment]
@LoZeno that first font doesn't contain those characters as it isn't powerline patched. Nothing we can do about that, you need to either switch to Cascadia Code PL (which also doesn't have every glyph used by default, only themes with the `minimal` name work 100%) or move to a Nerd Font (which is the best solution as it's designed around the availability of glyphs for context).

**Comment by LoZeno** [comment]
@JanDeDobbeleer I got to the [Fonts](https://ohmyposh.dev/docs/fonts) page of the documentation only after submitting the issue, my bad.

**Comment by JanDeDobbeleer** [comment]
@LoZeno we're here to help!
