### ISSUE TITLE
Incorrect output of formatted git log if theme is set in PowerShell profile

### ISSUE THREAD

**Issue by Peter-76** [JanDeDobbeleer/oh-my-posh#838]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

Output git log in compact 'oneline' format (`git log --pretty=oneline -n 30`) does not produce the correct output if a Posh Theme is set in the PowerShell profile. The output is interrupted, showing a `:`. It looks like as if there  is something wrong with the calculation of the number of required output lines (behavior as when executing a git command which needs more than one page (e.g. `git log` without the `-n` switch), in this case the `:` is show in the last line of the terminal and output is continued after pressing enter).

### Environment

- Oh My Posh version: 3.166.3
- Theme: powerlevel10k_modern (same behavior with other themes)
- Operating System: Windows 10 Version 21H1 (OS Build 19043.1052)
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal Preview 1.9.1523.0
- posh-git version: 1.0.0
- git version: 2.32.0.windows.1

### Steps to Reproduce

1. Import oh-my-posh and set posh prompt in PowerShell profile
2. Open PowerShell in Windows Terminal (make sure terminal window can display more than 30 lines)
3. `cd` to git repository
4.  `git log --pretty=oneline -n 30`

**Expected behavior:**

This is how it should behave and how it behaves if the theme is not selected in the PowerShell profile (theme is set as first command):

![image](https://user-images.githubusercontent.com/33368620/124424256-07f81180-dd67-11eb-9cc3-6cf9db43cc84.png)

$PROFILE:
```
Import-Module posh-git
Import-Module oh-my-posh
```

**Actual behavior:**

This is the output if the theme is set in PowerShell profile:

![image](https://user-images.githubusercontent.com/33368620/124424162-da12cd00-dd66-11eb-8f82-816072058e6f.png)

$PROFILE:
```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme powerlevel10k_modern
```

**Comment by JanDeDobbeleer** [comment]
@Peter-76 can you make sure git is up-to-date and try again of not? We're not doing anything that should influence git's functionality. What happens when you type `-30` rather than `-n 30`?

**Comment by Peter-76** [comment]
I've the latest git version:
```
❯ git --version
git version 2.32.0.windows.1
```

Updated to latest oh-my-posh:

```
❯ Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     3.168.0               oh-my-posh                          {Get-PoshInfoForV2Users, Get-PoshThemes, Set-PoshPrompt, Get-ThemesLocation…}
Script     1.0.0                 posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranchName, Get-GitBranchStatusColor…}
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}
```

Commands with correct output (with theme set in $PROFILE):
```
git log --pretty=oneline --abbrev-commit -n 30
git log --pretty=oneline --abbrev-commit -30
git log --oneline -n 30
git log --oneline -30
```

Commands with incorrect output (with theme set in $PROFILE):
```
git log --pretty=oneline -n 30
git log --pretty=oneline -30
```

If theme is set manually (not in $PROFILE) the last 2 commands behave correct as well

**Comment by JanDeDobbeleer** [comment]
@Peter-76 I can't reproduce this on any platform. There's also 0 difference when it comes to importing this on a `$PROFILE` level vs in line. The only reason I can think off (but still, identical on both cases) is that we set the terminal to UTF8. So what we can try is adding `$env:LC_ALL='C.UTF-8'` to the start of your `$PROFILE` to set git to UTF8 as well.

**Comment by Peter-76** [comment]
`$env:LC_ALL='C.UTF-8'` does not help.
Strange thing, I'll try this on a different machine later.

**Comment by Peter-76** [comment]
Some additional details:

- My terminal has an initial height of 40 lines (and a width of 180 columns).
With this configuration `git log --pretty=oneline -n <X>` works with X up to 24.
If I change the terminal height to 50, X is ok up to 31.

- Same behavior with PowerShell 7.1.3 and PowerShell 7.2.0-preview.7

- Same behavior using Windows Terminal or PowerShell directly

**Comment by Peter-76** [comment]
Now I've tested this on my other machine:
- PowerShell 7.1.3
- git 2.32.0.windows.1
- posh-git 1.0.0
- oh-my-posh 3.168.0
- Windows Terminal Preview 1.9.1523.0
- Windows 11 Version 21H2 (OS Build 22000.51)

Exactly the same behavior as on my first machine.

But there is another detail I discovered now:
- When there is no `Import-Module posh-git` in the `$PROFILE` the output is incorrect as described above (no matter if oh-my-posh theme is set in the profile or manually or not set at all or even if oh-my-posh is not imported at all)
- When there is a `Import-Module posh-git` in the `$PROFILE` the behavior is as reported originally

Thus this looks like a bug in git itself (in the first case there is no module loaded, just pure git) which is somehow 'partly fixed' by posh-git.

**Comment by Peter-76** [comment]
Narrowed down the issue:
Everything is fine with git versions `2.29.2.windows.2`, `2.30.0.windows.2` and `2.31.0.windows.2` but broken with the latest version `2.32.0.windows.1`
I think this issue can be closed, will report a git issue.
