### ISSUE TITLE
No longer possible to use shell functions to calculate a segment's value?

### ISSUE THREAD

**Issue by pfmoore** [JanDeDobbeleer/oh-my-posh#84]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

If I'm understanding the new structure, it seems like the only way(s) of creating a new type of segment are to either run a subprocess or write a new module for Oh-My-Posh. Is that correct? The reason I ask is that I have a Powershell function that returns the execution time of the last command, and that uses shell features (`get-history`) to get the data. So it can't be run in either of the two ways that seem to now be available.

I understand that the resulting configuration would not be portable across shells, but that isn't an issue for me.

Is this an intended limitation of the new version, or is it likely to be possible to do this at some point?

### Environment

- Oh my Posh version: 3
- Theme: N/A
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
There's no way we can interact with Powershell directly anymore through Go. But, there's actually a way to achieve this by using the module (or likewise functionality in case you're going for a manual installation) and the Environment Variable segment. See [here](https://ohmyposh.dev/docs/environment) for more context.

**Comment by pfmoore** [comment]
Thanks! That sounds like a fair workaround.

**Comment by JanDeDobbeleer** [comment]
> Thanks! That sounds like a fair workaround.

It was the prettiest solution of all ugly ones (and portable cross shell too).

**Comment by JanDeDobbeleer** [comment]
@pfmoore ok if we close this if the answer is acceptable?
