### ISSUE TITLE
Coloring based on git status not working

### ISSUE THREAD

**Issue by vkosev** [JanDeDobbeleer/oh-my-posh#847]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description
Upgraded to newest versions of oh-my-posh and posh-git and now the coloring of the powerline based on the git status is not working.

### Environment
- Oh My Posh version: 3.168.0
- Theme: Paradox
- Operating System: Windows 10
- Shell: PowerShell Core 7.1
- Terminal: Windows Terminal

#### Optional
- posh-git version: 1.0
- git version:  2.29.2.windows.1

### Steps to Reproduce
1. Delete the folders of the oh-my-posh and posh-git modules

2. Download the modules again
```
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser
```

3. Edit the power shell core profile with

```
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt -Theme paradox
$env:POSH_GIT_ENABLED = $true
```

**Expected behavior:**
When there are changes not staged for commit the color of the powerline was getting orange.
When my local branch is a head of origin, color of the powerline again changes to something else.

**Actual behavior:**
Now the color of the powerline is always green, no matter the git status

**Comment by JanDeDobbeleer** [comment]
@VKosev that's expected as that theme doesn't have status enabled (nor colors). Have a look at [exporting the theme](https://ohmyposh.dev/docs/pwsh#override-the-theme-settings) and setting your own with those settings. You can find the config values [here](https://ohmyposh.dev/docs/git#colors). For that to work, also set `"display_status": true`.
