### ISSUE TITLE
output of version check is incorrect.

### ISSUE THREAD

**Issue by SirTwsted** [JanDeDobbeleer/oh-my-posh#848]
When doing a **_oh-my-posh -version_** in the CLI , even though it is updated to the latest version
it still says 3.164.0, instead of 3.168.2

**Comment by JanDeDobbeleer** [comment]
Can I get some more information on your setup? Only saw that on MacOS, but that's been fixed a while ago. Did you restart your shell (when on Windows), also make sure you don't have 2 executables somewhere as that might give you a wrong impression.

**Comment by SirTwsted** [comment]
I'm using Windows 10 20H2  and Powershell.

**Comment by JanDeDobbeleer** [comment]
@SirTwsted tested on the latest version and that one's working as expected.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/2492783/125504816-6d27e27c-43fe-449a-85af-f8a65d375e75.png">

I'm pretty sure it's going to be linked to either your shell not being refreshed, or you have two oh-my-posh binaries and the old version precedes the new one when calling it from the CLI.

**Comment by SirTwsted** [comment]
@JanDeDobbeleer
I just updated Oh-My-Posh to v3.169.1 today,  and this is what I get back, its been like this for a while.
I even uninstalled and reinstalled Oh-My-Posh and I also made sure I updated windows updates to the latest edition. 
I'm using Windows Terminal v1.8.1521.0  and I am on Windows 10 20H2 and yes its a 64-bit system.

![Screenshot_280](https://user-images.githubusercontent.com/15247713/126254242-a0d0bce1-3ca4-40c0-94fc-c0c8e085faa3.png)

**Comment by JanDeDobbeleer** [comment]
@SirTwsted how did you update oh-my-posh?

**Comment by SirTwsted** [comment]
@JanDeDobbeleer 
 Update-Module oh-my-posh
Then I wait for the UI to ask me if I want to update all I select [A]  for all and press enter.
Then I see the progress bar after it downloads it from the internet that looks like this,
oooooooooooooooooooooooooo

Then it completes.

**Comment by JanDeDobbeleer** [comment]
@SirTwsted that's what I thought :-). When using the module, you don't have the `oh-my-posh` executable (at least not under that name). That means, at one point in time, you installed it via other means (maybe scoop, or winget, or even manual) which does install the `oh-my-posh` binary. If you've set the following in your `$PROFILE`, you will be using the latest version you installed:

 ```pwsh
Import-Module oh-my-posh
Set-PoshPrompt -Theme whatever
```

You can check the version of the powershell module by using `Get-Module oh-my-posh`.

**Comment by SirTwsted** [comment]
@JanDeDobbeleer 
But, I never installed it via scoop or winget ever.  :)
When I first installed it, I followed the instructions on the front page for Windows users using PowerShell.
And my profile is under -- C:\Users\Twsted\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

and when looking inside that profile document it says **this**:
Import-Module oh-my-posh
Set-PoshPrompt -Theme powerlevel10k_rainbow

**Comment by JanDeDobbeleer** [comment]
That's perfect. I can't tell you how that came onto your machine, but I can guarantee the module didn't do it 😉

**Comment by SirTwsted** [comment]
@JanDeDobbeleer 
It came onto my machine by me following the instructions on the page.
Install-Module oh-my-posh -Scope CurrentUser

Then I scrolled down the page and installed the theme by first looking at what theme I wanted using this line instruction,
Get-PoshThemes

Then I installed the theme I liked by typing this line of instructions given.
Set-PoshPrompt -Theme  powerlevel10k_rainbow

Then when new versions came out of the oh-my-posh,  as by the instructions of the website it says to do this.
Update-Module oh-my-posh


All this info I followed are from this page:
https://ohmyposh.dev/docs/pwsh

**Comment by JanDeDobbeleer** [comment]
That's all correct but it does not explain how the "plain" oh-my-posh executable came on your machine as that one doesn't come with the Powershell module. So I'm afraid I can't help you with that specific part. The good news is, your oh-my-posh installation is up-to-date 👍🏻

**Comment by SirTwsted** [comment]
![200](https://user-images.githubusercontent.com/15247713/126548270-38428494-6730-485a-9fad-1132b919dd30.gif)

Ok if you say so  😎👍

**Comment by JanDeDobbeleer** [comment]
@SirTwsted you can find out where that executable is at using `Get-Command oh-my-posh`. Depending on the output, you might get closer to finding out what happened.
