### ISSUE TITLE
Exit code does not work in PowerShell

### ISSUE THREAD

**Issue by krzysdz** [JanDeDobbeleer/oh-my-posh#849]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

After 9576e8212ec7776a9c9ac3b27230afdd4f9e4d1f exit code detection stopped working in PowerShell and success is always signalled, because `$?` is captured too late.

Moving the lines 78-79 to the top of the `ScriptBlock` solves the problem.

https://github.com/JanDeDobbeleer/oh-my-posh/blob/2aa00da41be2f82358cdc9be0cfb83c6f9b28c15/src/init/omp.ps1#L70-L79

### Environment

- Oh My Posh version: 3.168.2 / 3.166.3
- Theme: slimfat
- Operating System: Windows 10 21H1 / Windows 11 (22000.65 co_release)
- Shell: PowerShell 7.1.3
- Terminal: Windows Terminal Dev / Preview

#### Optional

- posh-git version: 1.0.0
- git version: 2.32.0.windows.2

### Steps to Reproduce

1. Select a theme with exit code. I used `slimfat`.
2. Execute command exiting with 0.
3. Execute command exiting with something other than 0, e.g. `python -c "exit(1)"`.

**Expected behavior:**

Appropriate exit status and code are shown.

![Exit code 0 after program exited with 0 and red exit code 1 after program exited with 1](https://user-images.githubusercontent.com/12915102/125209752-5c394f00-e29b-11eb-81a4-8133cbb73ada.png)

**Actual behavior:**

Success is always shown, regardless of the exit code.

![After executing `python -c "exit(1)"` success is reported (green indicator) and no error code is shown, even though `$LASTEXITCODE` is 1](https://user-images.githubusercontent.com/12915102/125209811-d8cc2d80-e29b-11eb-9e3f-dad2790ad042.png)

**Comment by JanDeDobbeleer** [comment]
@krzysdz absolutely right. I'm an idiot.
