### ISSUE TITLE
Feat: Use first letter of folder instead of folder_icon in path segment

### ISSUE THREAD

**Issue by claw0ry** [JanDeDobbeleer/oh-my-posh#851]
### Prerequisites

- [X] I have read and understood the `CONTRIBUTING` guide
- [X] I have looked for duplicate issues before submitting this one

### Description

I want to suggest another style to the path segment, that is very similar to "agnoster", but instead of using ".." the first letter of the folder is displayed.

It should look something like this:

* `usr/portage/media-plugins/banshee-community-extensions/files` becomes `/u/p/m/b/files`
* `/home/user1/media/video/music/live-sets` becomes `~/m/v/m/live-sets` (note the ~ character as replacement for $HOME)

More examples: [https://stackoverflow.com/questions/3497885/code-challenge-bash-prompt-path-shortener](https://stackoverflow.com/questions/3497885/code-challenge-bash-prompt-path-shortener)

**Comment by JanDeDobbeleer** [comment]
@madsaune ooh, I like that! Allow me to facilitate that request 👍🏻

**Comment by claw0ry** [comment]
Wow, that was fast! Thanks a lot! :)
