### ISSUE TITLE
Home icon still shows in agnoster_full path style

### ISSUE THREAD

**Issue by fun840** [JanDeDobbeleer/oh-my-posh#854]
### Prerequisites

- [ X ] I have read and understood the `CONTRIBUTING` guide
- [ X ] I have looked for duplicate issues before submitting this one

### Description

In the `path` segment, the [docs](https://ohmyposh.dev/docs/path#agnoster-full) say that when the style is set to `agnoster_full`, it will "Render each folder name separated by the `folder_separator_icon`", but it doesn't say anything about $HOME being a default mapped location. I want to have the C drive just say `C` instead of `C:\`, so I can't set `mapped_locations_enabled` to false, but I also don't want $HOME to show as `~`, so I tried using `agnoster_full`. 

### Environment

- Oh My Posh version: 3.168.3
- Theme: [Custom](https://pastebin.com/YkVN4rMR)
- Operating System: Windows 10
- Shell: Powershell 7.1.3
- Terminal: Windows Terminal Preview

### Steps to Reproduce

1. Create an oh-my-posh configuration with a path segment
2. In the segment properties, set `style` to `agnoster_full`
3. Use the prompt and cd to $HOME

**Expected behavior:** It would show the full path (`C:\Users\user`)

**Actual behavior:** [It shows `~`](https://i.imgur.com/vVLgTdW.png)

**Comment by JanDeDobbeleer** [comment]
That's by design. We never really imagined anyone would have this request 😅

**Comment by fun840** [comment]
oh, is there any way to disable the home icon being `~` without fully disabling mapped locations? if there's not, I can always just set a mapped location for MY home directory to be default, but that would have to be changed manually on other people's computers. Is there a way to use a powershell variable in mapped locations? I guess I can always just use a custom command to get the path and do the stuff I want with it.

**Comment by JanDeDobbeleer** [comment]
@fun840 I'll gladly create a switch for that 😉
