### ISSUE TITLE
Should the docs mention ExecutionPolicy for Windows?

### ISSUE THREAD

**Issue by justin-hackin** [JanDeDobbeleer/oh-my-posh#855]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

When I followed the instructions for installing on windows, I encountered an issue: $PROFILE was not executable due to the windows ExecutionPolicy. I tried to set the ExecutionPolicy in the admin powershell but it claimed I didn't have the permission to do so. I then tried to set the execution policy for the current user to Unrestricted and that seemed to fix the issue. I'm unfamiliar with Windows shell and all this was new to me. Now I'm concerned that I've made my machine insecure so I can have a beautiful shell. Is there a more secure way to fix this? Do you think it's worth mentioning steps for this in the documentation? Or did I miss something?

### Environment

- Oh My Posh version:
- Theme: N/A
- Operating System: Windows 10
- Shell: PowerShell
- Terminal: Windows Terminal

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce
N/A

**Comment by JanDeDobbeleer** [comment]
@justin-hackin you might want to change that to `RemoteSigned`. The thing is, this goes way beyond the scope of this project.

**Comment by floh96** [comment]
@justin-hackin the execution policy is not a security feature because you can bypass it easily. More information is in the [powershell docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.1)

**Comment by AmineDjeghri** [comment]
I just set it to `RemoteSigned` and it worked, is it dangerous to set it to this please?

**Comment by justin-hackin** [comment]
> @justin-hackin you might want to change that to `RemoteSigned`. The thing is, this goes way beyond the scope of this project.

Okay fair enough. However, by default the profile didn't exist so a link to instructions on how to create one might be useful as I gather you're supposed to use New-Item, correct? Or is it okay to just create that file with my editor?

**Comment by JanDeDobbeleer** [comment]
@justin-hackin yes, creating one with the editor is perfectly fine. The thing is, that's basic Powershell knowledge. I don't mean this in a bad way, only that adding all of these details to the docs, for every language and in extension every platform/terminal, is impossible. Those are things we sort of expect people to know. And obviously we have this medium to answer any questions in case that turns out to be untrue and help people out. We've all needed to learn that at one point in time.

**Comment by JanDeDobbeleer** [comment]
@AmineDjeghri you're all set!
