### ISSUE TITLE
MappedLocation doesn't work if config file is YAML

### ISSUE THREAD

**Issue by JustinGrote** [JanDeDobbeleer/oh-my-posh#860]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

If the mapped path is defined in json, works fine. If defined in yaml, doesn't work. Confirmed I was using the right format by exporting the json to YAML

### Environment

- Oh My Posh version: 3.169.0
- Theme: fish (modified)
- Operating System: Windows
- Shell: Powershell
- Terminal: Tested both vscode and windows terminal

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/15258962/126056608-b706ba84-fe94-4b82-a269-1566b4939ccf.png)

**Expected behavior:** [What you expected to happen]
Prompt says 'ok'

**Actual behavior:** [What actually happened]
Prompt still says C:\temp

**Comment by JustinGrote** [comment]
Looks like the YAML config importer doesn't pick up the config correctly.
![image](https://user-images.githubusercontent.com/15258962/126056861-7aaed176-c54f-4c93-8c4a-8dfbc6fe6c08.png)

**Comment by JustinGrote** [comment]
Happens with TOML too
```
    [blocks.segments.properties]
      folder_icon = ""
      folder_separator_icon = "  "
      mapped_locations_enabled = true
      postfix = " "
      prefix = "<transparent></> "
      style = "full"
      [blocks.segments.properties.mapped_locations]
        "C:\temp" = "ok"
```
This will fail to work.

**Comment by JanDeDobbeleer** [comment]
Let's see if we can fix that

**Comment by JustinGrote** [comment]
@JanDeDobbeleer was doing some debugging last night and looks to be an issue in the gookit/config library. At first I thought maybe it was the special characters in the keys but trying "CTemp" also failed, and it wasn't coming thru at the loadconfig step prior to the bindstruct. Wonder if it has something to do with a bug in the deep nesting of maps or something but I gave up last night :)

![image](https://user-images.githubusercontent.com/15258962/126071254-59a8fd2b-fae9-4e73-bc75-1c566f03cb36.png)

**Comment by JustinGrote** [comment]
At the parseSourceCode step in gooconfig, the debugger freaks out with an error when I try to open that deep nesting, so not sure if the value actually isn't populated or not. Opened https://github.com/go-delve/delve/issues/2599 for that.
![image](https://user-images.githubusercontent.com/15258962/126071821-2a0bd945-37de-4d84-ab77-478fdd14b8ea.png)

**Comment by JustinGrote** [comment]
Using Println it looks like the value is actually there after the bindstruct, so I don't think it's the config decoder anymore.

![image](https://user-images.githubusercontent.com/15258962/126072680-035eb6d4-9e9c-48ef-ab7a-4153a11fcc27.png)

**Comment by JustinGrote** [comment]
Delve shows the properties in quotes, and I get this trying to call println on the config
![image](https://user-images.githubusercontent.com/15258962/126072835-696b5671-35bd-4d15-b7b7-fd5ceb9af6ad.png)

![image](https://user-images.githubusercontent.com/15258962/126072856-7da84f63-5a0e-4fea-a849-869a171eccb0.png)

So there's definitely something screwy here.

**Comment by JustinGrote** [comment]
Think I'm getting warmer...
![image](https://user-images.githubusercontent.com/15258962/126073013-0b49edc6-4e20-4e11-8e5f-c1a24e833569.png)

**Comment by JustinGrote** [comment]
OK now I'm obsessed that I'm doing something wrong, left side is json, right side is yaml
![image](https://user-images.githubusercontent.com/15258962/126073592-e2090206-1622-4072-8df2-13fb09cf781f.png)

**Comment by JustinGrote** [comment]
Think I (sort of) found it, looks to be a typing problem. Top is yaml, bottom is json. In the YAML instead of getting to this point as a map[string] interface{}, it's a map[interface{}] interface{} and it fails out.
![image](https://user-images.githubusercontent.com/15258962/126074326-abd87287-483b-4cff-a0d6-b26c2cd771c0.png)

**Comment by JustinGrote** [comment]
@JanDeDobbeleer  Found the problem, PR submitted. Maybe as part of that "great refactor" branch I saw, the config parsing itself can be more strictly typed to avoid this kind of issue.
