### ISSUE TITLE
Wrong Font

### ISSUE THREAD

**Issue by 846910027** [JanDeDobbeleer/oh-my-posh#871]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

I have used Fira Code font，but it also have some wrong.

<img width="493" alt="截屏2021-07-27 上午10 24 23" src="https://user-images.githubusercontent.com/64388136/127085138-67ec598f-a1c6-4282-96f4-488366a8d852.png">
<img width="1013" alt="截屏2021-07-27 上午10 18 55" src="https://user-images.githubusercontent.com/64388136/127085149-1d5f5d6f-02c4-4709-9b94-4b9b2c02f66f.png">

### Environment

- Oh My Posh version: v3
- Theme: paradox
- Operating System: win10
- Shell:  Powershell
- Terminal:  Powershell

#### Optional

- posh-git version:
- git version:

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by JanDeDobbeleer** [comment]
@846910027 that's a Windows Terminal font question, not related to oh-my-posh. You can have a look [here](https://ohmyposh.dev/docs/fonts) for more assistance, but not much I can do to assist on that part.
