### ISSUE TITLE
Windows Terminal (WSL2): Opening folders in explorer.exe

### ISSUE THREAD

**Issue by TheFirstMe** [JanDeDobbeleer/oh-my-posh#872]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

Is it possible to open folders in explorer.exe when Ctrl + clicking on a path segment with hyperlink enabled?

### Environment

- Oh My Posh version: 3.169.2
- Theme:  bubbles
- Operating System: Windows 10
- Shell: Bash
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
The terminal determines which program is opened so oh-my-posh can't influence that. would be a question for Windows Terminal.

**Comment by amzon-ex** [comment]
Hi, has support for path hyperlinks been removed?

**Comment by JanDeDobbeleer** [comment]
@amzon-ex no, not at all. Why?

**Comment by amzon-ex** [comment]
I stopped using the feature for sometime, and now when I want to re-enable it, I can't find it in the documentation... in the Path segment.

**Comment by JanDeDobbeleer** [comment]
@amzon-ex that's because it's replaced with a [template function](https://ohmyposh.dev/docs/configuration/templates#custom).

**Comment by amzon-ex** [comment]
@JanDeDobbeleer Thanks, figured it out finally!
