### ISSUE TITLE
virtualenv segment missing in HOME?

### ISSUE THREAD

**Issue by Holt59** [JanDeDobbeleer/oh-my-posh#874]
### Prerequisites

- [X] I have read and understood the `CONTRIBUTING` guide
- [X] I have looked for duplicate issues before submitting this one

### Description

When in the home folder, the Python segment is missing. I am using the following config for the Python segment:

```json
{
    "type": "python",
    "style": "powerline",
    "powerline_symbol": "\uE0B0",
    "foreground": "#100e23",
    "background": "#906cff",
    "properties": {
        "prefix": " \uE235 ",
        "display_mode": "environment"
    }
},
```

### Environment

- Oh My Posh version: 3.169.2
- Theme: [gist](https://gist.github.com/Holt59/270a2a700ba964334836d85d549c87c1)
- Operating System: Windows.
- Shell: Powershell.
- Terminal: Windows Terminal / VS Code terminal.

#### Optional

- posh-git version: 1.0.0
- git version: 2.29.2

**Expected behavior:** [What you expected to happen]

The Python segment symbol should be visible when in the home folder.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/2393288/127553538-28b4932b-06ec-40d1-8d8e-9298b8d97add.png)

**Comment by JanDeDobbeleer** [comment]
@Holt59 that's actually by design. To always show the segment, you need to use `"display_mode": "always"` for the Python segment.

**Comment by Holt59** [comment]
@JanDeDobbeleer So there is now way to have the old v2 behavior? `"display_mode": "always"` shows the segment even when I'm not in a virtual environment, that's not what I want...

**Comment by JanDeDobbeleer** [comment]
@Holt59 we could do this differently, let me think about a different approach.
