### ISSUE TITLE
ZSH init in WSL fails if path to OMP includes whitespace

### ISSUE THREAD

**Issue by jonaskuske** [JanDeDobbeleer/oh-my-posh#879]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

If the path to the OMP binary contains a space, the generated ZSH init script (for use in WSL) breaks because the OMP path isn't quoted/escaped. I currently need to init like this:

```zsh
eval "$(oh-my-posh-wsl --init --shell zsh --config /the/path.json | sed -e 's/Jonas Kuske/JONASK~1/')"
```

### Environment

- Oh My Posh version: 3.171.0
- Theme: Agnoster Plus
- Operating System: Ubuntu via WSL2
- Shell: ZSH
- Terminal: Windows Terminal

### Steps to Reproduce

1. Install oh-my-posh on Windows (in my case via `winget`)
2. Have a whitespace as part of your `~` dir path
3. Initialize oh-my-posh in WSL

**Expected behavior:** oh-my-posh initializes

**Actual behavior:** 

```zsh
_omp-precmd:8: no such file or directory: /c/Users/Jonas
```

**Comment by JanDeDobbeleer** [comment]
That can be fixed. I'll treat it as a bug.
