### ISSUE TITLE
Templated text segment

### ISSUE THREAD

**Issue by evmoroz** [JanDeDobbeleer/oh-my-posh#884]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

In some cases it is nice to have conditional text displayed. (My use case is switching `$` to `#` as prompt for root, but I think there can be other usages). Currently text segment returns a static text string with an option to change the color. I think it would be useful to have an option to use templates there or have a separate "template" segment. What do you think is a better option? The template would could also receive environmental variables and other runtime information in the context.

I can provide a PR with the implementation

**Comment by JanDeDobbeleer** [comment]
Allowing templating capabilities in the text segment makes a lot of sense imho.
