### ISSUE TITLE
Ability to add text decoration to segment contents

### ISSUE THREAD

**Issue by vidhanio** [JanDeDobbeleer/oh-my-posh#885]
### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] I have looked for duplicate issues before submitting this one

### Description

Is it possible to apply text decorations (e.g. italics, bold) to the actual content of the segments? It seems to only be possible to add them to the pre/postfix and was wondering if it was possible to apply to the content.

### Environment

- Oh My Posh version: 3.171.2
- Theme: Custom
- Operating System: Windows 10
- Shell: Powershell
- Terminal: Windows Terminal

**Comment by JanDeDobbeleer** [comment]
@vidhanlol segments which have a `template` can be text decorated (see [kubectl](https://ohmyposh.dev/docs/kubectl) for example). Not every segment has this yet, something I wanted to do for V4 as it could break existing themes (so we need an upgrade functionality).

**Comment by vidhanio** [comment]
Interesting, I'll look into that. Thanks!

**Comment by JanDeDobbeleer** [comment]
@vidhanlol for which segment would you like this? Because we can extend without breaking for some.

**Comment by vidhanio** [comment]
Hey! Sorry, wasn't checking my notifications often. My current custom theme is using `git`, `python`, `session`, `time`, `path`, and `spotify`.

**Comment by tylerbutler** [comment]
For `path`, I took a quick look at the code and I think it would be safe to add a `template` property that, when set, overrides the other format related properties. This is how `template` behaves in most (all?) cases today.

This may be true for other segments; I didn't look.

@JanDeDobbeleer is my reading of the code correct? Do you foresee any compatibility issues with this change for `path`? I am interested in opening a PR if you're open to the change.

**Comment by JanDeDobbeleer** [comment]
@tylerbutler all segments would need to be adjusted so that templating works. So yes, we should do that 😅 There's a file called `segment_deprecated.go` where we've added properties which we silently support for backwards compatibility in case the usage of template would render those obsolete, not sure if it applies here but just in case.

**Comment by JanDeDobbeleer** [comment]
All segments now have templating capabilities.

**Comment by bckelley** [comment]
@JanDeDobbeleer  I'm trying to do this too, using a customized Nordtron just can't figure out how to make it ```<b>bold</b>``` I did see this in the docs [themes docs](https://ohmyposh.dev/docs/configuration/templates#text-decoration) 
small snippet
```JSON
{
  "foreground": "#FF0000",
  "style": "plain",
  "template": "{{ if .Root }}<#5e81ac>[</> <b>admin</b> <#5e81ac>]</>{{ end }}",
  "type": "text"
},
```

**Comment by JanDeDobbeleer** [comment]
@bckelley that should work, what does it produce?

**Comment by bckelley** [comment]
@JanDeDobbeleer it's the same with and without the ```<b></b>```

**Comment by JanDeDobbeleer** [comment]
@bckelley validate if your terminal supports it and if it's enabled. We tell the terminal to print that in bold, but that's the one who should do it.

**Comment by bckelley** [comment]
I believe it does It's windows terminal also tried powershell.exe and it's not working there either

**Comment by JanDeDobbeleer** [comment]
@bckelley the standard console doesn't work indeed, Terminal added support about a year ago, so that should work.

**Comment by bckelley** [comment]
interesting ... i didn't think the powershell.exe worked but wasn't sure

**Comment by JanDeDobbeleer** [comment]
@bckelley added this to iTerm on macOS, it clearly show this is bold (albeit a slight weight):
<img width="845" alt="image" src="https://user-images.githubusercontent.com/2492783/208098888-386e5de5-5b0e-4dde-9eca-1aaf2957002f.png">

On Windows Terminal it indeed doesn't seem to work:

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/2492783/208099007-aa163f80-7c7d-415d-b3a5-aedb818f2deb.png">

That said, this is a Terminal responsibility, we use the correct ANSI sequence for bold, as shown on iTerm.

EDIT: I found the setting you need for this! `Settings/Profile/Defaults/Appearance/Text Formatting` and set to `Bold`.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/2492783/208100015-c69530ec-f702-4342-befa-cd3a90ca0ecd.png">

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/2492783/208099725-77436504-2546-4ebb-a471-19dc56f5ea64.png">

**Comment by bckelley** [comment]
@jan thank you i missed that!

**Comment by jan** [comment]
@bckelley glad I could help!
