### ISSUE TITLE
Box symbols in prompt

### ISSUE THREAD

**Issue by AakashM** [JanDeDobbeleer/oh-my-posh#89]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Tried running in Windows Terminal and in Powershell directly, the symbols in many themes are not appearing correctly.

### Environment

- Oh my Posh version: 3.21.0
- Theme: powerline
- Operating System: Windows 10 2004
- Shell: Powershell 7.0.3
- Terminal: Windows Terminal
- Font: Cascadia Code PL  2009.022

### Steps to Reproduce

1. Run Get-PoshThemes

**Expected behavior:** No box symbols

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/4455636/96837178-a0fa2d00-1463-11eb-94ee-04a8d9dfff5f.png)

**Comment by JanDeDobbeleer** [comment]
@AakashM you have two options, use a [nerd font](https://www.nerdfonts.com/) on which the icons have been based (and working), or override the icons with icons which are available in Cascadia Code (but to be honest, switching font is the most straightforward option).

**Comment by AakashM** [comment]
Thanks! Switching to nerd font has solved the issue.

**Comment by JanDeDobbeleer** [comment]
You're welcome! I made sure to also add that context [here](https://ohmyposh.dev/docs/powershell).
