### ISSUE TITLE
support linux package manager

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh#896]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would be awesome if you could support also linux package managers.
Upgrading would be a lot easier.
I don't know what's the best option to support most distros.

**Comment by JanDeDobbeleer** [comment]
It seems https://openbuildservice.org might be a good candidate. The idea is as follows: set up a separate repo to create the configurations and trigger a build when we have a new release. Similar to our homebrew setup. There's a nice [guide](https://linuxkamarada.com/en/2019/03/19/integrating-the-open-build-service-with-github/#.YVltAy8RrPg) here.

**Comment by JanDeDobbeleer** [comment]
I gave this a go and decided not to pursue in favour of using homebrew on linux. I'll adjust the docs.
