### ISSUE TITLE
Upgrade spring to 3x

### ISSUE THREAD

**Issue by travikk** [JanDeDobbeleer/oh-my-posh#900]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Upgrade to sprig 3.x branch. There is a host of new functions that deal with OS paths (which are separator agnostic for windows/linux) that are currently not supported (specifically the os* functions).
This will make it easier to create templates that are parsing current path/folders.

**Comment by lnu** [comment]
Little typo, you mean [sprig](https://github.com/Masterminds/sprig)

=> can be helpful https://github.com/Masterminds/sprig/issues/278
