### ISSUE TITLE
There is an extra '\n' character at the end of the output line where with Chinese

### ISSUE THREAD

**Issue by chrisyy2003** [JanDeDobbeleer/oh-my-posh#908]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

There is an extra '\n' character at the end of the output line where with Chinese

![image](https://user-images.githubusercontent.com/63803385/130271987-abc45320-ec9d-4df7-a15a-8d75fd65d39a.png)

### Version

3.172.1

### Theme

no matter which theme i used, bugs will appear
![image](https://user-images.githubusercontent.com/63803385/130272699-a4bbf314-1f67-4b03-b535-1127c9417a10.png)

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
@chrisyang2003 at the end of the command output or before? We don't add a newline character (you can validate that by simply pressing enter).

**Comment by chrisyy2003** [comment]
how to check whether at the end of the command output or before? It was strange, if i don't set the theme, command would run correctly
![image](https://user-images.githubusercontent.com/63803385/130331521-0187bbbf-cd32-4b37-b97d-1109c02a8318.png)
![image](https://user-images.githubusercontent.com/63803385/130331556-dc88cca4-c019-471e-a7e3-aac982e99963.png)

**Comment by JanDeDobbeleer** [comment]
@chrisyang2003 what it could be is the fact that we set the terminal output to UTF8

**Comment by lnu** [comment]
you  can validate what @JanDeDobbeleer  said by executing this `[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding` (without loading omp before)

**Comment by chrisyy2003** [comment]
> you can validate what @JanDeDobbeleer said by executing this `[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding` (without loading omp before)

well, that works, setting no theme will do same as the above.So how to solve it ?
![image](https://user-images.githubusercontent.com/63803385/130350109-e6c76514-152d-4097-90f4-cf4cd9992537.png)

**Comment by JanDeDobbeleer** [comment]
@chrisyang2003 check the values of your encoding in a clean powershell window and remember that value. Then import and set oh-my-posh and revert back to your system's default encoding right after. Do know doing this can have annoying side effects in oh-my-posh (but not necessarily).

Can I ask which ls tool this is? Because we've never seen this behavior before.

**Comment by JanDeDobbeleer** [comment]
@chrisyang2003  add the following to your `$PROFILE` to resolve the issue:

```powershell
$currentEncoding =  [console]::InputEncoding
Import-Module oh-my-posh
Set-PoshPrompt -Theme Honukai
[console]::InputEncoding = [console]::OutputEncoding = $currentEncoding
```
