### ISSUE TITLE
Manual Installation not working in Powershell 7

### ISSUE THREAD

**Issue by HackXIt** [JanDeDobbeleer/oh-my-posh#91]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

I installed Oh-My-Posh via powershell modules and tried out the themes with `Get-PoshThemes` and `Set-PoshPrompt ...`.
Those commands are working fine.

Then I git cloned the repo, followed the Manual Installation Guide with creating `C:\Tools` and downloading the script there.
I copied over the Themes in the Sub-Directory `C:\Tools\PoshThemes` from the cloned repository.

But when I insert the code from below into `$PROFILE` (= Microsoft.Powershell_profile.ps1) the prompt doesn't seem to load, instead I get a regular prompt from powershell.
```
[ScriptBlock]$Prompt = {
  $realLASTEXITCODE = $global:LASTEXITCODE
  & "C:\Tools\oh-my-posh.exe" -config "C:\Tools\PoshThemes\powerlevel10k_classic.json" -error $realLASTEXITCODE -pwd $PWD
  $global:LASTEXITCODE = $realLASTEXITCODE
  Remove-Variable realLASTEXITCODE -Confirm:$false
}
Set-Item -Path Function:prompt -Value $Prompt -Force
```

The Prompt works fine if I use the following inside `$PROFILE`, but the loading time is around 0,5~0,7 seconds.
```
Set-PoshPrompt powerlevel10k_classic
```

### Environment

- Oh my Posh version: Latest 
- Theme: powerlevel10k_classic
- Operating System: Windows 10
- Shell: Powershell 7.0.3
- Terminal: Windows Terminal 1.3.2651.0

### Steps to Reproduce

1. `mkdir C:\Tools`
2. `Invoke-Webrequest https://github.com/JanDeDobbeleer/oh-my-posh3/releases/latest/download/posh-windows-amd64.exe -OutFile C:\Tools\oh-my-posh.exe`
3. Copy themes in `C:\Tools\PoshThemes`
4. Edit Powershell-Profile `notepad $PROFILE` and paste the sample code from above.

**Expected behavior:** Prompt of Oh-My-Posh when starting a new shell.
_If the failure would be in the Theme, I'd at least expect the default look as mentioned in the wiki._

**Actual behavior:** Regular Prompt of Powershell

**Comment by JanDeDobbeleer** [comment]
I've read this a couple of times now trying to find an explanation but to no avail. If the `$PROFILE` is the one that's being used, this should result in a prompt. Can you check the output of `$error`?

**Comment by JanDeDobbeleer** [comment]
@HackXIt can you check the new manual installation guide? There was indeed something off, but the new way of creating the prompt works with the following:

```powershell
[ScriptBlock]$Prompt = {
  $realLASTEXITCODE = $global:LASTEXITCODE
  if ($realLASTEXITCODE -isnot [int]) {
      $realLASTEXITCODE = 0
  }
  $startInfo = New-Object System.Diagnostics.ProcessStartInfo
  $startInfo.FileName = "C:\Tools\oh-my-posh.exe"
  $startInfo.Arguments = "-config C:\Tools\PoshThemes\powerlevel10k_classic.json -pwd $PWD -error $realLASTEXITCODE"
  $startInfo.Environment["TERM"] = "xterm-256color"
  $startInfo.CreateNoWindow = $true
  $startInfo.StandardOutputEncoding = [System.Text.Encoding]::UTF8
  $startInfo.RedirectStandardOutput = $true
  $startInfo.UseShellExecute = $false
  if ($PWD.Provider.Name -eq "FileSystem") {
      $startInfo.WorkingDirectory = $PWD
  }
  $process = New-Object System.Diagnostics.Process
  $process.StartInfo = $startInfo
  Set-PoshContext
  $process.Start() | Out-Null
  $standardOut = $process.StandardOutput.ReadToEnd()
  $process.WaitForExit()
  $standardOut
  $global:LASTEXITCODE = $realLASTEXITCODE
  Remove-Variable realLASTEXITCODE -Confirm:$false
}
Set-Item -Path Function:prompt -Value $Prompt -Force
```

**Comment by HackXIt** [comment]
> I've read this a couple of times now trying to find an explanation but to no avail. If the $PROFILE is the one that's being used, this should result in a prompt. Can you check the output of $error?

There indeed is an error coming up, but not one I can figure out:
```
Usage of C:\Tools\oh-my-posh.exe:
invalid value "-pwd" for flag -error: parse error
    	Override the shell you are working in
  -shell string
    	the path you are working in
  -pwd string
    	Config prints the current settings in json format
  -print-config
    	Error code of previously executed command
  -error int
    	Add the path to a configuration you wish to load
  -config string
```
To me the `-pwd` flag looks just fine, it's the same as in the manual and as I stated above.

Using the script you provided works though!

Thanks for the quick reply, sorry for my own late reply.
