### ISSUE TITLE
Theme documentation does not render screenshots of themes

### ISSUE THREAD

**Issue by divinebovine** [JanDeDobbeleer/oh-my-posh#912]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Opened the theme documentation and it states "Below are some screenshots of the more common themes." However there are no screenshots rendered.

### Version

N/A

### Theme

N/A

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

bash

**Comment by JanDeDobbeleer** [comment]
@divinebovine oh snap. Did I break my renderer? That's rather silly. Thanks for letting me know, that definitely needs a test in that case.

**Comment by JanDeDobbeleer** [comment]
I see the issue. With moving to Azure Static Web Apps, the command isn't correct anymore. I'll fix it.
