### ISSUE TITLE
Git worktrees count

### ISSUE THREAD

**Issue by xt0rted** [JanDeDobbeleer/oh-my-posh#913]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Support for a `display_worktrees_count` status option similar to that of stash count.

I've started to use [worktrees](https://git-scm.com/docs/git-worktree) after [reading about them](https://www.jvt.me/posts/2019/01/29/git-worktree-multiple-branches/) recently and similar to stashes I think it'd be helpful to know if there are any in the repo. I'm not sure if having an indicator if I'm in a worktree would be helpful yet, but at the very least knowing if i have any seems useful.

**Comment by lnu** [comment]
@JanDeDobbeleer  I have a working version if you want

**Comment by JanDeDobbeleer** [comment]
@lnu submit it, I can have a look. I'm still on holiday without a laptop.

**Comment by xt0rted** [comment]
Thanks for this feature @JanDeDobbeleer & @lnu!
