### ISSUE TITLE
Startup prompt showing with bugs

### ISSUE THREAD

**Issue by LittleNewton** [JanDeDobbeleer/oh-my-posh#925]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

After I upgrade the Windows Terminal to 1.10.2383.0, bugs happened during the startup of Windows terminal.

I am using the Paradox Theme.

![image](https://user-images.githubusercontent.com/17793356/131683711-cad0cfe3-7775-4651-8a94-a80007f266d1.png)

The bug shows like this picture.

However, when I push ENTER, the unexpected prompts disappeared. Just like this

![image](https://user-images.githubusercontent.com/17793356/131683909-da9d0c8e-3f86-45e5-b01f-4d14161d55dc.png)

### Version

3.176.0

### Theme

Paradox with a little modification.

``` jsonc
//
// * FileName: paradox.omp.json
// * Author: 刘 鹏
// * Email: littleNewton6@outlook.com
// * Date: 2021, Aug. 24
// * Copyright: GPL 3.0
//

{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "root",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffe9aa"
        },
        {
          "type": "session",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#ffffff"
        },
        {
          "type": "path",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#91ddff",
          "properties": {
            "folder_icon": "\uF115",
            "folder_separator_icon": "\\",
            "style": "full"
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#95ffa4"
        },
        {
          "type": "python",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#100e23",
          "background": "#906cff",
          "properties": {
            "prefix": " \uE235 ",
            "display_virtual_env": true,
            "display_default": true,
            "display_mode": "always"
          }
        },
        {
          "type": "exit",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#ffffff",
          "background": "#ff8080",
          "properties": {
            "prefix": " \uE20F"
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "newline": true,
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "#007ACC",
          "properties": {
            "prefix": "",
            "text": "\u276F"
          }
        }
      ]
    }
  ],
  "final_space": false
}

```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
NULL
```

**Comment by JanDeDobbeleer** [comment]
That's a Windows Terminal bug. See [here](https://ohmyposh.dev/docs/faq#windows-terminal-unexpected-space-between-segmentstext) for info and a workaround.

**Comment by gitolicious** [comment]
It looks like this is a slightly different issue as the `\u2800` postfix does not solve it.
For reference here is the default behavior (each screenshot showing a freshly opened Windows Terminal tab with PowerShell Core and then an empty new line after pressing _\<Enter>_):

![image](https://user-images.githubusercontent.com/26963495/132091368-04f7e3bb-b188-4fd7-946a-95af376b625a.png)

This is after adding the spacing character as postfix:

![image](https://user-images.githubusercontent.com/26963495/132091380-a16bce66-b491-4ec8-959f-7ca48664a472.png)

I found another workaround to also solve this "first line" issue: Add a `Clear-Host` line to your PowerShell `$PROFILE`. This makes everything look nice again.

![image](https://user-images.githubusercontent.com/26963495/132091396-927c82b1-2541-4e93-a5b9-92ef5728cf84.png)

Yes, it is quite hacky, but until Windows Terminal fixes their glyphs errors, I think this is the way we have to go.
