### ISSUE TITLE
Support pnpm (a node package manager)

### ISSUE THREAD

**Issue by Jack-Works** [JanDeDobbeleer/oh-my-posh#926]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

pnpm is a package manager for Node.js, has `pnpm-lock.yaml` as it's lockfile.

**Comment by JanDeDobbeleer** [comment]
@Jack-Works do you want the node segment to be visible when the `pnpm-lock.yaml` file is found?

**Comment by Jack-Works** [comment]
> @Jack-Works do you want the node segment to be visible when the `pnpm-lock.yaml` file is found?

Have no idea. Since the special point of pnpm is, pnpm is using hard link to link packages, I guess icon related to links are ok
