### ISSUE TITLE
In git segment, option to remove detailed added/modified/etc counts but keep status icon.

### ISSUE THREAD

**Issue by darthwalsh** [JanDeDobbeleer/oh-my-posh#93]
### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [X] I looked for duplicate issues before submitting this one

### Description

I'd like the git segment to include some icon to indicate there are local changes in working or staged, but without the detailed status string like `~1` or `?1`

### Environment

- Oh my Posh version: 3.22.1
- Theme: custom, here's the relevant segment:
```
                {
                    "type": "git",
                    "style": "plain",
                    "foreground": "#D0666F",
                    "properties": {
                        "branch_icon": "",
                        "branch_identical_icon": "",
                        "branch_ahead_icon": "",
                        "branch_behind_icon": "",
                        "branch_gone_icon": "",
                        "display_status": true,
                        "status_separator_icon": "",
                        "local_working_icon": "\u2717",
                        "local_staged_icon": "\u2717",
                        "commit_icon": "",
                        "rebase_icon": "",
                        "tag_icon": "",
                        "cherry_pick_icon": "",
                        "merge_icon": "",
                        "working_color": "#FFFF00",
                        "staging_color": "#00FF00",
                        "status_colors_enabled": true,
                        "color_background": false,
                        "prefix": " ",
                        "postfix": ""
                    }
                }
```
- Operating System: macOS
- Shell: pwsh
- Terminal: vs code integrated

### Steps to Reproduce

For these example shell commands that create `blah`, git add it, then create `blah2`:

```bash
➜ ~/repo develop  $ touch blah
➜ ~/repo develop  ✗ ?1 $ git add blah
➜ ~/repo develop  ✗ +1 $ touch blah2
➜ ~/repo develop  ✗ +1 ✗ ?1 $ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   blah

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        blah2
```

**Expected behavior:** Prompt is `➜ ~/repo develop  ✗ $ ` (colored appropriately based on working_color and staging_color) If both working and staged changes, then two `✗` with one of each color . 

**Actual behavior:**  Prompt is `➜ ~/repo develop  ✗ ?1 $ ` or `➜ ~/repo develop  +1 $ `

---

I could imagine a settings like `status_display_details` that controls whether https://github.com/JanDeDobbeleer/oh-my-posh3/blob/23233bc383b1eebe61b6493fd78140da3f2fdb83/segment_git.go#L133 includes the whole gitStatus string, or just the prefix.

**Comment by JanDeDobbeleer** [comment]
That could work and seems like it's an easy implementation as well. Let's do it. Do you want to give it a try, or shall I go for it?

**Comment by darthwalsh** [comment]
Awesome, thanks so much! I'm not an expert at go but for future FRs I can give it a try myself :)
