### ISSUE TITLE
Battery segment display as error% in windows

### ISSUE THREAD

**Issue by pandyamehul** [JanDeDobbeleer/oh-my-posh#945]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Getting error for the battery segment. 

![image](https://user-images.githubusercontent.com/33895324/132929264-109f2ed0-9b74-44f2-b21d-1e4724cac054.png)

with error message - oh-my-posh fatal error rendering battery segment:runtime error: invalid memory address or nil pointer dereference

### Version

oh-my-posh v3
Windows 10
Windows Terminal  / PowerShell 7.1.4

### Theme

Custom.

```
        {
          "type": "battery",
          "style": "powerline",
          "invert_powerline": true,
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#ffeb3b",
          "properties": {
            "battery_icon": "",
            "charging_icon": "\uE234 ",
            "charging_color": "#40c4ff",
            "charged_icon": "\uE22F ",            
            "charged_color": "#4caf50",
            "discharging_icon": "\uE231 ",
            "discharging_color": "#ff5722",
            "color_background": true,
            // "postfix": "\uF295 ",
            "prefix": "<#4caf50,transparent>\uE0B6</> ",
            "postfix": "\u003c#193549\u003e%\u003c/\u003e\u003c#FFFFFF\u003e \u003c/\u003e",
            "display_charging": true,
            "display_error": true,
            "template": "{{.Battery.Status}}"
          }
```

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
oh-my-posh fatal error rendering battery segment:runtime error: invalid memory address or nil pointer dereference
```

**Comment by pandyamehul** [comment]
on the same computer - it works properly on wsl

![image](https://user-images.githubusercontent.com/33895324/133000367-adda23c2-d3c1-417e-82d1-9c6e35341a37.png)

**Comment by JanDeDobbeleer** [comment]
@pandyamehul is it consistently broken on Windows are only in certain cases (charging/discharging/charged)?

**Comment by pandyamehul** [comment]
yes - it fails constantly irrespective of the different battery state i.e. charging/discharging/charged for Windows. However, same is working for WSL-Ubuntu 20.04

**Comment by pyxelr** [comment]
@pandyamehul: I think there is something wrong with the custom theme you are using.

After giving a try to your configuration, I got this error:
![1](https://user-images.githubusercontent.com/30161753/133323429-8b216a3f-02a4-443c-91db-12f64df10fe2.png)

However, afterwards I tried the config suggested in the official docs: the [Battery section](https://ohmyposh.dev/docs/battery), and it worked flawlessly:
![2](https://user-images.githubusercontent.com/30161753/133323562-cbda207b-334b-4a37-bba6-cf6dfe065ada.png)

FYI, I am using oh-my-posh `3.181.1` on Windows 10, and I tested it in different terminals (ConEmu and Windows Terminal) while being in a charging state.

**Comment by pandyamehul** [comment]
@pyxelr - I did upgraded oh-my-posh to 3.181.2 and also used the official docs: the [Battery section](https://ohmyposh.dev/docs/battery) - still getting error. See below screen shot and also the configuration used:

![image](https://user-images.githubusercontent.com/33895324/133448929-08943596-63c9-4cce-9276-256b3756ea52.png)

```
        {
          "type": "battery",
          "style": "powerline",
          "powerline_symbol": "\uE0B0",
          "foreground": "#193549",
          "background": "#ffeb3b",
          "invert_powerline": true,
          "properties": {
            "battery_icon": "",
            "discharging_icon": "\uE231 ",
            "charging_icon": "\uE234 ",
            "charged_icon": "\uE22F ",
            "color_background": true,
            "charged_color": "#4caf50",
            "charging_color": "#40c4ff",
            "discharging_color": "#ff5722",
            "postfix": "\uF295 ",
            "display_charging": true,
            "display_error": true
          }
        }
```

**Comment by pyxelr** [comment]
@pandyamehul: I tried the above configuration, and now it looks okayish in my theme:

![2021-09-15_16-22-28](https://user-images.githubusercontent.com/30161753/133451502-35be24a8-c075-4496-a179-17886fb57c31.png)

FYI, I am also using `CaskaydiaCove NF` font in the Windows Terminal above.

Try giving a try to my full theme to see if it also breaks for you:
[.mytheme.omp.json.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7170869/default.mytheme.omp.json.zip)

Generally, I have a pretty default Windows OS, and the only modifications I did once for Oh My Posh, was [adding 2 environment variables](https://github.com/JanDeDobbeleer/oh-my-posh/issues/939#issuecomment-913628638) since I wasn't able to activate conda environments. Maybe your issue is also related to setting up some environment variables or getting rid of specific bits in your theme, such as `osc99`.

**Comment by pandyamehul** [comment]
@pyxelr - Changed font to "CaskaydiaCove NF" in Windows Terminal under the "settings.json"

```
      {
        "backgroundImageAlignment": "bottomRight",
        "backgroundImageOpacity": 0.25,
        "backgroundImageStretchMode": "none",
        "colorScheme": "Campbell Powershell",
        "experimental.retroTerminalEffect": false,
        "fontFace": "CaskaydiaCove NF",
        "fontWeight": "normal",
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "hidden": false,
        "name": "PowerShell.Core",
        "source": "Windows.Terminal.PowershellCore",
        "useAcrylic": false
      },
```
Also used ".mytheme.omp.json" - facing the same error.
![image](https://user-images.githubusercontent.com/33895324/133528253-3930b9b1-de7d-4ffa-ab79-82c693335f58.png)

Checked environment variable - and not using any of the mentioned like PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO 

Could you please guide from where i can make changes for "osc99"?

**Comment by pyxelr** [comment]
You can set the value of 'osc99' in your exported Oh My Posh theme file, such as ".mytheme.omp.json", where I have already set it to 'false'. Check out the [Configuration](https://ohmyposh.dev/docs/configure) page for more info.

**Comment by pyxelr** [comment]
You can set the value of `osc99` in your exported Oh My Posh theme file, such as ".mytheme.omp.json", where I have already set it to `false`. Check out the [Configuration](https://ohmyposh.dev/docs/configure) page for more info.

**Comment by JanDeDobbeleer** [comment]
@pyxelr the help is great but I feel this is a bug in the code nonetheless. Something is off as we try to access data that doesn't exist. I'll have a look over the weekend.

**Comment by pandyamehul** [comment]
@pyxelr  - added the OSC99 - false to the theme file. 

![image](https://user-images.githubusercontent.com/33895324/133697339-d3b6fb61-657d-4b24-9fcd-9540d721404b.png)

but still it reflect the same error - 

![image](https://user-images.githubusercontent.com/33895324/133697373-f7e2e6f0-9d2d-4372-ac77-eb465d0fdae8.png)

seems no change. Any other suggestion ?

**Comment by JanDeDobbeleer** [comment]
@pandyamehul can you remove the `template` property in your config? It could be that it errors due to reasons and your template will try to access the battery status (and can fail).

Can you try to run the following exe in Windows? It displays the battery info using the lib that's included in oh-my-posh. Maybe we can find the root cause in that case. 
[battery.exe.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7182977/battery.exe.zip)

**Comment by pandyamehul** [comment]
removed all template property. Sharing complete theme file as reference
[pandyamehul.theme.terminal.omp.json.zip](https://github.com/JanDeDobbeleer/oh-my-posh/files/7186521/pandyamehul.theme.terminal.omp.json.zip)

Also , see output of battery.exe ... can see some error and could be that is causing the issue.

![image](https://user-images.githubusercontent.com/33895324/133802708-73d317fc-ada6-4981-8a1a-692767887b9a.png)

**Comment by JanDeDobbeleer** [comment]
Perfect. We can fix that. Seems like there's at least one battery that works 😅

**Comment by pyxelr** [comment]
@pandyamehul The message in your terminal seems to be pointing to the root cause. Here is my result for a reference:

![battery-test](https://user-images.githubusercontent.com/30161753/133897186-3a60b107-1a32-484a-bdb0-542ae7f55e6c.png)

**Comment by JanDeDobbeleer** [comment]
@pandyamehul this fix is a guess, curious to see the results.

**Comment by pandyamehul** [comment]
Unfortunately, doesn't look like issue is fixed. Now error changed to different message - refer below screen shot.

![image](https://user-images.githubusercontent.com/33895324/133944306-e6bf28b6-4f3c-47d6-a7fd-ea98c568a0c8.png)

It appears like BAT0 - message is getting displayed instead of BAT1 status.

**Comment by JanDeDobbeleer** [comment]
@pandyamehul that's perfect as it implies I did find the issue originally reported. If I now treat this error as one to skip in case of multiple batteries, it will work.

**Comment by JanDeDobbeleer** [comment]
The issue should be filtered out in the latest release

**Comment by pandyamehul** [comment]
Confirm closure of issue - can see now battery% reflecting correctly.

![image](https://user-images.githubusercontent.com/33895324/134018189-e674ea97-8251-4301-ab72-4621786351ee.png)
