### ISSUE TITLE
Theme does not display properly when we resize the window.

### ISSUE THREAD

**Issue by vedantmgoyal9** [JanDeDobbeleer/oh-my-posh#947]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When we resize the window, it should automatically adjust and when the screen size is too small, it shouldn't display the right part. It looks weird and when we start typing, it types over the theme.
![image](https://user-images.githubusercontent.com/83997633/132978246-7f96e452-279c-4a67-ab69-932c9e7f578b.png)

### Version

3.180.1

### Theme

jandedobbeleer.omp.json

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
That's the responsibility of the shell I would say. I don't even know if there's a way to get a trigger when this happens.

**Comment by pyxelr** [comment]
I believe it is something very hard to be managed, and generally, it looks like a theme from the screenshot is too wide to fit in such a narrow window. @vedantmgoyal2009: what you can do to optimize this behaviour, is to move the input field to a next line (as in my theme on the attached screenshot).

Generally, in the beginning it was also annoying for me that the layout wasn't displayed properly after resizing the window, but then I got used to fixing it by simply pressing `ENTER` and then doing `clear` or something equivalent.
![2021-09-14_21-31-03](https://user-images.githubusercontent.com/30161753/133322052-8d9113c5-1fd0-443a-ae65-a973bb57c591.png)

**Comment by JanDeDobbeleer** [comment]
I tried to resolve this earlier but somehow on Windows getting the terminal width doesn't work. Meaning I can't calculate if we need to skip displaying the right prompt. Maybe there's another solution, but so far that's been unsuccessful.

EDIT: you can find the logic [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/78d0a4255630842060e4986e41d7697b1227b1de/src/engine.go#L28-L28). But so far getting the actual console size on [Windows](https://github.com/JanDeDobbeleer/oh-my-posh/blob/f7de8aed27b2d88fdc594def9ee3d9fba95506c5/src/environment_windows.go#L71-L71) does not return the right value compared to [Linux/macOS](https://github.com/JanDeDobbeleer/oh-my-posh/blob/f7de8aed27b2d88fdc594def9ee3d9fba95506c5/src/environment_unix.go#L36-L36).

**Comment by vedantmgoyal9** [comment]
@pyxelr I have done that for now already after reporting the issue. I would look at how the logic actually works then find some way to do it. It will take some time for me.

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 I might have found a solution for the issue I mentioned above. Stay tuned.

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 @pyxelr can you have a look at what [4.1.0](https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v4.1.0) offers?

**Comment by pyxelr** [comment]
@JanDeDobbeleer: I just verified the situation and it's unfortunately the same as before in Windows Terminal or ConEmu.

**Comment by JanDeDobbeleer** [comment]
Euh. That's strange as it does work on my Windows installation. Did you reload the shell?

**Comment by rescenic** [comment]
Just type 'clear' in console, to refresh the layout.

**Comment by JanDeDobbeleer** [comment]
@pyxelr indeed, it does not work. I'll see what the issue is as my tests did succeed. Strange.

**Comment by pyxelr** [comment]
@JanDeDobbeleer Sorry, I was not being able to reply to you yesterday, but restarting the shell did not fix the issue on my side. I am keeping my fingers crossed for finding a solution.

**Comment by vedantmgoyal9** [comment]
It works!

**Comment by vedantmgoyal9** [comment]
Thanks, @JanDeDobbeleer for this improvement.

**Comment by JanDeDobbeleer** [comment]
@pyxelr @vedantmgoyal2009 I could reproduce it. Should work now. The behavior is as follows: before rendering rprompt, we check if there's enough room. If not, we do not print it. This means only the previously drawn prompts and output gets garbled, subsequent prompts will look good. No more text overlap (apart from when extending the standard breathing room we allow).

**Comment by pyxelr** [comment]
@JanDeDobbeleer: I just gave it a test after restarting Windows Terminal, and there does not seem any change, or maybe I do not understand what was fixed:

https://user-images.githubusercontent.com/30161753/133905527-b2e5d37f-4436-4bb9-b0ee-d133fb723bf1.mp4

**Comment by JanDeDobbeleer** [comment]
@pyxelr the logic only applies for `rprompt` [block](https://ohmyposh.dev/docs/configure#type), not a right aligned prompt block as you do not overwrite those.

**Comment by vedantmgoyal9** [comment]
I tested with the default theme i.e. `JanDeDobbeleer.omp.json`

**Comment by JanDeDobbeleer** [comment]
@vedantmgoyal2009 yes, that one has an `rprompt`.

**Comment by vedantmgoyal2009** [comment]
@JanDeDobbeleer Please accept my invitation on LinkedIn.
