### ISSUE TITLE
Syntax error on Ubunutu 20.04 on WSL2

### ISSUE THREAD

**Issue by sckennedy** [JanDeDobbeleer/oh-my-posh#953]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

Hi - I followed the instructions to install oh-my-posh on Ubunutu 20.03 installed on Windows WSL2 from here - [https://ohmyposh.dev/docs/linux]

The install worked fine.   I updated my .bashrc file to include the following line

eval "$(oh-my-posh --init --shell bash --config ~/jandedobbeleer.omp.json)"

and re-loaded the bashrc file and got the following error 

bash: eval: line 148: syntax error near unexpected token '('
bash: eval: line 148: 'function _omp_hook() {'

I've tried deleting and re-installing 

### Version

Version 3

### Theme

default theme jandebobbeleer.omp.json

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash

**Comment by JanDeDobbeleer** [comment]
@sckennedy I'll double check.

**Comment by JanDeDobbeleer** [comment]
@sckennedy works on my bash machine, which version of bash do you have installed there? Could be it needs to be updated.

I have the following line as well `eval "$(oh-my-posh --init --shell bash --config ~/jandedobbeleer.omp.json)"`

Additionally, you can provide the exact init script using the following and pasting it here `oh-my-posh --shell bash --print-init --config ~/jandedobbeleer.omp.json`

**Comment by sckennedy** [comment]
@JanDeDobbeleer - thanks for replying so quickly - appreciated.  

I'm running WSL2 Ubunutu version 20.04LTS 
The kernel version is 5.10.16.3-microsoft-standard-WSL2
Here is a screen shot of the --print-init that I ran if that helps.

![Screenshot 2021-09-14 174552](https://user-images.githubusercontent.com/6388648/133299695-912be313-9caf-4533-a3af-6f40286a0c7c.jpg)

**Comment by JanDeDobbeleer** [comment]
I see something off, the `PS0` line starts with a space. Probably that's my mistake somehow. I'll push a fix for that already, other than that I don't see what's off.

@sckennedy can you let me know what `bash --version` says?

**Comment by lnu** [comment]
I tried on my side and it works without any issue(and with the leading space). 
My bash version on ubuntu 20.04 in WSL2: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`

**Comment by sckennedy** [comment]
Hi @JanDeDobbeleer - result from bash --version is the same as Inu
`GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`

I'll pull latest version and let you know the outcome.

**Comment by sckennedy** [comment]
Still the same behaviour unfortunately with the syntax error.  

Screen shot of bash terminal:
![image](https://user-images.githubusercontent.com/6388648/133384816-1d77db16-8e50-4a77-b7f7-2d35345a465e.png)

with this line in my bashrc file
eval "$(oh-my-posh --init --shell bash --config ~/jandedobbeleer.omp.json)"

I appreciate that it's not possible to replicate it so will keep trying things to see if I can find out what the problem on my machine may be.

**Comment by sckennedy** [comment]
Hi @JanDeDobbeleer - I finally got to the bottom of the problem I was having.

In my .bash_aliases file I have the following line

`alias function='cd /mnt/d/code/c-mac/function-scheduler'`

and obviously 'function' is a keyword so made the whole thing blow up.  It was nothing to do with Oh My Posh at all.  Changing the alias to a different word and everything works fine.  Thanks for taking the time to have a look.
