### ISSUE TITLE
Battery status should be visible only if unplugged or charging

### ISSUE THREAD

**Issue by jprimke** [JanDeDobbeleer/oh-my-posh#958]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Hello

It would be nice if I could configure the visibility of the battery segment so that the segment is not displayed when the battery is fully charged.

As a suggestion: 

- add a parameter "display_charged" and do not show this segment when the battery is fully charged and the parameter is set to false.

Thanks

Joerg

**Comment by lnu** [comment]
@JanDeDobbeleer  so you would split the `display_charging` which hides when charging and full to `display_charging` and `display_charged`?

**Comment by JanDeDobbeleer** [comment]
@lnu thx for the change! Although it's bot really breaking, but hey, we're at 4 now 😂
