### ISSUE TITLE
Upgrade not working on Windows PowerShell

### ISSUE THREAD

**Issue by rashil2000** [JanDeDobbeleer/oh-my-posh#96]
### Prerequisites

- [ ] I have read and understand the `CONTRIBUTING` guide
- [x] I looked for duplicate issues before submitting this one

### Description

Oh-My-Posh-3 commands are not working when I upgrade the module.

### Environment

- Oh my Posh version: 3.23.0-beta
- Theme: Any theme
- Operating System: Windows 10.0.19042
- Shell: PowerShell 5.1.19041.546
- Terminal: Windows Terminal 

### Steps to Reproduce

Just followed the instructions given here - https://ohmyposh.dev/docs/upgrading

**Expected behavior:** The commands should work since no specific minimum version of PowerShell is specified anywhere in the docs.

**Actual behavior:** ![image](https://user-images.githubusercontent.com/46838874/97107802-702e2800-16ef-11eb-9a70-5b1dcd6dc39f.png)

**Comment by rashil2000** [comment]
Turns out I'm not even able to uninstall it now: 
![image](https://user-images.githubusercontent.com/46838874/97108100-39591180-16f1-11eb-8d26-0cee56060a0a.png)

Could you help me?

**Comment by JanDeDobbeleer** [comment]
Yes. You need at least Powershell 6, you have 5. Updating to Powershell 7 will do the trick, or doing a manual installation as I don't plan to actively support 5 due to being Windows only.

**Comment by rashil2000** [comment]
Oh, okay. You should mention the minimum version of PowerShell somewhere in the docs then. 

May I ask what specific commands are being used in PowerShell 6+ that won't work in 5? I thought the command set of PowerShell 6+ was a subset of 5.

**Comment by JanDeDobbeleer** [comment]
Everything should in theory work just fine, I just can't support it as it's limited to Windows only and I can only offer support for cross platform tooling due to having a life outside of this context 😉

**Comment by rashil2000** [comment]
@JanDeDobbeleer Could you put Scoop in the roadmap too so that manual installation becomes a tiny bit easier?

**Comment by JanDeDobbeleer** [comment]
I'm looking at winget as that's the new hot thing apparently. Scoop could be an option too, I'll check.

**Comment by rashil2000** [comment]
Sure, both of them are cool. 

I just mentioned this as V2 is there on Scoop too (not sure who added it), so V3 would just mean upgrading that. Or a separate package can be made too.

**Comment by JanDeDobbeleer** [comment]
Someone made it. Same for chocolatey.
