### ISSUE TITLE
Release failed for powershell

### ISSUE THREAD

**Issue by jetersen** [JanDeDobbeleer/oh-my-posh#962]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

https://github.com/JanDeDobbeleer/oh-my-posh/runs/3624688541

### Version

v4.0.0

### Theme

N/A

**Comment by JanDeDobbeleer** [comment]
@jetersen ah, right. The API key expired. I saw that message yesterday and gracefully failed to create a new one in time.

**Comment by jetersen** [comment]
@JanDeDobbeleer No worries 😅 It was simply a friendly reminder, it is so easy to miss and/or forget.

**Comment by JanDeDobbeleer** [comment]
@jetersen I'll push a new version tomorrow with a neat little addition. The key has been replaced.
