### ISSUE TITLE
WIndows arm64

### ISSUE THREAD

**Issue by pb5050** [JanDeDobbeleer/oh-my-posh#966]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

i am using surface pro x on  latest windows insider upon updating oh my posh i now get this erro 

Exception: Oh My Posh: Unsupported architecture: 12

### Version

newest

### Theme

custom

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
Exception: Oh My Posh: Unsupported architecture: 12
```

**Comment by JanDeDobbeleer** [comment]
@pb5050 can you let me know the output of `Get-CimInstance -Class Win32_Processor -Property Architecture`?

**Comment by pb5050** [comment]
@JanDeDobbeleer  


Availability                            :
CpuStatus                               :
CurrentVoltage                          :
DeviceID                                : CPU0
ErrorCleared                            :
ErrorDescription                        :
LastErrorCode                           :
LoadPercentage                          :
Status                                  :
StatusInfo                              :
AddressWidth                            :
DataWidth                               :
ExtClock                                :
L2CacheSize                             :
L2CacheSpeed                            :
MaxClockSpeed                           :
PowerManagementSupported                :
ProcessorType                           :
Revision                                :
SocketDesignation                       :
Version                                 :
VoltageCaps                             :
Caption                                 :
Description                             :
InstallDate                             :
Name                                    :
ConfigManagerErrorCode                  :
ConfigManagerUserConfig                 :
CreationClassName                       :
PNPDeviceID                             :
PowerManagementCapabilities             :
SystemCreationClassName                 :
SystemName                              :
CurrentClockSpeed                       :
Family                                  :
OtherFamilyDescription                  :
Role                                    :
Stepping                                :
UniqueId                                :
UpgradeMethod                           :
Architecture                            : 12
AssetTag                                :
Characteristics                         :
L3CacheSize                             :
L3CacheSpeed                            :
Level                                   :
Manufacturer                            :
NumberOfCores                           :
NumberOfEnabledCore                     :
NumberOfLogicalProcessors               :
PartNumber                              :
ProcessorId                             :
SecondLevelAddressTranslationExtensions :
SerialNumber                            :
ThreadCount                             :
VirtualizationFirmwareEnabled           :
VMMonitorModeExtensions                 :
PSComputerName                          :
CimClass                                : root/cimv2:Win32_Processor
CimInstanceProperties                   : {Caption, Description, InstallDate, Name…}
CimSystemProperties                     : Microsoft.Management.Infrastructure.CimSystemProperties

**Comment by JanDeDobbeleer** [comment]
@pb5050 is this a 64 bit device? I'll push a fix asap. You could resolve it by editing the module source (under `(Get-Module oh-my-posh).ModuleBase`) and replace 5 with 12 in [this](https://github.com/JanDeDobbeleer/oh-my-posh/blob/6bef088b83c5567e92cc157e22311d2ef7a685fe/packages/powershell/oh-my-posh/oh-my-posh.psm1#L28) file.

**Comment by pb5050** [comment]
i get this a bunch of times 
runtime: signal received on thread not created by Go.
runtime: signal received on thread not created by Go.
runtime: signal received on thread not created by Go.
runtime: signal received on thread not created by Go.
runtime: signal received on thread not created by Go.
runtime: signal received on thread not created by Go.

**Comment by JanDeDobbeleer** [comment]
OK. That's interesting. Is this a 32 bit arm device?

**Comment by pb5050** [comment]
nope arm  64 windows surface prox

**Comment by pb5050** [comment]
![Screenshot 2021-09-17 123055](https://user-images.githubusercontent.com/58855947/133829916-6172cc18-a509-43d2-a390-b72fe9c3a0a4.png)

**Comment by JanDeDobbeleer** [comment]
hmm. Ok. Can you check if you can run the windows arm binary here: https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/v4.2.0

**Comment by pb5050** [comment]
like as in download the .exe and run it? if so no same message


i doub this will help but  ge heres -verbos
![as](https://user-images.githubusercontent.com/58855947/133884710-122bb0fd-8890-403c-938a-720edf615f25.png)
e

**Comment by JanDeDobbeleer** [comment]
@pb5050 but you're not running the executable in your screenshot, right?

**Comment by pb5050** [comment]
yes it starts then the error right after runtime signal

**Comment by pb5050** [comment]
i cant set them

**Comment by pb5050** [comment]
@JanDeDobbeleer   ok this may help you or it may not 


  0 { return "$PSScriptRoot/bin/posh-windows-386.exe" } # x86
        6  { return "$PSScriptRoot/bin/posh-windows-arm64.exe" } # ARM
        12 { return "$PSScriptRoot/bin/posh-windows-amd64.exe" } # x64
    }

i set the 12 to run x64 since i can emulate x64 and it does indeed load and run the theme with the x64 version
did you change anything with that arm version or did windows change some stuff up with the latest insider update? if you cant figure out anything that would cause it i can do a roll back and see if it was the last insider update

**Comment by JanDeDobbeleer** [comment]
I added the ARM version. We can always default to amd64 for that case tbh. Let me do that.

**Comment by pb5050** [comment]
ah okay!  i am going to be off and on today i have tons of stuff i need to get done but if you want me to test anything just let me know and ill try it out for you

**Comment by JanDeDobbeleer** [comment]
@pb5050 any update on the issue being resolved?

**Comment by pb5050** [comment]
yes

**Comment by pb5050** [comment]
i updated to  5.7  didnt change anything in the files and it seems like its working is there a way to check which one im using?
i see what you did i am running 
12 { return "$PSScriptRoot/bin/posh-windows-amd64.exe" } # x64 emulated on Surface Pro X
why  is it doing 12 and not 5?

**Comment by JanDeDobbeleer** [comment]
Good question. 5 doesn't work for some reason. I have no idea why. But at least the amd64 emulation works.
