### ISSUE TITLE
Template for displaying git folder name

### ISSUE THREAD

**Issue by tommck** [JanDeDobbeleer/oh-my-posh#967]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Frequently, I am on very large projects where our branch names have to follow a pattern like `users/username/branch-name`.

When working on my own branches, I'd like to swap this out so that the prompt is shorter.. maybe make it so that it uses `~/` for _my_ branches, but shows the full path for other people's branches.

I'd love to see a way for us to be able to use a template (regex?) or something in order to manipulate the branch name before it is displayed in the git segment.

I'm not familiar with go as a language, so I figured it made sense to request the feature first and see if I can figure out how to do it later, which I don't have high confidence in.

Thanks

**Comment by tommck** [comment]
Looks like changing the `truncateBranch` method (probably with a new name) to handle this type of logic would be appropriate

**Comment by lnu** [comment]
so `branch_max_length` is not exactly what you're looking for.  It means it would be one or the other, exclusively.

**Comment by tommck** [comment]
I understand, I meant to replace that function with something more
comprehensive that would also enforce the maximum length after applying
whatever template logic is supplied

**Comment by JanDeDobbeleer** [comment]
@tommck with templates, this is now completely possible: `{{ .HEAD | replace \"users/username\" \"~\" }}`
