### ISSUE TITLE
[Windows] oh-my-posh.exe exits immediately

### ISSUE THREAD

**Issue by tigerinus** [JanDeDobbeleer/oh-my-posh#968]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

- Downloaded `posh-windows-amd64.exe`
- Renamed it to `oh-my-posh.exe`
- Placed it in `%PATH%`
- Run `oh-my-posh.exe` (in either WindowsTerminal or Command Prompt)

Actual: 

The prompt showed up, but terminated and went back to `cmd`.

Expect:

The prompt shows up and stays that way as a new prompt.

### Version

4.1.0

### Theme

Default

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

other (please specify)

### Relevant log output

```shell
C:\Users\xiaoh\AppData\Local\bin>oh-my-posh.exe -debug

Here are the timings of segments in your prompt:

ConsoleTitle(true) -   0 ms -
session(true)  -   0 ms -  xiaoh@powerberry 
path(true)     -   0 ms -   bin 
git(false)     -  13 ms -
battery(true)  -  11 ms -  100 
node(false)    -   0 ms -
shell(true)    -   0 ms -  ﲵ explorer 
root(false)    -   0 ms -
text(true)     -   0 ms -  NO CONFIG 
exit(true)     -   0 ms -   
```

**Comment by JanDeDobbeleer** [comment]
Please read the [installation](https://ohmyposh.dev/docs/windows#replace-your-existing-prompt) guide. You need to configure your shell.

**Comment by tigerinus** [comment]
> Please read the [installation](https://ohmyposh.dev/docs/windows#replace-your-existing-prompt) guide. You need to configure your shell.

I am trying to understand the logic behind the installation guide, before following it. The part I am confused about is the need of PowerShell.

I see there is a different section specifically for [PowerShell](https://ohmyposh.dev/docs/pwsh), so I am assuming this [Windows ](https://ohmyposh.dev/docs/windows)section is about Command Prompt `cmd.exe` customization. But I could be wrong.

Just to confirm - is this Windows installation guide for Command Prompt customization, or PowerShell?

**Comment by JanDeDobbeleer** [comment]
The Powershell installation guide is for the Powershell module. That's the same functionality, but wrapped and only useable from Powershell.

The Windows installation guide is to be able to use oh-my-posh in ANY shell, including Powershell. Given that you have the binary installed, you can follow the Windows guide and select the Powershell configuration on that page.
