### ISSUE TITLE
Issue in rendering path having space

### ISSUE THREAD

**Issue by jibin2706** [JanDeDobbeleer/oh-my-posh#98]
### Prerequisites

- [ x ] I have read and understand the `CONTRIBUTING` guide
- [ x ] I looked for duplicate issues before submitting this one

### Description

[Description of the bug or feature]

### Environment

- Oh my Posh version: 3
- Theme: zash
- Operating System: windows 10 2003
- Shell: powershell
- Terminal: windows terminal

### Steps to Reproduce
installed oh-my-posh according to the steps mentioned in the readme

**Expected behavior:** The pathname on the terminal should be `C:\Users\Jibin Thomas\dev`

**Actual behavior:** The path is being truncated till the space `C:\Users\Jibin`

Attaching a screenshot of the problem
![Capture](https://user-images.githubusercontent.com/28289448/97112594-4256dc80-170b-11eb-8e28-351c56e9b327.PNG)

**Comment by JanDeDobbeleer** [comment]
That's silly. Let's see if we can fix that.

**Comment by JanDeDobbeleer** [comment]
A new version will be available soon. The path wasn't provided in full to the binary it seems, causing spaces to drop everything that came after. Thanks for noticing this!

**Comment by jibin2706** [comment]
> A new version will be available soon. The path wasn't provided in full to the binary it seems, causing spaces to drop everything that came after. Thanks for noticing this!

Thanks for the quick fix :)
