### ISSUE TITLE
Export-PoshImage issue

### ISSUE THREAD

**Issue by LichLord91** [JanDeDobbeleer/oh-my-posh#980]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

When using Export-Posh image it adds extra characters after the left prompt and pushes out the right prompt past the background screen.

![jandedobbeleer](https://user-images.githubusercontent.com/8435580/134100479-f9b93881-460c-4a0d-bd55-fc867f944199.png)

### Version

5.2.1

### Theme

custome

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

**Comment by JanDeDobbeleer** [comment]
Noticed that too yesterday. Somehow we do not strip all characters anymore. Will check.

**Comment by JanDeDobbeleer** [comment]
@LichLord91 can you share your config? Will help me a great deal.

**Comment by LichLord91** [comment]
@JanDeDobbeleer the theme json or something else? I didn't modify anything after install other than set the theme via $PROFILE and oh-my-posh winget package.

**Comment by JanDeDobbeleer** [comment]
@LichLord91 the theme json indeed

**Comment by LichLord91** [comment]
Ah , its just your JanDeDobbeleer with different colors and adding the schema to the top. I was poking at making a Dracula theme for Oh-My-Posh but starting with your theme as a base. The bug also happens with your theme as well. 

Dracula: https://draculatheme.com/contribute
My Repo: https://github.com/LichLord91/Oh-My-Posh
Theme File :https://github.com/LichLord91/Oh-My-Posh/blob/master/dracula.omp.json

**Comment by JanDeDobbeleer** [comment]
@LichLord91 do you still have this with the latest version? I don't see this anymore now.

![test](https://user-images.githubusercontent.com/2492783/134718294-5cd76ab8-a6c1-44b0-b425-46a70f458bfc.png)

**Comment by LichLord91** [comment]
Tried 5.6.0 PSmodule and 5.5.2 winget package both still exhibit same issue for me.

**Comment by LichLord91** [comment]
Here's the commands im using too

`oh-my-posh --config C:\Users\jensen\AppData\Local\Programs\oh-my-posh\themes\dracula.omp.json --export-png --cursor-padding 0 --rprompt-offset 0 --author draculatheme.com --bg-color 282a36`


`Export-PoshImage -CursorPadding 0 -RPromptOffset 0 -Author draculatheme.com -BGColor 282a36`

**Comment by lnu** [comment]
I have exactly the same error as you with your theme:
![dracula](https://user-images.githubusercontent.com/1829553/134795436-8566c557-bb51-4c44-9086-7d56f92a7669.png)
and also others:
![craver](https://user-images.githubusercontent.com/1829553/134795482-864c2455-1439-4cbc-8a8d-b817cc5edfd7.png)
![jandedobbeleer](https://user-images.githubusercontent.com/1829553/134795485-65d207da-f259-47dd-beac-89a0ae8fda70.png)

But if I launch it from vscode(export png):
![dracula](https://user-images.githubusercontent.com/1829553/134795903-45732ade-cdbb-48ff-9e36-2692cecc67d4.png)

I tried from a noprofile powershell and the result is the same with the ansi characters at the end.

=> adding "--shell shell" works
`oh-my-posh --config dracula.omp.json --cursor-padding 0 --rprompt-offset 0 --author dracula --bg-color 282a36 --export-png --shell shell`
![dracula](https://user-images.githubusercontent.com/1829553/134796433-413b11ad-5b75-48a7-8fc4-417011ef97d2.png)

**Comment by LichLord91** [comment]
@JanDeDobbeleer  

This works with `Export-PoshImage` now.

However with `oh-my-posh.exe --export-png` etc. You need to add --shell shell for those extra characters not to show, not sure if thats intended or there may be some work still needed to be done .

**Comment by JanDeDobbeleer** [comment]
That's intended and [documented](https://ohmyposh.dev/docs/share).
