### ISSUE TITLE
support for busybox bash

### ISSUE THREAD

**Issue by tigerinus** [JanDeDobbeleer/oh-my-posh#989]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

Would it be possible to support busybox implementation of bash?

It's not compatible with regular bash:

```bash
~ $ eval "$(oh-my-posh --init --shell bash --config ~/jandedobbeleer.omp.json)"
bash: =~: unknown operand
```

Couple IoT devices are running busybox, which would be cool if posh is running on it.

**Comment by JanDeDobbeleer** [comment]
Any idea on how to properly emulate this? I see there's a macOS version of busybox, but will that be sufficient?

**Comment by tigerinus** [comment]
> Any idea on how to properly emulate this? I see there's a macOS version of busybox, but will that be sufficient?

That should be efficient.

I use busybox bash on Windows as a minimum alternative to cmd and PowerShell.

**Comment by JanDeDobbeleer** [comment]
@tigerinus this is not going to work. You can set it directly (using `export PS1="$(oh-my-posh --config ~/jandedobbeleer.omp.json --shell bash)"`), but as you can see BusyBox does not support inverted ANSI for example:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/2492783/134666409-d0ceead3-7988-4716-a6c6-f3f415119eae.png">
