### ISSUE TITLE
Add a new `inherit` color option

### ISSUE THREAD

**Issue by TheOnlyTails** [JanDeDobbeleer/oh-my-posh#994]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What would you like to see changed/added?

A new color value called `inherit`, which would automatically use the color of the previous segment.
If the segment in which `inherit` is used has nothing to inherit from (whether by being the first segment, or `inheritColor` is `false` for the block), the default color will be used (as if the field is not specified) and a warning will be issued.

I would also be nice to have an `inheritColor` option on blocks, which would specify if segments in said block are allowed to inherit the color from segments in other blocks.

for example, if we have this block:
```json5
{
	// -- snip --
	"segments": [
		{
			"type": "session",
			"style": "diamond",
			"foreground": "#ffffff",
			"background": "inherit", // warning
			"leading_diamond": "\uE0B6"
		},
		{
			"type": "path",
			"style": "plain",
			"foreground": "inherit", // will have the same foreground color as the session segment
            "background": "inherit", // will have the same background color as the session segment
            "properties": {
                "style": "folder"
            }
		}
	]
}
```

**Comment by TheOnlyTails** [comment]
I'm also thinking of a new type segment called `inherit` that works like so:
- has only the shared `prefix` and `postfix` properties
- can't have text apart from said properties
- automatically inherits the foreground and background colors

It would allow for very easy rounding segments:
```json5
{
	"type": "inherit",
	"properties": {
		"prefix": "\uE0B6"
	}
}
```

We could even have new `round_start` and `round_end` fields on segments which would automatically add those characters to the start and end of segments to make them round, but that's probably fit for another issue.

**Comment by JanDeDobbeleer** [comment]
I don't immediately see the use case for the first suggestion as this change already convers that which in combination with a diamond segment gives you exactly what you propose if I understand correctly.

**Comment by TheOnlyTails** [comment]
Hmm, on second thought, I agree. The 2nd one might be worth considering though, since it's pretty hard to figure out you could use `\uE0B6` and `\uE0B4` to round off diamond segments.

**Comment by JanDeDobbeleer** [comment]
@TheOnlyTails we can always get to that point with communication s(or sample configs with these use-cases).

**Comment by JanDeDobbeleer** [comment]
@All-contributors please add @TheOnlyTails for ideas

**Comment by TheOnlyTails** [comment]
Hmm, seems like `<inherit>text</>` doesn't work...

![image](https://user-images.githubusercontent.com/65342367/134721610-3f7cbbe9-63c0-496a-8292-8242f28b431e.png)

**Comment by JanDeDobbeleer** [comment]
Ah true, that's something I forgot. Will add.

EDIT: this is isn't an easy addition. Requires structural architectural changes. Need to think about this. Could as well turn out to be not supported for this usage.

**Comment by TheOnlyTails** [comment]
Hmm, interesting.

**Comment by JanDeDobbeleer** [comment]
@TheOnlyTails found an "acceptable" solution after the initial refactoring. Should land soon.

**Comment by TheOnlyTails** [comment]
That's great!

**Comment by JanDeDobbeleer** [comment]
@TheOnlyTails should be live

**Comment by TheOnlyTails** [comment]
Wonderful!

**Comment by JanDeDobbeleer** [comment]
@TheOnlyTails with the change in #1180 the `inherit` keyword will be deprecated and replaced by both `parentBackground` and `parentForeground`. Just a heads-up.

**Comment by TheOnlyTails** [comment]
got it, thanks for the heads up.
