### ISSUE TITLE
Problem Upgrading from 3.x to 5.x on Powershell 7

### ISSUE THREAD

**Issue by DWAK-ATTK** [JanDeDobbeleer/oh-my-posh#997]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### What happened?

I tried upgrading oh-my-posh from 3.166.3 to the latest, 5.5.2.  I was met with errors.

**update-module oh-my-posh**

> You are installing the modules from an untrusted repository. If you trust this repository, change its
>  InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install
> the modules from 'PSGallery'?
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
> Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:13069
>  Line |
> 13069 |  …           $sid = PackageManagement\Install-Package @PSBoundParameters
>       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       | Administrator rights are required to install or update. Log on to the computer with
>       | an account that has Administrator rights, and then try again, or install by adding
>       | "-Scope CurrentUser" to your command. You can also try running the Windows
>       | PowerShell session with elevated rights (Run as Administrator).

**update-module oh-my-posh -Scope CurrentUser**
Same error as above.

Running `update-module oh-my-posh` from an elevated (Administrator) powershell prompt produces a FileNotFound exception.

> Untrusted repository
> You are installing the modules from an untrusted repository. If you trust this repository, change its
> InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
> 'PSGallery'?
> [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
> PackageManagement\Install-Package : Could not find file
> 'C:\Users\dwalker\Documents\WindowsPowerShell\Modules\oh-my-posh\5.6.0'.
> At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2089 char:20
> + ...           $sid = PackageManagement\Install-Package @PSBoundParameters
> +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exce
>    ption
>     + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand,Microsoft.
>    PowerShell.PackageManagement.Cmdlets.InstallPackage

### Version

Running 3.166.3
Trying to upgrade to 5.5.2 or 5.6.0

### Theme

Agnoster

### What OS are you seeing the problem on?

Windows

### Which shell are you using?

powershell

### Relevant log output

```shell
See description.
```

**Comment by JanDeDobbeleer** [comment]
That's a PowerShellGet error, not oh-my-posh. I would update PowerShellGet and try again.

EDIT: Are you perhaps using Powershell 5? In that case, please update to Core.

**Comment by DWAK-ATTK** [comment]
Thank you Jan.  I am certain it is Powershell 7.

```
echo $PSVERSIONTABLE

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
get-module
ModuleType Version    PreRelease Name                                ExportedCommands                 
---------- -------    ---------- ----                                ----------------                 
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Cl… 
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Va… 
Script     3.166.3               oh-my-posh                          {Get-PoshInfoForV2Users, Get-Po…
Script     2.1.0                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-…
Script     0.5.2                 Terminal-Icons                      {Add-TerminalIconsColorTheme, A...
```

What is the recommended method of upgrading oh-my-posh on PS 7 from version 3.x to 5.x ?

**Comment by JanDeDobbeleer** [comment]
@DWAK-ATTK that's the right command, it's definitely something on the system as it doesn't download the package for some reason. You could uninstall and install again in case update doesn't work, but I'd find out why the command does not work tbh.

**Comment by JanDeDobbeleer** [comment]
@DWAK-ATTK try upgrading [PowershellGet](https://www.powershellgallery.com/packages/PowerShellGet/2.2.5) first.
